### ISSUE TITLE
traccar on raspberry pi

### ISSUE THREAD

**Issue by tamarko** [traccar/traccar#106]
Hi,

Trying to run traccar on a raspberry pi (32 bit ARM processor). JRE is installed OK (openJDK). 32 bit traccar installation is used.

However upon entering the following command:

```
pi@raspbmc:~$ sudo /opt/traccar/bin/traccar start
```

Response is:

```
Starting traccar...
 /opt/traccar/bin/./wrapper: 1: /opt/traccar/bin/./wrapper: Syntax error: "(" unexpected
Waiting for traccar..................
WARNING: traccar may have failed to start.
```

JRE is installed OK - using openJDK. installed java using: apt-get install openjdk-6-jre libjna-java

```
pi@raspbmc:~$ java -version
java version "1.7.0_07"
OpenJDK Runtime Environment (IcedTea7 2.3.2) (7u7-2.3.2a-1+rpi1)
OpenJDK Zero VM (build 22.0-b10, mixed mode)
```

Any ideas?

Tim

**Comment by domints** [comment]
Hi, sorry for digging, but I have found that Java Service Wrapper (I haven't found any mention about Java Server Wrapper) have armhf binaries now. Does it mean, that it will work on Rpi without any problems?
The wrapper I'm talking about is:
http://wrapper.tanukisoftware.com/doc/english/download.jsp
If you're using different one, sorry for my mistake.

**Comment by tananaev** [comment]
They always had armhf version, but it is not compatible with Raspberry Pi.

See following stackoverflow answer:
http://stackoverflow.com/questions/16214468/java-service-wrapper-on-raspberry-pi/16311531#16311531

**Comment by domints** [comment]
So it's possible to recompile JSW for mine RPi and noone mentioned it before, and it's good news :) And when it wouldn't work even after recompile I would just have to run traccar manually after every boot and it would stay as terminal window, am I right?

**Comment by tananaev** [comment]
You can always run Traccar manually. If you want to recompile JSW please share the result so other people can benefit as well.

**Comment by domints** [comment]
Yup, that's what I wanted to do :) just when I succed. And small info for
RPi2 users: they don't have to worry about this issue - RPi2 has fully
ARMv7 compatible CPU :)
5 mar 2015 09:59 "Anton Tananaev" <notifications@github.com> napisa³(a):
