### ISSUE TITLE
How to instal and use the TRACCAR

### ISSUE THREAD

**Issue by madhu781** [traccar/traccar#120]
Hi All,

I am new for traccar, Please let me know step by step process of Install and use of traccar.
Thanks in advance.

Regards,
Madhu

**Comment by markus120467** [comment]
I am unable to see my android phone after adding to traccar, any idea what I'm doing wrong? I am on a linux box, using all defaults in traccar.xml and I created a user and added my device....still no luck viewing on the MAP.

**Comment by tananaev** [comment]
@markus120467, please next time create a new thread instead of resurrecting some old one. As for your problem, please read following page:

https://www.traccar.org/troubleshooting/

**Comment by vaibhiarora** [comment]
@tananaev I am able to run the code in netbeans but i am not able to open the web interface. can you please guide me for that. I am using it on mac.

**Comment by tananaev** [comment]
@vaibhiarora, please don't comment on old closed threads.

**Comment by pinakin7664** [comment]
Hi All,

I am new for traccar, Please let me know step by step process of Install and use of traccar in Php Mysql.
Thanks in advance.

Regards,
Pinakin Patel

**Comment by Turbovix** [comment]
Friend, have you checked the documentation on the Traccar site?, follow the link!
https://www.traccar.org/documentation/
