### ISSUE TITLE
TK103

### ISSUE THREAD

**Issue by Wonderboy-BR** [traccar/traccar#1224]
Hello, I installed the server on windows, I opened the page on localhost, signed up the IMEI of the tracker, in open port 5006 on the modem, I sent the message pointing to the ip from my computer to the device, but nothing appeared on the screen. Wrong on something?

**Comment by tananaev** [comment]
First of all, please check if the port is visible from internet. You can do it here: http://www.tananaev.com/port.html.

**Comment by Wonderboy-BR** [comment]
Success: I can see your service on 201.7x.xxx.xx5 on port (5006)
Your ISP is not blocking port 5006

**Comment by tananaev** [comment]
Please check Traccar logs (tracker-server.log) to see if there any hex messages there.
