### ISSUE TITLE
Ничего не приходит на сервер

### ISSUE THREAD

**Issue by styxerq** [traccar/traccar#1225]
Доброго дня. Запустил сервер, однако на него ничего не приходит, в логе пусто. Комп на котором запущен сервер Win7 64 и подключен через роутер. делал проброс портов 8082 и 5023, без толку. Ни с трекера китайского ни со смарта данные не идут. В чем проблема? Айпи сервера выставлял тот который у вас на сайте выдавался.

**Comment by tananaev** [comment]
У вас внешний IP адрес есть от провайдера? Обычно это дополнительная плантая услуга.

Проверить открыт ли порт можно тут: http://www.tananaev.com/port.html

**Comment by styxerq** [comment]
Проблему решил. Спасибо брандмауэру виндовс. Отключил и все полетело. Однеако не хвататет плюшек в виде геозон различных, ограничений скорости и русского интерфейса. Ну и конечно прилаги для смартфона, чтоб отслеживать

**Comment by vitalidze** [comment]
В [моей модификации](http://traccar.litvak.su) есть возможность добавлять [геозоны](http://traccar.litvak.su/features/geofences.html), [русский интерфейс](http://traccar.litvak.su/features/russian.html), а также есть упрощенная версия мобильного интерфейса ([демо](https://d.traccar.litvak.su/m/)).

**Comment by tehnoinstyle** [comment]
@vitalidze 
Привет.
Установил  и запустил сервер Traccar на Synology и клиент на Андроид.
Есть ли информация на русском языке по настройке сервера: глобальные настройки, устройств, геозон, фильтров и т.д., т.е. по работе с программой?
А также по настройке клиентов: время обновления, источники обновления (сеть или gps).

**Comment by vitalidze** [comment]
@tehnoinstyle На русском языке документации к самой программе нет. Можно использовать переводчик встроенный в браузер (в chrome например). По настройке клиентов нужно обращаться к производителям устройств.

**Comment by tehnoinstyle** [comment]
А как пользовать геозоны? Что можно поиметь?
Хочу попробовать связать Traccar с OpenRemote.

**Comment by vitalidze** [comment]
[Здесь](http://traccar.litvak.su/features/geofences.html) описано как использовать. Можно настроить уведомления по почте или через [pushbullet](https://www.pushbullet.com/). А дальше интегрировать с OpenRemote.

**Comment by tehnoinstyle** [comment]
Да, нужно читать, переводить и разбираться.
Может, по мере продвижения, инструкцию набросаю. 
Спасибо.

**Comment by tehnoinstyle** [comment]
Настройки схожи немного. 
http://majordomo.smartliving.ru/Main/ScLocGeneral
Когда-то пробовал этот проект, но не силен в таком программировании.

**Comment by tehnoinstyle** [comment]
Виталий, привет.
Разбираюсь с программой. Настроил геозоны. Настроил отправку уведомлений через мейл (я создал для программы отд. учетку и п/я), работает.

Подскажи, как настроить Pushbullet? С какой учетной записи регистрироваться (с той же, что и для отправки мейл сообщений с Трассар)? Или с той, на которую отправляются сообщения?
И что вводить в строку в настройках Pushbullet?

**Comment by tehnoinstyle** [comment]
Да, и можно ли указать два эл/адреса, на которые отсылать уведомления?

**Comment by vitalidze** [comment]
Во-первых, не нужно засорять этот топик и этот баг трекер. У моего проекта есть отдельный баг-трекер https://github.com/vitalidze/traccar-web/issues Дальнейшее обсуждение нужно перенести туда.

По вопросам:

> Подскажи, как настроить Pushbullet? С какой учетной записи регистрироваться (с той же, что и для отправки мейл сообщений с Трассар)? Или с той, на которую отправляются сообщения?

Нужно регистрироваться с той, с которой планируется отсылка сообщений. Насколько я знаю исходящий адрес почты в сообщениях не будет фигурировать.
 
> И что вводить в строку в настройках Pushbullet?

В профиле pushbullet есть поле с ключом API. Нужно оттуда взять строку.

> Да, и можно ли указать два эл/адреса, на которые отсылать уведомления?

Для этого нужно завести еще одну учетную запись в системе со второй электронной почтой, дать доступ к нужным устройствам и настроить типы получаемых уведомлений в профиле.

**Comment by tehnoinstyle** [comment]
Спасибо.
Создал тему 
https://github.com/vitalidze/traccar-web/issues/228

**Comment by MkoDmitry** [comment]
Здравствуйте. У меня проблема, аналогичная проблеме @styxerq а именно что Traccar не прослушивает порты протоколов. В моем случае это протокол Автофон-а и порт 5077.
Ситуация такая: на выделенном физическом сервере с Debian на борту был установлен и запущен Traccar. Были открыты порты: 
iptables -I INPUT -p tcp --dport 5077 -j ACCEPT
iptables -I INPUT -p udp --dport 5077 -j ACCEPT
iptables -I OUTPUT -p tcp --dport 5077 -j ACCEPT
iptables -I OUTPUT -p udp --dport 5077 -j ACCEPT

Содержимое wrapper.log.20180514:

**Comment by tananaev** [comment]
Логи сервера смотрели?

**Comment by MkoDmitry** [comment]
Только что проверил. В access-logе запись с forward.url присутствует в единственном экземпляре, но цепочка вызовов указывает на то, что это был интеграционный тест, а не forwarding со стороны Traccar.

**Comment by MkoDmitry** [comment]
Со стороны Traccar - только wrapper.log.20180516.  Содержимое этого файла такое:

STATUS | wrapper  | 2018/05/16 07:12:04 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2018/05/16 07:12:04 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2018/05/16 07:12:04 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2018/05/16 07:12:04 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2018/05/16 07:12:04 |
STATUS | wrapper  | 2018/05/16 07:12:04 | Launching a JVM...
INFO   | jvm 1    | 2018/05/16 07:12:04 | WrapperManager: Initializing...
INFO   | jvm 1    | 2018/05/16 07:12:05 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2018/05/16 07:12:05 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2018/05/16 07:12:06 | INFO 5/16/18 7:12 AM: liquibase: Clearing database change log checksums
INFO   | jvm 1    | 2018/05/16 07:12:06 | INFO 5/16/18 7:12 AM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2018/05/16 07:12:06 | INFO 5/16/18 7:12 AM: liquibase: Successfully released change log lock
INFO   | jvm 1    | 2018/05/16 07:12:06 | INFO 5/16/18 7:12 AM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2018/05/16 07:12:08 | INFO 5/16/18 7:12 AM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO   | jvm 1    | 2018/05/16 07:12:08 | INFO 5/16/18 7:12 AM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO   | jvm 1    | 2018/05/16 07:12:08 | INFO 5/16/18 7:12 AM: liquibase: Successfully released change log lock
