### ISSUE TITLE
Can't delete records from H2 database

### ISSUE THREAD

**Issue by wolfbgn** [traccar/traccar#1227]
Hi, Anton.
I have read carefully comments about deleting old records from database but it seems to me they all are related to MySQL. Sorry if I got it wrong.
I can not delete old records. I am using default Traccar H2 database.I have tried with two suggestions that I have found in Issues with no avail.
`DELETE FROM positions;` - does nothing. I assume it is not command for H2.
`DELETE FROM positions WHERE time < TIMESTAMPADD('DAY', -7, NOW());` - prevents Traccar from starting.
I have put those lines like this:
```xml
    <entry key='database.insertPosition'>
        INSERT INTO positions (device_id, time, valid, latitude, longitude, alt$
        VALUES (:device_id, :time, :valid, :latitude, :longitude, :altitude, :s$
        DELETE FROM positions;
```
and made cronjob
```
crontab -e 
@midnight /opt/traccar/bin/traccar restart
```
Nothing happens. Old tracks are there. I restarted Traccar manually several times too.
Please help me.

**Comment by tananaev** [comment]
Are trying to remove all records from `positions` on every location update from device?

Anyway, I think the problem is that `devices` has links to `positions`, so you need to remove those links first before deleting data from `positions`.

**Comment by wolfbgn** [comment]
I want to remove all records N - days old. 
And to be honest I don't know what you said to me. I need to remove today - yesterday's recorded tracks of users. I'm sorry but I only can follow simple instructions, I don't understand programming,

**Comment by tananaev** [comment]
If you want to clean up old records, I would recommend to use MySQL database and have a cron job to remove old records using simple SQL script.
