### ISSUE TITLE
Change Database or host and need change name tables

### ISSUE THREAD

**Issue by gilgzz18** [traccar/traccar#1228]
Hi all,

I try migrate the DB in other server, the issue is in the other server i can not name tables, all tables i can make contains suffix for example: 

Table name: suffix_users_devices

I think that will be an issue that I find some settings in traccar.cfg to let me change the names of the tables

Regards!
Gilberto Gzz
Mexico

**Comment by tananaev** [comment]
Do you want to use Traccar web interface or just a device communication back-end?

**Comment by gilgzz18** [comment]
Hi tananaev,

My plan is in one server execute traccar and server second storage DB for data warehouse and queries

So my problem in second server is table name's cotains default prefix


Regards,
Gilberto Gzz
Mexico

**Comment by tananaev** [comment]
You didn't answer the question. Are you planning to use Traccar web interface? If yes, then you need to modify source code of the web interface to change table names.

**Comment by gilgzz18** [comment]
Hi tanannaev

I will not use the Traccar web interface, is possible not use table users_device or change name this table?

Thanks for your fast response tananaev

Regards,
Gilberto Gzz
Mexico

**Comment by tananaev** [comment]
If you are not going to use web interface you just need two tables: devices and positions. You can rename them and change SQL queries in the config file.

**Comment by gilgzz18** [comment]
In tests I've done to register a new GPS, I've seen that but I add the record in the table user_devices no record is added to the table positions

Any specification in the config to ignore the table user_devices necessary, understand that if so just rename the file config

Regards,
Gilberto Gzz
Mexico

**Comment by tananaev** [comment]
If you are not using web interface, you don't need `users_devices` table.

**Comment by gilgzz18** [comment]
Thanks tananaev i try.....

Regards,

Gilberto Gzz
Mexico
