### ISSUE TITLE
device IP

### ISSUE THREAD

**Issue by nuspl** [traccar/traccar#123]
Hello!

I use your solution with external database. A made own graphical interface for logged data. But i need the device IP number for seperate the daily route to part. Every time when connect the device has new IP, so this infromation i can use for split the dataline.

Do you think could it be possible to log IP address into external database?
Or can you tell the variable name that i have to add the insert script at config file? For example :deviceIP or something like this.

Thanks a lot! This is a very good project.

Akos.

**Comment by evigra** [comment]
Excuse me, I think, it's a good idea to add the IP.
When you add the last position of the device.

**Comment by guilhermesouza** [comment]
+1 Add ip address and the port also

Em ter, 23 de jun de 2015 às 13:45, evigra <notifications@github.com>
escreveu:

**Comment by tananaev** [comment]
Added IP address parameter to the XML field. Commit - 65a234c9b64461f9b946cdb256d46c53bd92b2d7.
