### ISSUE TITLE
BCE Device is always sending old positions[Fixed] 

### ISSUE THREAD

**Issue by ahmedaswai** [traccar/traccar#1235]
I have issue related to the BCE , the BCE  device always  sends old positions even after the service sent the response .

**Comment by tananaev** [comment]
Have you tried to contact manufacturer and ask why it could be happening? Possibly there is some problem with server response format.

**Comment by ahmedaswai** [comment]
After contacting  the manufacturer, he informed me that the confirmation key should be calculated y the next expression 

private static final int CONFIRM_ACK_KEY=0x7F;

int confirmKey = buf.readUnsignedByte()&CONFIRM_ACK_KEY;

I applied this fix and now no old data is sent from the device

**Comment by tananaev** [comment]
Can you please send a pull request with your fix.

**Comment by tananaev** [comment]
Is the https://github.com/tananaev/traccar/commit/16ebb921e416e94cb9e01340d38c7071882dd65f fix correct?

**Comment by ahmedaswai** [comment]
Yeah It is correct
