### ISSUE TITLE
Traccar Performance for 100-200 units reporting at 5sec

### ISSUE THREAD

**Issue by joepr** [traccar/traccar#1236]
Hello Guys

We have a upcoming project that we will like to use traccar. Here is the scenario. We have around 100 - 200 portable gps units that will be reporting their location every 5 seconds. This reporting could last from 1 to 5 hours then It will be offline. During this project from 400 - 500 users could be viewing the gps units position. We don't need the users (viewers) to play with the reporting, basically we want them to view the gps position.  I have configure traccar to use Mysql however I know I must fine tune mysql for a better performance. So far around 10 gps units are reporting fine to the server.

At this moment we are using a local server but we can switch to a Amazon Ec2 server.

So my question is:
What would you recommend for this scenario? (Hardware Specs, Mysql Setup, Ram, etc)
Could traccar manage this type of load?

Thanks!

**Comment by tananaev** [comment]
What is the time frame for your project? I am working on a new web interface which will have an in-memory cache of latest GPS locations. It will also support live updates using long polling instead of periodical (every 15 seconds in current version) requests like in the current version.

In general 200 devices with 5 seconds period is not a problem for the device communication back-end, but 500 web users might be a problem as current web interface and database queries are not optimal.

**Comment by ahmedaswai** [comment]
I would like to suggest to use  web sockets instead of long pooling for the positions notifications

**Comment by tananaev** [comment]
I think it's still to early for web sockets. Some IE versions and older Android devices don't support it. Probably in future I will change implementation to work over web sockets.

**Comment by joepr** [comment]
Greetings tananaev

Sorry for the delay on responding the question I was out of town. The project is scheduled for 1 month. For the backend service do you recommend any changes on the default mysql config to provide a better performance? I will be monitoring the site for the new web interface. Thanks!

**Comment by tananaev** [comment]
New web interface should be ready within a few weeks, so maybe it's better to wait.

**Comment by kirantpatil** [comment]
@joepr, any updates ? Please share your H/W configuration along with the performance observations and issues faced so far.

**Comment by tananaev** [comment]
Traccar has been using WebSockets for a very long time now.
