### ISSUE TITLE
Speed in Km Or Kn

### ISSUE THREAD

**Issue by farbeed** [traccar/traccar#1237]
Hi,

I use Traccar On mysql, Im trying diffrent devices(Gosafe,tk104,coban,teletonika,Reputela)I want to know when the data stored in the database , the speed stored in Kilometers or knots?

Thanks

**Comment by vitalidze** [comment]
AFAIK speed in database is stored in knots for all devices nevertheless of their protocol.

**Comment by farbeed** [comment]
Hi,

I Think it depends on the prtoocol, I noted that in Gosafe speed in KM while in TK104 Knotes

**Comment by vitalidze** [comment]
I can't say for all all protocols, but I know for sure that web UI expects that speed is stored in knots. Then you can set up display unit (km/h, mph) and it will dot a conversion for you.

**Comment by farbeed** [comment]
Hi,

Actually I uses my web application, so It is not clear to me how traccar deal with the speed

Sent from my HTC

----- Reply message -----

**Comment by tananaev** [comment]
Traccar converts speed values received from devices to knots and stores it in knots units in the database.

**Comment by maxicabanillas78** [comment]
https://play.google.com/store/apps/details?id=com.gpsroute66.android.gpstrackingapp&hl=pt-BR

**Comment by tananaev** [comment]
@maxicabanillas78, what is it? How is it related to the topic?

**Comment by halshehri** [comment]
Any chance of changing the shown value in the UI.  it seems my device "TK103" is sending knot and I want to show km.  FYI, I've downloaded latest version last week and install it on my server.

thanks in advance.

**Comment by bruzetti** [comment]
Hi Tananaev,

I'm reading the source code and in the OsmAndProtocol.java there is no conversion, that means that the app already send speed in knots units, right? 
Thanks.

**Comment by tananaev** [comment]
Traccar Client sends speed in knots.

**Comment by ombasaMukhwami** [comment]
The intellitrac Protocol speed has not been converted.
{"Position":{"Id":1010004265,"DeviceId":21,"Valid":true,"FixTime":"2018-09-27T10:19:10Z","DeviceTime":"2018-09-27T10:19:10Z","Protocol":"intellitrac","Latitude":-1.317458,"Longitude":36.773142,"Altitude":1766.0,"Speed":70.0,"Course":260.0,"StatusCode":"0xF11C"},"Attributes":{"fuel":0,"output":0,"sat":9,"rpm":"0","hdop":0.0,"io199":0,"adc1":175203.3,"odometer":0.0,"input":1,"adc2":0.0,"raw":"313031303030343236352C32303138303932373130313931302C33362E3737333134322C2D312E3331373435382C37302C3236302C313736362C392C322C312C302C3137353230332E33","ignition":false,"charge":false,"blocked":false,"battery":0.0,"distance":952.21,"totalDistance":317006.88,"motion":true,"temp1":0.0,"obdSpeed":0,"coolant":0,"fuelConsumption":0.0,"chargerPressure":0,"tpl":0,"axle":0,"obdOdometer":0}}
Raw data--1010004265,20180927101910,36.773142,-1.317458,70,260,1766,9,2,1,0,175203.3

**Comment by tananaev** [comment]
@ombasaMukhwami, please provide protocol documentation.
