### ISSUE TITLE
OCT800

### ISSUE THREAD

**Issue by farbeed** [traccar/traccar#1238]
HI,

Im asking about OCT800, did any one try it?shall it work on port 5009?

Thanks

**Comment by tananaev** [comment]
To identify protocol read following page:
https://www.traccar.org/identify-protocol/

**Comment by farbeed** [comment]
Hi Anton,

I'm trying, but the last step is not clear to me( find matching protocol), can you give me some details.

**Comment by tananaev** [comment]
Do you have HEX message samples?
