### ISSUE TITLE
MySql issue

### ISSUE THREAD

**Issue by al3x1s** [traccar/traccar#1241]
is the new engine not compatible with MySql??

I got this error in wrapper output

<pre>STATUS | wrapper  | 2015/06/09 17:39:18 | --&gt; Wrapper Started as Daemon
STATUS | wrapper  | 2015/06/09 17:39:18 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/06/09 17:39:18 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/06/09 17:39:18 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/06/09 17:39:18 |
STATUS | wrapper  | 2015/06/09 17:39:18 | Launching a JVM...
INFO   | jvm 1    | 2015/06/09 17:39:18 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp:
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mysql.jdbc.Util.getInstance(Util.java:372)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1449)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at org.traccar.database.QueryBuilder.executeUpdate(QueryBuilder.java:384)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.createDatabaseSchema(DataManager.java:159)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.initDatabase(DataManager.java:117)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.&lt;init&gt;(DataManager.java:60)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at org.traccar.Context.init(Context.java:92)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at org.traccar.Main.main(Main.java:26)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2015/06/09 17:39:21 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:745)
STATUS | wrapper  | 2015/06/09 17:39:23 | &lt;-- Wrapper Stopped</pre>

**Comment by tananaev** [comment]
It is not yet, but it will be very soon. See #1240.

**Comment by al3x1s** [comment]
thanks Anton

**Comment by tananaev** [comment]
I just merged that pull request, so MySQL should work. You can try and report if there are any issues.

Note that new web interface is not finished yet, so there are might be some major problems/bugs.

**Comment by al3x1s** [comment]
it works like a charm, thanks!

**Comment by daremen** [comment]
Hi Anton:
I.ve integrated Traccar 2.10 with OpenGTS and worked well, but I´ve upgraded Traccar to 2.12 and now I have issues with MySQL.

2015-06-23 00:31:50  INFO: Starting server...
2015-06-23 00:31:50  INFO: Operating System name: Linux version: 2.6.32-504.8.1.el6.x86_64 architecture: amd64
2015-06-23 00:31:50  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.79-b02
2015-06-23 00:31:50  INFO: Memory Limit heap: 643mb non-heap: 214mb
2015-06-23 00:31:50  INFO: Version: 2.12-SNAPSHOT
2015-06-23 00:32:44 DEBUG: [9F109321: 21505 <- 200.95.170.86] - HEX: 2b524553503a475449474e2c3130303130342c3836323139333032313136383438392c2c31343836362c302c302e302c35342c313133302e312c2d3130332e3437353337382c32352e3538313132312c32303135303632333035333133302c303333342c303032302c304642352c353844412c30302c2c323732372e362c32303135303632323233333234332c3145453924
2015-06-23 00:32:44  INFO: Query not provided: database.selectDevicesAll
2015-06-23 00:32:44  WARN: Unknown device - 862193021168489
2015-06-23 00:32:47  INFO: Closing connection by disconnect
2015-06-23 00:32:51 DEBUG: [D2998CB7: 21505 <- 200.95.170.86] - HEX: 2b524553503a475449474c2c3130303130342c3836323139333032313136383438392c2c2c30312c312c312c302e362c35342c313132382e312c2d3130332e3437353337392c32352e3538313133302c32303135303632333035333235302c303333342c303032302c304642352c353844412c30302c323732372e362c32303135303632323233333235302c3145454124
2015-06-23 00:32:51  INFO: Query not provided: database.selectDevicesAll
2015-06-23 00:32:51  WARN: Unknown device - 862193021168489
2015-06-23 00:32:54  INFO: Closing connection by disconnect


Please Help Anton.

**Comment by tananaev** [comment]
Looks like you are using debug version of Traccar from Dropbox. You need to use official release from https://www.traccar.org/download/.

**Comment by daremen** [comment]
I am using the downloaded version from GitHub with the opengts.xml

**Comment by tananaev** [comment]
Do you mean you compile the version from GitHub? There were a lot of changes since last release, so you need to modify the config file. See <a href="https://github.com/tananaev/traccar/blob/master/debug.xml">debug config</a> for example.

**Comment by daremen** [comment]
Yes I´ve compiled the GitHub version but I will download and compile it again and try the debug config file to see the results.
