### ISSUE TITLE
export database

### ISSUE THREAD

**Issue by fabover** [traccar/traccar#1249]
Hello, I would like to know how to export the database where users and devices are. I want to install a new server without losing all users. The old instalation is in Windows, the new is in windows too.

**Comment by tananaev** [comment]
If you are using default H2 database, you can just copy the content of `data` folder from one machine to another.

**Comment by fabover** [comment]
yes, try that, but the newly added devices do not work, it was possible to add them, but to put the id of those devices nothing happened, while aggregate equipment before if they worked. I thought I had done something wrong or that one ought to copy one of the files.Thanks

**Comment by tananaev** [comment]
Did you stop Traccar instance before copying data?
