### ISSUE TITLE
Having Address and time issue in Gps Device GT06N

### ISSUE THREAD

**Issue by conqsys** [traccar/traccar#1254]
I have a gps device GT06N I set the interval  to 5 min but still getting the record every 10s and also for every record the address is blank can help me to solve this problem

**Comment by tananaev** [comment]
Period issue is definitely a device config/firmware problem.

As for address, you need to enable reverse geocoding in the config. More info here:
https://www.traccar.org/configuration-file/

**Comment by conqsys** [comment]
Thank you so much for reply this information is helpful to me .

**Comment by conqsys** [comment]
Is there any way so that i can get record after 5 mins interval means if i get a location at 5.00 then another location i get 5:05 or more

**Comment by conqsys** [comment]
Or can you please help me regarding this problem that how can i set the time interval in device GT06N i tried the way given in manual but that's not working in my all devices i have around 10 device but time interval not working in any device .If you help me to resolve this problem this can be better to me

**Comment by tananaev** [comment]
So you basically want to ignore some reports on the server side? One option is use filtering:

<pre>    &lt;entry key='filter.enable'&gt;true&lt;/entry&gt;
    &lt;entry key='filter.limit'&gt;600&lt;/entry&gt;
    &lt;entry key='filter.distance'&gt;1000&lt;/entry&gt;</pre>

**Comment by conqsys** [comment]
i tried with it i set this configuration in my file by this configuration the difference is 6 min but still i get location every 10 second

**Comment by conqsys** [comment]
Speed save in database is in Knot unit or km unit

**Comment by tananaev** [comment]
Can I see the log?

As for speed, it's saved in knots.

**Comment by conqsys** [comment]
Thanks for reply


![log](https://cloud.githubusercontent.com/assets/5823673/8280974/c61c847a-1900-11e5-9cee-2eca13987500.png)
this is the image file of log file and here below is the google drive link
https://drive.google.com/file/d/0B0knqXidjEzPakc2bzExVUZMQW8/view?usp=sharing

so please tell me a solution to my problem

**Comment by conqsys** [comment]
Also help me with course check in log i think i got wrong course attribute and also plz can you tell me what the othe field in other column means eg : mnc etc

**Comment by conqsys** [comment]
i check many time its seems filtration is not working please help me to resolve this problem

**Comment by tananaev** [comment]
The config I provided above filters messages if time difference is less than 5 minutes and distance is less than 1 km. It works correctly as far as I can see. You can increase distance part if you want only time filtering.

Also I noticed that you are using old version of Traccar. I recommend to upgrade to the latest one.

Why do you think the course is wrong? Provide example.

MNC is a <a href="https://en.wikipedia.org/w/index.php?title=Mobile_Network_Code&redirect=no">Mobile Network Code</a>.

**Comment by conqsys** [comment]
![image1](https://cloud.githubusercontent.com/assets/5823673/8299695/bcfd7400-1999-11e5-8059-1b493b163742.png)

<entry key='filter.enable'>true</entry>
    <entry key='filter.limit'>300</entry>
    <entry key='filter.invalid'>true</entry>
    <entry key='filter.zero'>true</entry>
    <entry key='filter.duplicate'>true</entry>
<entry key='filter.distance'>100000</entry>


Above i send you an image and my config setting of filtration you can see in image the time i getting the record according to config its 300 second but still i get many records per minute

**Comment by tananaev** [comment]
Have you restarted the service after changing the config? Note that filtering would apply only for newly added records. If the problem persists, I need the latest log file to investigate the problem.

**Comment by conqsys** [comment]
Thanks for reply,
yes i restarted the service after change in config .and here is the google drive link of my log file 

https://drive.google.com/file/d/0B0knqXidjEzPSXp0akZ4RFdobFk/view?usp=sharing

Please Check and tell me the what i need to do to short out this problem quickly

Thanks in advance

**Comment by conqsys** [comment]
Forgot that here is my config file link so you look at both and tell me whats the problem so i can resolve this issue

https://drive.google.com/file/d/0B0knqXidjEzPUWZvVkVKRlZldE0/view

**Comment by tananaev** [comment]
Please upgrade to the latest version of Traccar. There might have been some bugs in filtering in the old version.
