### ISSUE TITLE
Traccar don't launch on browser

### ISSUE THREAD

**Issue by jbenitezlavado** [traccar/traccar#1255]
I have a problem with wrapper I think, this is my wrapper log.
```
STATUS | wrapperm | 2015/06/17 01:20:01 | Traccar service installed.
STATUS | wrapper  | 2015/06/17 01:22:54 | --> Wrapper Started as Service
STATUS | wrapper  | 2015/06/17 01:22:54 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/06/17 01:22:54 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/06/17 01:22:54 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/06/17 01:22:54 | 
STATUS | wrapper  | 2015/06/17 01:22:55 | Launching a JVM...
INFO   | jvm 1    | 2015/06/17 01:23:13 | WrapperManager: Initializing...
```

**Comment by tananaev** [comment]
Is this all you have in the `wrapper.log` file?

**Comment by jbenitezlavado** [comment]
Yes is this all I probe on windows and linux and i just have the same wrapper.log

**Comment by tananaev** [comment]
Are you using official Traccar release? What are the hardware specs of your machine? Are you sure you have Java installed?

**Comment by jbenitezlavado** [comment]
Yes I download source code from traccar.org I compiled traccar-web-master with eclipse and traccar-master with netbeans and I put the files on setup in order to compile setups, i run package.sh on linux and that created all instalers for diferent environmets the unique thing that i do manually is to zip the content of war folder because i couldn't create traccar-web.war and I did that with your advice but i don't no why no run. I hava Java installed in windows and linux.

**Comment by tananaev** [comment]
OK, so the answer to my question is actually no. Official release can be downloaded here: https://www.traccar.org/download/.

Did you change anything in the source code?

**Comment by jbenitezlavado** [comment]
Yes i put an Image on login and change traccar.html for index.html but also change that name on web.xml when I run on eclipse everything work's ok and i try to put that on my server.

**Comment by jbenitezlavado** [comment]
Maybe that image can help.
![ggss](https://cloud.githubusercontent.com/assets/12468663/8219815/47cd244a-1512-11e5-9185-c9805b5ba1d0.PNG)

**Comment by tananaev** [comment]
Are you sure you have compiled GWT project correctly? I suspect the problem is with web interface part.

**Comment by jbenitezlavado** [comment]
When i compile with GWT thats the result.
![compile](https://cloud.githubusercontent.com/assets/12468663/8220034/6849ead0-1514-11e5-8478-fcd741b70c7e.png)

**Comment by tananaev** [comment]
I think you can try to compare the content of your `war` file with the release version of Traccar and see what are the differences.

**Comment by jbenitezlavado** [comment]
Oh I see th war file from release have another folder META-INF but my compilation don't have just have the other folders like WEB-INF, traccar and html file but why don't create that, how I should compile traccar-web-master correctly.

**Comment by tananaev** [comment]
Don't worry about `META-INF`, but do you have everything else like `traccar` folder and `WEB-INF/classes` folder?

**Comment by jbenitezlavado** [comment]
Yes I have the other folder's.

**Comment by tananaev** [comment]
Maybe you should try to copy `META-INF` and see if it fixes the problem, but I don't think it would.

**Comment by jbenitezlavado** [comment]
Don't work the problem persist. But ubuntu show me a problem like java was stopped is like wrapper overload JRE I think it is because the program try an try to load but it can't.

**Comment by tananaev** [comment]
How do you run it?

What is the output of the following command:
<pre>java -version</pre>

**Comment by jbenitezlavado** [comment]
Java version 1.6.0_35
OpenJDK 64-bit server Server VM

**Comment by tananaev** [comment]
How do you run the service? Have you tried to run Traccar manually from the command line:

<pre>java -jar /opt/traccar/tracker-server.jar /opt/traccar/conf/traccar.cfg</pre>

**Comment by jbenitezlavado** [comment]
When i try to run manually give an error "Failed to bind to 0.0.0.0/0.0.0.0:5001" because the service is on when i chek service with "service traccar status" the result is :   traccar is runing PID:2638 , Wrapper:Started , Java:Started

**Comment by tananaev** [comment]
Looks like Traccar is already running.

**Comment by jbenitezlavado** [comment]
Hello, I take traccar again. I solve the problem with wrapper with new version of traccar, but now my problem is that when I run package.sh on traccar-server setup it create installers but not with my traccar-web.war instead of when i install on linux for example that charge your release version without my modifications i don't know why.

**Comment by tananaev** [comment]
Latest version of Traccar doesn't use `traccar-web.war` anymore.

**Comment by jbenitezlavado** [comment]
And now how i can compile traccar?

**Comment by tananaev** [comment]
New web interface is written in JavaScript, so you don't need to compile it.

**Comment by jbenitezlavado** [comment]
Oh i can see just need to download release version and modify files on web directory, Congratulations i think that its easier to modify (y).
