### ISSUE TITLE
archived filter

### ISSUE THREAD

**Issue by alonbz** [traccar/traccar#1256]
I can't see the filter option in the archive zone. I change the config  file:

<pre>    &lt;!-- Filtering options --&gt;
    &lt;entry key='filter.enable'&gt;true&lt;/entry&gt;
    &lt;entry key='filter.limit'&gt;3600&lt;/entry&gt;
    &lt;entry key='filter.invalid'&gt;true&lt;/entry&gt;
    &lt;entry key='filter.zero'&gt;true&lt;/entry&gt;
    &lt;entry key='filter.duplicate'&gt;true&lt;/entry&gt;
    &lt;entry key='filter.distance'&gt;50&lt;/entry&gt;</pre>

But still cannot see the filter option.
What am I do wrong?

Thanks

**Comment by tananaev** [comment]
This is server side only filtering. There is no corresponding web UI for it.

**Comment by alonbz** [comment]
So how can I export data from the UI? I thought that the filter open you an
option to export the data.
Thanks

**Comment by tananaev** [comment]
Filters have nothing to do with exporting data. Traccar currently doesn't support export.

**Comment by alonbz** [comment]
Many Thanks
