### ISSUE TITLE
tracker 108

### ISSUE THREAD

**Issue by sakisketc** [traccar/traccar#1257]
hellon could anyone tell me how to set up gps tracker 108? cause in the manual it's a bit difficult and not specified! I tried many times but im gettin crazy.... 
thank you in advance

**Comment by tananaev** [comment]
Does your device send data to the server?

**Comment by sakisketc** [comment]
No .i can't even set the apn....i follow the instructions and nothing happens

**Comment by tananaev** [comment]
Then I guess you need to contact seller or manufacturer for support.

**Comment by sakisketc** [comment]
I already send a message.nevertheless,the advice's led indicator is blue ..but doesnt send sms

**Comment by sakisketc** [comment]
Xmm i managed to make a call l to the device and send meback its position!!!!but i still can't set up the apn...do you have any idea??

**Comment by tananaev** [comment]
If device answers the call, it means it can connect to the network. So, I guess that command you use to set APN is in wrong format.

**Comment by sakisketc** [comment]
Yes but what am i doing wrong??i follow the instructions which says to send"123456apn cosmote internet" ...but nothing happens

**Comment by tananaev** [comment]
Do you have a manual for the device? Can you attach a photo of the page with APN command?

**Comment by sakisketc** [comment]
Yes i have but hiw to attach the photo?

**Comment by sakisketc** [comment]
![screenshot_2015-06-19-04-59-47](https://cloud.githubusercontent.com/assets/12951861/8246064/acf76ea0-1640-11e5-90b0-c42672877a99.png)
Ok i am from cellphone and i havent seen it

**Comment by tananaev** [comment]
OK, so why do you send `123456apn cosmote internet`? What is the APN for your phone company? Do you need username and password?

**Comment by sakisketc** [comment]
Cause the name=cosmote internet and the APN=internet
Username and password are not in use...

**Comment by tananaev** [comment]
What is name then?

As far as I understand you just need to send:
<pre>123456apn internet</pre>

**Comment by sakisketc** [comment]
Ι also tried this many times...but nothing+

**Comment by tananaev** [comment]
Does your device respond at all to the command?

Are you sure you don't need username and password?

Are you sure data works on your SIM card? Try to plug it in your cell phone and set same APN there.

**Comment by sakisketc** [comment]
Ι didn't tried other commands because i have to set the apn first.
Why do i have to use username and password  as there aren't exist in my phone and i have never change them
I used the card in cellphone and send an sms to another cellphome an was ok! What do you mean to set the same apn in the cellphone?

**Comment by tananaev** [comment]
Well, you need to try data on your phone, not only SMS. Cell phone has APN configuration as well. Usually it's configured for you automatically though.

**Comment by sakisketc** [comment]
could you explain to me how to use data?what am i going to do?

**Comment by tananaev** [comment]
Well, for example you can use browser.

**Comment by sakisketc** [comment]
my cellphone browser ,right?and wha am i suppose to do from there?

**Comment by tananaev** [comment]
You are supposed to check if Internet works with the "internet" APN.

**Comment by sakisketc** [comment]
You mean if i can surf in my browser from my cellphone??yes i can...

**Comment by sakisketc** [comment]
Well i find out the solution...there was an option in my sms settings which abandoned to receive sms from the device!!!
