### ISSUE TITLE
Regarding Direction

### ISSUE THREAD

**Issue by conqsys** [traccar/traccar#1258]
I m using Course attribute which is in other field of position table but i think its not giving right direction in which vehicle is moving can you please help me to solve this problem

**Comment by tananaev** [comment]
Course parameters shouldn't be in the other field. It's a separate parameter that is stored in its own column in the database.

If you think it's incorrect value, please provide corresponding HEX message from device that can be found in `tracker-server.log` file.

**Comment by conqsys** [comment]
every hex message is different this is the one that i give you so can you helo me with this 

2015-06-22 17:18:25 DEBUG: [8023 <- 118.149.240.240] - HEX: 78780a13440604000200468b6f0d0a
2015-06-22 17:18:25 DEBUG: [8023 -> 118.149.240.240] - HEX: 787805130046df4a0d0a
2015-06-22 17:18:25  INFO: device: 6, time: Mon Jun 22 17:18:25 NZST 2015, lat: -43.53970666666667, lon: 172.55989333333332


These are the three detail in traccarweb.config and the course in my database save at this time is 54 so can you pls tell me is this right or what i have to do to resolve this problem .

**Comment by conqsys** [comment]
I am waiting for your reply

**Comment by tananaev** [comment]
The sample you provided is a status message, so it doesn't have any GPS info.
