### ISSUE TITLE
Inverted latitude & longitude

### ISSUE THREAD

**Issue by Bismuto** [traccar/traccar#1260]
Hello, I have configured my server correctly for a Haicom Hi-604x client , but the latitude & longitude are displayed with the opposite sign.

The aicom csv log shows:
```
388,T,2015/06/18,15:00:20,40.416775,N,-3.70379,W,642.8m,243.63,0.1km/h
```
and the traccar server shows latitude -40.416775 and  3.70379 when the correct coordinate is 40.416775 and  -3.70379

Please, Can anybody help me?

**Comment by tananaev** [comment]
Please provide HEX from `tracker-server.log`.
