### ISSUE TITLE
GT06N - Unknow Protocol problem

### ISSUE THREAD

**Issue by moisesf** [traccar/traccar#1261]
Sometimes the device keeps sending login e heartbeat messages and a unknown messages:
```
RECEIVED - 78,78,0a,13,46,06,04,00,02,01,80,06,36,0d,0a 
SENT - 78,78,05,13,01,80,65,A8,0D,0A
RECEIVED - 79,79,00,5b,fd
```
What is wrong ?

**Comment by tananaev** [comment]
Why do you think something is wrong? I think it's just a new type of messages. Need protocol documentation to know what it means.
