### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cgarbero** [traccar/traccar#1278]
![traccar](https://cloud.githubusercontent.com/assets/12959087/8394338/b331b428-1d08-11e5-99fd-c4e9406e4cf5.jpg)
I uninstall the previous version of traccar, i enter but i dont have access to settings SERVER, why ?

**Comment by tananaev** [comment]
Are you logging in as an `admin` user?

**Comment by cgarbero** [comment]
i use register but not say anything of admin user

**Comment by tananaev** [comment]
Only users with admin rights have access to the server settings. Try to login as `admin` with password `admin`.

**Comment by cgarbero** [comment]
thanks!!!

**Comment by cgarbero** [comment]
this version has less option than the other? it can be ? or i have to reinstall the other version ?

**Comment by tananaev** [comment]
It should be the same functionality. Let me know if something is missing.

**Comment by cgarbero** [comment]
i mean, in the other version u can change icons, you have more settings to add, odometer, sensors, in setting i dont understand you have 3 fields what do u can do with this, there is only one map, in the other version you can choice differents maps, there are many things differents than the other version.

**Comment by tananaev** [comment]
What other version are we talking about? I assume you are talking about custom Web UI from @vitalidze, but that is a separate project. You can still use it with new version of Traccar if you want to.

As for the new interface, the plan is to add more functionality and eventually have fully-featured GPS tracking system.

Yes, you can change those parameters in the config to work with MySQL.
