### ISSUE TITLE
New protocol AL900 device.

### ISSUE THREAD

**Issue by hackerunet** [traccar/traccar#1286]
Hi anton, it's been a while, I have a new device which requires new protocol because is unsupported, but I cannot publish detailed information about this device due to copyright problems, so, I have to build the protocol, can you please give me a detailed information about what do I need to program in the last traccar version to include support for a binary protocol?
I saw you have a framedecoder, a protocol and a protocol decoder java program, so how do I include a new one?
thanks

**Comment by tananaev** [comment]
You need at least `*Protocol` and `*ProtocolDecoder` classes. Protocol includes pipeline initialization which used to be in `ServerManager` class.

If protocol messages have length field, then you can use standard `LengthFieldBasedFrameDecoder`. If not, then you would have to develop custom frame decoder as well.

**Comment by hackerunet** [comment]
Ok thank you anton, let me see if I'm capable of developing this protocol, I'll get back to you when I quite trying!!... regards.

**Comment by alentos** [comment]
They managed to include the AL900

**Comment by alentos** [comment]
'khd' protocol is the solution
