### ISSUE TITLE
Question regarding send command

### ISSUE THREAD

**Issue by and12345** [traccar/traccar#1289]
Hi, i want to learn about send command. What command exactly we needs to send to device, is it serial, binary, or what. Is there any resources to help me start learning about send command ? 

Many thanks

**Comment by tananaev** [comment]
The feature is not finished yet. For now I believe GPS103 (text) and GT06 (binary) protocols are partially supported.

**Comment by tananaev** [comment]
Commands are supported for all or most protocols by now.
