### ISSUE TITLE
Traccar v3 MySQL error

### ISSUE THREAD

**Issue by frozenmaiden** [traccar/traccar#1290]
![screen shot 2015-07-04 at 1 53 21 pm](https://cloud.githubusercontent.com/assets/783039/8506857/160c0f6c-2254-11e5-9af5-8c031b9373d6.png)
I run traccar with 500 device and today i try to update my traccar to version 3 and got the issue above. That because some of my device got NULL data on column "other" at positions table.

I also found the current query at "database.selectLatestPositions" quite slow, so i make some query changes from 

SELECT \* FROM position WHERE id IN (SELECT positionId FROM device);

to

SELECT p.\* FROM position p JOIN device d ON d.positionId = p.id;

Hope it can help someone, as i take half day to figure this issue

**Comment by tananaev** [comment]
It looks like the time value is NULL. There were quite a few changes to the database scheme. For example, there is no `time` field any more. Instead there are `serverTime`, `deviceTime` and `fixTime`.

As for query, it should result in the same execution plan as your one. Have you looked at the execution plans of those two queries?

**Comment by frozenmaiden** [comment]
Yes, the issue fixed when i fill all NULL field with random value.

For query, on my server the first query took almost 10s but second query took below 1s. The different on execution time quite big.

**Comment by tananaev** [comment]
Well, maybe the query was cached.
