### ISSUE TITLE
log shows no error and web portal not working

### ISSUE THREAD

**Issue by conqsys** [traccar/traccar#1295]
I have same thing working on my local machine but when i uploaded the same on server no error i found on server and also nothing is working

server details...

**Comment by tananaev** [comment]
What is this IP and port for? Is it supposed to be Traccar web interface? SSH access? Or something else?

**Comment by conqsys** [comment]
this is remote desktop details to check why applicaiton is not working...

**Comment by tananaev** [comment]
Looks like it's working. Can you provide more details on what is the issue.
