### ISSUE TITLE
Console logging stopped working (with code fix)

### ISSUE THREAD

**Issue by demianalonso** [traccar/traccar#1301]
Hi Anton,
  I think that in the current master version logging is not working properly (at least when I tried to run it I got a warning from SLF4J that it will default to "no-operation (NOP)" logger.

  I found a way to correct the pom and put it in here (I can make a pull request if it is useful): https://github.com/demianalonso/traccar/tree/slf4j-logging-fix

  But if it is only  happening to me, then I must have some other problem.

Thanks in advance and let me know if I should make a pull request.

**Comment by tananaev** [comment]
It happens for me too, but it's only a warning. Anyway, it would be nice if you could send me a pull request of your change. Thanks

**Comment by tananaev** [comment]
Logging has been re-implemented properly recently.
