### ISSUE TITLE
No puedo instalar traccar con Mysql he segido lo pasos descritos y nada 

### ISSUE THREAD

**Issue by andyguz08** [traccar/traccar#1303]
Muy buenas, necesito su ayuda para poder correr traccar con mysql estos son los pasos que he realizado
instalar java
crear la base de datos en mysql y los permisos
instalar traccar
cambiar traccar-war por el de http://traccar.litvak.su/installation.html
modifico el archivo conf
inicio traccar
al entrar a la pagina me sale en blanco 
 YA NO SE QUE HACER AYUDA!!!

**Comment by tananaev** [comment]
Please write in English. Also, looks like use are trying to use MOD UI which is not official Traccar project, so it's better to ask author for help:

https://github.com/vitalidze/traccar-web/issues

**Comment by evigra** [comment]
Yo tengo instalada la version 2.12 en linux
siguiendo estos pasos 
https://www.traccar.org/linux/

Descargando este ZIP
https://github.com/tananaev/traccar/releases/download/v2.12/tracker-server-2.12.zip

**Comment by tananaev** [comment]
If you want to download version 2.12 installer, you can find it here:

https://github.com/tananaev/traccar/releases/tag/v2.12
