### ISSUE TITLE
Installation Of Traccar and How to Use it ?

### ISSUE THREAD

**Issue by madhu781** [traccar/traccar#1304]
Hi All,

Thanks for the great Project Traccar.
I am new for the Trackcar.
Now i want to work on Traccar. Can you explain me how to Install and use it.
Thanks in Advance.

Regards,
Madhu

**Comment by tananaev** [comment]
Please read following page:
https://www.traccar.org/quick-start/

If you have any questions feel free to ask.

**Comment by Crisgps** [comment]
Hi! I read https://www.traccar.org/quick-start/  and create a VPS windows server with a public IP, and install traccar and java, the service works, if use http://localhost:8082/ show me all the page of traccar, but when I try to acces from outside with the public IP that vps give me, I can't acces to application, any ideas?

My VPS was create with aws amazon, and i oppenden the 8082 and 7070 ports, but I can't access from internet..

Any idea I'll appreciate too much!!! thanks

**Comment by Crisgps** [comment]
It solved, it's necessary to open port in the firewall, i can access from outside and add the device but I can't received position....

**Comment by tananaev** [comment]
Have you opened port for device as well? What device do you use and what port is it configured to?
