### ISSUE TITLE
Develop send command for Enfora

### ISSUE THREAD

**Issue by gioramies** [traccar/traccar#1306]
I have the code (a hack), to send commands to Enfora devices, but do not know how to implement it in the new traccar. ¿Can someone give me some help to do it? And how can I send a command using my own UI?
Thank you.

**Comment by tananaev** [comment]
I have seen your messages, but I haven't got time to look at your log or source code yet. I will let you know when I have any questions or updates.

**Comment by gioramies** [comment]
Thank you. I'll be in touch if you need some help. Is there any documentation about how implement a "Send command" for a protocol?

**Comment by tananaev** [comment]
I am doing some modifications to the commands, so it's better to wait for a few days till I finish it.

**Comment by tananaev** [comment]
I have made the changes, so now you can try to implement commands if you want.

Basically you need to do following things:

0. Add new command types to `Command` class if you need
1. Declare supported commands for your `Protocol` class (see `Gps103Protocol` for example)
2. Create encoder class based from `BaseProtocolEncoder` (see `Gps103ProtocolEncoder` for example)
3. Implement `encodeCommand()` method in the encoder
4. Add your encoder class to the protocol pipeline (see `Gps103Protocol` for example)

**Comment by gioramies** [comment]
Thank you. I have seen the code but do not understand it yet. 
My main concern is about how the server recieves the command order from the UI. 
In my implementation, and ended doing it in the new version too, I have a port opened to receive the commands, then find the channel in a List and send the message. 
I do not know if you have designed this functionality, if you need help I can send you the code.

**Comment by tananaev** [comment]
Commands would come from the web interface API directly. That part is ready, but I haven't implemented the UI for the commands yet.
