### ISSUE TITLE
Error Starting traccar: pls help. TIA 

### ISSUE THREAD

**Issue by sebdigo** [traccar/traccar#1307]
```
wrapper  | Unable to write to the configured log directory: ..\logs (Access is d
enied. (0x5))
wrapper  |   The Wrapper may also have problems writing or rolling the log file.

wrapper  |   Please make sure that the current user has read/write access.
wrapper  | Unable to write to the configured log file: ..\logs\wrapper.log.20150
716 (Access is denied. (0x5))
wrapper  |   Falling back to the default file in the current working directory:
wrapper.log
wrapper  | Unable to write to the default log file: wrapper.log (Access is denie
d. (0x5))
wrapper  |   Disabling log file.
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Community Edition 64-bit 3.5.26
wrapper  |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | WrapperSimpleApp:
jvm 1    | WrapperSimpleApp Error: Encountered an error running main:
jvm 1    | WrapperSimpleApp Error: java.io.FileNotFoundException: C:\Program Fil
es (x86)\Traccar\logs\tracker-server.log (Access is denied)
jvm 1    | WrapperSimpleApp Error:      at java.io.FileOutputStream.open0(Native
 Method)
jvm 1    | WrapperSimpleApp Error:      at java.io.FileOutputStream.open(Unknown
 Source)
jvm 1    | WrapperSimpleApp Error:      at java.io.FileOutputStream.<init>(Unkno
wn Source)
jvm 1    | WrapperSimpleApp Error:      at java.io.FileOutputStream.<init>(Unkno
wn Source)
jvm 1    | WrapperSimpleApp Error:      at org.apache.log4j.FileAppender.setFile
(FileAppender.java:294)
jvm 1    | WrapperSimpleApp Error:      at org.apache.log4j.FileAppender.<init>(
FileAppender.java:110)
jvm 1    | WrapperSimpleApp Error:      at org.apache.log4j.DailyRollingFileAppe
nder.<init>(DailyRollingFileAppender.java:203)
jvm 1    | WrapperSimpleApp Error:      at org.traccar.helper.Log.setupLogger(Lo
g.java:49)
jvm 1    | WrapperSimpleApp Error:      at org.traccar.Context.init(Context.java
:89)
jvm 1    | WrapperSimpleApp Error:      at org.traccar.Main.main(Main.java:26)
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.NativeMethodAccessorImpl.
invoke0(Native Method)
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.NativeMethodAccessorImpl.
invoke(Unknown Source)
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.DelegatingMethodAccessorI
mpl.invoke(Unknown Source)
jvm 1    | WrapperSimpleApp Error:      at java.lang.reflect.Method.invoke(Unkno
wn Source)
jvm 1    | WrapperSimpleApp Error:      at org.tanukisoftware.wrapper.WrapperSim
pleApp.run(WrapperSimpleApp.java:325)
jvm 1    | WrapperSimpleApp Error:      at java.lang.Thread.run(Unknown Source)
wrapper  | <-- Wrapper Stopped
Press any key to continue . . .
```

**Comment by sebdigo** [comment]
moved traccar from C: to D:
now having this error 
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Community Edition 64-bit 3.5.26
wrapper  |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | WrapperSimpleApp:
jvm 1    | WrapperSimpleApp Error: Encountered an error running main:
jvm 1    | WrapperSimpleApp Error: org.jboss.netty.channel.ChannelException: Fai
led to bind to: 0.0.0.0/0.0.0.0:5004
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.bootstrap.Connectionl
essBootstrap.bind(ConnectionlessBootstrap.java:204)
jvm 1    | WrapperSimpleApp Error:      at org.traccar.TrackerServer.start(Track
erServer.java:134)
jvm 1    | WrapperSimpleApp Error:      at org.traccar.ServerManager.start(Serve
rManager.java:135)
jvm 1    | WrapperSimpleApp Error:      at org.traccar.Main.main(Main.java:32)
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.NativeMethodAccessorImpl.
invoke0(Native Method)
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.NativeMethodAccessorImpl.
invoke(Unknown Source)
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.DelegatingMethodAccessorI
mpl.invoke(Unknown Source)
jvm 1    | WrapperSimpleApp Error:      at java.lang.reflect.Method.invoke(Unkno
wn Source)
jvm 1    | WrapperSimpleApp Error:      at org.tanukisoftware.wrapper.WrapperSim
pleApp.run(WrapperSimpleApp.java:325)
jvm 1    | WrapperSimpleApp Error:      at java.lang.Thread.run(Unknown Source)
jvm 1    | WrapperSimpleApp Error: Caused by: java.net.BindException: Address al
ready in use: bind
jvm 1    | WrapperSimpleApp Error:      at sun.nio.ch.Net.bind0(Native Method)
jvm 1    | WrapperSimpleApp Error:      at sun.nio.ch.Net.bind(Unknown Source)
jvm 1    | WrapperSimpleApp Error:      at sun.nio.ch.DatagramChannelImpl.bind(U
nknown Source)
jvm 1    | WrapperSimpleApp Error:      at sun.nio.ch.DatagramSocketAdaptor.bind
(Unknown Source)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.socket.nio.Ni
oDatagramPipelineSink.bind(NioDatagramPipelineSink.java:129)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.socket.nio.Ni
oDatagramPipelineSink.eventSunk(NioDatagramPipelineSink.java:77)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.DefaultChanne
lPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.jav
a:779)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.SimpleChannel
Handler.bindRequested(SimpleChannelHandler.java:299)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.SimpleChannel
Handler.handleDownstream(SimpleChannelHandler.java:265)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.DefaultChanne
lPipeline.sendDownstream(DefaultChannelPipeline.java:591)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.DefaultChanne
lPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.jav
a:784)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.handler.logging.Loggi
ngHandler.handleDownstream(LoggingHandler.java:338)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.DefaultChanne
lPipeline.sendDownstream(DefaultChannelPipeline.java:591)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.DefaultChanne
lPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.jav
a:784)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.handler.codec.oneone.
OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.DefaultChanne
lPipeline.sendDownstream(DefaultChannelPipeline.java:591)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.DefaultChanne
lPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.jav
a:784)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.SimpleChannel
Handler.bindRequested(SimpleChannelHandler.java:299)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.SimpleChannel
Handler.handleDownstream(SimpleChannelHandler.java:265)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.DefaultChanne
lPipeline.sendDownstream(DefaultChannelPipeline.java:591)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.DefaultChanne
lPipeline.sendDownstream(DefaultChannelPipeline.java:582)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.Channels.bind
(Channels.java:561)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.channel.AbstractChann
el.bind(AbstractChannel.java:198)
jvm 1    | WrapperSimpleApp Error:      at org.jboss.netty.bootstrap.Connectionl
essBootstrap.bind(ConnectionlessBootstrap.java:198)
jvm 1    | WrapperSimpleApp Error:      ... 9 more

**Comment by sebdigo** [comment]
tracker-server log
2015-07-17 00:16:55  INFO: Starting server...
2015-07-17 00:16:55  INFO: Operating System name: Windows 7 version: 6.1 architecture: amd64
2015-07-17 00:16:55  INFO: Java Runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.45-b02
2015-07-17 00:16:55  INFO: Memory Limit heap: 891mb non-heap: 0mb
2015-07-17 00:16:55  INFO: Version: 3.0-SNAPSHOT
2015-07-17 00:16:55  WARN: Address already in use: bind - BindException (... < TrackerServer.java:134 < ServerManager.java:135 < Main.java:32 < ...)
2015-07-17 00:16:55  INFO: Closing connection by exception

**Comment by tananaev** [comment]
You have some other application/service that uses port 5004. You need to either change port or stop that other app or change port in Traccar config file to different one.

**Comment by sebdigo** [comment]
changed port. now new error...

2015-07-17 17:11:24  WARN: Table "USER" not found; SQL statement:

        SELECT * FROM user;
     [42102-187] - JdbcSQLException (... < QueryBuilder.java:51 < *:120 < DataManager.java:225 < PermissionsManager.java:50 < ...)
2015-07-17 17:11:27  INFO: Starting server...
2015-07-17 17:11:27  INFO: Operating System name: Windows 7 version: 6.1 architecture: amd64
2015-07-17 17:11:27  INFO: Java Runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.45-b02
2015-07-17 17:11:27  INFO: Memory Limit heap: 891mb non-heap: 0mb
2015-07-17 17:11:27  INFO: Version: 3.0-SNAPSHOT
2015-07-17 17:17:21  WARN: Connections could not be acquired from the underlying database! - SQLException (... < QueryBuilder.java:46 < *:120 < DataManager.java:225 < PermissionsManager.java:50 < ...)
2015-07-17 17:19:03  WARN: Connections could not be acquired from the underlying database! - SQLException (... < QueryBuilder.java:46 < *:120 < DataManager.java:225 < PermissionsManager.java:50 < ...)

**Comment by sebdigo** [comment]
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Community Edition 64-bit 3.5.26
wrapper  |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | WrapperSimpleApp:
jvm 1    | WrapperSimpleApp Error: Encountered an error running main:
jvm 1    | WrapperSimpleApp Error: java.sql.SQLException: Connections could not
be acquired from the underlying database!
jvm 1    | WrapperSimpleApp Error:      at com.mchange.v2.sql.SqlUtils.toSQLExce
ption(SqlUtils.java:118)
jvm 1    | WrapperSimpleApp Error:      at com.mchange.v2.c3p0.impl.C3P0PooledCo
nnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
jvm 1    | WrapperSimpleApp Error:      at com.mchange.v2.c3p0.impl.AbstractPool
BackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
jvm 1    | WrapperSimpleApp Error:      at org.traccar.database.DataManager.init
DatabaseSchema(DataManager.java:144)
jvm 1    | WrapperSimpleApp Error:      at org.traccar.Context.init(Context.java
:115)
jvm 1    | WrapperSimpleApp Error:      at org.traccar.Main.main(Main.java:26)
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.NativeMethodAccessorImpl.
invoke0(Native Method)
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.NativeMethodAccessorImpl.
invoke(Unknown Source)
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.DelegatingMethodAccessorI
mpl.invoke(Unknown Source)
jvm 1    | WrapperSimpleApp Error:      at java.lang.reflect.Method.invoke(Unkno
wn Source)
jvm 1    | WrapperSimpleApp Error:      at org.tanukisoftware.wrapper.WrapperSim
pleApp.run(WrapperSimpleApp.java:325)
jvm 1    | WrapperSimpleApp Error:      at java.lang.Thread.run(Unknown Source)
jvm 1    | WrapperSimpleApp Error: Caused by: com.mchange.v2.resourcepool.Cannot
AcquireResourceException: A ResourcePool could not acquire a resource from its p
rimary factory or source.
jvm 1    | WrapperSimpleApp Error:      at com.mchange.v2.resourcepool.BasicReso
urcePool.awaitAvailable(BasicResourcePool.java:1469)
jvm 1    | WrapperSimpleApp Error:      at com.mchange.v2.resourcepool.BasicReso
urcePool.prelimCheckoutResource(BasicResourcePool.java:644)
jvm 1    | WrapperSimpleApp Error:      at com.mchange.v2.resourcepool.BasicReso
urcePool.checkoutResource(BasicResourcePool.java:554)
jvm 1    | WrapperSimpleApp Error:      at com.mchange.v2.c3p0.impl.C3P0PooledCo
nnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
jvm 1    | WrapperSimpleApp Error:      at com.mchange.v2.c3p0.impl.C3P0PooledCo
nnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
jvm 1    | WrapperSimpleApp Error:      ... 10 more
wrapper  | <-- Wrapper Stopped
Press any key to continue . . .

**Comment by tananaev** [comment]
Try to remove all files from `data` directory and see if it helps.

**Comment by sebdigo** [comment]
it helped... thanks tananaev.... :)

Current problem is im not getting any signal from traccar client..(android).. 
used my public 'ip' as shown by google n also that shown in https://www.traccar.org/quick-start/ (both are different..)...  im not getting any data in log... pls help again..tia

**Comment by sebdigo** [comment]
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Community Edition 64-bit 3.5.26
wrapper  |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | 2015-07-20 12:14:08.821:INFO:oejs.Server:jetty-8.1.17.v20150415
jvm 1    | 2015-07-20 12:14:08.844:INFO:oejs.AbstractConnector:Started SelectCha
nnelConnector@0.0.0.0:8082

**Comment by sebdigo** [comment]
Also when i tried to use phones IMEI as unique identifier it show error

 'Unique index or primary key violation: "CONSTRAINT_INDEX_7 ON PUBLIC.DEVICE(UNIQUEID) VALUES ('866376021800583', 1)"; SQL statement: UPDATE device SET name = ?, uniqueId = ? WHERE id = ?; [23505-187]'...

**Comment by tananaev** [comment]
Check if the port is visible from internet:
http://www.tananaev.com/port.html

As for error, looks like you already have device with the same unique id in the database.

**Comment by sebdigo** [comment]
POrt is closed... What to do now...?

**Comment by tananaev** [comment]
Well, it means that there is a problem with router or firewall.
