### ISSUE TITLE
iBaby GPS needs to register -- how do I respond to it?

### ISSUE THREAD

**Issue by zzmyers** [traccar/traccar#1313]
I have an iBaby Kids phone which identifies as Q5II-G-I-01 in a registration attempt with my server. Obviously if I use the manufacturers server, it gets a reply.

I wrote a quick and dirty decoder for the positioning messages, but this only works if the device is already registered. 

I have the protocol so I know what needs to be sent back.  I just don't really understand how to go about sending a reply. The protocol is using HTTP POST, so it should be possible to do. Maybe someone could point me at another protocol which does a similar thing so I can learn from that how to do this in traccar. Thanks,

**Comment by tananaev** [comment]
Can you please provide protocol documentation. If you don't want to publish it publicly, you can send it by email (address in profile).

**Comment by zzmyers** [comment]
Here is the protocol attached. Other than the bad English it looks 
pretty complete. I also included the manual as it does  include some 
other data about the unit, but more on the SMS side. I do know of one 
SMS command which is in neither manual which is to change the IP address 
of the unit, which is *setip:*<ip addres>*@*<port>*@*<subdirectory>, for 
example *setip:111.222.333.444@5001@*. Note that the last field can be 
blank, but you still need the @ sign. Pretty important to get it running 
with you server and it is not in the manual.

Steve

**Comment by tananaev** [comment]
You can't attach files to the GitHub email. If you want to send it directly, you can find my email address in the profile.

**Comment by zzmyers** [comment]
Forgot about that. I emailed them to you.

Steve

**Comment by tananaev** [comment]
There is OsmAnd HTTP protocol which just send OK response:
https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/OsmAndProtocolDecoder.java#L122

There is also an MTA6 protocol which has an example of response with payload data:
https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Mta6ProtocolDecoder.java#L56

I hope you will share the decoder with community :smirk:

**Comment by zzmyers** [comment]
Thanks. I was trying to use OsmAnd as a base but kept getting errors in 
the HTTP routines. I will look at MTA6, maybe it will give me a better clue.

I'll be happy to share -- it is real hackish at the moment with lots of 
debug code in it and is only decoding a couple of the messages just 
reading the HTTP posts as text and chopping them up. So, I definitely 
have some work to do.

**Comment by jamejo** [comment]
C88(G) - Ibaby GPS Trakcer protocol has been implemented on Traccar? It would be nice to know if this can be implemented in the next release and the next release date? of Traccar

**Comment by tananaev** [comment]
It's not implemented yet. @jamejo, please send me an email if you need this to be included in the next release.
