### ISSUE TITLE
Help to identify protocol

### ISSUE THREAD

**Issue by panariga** [traccar/traccar#1329]
Hello.
Can`t identify protocol. 
There is model on board GT02-V01. And sticker on RF-shield with number 06A
Hex messages from log:
```
78781f120f071f170011c905680b5f034538a900352c00ff036a32000548001c4d2d0d0a
78781f120f071f17002fc905680b5f034538a900352c00ff036a32000548001d72140d0a
78781f120f071f170111c805680b5f034538a900352c00ff036a32000548001e9c260d0a
78781f120f071f170130c905680b5f034538a900352c00ff036a32000548001f1d1a0d0a
```
IMEI 355488448815886
Any ideas?

**Comment by tananaev** [comment]
It's GT06 protocol. Port 5023 in Traccar.

**Comment by panariga** [comment]
Thank you!
Why it doesn`t work when I try this port myself?
But after your answer - work as expected))))

**Comment by tananaev** [comment]
Maybe you didn't wait long enough. Some devices can take up to 10 minutes to get an initial GPS fix.
