### ISSUE TITLE
Time to upgrade to netty 4.0?

### ISSUE THREAD

**Issue by hallmark9** [traccar/traccar#1338]
Netty 4.0 has been out for a while. And I actually built traccar against it and everything appears ok. You might want to consider upgrading to take advantage of the new features/fixes.

**Comment by tananaev** [comment]
Can you send me a pull request? What are the new features? As for bug fixes, many big projects are using Netty 3 and it's still supported.

There is also Netty 5. Does it makes sense to upgrade straight to 5?

**Comment by hallmark9** [comment]
You are right. I actually just tried 5.0.0.Alpha2 and it worked too. Here are the noteworthy changes:http://netty.io/wiki/new-and-noteworthy.html I guess some traccar code can be refactored simplier with the new version (without refactoring, the current code is still compatible though).

Big projects might be more tied to old versions for that it naturally use more APIs making it more risky to upgrade. 

I don't have a clean fork to create a pull request but the changes are only 2 lines in  traccar/pom.xml
:

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>5.0.0.Alpha2</version>
        </dependency>

**Comment by hallmark9** [comment]
I take that back. My previous build against netty 4 was not clean.

Now I've cleaned and rebuilt it, if failed. Most of the failures look like related to package name change, and ChannelBuffer class name change in netty 4.

This doesn't look trivial so I'll leave it with netty 3, unless someone takes on the upgrade.

**Comment by tananaev** [comment]
I plan to update eventually, but I want to wait till stable version of Netty 5 is out.

**Comment by tananaev** [comment]
Traccar has been migrated to Netty 4.1.
