### ISSUE TITLE
Add Weather‏ api

### ISSUE THREAD

**Issue by maxicabanillas78** [traccar/traccar#1343]
friend would be great if you added an API with temperature.
One more and very interesting it has no differential
it would use this api

http://api.openweathermap.org/data/2.5/weather?lat=-22.8188773&lon=-42.9958001&units=metric

`{"coord":{"lon":-43.04,"lat":-22.82},"weather":[{"id":800,"main":"Clear","description":"Sky is Clear","icon":"01n"}],"base":"stations","main":{"temp":21.62,"pressure":1023,"humidity":73,"temp_min":15.56,"temp_max":27.78},"visibility":10000,"wind":{"speed":4.6,"deg":80},"clouds":{"all":0},"dt":1439174800,"sys":{"type":1,"id":4565,"message":0.0124,"country":"BR","sunrise":1439198442,"sunset":1439238875},"id":6322065,"name":"São Gonçalo","cod":200}`

all this api be great to get
"temp":21.62
"icon":"01n"
http://openweathermap.org/img/w/01n.png
http://openweathermap.org/weather-conditions

thank you
I hope that you can apply this api in its largest project is the traccar
desculpa my English

**Comment by SebastEnn** [comment]
OpenWeather got [inplemented](https://github.com/traccar/traccar/issues/4865#issuecomment-1153188991). Issue can be closed.

**Comment by tananaev** [comment]
Don't know if this is exactly the same, but we can close for now. If something more needed, let us know.
