### ISSUE TITLE
Sending commands through another interface

### ISSUE THREAD

**Issue by marcuscarvalho6** [traccar/traccar#1346]
I use traccar only as a server , I have my own web interface. Is there any way to send the command without the standard interface?

**Comment by tananaev** [comment]
Yes, there is an API that you can use. Unfortunately there is no documentation on the commands part yet.

Here you can find some information:
https://www.traccar.org/traccar-api/

For commands I guess you would have to look at the code. Let me know if you have any problems or questions.

**Comment by marcuscarvalho6** [comment]
Could you tell me a command sent sample through the API ?

**Comment by tananaev** [comment]
API path: `/api/command/send`

Payload example:
<pre>{deviceId: 2171, type: "engineStop"}</pre>

**Comment by mtrntx** [comment]
Is possible that I can write every command by protocol in a module to add the command label and the command to send
For example in the case of a meitrack device
The label command Stop Engine
The command C01,0,12222
This command active the output 1 on the meitrack device

**Comment by tananaev** [comment]
Command types are shared, but every protocol needs to implement message formatting.

**Comment by thaihau** [comment]
Can i ask how this command work? Is zit tracker server send command to device via it's IP in GPRS network?

**Comment by tananaev** [comment]
Server sends commands via open connection in case of TCP protocol or to IP and port in case of UDP protocol.
