### ISSUE TITLE
GPS306 tracker support

### ISSUE THREAD

**Issue by ershov-a** [traccar/traccar#1350]
I have this [tracker](http://www.aliexpress.com/item/tk306a-Car-Vehicle-GSM-GPS-OBD-Tracker-Coban-GPS306A-OBD-Data-OBD2-Free-PC-tracking-software/2049717940.html). Is it support TracCar?

**Comment by tananaev** [comment]
Most likely it is. Please read following page:

https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/

**Comment by hulizu** [comment]
Thanks, I will try it later.

**Comment by hulizu** [comment]
Is there support for information from OBD II?

**Comment by tananaev** [comment]
It depends on the protocol. Some protocols include support for OBD.

**Comment by hulizu** [comment]
OK, is traccar support OBD information display?

**Comment by tananaev** [comment]
Yes, but for now only in current status.
