### ISSUE TITLE
Jingmei Tracker

### ISSUE THREAD

**Issue by farbeed** [traccar/traccar#1354]
Hi,

Is Traccar support JingMei Trackers?

here is the link of the device in AliBaba
http://www.alibaba.com/product-detail/sos-button-gps-car-tracker-car_60102542782.html?spm=a2700.7724857.35.1.M0DATV

**Comment by tananaev** [comment]
Most likely yes, but to confirm I need protocol documentation or message samples.

If you already have the device, you can try port from the following page:
https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/
