### ISSUE TITLE
Route Trace

### ISSUE THREAD

**Issue by minimalstudiodesgn** [traccar/traccar#1358]
Is there any way to trace the routes correctly through the streets?
![captura de pantalla 2015-08-17 a las 16 20 27](https://cloud.githubusercontent.com/assets/8333573/9313961/5d08df06-44fc-11e5-83fd-6f6e3eefa1d0.png)

**Comment by tananaev** [comment]
What device are you using? I suspect there is some problem with time or GPS coordinates.

**Comment by minimalstudiodesgn** [comment]
I'm testing with an android device (using traccar client).

**Comment by tananaev** [comment]
Which version of Traccar Client are you using?

**Comment by minimalstudiodesgn** [comment]
The last version, from play store, anyway, the route should fit the pattern of the streets, I'm wrong?

**Comment by tananaev** [comment]
Traccar just connects reported GPS points with lines, but yes, it should follow the streets as long as the data is correct. Can you please provide `tracker-server.log` file for me to investigate.

**Comment by minimalstudiodesgn** [comment]
this route was tested in your demo site: demo.traccar.org

**Comment by tananaev** [comment]
The latest version was release after you recorded your track. I guess you were using the latest one at that point which had an option for "mixed" location provider. Did you use that provider?

**Comment by karussell** [comment]
@tananaev I really like your project and there could be a nice possibility to join forces for features like the requested here "snap to road". We've developed this algorithm called 'map matching' based on GraphHopper [here](https://github.com/graphhopper/map-matching), also Java, also Apache License so it could be a nice fit :)

See this animation 

![map matching](https://graphhopper.com/api/1/docs/img/map-matching-example.gif)

And one could also attach properties back to the coordinates like maximum speed, road name, turn instructions, road type, ...

Still investigating the issues here, what kind of use case would be the most interesting for traccar users. Do you have a forum or mailing list?

**Comment by tananaev** [comment]
@karussell, this particular issue here has nothing to do with snapping to road. If you want to discuss this topic, I would recommend to create a new issue or find a relevant one.

There is a forum here if you want to discuss it there:

https://www.traccar.org/forums/
