### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Mikelord2** [traccar/traccar#1360]
Questions, install the latest version of traccar 3.1, VPS, clean installation, before executing anything, change the lines for MySQL server as indicated by the manual, add an Android device for generating positions, but to check in the database no position stored in the "position" table, and my other question has traccar mobile version 3.1?

![image](https://cloud.githubusercontent.com/assets/10438858/9320862/401e9f00-4535-11e5-9600-7817b0ab868b.png)

**Comment by tananaev** [comment]
It looks like there is some problem with reverse geocoding. Try to disable it and see if it helps.

**Comment by superservidor** [comment]
@Mikelord2  You can buy a good VPS server ( 1 x 2.4 Ghz CPU, 1GB Ram, 40 GB Storage, 1 Terabyte monthly Transfer) starting at EUR 1.99 by month at http://www.time4vps.eu/aff.php?aff=181 . If you buy this VPS server I can give you the Traccar server already installed on it using Ubuntu 14.04. IF you are interested please send me an e-mail.
