### ISSUE TITLE
Error on install from Source Code

### ISSUE THREAD

**Issue by marcuscarvalho6** [traccar/traccar#1361]
Anton, please help-me, i'm tried install traccar from source code. And I'm running into the following problem:

<pre>root@ip-172-31-4-28:/home/ubuntu/traccar/setup# ./package.sh '3.1'
../tools/minify.sh: 7: ../tools/minify.sh: sencha: not found
warning: unexpected setup data version: 5.5.6
warning: unexpected Uninstall Log Mode value: 153
warning: unexpected Auto Boolean value: 9
warning: unexpected Compression Method value: 84
warning: unexpected Architecture flags: 40
warning: unexpected Architecture flags: 40
warning: unexpected Auto Boolean value: 69
warning: unexpected Auto Boolean value: 67
stream error: basic_ios::clear
Done with 1 error and 8 warnings.
If you got any errors here try isetup version 5.5.5 (or check what versions are supported by 'innoextract -v')
wine: cannot find 'app/ISCC.exe'
    zip warning: name not matched: windows/Output/setup.exe
updating: README.txt (deflated 52%)
Archive:  wrapper-windows-x86-64-3.5.26-st.zip
replace wrapper-windows-x86-64-3.5.26-st/README_de.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: wrapper-windows-x86-64-3.5.26-st/README_de.txt  
  inflating: wrapper-windows-x86-64-3.5.26-st/README_en.txt  
  inflating: wrapper-windows-x86-64-3.5.26-st/README_es.txt  
  inflating: wrapper-windows-x86-64-3.5.26-st/README_ja.txt  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/DemoApp.bat  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/GetHostId.bat  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/InstallTestWrapper-NT.bat  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/PauseTestWrapper-NT.bat  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/QueryTestWrapper-NT.bat  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/ResumeTestWrapper-NT.bat  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/StartTestWrapper-NT.bat  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/StopTestWrapper-NT.bat  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/TestWrapper.bat  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/TestWrapperCommand.bat  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/UninstallTestWrapper-NT.bat  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/wrapper.exe  
  inflating: wrapper-windows-x86-64-3.5.26-st/bin/wrapperw.exe  
  inflating: wrapper-windows-x86-64-3.5.26-st/conf/demoapp.conf  
  inflating: wrapper-windows-x86-64-3.5.26-st/conf/wrapper-license.conf  
  inflating: wrapper-windows-x86-64-3.5.26-st/conf/wrapper.conf  
  inflating: wrapper-windows-x86-64-3.5.26-st/doc/index.html  
  inflating: wrapper-windows-x86-64-3.5.26-st/doc/revisions.txt  
  inflating: wrapper-windows-x86-64-3.5.26-st/doc/wrapper-development-license-1.2.txt  
  inflating: wrapper-windows-x86-64-3.5.26-st/doc/wrapper-server-license-1.2.txt  
  inflating: wrapper-windows-x86-64-3.5.26-st/doc/wrapper-tsims-addendum-1.2.txt  
  inflating: wrapper-windows-x86-64-3.5.26-st/lang/wrapperTestApp_de.mo  
  inflating: wrapper-windows-x86-64-3.5.26-st/lang/wrapperTestApp_ja.mo  
  inflating: wrapper-windows-x86-64-3.5.26-st/lang/wrapper_de.mo  
  inflating: wrapper-windows-x86-64-3.5.26-st/lang/wrapper_ja.mo  
  inflating: wrapper-windows-x86-64-3.5.26-st/lang/wrapperjni_de.mo  
  inflating: wrapper-windows-x86-64-3.5.26-st/lang/wrapperjni_ja.mo  
  inflating: wrapper-windows-x86-64-3.5.26-st/lib/wrapper.dll  
  inflating: wrapper-windows-x86-64-3.5.26-st/lib/wrapper.jar  
  inflating: wrapper-windows-x86-64-3.5.26-st/lib/wrapperdemo.jar  
  inflating: wrapper-windows-x86-64-3.5.26-st/lib/wrappertest.jar  
  inflating: wrapper-windows-x86-64-3.5.26-st/logs/wrapper.log  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/bin/App.bat.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/bin/AppCommand.bat.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/bin/AppNoWrapper.bat.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/bin/AppTemplate.bat.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/bin/AppTemplatePassThrough.bat.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/bin/InstallApp-NT.bat.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/bin/PauseApp-NT.bat.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/bin/QueryApp-NT.bat.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/bin/ResumeApp-NT.bat.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/bin/StartApp-NT.bat.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/bin/StopApp-NT.bat.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/bin/UninstallApp-NT.bat.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/conf/wrapper-license-time.conf  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/conf/wrapper.conf.in  
  inflating: wrapper-windows-x86-64-3.5.26-st/src/conf/wrapper.conf.in_ja  
cp: cannot stat ‘wrapper_*_src/bin/wrapper.exe’: No such file or directory
cp: cannot stat ‘wrapper_*_src/lib/wrapper.dll’: No such file or directory
cp: cannot stat ‘wrapper_*_src/lib/wrapper.jar’: No such file or directory
wine: cannot find 'app/ISCC.exe'
    zip warning: name not matched: windows/Output/setup.exe
updating: README.txt (deflated 52%)
Header is 498 lines long

About to compress 10632 KB of data...
Adding files to archive named "traccar.run"...
./
./logs/
./web/
./web/app.js
./web/debug.html
./web/l10n/
./web/l10n/de.js
./web/l10n/en.js
./web/l10n/dk.js
./web/l10n/es.js
./web/l10n/pt.js
./web/l10n/fr.js
./web/l10n/zh.js
./web/l10n/pl.js
./web/l10n/ru.js
./web/l10n/nl.js
./web/l10n/th.js
./web/release.html
./web/app/
./web/app/controller/
./web/app/controller/Root.js
./web/app/Resources.js
./web/app/model/
./web/app/model/Device.js
./web/app/model/Position.js
./web/app/model/User.js
./web/app/model/Command.js
./web/app/model/Parameter.js
./web/app/model/Server.js
./web/app/Application.js
./web/app/ErrorManager.js
./web/app/store/
./web/app/store/TimeUnits.js
./web/app/store/SpeedUnits.js
./web/app/store/CommandTypes.js
./web/app/store/MapTypes.js
./web/app/store/Parameters.js
./web/app/store/DistanceUnits.js
./web/app/store/Users.js
./web/app/store/Positions.js
./web/app/store/LiveData.js
./web/app/store/Languages.js
./web/app/store/Devices.js
./web/app/view/
./web/app/view/admin/
./web/app/view/admin/ServerDialogController.js
./web/app/view/admin/ServerDialog.js
./web/app/view/login/
./web/app/view/login/Register.js
./web/app/view/login/Login.js
./web/app/view/login/RegisterController.js
./web/app/view/login/LoginController.js
./web/app/view/map/
./web/app/view/map/Map.js
./web/app/view/map/MapController.js
./web/app/view/device/
./web/app/view/device/Device.js
./web/app/view/device/DeviceController.js
./web/app/view/device/DeviceDialog.js
./web/app/view/device/DeviceDialogController.js
./web/app/view/main/
./web/app/view/main/MainMobile.js
./web/app/view/main/Main.js
./web/app/view/state/
./web/app/view/state/State.js
./web/app/view/state/StateController.js
./web/app/view/command/
./web/app/view/command/CommandDialogController.js
./web/app/view/command/CommandDialog.js
./web/app/view/report/
./web/app/view/report/Report.js
./web/app/view/report/ReportController.js
./web/app/view/user/
./web/app/view/user/UserDialog.js
./web/app/view/user/User.js
./web/app/view/user/UserController.js
./web/app/view/user/UserDialogController.js
./web/app/LoginManager.js
./web/favicon.ico
./web/locale.js
./tracker-server.jar
./conf/
./conf/wrapper.conf
./conf/traccar.xml
./bin/
./bin/wrapper
./bin/traccar
./data/
./setup.sh
./lib/
./lib/jetty-webapp-9.2.13.v20150730.jar
./lib/jetty-http-9.2.13.v20150730.jar
./lib/jetty-io-9.2.13.v20150730.jar
./lib/javax.json-1.0.4.jar
./lib/jetty-security-9.2.13.v20150730.jar
./lib/mchange-commons-java-0.2.10.jar
./lib/wrapper.jar
./lib/slf4j-simple-1.7.12.jar
./lib/log4j-1.2.17.jar
./lib/libwrapper.so
./lib/c3p0-0.9.5.1.jar
./lib/jetty-util-9.2.13.v20150730.jar
./lib/jetty-xml-9.2.13.v20150730.jar
./lib/jetty-server-9.2.13.v20150730.jar
./lib/slf4j-api-1.7.12.jar
./lib/postgresql-9.4-1201-jdbc41.jar
./lib/mysql-connector-java-5.1.36.jar
./lib/async-http-client-1.9.30.jar
./lib/javax.servlet-api-3.1.0.jar
./lib/h2-1.4.187.jar
./lib/joda-time-2.8.1.jar
./lib/netty-3.10.4.Final.jar
./lib/jetty-servlet-9.2.13.v20150730.jar
CRC: 3041490277
MD5: 707b313f19c54606845dbee78580fba4

Self-extractable archive "traccar.run" successfully created.
updating: traccar.run (deflated 0%)
updating: README.txt (deflated 52%)
Header is 498 lines long

About to compress 10680 KB of data...
Adding files to archive named "traccar.run"...
./
./logs/
./web/
./web/app.js
./web/debug.html
./web/l10n/
./web/l10n/de.js
./web/l10n/en.js
./web/l10n/dk.js
./web/l10n/es.js
./web/l10n/pt.js
./web/l10n/fr.js
./web/l10n/zh.js
./web/l10n/pl.js
./web/l10n/ru.js
./web/l10n/nl.js
./web/l10n/th.js
./web/release.html
./web/app/
./web/app/controller/
./web/app/controller/Root.js
./web/app/Resources.js
./web/app/model/
./web/app/model/Device.js
./web/app/model/Position.js
./web/app/model/User.js
./web/app/model/Command.js
./web/app/model/Parameter.js
./web/app/model/Server.js
./web/app/Application.js
./web/app/ErrorManager.js
./web/app/store/
./web/app/store/TimeUnits.js
./web/app/store/SpeedUnits.js
./web/app/store/CommandTypes.js
./web/app/store/MapTypes.js
./web/app/store/Parameters.js
./web/app/store/DistanceUnits.js
./web/app/store/Users.js
./web/app/store/Positions.js
./web/app/store/LiveData.js
./web/app/store/Languages.js
./web/app/store/Devices.js
./web/app/view/
./web/app/view/admin/
./web/app/view/admin/ServerDialogController.js
./web/app/view/admin/ServerDialog.js
./web/app/view/login/
./web/app/view/login/Register.js
./web/app/view/login/Login.js
./web/app/view/login/RegisterController.js
./web/app/view/login/LoginController.js
./web/app/view/map/
./web/app/view/map/Map.js
./web/app/view/map/MapController.js
./web/app/view/device/
./web/app/view/device/Device.js
./web/app/view/device/DeviceController.js
./web/app/view/device/DeviceDialog.js
./web/app/view/device/DeviceDialogController.js
./web/app/view/main/
./web/app/view/main/MainMobile.js
./web/app/view/main/Main.js
./web/app/view/state/
./web/app/view/state/State.js
./web/app/view/state/StateController.js
./web/app/view/command/
./web/app/view/command/CommandDialogController.js
./web/app/view/command/CommandDialog.js
./web/app/view/report/
./web/app/view/report/Report.js
./web/app/view/report/ReportController.js
./web/app/view/user/
./web/app/view/user/UserDialog.js
./web/app/view/user/User.js
./web/app/view/user/UserController.js
./web/app/view/user/UserDialogController.js
./web/app/LoginManager.js
./web/favicon.ico
./web/locale.js
./tracker-server.jar
./conf/
./conf/wrapper.conf
./conf/traccar.xml
./bin/
./bin/wrapper
./bin/traccar
./data/
./setup.sh
./lib/
./lib/jetty-webapp-9.2.13.v20150730.jar
./lib/jetty-http-9.2.13.v20150730.jar
./lib/jetty-io-9.2.13.v20150730.jar
./lib/javax.json-1.0.4.jar
./lib/jetty-security-9.2.13.v20150730.jar
./lib/mchange-commons-java-0.2.10.jar
./lib/wrapper.jar
./lib/slf4j-simple-1.7.12.jar
./lib/log4j-1.2.17.jar
./lib/libwrapper.so
./lib/c3p0-0.9.5.1.jar
./lib/jetty-util-9.2.13.v20150730.jar
./lib/jetty-xml-9.2.13.v20150730.jar
./lib/jetty-server-9.2.13.v20150730.jar
./lib/slf4j-api-1.7.12.jar
./lib/postgresql-9.4-1201-jdbc41.jar
./lib/mysql-connector-java-5.1.36.jar
./lib/async-http-client-1.9.30.jar
./lib/javax.servlet-api-3.1.0.jar
./lib/h2-1.4.187.jar
./lib/joda-time-2.8.1.jar
./lib/netty-3.10.4.Final.jar
./lib/jetty-servlet-9.2.13.v20150730.jar
CRC: 3526722589
MD5: 5c04e46a6c2fe1f7dabf5a129e9d4a13

Self-extractable archive "traccar.run" successfully created.
updating: traccar.run (deflated 0%)
updating: README.txt (deflated 52%)
Header is 498 lines long

About to compress 11076 KB of data...
Adding files to archive named "traccar.run"...
./
./logs/
./web/
./web/app.js
./web/debug.html
./web/l10n/
./web/l10n/de.js
./web/l10n/en.js
./web/l10n/dk.js
./web/l10n/es.js
./web/l10n/pt.js
./web/l10n/fr.js
./web/l10n/zh.js
./web/l10n/pl.js
./web/l10n/ru.js
./web/l10n/nl.js
./web/l10n/th.js
./web/release.html
./web/app/
./web/app/controller/
./web/app/controller/Root.js
./web/app/Resources.js
./web/app/model/
./web/app/model/Device.js
./web/app/model/Position.js
./web/app/model/User.js
./web/app/model/Command.js
./web/app/model/Parameter.js
./web/app/model/Server.js
./web/app/Application.js
./web/app/ErrorManager.js
./web/app/store/
./web/app/store/TimeUnits.js
./web/app/store/SpeedUnits.js
./web/app/store/CommandTypes.js
./web/app/store/MapTypes.js
./web/app/store/Parameters.js
./web/app/store/DistanceUnits.js
./web/app/store/Users.js
./web/app/store/Positions.js
./web/app/store/LiveData.js
./web/app/store/Languages.js
./web/app/store/Devices.js
./web/app/view/
./web/app/view/admin/
./web/app/view/admin/ServerDialogController.js
./web/app/view/admin/ServerDialog.js
./web/app/view/login/
./web/app/view/login/Register.js
./web/app/view/login/Login.js
./web/app/view/login/RegisterController.js
./web/app/view/login/LoginController.js
./web/app/view/map/
./web/app/view/map/Map.js
./web/app/view/map/MapController.js
./web/app/view/device/
./web/app/view/device/Device.js
./web/app/view/device/DeviceController.js
./web/app/view/device/DeviceDialog.js
./web/app/view/device/DeviceDialogController.js
./web/app/view/main/
./web/app/view/main/MainMobile.js
./web/app/view/main/Main.js
./web/app/view/state/
./web/app/view/state/State.js
./web/app/view/state/StateController.js
./web/app/view/command/
./web/app/view/command/CommandDialogController.js
./web/app/view/command/CommandDialog.js
./web/app/view/report/
./web/app/view/report/Report.js
./web/app/view/report/ReportController.js
./web/app/view/user/
./web/app/view/user/UserDialog.js
./web/app/view/user/User.js
./web/app/view/user/UserController.js
./web/app/view/user/UserDialogController.js
./web/app/LoginManager.js
./web/favicon.ico
./web/locale.js
./tracker-server.jar
./conf/
./conf/wrapper.conf
./conf/traccar.xml
./bin/
./bin/wrapper-linux-armhf-32
./bin/traccar
./bin/wrapper-linux-armel-32
./data/
./setup.sh
./lib/
./lib/jetty-webapp-9.2.13.v20150730.jar
./lib/jetty-http-9.2.13.v20150730.jar
./lib/jetty-io-9.2.13.v20150730.jar
./lib/javax.json-1.0.4.jar
./lib/jetty-security-9.2.13.v20150730.jar
./lib/mchange-commons-java-0.2.10.jar
./lib/wrapper.jar
./lib/slf4j-simple-1.7.12.jar
./lib/log4j-1.2.17.jar
./lib/c3p0-0.9.5.1.jar
./lib/jetty-util-9.2.13.v20150730.jar
./lib/jetty-xml-9.2.13.v20150730.jar
./lib/jetty-server-9.2.13.v20150730.jar
./lib/slf4j-api-1.7.12.jar
./lib/postgresql-9.4-1201-jdbc41.jar
./lib/libwrapper-linux-armel-32.so
./lib/mysql-connector-java-5.1.36.jar
./lib/async-http-client-1.9.30.jar
./lib/javax.servlet-api-3.1.0.jar
./lib/h2-1.4.187.jar
./lib/libwrapper-linux-armhf-32.so
./lib/joda-time-2.8.1.jar
./lib/netty-3.10.4.Final.jar
./lib/jetty-servlet-9.2.13.v20150730.jar
CRC: 2420927879
MD5: b980ff28583bfa15ed0fbd9bb336a621

Self-extractable archive "traccar.run" successfully created.
updating: traccar.run (deflated 0%)
updating: README.txt (deflated 52%)
Header is 498 lines long

About to compress 11364 KB of data...
Adding files to archive named "traccar.run"...
./
./logs/
./web/
./web/app.js
./web/debug.html
./web/l10n/
./web/l10n/de.js
./web/l10n/en.js
./web/l10n/dk.js
./web/l10n/es.js
./web/l10n/pt.js
./web/l10n/fr.js
./web/l10n/zh.js
./web/l10n/pl.js
./web/l10n/ru.js
./web/l10n/nl.js
./web/l10n/th.js
./web/release.html
./web/app/
./web/app/controller/
./web/app/controller/Root.js
./web/app/Resources.js
./web/app/model/
./web/app/model/Device.js
./web/app/model/Position.js
./web/app/model/User.js
./web/app/model/Command.js
./web/app/model/Parameter.js
./web/app/model/Server.js
./web/app/Application.js
./web/app/ErrorManager.js
./web/app/store/
./web/app/store/TimeUnits.js
./web/app/store/SpeedUnits.js
./web/app/store/CommandTypes.js
./web/app/store/MapTypes.js
./web/app/store/Parameters.js
./web/app/store/DistanceUnits.js
./web/app/store/Users.js
./web/app/store/Positions.js
./web/app/store/LiveData.js
./web/app/store/Languages.js
./web/app/store/Devices.js
./web/app/view/
./web/app/view/admin/
./web/app/view/admin/ServerDialogController.js
./web/app/view/admin/ServerDialog.js
./web/app/view/login/
./web/app/view/login/Register.js
./web/app/view/login/Login.js
./web/app/view/login/RegisterController.js
./web/app/view/login/LoginController.js
./web/app/view/map/
./web/app/view/map/Map.js
./web/app/view/map/MapController.js
./web/app/view/device/
./web/app/view/device/Device.js
./web/app/view/device/DeviceController.js
./web/app/view/device/DeviceDialog.js
./web/app/view/device/DeviceDialogController.js
./web/app/view/main/
./web/app/view/main/MainMobile.js
./web/app/view/main/Main.js
./web/app/view/state/
./web/app/view/state/State.js
./web/app/view/state/StateController.js
./web/app/view/command/
./web/app/view/command/CommandDialogController.js
./web/app/view/command/CommandDialog.js
./web/app/view/report/
./web/app/view/report/Report.js
./web/app/view/report/ReportController.js
./web/app/view/user/
./web/app/view/user/UserDialog.js
./web/app/view/user/User.js
./web/app/view/user/UserController.js
./web/app/view/user/UserDialogController.js
./web/app/LoginManager.js
./web/favicon.ico
./web/locale.js
./tracker-server.jar
./conf/
./conf/wrapper.conf
./conf/traccar.xml
./bin/
./bin/wrapper
./bin/traccar
./data/
./setup.sh
./lib/
./lib/jetty-webapp-9.2.13.v20150730.jar
./lib/jetty-http-9.2.13.v20150730.jar
./lib/jetty-io-9.2.13.v20150730.jar
./lib/javax.json-1.0.4.jar
./lib/jetty-security-9.2.13.v20150730.jar
./lib/mchange-commons-java-0.2.10.jar
./lib/wrapper.jar
./lib/slf4j-simple-1.7.12.jar
./lib/log4j-1.2.17.jar
./lib/c3p0-0.9.5.1.jar
./lib/jetty-util-9.2.13.v20150730.jar
./lib/jetty-xml-9.2.13.v20150730.jar
./lib/jetty-server-9.2.13.v20150730.jar
./lib/slf4j-api-1.7.12.jar
./lib/postgresql-9.4-1201-jdbc41.jar
./lib/mysql-connector-java-5.1.36.jar
./lib/async-http-client-1.9.30.jar
./lib/libwrapper.jnilib
./lib/javax.servlet-api-3.1.0.jar
./lib/h2-1.4.187.jar
./lib/joda-time-2.8.1.jar
./lib/netty-3.10.4.Final.jar
./lib/jetty-servlet-9.2.13.v20150730.jar
CRC: 3249809047
MD5: cb42756d416033bf0aad5e846fc2ab5c

Self-extractable archive "traccar.run" successfully created.
updating: traccar.run (deflated 0%)
updating: README.txt (deflated 52%)
updating: conf/ (stored 0%)
updating: conf/traccar.xml (deflated 80%)
updating: data/ (stored 0%)
updating: lib/ (stored 0%)
updating: lib/jetty-webapp-9.2.13.v20150730.jar (deflated 6%)
updating: lib/jetty-http-9.2.13.v20150730.jar (deflated 6%)
updating: lib/jetty-io-9.2.13.v20150730.jar (deflated 10%)
updating: lib/javax.json-1.0.4.jar (deflated 13%)
updating: lib/jetty-security-9.2.13.v20150730.jar (deflated 9%)
updating: lib/mchange-commons-java-0.2.10.jar (deflated 14%)
updating: lib/slf4j-simple-1.7.12.jar (deflated 14%)
updating: lib/log4j-1.2.17.jar (deflated 10%)
updating: lib/c3p0-0.9.5.1.jar (deflated 7%)
updating: lib/jetty-util-9.2.13.v20150730.jar (deflated 7%)
updating: lib/jetty-xml-9.2.13.v20150730.jar (deflated 6%)
updating: lib/jetty-server-9.2.13.v20150730.jar (deflated 6%)
updating: lib/slf4j-api-1.7.12.jar (deflated 13%)
updating: lib/postgresql-9.4-1201-jdbc41.jar (deflated 6%)
updating: lib/mysql-connector-java-5.1.36.jar (deflated 5%)
updating: lib/async-http-client-1.9.30.jar (deflated 11%)
updating: lib/javax.servlet-api-3.1.0.jar (deflated 12%)
updating: lib/h2-1.4.187.jar (deflated 4%)
updating: lib/joda-time-2.8.1.jar (deflated 18%)
updating: lib/netty-3.10.4.Final.jar (deflated 11%)
updating: lib/jetty-servlet-9.2.13.v20150730.jar (deflated 6%)
updating: logs/ (stored 0%)
updating: README.txt (deflated 52%)
updating: tracker-server.jar (deflated 11%)
updating: web/ (stored 0%)
updating: web/app.js (deflated 39%)
updating: web/debug.html (deflated 57%)
updating: web/l10n/ (stored 0%)
updating: web/l10n/de.js (deflated 62%)
updating: web/l10n/en.js (deflated 66%)
updating: web/l10n/dk.js (deflated 62%)
updating: web/l10n/es.js (deflated 63%)
updating: web/l10n/pt.js (deflated 63%)
updating: web/l10n/fr.js (deflated 63%)
updating: web/l10n/zh.js (deflated 55%)
updating: web/l10n/pl.js (deflated 60%)
updating: web/l10n/ru.js (deflated 61%)
updating: web/l10n/nl.js (deflated 63%)
updating: web/l10n/th.js (deflated 66%)
updating: web/release.html (deflated 56%)
updating: web/app/ (stored 0%)
updating: web/app/controller/ (stored 0%)
updating: web/app/controller/Root.js (deflated 59%)
updating: web/app/Resources.js (deflated 47%)
updating: web/app/model/ (stored 0%)
updating: web/app/model/Device.js (deflated 42%)
updating: web/app/model/Position.js (deflated 57%)
updating: web/app/model/User.js (deflated 56%)
updating: web/app/model/Command.js (deflated 41%)
updating: web/app/model/Parameter.js (deflated 42%)
updating: web/app/model/Server.js (deflated 53%)
updating: web/app/Application.js (deflated 56%)
updating: web/app/ErrorManager.js (deflated 55%)
updating: web/app/store/ (stored 0%)
updating: web/app/store/TimeUnits.js (deflated 44%)
updating: web/app/store/SpeedUnits.js (deflated 49%)
updating: web/app/store/CommandTypes.js (deflated 48%)
updating: web/app/store/MapTypes.js (deflated 44%)
updating: web/app/store/Parameters.js (deflated 39%)
updating: web/app/store/DistanceUnits.js (deflated 41%)
updating: web/app/store/Users.js (deflated 49%)
updating: web/app/store/Positions.js (deflated 43%)
updating: web/app/store/LiveData.js (deflated 38%)
updating: web/app/store/Languages.js (deflated 47%)
updating: web/app/store/Devices.js (deflated 50%)
updating: web/app/view/ (stored 0%)
updating: web/app/view/admin/ (stored 0%)
updating: web/app/view/admin/ServerDialogController.js (deflated 46%)
updating: web/app/view/admin/ServerDialog.js (deflated 65%)
updating: web/app/view/login/ (stored 0%)
updating: web/app/view/login/Register.js (deflated 57%)
updating: web/app/view/login/Login.js (deflated 61%)
updating: web/app/view/login/RegisterController.js (deflated 48%)
updating: web/app/view/login/LoginController.js (deflated 61%)
updating: web/app/view/map/ (stored 0%)
updating: web/app/view/map/Map.js (deflated 62%)
updating: web/app/view/map/MapController.js (deflated 73%)
updating: web/app/view/device/ (stored 0%)
updating: web/app/view/device/Device.js (deflated 66%)
updating: web/app/view/device/DeviceController.js (deflated 71%)
updating: web/app/view/device/DeviceDialog.js (deflated 53%)
updating: web/app/view/device/DeviceDialogController.js (deflated 51%)
updating: web/app/view/main/ (stored 0%)
updating: web/app/view/main/MainMobile.js (deflated 48%)
updating: web/app/view/main/Main.js (deflated 57%)
updating: web/app/view/state/ (stored 0%)
updating: web/app/view/state/State.js (deflated 46%)
updating: web/app/view/state/StateController.js (deflated 68%)
updating: web/app/view/command/ (stored 0%)
updating: web/app/view/command/CommandDialogController.js (deflated 54%)
updating: web/app/view/command/CommandDialog.js (deflated 58%)
updating: web/app/view/report/ (stored 0%)
updating: web/app/view/report/Report.js (deflated 66%)
updating: web/app/view/report/ReportController.js (deflated 62%)
updating: web/app/view/user/ (stored 0%)
updating: web/app/view/user/UserDialog.js (deflated 68%)
updating: web/app/view/user/User.js (deflated 54%)
updating: web/app/view/user/UserController.js (deflated 62%)
updating: web/app/view/user/UserDialogController.js (deflated 54%)
updating: web/app/LoginManager.js (deflated 73%)
updating: web/favicon.ico (deflated 59%)
updating: web/locale.js (deflated 49%)
rm: cannot remove ‘../web/app.min.js’: No such file or directory </pre>

**Comment by tananaev** [comment]
You need to have ExtJS and Sencha CMD installed to compile web interface.

Check `tools/minify.sh` script for more information on what it expects.
