### ISSUE TITLE
Send instructions error "The device is not registered on the server"

### ISSUE THREAD

**Issue by he-jialin** [traccar/traccar#1362]
Hey Anton,I tried to website demo send instructions is an error is as follows: "The device is not registered on the server" ,  I try to use Intellj IDEA configuration traccar but always fails -"{Error running traccar:GWT Fecet is not configured for module 'traccar' } and {Error running traccar:No GWT modules found is 'traccar'} ",My computer system is Linux version, you are MAC configured Course, difference is very big,Do you can write a Windows and Linux Intellj IDEA configured Course?  thank you! My email is 2722539@qq.com

**Comment by tananaev** [comment]
"The device is not registered on the server" means that your device didn't send any data. What is the device id and port?

As for Intellij, it looks like you are doing something wrong. Traccar is not a GWT project.

I am using Linux as well.

**Comment by Galin96** [comment]
@tananaev     I fill in the data on the android app is Device id = IMEI and port = 5055, This is wrong?
Thanks to reply me.

**Comment by tananaev** [comment]
That is correct if you are using the latest version.

**Comment by Galin96** [comment]
@tananaev Is the latest ,From the website to download the app.

**Comment by tananaev** [comment]
What do you see on the status screen on the app? Any location updates there or errors?

Also, if you want me to check on the server side, I need to know your account name or device id.

**Comment by Galin96** [comment]
@tananaev My account name is 2722539@qq.com and device ID is: 863396022064131

**Comment by tananaev** [comment]
I don't see any messages from your device in the logs. What do you see on the status screen in the app?

**Comment by Galin96** [comment]
@tananaev My application data is the device ID is: 863396022064131, server address: demo.traccar.org, server port: 5055, frequency: 300. The state is open .

**Comment by tananaev** [comment]
In the app there is a status screen (menu -> status) which shows information about location updates and errors.

**Comment by Galin96** [comment]
@tananaev Please find I send you an email containing pictures

**Comment by tananaev** [comment]
You can find my email address in profile, but your should be able to attach photos here as well.

**Comment by Galin96** [comment]
@tananaev android application send data status :send failed

**Comment by tananaev** [comment]
It means that your device can't connect to the server.
