### ISSUE TITLE
Plugin for handle Meitrack TC68 Obd data?

### ISSUE THREAD

**Issue by hamdta** [traccar/traccar#1381]
Hi
Is there any chance to add a plugin for handle the TC68 OBD data and integrated them o Traccar software?

Thanks in advance
Paulo

**Comment by tananaev** [comment]
What do you mean by plugin?

If OBD data is sent along with GPS info, it should be possible to parse it. If not, then you need to wait for the next release where I plan to implement support for messages without GPS info.

**Comment by hamdta** [comment]
Hi Anton Tananaev!
Thanks for the answer, in fact the OBD data was sent along( enbebed) with
Gps info stream, so I need some code for treat the OBD data and put them
on  your Traccar webserver  data base , and after was possible read / show
them.

Thanks  in advance
Paulo

Em 28/08/2015 00:49, "Anton Tananaev" <notifications@github.com> escreveu:
>
> What do you mean by plugin?
>
> If OBD data is sent along with GPS info, it should be possible to parse
it. If not, then you need to wait for the next release where I plan to
implement support for messages without GPS info.

**Comment by tananaev** [comment]
I need protocol documentation and HEX messages from your device to implement decoding.

**Comment by hamdta** [comment]
OK I send them later .The Hex message only when I set up the server...

Thanks
Paulo
Em 29/08/2015 01:07, "Anton Tananaev" <notifications@github.com> escreveu:

**Comment by hamdta** [comment]
Here the protocol  in attach ...I end my holidays after I set the server ...

Thanks
Paulo
Em 29/08/2015 09:54, "Paulo Hamdta" <hamdta@gmail.com> escreveu:

**Comment by tananaev** [comment]
You are sending emails to GitHub and it doesn't accept attachments.

**Comment by hamdta** [comment]
So what I can do for send the files?
Em 29/08/2015 10:04, "Anton Tananaev" <notifications@github.com> escreveu:

**Comment by tananaev** [comment]
You can either upload it somewhere or send me to email (address in profile).

**Comment by tananaev** [comment]
It's a standard Meitrack protocol. Can you please point out where I can find information about OBD data there.

**Comment by hamdta** [comment]
Hi Anton!

I found this wiki on this link:
https://en.wikipedia.org/wiki/On-board_diagnostics#OBD-II,i never test
(yet) or analyse this information for confirm if right or wrong,but i could
with some help...

Thanks in advance.
Paulo

2015-08-29 23:42 GMT+01:00 Anton Tananaev <notifications@github.com>:

**Comment by tananaev** [comment]
I know what OBD is. I just don't see any information about OBD in the document that you sent earlier.

**Comment by hamdta** [comment]
Hi Anton!
Sorry but a don't know what you mean with " I don't see any information
about the OBD in the document"
Please specific what information you want /need about the OBD?

Regards
Paulo
Em 31/08/2015 22:36, "Anton Tananaev" <notifications@github.com> escreveu:

**Comment by tananaev** [comment]
As far as I can tell your device is using standard Meitrack protocol, so it will work on port 5020.

If your device can send OBD data and you want to see that extra information in Traccar, I need protocol documentation that describes the format for that extra data. The one that you provided doesn't. Are you sure your device can send OBD info?
