### ISSUE TITLE
Totem at07

### ISSUE THREAD

**Issue by sdserrano** [traccar/traccar#1385]
Hello, thank you for your support. I have a new device with the below given string.

<pre>$$0108AA864244026063437|1A0000001401010101014111000027BA0E57003100000000.000000000000.0000N00000.0000E048156</pre>

I bought this device from totem . The device is at07 seems not yet to existing protocols. I would like to know how to add a  protocol device.

**Comment by tananaev** [comment]
It looks like GPS info is missing, so the message is ignored by Traccar.

**Comment by sdserrano** [comment]
Thanks for the reply tananaev! It is an example of a protocol, but the device sends information very well on another platform. 
There is some information on how to modify an existing protocol?
Thanks!

**Comment by tananaev** [comment]
As I said, the GPS info is empty. Possibly device didn't have a GPS file at that point. Please provide an example with GPS info present.

**Comment by sdserrano** [comment]
$$0108AA864244026063999|500440001509071845394212000052093852112903600000.700000000008.4856S07829.5025W048554

This is the gps info complete.

**Comment by sdserrano** [comment]
This is the url for the protocol: https://www.google.com.ec/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CBwQFjAAahUKEwj5hvT_0eXHAhWL1x4KHSWWCqA&url=http%3A%2F%2Ff01.s.alicdn.com%2Fkf%2FHLB1nsYmHFXXXXcaaXXX.PRXFXXX4.pdf&usg=AFQjCNF8O5aMCOwCbWMeBiJW7ulqBHoUkA&sig2=cIHK24UHneKCytB3mwdC0g&bvm=bv.102022582,d.dmo

**Comment by tananaev** [comment]
I have checked the documentation and the protocol is quite different from the Totem. I guess we need to implement it as a separate protocol as it requires different frame decoder and message format is different as well.

**Comment by sdserrano** [comment]
Thank you very much for answer me. Can you give me some instruction on how to implement a new FrameDecoder?

**Comment by tananaev** [comment]
Here is an example:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/TotemFrameDecoder.java

**Comment by xeeshan-ahmad** [comment]
@tananaev  is there any update in Traccar for AT07 from Totemt?

**Comment by tananaev** [comment]
It should probably work. Make sure you are using latest code. If it still doesn't work provide logs.

**Comment by xeeshan-ahmad** [comment]
$$0108AA865794036523258|188060001805131121493907000029DD7107062119400001.800000003147.8965N07415.1872E005654

**Comment by tananaev** [comment]
Please point where you found that string in your log.

**Comment by xeeshan-ahmad** [comment]
Device is in configuration mode and this string is in configuration manager.

**Comment by tananaev** [comment]
Obviously when I asked for logs I'm expecting logs with data from your device.

**Comment by xeeshan-ahmad** [comment]
I uploaded device log file here
http://linjahsandghana.com/20180513.txt

**Comment by tananaev** [comment]
Are you serious? I need SERVER logs with data from your device.

**Comment by xeeshan-ahmad** [comment]
this is server log file!
http://linjahsandghana.com/tracker-server.txt

are you looking for this one?

**Comment by tananaev** [comment]
OK, not show me data from your Totem device there. Exact line number please.

**Comment by xeeshan-ahmad** [comment]
I can find logs of my mobile when i use your android client app, but i couldn't find AT07 device logs

**Comment by tananaev** [comment]
That's exactly my point. Your device doesn't send anything to the server.
