### ISSUE TITLE
Decode H02 protocol to help location with GSM

### ISSUE THREAD

**Issue by jdariasl80** [traccar/traccar#1390]
Hi,

This issue https://github.com/tananaev/traccar/issues/1173 was very helpful to me. But I just want to know if I can find more information about a gps tracker protocol.

I got this data: (Clearly h02 protocol and I can decode as the issue tells)
*HQ,1505004264,LINK,045017,70,0,94,0,0,020915,FFFFFFFF#

But I also I get this info:
*HQ,1505004264,NBR,043042,732,103,255,4,51511,20350,135,51509,10375,132,51303,20414,129,51511,20166,128,020915,FFFFFFFF#
This is the location of the GSM cells
With this tool http://www.open-electronics.org/celltrack/ I was able to find a relative accurate position of my gps, but only changing the order of the cells (previous knowing my location) in the following order

732, -mcc
103, -mnc
1,5, -> don't know what is this.
51509,30375,136, -> This should be the main cell. but is not the first data of the string
51511,20350,134,  -> This should be the first neighbor cell.
51510,10009,130,  -> This should be the second neighbor cell.
51510,20193,138,  -> This should be the third neighbor cell.
51510,10228,131,  -> This should be the four neighbor cell.

does any one have any idea of how to find the main cell? Also does any one know what is the third number of the sequences (136, 134, 130, 138 and 131)?

I'll thank any help.

Best regards,
George.

**Comment by tananaev** [comment]
I'm guessing that it's a signal strength.
