### ISSUE TITLE
Help, decoding gt02a gps trackerr

### ISSUE THREAD

**Issue by draganjovanovich** [traccar/traccar#1394]
I setup gt02a device and set to 5002 port but it shows wrong position and time iz 2 dayss in past,here is hex

283032373034333432353037334252303031353039303241343435382e393538344e30323030392e35393337453030302e373230303732363132302e333030303030303030304c303030303030303029

Thanks.

**Comment by shorty131** [comment]
Solved , after 20 minutes device start  sending correct position and time... port 5002

**Comment by tananaev** [comment]
Cold GPS fix can take 15 or more minutes.
