### ISSUE TITLE
Server registration issue 

### ISSUE THREAD

**Issue by shahanepratap18** [traccar/traccar#1399]
Hello All,
my tracecar server started but I'm can not able to register device on server I'm use TK116 device please help me about this problem

**Comment by tananaev** [comment]
Well, you need to provide more details.

1. Are you sure device port is visible from Internet?
2. Check `tracker-server.log` file for HEX messages.

**Comment by shahanepratap18** [comment]
1 ) yes port open from firewall 
 2 ) in tracker-server.log file hex output as follows 


474554202f20485454502f312e310d0a486f73743a206c6f63616c686f73743a353036340d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a43616368652d436f6e74726f6c3a206d61782d6167653d300d0a4163636570743a20746578742f68746d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c6170706c69636174696f6e2f786d6c3b713d302e392c696d6167652f776562702c2a2f2a3b713d302e380d0a557067726164652d496e7365637572652d52657175657374733a20310d0a557365722d4167656e743a204d6f7a696c6c612f352e30202857696e646f7773204e5420362e3129204170706c655765624b69742f3533372e333620284b48544d4c2c206c696b65204765636b6f29204368726f6d652f34352e302e323435342e3835205361666172692f3533372e33360d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174652c20736463680d0a4163636570742d4c616e67756167653a20656e2d55532c656e3b713d302e380d0a0d0a

**Comment by tananaev** [comment]
1. Please check here: http://www.tananaev.com/port.html
2. It's from your browser. If there nothing else, it means server didn't get any data from the device.

**Comment by shahanepratap18** [comment]
Hello
I'm open both port 8082 and 5064 from firewall but did not get any data
in tracker-server.log

On Wed, Sep 9, 2015 at 4:16 PM, Anton Tananaev <notifications@github.com>
wrote:

>
>    1. Please check here: http://www.tananaev.com/port.html
>    2. It's from your browser. If there nothing else, it means server
>    didn't get any data from the device.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1399#issuecomment-138870582>.
>



-- 

*Regards*


*Pratap Shahane *

*LogicalDNA* <http://logicaldna/>* IT Solutions Private Limited | *
*www.logicaldna.com* <http://www.logicaldna.com/>
*Cell: +91 9011057893 | Phone: +91-20-24225707 x-17 *

**Comment by shahanepratap18** [comment]
please help me I'm very tired with this problem

**Comment by tananaev** [comment]
Have you checked if the ports are visible using the link? The fact that you open them on the firewall doesn't mean that everything else is configured correctly (e.g. router).

**Comment by aliz701** [comment]
Hello, I have a qbit mini tracker, what software can I use to set it up?
