### ISSUE TITLE
Running Traccar On Azure as a Website instead of a VM

### ISSUE THREAD

**Issue by georgend** [traccar/traccar#1400]
Hi,

I have a scenario to aid in major cost reductions. I have configured my traccar to use Microsoft SQL Server (inside a vm), I want to move it to SQL Azure. I want to abandon Virtual Machines completely and move to fully Azure managed Services. So Is it possible to run the traccar Windows Services as an Azure Web Job or some other batch like/background service. In the long run this would become cheaper, and very scalable, without us doing the heavy lifting.

Is this feasible?

**Comment by tananaev** [comment]
It should be possible to use SQL Azure as it's basically a MS SQL instance, but I don't know about Web Job.

**Comment by slax0r** [comment]
Just to chime in a little bit.  Most of Traccar itself can run as a web app under Azure web apps, however you are stuck.  The comm services that receive data from GPS units via non-HTTP protocols need a regular network environment that can open TCP and UDP servers to receive gps packets to operate.
