### ISSUE TITLE
Azure VM - pop-up saying Not found

### ISSUE THREAD

**Issue by HarshaNyshadham** [traccar/traccar#1405]
Hello,

We are trying to host traccar on Azure VM, we did the following steps:

1) Installed Ubuntu, Java and LAMP on the VM.
2) Started the deamons for Traccar.

when trying to connect to the server, http://fleettrack.cloudapp.net (our dns), we get the following error:

![11997913_10206672515624360_985757078_n](https://cloud.githubusercontent.com/assets/4297602/9829636/cdca2906-58da-11e5-8b88-e773b92efdb9.jpg)

When we try the port along with dns -> http://fleettrack.cloudapp.net:8082, the page times out.

Any help is appreciated, thanks!!!

**Comment by tananaev** [comment]
How did you install Traccar? Why is it going through Apache? Have you set up Apache as a proxy to Traccar server?

**Comment by HarshaNyshadham** [comment]
Ok. now we tried without Apache2 server. This is how we installed it!


sudo apt-get install default-jdk
wget https://github.com/tananaev/traccar/releases/download/v3.1/traccar-linux-64-3.1.zip

sudo apt-get install unzip
unzip traccar-linux-64-3.1.zip
sudo ./traccar.run


viki@shuttletrack:~$ unzip traccar-linux-64-3.1.zip
Archive:  traccar-linux-64-3.1.zip
  inflating: traccar.run
  inflating: README.txt
viki@shuttletrack:~$ ls
README.txt  traccar-linux-64-3.1.zip  traccar.run
viki@shuttletrack:~$ sudo ./traccar.run
Verifying archive integrity... All good.
Uncompressing traccar  100%
Detected Ubuntu or Debian:
Installing the traccar daemon using init.d..
viki@shuttletrack:~$ sudo /opt/traccar/bin/traccar start
Starting traccar...
Waiting for traccar......
running: PID:8883
viki@shuttletrack:~$

afte doing this we try :   
http://shuttletrack.cloudapp.net:8883/

**Comment by tananaev** [comment]
Everything seems fine except the URL. Traccar web interface is running on port 8082 by default.

**Comment by HarshaNyshadham** [comment]
Oh. even 8082 timesout
http://shuttletrack.cloudapp.net:8082/

**Comment by tananaev** [comment]
It works for me.

**Comment by HarshaNyshadham** [comment]
Yup! now it works! We forgot to open the port 8082. Silly! Thanks for the help!

**Comment by HarshaNyshadham** [comment]
Thanks for the help, How do i clear up the internal DB. I am not able to register the same device with different logins, throws an DB constraint violation. 

Also we are not able to locate our device on the web.
This is what we did:

1) Register our self on the web and logged into the web.
2) Download the client on Android, setup up the server name(above dns name) and port (8082)
3) Register/Add the device on the web. We were not able to view our location. We change the port on client back to 5055 and tried again still not able to locate our device on web.

What are we missing? Please advise.

**Comment by tananaev** [comment]
Sounds correct. Does phone report location? Check status screen and server logs (tracker-server.log).
