### ISSUE TITLE
Protocol TK100

### ISSUE THREAD

**Issue by ffigueroa** [traccar/traccar#1407]
I purchased a GPS Tracker from Aliexpress and the Protocol of the "GT06" is TK100 :-1: 

https://www.dropbox.com/s/knsijjbm4b67omf/TK100%2B%E8%8B%B1%E6%96%87%E9%80%9A%E8%AE%AF%E5%8D%8F%E8%AE%AE%20%281%29.pdf?dl=0

If somebody can help me to implement that protocol, I'll be happy forever xD

**Comment by tananaev** [comment]
Most likely it's using one of the protocol from the following page:

https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/
