### ISSUE TITLE
Queclink devices

### ISSUE THREAD

**Issue by warlockopy** [traccar/traccar#1408]
Hello, is the protocol implementation ready for sending commands to the gv55 queclink devices?
can we set an output via udp messages?

**Comment by tananaev** [comment]
There are two protocols in Traccar for Queclink devices:

1. GL100 - older one. Supports only TCP and doesn't support commands.
2. GL200 - newer one (most devices use this one). Supports both UDP and TCP channels, but unfortunately it doesn't currently support commands.

**Comment by warlockopy** [comment]
hello, when do you think commands will be available, or ele, can you give me a quick guide were I find the code for this protocol to implement and try. i can code it.

**Comment by tananaev** [comment]
This is the GL200 decoder:
https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gl200ProtocolDecoder.java

To support commands you need to implement an encoder. For examples you can take a look at GPS103 one:
https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gps103ProtocolEncoder.java

Also you need to declare supported commands in the protocol class:
https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gl200Protocol.java

For example you can see GPS protocol again:
https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gps103Protocol.java

**Comment by daipayan-matrix** [comment]
I have a query, I had installed the Driver in my laptop. Added the Server FTP path and allowed the port in the server. But problem is no file is generated in the provided FTP. Am tried to search a lot but no where I find any sort of files with GPS data.

Am using GL50X @Track Air Interface Protocol R3.00

Anyone please guide me!
