### ISSUE TITLE
Making my own server

### ISSUE THREAD

**Issue by pgarin** [traccar/traccar#1423]
Hi, I downloaded traccar client from iTunes, and i want to make my own server (maybe a servlet). It's possible to make it?.
I make some code (socket listening from a port), and the clients sends a GET request, maybe parsing the HTTP GET request string it's enough?

Thanks!

**Comment by tananaev** [comment]
If you don't want to use Traccar server, it should be pretty easy to create a Servlet that would handle Traccar Client messages. The app expects HTTP OK in response and all GPS data is in URL parameters, so it should be easy to parse.

**Comment by pgarin** [comment]
Great! Thanks!
