### ISSUE TITLE
Custom the traccar server 

### ISSUE THREAD

**Issue by jcroman-itch** [traccar/traccar#1427]
Hello tananaev, thanks for develop the traccar system, it had been very useful.
I installed the traccar server in my computer with windows 7 and it's run very well but i want to custom the user interface and database connection.
Is it possible make these changes? 

I downloaded traccar-master.zip  file but it seems it's a maven proyect and i don't know where i should make the changes.

Please help.

**Comment by tananaev** [comment]
Database connection can be changed in the config file (https://www.traccar.org/configuration-file/).

User interface files are in the `web` directory:

https://github.com/tananaev/traccar/tree/master/web

**Comment by SebastEnn** [comment]
Question answered. Issue can be closed.
