### ISSUE TITLE
Determine Protocol Type

### ISSUE THREAD

**Issue by kuldiplive** [traccar/traccar#1429]
Hi!

Can an one make out which device protocol it runs or device manufacturer  ? 

[2015-09-25 02:37:03] - CLIENT TO SERVER
ASCII: PT;863771024591853;111;20150925;02:36:47;404,98,21072,05201;+20.533678;+073.181515;000.000;22.380;6;1;0021E653;12.65;3.900;000000;1;0;1;0001
HEX: 50543B3836333737313032343539313835333B3131313B32303135303932353B30323A33363A34373B3430342C39382C32313037322C30353230313B2B32302E3533333637383B2B3037332E3138313531353B3030302E3030303B32322E3338303B363B313B30303231453635333B31322E36353B332E3930303B3030303030303B313B303B313B30303031

Thanks !

Kuldip

**Comment by tananaev** [comment]
It looks similar to SunTech protocol, but there are some differences.

**Comment by kuldiplive** [comment]
received below data:

[2015-09-26 09:00:17] - CLIENT TO SERVER ASCII: 
PTH;863771024591853;111;20150926;08:59:17;404,98,55572,05201;+20.533730;+073.181558;000.000;24.720;0;0;00224CCC;12.67;4.000;000000;1;0;1;0006 
HEX: 
5054483B3836333737313032343539313835333B3131313B32303135303932363B30383A35393A31373B3430342C39382C35353537322C30353230313B2B32302E3533333733303B2B3037332E3138313535383B3030302E3030303B32342E3732303B303B303B30303232344343433B31322E36373B342E3030303B3030303030303B313B303B313B30303036 
[2015-09-26 09:00:39] - CLIENT TO SERVER ASCII: 
PT;863771024591853;111;20150926;09:00:20;404,98,55572,05201;+20.533796;+073.181553;000.000;120.99;7;1;00224CCC;12.67;4.000;000000;1;0;1;0007 
HEX: 
50543B3836333737313032343539313835333B3131313B32303135303932363B30393A30303A32303B3430342C39382C35353537322C30353230313B2B32302E3533333739363B2B3037332E3138313535333B3030302E3030303B3132302E39393B373B313B30303232344343433B31322E36373B342E3030303B3030303030303B313B303B313B30303037

------ Original Message ------

**Comment by caluca20** [comment]
Hello friends, please , could you help me with the problem , I bought a tracker AL- 900E , which configures the port 5058 , but does not work , please help me .

**Comment by tananaev** [comment]
@caluca20, you should create a new thread and provide all the information there (e.g. server log).
