### ISSUE TITLE
Teltonika Protocol

### ISSUE THREAD

**Issue by xblack79** [traccar/traccar#143]
Can you please add Inputs on Teltonika protocol???

**Comment by geduxas** [comment]
hello, it is possible to implement full teltonika protocol ? it is now open 
https://wiki.teltonika.lt/view/FMB_AVL_ID

**Comment by tananaev** [comment]
@geduxas 

1. That's not protocol. It's just ids.
2. Teltonika protocol is already implemented. For many years it's been available.
3. Please never comment on old closed threads.

**Comment by geduxas** [comment]
Sorry for that :) just thouht i will post it somwhere about AVL ID's.. i see that there is only basic list, i haveade some changes for my local version, an would like to get all avl id's in official releases..
