### ISSUE TITLE
How to publish traccar on WEB

### ISSUE THREAD

**Issue by andrealansp** [traccar/traccar#1431]
Gentlemen, I managed to run the web traccar on my server but would like to use the web client at: teste.autointacto.com.br. I have found no documentation about it. can you help me ?

**Comment by tananaev** [comment]
Do you mean you want to install it on hosting? You need a VPS to host Traccar server.

**Comment by andrealansp** [comment]
Thanks, Tananaev !

**Comment by younus93** [comment]
Is there a step by step guide on how to install to a VPS?
After downloading and extracting the linux zip, when running the ./traccar.run file, I'm getting a permission denied error. Despite running it as sudo.

**Comment by tananaev** [comment]
@younus93, are you using CentOS on your VPS? I have heard about this issue a few times (e.g. #101). I will try to fix it for next release, but for now you have to extract files manually and run setup shell script.

**Comment by younus93** [comment]
I'm using Ubuntu 12.02 LTS on VPS. Could you please tell me where to find the files to extract and run shell script?

**Comment by tananaev** [comment]
Traccar installer is made using makeself (http://stephanepeter.com/makeself/). You can use command line arguments to extract files and then run `setup.sh` manually.

**Comment by superservidor** [comment]
You can buy a good VPS server ( 1 x 2.4 Ghz CPU, 1GB Ram, 40 GB Storage, 1 Terabyte monthly Transfer) starting at EUR 0.99 by month at http://www.time4vps.eu/aff.php?aff=181 . If you buy this VPS server I can give you the Traccar server already installed on it using Ubuntu 14.04. IF you are interested please send me an e-mail.

**Comment by tananaev** [comment]
@superservidor, please stop spamming with your links in all threads.

**Comment by superservidor** [comment]
OK, sorry, I only wanted to help. !!!

**Comment by tananaev** [comment]
It makes sense if your message is relevant to the topic and the topic is recent. This one is 3 months old, so it just spam.

**Comment by superservidor** [comment]
OK, Understood. In this case the published info is relevant for the user, but it was posted out-of-date. I will take care of if. Tks.
