### ISSUE TITLE
New Traccar

### ISSUE THREAD

**Issue by wagnerdracha** [traccar/traccar#1436]
Hi, 

The new traccar send command to devices?

thank's

**Comment by tananaev** [comment]
Yes, starting from version 3.1 Traccar supports commands. Support is limited. For more info see following blog post:

https://www.traccar.org/blog/traccar-3-1/

**Comment by wagnerdracha** [comment]
Ohhh good!

To record the commands sent by Traccar, I need only change the traccar.xml?

**Comment by tananaev** [comment]
Commands are not recorded anywhere.

**Comment by wagnerdracha** [comment]
Hi, other question. The traccar receive the position and save in database with this sql:

	<entry key='database.insertPosition'>
        INSERT INTO position (deviceId, protocol, serverTime, deviceTime, fixTime, valid, latitude, longitude, altitude, speed, course, address, other)
        VALUES (:deviceId, :protocol, CURRENT_TIMESTAMP(), :time, :time, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :other);
    </entry>

But this SQL don't save the uniqueId. So, how i can save the uniqueId?

thank's

**Comment by tananaev** [comment]
Why do you need to save `uniqueId`? It should already be in the `device` table.

**Comment by wagnerdracha** [comment]
Because, for example, i have 26,486,266 positions (4.5 GB), and i have client A and client B. Now, think the Client A making a position report and MySql (in my case) having to separate all this data. It will be very time consuming. So I thought to separate for each client a database with the positions and characteristics of each, and a master database for the system.

Thank you for your attention and I apologize for any errors in my English.

**Comment by tananaev** [comment]
It doesn't explain why you can't take unique ids from the other table.

**Comment by wagnerdracha** [comment]
So, in the database of system, I just let the system settings, customer accounts, customer devices, users and customers. And in another database, it left only the position data. Only for me to find what is the bank that I will record the positions, I need to know the customer, and I research the customer's database by uniqueId.

You understand? If you have any suggestion, I thank you.

Thank you

![sem titulo](https://cloud.githubusercontent.com/assets/13226998/10413541/68952bde-6f83-11e5-99b0-5e61536ff0c8.jpg)

**Comment by tananaev** [comment]
Yes, but you can just use `deviceId` for the same purpose.
