### ISSUE TITLE
Ruptela device configuration

### ISSUE THREAD

**Issue by TrackerT** [traccar/traccar#1441]
Hello, 

I am trying to configure a device to send data to the demo account. I have used the IP 104.43.219.242 and also the domain demo.traccar.org and port 5046 but is not working. I have used UDP protocol. Any ideea what is not working?

Thanks

**Comment by tananaev** [comment]
Currently Traccar supports only TCP communication for Ruptela devices.

**Comment by perticas** [comment]
Sorry. My mistake. I have used TCP

**Comment by tananaev** [comment]
The port was closed. Please try again now.

**Comment by perticas** [comment]
It is still not working

**Comment by tananaev** [comment]
I don't see any messages on port 5046.

**Comment by perticas** [comment]
Hy. Now i can see the device. But only one position of him. I cannot read nothing from history. Also where can i see at wich hour did he sent that position? Tks

**Comment by perticas** [comment]
I have found the problem. It was in configuration. Thank you

**Comment by tananaev** [comment]
Let me know if you have any other issues or questions.

**Comment by perticas** [comment]
Hello. I am trying to connect and get data through API. Could you please tell me which is the compete sentence to login and wich to get data?

Thank you

**Comment by tananaev** [comment]
You can find some details about API here:

https://www.traccar.org/traccar-api/

**Comment by perticas** [comment]
Sorry. I am new at this. i saw them but i dont know the exact sentence that i have to write.tks

**Comment by tananaev** [comment]
What do you mean by sentence?

**Comment by perticas** [comment]
I mean http://.....

**Comment by tananaev** [comment]
For example for login (assuming your server is running locally):

<pre>http://localhost:8082/api/login</pre>

**Comment by perticas** [comment]
I am getting {"success":false}

But shouldnt i have something like  http://localhost:8082/api/login/username,password?

**Comment by tananaev** [comment]
You need to provide `email` and `password` parameters. Please read the documentation page that I pointed out earlier.

**Comment by perticas** [comment]
Hello, Regarding the API: Am I right if I think that the /api/async call doesn't need any parameters and it returns all of the "new" coordinates, that we haven't received yet?

**Comment by tananaev** [comment]
Correct. It returns all updates for the current user.

**Comment by perticas** [comment]
Hy. Can i know from somewhere if car engine is on or off? can i rename lo2, lo3, lo4 , and other parameters?

**Comment by vitalidze** [comment]
FYI, my web UI mod have a function to re-name these parameters (called sensors), find more info [here](http://traccar.litvak.su/features/sensors.html). Also it is possible to define 'custom intervals' so you can change the displayed value too.

**Comment by perticas** [comment]
tks. but i cannot find those settings. Any ideea where they are?

**Comment by vitalidze** [comment]
It is present in the web UI mod along with other [features](http://traccar.litvak.su/features/). There are no such function in default traccar web UI.

**Comment by perticas** [comment]
It is also open source?

**Comment by vitalidze** [comment]
Yes, this is actually a fork of the old GWT-based web UI of traccar. The github repository is [here](https://github.com/vitalidze/traccar-web)

**Comment by perticas** [comment]
Can you help me how can we pairing the datas in the API?

In the /api/device/get we receive the "uniqueId", the "name" and the "id", but int the /api/async we get  "deviceId" and an "id" field.
In the example the two "id" fields not equals.

How can we pair the records?
Is the two "id" fields are the same?

**Comment by tananaev** [comment]
When you call `/api/device/get` you receive a list of `device` objects.

When you call `/api/async` you receive a list of `position` objects.

As for matching, `deviceId` in the `position` object should match `id` in the `device` object. The `id` in `position` object doesn't match anything as it's just a unique key for this particular position.

**Comment by perticas** [comment]
Tks. how can i translate it to romanian also?

**Comment by tananaev** [comment]
@perticas, you can add translation here:

https://www.transifex.com/traccar/traccar

**Comment by perticas** [comment]
Hello, Vitalidze can you please tell me where i can find out every parameter what exactry represent. Which is ignition, which is power supply. tks

**Comment by perticas** [comment]
Hello, 

I have downloaded the translation from transifex but now where should i upload it

**Comment by vitalidze** [comment]
@perticas you should read documentation about your device and compare parameter names with the one you see in traccar

**Comment by perticas** [comment]
Hello @vitalidze after instaling your ui mod the api is not working any more. Any ideea why?

**Comment by vitalidze** [comment]
@perticas if you are using the 3.0 or 3.1 versions, then it will not work because it wasn't possible to run both API and web application from `.war` file at the same time. Since 3.2 it should be working.

**Comment by perticas** [comment]
Is 3.2 aviable? where?

**Comment by vitalidze** [comment]
It is available on the official web site https://www.traccar.org/download/

**Comment by perticas** [comment]
Does this version containds the posibility to rename the parameters? tks

**Comment by vitalidze** [comment]
My web UI mod contains such functionality. You can install my mod over that version.

**Comment by perticas** [comment]
can you give me some details how? sorry. as i have told you i am new at this. tks :)

**Comment by vitalidze** [comment]
Here are the installation instructions http://traccar.litvak.su/installation.html

**Comment by perticas** [comment]
One more question, please. I have translated on https://www.transifex.com/traccar/traccar into romanian and downloaded the translation but how can i import it into website because i didnt find any instructions. tks

**Comment by tananaev** [comment]
If you are using UI mod, the localization process is different. I guess @vitalidze can clarify the process there.

If you are using default interface, you need to put translation into the `web/l10n` folder, add a line to `web/locale.js` file and use web interface via `debug.html` (alternatively you can try to compile release version, but it's more complicated).

**Comment by perticas** [comment]
Hello, I have updated to latest version and instaled the UI mod but when i am trying to ecces api i got {"success":false}. any idee why?

**Comment by tananaev** [comment]
@perticas, which API are you trying to access?

**Comment by perticas** [comment]
I am trying to acces /api/login

**Comment by tananaev** [comment]
I guess you are using an old version. There is supposed to be an "error" property explaining the failure.

**Comment by tananaev** [comment]
It means wrong email or password.

**Comment by perticas** [comment]
when i am trying the link it gives me that answer. 
http://monitorizare.cargotrack.ro/api/login

Did something change in the last version to the api?

**Comment by tananaev** [comment]
Nothing changed in version 3.2, but there will be changes in the next release.

**Comment by perticas** [comment]
What am i doing wrong the when accesing http://monitorizare.cargotrack.ro/api/login?

where should i put username and password?

**Comment by tananaev** [comment]
It's an API that requires email and password parameters.

**Comment by perticas** [comment]
Please tell me what sentensce should i use then http://monitorizare.cargotrack.ro/api/login.... and what. i didnt find anythin in instructions

**Comment by tananaev** [comment]
API documentation is here:

https://www.traccar.org/traccar-api/

**Comment by perticas** [comment]
Hello tananaev. Do you have the translation of the parameters from the Teltonika FM1100, 1200 and fm 5300, and ruptela fm eco4 devices? (i mean i want to translate them from IO5 to power Supply fror example) Thank you

**Comment by tananaev** [comment]
Limited mapping is implemented in [the decoder](https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/TeltonikaProtocolDecoder.java#L71).

**Comment by perticas** [comment]
Hello. Maybe you can help us with a problem that we are confrunting. We are receiving data from devices but in traccar we are not seeing if fifo althought the devices are transmiting the data fifo. We supose that the data is messed up somehow in traccar but we cant figure it out why. I think some settings are not ok.

**Comment by tananaev** [comment]
Can I see some message samples that you are talking about?
