### ISSUE TITLE
Calling traccar API

### ISSUE THREAD

**Issue by and12345** [traccar/traccar#1442]
Hi Anton,

Wanna ask how to call the API since i'm very new to programming, i have read he https://www.traccar.org/traccar-api/ but still can't understand it :( shame on me. 
Let's say i've deviceId: 1, and i want to send command type: "engineStop". What url i need to call, assume i already login.

Many thanks

**Comment by tananaev** [comment]
Please read following page:

https://www.traccar.org/traccar-api/
