### ISSUE TITLE
Calamp protocol

### ISSUE THREAD

**Issue by warlockopy** [traccar/traccar#1443]
Is the traccar ready for calamp devices?
incoming and outcoming?
Regards

**Comment by tananaev** [comment]
Traccar does support CalAmp devices, but only for receiving data. Commands are not implemented yet.

**Comment by evallgar** [comment]
Sorry to bring back this issue, I'm not sure if there's something I can help with to have Calamp commands implemented.

Is there a specific problem for have not implemented calamp commands?

thanks in advance.

**Comment by tananaev** [comment]
I don't think there is any problem. It's just no-one has worked on it yet.

**Comment by evallgar** [comment]
Great. I'm willing to work on this.
I'll see what I can do.

I was going to ask you if you could lead me to a good jump start, but then I heard you saying: "Good luck..."

Thanks for such a great software! Hope to contribute.

**Comment by tananaev** [comment]
I would recommend to look at commands implementation for other binary protocols as an example. For instance check `Gt06ProtocolEncoder` class.

**Comment by delkant** [comment]
Hello, I am looking forward to work with Calamp devices. I was wondering what level of support does traccar has with these devices, @evallgar did you make any progress with the commands implementation? is it already merged? (I know this ticket is old but it is still open, so I am not so sure about what is the status of it)

Thanks!!

**Comment by evallgar** [comment]
Hello @delkant, I have not yet make any progress on it. Have been busy integrating api to a new mobile app.
However, will soon be in need of this. As soon as I have something will get  back to you with some information.

Best regards,
