### ISSUE TITLE
How to add my google account for over limit request?

### ISSUE THREAD

**Issue by myexpertiseforyou** [traccar/traccar#1444]
Hello @tananaev .
Traccar working successfully but i crossed google api default request so i purchase some extra request. Where to add my credentials?? In which file 
Thanks in advance :)

**Comment by tananaev** [comment]
You would have to change the source code as URL is hard-coded for Google API:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/geocode/GoogleReverseGeocoder.java
