### ISSUE TITLE
Ruptela device configuration

### ISSUE THREAD

**Issue by ghost** [traccar/traccar#1446]
Hi

I have configured one device using the ip address 104.43.219.242 and port 5046 and protocol is TCP  but i could not see this device in the system please help me out to sort this issue.

Thanks

**Comment by tananaev** [comment]
What's the device id?

**Comment by asifmian** [comment]
Hi dear

now it is whowing in the system now i want to check one thing more if i upload the while system on my server and configure it and my server will have dedicated ip address then which configuration device has to send data i mean my ip address and what will be the port for it.

Thanks

**Comment by tananaev** [comment]
The port would be the same (5046).
