### ISSUE TITLE
support Null Message calamp protocol 

### ISSUE THREAD

**Issue by HusseinYounis** [traccar/traccar#1447]
null message in calamp mean the gps heart beat 

Null Message Example
This is an example of a basic Null message format.
Raw Data:
  83 05 01 02 03 04 05 01 01 00 00 00 01 

Decoded:
  -------Options Header--------
  83           Options Byte
  05           Mobile ID field length
  0102030405   Mobile ID
  01           Mobile ID Type Length
  01           Mobile ID Type
  -------Message Header--------
  00           Service Type, for this message 0 = Unacknowledged Request
  00           Message Type, for this message 0 = Null Message
  0001         Sequence number of the message you are responding to

can you support it in traccar ?

**Comment by tananaev** [comment]
What do you want me to do with this message on the server side? There is no useful information inside.

**Comment by HusseinYounis** [comment]
When the vehicle status that the calamp unit connected to is ignition off
for more than one day , calamp will sleep and will not send any data .. so
how can i know if the unit is work fine or not .. by null message we can
know that the unit work fine but the vehicle is ignition off .. also when
the vhicle is ignition off and no null message recived that mean there is
some problem

**Comment by tananaev** [comment]
Traccar currently doesn't support any messages without GPS info. I plan to change it very soon and then it would be possible to implement what you want.

**Comment by tananaev** [comment]
Traccar has supported messages with GPS for quite some time now, so closing this old ticket.
