### ISSUE TITLE
At JsonReverseGeocoder.java  exception

### ISSUE THREAD

**Issue by gpsim** [traccar/traccar#1448]
geocoder.type   set    google，At JsonReverseGeocoder.java 
try (JsonReader reader = Json.createReader(response.getResponseBodyAsStream())) {

There will be an exception

**Comment by tananaev** [comment]
There will be an exception if something goes wrong.

Do you get an exception? What is the exception?

**Comment by gpsim** [comment]
I have increased the catch.

try (JsonReader reader = Json.createReader(response.getResponseBodyAsStream())) {
..........
}catch(Exception e){
                	 System.out.println(e);
                }

javax.json.stream.JsonParsingException: Unexpected char 1
14 at (line no=1, column no=1, offset=0)

**Comment by tananaev** [comment]
Your shouldn't catch it if it's a legitimate error.

**Comment by gpsim** [comment]
I would like to use Baidu maps, the results and the other is the same as here after the exception, access to the address，I tested only nominatim normal access to the address。

baimap geocoder api:
http://api.map.baidu.com/geocoder/v2/?ak=E4805d16520de693a3fe707cdc962045&callback=renderReverse&location=39.983424,116.322987&output=json&pois=1

**Comment by gpsim** [comment]
Has been increased by BaiduReverseGeocoder.java  
the program does not trigger this code

**Comment by tananaev** [comment]
I guess there is some problem with the response then.
