### ISSUE TITLE
Understanding Traccar working and Protocol integration

### ISSUE THREAD

**Issue by younus93** [traccar/traccar#1449]
As far as I have observed, consider a GPS Device which uses a GT06 protocol. 
1. It sends a login packet to the traccar server. This packet contains the IMEI number to identify the GPS device. 
2. Traccar server sends back an acknowledgement packet. 
3. Tracker sends the Location packet. This location packet does not contain any information to link it to the device. 
4. Traccar server decodes the packet, stores the information and sends back a heartbeat packet to keep the connection alive.

My question is 
1. How do Traccar server know which packet belongs to what device.
2. If the connection is kept alive, which means right from the login message to receiving continuous heartbeat packets, How is the system able to handle so many requests coming in to the same port from different devices?

**Comment by tananaev** [comment]
Traccar doesn't initiate heartbeat messages, but it replies to the GPS tracker if required.

As for questions:
1. Messages that come from same TCP connection belong to the same device.
2. Network ports can handle any number of connections. I don't see the problem.

**Comment by younus93** [comment]
Is there a delay in displaying the data? 
My hardware indicates that it is uploading data to the server, but I am not able to see any data for the date 11th October 2015. 
The IMEI number is 358911020149049.

**Comment by tananaev** [comment]
Are you using demo server or your own one?

**Comment by younus93** [comment]
Demo server

**Comment by SebastEnn** [comment]
Questings answered. Issue can be closed.
