### ISSUE TITLE
upgrade from 2.6 to 3.1 

### ISSUE THREAD

**Issue by farbeed** [traccar/traccar#1455]
Hi,

I have upgarded my traccar server with mySQL database from 2.6 to 3.1, by just normal install

I have problem now that all position I receive has error, all devices are unknown
Unknown device - 1234567896545

How can I fix this issue

**Comment by tananaev** [comment]
How did you upgrade the server? Have you used instructions from the following pages?

https://www.traccar.org/update-from-2-x-to-3-0/
https://www.traccar.org/update-from-3-0-to-3-1/

**Comment by farbeed** [comment]
No, I just ran the setup file for 3.1 version

Sent from my HTC

----- Reply message -----

**Comment by tananaev** [comment]
Version 2 and 3 are not compatible, so you need to copy data manually if you want to save it.

**Comment by SebastEnn** [comment]
Questions answered. Issue can be closed.
