### ISSUE TITLE
change UX design

### ISSUE THREAD

**Issue by addonravi** [traccar/traccar#1461]
Currently show 2 type of circle in map red and green(Parakeet).
My device send 2 type of data GPS and LBS(Location based service).
Now if device is active then show green color otherwise show red color.
I need 3 type of color 
1.red if device is off (currently working)
2.green if device send GPS data
3.Blue if device send LBS data.

This type of change is possible or not.
If yes then How??
I don't  know Ext.js.

**Comment by addonravi** [comment]
Can i add one extra field in Position table like type??

**Comment by tananaev** [comment]
I plan to implement colors at some point, but there is some work required to be done on the back-end to support it first.

**Comment by SebastEnn** [comment]
Feature rejected. Colors don't differenciate between what type the tracking data is, but in what state the device is.

Issue can be closed.

**Comment by tananaev** [comment]
I believe it should be possible to implement using computed attributes. We support color overrides.
