### ISSUE TITLE
H2 to mysql please more help.

### ISSUE THREAD

**Issue by waca98** [traccar/traccar#1474]
Hello,
After running as  mysql database, do I need to keep theese 2 files :
/data/database.mv.db
and
/data/database.trace.db ???

**Comment by tananaev** [comment]
No, you can remove those files.

**Comment by waca98** [comment]
Thanks a lot, 

a last thing please; as I want to make daily backup of this database on a cron line as

15 07-18 * * 1-5 /bin/bash -c 'mysqldump --lock-tables=0 -h localhost -u USER -pPASSWD traccar --add-drop-table > /home/corail/Dropbox/Backup/traccar.sql'

Hope this will make a good backup; what about restoring inside traccar if needed ?

Thanks.

**Comment by tananaev** [comment]
It's a standard MySQL database. When you want to restore a backup, you need to stop Traccar service, run the backup script, start Traccar again.

**Comment by waca98** [comment]
Thanks a lot, and thanks for you very good job.
