### ISSUE TITLE
Adding OpenCellID to Traccar (Cell tower location)

### ISSUE THREAD

**Issue by pierrot10** [traccar/traccar#1476]
Good day,

Some time we can not get a GPS position, particularely when we are in a building a traveling by train.
There is nice Opensource project call OpenCellid
http://wiki.opencellid.org/wiki/What_is_OpenCellID

OpenGTS include OpenGTS and when a GPS position is unavailable, it send the cell tower position to OpenCellID and open cell id return the GPS position

I would like to suggest this feature because I think it's important to have a position even we are in "closed\* location, as the train which make a barrier.
The Traccar administrator need to provide the OpenCellID key. He also need to open an account.

Since July 7th, 2014 all user accounts that just read data from the OpenCellID database but do not contribute anything to OpenCellID on more than 15 individual calender days with download activities in a row are automatically blocked.
Example: if a user downloads OpenCellID data once per week using the OpenCellID API but never contributes at least 10% of the data volume of the downloaded data in the same time frame, his account will be blocked.
Additionnaly, and what does not do OpenGTS, I also would suggest to let the Traccar administrator send send GPS fix with the collected cell tower position, to contribuate and not be blacklisted after 15 days.

I hope to find that idea nice to use :o)
Cheers

**Comment by tananaev** [comment]
It's already on my TODO list.

I am in the process of discussing integration options with OpenCellID project.

**Comment by Gitschubser** [comment]
Another options:

1. Mozilla Location Service
- Website: https://location.services.mozilla.com/
- Api: https://location.services.mozilla.com/api
- Statistics: https://location.services.mozilla.com/stats

2. Openbmap
- Website: http://radiocells.org/
- Api: http://radiocells.org/geolocation
- Statistics: http://radiocells.org/stats/countries

3. Offline
- Download MLS...cell-export...   -> https://location.services.mozilla.com/downloads
- Import the data to database (Filter out your MCC, MNC and maybe the radiotype GSM because your tracker use only GSM)
- Use the offline database for cell towers

MLS -> 17.35 millions cells, OCID only 7.72 millions

**Comment by pierrot10** [comment]
That is excellent. Thank tananaev. Do you have an estimate time regarding that update? Cheers

**Comment by tananaev** [comment]
I want to include it in the next release, so it will be available some time in December or early next year.

**Comment by Gitschubser** [comment]
Perfect, thank you.

**Comment by chathudan** [comment]
How about this  **Public mobile cells database. GeoLocation API** which has both Mobile towers and Wifi hotspots geo location data 
https://www.mylnikov.org/archives/1059

**Comment by tananaev** [comment]
@chathudan, it doesn't look very reliable. What are the chances that the guy who provides the service won't turn it off tomorrow?

**Comment by chathudan** [comment]
@tananaev you can download the data base https://www.mylnikov.org/download without accessing their service

**Comment by tananaev** [comment]
I see, but I don't plan to implement local database for now. Also, I suspect that Mozilla Location Service aggregates OpenCellID already, so it's kind of redundant.

**Comment by samequefarias** [comment]
@tananaev @chathudan Hello, do you know if it is possible to collect user location information through the wifi network by the mozilla loocation service? If yes, which step should I follow, you have some algorithm that can help me. I'm a doctoral student and I was in need of such data. Email: sameque@det.ufc.br

**Comment by tigetxt** [comment]
> Another options:
> 
> 1. Mozilla Location Service
>    Website: https://location.services.mozilla.com/
>    Api: https://location.services.mozilla.com/api
>    Statistics: https://location.services.mozilla.com/stats
> 2. Openbmap
>    Website: http://radiocells.org/
>    Api: http://radiocells.org/geolocation
>    Statistics: http://radiocells.org/stats/countries
> 3. Offline - Use the offline database for cell towers
>    Download MLS...cell-export...   -> https://location.services.mozilla.com/downloads
>    Import the data to database (Filter out your MCC, MNC and maybe the radiotype GSM because your tracker use only GSM)
> 
> MLS -> 17.35 millions cells, OCID only 7.72 millions

can i use OpenCellID offline

**Comment by tigetxt** [comment]
can i use OpenCellID offline??

**Comment by SebastEnn** [comment]
Support for [OpenCellID](https://www.opencellid.org) and [Mozilla Location Service](https://location.services.mozilla.com/) (although being [shutdown for public use](https://github.com/mozilla/ichnaea/issues/2065)) was added in [Version 3.3](https://www.traccar.org/blog/traccar-3-3/).

This issue can be closed.
