### ISSUE TITLE
debug mode of traccar server

### ISSUE THREAD

**Issue by SRIKAAA** [traccar/traccar#1477]
Dear Tananaev, I have implemented the setup file in our server and is working fine now. I have developed a test server to debug few data packets sent from the server. I have pointed the tracker to my system GLOBAL IP and port.
I am using NETBEANS (with Maven Plugin). Below are the challenges
1. In the port peeker i can see that data is coming from tracker.
2. But when i run the traccar in debug mode, inserted breakpoint at GT06ProtocolDecoder file under Decode Function. But the breakpoint is not getting hit there.

What is the solution?

**Comment by tananaev** [comment]
Do you see messages in the `tracker-server.log` file?

**Comment by SRIKAAA** [comment]
I have not installed any set up file in my PC. I have opened the code in NETBEANS and run the project. I inserted the breakpoint in GT06Protocol. But it is not getting called.

What do i need to do for me to debug the Live data sent from device to the project running in NETBEANS. Is it possible.

Regarding tracker-server.log ......after installation of setup file only it is updating.....but when i run the project in NETBEANS ...there is not log file created.

**Comment by tananaev** [comment]
You need to provide path to your configuration file as a command line argument. After that you should be able to run and debug Traccar.

**Comment by SRIKAAA** [comment]
Where do i need to provide the path...in which file of NETBEANS project

**Comment by tananaev** [comment]
It should be somewhere in:

Project -> Properties -> Run -> Arguments

**Comment by SRIKAAA** [comment]
I have set the config. file in arguments section and clicked on Run.
I am using MS SQL server. It is mentioning that com.microsoft.sqlserver.jdbc.SQLServerDriver  is not found.
I have downloaded the sqljdbc driver from microsoft site and set the path at <entry key='database.driverFile'>

Please suggest the solution as i have to debug few things that tracker is sending to server....

**Comment by tananaev** [comment]
You need to do following modification to the config to work with MS SQL:

https://www.traccar.org/ms-sql/

**Comment by SRIKAAA** [comment]
Now the error is solved. But device is not sending any data ...when i clicked on debug traccar project in net beans.

Do i need to change IP address anywhere in the config file.

**Comment by tananaev** [comment]
By default Traccar listens on all network interfaces, so you don't need to specify IP address in the config.
