### ISSUE TITLE
user_device Table

### ISSUE THREAD

**Issue by snoop168** [traccar/traccar#1485]
in the user_device table you might want to rename the "read" and "write" columns as MYSQL warns that "read" and "write" are reserved keywords. Additionally there were no Primary Keys defined on that table in the schema so some of the options in PHPMYADMIN are automatically disabled. I would assume the PK's should be both the UserID & DeviceID columns together. That's how I did it on my DB and seems to work fine.

**Comment by tananaev** [comment]
I know that those are reserved keywords. That's why they are quoted in the script.

As for primary key, it's not required in that table because we already have a foreign key index for searching.
