### ISSUE TITLE
device data showing up under wrong devices

### ISSUE THREAD

**Issue by snoop168** [traccar/traccar#1486]
On the main screen when you click devices the "State" pane below the device list updates with some data for incorrect devices (I've got about 33 devices configured but only have 3 configured to send GPS) and cars that do not have GPS being sent for them are showing data underneath it. Apparently the web interface knows this is false data for those particular cars because when I highlight it, the map does not auto center on that particular cars false data. The auto center only works on the cars that do truly have data. I checked the DB and do confirm that the records in the position table are in fact all correctly identified by one of the 3 intended devices and also in the devices table the positionID field is only filled for the 3 cars that should have associated position records and the ones that are falsely displaying data are set to NULL.

**Comment by tananaev** [comment]
Can you please make a screenshot of what you see in the state panel.

**Comment by snoop168** [comment]
![image](https://cloud.githubusercontent.com/assets/2731594/10846168/eba19c96-7ee3-11e5-87ff-eec514f0be71.png)
in the above, that highlighted car actually does not have any position data and in the device table its "positionID" field is set to null, yet the web interface displays data below as shown in the screenshot. When you click this particular device the map does not auto center. (Its like your auto center function knows there is no data but whatever function displays below is somehow crossing records for other devices)

**Comment by tananaev** [comment]
Is it possible for me to take a look? You can send address and login details to my email (address is in profile).

I tried on the demo server and if a car doesn't have any data, it shows empty state.
