### ISSUE TITLE
 Deploy Server after modifications

### ISSUE THREAD

**Issue by mannu7099** [traccar/traccar#1489]
Hi,
I have made few customization and modifications in the server code now I want to deploy it but unfortunately I didn't find the default configuration referred in few issues :https://github.com/tananaev/traccar/blob/master/default.cfg 

Moreover I am not able to create package. can you explain how to setup the prerequites like the package builder is reaching "../../EXT-**" and other items in check list is also there but I didn't find any document regarding how to set up those pre requites I am using ubuntu- 14.X for building the package.

Please help me to setup server after customization.

**Comment by tananaev** [comment]
What part of the code have you modified? If it's just Java code, you can install official release and just replace the `.jar` file.

You can find some more information about building from source here:

https://www.traccar.org/build/

Note that you need to have ExtJS and Sencha CMD for web interface minification.
