### ISSUE TITLE
когда трекер в офлайне

### ISSUE THREAD

**Issue by edgiru** [traccar/traccar#1490]
Извините я не знаю кому написать про эту ошибку (может это и не ошибка) то ли Вам то ли Vitalidze (я использую его доработку вашего сервера https://github.com/vitalidze/traccar-web) Я тоже задавал вопрос ему, но т.к. я не очень хорошо знаю английский, не могу ему ответить правильно. Решил спросить у Вас.

Заметил когда трекер не передает данные (написано Offline), сервер показывает как будто машина (маркер) едет назад по тем же точкам как и приехала. т.е. маркер начинает сам перемещаться обратно по треку.

**Comment by tananaev** [comment]
На сколько я помню @vitalidze тоже русский понимает. Похоже что проблема какая-то именно с веб интерфейсом.

**Comment by vitalidze** [comment]
Антон прав. Можно писать по-русски. Я думаю, что проблема с устройством, но не исключаю и проблем с интерфейсом. Я здесь https://github.com/vitalidze/traccar-web/issues/314 ответил, можно там продолжить обсуждение.

**Comment by mpele** [comment]
It should be checked the sorting order at device. The first collected
position was it reported to server at the begining or at the end of data
block (FIFO or FILO)?
Some devices, after geting in online mode, think that it is better to
report the most resent positions as soon as posible.
