### ISSUE TITLE
identified protocol

### ISSUE THREAD

**Issue by perfectwebtech** [traccar/traccar#1492]
what is this protocol device and is it can work with our traccar ? 

http://omlinux.com/proto/gprs2.doc

http://omlinux.com/proto/gprs1.doc

thanks
parbat

**Comment by tananaev** [comment]
It's Meiligao protocol. Port 5009 in Traccar by default.

**Comment by perfectwebtech** [comment]
why it's getting  

2015-10-31 15:09:48 DEBUG: [25EE2C29: 5023 < 117.229.28.0] HEX: 78780a13000604000205ec57f70d0a
2015-10-31 15:09:48 DEBUG: [25EE2C29: 5023 > 117.229.28.0] HEX: 7878051305ecaba20d0a
2015-10-31 15:10:07 DEBUG: [3FC3C635: 5009 < 183.90.36.235] HEX: 242400786028264614ffff99553039343030332e3030302c412c303131382e323037352c4e2c31303335312e313837392c452c3030302e302c3139372e352c3331313031352c2c2c412a36347c312e367c33302e347c303030307c303030302c303030307c3030303033343634377c3030303030d6920d0a
2015-10-31 15:10:07  WARN: Unknown device - 6028264614

**Comment by perfectwebtech** [comment]
sorry 

it was my mistake like we keep 0 before device id so :) 

1) what files i should make changes for insert status code like speed greater than 4 then moving if less than 4 speed then stop like those all status code where i can make it working ?
2) for commands which file i should make changes according to my need which files i should do coding ? in protocols java files ?

**Comment by tananaev** [comment]
1) What status code are you talking about?

2) If you want to implement commands, you need to create protocol encoder class. See GPS103 for example:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gps103ProtocolEncoder.java

**Comment by perfectwebtech** [comment]
ok and case there is device send some other data and notification alert so
want to in status code

On Sun, Nov 1, 2015 at 3:01 AM, Anton Tananaev <notifications@github.com>
wrote:

> 1) What status code are you talking about?
>
> 2) If you want to implement commands, you need to create protocol encoder
> class. See GPS103 for example:
>
>
> https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gps103ProtocolEncoder.java
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1492#issuecomment-152774558>.
>



-- 
thanks
http://omlinux.com
http://www.perfectwebtechs.com

**Comment by tananaev** [comment]
Alert and notifications are not supported at the moment, but it's in plans.

**Comment by tananaev** [comment]
I believe alerts have been supported for a while now.
