### ISSUE TITLE
Question about RegExp

### ISSUE THREAD

**Issue by paulo-coutinho** [traccar/traccar#1493]
Hi,

Why you use RegExp here for example:
https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gps103ProtocolDecoder.java

And not use String Split by comma "," ? Any good reason? It is only a question.

Thanks.

**Comment by tananaev** [comment]
Splitting by comma might work for some protocols, but regular expressions work for all of them (there is one exception where I uses splitting by comma).
