### ISSUE TITLE
SOS button Developer

### ISSUE THREAD

**Issue by kochphilipp94** [traccar/traccar#1494]
Hello i search a developer what my can make a SOS button to the Traccar Client ( iOS / Android ) 

When i Press the Button then musst on the Web begin flashing....
Also i search people what my can make on the Web a special solution with push or IP call...

Please send my a msg when you can doing this to : chlinekoch@gmail.com

**Comment by dschense** [comment]
This feature would be really cool. Have a look on this.

**Comment by kochphilipp94** [comment]
@dschense can you my give your skype or email ?

**Comment by dschense** [comment]
I am at work atm will contact you this evening.. But I am not that good with this coding stuff... Maybe others are also interested in this and can help.

**Comment by dschense** [comment]
Any progress on this?

**Comment by vitas** [comment]
I did android sos button functionality for similar project, please contract me.

**Comment by igaran** [comment]
Please send my  app to : igaran@inbox.ru
