### ISSUE TITLE
statusCode with openGTS integration

### ISSUE THREAD

**Issue by kevalkk** [traccar/traccar#1496]
can i take statusCode like ":statusCode" same as speed ":speed" on traccar.xml?

I am using GT06 and GT06N device

i want to put statusCode directly to eventdata "statusCode" field.

On status code there will be like

<pre>
    public static final int STATUS_MOTION_START         = 0xF111;   // 61713
    // Description:
    //      Device start of motion

    public static final int STATUS_MOTION_IN_MOTION     = 0xF112;   // 61714
    public static final int STATUS_MOTION_EN_ROUTE      = 0xF112;   // 61714
    // Description:
    //      Device in-motion interval

    public static final int STATUS_MOTION_STOP          = 0xF113;   // 61715
    // Description:
    //      Device stopped motion

    public static final int STATUS_MOTION_DORMANT       = 0xF114;   // 61716
    // Description:
    //      Device dormant interval (ie. not moving)

    public static final int STATUS_MOTION_STOPPED       = 0xF115;   // 61717
    // Description:
    //      Alternate to Dormant (ie. not moving)

    public static final int STATUS_MOTION_IDLE          = 0xF116;   // 61718
    // Description:
    //      Device idle interval (ie. not moving, but engine may still be on)

    public static final int STATUS_MOTION_EXCESS_IDLE   = 0xF118;   // 61720
    // Description:
    //      Device exceeded idle threashold
</pre>

Waiting for your Reply.

keval mer

**Comment by tananaev** [comment]
What's the difference with #1497?

**Comment by kevalkk** [comment]
this is for status motion/movement , stop,

I want to know from you in xml file we are fetching :speed from gps responce how can i get ":status"?

is it possible.

**Comment by tananaev** [comment]
What do you mean by status? Traccar doesn't calculate OpenGTS status code for database.

There is another integration option (it has `statusCode` field):
https://github.com/tananaev/traccar/issues/1131#issuecomment-121150718

**Comment by kevalkk** [comment]
status=statusCode. but device will return hax code for statusCode. i want to insert that record on opengts database. i dont know hot to fetch that perticular hax.

**Comment by tananaev** [comment]
Devices don't return OpenGTS status codes. It needs to be calculated based on the data from devices.

**Comment by kevalkk** [comment]
please tell me .java files name from which we can get device data and read.

and also tell me .java files from which you are inserting data on traccar
database

so i can calculate and get  data of statuses.

and thanks for help

waiting for your reply

keval mer

**Comment by tananaev** [comment]
You can try to add statusCode somewhere here:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/database/DataManager.java#L344
