### ISSUE TITLE
Alarm status on openGTS integration

### ISSUE THREAD

**Issue by kevalkk** [traccar/traccar#1497]
can i take alarm status like ":statusCode" same as speed ":speed" on traccar.xml?

I am using GT06 and GT06N device

i want to put alarmstatus directly to eventdata "statusCode" field.

On status code there will be like

<pre>public static final int STATUS_INPUT_STATE          = 0xF400;   // 62464
//      Current input state change

public static final int STATUS_IGNITION_ON          = 0xF401;   // 62465
//      Ignition turned ON

public static final int STATUS_INPUT_ON             = 0xF402;   // 62466
//   Input turned ON

public static final int STATUS_IGNITION_OFF         = 0xF403;   // 62467
//      Ignition turned OFF

public static final int STATUS_INPUT_OFF            = 0xF404;   // 62468
//      Input turned OFF

public static final int STATUS_OUTPUT_STATE         = 0xF406;   // 62470
//      Current output ON state (bitmask)

public static final int STATUS_OUTPUT_ON            = 0xF408;   // 62472
//      Output turned ON

public static final int STATUS_OUTPUT_OFF           = 0xF40A;   // 62474
//      Output turned OFF

public static final int STATUS_ENGINE_START         = 0xF40C;   // 62476
//      Engine started

public static final int STATUS_ENGINE_STOP          = 0xF40D;   // 62477
//      Engine stopped

public static final int STATUS_INPUT_ON_00          = 0xF420;   // 62496
public static final int STATUS_INPUT_ON_01          = 0xF421;   // 62497
public static final int STATUS_INPUT_ON_02          = 0xF422;   // 62498
public static final int STATUS_INPUT_ON_03          = 0xF423;   // 62499
public static final int STATUS_INPUT_ON_04          = 0xF424;   // 62500
public static final int STATUS_INPUT_ON_05          = 0xF425;   // 62501
public static final int STATUS_INPUT_ON_06          = 0xF426;   // 62502
public static final int STATUS_INPUT_ON_07          = 0xF427;   // 62503
public static final int STATUS_INPUT_ON_08          = 0xF428;   // 62504
public static final int STATUS_INPUT_ON_09          = 0xF429;   // 62505
public static final int STATUS_INPUT_ON_10          = 0xF42A;   // 62406
public static final int STATUS_INPUT_ON_11          = 0xF42B;   // 62407
public static final int STATUS_INPUT_ON_12          = 0xF42C;   // 62408
public static final int STATUS_INPUT_ON_13          = 0xF42D;   // 62409
public static final int STATUS_INPUT_ON_14          = 0xF42E;   // 62510
public static final int STATUS_INPUT_ON_15          = 0xF42F;   // 62511

//      Digital input state changed to ON

public static final int STATUS_DOOR_OPEN_0          = 0xF434;   // 62516
public static final int STATUS_DOOR_OPEN_1          = 0xF435;   // 62517
public static final int STATUS_DOOR_OPEN_2          = 0xF436;   // 62518
//      Door open</pre>

I want to get this statuses

waiting for your reply

keval mer

**Comment by tananaev** [comment]
It should be possible to calculate those status codes in the SQL query, so someone can try to implement it.

**Comment by kevalkk** [comment]
Alarm status like SOS press.

i want to fetch/get that statuses on xml file what is the name of this :alarmstatus? or :status?

is it possible to get status like :speed to :status?
