### ISSUE TITLE
GPRS Commands for traccar with openGTS

### ISSUE THREAD

**Issue by kevalkk** [traccar/traccar#1498]
GPRS commands read and put into database.

commands like WHERE# //for current location

STATUS# //for check status

you can read GT06N commands like bellow file

http://ads.pwtech.pw/gpscommands/GT06N%20command%EF%BC%88V2.0%EF%BC%89.xlsx

Please tell me how can i read this commands responce and how can insert on openGTS database.

and from where i can send this commands manually from traccar java file?

because i want to put commands by users on database. traccar will read command and sent to server and then server will reply and ready by traccar and insert into database.

waiting for your reply

keval mer

**Comment by tananaev** [comment]
Do you want to send commands through Traccar from OpenGTS interface? I don't think it's possible.

You can use Traccar API if you want to send commands, but I'm not sure if it's going to work with current OpenGTS integration config. You might need to modify it.

**Comment by kevalkk** [comment]
Can i know which table's of traccar database is reponsible for this type of commands?

i will put that table on database of openGTS. 

if i know from which file traccar api fetching this data and send to device then i will put database table on opengts and then it will work like traccar?

is it possible?

**Comment by tananaev** [comment]
Commands are sent directly to the connected devices. They are not store in the database.

**Comment by prashant075** [comment]
Hi ,
I have a sets of command that are stored in db in one of the gts table.
I want to send this command back to device .
Please help me or given some idea to solve this problem.
(I am able to send the command via a trackhandler java code but it's set by server side or me , now i need this command set by web interface and  that will store in db , if packet will come I have to get back the command to particular device )
@kevalkk  @tananaev 

Thank You.

**Comment by tananaev** [comment]
@prashant075, you are asking in the wrong place. This is Traccar project.

**Comment by prashant075** [comment]
Thanks
