### ISSUE TITLE
Web administration port forwarding problem

### ISSUE THREAD

**Issue by strejcradis** [traccar/traccar#1499]
Hi guys,

I want to access administration via internet, but when i forward port 8082 (web administration is running on localhost:8082), i cant access to the administration. Can anybody help me with it please? Thanks :(

**Comment by tananaev** [comment]
What is the error? There is nothing special about forwarding ports to Traccar server. It should just work. Are you sure there is nothing else that can block connection (e.g. firewall)?

**Comment by strejcradis** [comment]
I am running Apache server on the same machine on port 85 and everything works great. Also, i have problem that server didnt receive any data from app. 
I will describe you my configuration:

Android app setting: 
 Identificator: 233722
 Server IP: 193.85.227.100
 Port: 5055

Server:
  Local ip: 192.168.2.34
  Port: 80

Forwarding:
  Forward 193.85.227.100:5055 to 192.168.2.34:5055

Stil not receiving any data, dont you know how is it possible?

**Comment by tananaev** [comment]
Port 8082 is closed, but 5055 seems to be open. What do you see in the Android app (status screen)?

**Comment by strejcradis** [comment]
Yeah, I turned off firewall and Traccar server started receiving data. Great, but can you help me how to add exception for Traccar in firewall to keep everything else protected?
