### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by perfectwebtech** [traccar/traccar#1500]
is there way good accuracy 

sometime not good accuracy  of gt06 device

like device in india and lat long goes in singapore sometime only happen like

15 minutes device move and like 30 to 50 records wrong lat long goes in singapore 

or can edit in code of java where for accuracy thing ? protocol calculation thing ?

**Comment by tananaev** [comment]
Please provide HEX samples from the `tracker-server.log` file with wrong coordinates.
