### ISSUE TITLE
timestamp

### ISSUE THREAD

**Issue by perfectwebtech** [traccar/traccar#1501]
hello

is there bestway how can do case i see if first time device add then just data comes without gps only heartbit so during heartbit  timestamp can update in device table or not i use gts with my own interface

opengtsdatabase and my own interface using php 

so i want to show online offline device so during heartbit also time stamp important is it worked ? 
or i need to do customization something ?

**Comment by tananaev** [comment]
Implementing support for device online/offline status is in plans, but not implemented yet.

**Comment by tananaev** [comment]
This has been supported for a while.
