### ISSUE TITLE
tk103 battery alert

### ISSUE THREAD

**Issue by aspergames** [traccar/traccar#1502]
Hi, i tested tracker t8800 with traccar and it worked  under GPS-103 protocol and BP05 messages, but when my tracker send ZCxx type messages, like battery level , dont save  battery data, only save positions.

please helpme

Thanks !!!

**Comment by tananaev** [comment]
Traccar versions 3.1 and below don't support messages without GPS info.

Next release will include support for such messages. You can try this build:

https://www.dropbox.com/s/myt68q5u7fiz49r/tracker-server-jar-with-dependencies.jar?dl=0

**Comment by aspergames** [comment]
Thanks !!, proves the solution and its result will comment
