### ISSUE TITLE
"ADB not responding..." When Traccar is running on Mac. 

### ISSUE THREAD

**Issue by Java-god** [traccar/traccar#1519]
I suddenly started getting an error "ADB not responding..." on Android Studio (Mac) after I ran Traccar and couldn't resolve it until I uninstalled Traccar and reinstalled Android Studio. 

Just to be sure where the error was coming from, I ran Traccar again and the ADB error started again, forcing me to repeat the same processe all over again. 

Is there a way to run Traccar on my Mac without it affecting my ADB?

**Comment by tananaev** [comment]
By default both ADB and Traccar use port 5037. You can change the port in Traccar config to avoid this conflict.

**Comment by Java-god** [comment]
OK, I didn't know that. Please how do I do that?

**Comment by tananaev** [comment]
Just change the port in the config file:

https://www.traccar.org/configuration-file/

Then restart Traccar service:

<pre>sudo /opt/traccar/bin/traccar restart</pre>

**Comment by Java-god** [comment]
Thanks for your continued support. 
What do I change it to? Can I use any random numbers as port or is there a convention I must follow?

**Comment by tananaev** [comment]
Any random number. For example, 6037.

**Comment by Java-god** [comment]
Awesome, thanks!
