### ISSUE TITLE
latest version suggestion

### ISSUE THREAD

**Issue by perfectwebtech** [traccar/traccar#1521]
anton as you have done latest version might be other users could be problem 

case you are inserting 0 value during heartbit ? or sleeping mode ? as latest version ? 

so all time but problem is solved from xml  as i did ignore 0 and seems working fine and great 

so may be this sample config files users can use it and problem solved ? as 0 filtering so will have great working this last version for all people really 

case they people can get consider as status of device 

i  have done other class customized and working fine according my need  :)

**Comment by tananaev** [comment]
I don't quite understand what you are talking about. Heartbeat messages are not saved in the database and they won't be.

**Comment by perfectwebtech** [comment]
heartbeat mean device sleeping then just send details without gps lat long got it ?

**Comment by tananaev** [comment]
The idea is that on heartbeat message server would just update device status and timestamp.

**Comment by perfectwebtech** [comment]
yes true and it's working fine great work it could be stable version i have tested more time
