### ISSUE TITLE
АВТОГРАФ-GSM

### ISSUE THREAD

**Issue by smith-job** [traccar/traccar#1523]
Здравствуйте.
Есть такой трекер "АВТОГРАФ-GSM".
http://www.tk-ekat.ru/monitoring-transporta/oborudovanie-dlya-monitoringa/avtograf-gsm2 
Как бы обеспечить его поддержку и что для этого надо.
С уважением, Андрей К.

**Comment by smith-job** [comment]
Подключили на ваш тестовый сервер 
  Domain name: demo2.traccar.org
  IP address: 107.150.40.254
на порт 5019 (почти наобум)
такое устройство (imei 355094042854202)

**Comment by tananaev** [comment]
Вижу вот такие данные от трекера:
<pre>2015-11-11 12:20:21 DEBUG: [8B79191F: 5019 < 85.26.233.109] HEX: 24d4010000d854030000113132333435363738f060250d544dcff3908899230ff3e6a8f060258d0403008c0035800c0ff3e6fbf060258d0eec3a2d000005000ff3e684f960250d000000a0000000000ff7fee11261250d024ecff3228899030ff7e6661261258d0418809a00fffff70ff7e69d1261258d0eec3a2d000000000ff7e6cc1861250d6e4ecff32c8899230ff7f6641861258d041b8089003b800b0ff7f6851861258d0eee3a2d000000000ff7f6a92861250d5e4ecff3988899230ff7f6642861258d04440034003c000c0ff7f6a82861258d0eef3a2d000000000ff7f6262a61250d324ecfe3f08899230ff7f61d2a61258d0442804c003b000c0ff7f6902a61258d0ef03a2d000000000ff7f60d2c61250df74dcff3f68899230ff7f6d52c61258d0436005a003a000c0ff7f6082c61258d0ef13a2d000000000ff7f6e83161250dc14dcff3ea8899230ff7e6523161258d040100000039800c0ff7e6243161258d0ef23a2d000000000ff7e6206461250dbc4dcff3ed8899230ff7e64d6461258d04000000003d800c0ff7e6476461258d0ef23a2d000000000ff7e6519761250db64dcff3fc8899230ff7e6039761258d04000000003b800c0ff7e6309761258d0ef23a2d000000000ff7e694b0
2015-11-11 12:21:25 DEBUG: [8B79191F: 5019 < 85.26.233.109] HEX: 24d4010000d854030000123132333435363738f060250d544dcff3908899230ff3e6a8f060258d0403008c0035800c0ff3e6fbf060258d0eec3a2d000005000ff3e684f960250d000000a0000000000ff7fee11261250d024ecff3228899030ff7e6661261258d0418809a00fffff70ff7e69d1261258d0eec3a2d000000000ff7e6cc1861250d6e4ecff32c8899230ff7f6641861258d041b8089003b800b0ff7f6851861258d0eee3a2d000000000ff7f6a92861250d5e4ecff3988899230ff7f6642861258d04440034003c000c0ff7f6a82861258d0eef3a2d000000000ff7f6262a61250d324ecfe3f08899230ff7f61d2a61258d0442804c003b000c0ff7f6902a61258d0ef03a2d000000000ff7f60d2c61250df74dcff3f68899230ff7f6d52c61258d0436005a003a000c0ff7f6082c61258d0ef13a2d000000000ff7f6e83161250dc14dcff3ea8899230ff7e6523161258d040100000039800c0ff7e6243161258d0ef23a2d000000000ff7e6206461250dbc4dcff3ed8899230ff7e64d6461258d04000000003d800c0ff7e6476461258d0ef23a2d000000000ff7e6519761250db64dcff3fc8899230ff7e6039761258d04000000003b800c0ff7e6309761258d0ef23a2d000000000ff7e69437
</pre>

**Comment by tananaev** [comment]
На навис протокол не похож. Мне нужно документация на протокол что-бы расшифровать данные.

**Comment by smith-job** [comment]
К сожалению, все выглядит так, что описания протокола нет. Заинтересованы ли вы в анализе этого протокола? В принципе, выглядит не так уж страшно. Явно выделяется часть посылки с адресом устройства и координатами и временем. Если будет выделенный порт на тестовом сервере, я мог бы сконфигурировать пару устройств. Совместно мы могли бы расшифровать формат сообщения.

**Comment by tananaev** [comment]
Я честно говоря ничего явного не вижу. Можете показать где именно в посылке адрес, координаты и время?

**Comment by smith-job** [comment]
В ASCII видно вначале адрес устройства (с 11 по 18 байты включительно) "12345678".
Самый хвост в посылках тоже изменился, координаты устройства в тот момент времени не менялись, думаю - это время.

Думаю, при анализе данных с двух устройств можно попытаться выделить изменяющиеся части и проанализировать. Если Вы можете выделить порт и если у Вас есть заинтересованность. 

С производителем устройств я связывался, их online консультант сообщил, что протокол - закрытая часть и они подумают по поводу open source системы и свяжутся со мной (Ваш контакт я не рискнул без Вашего разрешения им давать, спрашивал об их отношении ко всем open source проектам). Не связались. 
На их сайте в документации прочел, что дают они его разработчикам только под соглашение о неразглашении, что на мой взгляд не согласуется с open source лицензиями.

**Comment by tananaev** [comment]
В хвосте посылки скорее всего контрольная сумма а не время.

Соглашение о неразглашении это достаточно распространенная практика. Я уже подписал такие с несколькими производителями. Главное чтобы разрешали исходники публиковать. Можете смело давать мои координаты им если это поможет.
