### ISSUE TITLE
Connecting to MS SQL Express

### ISSUE THREAD

**Issue by sammy1000** [traccar/traccar#1525]
Hi Anton,
Been trying to connect traccar server to sqlexpress on local machine and had followed all steps to best of my knowledge, but I am sure I am missing something because traccar server cannot connect with sqlexpresss as in the reported message in wrapper log:

<pre>WARN com.mchange.v2.c3p0.DriverManagerDataSource - Could not load driverClass com.microsoft.sqlserver.jdbc.SQLServerDriver</pre>

This is the database configuration entries in traccar.xml:

```
<entry key='database.driverFile'>C:\Program Files (x86)\Traccar\lib\sqljdbc42.jar</entry> 
<entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry> 
<entry key='database.url'>jdbc:sqlserver://MAIN-PC\SQLEXPRESS;user=traccar;password=traccar;</entry> 
<entry key='database.user'>traccar</entry> 
<entry key='database.password'>traccar</entry>
```

Is this an issue with JDBC driver not being loaded, and if so, what should I do to correct it. Or should I look for other possible issues I may have in my setup.
Appreciate your help ...

Thanks,

**Comment by tananaev** [comment]
You are using Java 8 driver. I guess it could be the problem. Try to use `sqljdbc41`; it's the one for Java 7.

**Comment by sammy1000** [comment]
Thanks a lot for your help Anton .... the driver is loaded just fine now ...
Cheers & have a good day ...
Sammy

**Comment by sammy1000** [comment]
Hi Anton,
Sorry to bother you again but I mistakenly thought the issue was resolved.
you're right. I am using Java version 8 update 65 and sqljdbc41 still did not work. It gives the same error.
I tried sqljdbc4, 41, and 42 but without success.
Incidentally, Oracle pulled out the option to download version 7 from its Java site.
Any ideas ... Please
Sammy

**Comment by tananaev** [comment]
I think the best option is to use JDBC 4.1.

I guess there must be some problem with the driver path.

**Comment by sammy1000** [comment]
Here is a screenshot of where the driver is ...
![image](https://cloud.githubusercontent.com/assets/15820024/11130130/7a7456c4-8994-11e5-8649-e8979e5b9c9f.png)

**Comment by tananaev** [comment]
One more idea - make sure the file permissions are correct. Traccar is usually running from System user account.

**Comment by sammy1000** [comment]
Perhaps this might help from wrapper log ...
INFO   | jvm 1    | 2015/11/12 23:29:58 | [C3P0PooledConnectionPoolManager[identityToken->1hgeknc9c1yb1oonsr8wli|571b4793]-HelperThread-#1] WARN com.mchange.v2.c3p0.DriverManagerDataSource - Could not load driverClass com.microsoft.sqlserver.jdbc.SQLServerDriver
INFO   | jvm 1    | 2015/11/12 23:29:58 | java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at java.net.URLClassLoader.findClass(Unknown Source)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at java.lang.ClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at java.lang.ClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at java.lang.Class.forName0(Native Method)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at java.lang.Class.forName(Unknown Source)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at com.mchange.v2.c3p0.DriverManagerDataSource.ensureDriverLoaded(DriverManagerDataSource.java:143)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:173)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
INFO   | jvm 1    | 2015/11/12 23:29:58 | 	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

**Comment by sammy1000** [comment]
By the way ...I have installed Traccar server as an Administrator ...

**Comment by tananaev** [comment]
You have to install it as administrator to be able to create a system server. What are the user permissions on the driver file? Can you make a screenshot?

**Comment by sammy1000** [comment]
Here you go ... as requested ...

![image](https://cloud.githubusercontent.com/assets/15820024/11130563/be43b0aa-8996-11e5-959b-a5b597bebff8.png)

However, I have no problem running it with default H2 java database configuration ... besides I believe that I have administrator privilege ...

**Comment by tananaev** [comment]
I have no other ideas why it's happening. We must be missing something.

**Comment by sammy1000** [comment]
Thanks Anton anyway ... Will let you know if I have any update ...

**Comment by tananaev** [comment]
Try database URL like this:
<pre>jdbc:sqlserver://localhost:1433;databaseName=traccar</pre>

**Comment by sammy1000** [comment]
Hi Anton,
I switched from this setup ....
     - Windows 10, Edge browser
     - x64 bit machine
     - traccar server 64
     - MSSQL Express 2012
to this setup ...
     - Windows 7, IE 11
     - x86 (32) bit PC
     - traccar server 32
     - MySQL 5.7 community GA
traccar worked beautifully and is able to track devices ....
Thanks buddy for your traccar, and for your help ...
Cheers ...
Sam
