### ISSUE TITLE
Некорректно работают тайлы яндекс карт

### ISSUE THREAD

**Issue by alexmorbo** [traccar/traccar#1531]
Одно и тоже расположение трекеров, 2 скриншота, яндекс карты и OSM
На яндексе чуть выше все распологается, некорректно
![OSM](https://mrbscreens.s3.amazonaws.com/Traccar_2015-11-16_11-19-11.png)
![Yandex](https://mrbscreens.s3.amazonaws.com/Traccar_2015-11-16_11-19-20.png)

**Comment by tananaev** [comment]
Проблема в том что Яндекс Карты используют немного другую проекцию (EPSG:3395), так что к сожалению их подключить к Traccar пока не получится.
