### ISSUE TITLE
User not logged in - AccessControlException

### ISSUE THREAD

**Issue by Gitschubser** [traccar/traccar#1535]
Hello,

i want to add a new device and get this message:
User not logged in - AccessControlException (BaseServlet:77 < DeviceServlet:74 < *:33 < BaseServlet:53 < ...)

I get the problem with the user admin and a new user.

**Comment by tananaev** [comment]
It looks like you are not using session cookies for the request.

**Comment by Gitschubser** [comment]
Thank you. It works.

**Comment by manishsaharan** [comment]
Hello,

i want to remove a device and get this message:
 {"success":false,"error":"Device access denied - SecurityException (PermissionsManager:81 < DeviceServlet:90 < *:39 < BaseServlet:53 < ...)"}

but in postman if i call same api the response is correct but when i call api from my android device then getting this message.
Plz help..

**Comment by tananaev** [comment]
@manishsaharan, this error message means that the user doesn’t have permissions for the selected device.

**Comment by manishsaharan** [comment]
@tananaev ,Thanks

 The device which i want to remove added by my account and from same account i want to remove.
Can you tell me how to add device in my account I am using device/add api and send {"id:"-1,"uniqueId:" IMEI,"name:" devicename} and response is success true.
If in add device any problem plz let me know..

I am also use user/update api for update profile then error message i got SecurityExcption but permission manager code is different.
I am using demo.traccar server for testing.

I am only set cookie and content-type after login any api hit if any other param i miss then let me know.

**Comment by manishsaharan** [comment]
@tananaev 
I am missing somthiing to write...
If I am hit any API using postman then all api hit successfully.
So, I think i am miss any param.

**Comment by tananaev** [comment]
Just compare what default Traccar web interface sends with what you send.
