### ISSUE TITLE
Login API - MySQL field hashedPassword

### ISSUE THREAD

**Issue by evigra** [traccar/traccar#1536]
Hello Tananaev, 

I read your API: https://www.traccar.org/traccar-api/

I insert and consult directly in MySQL using PHP.

How should I store hashedPassword field?
Because the API returns me, 
in http://url:8082/api/login

{"success": false, "error": "For input string:

**Comment by tananaev** [comment]
Password are hashed using PBKDF2-HMAC-SHA1 with following parameters:

<pre>ITERATIONS = 1000;
SALT_SIZE = 24;
HASH_SIZE = 24;</pre>

Password and salt are stored in separate fields in the database.

**Comment by evigra** [comment]
Some example PHP?

i try with.
$pass 		= "ExamplePass";
$iteraciones 	= 1000;
$sal 			= 24;
$hash 		= hash_pbkdf2("sha1", $pass, $sal, $iteraciones, 24);

MySQL
hashedPassword   = 'c280d7b866b92ab4e729be93'
salt                         = 24

**Comment by tananaev** [comment]
Here is an example of hash for password "password":

`ef38a22ac8e75f7f3a6212dbfe05273365333ef53e34c14c` (hash)
`000000000000000000000000000000000000000000000000` (salt)

**Comment by evigra** [comment]
HASH_SIZE = 24???
in your example = 48

**Comment by tananaev** [comment]
It's 24 bytes. I provided HEX representation of binary data.

**Comment by evigra** [comment]
you will have an example in php?
The data I provide me for MySQL, if they worked

**Comment by tananaev** [comment]
I don't have a example in PHP. Java code is here:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/helper/Hashing.java

**Comment by evigra** [comment]
Thank you
I read during the day

**Comment by jorgejimenez88** [comment]
evigra do you have an example to login in php?
Because I try with the example from the forum but don't work
