### ISSUE TITLE
Implement camera for GL200

### ISSUE THREAD

**Issue by bernamaxim** [traccar/traccar#1538]
I want to implement camera for GL200 protocol, server can parse it into a picture by base 64code. It will be converted to .jpg extension. Because the picture is about 10Kb, it would be separated by about 20 messages to send to the server. Can you help me to parsing this to the server?

**Comment by tananaev** [comment]
Do you have documentation and message samples?

**Comment by bernamaxim** [comment]
This is the documentation:
[GV300 User Manual R1.01.pdf](https://github.com/tananaev/traccar/files/37507/GV300.User.Manual.R1.01.pdf)

Here the example of raw data:
```+RESP:GTPHL,250506,863286020254562,,0,,20151118115119,0,0.0,181,21.1,106.909667,-6.147427,20151118043219,0510,0010,0095,5056,00,,,,,20151118115125,85FC$

+RESP:GTPHD,250506,863286020254562,,0,,20151118115119,7,1,684,/9j/2wCEAA0JCQsJCA0LCgsODQ0PEx8UExEREyYbHRcfLSgwLy0oLCsyOEg9MjVENissP1U/REpNUFFQMDxYX1hOXkhPUE0BDQ4OExATJRQUJU00LDRNTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTf/AABEIAHgAoAMBIQACEQEDEQH/3QAEAAr/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4Q=,,,,,20151118115127,85FD$

+RESP:GTPHD,250506,863286020254562,,0,,20151118115119,7,2,684,hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDsvs6QQ4AAAHFc/q96IlIBoA4jVL5nYqDyetY7GgCMnmo2bmgB9pcCG4VznAzn8qms4jIkjNkRqMuf5D8aAIx5iyAAcnkCtK1trm7kWGNW+agD1zwz4ZtdB00GaNGuHG6V3AO329q4/WGi1PWJr/aFtYuIxjAOO/40AcjqeoNc3X7okAHjFdL4Z055CLi6Yu5HAY5NAHo2l2MUaibYM444rToA5zxDPcXIMNrE8gH90dTXEXnhzVBG881vx1PzDNAHNy2ZeQqo5zWvpfh5nAZlyaAP/9DrtXvFhjbBrhrhp9VvRb2ymSRjgKKAMy/8OajbEma1lX3K1jTWkiH5lI/CgCuYXLdKidTnpQA0JWtaQXE9vDCkOIiWkZycA44yT2AoAesAa5Y8SMTgY6V6J4G8PhV/tG4XIz+6yPvH+9/hQBteILsyqbCFsAjM7ei+n415x4g1JJHNpbfLEvBx3oAo6RpkbT+ZLg4PArttGtxJcokfQHnFAHdIgjQKvQDFZ+r6kLOEqh+c9fagDiLrxHfeawhk2r61nXF9qF58sly7Z7ZoAvaL4ce4kDuMk+s=,,,,,20151118115128,85FE$

+RESP:GTPHD,250506,863286020254562,,0,,20151118115119,7,3,684,Xc2GjQ2qDeoLUAf/0V8Rav8AeUGqXhXUDZXkl4VyQuBmgDqR4webKtEpU88ike70q++WezjLt1I4xQBmXmh6RO22zbHPIPasK88IsZMw/MDQBlzaDPB1UioJTPGkdu5by1zhe3XNAHSeFfD0uq3ahkKQj5pH9vQe9elX91HpVkqQqqtjZEnYY/oKAOJ1e4uGtXW1y7MfncnlmNc9HoUkeZrtvf5jgUALGR5wWM8Z7V2Xh3bCVdqAOiutXjhjOzlv5VxGtau0rsqvkk8mgDEVJJ3+XJzXUaF4daZg8g496AO0tbOK1TbGv40zULxbK2aRjzjigD//0uW1K6M9wRnvVq0cpbheRQBPFMQCAeT3qaOcjJLc9KAFiuDkuj5z+lbNhdyKAS2e/NAF2eeCeM+YgyepxWXpz6WurR293YNeSscog6An19aAPRiYLG1L7EhiQZIUAAflXEapqc99cuyAl24RR/CKAM+S9i0m2+YeZOeSfQ1gXWo3F/JukY7ewoAmsVzICeldPZylEB6CgCtq2p7Y9kbfMf0rHgt5bqTCgnPWgDstC8NgKsko/OusiiSFAiDAFACySLEhdjgCuD8Tay9w5jiPFAH/0+K5M/PrV9JR8owOD0oAnWRWBBGOafI/7olB8x4FAE1uoAAGABWlBJgcUAPnulRCWOFUZNX/AAg=,,,,,20151118115130,85FF$

+RESP:GTPHD,250506,863286020254562,,0,,20151118115119,7,4,684,29tA8uvag6gnKQJ1JPc4/T86AJtY8QzaiTGg8uBTwncn3pLezW1tHubptrlcjntQByF+5uZmbkJngVVVSzYHSgDc02xZlDsMLV2/nMEBSMfORwfSgDP02wmvZMOC2T1ru9G8PR2yK8q8+lAG+qhQAowBSk4GTQBzuu6qufIibPqRXIXkYdiV79aAP//U4pnBcMO/Wp42ywoA77wj4d0+6jE11F9oPXDZx+VS+KNI04XCx28CQFRz5YxQBys0JtZAucg9DTluCnC0AOEBuflkJ29/etqTS5bHShdXBEKniKM/eb3x2FAGbBIv2qLzG+XOWqbUL2W95kO2JfurQBhzv5j7EFaWl6WXYM68UAdTawxxJtcYU8E1nLprPevBG3mQk5XPUUAdfpWjRWMYZlBf+ValAASAMmuf1nW8K0Fq3PQtQBzyBpH+bknvUsmn7gdvYUAf/9XhVPNSI/zigD0/wlq9jaWREjsHwOACfrVLVtUiurqaTlSW+XPHFAHM3lwXmHerFjbNKQ2CSxwB60Ad3o/h+LToftuogF1G4R4yF+vqa57xJqb6g6uSQH5VP7o9Pr60AZtrbZG+T9aiuPMuZRDCuaANOx8PFF3uMnuautdWemRFpj8w6KO9AFIanc6pLtQeXHnoK7LQ9MW3hEsgyx6ZoA2KKAMzVdQjit5YkbM=,,,,,20151118115131,8600$

+RESP:GTPHD,250506,863286020254562,,0,,20151118115119,7,5,684,IRjjsa5IgluaAJVGxRjrUkM7J8p70Af/1uFUcZpUI80Z9aAN/Tnl37ImY4XJAbaKk+0GRmV8gH+8aAK6Wz3F/wCUoLBcYxXpnhzw8unQrc3ag3GMqp6Rj/GgCnqnimLzZfL+aJAVjP8Aebuf8K5JWMzh5OwwBQBYQPcMI4+B3Nbljp0FqgdsZ7k96ADVtYisoMRgFz91RXJhJ9QuDJLkkmgDtfDeg7VWaVcKOnvXVgADA4AoASSQRRs56KMmuQn8ZefqP2eBDHCOCx6t/hQA68UhVmX7jVXVAeRQAmzLc1KsHQ0Af//X4QtgVAzndkUAdFobeai7tmMEHcM4/CpLlXjjldsll6ZGM0AdV4A0v7U5v5lysZ4JHV//AK3+FbXi7WktrV7GJmErgbiPT0oA4bmTDN26CpE4PzcCgC5b3McPIINSz6rLONkIyfXsKAIY7CW5kDSZdjXU6N4aCBZbgYHULQB0ZdIgEUdOiilLFVyfyoAqwXBknaOQfK3QVyHirRDZXIu7cfu3OSB2NAF3RblL6z8iU844qBla0uzDIDt7GgCx5OTkdKcOBigD/9DgXNTafDFcXJhlGTIjBD6Njj9f50AW9Ev1tJ9sg6Hite5kmubaZ1AddwUDvz0oA7m21O30DQLeytAJLhU+Y9gx5JNcrfs87tPM5d2OST3oAzE=,,,,,20151118115133,8601$

+RESP:GTPHD,250506,863286020254562,,0,,20151118115119,7,6,684,rhlfCip0jnuMADAoA0LXR2xl81rWuljICLQB0WnWEFqA7gM1aDvNJxEuxfU9aAIjZzA5SRQ3qeaeba4cYe4H4L/9egBo04ht3ntn1xSXelpfRCK5ldk9BxQBVi8OWdnmS3MiuORk5qeaxS9twWTEqjuKAM1rZrXAbJQ8fSjyC7jbQB//0eCYU2N2ilWRDhkIINAFhoib4vjCt8/4HmuospFZCDhTgdO9AFtXLDaOaRraWfjacUAWLbQJZGBZMD3rXh02O2XnrQBOir0xxWnZWcjgFV2r6mgDVigWIep9aloAKKACigAoxzmgCC5gEsTYUEkdPWsm3k2Oy9wcc0Af/9Lh3TdyB9aasDO2ApP0oA1bbRby5ACqcdMmux03wsDZQoEczD7zdqAN+z8KogBlIHsK14NKtLcfLECfU0ASyW0ZU4AXFYF75YkIU5oAbG8Fsnmyt0ofxBNKoS1XYvTcetAHSwhhCgY5baMn3p9ABRQAUUAFFAEU9wluoL9zgCop7JJm8xflc9/WgD//00svBEspG5Sa6Kw8Eww4MgUUAb1ro1pagbYwSPWryqFGFAA9qAFqOWdIR8x59KAM+9uHaFiflXGcCuMvdQkdm8vjnrQBZCNLaxljksBWhaWJVogRgEigDru1FABRQAUUAFFAFea0Wa4jldj8nRe1WOooA/8=,,,,,20151118115135,8602$

+RESP:GTPHD,250506,863286020254562,,0,,20151118115119,7,7,320,1PTQABgDFLQA1nVB8zAfU1VuNVtbcEtID9KAMS58WwmQxwsM1z934jneWVWJUZG00AdRJcrc2CN/0yGea5q5twsJb1NAF3TisscMfVgK6eO3wYiV7igDQooAKKACigAooAK57X9eNvm1tDiQj5nHb6UAf//V6qXxZGo+XbWfc+L5CMR5/CgDJufEF7MTg4z71lz3FxLy7sT9aAKyGSOUPirt1Gb20YINrgZHvQBraJfvMDDJ18sDGatzQs9v0oAk8PwM2oKpHArtMcUALRQAUUAFFABRQBz2saxId0Fr8oHDN3Ncnqs8nE3UjrQB/9k=,,,,,20151118115136,8603$

**Comment by bernamaxim** [comment]
If I joined the camera data, it would be like this:
`/9j/2wCEAA0JCQsJCA0LCgsODQ0PEx8UExEREyYbHRcfLSgwLy0oLCsyOEg9MjVENissP1U/REpNUFFQMDxYX1hOXkhPUE0BDQ4OExATJRQUJU00LDRNTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTU1NTf/AABEIAHgAoAMBIQACEQEDEQH/3QAEAAr/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4Q=hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDsvs6QQ4AAAHFc/q96IlIBoA4jVL5nYqDyetY7GgCMnmo2bmgB9pcCG4VznAzn8qms4jIkjNkRqMuf5D8aAIx5iyAAcnkCtK1trm7kWGNW+agD1zwz4ZtdB00GaNGuHG6V3AO329q4/WGi1PWJr/aFtYuIxjAOO/40AcjqeoNc3X7okAHjFdL4Z055CLi6Yu5HAY5NAHo2l2MUaibYM444rToA5zxDPcXIMNrE8gH90dTXEXnhzVBG881vx1PzDNAHNy2ZeQqo5zWvpfh5nAZlyaAP/9DrtXvFhjbBrhrhp9VvRb2ymSRjgKKAMy/8OajbEma1lX3K1jTWkiH5lI/CgCuYXLdKidTnpQA0JWtaQXE9vDCkOIiWkZycA44yT2AoAesAa5Y8SMTgY6V6J4G8PhV/tG4XIz+6yPvH+9/hQBteILsyqbCFsAjM7ei+n415x4g1JJHNpbfLEvBx3oAo6RpkbT+ZLg4PArttGtxJcokfQHnFAHdIgjQKvQDFZ+r6kLOEqh+c9fagDiLrxHfeawhk2r61nXF9qF58sly7Z7ZoAvaL4ce4kDuMk+s=Xc2GjQ2qDeoLUAf/0V8Rav8AeUGqXhXUDZXkl4VyQuBmgDqR4webKtEpU88ike70q++WezjLt1I4xQBmXmh6RO22zbHPIPasK88IsZMw/MDQBlzaDPB1UioJTPGkdu5by1zhe3XNAHSeFfD0uq3ahkKQj5pH9vQe9elX91HpVkqQqqtjZEnYY/oKAOJ1e4uGtXW1y7MfncnlmNc9HoUkeZrtvf5jgUALGR5wWM8Z7V2Xh3bCVdqAOiutXjhjOzlv5VxGtau0rsqvkk8mgDEVJJ3+XJzXUaF4daZg8g496AO0tbOK1TbGv40zULxbK2aRjzjigD//0uW1K6M9wRnvVq0cpbheRQBPFMQCAeT3qaOcjJLc9KAFiuDkuj5z+lbNhdyKAS2e/NAF2eeCeM+YgyepxWXpz6WurR293YNeSscog6An19aAPRiYLG1L7EhiQZIUAAflXEapqc99cuyAl24RR/CKAM+S9i0m2+YeZOeSfQ1gXWo3F/JukY7ewoAmsVzICeldPZylEB6CgCtq2p7Y9kbfMf0rHgt5bqTCgnPWgDstC8NgKsko/OusiiSFAiDAFACySLEhdjgCuD8Tay9w5jiPFAH/0+K5M/PrV9JR8owOD0oAnWRWBBGOafI/7olB8x4FAE1uoAAGABWlBJgcUAPnulRCWOFUZNX/AAg=29tA8uvag6gnKQJ1JPc4/T86AJtY8QzaiTGg8uBTwncn3pLezW1tHubptrlcjntQByF+5uZmbkJngVVVSzYHSgDc02xZlDsMLV2/nMEBSMfORwfSgDP02wmvZMOC2T1ru9G8PR2yK8q8+lAG+qhQAowBSk4GTQBzuu6qufIibPqRXIXkYdiV79aAP//U4pnBcMO/Wp42ywoA77wj4d0+6jE11F9oPXDZx+VS+KNI04XCx28CQFRz5YxQBys0JtZAucg9DTluCnC0AOEBuflkJ29/etqTS5bHShdXBEKniKM/eb3x2FAGbBIv2qLzG+XOWqbUL2W95kO2JfurQBhzv5j7EFaWl6WXYM68UAdTawxxJtcYU8E1nLprPevBG3mQk5XPUUAdfpWjRWMYZlBf+ValAASAMmuf1nW8K0Fq3PQtQBzyBpH+bknvUsmn7gdvYUAf/9XhVPNSI/zigD0/wlq9jaWREjsHwOACfrVLVtUiurqaTlSW+XPHFAHM3lwXmHerFjbNKQ2CSxwB60Ad3o/h+LToftuogF1G4R4yF+vqa57xJqb6g6uSQH5VP7o9Pr60AZtrbZG+T9aiuPMuZRDCuaANOx8PFF3uMnuautdWemRFpj8w6KO9AFIanc6pLtQeXHnoK7LQ9MW3hEsgyx6ZoA2KKAMzVdQjit5YkbM=IRjjsa5IgluaAJVGxRjrUkM7J8p70Af/1uFUcZpUI80Z9aAN/Tnl37ImY4XJAbaKk+0GRmV8gH+8aAK6Wz3F/wCUoLBcYxXpnhzw8unQrc3ag3GMqp6Rj/GgCnqnimLzZfL+aJAVjP8Aebuf8K5JWMzh5OwwBQBYQPcMI4+B3Nbljp0FqgdsZ7k96ADVtYisoMRgFz91RXJhJ9QuDJLkkmgDtfDeg7VWaVcKOnvXVgADA4AoASSQRRs56KMmuQn8ZefqP2eBDHCOCx6t/hQA68UhVmX7jVXVAeRQAmzLc1KsHQ0Af//X4QtgVAzndkUAdFobeai7tmMEHcM4/CpLlXjjldsll6ZGM0AdV4A0v7U5v5lysZ4JHV//AK3+FbXi7WktrV7GJmErgbiPT0oA4bmTDN26CpE4PzcCgC5b3McPIINSz6rLONkIyfXsKAIY7CW5kDSZdjXU6N4aCBZbgYHULQB0ZdIgEUdOiilLFVyfyoAqwXBknaOQfK3QVyHirRDZXIu7cfu3OSB2NAF3RblL6z8iU844qBla0uzDIDt7GgCx5OTkdKcOBigD/9DgXNTafDFcXJhlGTIjBD6Njj9f50AW9Ev1tJ9sg6Hite5kmubaZ1AddwUDvz0oA7m21O30DQLeytAJLhU+Y9gx5JNcrfs87tPM5d2OST3oAzE=rhlfCip0jnuMADAoA0LXR2xl81rWuljICLQB0WnWEFqA7gM1aDvNJxEuxfU9aAIjZzA5SRQ3qeaeba4cYe4H4L/9egBo04ht3ntn1xSXelpfRCK5ldk9BxQBVi8OWdnmS3MiuORk5qeaxS9twWTEqjuKAM1rZrXAbJQ8fSjyC7jbQB//0eCYU2N2ilWRDhkIINAFhoib4vjCt8/4HmuospFZCDhTgdO9AFtXLDaOaRraWfjacUAWLbQJZGBZMD3rXh02O2XnrQBOir0xxWnZWcjgFV2r6mgDVigWIep9aloAKKACigAoxzmgCC5gEsTYUEkdPWsm3k2Oy9wcc0Af/9Lh3TdyB9aasDO2ApP0oA1bbRby5ACqcdMmux03wsDZQoEczD7zdqAN+z8KogBlIHsK14NKtLcfLECfU0ASyW0ZU4AXFYF75YkIU5oAbG8Fsnmyt0ofxBNKoS1XYvTcetAHSwhhCgY5baMn3p9ABRQAUUAFFAEU9wluoL9zgCop7JJm8xflc9/WgD//00svBEspG5Sa6Kw8Eww4MgUUAb1ro1pagbYwSPWryqFGFAA9qAFqOWdIR8x59KAM+9uHaFiflXGcCuMvdQkdm8vjnrQBZCNLaxljksBWhaWJVogRgEigDru1FABRQAUUAFFAFea0Wa4jldj8nRe1WOooA/8=1PTQABgDFLQA1nVB8zAfU1VuNVtbcEtID9KAMS58WwmQxwsM1z934jneWVWJUZG00AdRJcrc2CN/0yGea5q5twsJb1NAF3TisscMfVgK6eO3wYiV7igDQooAKKACigAooAK57X9eNvm1tDiQj5nHb6UAf//V6qXxZGo+XbWfc+L5CMR5/CgDJufEF7MTg4z71lz3FxLy7sT9aAKyGSOUPirt1Gb20YINrgZHvQBraJfvMDDJ18sDGatzQs9v0oAk8PwM2oKpHArtMcUALRQAUUAFFABRQBz2saxId0Fr8oHDN3Ncnqs8nE3UjrQB/9k=`

Please copy and paste data above to http://codebeautify.org/base64-to-image-converter# to generate image and you will see an image.

**Comment by tananaev** [comment]
I have added it to my backlog, but it might take some time till I get to implement it.

**Comment by al3x1s** [comment]
Hello anton, have you implemented this feature in the latest release?

**Comment by tananaev** [comment]
No, unfortunately it's not implemented yet.
