### ISSUE TITLE
Время, когда трекер последний раз выходил на связь

### ISSUE THREAD

**Issue by alexmorbo** [traccar/traccar#1541]
Сейчас в базе есть lastUpdate, но он может не обновиться, если координаты отфильтрованы.
Как таковой актуальной даты, когда трекер пытался отправить координаты на сервер - нет.
Возможно ли добавить?

**Comment by tananaev** [comment]
Вы проверяли что поле не обновляется? Обновление lastUpdate никак не зависит от фильтрации данных. Я только что на всякий случай проверил. Все обновляется как и должно.

**Comment by alexmorbo** [comment]
На сколько вижу я, если убрать все фильтры, то lastUpdate обновляется каждые 5 секунд, как и трекер отправляет информацию каждые 5 секунд.

Если включаю фильтры:
```
    <!-- Custom -->
    <entry key='filter.enable'>true</entry>
    <entry key='filter.zero'>true</entry>
    <entry key='filter.invalid'>true</entry>
    <entry key='filter.duplicate'>true</entry>
    <entry key='filter.distance'>50</entry>
```

То, lastUpdate обновляется если координаты проходят фильтры

**Comment by tananaev** [comment]
Я перепроверил еще раз. У меня все работает. Более того, `lastUpdate` работает совершенно независимо от фильтрации и я не представляю как одно может влиять на другое.
