### ISSUE TITLE
Export report in Excel/CSV [New feature request]

### ISSUE THREAD

**Issue by sosoxuc** [traccar/traccar#1545]
CSV is best I think

We will try to do this on Saturday and show you

**Comment by tananaev** [comment]
This is in plans as well.

**Comment by guilhermesouza** [comment]
+1 add PDF format

Em seg, 23 de nov de 2015 às 20:45, Anton Tananaev <notifications@github.com>
escreveu:

**Comment by Abyss777** [comment]
Export reports to CSV is implemented in 3.7

**Comment by tananaev** [comment]
I'm not sure if we need PDF format, but I guess it should be fairly easy to add.
