### ISSUE TITLE
Technoton Protocol

### ISSUE THREAD

**Issue by SRIKAAA** [traccar/traccar#1548]
Dear Team
Kindly let me know which port to use for technoton MVT17L3 DEVICE.

Packet in hex format:
5041434B455453544152542A534C463036303031005544503135323000150002A403C513301900A5655447C02410102E0000002502131C10E002000000000000000C513302827A5655447C02410102E0000002502131810E0020000000000000000560E5041434B4554454E442A

**Comment by tananaev** [comment]
I don't think this protocol is supported. Also, you provided invalid HEX data (odd number of characters).
