### ISSUE TITLE
GPS tracker decoder issue for GT02 protocol

### ISSUE THREAD

**Issue by luv-gupta** [traccar/traccar#1550]
Need to decode the HEX Format message for GT02A . Data getting is not correct and it exits saying unknown device. 
HEX raw data : 283032373034333635353131374252303031353131323441313235342e393035344e30373733372e39323437453030302e333039353130393139362e313830303030303030304c303030303030303029

**Comment by tananaev** [comment]
Answered here: https://github.com/tananaev/traccar/issues/1011#issuecomment-159214220

Please don't duplicate your messages.
