### ISSUE TITLE
Backup mysql

### ISSUE THREAD

**Issue by waca98** [traccar/traccar#1552]
Hello,

For backing up traccar's mysql database, I use a crontab shell command
sudo crontab -e
00 \* \* \* \* /bin/bash -c 'mysqldump --lock-tables=0 -h localhost -u name -pPasswd traccar --add-drop-table > /path/to/backupfile.sql'
This command line work fine.... but because I don't close traccar     [service traccar stop]     so database is still open...
My very first question is, 
Do you think that backup file is possibly corrupt ?

Thanks.

**Comment by tananaev** [comment]
It shouldn't be. The worst case scenario I can think of is that `position` object would be saved, but a link from `devices` won't be updated.

**Comment by vitalidze** [comment]
You can use the `--single-transation` key of the `mysqldump` to do the backup of all your data within a single database transaction. This way the consistency should be guaranteed.

**Comment by waca98** [comment]
So like this, it will save realy all ?

00 * * * * /bin/bash -c 'mysqldump --single-transaction --lock-tables=0 -h localhost -u name -pPasswd traccar --add-drop-table > /path/to/backupfile.sql'

**Comment by vitalidze** [comment]
This will guarantee that you will not get a broken database. But the case which @tananaev is talking about may take place because from my understanding posting of new position and updating reference in device happen in different database transactions.

**Comment by waca98** [comment]
Not sure to understand all....
So what is the best way to have a backup of all (devices, history, users, admin, manager and so....)
- database   I use your command with  --single-transaction
- config     I have a cron backup of  /traccar/conf

Thanks.

**Comment by waca98** [comment]
Hello,

No idea about this ?

**Comment by tananaev** [comment]
I guess config doesn't change often, so you can just keep a copy somewhere. Everything else is in the database and will be backed-up by `mysqldump` utility.
