### ISSUE TITLE
Typo in Dutch translation of Traccar

### ISSUE THREAD

**Issue by apeman76** [traccar/traccar#1556]
When I go to my Traccar login page and select the Dutch (Netherlands) language, the password box says "WachtwoordPassword"
This should just be "Wachtwoord"

**Comment by tananaev** [comment]
Thanks for feedback. I have updated the translation.

If you are interested, you can help with translating Traccar here:

https://www.transifex.com/traccar/traccar/

**Comment by SebastEnn** [comment]
Typo is fixed in latest version.

![grafik](https://github.com/traccar/traccar/assets/103125747/6d01a5cc-1dde-4d66-8bb4-54a51f1dfb5a)

This issue can be closed.
