### ISSUE TITLE
Problem to connect database MySQl

### ISSUE THREAD

**Issue by pjrastreadores** [traccar/traccar#1564]
Good afternoon everyone.

I am having trouble connecting my database in the new version of the web traccar because standards put data as below and give ok :

<pre>&lt;entry key='database.driver'&gt;org.h2.Driver&lt;/entry&gt;
&lt;entry key='database.url'&gt;jdbc:h2:/home/user/Documents/traccar/target/database&lt;/entry&gt;
&lt;entry key='database.user'&gt;sa&lt;/entry&gt;
&lt;entry key='database.password'&gt;&lt;/entry&gt;</pre>

but as my abaxo does not :

<pre>&lt;entry key='database.driver'&gt;com.mysql.jdbc.Driver&lt;/entry&gt; 
&lt;entry key='database.url'&gt;jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&amp;amp;autoReconnect=true&amp;amp;useUnicode=yes&amp;amp;characterEncoding=UTF-8&amp;amp;sessionVariables=sql_mode=ANSI_QUOTES&lt;/entry&gt;
&lt;entry key='database.user'&gt;user2&lt;/entry&gt; 
&lt;entry key='database.password'&gt;pass2&lt;/entry&gt;</pre>

**Comment by tananaev** [comment]
There must be something wrong with connection parameters. I would recommend to try same parameters via some JDBC client (e.g. SQuirrel SQL) and see if it works.

**Comment by pjrastreadores** [comment]
Good afternoon my friend,
I managed to solve the problem in mysql as was reported earlier . I gave permission in phpMyAdmin created in the bank and restart traccar twice as it says in the tutorial. Thanks to everyone

**Comment by SebastEnn** [comment]
Problem was solved. Issue can be closed.
