### ISSUE TITLE
Hosting traccar for tk103 on a shared hosting server

### ISSUE THREAD

**Issue by SumantaBee** [traccar/traccar#1568]
Is it possible to host the traccar apis and gps reciever on a php server(not home pc)? If it is possible how can I do that?

**Comment by tananaev** [comment]
You need a VPS or dedicated server to host Traccar.

**Comment by SumantaBee** [comment]
Hi! can I use a dedicated ip and shared hosting and a domain for that? dedicated ips cost less.

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Thu, Dec 3, 2015 at 7:42 PM -0800, "Anton Tananaev" <notifications@github.com<mailto:notifications@github.com>> wrote:


You need a VPS or dedicated server to host Traccar.

-

**Comment by tananaev** [comment]
You can't use shared hosting because Traccar requires access to raw TCP and UDP ports that regular shared hosting doesn't provide.

**Comment by SumantaBee** [comment]
So a dedicated ip won't work?

**Comment by tananaev** [comment]
I guess it depends on the type of hosting. If it allows you to run arbitrary applications on the server, it should work.

**Comment by SumantaBee** [comment]
I'll try. I am in a very bad condition. we took the project and the nodejs developer left. I need to complete the project anyhow.

**Comment by SumantaBee** [comment]
Thank you for your time sir.

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Thu, Dec 3, 2015 at 7:49 PM -0800, "Anton Tananaev" <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess it depends on the type of hosting. If it allows you to run arbitrary applications on the server, it should work.

-

**Comment by superservidor** [comment]
@SumantaBee I think that for your case it is better to use a VPS server to run the Traccar instance. You can buy a good VPS server starting from EUR 1.99 with monthly payment using my link at http://www.time4vps.eu/aff.php?aff=181
