### ISSUE TITLE
device tables issues

### ISSUE THREAD

**Issue by sonuauti** [traccar/traccar#1575]
status field in device field is showing null

**Comment by tananaev** [comment]
Are you sure device is connected to the server?

**Comment by cispune** [comment]
yes device is connected and moving but status field is null

**Comment by tananaev** [comment]
What version of Traccar are you using?

**Comment by cispune** [comment]
latest

On Fri, Dec 11, 2015 at 1:52 AM, Anton Tananaev <notifications@github.com>
wrote:

> What version of Traccar are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1575#issuecomment-163739265>.
>



-- 
CIS Technologies (P) Ltd.

**Comment by tananaev** [comment]
Status field is not supported in version 3.2. It will be available in the next official release. Alternatively you can compile a version from source code if you don't want to wait.

**Comment by cispune** [comment]
okay thank you !

On Sat, Dec 12, 2015 at 5:27 AM, Anton Tananaev <notifications@github.com>
wrote:

> Status field is not supported in version 3.2. It will be available in the
> next official release. Alternatively you can compile a version from source
> code if you don't want to wait.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1575#issuecomment-164084174>.
>



-- 
CIS Technologies (P) Ltd.
