### ISSUE TITLE
Traccar doesn't work via HTTPS protocol?

### ISSUE THREAD

**Issue by volokva** [traccar/traccar#1576]
Tittle is my question basically, is there any way to work via HTTPS protocol?

**Comment by nelim** [comment]
I'm using apache mod_proxy, I think you can use nginx also, on some pages it gives warning it is partially encrypted and images are not, maybe because some external http:// content, tiles or something else..

**Comment by vladamirk** [comment]
But default web server Jetty

**Comment by nelim** [comment]
apache mod_proxy example:

SSLEngine On
SSLCertificateFile ....etc etc

SSLProxyEngine On
ProxyRequests off
ProxyPreserveHost On
ProxyPass / http://localhost:8082/
ProxyPassReverse / http://localhost:8082/


I dont know about default web server Jetty.. maybe Owner will know, good luck

**Comment by vladamirk** [comment]
Thank you for response

**Comment by tananaev** [comment]
Jetty is embedded server used in Traccar. Although Jetty can support HTTPS connection, there are no plans to enable it at the moment because it makes code and configuration more complicated. As @nelim  pointed out, you can easily set up Apache proxy to enable secure connections.
