### ISSUE TITLE
Стрелка и время стоянки (остановки)

### ISSUE THREAD

**Issue by edgiru** [traccar/traccar#1578]
Добрый день!
Не подскажите как настроить что бы значек (Стрелка)  показывал направление движения автомобиля? И при просмотре истории движения авто нет точек стоянки. т.е. посмотреть где и сколько стояла машина.

**Comment by tananaev** [comment]
У меня все показывается. Вы какую версию используете?

**Comment by edgiru** [comment]
последнюю с сайта. 3.2 14-Nov-2015

**Comment by tananaev** [comment]
Стрелки на месте на сколько я вижу из скриншота. Проблема с временем будет поправлена в следующей версии.

**Comment by edgiru** [comment]
я не про стрелку на маршруте говорил, а про стрелку показывающую саму машину. Вообщем я понял почему у меня обратно ехала машина. У меня уже стоял traccar и что то подлагивало и решил я переустановить, сделал резервную копию, удалил, поставил заново все, зарегистрировал первые машины и смотрю стрелка поехала назад ну думаю может так написано что стрелка не показывает направление движения. потом через некоторое время она появилась в другом месте и стала нормально двигаться как положено. Я подозреваю что дело было все в точках с треккера загрузились все точки которые были в буфере (в истории) по этому по мере загрузки точек машина как-буд то ехала назад.

**Comment by tananaev** [comment]
Такого не должно быть. Точки фильтруются по времени.
