### ISSUE TITLE
temperature for meiligao

### ISSUE THREAD

**Issue by perfectwebtech** [traccar/traccar#1580]
hello

<pre>2424001415122008ffffff994408532b4da00d0a</pre>

   this is temperature data sample
 we are getting from device
  how to make different pattern of this data
 i want to add temperature data on database
 but there is not lat long and pattern matching thats why
 i had updated but there is some mistake
can you help me by update/solve my mistake

``` Java
 private static final Pattern PATTERN_TEMPERATURE = new PatternBuilder()
            .number("(dd)(dd)(dd)")            // temperature
            .compile();


  Parser parser = new Parser(
                pattern, buf.toString(buf.readerIndex(), buf.readableBytes() - 4, Charset.defaultCharset()));
        if (!parser.matches()) {
            Log.debug("Parser Not Match");
            return null;
        }
```

I am getting "Parser Not Match"

**Comment by tananaev** [comment]
Can you please provide protocol documentation with format for this type of message.

**Comment by perfectwebtech** [comment]
http://devtest.zonjesg.com/GPRS%20Communication%20Protocol%207.0%281%29.doc

**Comment by tananaev** [comment]
There is nothing about command `0x9944` in the document.

**Comment by perfectwebtech** [comment]
2424001415122008ffffff994409022b471e0d0a

09022bis temperature data. to decimal +23.06

 0902hex to decimal

2b= "+" hex to ascii

2424=$$
0014 =length

15122008=deviceid

9944=type of data(temperature)

471e is the checksum

full:  2424007b15122008ffffff99553037343235392e3030302c412c303131382e323033382c4e2c31303335312e313833372c452c312e31312c34312e30372c3038313231352c2c2c442a35307c312e30307c32382e327c303230317c303030302c303030307c3030303132303436367c30303030303030307d260d$$ÿÿÿ {   ÿÿÿ U074259.000,A,0118.2038,N,10351.1837,E,1.11,41.07,081215,,,D*50|1.00|28.2|0201|0000,0000|000120466|00000000}&

 
as u see in protocol not mention but they send as in protocol not mention

**Comment by tananaev** [comment]
Well, as far as I understand from what what you said before, the temperature information is encoded in binary format, so you can't use regular expressions to parse it. You need to read it as binary from `ChannelBuffer`.

**Comment by perfectwebtech** [comment]
example hax record for temperature=2424001415122008ffffff994408532b4da00d0a

position.set(Event.KEY_TEMPRATURE, buf.readBytes(2));//0853
and 1 byte=2b(08532b)=+

i am at position of how can get this record 3bytes

and how can insert temperature record like database.updateDeviceStatus(heartbeat)

how can pass/insert data without pattern & parser.

please help me i want to add this record on another database table. its like heartbeat not sending gps data(latitude,longitude)

**Comment by tananaev** [comment]
It is not possible to use `updateDeviceStatus` for the temperature. You need to add this data to position object. You can use `getLastLocation` method to fill location details from last message.

**Comment by perfectwebtech** [comment]
Is there any example of java file that consider to insert different data in different tables of database?

I want to add temperature record into table like "temperaturedata" in which i will insert id,deviceid,temperature,timestamp.

i can manage class from connection manager and database manager and also set at xml file.

how can i send data @ connectionManager.java without position. is it possible without position?

position is return @ decode() method @ protocolDecoder.jaa

**Comment by tananaev** [comment]
There are no examples. If you want to add messages without position, you would have to add a lot of code because it's not supported at the moment.
