### ISSUE TITLE
Does tracer support MQTT protocol

### ISSUE THREAD

**Issue by pierrot10** [traccar/traccar#1582]
Dear all,
I found a nice library which send coordinate with the MQTT protocol.
Does it work with traccar?

**Comment by tananaev** [comment]
As far as I understand MQTT is just a messaging protocol. It has nothing to do with GPS tracking.

**Comment by pierrot10** [comment]
Hello,Yes. Sorry if if did not detail well my question. Adafruit has a library which track a devise, get the GPS fix and send it to the server io.adafruit.com. It use MQTT, which is a messaging protocole, to send the coords to the server.
I was wundering if it's compatible with Traccar, as I want to use traccar. But does traccar accept and records the coords if it's sent with the MQTT messaging?

**Comment by tananaev** [comment]
I need to know the format in which it sends coordinates, but most likely it's not supported.

**Comment by tbarthelet** [comment]
I would refer to @ivanfmartinez regarding this topic, maybe he can explain us how he built his working prototype plugging a specific handler to traccar enabling MQTT messaging. cf. #1534

**Comment by ivanfmartinez** [comment]
My handles just publish the coordinates from traccar to MQTT, its working in my system, but I have to refactor to make available in traccar, and will require paho as an extra library.

@pierrot10  is talking about getting coordinates into traccar.

I did not worked much with protocols to receive messages. A quick look at code show Protocol classes that instantiate TrackerServer to bind and receive connections. The MQTT should work as an client connected to the MQTT server, and the standard protocols in traccar are servers.

To receive data from an MQTT without doing many changes in traccar I suggest to create an script that gets data from MQTT and use an http protocol already implemented to inject the data in traccar.

Or maybe @tananaev  can give an easy hint how to attach one thread that will wait for mqtt data,  create the position object and push to traccar processing.

**Comment by rodrigocastrillon** [comment]
Hello, did anyone get any progress? Integration with MQTT would greatly increase adoption as it could as well handle IoT devices publishing places temperature, for instance. However this would demand many changes in the code. 
I am interested in help on this matter. I will try to build some kind of publisher so traccar can publish what the GPS protocols receives to MQTT servers. This would be a start.

@ivanfmartinez, do you mind sharing what you have? I can try to build an integration .

PS. I would do hanged in the fork I have.

**Comment by jpmens** [comment]
It seems unlikely to me that Traccar can be made to consume MQTT messages from a broker, but I admit to knowing very little of Traccar's architecture.

We have recently been doing experiments with OwnTracks, and we've provided an [owntracks protocol decoder](https://github.com/tananaev/traccar/pull/3242) which was merged into Traccar; this can be fed either directly from OwnTracks apps or via something which subscribes to MQTT and can then submit HTTP requests (e.g. mqttwarn).

On the other hand, using position forwarding, Traccar can submit, via HTTP, device positions and that can, relatively easily, be translated into OwnTracks-compatible MQTT message publishes.

As much as I'd like to see MQTT as a first-class Traccar I/O thing, I don't know if it's feasable.

**Comment by rodrigocastrillon** [comment]
It is good to know that more people are interested in this. I will reseach the api docs and the code to see how publish the data to a broker. I want that traccar is able to forward all events and gps/odb data into a broker so this data can be used later, to connect to nodered, Twilio, etc
Thanks for the feedback

**Comment by leifnel** [comment]
I have used this php to enter data into traccar, by emulating a TK101.
You can combine this with a php-mqtt library of your choice.

`   

    function sendToTraccar($devid,$time,$latitude,$longitude); 
      $date=date_create($time); 
  
      $gpmrc=sprintf("GPRMC,%s,A,%09.4f,N,%010.4f,E,0.00,0.00,%s,,,A", 
        date_format($date,"His.v"), 
        toNmea($latitude), 
        toNmea($longitude), 
        date_format($date,"dmy"));
      $xs=xorsum($gpmrc);
      $part1=sprintf("%s,%s*%X,F,imei:%015s","12345",$gpmrc,$xs,$devid);
      $str=sprintf("%s,%s,%d",date_format($date,"ymdHis"),$part1,strlen($part1));

      $fp = fsockopen("tracker.example.com", 5006, $errno, $errstr, 30);
      if (!$fp) {
          echo "$errstr ($errno)<br />\n";
      } else {
          fwrite($fp, $str);
          fclose($fp); // To close the connection
      }
    }

    function toNmea($deg) {
      $i=floor($deg);
      $p=$deg-$i;
      return(100*$i+60*$p);
     }
     function xorsum($data)
     {
       $crc = 0x00;
       for ($i = 0; $i < strlen($data); $i++)
       {
         $crc = ($crc ^ ord($data[$i])) & 0xFF;
       }
       return $crc;
     }
`
To enter data into traccar I use this. I have omitted the datasource; it is json, in $data, hopefully self-explanatory:

`   

    function sendToTraccar($devid,$time,$latitude,$longitude); 
      $date=date_create($time); 
  
      $gpmrc=sprintf("GPRMC,%s,A,%09.4f,N,%010.4f,E,0.00,0.00,%s,,,A", 
        date_format($date,"His.v"), 
        toNmea($latitude), 
        toNmea($longitude), 
        date_format($date,"dmy"));
      $xs=xorsum($gpmrc);
      $part1=sprintf("%s,%s*%X,F,imei:%015s","12345",$gpmrc,$xs,$devid);
      $str=sprintf("%s,%s,%d",date_format($date,"ymdHis"),$part1,strlen($part1));

      $fp = fsockopen("tracker.example.com", 5006, $errno, $errstr, 30);
      if (!$fp) {
          echo "$errstr ($errno)<br />\n";
      } else {
          fwrite($fp, $str);
          fclose($fp); // To close the connection
      }
    }

    function toNmea($deg) {
      $i=floor($deg);
      $p=$deg-$i;
      return(100*$i+60*$p);
     }
     function xorsum($data)
     {
       $crc = 0x00;
       for ($i = 0; $i < strlen($data); $i++)
       {
         $crc = ($crc ^ ord($data[$i])) & 0xFF;
       }
       return $crc;
     }
`

**Comment by tsmgeek** [comment]
@leifnel why not use osmand protocol?

**Comment by tsmgeek** [comment]
I was thinking about the SmppClient, this seems to maintain some sort of background connection to a Smpp server.
Something similar for MQTT in Java - https://www.eclipse.org/paho/clients/java/
May be some pointers to get this supported.

**Comment by leifnel** [comment]
@tsmgeek You are welcome to write an osmand interface. Mine works, so I won't bother rewriting it ;-)

**Comment by biskandar** [comment]
I just wonder is there any open standard protocol for gps tracking instead of MQTT ?

**Comment by tananaev** [comment]
There is OpenDMTP, but nobody uses it. If you need a simple protocol I would recommend OsmAnd:

https://www.traccar.org/osmand/

Quite a few tracking apps, including Traccar Client, are using it.

**Comment by ivanfmartinez** [comment]
For anyone interested in testing my handler for publishing data on mqtt : https://github.com/ivanfmartinez/ivanfm-traccar-mqtt

**Comment by jsponz** [comment]
Any idea how to install it? 

@ivanfmartinez It would be great if you could explain it.

**Comment by ivanfmartinez** [comment]
> Any idea how to install it?
> 
> @ivanfmartinez It would be great if you could explain it.

You have to compile and add to classpath and configure as in : https://github.com/ivanfmartinez/ivanfm-traccar-mqtt/blob/master/README.md

**Comment by tananaev** [comment]
We do support some MQTT based protocols now.
