### ISSUE TITLE
Problem with SQL Server 2012

### ISSUE THREAD

**Issue by a7medma7moud** [traccar/traccar#1587]
Hi,
I downloaded server source code and I tried to connect with SQL Server ,
So, What are the corrects steps that I should to do to make the source code listen correctly to traccar client application (android version) and store the received data in data base and what should I do on SQL server 

Thanks a lot

**Comment by tananaev** [comment]
You need to provide config file as a command line argument.

As for SQL Server, you can find config info here:

https://www.traccar.org/ms-sql/
