### ISSUE TITLE
no gps cordenates using tk103 protocol

### ISSUE THREAD

**Issue by jcroman-itch** [traccar/traccar#1604]
Hi anton
I bought Vjoy model T500 gps tracker and I tried to connect it to my own server with tracker 3.2 version, the device is using tk103 protocol by port 5002.
I can see only the offline status but the gps coordinates are Lat:0000,Lon:000.
I follow your instructions for chinese trackers but it seems nothing happen.

I hope you can help me

[gps_vacas.txt](https://github.com/tananaev/traccar/files/65900/gps_vacas.txt)

**Comment by tananaev** [comment]
I guess device doesn't have a GPS fix yet. Not that GPS doesn't work indoors and first GPS fix can take 15 or more minutes.

**Comment by jcroman-itch** [comment]
So you say is no tk103 protocol bug?
You think is the gps tracker configuration?
The Vjoy seller told me that the T500 tracker used the same protocol than others trackers like T4400 or T8800.

**Comment by tananaev** [comment]
It's not a protocol issue.
