### ISSUE TITLE
Traccar + GT06

### ISSUE THREAD

**Issue by apeman76** [traccar/traccar#1605]
Hello Traccar, my GT06 tracker isn't working

Today I recieved my GT06, and connected it but I keep having errors

The error codes : http://pastebin.com/5YQrkNwg

I use stock installation, no configs edited. Only set web page to port 8080
The HEX decoder isnt really giving any information from the HEX

**Comment by tananaev** [comment]
I don't see any errors. Everything is working fine as far as I can tell.

**Comment by Hoekynl** [comment]
Oh, so those debug lines aren't errors? And these lines? http://pastebin.com/ePbMjRux

**Comment by tananaev** [comment]
Please ignore any `AsyncSession` logging. It's just debugging information.

**Comment by Hoekynl** [comment]
Okay, thanks! It works now. The GT06 is located correctly. I just need the command for data send interval. (TIMER,300# Doesn't work.) Do you know that command?

**Comment by tananaev** [comment]
Unfortunately I don't know. Maybe someone who has the device can help you.

**Comment by Hoekynl** [comment]
Do you by accident, know a device that uses commands like #IP#password#<ServerIP>#<port>#?

**Comment by tananaev** [comment]
No, sorry. You can try to search GitHub issues to see if someone mentioned something similar.

**Comment by jamejo** [comment]
For Timer if its GT06 then the command is (TIMER,5,5#) Where minimum value is in seconds 5,

And for your second query #IP#password#ServerIP#port#? (Seems like a TK range of device) maybe Tk103 or TK06

**Comment by kuldiplive** [comment]
Yes its TK06A, It will work on ConCox protocol . I have attached user manaul
[TK06A_Old.pdf](https://github.com/tananaev/traccar/files/75862/TK06A_Old.pdf)

**Comment by kuldiplive** [comment]
@jamejo for GT06 models leave timer default , even time zone in older gt06 it had many issues .
It would stop sending DATA upon changing its parameters .

New GT06N does not have that issue any more.
