### ISSUE TITLE
Send GPRS Command - Query

### ISSUE THREAD

**Issue by alltimeashu** [traccar/traccar#1607]
Hi,

I am currently using traccar server 2.xx with my own web interface. I would like to implement send gprs command feature. can you guide me which source code version i can download and what modification required in mysql database. i assume that there would be separate table for the gprs command and traccar server will pick up the command from the table and send to the device and update back record in same table.
Please guide me on this.

Thanks,
Ashutosh

**Comment by tananaev** [comment]
That's not how commands work. Commands are send directly without going through database.

**Comment by alltimeashu** [comment]
Oh.. then how to send command. Do tracker server have any command line or any other method to send command?

**Comment by tananaev** [comment]
There is a web API to send commands:

https://www.traccar.org/traccar-api/

**Comment by alltimeashu** [comment]
ok. so i believe that the current send command is always response true and not provide actual data return from the device after command executed successfully. i mean, traccar is not waiting for the response from device after command sent to the device right?

**Comment by alltimeashu** [comment]
Is it possible to use this API from my own web interface. as i m using traccar server only and web interface is developed separately. any document or comments how i can call api from my web interface.

**Comment by tananaev** [comment]
Correct, Traccar is not waiting for response.

You can use Traccar API from your own web interface. See the link above and you can also check source code as well.

**Comment by alltimeashu** [comment]
Thanks for the detail tananaev. it would be great if you can give me simple example, how i can call this api from my jsp or servlet page (my web interface is spring based jsp/servlet application). thanks.

**Comment by tananaev** [comment]
Not sure what you want me to show. You can try to run default web interface and see what commands it sends via browser developer console.
