### ISSUE TITLE
Traccar stops receiving data after initial few updates

### ISSUE THREAD

**Issue by v920749** [traccar/traccar#1608]
I ran traccar without issue till 20 devices and now I have around 50 devices on it. Strangely when I restart traccar, all the newly added devices are updated in traccar database with latest position and after that it just doesn't work. Initially added devices work as expected though.  As many times I restart traccar I am able to get latest position from these devices but just single record and sometime 4 5 in whole day. I have set server update frequency in device properly.

**Comment by tananaev** [comment]
What devices are you using?

**Comment by v920749** [comment]
protocol coloumn says tk103.

**Comment by v920749** [comment]
2015-12-18 13:44:02 DEBUG: [923909B1: 5002 > 223.225.133.219] HEX: 283032373034333435343836374150303148534f29
2015-12-18 13:44:02 DEBUG: [923909B1: 5002 < 223.225.133.219] HEX: 283032373034333435343836374252303031353132313841323932382e383235334e30373530332e32323530453036312e373038313335313133362e393930303030303030304c303030303030303029
2015-12-18 13:44:02  INFO: [923909B1] id: 39, time: 2015-12-18 13:43:51, lat: 29.48042, lon: 75.05375, speed: 33.3, course: 137.0


One and only data point thats collected after restart, after this it goes dark.

**Comment by v920749** [comment]
Tried to debug it further, pointed it to a nodejs server https://github.com/freshworkstudio/gps-tracking-nodejs,  it looks like "login_request" is not sent by device, is it normal or issue with device? but how come first data point gets recorded?

**Comment by v920749** [comment]
Adding more inputs: device id decoded by traccar is 027043454867 and by nodejs is 027043492768.

**Comment by tananaev** [comment]
You must be looking at two different devices.

**Comment by v920749** [comment]
Please ignore the last input. Issue still persists. May be its specific to my case. Would appreciate any pointers to help me resolve it.

**Comment by tananaev** [comment]
Maybe device waits for some kind of response? Do you have protocol documentation?

**Comment by v920749** [comment]
For anyone coming to this thread with same problem. in  the command for setting frequency  timer,666666,,30#  notice the double coma. If you miss this, it goes all wrong.

@tananaev  is an amazing person helping a lot of people with this awesome software. Thanks for your time.
