### ISSUE TITLE
Does traccar support TK303-B?

### ISSUE THREAD

**Issue by KumarK80** [traccar/traccar#1684]
Hi,

I am planning to buy GPS tracking device - TK303-B (http://www.amazon.com/RioRand-Vehicle-Tracker-Gps303b-Quad-band/dp/B00MGIC4NU) Can you please let me know whether traccar support this device. I searched in the device list but did not find this one being listed.

Thank you in advance

**Comment by tananaev** [comment]
Most likely Traccar already supports it, but to be absolutely sure I need protocol documentation to verify. This page may be useful for you:

https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/

**Comment by erickdeoliveiraleal** [comment]
any news on this issue?

**Comment by tananaev** [comment]
I haven't received the documentation, but suggestion is still the same as in my previous comment.

**Comment by erickdeoliveiraleal** [comment]
so, I can just setup it just like a tk103?

**Comment by tananaev** [comment]
Yes, but the port might be different. See the link above.

**Comment by veniciosn** [comment]
It works on port 5001. GPS103 protocol. No flaws until now.

**Comment by Haezal** [comment]
Hi veniviosn,
Are you talking about gps TK303 right?

**Comment by SebastEnn** [comment]
Since @veniciosn approved functionality, the device (TK303B, with the same config as TK303G) could be added to [list of supported devices](https://www.traccar.org/devices/).

This issue could then be closed.
