### ISSUE TITLE
Translation of english texts in pop-Up Window to Spanish..

### ISSUE THREAD

**Issue by crarchile** [traccar/traccar#1687]
Dear Anton

How can I translate the english words shown on the image to spanish language?

![image](https://cloud.githubusercontent.com/assets/11233964/12566803/5e7c9126-c39a-11e5-9faa-ac81a898a243.png)

Regards,

Carlos

**Comment by tananaev** [comment]
Additional parameters are not translated at the moment. The only option would be to rename those parameters in Java code:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/model/Event.java#L23

**Comment by superservidor** [comment]
I have done the translation to spanish sucessfully 

![image](https://cloud.githubusercontent.com/assets/11233964/12570134/b8c3f4ee-c3b3-11e5-9aef-31975f0f4080.png)

The translated text is below:

    // Words separated by dashes (word-second-third)
    public static final String KEY_INDEX = "index";
    public static final String KEY_HDOP = "hdop";
    public static final String KEY_SATELLITES = "Satelites";
    public static final String KEY_GSM = "Gsm";
    public static final String KEY_GPS = "Gps";
    public static final String KEY_EVENT = "Evento";
    public static final String KEY_ALARM = "Alarmas";
    public static final String KEY_STATUS = "Estado";
    public static final String KEY_ODOMETER = "Odometro";
    public static final String KEY_INPUT = "Entradas-Activas";
    public static final String KEY_OUTPUT = "Salidas-Activas";
    public static final String KEY_POWER = "Energia";
    public static final String KEY_BATTERY = "Bateria";
    public static final String KEY_MCC = "Mcc";
    public static final String KEY_MNC = "Mnc";
    public static final String KEY_LAC = "Lac";
    public static final String KEY_CELL = "Cell";
    public static final String KEY_FUEL = "Combustible";
    public static final String KEY_RFID = "Rfid";
    public static final String KEY_VERSION = "Version";
    public static final String KEY_TYPE = "Tipo";
    public static final String KEY_IGNITION = "Ignicion";
    public static final String KEY_FLAGS = "Modificadores";
    public static final String KEY_CHARGE = "Carga-de-Bateria";
    public static final String KEY_IP = "Direccion-IP";
    public static final String KEY_ARCHIVE = "Archivo";
    public static final String KEY_DISTANCE = "Distancia";
    public static final String KEY_DOOR = "Puerta";
    public static final String KEY_RPM = "Rpm";
    public static final String KEY_HOURS = "Horas";
    public static final String KEY_VIN = "Vin";
    public static final String KEY_OBD_SPEED = "Velocidad-Odb";
    public static final String KEY_OBD_ODOMETER = "Odometro-Odb";
    public static final String PREFIX_TEMP = "Temperatura";
    public static final String PREFIX_ADC = "Conversor-Analogo-Digital";
    public static final String PREFIX_IO = "Entrada-Salida";
    public static final String PREFIX_COUNT = "Contador";

Thanks.

**Comment by tananaev** [comment]
Well, you need to compile your custom version now:

https://www.traccar.org/build/

**Comment by superservidor** [comment]
Anton,

I already made the compilation (BUILD) of v3.2 with no errors and now the pop-up is showing the texts translated to spanish OK.

Thanks again.

**Comment by SebastEnn** [comment]
Problem solved and since UI got overhauled, translations were added.

This issue can be closed.
