### ISSUE TITLE
traccer server

### ISSUE THREAD

**Issue by emrahtuna** [traccar/traccar#1702]
hi i traccar server, you could not help wonder if you want to build your own: www.mysite.com/guppy/

**Comment by tananaev** [comment]
Link doesn't work.

**Comment by emrahtuna** [comment]
http://aractakip.ekonomikinternet.com.tr/ my site

**Comment by tananaev** [comment]
What's the question? Do you want to install Traccar on your own server? If yes, just follow the instructions from the official website. You need a VPS. Regular shared hosting won't be enough.

**Comment by emrahtuna** [comment]
VPS is working in my locale you want to install myself , but entering my ip number does not work outside

**Comment by emrahtuna** [comment]
If you want I can send mail as the VPS information

**Comment by tananaev** [comment]
My email address is in GitHub profile if you want to send details.

**Comment by tananaev** [comment]
Your don't even have Traccar installed on your server.

**Comment by emrahtuna** [comment]
How do I add Turkish language pack and play in the android source code gives an error I would draw

**Comment by tananaev** [comment]
You can add Turkish localization to the web interface here:

https://www.transifex.com/traccar/traccar

What is the error with Android source code?

**Comment by SebastEnn** [comment]
I guess he installed it successfully... or since his domain doesn't exists anymore he gave up?

Issue can be closed.
