### ISSUE TITLE
Using MySQL

### ISSUE THREAD

**Issue by tufanbhattarai** [traccar/traccar#1707]
Hello tananaev, I tried to configure the traccar project using mysql database. The project builds successfully but during run time, it generates the following error. I am using netbeans IDE for development. Could you please guide me through this? I would be pleased.  
![project_error](https://cloud.githubusercontent.com/assets/15609332/12871855/cf6e8f54-cdb5-11e5-8937-b0be247a802d.JPG)

**Comment by tananaev** [comment]
Java class names are case-sensitive. Driver name should be `com.mysql.jdbc.Driver`.

**Comment by tufanbhattarai** [comment]
OH..shame on me..thank you for your reply .

**Comment by tufanbhattarai** [comment]
Should i delete the dependency from the pom.xml file for h2 database if i want to use mysql?

**Comment by tananaev** [comment]
You can if you want to save some space, but you don't have to. You can also remove postgresql driver from dependencies as well.

**Comment by SebastEnn** [comment]
Issue solved. Can be closed.
