### ISSUE TITLE
Traccar database model and logic possible improvement.

### ISSUE THREAD

**Issue by hackerunet** [traccar/traccar#1715]
Hi anton, as you requested, I opened up a new issue regarding traccar logic and possible logic re engineering.
As I told you before I did several changes to my traccar installation, I added more stored procedures to be able to handle variable table names, my concept or idea was originally to distribute the target table to store all devices positions, so what I did was create a procedure to do this:

```
INSERT INTO positions_$variable VALUES (A,B,C,D,E,F,G);
```

That way instead of having a single table with all positions of all devices I can have a table per device so performance for querying historical information won't impact the database engine because is not the same look a needle in a stack or look the stack where the needle belongs to.
So, as far as i know mysql doesn't allow variable table names in a query, so is there a way to implement variable table names using traccar.xml configuration file?
If this is possible i think performance issues will be solved for ever.
I used to have the original single table positions with all positions but server performance is highly decreased for querying a table with large number of records.
What do you think about this?
regards.

**Comment by tananaev** [comment]
You can have a dynamic query in the configuration file that would write data into different tables depending on the device id, so it's possible.

My opinion is that it's not the right solution though. Database engine should take care of big amounts of data. That's what they are for. If you have correct indexing and clustering, there should be no difference in performance between using different tables and a single table.

**Comment by hackerunet** [comment]
I understand, how do you think can be possible to implement dynamic queries in the configuration file?
well, I did that because when I started using traccar I attached 1000 vehicles to the system with the original traccar version and it was impossible to build a report because the database engine couldn't handle so many records, so when I split everything in distributed tables the database engine recovered itself and everything started behaving much much better, that's what happened 3 years ago.

**Comment by tananaev** [comment]
Here is an example of dynamic query that inserts data into different tables for each device id:
```
<entry key='database.insertPosition'>
    set @sql = concat('insert into gs_tracker_data_', :device_id, ' (dt_server, dt_tracker, lat, lng, altitude, angle, speed, params) values (?, ?, ?, ?, ?, ?, ?, "")');
    prepare stmt from @sql;
    set @time = :time; set @lat = :latitude; set @lon = :longitude; set @alt = :altitude; set @course = :course; set @speed = :speed;
    execute stmt using @time, @time, @lat, @lon, @alt, @course, @speed;
    deallocate prepare stmt;
</entry>
```

**Comment by hackerunet** [comment]
Awesome, I'm going to fix a couple of things, remove 4 store procedures and try to get closer to the traccar standard to minimize differences how system treats information.
regards, let me implement this and update the case, if it work I'll let you know to close this.

**Comment by bpali** [comment]
Hello there
Any news on the topic?
I'm interested too into getting a working dynamic query for inserting positions into a separate table for each device. I'm using traccar 3.14 and I've added the following to my ```conf/traccar.xml``` file

    <entry key='database.insertPosition'>
        set @sql = concat('insert into gs_tracker_data_', :device_id, ' (dt_server, dt_tracker, lat, lng, altitude, angle, speed, params) values (?, ?, ?, ?, ?, ?, ?, "")');
        prepare stmt from @sql;
        set @time = :time; set @lat = :latitude; set @lon = :longitude; set @alt = :altitude; set @course = :course; set @speed = :speed;
        execute stmt using @time, @time, @lat, @lon, @alt, @course, @speed;
        deallocate prepare stmt;
    </entry>

but it is not working and this is the error i get into the logs afterwards

    2017-09-29 11:44:58  WARN: No value specified for parameter 1 - SQLException (... < QueryBuilder:477 < DataManager:327 < DefaultDataHandler:27 < ...)

**Comment by tananaev** [comment]
There is no `:device_id` parameter.

**Comment by bpali** [comment]
Thanks for the reply
Where can I get a list of the available parameters at insert position?

**Comment by tananaev** [comment]
Parameter names match names of Java properties.

**Comment by bpali** [comment]
@hackerunet would you be so kind to send me over the solution you are using for this?

**Comment by hackerunet** [comment]
Sure, today i'll send it to you, im at work but you can count on it!!

**Comment by bpali** [comment]
thanks @hackerunet !

write it here or email it to me at: bogdan[at]pbogd.ro

**Comment by bpali** [comment]
I have finally got my working solution for traccar 3.14

I need to mention for other users that this solution is only good if you're using traccar only as an engine and not using any web interface feature

following si to be added to ```traccar/cont/traccar.xml```
```
    <entry key='database.insertPosition'>
        set @sql = concat('INSERT INTO positions_', :deviceId, ' (protocol, deviceid, servertime, devicetime, fixtime, valid, latitude, longitude, altitude, speed, course, address, attributes, accuracy, network) (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');
        prepare stmt from @sql;
        set @protocol = :protocol;
        set @deviceId = :deviceId;
        set @serverTime = :serverTime;
        set @deviceTime = :deviceTime;
        set @fixTime = :fixTime;
        set @valid = :valid;
        set @latitude = :latitude;
        set @longitude = :longitude;
        set @altitude = :altitude;
        set @speed = :speed;
        set @course = :course;
        set @address = :address;
        set @attributes = :attributes;
        set @accuracy = :accuracy;
        set @network = :network;
        execute stmt using @protocol, @deviceId, @serverTime, @deviceTime, @fixTime, @valid, @latitude, @longitude, @altitude, @speed, @course, @address, @attributes, @accuracy, @network;
        deallocate prepare stmt;
    </entry>
```

and you will have each device positions in its own positions_[deviceId] table.
These tables you need to create and manage by your own.

**Comment by pinakin7664** [comment]
hello  hackerunet

pls send me this dynamic query code so i will implement in my system
my email id : pinakin7664@gmail.com

**Comment by jvmvl** [comment]
@tananaev Is this not working in newer versions? if not how to we get it back please?

**Comment by tananaev** [comment]
It's not possible on newer versions. And there's no easy way to bring it back.

But again, as I explained before, this is not the right solution to the problem.

**Comment by jvmvl** [comment]
> It's not possible on newer versions. And there's no easy way to bring it back.
> 
> But again, as I explained before, this is not the right solution to the problem.

The thing is you still haven't explained why it's not the right solution, because as i see it it's a good solution when you have tons of devices let's say just 100 and each of these devices send data each day for one month that would be huge for just one table, so you'll be forced to either delete the data or backup it up and you have to do it on a daily basis. So please tell me how is this a good solution?

**Comment by tananaev** [comment]
The good solution is to do proper partitioning on the database side. That way you can have separate files per device or whatever you want, but from Traccar point of view, it still looks like a single table.

**Comment by jvmvl** [comment]
Thank you @tananaev
