### ISSUE TITLE
How to know current time?

### ISSUE THREAD

**Issue by zizango123** [traccar/traccar#1758]
Anyway to know the current time on the device?

**Comment by tananaev** [comment]
What device are we talking about? Usually devices send timestamp and you can see latest report in the status panel including device time.

**Comment by zizango123** [comment]
its a gt06 concox device. I know it sends timestamp but how is the timestamp determined as the current timestamp without the current time. I just want to know the current time of the device to see whether the timestamp sent is correct or not.

**Comment by tananaev** [comment]
What do you mean by "current timestamp without the current time".

**Comment by zizango123** [comment]
the device sends a timestamp right!! What i want to know is the date time used by the device in generating the timestamp sent

**Comment by tananaev** [comment]
It still doesn't make much sense to me. Device already sends time, but you want it to send time. How else can you see the time? Do you want it to send it different format or something?

**Comment by zizango123** [comment]
it sends the time but in which timezone is it being sent and is the time being sent correct. That is what i want to know

**Comment by tananaev** [comment]
I can check if you provide some message samples.

**Comment by OzWookiee** [comment]
Can I assume that maybe the device sends the timestamp _without_ the timezone? e.g.
imei:868683022206050,tracker,160317164342,,F,064339.000,A,3748.9143,S,14518.3287,E,31.51,10.05;
^^-data from a gp103

160317164342 <- timestamp _without_ timezone

**Comment by tananaev** [comment]
@OzWookiee, GPS103 protocol includes local date and time (`160317164342` in your example) and also GMT time (`064339.000` in your example).

**Comment by SebastEnn** [comment]
Question answered. Issue can be closed.
