### ISSUE TITLE
Inconsistencies in Database data

### ISSUE THREAD

**Issue by santosharjun** [traccar/traccar#1762]
We has setup traccar with OpenGTS and have approx 300 devices running. 
Server config is: 4 cores, 28GB RAM, Azure server (D12) with SSD Hard disk

Two issues are coming frequently:

1) We have added a query in traccar.xml for calculating distance/odometer. This sometimes shows higher values than original distance. once we scaled up server this has come down but as we add devices it is again showing same errors in distance calculation.

2) As you can see below, latitude/longitude of device had changed to different city only for one record

Date                    Time    Status  Lat/Lon   Speedkm/h Altitude meters OdometerKm  
7   2016/03/01  23:59:40    Stopped 17.66028/83.19928   0       0   1050  
**8 2016/03/02  00:00:45    Stopped 17.34442/78.57821   0       0   428**  
9   2016/03/02  00:01:40    Stopped 17.66027/83.19937   0       0   1050  
10  2016/03/02  00:03:40    Stopped 17.66027/83.19932   0       0   1050  
11  2016/03/02  00:05:41    Stopped 17.66025/83.19933   0       0   1050  
**12    2016/03/02  00:05:45    Stopped 17.34442/78.57821   0   0   1541**  
13  2016/03/02  00:07:41    Stopped 17.66027/83.19932   0       0   1050     

Any ideas on how to fix these issues?

**Comment by tananaev** [comment]
1) Are stops filtered on the server? If not, that might cause extra distance.

2) What device is it? I need original HEX messages to check if it's device or server problem.

**Comment by santosharjun** [comment]
1) stops are filtered out but we see more distance for a certain pair for of long/lats. If we run the query separately on our laptop on same data, distance is correct.  

2) Hex data is given below:
Grep in the log files with given IMEI number

tracker-server.log.20160301:2016-03-01 23:57:42  INFO: [F55D12E0] id: 4209012984, time: 2016-03-01 23:59:40, lat: 17.66028, lon: 83.19928, speed: 0.0, course: 0.0
tracker-server.log.20160301:2016-03-01 23:59:42 DEBUG: [F55D12E0: 5013 < 106.220.48.56] HEX: 2442090129841831400103161739616006083119620e000000fffffbffff001d00000000a10194310000000031
tracker-server.log.20160301:2016-03-01 23:59:42  INFO: [F55D12E0] id: 4209012984, time: 2016-03-02 00:01:40, lat: 17.66027, lon: 83.19937, speed: 0.0, course: 0.0
tracker-server.log.20160301:2016-03-01 23:59:55  INFO: [F55D12E0] id: 4209012984, time: 2016-03-02 00:01:51, lat: 17.66028, lon: 83.19937, speed: 0.0, course: 0.0
tracker-server.log.20160302:2016-03-02 00:01:43 DEBUG: [F55D12E0: 5013 < 106.220.48.56] HEX: 2442090129841833400103161739616006083119590e000000fffffbffff001d00000000a10194310000000032
tracker-server.log.20160302:2016-03-02 00:01:43  INFO: [F55D12E0] id: 4209012984, time: 2016-03-02 00:03:40, lat: 17.66027, lon: 83.19932, speed: 0.0, course: 0.0
tracker-server.log.20160302:2016-03-02 00:02:54  INFO: [F55D12E0] id: 4209012984, time: 2016-03-02 00:04:52, lat: 17.66026, lon: 83.19935, speed: 0.0, course: 0.0
tracker-server.log.20160302:2016-03-02 00:03:43 DEBUG: [F55D12E0: 5013 < 106.220.48.56] HEX: 2442090129841835410103161739615006083119600e000000fffffbffff001d00000000a10194310000000033
tracker-server.log.20160302:2016-03-02 00:03:43  INFO: [F55D12E0] id: 4209012984, time: 2016-03-02 00:05:41, lat: 17.66025, lon: 83.19933, speed: 0.0, course: 0.0
tracker-server.log.20160302:2016-03-02 00:05:44 DEBUG: [F55D12E0: 5013 < 106.220.48.56] HEX: 2442090129841837410103161739616006083119590e000000fffffbffff001d00000000a10194310000000034
tracker-server.log.20160302:2016-03-02 00:05:44  INFO: [F55D12E0] id: 4209012984, time: 2016-03-02 00:07:41, lat: 17.66027, lon: 83.19932, speed: 0.0, course: 0.0
tracker-server.log.20160302:2016-03-02 00:05:54  INFO: [F55D12E0] id: 4209012984, time: 2016-03-02 00:07:51, lat: 17.66027, lon: 83.19932, speed: 0.0, course: 0.0
tracker-server.log.20160302:2016-03-02 00:07:45 DEBUG: [F55D12E0: 5013 < 106.220.48.56] HEX: 2442090129841839410103161739616006083119600e000000fffffbffff001d00000000a10194310000000035
tracker-server.log.20160302:2016-03-02 00:07:46  INFO: [F55D12E0] id: 4209012984, time: 2016-03-02 00:09:41, lat: 17.66027, lon: 83.19933, speed: 0.0, course: 0.0
tracker-server.log.20160302:2016-03-02 00:08:53  INFO: [F55D12E0] id: 4209012984, time: 2016-03-02 00:10:52, lat: 17.66028, lon: 83.19932, speed: 0.0, course: 0.0
tracker-server.log.20160302:2016-03-02 00:09:45 DEBUG: [F55D12E0: 5013 < 106.220.48.56] HEX: 2442090129841841430103161739616006083119570e000000fffffbffff001d00000000a10194310000000036

**Comment by tananaev** [comment]
1) What query are you talking about?

2) Log doesn't match you previous example.

**Comment by santosharjun** [comment]
1)   SELECT  @distance := 1.609344 * 3956 * 2 * ASIN(SQRT( POWER(SIN((@lastLatitude - :latitude) *  pi()/180 / 2), 2) +COS(@lastLatitude * pi()/180) * COS(:latitude * pi()/180) * POWER(SIN((@lastLongitude - :longitude) * pi()/180 / 2), 2) ));


2) yeah, it doesn't match. and facing these inconsistencies with data base. any pointers on how to debug this kind of issue?

**Comment by tananaev** [comment]
1) The query doesn't look right. Traccar already includes distance calculation functionality, so you can just use that.

2) If you haven't done any modifications to Traccar, what you see in the log should exactly match the database.

**Comment by santosharjun** [comment]
The issue is things are not present in log file and are appearing in DB. plus we hadn't made any changes except to traccar.xml

**Comment by tananaev** [comment]
What were the changes in the config?

**Comment by santosharjun** [comment]
<entry key='web.enable'>false</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>/opt/traccar/web</entry>



    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://localhost:3306/gts?allowMultiQueries=true</entry>
    <entry key='database.user'>root</entry>
    <entry key='database.password'>mmm123456m</entry>
    <entry key='gt06.resetDelay'>600</entry>


  SELECT * FROM traccar;
    </entry>

        <entry key='database.selectDevicesAll'>
        SELECT imeiNumber AS id, imeiNumber AS uniqueId FROM Device WHERE imeiNumber REGEXP '^[0-9]+$';
    </entry>

    <entry key="database.insertPosition">
        START TRANSACTION;
            SELECT @lastIgnitionValue := ignitionIndex, @statusCode := statusCodeState, @lastBatteryLevel := lastBatteryLevel,  @lastLatitude := lastValidLatitude, @lastLongitude := lastValidLongitude, @odometer := lastOdometerKM, @lastSpeedKPH := lastValidSpeedKPH FROM Device WHERE imeiNumber = :device_id;
        SET @alarmpos := LOCATE('alarm', :attributes) + 7;
        SELECT @ignitionval := CASE
           WHEN (@alarmpos &gt; 0) AND (SUBSTR(:attributes, @alarmpos, 1) = 't') AND SUBSTRING(:attributes, LOCATE('ignition', :attributes, @alarmpos) + 10, 1) = 't' THEN 1
           ELSE @lastIgnitionValue
        END;

        SELECT @powerval := CASE
           WHEN (@alarmpos &gt; 0) AND (SUBSTR(:attributes, @alarmpos, 1) = 't') THEN  SUBSTRING(:attributes, LOCATE('power', :attributes, @ignitionpos) + 7, 1)
        ELSE @lastBatteryLevel
        END;





        SELECT @statusCode := CASE
            WHEN (@lastIgnitionValue = 0) AND (@ignitionval =1) THEN 62465
            WHEN (@ignitionval =1) AND (:speed &lt; 3)THEN 61718
            WHEN (:speed &gt; 3) AND (@lastSpeedKPH &lt; 3) THEN 61713
            WHEN (:speed &gt; 3) AND (@lastSpeedKPH &gt; 3) THEN 61714
            WHEN (:speed &lt; 3) AND (@lastSpeedKPH &gt; 3) THEN 61715

            WHEN (:speed &lt; 3) AND (@lastSpeedKPH &lt; 3) THEN 61717
            ELSE 61717
        END;



        SELECT  @distance := 1.609344 * 3956 * 2 * ASIN(SQRT( POWER(SIN((@lastLatitude - :latitude) *  pi()/180 / 2), 2) +COS(@lastLatitude * pi()/180) * COS(:latitude * pi()/180) * POWER(SIN((@lastLongitude - :longitude) * pi()/180 / 2), 2) ));
 
        UPDATE Device SET ignitionIndex = @ignitionval, statusCodeState = @statusCode, lastBatteryLevel = @powerval, lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastOdometerKM = @odometer + @distance, lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastValidSpeedKPH = :speed, lastUpdateTime = UNIX_TIMESTAMP(NOW()) WHERE imeiNumber = :device_id;
            SELECT @accountID := accountID, @deviceID := deviceID FROM Device WHERE imeiNumber = :device_id;
            INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, distanceKM, odometerKM, creationTime)
            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:time), @statusCode, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', @distance, @odometer + @distance, UNIX_TIMESTAMP(NOW()));
        COMMIT;
    </entry>

**Comment by tananaev** [comment]
Your config is not a valid XML.

**Comment by santosharjun** [comment]
Can you expand a bit more, so that i can fix the issue?

**Comment by tananaev** [comment]
Can you please clean it up and remove comments. Currently it's unreadable.

**Comment by nokiado** [comment]
<entry key='database.insertPosition'>
    START TRANSACTION;
       
        SELECT @lastIgnitionValue := ignitionIndex,  @lastBatteryLevel := lastBatteryLevel, @accountID := accountID, @deviceID := deviceID, @lastSpeedKPH := lastValidSpeed, @lastLatitude := lastValidLatitude, @lastLongitude := lastValidLongitude, @odometer := lastOdometerKM FROM Device WHERE imeiNumber = SUBSTRING(CAST(:deviceId AS CHAR(32)), 2);
        
        SET @alarmpos := LOCATE('alarm', :attributes) + 7;

        SELECT @ignitionval := CASE
           WHEN (@alarmpos > 0) AND (SUBSTR(:attributes, @alarmpos, 1) = 't') AND SUBSTRING(:attributes, LOCATE('ignition', :attributes, @alarmpos) + 10, 1) = 't' THEN 1
           ELSE @lastIgnitionValue
        END;

        SELECT @powerval := CASE
           WHEN (@alarmpos > 0) AND (SUBSTR(:attributes, @alarmpos, 1) = 't') THEN  SUBSTRING(:attributes, LOCATE('power', :attributes, @ignitionpos) + 7, 1)
        ELSE @lastBatteryLevel
        END;

        SELECT @fakeStatus := CASE      	
           
		    WHEN (:speed &gt; 3) AND (@lastSpeedKPH &lt; 3) THEN 61713 
            WHEN (:speed &gt; 3) AND (@lastSpeedKPH &gt; 3) THEN 61714
            WHEN (:speed &lt; 3) AND (@lastSpeedKPH &gt; 3) THEN 61715
            WHEN (:speed &lt; 3) AND (@lastSpeedKPH &lt; 3) THEN 61472
            WHEN (@ignitionval =1) AND (:speed &lt; 3)THEN 61718
            WHEN (@lastIgnitionValue = 0) AND (@ignitionval =1) THEN 62465
            WHEN (@lastIgnitionValue = 1) AND (@ignitionval =0) THEN 62467
           	    
		END;
		
		SELECT  @distance := 1.609344 * 3956 * 2 * ASIN(SQRT( POWER(SIN((@lastLatitude - :latitude) *  pi()/180 / 2), 2) +COS(@lastLatitude * pi()/180) * COS(:latitude * pi()/180) * POWER(SIN((@lastLongitude - :longitude) * pi()/180 / 2), 2) ));

		SET @lastOdometer := @odometer + @distance;

		UPDATE Device SET ignitionIndex = @ignitionval,  lastBatteryLevel = @powerval, lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = UNIX_TIMESTAMP(:fixTime), lastUpdateTime = UNIX_TIMESTAMP(NOW()), lastValidSpeed = :speed * 1.852, lastOdometerKM = @lastOdometer   WHERE imeiNumber = SUBSTRING(CAST(:deviceId AS CHAR(32)), 2);

        INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, distanceKM, odometerKM, creationTime, address)
        VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:fixTime), @fakeStatus, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', @distance, @lastOdometer, UNIX_TIMESTAMP(NOW()), :address);
    COMMIT;
</entry>


my problem is the ignition and panic button does not recognize me  ,,,  any idea ?

**Comment by tananaev** [comment]
@nokiado for questions there is forum.
