### ISSUE TITLE
How to register a device which isn't in the list

### ISSUE THREAD

**Issue by noodgevallen** [traccar/traccar#1763]
Hi everyone..
Im trying to add a gps device to the traccar platform but i can't seem to get it right.
I'ts a personal alarm button which communicates to a server. The factory presets it to it's own platform but that's in chinese.. So not an option for europeans ;-)..

their server uses the imei number of the device to identify the device online and let it communicate over the standard portsettings of 5050.. We can change the server, but because the device isn't able to generate an traccar id we can't get it working on the platform..

Does anybody have a clue how to get it working? The device can be compared to a really simple automated GSM phone, using GPRS to connect to the server and transmit its coordinates to the server..

Hope someone has an opinion or a clue how to get it working

Thanks!!!!

**Comment by tananaev** [comment]
Does it send any data to Traccar? Check log files for HEX messages.

**Comment by noodgevallen** [comment]
Hi anton 
No because we cannot create an user number on the device so it doesn't connect to the server.. We can't add authentication in the communication protocol of the device it sends its imei as id but traccar doesn't accept it because it doesn't correspond

Met vriendelijke groet,

Martijn van der Veen


Op 4 maart 2016 12:54:17 +01:00, schreef Anton Tananaev <notifications@github.com>:

**Comment by tananaev** [comment]
So, it does send IMEI? Please provide HEX messages from log.

**Comment by SebastEnn** [comment]
Since the author didn't answered in the past 8 years and there's nothing to investigate, this issue can probably be closed.
