### ISSUE TITLE
change the encryption method

### ISSUE THREAD

**Issue by cadastro2005** [traccar/traccar#1777]
it would be possible to change the encryption method of sha1 to sha512?

thx

**Comment by tananaev** [comment]
It is possible, but I need a serious reason for that.

**Comment by SebastEnn** [comment]
I guess this is about the encryption algorithm of user passwords. 
If so, I pray that this has been changed. SHA1 is not that secure.

Then this issue can be closed.

**Comment by tananaev** [comment]
The author has not provided the full context. We use PBKDF2 with SHA1, which is still considered secure.
