### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by snoop168** [traccar/traccar#1784]
After some time of the server running we get the following error when attempting to load the webpage:
`Error 500
/opt/traccar/web/release.html (too many open files)`

**Comment by tananaev** [comment]
There are two things you should consider doing:

1. Increase the open files limit for Traccar service
2. Add `resetDelay` parameter to the config file for the protocol(s) that you use

**Comment by snoop168** [comment]
1. Can you point me where to do this? and is there a recommended number to use? Ie. should it be based on how many cars are listed or reporting gps at any given time or how many users are logging into the web interface?
2. basically same questions on `resetDelay`. What should a normal range be based on?

Thank you.

**Comment by tananaev** [comment]
1. Both. Each connection counts as an open file. It's an operating system setting.

2. The value is in seconds. I would recommend to pick a value slightly bigger than your device reporting interval.

**Comment by mani-rai** [comment]
Hello tananaev,

I am using traccar 3.5 release with around 71 devices. It's been months I am monitoring traccar behavior trying to find the solution to this problem. Our devices feed interval are set to 10 sec, I tried configuring resetDelay slightly higher this interval to 15 seconds. But with this configuration, "too many files open" error occurs within couple of days. Then I tried with 2 mins, this problem occurs in a week. And also I tried with 0 sec, its take couple of weeks to re-occur this problem.

I cannot understand why is this happening. Please help me out.

Thanks

**Comment by tananaev** [comment]
@mani-rai, what you are describing doesn't make any sense. The lower timeout you set, the longer it should be till you get to the limit (ideally never). I suspect you have some problem with config.

**Comment by mani-rai** [comment]
@tananaev, I am using devices of tk103 protocol. My additional configuration was just

`<entry key='tk103.resetDelay'>120</entry>`

And my user soft limit is 4000. Let me check with operating system limit once.

**Comment by tananaev** [comment]
You have it set up to 2 minutes. If your devices report every 10 seconds, it doesn't make sense to put such a long period.

Also, you should be using "timeout" parameter instead of "resetDelay". Both mean the same thing, but the second one will be eventually removed.

You should check file limit for the Traccar process.
