### ISSUE TITLE
Login using old API

### ISSUE THREAD

**Issue by hanselsen** [traccar/traccar#1787]
I'm trying to login onto my Traccar instance on my server, but I keep getting {"success":false} as a response.
The weird thing is that I CAN login to my local instance running in IntelliJ.
I'm using the web client of @vitalidze at https://github.com/vitalidze/traccar-web
I'm totally bumping against walls here. Can somebody help me?

Here is part of the server config (traccar.xml)

```
    <entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>/path/to/web</entry>
    <entry key='web.type'>old</entry>
    <entry key='web.application'>/path/to/traccar-web.war</entry> 
    <entry key='web.old'>true</entry>
```

Here is my local config (debug.xml)

```
    <entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.application'>/path/to/traccar-web.war</entry>
    <entry key='web.old'>true</entry>
    <entry key='web.type'>old</entry>
    <entry key='web.path'>web</entry>
    <entry key='web.debug'>true</entry>
    <entry key='web.console'>true</entry>
```

**Comment by tananaev** [comment]
Not related to the problem, but you can remove following lines:
```
<entry key='web.old'>true</entry>
<entry key='web.old'>true</entry>
```

As for the problem, maybe you just using wrong credentials?

**Comment by hanselsen** [comment]
Okay thanks. I can remove it, even though I'm using the web UI mod?

The credentials I'm using are correct. I double/triple checked.

Op di 15 mrt. 2016 22:02 schreef Anton Tananaev <notifications@github.com>:

**Comment by tananaev** [comment]
There is no difference in running server from IntelliJ and running in as a service. Try to add some logging to debug the problem.

**Comment by SebastEnn** [comment]
He probably found the problem. Issue can be closed.
