### ISSUE TITLE
I have this problem

### ISSUE THREAD

**Issue by leontino** [traccar/traccar#1793]
```
2016-03-16 00:06:01  WARN: [8E90A8B6] error - Connection reset by peer - IOException (...)
2016-03-16 00:06:01  INFO: [8E90A8B6] disconnected
```

**Comment by tananaev** [comment]
It means that device has disconnected from server.

**Comment by evigra** [comment]
Hello Tananaev,
I have the same problem.
It is presented, with all devices (14).
then, only appears offline (disconnected).
and does not update the positions.
on occasion, they spend 5 hours
I have to stop and start traccar
some cause ???

**Comment by tananaev** [comment]
It's not a problem. Actual problem must be with something else.

**Comment by SebastEnn** [comment]
Since it's not a problem, this is an issue that can be closed 🙂
