### ISSUE TITLE
tektonika fm1120 sw01.11.07.Rev.1.е как изменить название пунктов loXX

### ISSUE THREAD

**Issue by pivasik** [traccar/traccar#1795]
![carrrr](https://cloud.githubusercontent.com/assets/17912282/13857865/e5528af0-ec8c-11e5-99d5-c85dd098fb41.JPG)
как изменить название. И если это возможно единицы измерения
За ранее спасибо

**Comment by tananaev** [comment]
Пока только в коде можно поменять названия.

**Comment by pivasik** [comment]
Спасибо за быстрый ответ. А можно чуть поподробнее где именно копать языки я понял где менять а вот как менять те пункты которых там нет

**Comment by tananaev** [comment]
Если говорить конкретно про Teltonika, то параметры вот тут:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/TeltonikaProtocolDecoder.java

**Comment by pivasik** [comment]
Я конечно прошу прощение за глупые вопросы, я не совсем еще разобрался как собирать из исходников, а возможно изменять уже с установленного traccar.
И вопрос не по теме чем отличается сборка Виталия от вашей?

**Comment by tananaev** [comment]
Про сборку из исходников можно почитать тут:

https://www.traccar.org/build/

Сборка от Виталия это модифицированная версия старого веб интерфейса.

**Comment by pivasik** [comment]
Спасибо=) Не плохо бы было добавить возможность изменения в ваш интерфейс. Спасибо за ваши труды

**Comment by tananaev** [comment]
Попробую добавить как будет свободное время.

**Comment by SebastEnn** [comment]
Since translation were added, this issue can be closed.

**Comment by tananaev** [comment]
I don't think we added mapping for everything, but we have computed attributes now for this.
