### ISSUE TITLE
Send command from traccar to GPS (Stop/Resume Engine)

### ISSUE THREAD

**Issue by gilgzz18** [traccar/traccar#1796]
Hi Anton,

I'm trying to send JSON from an .html file to turn on or turn off the engine, but I try to have no more success.

This is my code in html

```
jQuery.ajax({
    type: "POST",
    url: "http://url:8082/api/command/send",
    dataType: "text",
    data: JSON.stringify({
        deviceId: 2,
        type: "positionStop"
    }),
    success: function (res) {           
        console.log("done");
        console.log(res);    
    }
});
```

</script>

Results in console.log:  {"success":false,"error":"Device access denied"}

In this image and analyze a little on the subject of receiving and sending responses via JSON, just that I can not do

![traccar_sendcommand](https://cloud.githubusercontent.com/assets/963630/13863912/11f72554-ec63-11e5-89ef-1d711acad474.png)

![traccar_sendcommand_1](https://cloud.githubusercontent.com/assets/963630/13863955/70d3e788-ec63-11e5-8b76-42ef1a86ada2.png)

Any help is welcome!

**Comment by tananaev** [comment]
It's code for old API. Please use new REST API:

https://www.traccar.org/traccar-api/

**Comment by gilgzz18** [comment]
Hi Anton,


Thanks for your answer , I apologize for my ignorance in swagger , I hope to continue to have your support and everyone in the forum to keep learning.


Swagger researching I found the following:

https://github.com/swagger-api/swagger-js

Calling an API with swagger + the browser!
Download browser/swagger-client.js into your webapp:

![swagger_1](https://cloud.githubusercontent.com/assets/963630/13886892/cb229a86-ecfe-11e5-95e6-c5d517905ef0.png)


I want to do something similar but in traccar and in this case to turn on or turn off the engine

I want the website to turn on or off the engine, for example with a click of a button html


Someone will have some example of how to interpret swagger - traccar from a Web browser

Thank you!

Best Regards,
Gilberto Gonzalez

**Comment by tananaev** [comment]
Swagger is basically API documentation. You don't have to use any specific tools or libraries to implement it.

If you want to look at query examples, you can capture requests sent by official web interface.

**Comment by gilgzz18** [comment]
Hi Anton,

I try send commands without officcial web because for internal process , now i understand more less the  swagger standard , but i can not send for example command "stop123456" via traccar without official web

Any example tnanks for advance!

Regards,

**Comment by tananaev** [comment]
I told to look at the official web interface for examples. You don't have to use it for your project. Just take examples from there.

**Comment by SebastEnn** [comment]
Advice given. Issue can be closed.
