### ISSUE TITLE
forward URL

### ISSUE THREAD

**Issue by mm108** [traccar/traccar#1811]
I have an online db into which data case be inserted using the following ajax call. Can I change the transform URL to do the same? Btw I also need the IMEI to be part of the position 

How do I get the IMEI to also be a part of gprmc data. I believe the uniqueId is the IMEI? Can I just move the things in bracket in a different way so as to achieve the url format shown in ajax call?

```
<entry key='forward.enable'>true</entry>
<entry key='forward.url'>http://example.com:8080/gprmc/Data?id={uniqueId}&amp;code=0x0000&amp;gprmc={gprmc}</entry>
```

```
$.ajax( { url: "https://api.domain.com/database/dbname/my-coll?apiKey=myAPIKey",
          data: JSON.stringify( { "x" : 1 } ),
          type: "POST",
          contentType: "application/json" } );
```

Thanks for the excellent response time & support
M.M

**Comment by tananaev** [comment]
Yes, `uniqueId` is IMEI (if device uses IMEI number as an id). Also, you don't have to use `gprmc` if you don't want to parse it. You can access to location attributes directly:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/WebDataHandler.java#L99

**Comment by m-menon** [comment]
You mentioned that "if device uses IMEI number as an id" ... do you mean there are devices where the ID is not IMEI? In that case when you add a new device, what is to be used for Identifier? That may depend on the device I guess but can you name any so that I can look it up to understand it better. Thanks

**Comment by tananaev** [comment]
For example most devices with TK103 protocol use 12-digit identifier instead of IMEI.

**Comment by m-menon** [comment]
oh alight, thanks :-)

**Comment by m-menon** [comment]
`<entry key='forward.url'>http://example.com:8080/gprmc/Data?id={uniqueId}&amp;code=0x0000&amp;gprmc={gprmc}</entry>`

Btw does the `&amp;code=0x0000&amp;` in the forward url example mean something?

**Comment by tananaev** [comment]
It's a status code for OpenGTS.

**Comment by m-menon** [comment]
ok thanks. and the uniqueId will "either" be the IMEI or the 12-digit identifier depending upon the device type I guess

**Comment by tananaev** [comment]
Yes. Some other types of devices can use other identifiers as well.

**Comment by m-menon** [comment]
cool thanks :+1:

**Comment by m-menon** [comment]
So any suggestion for "transforming" the forward url? Or do you think it would be best if I call another page on the web server, then manipulate the URL the way I want and then post it to the online db using ajax? Or could there be a better way? Thanks

**Comment by tananaev** [comment]
Well, I guess you need to write some code either way. You can just modify Traccar to send in the format that you need.

**Comment by m-menon** [comment]
okay, so if I just need to change the forward url to send the parameters in a json string, either with IMEI or the Identifier (whichever is available), which part of the code do I modify? Thanks

**Comment by tananaev** [comment]
I already provided a link above.

**Comment by m-menon** [comment]
right thanks but I only want the forward url format to be changed rest remaining the same

**Comment by tananaev** [comment]
Is there something wrong with the link I provided?

**Comment by m-menon** [comment]
well not really. I'll figure that out. Thanks

**Comment by m-menon** [comment]
btw forward.url is exected by a GET or POST request? Thanks

**Comment by tananaev** [comment]
By default it's GET as far as I remember.

**Comment by m-menon** [comment]
Yes thanks it is :-) https://github.com/tananaev/traccar/blob/master/src/org/traccar/WebDataHandler.java#L135

**Comment by kani-rifluxyss** [comment]
I was wondering why the positions not coming through GET or POST methods. We had specified only the URL for the script, did not include the parameters! :| Helped by the question details by @m-menon  
Thanks a lot.

@tananaev  and the great devs at Traccar, it may help new users if you could add a note about the URL parameters in the document for  "forward.url"

`https://www.traccar.org/configuration-file/`

Thanks again for the wonderful project!

**Comment by tananaev** [comment]
Updated documentation with some more info, thanks.

**Comment by kani-rifluxyss** [comment]
Awesome!!!

**Comment by m-menon** [comment]
Amazing support as always :+1:

**Comment by SebastEnn** [comment]
Documentation got enhanced. Issue can be closed.
