### ISSUE TITLE
Google geocoder

### ISSUE THREAD

**Issue by mm108** [traccar/traccar#1812]
I believe traccar uses Google APIs for looking up the address I guess. Is there a need to sign up or add an Google API key or something if this volume increases? If yes where do I put in the API key? Thanks

**Comment by tananaev** [comment]
Some info here:

https://www.traccar.org/reverse-geocoding/

With next release there will be an option to add API key to increase the limit.

**Comment by m-menon** [comment]
Ok thanks

**Comment by SebastEnn** [comment]
Question answered. Issue can be closed.
