### ISSUE TITLE
Listen 8082 is required?

### ISSUE THREAD

**Issue by mm108** [traccar/traccar#1814]
I have set my Apache to only listen on LAN IP and I do a routing from my public gateway. Do I need to set Listen 8082 in the ports.conf or is it not really needed? Thanks

I am referring to this ssl set up [here](https://www.traccar.org/secure-connection/)

**Comment by tananaev** [comment]
No, you don't need port 8082 in Apache ports config.

**Comment by m-menon** [comment]
cool thanks

**Comment by SebastEnn** [comment]
Question answered. Issue can be closed.
