### ISSUE TITLE
Zooming to devices

### ISSUE THREAD

**Issue by ghost** [traccar/traccar#1819]
If a device is selected on the devices pane, and we move the map taking the device marker out of the view, in order to focus it again I have to click on another device and back on the first one to get it back in view. Wouldn't it be easier by just clicking again on the same device?

**Comment by tananaev** [comment]
Good point and it should be fairly easy to implement.

**Comment by SebastEnn** [comment]
Is this implemented?

**Comment by tananaev** [comment]
Implemented here: https://github.com/traccar/traccar-web/commit/731898d1ffd785ce524833204d1aeac476b35104.
