### ISSUE TITLE
new role - manager [New feature request]

### ISSUE THREAD

**Issue by glbatistabh** [traccar/traccar#1835]
Suggestion: new ‘managers’ functionality
- manager: Managers can add users and can manage access between devices of their users. So they have access to their devices and to devices of all managed users _(analogy: is an administrator of a subset of users)_.
- administrators: have full access to everything. They can manage all devices, all users and access between devices and users.

**Comment by tananaev** [comment]
Thanks for the suggestion. I don't think I would be able to implement this feature in near future, but it's definitely a good idea to have this functionality.

**Comment by SebastEnn** [comment]
Manager role was added in [3.10](https://www.traccar.org/blog/traccar-3-10/). Issue can be closed.
