### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by ghost** [traccar/traccar#1843]
1. Сохранение в файл/ы позиции устройств за какой то период времени, например за сутки т.к. запрос на все позиции любого трекера выполняется очень долго. У меня есть трекер который шлет позицию каждые 5 секунд, получаться за сутки примерно 17К записей. Было бы не плохо записывать в файл (JSON например) все позиции за сутки каждого устройства, а клиент мог бы загружать их по мере необходимости и не было бы тяжелых запросов через АПИ.
2. Ограничительные зоны для трекера или группы трекеров c возможностью информирования юзера по почте и/или SMS если он вышел за пределы зоны
   ![map_zone](https://cloud.githubusercontent.com/assets/5452857/14203966/c69313a4-f809-11e5-936a-6fe753b49754.png)

**Comment by tananaev** [comment]
1. Выгрузка данных в файл в планах.

2. Geo-fencing тоже планируется добавить скоро.

**Comment by SebastEnn** [comment]
Geofences got implemented. Issue can be closed.
