### ISSUE TITLE
Why my position are not all saved

### ISSUE THREAD

**Issue by pierrot10** [traccar/traccar#1850]
Good day all falks,

My module send GPS position to traccar. I observed that some are sent but not saved
I am using Adafruit board to manage my GPS module and format the URL and send the position to Traccar.
When my Adafruit microcontroller send the position, my log file store the following when a position is sent

> ```
> HTTP_init
> HTTP_para CID
> HTTP_para URL
> HTTP_action
> HTTP_raedall: (0)
> HTTP_term OK
> Coordinates sent (HTTP)
> ```

It's means that my position has been sent and save to traccar.
My AT+HTTPREAD, read the respond of the server

The problem I observed, some time the above line are display but the position are not save into traccar.
To be sure about it, I past the following line to my browser (I modified the url by adding dddddd) : 

> http://dddddd.dyndns.org:5055/?id=865067020750884&valid=true&lat=46.456604&lon=6.218282&speed=41.40&altitude=722.09&heading=64.400001&batt=80&desc=GPS%20localisation&timestamp=2016-02-27%2016:48:35

and then I can see my position in my traccar map.
However, the web page remind blank. It the reason my My AT+HTTPREAD return 0

> > ```
> > HTTP_raedall: (0)
> > ```

I have to understand why my microcontroller could send and traccar can save a lot but some are not save.

I looked at the traccar log file and I can not see a trace of my position sent at 2016-02-27 at 2016:48:35.

In my traccar.xml, I did not set any filter.

As I wrote, I observed, when I pasted the following line to my browser

> http://dddddd.dyndns.org:5055/?id=865067020750884&valid=true&lat=46.456604&lon=6.218282&speed=41.40&altitude=722.09&heading=64.400001&batt=80&desc=GPS%20localisation&timestamp=2016-02-27%2016:48:35

The position is saved into traccar but the web page remind blank.
My command AT+HTTPREAD can not read an respond from the server.

**The think I would like to do** is to have an OK or a KO returned by traccar on the web page after entering the above URL. In that way, my command AT+HTTPREAD can read OK or KO because the server confrim the record to my microcontroller.

> HTTP_init
> HTTP_para CID
> HTTP_para URL
> HTTP_action
> HTTP_raedall:*\* OK**
> HTTP_term OK
>  Coordinates sent (HTTP)

or

> HTTP_init
> HTTP_para CID
> HTTP_para URL
> HTTP_action
> HTTP_raedall: **KO**
> HTTP_term OK
>  Coordinates sent (HTTP)

even if my code display

>  Coordinates sent (HTTP)

Some has a idea?

Thank for your help

**Comment by tananaev** [comment]
Can I see server logs?

**Comment by pierrot10** [comment]
Hello, here is a exemple
On the 2 of april at 15:15 the following URL was sent

> http://dddd.dddd.org:5055/?id=865067020750884&valid=true&lat=46.167728&lon=6.096257&speed=81.44&altitude=407.20&heading=321.600006&batt=32&desc=GPS%20localisation&timestamp=2016-04-02%2015:15:48
with the following log (personal log)

> Sending new Geolocalisation
> -----------------------------------
> URL	http://ddd.dddd.org:5055/?id=865067020750884&valid=true&lat=46.167728&lon=6.096257&speed=81.44&altitude=407.20&heading=321.600006&batt=32&desc=GPS%20localisation&timestamp=2016-04-02%2015:15:48
> Length	197
> Running since: 7180 sec.
> 
> 
> HTTP_init
> HTTP_para CID
> HTTP_para URL
> HTTP_action
> HTTP_raedall: (0)  [false]
> HTTP_term OK
> Sending finished (HTTP)
> 
> countDataSent:212
> 
> Coordinates sent (HTTP)

But the record was not done on traccar. I past the above URL to the browser and the trracr record the position.

Net next position has the same problem but I have not past it to my browser, and I will try to find the traccar log and past it.

> Sending new Geolocalisation
> -----------------------------------
> URL	http://ddd.dddd.org:5055/?id=865067020750884&valid=true&lat=46.172763&lon=6.090614&speed=82.47&altitude=406.89&heading=322.100006&batt=31&desc=GPS%20localisation&timestamp=2016-04-02%2015:16:19
> Length	197
> Running since: 7211 sec.
> 
> 
> HTTP_init
> HTTP_para CID
> HTTP_para URL
> HTTP_action
> HTTP_raedall: (0)  [false]
> HTTP_term OK
> Sending finished (HTTP)
> 
> countDataSent:213
> 
> Coordinates sent (HTTP)

Here is the traccar log:
(Apparently, there is nothing for 15:16:19), but AT+HTTPACTION, AT+HTTPREAD and all AT+HTTP command return TRUE

> 6d652e64796e646e732e6f72673a353035350d0a557365722d4167656e743a204d6f7a696c6c612f352e3020284d6163696e746f73683b20496e74656c204d6163204f5320582031302e31313b2072763a34352e3029204765636b6f2f32303130303130312046697265666f782f34352e300d0a4163636570743a20746578742f68746d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c6170706c69636174696f6e2f786d6c3b713d302e392c2a2f2a3b713d302e380d0a4163636570742d4c616e67756167653a2066722d43482c656e2d55533b713d302e372c656e3b713d302e330d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174650d0a436f6f6b69653a204757545f4c4f43414c453d64656661756c743b204a53455353494f4e49443d31346133666f37737136306866316e6e6a7979696d3730346b380d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a0d0a
> 2016-04-02 23:43:05 DEBUG: [DEB78684: 5055 > 178.198.74.105] HEX: 485454502f312e3120323030204f4b0d0a0d0a
> 2016-04-02 23:43:05  INFO: [DEB78684] disconnected
> 2016-04-02 23:43:06  INFO: [DEB78684] id: 1, time: 2016-04-02 16:33:34, lat: 46.21474, lon: 6.00615, speed: 0.9, course: 257.8
> 2016-04-02 23:44:30  INFO: [35F1D5CB] connected
> 2016-04-02 23:44:30 DEBUG: [35F1D5CB: 5055 < 178.198.74.105] HEX: 474554202f3f69643d3836353036373032303735303838342676616c69643d74727565266c61743d34362e323134373731266c6f6e3d362e3030363135362673706565643d302e383126616c7469747564653d3435382e32302668656164696e673d3333362e31303030303626626174743d323626646573633d4750532532306c6f63616c69736174696f6e2674696d657374616d703d323031362d30342d303225323031363a33313a323520485454502f312e310d0a486f73743a206269706d652e64796e646e732e6f72673a353035350d0a557365722d4167656e743a204d6f7a696c6c612f352e3020284d6163696e746f73683b20496e74656c204d6163204f5320582031302e31313b2072763a34352e3029204765636b6f2f32303130303130312046697265666f782f34352e300d0a4163636570743a20746578742f68746d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c6170706c69636174696f6e2f786d6c3b713d302e392c2a2f2a3b713d302e380d0a4163636570742d4c616e67756167653a2066722d43482c656e2d55533b713d302e372c656e3b713d302e330d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174650d0a436f6f6b69653a204757545f4c4f43414c453d64656661756c743b204a53455353494f4e49443d31346133666f37737136306866316e6e6a7979696d3730346b380d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a0d0a
> 2016-04-02 23:44:30 DEBUG: [35F1D5CB: 5055 > 178.198.74.105] HEX: 485454502f312e3120323030204f4b0d0a0d0a
> 2016-04-02 23:44:30  INFO: [35F1D5CB] disconnected
> 2016-04-02 23:44:30  INFO: [35F1D5CB] id: 1, time: 2016-04-02 16:31:25, lat: 46.21477, lon: 6.00616, speed: 0.8, course: 336.1
> 2016-04-02 23:44:40  INFO: [A2F99172] connected
> 2016-04-02 23:44:40 DEBUG: [A2F99172: 5055 < 178.198.74.105] HEX: 474554202f3f69643d3836353036373032303735303838342676616c69643d74727565266c61743d34362e323134373731266c6f6e3d362e3030363135362673706565643d302e383126616c7469747564653d3435382e32302668656164696e673d3333362e31303030303626626174743d323626646573633d4750532532306c6f63616c69736174696f6e2674696d657374616d703d323031362d30342d303225323031363a33313a323520485454502f312e310d0a486f73743a206269706d652e64796e646e732e6f72673a353035350d0a557365722d4167656e743a204d6f7a696c6c612f352e3020284d6163696e746f73683b20496e74656c204d6163204f5320582031302e31313b2072763a34352e3029204765636b6f2f32303130303130312046697265666f782f34352e300d0a4163636570743a20746578742f68746d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c6170706c69636174696f6e2f786d6c3b713d302e392c2a2f:
> 

I hope my information help!!

**Comment by pierrot10** [comment]
Note, at this time I had a french sim card and I return to Switzerland. So my module was in Roaming mode. All the time I was in French territory, it seams to works. But I also meet that problem with Swiss SIM card on Swiss territory

**Comment by tananaev** [comment]
As far as I can see from the log, the data is saved successfully in the database.

**Comment by pierrot10** [comment]
Yes but not this one which has been send at 15:16:10

> URL http://ddd.dddd.org:5055/?id=865067020750884&valid=true&lat=46.172763&lon=6.090614&speed=82.47&altitude=406.89&heading=322.100006&batt=31&desc=GPS%20localisation&timestamp=2016-04-02%2015:16:19

it not in the log

**Comment by tananaev** [comment]
If you don't see corresponding HEX message in the log, it means server hasn't received this request.

**Comment by pierrot10** [comment]
OK, then how can I ask the server to return an OK when a something has been received and recoord.
As I observed, when I past an URL, the datas are record but the page reming blank. If it could return an "OK" my AT+HTTPREAD could read an OK. IF nothing has been received (then saved) the page remind blank.

Then I can deal with the AT+HTTPREAD command to make my code to return FLASE if AT+HTTPREAD does not read an OK.

**Comment by tananaev** [comment]
It returns standard OK HTTP response.

**Comment by pierrot10** [comment]
Dear tananaev, Thank for your reply but how can I read it from my microcontroller. How the traccar server can return it, or how can my microcontroller car now ir. When I enter thw following URL (it a new one)

> http://ddd.ddd.org:5055/?id=865067020750884&valid=true&lat=46.221416&lon=6.139848&speed=0.03&altitude=402.20&heading=114.099998&batt=31&desc=GPS%20localisation&timestamp=2016-04-02%2015:31:03

and I read the view the source of my web page, the page is empty with no html or body tag.

**Comment by tananaev** [comment]
There is no body, but there is HTTP response code indicating success or failure.

**Comment by pierrot10** [comment]
Dear tananaev, Thank for your reply and sorry to insist. I can not understand. Where is the HTTP response?
It's only readable on the log file?
You wrote "There is no body but there is HTTP reponse...". So you means in the web page? How can I get/read it? I ma using Firedebug and I have not found a such response from the server.
Cheers

**Comment by tananaev** [comment]
What is Firedebug? Please read about HTTP protocol. There is always a response code and status.

**Comment by pierrot10** [comment]
Oups sorry,  I was speaking about Firebug on firefox.
[https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html](url)
So I am wondering if it's always return OK because my function send an AT+HTTPACTION and wait for the value 200 (OK response).

> AT+HTTPACTION=0,200,100

Then when the AT+HTTPACTION reponse is +HTTPACTION:0,200,100, it means he got the OK from the server. But when my URL is sent but not recorded to tracar, the AT+HTTPACTION response is as I just mentioned, with 200.

I am going to to make more test with more debug display, to make sure about the response of my command AT+HTTPACTION

**Comment by tananaev** [comment]
If you get OK response, but data is not stored, something is wrong. I need logs in that case.

**Comment by pierrot10** [comment]
Dear tanaev, I sent you the log, but I will make more test in order to make sure about my code. I already add some debug to read exactely the reponse of AT+HTTPACTION. Then I will provide you exact information when this problem occured again

**Comment by tananaev** [comment]
As I said before, your previous log indicates that data was stored correctly.

**Comment by SebastEnn** [comment]
He probably figured out what response traccar sent or if his request was even sent.

Issue can be closed.
