### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by harold66** [traccar/traccar#1852]
Can I add charting functionality to the existing ExtJS in traccar? I'm following the directions written here https://docs.sencha.com/extjs/5.1/components/introduction_to_charting.html but I don't know how to go on.

**Comment by tananaev** [comment]
It should be possible, but I have never tried it myself.

**Comment by harold66** [comment]
Where can I find the following file? 
`{appRoot}/app.json`

And would I be able to rebuild the application using `sencha app build`?

**Comment by tananaev** [comment]
No. It doesn't use `app.json` file.

**Comment by russellhoff** [comment]
Hi @tananaev, I'm @harold66 workmate who's helping him out with that issue. If it doesn't use app.json, is there any way to adding charts?

**Comment by tananaev** [comment]
There must be a way, but as far as I know Charts are not part of GPL version, so you need to buy a license.

**Comment by russellhoff** [comment]
@tananaev thanks for your kind help

**Comment by russellhoff** [comment]
So any way to use any chart (google charts, highcharts, chartjs...)?

**Comment by tananaev** [comment]
Of course. You can use any web technology you want.

**Comment by kirantpatil** [comment]
Hi @russellhoff, any updates on Charts ?

**Comment by russellhoff** [comment]
Sorry @kirantpatil , I wasn't in charge of the project at my company. Indeed, the project was left over and the person left the company.

**Comment by Abyss777** [comment]
I'm thinking over charts.
What charts do you want?
Only speed chart comes to my mind.

**Comment by kirantpatil** [comment]
I am thinking some kind of analytic to embed to get meaningful graphs and stats.

How about using R ?

Allowing using R will help come up with advanced stats with future projection.

**Comment by Abyss777** [comment]
IMHO, so powerful analytics should be external part, not the part of traccar, at least at current stage.

But still..., You are talking about tools..., but what graph and stats do you want to get?

**Comment by kirantpatil** [comment]
Yes, I agree with you.

I would go for traccar community members suggestion, who have production setup.

**Comment by tananaev** [comment]
One simple option is to allow user to pick attribute and period of time, and just draw it as a graph.

**Comment by SebastEnn** [comment]
Charts got implemented. Issue can be closed.
