### ISSUE TITLE
Tomcat Instalation

### ISSUE THREAD

**Issue by shahbour** [traccar/traccar#1853]
Hello

is it possible to install the web inside tomcat or the whole system , if yes please any guidance ?

BR
Shahbour

**Comment by tananaev** [comment]
It is possible to put static part of the web inside Tomcat, but why would you want to do that?

It's not possible to put whole Traccar system into Tomcat because of the limitation of Java app servers.

**Comment by shahbour** [comment]
I want to install it on a server that already have tomcat and wanted to
give it a domain name .

Br

**Comment by tananaev** [comment]
Do you have Apache or some other proper web server in front of the Tomcat? Or is it just pure Tomcat?

**Comment by shahbour** [comment]
Just tomcat , but I will install Apache and use it as reverse proxy for
both tomcat and traccar

Thanks

**Comment by tananaev** [comment]
This might help with setting up proxy:

https://www.traccar.org/secure-connection/

**Comment by shahbour** [comment]
Thanks a lot

Out of order question , is their any recommended device as i want to use
the solution to monitor Trucks , i was thinking of this
<http://www.aliexpress.com/item/Guaranteed-100-4-band-car-GPS-tracker-GT02A-Google-link-real-time-tracking-free-shipping/1257279802.html?spm=2114.01010208.3.20.o3rCIr&ws_ab_test=searchweb201556_0,searchweb201602_5_9122_10017_10005_10006_10034_10021_507_10022_10032_10020_10018_10019,searchweb201603_9&btsid=bd16b55f-6fd7-4a39-92d5-ada3407ec0ce>
 or this
<http://www.aliexpress.com/item/4-bands-multi-function-waterproof-car-gps-tracker-GT003-GPS-data-high-speed-platform-free-shipping/32259198202.html?spm=2114.10010108.1000013.4.6oqmCo>
but
i am not sure if they are considered cheap devices .

BR

**Comment by tananaev** [comment]
Unfortunately I can't recommend anything hardware-wise, but as long as it's in the list of supported devices it should work. Most cheap Chinese devices are supported.

**Comment by SebastEnn** [comment]
Advise given. Issue can be closed.
