### ISSUE TITLE
Google Earth integration via KML file creation on export

### ISSUE THREAD

**Issue by Hatchorder** [traccar/traccar#1858]
Hi.

Is it possible to add a feature on the server side to allow the export of positions as Latitude and Longitude into an KML file to open in Google Earth to create a track? This was a feature of Marinetraffic.com but they have removed it. Or even a generic export feature to allow people to extract the data to use in other applications?

Thank you.

Ian

**Comment by daviddesmedt** [comment]
Hi, I agree this would be a useful function. Although I believe it is possible to generate such a file yourself using a scripting language, based on the server logs file.

**Comment by galciu** [comment]
Yes, kml export to google earth would be awesome.
How much it would cost to accelerate this future?

**Comment by tananaev** [comment]
You can already export in GPX format. There are tools that can convert GPX to KML or maybe Google Earth even supports it directly.

**Comment by galciu** [comment]
Looks like Google Earth supports directly import from GPX,
but in TC there is no GUI export for GPX, it's only possible by API?

**Comment by tananaev** [comment]
Yes, it's possibly via API.
