### ISSUE TITLE
How to make the session be stored persistently?

### ISSUE THREAD

**Issue by ulion** [traccar/traccar#1862]
According to this doc: http://www.eclipse.org/jetty/documentation/current/using-persistent-sessions.html

it's possible to let the HashSessionManager store session data persistently, but how?

I'm using netbeans on osx, thx.

**Comment by tananaev** [comment]
I guess you just need to set up `storeDirectory` parameter.

**Comment by ulion** [comment]
Yes, but I'm not familiar with the way to config the java app, then where
should I set up that parameter?

2016-04-11 9:32 GMT+08:00 Anton Tananaev <notifications@github.com>:

> I guess you just need to set up storeDirectory parameter.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1862#issuecomment-208111798>
>



-- 
Ulion

**Comment by tananaev** [comment]
You need to do it programmatically. There must be a method.

**Comment by ulion** [comment]
got it. so no simple config way without rebuild the server from code can do
it.

2016-04-11 9:34 GMT+08:00 Anton Tananaev <notifications@github.com>:

> You need to do it programmatically. There must be a method.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1862#issuecomment-208112110>
>



-- 
Ulion

**Comment by tananaev** [comment]
No, there is no way to do it via config file.

**Comment by SebastEnn** [comment]
Simple answer: You can't. You would have to change it yourself in code.

Issue can be closed.

**Comment by tananaev** [comment]
Actually we have a configuration option to persist sessions in the database. Check the documentation.
