### ISSUE TITLE
Change to the mysql database

### ISSUE THREAD

**Issue by mechanic98** [traccar/traccar#1866]
Hi everyone
I've installed the traccar of version 3.4.
I'm going to change h2 database to mysql, 
So did the steps according to the link below
[https://www.traccar.org/mysql/](url)
## I created a database according to the following steps:

```
---------------------

mysql> CREATE USER 'test'@'localhost' IDENTIFIED BY 'test123test!';
Query OK, 0 rows affected (0.00 sec)

---------------------

mysql> create database testdb;
Query OK, 1 row affected (0.00 sec)

---------------------------------------------------------------------

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| da_roundcube       |
| mysql              |
| mysql_old          |
| performance_schema |
| testdb             |
| traccar            |
+--------------------+
7 rows in set (0.00 sec)

---------------------------------------------------

mysql> GRANT ALL PRIVILEGES ON testdb.* TO 'test'@'localhost' WITH GRANT OPTION;
Query OK, 0 rows affected (0.00 sec)

---------------------------

mysql> grant all privileges on testdb.* to test@'localhost' identified by 'test123test';
Query OK, 0 rows affected (0.00 sec)

-------------

mysql> use testdb;
Database changed

-------------------BEFORE RUNING TRACCAR ------------------
mysql> show tables;
Empty set (0.00 sec)

--------------------------------------------------

mysql> FLUSH PRIVILEGES;
Query OK, 0 rows affected (0.00 sec)

------------------------------ change the traccar.xml ------------------
https://i.imgsafe.org/24b5e75.png

---------------------------------

stop tracar and then start traccar>> and reload the address :http://62.60.148.128:8082/
And I encountered the following error:
https://i.imgsafe.org/2b8e29c.png

----------------AFTER RUNING TRACCAR---------------------
mysql> show tables;
+-----------------------+
| Tables_in_testdb      |
+-----------------------+
| DATABASECHANGELOG     |
| DATABASECHANGELOGLOCK |
| devices               |
| positions             |
| server                |
| user_device           |
| users                 |
+-----------------------+
7 rows in set (0.00 sec)

------------------------------------------------
```

this is my wrapper log :
http://gpsmizban.ir/wrapper.txt

I thank you help me
Thanks a lot

**Comment by tananaev** [comment]
Error indicates that connection to the database timed out. Try to increase timeout value.

**Comment by mechanic98** [comment]
How Try to increase timeout value? 
Thank you.

**Comment by tananaev** [comment]
It's part of MySQL configuration.

**Comment by mechanic98** [comment]
## this is my MySQL configuration file :
that i run it whit this command: 
`sudo vi /etc/my.cnf`

> [mysqld]
innodb_file_per_table=1
default-storage-engine=MyISAM
max_allowed_packet=512M
query_cache_size = 1024M
query_cache_type=1
thread_cache_size = 384
join_buffer_size=1024M
max_connections=500
local-infile=0
table_cache= 10000
open_files_limit = 8192
tmp_table_size=256M
max_heap_table_size=256M
wait_timeout=5

Should I increase wait_timeout??
How much should I raise?
Thanks a lot

**Comment by tananaev** [comment]
Please read following comment:

http://stackoverflow.com/a/10772407/2548565

**Comment by mechanic98** [comment]
Thanks a lot
Finally worked properly
I added my /etc/my.cnf and I changed the following:

wait_timeout=28800
interactive_timeout = 28800
connect_timeout = 28800

Thank you, Wish you a great day :)

**Comment by SebastEnn** [comment]
Problem solved. Issue can be closed.
