### ISSUE TITLE
where should set IP address 

### ISSUE THREAD

**Issue by vipinjacob** [traccar/traccar#1867]
In which file i should set the ip address of my public server.

**Comment by tananaev** [comment]
Why do you need to set IP address?

**Comment by vipinjacob** [comment]
Then how the system will recognise my IP or it will automatically take the IP its running

**Comment by tananaev** [comment]
By default it listens on all network interfaces. It doesn't have to know any IP addresses.

It's possible to specify one if you really need.

**Comment by SebastEnn** [comment]
Question answered. Issue can be closed.
