### ISSUE TITLE
Windows10 & Java 8 installation issue with traccar

### ISSUE THREAD

**Issue by odintheterrible** [traccar/traccar#1870]
Windows 10 fully updated; Java 8 installed with OFFLINE installer and as admin
Tried to install traccar (run as admin) but still getting this stupid message about Java ....

Any thoughts on how to resolve this issue  ????

**Comment by m-menon** [comment]
> stupid message about Java

 is the summary, a bit more of a detail would help understand the problem better :-)

**Comment by tananaev** [comment]
If you get the error it means that Java runtime is not available for the System user which is required to run Traccar service.

**Comment by SebastEnn** [comment]
He hopefully figured out how to install Java properly.

Issue can be closed.
