### ISSUE TITLE
Add new command 

### ISSUE THREAD

**Issue by Elajaj** [traccar/traccar#1872]
Hi everyone,
i try  to add a new command and  i need help, how can i add new *_text field  *_ and read its value.

![1](https://cloud.githubusercontent.com/assets/18051832/14531291/988c6e7e-0254-11e6-8fc5-200b420832c5.PNG)

**Comment by tananaev** [comment]
I would recommend to read official ExtJS documentation:

http://docs.sencha.com/extjs/6.0/
http://docs.sencha.com/extjs/6.0/6.0.1-classic/

**Comment by SebastEnn** [comment]
Advice given. Issue can be closed.
