### ISSUE TITLE
Traccar is not running

### ISSUE THREAD

**Issue by mechanic98** [traccar/traccar#1875]
Hello ;
Could you please help me?
my Traccar is not running

my wrapper log:
http://txt.do/5ydyj

java -version:
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

[root@vps logs]# sudo service traccar status
traccar is running: PID:22095, Wrapper:STARTED, Java:STARTED

my server address:
http://136.243.197.215:8082/

lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.5 (Final)
Release:        6.5
Codename:       Final

service iptables stop is active but Traccar is not running :(

**Comment by tananaev** [comment]
According to the log, it is running.

**Comment by mechanic98** [comment]
but is not work!!!
iptables in stop,
i see warn in wrapper:
org.eclipse.jetty.server.handler.AbstractHandler - No Server set for org.traccar.web.WebServer$1@2efb76a6

**Comment by tananaev** [comment]
How are iptables related to Traccar?

**Comment by mechanic98** [comment]
I stopped my IP table
Because I would probably block 8082 port,
But with these conditions my Traccar is not running :(
can i send you my user & pass of my vps to see my problem?

**Comment by tananaev** [comment]
OK, my email address is in profile.

**Comment by tananaev** [comment]
As I said it's running:
```
[root@vps traccar]# ps aux | grep traccar
root     22095  0.0  0.1 116632  1500 ?        Sl   12:18   0:02 /opt/traccar/bin/./wrapper /opt/traccar/bin/../conf/wrapper.conf wrapper.syslog.ident=traccar wrapper.pidfile=/opt/traccar/bin/./traccar.pid wrapper.daemonize=TRUE wrapper.name=traccar wrapper.displayname=traccar wrapper.statusfile=/opt/traccar/bin/./traccar.status wrapper.java.statusfile=/opt/traccar/bin/./traccar.java.status wrapper.lockfile=/var/lock/subsys/traccar wrapper.script.version=3.5.28
root     22097  0.3 13.7 2299164 140160 ?      Sl   12:18   0:19 /usr/local/java/jdk1.8.0_77/bin/java -Dfile.encoding=UTF-8 -Djava.library.path=../lib -classpath ../lib/wrapper.jar:../tracker-server.jar -Dwrapper.key=VmkYGU4J7AhuAAVF -Dwrapper.port=32000 -Dwrapper.jvm.port.min=31000 -Dwrapper.jvm.port.max=31999 -Dwrapper.disable_console_input=TRUE -Dwrapper.pid=22095 -Dwrapper.version=3.5.28 -Dwrapper.native_library=wrapper -Dwrapper.arch=x86 -Dwrapper.service=TRUE -Dwrapper.cpu.timeout=10 -Dwrapper.jvmid=1 org.tanukisoftware.wrapper.WrapperSimpleApp org.traccar.Main ../conf/traccar.xml
```
Port:
```
[root@vps traccar]# netstat -ln | grep 8082
tcp        0      0 :::8082                     :::*                        LISTEN  
```

**Comment by mechanic98** [comment]
but why it's noting show in http://136.243.197.215:8082/ address??!!
Do you have see something in 136.243.197.215:8082  address??

**Comment by tananaev** [comment]
No, I don't. I guess there is some network issue.

**Comment by mechanic98** [comment]
What would you recommend for me?
Do you think's java have a problem?

**Comment by tananaev** [comment]
It's not a Java problem. It's a network problem. Most likely the port is blocked by firewall or not forwarded properly.

**Comment by yeekhoon** [comment]
mechanic98, maybe you can try to check your router port forwarding setting..  very likely your port is not forwarded correctly...

**Comment by mechanic98** [comment]
> maybe you can try to check your router port forwarding setting.. very likely your port is not forwarded correctly...

thank you yeekhoon , but this is vps and I do not have access to the router

**Comment by mechanic98** [comment]
this is :   #iptables -L
http://txt.do/5yrib

**Comment by tananaev** [comment]
I'm not an expert in iptables, so I can't really tell if anything is wrong there.

**Comment by mechanic98** [comment]
The problem was hardware firewall,and After asking the sysadmin port opened
Thanks for all

**Comment by labenavides** [comment]
mechanic98, could you give us more information about the firewall issue? i have the same problem and i dont know why.

**Comment by mechanic98** [comment]
I do not have full information about firewall
Because I do not have access to it
I raised the issue with the system administrator
And he opened port

**Comment by SebastEnn** [comment]
Problem got solved by vps network administrator. Issue can be closed.
