### ISSUE TITLE
users privileges

### ISSUE THREAD

**Issue by inghenryh** [traccar/traccar#1885]
Hi, I like can prevent the user can change their own user name. is that possible?

**Comment by tananaev** [comment]
It's not possible in the default version, but it should be fairly easy to implement as a customization.

**Comment by inghenryh** [comment]
in this case as you can do? you can help?

**Comment by tananaev** [comment]
Send me an email to discuss. Address is in profile.

**Comment by SebastEnn** [comment]
Discussion shifted to private. Issue can be closed.
