### ISSUE TITLE
The same LAN, the server does not detect Android equipment

### ISSUE THREAD

**Issue by ylot0** [traccar/traccar#1890]
Server system: Ubuntu 14.04  64bit
Client: 1, Android 4.0.4 2, Android 5.0.1
Ubuntu command
sudo ./traccar.run
sudo /opt/traccar/bin/traccar start

Same local area network:
After the installation is completed through the localhost:8082 can be accessed normally. Add the client device ID (the same as the client ID), but the device is not detected.
The client is set as follows: the device ID software is automatically generated, the server IP:192.168.10.88 port: 5055
After the server installation is complete，IPV4 protocol port 5055 is close,  ipv6 protocol port 5055 is open.
Why not detect the client?

**Comment by tananaev** [comment]
Why port 5055 is closed? How have you determined that?

**Comment by ylot0** [comment]
I use the command

sudo lsof -i:5055

See only the IPV6 protocol

**Comment by tananaev** [comment]
Most modern Linux distributions have dual TCP stack, so if you don't see IPv4 there, it doesn't mean it's not listening for it.

Anyway, have you checked server logs to see if you receive any data there?

**Comment by ylot0** [comment]
It is very simple steps, there is no reason to make a mistake.Because I am not here outside the network IP address, I in the realization of traacr at the beginning of thought is by ngrok generating a network address, and then are connected, but failed. Then I removed the ngrok, delete the traccar and reinstall, still does not work to consult!But I want to say is the Samsung S6, Android 5.0.1, the use of non hidden version of the client service has stopped the problem will appear.

**Comment by tananaev** [comment]
Please see following page:

https://www.traccar.org/troubleshooting/

**Comment by ylot0** [comment]
2016-04-20 13:58:02  INFO: Operating system name: Linux version: 3.13.0-85-generic architecture: amd64
2016-04-20 13:58:02  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.95-b01
2016-04-20 13:58:02  INFO: Memory limit heap: 1753mb non-heap: 214mb
2016-04-20 13:58:02  INFO: Character encoding: UTF-8 charset: UTF-8
2016-04-20 13:58:02  INFO: Version: 3.4-SNAPSHOT
2016-04-20 13:58:05  INFO: Starting server...

**Comment by ylot0** [comment]
ifconfig 
inet 地址:192.168.10.88  广播:192.168.10.255  掩码:255.255.255.0
          inet6 地址: fe80::c685:8ff:fe61:3000/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  跃点数:1
          接收数据包:2165717 错误:0 丢弃:1 过载:0 帧数:0
          发送数据包:1550274 错误:0 丢弃:0 过载:0 载波:0
          碰撞:0 发送队列长度:1000 
client    
      Android4.0.4   server address     192.168.10.88        server port   5055      

I started  localhost:8082   Added equipment ID, but that is not found in the device, the system does not have a firewall, routing is not set up a firewall

**Comment by tananaev** [comment]
What do you see on the status screen in the Traccar Client app?

**Comment by ylot0** [comment]
Yes, that's my cell phone.

**Comment by tananaev** [comment]
That's not an answer for my question. There is a status screen in the app. What do you see on it?

**Comment by ylot0** [comment]
2:28PM-service created
2：28PM-connectivity change

**Comment by tananaev** [comment]
Well, it means you don't have a location on your phone.

**Comment by ylot0** [comment]
I'm sorry, I don't know what you mean.

**Comment by tananaev** [comment]
Which location provider are you using in the app? If GPS, it means that your phone doesn't have a GPS fix.

**Comment by ylot0** [comment]
My setting is
location provider    ===    network provider

**Comment by tananaev** [comment]
Then I guess your phone can't get a network location for some reason. Are you sure you enabled network location in the phone system settings?

**Comment by ylot0** [comment]
I understand what you mean is, my mobile phone does not have a IP address for the network, so cannot be located?My phone is not mobile phone cards, means that you can not use GPS, but my phone is through WiFi network, i can link to the internet

**Comment by tananaev** [comment]
It depends. Sometimes Wi-Fi is enough. Alternatively you can use GPS.

**Comment by ylot0** [comment]
If the use of GPS, but my server no IP address of the internet, still unable to link, whether it can be combined with "ngrok" get a internet address of the link?

**Comment by ylot0** [comment]
Thank you very much for your help. Thank you.！！！

**Comment by tananaev** [comment]
Does your last comment mean that everything works now?

**Comment by ylot0** [comment]
NO，I just know what you're thinking.

**Comment by ylot0** [comment]
ngrok by @inconshreveable                                       (Ctrl+C to quit)
                                                                                
Tunnel Status                 online                                            
Version                       2.0.25/2.0.25                                     
Region                        United States (us)                                
Web Interface                 http://127.0.0.1:4040                             
Forwarding                    http://22e76e0f.ngrok.io -> localhost:5055        
Forwarding                    https://22e76e0f.ngrok.io -> localhost:5055       
                                                                                
Connections                   ttl     opn     rt1     rt5     p50     p90       
                              0       0       0.00    0.00    0.00    0.00

**Comment by tananaev** [comment]
I don't know what it means. Is there some problem?

**Comment by ylot0** [comment]
I don't have a internet address, to then is on my server 5055 port service mapping out through the ngrok, but doesn't work, localhost:8082 cannot open the!

**Comment by RivasAlejandro** [comment]
Hey, I 've just install centos 7  on virtual box, install traccar then i can see traccar panel in my host computer,  I download from play store traccar client and send error sending data to server 
server entos: 192.168.1.27 
host: 192.168.1.20
android lolipop 
All in the same local network 
what  probabily wrong?

**Comment by SebastEnn** [comment]
ylot0's problem got solved. Issue can be closed.
