### ISSUE TITLE
v 3.5 address is null

### ISSUE THREAD

**Issue by eliduroma** [traccar/traccar#1902]
I'm using nominatim geocode . Not possess post limit. 

95 % of the addresses are null.

debug.xml

```
<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>nominatim</entry>
<entry key='geocoder.url'>http://nominatim.openstreetmap.org/reverse</entry>
<entry key='geocoder.processInvalidPositions'>true</entry>
```

Average daily use : 12920 positions

**Comment by tananaev** [comment]
You are not supposed to use Nominatim official hosted server. They seem to actually ban Traccar already because of people like you.

If you want to use Nominatim, you need to either host your own server or use one of the paid service providers.

**Comment by eliduroma** [comment]
You indicate me some free geocode service without limit?

Or my average positions(12920 positions/day) better host the geocode service on my server?

**Comment by tananaev** [comment]
There are no free services without limits as far as I know.

Looks like MapQuest provides 15000 per month for free:

https://developer.mapquest.com/plans

You can also check other geocoder options:

https://github.com/tananaev/traccar/tree/master/src/org/traccar/geocode

**Comment by eliduroma** [comment]
I need many requests day and can not spend. The solution will be staying in own server.

Thank you very much

**Comment by SebastEnn** [comment]
Issue can be closed.
