### ISSUE TITLE
Send Command Tracker Without using SMS

### ISSUE THREAD

**Issue by eliduroma** [traccar/traccar#1903]
I use suntech protocol.

I can send commands to the equipment ( tracker ), requesting the current position via GPRS?

Is there any library for that?

Currently use SMS to communicate with the equipment ( tracker ).

**Comment by tananaev** [comment]
Not sure what you mean by library, but you can use Traccar server to send commands to Suntech devices connected via GPRS.

**Comment by eliduroma** [comment]
We try to send the command via interface displays error "NullPointerException (Command Resource: 37 <...".

![image](https://cloud.githubusercontent.com/assets/18648961/14872981/ed93d8c6-0cc7-11e6-9e87-7a5ab5ea360b.png)

**Comment by tananaev** [comment]
It means that device is disconnected. It's colored red in the devices panes which means that it's not connected.

**Comment by eliduroma** [comment]
I could send commands Command.TYPE_ENGINE_STOP and Command.TYPE_ENGINE_RESUME successfully in suntech device.

For protocol suntech have any command that returns the current position(lat,long), speed and other attributes?

**Comment by tananaev** [comment]
Those are the only two supported for that particular protocol at the moment:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/SuntechProtocol.java

**Comment by eliduroma** [comment]
I'm trying to implement the current position in suntech.

The command strings sent to the equipment ( traccer ) is similar to the command sent via sms ? 

Where do I start ? Any suggestion?

**Comment by tananaev** [comment]
Well, you need to start with proper protocol documentation.

**Comment by SebastEnn** [comment]
suntech protocol is supported. See [protocol list](https://www.traccar.org/protocols/).

Issue can be closed
