### ISSUE TITLE
Traccar server DB reset

### ISSUE THREAD

**Issue by excepticons** [traccar/traccar#1905]
Hi, everybody. 
Please, If I need to start from zero with Traccar server and clients (0 groups, 0 users, 0 devices, 0 positions), how can delete all rows of all tables and start again without a new install? VPS and DB server works fine. 
Is there any store procedure or script for that?
Thanks.

Gustavo.

**Comment by tananaev** [comment]
Are you using default H2 database? If yes, you can just remove the database file and Traccar will re-create it on restart.

**Comment by excepticons** [comment]
Hi, Anton.
I'm using a MySql database. I can see tables like users, groups, devices, positions, user-devices, etc.
Thank you.

**Comment by excepticons** [comment]
Maybe deleting the tables? I remember that I was created the database and Traccar was created tables from zero.
Thanks.

**Comment by tananaev** [comment]
Just re-create the database and restart the service.

**Comment by excepticons** [comment]
Thanks.

**Comment by SebastEnn** [comment]
Question answered. Issue can be closed.
