### ISSUE TITLE
Value not coming 

### ISSUE THREAD

**Issue by vipinjacob** [traccar/traccar#1908]
We are receiving values from from very few devices though we have 1000+ devices added in database. We have demo tomm please let us know any solution is there.

**Comment by tananaev** [comment]
You haven't provided any information that can help to determine what is the problem.

This page might be useful:

https://www.traccar.org/troubleshooting/

**Comment by SebastEnn** [comment]
Since they haven't provided any new information, they figured something out themselfes?

Issue can be closed.
