### ISSUE TITLE
WARN org.eclipse.jetty.servlet.ServletHandler - /api/socket

### ISSUE THREAD

**Issue by charlymanja** [traccar/traccar#1909]
Hi, all users are unable to list their devices in the Device panel (keep loading data and never ends) this happens after I upgrade from 3.3 to 3.4 version.

I increase log level of wrapper to see what's going on and I get the following error.

```
INFO   | jvm 1    | 2016/04/26 23:18:46 | [qtp1397247555-44] WARN org.eclipse.jetty.servlet.ServletHandler - /api/socket
INFO   | jvm 1    | 2016/04/26 23:18:46 | java.lang.NullPointerException
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.traccar.api.AsyncSocketServlet$1.createWebSocket(AsyncSocketServlet.java:37)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:166)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:153)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.websocket.servlet.WebSocketServlet.service(WebSocketServlet.java:151)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/04/26 23:18:46 |       at java.lang.Thread.run(Thread.java:744)
```

Can somebody help me?

Regards

**Comment by charlymanja** [comment]
![untitled](https://cloud.githubusercontent.com/assets/978744/14841731/722726aa-0c06-11e6-9a37-ef3a823be3c9.png)

An image from the Device panel loader

**Comment by tananaev** [comment]
This error in the log usually means that sessions has expired. Possibly after service restart.

**Comment by charlymanja** [comment]
I hace been waiting for 10 minutes ánd never get all devices, is there anotherway to make troubleshooting?

**Comment by tananaev** [comment]
Check browser developer console for error messages.

**Comment by charlymanja** [comment]
Hi!
I realize that only 1 user in traccar can load the device panel.

This is the error.... What does it means?
Thx in advance

`ext-all.js:22 Uncaught TypeError: Cannot read property 'isModel' of nullExt.cmd.derive.extractData @ ext-all.js:22Ext.cmd.derive.extractData @ ext-all.js:22Ext.cmd.derive.readRecords @ ext-all.js:22Ext.cmd.derive.readRecords @ ext-all.js:22Ext.cmd.derive.read @ ext-all.js:22Ext.cmd.derive.processResponse @ ext-all.js:22(anonymous function) @ ext-all.js:22Ext.apply.callback @ ext-all.js:22Ext.cmd.derive.onComplete @ ext-all.js:22Ext.cmd.derive.onStateChange @ ext-all.js:22(anonymous function) @ ext-all.js:22`

**Comment by tananaev** [comment]
That is incorrect statement. Any number of users can load device panel.

I don't know what that error means. Are you using official Traccar release without any modifications?

**Comment by charlymanja** [comment]
When I said "just 1 user can load device panel" I mean that only 1 user can get all devices (the panel still waiting for data). 1 screenshot as example with 2 user accounts logged in.

I'm using Traccar 3.4

![untitled1](https://cloud.githubusercontent.com/assets/978744/14870290/04467c64-0c9f-11e6-9866-71e97c341c66.png)

**Comment by tananaev** [comment]
What's in the developer console for the second user?

**Comment by charlymanja** [comment]
Working ok
![untitled2](https://cloud.githubusercontent.com/assets/978744/14870663/615aeac8-0ca1-11e6-8c99-d2b04307fd2a.png)

Not Working
![untitled3](https://cloud.githubusercontent.com/assets/978744/14870875/02a42cfe-0ca3-11e6-9e2b-986e61592d4e.png)

![untitled2](https://cloud.githubusercontent.com/assets/978744/14870848/d58b3cda-0ca2-11e6-80f7-075776ae65cd.png)

**Comment by tananaev** [comment]
What's the content of "devices" response?

**Comment by charlymanja** [comment]
Not sure I'm understanding to you...

The content is the "loader" and never get devices status
![untitled4](https://cloud.githubusercontent.com/assets/978744/14871083/a95696f8-0ca4-11e6-801a-db9d69d5fc17.png)

**Comment by charlymanja** [comment]
Still not working...

I try this,
-stop traccar
-backups DB to a dump file
-delete app install directory (/opt/traccar)
-reinstall traccar 3.4 (./traccar.run)
-drop MySQL db and create it again
-restart MySQL daemon
-restore MySQL dump
-start traccar

Is there something wrong with the db data?

**Comment by tananaev** [comment]
I want to see the HTTP API call response content.

**Comment by charlymanja** [comment]
Hi, check the tcp trace

[http-trace-8080.txt](https://github.com/tananaev/traccar/files/240864/http-trace-8080.txt)

This help to see the error? Wich tool you recomend to use to get the HTTP API call response?

**Comment by charlymanja** [comment]
This is response of api/devices

`[{"id":16,"name":"111","uniqueId":"111","status":null,"lastUpdate":"2016-04-27T04:08:22.000+0000","positionId":0,"groupId":4},{"id":13,"name":"TR-13","uniqueId":"868683021830538","status":"online","lastUpdate":"2016-04-28T15:19:35.000+0000","positionId":816402,"groupId":3},null]`

**Comment by tananaev** [comment]
The problem is that you have `null` as a device. Are you sure you are using official Traccar version without any modifications?

**Comment by charlymanja** [comment]
Yes Sir, the only modifications I made is on traccar and wrapper xml configuration file

**Comment by tananaev** [comment]
Can I see the modifications that you made in the config file?

**Comment by charlymanja** [comment]
I send to you an email with information required

**Comment by tananaev** [comment]
Are the database connection parameters the only ones you've changed?

**Comment by charlymanja** [comment]
yes, and log level params in wrapper

**Comment by tananaev** [comment]
Can you send me a dump of your MySQL database for investigation?

**Comment by charlymanja** [comment]
Send to you the dropbox link to your email

**Comment by tananaev** [comment]
I will take a look later.

**Comment by tananaev** [comment]
The problem is that some tables contain references to non-existing devices. I'm assuming that you have removed those, but referencing records haven't been removed.

**Comment by charlymanja** [comment]
Thx for solution!
Regards

**Comment by SebastEnn** [comment]
I guess you've taken your look and resolved any issues that have arisen.

Issue can be closed.
