### ISSUE TITLE
unknown protocol 

### ISSUE THREAD

**Issue by halie412** [traccar/traccar#1913]
hello several times I have met with Chinese GPS that do not work in the traccar server. And in my hex only show something like:

```
2016-04-27 16:59:58 DEBUG: [E168FFB4: 5002 < 181.246.69.252] HEX: 78780d010358899051726522001c250d0d0a
2016-04-27 17:00:19 DEBUG: [E168FFB4: 5002 < 181.246.69.252] HEX: 78780d010358899051726522001e061f0d0a
```

this has a solution? or am I doing something wrong?

**Comment by tananaev** [comment]
It's GT06 protocol, port 5023 in Traccar.

**Comment by wolfbgn** [comment]
Some Chinese sellers distribute models called TK103 which Traccar identifies as using  GT06 protocol, I use port 5023 and the first packet of data after turning the device on is decoded correctly. After that for some reason those devices lose connection with the server and stop sending data ( at least no data in log file ). This is Traccar 2.12.
If I set port 5000 device keeps sending data at the preset time interval which of course Traccar does not show in UI.

**Comment by tananaev** [comment]
Port number shouldn't make any difference, but if it does, you can always change GT06 to listen on port 5000. I doubt it would fix anything though.

**Comment by wolfbgn** [comment]
I don't mean that port makes any difference.
What I had in mind is that probably Chinese made some changes in protocol of these devices and there is a bug. Of course I have no way to be sure about that.

**Comment by tananaev** [comment]
Have you tried to contact device manufacturer about this issue?

**Comment by wolfbgn** [comment]
No, sir, and as a matter of fact I don't think this will be successful. I really don't want to waste your time.
Just shared my appinion as an amateur.

**Comment by tananaev** [comment]
So does it work on port 5000? If yes, just change Traccar to use port 5000 for GT06 and the problem is solved.

**Comment by SebastEnn** [comment]
Maybe he did this and his problem is now solved. Issue can be closed.
