### ISSUE TITLE
Raw data required

### ISSUE THREAD

**Issue by vipinjacob** [traccar/traccar#1914]
My client want raw data, so how can i get the raw data in my mysql database

**Comment by vipinjacob** [comment]
I am using traccar for only listening and inserting values to my server.

**Comment by tananaev** [comment]
You can use `database.saveOriginal` config parameter to save original raw data.

**Comment by Raja-RN** [comment]
Entry key is **database.saveOriginal ** Ok.
How i can identify the key name for raw data , and device id to insert database

**Comment by tananaev** [comment]
Internal device id can be accessed using `:deviceId` parameter. Raw data is in JSON in `:attributes` parameter.

**Comment by Raja-RN** [comment]
i am storing attributes in positions table its like {"alarm":true,"ignition":true,"status":0,"ip":"106.220.197.6"}.

But i need actual value from device.

**Comment by tananaev** [comment]
What version of Traccar are you using?

**Comment by Raja-RN** [comment]
I am using traccar-other-3.4

On 4 May 2016 at 04:16, Anton Tananaev <notifications@github.com> wrote:

> What version of Traccar are you using?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1914#issuecomment-216687734>
>



-- 
Regards,

*Kaliyugaraja M,*
Software Developer,

**Comment by tananaev** [comment]
You need to update to the latest version.

**Comment by Raja-RN** [comment]
Hi , I have one doubt about traccar ., Did traccar implements
multithreading or asynchronous .,

On 5 May 2016 at 11:27, Anton Tananaev <notifications@github.com> wrote:

> You need to update to the latest version.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1914#issuecomment-217081799>
>



-- 
Regards,

*Kaliyugaraja M,*
Software Developer,

**Comment by tananaev** [comment]
I'm guessing that the question you are trying to ask is whether Traccar uses asynchronous or synchronous network calls. It uses asynchronous calls.

**Comment by Raja-RN** [comment]
Is multi threading different from asynchronous or same?

If yes ,
Why traccar not implemented by multi threading ?


On 8 May 2016 at 03:19, Anton Tananaev <notifications@github.com> wrote:

> I'm guessing that the question you are trying to ask is whether Traccar
> uses asynchronous or synchronous network calls. It uses asynchronous calls.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1914#issuecomment-217670801>
>



-- 
Regards,

*Kaliyugaraja M,*
Software Developer,

**Comment by tananaev** [comment]
First you asking a question, and now you are asking what your own question means. It's two different things. Traccar uses both.

**Comment by Raja-RN** [comment]
Hi sir,

 I have one query about traccar3.5

I   downloaded   * traccar-other-3.5 *and installed manually , In manual
installation, I created Mysql database as from the instructions , In manual
installation , traccar does not create tables automatiically.



Log file shows :

2016-05-26 20:19:06  WARN: Table 'traccar.server' doesn't exist -
MySQLSyntaxErrorException (... < QueryBuilder:376 < *:275 < DataManager:457
< PermissionsManager:74 < ...)
2016-05-26 20:19:06  WARN: Table 'traccar.positions' doesn't exist -
MySQLSyntaxErrorException (... < QueryBuilder:376 < DataManager:452 <
ConnectionManager:55 < ...)
2016-05-26 20:19:07  INFO: Starting server...





Like this ,

Whether traccar create tables automatically in MYSQL , Or we need to create
tablees? If we need to create tables means where i will get the .sql file .





On 9 May 2016 at 15:44, Anton Tananaev <notifications@github.com> wrote:

> First you asking a question, and now you are asking what your own question
> means. It's two different things. Traccar uses both.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1914#issuecomment-217827032>
>



-- 
Regards,

*Kaliyugaraja M,*
Software Developer,

**Comment by tananaev** [comment]
Traccar creates database tables automatically. I guess your config is incorrect if it doesn't.

**Comment by Raja-RN** [comment]
This is my Mysql config ,



<entry key='database.driver'>com.mysql.jdbc.Driver</entry>
<entry key='database.url'>jdbc:mysql://*[MYIP]*:3306/*[MYDB]*
?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
<entry key='database.user'>*[MYUSERNAME]*</entry>
<entry key='database.password'>*[MYPASSWORD]*</entry>




What i want to change , to create tables automatically

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On 26 May 2016 at 22:17, Anton Tananaev <notifications@github.com> wrote:

> Traccar creates database tables automatically. I guess your config is
> incorrect if it doesn't.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1914#issuecomment-221928171>
>



-- 
Regards,

*Kaliyugaraja M,*
Software Developer,

**Comment by tananaev** [comment]
1. It's not full config
2. Instead of your ip address in the database URL, you should use localhost (unless database is on different server)
3. Please answer through GitHub so config can be properly formatted

**Comment by Raja-RN** [comment]
##########################################################################


<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    

    <entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>[WEB]</entry>

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>[LOG]</entry>

    
	 

<entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
<entry key='database.url'>jdbc:mysql://localhost:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
<entry key='database.user'>root</entry> 
<entry key='database.password'>password</entry>
	

    

    <entry key='database.selectServers'>
        SELECT * FROM server;
    </entry>

    <entry key='database.updateServer'>
        UPDATE server SET
        registration = :registration,
        readonly = :readonly,
        map = :map,
        bingKey = :bingKey,
        mapUrl = :mapUrl,
        distanceUnit = :distanceUnit,
        speedUnit = :speedUnit,
        latitude = :latitude,
        longitude = :longitude,
        zoom = :zoom,
        twelveHourFormat = :twelveHourFormat
        WHERE id = :id;
    </entry>

    <entry key='database.loginUser'>
        SELECT * FROM users
        WHERE email = :email;
    </entry>

    <entry key='database.selectUser'>
        SELECT * FROM users
        WHERE id = :id;
    </entry>

    <entry key='database.selectUsersAll'>
        SELECT * FROM users;
    </entry>

    <entry key='database.insertUser'>
        INSERT INTO users (name, email, hashedPassword, salt, admin, map, distanceUnit, speedUnit, latitude, longitude, zoom, twelveHourFormat)
        VALUES (:name, :email, :hashedPassword, :salt, :admin, :map, :distanceUnit, :speedUnit, :latitude, :longitude, :zoom, :twelveHourFormat);
    </entry>

    <entry key='database.updateUser'>
        UPDATE users SET
        name = :name,
        email = :email,
        admin = :admin,
        map = :map,
        distanceUnit = :distanceUnit,
        speedUnit = :speedUnit,
        latitude = :latitude,
        longitude = :longitude,
        zoom = :zoom,
        twelveHourFormat = :twelveHourFormat
        WHERE id = :id;
    </entry>

    <entry key='database.updateUserPassword'>
        UPDATE users SET hashedPassword = :hashedPassword, salt = :salt WHERE id = :id;
    </entry>

    <entry key='database.deleteUser'>
        DELETE FROM users WHERE id = :id;
    </entry>

    <entry key='database.selectDevicePermissions'>
        SELECT userId, deviceId FROM user_device;
    </entry>

    <entry key='database.selectGroupPermissions'>
        SELECT userId, groupId FROM user_group;
    </entry>

    <entry key='database.selectDevicesAll'>
        SELECT * FROM devices;
    </entry>

    <entry key='database.insertDevice'>
        INSERT INTO devices (name, uniqueId, groupId) VALUES (:name, :uniqueId, :groupId);
    </entry>

    <entry key='database.updateDevice'>
        UPDATE devices SET name = :name, uniqueId = :uniqueId, groupId = :groupId WHERE id = :id;
    </entry>

    <entry key='database.updateDeviceStatus'>
        UPDATE devices SET status = :status, lastUpdate = :lastUpdate WHERE id = :id;
    </entry>

    <entry key='database.deleteDevice'>
        DELETE FROM devices WHERE id = :id;
    </entry>

    <entry key='database.linkDevice'>
        INSERT INTO user_device (userId, deviceId) VALUES (:userId, :deviceId);
    </entry>

    <entry key='database.unlinkDevice'>
        DELETE FROM user_device WHERE userId = :userId AND deviceId = :deviceId;
    </entry>

    <entry key='database.selectGroupsAll'>
        SELECT * FROM groups;
    </entry>

    <entry key='database.insertGroup'>
        INSERT INTO groups (name) VALUES (:name);
    </entry>

    <entry key='database.updateGroup'>
        UPDATE groups SET name = :name, groupId = :groupId WHERE id = :id;
    </entry>

    <entry key='database.deleteGroup'>
        DELETE FROM groups WHERE id = :id;
    </entry>

    <entry key='database.linkGroup'>
        INSERT INTO user_group (userId, groupId) VALUES (:userId, :groupId);
    </entry>

    <entry key='database.unlinkGroup'>
        DELETE FROM user_group WHERE userId = :userId AND groupId = :groupId;
    </entry>

    <entry key='database.selectPositions'>
        SELECT * FROM positions WHERE deviceId = :deviceId AND fixTime BETWEEN :from AND :to ORDER BY fixTime;
    </entry>

    <entry key='database.insertPosition'>
        INSERT INTO positions (deviceId, protocol, serverTime, deviceTime, fixTime, valid, latitude, longitude, altitude, speed, course, address, attributes)
        VALUES (:deviceId, :protocol, :now, :deviceTime, :fixTime, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :attributes);
    </entry>

    <entry key='database.selectLatestPositions'>
        SELECT * FROM positions WHERE id IN (SELECT positionId FROM devices);
    </entry>

    <entry key='database.updateLatestPosition'>
        UPDATE devices SET positionId = :id WHERE id = :deviceId;
    </entry>

    
	
	
   <entry key='gt06.port'>22223</entry>

   

</properties>


############################################################################




This is my full config., And i have used localhost , But tables not created automatically..

**Comment by tananaev** [comment]
Why have you commented out `database.changelog` parameter?

**Comment by Raja-RN** [comment]
Hi ,

Thanks for your response , It is very  usefull for us ,

I found my mistake about create tables automatically ,

Now it create tables automatically ,






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On 27 May 2016 at 21:43, Anton Tananaev <notifications@github.com> wrote:

> Why have you commented out database.changelog parameter?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tananaev/traccar/issues/1914#issuecomment-222188639>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASR1IrUmtJ4-jpn44mAzFIsQ3F0p-rZyks5qFxgzgaJpZM4IS6M7>
> .
>



-- 
Regards,

*Kaliyugaraja M,*
Software Developer,

**Comment by Raja-RN** [comment]
Hi sir ,
I have another issue

Web ui not working , How to run it on my browsers ,

I am using centos 6 , and mysql database

Here i attached my we configuration text for web ,


    

    <entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>/var/www/html/javaports3.5/web</entry>

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>[LOG]</entry>




I extracted *traccar-other-3.5.zip *, in inside the javaports3.5 folder ,

And how config my  static IP , and run it using MY IP in browser











On 28 May 2016 at 15:56, Raja MK <raja.avancer@gmail.com> wrote:

> Hi ,
>
> Thanks for your response , It is very  usefull for us ,
>
> I found my mistake about create tables automatically ,
>
> Now it create tables automatically ,
>
>
>
>
>
>
>
> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail> Virus-free.
> www.avast.com
> <https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
> <#m_-2924198831640296341_DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
>
> On 27 May 2016 at 21:43, Anton Tananaev <notifications@github.com> wrote:
>
>> Why have you commented out database.changelog parameter?
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/tananaev/traccar/issues/1914#issuecomment-222188639>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ASR1IrUmtJ4-jpn44mAzFIsQ3F0p-rZyks5qFxgzgaJpZM4IS6M7>
>> .
>>
>
>
>
> --
> Regards,
>
> *Kaliyugaraja M,*
> Software Developer,
>
>


-- 
Regards,

*Kaliyugaraja M,*
Software Developer,

**Comment by tananaev** [comment]
Why are you not using Linux installer? Also, please reply through GitHub.

**Comment by Raja-RN** [comment]
I need to customise the traccar , If i will use installer means how i will change . Manual installation means I can customise . So that i am using *traccar-other-3.5.zip*

**Comment by tananaev** [comment]
What exactly do you need to customize? You can just replace files after installation same as with "other" version.

**Comment by Raja-RN** [comment]
Hi sir ,

 Can you tell me what is the maximum number of vehicles i can connect to a
single port using TRACCAR.

On 30 May 2016 at 16:49, Anton Tananaev <notifications@github.com> wrote:

> What exactly do you need to customize? You can just replace files after
> installation same as with "other" version.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tananaev/traccar/issues/1914#issuecomment-222471051>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASR1IpY-AfckBHMRL_Y_Vxlu-BlM69hUks5qGsfFgaJpZM4IS6M7>
> .
>



-- 
Regards,

*Kaliyugaraja M,*
Software Developer,

**Comment by tananaev** [comment]
There is no limit. Traccar has been tested with 100k devices and more.

**Comment by SebastEnn** [comment]
All questions answered. Issue can be closed.
