### ISSUE TITLE
Bug with traccar and opengts integration (last version of Mac OS X)

### ISSUE THREAD

**Issue by achi2211** [traccar/traccar#1915]
Hi there, 

I have been working with integration between traccar and opengts and I have found the next bugs: 
1s) in traccar.xml if you guys set web.enable as false it throws NullPointerException in log file. I have to set as true.
2) in database.insertPosition the param :time is not recognized I had to remove it. Finally my insertPosition sql transaction looks like that: 

```
<entry key='database.insertPosition'>
        START TRANSACTION;
            UPDATE Device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = UNIX_TIMESTAMP(NOW()), lastUpdateTime = UNIX_TIMESTAMP(NOW()) WHERE imeiNumber = :deviceId;
            SELECT @accountID := accountID, @deviceID := deviceID FROM Device WHERE imeiNumber = :deviceId;
            INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, creationTime, address)
            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(NOW()), 0, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', UNIX_TIMESTAMP(NOW()), :address);
        COMMIT;
    </entry>
```

That works for me. 

Regards!

**Comment by tananaev** [comment]
1) This is a know issue and I'm working on it.

2) Where did you find `:time` parameter? I thought I've updated all the documentation to remove it.

**Comment by achi2211** [comment]
Great!

the code with :time parameter I copied from https://www.traccar.org/opengts/ last week but I just checked and I could see is updated, now par name is :fixTime I tested and that works fine! Awesome job buddy!!

**Comment by SebastEnn** [comment]
1. solved?
2. is it removed?

Maybe this can be closed?

**Comment by tananaev** [comment]
This integration is not supported anymore. The forwarding option should be used instead now.
