### ISSUE TITLE
cannot build intellij

### ISSUE THREAD

**Issue by beryindo** [traccar/traccar#1916]
What wrong ?
![screenshot_1312](https://cloud.githubusercontent.com/assets/11897545/14938919/6433e3fc-0f5e-11e6-9ca0-fbff1a000fa7.png)

**Comment by tananaev** [comment]
Everything seems fine.

**Comment by beryindo** [comment]
but can't open localhost:8082
why ?

**Comment by tananaev** [comment]
What config file are you using?

**Comment by beryindo** [comment]
config original, I am not edit config
I using windows 7 64 bit, java, jdk 8

**Comment by tananaev** [comment]
What do you mean by original?

**Comment by beryindo** [comment]
where config in traccar-web ? I not install traccar in my pc.

**Comment by tananaev** [comment]
How do you run Traccar without a config?

**Comment by beryindo** [comment]
I read from here
![screenshot_1316](https://cloud.githubusercontent.com/assets/11897545/14941855/1348f992-0fd5-11e6-8826-afc560a2abb6.png)

**Comment by tananaev** [comment]
So you are using `debug.xml` as your config. You might need to adjust paths there.

**Comment by mircea2003** [comment]
use  netbeans

**Comment by SebastEnn** [comment]
netbeans lmao. I guess he just changed his config.

Issue can be closed.

**Comment by tananaev** [comment]
Netbeans used to be the recommended option when we had maven project.
