### ISSUE TITLE
New column in devices table

### ISSUE THREAD

**Issue by mm108** [traccar/traccar#1917]
If I want to add another column in the devices table to maintain the color of the marker or the marker shape, can I just add a column to the table devices and alter this query in 

```
<entry key='database.insertDevice'>
    INSERT INTO devices (name, uniqueId, groupId, markerColor) VALUES (:name, :uniqueId, :groupId, :markerColor);
</entry>
```

traccar.xml with the additional column as shown above? Thanks

And also a simple question - When a device is added I believe it happens in 2 steps? First step is that the device is added to the devices table, and then a link is set between the device and the userid - am I  correct in guessing that? Thanks a ton for your time

**Comment by tananaev** [comment]
Yes, you can just add it to the query.

You are correct about two steps.

**Comment by m-menon** [comment]
Thank you so much. Really appreciate your time in answering my questions :+1:

**Comment by SebastEnn** [comment]
Question answered. Issue can be closed.
