### ISSUE TITLE
Conversion of UTM coordinates to Spherical coordinates

### ISSUE THREAD

**Issue by Siegejhei** [traccar/traccar#1921]
How can I convert  UTM coordinates to spherical coordinates?? can you teach me how?? If it's possible.

**Comment by Siegejhei** [comment]
How can I convert  UTM coordinates to spherical coordinates?? can you teach me how??

**Comment by tananaev** [comment]
It's not supported yet, but it's possible to implement it in one of the future versions.

**Comment by Siegejhei** [comment]
Ok sir. thanks a lot. I hope it will be implemented  in one of the future version. :)

**Comment by tananaev** [comment]
I will implement it at some point.

**Comment by Siegejhei** [comment]
Ok sir. Thank you so much for spending time to reply in my request. :).  I am looking forward for the new version of traccar.

**Comment by Siegejhei** [comment]
Is GDC supported by traccar??

**Comment by tananaev** [comment]
What is GDC?

**Comment by Siegejhei** [comment]
Geodetic coordinate system.

**Comment by tananaev** [comment]
I need some more details. What do GDC coordinates look like?

**Comment by Siegejhei** [comment]
http://www-lite.larc.nasa.gov/level1doc/geodetic_coords.html

**Comment by Siegejhei** [comment]
I think GDC is more like an spherical coordinate.. I'm not sure! :D

**Comment by tananaev** [comment]
Isn't it just regular coordinates?

**Comment by Siegejhei** [comment]
I think it is. I'm wondering to convert UTM >> GDC >> Spherical coordinates to make it easier. :) what do you think?

**Comment by tananaev** [comment]
I think it's just some general term and not a specific format.

**Comment by Siegejhei** [comment]
ok sir. thank you very much!! :+1:

**Comment by SebastEnn** [comment]
Question answered. Issue can be closed.

But, is UTM coordinates to spherical coordinates conversion implemented or what's the status?

**Comment by tananaev** [comment]
I don't think there's any status. It's not clear what needs to be implemented.
