### ISSUE TITLE
Replace h2 database with firebase?

### ISSUE THREAD

**Issue by onethings** [traccar/traccar#1925]
Can traccar use firebase as database? And which I have file to edit ( configuration file )?

**Comment by tananaev** [comment]
It might be possible, but it won't be as easy as with some other databases. Why do you need it?

**Comment by onethings** [comment]
I'm consider for separate server and database and scalability also include cost :)

**Comment by tananaev** [comment]
It doesn't actually answer the question. I don't think Firebase is best in any of those characteristics.

Anyway, if there is a JDBC driver, it should be possible. There might be some query tweaking (in config) required. Automatic database creation using Liquibase changelogs probably won't work either.
