### ISSUE TITLE
selected group vehicles shown on live map 

### ISSUE THREAD

**Issue by digitaltrackit** [traccar/traccar#1929]
I want that once a particular group is selected , only the vehicles on that selected  group should be shown on the live map. what changes should i do?  please advice.

**Comment by tananaev** [comment]
You need to modify `MapController` class.

**Comment by digitaltrackit** [comment]
Thanks  sir 
Can you please guide what  modification I need to do in MapController ?

**Comment by tananaev** [comment]
What kind of guidance do you need?

**Comment by digitaltrackit** [comment]
I want only vehicles on that selected group will show on map.  not other groups or all vehicle.  what necessary changes i need to do in  MapController as u suggested  before.

**Comment by tananaev** [comment]
Do you want me to write code for you? If yes, send me an email to discuss it.

**Comment by digitaltrackit** [comment]
my e mail id is digitaliconsolutions@gmail.com

On Sun, May 8, 2016 at 5:39 PM, Anton Tananaev <notifications@github.com>
wrote:

> Do you want me to write code for you? If yes, send me an email to discuss
> it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1929#issuecomment-217712239>
>



-- 
Mangesh Mane
Digital Icon Solutions
9822876332

#CCTV #CCTV-AMC #Computers & Laptops #Computer Accessories
#Computers/Networking AMC

**Comment by tananaev** [comment]
My email address is in GitHub profile.
