### ISSUE TITLE
Rename Export csv/gpx 

### ISSUE THREAD

**Issue by spaceruv** [traccar/traccar#1939]
when I export in CSV or GPX it renames the file in an automatic traccar-positions, can I change the name and add date and time of start and end date-time filter?
Thanks.

**Comment by tananaev** [comment]
Traccar doesn't have export functionality yet.

**Comment by spaceruv** [comment]
sorry I meant Traccar Web UI


Luca Ruvolo
IT Manager
Mobile: +39 366 5759443 
 <http://www.rifatech.it/firma.png> 
Rifatech Soluzioni Innovative s.r.l.
Sede Legale e operativa: via Leonardo da Vinci snc - 93100 Caltanissetta CL – Italy
Sede operativa: viale Trieste, 80 – 93100 Caltanissetta CL – Italy

Uffici commerciali: via Senigallia 18/2 Torre A – 20161 Milano – Italy
Tel. +39 0934 597397 - Fax +39 0934 1965110 – Numero verde 800 129762

Web: http://www.rifatech.it <http://www.rifatech.it/>  – info@rifatech.it <mailto:info@rifatech.it>  - PEC: rifatechsoluzioniinnovativesrl@pec.it <mailto:rifatechsoluzioniinnovativesrl@pec.it> 

Partita IVA 01884320852 – REA 105580

--------------------------------
CONFIDENZIALE: Questo messaggio e gli eventuali allegati sono confidenziali e riservati. Se vi è stato recapitato per errore e non siete fra i destinatari elencati, siete pregati di darne immediatamente avviso al mittente. Le informazioni contenute non devono essere mostrate ad altri, né utilizzate, memorizzate o copiate in qualsiasi forma.
CONFIDENTIAL: This  e-mail  and  any attachments are confidential and may contain reserved information. If  you are not one of the named recipients, please notify the sender immediately. Moreover, you should not disclose the contents to any other persons, nor should the information contained be used for any purpose or stored or copied in any form.

-----Messaggio originale-----
Da: Anton Tananaev <notifications@github.com>
Inviato: Mercoledì 11th Maggio 2016 14:57
A: tananaev/traccar <traccar@noreply.github.com>
Cc: luca <luca.ruvolo@rifatech.it>; Author <author@noreply.github.com>
Oggetto: Re: [tananaev/traccar] Rename Export csv/gpx (#1939)

Traccar doesn't have export functionality yet.

**Comment by tananaev** [comment]
Traccar web UI from Litvak is not an official Traccar project. It has it's own repository and issue tracker.

**Comment by spaceruv** [comment]
sorry for disturbing!

Luca Ruvolo
IT Manager
Mobile: +39 366 5759443 
 <http://www.rifatech.it/firma.png> 
Rifatech Soluzioni Innovative s.r.l.
Sede Legale e operativa: via Leonardo da Vinci snc - 93100 Caltanissetta CL – Italy
Sede operativa: viale Trieste, 80 – 93100 Caltanissetta CL – Italy

Uffici commerciali: via Senigallia 18/2 Torre A – 20161 Milano – Italy
Tel. +39 0934 597397 - Fax +39 0934 1965110 – Numero verde 800 129762

Web: http://www.rifatech.it <http://www.rifatech.it/>  – info@rifatech.it <mailto:info@rifatech.it>  - PEC: rifatechsoluzioniinnovativesrl@pec.it <mailto:rifatechsoluzioniinnovativesrl@pec.it> 

Partita IVA 01884320852 – REA 105580

--------------------------------
CONFIDENZIALE: Questo messaggio e gli eventuali allegati sono confidenziali e riservati. Se vi è stato recapitato per errore e non siete fra i destinatari elencati, siete pregati di darne immediatamente avviso al mittente. Le informazioni contenute non devono essere mostrate ad altri, né utilizzate, memorizzate o copiate in qualsiasi forma.
CONFIDENTIAL: This  e-mail  and  any attachments are confidential and may contain reserved information. If  you are not one of the named recipients, please notify the sender immediately. Moreover, you should not disclose the contents to any other persons, nor should the information contained be used for any purpose or stored or copied in any form.

-----Messaggio originale-----
Da: Anton Tananaev <notifications@github.com>
Inviato: Mercoledì 11th Maggio 2016 15:09
A: tananaev/traccar <traccar@noreply.github.com>
Cc: luca <luca.ruvolo@rifatech.it>; Author <author@noreply.github.com>
Oggetto: Re: [tananaev/traccar] Rename Export csv/gpx (#1939)

Traccar web UI from Litvak is not an official Traccar project. It has it's own repository and issue tracker.
