### ISSUE TITLE
Handle error in command framework

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar#1952]
Hello, I'm testing new framework #1920 a bit

Requesting `/api/commandtypes?deviceId=1` while device is not connected to server (sleep) I've got error

```
{"message":null,"details":"NullPointerException (CommandTypeResource:39 < ...)"}
```

If i click on "command" in browser, I've got

```
GET https://traccar.xxx.xxx/api/commandtypes?deviceId1&_dc=xxxxxxxxxxxxx&query=&deviceId=1&page=1&start=0&limit=25 400 (Bad Request)
```

I think in https://github.com/tananaev/traccar/blob/master/src/org/traccar/api/resource/CommandTypeResource.java#L39 there is no check if `getActiveDevice(deviceId)` returned something.
May be api should return error but not the exception.

And I think It is better totally disable "Command" button in web interface while device is not active to avoid user confusing.

**Comment by tananaev** [comment]
I think exception is fine in this case, but maybe it should be converted to more readable format for the use.
