### ISSUE TITLE
Coban 103 protocol 18 

### ISSUE THREAD

**Issue by ephedrine** [traccar/traccar#1954]
Hi there . Who have a document of new coban gprs protocol ?

They call protocol 18 . it's come with fuel level . And other I/O .

**Comment by tananaev** [comment]
Most documentation that I have is here:

https://www.traccar.org/protocols/

**Comment by ephedrine** [comment]
Thank you friend . But this document is not include new protocol .

:)

**Comment by tananaev** [comment]
Then I guess I don't have it. Please share if you manage to find it.

**Comment by ephedrine** [comment]
yes sure . I will

**Comment by maxicabanillas78** [comment]
[coban GPRS PROTOCOL_COCO HUO  20141212 (1).pdf](https://github.com/tananaev/traccar/files/271381/coban.GPRS.PROTOCOL_COCO.HUO.20141212.1.pdf)

Protocol Coban 103

**Comment by ephedrine** [comment]
Thank you , maxicabanillas78

**Comment by GSMELECTRONICO** [comment]
good afternoon friends need help with events coban 103a
my problem is that my platform does not identify the next event
imei:868683021509447,ac alarm,160718000158, ,F,040155.000,A,0819.5862,N,07205.0376,W,0.00,0;|
not how to make it reconnoitre can help me please

**Comment by tananaev** [comment]
@GSMELECTRONICO, it's GPS103 protocol, so correct port is 5001.
