### ISSUE TITLE
mobile showing send failed error 

### ISSUE THREAD

**Issue by jaypan007** [traccar/traccar#1956]
I have installed traccar server on my pc. having a static IP and registered a mobile device with correct identifier. i have put correct ip add of server in client app and default port 5055. even than it shows send failed. Kindly resolver

**Comment by dschense** [comment]
when its a PC with static IP connection, then you have to open the Port in Router. When using a server, and use iptables and use a DROP ALL Statement, then you have to directly accept incoming traffic over 5055 in the iptables config.
maybe you must give some more informations of your setup.

**Comment by tananaev** [comment]
@jaypan007, please read following page:

https://www.traccar.org/troubleshooting/
