### ISSUE TITLE
About Port 

### ISSUE THREAD

**Issue by kedarnathjimage** [traccar/traccar#1960]
I am using Gosafe G3A GPS Device. I am unable to see the device on map, when i check the log i get this hex. I am sending the data on port 5078

```
2a475330322c3335353233333035343639383931332c434c4c3a3030303030303030303030303b3430343b32323b31303133353b313233312c5354543a34303b302c4144433a303b31312e393b313b34342e303b323b342e323b333b302e3023
```

Any input on this will be highly appreciated. Thanks

**Comment by tananaev** [comment]
Your device doesn't send any GPS info. Possibly it doesn't have a GPS fix.
