### ISSUE TITLE
Telic wrong GPS Data - Decoder

### ISSUE THREAD

**Issue by dschense** [traccar/traccar#1961]
Iam running a telic tracker. It connects fine to the server over Port 5067.
But there seems to be a Problem with some formats:

clear Data looks like this:

```
0026405066|262|01|004006005 a   
002140506699,230315094200,0,230315094200,96729,486867,3,0,2,11,,,335,258625,,0110,00,202,0,0,0100
```

lat: 486867
lon: 96729

TelicProtocolDecoder.java tells:

```
private static final Pattern PATTERN = new PatternBuilder()
            .number("dddd")
            .number("(d{6})")                    // device id
            .number("(d+),")                     // type
            .number("d{12},")                    // event time
            .number("d+,")
            .number("(dd)(dd)(dd)")              // date
            .number("(dd)(dd)(dd),")             // time
            .groupBegin()
            .number("(ddd)(dd)(dddd),")          // longitude
            .number("(dd)(dd)(dddd),")           // latitude
            .or()
            .number("(-?d+),")                   // longitude
            .number("(-?d+),")                   // latitude
            .groupEnd()
            .number("(d),")                      // validity
            .number("(d+),")                     // speed
            .number("(d+),")                     // course
            .number("(d+),")                     // satellites
            .expression("(?:[^,]*,){7}")
            .number("(d+),")
            .any()
            .compile();
```

This is the HEX:

```
303032363430353036367c3236327c30317c30303430303630303500680000003030323134303530363639392c3139303531363038313230302c302c3139303531363038313230312c3030393637343430302c34383638373134362c332c302c34392c31302c2c2c3335342c3333323239392c2c303031302c30302c3137382c302c302c3031303000
```

Decoded:

```
0026405066|262|01|004006005�h���002140506699,190516081200,0,190516081201,009674400,48687146,3,0,49,10,,,354,332299,,0010,00,178,0,0,0100�
```

Info Log tells:

```
time: 2016-05-19 08:12:01, lat: 49.14524, lon: 10.12400, speed: 0.0, course: 49.0
```

the GPS data are not fine. Anybody with Idea?

These should be the right coordinates 

```
009674400,48687146
```

but the server uses

```
lat: 49.14524, lon: 10.12400
```

**Comment by tananaev** [comment]
So what are the right coordinates?

**Comment by dschense** [comment]
The right coordinates are:

lon:009674400
lat:48687146

and its showing

lat:49.14524
lon:10.12400

**Comment by tananaev** [comment]
Coordinates should be in degrees. Neither 009674400 nor 48687146 are degrees values.

**Comment by dschense** [comment]
for shure ;) but thats what the device is sending to the server ^^

**Comment by tananaev** [comment]
It has to be decoded. That's what Traccar does.

**Comment by argokask** [comment]
What kind of Telic are you using? 

I have using Picotracker and SBC-AVL, but they both have exactly the same protocol format and never seen problems with coordinates.

**Comment by hschuenemann** [comment]
Have you found a solution for this? 

I have the same problem with a Telic SBC_AVL and Picotrack Endurance devices (described here: https://www.traccar.org/forums/topic/telic-decoding-with-wrong-longlat/)

I guess the right coordinates in the example above should be: 
48.687146° and 9.674400°

It is strange that this is working for @argokask ... I use the latest docker image but even on the demo server i have the same problems.
