### ISSUE TITLE
IOException and StringIndexOut...

### ISSUE THREAD

**Issue by atiliocd** [traccar/traccar#1967]
Greetings!

In log files i can see this specifics warning messages:

WARN: [F82650E4] error - String index out of range: -1 - StringIndexOutOfBoundsException (... < Tlt2hProtocolDecoder:66 < ExtendedObjectDecoder:59 < ...)

AND

WARN: [68E642A7] error - Tempo esgotado para conexão - IOException (...)

Running traccar latest version and Ubuntu 12 and Java 8.

Can someone send me a light in this "problem".

**Comment by tananaev** [comment]
To check the first warning, I need to see corresponding HEX message.

Second warning is just connection timeout.

**Comment by atiliocd** [comment]
How can i provide this information to you Tanaev?

**Comment by tananaev** [comment]
If you don't want to share it here, you can send me an email (address is in profile).

**Comment by atiliocd** [comment]
Is there
