### ISSUE TITLE
Cant figure out wich port to use on my TK110 device...

### ISSUE THREAD

**Issue by Estebanmg** [traccar/traccar#1969]
Been looking around how to solve this but I was just not able to do so... 

Tho I managed to decode a hex from the device, but I havent been able to identify the right protocol.

This is the decoded hex:

```
(087072506813BZ00,334,003,2b0d,7aa9,2b0d,78df,2b0d,778b,2b0d,78de,2b0d,778a,2b0d,7597,01000000)
```

Thanks in advance

**Comment by Estebanmg** [comment]
Solved it, it turned out to be a tk103 device.

Another question, why it shows ignition on even tho it is not plugged to the car yet...?

And what would be the right command to set the reporting interval higher, it is reporting every 20 seconds by default, would like to change it to 60 sec

**Comment by tananaev** [comment]
If it shows ignition,, it means that your device reports it.

Traccar doesn't support commands for TK103 protocol yet, so you need to configure it using SMS. Check device manual for command format.

**Comment by vbonne** [comment]
Hi Tananaev,

Which protocols are fully supported by traccar in order to be able to send commands ? based on this I will purchase device...

thanks !

**Comment by tananaev** [comment]
You can take a look at `*Protocol.java` classes to see the list of commands that's supported by particular protocol. Different protocols support different set of commands.

It's always possible to add support for commands for a protocol that doesn't support it at the moment. Contact me if you choose this option.

**Comment by vbonne** [comment]
Thanks a lot Tananaev, I will go for gps103 protocol then. Already purchased one item. I will test it.
