### ISSUE TITLE
Could not run the project.

### ISSUE THREAD

**Issue by amitbatajoo** [traccar/traccar#1972]
As I run the project in netbeans 8.1 window 10 using source code i get the error message

_**Exception in thread "main" java.lang.NullPointerException
    at org.traccar.database.PermissionsManager.refresh(PermissionsManager.java:75)
    at org.traccar.database.PermissionsManager.<init>(PermissionsManager.java:67)
    at org.traccar.Context.init(Context.java:178)
    at org.traccar.Main.main(Main.java:30)**_

Please let me know the cause of error and workable steps to run the server using netbeans.
thank you

**Comment by tananaev** [comment]
Have you provided a config file?

**Comment by amitbatajoo** [comment]
I really have no idea how to provide a config file, can you tell me the steps or provide me some work able tutorial .

Thank you

**Comment by tananaev** [comment]
Please see the following page:

https://www.traccar.org/build-in-netbeans/

**Comment by amitbatajoo** [comment]
@tananaev ..thank you very much it works now.

**Comment by amitbatajoo** [comment]
Dear Tananaev

Thank you for your previous tutorial, it works but I have a problem that
the server and client in different IP address location is unable to track
the position of client. Can you please suggest me any configuration so that
client in any other ip address location can be detected by the server in
different ip addres location.

Advance Thank you



On Wed, May 25, 2016 at 2:15 AM, Anton Tananaev <notifications@github.com>
wrote:

> Please see the following page:
>
> https://www.traccar.org/build-in-netbeans/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1972#issuecomment-221339373>
>



-- 
Er. BATAJOO, Amit
Researcher
Wakkanai Hokusei Gakuen University
Wakkanai, Hokkaido, Japan
-----------------------------------------------------------------------
Skype : abatajoo7
E-Mail :batajooseamusu7@gmail.com,batajooamit@gmail.com,
bataj007amit@gmail.com

**Comment by tananaev** [comment]
As long as your server address is accessible from client, it should be fine.

**Comment by amitbatajoo** [comment]
@tananaev how can I integrate the web User Interface of traccar in web site developed for user developed in PHP, can you provide me tutorial.

thank you in advance

**Comment by tananaev** [comment]
What do you mean by integration?

**Comment by amitbatajoo** [comment]
@tananaev  I have a website for client and I want to show the map on their profile with client login, so I want to integrate the tracked map of traccar in my another site. is this possible or do i need some plugins. please suggest me the solution.
thank you

**Comment by tananaev** [comment]
The easiest option is to put it into a frame.

**Comment by amitbatajoo** [comment]
@tananaev  can you help me some sample work or tutorial for it

**Comment by tananaev** [comment]
Check this page:

http://www.w3schools.com/tags/tag_iframe.asp

**Comment by amitbatajoo** [comment]
Subject Line (for proofing, doesn't show in actual email)
<https://www.digitalocean.com>                         == Deploy a Server
For Free! ==

  Your friend Amit Batajoo has been using DigitalOcean – a cloud hosting
service designed just for developers – and thought you might want to give
it a shot. You can deploy a server in 55 seconds from our control panel or
use our simple API. 

 Because you’ve been invited by a friend, we’d like to give you a $10
credit to try it out. Just use this link to create an account and you’ll
be credited automatically.

 Redeem Your Credit
<https://cloud.digitalocean.com/accept?code=067c756451985b&amp;utm_campaign=Referral_Invite&amp;utm_medium=Referral_Program&amp;utm_source=Mandrill>

  Happy Coding,
 DigitalOcean 

            © DigitalOcean <http://do.co/email_twitter>
<http://do.co/email_gplus> <http://do.co/email_facebook>

**Comment by amitbatajoo** [comment]
@tananaev thank you for your suggestion. Currently I am working to use this
application for my research purpose.
Could you introduce me any previously implemented client application in php
which are openly available. Or any helpful resources so that it would be
helpful for my research too. I would certainly be happy to contribute my
research for this application.
Thank you for your help.


On Wed, Jun 1, 2016 at 7:17 PM, Anton Tananaev <notifications@github.com>
wrote:

> Check this page:
>
> http://www.w3schools.com/tags/tag_iframe.asp
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tananaev/traccar/issues/1972#issuecomment-222951702>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF7N_pRj4Z8XwTCz6BL9lVin2dBxRIWgks5qHVwsgaJpZM4IkZMt>
> .
>



-- 
Er. BATAJOO, Amit
Researcher
Wakkanai Hokusei Gakuen University
Wakkanai, Hokkaido, Japan
-----------------------------------------------------------------------
Skype : abatajoo7
E-Mail :batajooseamusu7@gmail.com,batajooamit@gmail.com,
bataj007amit@gmail.com

**Comment by tananaev** [comment]
Take a look at this project:

https://www.traccar.org/forums/topic/new-web-interface-for-traccar-server-made-for-joomla/
