### ISSUE TITLE
Load CSV (from TK102 offline) to Database MYSQL

### ISSUE THREAD

**Issue by juanpnaranjo** [traccar/traccar#1974]
Good day, I tried to load the database data from csv file generated by the GPS, but the format did not coordinate corresponds to the current location. Colombia Bogota

Anyone know what kind of conversion should do?

I'm trying to do the coordinate transformation with Pyproj.

This is an example of the data sent by the GPS.

imei: 868683022727329, tracker, 160512022646, F, 182645.000, A, 0439.8549, N, 07404.3335, W, 3.31,157.21;

**Comment by tananaev** [comment]
Please don't duplicate your questions.
