### ISSUE TITLE
Table 'traccar.server' doesn't exist

### ISSUE THREAD

**Issue by ucheobere** [traccar/traccar#1983]
After migrating to Mysql, get table 'traccar.server' doesn't exist. here is the tracker server log. 
Pls any idea what might be the problem?

```
2016-05-29 19:50:07  INFO: Shutting down server...
2016-05-29 19:50:08  INFO: Operating system name: Linux version: 3.13.0-74-generic architecture: amd64
2016-05-29 19:50:08  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.91-b14
2016-05-29 19:50:08  INFO: Memory limit heap: 241mb non-heap: 0mb
2016-05-29 19:50:08  INFO: Character encoding: UTF-8 charset: UTF-8
2016-05-29 19:50:08  INFO: Version: 3.5-SNAPSHOT
2016-05-29 19:50:09  WARN: Table 'traccar.server' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:376 < *:275 < DataManager:457 < PermissionsManager:74 < ...)
2016-05-29 19:50:10  INFO: Starting server...
```

**Comment by tananaev** [comment]
What version of Traccar are you using? Have you changed the config?

**Comment by ucheobere** [comment]
I am running version 3.5 and I changed the config to this...

<entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8</entry>
<entry key='database.user'>root</entry> 
<entry key='database.password'>un1f13d</entry>

**Comment by tananaev** [comment]
Do you have `database.changelog` parameter in your config?

**Comment by ucheobere** [comment]
I have it like this  
`<!-- entry key='database.changelog'>C:\Program Files (x86)\Traccar\data\changelog-master.xml</entry -->`

**Comment by tananaev** [comment]
Why is it commented out?

**Comment by ucheobere** [comment]
I was following a blog instruction. Pls what am I suppose to put there. I am running the service on ubuntu 14

**Comment by tananaev** [comment]
Can I have a link to the blog post?

**Comment by ucheobere** [comment]
http://traccar.litvak.su/installation.html

**Comment by tananaev** [comment]
OK, so you are not even using official version of Traccar web interface. Please contact the author about your issue.

**Comment by ucheobere** [comment]
I also got instructions from here https://httpdot.org/howto/11-publish-your-current-location-from-traccar-2

**Comment by tananaev** [comment]
It's not an official blog.

**Comment by ucheobere** [comment]
Outside this I also could not get my queclink GV320 connected to demo.traccar.org

**Comment by tananaev** [comment]
When did you try it and what's the device id?

**Comment by ucheobere** [comment]
I tried it some hours ago here's my id 862894021415222

**Comment by ucheobere** [comment]
I just set it up again.

**Comment by tananaev** [comment]
I can see data from your device, but it doesn't send any GPS info, so messages are ignored.

**Comment by JorgeRomano** [comment]
Hello, After I followed the blog instruction for opengts integration (https://www.traccar.org/opengts/), this error is int the log of traccar.
is it normal?

**Comment by tananaev** [comment]
@JorgeRomano, if you get the error, it means that you haven't applied integration instructions properly.

**Comment by daipayan-matrix** [comment]
I have a query, I had installed the Driver in my laptop. Added the Server FTP path and allowed the port in the server. But problem is no file is generated in the provided FTP. Am tried to search a lot but no where I find any sort of files with GPS data.

Am using GL50X @Track Air Interface Protocol R3.00

Anyone please guide me!
