### ISSUE TITLE
Websockets access nodejs

### ISSUE THREAD

**Issue by mhinostroza** [traccar/traccar#1989]
Hello!

I have a question for days.

I’m consuming 3.3 API Traccar

I can consume the API Standard HTTP authorization headers from nodejs.

But … I would like to consume the web sockets ??

As it is the api is really working with session Using cookies?

Thank you.

**Comment by tananaev** [comment]
WebSocket API requires session cookie for authentication.

**Comment by benrogmans** [comment]
You can. First authenticate with an HTTP post to get a cookie and then use the WS package: https://github.com/websockets/ws.

`HTTP.post('http://localhost:8082/api/session',
		    {
			    headers: {
				    'Content-Type': 'application/x-www-form-urlencoded'
			    },
			    content: "email=your@email.com&password=yourpass"
		    }, function(error, response){

				var socket = new WebSocket('ws://localhost:8082/api/socket', [], {
						        'headers': { 'Cookie': response.headers['set-cookie'][0] }
				});

				socket.on('open', function open() {
					console.log('Succesfully connected to Traccar');
				});
				
				socket.on('message', function(message, flags){
					
					var data = JSON.parse(message);
					// Work your magic here
					// data.positions contains tracker positions
				});
				
				socket.on('disconnect', function(){
					console.log('disconnected');
				});
});`

**Comment by hansfpc** [comment]
@benrogmans not working, have you a updated version of that code?

**Comment by gaiththewolf** [comment]
Reading Set-cookie not working in new browser
