### ISSUE TITLE
Special characters in device identifier

### ISSUE THREAD

**Issue by mm108** [traccar/traccar#1993]
hi,

Was just curious whether you have come across any special characters being used in device identifier?  To minimize the chances of users inputting something invalid, perhaps by mistake, I wanted to add some basic filter to the device id input field. Thanks a lot

**Comment by tananaev** [comment]
I can't recall any special characters. Usually it's digits and/or letters, but some apps (e.g. Traccar Client and some other) allow user to use anything as device id.
