### ISSUE TITLE
Location Jumps Filter

### ISSUE THREAD

**Issue by v920749** [traccar/traccar#1996]
Hi Anton,

Here is data of jumps that my device GT02A  took recently. I read in this issue section someone having same issue because of not using device time. That doesnt apply to me as I used deviceTime only.  Is there any filter or logic that can help?

```
"dt_server" "dt_tracker"    "lat"   "lng"   "altitude"  "angle" "speed" "params"
"2016-06-02 22:41:15"   "2016-06-02 17:11:19"   "29.531017" "75.24112"  "0" "96"    "28"    ""
"2016-06-02 22:41:12"   "2016-06-02 17:11:14"   "29.531645" "75.186903" "0" "86"    "27"    ""
"2016-06-02 22:40:33"   "2016-06-02 17:10:34"   "29.53195"  "75.234753" "0" "106"   "27"    ""
"2016-06-02 22:40:19"   "2016-06-02 17:10:24"   "29.531645" "75.186903" "0" "86"    "27"    ""
"2016-06-02 22:39:50"   "2016-06-02 17:09:54"   "29.532787" "75.229158" "0" "56"    "11"    ""
"2016-06-02 22:39:49"   "2016-06-02 17:09:49"   "29.531645" "75.186903" "0" "86"    "27"    ""
"2016-06-02 22:36:26"   "2016-06-02 17:06:28"   "29.531645" "75.186903" "0" "86"    "27"    ""
"2016-06-02 22:35:53"   "2016-06-02 17:05:58"   "29.532087" "75.195977" "0" "87"    "25"    ""
```

**Comment by tananaev** [comment]
What do you mean by jumps? Can you provide a screenshot?

**Comment by v920749** [comment]
@tananaev Please find snapshot link. This is obviously a device/firmware error, A filter to filter out such device errors will help a lot.

http://i.imgur.com/SS5x9Ho.jpg?1

**Comment by tananaev** [comment]
Not sure how to filter those. Any ideas?

**Comment by v920749** [comment]
@tananaev I am planning to do in backend code that I am using to filter on basis of 
 
IF (change in angle > X && "distance tranvelled" or "speed"  is more than Y meters (/s))
{
  return true; // Filter out these data points
}

As I saw these data points, I noticed that angle value changes abruptly and obviously distance travelled would be too much and calculated speed based on current and previous location too would be high

**Comment by v920749** [comment]
@tananaev would appreciate your opinion on above solution or any input to make it better.

**Comment by tananaev** [comment]
I think your solution is very error prone. Angle can change, but it can also be the same. How would you distinguish "correct" locations from "incorrect"?

**Comment by v920749** [comment]
@tananaev I think I will be fine with few lost data points, still lets see. I am also planing to move to Coban devices.   Apart from this, you would be amazed to know www.gpswox.com guys use traccar to interface with devices.

**Comment by tananaev** [comment]
I'm aware that gpswox uses Traccar server as a back-end.
