### ISSUE TITLE
Odometer and START - STOP flag

### ISSUE THREAD

**Issue by tosuja** [traccar/traccar#1997]
Hi all,

traccar is absolutely new for me, so I apologize for simple questions.
We have the traccar server (linux, version 3.5). I currently have two devices (CalAmp LMU-3030-VERIZON-CDMA)

Everything works fine. Data is sent to the mysql database. But I have a questions.
- In database table is not column ODOMETER. Is there any way to get this information?
- Maybe is this information hidden in a field "attributes". This field looks like this:

{"sat":10,"carrier":299,"gsm":-68,"modem":15,"hdop":8,"input":0,"status":0,"event":45,"acc0":0,"acc1":0,"acc2":7800,"acc3":1333,"acc4":3125000,"acc5":8627,"acc6":0,"acc7":0,"acc8":1664,"acc9":0,"acc10":13376,"acc11":0,"acc12":0,"acc13":0,"acc14":0,"ip":"xxx.xxx.xxx.xxx"}_

Is there any possibility to decode these attributes?
- Is there any chance to find out whether it is a start or stop of a vehicle? Device transmits constantly coordinates constantly. Even if the car is in the parking lot. I need to know that the car began to move.
- Is there any possibility to decode HEX information from the tracker-server.log? For example:
  **4CD0801: 5082 < xxx.xxx.xxx.xxx] HEX: 830545420174170101010200015751261b5751263f14b6...............**

Thank you very much for your answers

**Comment by tananaev** [comment]
If there was odometer, it would be in "attributes". I don't really know what those parameters mean. You configured device, so I assume you should know.

**Comment by warlockopy** [comment]
Calamp devices has a script configuration very flexible, and have acumulators like variables for several uses. you can setup one acumulator to measure odometer. but the parser in traccar should have standard.
