### ISSUE TITLE
Proxypass configuration for path different from root

### ISSUE THREAD

**Issue by onlygecko** [traccar/traccar#2001]
Hello,

first of all: Superb installation routine. It took me 5 minutes to have the server running with one client. :-)

The tutorial for running traccar via https is good as well. For me it unfortunatelly just works for the main domain like 'mydomain.com'. For domains with an additional path like 'mydomain.com/gps/' I get an JavaScript error.

The following snippet is the part from the apache configuration I've changed:

```
ProxyPass gps/api/socket ws://localhost:8082/api/socket
ProxyPassReverse gps/api/socket ws://localhost:8082/api/socket

ProxyPass /gps/ http://localhost:8082/
ProxyPassReverse /gps/ http://localhost:8082/
```

Here is a screenshot of the website with the JS error.
![auswahl_001](https://cloud.githubusercontent.com/assets/3233376/15801531/4ff9fade-2a98-11e6-9a5f-321c85742346.png)

Do I have to add anything to the apache configuration?
(System: Ubuntu 14.04, Apache 2.4.7)

**Comment by tananaev** [comment]
Try to open `debug.html`.

**Comment by onlygecko** [comment]
Thanks for the quick response. :-)

This is the output of debug.html

![auswahl_002](https://cloud.githubusercontent.com/assets/3233376/15804169/b038205c-2b00-11e6-9976-a65cd3ad8cab.png)
![auswahl_003](https://cloud.githubusercontent.com/assets/3233376/15804170/b3e31ab8-2b00-11e6-805f-677b231c4714.png)

**Comment by tananaev** [comment]
Looks like proxy returns some HTTP error instead of JSON for API calls.

**Comment by onlygecko** [comment]
Sorry for the late response. I've tried to recreate the error on a blank ubuntu installation.

The following script installs and configures apache and installs traccar. You can later open the browser and enter http://localhost/gps/. The same error occurs as in my 'production' environment. Is there anything I can do to help fix the bug? Or might any additional apache configuration help?

```sh
#!/bin/bash

# install necessary packages
sudo apt install apache2 openjdk-8-jre-headless -y

# setup apache modules
sudo a2enmod ssl
sudo a2enmod proxy_http
sudo a2enmod proxy_wstunnel

# configure apache site
sudo cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf.bak
sudo echo "<VirtualHost *:80>
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

        ProxyPass /gps/api/socket ws://localhost:8082/api/socket
        ProxyPassReverse /gps/api/socket ws://localhost:8082/api/socket

        ProxyPass /gps/ http://localhost:8082/
        ProxyPassReverse /gps/ http://localhost:8082/
</VirtualHost>" > /etc/apache2/sites-available/000-default.conf

sudo service apache2 restart

# download and run traccar
wget https://github.com/tananaev/traccar/releases/download/v3.5/traccar-linux-64-3.5.zip
unzip traccar-linux-64-3.5.zip
sudo ./traccar.run
sudo /opt/traccar/bin/traccar start
```

**Comment by tananaev** [comment]
Can I have access to the server (web console) to take a look?

**Comment by onlygecko** [comment]
I've run script on a local virtual box machine with an blank Ubuntu installation. If you like I could try to setup a 'public' vm.

**Comment by tananaev** [comment]
Here are the steps that I ran on clean Ubuntu and it works just fine:

https://www.traccar.org/secure-connection/

**Comment by onlygecko** [comment]
Did the procedure (https://www.traccar.org/secure-connection/) also works for _paths beside the root path_? I used the following traccar.conf for apache2. Difference to yours is the missing ssl connection, a different servername and the use of the path '/gps/'. It just will not work. :-(

```

        <VirtualHost _default_:80>

                ServerName localhost
                ServerAdmin webmaster@localhost

                DocumentRoot /var/www/html

                ProxyPass /gps/api/socket ws://localhost:8082/api/socket
                ProxyPassReverse /gps/api/socket ws://localhost:8082/api/socket

                ProxyPass /gps/ http://localhost:8082/
                ProxyPassReverse /gps/ http://localhost:8082/

        </VirtualHost>
```

**Comment by tananaev** [comment]
I haven't tried anything beside root path. Check network requests in the browser console to make sure all of them use relative URLs.

**Comment by gustavofcalmeida** [comment]
I have the same problem.
The login screen appears. I log in and, can se the map for a second and  get logged out immediately.

I get status code 404 on these:
```
Request URL:https://192.168.0.70/gps/fake-login.html
Request URL:https://192.168.0.70/gps/api/session?_dc=1495481285588
```

And 401 on these:
```
Request URL:https://192.168.0.70/gps/api/groups?_dc=1495481284153&page=1&start=0&limit=25
Request URL:https://192.168.0.70/gps/api/geofences?_dc=1495481284154&page=1&start=0&limit=25
Request URL:https://192.168.0.70/gps/api/calendars?_dc=1495481284155&page=1&start=0&limit=25
Request URL:https://192.168.0.70/gps/api/attributes/aliases?_dc=1495481284158&page=1&start=0&limit=25
Request URL:https://192.168.0.70/gps/api/users/notifications?_dc=1495481284160&all=true&page=1&start=0&limit=25
Request URL:https://192.168.0.70/gps/api/devices?_dc=1495481284166&page=1&start=0&limit=25
Request URL:https://192.168.0.70/gps/api/devices?_dc=1495481284236
Request URL:https://192.168.0.70/gps/api/positions?_dc=1495481284236
```

**Comment by tananaev** [comment]
I guess something is wrong with the session.

**Comment by gustavofcalmeida** [comment]
@onlygecko Once I couldn't stop Traccar from being the root of the domain, I changed it to be the root but in another port.

/etc/apache2/ports.conf:
```
Listen 80

<IfModule ssl_module>
	Listen 443
	Listen 8443 https
</IfModule>
```
traccar.conf:
```
<IfModule mod_ssl.c>
        <VirtualHost _default_:8443>

                ServerName demo.traccar.org
                ServerAdmin webmaster@localhost

                DocumentRoot /var/www/html

                ProxyPass /api/socket ws://localhost:8082/api/socket
                ProxyPassReverse /api/socket ws://localhost:8082/api/socket

                ProxyPass / http://localhost:8082/
                ProxyPassReverse / http://localhost:8082/

                SSLEngine on
                SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
                SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key

        </VirtualHost>
</IfModule>
```

**Comment by gustavofcalmeida** [comment]
@onlygecko It seems our problem has been solved:
https://www.traccar.org/secure-connection/

Thanks @tananaev

**Comment by imukunzi** [comment]
Hi, 
I am new to linux configuration and I want to configure SSL for web access could you please advise what might be wrong on my configuration? I use ubuntu 16.04 ? I can access https://mydomain.org and access default apache page. Thanks
here is my  /etc/apache2/ports.conf

Listen 80
<IfModule ssl_module>
        Listen 443
</IfModule>
<IfModule mod_gnutls.c>
        Listen 443
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

here is my  /etc/apache2/sites-available/traccar.conf
<IfModule mod_ssl.c>
         <VirtualHost _default_:443>

                ServerName mydomain.org
                ServerAdmin webmaster@localhost

                DocumentRoot /var/www/html

                ProxyPass /api/socket ws://localhost:8082/api/socket
                ProxyPassReverse /api/socket ws://localhost:8082/api/socket

                ProxyPass / http://localhost:8082/
                ProxyPassReverse / http://localhost:8082/

                SSLEngine on
                SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
                SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key

        </VirtualHost>
</IfModule>

here is my 000-default.conf
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
RewriteEngine on
RewriteCond %{SERVER_NAME} =mydomain.org
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
