### ISSUE TITLE
Invalid object name 'DUAL'

### ISSUE THREAD

**Issue by javisan** [traccar/traccar#2002]
Dear Anton,

Traccar with SQL Server works if line 120 in FileDataManager.java is modified like this:
ERROR - hikariConfig.setConnectionInitSql("SELECT 1 FROM DUAL");
OK - hikariConfig.setConnectionInitSql("SELECT 1");

NetBeans doesn't allow me to Push the new branch with that modification. I'm doing something wrong I supose.

**Comment by tananaev** [comment]
@drecchia, first issue with Hikari. Why did you hardcode an SQL statement there? I don't know how I missed it in the review. That's definitely incorrect. Not all databases have `DUAL`.

**Comment by drecchia** [comment]
I will submit a pull request in a few minutes, sorry.

**Comment by barfinup** [comment]
Hi guys, SELECT 1 FROM DUAL was correct for oracle databases
SELECT 1 is not and now traccar won't start when using Oracle (ORA-00923: FROM keyword not found where expected)

Please do not hardcode any SQL statements, even the connection init SQL - this needs to be moved into traccar.xml

This is currently a problem with DataManager.java line 104

**Comment by tananaev** [comment]
It's not hardcoded. There is a default value that works with most popular database, but you can also configure it:
```xml
<entry key='database.checkConnection'>SELECT 1 FROM DUAL</entry>
```

**Comment by barfinup** [comment]
Ahha - yes I see now the 'hardcoded' bit is just a default, didn't see any section in the XML and that one wasn't mentioned in the configuration file documentation
Thanks for the quick response

**Comment by tananaev** [comment]
Updated config documentation, thanks for feedback.

**Comment by gpproton** [comment]
I'm not sure about my traccar with oracle db installation since I have little experience with oracle db, no table is created and traccar does not start Anton earlier referenced me to this issue but I tried this configuration earlier it didn't help.

**Comment by barfinup** [comment]
This is just one of the config changes required to run on oracle. 
You also need to remove the ";" from queries in the server config, and update the liquibase changelog files to remove auto-increment and add sequences, reduce limit of varchars, and do any other type conversions such as int to number (https://docs.oracle.com/cd/B19306_01/gateways.102/b14270/apa.htm)

Be aware that the traccar liquibase files do not have any rollback code, so after making any change make sure to drop all your traccar tables first or you will have a variety of issues such as missing tables.

**Comment by tananaev** [comment]
@barfinup, thanks for sharing the information.

I've just [removed semicolons from queries](1937a36997710f117bc742e0e2d9bcab8d9f2d5b). It should make default config more universal.

It would be nice if you could share changelog files for other people to use.

**Comment by barfinup** [comment]
@tananaev is there an appropriate discussion spot to do that, or are you not fussed if we just use these issue tickets to dump stuff? :)

**Comment by tananaev** [comment]
You can create another ticket if you want.

**Comment by gpproton** [comment]
Thanks @barfinup your information has been very helpful.
