### ISSUE TITLE
How to add the domain Name in Traccar

### ISSUE THREAD

**Issue by sourabhkhare** [traccar/traccar#2007]
Dear Sir,

I have install the traccar in Windows VPS server. How to add the domain name in Traccar

example : www.spanairgpstracker.in

Regards
Sourabh

**Comment by tananaev** [comment]
You don't need to add domain name in Traccar. Just configure your DNS records to point to the server and it will work.

**Comment by sourabhkhare** [comment]
Dear Sir,

I have configure the DNS record to ppoint the server. But its not working. Please help me.

**Comment by tananaev** [comment]
What's the server address? What the DNS name?

**Comment by sourabhkhare** [comment]
Dear Sir,
My Domain Name is: vtrack.spanairgpstracker.in
Server IP is :108.61.188.218

**Comment by tananaev** [comment]
It works for me:

http://vtrack.spanairgpstracker.in:8082/

If you want to remove 8082 at the end, you need to change web port to 80 in the config.
