### ISSUE TITLE
tracker for moto-cicle  Hz-Tx 5

### ISSUE THREAD

**Issue by caluca20** [traccar/traccar#2010]
Hi friend, I have a problem, the Tracker Hz-Tx-5 save one record as 

```
2a48512c3335333530363035303535313031362c56312c2c562c2c4e2c2c452c302e30302c302c2c46464646464646462c3265342c302c353230392c32373364230d0a
```

in the log

but these records could not to view on traccar console
I am setting the port on 5013 , this is opened
please your help, thanks

**Comment by tananaev** [comment]
The problem is that your device doesn't send GPS info. Traccar doesn't support LBS data for H02 protocol yet. I need to documentation to implement it.

**Comment by caluca20** [comment]
What kind of documentation

**Comment by tananaev** [comment]
Protocol documentation.

**Comment by caluca20** [comment]
Hi friend, the seller sent me the next information about the protocol.

"..
# 353505911251129 ## 0 # 0000 # AUT # 01 # 46000027b8f34 # 0, E, 0, N, 0,0 # 0 # 0 ##

imei = 353505911251129
Status = 0
Password = 0000
Instruction head = AUT (SMS)
Upload package = 01
Base station location data = 46000027b8f34
GPS Location Package = 0, E, 0, N, 0,0
date
time

When the device is made up SMS data when issued at the location server information applies data formats GB2312  ... "


Please help me with it.

**Comment by tananaev** [comment]
Here is the message from your original post:
```
*HQ,353506050551016,V1,,V,,N,,E,0.00,0,,FFFFFFFF,2e4,0,5209,273d#
```

It doesn't match the one in your last post. Do I need to support both? Where did you get the second one?

**Comment by tananaev** [comment]
In fact it's a completely different protocol. Your device is using H02 protocol. Last example with breakdown is from V680 protocol.

**Comment by caluca20** [comment]
the second one (#353505911251129##0#0000#AUT#01#46000027b8f34#0,E,0,N,0,0#0#0##) it sent me the seller of the equipments, i think is example.

**Comment by tananaev** [comment]
As I said in previous comment, it's a different protocol.

**Comment by caluca20** [comment]
the log of the console is: 2a48512c3335333530363035303535313031362c56312c2c562c2c4e2c2c452c302e30302c302c2c46464646464646462c3265342c302c353230392c32373364230d0a

in ASCII is.

*HQ,353506050551016,V1,,V,,N,,E,0.00,0,,FFFFFFFF,2e4,0,5209,273

**Comment by tananaev** [comment]
Not sure why you are repeating what I already said, but as you can see two examples don't match.

**Comment by caluca20** [comment]
Hi friend, the next the log of device TX-5 that I am doing the test, please help me.

2016-06-13 23:32:34 DEBUG: [CCE3FEDF: 5013 < 200.85.80.214] HEX: 2a48512c3335333530363035303535313031362c56312c2c562c2c4e2c2c452c302e30302c302c2c46464646464646462c3265342c302c353230392c33326635230d0a

**Comment by tananaev** [comment]
As I said before, I need protocol documentation to be able to help you.

**Comment by caluca20** [comment]
friend, please could you send a example of protocol.

**Comment by tananaev** [comment]
Here are some protocol documentations:

https://www.traccar.org/protocols/
