### ISSUE TITLE
Port 5082 not responding on any Demo site

### ISSUE THREAD

**Issue by joepr** [traccar/traccar#2015]
Hello Everyone
I recently purchase a Calamp LMU-1175 . I was able to send SMS commands to setup the tracker to point to a specific IP and Port . I wanted to test it on the traccar demo sites before moving to my local server however everysingle demo site seems to have port 5082 closed. Could this be the issue why I don't see the tracker reporting to my demo account?

![image](https://cloud.githubusercontent.com/assets/10345032/15985145/2f958e56-2fb2-11e6-879a-05b4c468217d.png)

![image](https://cloud.githubusercontent.com/assets/10345032/15985150/486d3d02-2fb2-11e6-89b7-c610de8d7814.png)

![image](https://cloud.githubusercontent.com/assets/10345032/15985154/564c8aae-2fb2-11e6-99c4-0e00b46d53f6.png)

![image](https://cloud.githubusercontent.com/assets/10345032/15985157/6981968c-2fb2-11e6-96dd-b2f8b26b5574.png)

However if I did try other ports like 5013 They show up like open
![image](https://cloud.githubusercontent.com/assets/10345032/15985163/9ec3f29a-2fb2-11e6-8947-ebedd8a2c799.png)

**Comment by tananaev** [comment]
CalAmp uses UDP protocol, so port check won't work for it. Note that the port might be closed on main demo server, so I would recommend to try second server.

**Comment by joepr** [comment]
Thanks Tananaev for the reply. I also try the second server, send the following commands via SMS to the tracker

To change the IP address
![image](https://cloud.githubusercontent.com/assets/10345032/15986624/31507c88-2fda-11e6-9d9e-3cce2f858243.png)
To change the port
![image](https://cloud.githubusercontent.com/assets/10345032/15986631/4573b50e-2fda-11e6-8fac-706f53525978.png)

The LMU-1175 seems to get the new settings however I still can't seem to get a response in the demo site. This is my first Calamp device and after the purchase they gave me access to the PULS manager.  I guess I should see the Calamp device in the PULS account however I don't see it. Do you or anyone here happen to have a Calamp device in your inventory? I will like to know if you see your device under your PULS account. 


Demo site 2 - Added the Calamp device by typing the IMEI number
![image](https://cloud.githubusercontent.com/assets/10345032/15986616/0cfec510-2fda-11e6-89c4-daf74ead6892.png)

**Comment by tananaev** [comment]
I can see data from your device, but it's all zeroes. I guess it doesn't have a GPS fix yet.

**Comment by joepr** [comment]
Sorry for the inconvenience

I was able to make it work. For other users with Calamp trackers you will need to send the initial configuration script directly from the Calamp PULS Manager. Then after that you will be able to setup your device on traccar by adding the device and using the tracker ESN number.
