### ISSUE TITLE
Password Hash in C#

### ISSUE THREAD

**Issue by elyfran** [traccar/traccar#2017]
how can I generate the same kind of traccar the password in C #?

**Comment by tananaev** [comment]
Traccar uses PBKDF2 standard for password hashing:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/helper/Hashing.java

There must be a way to do it C#. Quick search gives this link:

https://msdn.microsoft.com/en-us/library/system.security.cryptography.rfc2898derivebytes(v=vs.110).aspx

**Comment by cristianormoraes** [comment]
@elyfran did you make the login with c#? have a sample code?

**Comment by w32gold** [comment]
Per Anton (author), Traccar is purely written in Java..
