### ISSUE TITLE
How to use existing database tables instead of creating new by Traccar?

### ISSUE THREAD

**Issue by mrameezraja** [traccar/traccar#2020]
I have an existing production db with all necessary tables. When i try to change queries in traccar.xml nothing works. I don't want to use database structure created by Traccar. Also i have my own frontend,  traccar will be used only as a server for gps devices.

How can i achieve that? Any help would be highly appreciated.

**Comment by tananaev** [comment]
You can take a look at <a href="https://www.traccar.org/opengts/">OpenGTS config example</a>.

Basically you need to provide `database.selectDevicesAll` and `database.insertPosition` queries.

**Comment by mrameezraja** [comment]
Is it possible to stop traccar schema creation?

**Comment by tananaev** [comment]
Yes, just remove `database.changelog` parameter from config.

**Comment by mrameezraja** [comment]
One last thing is there a way where i can use battery/power status in database.insertPosition query?

**Comment by tananaev** [comment]
Power value is passed through `:attributes` parameter in JSON or XML format. If your database engine can parse that format, you should be able to access power value.

**Comment by mrameezraja** [comment]
I want to add `:power` in direct query. Where should i start looking in code?

**Comment by tananaev** [comment]
Here is the method you need to modify:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/database/DataManager.java#L467

**Comment by prusswan** [comment]
What are the restrictions when it comes to using existing tables? Can I modify the queries return dummy values for columns that do not exist?

**Comment by tananaev** [comment]
Yes, you can.

**Comment by neha21feb** [comment]
Did anyone able to modify the code for parsing  "attributes" to generate separate columns in DB? Eg. "Odometer" , "distance", "motion" etc.
Any suggestions will be appreciated!

**Comment by mrameezraja** [comment]
Yes you can. I have extracted "POWER" from attributes to a separate column. Here are steps to do that.

1. Add a new method in Position.java model
```java
public String getBattery() {
        Object power = this.getAttributes().get(Position.KEY_POWER);
        Object battery = this.getAttributes().get(Position.KEY_BATTERY);
        if (power != null) {
            return power.toString();
        } else if (battery != null) {
            return battery;
        } else {
            return "n/a";
        }
    }
```

2. Change in db query like 

```xml
 <entry key='database.insertPosition'>
        INSERT INTO positions (deviceId,  latitude, longitude, altitude, attributes, **power**)
        VALUES (:deviceId, :latitude, :longitude, :altitude, :attributes, **:battery**);
    </entry>
```

Concept: 
While parsing query traccar looks for public methods starting with "get..." and sets value of the keyword in query like ":method_name_without_get". In the above example **getBattery** value is replaced by **:battery**.

**Comment by neha21feb** [comment]
@mrameezraja :  Thank you so much for taking the time to answer my query.
                              I followed your steps and did the following changes in my code:

1. Added new changelog file with added column "batteryLevel"
2. Added "batteryLevel" field and method to Position data model.
3. Added "batteryLevel" field to JavaScript data model.
4. Added insert query in traccar.xml for tc_position table with new column "batteryLevel"

But I am getting the following error :
**WARN: Failed to store position - Unknown column 'batteryLevel' in 'field list' - SQLSyntaxErrorException**

Not sure which step I am missing here.
Any help would be greatly appreciated.

Thanks

**Comment by mrameezraja** [comment]
Can you share query here ?

**Comment by neha21feb** [comment]
My bad !! I am using Mysql but forgot to change <dbms type="mssql" /> to <dbms type="mysql" /> in my changelog xml file 
All working fine now .

Thanks for your help!

**Comment by neha21feb** [comment]
My bad !! I am using Mysql but forgot to change( dbms type=mssql ) to  ( dbms type=mysql ) in my changelog xml file
All working fine now .

Thanks for your help!
