### ISSUE TITLE
Getting 'WARN: Unknown device - IMEI'

### ISSUE THREAD

**Issue by mrameezraja** [traccar/traccar#2021]
I am getting 'Unknown device - IMEI' in traccar-server.log, when i connected a new device. Device exists in db. Also tried with config `<entry key='database.ignoreUnknown'>false</entry>` but having no luck.

**Comment by tananaev** [comment]
It means that your device have "IMEI" as a unique id. What exactly did you add to the database? Can I see a screenshot?

**Comment by mrameezraja** [comment]
IMEI = 420898999911

**Comment by tananaev** [comment]
Your device sends "IMEI" (literally) as unique id. Not number.

**Comment by mrameezraja** [comment]
No no my device sends a number as unique id, i just put IMEI for reference only. Sorry for miscommunication. :(

Exact log is 
WARN: Unknown device - 420898999911 (ip address)

**Comment by tananaev** [comment]
It means that server can't find device in the database.
