### ISSUE TITLE
Implement New Protocol

### ISSUE THREAD

**Issue by AKVTS** [traccar/traccar#2022]
Hi

I have a new tracking device sample of the data sent by the device is as below:

```
HEX: 2453554e53544152547c31313635307c3335333231383037323835363939317c56312e32377c3035303631363130343933317c3335333231383037323835363939317c23
HEX: 2453554e414c4552547c31313635307c347c317c323833372e333532377c30373730372e313338347c322e34307c3035303631363130343933317c3138322e30327c567c307c307c323131372e357c3335333231383037323835363939317c23
HEX: 2453554e504f4c4c7c31343338317c323833332e333033357c30373732322e363333357c3039333832397c3036303631367c32372e37317c302e307c32352e34367c30377c317c307c30307c307c307c302e3031357c342e317c31342e317c323137352e367c317c302e307c317c307c302e327c312e32377c3335333231383037323835363939317c23
```

Please guide on how to implement the above protocol.

**Comment by tananaev** [comment]
You can find info on how to implement new protocol here:

https://www.traccar.org/implement-protocol/

It might be a bit outdated, so check existing source code as well.

**Comment by AKVTS** [comment]
OK Thanks, I shall try to follow the same and come back to you in case I face any problem.

**Comment by tananaev** [comment]
Sure. Feel free to ask any questions related to Traccar and adding new protocol.
