### ISSUE TITLE
Is it possible to use websockets and traccar api in web.enable mode set to false?

### ISSUE THREAD

**Issue by mrameezraja** [traccar/traccar#2023]
I need to use both in web.enable mode set to false. Or is there any way to send commands and catch events in web disabled mode (from custom frontend)?

**Comment by tananaev** [comment]
No, it's not possible. The `web.enable` flag controls embedded server. You can't have web APIs without a web server.

**Comment by mrameezraja** [comment]
With below traccar configs i am able to successfully add data in sql server, everything works just great.

I want to send commands and catch events via web sockets. If i connect to websockets after setting `web.enable` true, it is giving error 'WebSocket connection to 'ws://<ip>:8082/api/socket' failed: Error during WebSocket handshake: Unexpected response code: 503'.


Here is my traccar.xml:

```
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>
    <!-- SERVER CONFIG -->
    <entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>C:\Program Files (x86)\Traccar\web</entry>

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>C:\Program Files (x86)\Traccar\logs\tracker-server.log</entry>

    <!-- DATABASE CONFIG -->

    <entry key='database.driverFile'>C:\sqljdbc4.jar</entry>
    <entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
    <entry key='database.url'>jdbc:sqlserver://localhost;user=sa;password=...;databaseName=DB;</entry>
    <entry key='database.user'>sa</entry>
    <entry key='database.password'>...</entry>
    <entry key='database.saveOriginal'>true</entry>
    <entry key='database.selectDevicesAll'>
        SELECT CONCAT('1', IMEI_NUMBER) AS id, IMEI_NUMBER AS uniqueId FROM TX_GPS_DEVICES;
    </entry>
    <entry key='database.insertPosition'>
        DECLARE @deviceID BIGINT        
        UPDATE TX_GPS_DEVICES SET LAST_LATITUDE = :latitude, LAST_LONGITUDE = :longitude, LAST_BATTERY_STATUS = :battery, DATE_UPDATE = GETDATE() WHERE IMEI_NUMBER = SUBSTRING(CAST(:deviceId AS CHAR(32)), 2, LEN(CAST(:deviceId AS CHAR(32))));

        SELECT @deviceID = GPS_DEVICE_ID FROM TX_GPS_DEVICES WHERE IMEI_NUMBER = SUBSTRING(CAST(:deviceId AS CHAR(32)), 2, LEN(CAST(:deviceId AS CHAR(32))));
        INSERT INTO TX_GPS_DEVICE_LOGS (GPS_DEVICE_ID, TIME_STAMP, LATITUDE, LONGITUDE, SPEED_IN_KM, RAW_DATA, IS_VALID, DATE_ADDED, DATE_UPDATED, BATTERY_STATUS)
        VALUES (@deviceID, :fixTime, :latitude, :longitude, :speed * 1.852, :rawText, :valid, GETDATE(), GETDATE(), :battery);
    </entry>
    <!-- PROTOCOL CONFIG -->
    <entry key='h02.port'>5013</entry>
    <entry key='watch.port'>5093</entry>
</properties>
```

**Comment by tananaev** [comment]
Well, `ws://:8082/api/socket` is not a valid address.

**Comment by mrameezraja** [comment]
`ws://<ip>:8082/api/socket`

**Comment by tananaev** [comment]
Are you using local server?

**Comment by mrameezraja** [comment]
I am running traccar on a amazon server.

**Comment by tananaev** [comment]
There might be a problem with your ISP. For example, I have similar problem at home where my internet provider messes up with headers which breaks WebSockets communication. Only HTTPS works for me at home.

I would recommend to try locally or over HTTPS connection.

**Comment by mrameezraja** [comment]
https solved the websockets issue but when i access commands api, server is returning '401 Unauthorized'.

```
$.ajax({
               url: 'http://url:8082/api/commands',   
               type: 'POST',
               data: JSON.stringify({ deviceId: 14208099911, type: "custom", attributes: { data: 'check123456' } }),
               contentType:'application/json'
            });
```

**Comment by tananaev** [comment]
It means exactly what it says. You either need to create a session or provide autorization header in every request.

**Comment by mrameezraja** [comment]
I have added Basic Auth header and now i am getting 'Bad Request' error:

```
$.ajax({
               url: 'http://localhost:8082/api/commands',   
               type: 'POST',
               data: JSON.stringify({ deviceId: 14208099911, type: "custom", attributes: { data: 'check123456' } }),               
               //dataType: 'json',
               contentType:'application/json',
               headers: {
                    "Authorization": "Basic " + btoa("admin:admin")
               }
            });
```

**Comment by tananaev** [comment]
What's the error message in the response content?

**Comment by mrameezraja** [comment]
@tananaev your support is highly appreciated. thank you.

Here is the situation, i added an extra attribute in ajax call `xhrFields: {  withCredentials: true }`, api started working.

But when i changed traccar.xml with with only two queries (database.selectDevicesAll, database.insertPosition and web.mode enabled) as don't need traccar schema and web interface. It is again giving '401 Unauthorized' response, switched back to default traccar.xml everything works fine.

**Comment by tananaev** [comment]
Have you provided SQL queries for user login?

**Comment by mrameezraja** [comment]
Nopes, there are only two queries in traccar.xml. `database.selectDevicesAll, database.insertPosition`

**Comment by mrameezraja** [comment]
i am using basic auth.

**Comment by tananaev** [comment]
Not sure how you expect it to work without any user database. Where would it get information about the users?

**Comment by mrameezraja** [comment]
@tananaev  thank you so much for your support. Everything is working as expected with some hacks ;).

**Comment by kirantpatil** [comment]
Hi @mrameezraja, could you please post the details that made to resolve your issue.

**Comment by mrameezraja** [comment]
I just disabled authentication logic from traccar server. Updated `login` function in `DataManager.java` as below:

```java
public User login(String email, String password) throws SQLException {
        User user = QueryBuilder.create(dataSource, getQuery("database.loginUser"))
                .setString("email", email)
                .executeQuerySingle(User.class);
        if (user != null) {  // && user.isPasswordValid(password)) {
            return user;
        } else {
            return null;
        }
    }
```

**Comment by kirantpatil** [comment]
Thank you Sir.
