### ISSUE TITLE
traccar command using opengts

### ISSUE THREAD

**Issue by perfectwebtech** [traccar/traccar#2025]
hello

i did enabled opengts database with traccar and i don't need web platform as traccar but i need working api and there is rest api not working i did created require field even not working

api any guidance or idea ? 

like this not working http://t.mydomain.com:8082/traccar/rest/sendCommand

i did customization command thing by files but here api not able to working anyone can guidance me

**Comment by tananaev** [comment]
Traccar API won't work with OpenGTS database.

**Comment by perfectwebtech** [comment]
is there no any shortcut or customization guidance ? 

by api command or directly with java command could be work or any guidance would be appreciate :)

**Comment by tananaev** [comment]
I don't think there is any simple solution. API requires user accounts for authentication. You need to somehow make it understand OpenGTS accounts which I imagine would require quite a few changes in Java code.

**Comment by perfectwebtech** [comment]
ok thanks but in java which section would be easy to coding or some how guidance would be possible for developer ?

**Comment by tananaev** [comment]
As I said, I don't think it would be that easy.
