### ISSUE TITLE
gopass avl901d protocol

### ISSUE THREAD

**Issue by warlockopy** [traccar/traccar#2026]
Hello.
I have setup everything as allways, but the avl901d is not reporting to the platform. The package does arrive to the server, but it is not shown on the log.

```
0x0000:  4500 0077 a851 0000 2311 4428 c9d9 1a16  E..w.Q..#.D(....
0x0010:  c0a9 0664 66f4 138d 0063 e68c 4e6f 2332  ...df....c..No#2
0x0020:  3030 0d0a 3335 3832 3434 3031 3736 3731  00..358244017671
0x0030:  3330 380d 0a24 4750 524d 432c 3233 3539  308..$GPRMC,2359
0x0040:  3439 2e32 3030 2c56 2c30 3030 302e 3030  49.200,V,0000.00
0x0050:  3030 2c4e 2c30 3030 3030 2e30 3030 302c  00,N,00000.0000,
0x0060:  452c 302e 302c 302e 302c 3035 3031 3830  E,0.0,0.0,050180
0x0070:  2c2c 2c4e 2a37 38                        ,,,N*78  
```

this it the tcpdump
also port is enabled on ufw

**Comment by warlockopy** [comment]
will give it a try with (after reading similar issue)
socat UDP-LISTEN:5005,fork TCP:localhost:5005
on linux.

**Comment by warlockopy** [comment]
2016-06-17 12:12:25  INFO: [07CFF6ED] connected
2016-06-17 12:12:25 DEBUG: [07CFF6ED: 5005 < 127.0.0.1] HEX: 4e6f233230300d0a3335383234343031373637313330380d0a244750524d432c3136313232332e3030302c412c323531372e303534352c532c30353733392e313738382c572c302e302c302e302c3031313139362c2c2c412a3631
2016-06-17 12:12:25  INFO: [07CFF6ED] disconnected

**Comment by warlockopy** [comment]
after checking source code of t55 protocol, i do not see where the parser takes into account the imei.

also this method? getdeviceId(), how takes that into account from the sentence?
Regards.

if (hasDeviceId()) {
            position.setDeviceId(getDeviceId());
}

**Comment by tananaev** [comment]
Device id is set by `identify` method called from protocol decoder class.

Just look at the `T55ProtocolDecoder`. It does all the decoding.

**Comment by warlockopy** [comment]
yes but there is a case is a difference in t55 protocol, it seems similar but not equal.
https://www.traccar.org/forums/topic/problem-with-t55-protocol/

the device is not sending $PGID,123456789012345*0F, it send other line, and that is not contemplated on the parser, so no device is updated after parsing, because there is no parser pattern.
I think if we add a new patter might work.

Messages are like this,
No#200\r                                                                                                     
358244017671308\r                                                                                            
$GPRMC,161633.000,A,2517.0533,S,05739.1804,W,0.0,0.0,011196,,,A*6E> 2016/06/17 12:17:32.592380

**Comment by tananaev** [comment]
T55 decoder supports multiple options for device authentication, including just IMEI number which your device sends.

**Comment by warlockopy** [comment]
yes, but it is not updating on database? does this anything to do with ip of the sender, beacause this was forwarded internally on the server, because original package is UDP, and then converter to TCP. No insertion. Maybe somekind of nat is needed it that is the issue?

**Comment by tananaev** [comment]
The problem is that you don't have a delimiter (new line) at the end of the message.
