### ISSUE TITLE
Communications link failure error

### ISSUE THREAD

**Issue by excepticons** [traccar/traccar#2029]
Hi.

I posted this issue because I can't find posts related that can help me with this error message.

When I try to do some normal tasks (create group, create user, etc.) using a Google Chrome, some times I get the error message: 

```
Communications link failure The last packet successfully received from the server was 88,953 milliseconds ago. The last packet sent successfully to the server was 16 milliseconds ago. - CommunicationsException (... < QueryBuilder:376 < DataManager:383 < *:209 < *:398 < GroupResource:59 < ...)
```

Other times works fine, without error messages.

I'm using a remote MySQL DB, and I already tested remote connection several times, with all results fine. I'm using MySQL Workbench desktop application and every time that I run some actions (select, refresh, etc.), results are displayed quickly.

My traccar platform description:

Traccar Server for Windows installed on a AWS server with Microsoft Windows Server 2012 R2 (1 GB RAM, 30 GB HD). 
Ports 8082, 5000-5099 open.
DB MySQL, hosted on GoDaddy (I can't change server system variables).

I can't find error messages on files tracker-server.log or wrapper.log.20160617.

Please, how can troubleshoot this issue?

Thank you.

Gustavo Barboza

**Comment by tananaev** [comment]
As you can see, the connection has timed out. Not sure what can be done if you can't change MySQL configuration. What database URL are you using in Traccar?

**Comment by excepticons** [comment]
Hi, Tanaev.

This is my db config:

```
    <!-- DATABASE CONFIG -->

	<entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
	<entry key='database.url'>jdbc:mysql://198.71.227.97:3306/GeoInfoDB?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
	<entry key='database.user'>MyUser</entry> 
	<entry key='database.password'>MyPass</entry>

    <entry key='database.changelog'>C:\Program Files (x86)\Traccar\data\changelog-master.xml</entry>
```

Thank you.

**Comment by tananaev** [comment]
Looks fine. The `autoReconnect` option supposed to re-connect after timeout, but seems like it doesn't.

**Comment by excepticons** [comment]
Then, the solution will be MySQL server variables, like `wait_timeout` ?

**Comment by excepticons** [comment]
This is an global issue, or only affect web?

**Comment by tananaev** [comment]
What do you mean by global?

**Comment by excepticons** [comment]
Global like affects I/O packets from registered GPSs.
But, I'm right now changing DB server. I have other DB hosting that maybe they are more fast.
I will update you later about tests on other DB servers.
Thank you very much.

Gustavo.

**Comment by tananaev** [comment]
Yes, it affects all DB operations because Traccar share database connections.

I would recommend to try MySQL on the same server. That's what I'm doing for demo servers.

**Comment by excepticons** [comment]
Solved with other DB server.
Thanks, tananaev.
