### ISSUE TITLE
how to convert gt06 data in english language or readable data

### ISSUE THREAD

**Issue by amitsharma957** [traccar/traccar#2031]
Dear Plz give any sugesstion to translate coming data from device convert into readble data

**Comment by tananaev** [comment]
You can take a look at protocol documentation here:

https://www.traccar.org/protocols/

**Comment by amitsharma957** [comment]
i am trying on .net but not success to find the perfect solution, to parse data and imei number not find in every packets.

**Comment by tananaev** [comment]
By .NET I assume you mean C#, right? I don't have much experience with C#. Why don't you want to use Traccar server?

**Comment by amitsharma957** [comment]
sorry but i am java developer i already have communication server for tk103 running 300 + vechicle but i want to make for gt06 could you help me?

**Comment by tananaev** [comment]
As I said, I'm not a C# developer. What kind of help do you want from me?
