### ISSUE TITLE
Cannot run from custom root path

### ISSUE THREAD

**Issue by pengc99** [traccar/traccar#2032]
Trying to setup a Traccar instance on my Apache2 server - I can not use the root location for the application, and the application must run from either port 80 or 443 (HTTP or HTTPS).

I have read the instructions on how to setup with an HTTPS reverse proxy using Apache2, but this assumes using the default root path.

I'm trying to run the application from another root path, such as /traccar

Attempting to use /traccar in the ReverseProxy configuration results in numerous 404 errors. Digging through the source code, I could not find any configuration to set the root path as the application assumes it is running from /

**Comment by pengc99** [comment]
https://www.eclipse.org/jetty/documentation/9.3.x/configuring-contexts.html

This might have more information on setting a contextpath

**Comment by tananaev** [comment]
Traccar is not a web app. It's a system service. Can you run those?

**Comment by pengc99** [comment]
Yes, I can get it all to run perfectly from the root path, just not a deeper contextpath

**Comment by tananaev** [comment]
You might need to modify some paths. For example here:

https://github.com/tananaev/traccar/blob/master/web/app/store/AllDevices.js#L23

Alternatively you can keep `/api` at the top level. I think it should work that way.

**Comment by pengc99** [comment]
Yes I think /api can be the same because it's just for the websocket right? I only intend to have one websocket application. Let me try that out and see how it works.

**Comment by tananaev** [comment]
It's for WebSockets and REST API.

**Comment by pengc99** [comment]
I was able to get it to work with the following apache2 configuration:

`       # Proxy section for Traccar API
        <Location /api>
        ProxyPass http://localhost:8082/api
        ProxyPassReverse http://localhost:8082/api
        </Location>

        # Proxy section for Traccar API websocket
        <Location /api/socket>
        # Reverse Proxy
        ProxyPass ws://localhost:8082/api/socket
        ProxyPassReverse ws://localhost:8082/api/socket
        </Location>

        # Proxy section for Traccar web interface
        <Location /traccar>
        ProxyPass http://localhost:8082/traccar
        ProxyPassReverse http://localhost:8082/traccar
        </Location>
`
I then had to move everything in the web directory to /traccar

This allows the application to load at my domain name as:
http://mydomainname/traccar

**Comment by tananaev** [comment]
Thanks for sharing the info.
