### ISSUE TITLE
how to add new protocol for any new device

### ISSUE THREAD

**Issue by karthikindia** [traccar/traccar#2036]
how to add new protocol for any new device
I received a protocol document from the device manufacturer
I tried by pointing to my server ip and port using sms config option. the device posts hex.
i decoded the hex also, but unable to find possible or understandable notes to add new device.

I dont have much idea on how to add the device.

can u suggest or help on this.

HEX CODE 

```
200141544c3836383030343032333833363733302c244750524d432c3133323835332c412c313130312e363237312c4e2c30373730312e343536312c452c302c3135332c3230303631362c2c2c2a33462c2330313130303031313030303030302c302c302c302c352e35392c33352e33362c342e302c33302c3430352c3835352c33332c36653841544c0213
```

HEX DECODE

```
 ATL868004023836730,$GPRMC,132853,A,1101.6271,N,07701.4561,E,0,153,200616,,,*3F,#01100011000000,0,0,0,5.59,35.36,4.0,30,405,855,33,6e8ATL
```

does it looks like T55

**Comment by tananaev** [comment]
It doesn't look like T55. Please provide protocol documentation.

**Comment by karthikindia** [comment]
PROTOCOL 
0×20START CHARATERSIGNATUREIMEI,GPS DATA($GPRMC STRINGS) (80 CHAR)$LOC,LOCATION NAME,#I1I2I3I4I5I6I7I8I9I10I11I12I13I14, analog voltage of fuel(2Sg)/N.C,FUEL REMAINING(5Sg)/N.C,TANK CAPACITY(3Sg),ODO READING(7Sg), ,TEMPERATURE(3Sg), Internal battery voltage(3Sg),GSM signal  strength(%2),MCC(3 digit),MNC(3 digit),LAC(6 char),CellID(5Digits)SIGNATURE END CHARACTER Checksum 

•	EXAMPLE 
•	WITH  FUEL NOT CALIBRATED

0×200×01ATL356895037533745,$GPRMC,111719.000,A,2838.0045,N,07713.3707,E,0.00,,120810,,,A*75$,#01100111001010,N.C,N.C,N.C,12345.67,31.4,4.2,21,MCC,MNC,LAC,CellIDATL0×020×7A

•	WITH FUEL CALIBRATED 

0×200×01ATL356895037533745,$GPRMC,111719.000,A,2838.0045,N,07713.3707,E,0.00,,120810,,,A*75#01100111001010,2.3,35.67,80,12345.67,31.4,4.2,21,MCC,MNC,LAC,CellIDATL0×020×7A
•	MEMORY DATA

0×200×03ATL356895037533745,$GPRMC,111719.000,A,2838.0045,N,07713.3707,E,0.00,,120810,,,A*75$LOC,Connaught Circus  Connaught Place  New Delhi  Delhi  India,#01100101101010,2.3,35.67,80,12345.67,31.4,4.2,21,MCC,MNC,LAC,CellIDATL0×040×7A




PROTOCOL DESCRIPTION

The protocol is having the following parts
•	0×20
•	Starting character
•	Signature of protocol
•	IMEI number of device
•	GPRMC strings
•	Location name
•	Alerts
•	Signature
•	End character
•	Checksum


•	0×20----Fixed(Space)
•	0×01/0×03   ----Starting Character of protocol
0×01—for live data and0×03---for Memory data

•	ATL                ---Signature of the Protocol
•	356895037533745    - IMEI       -15 CHAR
•	$GPRMC - GPS DATA    -66 CHAR

THIS SECTION RELATES TO GPS DATA. 

$GPRMC STRING CONTAINS 13 FIELDS, WHICH ARE AS FOLLOWS:

$GPRMC,220516,A,5133.82,N,00042.24,W,173.8,231.8,130694,004.2,W,A*70

Info
Description
$GPRMC
Fixed
220516
TIME STAMP (GMT)
A
VALIDITY     A- VALID,     V - INVALID
5133.82
CURRENT LATITUDE
N
NORTH/SOUTH(S)
00042.24
CURRENT LOGITUDE
W
WEST /EAST(E)
173.8
SPEED IN KNOTS
231.8
TRUE COURSE
130694
DATE STAMP  (DDMMYY)
004.2
MAGNETIC VARIATION DEGREE
W
WEST/ EAST(E) of magnetic variation
A
Mode indicator, (A=Autonomous, D=Differential, E=Estimated, N=Data not valid)

*70
CHECKSUM










•	ALERTS

THIS SECTION RELATES TO VARIOUS ALERTS RAISED ON THE BASIS OF SYSTEM STATUS. 


,#0110010011101,0.3,0,0,12345.67,31.4,4.2,21,MCC,MNC,LAC,CellID
1        2                   3    4   5       6            7      8    9    10       11    12     13    


Sl.No.
Value
Discription
1
#
FIXED
2
11011001001010
STATUS OF VARIOUS I/O FROM I1 to I14
3
0.3
ADC Voltage ( ADC*12=Actual Voltage)
4
0
Reserved for future use
5
0
Reserved for future use
6
12345.90
ODOMETER READING
7
31.4
Temperature/version_IMSI(mobile no.)
8
4.2
Device internal battery voltage
9
21
GSM signal Strength
10
MCC
Mobile country code[3 digits]
11
MNC
Mobile Network Code[3 digits]
12
LAC
Location area code(Mobile)[6 digits]
13
CellId
GSM cell ID[5 digits]

Note:- In field number 7 there may be two different values in protocol.
            1. Temperature of module   OR
            2. Firmware version _mobile no. ( if mobile number is not available, the IMSI        number would come)
           
•	ATL              -----------Signature
•	0×02/0×04    -------------end charactor
0×02  -----------for live data and  0×04   -----for memory data
•	0×7A----------check sum



Note:-
•	The start character and end character are ASCII in protocol need to convert to hex.
•	The checksum is ASCII in protocol need to convert to hex.
•	If checksum is FF read it as 1B, due to some data sending limitation we cannot send 1B. So adjust the same at server end

CHECKSUM CALCULATING METHOD:

voidchksum_gprs(char * ptr)
{
	unsignedint i = 0;
	charchksum=0;

		for(i=0;i<1000 && *ptr != 0x00;i++)
		{
			chksum ^= *ptr++;
		}
		return(chksum);

}
NOTE: FOR ALL DATA PACKETS, AT LAST YOU WOULD GET 
CHECKSUM OF ALL BYTES IN PACKET BETWEEN STARTING  CHARACTER AND END CHARACTER (EXCLUDING BOTH STARTING  CHARACTER AND END CHARACTER).


INPUT DATAILS

INPUTS
Use
Description
I1
High Sense
Ignition, 0=OFF&1=ON
I2
Low sense
Door
I3
Low sense
SOS
I4
Low sense

I5
Low sense

I6
High Sense
A/C , 0=OFF and 1=ON
I7
Low sense

I8
High Sense
Main Power(Fixed), 0=OFFand 1=ON
I9
Harsh speeding
0=normal
I10
Harsh braking
0= normal
I11
ARM/DIASRM
1=ARM & 0=DISARM
I12
Sleep Status
1=Not in Sleep & 0= in Sleep
I13
General relay status
1= Relay ON & 0= Relay OFF
I14
Status of accelerometer
1=In motion& 0= Not in motion

**Comment by tananaev** [comment]
Can you please provide a proper format. I assume it's in word or pdf format originally, right?

**Comment by tananaev** [comment]
Attached the protocol.
[VTS_GPS_L100_V1.1.docx](https://github.com/tananaev/traccar/files/324718/VTS_GPS_L100_V1.1.docx)

**Comment by karthikindia** [comment]
I have sent an email with word foc attachment

**Comment by tananaev** [comment]
Here is a guide for adding new protocols:

https://www.traccar.org/implement-protocol/
