### ISSUE TITLE
Integrate with traccar server for Pushing data and pushing to traccar

### ISSUE THREAD

**Issue by jedjones-uk** [traccar/traccar#2037]
Hi Anton,

I have been using traccar for a while now, and it's been working great but now I am working on a new interface for my system and was hoping you could shed some light on how to achieve what I need.

I would like to be able to do two things:
1) Connect a micro service to the traccar client that will have the new positions pushed to it, so they can be then pushed to our client. 
The reason for this is the tracking is only a part of a larger system and it has its own user/groups management, as well as device management etc. The micro service will handle the authentication and verification of the groups and permissions, before pushing new records to the client.

2) Push updated position data to the traccar service, preferably over a HTTP API.
The reason for this is I want the system to allow for a user to sync their odometer between the value recorded from other sources, and the running total distance under attributes. I can handle updating the latest record and the other system areas, but because traccar calculates the distance between the last position and the next, and the last position is cached the next record would immediately be out of sync again.

Is there some functionality already in the traccar service I can expand or hook into to achieve these things, or if not, where is the best areas for me to look at extending in the source to add it?

Thanks for the fantastic project.

**Comment by tananaev** [comment]
1) There is HTTP forwarding functionality in Traccar that you can use to push data to your service. Here is an example:

https://www.traccar.org/forums/topic/are-there-server-hooks/#post-1934

2) There is no API for this part. I guess you either need to do it your side, and disable Traccar odometer calculation. Or you have to modify Traccar somehow to allow updates.
