### ISSUE TITLE
GT06 Alarm Packet

### ISSUE THREAD

**Issue by gbvaz** [traccar/traccar#2039]
Hi!

I'm having some trouble dealing with the Alarm Packet from GT06, I've checked the Protocol, and I can't seem to find any data on my Traccar database. Can you help me out? Where can I check it? I can see for example the device battery level, but I can't see any thing related to alarms set on the device, such as SOS, power cut etc.

Thanks!

**Comment by tananaev** [comment]
Can you please provide some HEX message samples with alarm info.

**Comment by gbvaz** [comment]
```
5/21/2016 7:21:48 INFO: [440C969C] connected

5/21/2016 7:21:48 DEBUG: [440C969C: 5023 < 177.79.47.81] HEX: 78780d0103837141118104150002a2700d0a

5/21/2016 7:21:48 DEBUG: [440C969C: 5023 > 177.79.47.81] HEX: 787805010002eb470d0a

5/21/2016 7:21:59 DEBUG: [440C969C: 5023 < 177.79.47.81] HEX: 78780a130006640001000269e80d0a

5/21/2016 7:21:59 DEBUG: [440C969C: 5023 > 177.79.47.81] HEX: 787805130002db6a0d0a

5/21/2016 7:21:59 INFO: [440C969C] id: 75, time: 2016-05-21 04:20:23, lat: -19.86391, lon: -43.95155,

5/21/2016 7:23:41 DEBUG: [440C969C: 5023 < 177.79.47.81] HEX: 78781f12100515121729c60221942104b72a4e00

5/21/2016 7:23:41 DEBUG: [440C969C: 5023 > 177.79.47.81] HEX: 787805120003903f0d0a

5/21/2016 7:23:42 INFO: [440C969C] id: 75, time: 2016-05-21 15:23:41, lat: -19.86391, lon: -43.95155,
```

The first debug 78780d0103837141118104150002a2700d0a is a 18 byte, which represents the alarm.

Thanks for your help, I really appreciate it!

**Comment by tananaev** [comment]
First message represents login and not alarm.

**Comment by gbvaz** [comment]
Sorry, my bad!

Here's the correct one:

`5/27/2016 12:28:54 PM DEBUG: [5535E9BC: 7878251610051b0f1c34c5022515d504b5dcd20738080902d4022bdf009cba5006640201006`

Thanks!

**Comment by tananaev** [comment]
This time is not even a valid HEX. It has odd number of characters. Can you please be more careful.

**Comment by gbvaz** [comment]
Really sorry again, my excel cropped the end of the string. Here it is directly from the log file:

2016-05-27 12:28:54 DEBUG: [5535E9BC: 5023 < 187.60.56.100] HEX: 7878251610051b0f1c34c5022515d504b5dcd20738080902d4022bdf009cba5006640201006759680d0a

Thanks again!

**Comment by tananaev** [comment]
OK, I can see that the message is marked as alarm. Is anything missing? If yes, I need protocol documentation that describes this message.

**Comment by gbvaz** [comment]
In my Positions table, from that exact same server time, I have no information whatsoever that the alarm have been triggered:

{"sat":5,"mcc":724,"mnc":2,"lac":11231,"cid":40122,"alarm":true,"ignition":false,"power":6,"gsm":100,"index":103,"ip":"187.60.56.100"}

For example, that hex code was sent when I physically removed the car's battery. The device sent an alarm message containing that information. What I mean is, how can I possibly know if the device sent an alarm message, and which alert was that?

**Comment by tananaev** [comment]
I need protocol documentation to know how to decode that data.

**Comment by gbvaz** [comment]
Can I send you via email?

**Comment by tananaev** [comment]
Yes, address is in profile.

**Comment by gbvaz** [comment]
Ok! Just sent it, let me know if you need anything else :)

**Comment by tananaev** [comment]
It looks like alarm type is part of `status` flags. Not sure why you don't have it. What version of Traccar are you using?

**Comment by gbvaz** [comment]
You mean the status flag from the device table? I'm currently running version 3.3. Should it be working on this version? If not, which one should I upgrade it to?

**Comment by tananaev** [comment]
You should upgrade to the latest one.

**Comment by gbvaz** [comment]
Great! That would be the 3.5?

**Comment by tananaev** [comment]
Yes, you can always check latest version on the official website:

https://www.traccar.org/download/

**Comment by gbvaz** [comment]
Hi @tananaev , I've successfully managed to upgrade to the most recent version (3.5), and I've simulated the same situation as before, removing the battery from the car. Here's the new hex code from the alarm message to the server:

````
2016-06-29 08:34:22 DEBUG: [57CA53B2: 5023 < 187.60.56.100] HEX: 7878251610061d0b212dc7022517c904b5dd3b0038e60902d4022bdf009cba50066402010006d2b50d0a
```

And here's the data from the positions table:

```
{"sat":7,"mcc":724,"mnc":2,"lac":11231,"cid":40122,"alarm":true,"ignition":false,"status":80,"power":6,"gsm":100,"index":6,"ip":"187.60.56.100"}
```

I still can't see any information regarding the alarm, which type was it and how to deal with it. Am I missing something here? Any help?

Thanks again!

**Comment by tananaev** [comment]
Status bitmask is there.

**Comment by gbvaz** [comment]
You mean this? 

"status":80

**Comment by tananaev** [comment]
Yes, that's exactly what I mean.

**Comment by gbvaz** [comment]
And that does the "80" value represents? Is this from the protocol or is it a defined pattern from Traccar itself? What are the other possibilities?

**Comment by tananaev** [comment]
It's a status byte directly from protocol. You can find description in the document that you sent me earlier.

**Comment by gbvaz** [comment]
It says it occupies one byte. If "80" is the byte in hex, it makes no sense because the hex code I sent you does not contain such byte. Are you sure about this? I've checked the protocol and it's not matching with anything. Can you be a little bit more specific?

**Comment by tananaev** [comment]
80 is decimal, not hex.

**Comment by gbvaz** [comment]
How am I supposed to know that? 80 could be hex which is 128 in decimal. Any way.. That being said, 50  in hex represent the 80 in decimal. We do have a 50 byte, on the 32nd position, which according to the protocol, for this type of package, is LBS Near Cell ID. This has nothing to do with which type of alarm nor status of the device. Are you 100% sure about this? All I need to know is how do I keep track of fired alarms on the server so I can notify the user or take any other action based on that information.

**Comment by tananaev** [comment]
Well, decimal is the default format that we use. You don't expect to see prices in a supermarket in hex format when you go there. You don't ask how you know that the price is in decimal, right?

I'm pretty sure it's the right field. It's called "Device information" in the document. So, you have 1010000 in binary format. Alarm is 3-5 bits, so it's 010 in binary (cut-off alarm). Is that what you are expecting?

**Comment by gbvaz** [comment]
Of course decimal is the default format, but in a supermarket there is no such thing as data packages flying all around you with the price encoded in hex waiting for you to interpret them or convert to decimal or binary, right?

So in this case, being the cut-off alarm alright, going back to my original question on this matter, do we or don't we have the information on the database already decoded? If not, I have to decode it by myself, right?

**Comment by tananaev** [comment]
Currently it's the whole mask as one field in the database, but it can be decoded separately. Just need to add some code.
