### ISSUE TITLE
Alarm Icon

### ISSUE THREAD

**Issue by monitoreogps** [traccar/traccar#2042]
Hi friend

In traccar, How Do you can to change the icons of the vehicule actual position , actualy i view a blue triangle. Also, How I can view on the map the alarm , when i push the SOS buttom. 

Thank you

**Comment by tananaev** [comment]
If you want to change icon, you need to make some modifications to `MapController` class.

**Comment by monitoreogps** [comment]
this is, i should create a java proyect and compilate all the proyect al install the .jar?
or i can change any file on traccar server?

**Comment by tananaev** [comment]
You can change JavaScript files without compilation. You just need to <a href="https://github.com/tananaev/traccar/issues/2040#issuecomment-227939314">enable debug mode<a/> for web interface.

**Comment by monitoreogps** [comment]
I enable debug mode on the servero or the client?

**Comment by tananaev** [comment]
Please read linked thread carefully.
