### ISSUE TITLE
Group Snapshot / Replay [New Feature Request]

### ISSUE THREAD

**Issue by neilromig** [traccar/traccar#2053]
It would be useful to have the option to view all locations for a Group for a previous date & time.
I am keen not to clutter up the existing clean and simple interface, so perhaps this could be done by a button or option to set the map time from "Now" to some previous value.
Another approach could be to have optional panes on the interface so that the "State" pane could be turned off and replaced with the new "Snapshot" pane?
I would then easily be able to answer such questions as "Who was at a particular location last Tuesday at 16:00?" Also, it would be even better to then be able to step the map forwards by intervals of 1/5/10 minutes...

**Comment by tananaev** [comment]
Thanks for create a feature request. I will post an update here as soon as I have anything.

**Comment by neilromig** [comment]
I would consider this issue closed, since practically all the required functionality is in the Trip report in v3.8.

**Comment by darshan2210** [comment]
Hi Anton,

Any chance we can add the playback(Reply) functionality in Route(report).

That's really helpful feature.

Thanks.

**Comment by tananaev** [comment]
There is a good chance, but I just can't tell when it will happen.

**Comment by darshan2210** [comment]
Thank you for that. Hope we can soon have this feature in coming up update.

**Comment by aldesantis** [comment]
@tananaev have there been any updates on this by any chance?

**Comment by tananaev** [comment]
Not yet. It's unlikely that we would be adding any new functionality to the old web app. If we implement this, it will be in the new web app.

**Comment by tananaev** [comment]
Modern app has replay functionality.
