### ISSUE TITLE
Traccar commands with PT502

### ISSUE THREAD

**Issue by tmami** [traccar/traccar#2055]
Hi Tananaev,

We just installed traccar 3.5 and test the PT502, it worked fine for us untill we decide testing the commands (engine stop), we get this error:

```
"{\"reason\":\"java.lang.RuntimeException: Command engineStop is not supported in protocol pt502\",\"success\":false}"
```

Close

I guess that the protocol at the backend is not finish yet? - do you have the list of the protocols that already implement this feature so I can test if I have the device, I have TK103 and PT600. (just in case)

Finally, is-it easy to help you on developing these commands ? - I am just new in java, but I think the encoder is already there so if I just stick to the device protocol I can make it !

Thanks for your feedback.

cheers
Thomas

**Comment by tananaev** [comment]
You can check what commands are supported for a particular protocol by looking at the protocol class:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Pt502Protocol.java#L33

Adding new commands should be straight forward if you have protocol documentation.

**Comment by drecchia** [comment]
Hey everyone! I got this protocol and I will try to help :)

Anton, the OPC command you implemented at:
https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Pt502Protocol.java#L33
has different format from the documentation ( attached )
![screenshot 2016-07-05 17 33 59](https://cloud.githubusercontent.com/assets/5439830/16599261/e87e9592-42d7-11e6-9293-f62b4d913061.png)

The tracking implementation matches the doc.

Can I fix TYPE_OUTPUT_CONTROL as the document and implement TYPE_ENGINE_STOP and TYPE_ENGINE_RESUME based on OPC ?

Thanks
Danilo Recchia

**Comment by tananaev** [comment]
Yes, I think you are right. The format I'm using is most likely incorrect.

**Comment by drecchia** [comment]
Ok, this feature is merged into trunk, but I wasnt able to implement ENGINE_STOP and ENGINE_START since there is no default port on this device. But you can achieve the same behavior using the OUTPUT_CONTROL that I fixed.

Regards
