### ISSUE TITLE
What is the strategy of marking device online/offline?

### ISSUE THREAD

**Issue by Farhan7786** [traccar/traccar#2058]
I have a running device sending data to server continuously means device has active tcp connection (device is online), but then i switched off the device it is still showing online. Is it a bug or is there any timeout limit for marking inactive device as offline?

Thanks

**Comment by tananaev** [comment]
Device online status means TCP connection status. If you device doesn't properly close connection, it will show as online until connection times out. By default it's just OS timeout, but you can set custom timeout per protocol in Traccar. More info here:

https://www.traccar.org/configuration-file/
