### ISSUE TITLE
traccar and cyberfleet

### ISSUE THREAD

**Issue by erik2016** [traccar/traccar#2067]
Как ретранслировать данные из сервера traccar  в cyberfleet?

**Comment by tananaev** [comment]
Что такое cyberfleet? Неплохо было-бы ссылочку привести какую-нибудь.

**Comment by erik2016** [comment]
http://m2m-t.ru/cyberfleet/.    Клиентская программа. M2M.

**Comment by tananaev** [comment]
На их сайте не смог найти никакой информации о том как передавать данные в CyberFleet.

**Comment by erik2016** [comment]
может для traccar есть аналог cyberfleet?

**Comment by erik2016** [comment]
для cyberfleet есть серверное по bncomplex.

**Comment by erik2016** [comment]
Хотим подключить к traccar терминалы M2M Cyber GL, GLX, Stab Liner, нужно чтобы доступ к мониторингу был только с одного компьютера, (по типу bncomplex(сервер) - cyberfleet(компьютер клиента)).

**Comment by tananaev** [comment]
Не совсем понимаю что именно требуется. Если нужно ограничить доступ к Traccar, то это можно сделать через firewall, но только не совсем понимаю зачем. Чтобы пользоваться системой все равно нужен логин и пароль, так что кто попало зайти не сможет.

**Comment by erik2016** [comment]
нужно чтобы через программу только входили в traccar, без логина и пароля.

**Comment by erik2016** [comment]
через клиентскую программу из компьютера в офисе.

**Comment by erik2016** [comment]
дежурные пользователи разные, доступ к терминалу один.

**Comment by erik2016** [comment]
и только с одного компьютера.

**Comment by tananaev** [comment]
Чтобы с одного компьютера только заходить можно было делается через firewall легко. Чтобы без логина можно было заходить нужно доработать код немного. Напишите мне на электронную почту если нужна помощь (адрес в профиле).

**Comment by erik2016** [comment]
ок спасибо антон.
