### ISSUE TITLE
macbook pro

### ISSUE THREAD

**Issue by chapstar1** [traccar/traccar#2070]
i have already installed java 8 and still getting this issue plz 

```
MacBook-Pro:~ james$ /Users/james/Desktop/traccar-macosx-64-3.5-2/traccar.run 
Verifying archive integrity... All good.
Uncompressing traccar  100%  
Java 7 or higher required
```

**Comment by tananaev** [comment]
What's the output of the following command:
```
java -version
```

**Comment by chapstar1** [comment]
MacBook-Pro:~ james$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode

**Comment by chapstar1** [comment]
now im getting this
MacBook-Pro:~ james$ /Users/james/Desktop/traccar.run 
Verifying archive integrity... All good.
Uncompressing traccar  100%  
mkdir: /opt/traccar: Permission denied
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
chmod: /opt/traccar: No such file or directory
./setup.sh: line 14: /opt/traccar/bin/traccar: No such file or directory
rm: /opt/traccar/setup.sh: No such file or directory

**Comment by tananaev** [comment]
You need to run it as root:
```
sudo /Users/james/Desktop/traccar.run
```
