### ISSUE TITLE
I can't install on raspberry pi

### ISSUE THREAD

**Issue by MrCyjaneK** [traccar/traccar#2094]
Starting traccar .................
Unable to start traccar

**Comment by tananaev** [comment]
Check wrapper log file.

**Comment by sambote** [comment]
Bonjour,

Je suis completement novice en linux et je souhaiterai installe TRACCAR sur mon Raspberry Pi, quelqu'un pourrait me conseiller ou m'aider?

Sam

**Comment by tananaev** [comment]
@sambote, please create a separate thread. Also, there is a better chance of getting reply if you state your question in English. Also, search existing thread. There were questions about Raspberry Pi before.
