### ISSUE TITLE
is it safe to add some code under GT06protocoldecoder.java

### ISSUE THREAD

**Issue by sonuauti** [traccar/traccar#2098]
i have added some notification functionality in GT06protocoaldecoder.java class and decodeStatus function like like send notification when device is turn on/off. it working fine but 20-30 min traccar server stop tracking the devices.
following is the code snippets,\

``` java
 if(position.getDeviceId()>0){
            String query = "SELECT * FROM notification WHERE deviceId=" + position.getDeviceId();

            Statement statement = Context.getDataManager().getDataSource().getConnection().createStatement();
            ResultSet rs = statement.executeQuery(query);

            String notificationId = "";
            String lastStatus = "";
            while(rs.next()){
            notificationId = rs.getString("notificationKey");
            lastStatus = rs.getString("lastStatus");
            }

            SendNotifications sn=new SendNotifications();
            //   con=Context.getDataManager().getDataSource().getConnection();
            if (BitUtil.check(flags, 1) == true) {
                // System.out.println(cl.toArray());
                if (lastStatus.equalsIgnoreCase("false") || lastStatus.equalsIgnoreCase("0")) {

                    String msg=URLEncoder.encode("ON" + " at " + position.getDeviceTime(), "UTF-8");
                    sn.sendNotifications(notificationId,msg , 2);

                    String q = "UPDATE notification SET lastStatus=true WHERE deviceId=" + position.getDeviceId();
                    statement = Context.getDataManager().getDataSource().getConnection().createStatement();
                    statement.executeUpdate(q);
                }

            }

            if (BitUtil.check(flags, 1) == false) {

                if (lastStatus.equalsIgnoreCase("true") || lastStatus.equalsIgnoreCase("1")) {
                    String msg=URLEncoder.encode("OFF" + " at " + position.getDeviceTime(), "UTF-8");
                    sn.sendNotifications(notificationId,msg , 2);
                    String q="UPDATE notification SET lastStatus=false WHERE deviceId="+position.getDeviceId();
                    statement = Context.getDataManager().getDataSource().getConnection().createStatement();
                    statement.executeUpdate(q);

                }

            } 
```

**Comment by tananaev** [comment]
What is `SendNotifications`? Your code is wrong in many ways, but I guess it should work. Try to debug and see why it stops to receive data.

**Comment by cispune** [comment]
SendNotification is simple class which send notification via google gcm.
its 4 line code only. what mistake i made can you tell me?

On Mon, Jul 11, 2016 at 4:51 PM, Anton Tananaev <notifications@github.com>
wrote:

> What is SendNotifications? Your code is wrong in many ways, but I guess
> it should work. Try to debug and see why it stops to receive data.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tananaev/traccar/issues/2098#issuecomment-231707842>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APXoByvpuid44WzJCqCP28ckUAvIQTWmks5qUicpgaJpZM4JJFX7>
> .
>



-- 
CIS Technologies (P) Ltd.

**Comment by tananaev** [comment]
I don't see any obvious mistakes. It's just bad practices like using string concatenation for SQL queries, accessing database directly from decoder. But technically it should work.

Are you sure your `SendNotifications` is fine? Does it do blocking calls? It might be a problem if it does.

**Comment by cispune** [comment]
i placed the send notification inside the thread run method to avoid any
blocking but still no success, tracker server work for 20-30 min and goes
down with no any debug or error message

On Tue, Jul 12, 2016 at 3:56 AM, Anton Tananaev <notifications@github.com>
wrote:

> I don't see any obvious mistakes. It's just bad practices like using
> string concatenation for SQL queries, accessing database directly from
> decoder. But technically it should work.
>
> Are you sure your SendNotifications is fine? Does it do blocking calls?
> It might be a problem if it does.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tananaev/traccar/issues/2098#issuecomment-231884620>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APXoB2Jn3fsibrMakJrwyfetnWssZL1fks5qUsMqgaJpZM4JJFX7>
> .
>



-- 
CIS Technologies (P) Ltd.

**Comment by tananaev** [comment]
What do you mean by "goes down"? Is the process running?

**Comment by cispune** [comment]
yes

On Tue, Jul 12, 2016 at 10:53 AM, Anton Tananaev <notifications@github.com>
wrote:

> What do you mean by "goes down"? Is the process running?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tananaev/traccar/issues/2098#issuecomment-231940363>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APXoB1PlVo-tqyqH9bYY6Gax6u5f9UaCks5qUyTVgaJpZM4JJFX7>
> .
>



-- 
CIS Technologies (P) Ltd.

**Comment by tananaev** [comment]
Then you can get stack traces using `jstack` and see why it gets stuck.
