### ISSUE TITLE
Allow Icons to gray/disappear off map after a set amount of time

### ISSUE THREAD

**Issue by snoop168** [traccar/traccar#2105]
After a set amount of time it would be nice to gray out the icon (one setting) to indicate that the location is stale.

Additionally a second setting to actually remove the icon from the map.

**Comment by tananaev** [comment]
As I said, there is already a "stale" state which shows as yellow. I don't see much value in changing the color from yellow to gray.

As for removing the icon from map, this might be useful, so I'll consider implementing it in one of the future versions.

**Comment by snoop168** [comment]
Is there a setting for "Stale" time? or is the value hard coded?

**Comment by tananaev** [comment]
Yes, you can set it in the server config (value is in milliseconds):
```
<entry key='status.timeout'>30000</entry>
```
