### ISSUE TITLE
How to prevent displaying data like this?

### ISSUE THREAD

**Issue by mrameezraja** [traccar/traccar#2114]
We have a tracker installed in a vehicle, which sends data continously while parking. Which displays like below. How can we make it more user friendly?
![screen shot 2016-07-14 at 8 37 54 pm](https://cloud.githubusercontent.com/assets/8121938/16845709/47cd5e84-4a03-11e6-967a-e0c9584b0f10.png)

**Comment by tananaev** [comment]
You can enable filtering in the [config file](https://www.traccar.org/configuration-file/).

**Comment by fcazar** [comment]
witch parameter?

**Comment by tananaev** [comment]
You need to use `filter.distance` parameter.
