### ISSUE TITLE
VPS or local server

### ISSUE THREAD

**Issue by poobaisle** [traccar/traccar#2128]
I don't know where to post this. I try here. I believe it is possible to run traccar on a local server even though it is more complicated without static IP address. So I am also thinking to host the application on a VPS. I have a question about this which is not directly related to traccar but more general. Is it a problem to find a VPS outside of the country where I work to get better hosting prices ? I mean on a technical ground, the fact that the server might be in the US or somewhere else Thailand (where I work), will it somehow impact the reliability of Traccar ? Based on my basic knowledge I don't see why it should but I may be wrong. Can someone please advise me on that point ? Thank you
Poobaisle

**Comment by tananaev** [comment]
There would be no difference is reliability of Traccar. It doesn't matter where the server is hosted. If anything, US hosting would probably more stable than the one in Thailand. Depends on the provider of course.

The only difference might be ping to the server, but it still should be reasonably good.

**Comment by poobaisle** [comment]
Happy to learn that my basic knowledge in IT stuff was good enough. Should build up some knowledge in economy to understand how local VPS can attract customers with prices by far much higher... Is 2 GB RAM sufficient to run Traccar or I should rather go for 4 GB ?

**Comment by tananaev** [comment]
It depends on volume of location reports from devices, and also from number of users.

**Comment by poobaisle** [comment]
Let's say about 500 locations/point of interest/geofences and 10-20 users max

**Comment by tananaev** [comment]
I was asking about number of reports from devices per some period of time.

Anyway, 2GB should be enough for 500 devices with some average reporting period (say 1 minute).

**Comment by poobaisle** [comment]
Hello, yes it is 1 signal/minute/device

**Comment by poobaisle** [comment]
I don't have 500 devices though but only 40 so far and around 500 delivery spots to be monitored.

**Comment by tananaev** [comment]
Then definitely 2GB should be enough.

**Comment by poobaisle** [comment]
You didn't comment the possibility of running Traccar on a local server. Too difficult to set up you think ?

**Comment by tananaev** [comment]
It might require some technical knowledge to configure router and firewall. Installing Traccar server itself if very simple.

**Comment by flyjodel** [comment]
Hi, I use traccar on a VULTR VPS (the smallest and cheapest machine available), it costs me around 5 $ a month, and the reliability is 100%. I recently added the static IP option. 

The most difficult point before installation is to enter the password in the terminal. But after that, it runs smoothly with 768 MB memory and 1 processor only. And the 15GB SSD gives plenty of space for other applications.

**Comment by flyjodel** [comment]
#               Uptime | System                                     Boot up   
----------------------------+---------------------------------------------------   
->   1    41 days, 08:35:14 | Linux 3.2.0-4-amd64       Wed Jun 22 21:00:27 2016   
     2     1 day , 10:07:54 | Linux 3.2.0-4-amd64       Tue Jun 21 10:52:23 2016   
----------------------------+---------------------------------------------------   
NewRec    39 days, 22:27:19 | since                     Fri Jun 24 07:08:20 2016   
    up    42 days, 18:43:08 | since                     Tue Jun 21 10:52:23 2016   
  down     0 days, 00:00:10 | since                     Tue Jun 21 10:52:23 2016   
   %up              100.000 | since                     Tue Jun 21 10:52:23 2016


The downtime is due to a reset for test purposes because my Linux knowledge is basic.
