### ISSUE TITLE
GT06 protocol acc on/off not showing in flags

### ISSUE THREAD

**Issue by vasu2211** [traccar/traccar#2133]
Please help me to solve the issue , gt02 device connected to traccar and location showing in flag but acc on/off not showing . how to get it. device is connected to port 5023 , please help.

**Comment by tananaev** [comment]
Are you sure you device sends ACC info? Can you provide HEX message samples from log?

**Comment by vasu2211** [comment]
3431453034352e313131313432303237372e393230313030303030374c303139363233333629
2016-07-20 11:14:26  INFO: [74CA99F3] id: 11, time: 2016-07-20 11:14:20,
lat: 17.79125, lon: 75.68924, speed: 24.4, course: 277.9
2016-07-20 11:14:30 DEBUG: [722AE57B: 5023 < 49.15.133.18] HEX:
78780a134406040002011938c50d0a
2016-07-20 11:14:30 DEBUG: [722AE57B: 5023 > 49.15.133.18] HEX:
7878051301196ce00d0a
2016-07-20 11:14:30  INFO: [722AE57B] id: 9, time: 2016-07-20 11:10:38,
lat: 17.01647, lon: 81.79848, speed: 0.0, course: 33.0
2016-07-20 11:14:51 DEBUG: [9C0CA407: 5023 < 27.97.192.81] HEX:
78780a1344060400020033af450d0a
2016-07-20 11:14:51 DEBUG: [9C0CA407: 5023 > 27.97.192.81] HEX:
787805130033fb600d0a
2016-07-20 11:14:51  INFO: [9C0CA407] id: 7, time: 2016-07-20 11:10:09,
lat: 16.96227, lon: 82.27032, speed: 0.0, course: 10.0

**Comment by boudgeau** [comment]
hello, i'm having the same problem here , all of my gt06 and gt06n devices having the same problem! any idea?
Thanks

**Comment by tananaev** [comment]
I guess it doesn't have a GPS fix, so it reports zero coordinates.

**Comment by boudgeau** [comment]
i don't know, ,but the device is moving on map and been tracked well and accurate!! could't there be  another problem ?

**Comment by tananaev** [comment]
That's not possible. You must be missing something.

**Comment by boudgeau** [comment]
you are right, it's showing location normally in the debug, i've chose bad sample with non fix gps status, but however the ACC flags not showing , plus the HEX debugger is showing bad hex and cannont be decoded?
Sample:
 
2016-08-27 07:53:51 DEBUG: [BC2B4760: 6023 < 212.98.134.21] HEX: 78781f1210081b0f3427c803959dfc03ce0b531b341500019f0302c2001d309222180d0a
2016-08-27 07:53:51 DEBUG: [BC2B4760: 6023 > 212.98.134.21] HEX: 787805123092a39d0d0a
2016-08-27 07:53:51  INFO: [BC2B4760] id: 353419034850961, time: 2016-08-27 15:52:39, lat: 33.40942, lon: 35.46387, speed: 14.6, course: 21.0

**Comment by tananaev** [comment]
If you don't see ACC, it means your device doesn't send it. Where is the bad HEX?

**Comment by boudgeau** [comment]
it used to send normally, hex in first line
78781f1210081b0f3427c803959dfc03ce0b531b341500019f0302c2001d309222180d0a

**Comment by tananaev** [comment]
It is decoded just fine as far as I can see.

**Comment by boudgeau** [comment]
im using your decoder decoder https://www.traccar.org/hex-decoder/ and here's the output:
xx4'ÈüÎS4Â0"
 ?

**Comment by tananaev** [comment]
It's GT06 protocol, port 5023.

**Comment by boudgeau** [comment]
does it have acc info ?

**Comment by tananaev** [comment]
If you don't see it in the state, it doesn't.

**Comment by saulo1212** [comment]
Hi!
I started a project with gt06, I'm getting the localization package,

<Buffer 78 78 1f 12 15 04 11 0d 3a 38 c9 01 d9 66 a4 05 07 04 8c 00 18 00 02 d4 02 51 02 00 ad 9a 00 f5 4c 16 0d 0a>

how to extract the inginition status on or off, I was confused by the documentation

**Comment by saulo1212** [comment]
Hi!
I started a project with gt06, I'm getting the localization package,

<Buffer 78 78 1f 12 15 04 11 0d 3a 38 c9 01 d9 66 a4 05 07 04 8c 00 18 00 02 d4 02 51 02 00 ad 9a 00 f5 4c 16 0d 0a>

how to extract the ingnition status on or off, I was confused by the documentation

**Comment by saulo1212** [comment]
Hi!
I started a project with gt06, I'm getting the localization package,

<Buffer 78 78 1f 12 15 04 11 0d 3a 38 c9 01 d9 66 a4 05 07 04 8c 00 18 00 02 d4 02 51 02 00 ad 9a 00 f5 4c 16 0d 0a>

how to extract the ignition status on or off, I was confused by the documentation
