### ISSUE TITLE
traccar suddenly stopped unable to open from server ip with port 8082

### ISSUE THREAD

**Issue by vasu2211** [traccar/traccar#2138]
I checked on server traccar status is running when tried open with server ip 104.218.50.11:8082

i am getting this error below

```
Directory: /
WEB-INF/    4096 bytes  Jul 9, 2016 7:03:16 AM
img/    4096 bytes  Jul 9, 2016 7:03:13 AM
js/     4096 bytes  Jul 9, 2016 7:03:13 AM
traccar/    4096 bytes  Jul 9, 2016 7:03:14 AM
```

**Comment by drecchia** [comment]
I do not believe that it is an error message.

**Comment by drecchia** [comment]
Anyway, looks that your project is missing some front end files. Are you compiling the project by your self?

**Comment by tananaev** [comment]
@vasu2211, I don't think you are using official version of Traccar.

**Comment by vasu2211** [comment]
Stop traccar service and started problem solved.
