### ISSUE TITLE
Device configuration

### ISSUE THREAD

**Issue by poobaisle** [traccar/traccar#2143]
Hello,
Is there an SMS command that will allow the device to turn back to factory setting without the password ?

**Comment by tananaev** [comment]
What device are you talking about? Traccar supports more than 600 models and each of them are different.

**Comment by poobaisle** [comment]
It has nothing to do with traccar. I am just trying to find a way to
configure the device to send information to the server ip without admin
password. I have 10 trackers that I want to reuse from I previous
commercial contract.

Le samedi 23 juillet 2016, Anton Tananaev <notifications@github.com> a
écrit :

**Comment by tananaev** [comment]
Yes, but you missed my point. You didn't say what kind of devices you have. It's not possible to help you without knowing what device model you have.

**Comment by poobaisle** [comment]
There is another post "Device configuration #2130" where I give all the details about the device I am talking about.

**Comment by tananaev** [comment]
First of all, I can't remember all the thread and names. Also, why have you created a second thread?

**Comment by poobaisle** [comment]
Well, the first post is about the specific device I couldn't configure with all the details about it. The second post is about "generic SMS command" to configure any device. Just trying to find a way out. I am not suggesting you should or could remember all the thread and names. You were asking about the device so I gave you the answer. No hard feelings please.

**Comment by tananaev** [comment]
Unfortunately there is no such thing as "generic SMS command".

**Comment by poobaisle** [comment]
Which means that if I don't get the specific configuration manual + password that has been used to configured the device I can just throw them away ? After double checking 19 of them are installed on my trucks so I am a bit concerned...

**Comment by tananaev** [comment]
Correct, if you can't find manuals for your specific devices, you won't be able to re-configure them.

**Comment by Abyss777** [comment]
Hello, @poobaisle
I'm pretty sure that there is a button somewhere inside to reset configuration and password. 
You can try to buy new device and force seller provide you documentation, but success depends of laws in your country.
It can be cheaper than replace all 19 devices.

**Comment by josephphale** [comment]
Hi i am finding it difficult to configure traccar...it does not show the registered device on the me...somebody help...

**Comment by poobaisle** [comment]
Thank you @Abyss777 for your support ! Believe me, I have been searching every micro² with my magnifying glass for that magic reset "click hole"... but I couldn't find it. And @tananaev is right, even though I reset everything. If I don't have the manual to know which command to enter it is useless... My only hope was to plug in the device through the serial port or something like that. Someone can do this for sure but not me...

**Comment by tananaev** [comment]
@josephphale, please create a separate issue and provide more details about the problem.

@poobaisle, one option I can think of is try to find your device by photo on Google, then if you find the model, contact vendor/seller and ask for manual. Or even buy one device to force them to provide it as @Abyss777 suggested.
