### ISSUE TITLE
Support GPS Tracker MT-1 version 08

### ISSUE THREAD

**Issue by boonya** [traccar/traccar#2145]
Hello everyone.
I have a few devices bought on aliexpress called **GPS Tracker MT-1 version 08**. [This one](http://www.i-trac.cn/productshow.asp?ArticleID=Q5RWT60YZT&id=1484).
Seems like it use protocol H02 which implemented already, but I'm not sure. Each line of data I've got from this tracker looks like above:

```
*HQ,8160522977,V1,115637,A,4831.0453,N,03502.3833,E,000.21,000,230716,FBFFBBFF,255,06,30453,1853#
```

So, the question is - do you support this kind of protocol? Is it the same `H02`? And if so, then could you add MT-1 v08 to the list of supported devices..

**Comment by tananaev** [comment]
It is H02 protocol. I will update the list of supported devices.

**Comment by boonya** [comment]
BTW., seems like it works not really correctly. ![Screenshot](http://dl2.joxi.net/drive/2016/07/25/0000/2016/38880/80/e9e819e446.jpg). ACC on my vehicle is switched off currently, but UI shows opposite ignition status. It has been showing "**no**" when was switched on.
And just a question, what does status value mean? Is it depends on tracker model?

**Comment by tananaev** [comment]
I have fixed the problem with ignition.

As for status, value depends on the protocol and possibly model as well.
