### ISSUE TITLE
Socket Programming issue fortopflytech t8806 GPS Tracking devices

### ISSUE THREAD

**Issue by abnan0001** [traccar/traccar#2146]
Hello All
1. we are getting the login data but after getting we need to send responce to device with a format that device can verify server and then send actual gps data to server.
2. we are not able to send login data to that device so that's why device not send us gps data.
3. Login Data we are getting is like :- 2323101501f357367031649441529625060.
4. We are not getting further process what to do to get Device gps data to our server.

below is the code:

``` java
package com.trackit;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ServerListener {

    public static void main(String[] args) {
        new ServerListener().startServer();
    }

    public void startServer() {
        final ExecutorService clientProcessingPool = Executors.newFixedThreadPool(03);

        Runnable serverTask = new Runnable() {
            @SuppressWarnings("resource")
            @Override
            public void run() {
                try {
                    ServerSocket serverSocket = new ServerSocket(5094);
                    System.out.println("Waiting for clients to connect...");
                    while (true) {
                        Socket clientSocket = serverSocket.accept();
                        clientProcessingPool.submit(new ClientTask(clientSocket));
                    }
                } catch (IOException e) {
                    System.err.println("Unable to process client request");
                    e.printStackTrace();
                }
            }
        };
        Thread serverThread = new Thread(serverTask);
        serverThread.start();
    }

    private class ClientTask implements Runnable {
        private final Socket clientSocket;

        private ClientTask(Socket clientSocket) {
            this.clientSocket = clientSocket;
        }

        @Override
        public void run() {
            System.out.println("Got a client !");
            try {
                BufferedReader reader = new BufferedReader( new InputStreamReader(clientSocket.getInputStream()));
                String clientData = "";

                clientData = reader.readLine();

                String hex_value = asciiToHex(clientData);

                System.out.println("Hex Value :-"+hex_value);


            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        private String asciiToHex(String clientData) {

            char[] chars = clientData.toCharArray();
            StringBuffer hex = new StringBuffer();
            for (int i = 0; i < chars.length; i++)
            {
                hex.append(Integer.toHexString((int)chars[i]));
            }
            return hex.toString();
        }
     }

}
```

**Comment by tananaev** [comment]
So, what is your question?

Also, why do you want to implement your own server if Traccar already can handle it?

**Comment by abnan0001** [comment]
Thanks for ur warm response..

We are developing some own products of our company & in that we have a part
of live map with many other functionality for our product..

So , could you please help us to sort the issue..

I will connect you to our developers

Thanks alot


*--------------------------------------------------------------------------------------------------------------------------------------------------*
M.A. ABNAN YAZDANI
*GEOMATICS & CIVIL ENGINEER*
Skype  :  muhammad_madina
| Jeddah | Saudi Arabia.

**Comment by tananaev** [comment]
It doesn't explain why you can't reuse existing solution. Traccar can work as a back-end and you can develop your own functionality on top of that. Don't see any reason to invent something that already exists.

**Comment by abnan0001** [comment]
Thanks for ur reply..

Already , we have used some servers but we failed to implement the plugins
, finally we came up with our own server..

I have connected our core developer , He can explain you much better than
me.

@sameer , please explain Mr tananaev in detail


*--------------------------------------------------------------------------------------------------------------------------------------------------*
M.A. ABNAN YAZDANI
*GEOMATICS & CIVIL ENGINEER*
Skype  :  muhammad_madina
| Jeddah | Saudi Arabia.

**Comment by sameer2020** [comment]
Hello @tananaev  and @abnan0001 
We are looking to use traccar however please confirm me if we use Traccar can it support all advanced and basic features of Topfly deveices.

Topfly Devices are as follows:
Basic Device: T8803
Advanced Device: T8806
ODB: T8806

Advanced fetures like as follows:
- Fuel Details
- Door Open
- AC
- Relay
- Ignition
- Sorting of all tracker on google map
- Customized Icon for Vehicle.

based on our Finding it look like traccar only support basic topfly device features.

Please confirm on this.

Thank you.
