### ISSUE TITLE
Feature Request : Reverse Geocode : LocalStorage/Cache

### ISSUE THREAD

**Issue by jaimzj** [traccar/traccar#2151]
Dear Anton and All,

What is your opinion on a feature, where (traccar locally stores) the reverse geo-code results, (so that everytime a gps location is recieved) it reaches out to the geocode provider only if traccar itself does not have records for it.

?

**Comment by tananaev** [comment]
Reverse geocoding cache is already available. You can control the size using `geocoder.cacheSize` configuration parameter. It's in-memory cache, so it will be cleared when you restart service.

**Comment by nefertiti007** [comment]
Perfect,  I never knew this existed :) 

However do you feel, it would make sense to implement a permanent cache, than an in-memory cache.

?

**Comment by tananaev** [comment]
There is no plan for that at the moment. I don't want to over-complicate server side because of this. Mostly because I'm not so sure it's a good idea to do caching of reverse geocoding requests. I want to know some statistics to see if it actually works.

**Comment by Abyss777** [comment]
Hello, @nefertiti007 
In addition
You can install separate cache for requests, for example https://github.com/tobias74/reverse-geocoder-cache

or even install your own nominatim https://github.com/twain47/Nominatim

And there are some more standalone solutions.
