### ISSUE TITLE
Is there a way to show geofences on the map at all times?

### ISSUE THREAD

**Issue by deathg0d** [traccar/traccar#2156]
The UI would be very intuitive if we could show geofences on the map at all times. This would make viewing how a vehicle interacts with a geofence much easier to see.

**Comment by tananaev** [comment]
Good point. We'll definitely consider it in one of the next releases.

**Comment by Abyss777** [comment]
@tananaev I think it should be switchable and wanted to place button near "Mute" but there is no place left. Should we increase width of device panel or put switch in other place? Should we store state somewhere (like user attribute) or not like "Mute".

**Comment by tananaev** [comment]
It should be switchable. We can move general buttons like that into the map toolbar. Not actual toolbar, but into the title bar (blue one).

**Comment by Abyss777** [comment]
I'm working on this feature now.
What will be default state? (show or hide)
Do we need labels (name) near geometry?
Do we need some action on click?

**Comment by tananaev** [comment]
> What will be default state? (show or hide)

I think show by default would be a good idea.

> Do we need labels (name) near geometry?

I think it's good to show labels.

> Do we need some action on click?

It would be perfect to be able to add/edit/delete geozones from the same map. Not sure if it's in scope for this particular issue.

**Comment by deathg0d** [comment]
Any update on this? Has this been implemented on the newer releases of Traccar?

**Comment by tananaev** [comment]
Yes, it has been implemented.
