### ISSUE TITLE
Synology upgrade to 3.6-009 stoped working

### ISSUE THREAD

**Issue by megaghis** [traccar/traccar#2162]
Yesterday I have upgrade Traccar, on my Synology, to version 3.6-009 and now Traccar is not working anymore. Before it was working geat (I just installed it 5 days ago).

I have tried :
uninstall and reinstall Traccar 3.6-009
uninstall (erase the database) and reinstall Traccar 3.6-009
uninstall Traccar 3.6-009 and install Traccar 3.4-006
restart the service.

Everytime, the same results : Traccar is not starting.

In fact, if I try to "run" Traccar the application seems to run for 1 second and stops.

I am new to Traccar and I am not used to Linux environnement so I don't know how to extract a log to send the information here.

My Synology is a DS1815+.

Thanks

**Comment by tananaev** [comment]
@1sthandy might be able to help. He developed Synology package.

**Comment by 1sthandy** [comment]
Restart your Synology it seems, that traccar is running in background. After restart you can install the new version.
