### ISSUE TITLE
Database Schema was not created after upgrade from 3.4 -> 3.5 -> 3.6

### ISSUE THREAD

**Issue by charlymanja** [traccar/traccar#2169]
Hi Anton, after upgrade the database schema was not updated with the new tables...

```
2016-07-29 15:52:38  WARN: Table 'geofences' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:380 < DataManager:565 < GeofenceManager:115 < ...)
2016-07-29 15:52:38  WARN: Table 'notifications' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:380 < DataManager:651 < NotificationManager:102 < ...)
2016-07-29 15:52:39  INFO: Starting server...

2016-07-29 15:58:51  WARN: Table 'notifications' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:435 < DataManager:663 < NotificationManager:152 < ...)
```

```
mysql> show tables;
+-----------------------+
| Tables_in_RTTracking  |
+-----------------------+
| DATABASECHANGELOG     |
| DATABASECHANGELOGLOCK |
| devices               |
| events                |
| groups                |
| positions             |
| server                |
| user_device           |
| user_group            |
| users                 |
+-----------------------+
10 rows in set (0.01 sec)
```

Can you provide me a DB Schema for mysql ?
Why the tables were not created?

Thx in advance

**Comment by tananaev** [comment]
I guess you are missing something in the configuration.

Also, check if `DATABASECHANGELOG` table has changelog for version 3.6.

**Comment by charlymanja** [comment]
Hi, I copy the last configuration file ( ${TRACCAR_HOME}/conf/traccar.conf ) from the sources and edited to fit with my options. Is there any option to check?

mysql> select * from DATABASECHANGELOG where ID = 'changelog-3.6'\G;
*************************** 1. row ***************************
           ID: changelog-3.6
       AUTHOR: author
     FILENAME: changelog-3.6
 DATEEXECUTED: 2016-07-29 11:41:16
ORDEREXECUTED: 16
     EXECTYPE: MARK_RAN
       MD5SUM: 7:004a8d524956a3f4e1f4dbffdb2ec9de
  DESCRIPTION: createTable tableName=events; addForeignKeyConstraint baseTableName=events, constraintName=fk_event_deviceid, referencedTableName=devices; addColumn tableName=devices; createTable tableName=geofences; createTable tableName=user_geofence; addForeig...
     COMMENTS:
          TAG: NULL
    LIQUIBASE: 3.5.1
     CONTEXTS: NULL
       LABELS: NULL
DEPLOYMENT_ID: 9810476765
1 row in set (0.00 sec)

**Comment by tananaev** [comment]
Instead of `MARK_RAN`, it should be `EXECUTED`. It means you had `events` table in your database, so Traccar assumed that you've already updated your database schema.

**Comment by charlymanja** [comment]
Should I change the récord un the database and restart traccar or drop the table eventos and restart?

**Comment by tananaev** [comment]
Not sure. Did you manually create events table in your database?

**Comment by charlymanja** [comment]
Thx for the "light"! Let me see how can I fix it and I'll update to you

**Comment by charlymanja** [comment]
noup, nothing to do, I reinstall, delete the DATABASECHANGELOG record droping event table and nothing.

Can you provide me the MySQL DB Schema of 3.6 version?

**Comment by charlymanja** [comment]
I don´t create the events table manually, I think was created on upgrade to 3.6

**Comment by tananaev** [comment]
I don't have a schema. I just have the changelog files:

https://github.com/tananaev/traccar/tree/master/schema
