### ISSUE TITLE
Backup the 'conf/traccar.xml' while updating traccar

### ISSUE THREAD

**Issue by 4nonym0us** [traccar/traccar#2184]
Hello,

To start with I'd like to say that It's great that traccar is still being actively developed and new features are released all the time. Traccar is easy to use, simple, open-source and I really enjoy using it. Thank you, @tananaev!

I'd like to suggest you to check whether there are existing config files of traccar before replacing them with a new configs. The issue is simple: when people update traccar, they (most likely) want to save the old DB connection string and all of the other (filter, encoder, etc.) settings.
I understand that It's necessary to update config files because SQL queries are stored here and they need to be updated, but we can at least back up old configs so people can move their settings to a new config.
Also, I think that Java must have some sort of XML serializer, that would allow us to read the '<entry>' nodes and transfer them to a new config automatically.

**Comment by tananaev** [comment]
It's hard to achieve using current technologies, but I plan to change installer at some point and it would definitely help to improve upgrade process. In the meanwhile, you should backup any files that you changed manually before doing an upgrade.

Thanks for feedback.
