### ISSUE TITLE
Odometer not working with OpenGTS

### ISSUE THREAD

**Issue by himsashu** [traccar/traccar#2191]
Hi Tananaev
Really very special project for me. I really appreciate your hard work on this project.

I have integrated the OpenGTS with Traccar. I am using below configuration but I am getting wroing Odometer reading..

```
<entry key='database.insertPosition'>
    START TRANSACTION;
        SELECT @lastLatitude := lastValidLatitude, @lastLongitude := lastValidLongitude, @odometer := lastOdometerKM FROM Device WHERE imeiNumber = :device_id;
        SELECT @distance := ((ACOS(SIN(@lastLatitude * PI() / 180) * SIN(:latitude * PI() / 180) + COS(@lastLatitude * PI() / 180) * COS(:latitude * PI() / 180) * COS((@lastLongitude - :longitude) * PI() / 180)) * 180 / PI()) * 60 * 1.852) * 1000;
        UPDATE Device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastOdometerKM = @odometer + @distance, lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastUpdateTime = UNIX_TIMESTAMP(NOW()) WHERE imeiNumber = :device_id;
        SELECT @accountID := accountID, @deviceID := deviceID FROM Device WHERE imeiNumber = :device_id;
        INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, distanceKM, odometerKM, creationTime)
        VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:time), 0, :latitude, :longitude, :speed, :course, :altitude, '', @distance, @odometer + @distance, UNIX_TIMESTAMP(NOW()));
    COMMIT;
</entry>
```

The report is like below:

![image](https://cloud.githubusercontent.com/assets/6337704/17448589/bad1adb0-5b72-11e6-9b1e-34b0a3b31706.png)

You can see the second last column is odometer reading. It is random value.
Kindly help me.

**Comment by tananaev** [comment]
What you are calculating is a distance between reports, not accumulated odometer.

**Comment by himsashu** [comment]
I want accurate odometerKM in openGTS database. Means calculate the distance between last lat/long with current and add this value to last OdometerKM.

I want this to get the distance KM report in OpenGTS frontend.

**Comment by tananaev** [comment]
You can add value from previous report to the distance value in your SQL query.

Another option is to use `distance.enable` parameter in [the config file](https://www.traccar.org/configuration-file/).

**Comment by himsashu** [comment]
Hi Sir
I have gone through the link and there is option to enable in config file.
But I am not be able to understand after enable how to put distance
variable in <entry key='database.insertPosition'>

It would be great if you can provide me a sample file of traccar.xml after
enabling distance for OpenGTS database.
Thanks.

**Comment by tananaev** [comment]
Distance value is stored in the `:attributes` parameter in JSON format. I know latest versions of MySQL support JSON data and there must be a way to extract a value from there. For old versions of MySQL, you need to use [stored function to extract JSON](http://stackoverflow.com/a/31127857/2548565).
