### ISSUE TITLE
custom command

### ISSUE THREAD

**Issue by tectonny** [traccar/traccar#2196]
the custom command is to send command exactly as used in SMS?

**Comment by tananaev** [comment]
It depends on the protocol. You need to ask vendor for documentation for your device. For some protocols format for SMS and GPRS commands is different.

**Comment by perfectwebtech** [comment]
hello tananaev is there gt06n custome command works with opengts database ? or by api is it working now or only 2 command works till with api ? engine stop and engine start ?

**Comment by tananaev** [comment]
I don't think you can use commands API with OpenGTS. Custom command is available for all protocols.

**Comment by perfectwebtech** [comment]
but is there anything new ? we did try before but only works engine stop and engine start so i can use all command can work with gt06n with traccar ? how i can send custome command if works ?

**Comment by tananaev** [comment]
There is a special type of command where you can provide raw message to the device.

**Comment by perfectwebtech** [comment]
is there document or readme  ? for me so i can use it ?

**Comment by tananaev** [comment]
No, but you can look at the default web interface for code example.
