### ISSUE TITLE
Send Via Web

### ISSUE THREAD

**Issue by mm108** [traccar/traccar#2204]
hi, there's an option to send notification via web. What does that do and how should this be configured? Thanks

**Comment by m-menon** [comment]
And also one Notification for "device exceeds Speed". Should the speed be set in the traccar.xml and if yes then can you please give me the key name? Thanks a lot - M.M

**Comment by Abyss777** [comment]
Hello
1. "Send via Web" is coming up toasts in low right corner in web interface
2. If you are using 3.6, you need enable overspeed event handler and set speed limit in traccar.xml
````
    <entry key='event.overspeedHandler'>true</entry>
    <entry key='event.globalSpeedLimit'>90</entry>
````
It is in kilometers

**Comment by m-menon** [comment]
Cool....that's fantastic. Thanks a lot :+1:
