### ISSUE TITLE
Notification Email Log

### ISSUE THREAD

**Issue by mm108** [traccar/traccar#2220]
hi,

Is there any log to see if traccar attempted to send notification email? I am using the latest 3.6 version. As there is no way to test if the smtp / email settings are working. Is there any suggestion? 

I have tried setting every kind of notification but i just don't get any notification emails and my credentials are correct because i can telnet and send mail from the same machine. It's on Ubuntu 14 LTS and using STARTTLS on port 587

Thanks,
M.M

**Comment by tananaev** [comment]
I think you should get an error message if something has failed. @Abyss777, please confirm.

**Comment by Abyss777** [comment]
Yes, you will get a error in log if something has failed on the stage of mail sending. Also because send happen in asyncronious way you can get it after some period of time, some default timeouts are rather big.

I want to notice that you can lost mails on the next stage, and you have to set valid "from" to not miss such errors and get return mail.

Another thing can happen, for example I tried to send to "mail.ru" address via my corporate server  with same "from" field. Mail.ru denies such confusing situation, my corporate mail could not send neither mail nor return mail. And traccar will never know about this.

**Comment by m-menon** [comment]
oic....but from telnet on the same server, I used the same credentials (smtp host, username, password, starttls etc) and the email gets delivered. The same parameters in the traccar.xml file does not work. Does it log it in traccarserver log file when it tries to send the email? Thanks

**Comment by Abyss777** [comment]
No, it do not log every attempt, only errors.

**Comment by Abyss777** [comment]
Also have you got web notifications?

**Comment by m-menon** [comment]
Alright - so is there any way that I could manually trigger an email so that I could test it with different params? Thanks Web notifications are working fine and I can see them in the browser.

**Comment by Abyss777** [comment]
Unfortunately not, there is no "Test" button for email notification. 
Are you trying clean 3.6 version? There was some bugs, have you tried this build https://www.traccar.org/forums/topic/traccar-mail-notifications/#post-7449

**Comment by m-menon** [comment]
I just updated the jar file with the one mentioned in the link you gave. I can see the web notifications and now I will try changing my email parameters and see if it helps. Thanks

**Comment by m-menon** [comment]
I noticed something in the log file just now. Not related to the mail but not sure. Thought I should post

```
2016-08-16 12:32:41 DEBUG: [4CD7B335: 5023 < 192.168.255.37] HEX: 78780a13060604000200410f6d0d0a
2016-08-16 12:32:41 DEBUG: [4CD7B335: 5023 > 192.168.255.37] HEX: 787805130041abf50d0a
2016-08-16 12:32:41  WARN: NullPointerException (DefaultDataHandler:29 < BaseDataHandler:29 < ... < ExtendedObjectDecoder:60 < ...)
2016-08-16 12:32:41  WARN: [4CD7B335] error - NullPointerException (WebDataHandler:103 < *:140 < BaseDataHandler:29 < ... < ExtendedObjectDecoder:60 < ...)
2016-08-16 12:32:41  INFO: [4CD7B335] disconnected
2016-08-16 12:32:43 DEBUG: [E4999DDC: 5023 < 192.168.255.37] HEX: 78781f1210081014202ac700246e040b27a79d261419020d0007f0003305024473200d0a
```

**Comment by Abyss777** [comment]
Seems not related to mail notification, but curious...
It stars after replacing jar file or was before?

**Comment by m-menon** [comment]
could have been before. Let me see if I can locate any other place in the log that I see this

**Comment by m-menon** [comment]
I will open that issue in another post. Let me continue looking at the email issue. Will post updates in a few minutes. Thanks

**Comment by m-menon** [comment]
Okay I am now able to get the notification emails :+1:
