### ISSUE TITLE
Timezone detect by traccar suddenly wrong.

### ISSUE THREAD

**Issue by MRokas** [traccar/traccar#2226]
For past two weeks, traccar kept using UTC (instead of ST EEST), for some reason. I managed to hacky-way fix that, but that ain't the solution. (It worked fine for past year)

`date()` in terminal and `now()` in sql both returns good time(ST EEST), so problem is somewhere deeper(It might not be traccar-related however - I'm not sure). what would be best way around debugging it?

Edit: `date +%Z` returns EEST too. :/

**Comment by tananaev** [comment]
Are you using latest official release without any modification (including config)?

Please provide a fragment from log file with HEX, decoded data and state expected result.
