### ISSUE TITLE
The Traccar Server Installation Guide on a Linux VPS.

### ISSUE THREAD

**Issue by smsoousa** [traccar/traccar#2230]

**Comment by tectonny** [comment]
Search right here, there are already answers.
Basically it is to install java and run the installer traccar.

**Comment by tananaev** [comment]
Just download the installer and follow README instructions.

**Comment by smsoousa** [comment]
Okay, thank you friends, try to install. It is because I am innocent in this project so many doubts.

**Comment by tananaev** [comment]
https://www.traccar.org/install-digitalocean/
