### ISSUE TITLE
Allow multiple groups per device

### ISSUE THREAD

**Issue by ninioe** [traccar/traccar#2239]
Hi Anton,
I would like to work on the devices groups and improve it.
Today a device can only belong to one group, and if more than one account has access to view the device, each user account override the the device's group of the other account.
Also if one account change the device's group the other account can only see the group id and not the group name.

In addition, can we overcome the bugs of the ExtJS treeView and put it back in the devices panel for the groups? 
What was the bug and how do I reproduce it again? I would like to try and investigate this.

Thanks
Erez

**Comment by tananaev** [comment]
I think you should split the two tasks. Fixing device tree is one thing and changing how groups work is another. How exactly do you want to change groups? Allow multiple groups per device?

As for bug, there are problems with adding new items. It's very easy to reproduce. Just play with it for a bit and you'll notice the issues.

**Comment by ninioe** [comment]
Hi Anton,
Thanks for your replay, I will open a new task for this.
about your question, the answer is yes, I think we should allow multiple groups per device.

**Comment by tananaev** [comment]
Allowing multiple groups per device is a very big change. Are you sure you want to do it? I would list pros and cons first.

**Comment by ninioe** [comment]
It can wait...

**Comment by tananaev** [comment]
Closing as I don't think there's enough interest and it's very complicated to do.
