### ISSUE TITLE
Fixing device tree

### ISSUE THREAD

**Issue by ninioe** [traccar/traccar#2241]
There are problems with adding new items

**Comment by ninioe** [comment]
Hi Anton,
Can you help me restore the tree view to the state it was before it was removed?

Thanks
Erez

**Comment by ninioe** [comment]
Hi Anton,
can you tell me the exact point in time of the commit when you removed the last updated tree view?

**Comment by tananaev** [comment]
I reverted it in f5a96bb1547dcfbddf26c05143874195b4a50d0f, so you can take a previous commit.

**Comment by ninioe** [comment]
Hi Anton,
I checked the tree view with the separate class for tree store in [ff266d3](https://github.com/ninioe/traccar/commit/ff266d342ae3c6922005f043470ef659447882b5) (committed on Apr 7) and there where problems with adding new items.
But the earlier version [525d5b8](https://github.com/ninioe/traccar/commit/525d5b80d792e742e6d101ce85531294f5dc5300) Replace devices grid with tree view (committed on Mar 11) works fine

**Comment by tananaev** [comment]
One bug is that if you have an empty group, it doesn't work properly.

**Comment by tananaev** [comment]
Another one is that when you add one group to another, it doesn't update.

**Comment by tananaev** [comment]
Please do a thorough testing before you claim that it "works fine".
