### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by ns327** [traccar/traccar#2255]
Hi all,

Would it be possible to have a popup/separate window for the report page where you could select devices and the type of report, maybe including a map preview, then export them to a separate spreadsheet like xls (not csv) or html. 

Thanks

**Comment by tananaev** [comment]
All you are talking about will be available in the next release.

**Comment by condeitokako** [comment]
Hi 
you can include reports sos, would be helpful

**Comment by tananaev** [comment]
@condeitokako, what's "reports sos"?

**Comment by condeitokako** [comment]
Sorry alerts the sos tk103

**Comment by condeitokako** [comment]
the idea is to generate a report of the times that oppressed the SOS button , if no alarms or alerts are .

**Comment by tananaev** [comment]
There will be a report for alerts.

**Comment by condeitokako** [comment]
Perfect thank you very much for your prompt response.
