### ISSUE TITLE
problem with devicetime

### ISSUE THREAD

**Issue by and117** [traccar/traccar#2264]
I have a problem when the devicetime sometimes is wrong. Later then the servertime
When that happend its not possible to see the location in traccar manager or from a mobilephone.
I deleted the rows in the databas but the wrong time is still there.

I use server version 3.6 with a mysql database.

Anders

**Comment by tananaev** [comment]
I guess that's a problem with your device. Is it GT06 by any chance? You need to make sure your device reports UTC/GMT time.

**Comment by and117** [comment]
It is H02 protocol. The timezon is correct but sometimes the gps sends a date that is not correct. And when that hapends the date in the status field have problem with that.

How can i delete the future date in the state field? I haven't find that.

![image](https://cloud.githubusercontent.com/assets/21292362/18063392/0da4fbe4-6e2b-11e6-88a5-3dc3bc8b0df9.png)

**Comment by tananaev** [comment]
You need to manually remove the `positionId` from `devices` table and then restart the service.

**Comment by and117** [comment]
Thanks, now is it okey for this time :)

Is it possible to change so the device table use the latest positionId insteed of the positionID och the latest date?

**Comment by tananaev** [comment]
What do you mean by "possible"? It is possible to change the code to use position time, but at the moment there is no plan to implement it this way in the official version.

**Comment by and117** [comment]
Okey, thank you for your help.

**Comment by tananaev** [comment]
We have overrides for time now.
