### ISSUE TITLE
Regarding Gt06

### ISSUE THREAD

**Issue by abhit011** [traccar/traccar#2267]
Hello 

Just need some info, do we need to sendresponse to client for all the types for GT06 messages,e.g like 0x01 , 0x13 ,0x16, 0x26, 0x27 . What about others types ? Where as I see your code that it send response back to the client for all types. Please clarify that.

**Comment by tananaev** [comment]
Traccar server just sends response for all requests. I'm not sure if it's technically required, but it works.
