### ISSUE TITLE
forward data raw to manufacturer platform

### ISSUE THREAD

**Issue by opengrace** [traccar/traccar#2281]
Hi @tananaev,

I want to know, 
is it can traccar forward data original to main platform ..
i mean like this, GT06N --> Traccar-->Cootrack platform

is it possible ?

**Comment by tananaev** [comment]
Traccar can forward data in HTTP format. I don't know anything about Cootrack platform, so I don't know if it supports it.

**Comment by Heisenberg2980** [comment]
> Traccar can forward data in HTTP format. I don't know anything about Cootrack platform, so I don't know if it supports it.

How can Traccar be setup to forward the original raw message to another platform? I tried adding this to the config with no success:

```
    <entry key='database.saveOriginal'>true</entry>
    <entry key='forward.enable'>true</entry>
    <entry key='forward.url'>http://platformIP:PlatformPort?attributes={attributes}</entry>
```

**Comment by Heisenberg2980** [comment]
@tananaev I can see this issue is pretty old (2016) but I haven´t found an answer to this question anywhere, would you be able to help with this?

**Comment by tananaev** [comment]
For questions please use the forum.

**Comment by Heisenberg2980** [comment]
@tananaev I already searched in the forum and I couldn´t find this question answered (I saw many people asked about it in different threads but it was never properly answered), I just saw a comment from you mentioning this database.saveOriginal and that is what I tried (details in my previous comment) but you were not giving more details, and the documentation doesn´t explain it either, why don´t you explain it properly?

**Comment by Heisenberg2980** [comment]
Just in case anyone reaches this issue looking for an answer to the same question, I have analysed the messages Traccar sends when the forward option is setup and as @tananaev mentioned the format Traccar generates is html and not the original NMEA format sent by the tracker, so answering my own question regarding a smooth transition from other platforms to Traccar, unfortunately the answer is no, it is not possible to forward the raw data in the original format to the other platform to be able to use both platforms simultaneously during the transition.

**Comment by tananaev** [comment]
It's not HTML, it's an HTTP request. To clarify, you can forward the raw data along with decoded data. You can't forward the data stream as is.

**Comment by Heisenberg2980** [comment]
Thank you for finally answering the question after I had already answered it. Sorry for the sarcasm, but I hate when a simple question is asked multiple times and some people even knowing the answer refuse to give a proper response (specially considering how simple this response was).

Next step for me now is to create a simple TCP/IP socket server that is listening for messages, and forward them to both Traccar and the other platform to be able to use them both simultaneously.
