### ISSUE TITLE
SMS Commands?

### ISSUE THREAD

**Issue by jenellej** [traccar/traccar#2286]
Hi! First off great project!

Got Traccar working on a droplet in Digital Ocean. Now what I just want to know is (if our device can only receive commands via SMS), how can I setup Traccar to send SMS commands instead of sending them over the internet?

Thanks!

**Comment by tananaev** [comment]
Traccar doesn't support SMS commands at the moment.

**Comment by jenellej** [comment]
Does Traccar support sending commands via email? We worked around the same limitation on another system by sending commands via email to a monitored mailbox and having that machine send the actual sms commands

**Comment by tananaev** [comment]
No, it doesn't.

**Comment by tananaev** [comment]
Traccar has supported both SMS and network commands for a while now.
