### ISSUE TITLE
Sending Events Alerts, Geofencing to another APP

### ISSUE THREAD

**Issue by cetabio** [traccar/traccar#2299]
Hi im Integrating traccar with an php application ; Had sucefully get devices and position from raw database (Maybe will swap to api, but not sure if its better). But for Events that are generated on the traccar backed How can I send them to the php app.

My idea is create an api in the php app and add some code to traccar; that send the event to this api
after the normal store to DB. Would be the java side hard to implement? I think it would be a good feature since events are data thats its fired and notified usually so no sense to read DB api 24/7 for new event adds.

Any other idea or TIP I would appreciate it , as any guide to better place and way to implement.

Ty all , and ty Anton Tanaev for this good and cool project.

**Comment by Abyss777** [comment]
Hello,
Events forwarding is already implemented #2101 
I believe that it is what you need.

**Comment by cetabio** [comment]
Ty Abyss777, yehh its what I want to implement 

This is the configuration needed or there is something more?
   
```
 <!--<entry key='event.forward.enable'>true</entry>
 <entry key='event.forward.url'>http://localhost/</entry>
 <entry key='event.forward.header'>
  Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l
 </entry>-->
``
And just to confirm every alert is a event right? Oversped , motion , stop, geofencing.

**Comment by tananaev** [comment]
Yes, all alerts are events.

**Comment by Abyss777** [comment]
@cetabio Yes, it is only configuration needed, also `event.forward.header` is optional. It is made in case you want authorization or pass additional parameters to your app.

Here is list of currently implemented events https://github.com/tananaev/traccar/blob/master/src/org/traccar/model/Event.java#L38
Also you can retrieve this list via API `api/users/notifications?all=true`
