### ISSUE TITLE
How to use device Attribute

### ISSUE THREAD

**Issue by onethings** [traccar/traccar#2303]
Hi,
       New to using Traccar 3.7.  I change Adc1  to display as Fuel, but not success. Could you tell me correct way to display using with Attribute. Thanks.
![fuel](https://cloud.githubusercontent.com/assets/18694038/18410176/b5bccb46-7780-11e6-968e-6bceddac242d.png)

**Comment by tananaev** [comment]
Device attributes have nothing to do with position attributes.
