### ISSUE TITLE
device selection

### ISSUE THREAD

**Issue by akmal1999** [traccar/traccar#2305]
Hi,

which device works the best with traccar and which one does not need phone chip meaning without data it should only work with gps satellites.

thanks

**Comment by tananaev** [comment]
There are no GPS trackers that work only with GPS satellites. You need a way to send data to the server.

**Comment by akmal1999** [comment]
hi,

so what device you suggest for trucks to intall to get gas engine and speed info am seeking a good gps if you know have given good results...?

**Comment by tananaev** [comment]
I can't recommend anything specific because I rarely deal with actual hardware.
