### ISSUE TITLE
How to connect etl tools or reporting tools to traccar database?

### ISSUE THREAD

**Issue by akmal1999** [traccar/traccar#2311]
How to connect etl tools or reporting tools to traccar database? and what are root user id and password

I am trying to connect some reporting tool to the traccar mysql database to pool some reporting..

**Comment by tananaev** [comment]
If you are using MySQL, you should know the username and password for your instance.

**Comment by akmal1999** [comment]
I am really sorry, when I installed the source code i downloaded I did not provide any source for database. Does the source code install the a DB what type of DB does it install? I am not sure about this part.. please help me.

**Comment by tananaev** [comment]
By default it uses embedded H2 database. If you want external access, I would recommend to [configure Traccar to use MySQL database](https://www.traccar.org/mysql/).

**Comment by akmal1999** [comment]
Hi

i have created the mysql db and added parameters in traccar.xml. however the mysql db still does not have any columns or data. how can i make sure the system uses mysql db?

**Comment by tananaev** [comment]
Have you restarted the service? Check logs to see if there are any errors there.

**Comment by akmal1999** [comment]
Yes! i stopped traccar made all changes and at the end started traccar.  i will check the logs today. thanks
