### ISSUE TITLE
Embedded public view

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar#2313]
There are some feature requests to allow embed map with devices in the other site.
I'm not sure if it should be implemented in current web interface, may be some other lightweight project.

But definitely something should be done on server side to allow public access. Special "public" user or tokens or something else.

**Comment by kirantpatil** [comment]
Now User can authorize using token, is it possible to get embeddable map with device/s in other site ?

**Comment by Abyss777** [comment]
No, it is not implemented yet.

**Comment by tananaev** [comment]
It is in plans though.

**Comment by kirantpatil** [comment]
Hi @Abyss777 and @tananaev , how are you planning to implement it ? Please provide the details and I am available for testing activity.

**Comment by Abyss777** [comment]
It will be very simplified page on pure js with openlayers map only, without dependencies from ExtJS.
That do a few requests to traccar API: server, session, devices, positions and listen for websocket updates.
It will show only current devices status via icon color and their positions on map.

It is how I see it.

**Comment by kirantpatil** [comment]
Thanks a lot.  Does it show geofencing as well ?
I am eager to test this feature. Any plans to start it soon ?

**Comment by kirantpatil** [comment]
Merry Christmas to all.

@tananaev any updates on the "Embedded public view" feature.

Is it available in the master branch for testing ?

**Comment by tananaev** [comment]
Yes, it is:

https://github.com/tananaev/traccar-web/tree/master/web/simple

**Comment by kirantpatil** [comment]
Sir, may I know how to test it ?

From where can I get the URL from the user account ?

**Comment by tananaev** [comment]
You have to put URL and token into the JavaScript file.

**Comment by kirantpatil** [comment]
Sir, I want a URL, so that I can share it to multiple people over the email or sms for tracking.

Please guide me, how to achieve it ?

**Comment by tananaev** [comment]
If you want Traccar to give you URL, it's not implemented yet.

**Comment by kirantpatil** [comment]
@tananaev, any idea/thought of how to implement it ?

**Comment by tananaev** [comment]
I haven't thought about it yes, but I guess we can have the token as URL parameter and user would just some button to get fully-formatted URL.

**Comment by kirantpatil** [comment]
Great and Thanks you. I will check now by manually assembling it (URL+TOKEN).

**Comment by kirantpatil** [comment]
The below format logins in to app.

http://xx.xxx.x.224:8082/?token=b4T8UpuGPKA7Qu3PskptokedweDiMsxNtc2

We need an api to get this URL.

How about making Devices and State sidebar in minimized state when we access from token ?

**Comment by tananaev** [comment]
We don't need any new API. You can get token from user account.

**Comment by kirantpatil** [comment]
You mean, get Token by using user API ?

**Comment by tananaev** [comment]
Yes. I'm not sure if we are talking about the same things here. You don't even need to call user API. You always have current user info.

**Comment by kirantpatil** [comment]
Yes, I am also confused here. Let me start using it and report for any issue.

**Comment by kirantpatil** [comment]
@tananaev, can we have a option to get the URL via email notification ?

**Comment by tananaev** [comment]
It's possible to implement. It might be a good idea, so that user doesn't need to login, but it also might be a security issue as token is a sensitive information.

**Comment by macano13** [comment]
> Yes, it is:
> 
> https://github.com/tananaev/traccar-web/tree/master/web/simple

In which field of the javascript  the url with token must be inserted ?
