### ISSUE TITLE
Cheap chinese tracker

### ISSUE THREAD

**Issue by DamienFlynn** [traccar/traccar#2314]
Hi I have set up an account on demo server, email damofly@yahoo.com. I have added a tracker and tried different ports suggested but no luck. The IMEI No is 352887072452430 can anyone help?
Thank you

**Comment by tananaev** [comment]
Correct port for your device is 5002. And you should be using 087072452430 as unique id.

**Comment by DamienFlynn** [comment]
When i type 81.153.162.139 into a browser i get a screen asking for account and password. When i type 1.22.139.50 i get a blank screen. Thanks

**Comment by tananaev** [comment]
Are you sure you have a public IP address? Check with your ISP if you are not sure.

**Comment by DamienFlynn** [comment]
OK I will do

**Comment by DamienFlynn** [comment]
Hi I have set up a static ip address 81.130.187.82. Do I need to check for firewall on the laptop and or router?

**Comment by tananaev** [comment]
Make sure server is running and then check port (e.g. 5001) here:

https://www.traccar.org/port-check/

**Comment by DamienFlynn** [comment]
Thanks I got the ports opened on the router and it all seems to work OK.
Thank you very much for you help.
Damien

**Comment by PA3VOS** [comment]
Hi tananaev,

I had an almost similar problem as described above. having my GT02A running on your demo server works OK with port 5002. Now I am trying to get it running on de Traccar Server installed on my Laptop.
I configured my router NAT as  below:

![image](https://cloud.githubusercontent.com/assets/22261716/18618467/b0292e5a-7de7-11e6-93ab-dd8ea45956b9.png)

I don't see my GT02A when I log in on my localhost :8082.
On my Samsung S4 I am running the Traccar Client. In the status overview I see continiously Location update. I double checked the settings in the client and everything seems OK ! Also double checked my GT02A settings and IP number and port number are OK! what is possibly going wrong?

greetz,
Fokko

**Comment by DamienFlynn** [comment]
Hi that IP address is not your public IP address. Type what is my IP into google and it will tell you your public IP. Note this IP address will change from time to time unless you ask your service provider for a static IP.

**Comment by PA3VOS** [comment]
Hi,
as you can see the IP 192.168.2.51 is the static IP address of my laptop. NOT my WAN IP. of coarse I configured the WAN IP address in my GT02A  and in the Traccar Client too.

**Comment by DamienFlynn** [comment]
Well try checking the port is open on you public IP address.

If not try disabling you firewall and try again.

I had to open the port on windows firewall.


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.0.85&pv=6.0&source=email_footer_2] On Sun, Sep 18, 2016 at 9:35pm, PA3VOS < notifications@github.com [notifications@github.com] > wrote:
Hi,
as you can see the IP 192.168.2.51 is the static IP address of my laptop. NOT my WAN IP. of coarse I configured the WAN IP address in my GT02A and in the Traccar Client too.

**Comment by PA3VOS** [comment]
I checked with the port checker on Traccar, and it says the port is open.
I enabled the port 8082 in my Windows firewall so this should be OK too.Or should I open port 5002 in Windows as well? does notmake sense to me...

**Comment by DamienFlynn** [comment]
Well if the port checker says it is open then that is OK.

Is there any thing in the log file to indicate any data coming through?


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.0.85&pv=6.0&source=email_footer_2] On Sun, Sep 18, 2016 at 9:48pm, PA3VOS < notifications@github.com [notifications@github.com] > wrote:
I checked with the port checker on Traccar, and it says the port is open.
I enabled the port 8082 in my Windows firewall so this should be OK too.Or should I open port 5002 in Windows as well? does notmake sense to me...

**Comment by DamienFlynn** [comment]
Have you checked port 5002 is open?

**Comment by PA3VOS** [comment]
Where can I find the log file?

and yes the port is open. See screen shot:

![image](https://cloud.githubusercontent.com/assets/22261716/18619200/c8761ff4-7df6-11e6-87f1-51c6a7e00590.png)

**Comment by tananaev** [comment]
You need to forward port 5002, not 8082.

**Comment by PA3VOS** [comment]
Probably you didn't notice that I forwarded port 5002 to the port of the local host which is 8082. I don't know why you think this is wrong.

**Comment by tananaev** [comment]
I noticed that and I'm saying that it is exactly what's wrong. You need to expose local port 5002, not 8082.

**Comment by tananaev** [comment]
Port 5002 (and other 5xxx ports) is for devices. Port 8082 is for web interface and NOT for devices.

**Comment by PA3VOS** [comment]
Ok. So in my case i should forward 5002 external to 5002 internal ?

**Comment by tananaev** [comment]
Yes, you should be using local port 5002 for this device.

**Comment by PA3VOS** [comment]
Thanks many times! It works now. I tried this setting before but it didn't work. I guess due to the port was not enabled in my Windows firewall.
