### ISSUE TITLE
calamp event report table

### ISSUE THREAD

**Issue by DjameleddineBourahla** [traccar/traccar#2318]
Hi ,
I'm sorry if I bother you, but I'm trying to implement a CalAmp LMU decoder.
So please  how to obtain the Event Report Table for calamp lmu messaging units.?
for example:
ignition(input 0) "on or off" it send "key event =11"....?

Thanks.

**Comment by tananaev** [comment]
Traccar already decodes event for CalAmp.

**Comment by DjameleddineBourahla** [comment]
yes,i know
but how does "calamp lmu" send them ?
where  can i  find the event code table (sorry, i m beginner in devlopment)

**Comment by tananaev** [comment]
I don't really know what table you are talking about. Do you mean the mapping between event codes and what they mean?

**Comment by DjameleddineBourahla** [comment]
yes

**Comment by tananaev** [comment]
You need to contact CalAmp. Unfortunately I'm not allowed to share any of their documentation.

**Comment by DjameleddineBourahla** [comment]
OK,Thanks for your time
