### ISSUE TITLE
Tracker sending coordinates 0.000000,0.000000

### ISSUE THREAD

**Issue by pixeye33** [traccar/traccar#2326]
Hello,

My tracker (with GT06 if thats relevant), sometimes send ONE position with 0.000000,0.000000 coordinates.

Could Traccar simply ignore that position ? there is nothing there but Ocean !

Or ignore jumps with a distance of more than X kilometers if position is 0.000000,0.000000 ? (that way people arround that area would not be affected by this change).

Thanks !

Bonus : a way to edit positions would be usefull too sometimes ?

**Comment by tananaev** [comment]
There is an option to filter zero coordinates. More info here:

https://www.traccar.org/configuration-file/

**Comment by pixeye33** [comment]
Oh, my bad.
Thanks !
