### ISSUE TITLE
VPS linux 64 x86 redhat

### ISSUE THREAD

**Issue by alidiaby** [traccar/traccar#2327]
Hi I am seting up traccar on a VPS server (bluehost) and the linux versionis 64 x86 version,I created a trackar subdomain and try to install inside. I have been able to uncompress but installation is not starting. Where i have to copy the file on the server, knowing that I already have a couple of website on the same server.

**Comment by tananaev** [comment]
You need to run installer. It doesn't matter where you put it. Then if you don't have a separate IP address for Traccar, you would have to configure virtual host in your web server and proxy it to Traccar.

**Comment by alidiaby** [comment]
ok, I am using bluehost and I dont fully understand what you mean. How do I proxy to traccar? by putting the Ip adress with  port 8082 to the end?
thank you for the help.

**Comment by tananaev** [comment]
You can find example of how to configure proxy here:

https://www.traccar.org/secure-connection/

**Comment by alidiaby** [comment]
thank you , I will try
