### ISSUE TITLE
How can i configure ssl for traccar web api ?

### ISSUE THREAD

**Issue by mrameezraja** [traccar/traccar#2330]
Hi,

Is it possible to configure ssl for traccar web api ? I am accessing api via custom frontend.

-Thanks

**Comment by tananaev** [comment]
Yes, it is possible. Here is an example using Apache proxy:

https://www.traccar.org/secure-connection/

**Comment by mrameezraja** [comment]
I have installed traccar on a windows server.

**Comment by tananaev** [comment]
Then you can use IIS proxy.

**Comment by mrameezraja** [comment]
@tananaev  thank you :)

**Comment by cesarruben** [comment]
Hi Rameez Raja please could you explain how to configure on windows iis proxy. I have tried 1000 ways  and without success. regards
