### ISSUE TITLE
indentify protocol GTE trax 

### ISSUE THREAD

**Issue by maxwellweb** [traccar/traccar#2332]
Hello, I need to identify the protocol of this device GTE trax s6

This is the protocol that gives me.

in hex

```
202006203e5250493136303931363138313534372d323630373737322d303537323433363033353430383431303930303030313030393131313330303030373739393336434231303b49443d313032373b234c4f473a304138373b2a37443c
```

decrypted:

```
 >RPI160916181547-2607772-057243603540841090000100911130000779936CB10;ID=1027;#LOG:0A87;*7D<
```

 
Thank you.

sorry for my bad English, I speak Spanish.

**Comment by tananaev** [comment]
It looks like TAIP protocol. Try port 5031.

**Comment by sistemasrefsa** [comment]
Hello, I have the same trax gte device, I tried port 5031 but it doesn't work, any solution? 
thank you

**Comment by tananaev** [comment]
For questions please use the forum.
