### ISSUE TITLE
communication to server from client.

### ISSUE THREAD

**Issue by akmal1999** [traccar/traccar#2336]
when i only configure to use gps network i can not see device moving in admin panel.  when i turn on data then i get feed back is the feedback use data ot text to communicate with server?

**Comment by akmal1999** [comment]
when i only configure to use gps network i can not see device moving in admin panel.  when i turn on data then i get feed back is the feedback use data ot text to communicate with server?

**Comment by tananaev** [comment]
Traccar Client uses Internet connection to communicate with server.

**Comment by akmal1999** [comment]
thanks
