### ISSUE TITLE
About Mysql Database cleaning in last 3.7 release

### ISSUE THREAD

**Issue by TecSeguridad** [traccar/traccar#2341]
Hello, Tananaev i want to answer if the bolded  forward commands can be used in last Traccar  3.7 release and can you tell me how should be applied.  I must stop service and add it to conf xml file, then start again? Im correct?. Thank you

**DELETE FROM positions WHERE time < DATE_ADD(NOW(), INTERVAL -3 MONTH);
UPDATE devices SET latestPosition_id = NULL WHERE latestPosition_id NOT IN (SELECT id FROM positions);**

**Comment by tananaev** [comment]
If you are using correct config for version 3.7, it already has similar query. You can use `database.positionsHistoryDays` config parameter to set number of days that you want to keep history for.

**Comment by TecSeguridad** [comment]
Can you tell me please how should i do this on 3.10 or 3.11 vesion. Im already try several ways and get sintaxis and other errors. 

PD: Im using Mysql database

**Comment by tananaev** [comment]
Something like this:
```sql
DELETE FROM positions WHERE serverTime < DATE_ADD(NOW(), INTERVAL -1 MONTH);
UPDATE devices SET positionId = NULL WHERE positionId NOT IN (SELECT id FROM positions);
```

**Comment by TecSeguridad** [comment]
i get

Fallo al ejecturar SQL : SQL DELETE FROM positions WHERE serverTime < DATE_ADD(NOW(), INTERVAL -1 MONTH); UPDATE devices SET positionId = NULL WHERE positionId NOT IN (SELECT id FROM positions); falló: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UPDATE devices SET positionId = NULL WHERE positionId NOT IN (SELECT id FROM pos' at line 1

**Comment by tananaev** [comment]
I guess whatever you use to execute queries doesn't support multi-queries, so you have to execute them one by one.

**Comment by TecSeguridad** [comment]
Ahhh you right. but how can do this automatically. In Cron maybe? Im using VPS with debian 7

**Comment by tananaev** [comment]
What about `positionsHistoryDays` parameter?
