### ISSUE TITLE
TK102 no work

### ISSUE THREAD

**Issue by onetechct** [traccar/traccar#2344]
Hi, I have buyed a TK102 and tried port 5006 but not show in the map.
The autotrack command is t030s***123456    The imei is 352887072105202
Can check in the log please ?

**Comment by tananaev** [comment]
Are you using demo server? If yes, which one?

**Comment by onetechct** [comment]
Yes main demo server No way to understand if is a port problem or wrong imei identification ? With the command sms show same imei of the label

**Comment by onetechct** [comment]
40.122.161.243

**Comment by tananaev** [comment]
I don't see any data from your device in the server logs.

**Comment by onetechct** [comment]
I changenged the sim card but still not show (( can you check again please ?352887072105202
Possible have different imei ?

**Comment by tananaev** [comment]
I think I can see your device now. It's using TK103 protocol, so correct port is 5002. Also, you have to use 087072105202 as the device id.

**Comment by onetechct** [comment]
Hello Anton,

thank you very much ))

I have registered in the demo2 server and now show position))

With your software Is possible to search histoy by mobile app ?


Regards





________________________________
Da: Anton Tananaev <notifications@github.com>
Inviato: martedì 20 settembre 2016 22.01
A: tananaev/traccar
Cc: onetechct; Author
Oggetto: Re: [tananaev/traccar] TK102 no work (#2344)


I think I can see your device now. It's using TK103 protocol, so correct port is 5002. Also, you have to use 087072105202 as the device id.

-

**Comment by tananaev** [comment]
Not yet. Reports are not supported in mobile apps at this point.

**Comment by onetechct** [comment]
I love your software!

Is simple and work very well...I miss only a player with pause a and speed...like a videoplayer

Tk-102 can send fix only if change position ? Battery go down very fast when stay in same position..

Is possible to use shock sensor and and send Gprs data only with moviment ?Or turn on it just with moviment ?

Thank you very much


Best regards


________________________________
Da: Anton Tananaev <notifications@github.com>
Inviato: mercoledì 21 settembre 2016 05.56
A: tananaev/traccar
Cc: onetechct; Author
Oggetto: Re: [tananaev/traccar] TK102 no work (#2344)


Not yet. Reports are not supported in mobile apps at this point.

-

**Comment by tananaev** [comment]
For you feature request vote here:

https://github.com/tananaev/traccar/issues/2308

As for device, I don't know if it's possible to configure it the way you want. You need to ask device vendor about it.
