### ISSUE TITLE
Web interface removed from the main repo

### ISSUE THREAD

**Issue by ninioe** [traccar/traccar#2345]
Hello Anton,
Why did you remove the web interface from the main repo?
What if I try to merge the latest changes from tananaev/master won't it delete my web interface too?

Regards
Erez

**Comment by tananaev** [comment]
It will. You would have to do web interface changes in `traccar-web` repository now.

The biggest reason is that extjs doesn't allow open source license exceptions anymore, so we can't use Apache license for web interface. We have to relicense into GPL, so I moved it into a separate repository with a new license.

**Comment by woodie2** [comment]
When did extjs change the license? They use GPL since a long time or?

Do I need to switch to the new license, when I use the old repo, where apacha licence was valid? Or must I switch to the new one?

**Comment by tananaev** [comment]
@woodie2, ExtJS was always GPL, but they had exceptions that allowed to use their framework with some other open source licenses (Apache in our case). Recently they discontinued the exceptions, so now we have to use GPL only.

I'm not a lawyer, so I don't really know whether you can use old source code under original license. I'm guessing you can, but it's better to seek professional legal advice on this. Or you can try to ask Sencha support.
