### ISSUE TITLE
How do you calculate the coordinates for sanav mu-201

### ISSUE THREAD

**Issue by anagas** [traccar/traccar#2346]
Hello,

how do you calculate the coordinates ddmm.mmmm to decimal degrees? 

Thats how i try it:

```
var val;
val = parseFloat(strValue);
var dd =  parseInt(val / 100);
var mmmm = (val % 100)/60;
var res = (dd+mmmm);
```

Sorry that i ask this but i need this for a project.

Thanks!

**Comment by tananaev** [comment]
In Traccar we use regular expression like `(\d+)(\d\d\.\d+)`. First part would be degrees and the second part would be minutes. Then you just divide minutes by 60 and add those together.
