### ISSUE TITLE
Need to understand Some thing

### ISSUE THREAD

**Issue by necromancersecret** [traccar/traccar#2350]
Hello 
I have few questions. Please help me understand that.
1. I need to understand how the data from devices gets parsed and stored in respective db. 
2. And where all the analysic is happening, e.g like over speeding, geofencing , ignition on/off etc.
3.  Is it happening at DB side or on this traccar server side only. And if its happening on traccar server side lets say if there are 1 million unique devices, is the server maintaining the recent most location and other details of all the devices  ? If yes please let me know where and what if the server gets started and at that time all the previous location will be null, how its handling that.

Neo

**Comment by tananaev** [comment]
1. What's the question? Please be more specific with your question.
2. In various handler classes. Mostly in events package.
3. Traccar side only. Yes, Traccar maintains last location and other relevant data. On start or re-start Traccar reads data from the database.

**Comment by necromancersecret** [comment]
Okie Anton

My question was like some references in the code that helps me understanding like once the data received, it gets parsed like e.g "handleUpstream' of ExtendedObjectDecoder , is parsing the data using decode API and then passing it to onMessageEvent. 

Neo

**Comment by tananaev** [comment]
If you want to understand how it works, I would recommend to read Netty guide:

http://netty.io/3.8/guide/

**Comment by necromancersecret** [comment]
Thanks Anton, let me read through it
