### ISSUE TITLE
Add GPS devices or Mobile devices dynamically in Traccar Server

### ISSUE THREAD

**Issue by RamRamesh** [traccar/traccar#2353]
Hi,

Pls guide me to add GPS devices or Mobile devices dynamically in Traccar Server. 

Thanking you,
Ramesh

**Comment by RamRamesh** [comment]
@trac

**Comment by tananaev** [comment]
Is the issue solved?

**Comment by RamRamesh** [comment]
No..pls  guide

**Comment by tananaev** [comment]
Why did you close the issue then?

As for the question, what exactly do you mean by dynamically adding devices?

**Comment by RamRamesh** [comment]
oh sorry i'm new here. I thought my request is still open. 
We can add devices in Traccar Server by using Add device tool. Its a manual process. We are creating one external java application to perform device addition dynamically in Traccar Server.

**Comment by tananaev** [comment]
You can use Traccar API:

https://www.traccar.org/traccar-api/
