### ISSUE TITLE
GV500

### ISSUE THREAD

**Issue by lobqv** [traccar/traccar#2359]
Hello
Thaks for thw wonderful job you have done!
I'm trying to configure a Quecklink GV500 item, but it really is a pain in my head by now.
I've installed Traccar server in my server and I can see other devices connected by Traccar client (phones). But I just can not connect the GV500.
First of all, there is practically no support here in Mexico for this device. I have to spend tree days for knowing that a special cable is required. I'm now able to connect and configure the device, but is just not possible to obtain any info in log files, like the device is not sending any info to Traccar.
My questions, if you are able to answer them, are:
- Do you know if Traccar software is able to manage GV500 devices?
- It is possible to send SMS to device and configure it,  but device is not answering any SMS for confirmation. Do you think that device is not been able to send any SMS/GPRS messages?
- As probably you know, GV500 is an OBD-II device. Do you know if I have to plug it into the car in order of receiving data to server? (device battery is fully charge and it i supposed it can connect to Traccar by this mode)
- I attach a screen shot of my GV500 configuration

I really really hope you could answer some info that brings new ideas
Thanks
![traccar-gv500](https://cloud.githubusercontent.com/assets/22354801/18730955/a947cd92-801e-11e6-937d-f196a5c9a3a1.png)

**Comment by tananaev** [comment]
> Do you know if Traccar software is able to manage GV500 devices?

Yes, I'm pretty sure that Traccar can work with this device.

> It is possible to send SMS to device and configure it, but device is not answering any SMS for confirmation. Do you think that device is not been able to send any SMS/GPRS messages?

I don't know. It can be a SIM card issue or device issue or something else.

> Do you know if I have to plug it into the car in order of receiving data to server?

I'm not sure, but if it has internal battery, there is a good chance that it would work without being connected to OBD.

**Comment by lobqv** [comment]
Hello Anton

Thanks for you answer


I'm able now to receive messages from GV500. I've added the device to traccar server, but can not see any track history. I got this kind of messages:

2016-09-26 14:28:58  WARN: Unknown device - +RESP:GTSTT,360100,864251020141408,,gv500,41,0,0.0,0,2291.3,-99.257087,19.555913,20160926192856,0334,0020,0085,65AC,00,20160926192857,0812 (200.68.129.196)
2016-09-26 14:29:00 DEBUG: [21AB5CD3: 5005 < 200.68.129.196] HEX: 2b524553503a47544652492c3336303130302c3836343235313032303134313430382c2c67763530302c2c31302c312c322c302e302c302c323239312e332c2d39392e3235373038372c31392e3535353931332c32303136303932363139323835392c303333342c303032302c303038352c363541432c30302c302e302c2c2c2c34322c3431303030302c2c2c2c32303136303932363139323930302c3038313324

2016-09-26 14:27:48  WARN: Unknown device - +RESP:GTSTC,360100,864251020141408,,gv500,,0,0.0,0,2291.3,-99.257087,19.555913,20160926192744,0334,0020,0085,65AC,00,20160926192745,0811 (200.68.129.196)
2016-09-26 14:28:58 DEBUG: [21AB5CD3: 5005 < 200.68.129.196] HEX: 2b52455


Is Traccar server able to manage them? shoud I need to configure something else?

Thanks a lot

________________________________

**Comment by tananaev** [comment]
You should use correct port for your device. Why did you change port from 5004 to 5005?

Also, please reply via GitHub so that messages can be properly formatted.

**Comment by lobqv** [comment]
Hello Anton
Thank you for your answer, it is working perfectly now.
I'm checking now other messages from the OBD system. I got info related to this, but I want to know if Traccar is able to save those messages.
Here some examples:
I got: 2b524553503a47544652492c3336303130302c3836343235313032303134313430382c335657475736414a30464d3233373332342c67763530302c2c31302c312c312c302e302c302c323235382e342c2d39392e3235363934382c31392e3535353830302c32303136303932393231343734332c303333342c303032302c303038342c363541432c30302c302e302c2c2c2c3130302c3431303030302c302c6e616e2c2c32303136303932393231343734332c3133424124
That means:
+RESP:GTFRI,360100,864251020141408,3VWGW6AJ0FM237324,gv500,,10,1,1,0.0,0,2258.4,-99.256948,19.555800,20160929214743,0334,0020,0084,65AC,00,0.0,,,,100,410000,0,nan,,20160929214743,13BA$
Info related to OBD car computer. Could you please tell me if I can save those messages to DB?
And finally, is it possible to send commands to the device by Traccar system?
Regards

**Comment by tananaev** [comment]
It doesn't have any OBD data as far as I can see.

**Comment by lobqv** [comment]
Do you mean the example message I sent to you?
It does: 3VWGW6AJ0FM237324 is the VIN data and the other parameters are keys from protocol.
Does Tracar is able to manage those messages and put them into DB?
Can I send back control messages via Traccar systems?
Thanks

**Comment by tananaev** [comment]
Yes, I'm talking about the message example that you provided. VIN is just an identifier, is there any other OBD data there? I see only regular GPS info which would work just fine with Traccar. Traccar support OBD data for Queclink protocol as well, but the message that you provided is not it.

You can send commands if that's what you mean by "control messages".

**Comment by lobqv** [comment]
Thanks again
That VIN data, among other, is provided by OBD message from device. I also have parameters there like Engine RPM, Vehicle Speed (both zero because car is stopped) and so on. 
Where does Traccar process the OBD data? (maybe device is not sending the correct format for it)
How can I send command to device?
Thanks

**Comment by tananaev** [comment]
As I said, Traccar supports OBD data.

You can send commands from web interface of via web API.

**Comment by lobqv** [comment]
Thanks for the info
Regards

**Comment by daipayan-matrix** [comment]
I have a query, I had installed the Driver in my laptop. Added the Server FTP path and allowed the port in the server. But problem is no file is generated in the provided FTP. Am tried to search a lot but no where I find any sort of files with GPS data.

Am using GL50X @Track Air Interface Protocol R3.00

Anyone please guide me!

**Comment by voordev** [comment]
Im in the same boat,
Are there some specific instruction pages in the help on how to flash and setup the GV500 for traccar?

I previously bought a traccar unit with a subscription from a company so there *endpoint* the location where the data is stored in, is on the gv500.

So I guess i Have to:

1) Flash the devise to default ?
2) Set endpoint to point to my traccar server instance

Any help regarding those 2 items would be highly appreciated. kind regards

**Comment by andamahenry** [comment]
> Thanks for the info
> Regards

hi,
would u please help send me a copy of the sms u used to configure the gv500 tracking device?
i am also trying to configure it through sms but it is not replying with any messages.
so, please help me solve this problem if u can

**Comment by AniruddhaVKulkarni** [comment]
Hello.
Can you please provide me with the Java Parser for GV500 ?
I am unable to figure out how it should be.
