### ISSUE TITLE
How to get device motion status in traccar 3.7?

### ISSUE THREAD

**Issue by mrameezraja** [traccar/traccar#2361]
Hi,

I am currently using 3.5 version and i have made some changes to source code locally. Now i want to upgrade to version 3.7 and there is no motion status properties/methods anymore in Device model. Where can i get that in code?

Any help would be highly appreciated.

-Thanks

**Comment by tananaev** [comment]
Motion is now reported as events.

**Comment by mrameezraja** [comment]
Which file handles events? BaseEventHandler.java or ManEventHandler?

**Comment by mrameezraja** [comment]
Figured it out. Thanks @tananaev .

**Comment by jannier** [comment]
How do I get the status of the device in version 3.7?

**Comment by tananaev** [comment]
Same way as before. It's available in the API.
