### ISSUE TITLE
Traccar X MySQL 

### ISSUE THREAD

**Issue by paraisotech** [traccar/traccar#2364]
I've tried to change the default database server, from H2 to MySQL, but when comment the H2 lines in traccar.xml and insert the MySQL ones, the daemon doesn't work anymore. 
I've created the database traccar in mysql databases collection before switching the databases...

**Comment by tananaev** [comment]
Check wrapper log file for errors.

**Comment by paraisotech** [comment]
Suddenly started to work. Thanks for the reply. 
P.S.: your Traccar project is amazing. I've developed last year a complete gps103 and xexum conversation server(Perl + PHP + MySQL), but your tracker x server layer is the best i've seen. Congratulations. I'll merge your project with mine as soon as i can. Congratulations again.
