### ISSUE TITLE
Report received ST-340 module (Suntech)

### ISSUE THREAD

**Issue by Turbovix** [traccar/traccar#2365]
@tananaev,  i ask you to check the report below the ST-340/240 module sends to the server, note that in the 15th row (100010) each string is a state of a teterminado module feature, except that the value is 1 (on) or 0 ( off).

Looking at the code SuntechProtocolDecoder.java file so that the code does not look for that line, and the information contained in it are extremely important to display the device poupap.
Currently this information (ignition on, engine locked, unlocked motor, alarm on, alarm off, battery voltage, battery removal Main) are not displayed

Report:

```
SA200STT;         Status report header
08XXXX;           Device ID
393;              Soft. Releaase Version
20160921;         Date GPS
23:51:48;         GPS Time
428,332;          CELL - Location COD
-20.417890;       Latitude
-040.337037;      Longitude
000,202;          Speed ​​in km / h
000.00;           Course in degree
6;                Number of satellites
1;                GPS Fixed
13394;            Traveled distance in meter.
12:36;            Voltage value of main power
**100010;         ignition, Input 1, Input 2, Input 3, Out 1, Out 2**
2;
0176;
004,462;
4.1;
1
```

**Comment by tananaev** [comment]
The problem with Suntech protocol is that there are multiple versions and all of them have different parameters.

**Comment by Turbovix** [comment]
@tananaev from what I know of Suntech modules specifically ST-215 models, 240 and 340 which are the most popular, both send the same data to the server. It would be possible for you to implement the missing in code using only the protocol which you made the base?, It will be easier to make any changes in relation to the model and need. The knowledge I have programming is minimal, the little I know is C ++ for Arduino.

**Comment by tananaev** [comment]
If you look at the [SuntechProtocolDecoderTest](https://github.com/tananaev/traccar/blob/master/test/org/traccar/protocol/SuntechProtocolDecoderTest.java), you'll see that not all messages match your description.

**Comment by Turbovix** [comment]
@tananaev now I understand what you mean about the model variety and diversity in the protocol. I noticed that there was ST-340 model then added, only it will be able to display the information on the device pop-up?

**Comment by Turbovix** [comment]
@tananaev now yes, thanks again!
now it worked all ...

**Comment by cadastro2005** [comment]
This device is fully supported in the traccar?

**Comment by tananaev** [comment]
It is supported, but not all of the additional parameters are decoded.

**Comment by cadastro2005** [comment]
@tananaev 
where I can see which parameters are being supported?

Thx

**Comment by cadastro2005** [comment]
Ignition, distance, lat, lng, speed are supported?

**Comment by tananaev** [comment]
In the [SuntechProtocolDecoder](https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/SuntechProtocolDecoder.java) class.

**Comment by Turbovix** [comment]
@cadastro2005  Do not forget to look at the file  [SuntechProtocolDecoderTest.java](https://github.com/tananaev/traccar/blob/master/test/org/traccar/protocol/SuntechProtocolDecoderTest.java) and verify that the data that your module sends to the server are discriminated iqualmente this file.

**Comment by elyfran** [comment]
@Turbovix ok and thanks for the support. what is your assessment of this device? It is working without any problems?

**Comment by Turbovix** [comment]
@elyfran, i work only with the ST-340 model, so I made the necessary changes to this model.

Running: locking and unlocking / on and off alarm

Information on the popup available: number of satellites, fixed GPS, battery voltage

unavailable information in popup: On Ignition / Off, alarm on / off and inputs 1, 2 and 3.
