### ISSUE TITLE
Windows XP - wrapper.exe not win32

### ISSUE THREAD

**Issue by Defactio** [traccar/traccar#2368]
I have Traccar server for a GT06N on my Windows 8 development pc - all works fine.
I have a Windows XP pc which I'd like to use as a permanently-on server.
Part-way through the Traccar install, it attempts to run 'wrapper.exe' in a command shell but fails with: 'wrapper.exe is not a win32 executable'.

I downloaded the latest Windows 32 bit traccar installation from \traccar.org.
I realise that this is Java related, and have re-installed Java on the XP pc.

Any ideas?

**Comment by tananaev** [comment]
I just downloaded and checked both installers and everything is correct. You must be trying wrong versions.

**Comment by Defactio** [comment]
Thanks for the response Tananaev,

Which version did you install - I installed 3.7 - 10 Sep?

**Comment by tananaev** [comment]
I installed version 3.7. No, I wasn't referring to Java.
