### ISSUE TITLE
How to handle, if old location data comes

### ISSUE THREAD

**Issue by necromancersecret** [traccar/traccar#2370]
Lets say i get location from a device like device time :
2016-09-26 09:50:01,
I update its distance travelled by querying its last location 
2016-09-26 09:52:01,
I update its distance travelled by querying its last location 
2016-09-26 09:54:01,
I update its distance travelled by querying its last location 
2016-09-26 09:56:01,
I update its distance travelled by querying its last location 

Now lets say device sends some old data , eg location at 2016-09-26 09:48:01 , now this case how its supposed to handle the distance travllled ?

**Comment by tananaev** [comment]
Old locations are ignored for distance calculation.

**Comment by necromancersecret** [comment]
Where its getting ignored ? I mean in code ?

**Comment by Abyss777** [comment]
The code is here https://github.com/tananaev/traccar/blob/master/src/org/traccar/DistanceHandler.java

But it is not obvious ignore, `DistanceHandler` calculates distance between current and last position.
If "current" will not became "last" (it is older then last) then next distance calculation will be between next "current" and the same "last".

**Comment by necromancersecret** [comment]
I seriously could not understood ? because in the DistanceHandler.java i could not see anything like that ?
Please comment

**Comment by tananaev** [comment]
Here is the actual check:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/database/DeviceManager.java#L202

**Comment by necromancersecret** [comment]
Lets say
Device Sends initial message
78781101012345867089101120000001000055AE0D0A

Server responds with ACK

Now Lets say at 15:28.53 Hrs I get Message 7878058A0001FC960D0A from device
now At 15:29.10 Hrs, i get Message 78780A1346060400020002B8F40D0A

`Now at 15:29.15 Hrs, I get Message which is OLD data 78782222100A19071C00C000000000000000001E143101944601190060890102010005DC850D0A78782222100A19071C03C000000000000000001B1445019446011900608901020100066A3D0D0A78782222100A19071C19C000000000000000001F1454019446011900608901020100075A7C0D0A78782222100A19071C2BC000000000000000000F1432019446011900608901020100085BE20D0A78782222100A19071C30C0000000000000000014142001944601190060890102010009BDE80D0A78782222100A19071D12C000000000000000001014140194460119006089010001000A42F40D0A

Now how its going to update ?

neo

**Comment by tananaev** [comment]
Traccar will store the old data. Can you be more specific with your question?

**Comment by necromancersecret** [comment]
See at 15:29 Hrs , I have got the **Status Message** and now in this case, will this be message be the current data of device or old , I am talking about Status Message 13?. E.g Message does not send any date so , we will set the date time of device to the current time , right ? And whats this fixtime ?

Now after 15:29 hrs, the device had sent the old location data message which it had buffered at its end and once it gets the NW , it sends all its pooled data to the server.
Now I am confused since if the Status Message corresponds to Current Time, but then we would be keeping its position to its getLastPostion

**Comment by tananaev** [comment]
Status message gets time and location from last known location. "Last" is determined by fix time.

**Comment by necromancersecret** [comment]
Lets say I have last location data for the deviceid 12345678910  at 15:00 hours at traccar server , and now after 15:00 hours the device is not getting the NW, now it will buffer all the captured data at its end. I mean what ever its supposed to send to server , if its not getting NW, it will pool data at its end. Now at 15:29 hours (Current time of server too), the device gets the NW and it starts creating the session with server again. Now I want to understand does the status message refers to the OLD Buffered data that device has captured or its always fresh data , I mean status message had occurred at 15:29 hours at device too?

**Comment by tananaev** [comment]
OK, so you last message has time 15:00. Now device reconnect to server and send one of the following:

1. New status message - it will get timestamp 15:00 because status message don't have their own timestamp
2. Old status message - it will get timestamp 15:00 for the same reason
3. New location message - it has its own timestamp, so it will become the new "latest" message
4. Old location message - it has its own timestamp, if it's less than 15:00, it will just go into the database. If it's later than 15:00, then it will become new "latest" message

I hope it's clear.

**Comment by necromancersecret** [comment]
If its a new status message, then don't you feel all the status related events are calculated at wrong time ?

**Comment by tananaev** [comment]
Possibly, but I don't see any better option.
