### ISSUE TITLE
Slowness in SQL server while running the listener

### ISSUE THREAD

**Issue by a7medma7moud** [traccar/traccar#2375]
I updated the listener configuration to make the listener running with SQL server , and it is run well and the device sent the date perfectly to the server but there are slowness at the SQL server  while retrieving the data and it is very very slow on executing more than one transaction at the same time whether the transaction was at the same database or any other database , and these transactions  may committed  successfully or rolled back and it often rolled back , and when the listener is stopped every thing run well.
So , what do you think which may causes this slowness.

Thanks,

**Comment by tananaev** [comment]
I guess there is some problem with SQL server configuration, or it just lacks resources to process data quickly.

**Comment by a7medma7moud** [comment]
I don't think that there are any problem with the configuration because SQL server run well since more than  3 years and it works well and this problem occurred only when I run the listener , and also the machine uses Windows server 2012 as OS , 16 GB RAM , CORE i5 , SQL server 2012,
So what are the  additional configurations that I have to set or modify ?

Thanks,

**Comment by tananaev** [comment]
You need to consult with a DBA about your database performance.

As for screenshot, it looks like you don't have a JDBC driver.

**Comment by a7medma7moud** [comment]
But I already have it , If I don't have a JDBC driver , Is it possible that the traccar listener receive the messages normally  and store them in database ?

**Comment by tananaev** [comment]
Not in the MSSQL database. It won't be able to store them there if there is no driver.

**Comment by a7medma7moud** [comment]
That's mean that JDBC driver works well with me , and I don't have any problem with it.

**Comment by tananaev** [comment]
That error indicates that Traccar can't find the database driver.

**Comment by a7medma7moud** [comment]
How can I fix some thing like this , and may this error is to be responsible for this slowness ?
