### ISSUE TITLE
Error in Traccar installation script for Linux(Ubuntu 16.04).

### ISSUE THREAD

**Issue by Turbovix** [traccar/traccar#2376]
There is an error in Traccar installation script for Linux(Ubuntu 16.04).

> INFO: error on creating script link /etc/init.d/rc5.d/S20Traccar
> Sep 27, 2016 11:47:22 AM org.rzo.yajsw.os.posix.PosixService install
> INFO: error on creating script link /etc/init.d/rc5.d/K20Traccar

The correct is:

> creating script link /etc/rc5.d/S20Traccar
> creating script link /etc/rc5.d/K20Traccar

**Comment by Turbovix** [comment]
@tananaev content that would be created in the file above is the same /etc/init.d/Traccar file?

**Comment by tananaev** [comment]
What version of Traccar are you talking about?

**Comment by Turbovix** [comment]
The latest, 3.7!
But the system works, I was only intrigued the error appears at installation time.
I noticed that at dawn the sitema for work and have to do a restart, would have something relationship?

**Comment by tananaev** [comment]
You don't really need to restart the system, you can just start the service manually.

Version 3.7 doesn't use YAJSW, so I don't think you are using official version.

**Comment by Turbovix** [comment]
I did not understand your answer.
The version I use the official repository linked to Netbeans Traccar.
Having made the customizations I compile and then I am packing utiliando the script (package.sh)

**Comment by tananaev** [comment]
Please next time be very clear that you are not using official release. Master branch is very far from version 3.7. It's not guaranteed to be stable and if you decided to use it, you have to be prepared to deal with potential issues.

If you want a stable version, you should branch from one of the release tags.

Any feedback on master branch is appreciated, but you need to make it clear that it's a build from master branch.

As for the problem, when did you make the build? I think service name should be lower case now.

**Comment by Turbovix** [comment]
@tananaev, i really was not clear, and had no knowledge of the information.
In private messenger directory (rc5.d) is contained in the directory (/ etc /) and not (/etc/init.d/)

**Comment by tananaev** [comment]
Maybe YAJSW has to be changed to support newer versions of Ubuntu.
