### ISSUE TITLE
Problem GPS CCTR800

### ISSUE THREAD

**Issue by evigra** [traccar/traccar#2378]
Hello tana ...
Again.
I have a gps, CCTR-800 model in 5040 port.
not recorded positions.

can you help me?

```
2016-09-27 17:58:33 DEBUG: [D05C051A: 5040 < 200.68.139.17] HEX: 2a48512c313530303036303630312c56312c3137353833322c412c313930362e323532302c4e2c313$
2016-09-27 17:58:34 DEBUG: [D05C051A: 5040 < 200.68.139.17] HEX: 2a48512c313530303036303630312c4c494e4b2c3137353833332c32322c31322c3130302c302c302$
2016-09-27 17:58:35 DEBUG: [D05C051A: 5040 < 200.68.139.17] HEX: 2a48512c313530303036303630312c56312c3137353833342c412c313930362e323532302c4e2c313$
```

hex to acii

```
*HQ,1500060601,V1,175832,A,1906.2520,N,1
*HQ,1500060601,LINK,175833,22,12,100,0,0
*HQ,1500060601,V1,175834,A,1906.2520,N,1
```

**Comment by tananaev** [comment]
It's H02 protocol, port 5013.

**Comment by evigra** [comment]
Thanks Tananaev

Change the port to 5013
>2016-09-28 04:01:43 DEBUG: [D3BAFA76: 5013 < 187.216.136.33] HEX: 2a48512c313530303036303630312c4c494e4b2c3034303134312c31312c31312c38352c302c302c$
>2016-09-28 04:03:42 DEBUG: [D3BAFA76: 5013 < 187.216.136.33] HEX: 2a48512c313530303036303630312c4c494e4b2c3034303334312c31312c31302c38352c302c302c$
>2016-09-28 04:05:42 DEBUG: [D3BAFA76: 5013 < 187.216.136.33] HEX: 2a48512c313530303036303630312c4c494e4b2c3034303534312c31302c31302c38342c302c302c$
>2016-09-28 04:05:45  INFO: [58332361] connected
>2016-09-28 04:07:42 DEBUG: [D3BAFA76: 5013 < 187.216.136.33] HEX: 2a48512c313530303036303630312c4c494e4b2c3034303734312c31312c31312c38352c302c302c$
>2016-09-28 04:07:53  INFO: [7225637E] connected


HEX to ASCII
>*HQ,1500060601,LINK,040141,11,11,85,0,0,
>*HQ,1500060601,LINK,040341,11,10,85,0,0,
>*HQ,1500060601,LINK,040541,10,10,84,0,0,
>*HQ,1500060601,LINK,040741,11,11,85,0,0,

**Comment by tananaev** [comment]
Your device doesn't seem to send any GPS data.

PS please use code blocks instead of quotes for logs and other data formatting

**Comment by evigra** [comment]
Thank you very much. 
The change indicated, worked correctly
