### ISSUE TITLE
Can help solve the HikariPool problem?

### ISSUE THREAD

**Issue by gpsim** [traccar/traccar#2384]
Hello!
 Can help solve this problem?
 Is the problem of code or the third party HikariCP?

WARN: HikariPool-1 - Connection is not available, request timed out after 30000ms

**Comment by tananaev** [comment]
It's not a problem with code, it's a problem with database connection.

**Comment by gpsim** [comment]
I will restore the tracker-server and pom.xml to the previous version， without such a mistake,
So confused.

**Comment by RaNd250** [comment]
Same problem here with  4.2 ...
Any sugestions ?
CentOS Linux release 7.5.1804 (Core)
5.5.60-MariaDB
