### ISSUE TITLE
Auto erase old positions

### ISSUE THREAD

**Issue by leontino** [traccar/traccar#2391]
Hi everyone

I put this in my config file

```
<entry key='database.positionsHistoryDays'>90</entry>
```

It's correct to erase positions with more 90 days?

How I do ?

**Comment by tananaev** [comment]
As long as you don't have those extra spaces, it looks correct.

**Comment by JohnnyDevine** [comment]
I think this might delete geozone info also?

JD

**Comment by tananaev** [comment]
What do you mean by geozone info? Currently it removes only positions.

**Comment by JohnnyDevine** [comment]
I entered that line into my config file set to 1 day for testing, and a geozone area I had set previous dissapeared

**Comment by tananaev** [comment]
It definitely doesn't remove geozones, so your issue has nothing to do with this parameter.

**Comment by JohnnyDevine** [comment]
OK I will look into it further.......
