### ISSUE TITLE
Feature Request : Horizontal scalling (Multiple Servers)

### ISSUE THREAD

**Issue by jaimzj** [traccar/traccar#2393]
Dear All,

If a user wants to add multiple instances of Traccar, yet have a single web-interface and user login.

Maybe gradually adapting the database to handle these would be a good idea,? Whats your thoughts?

I was thinking,
1. A configurable parameter that says, its a single instance or a cluster of servers.

Based on that, by putting a check on username creation, and ensuring usernames to be unique in the cluster of servers, with a login module that checks for the user, and the server it is associated with and start the  users session with the relevant server/db.

Or would this be a wrong approach? I have a custom web-front end, where I have done this.

**Comment by Abyss777** [comment]
Hello

What problems does user want to solve with such configuration (one web-interface, multiple traccars)? 

Anyway all traccar instances can access same `users` table with help of DB e.g. federated tables http://dev.mysql.com/doc/refman/5.7/en/federated-create-connection.html

And I agree, external login is good feature. It will be useful for example for ldap or other non-sql mechanisms.

**Comment by tananaev** [comment]
I think I actually understand what @jaimzj mean. Currently Traccar can handle maybe 100k devices or maybe more on a single server, but if we want a million of devices, we should be able to create a cluster. I've been thinking about it as well.

**Comment by jaimzj** [comment]
@tananaev Exactly thats what I meant, because in my case I use VPS which can handle upto 7000 devices, after that I keep adding more and more VPS Instances (Rather than investing into huge hardware or cloud servers), this can help certain users keep the cost low etc.

**Comment by Abyss777** [comment]
What are disadvantages of multiple traccar instances used one DB cluster? (except internal traccar cache of course)

**Comment by tananaev** [comment]
My idea was that each instance would have its own database, so each server would server only a subset of users.

**Comment by Abyss777** [comment]
@tananaev It works out of the box, isn't it?
What will be common then in such cluster?

**Comment by tananaev** [comment]
Same web address. For example, we have 4 demo servers. It would be nice to have single address http://demo.traccar.org and it will automatically connect to correct back-end behind the scenes, depending on the logged-in user.

**Comment by Abyss777** [comment]
There is Apache mod_proxy_balancer https://httpd.apache.org/docs/2.4/mod/mod_proxy_balancer.html that can respect `JSESSIONID` the only thing rest is get cookie from correct server.

**Comment by tananaev** [comment]
The biggest problem is that we need to balance both HTTP requests from users and data from GPS devices.

**Comment by Abyss777** [comment]
I think it is possible only with splitting traccar on two essence: 
- the network server, that handles connections, decode messages and put them in pipeline
- the rest server that extracts messages from pipeline and do all other things

**Comment by kirantpatil** [comment]
@jaimzj, Can you please provide the details of your configuration and VPS details to handle 3000 devices ?

What is the frequency of data you receive from device ?

How did you do VPS sizing ?

Thanks,
Kiran.

**Comment by jaimzj** [comment]
@kirantpatil  vpsdime.com. 32GB premium vps plan,  frequency of update being 5 seconds.

**Comment by kirantpatil** [comment]
@jaimzj, thanks a lot.

**Comment by jaimzj** [comment]
I would love to revive this as a feature request again.

Hoping some others might be interested in up-voting this request.

**Comment by tsmgeek** [comment]
For a cluster to work I guess you could do a few things but ultimately would split traccar into separate parts. Its a complicated task without knowing how much each part of the system loads up. I would guess that all the protocol decoding/notifications etc is the slowest part, DB fairly minor.

1. ingestion, push data packet from tracker to say a Redis queue or ZMQ etc (you could have lots of these, balanced though say Haproxy if needed or just multiple hostnames to each endpoint)
2. decoding, pull packet from queue, process and push to DB and update state management as needed
3. state management, storing any shared state information across all servers all messages to go back to WS would be pushed to all redis servers via the PUB/SUB methods
4. frontend API handler
5. frontend WS handler, accesses PUB/SUB queues on Redis as needed, does not matter which one they are connected to as all receive the data

**Comment by tananaev** [comment]
Remember that we need two-way communication with devices, so just balancing incoming data is not enough.

**Comment by jon-stumpf** [comment]
I would like the ability to have multiple traccar instances (no web) manage a subset of devices, posting data into a single, replicated database.  These instances would also store device state in the database and other in-memory information.  Other multiple traccar instances (no device management) would handle web requests.

The database would be the sole mechanism for data exchange.  No in-memory cache.

**Comment by parthibd** [comment]
Any updates on this ?

**Comment by techsolic** [comment]
Any update

**Comment by iceberg1369** [comment]
It seems like the developer has started implementing this recently. But I think it wont be availble any time soon

**Comment by swaydevs** [comment]
> It seems like the developer has started implementing this recently. But I think it wont be availble any time soon

Updates and information are available in the following issue. 

#4803 

and forum post : [Forum Post](https://www.traccar.org/forums/topic/distributed-cache-for-scaling-feature-development/)

**Comment by tananaev** [comment]
Closing in favor of https://github.com/traccar/traccar/issues/4803. We are very close to supporting horizontal scaling. If anyone wants to contribute, please let me know.
