### ISSUE TITLE
Understanding the Positions table on traccar db

### ISSUE THREAD

**Issue by jpambulo** [traccar/traccar#2394]
I have few questions regarding the values saved  on the POSITIONS table.
1. What does the 'valid' column supposed to contain?
2. I am receiving the following attribute values from h02 protocol:

```
{"power":6,
"ignition":false,
"status":3221224447,
"ip":"121.54.44.176",
"distance":0.0,
"totalDistance":1236.72
}
```

here I want to know how the attribute 'status' can be interpreted also the relationship between the distance and totalDistance columns. It appears the distance column always have a value of 0 while the totalDistance varies from time to time.

**Comment by tananaev** [comment]
1. Valid column indicates if location data is current and accurate.
2. You can find status definition in [the protocol documentation](https://www.traccar.org/protocols/)

**Comment by jpambulo** [comment]
thanks for clearing the valid column.

For the status attribute, I am still perflexed. I assume that the value 3221224447 is a decimal representation. Its correspondign HEX value is BFFFFBFF matching the format on the LKGPS protocol vehicle_status#. Converting it further to its binary value, it returns 
10111111 11111111 11111011 11111111 
Does 1 means the alarm was triggered or settings are ON?

**Comment by tananaev** [comment]
Yes, it's a decimal representation of the status field.

All the documentation that I have about this protocol is on the page that I provided. I don't have any other information.

**Comment by jpambulo** [comment]
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Anton Tananaev <notifications@github.com> Date: 10/4/16  4:45 AM  (GMT+08:00) To: tananaev/traccar <traccar@noreply.github.com> Cc: jpambulo <jpambulo@gmail.com>, Author <author@noreply.github.com> Subject: Re: [tananaev/traccar] Understanding the Positions table on traccar db (#2394) 
Yes, it's a decimal representation of the status field.

All the documentation that I have about this protocol is on the page that I provided. I don't have any other information.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tananaev/traccar","title":"tananaev/traccar","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tananaev/traccar"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tananaev in #2394: Yes, it's a decimal representation of the status field.\r\n\r\nAll the documentation that I have about this protocol is on the page that I provided. I don't have any other information."}],"action":{"name":"View Issue","url":"https://github.com/tananaev/traccar/issues/2394#issuecomment-251221525"}}}
