### ISSUE TITLE
OpenGTS traccar Integration

### ISSUE THREAD

**Issue by dsolissilva** [traccar/traccar#2404]
Dear, I've been trying to integrate OpenGTS without result, I would like your help. thank you very much.

```
    <!-- SERVER CONFIG -->

    <entry key='web.enable'>false</entry>
    <entry key='web.port'>80</entry>
    <entry key='web.path'>C:\Program Files (x86)\Traccar\web</entry>

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>C:\Program Files (x86)\Traccar\logs\tracker-server.log</entry>

    <!-- DATABASE CONFIG -->

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://localhost:3306/gts?allowMultiQueries=true</entry>
    <entry key='database.user'>root</entry>
    <entry key='database.password'>PassWord</entry>

    <entry key='database.selectDevicesAll'>
        SELECT CONCAT('1', imeiNumber) AS id, imeiNumber AS uniqueId FROM Device WHERE imeiNumber REGEXP '^[0-9]+$';
    </entry>

    <entry key='database.insertPosition'>
        START TRANSACTION;
            UPDATE Device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = UNIX_TIMESTAMP(:fixTime), lastUpdateTime = UNIX_TIMESTAMP(NOW()) WHERE imeiNumber = SUBSTRING(CAST(:deviceId AS CHAR(32)), 2);
            SELECT @accountID := accountID, @deviceID := deviceID FROM Device WHERE imeiNumber = SUBSTRING(CAST(:deviceId AS CHAR(32)), 2);
            INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, creationTime, address)
            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:fixTime), 0, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', UNIX_TIMESTAMP(NOW()), :address);
        COMMIT;
    </entry>

    <!-- PROTOCOL CONFIG -->

    <entry key='gps103.port'>5001</entry>
    <entry key='tk103.port'>5002</entry>
    <entry key='teltonika.port'>5027</entry>


</properties>
```

Traccar log

```
2016-10-05 00:30:01  WARN: Unknown device - 868683021XXXXXX (186.9.131.1)
2016-10-05 00:30:19 DEBUG: [C2FD394F: 5001 < 186.9.131.1] HEX: 38XXXXX638XXXXXXX323XXXXXXXXb
2016-10-05 00:30:19 DEBUG: [C2FD394F: 5001 > 186.9.131.1] HEX: 4f4e
```

I'm using version 3.5 (traccar) and version 2.6.3 (OpenGTS) in Windows 2008 Server

**Comment by tananaev** [comment]
The problem seems to be that your device is not registered in the OpenGTS database:
```
Unknown device - 868683021XXXXXX
```

**Comment by dsolissilva** [comment]
I have registered on the website
![captura](https://cloud.githubusercontent.com/assets/16345932/19095164/ac3f364c-8a6a-11e6-85f6-ca71ecb8eb2f.PNG)

**Comment by tananaev** [comment]
Run following query in the database:
```
SELECT CONCAT('1', imeiNumber) AS id, imeiNumber AS uniqueId FROM Device WHERE imeiNumber REGEXP '^[0-9]+$';
```

... and check if your device is there.

**Comment by dsolissilva** [comment]
> 0 row(s) returned


What I can do?

**Comment by dsolissilva** [comment]
When I check the 'Device' table, if they leave my devices

> 01:11:14 SELECT deviceID FROM `gts`.`device` LIMIT 0, 1000	6 row(s) returned	0.000 sec / 0.000 sec

**Comment by tananaev** [comment]
Make sure `imeiNumber` is set for your device.

**Comment by dsolissilva** [comment]
now I get this.
> 2016-10-05 03:06:44  INFO: Query not provided: database.updateDeviceStatus
2016-10-05 03:06:44  WARN: [B5162584] error - NullPointerException (ConnectionManager:115 < BaseProtocolDecoder:104 < ExtendedObjectDecoder:60 < ...)
2016-10-05 03:06:44  INFO: [B5162584] disconnected
2016-10-05 03:06:44  INFO: Query not provided: database.updateDeviceStatus
2016-10-05 03:06:44  WARN: [B5162584] error - NullPointerException (ConnectionManager:115 < *:71 < MainEventHandler:73 < ... < ExtendedObjectDecoder:53 < ...)
2016-10-05 03:06:45  INFO: [33DD4AFC] connected

**Comment by tananaev** [comment]
Looks like you are not running official version of Traccar.

**Comment by dsolissilva** [comment]
traccar reinstalling. I'll tell you how it goes. Thank you so much for your work and excuse my English translation by google.

**Comment by dsolissilva** [comment]
After reinstalling I worked perfectly with traccar 3.7! Thank you very much for your help.
