### ISSUE TITLE
Feature Request : Timed Geozones

### ISSUE THREAD

**Issue by JohnnyDevine** [traccar/traccar#2410]
It would be nice to be able to have Geozones active only at certain times of the day or night i.e. overnight leaving a zone......

Thanks

JD

**Comment by tananaev** [comment]
I have heard this request before, so we might consider implementing it soon.

**Comment by JohnnyDevine** [comment]
Excellent.......

**Comment by JohnnyDevine** [comment]
any idea time wise on the next release ? Would you like me to beta ?

**Comment by tananaev** [comment]
If everything goes as planned, next release will be ready in a couple of weeks time.

**Comment by Abyss777** [comment]
@tananaev 
Where we will store start and end time? In attributes or will extend model?

**Comment by tananaev** [comment]
I guess time should be it attributes for geozone permission. So that we can specify time per device. Another thing, we should probably consider something like [RRULE](http://www.kanzaki.com/docs/ical/rrule.html), so that we can enable repeating time, not just one-time.

**Comment by tananaev** [comment]
I believe we already support this with calendars.
