### ISSUE TITLE
Tramigo T23 landmark data

### ISSUE THREAD

**Issue by gpproton** [traccar/traccar#2412]
Hi Anton

Tramigo T23 devices have an internal landmark for specific location, it'll be very useful if the landmark information can be accessed. This is the hex and report sample below.

1.24 km SE of Kachia Road-Kaduna Refinery Road, Kaduna City, Kaduna, NG

```
80002117b00098000101deb7037733762088f5575472616d69676f3a205061726b65642c20312e3234206b6d205345206f66204b616368696120526f61642d4b6164756e6120526566696e65727920526f61642c204b6164756e6120436974792c204b6164756e612c204e472c2031302e34333635382c20372e35303435312c20536c6565702c2032333a3538204f637420352020454f46
```

**Comment by tananaev** [comment]
Do you have protocol documentation with full format description? I won't be able to parse all the data reported by the device.

**Comment by gpproton** [comment]
I have the protocol document but i don't completely understand the contents, it attached to this comment.
[T23_GPRSS_GPRS_Specification_ENG_v0.94.pdf](https://github.com/tananaev/traccar/files/512688/T23_GPRSS_GPRS_Specification_ENG_v0.94.pdf)

**Comment by tananaev** [comment]
I have this document as well, but unfortunately here is all it says about format:
> 5.7.2 Payload example
> The body of the GPRS message.
> Tramigo: Parked, 0.12 km E of McDonald's H.V. dela Costa, Makati, 11:07 Mar 27

**Comment by gpproton** [comment]
Ok but do you think something can still be done.

**Comment by tananaev** [comment]
Something can be done if someone can tell me all the possible formats for the data.

**Comment by gpproton** [comment]
Anton i'll get in touch with the company, to see if i can get any other documentation for you.
