### ISSUE TITLE
Gisgraphy Geolocalisation service

### ISSUE THREAD

**Issue by gpproton** [traccar/traccar#2416]
Hi Anton

I would like to know if it currently possible to use Gisgraphy Geo-localisation service to get nearest location or landmark to trackers on tracker, i just made a new setup of Gisgraphy and i'm looking to use it as most places out of the cities in my country are not properly mapped.

**Comment by tananaev** [comment]
Please be more specific. Provide some coordinates, what Gisgraphy returns, and what's expected.
