### ISSUE TITLE
Error valid position or coordinates

### ISSUE THREAD

**Issue by lluistaa** [traccar/traccar#2418]
Hello,
I have a problem with latitude and longitude. I'm using traccar 3.7 and MySQL. The problem is that in some cases saved incorrect values. I have activated the filter.invalid but ... does not consider it invalid than 180 or -180 for length and 90 or -90 for latitude? I saved superior values ​​that give false positions.

**Comment by tananaev** [comment]
Please provide some examples of what you are talking about.

**Comment by lluistaa** [comment]
values ​​are stored as -270.60823333333333 that is out of range of the GPS system. Usually it occurs after a downtime. Surely it is a device error when it starts again, but should not be filtered as an error?

Thank you

**Comment by tananaev** [comment]
What protocol are you using? Is it H02 by any chance?

**Comment by lluistaa** [comment]
Yes H02

**Comment by tananaev** [comment]
Please read this thread:

https://www.traccar.org/forums/topic/traccar-3-7-odd-position-issue/

**Comment by lluistaa** [comment]
I will try the proposed solution. When this happened also saved the date as 00: 00: 000 I solved not saving the date of device. With this solution I can think back to save the date correctly.

Thank you very much!

**Comment by lluistaa** [comment]
Hello,
I want to upgrade to version 3.8 My question is if in this version the problem is solved. Thank you very much

**Comment by tananaev** [comment]
Yes, it is solved.

**Comment by lluistaa** [comment]
OK! Thank you very much
