### ISSUE TITLE
Question about requirements

### ISSUE THREAD

**Issue by Raffamondo** [traccar/traccar#2421]
Hello, i would like to use traccar for a project. I looked into the database and i am asking myself if the server  is able to receive positions also if the device is not registered. 

Which tables need to be filled to acquire in "positions" table? just devices? groups? 

Thank you
Raffaello

**Comment by tananaev** [comment]
In the next version there will be an option to automatically register unknown devices (https://github.com/tananaev/traccar/pull/2349).

**Comment by Raffamondo** [comment]
HEllo, thank you that would be a great feature!
