### ISSUE TITLE
Problem with Device mapping when Geo Data received by Traccar Server

### ISSUE THREAD

**Issue by aripaka** [traccar/traccar#2431]
Hi,

I am facing the following problem while sending Geo positions data from device or OsmAndProtocol.

**Case 1.** 
Device not registered with Traccar Server, sending Geo Lat Lon data 
Result : 400 Bad Request, because device unknown
_**Summary : Valid Result as expected**_

**Case 2.**
Device registered with Traccar Server, sending Geo Lat Lon data
Result : Empty 
_**Summary : Valid Result as expected**_

**Case 3.**
Device not registered with Traccar Server, sending Geo Lat Lon data
Result : Empty
_**Summary : Invalid Result not expected**_

Here in Case 3. the Geo Lat Lan data is mapped with previously device in Case 2 and updated this will happen to all unknown device received by the server until it again gets valid registered device.

I have fixed this from My end. I advice it is a very serious error in case if Server receives Geo Data from any unregistered device.

Regards.
Aripaka V

**Comment by tananaev** [comment]
It works as intended. Traccar has internal cache that's synced with database every 5 minutes by default.

**Comment by Abyss777** [comment]
May be it is connected with #2372

**Comment by aripaka** [comment]
That's absolutely correct the issue is related to that 

Now all my positions are mapped to different device id which is creating problem in tracking devices

Is there is any fix related to this Issue

**Comment by tananaev** [comment]
I have implemented a solution for #2372.
