### ISSUE TITLE
Help with API to update

### ISSUE THREAD

**Issue by marchantm** [traccar/traccar#2433]
Do you have a example how be updated some data using the API? Please your help

**Comment by tananaev** [comment]
You can look at the web interface or Traccar Manager apps for API examples.

**Comment by marchantm** [comment]
Thanks but there is not a clear example of how to use UPDATE with SWAGGER API. 
Somone in this forum has an example in PHP? 
Im using Guzzle to interact with Laravel. By example this is how i add a Geofence:
$client = new Client([
            'base_uri' => 'http://www.mytraccarserver.cl:8082/api/',
            'timeout'  => 2.0,
]);

$response = $client->request('POST', 'geofences', ['json' => ['name' => $input["name"], 'area' => $input["area"]],'auth' => ['username', 'pass']]);

**Comment by tananaev** [comment]
Update is the same as create except you have to use `PUT` verb instead of `POST`.
