### ISSUE TITLE
Server is Running 

### ISSUE THREAD

**Issue by itnaaga** [traccar/traccar#2435]
My server is running but it won't shows the UI , it only shows the   ../traccar-web/web on the web page 
how can we load UI

**Comment by tananaev** [comment]
I'm guessing that you are trying to run from source code. You need to checkout `traccar-web` repository first, and then configure path to the `web` folder in the config file.

**Comment by itnaaga** [comment]
Yes,sir i am running from source.how to change configfile

**Comment by tananaev** [comment]
It's just a regular text file. You pass it as an argument.
