### ISSUE TITLE
Uncaught Error: You're trying to decode an invalid JSON String

### ISSUE THREAD

**Issue by nikhilnayak98** [traccar/traccar#2441]
ext-all.js:22 Uncaught Error: You're trying to decode an invalid JSON String

![image](https://cloud.githubusercontent.com/assets/16633884/19408606/4e1a0efc-92df-11e6-9655-d59c0d02415b.png)

**Comment by w32gold** [comment]
Have you tried using:
localhost:8082 only?

**Comment by nikhilnayak98** [comment]
@w32gold  for all the ports

**Comment by tananaev** [comment]
Why do you have a "web" subfolder. It seems like your config is incorrect.

**Comment by samuelrojasp** [comment]
have the same issue on traccar 4.3
