### ISSUE TITLE
Can't open Traccar web page

### ISSUE THREAD

**Issue by paraisotech** [traccar/traccar#2443]
I've installed NetBeans 8 and cloned the github project. When i run the project in NetBeans, everything seems to be correct, but when i open the address http://localhost:8082/ i get only the message "../traccar-web/web" in Chrome Tab...
Can anyone help me???

**Comment by tananaev** [comment]
You need to clone "traccar-web" repository as well. Also, on Windows symbolic links don't work, so you would have to configure path to the web interface there.

**Comment by paraisotech** [comment]
Thanks for your reply! I'll try to improve some coban and xexun alerts and make my sms sender server with traccar notifications.

**Comment by paraisotech** [comment]
Before of all, i'm sorry for asking again. Maybe it is obvious for who is an expert with NetBeans and Java development. I clonned the "traccar-web" repository, but i don't know what to do after that. I'm sure that if i can run the project here at my notebook, i'll be able to do all changes i want to do, although i don't have that big experience in netbeans + java, i'm kind of autodidact and it is a matter of time for me to familiarize myself with it. 
My old tracker plataform mainly uses Xexun and Coban trackers, but your traccar server although is the best one i've seen, it is missing some alerts and other features that i've implemented in my old one.

**Comment by tananaev** [comment]
[Symbolic links](https://en.wikipedia.org/wiki/Symbolic_link) have nothing to do with Java or programming. You need to change path to the web interface in your config file.
