### ISSUE TITLE
How to update version 2.12 to latest (3.7) without manually change?

### ISSUE THREAD

**Issue by sdip025** [traccar/traccar#2449]
I am using  version 2.12. In this version i am getting problem about features. So i wants to update from version 2.12 to 3.7. Please tell me the easiest process to change.

**Comment by tananaev** [comment]
You need to update to version 3.0, then to 3.3, then to the latest.

https://www.traccar.org/update-from-2-x-to-3-0/

**Comment by sdip025** [comment]
Thank You .
