### ISSUE TITLE
Traccar 3.7 and OpenGTS Integration for linux

### ISSUE THREAD

**Issue by FanerK** [traccar/traccar#2452]
Hello Anton;

I just installed traccar 3.7 and i want to integrate it with openGTS 2.6.0 , i tried to fellow the step by step guide to do it. We can be given steps to install the CentOS 6.

**Comment by tananaev** [comment]
I'm assuming that you have set up OpenGTS already.

First you need to install Traccar. [Download](https://www.traccar.org/download/) installation package and follow ready instructions there.

Then follow instructions here:

https://www.traccar.org/opengts/

**Comment by FanerK** [comment]
I don't have set up OpenGTS, How do I install opengts for linux? 
Can give steps in the install, thanks

**Comment by tananaev** [comment]
You should check OpenGTS project website for information on how to install it.

**Comment by FanerK** [comment]
I've installed Opengts, how to upgrade from 2.12  to traccar 3.7 which already exists. Thank you

**Comment by tananaev** [comment]
You can search for update instructions on the website and GitHub.

**Comment by FanerK** [comment]
What is link instruction on website or github?

**Comment by tananaev** [comment]
Here is the most important one:

https://www.traccar.org/update-from-2-x-to-3-0/
