### ISSUE TITLE
GT06N CAN'T SEND Data  IN C#

### ISSUE THREAD

**Issue by mnbgh** [traccar/traccar#2453]
Issue Regard gt06n device in c#

i got only login packet and Heartbeat Packet from device.

This is my responce to device  after get login packet

``` c#
byte[] msg2 = new byte[] { 0x78, 0x78, 0x05, 0x01, 0x00, 0x02, 0xEB, 0x47, 0x0D, 0x0A };
client.Send(msg2, msg2.Length, SocketFlags.None);
```

This is my responce to device  after get Heartbeat Packet

``` c#
byte[] msghb = new byte[] { 0x78, 0x78, 0x05, 0x13, 0x00, 0x02, 0xD9, 0xDC, 0x0D, 0x0A };  client.Send(msghb, msghb.Length, SocketFlags.None);
```

**Comment by tananaev** [comment]
Response include index on the original message, so you can't just hardcode it. Check [Gt06ProtocolDecoder class](https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gt06ProtocolDecoder.java) for more details.

**Comment by mnbloch** [comment]
I connected 2 device to server get data from only one device and got error
10060 : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to
 respond

**Comment by tananaev** [comment]
Why would server try to establish connection with device? You are clearly doing something wrong. Server only listens to incoming connections.
