### ISSUE TITLE
Traccar Server Version 3.7  database issue in mysql.

### ISSUE THREAD

**Issue by sdip025** [traccar/traccar#2469]
Step1- Download And  installed Traccar server version 3.7 from https://www.traccar.org/download/.
Step2-Configure Mysql database from https://www.traccar.org/mysql/.
 When i wants to run from local in my Local computer(Windows7) in URL localhost:8082.
It's can't run.
How to solve this?
wrapper.log file error 

```
| 2016/10/21 14:45:47 | SEVERE 10/21/16 2:45 PM: liquibase: C:/Program Files (x86)/Traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Change Set changelog-3.7::changelog-3.7::author failed.  Error: Can't create table `traccar`.`#sql-a30_d` (errno: 121 "Duplicate key on write or update") [Failed SQL: ALTER TABLE traccar.devices ADD CONSTRAINT fk_device_group_groupid FOREIGN KEY (groupid) REFERENCES traccar.groups (id) ON UPDATE RESTRICT ON DELETE SET NULL]
INFO   | jvm 1    | 2016/10/21 14:45:48 | INFO 10/21/16 2:45 PM: liquibase: changelog-3.7::changelog-3.7::author: Successfully released change log lock
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error: liquibase.exception.MigrationFailedException: Migration failed for change set changelog-3.7::changelog-3.7::author:
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:      Reason: liquibase.exception.DatabaseException: Can't create table `traccar`.`#sql-a30_d` (errno: 121 "Duplicate key on write or update") [Failed SQL: ALTER TABLE traccar.devices ADD CONSTRAINT fk_device_group_groupid FOREIGN KEY (groupid) REFERENCES traccar.groups (id) ON UPDATE RESTRICT ON DELETE SET NULL]
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.changelog.ChangeSet.execute(ChangeSet.java:605)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.Liquibase.update(Liquibase.java:214)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.Liquibase.update(Liquibase.java:192)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.Liquibase.update(Liquibase.java:188)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:141)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at org.traccar.database.DataManager.<init>(DataManager.java:67)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at org.traccar.Context.init(Context.java:150)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error: Caused by: liquibase.exception.DatabaseException: Can't create table `traccar`.`#sql-a30_d` (errno: 121 "Duplicate key on write or update") [Failed SQL: ALTER TABLE traccar.devices ADD CONSTRAINT fk_device_group_groupid FOREIGN KEY (groupid) REFERENCES traccar.groups (id) ON UPDATE RESTRICT ON DELETE SET NULL]
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1273)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1255)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.changelog.ChangeSet.execute(ChangeSet.java:568)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   ... 15 more
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error: Caused by: java.sql.SQLException: Can't create table `traccar`.`#sql-a30_d` (errno: 121 "Duplicate key on write or update")
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:299)
INFO   | jvm 1    | 2016/10/21 14:45:48 | WrapperSimpleApp Error:   ... 20 more
STATUS | wrapper  | 2016/10/21 14:45:50 | <-- Wrapper Stopped
```

**Comment by tananaev** [comment]
It looks like there is some problem with group ids.

**Comment by sdip025** [comment]
How to solve this?Please Help me for What i needs to do to solve this?

**Comment by tananaev** [comment]
I don't know what exactly the problem is. You have to look manually in the database and find it out. Possibly group ids are not unique or something like that.

**Comment by sdip025** [comment]
I solved this problem.
How to free this port?


But next error is

wrapper.log
"
Error: Encountered an error running main:
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: org.jboss.netty.channel.ChannelException: Failed to bind to: 0.0.0.0/0.0.0.0:5004
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.bootstrap.ConnectionlessBootstrap.bind(ConnectionlessBootstrap.java:204)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.traccar.TrackerServer.start(TrackerServer.java:138)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.traccar.ServerManager.start(ServerManager.java:73)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:38)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: Caused by: java.net.BindException: Address already in use: bind
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at sun.nio.ch.Net.bind0(Native Method)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at sun.nio.ch.Net.bind(Unknown Source)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at sun.nio.ch.DatagramChannelImpl.bind(Unknown Source)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at sun.nio.ch.DatagramSocketAdaptor.bind(Unknown Source)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.socket.nio.NioDatagramPipelineSink.bind(NioDatagramPipelineSink.java:129)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.socket.nio.NioDatagramPipelineSink.eventSunk(NioDatagramPipelineSink.java:77)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.SimpleChannelHandler.bindRequested(SimpleChannelHandler.java:299)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:265)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.handler.logging.LoggingHandler.handleDownstream(LoggingHandler.java:338)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.SimpleChannelHandler.bindRequested(SimpleChannelHandler.java:299)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:265)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.Channels.bind(Channels.java:561)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.AbstractChannel.bind(AbstractChannel.java:197)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	at org.jboss.netty.bootstrap.ConnectionlessBootstrap.bind(ConnectionlessBootstrap.java:198)
INFO   | jvm 1    | 2016/10/21 17:40:55 | WrapperSimpleApp Error: 	... 9 more
STATUS | wrapper  | 2016/10/21 17:40:58 | <-- Wrapper Stopped"

**Comment by tananaev** [comment]
You need to find the process that uses that port. Or you can change port in Traccar config.

**Comment by m-menon** [comment]
Are you running any DVR or video streaming server on your machine? If yes then that could be the suspect.

**Comment by waca98** [comment]
> I solved this problem.

@sdip025 
How did you make it work with mysql please ?

**Comment by sdip025** [comment]
@waca98   .I had previous version database.After delete and create database
,It's is working properly.5004 port is used by OS.You have to stop it from
your PC for live data transfer.
