### ISSUE TITLE
Requested Enhancement

### ISSUE THREAD

**Issue by ilevans** [traccar/traccar#2471]
Hi Anton

I have only just upgraded to V3.7 and I am loving the features that you have added.   :+1:  :smile:

In particular I like the Trip Report and would like to suggest an enhancement. 

Could you enhance the report please so that when a Trip detail line is selected in the report, the route is displayed on the map.

cheers

Ian Evans

**Comment by tananaev** [comment]
What you are asking for is already implemented and will be available in the next release.

**Comment by ilevans** [comment]
Brilliant, thank you.
cheers 
Ian
