### ISSUE TITLE
Only listening data from device and save data in my own mysql database

### ISSUE THREAD

**Issue by kaziArif123** [traccar/traccar#2476]
Hello,
First of all thanks for your effort.
I am using T1 device for tracking. Due to some additional requirements I can't use your web portal that's why  I want to use traccar for listening data from device and save those data in my own designed mysql database. Please help me out.

**Comment by tananaev** [comment]
It's very easy. Here is an example of writing data into OpenGTS database:

https://www.traccar.org/opengts/

You need something similar.

**Comment by kaziArif123** [comment]
Thanks for reply. 
I am trying. If I face any issue I hope I will get your help.
