### ISSUE TITLE
h02 Protocol issue

### ISSUE THREAD

**Issue by arrafa20** [traccar/traccar#2482]
Hi Anton,

i bought a device called tk-909, it is kind of understanding through the port 5013, but it is not working properly.

I am receiving 3 Hez codes (first one have he location)

```
HEX: 2a48512c393130363134333138382c4e42522c3136303132382c3731322c332c302c312c323030362c31323934332c32312c3234313031362c46464646464246462c36232a48512c393130363134333138382c5631392c3136303132372c562c303935372e383632342c4e2c30383430372e313231352c572c3030302e30302c3030302c3234313031362c2c38393932303134372c383935303630333031363830393938313433393f2c464646464642464623

HEX: 24910614318816013824101609578620060840712104000000fffffbffff000b000000000002c8030000000081

HEX: 2a48512c393130363134333138382c4e42522c3136303134382c3731322c332c302c352c323030362c31323934332c32302c323030362c31323934312c32372c323030362c31323934322c32352c323030362c31303231332c31382c323030362c31303138332c31372c3234313031362c46464646464246462c3623
```

But in the server i can see the picture attached
![untitled](https://cloud.githubusercontent.com/assets/22230961/19654249/caf948e2-99d4-11e6-973d-8b4649d1f3cf.png)

Could be this something different in the protocol? the devices says it have valid GPS signal

**Comment by tananaev** [comment]
Please read following thread:

https://www.traccar.org/forums/topic/traccar-3-7-odd-position-issue/
