### ISSUE TITLE
How to Send command to device gt06n in c#

### ISSUE THREAD

**Issue by mnbgh** [traccar/traccar#2485]
How to Send command from server  to terminal in  gt06n device using  c#

**Comment by tananaev** [comment]
Web API documentation is in swagger, so you can generate code for it:

https://github.com/swagger-api/swagger-codegen

**Comment by mnbloch** [comment]
Enable to find Web API documentation Please help.

**Comment by tananaev** [comment]
Not sure where you searched, but it's on the official website:

https://www.traccar.org/traccar-api/

**Comment by necromancersecret** [comment]
Lets say 
Device Sends initial message 
78781101012345867089101120000001000055AE0D0A

Server responds with ACK

Now Lets say at 15:28.53 Hrs I get Message 7878058A0001FC960D0A from device
now At 15:29.10 Hrs, i get Message 78780A1346060400020002B8F40D0A

`Now at 15:29.15 Hrs, I get Message which is OLD data 78782222100A19071C00C000000000000000001E143101944601190060890102010005DC850D0A78782222100A19071C03C000000000000000001B1445019446011900608901020100066A3D0D0A78782222100A19071C19C000000000000000001F1454019446011900608901020100075A7C0D0A78782222100A19071C2BC000000000000000000F1432019446011900608901020100085BE20D0A78782222100A19071C30C0000000000000000014142001944601190060890102010009BDE80D0A78782222100A19071D12C000000000000000001014140194460119006089010001000A42F40D0A

Now how its going to update ?

neo

**Comment by tananaev** [comment]
@necromancersecret, how is it related to the topic?
