### ISSUE TITLE
Installation Windows 10

### ISSUE THREAD

**Issue by paulocffs** [traccar/traccar#2494]
Okay tananaev, did the installation in Windows 10 and managed to open on localhost: 8082 which would be the next step in this windows installation and need to install a database yes or no. Recalling that since I directed my public IP but I see the port 80 is closed.

**Comment by tananaev** [comment]
Traccar comes with embedded database which should be enough for testing, but for any production use I would recommend a fully featured database engine. For example, MySQL.

Traccar uses port 8082 by default. If you want it to work on port 80, change number in the config.

**Comment by paulocffs** [comment]
tananavae thanks for the reply and the tip for the MySQL achieve, communication on port 80.
