### ISSUE TITLE
Feature: delayed commands 

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar#2497]
There are some devices that do not keep tcp connection. Send data and close it.
Other devices can be configured to wake up rather rarely (once a hour/day/week).
Sometime it is really hard to catch when device is online.
We can implement some kind of delayed commands.

I see it like:
- Accept commands even if device is offline
- If device is offline place command to some per-device-queue
- As soon as device becomes online try to send all commands from queue to it.

There are some possible problems that also should be solved: interface to flush queues, command expiration and may be others.

Or we should not spent time to such solution and direct our efforts to fallback on sms commands...

@tananaev what do you think?

**Comment by tananaev** [comment]
It's a very useful feature. I know quite a few users implemented similar functionality themselves.

Not sure about SMS commands. Technically SMS commands can be more useful, but require some gateway to send messages. Probably mobile phone can be used for that.

**Comment by Abyss777** [comment]
I have not found any open-source android application for remote SMS sending.
We can consider some open-source SMS gateway and implement its support.
Like https://playsms.org/ or https://www.rapidsms.org/

Anyway, I think it's worth to implement internal delayed commands, we can re-use part of its infrastructure to sens SMS in future.

**Comment by Abyss777** [comment]
The first one covers only part of users, that installed traccar on real hardware. But big part use VPS/VDS and can not install modem/connect phone to server.

Also, some devices accept SMS only from approved numbers, they won't work with services which do not send CallerID or send dinamic CallerID

**Comment by jaimzj** [comment]
@Abyss777  Yes both of it is true you are right.

But some providers, do allow sending SMS from VNM (Virtual numbers) so maybe we can make provision for web-services based SMS sending option. this way if the user has an option to have Virtual Number, he can keep that number as approved number and utilize this feature.

The same is possible with SMPP protocol as well. (But like you said, not all providers or region support) dynamic or numeric valid numbers.

**Comment by Abyss777** [comment]
Another problem with web-services is they really Zoo. I studied a few push-services API to implement push notification. It is really impossible cover all. One use POST, other GET, one accept authorization in request, other in header, one use JSON, other XML and so on. Wrapper will be really complicated.

**Comment by jaimzj** [comment]
Then, All I can think of is implementation of SMPP Protocol for SMS.

- All SMS Aggregators Providers.
- All Telecom Service Providers.
- And All Medium to Large SMS Providers do provide SMPP accounts and access.

---

SMPP can also have virtual numbers assigned to the account.
SMPP is the Standard protocol used by telco's to interconnect their SMSC's and does not change. (The methods)
Implementing SMPP Client in Traccar could not just help in sending, but also reciving SMS's.

**Comment by tananaev** [comment]
I think SMPP is the best option. It would also be nice to find or implement a mobile app that would act like SMPP server.

**Comment by Abyss777** [comment]
I've found one https://play.google.com/store/apps/details?id=com.ozeki.androidsmppsmsgatewayfull
There is also free version https://play.google.com/store/apps/details?id=com.ozeki.androidsmppsmsgatewaylite

**Comment by tananaev** [comment]
Nice, so there is already an existing solution.

**Comment by jaimzj** [comment]
If there is a ever a need for SMPP accounts, for testing, Please do let me know I can try to get a LIVE SMPP accounts for testing purposes. (In the country you would want to test it for). from my current SMS Provider who does have international routes.

**Comment by Abyss777** [comment]
@tananaev how do you feel, what is the ratio of protocols where:
- GPRS and SMS commands are the same

and

- GPRS and SMS commands are different

I mean which are more?

**Comment by tananaev** [comment]
I don't have much insight into SMS commands, but I think most of the time they are different. Or often SMS commands are wrapped into a packet with some special header and ending to be transmitted over GPRS.

**Comment by Abyss777** [comment]
The next question is, how do you think, should SMS commands be some kind extension of protocol encoders and be like fallback transport or they will be something totally different?

Also may be... some day... we will implement SMS decoders to some protocols.

**Comment by tananaev** [comment]
I guess they can be separate encoders.

Decoders can also be separate from GPRS versions.

But everything can still be based about Netty framework.

**Comment by Abyss777** [comment]
I'm not sure if we can put SMS (received by other library) to Netty queue.  But it if we can it would be great.

**Comment by tananaev** [comment]
If we use SNMP protocol for SMS, we can use Netty for it. That was my idea.

**Comment by Abyss777** [comment]
Hello, @jaimzj 
Is your offer about testing accounts still up to date? 
If yes, it would be great to get account for Russia. My mail is in profile or project readme.

**Comment by jaimzj** [comment]
Hello @Abyss777 

Yes I can provide you the accounts, but I might need a day or two, as I am currently travelling (around 19th february i can email you with the details is that okay?)

**Comment by Abyss777** [comment]
@jaimzj Sure, it is OK.

**Comment by Abyss777** [comment]
Want to come back to queued/delayed protocol commands because of a few reasons...

- We have SMS, but it costs money, It is really necessary only in a few cases like: configure server IP or do something urgently. In many other cases it would OK to wait when device comes online and send command.
- I remember you discussed somewhere commands to Traccar Client and send them in HTTP response. I think to implement this we anyway need some mechanism to temporary store commands until osmand client connected to put commands in response. We would use the same queue mechanism.

**Comment by tananaev** [comment]
Sure. It's one of the frequently requested features.

**Comment by Abyss777** [comment]
I believe `fallbackToText` flag is meaningless when queues are implemented. If it is enabled command never be queued. What do you think?

**Comment by tananaev** [comment]
Maybe user wants to execute something immediately. For example stop engine, so he can't wait and wants to force use SMS straight away.

**Comment by Abyss777** [comment]
He can tick "Send via SMS" in Send Command dialog.
Also I see some confusing thing in current behavior. User can get "Unsupported command" error if he sends supported channel command, fallback to SMS, but it is unsupported via SMS.

**Comment by tananaev** [comment]
Then I agree that it's basically useless if we implement queue. The only corner case I can think of is when server is stopped we would probably lose all the buffered commands, so user might want to send SMS as a last resort. Or do we plan to store commands in the database? It might be too complicated.

**Comment by Abyss777** [comment]
No, I do not have plan to store buffered commands in DB, at least for now.
But I'm not understand how will we send SMS as a last resort after server restart if nothing buffered?

**Comment by tananaev** [comment]
Not after, but before. In the `Main` class we have shutdown hook which can execute some code before shutdown. Basically we can send remaining commands in the buffer using SMS before shutting down.

**Comment by Abyss777** [comment]
Interesting idea, but I think we need other config flag for that `textCommandsOnShutdown` or something.

For me corner case is when user select online device, want to stop engine immediately (his car is stolen), but while he selecting command device becomes offline. He push "Send" and command is put in buffer. If he noticed that device became offline he have to send command again via SMS, but if he misses that he may lost priceless time.

**Comment by tananaev** [comment]
I suggest we remove the flag for now and don't implement shutdown until people ask for it. It seems like a real rare corner case.

**Comment by Abyss777** [comment]
OK. One more thing...
My vision of handling send buffered commands errors when device becomes online:
- Successfully sent commands are removed from queue
- Command that causes `RuntimeException` (usually Unsupported) also removed from queue
- Any other exceptions not handled and interrupted process of sending buffered commands (I belive they related with connection and basically mean that device become offline again), rest of commands will be sent when device become online again.

**Comment by Abyss777** [comment]
Noticed one thing, why do not we remove device from `activeDevice` lists when its state become unknown? Traccar tries to send commands to such devices, I believe it should not. I have only doubts about UDP devices. What do you think?

**Comment by Abyss777** [comment]
It's interesting, are there any other protocols accepted commands in response?

**Comment by tananaev** [comment]
I believe we should buffer commands only if device is not online. We should not catch exceptions.

Unknown status can go either way. I don't really have any preference. Unknown can still be connected, but just not reporting, but it also can mean dead connection. Probably makes more sense to remove them.

**Comment by tananaev** [comment]
We already support commands queue.
