### ISSUE TITLE
positions api - 401 unauthorized

### ISSUE THREAD

**Issue by mm108** [traccar/traccar#2500]
hi,

I have the exact same issue described here. I have traccar and my application running on 2 different machines. When I use the login api, it succeeds. But subsequently when I try to execute the api/positions api, it doesn't work. It says that it's 401 unauthorized.

It's the same as the problem described [here](https://github.com/tananaev/traccar/issues/1526)

I didn't quite get the solution. Could you please tell me what I could do to solve this?

Thanks,
M.M

**Comment by tananaev** [comment]
Unauthorized  error means that either you are not logged in, or you don't have access to a particular device.
