### ISSUE TITLE
JsonConverter in reports

### ISSUE THREAD

**Issue by tananaev** [traccar/traccar#2501]
@Abyss777, do we have to use JsonConverter in the reports? Ideally I want to get rid of this class.

**Comment by Abyss777** [comment]
Technically not, seems I just copied it from PositionResource.
If jetty will cope with our objects, why not.
I will try to remove it from reports.

**Comment by tananaev** [comment]
Thanks. I just don't like that we have two ways of converting data to/from JSON.

**Comment by Abyss777** [comment]
Agree, I was confused a bit first time.

**Comment by Abyss777** [comment]
How replace `JsonConverter.parseDate(from)` ? Or leave it?

**Comment by tananaev** [comment]
I think we can leave that one, but better to move it to a separate class. Maybe something like `DateUtil` to not confuse it with JSON, because it has little to do with actual JSON. It's just to parse ISO formatted date.
