### ISSUE TITLE
GPS device support

### ISSUE THREAD

**Issue by akmal1999** [traccar/traccar#2506]
Hi, 

Are these GPS devices supported?

cctr-808s   https://rfq.alibaba.com/rfq/detail.htm?spm=a2700.8073704.0.0.Q5F5YM&productId=30002756181&tracelog=marfq

https://www.alibaba.com/product-detail/gps-tracker-sirf-iv-waterproof-powerful_60052668547.html

thanks

**Comment by tananaev** [comment]
Most likely they are, but I need protocol documentation to confirm.
