### ISSUE TITLE
./traccar.run: line 488: ./setup.sh: Permission denied

### ISSUE THREAD

**Issue by agusu888** [traccar/traccar#2511]
Hi Tananaev,

I tried to install traccar with following permission denied message. i have did 'chmod +x traccar.run' but still got same message, need your help
```
[root@server src]# ./traccar.run
Verifying archive integrity... All good.
Uncompressing traccar  100%
./traccar.run: line 488: ./setup.sh: Permission denied
```
Thanks in advance

**Comment by tananaev** [comment]
You can extract it manually and run setup script. See https://github.com/tananaev/traccar-client-android/issues/101 for some more info.

**Comment by khfrabbi** [comment]
I used following syntax for the same error you mentioned

./traccar.run --target /opt/traccar --noexec

**Comment by neroshin** [comment]
Hi @tananaev I also got some experience on Permission denied 
./traccar.run: line 488: ./setup.sh: Permission denied
can you help me to resolve it

**Comment by tananaev** [comment]
What version are you using?

**Comment by jon-stumpf** [comment]
I believe you are running as a regular user which does not have the ability to create /opt/traccar.

Try running the script with elevated privilege - i.e., "$ sudo ./traccar.run --target /opt/traccar"
