### ISSUE TITLE
Protocol Easy Track Port 5056

### ISSUE THREAD

**Issue by realyte** [traccar/traccar#2513]
Hello I'm the problem easy track protocol port 5056 I correctly direct it to the tracker server and get the hexadecimal string plus traccar does not update or recognize the device in the logs have it:
```
03.11.2016 15:38:31 DEBUG: [EC54C791: 5056 <186227158250] HEX: 2a45542c3335383135353130303035333033362c48422c412c3130306230342c3031323631662c38306437303332322c38316164306563312c303036312c303030302c34306330303030302c31642c3130302c303030302c6132622c383532230d0a

03.11.2016 15:38:36 DEBUG: [EC54C791: 5056 <186227158250] HEX: 2a45542c3335383135353130303035333033362c4d51230d0a

03.11.2016 15:39:06 DEBUG: [EC54C791: 5056 <186227158250] HEX: 2a45542c3335383135353130303035333033362c4d51230d0a
```
<img id="main-image" src="https://s17.postimg.org/50hm3d97j/2016_11_07_16_56_30_Link_Tracker_Enabled_Solu.png" style="display:block;width:100%;max-width:705px;" data-full="//s17.postimg.org/x0lpnncnx/2016_11_07_16_56_30_Link_Tracker_Enabled_Solu.png" data-width="705" data-height="604">
 
I've tried using older versions nothing works ....

Can you help me please...

att,
Wagner Vieira

**Comment by tananaev** [comment]
The issue might be the same as #2509.
