### ISSUE TITLE
issue with traccar source code after  WEB UI execution

### ISSUE THREAD

**Issue by sureshmalla** [traccar/traccar#2514]
I am working with your traccar web ui source code in netbeans guided from the website http://traccar.litvak.su/installation.html and every thing is working fine after the process of ATTACH DEBUGGER from DEBUG menu and i am getting traccar web ui in my default browser with url " http://127.0.0.1:8888/traccar.html " and i have added an android client with which is working fine with your demo.traccar.org but when i want to see my device in this web ui it is not visible . In my mobile client LOCATION UPDATE is coming and after few seconds it is visible SENT FAILED with mobile client app ip address of my local ip and server as 5055 and preferred ALL THREE PROVIDERS one by one and my traccar web ui log is showing" Log is not available. Looked at D:\NetBeansProjects\traccar-web\logs\tracker-server.log, " . In the downloaded source code i have not seen any traccar-server.log 
 file . So can you please help me how to execute this with my device
can i use public ip to test  this application?
thanks in advance

**Comment by tananaev** [comment]
It sounds like you don't have a back-end. Traccar web UI from Litvak is just a web interface. You need a back-end as well to receive data from any device.

**Comment by sureshmalla** [comment]
I have downloaded your traccar (server) from " https://www.traccar.org/support/ " and compiled it in net beans guided from " https://www.traccar.org/build-in-netbeans/" . I have followed all the same steps but when traccar web interface using localhost:8082 is is returning 404 not found error and one more thing the web ui I have connected with my MySQL database and all the tables were created automatically. only this mobile client detection is showing problem.

**Comment by w32gold** [comment]
Please provide logs.

**Comment by sureshmalla** [comment]
cd C:\Users\11011107\Documents\NetBeansProjects\traccar-master; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_91" cmd /c "\"\"C:\\Program Files\\NetBeans 8.0.2\\java\\maven\\bin\\mvn.bat\" -Dexec.args=\"-classpath %classpath org.traccar.Main debug.xml\" -Dexec.executable=\"C:\\Program Files\\Java\\jdk1.8.0_91\\bin\\java.exe\" -Dmaven.ext.class.path=C:\\Users\\11011107\\AppData\\Roaming\\NetBeans\\8.0.2\\maven-nblib\\netbeans-eventspy.jar -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building traccar 3.7-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ traccar ---
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO 11/8/16 3:07 PM: liquibase: Clearing database change log checksums
INFO 11/8/16 3:07 PM: liquibase: Successfully acquired change log lock
INFO 11/8/16 3:07 PM: liquibase: Successfully released change log lock
INFO 11/8/16 3:07 PM: liquibase: Successfully acquired change log lock
INFO 11/8/16 3:07 PM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO 11/8/16 3:07 PM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO 11/8/16 3:07 PM: liquibase: Successfully released change log lock
[main] INFO org.eclipse.jetty.util.log - Logging initialized @9801ms
[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.19.v20160908
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@31464a43{/api,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@f2ce6b{/console,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@2f2487e3{HTTP/1.1}{0.0.0.0:8082}
[main] INFO org.eclipse.jetty.server.Server - Started @24958ms

**Comment by tananaev** [comment]
What config are you using for Traccar server? It should have a path to log file location.

**Comment by sureshmalla** [comment]
can you please tell me step by step source code installation or any relavant detail documentation of it to execute successfully 
thanks in advance

**Comment by sureshmalla** [comment]
In my traccar server log i found some thing like this..
2016-11-08 03:17:44  INFO: Operating system name: Windows 10 version: 10.0 architecture: amd64
2016-11-08 03:17:44  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.60-b23
2016-11-08 03:17:44  INFO: Memory limit heap: 894mb non-heap: 0mb
2016-11-08 03:17:44  INFO: Character encoding: Cp1252 charset: windows-1252
2016-11-08 03:17:44  INFO: Version: null
2016-11-08 03:18:06  INFO: Starting server...
2016-11-08 03:18:11  WARN: Address already in use: bind - BindException (... < WebServer:154 < Main:40)
2016-11-08 05:46:06  INFO: Operating system name: Windows 10 version: 10.0 architecture: amd64
2016-11-08 05:46:06  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.60-b23
2016-11-08 05:46:06  INFO: Memory limit heap: 894mb non-heap: 0mb
2016-11-08 05:46:06  INFO: Character encoding: Cp1252 charset: windows-1252
2016-11-08 05:46:06  INFO: Version: null
2016-11-08 05:47:06  INFO: Starting server...

**Comment by sureshmalla** [comment]
i have got access with  mysql database but only thing i am not getting is the "404 not found " error on browser  when running traccar server

**Comment by tananaev** [comment]
You said that it worked before (in the first post). I'm completely confused on what you are trying to do and what's not working.

**Comment by sureshmalla** [comment]
the web ui I said that it was working but not detecting the device but after you said about server I have compiled traccar server and it is showing 404 not found error. 1) the web ui is executed but not detecting the device 2) traccar server executing and showing 404 not found error in browser when we use localhost:8082

**Comment by tananaev** [comment]
Which of the two problems do you want to solve?

**Comment by tananaev** [comment]
Do you back-end with web UI? Or you just run in on its own?

**Comment by sureshmalla** [comment]
I just run this web ui but its not detecting the device and providing its back-end I am not understanding how to integrate it with web ui.

**Comment by tananaev** [comment]
Web UI mod is just a web interface, as I said before. You need back-end. For integration of two, you need to ask mod author.

**Comment by sureshmalla** [comment]
i am not understanding what is mod author

**Comment by tananaev** [comment]
If I'm understanding correctly, you are using this:

http://traccar.litvak.su/installation.html

It's not an official Traccar project, so you need to contact author of that project for support.

**Comment by w32gold** [comment]
The author of the Traccar-web UI is Vitaly Litvak.

**Comment by sureshmalla** [comment]
I am executing your traccar server project also but its also giving 404 not found error in browser. can you help me to execute this traccar server

**Comment by tananaev** [comment]
Have you checkout out `traccar-web` git submodule in Traccar?

**Comment by sureshmalla** [comment]
ya I saw but I am asking about your this traccar server which is executed with url localhost:8082 which is compiling very fine and building all tables in database when I debug the project but the only problem I am getting is when I am typing localhost:8082 in my browser I am getting 404 not found error

**Comment by tananaev** [comment]
I think you misunderstood me. I am talking about official Traccar web interface. There is a folder called "traccar-web" in "traccar" repository. Is it empty? If yes, it means that you haven't checked out git submodule.

**Comment by sureshmalla** [comment]
yes it is empty

**Comment by tananaev** [comment]
Did you use git to download source code?

**Comment by sureshmalla** [comment]
i hava downloaded it from https://github.com/tananaev/traccar website

**Comment by tananaev** [comment]
So you didn't use git. Then you should probably download web interface part as well:

https://github.com/tananaev/traccar-web

**Comment by sureshmalla** [comment]
ya i have downloaded the traccar web ... now i hava to paste all the files of traccar web in traccar-web folder of traccar server or is there any other steps to integrate

**Comment by tananaev** [comment]
That's it. Make sure you have correct path to the web folder in the config file.

**Comment by sureshmalla** [comment]
Thank you so much.... i have copied and pasted all the files of traccar web to the folder of traccar-web of traccar server and its working.... thank you so much for your response......
i will touch with you......

**Comment by sureshmalla** [comment]
Hi... tananaev.. I am using  JM01 gps device and i am sending all the commands using SMS and its replying to it with "SERVER,1,demo.traccar.org,5023,0#" command but when i am using the command for my public IP "SERVER,1,http://182.77.56.62:8082,5023,0#" it is not responding to it anything. shall i have to take a domain name for my IP. I have been stuck with it since 8 days. so can you please help me anything to solve this

**Comment by tananaev** [comment]
@sureshmalla, are you serious? Why are you using URL instead of IP address. It should be:
```
SERVER,1,182.77.56.62,5023,0#
```

**Comment by sureshmalla** [comment]
when I am sending the SMS like "SERVER,1,182.77.56.62,5023,0#" the device is responding "Error: Parameter 2 domain is not formatted correctly!" and when I am adding http:// before IP address its responding "OK"... I am not able to understand whats happening with the device to send response to the web interface....

**Comment by tananaev** [comment]
What does second parameter ("1") mean?

**Comment by sureshmalla** [comment]
that is not given in the manual...
5.3 Server setting
To connect other platform, please send the SMS commands below:
Command format： SERVER,1,domain,Port,0#
Example: SERVER,1,www.cooaccess.net,8841,0#
It will reply “OK” after set successfully.  Its given in the manual only like this tananaev.....

**Comment by tananaev** [comment]
Your documentation is not complete. I think it should be:
> Server Setting
Command Reply SMS Description
(a)SERVER,1,domain,port,0#
(b)SERVER,0,ip,port,0#

Which mean for IP address you can use:
```
SERVER,0,182.77.56.62,5023,0#
```

**Comment by sureshmalla** [comment]
ya I am using like this and its replying OK but when I add the device with IMEI number as unique id its position is not shown in the UI... and even I tried with demo.traccar.org but it was not succesful

**Comment by sureshmalla** [comment]
I have also tried with your Demo server 4, typed "104.251.215.88" in the url for UI and sent the SMS "SERVER,0,104.251.215.88,5023,0#" and the device replied OK but after adding the device with IMEI number in demo server 4 the location is not visible...

**Comment by tananaev** [comment]
What's the device id?

**Comment by sureshmalla** [comment]
TK103---"868683025569249"  . I have been trying with your demo server 40.122.161.243 but its not showing any location...

**Comment by sureshmalla** [comment]
TK103---"868683025569249" . I have been trying with your demo server 104.251.215.88 but its not showing any location...

**Comment by tananaev** [comment]
I don't see any data from your device on either of the demo servers.

**Comment by sureshmalla** [comment]
when i am sending SMS to the tk-103 device "check123456" its responding 
Power:ON
Bat:100%
GPRS:OFF
GPS:ON
ACC:OFF
Door:OFF
GSM:14
Oil:0.00%
APN:airtelgprs.com
Ip:40.122.161.243
my gprs is OFF  is that any issue with my network provider
when i send GPRS123456 from my mobile it responds GPRS OK 
but when i check command check123456 it shows above details
so how can we fix this problem
i tried with two sim cards  but it does not work

**Comment by tananaev** [comment]
I can see the data now, but you haven't registered your device on the server:
```
WARN: Unknown device - 868683025569249
```

**Comment by sureshmalla** [comment]
when i use check123456 command it showing gprs:OFF  in tk103 device 
how can i solve this problem tananaev

**Comment by tananaev** [comment]
Your device sends data, so configuring device is not a problem. You just have to register it on the server side.

**Comment by sureshmalla** [comment]
i am not understanding how to register on the server

**Comment by tananaev** [comment]
Login and add device with the unique id.

**Comment by sureshmalla** [comment]
i have added the device in your ip 104.251.215.88 named tk103 and device identifier 083025569249
can you please check

**Comment by tananaev** [comment]
The unique id is "868683025569249", why are you adding "083025569249"?

**Comment by sureshmalla** [comment]
its tk103 thats why i removed the first four digits

**Comment by tananaev** [comment]
It's NOT TK103 protocol. You device is using GPS103 protocol. Please see following page:

https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/

**Comment by CVSz** [comment]
@sureshmalla unique id 868683025569249 port 5001 for gps103

**Comment by sureshmalla** [comment]
it worked on your demo server 104.251.215.88 with fix030s***n123456 command and 5001 port... thanks a lot tananaev.. these many days I worked with it and as you suggested I got the output and I am very happy with it... thanks a lot.... I will test it with my public ip and  will send you the result soon.. once again thanks a lot....

**Comment by AijazAliShah** [comment]
hi,
can you help me?
i am facing this error when i run traccar server code
(Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project traccar: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.)

**Comment by tananaev** [comment]
@AijazAliShah, I would recommend that you create your own issue to discuss it instead of commenting on this one.
