### ISSUE TITLE
I create a new  User form in Spring MVC(JAVA) for traccar.But How to insert password  in database  from Registration form.?Help me how to do this?

### ISSUE THREAD

**Issue by sdip025** [traccar/traccar#2515]
As per my requirement i have a New user from in Spring MVC.But  how to insert password in same format(hash and salt) as given in traccar.?

**Comment by tananaev** [comment]
Use this class:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/helper/Hashing.java
