### ISSUE TITLE
Ruptela Commands

### ISSUE THREAD

**Issue by barigo** [traccar/traccar#2519]
hi , 

i want to know if the custom command is working with the version 3.7.

i have tried to send the setio 2,1 but nothing work.

many thanks

**Comment by tananaev** [comment]
Ruptela is a binary protocol, so you have to send binary command (in HEX format).

**Comment by barigo** [comment]
thanks for reply .

so i'll convert the command (setio 2,1) to hex like that **736574696f20322c31** and send it with web interface : 

send command > custom > **736574696f20322c31**

right?

**Comment by tananaev** [comment]
No, it's not right. You have to follow special format for the message. It has to include Packet length, Command ID, Payload (this is your HEX) and CRC16 for the message.

**Comment by tananaev** [comment]
Send me an email if you want to discuss better support for Ruptela commands.

**Comment by barigo** [comment]
can i have your email please?

**Comment by tananaev** [comment]
It's in my profile.

**Comment by barigo** [comment]
i send you an Email. thanks

**Comment by kakaba** [comment]
hey guys, I am facing the same problem, can you help me out ?
I tried any possible way without success :/.  
thanks in advance
