### ISSUE TITLE
GT007

### ISSUE THREAD

**Issue by richieri** [traccar/traccar#2530]
My device returns this:
*HQ,356803210091319,BS,,2d4,a,1b63,1969,26,1b63,10b2,31,0,0,25,,ffffffff,60#

I tried to send to port 5013, imagining that it was a h02, but when I compared better, it didnt work.

I'm not sure about the name of the device. This is where I bought:
http://www.dx.com/p/gps-tracker-locator-for-car-vehicle-w-magnet-and-3000mah-battery-447272#.WCjzrXUrKis

I opened the device and it's written GT007 on the chipset. Can you guys help me on that?

thanks!

**Comment by tananaev** [comment]
It's H02 protocol, but the message that you provided does not include GPS data. It seems like cell information, but I would need protocol documentation to decode it.

**Comment by richieri** [comment]
Dear!

I'm analysing and it seems that my device stills not fixing gps data. First
I'll analyse it than i came back here.

Sorry for bothering with this!

Em 13 de nov de 2016 10:33 PM, "Anton Tananaev" <notifications@github.com>
escreveu:

**Comment by tananaev** [comment]
Are you sure your device has a GPS module?

**Comment by tananaev** [comment]
Looked at the description and it seems like it does. Some Chinese devices don't have GPS modules, even if they are called "GPS" devices.

**Comment by richieri** [comment]
I think it does. At least, I think it is. I'm attaching the image. I think
this GT007 is the GPS chipset.

I asked the vendor to confirm. Thanks!

Em 13 de nov de 2016 10:40 PM, "Anton Tananaev" <notifications@github.com>
escreveu:
