### ISSUE TITLE
Nominatim NULL address

### ISSUE THREAD

**Issue by fetteh** [traccar/traccar#2534]
Hi all,
I have successfully installed Nominatim in my own server and it worked perfectly in my country "Tunisia".
For example when I made a request for a reverse geocoding like this one :
("http://xxxxxxxxxxxxxxxxxx/html/nominatim/reverse.php?format=json&lat=35.693050401732215&lon=9.749336242675781")
It gives me this result : 
{"place_id":"118105","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"way","osm_id":"34340131","lat":"35.6580777","lon":"9.7777964","display_name":"RN 12 طو, Ain Zena, Kairouan, Tunisia","address":{"road":"RN 12 طو","village":"Ain Zena","state":"Kairouan","country":"Tunisia","country_code":"tn"}}

The problem is that the address is empty with Traccar 3.3 using the following configuration :
```
<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>nominatim</entry>
<entry key='geocoder.url'>http://xxxxxxxxxxxxxxxxxx/html/nominatim/reverse</entry>
```
I dont know if traccar support the arabic language ?
Do you have any idea ?
Thanks.

**Comment by tananaev** [comment]
Why did you remove ".php" at the end? It should be part of the URL.

**Comment by fetteh** [comment]
I get NULL address also when I used reverse.php, I tried also to disable the firewall but nothing changed ! I think that I have to check the log file.

**Comment by tananaev** [comment]
I think the only option would be to debug the code.
