### ISSUE TITLE
Traccar with Taxi -URGENTLY NEEDED!!!!!

### ISSUE THREAD

**Issue by TheGreatB** [traccar/traccar#2538]
is it possible to use traccar for showing location of driver to a particular customer? if so how can i make customer app see location of a just one driver...

**Comment by kirantpatil** [comment]
Also it would be good if there is a mechanism to know "Expected Time of Arrival" of Taxi to My location. I am interested in this project.

**Comment by tananaev** [comment]
It's possible to use API to implement it. One way is to make user register (or automate it), then link a device to that user using Traccar API. That way user would be able to access location of a specific car.

**Comment by kirantpatil** [comment]
@tananaev, is there a way to predict "Expected Time of Arrival" of Taxi from its current place to my place ?

**Comment by tananaev** [comment]
@kirantpatil, no, you need a navigation engine for that.

**Comment by TheGreatB** [comment]
@kirantpatil yea you can but not with traccar..i got a source code for that. calculates the ETA between two given adresses

**Comment by TheGreatB** [comment]
@tananaev yes i have tried your suggestion before but is what i need is for customer application to view only location of just one driver who accepted request. the customer should not be able to see devices but one

**Comment by TheGreatB** [comment]
@tananaev How can i achieve this?

**Comment by tananaev** [comment]
You can link that one device to the customer user account.

**Comment by kirantpatil** [comment]
@tananaev, can we create group like "route 20" with Device and link customer user account to it ?

Right now I see that groups can be created it is not visible in other user accounts.

**Comment by tananaev** [comment]
Yes, you can link groups to user accounts.

**Comment by kirantpatil** [comment]
@tananaev, There is no interface in v3.7 to add group to user account. Is it part of v3.8 ?

**Comment by kirantpatil** [comment]
Sorry, it is present in v3.7 found a bug.

**Comment by tananaev** [comment]
What's the bug?

**Comment by kirantpatil** [comment]
@TheGreatB any updates regarding the Taxi solution ? 

Please share your pain points as well while building the solution.

**Comment by kirantpatil** [comment]
@TheGreatB any updates regarding usage of Traccar as Taxi solution ? Have you built the taxi solution ?

**Comment by TheGreatB** [comment]
Yes i found much better solution but not using traccar. If you need it let me know

**Comment by kirantpatil** [comment]
Please share the details.

**Comment by kirantpatil** [comment]
@TheGreatB 

What have you used to build taxi solution ?
