### ISSUE TITLE
How Can i deploy traccar on a host

### ISSUE THREAD

**Issue by deltaforce3** [traccar/traccar#2543]
- I want to host the application online, I don't know how to install it on hosting accounts( Hosting service provided by hostgator/godaddy or others) Can you please specify account type i need to buy?

- I want to deploy it online i have successfully installed it on my windows system and now i want to use it on a web server to host it online.

**Comment by CVSz** [comment]
i think can u use vps at http://www.vultr.com/?ref=7029990-3B
i see your vps clond have averyting traccar need to use and low cost :)

**Comment by deltaforce3** [comment]
@CVSz  Thanks a lot :+1:  can you please also tell me how to install it online? 
( i am a newbie in deploying application online any good study material that i can go through could also help me out)
 Thanks.

**Comment by deltaforce3** [comment]
@CVSz  Thanks a lot :+1:  can you please also tell me how to install it online? 
( i am a newbie in deploying application online any good study material that i can go through could also help me out)
 Thanks.

**Comment by CVSz** [comment]
tell me if you need more help

**Comment by tananaev** [comment]
You need a VPS. When you get VPS, just [download ](https://www.traccar.org/download/) installation package and follow README file instructions.

**Comment by deltaforce3** [comment]
thanks a lot @tananaev :+1: 
 i have done some tweaks in the UI. Can i create package of the modified version and then install it?  
If yes how can i create package ?

**Comment by tananaev** [comment]
I would recommend to manually update the files on the installed system. Packaging installer is not an easy task. Note that you would still need to minify JavaScript files if you have modified anything there.

**Comment by deltaforce3** [comment]
@CVSz  will block storage option here be enough to host this application ?
Thanks.
https://www.vultr.com/pricing/blockstorage/

**Comment by CVSz** [comment]
yes, bro it's optional not required if you need more enough can you pay

**Comment by may22280** [comment]
Hi,
Trying to upgrade from 3.7v to 3.8v.
I used this command 
"wget https://github.com/tananaev/traccar/releases/download/v3.8/traccar-linux-64-3.8.zip"
 but it wouldn't work. I don't have any tracker device on the server yet, so I want to install a clean 3.8v.  Do I need to uninstall the 3.7v first? I used this command
 "sudo /opt/traccar/bin/traccar remove"
 and try installing the new release 3.8v with this command 
"wget https://github.com/tananaev/traccar/releases/download/v3.8/traccar-linux-64-3.8.zip"
 yet it respond with an error 404:not found.

Please help me out, what should I do? or what am I not doing correctly?

Thanks

**Comment by tananaev** [comment]
The links that you are using are incorrect. Please use ones from the official website:

https://www.traccar.org/download/

**Comment by devopsexpert** [comment]
I have been using Silicon House dedicated servers for my requirements. Check out https://www.siliconhouse.net/traccar-gps-tracking-hosting

They are the best. Moreover they give you optimized Traccar with Mysql too. Also I can integrate with my site using php and mysql. Like run my portal as well as GPS tracking in the same server.
