### ISSUE TITLE
 No response from sent commands

### ISSUE THREAD

**Issue by Omar-Desarrollo** [traccar/traccar#2544]
Dear, thank you very much for this great project.

I have the following problem: when I send an alarmArm command the command is sent correctly but does not resize the alerts from the device when the alarm is activated.

I do not resent any alerts when I send commands.

I am using the 3.7 version with a gps tk300

Do you know what can be happening

**Comment by tananaev** [comment]
What protocol are you using?

**Comment by Omar-Desarrollo** [comment]
I'm using gps103 protocol

**Comment by tananaev** [comment]
How do you know if your device accepted the command. I guess it just doesn't understand or doesn't support it.

**Comment by Omar-Desarrollo** [comment]
The command to stop the engine works correctly but the server does not show
the message of confirmation
(StopEngine Ok)

**Comment by tananaev** [comment]
If you have the documentation, I can check if the other commands are correct.

**Comment by Omar-Desarrollo** [comment]
I have the documentation physically. But I send you some photos

http://subefotos.com/ver/?aded740f9e89ef7fae476c71a7b55852o.jpg

http://subefotos.com/ver/?c21f6c0968896188282affa4a6b91856o.jpg

**Comment by tananaev** [comment]
That's just device manual. I need documentation for communication protocol.

**Comment by Omar-Desarrollo** [comment]
I found this documentation. It's enough?

**Comment by tananaev** [comment]
I don't know if you realize, but you are sending email directly to GitHub. It doesn't handle attachments. You can do it through GitHub website directly.

**Comment by Omar-Desarrollo** [comment]
You're right, sorry I send you the file link.

https://www.google.cl/url?sa=t&source=web&rct=j&url=http://www.spadamar.com/wp-content/uploads/2011/11/GPRS-Data-Protocol.xls&ved=0ahUKEwjiqc7r6a7QAhXKEZAKHaSvA-UQFghLMAQ&usg=AFQjCNEhMNSn2CjW9H0FSTSxEOn11ob7qg

**Comment by tananaev** [comment]
There is nothing about commands for engine stop/resume or arm/disarm.

**Comment by Omar-Desarrollo** [comment]
That means that gps does not support those commands via gprs only sms?

**Comment by tananaev** [comment]
It probably means that documentation is not complete.

**Comment by evigra** [comment]
para quien trabjas omar??

**Comment by Omar-Desarrollo** [comment]
Hola eduardo,

por que lo preguntas?

2017-01-06 22:56 GMT-04:00 Eduardo Vizcaino <notifications@github.com>:

**Comment by Omar-Desarrollo** [comment]
Hola eduardo,

por que lo preguntas?

**Comment by evigra** [comment]
pq un desarrollador que pregunta eso... 
deberia ser el dueño...
y no trabajar para alguien

**Comment by Omar-Desarrollo** [comment]
no trabajo aun estoy estudiando
