### ISSUE TITLE
meiligao Protocol

### ISSUE THREAD

**Issue by SRIKAAA** [traccar/traccar#2549]
[tracker-server(5).txt](https://github.com/tananaev/traccar/files/597119/tracker-server.5.txt)

In the above attached log, we configured once device to 8840 port of  meiligao Protocol and we are receiving GPS data. But when the vehicle is moving , the mileage parameter is not getting stored in the database. Whereas in protocol  it is mentioned that mileage is available.

Kindly suggest which port to use for getting mileage.

**Comment by SRIKAAA** [comment]
242400706573402852404799553130313932372e3030302c412c313732362e38323739332c4e2c30373832382e31393637312c452c312e382c362e342c3137313131362c2c2a32427c312e36387c3534342e327c313030307c303030302c303030307c3030303032383638373a1a0d0a



is the sample packet for reference

**Comment by tananaev** [comment]
It works for me:
```
attributes = {LinkedHashMap@2592}  size = 5
 0 = {LinkedHashMap$Entry@2607} "hdop" -> "1.68"
 1 = {LinkedHashMap$Entry@2608} "status" -> "1000"
 2 = {LinkedHashMap$Entry@2609} "adc1" -> "0"
 3 = {LinkedHashMap$Entry@2610} "adc2" -> "0"
 4 = {LinkedHashMap$Entry@2611} "odometer" -> "165511"
```
