### ISSUE TITLE
Set Alarm when location service is turned off on Android

### ISSUE THREAD

**Issue by nikhilnayak98** [traccar/traccar#2550]
The buzzer alarm sounds up when the location services are turned off. How can we know from the traccar server that the location services of a mobile is turned off.

**Comment by tananaev** [comment]
Currently there is no way to know.

**Comment by kirantpatil** [comment]
May be using events as shown below, which shows device is online or offline.

![screenshot from 2016-11-18 17 47 15](https://cloud.githubusercontent.com/assets/1178055/20429865/31377f84-adb7-11e6-81ba-34de5050b8e6.png)

**Comment by tananaev** [comment]
If this is still needed, please submit a ticket for Traccar Client.
