### ISSUE TITLE
Remove Register option at login screen

### ISSUE THREAD

**Issue by deltaforce3** [traccar/traccar#2553]
Hello can you please guide me how to remove register option at log in screen?

**Comment by tananaev** [comment]
Login as admin, open settings -> server, uncheck registration checkbox.

**Comment by malkitsingh** [comment]
@tananaev this disables registering users through API too. What if I want to disable registration through web interface but allow registrations through API's only?

**Comment by tananaev** [comment]
It doesn't make much sense, and it's not possible. However, you can easily modify web interface to remove the button if you want.
