### ISSUE TITLE
Upgrade from 3.7 to 3.8

### ISSUE THREAD

**Issue by paraisotech** [traccar/traccar#2558]
What are the steps that we have to follow to upgrade from 3.7(working) to the new 3.8 release without loosing any stored data in db? I'm using CentOS(RedHat) and MySQL as DB engine...

**Comment by strasharo** [comment]
Just backup the 4 configuration lines for the database connection and run the installer. Then place the config in the new traccar.xml in /opt/traccar/conf/. The info in the database will be preserved.

**Comment by Abyss777** [comment]
In the 3.8 was implemented split to `traccar.xml` and `default.xml`. 
You do not need edit `default.xml` in most cases. You should place settings to `traccar.xml`
I'll try to describe the steps:

1. Backup `/opt/traccar` folder just in case, you will need `/opt/traccar/conf/traccar.xml` at least.
2. Run installation script (service will be stopped, updated, but not started again, it is good)
3. Very carefully copy all settings you made manually in previous version from old (backuped) `traccar.xml` to new `/opt/traccar/conf/traccar.xml`
Do not occasionally remove link to `default.xml` 
4. Start traccar service
5. Check if there are no any errors in `wrapper.log` and `tracker-server.log`

**Comment by paraisotech** [comment]
Thanks for your answer...
