### ISSUE TITLE
3.8 Webpage freezing

### ISSUE THREAD

**Issue by viacom1234** [traccar/traccar#2561]
Unable to use version 3.8. Added a new device and now the webpage becomes unresponsive. Also the new device that was added is jumping all around on the map.

**Comment by Abyss777** [comment]
What browser are you using?

**Comment by viacom1234** [comment]
Chrome Version 54.0.2840.99 m

Tested from 2 different PCs

**Comment by Abyss777** [comment]
Any errors in browser console?

**Comment by viacom1234** [comment]
Nope. Just freezes and have to close down the browser.  It happens when I add an android client device. The device screen also shows updates every second even though I have it set to 60 seconds on the device.

**Comment by Abyss777** [comment]
Are time row in state panel also changes every second?

**Comment by viacom1234** [comment]
Now I cant get any android clients communicating with my server or demo server. Let me do more testing...

**Comment by viacom1234** [comment]
Android devices were communicating 2 hours ago and now show "send failed" from device

Log on server has errors too?

2016-11-19 13:08:49  WARN: [FE6861F3] error - invalid version format: ￀ - IllegalArgumentException (...)
2016-11-19 13:08:49  INFO: [FE6861F3] disconnected
2016-11-19 13:08:49  WARN: [FE6861F3] error - invalid version format: ￀ - IllegalArgumentException (... < MainEventHandler:103 < *:92 < ... < ExtendedObjectDecoder:52 < ... < ReverseGeocoderHandler:48 < ...)

**Comment by Abyss777** [comment]
What geocoder are you using?

**Comment by viacom1234** [comment]
Not sure what that is. Using default settings with traccar I am sure.

**Comment by Abyss777** [comment]
Have you enabled Encryption in traccar client?

**Comment by viacom1234** [comment]
Yes. I did just enable that today too. I disabled and its working.

**Comment by Abyss777** [comment]
The problem of freezing is solved now?

**Comment by viacom1234** [comment]
So far its working... Ill report back if it happens again.

**Comment by Abyss777** [comment]
@tananaev I think we should mention somewhere about configuring Encryption for Traccar Client.

**Comment by tananaev** [comment]
For encryption you have to have an SSL proxy on the server side. Have you done that?

**Comment by viacom1234** [comment]
No. Maybe a popup box should remind users that its required if they enable encryption on the client.

**Comment by tananaev** [comment]
Maybe, but it has nothing to do with updating to version 3.8.
