### ISSUE TITLE
Export xlsx

### ISSUE THREAD

**Issue by ns327** [traccar/traccar#2565]
Good evening,

I am trying out the new features, however every time I click on the "export" button it does not do anything. I have checked the dev console and this is what I get:
```
ext-all-debug.js:24866 GET http://localhost:8082/api/reports/summary?_dc=1479591732597&deviceId=1&type…llEvents&from=2016-11-19T20%3A50%3A35.000Z&to=2016-11-19T21%3A20%3A35.000Z 400 (Bad Request)
start @ ext-all-debug.js:24866
request @ ext-all-debug.js:25925
downloadFile @ ReportController.js:174
onReportClick @ ReportController.js:111
callback @ ext-all-debug.js:8442
fireHandler @ ext-all-debug.js:130649
onClick @ ext-all-debug.js:130637
fire @ ext-all-debug.js:20226
fire @ ext-all-debug.js:32466
publish @ ext-all-debug.js:32442
doDelegatedEvent @ ext-all-debug.js:32492
onDelegatedEvent @ ext-all-debug.js:32479
(anonymous function) @ ext-all-debug.js:6665
```

Any suggestions?

**Comment by tananaev** [comment]
You should look at the HTTP request and response.

**Comment by ns327** [comment]
Could you elaborate on that please. Im a noob.

**Comment by tananaev** [comment]
Open developer console in your browser, then open network tab there and look at the `api/reports/summary` request. Copy everything including all headers and content here. Ideally a screenshot.

**Comment by ns327** [comment]
So in the response I get the following error:
`templates\export\route.xlsx (The system cannot find the path specified) - FileNotFoundException (... < Route:80 < ReportResource:53 < ...)`

How can I specify the location in the traccar.xml file?

**Comment by tananaev** [comment]
You can specify report template folder using `report.templatesPath` parameter in the config. By default the value is `templates/export/`.

**Comment by ns327** [comment]
Thank you, got it working. I did not have the parameter in the config file. Thanks again.

**Comment by Turbovix** [comment]
@tananaev , 
I'm getting this error at the time of generating a report.
Traccar v3.8

`ext-all.js:22 GET http://turbotrack.com.br/api/reports/route?_dc=1480130623993&deviceId=1&typ…ts&from=2016-11-26T00%3A53%3A22-02%3A00&to=2016-11-26T01%3A23%3A22-02%3A00 400 (Bad Request)`

**Comment by tananaev** [comment]
Your should look at the network response code and message.

**Comment by Turbovix** [comment]
Sorry, but I did not understand your answer. I opened the browser inspector on the network tab and there is no other information.

**Comment by Turbovix** [comment]
`Failed to load resource: the server responded with a status of 404 (Not Found)
ext-all-debug.js:9126 [W] For WAI-ARIA compliance, IMG elements SHOULD have an alt attribute.log @ ext-all-debug.js:9126
http://localhost:9272/fake-login.html Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9272/api/reports/summary?_dc=1480164549202&deviceId=1&type…ts&from=2016-11-26T10%3A16%3A42-02%3A00&to=2016-11-26T10%3A46%3A42-02%3A00 Failed to load resource: the server responded with a status of 400 (Bad Request)
ext-all-debug.js:24866 GET http://localhost:9272/api/reports/summary?_dc=1480164562828&deviceId=1&type…ts&from=2016-11-26T10%3A16%3A42-02%3A00&to=2016-11-26T10%3A46%3A42-02%3A00 400 (Bad Request)start @ ext-all-debug.js:24866request @ ext-all-debug.js:25925downloadFile @ ReportController.js:174onReportClick @ ReportController.js:111callback @ ext-all-debug.js:8442fireHandler @ ext-all-debug.js:130649onClick @ ext-all-debug.js:130637fire @ ext-all-debug.js:20226fire @ ext-all-debug.js:32466publish @ ext-all-debug.js:32442doDelegatedEvent @ ext-all-debug.js:32492onDelegatedEvent @ ext-all-debug.js:32479(anonymous function) @ ext-all-debug.js:6665
ext-all-debug.js:24866 GET http://localhost:9272/api/reports/summary?_dc=1480164565976&deviceId=1&type…ts&from=2016-11-26T10%3A16%3A42-02%3A00&to=2016-11-26T10%3A46%3A42-02%3A00 400 (Bad Request)start @ ext-all-debug.js:24866request @ ext-all-debug.js:25925downloadFile @ ReportController.js:174onReportClick @ ReportController.js:111callback @ ext-all-debug.js:8442fireHandler @ ext-all-debug.js:130649onClick @ ext-all-debug.js:130637fire @ ext-all-debug.js:20226fire @ ext-all-debug.js:32466publish @ ext-all-debug.js:32442doDelegatedEvent @ ext-all-debug.js:32492onDelegatedEvent @ ext-all-debug.js:32479(anonymous function) @ ext-all-debug.js:6665
ext-all-debug.js:24866 GET http://localhost:9272/api/reports/summary?_dc=1480164566928&deviceId=1&type…ts&from=2016-11-26T10%3A16%3A42-02%3A00&to=2016-11-26T10%3A46%3A42-02%3A00 400 (Bad Request)start @ ext-all-debug.js:24866request @ ext-all-debug.js:25925downloadFile @ ReportController.js:174onReportClick @ ReportController.js:111callback @ ext-all-debug.js:8442fireHandler @ ext-all-debug.js:130649onClick @ ext-all-debug.js:130637fire @ ext-all-debug.js:20226fire @ ext-all-debug.js:32466publish @ ext-all-debug.js:32442doDelegatedEvent @ ext-all-debug.js:32492onDelegatedEvent @ ext-all-debug.js:32479(anonymous function) @ ext-all-debug.js:6665
ext-all-debug.js:24866 GET http://localhost:9272/api/reports/summary?_dc=1480164567656&deviceId=1&type…ts&from=2016-11-26T10%3A16%3A42-02%3A00&to=2016-11-26T10%3A46%3A42-02%3A00 400 (Bad Request)start @ ext-all-debug.js:24866request @ ext-all-debug.js:25925downloadFile @ ReportController.js:174onReportClick @ ReportController.js:111callback @ ext-all-debug.js:8442fireHandler @ ext-all-debug.js:130649onClick @ ext-all-debug.js:130637fire @ ext-all-debug.js:20226fire @ ext-all-debug.js:32466publish @ ext-all-debug.js:32442doDelegatedEvent @ ext-all-debug.js:32492onDelegatedEvent @ ext-all-debug.js:32479(anonymous function) @ ext-all-debug.js:6665`

**Comment by Abyss777** [comment]
@Turbovix 

![image](https://cloud.githubusercontent.com/assets/5688080/20640529/920f4cc2-b412-11e6-9b7a-773e3a26a8ff.png)

What is in response tab?

**Comment by Turbovix** [comment]
@Abyss777 ,   does not contain any information in XHR.

![captura de tela de 2016-11-26 11-15-32](https://cloud.githubusercontent.com/assets/3914126/20640599/cb0751f8-b3c9-11e6-96da-006641b69468.png)

**Comment by tananaev** [comment]
You have to keep console open while you requesting the report for data to be captured.

**Comment by Turbovix** [comment]
![captura de tela de 2016-11-26 19-27-43](https://cloud.githubusercontent.com/assets/3914126/20644002/7ff46846-b40e-11e6-9d42-92035f16c543.png)

`http://turbotrack.com.br/api/reports/route?_dc=1480195579409&deviceId=1&type=allEvents&from=2016-11-26T18:54:50-02:00&to=2016-11-26T19:24:50-02:00`

**Comment by tananaev** [comment]
Can you please make a screenshot including all data. Also, response tab screenshot as well.

**Comment by Turbovix** [comment]
![captura de tela de 2016-11-26 19-42-29](https://cloud.githubusercontent.com/assets/3914126/20644084/811b20dc-b410-11e6-815a-a1fc47bddec9.png)

**Comment by Turbovix** [comment]
![captura de tela de 2016-11-26 19-47-53](https://cloud.githubusercontent.com/assets/3914126/20644118/42432ce6-b411-11e6-84aa-78ea188d4873.png)

**Comment by tananaev** [comment]
Can you please show the response as well.

**Comment by Turbovix** [comment]
The answer is not this answer? (Response)

**Comment by tananaev** [comment]
I don't understand the question. As you can see on your screenshots, there is a "Response" tab. I need to see what's in there.

**Comment by Turbovix** [comment]
![captura de tela de 2016-11-26 20-36-42](https://cloud.githubusercontent.com/assets/3914126/20644342/228d834a-b418-11e6-887d-479262f84538.png)

SW52YWxpZCBmb3JtYXQ6ICIyMDE2LTExLTI2VDIwOjA1OjA3LTAyOjAwIiBpcyBtYWxmb3JtZWQgYXQgIi0wMjowMCIgLSBJbGxlZ2FsQXJndW1lbnRFeGNlcHRpb24gKC4uLiA8IERhdGVVdGlsOjY0IDwgUmVwb3J0UmVzb3VyY2U6NTQgPCAuLi4p

**Comment by Turbovix** [comment]
Did you understand something there?

**Comment by tananaev** [comment]
Interesting, looks like the error was base64-encoded for some reason. Here is what it says:
```
Invalid format: "2016-11-26T20:05:07-02:00" is malformed at "-02:00" - IllegalArgumentException (... < DateUtil:64 < ReportResource:54 < ...)
```

**Comment by tananaev** [comment]
Can you try Chrome browser?

**Comment by Turbovix** [comment]
Invalid format: "2016-11-26T22:02:19-02:00" is malformed at "-02:00" - IllegalArgumentException (... < DateUtil:64 < ReportResource:43 < ...)

**Comment by tananaev** [comment]
Wait, are you using official release?

**Comment by Turbovix** [comment]
Yes, Traccar 3.8

**Comment by tananaev** [comment]
What version of Chrome? I'm using latest Chrome and everything works for me. Are you absolutely sure you don't have any modification on top of official 3.8?

**Comment by Turbovix** [comment]
turbotrack.com.br

User: christianetorloni@gmail.com
Pass: c04c04

**Comment by tananaev** [comment]
That's definitely NOT official version 3.8.

**Comment by Turbovix** [comment]
How not?

**Comment by tananaev** [comment]
When you take source code from master branch from official repository, you can't claim that it's official version 3.8. Official version is here:

https://www.traccar.org/download/

**Comment by Turbovix** [comment]
I downloaded the official version here: https://github.com/tananaev/traccar/releases

But the official web-crawl here: https://github.com/tananaev/traccar-web

**Comment by Turbovix** [comment]
Where should I get the source code of the "Official" Traccar-web?

**Comment by tananaev** [comment]
Official release is a binary package that includes a specific version of back-end and web interface that are both compatible with each other. If you modified ANY FILES, it's NOT OFFICIAL RELEASE anymore. If you take files from master, it's NOT OFFICIAL RELEASE 3.8, it's files that might be part of 3.9, but it's not even guaranteed to work. Please don't make false claims anymore.

**Comment by Turbovix** [comment]
I got it, thanks!

**Comment by tananaev** [comment]
If you want source code for 3.8, you can find it on the "v3.8" tag.

If you want to use latest source code (master branch), you have to take both back-end and web interface. Note that if you raise issues for it, make it absolutely clear to us that you are no using official RELEASE, you are using unstable code from MASTER branch.

**Comment by Turbovix** [comment]
I really apologize, I understand what is official now.

**Comment by Turbovix** [comment]
I need to ask you this, so I can not get the traccar-web code that you used for official traccar?
I think you should make the releases of the traccar-web available, just like you do with the traccar, unless you have personal reasons.

**Comment by tananaev** [comment]
`traccar-web` repository is a submodule of `traccar`. If you check it out from git properly, you will get correct version.

**Comment by Turbovix** [comment]
I understood, and I'm sorry for the big trouble. Now everything was right, including the reports. Thank you comrade!

**Comment by ramseslinux** [comment]
unreachable code after return statement[Saber más]  ext-all-debug.js:45508:8
downloadable font: kern: Too large subtable, table discarded (font-family: "Open Sans" style:normal weight:600 stretch:normal src index:0) source: https://localhost/fonts/OpenSans-Semibold.ttf  theme-triton-all_2.css:4465:12
GET 
XHR    i put in a centos 7 minimal , you have a recomendatios on linux?

**Comment by tananaev** [comment]
@ramseslinux, I don't think your issue is related to the topic. Try different browser first. If it doesn't help, create a separate issue with as much details as possible.
