### ISSUE TITLE
I found a BUG - 3.8 release

### ISSUE THREAD

**Issue by paraisotech** [traccar/traccar#2566]
I had some testing trackers registered in my account. As i finished all the tests, i selected all of the testing devices and deleted them by pressing the "Remove" button. Everything seems to be ok because the device wasn't listing anymore. But after doing a logoff and login, the device list keeps in a endless loop like trying  "loading" all devices that my account has the permission to track. 
THe solution i found it was to go to the database(mysql in my case) and manually removing the records at the "user_device" table. After that, i needed to restart the traccar service in my server and everything works great again.
Maybe it is going to be necessary to include in the delete routine another call to also delete that device id from the "user_device" as well...

**Comment by tananaev** [comment]
What engine are you using for your MySQL database? MyISAM?

**Comment by tananaev** [comment]
Traccar requires InnoDB:

https://www.traccar.org/mysql/

**Comment by paraisotech** [comment]
here is my configuration lines
<entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
    <entry key='database.url'>jdbc:mysql://127.0.0.1:3306/tagger?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>

**Comment by tananaev** [comment]
It has nothing to do with Traccar configuration. You should check your database engine.

**Comment by paraisotech** [comment]
I checked now, using MyISAM... =(

**Comment by tananaev** [comment]
You have to change to InnoDB. MyISAM doesn't support foreign keys.

**Comment by tananaev** [comment]
By the way, it has nothing to do with version 3.8. All Traccar version have the same requirement.

**Comment by paraisotech** [comment]
Great to know that. Sorry!!!
i'm closing this thread...

**Comment by paraisotech** [comment]
i'd converted my db to InnoDB.
By the way, here is a simple PHP code that done all the work for me:

<?php
    // connect your database here first 
    // 

    // Actual code starts here 

    $sql = "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'your_database_name' 
        AND ENGINE = 'MyISAM'";

    $rs = mysql_query($sql);

    while($row = mysql_fetch_array($rs))
    {
        $tbl = $row[0];
        $sql = "ALTER TABLE `$tbl` ENGINE=INNODB";
        mysql_query($sql);
    }
?>

Enjoy who needs to do the same.

**Comment by tananaev** [comment]
That won't be enough. You would have to recreate database structure or manually add foreign key constraints.

**Comment by paraisotech** [comment]
reinstall traccar solves?

**Comment by tananaev** [comment]
It won't unless you clear the database.

**Comment by paraisotech** [comment]
All done.
Stopped the traccar service, Dropped the database, changed the default database engine to innodb, created a new database and started the traccar service. All tables are now INNODB. \o/ 
Thanks
