### ISSUE TITLE
Set speed limit for gps103 protocol

### ISSUE THREAD

**Issue by paraisotech** [traccar/traccar#2567]
Is it in your plans to create a new command that will be possible to set up speedlimit on gps103 protocol devices.

The command that is suposed to be sent is
**H**,**SPEED_LIMIT_PARAMETER** with 3 bytes
For example:
to set up the speedlimit to 80km/h, send to the tracker the command H,080
to set up the speedlimit to 100km/h, send to the tracker the command H,100
to set up the speedlimit to 5km/h, send to the tracker the command H,005

or also set the speedlimit in the device parameter and when a position record comes from the device, trigger a routine to compare the speed sent with the parameter, if it is over limit, send notifications. 

Speed limit notifications are very important!!!!!

**Comment by tananaev** [comment]
Are you sure the command is the same for all GPS103 devices?

**Comment by tananaev** [comment]
By the way, you can already send it as a custom command.

**Comment by paraisotech** [comment]
All gps103 devices that i have here accepts this command... Maybe it is a
standard...

Em 19 de nov de 2016 22:29, "Anton Tananaev" <notifications@github.com>
escreveu:

**Comment by paraisotech** [comment]
I'll try to send this command as a custom command and keep your updated...

Em 19 de nov de 2016 22:30, "Anton Tananaev" <notifications@github.com>
escreveu:
