### ISSUE TITLE
Tramigo T23 device status

### ISSUE THREAD

**Issue by gpproton** [traccar/traccar#2568]
Hi @tananaev i ve tested out the direction feature for Tramigo T23 is works fine, but there are some other information that i feel needs to be decoded see the hex and explanations below:
```
8000d614b0000501010115a20381d38c2bea3058323336323637313336333a205374617475732c204750533a203931252c2047534d3a203538252c20475052533a20436f6e6e65637465642c20626174746572793a203938252028706f77657220636f6e6e6563746564292c204750525351756575653a20312c207265706f7274733a2046696e642028312c302e312c352c2d292c2049676e6974696f6e20286f6666292c20506f7765722c2053706565642028313830292c205374617475732028352c2d2c2d2c2d292c20496e7075742028706f7765726375742920286f6e292c20362e37303438362c20332e34313636372c2030313a3131204e6f7620323020454f46
```
```
...2362671363: Status, GPS: 91%, GSM: 58%, GPRS: Connected, battery: 98% (power connected), GPRSQueue: 1, reports: Find (1,0.1,5,-), Ignition (off), Power, Speed (180), Status (5,-,-,-), Input (powercut) (on), 6.70486, 3.41667, 01:11 Nov 20 EOF
```
GPS - Gps signal strength
GSM - Gsm signal strength
GPRS - Connection to server status
Battery - Battery status
GPRSQueue - No of events no yet sent to server
Connected to power - When (power connected) is included in battery status.

And by the way for 3.8 it's a great job, you you guys did a lot.

**Comment by tananaev** [comment]
I need protocol documentation to decode all additional data.

**Comment by gpproton** [comment]
I recently requested for a protocol document from the manufacturer office and they gave me the attached document, i'm not sure if it what you need but please check it out,
[T23_GPRSS_GPRS_Specification_ENG_v0.94.pdf](https://github.com/tananaev/traccar/files/601845/T23_GPRSS_GPRS_Specification_ENG_v0.94.pdf)

**Comment by tananaev** [comment]
It's the same document that I have and unfortunately it doesn't have much information. This is all the information about payload:
> 5.7.2 Payload example
> The body of the GPRS message.
> Tramigo: Parked, 0.12 km E of McDonald's H.V. dela Costa, Makati, 11:07 Mar 27

**Comment by gpproton** [comment]
Ok i already sent request for a more detailed document.

**Comment by gpproton** [comment]
Hi Anton i was able to get this attached tramigo document i feel might be useful in decoding new attributes from the devices.
Please take a look at it.

[Cloud_M2M_V2_specification_0.97 – ext-halt.pdf](https://github.com/traccar/traccar/files/2458203/Cloud_M2M_V2_specification_0.97.ext-halt.pdf)

**Comment by tananaev** [comment]
That's a completely different protocol.

**Comment by gpproton** [comment]
I was told it's just an update but however this is also tramigo protocol but I'll get more details on the changes and revert.

**Comment by gpproton** [comment]
Hi @tananaev i started testing out the new firmware for the device from the standard T23 to T24 and just as you said it looks completely new, from my test it didn't work at all. Below are the hex message received so you can decide what the next step is with the protocol, i'll provide any sample data possible. Thanks



##POWERCUT EVENT
1296400899: Input (PowerCut) on detected, parked, 1.50 km NW of Arepo, Ogun, NG, 6.70450, 3.41653, 01:00:06 Jan 1   EOF

80000100b0008b00010101e00382454d9ade2d5c313239363430303839393a20496e7075742028506f77657243757429206f6e2064657465637465642c207061726b65642c20312e3530206b6d204e57206f6620417265706f2c204f67756e2c204e472c20362e37303435302c20332e34313635332c2030313a30303a3036204a616e2031202020454f46

**Comment by tananaev** [comment]
Then it sounds like a different protocol to me. Do you have documentation?
