### ISSUE TITLE
Systemd Installation

### ISSUE THREAD

**Issue by neilromig** [traccar/traccar#2570]
In both 3.7 and 3.8 installation fails initially because Arch Linux is systemd only and has no /etc/init.d so it would be good if traccar.run checked for systemd or prompted during install so it doesn't fail.

**Comment by tananaev** [comment]
Does it have `/etc/rcX.d` folders?

**Comment by CVSz** [comment]
arch linux

```
Systemd
systemd is the default init framework, replacing initscripts. The services which are started by systemd can be found in the subfolders of /etc/systemd/system/. Services can be enabled using the systemctl command. For more information about systemd and how to write autostart scripts for it, see at systemd. To autostart scripts for specific users, see systemd/User.
```
[](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Examples)

**Comment by neilromig** [comment]
I think other distros like debian have a hybrid init setup, but Arch is purely systemd and has no init.d or rcX.d folders. All is done using systemd. Traccar 3.7 worked OK if I fooled traccar.run into thinking it was on debian by creating /etc/lsb-release, otherwise even setting USE_SYSTEMD was ineffective. Perhaps if the /etc/systemd hierarchy is present the install should create systemd .service files only?

**Comment by CVSz** [comment]
yes, i think but i'm not test on arch linux i see docs only
can you try to download traccar-other-3.8 and test again

**Comment by neilromig** [comment]
I have installed traccar-other-3.8, though it is not really an "installation" just unzipping the archive! It will start by running traccar.sh directly from /opt/traccar folder, but the systemd service file fails with no error messages, the journalctl says traccar started, and the file /tmp/traccar-pid still exists though no process present. I tried putting "cd /opt/traccar" into traccar.sh but still systemctl start fails.
I will try and find out the problem with systemctl...

**Comment by neilromig** [comment]
Update: I put "ExecStop=/opt/traccar/traccar.sh stop" into the service file and journalctl showed that systemd started and immediately stopped traccar, so I try using Type=forking and success! I am sure the service file needs some tweaks and I will work on this because I am new to Arch & systemd, perhaps somebody already knows how best to write systemd service file?

**Comment by CVSz** [comment]
can you check more setting at https://www.freedesktop.org/software/systemd/man/systemd.service.html#Examples

**Comment by neilromig** [comment]
I will check it out! 

My current traccar.service file is:

`[Unit]
Description=traccar
After=syslog.target

[Service]
Type=forking
ExecStart=/opt/traccar/traccar.sh start
ExecStop=/opt/traccar/traccar.sh stop
PIDFile=/tmp/traccar-pid

[Install]
WantedBy=multi-user.target
`

But I have had to put

`cd /opt/traccar`

into traccar.sh because the path names PATH_TO_JAR and PATH_TO_CONF are relative. If I change them to absolute then the java command runs but I cannot login to the web interface (?!?).

**Comment by tananaev** [comment]
New version of Traccar is using YAJSW to run Traccar as a native service. I don't think it supports systemd.

**Comment by BotoX** [comment]
I don't have a traccar.sh in the traccar folder?
I tried to run it like so:
```
$ bin/startDaemon.sh 
++++++++++ YAJSW SET ENV ++++++++++
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (build 1.8.0_112-b15)
OpenJDK 64-Bit Server VM (build 25.112-b15, mixed mode)
wrapper home : /opt/traccar
configuration: /opt/traccar/conf/wrapper.conf
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (build 1.8.0_112-b15)
OpenJDK 64-Bit Server VM (build 25.112-b15, mixed mode)
---------- YAJSW SET ENV ----------
++++++++++ YAJSW SET ENV ++++++++++
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (build 1.8.0_112-b15)
OpenJDK 64-Bit Server VM (build 25.112-b15, mixed mode)
wrapper home : /opt/traccar
configuration: /opt/traccar/conf/wrapper.conf
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (build 1.8.0_112-b15)
OpenJDK 64-Bit Server VM (build 25.112-b15, mixed mode)
---------- YAJSW SET ENV ----------
YAJSW: yajsw-beta-12.07
OS   : Linux/4.4.31-1-lts/amd64
JVM  : Oracle Corporation/1.8.0_112//usr/lib/jvm/java-8-openjdk/jre/64
Nov 22, 2016 11:19:53 AM org.apache.commons.vfs2.VfsLog info
INFO: Using "/tmp/vfs_cache" as temporary files store.
Nov 22, 2016 11:19:53 AM org.rzo.yajsw.os.posix.PosixService init
WARNING: Error /etc/init.d : is not a directory
************* STARTING traccar ***********************

Nov 22, 2016 11:19:53 AM org.rzo.yajsw.os.posix.PosixService getPid
INFO: wrapper pid file: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.rzo.yajsw.boot.WrapperExeBooter.main(WrapperExeBooter.java:49)
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at org.rzo.yajsw.os.posix.PosixService.start(PosixService.java:552)
	at org.rzo.yajsw.wrapper.WrappedService.start(WrappedService.java:402)
	at org.rzo.yajsw.WrapperExe.doStart(WrapperExe.java:488)
	at org.rzo.yajsw.WrapperExe.executeCommand(WrapperExe.java:158)
	at org.rzo.yajsw.WrapperExe.main(WrapperExe.java:124)
	... 5 more
```
But as you can see no success :(

I am on Archlinux.

**Comment by Abyss777** [comment]
There are two options:
- Install `systemd-sysv-generator` if it is available for ArchLinux that enable SysVinit compatiblity for systemd
- Instead of `traccar-linux-3.8.zip` use `traccar-other-3.8.zip` and use this `traccar.service` example https://github.com/tananaev/traccar/issues/2570#issuecomment-261789950

**Comment by BotoX** [comment]
I went for option two and it works fine, thank you!
Maybe a better idea to let systemd handle the java process directly instead of using the traccar.sh script
This way it could also autorestart it etc.

**Comment by tananaev** [comment]
The problem is that not all Linux distributions use systemd.

**Comment by kirantpatil** [comment]
Systemd is universal now [Redhat, CentOS, Fedora, Opensuse, Arch and so on], even in ubuntu from 16.04 onwards. IMHO it is better to have support for Systemd.

**Comment by neilromig** [comment]
Can I ask, for the sake of moving the PID file to its usual /var/run location can I just change the "/tmp" Java argument in traccar.sh to "/var/run" and relocate the PID file?

**Comment by tananaev** [comment]
@kirantpatil, I need some statistics. You are talking about latest versions of distros. There are many servers that run older versions or alternative distribution (especially in embedded world).

@neilromig, you can try. It would probably move some other files there as well.

**Comment by kirantpatil** [comment]
[Systemd](https://en.wikipedia.org/wiki/Systemd) adoption of major Linux distributions

![screenshot from 2016-11-24 12 02 46](https://cloud.githubusercontent.com/assets/1178055/20588812/1578279a-b23e-11e6-861a-3558e386f461.png)

**Comment by tananaev** [comment]
So, it was made default in 2015, and it's still not there for Gentoo. I think it's too early for full switch, but maybe it's a good idea to provide a separate installer for it. The main problem is that YAJSW doesn't support it.

**Comment by kirantpatil** [comment]
:+1:  for separate installer

**Comment by Abyss777** [comment]
If somebody interested, here is systemd service to use with wrapper:
````
[Unit]
Description=traccar
[Service]
Type=forking
WorkingDirectory=/opt/traccar
ExecStart=/usr/bin/java -Dwrapper.pidfile=/var/run/wrapper.traccar.pid -Dwrapper.service=true -Dwrapper.visible=false -Djna_tmpdir=/opt/traccar/tmp -jar /opt/traccar/wrapper.jar -tx /opt/traccar/conf/wrapper.conf
ExecStop=/usr/bin/java -Dwrapper.pidfile=/var/run/wrapper.traccar.pid -Dwrapper.service=true -Dwrapper.visible=false -Djna_tmpdir=/opt/traccar/tmp -jar /opt/traccar/wrapper.jar -px /opt/traccar/conf/wrapper.conf
PIDFile=/var/run/wrapper.traccar.pid
SuccessExitStatus=143
TimeoutStopSec=30
[Install]
WantedBy=multi-user.target
````

Exit code and timeout are adjusted to stop service correctly.

wrapper has some useful features, like writing log, detecting deadlocks and others.

**Comment by BotoX** [comment]
@Abyss777 Getting following error on a systemd only OS (Archlinux)
WARNING: Error /etc/init.d : is not a directory

It works fine after creating /etc/init.d - I guess this is a YAJSW bug(feature?) as it doesn't even touch the folder...
Just something to consider as not every distribution has a /etc/init.d directory.

**Comment by tananaev** [comment]
You can probably change directory using `wrapper.daemon.dir` parameter:

http://yajsw.sourceforge.net/YAJSW%20Configuration%20Parameters.html

**Comment by kirantpatil** [comment]
@BotoX any updates on @tananaev suggestion ?

**Comment by BotoX** [comment]
I just created /etc/init.d to solve the issue.
I guess you can change the path to some empty directory in the traccar install path. But the proper solution would be for YAJSW to fix this issue.

**Comment by kirantpatil** [comment]
@Abyss777,

I am using your traccar.service code and it is running fine, without any error as below.

Also observed that traccar file is present in /etc/init.d directory.
$ ls /etc/init.d/traccar 
/etc/init.d/traccar

I am using ubuntu 16.04.1 LTS.
$ cat /etc/issue
Ubuntu 16.04.1 LTS \n \l

Please let me know if you want me to check further with systemd related issues. 

$ sudo systemctl status traccar.service
● traccar.service - traccar
   Loaded: loaded (/lib/systemd/system/traccar.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2016-12-26 08:47:16 UTC; 23s ago
  Process: 5710 ExecStop=/usr/bin/java -Dwrapper.pidfile=/var/run/wrapper.traccar.pid -Dwrapper.service=true -Dwrapp
  Process: 5734 ExecStart=/usr/bin/java -Dwrapper.pidfile=/var/run/wrapper.traccar.pid -Dwrapper.service=true -Dwrap
 Main PID: 5749 (java)
    Tasks: 57
   Memory: 171.7M
      CPU: 9.812s
   CGroup: /system.slice/traccar.service
           ├─5749 java -Dwrapper.pidfile=/run/wrapper.traccar.pid -Dwrapper.service=true -Dwrapper.visible=false -Dj
           └─5765 java -classpath /opt/traccar/wrapperApp.jar:/opt/traccar/tracker-server.jar:/opt/traccar/lib/log4j

Dec 26 08:47:14 ip-172-31-4-64 java[5734]: Dec 26, 2016 8:47:14 AM org.rzo.yajsw.os.posix.PosixService startProcess
Dec 26 08:47:14 ip-172-31-4-64 java[5734]: INFO: calling java -Dwrapper.pidfile=/run/wrapper.traccar.pid -Dwrapper.s
Dec 26 08:47:14 ip-172-31-4-64 java[5734]: Dec 26, 2016 8:47:14 AM org.rzo.yajsw.os.posix.PosixService getPid
Dec 26 08:47:14 ip-172-31-4-64 java[5734]: INFO: wrapper pid file: /run/wrapper.traccar.pid
Dec 26 08:47:16 ip-172-31-4-64 java[5734]: Dec 26, 2016 8:47:16 AM org.rzo.yajsw.os.posix.PosixService getPid
Dec 26 08:47:16 ip-172-31-4-64 java[5734]: INFO: wrapper pid file: /run/wrapper.traccar.pid
Dec 26 08:47:16 ip-172-31-4-64 java[5734]: Dec 26, 2016 8:47:16 AM org.rzo.yajsw.os.posix.PosixService getPid
Dec 26 08:47:16 ip-172-31-4-64 java[5734]: INFO: wrapper pid file: /run/wrapper.traccar.pid
Dec 26 08:47:16 ip-172-31-4-64 java[5734]: Service traccar started
Dec 26 08:47:16 ip-172-31-4-64 systemd[1]: Started traccar.

ubuntu@ip-172-31-4-64:~$ tail -f /opt/traccar/logs/tracker-server.log 
2016-12-26 08:38:09  INFO: Character encoding: UTF-8 charset: UTF-8
2016-12-26 08:38:09  INFO: Version: 3.9-SNAPSHOT
2016-12-26 08:38:15  INFO: Starting server...
2016-12-26 08:47:06  INFO: Shutting down server...
2016-12-26 08:47:17  INFO: Operating system name: Linux version: 4.4.0-53-generic architecture: amd64
2016-12-26 08:47:17  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 25.111-b14
2016-12-26 08:47:17  INFO: Memory limit heap: 239mb non-heap: 0mb
2016-12-26 08:47:17  INFO: Character encoding: UTF-8 charset: UTF-8
2016-12-26 08:47:17  INFO: Version: 3.9-SNAPSHOT
2016-12-26 08:47:21  INFO: Starting server...

**Comment by Abyss777** [comment]
@kirantpatil thanks for feedback.

`/etc/init.d/traccar` likely was created by traccar installer

**Comment by jzahraoui** [comment]
I've made some modifications to run the service with another user.  I'm sharing this to help :

`sudo addgroup --system traccar
sudo adduser --disabled-password --system --home /opt/traccar --gecos "TracCar" --ingroup traccar traccar`

```

[Unit]
Description=traccar
After=syslog.target mysql.service
Wants = mysql.service

[Service]
RuntimeDirectory=traccar
RuntimeDirectoryMode=0755

User=traccar
Group=traccar

Type=forking
WorkingDirectory=/opt/traccar
# ExecStart=/opt/traccar/bin/traccar start sysd
# ExecStop=/opt/traccar/bin/traccar stop sysd

ExecStart=/usr/bin/java -Dwrapper.pidfile=/var/run/traccar/wrapper.traccar.pid -Dwrapper.service=true -Dwrapper.visible=false -Djna_tmpdir=/opt/traccar/tmp -jar /opt/traccar/wrapper.jar -tx /opt/traccar/conf/wrapper.conf
ExecStop=/usr/bin/java -Dwrapper.pidfile=/var/run/traccar/wrapper.traccar.pid -Dwrapper.service=true -Dwrapper.visible=false -Djna_tmpdir=/opt/traccar/tmp -jar /opt/traccar/wrapper.jar -px /opt/traccar/conf/wrapper.conf

PIDFile=/var/run/traccar/wrapper.traccar.pid
SuccessExitStatus=143
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target

```

**Comment by tananaev** [comment]
@jzahraoui, thanks for sharing the information.

**Comment by alexanderzatko** [comment]
I am trying to create a systemd drop-in, that would automatically restart the service after crash. The code above contains information I could use in my code, but judging from the fact that paths like /opt/traccar/conf/wrapper.conf no longer exist (at least in version: 4.2), it does not seem applicable any more.

This is what I have:
[Service]
Type=forking
GuessMainPID=yes
RemainAfterExit=no
Restart=no
RestartSec=5s

..but it does not work. Systemd can see the file, but after I crash the service, it does not start back up. Could somebody please give me some pointers about how to make this work?

**Comment by alexanderzatko** [comment]
.. more precisely, I am looking for values for these parameters:

PIDFile (URI)
ExecStart 
ExecStop

I "think" the value for the ExecStart and ExecStop is the same and looks like this: 
/opt/traccar/jre/bin/java -jar tracker-server.jar conf/traccar.xml

...but the PIDFile value I have no idea what that could be (running Ubuntu 14.04).

**Comment by tananaev** [comment]
Recent versions of Traccar use systemd by default.
