### ISSUE TITLE
Routes report view have problem ?

### ISSUE THREAD

**Issue by CVSz** [traccar/traccar#2574]
![image](https://cloud.githubusercontent.com/assets/4076926/20473201/9af98200-aff1-11e6-907b-695995ce455a.png)

![image](https://cloud.githubusercontent.com/assets/4076926/20473221/c952b1f8-aff1-11e6-8a08-6ce7314cfdf2.png)

**Comment by Abyss777** [comment]
Looks like device issue, it sends current and archive positions mixed.
What is device and protocol?

**Comment by CVSz** [comment]
Test on osmand in android 5.1  with traccar android client

**Comment by tananaev** [comment]
Are you using mixed location provider? If yes, try GPS only.

**Comment by CVSz** [comment]
Yes, and now im try gps only
