### ISSUE TITLE
How to upgrade the Windows traccaer 3.7 to 3.8 Server.

### ISSUE THREAD

**Issue by chandersharma** [traccar/traccar#2575]
How to upgrade the Windows traccaer 3.7 to 3.8 Server.
without losing any data.

if i install traccar 3.8 on windows server 2012 r2 then traccar service are not showing.

now i install the 3.7 which is working fine. but now i want to upgrade 3.7 to 3.8 

Thank you 
Chander Sharma

**Comment by CVSz** [comment]
Open task manager
stop traccar service
Close task manager
Backup traccar.xml
Install new version
Reinstall backup traccar.xml
Restart or Open task manager for start service

**Comment by tananaev** [comment]
To upgrade make sure you save database files and your config (if modified). Then just remove old version and install the new one.

Do you mean service doesn't show up in the services panel?

**Comment by chandersharma** [comment]
Do you mean service doesn't show up in the services panel?

Yes right .. Services are not showing in service panel.

**Comment by CVSz** [comment]
I see after install again in traccar service not show up if you close and open again now traccar service show sure bcoz i have t test 2 base server Ubuntu 16.1064bit and windows server 2012 r2with mssql

**Comment by tananaev** [comment]
@chandersharma, service should be there if installation was successful. Double-check everything carefully.
