### ISSUE TITLE
Problem connecting to mysql db

### ISSUE THREAD

**Issue by sefelectronics** [traccar/traccar#2576]
Hello there, I'm using version 3.7 but i also tried 3.8 but didn't work too, I didn't realize how to use console with new version though.
What I'm facing is a problem while trying to start the service with mysql db, the error it shows is about encoding

    jvm 1    | WrapperSimpleApp Error: Encountered an error running main:
    jvm 1    | WrapperSimpleApp Error: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.

If i use the default setting traccar start properly and i can track my device with no problem but it seems impossibile to stop the service and I need to reboot to stop it, it hangs waiting
There is also an error loading the wrapper 

    wrapper  | The value of wrapper.java.command does not appear to be a java binary.
    wrapper  | The use of scripts is not supported. Trying to continue, but some features may not work correctly..

I tried to force the actual path of java but the result is the same, what I've done in wrapper is 

    #wrapper.java.command=java
    set.JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.111-2.6.7.2.el7_2.x86_64/jre
    wrapper.java.command=%JAVA_HOME%/bin/java

this is my config

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
    <entry key='database.url'>jdbc:mysql://localhost:3306/traccar_db?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
    <entry key='database.user'>traccar_usr</entry>     
    <entry key='database.password'>******</entry>

By the way I've set in `my.cf` to use `innodb` as default `engine`. Chartset of db is `utf-8_general_ci`
Any help would be much apreciated

**Comment by tananaev** [comment]
What exactly is the error? Can I see full stack trace?

**Comment by sefelectronics** [comment]
here it comes

STATUS | wrapper  | 2016/11/21 11:35:54 | --> Wrapper Started as Console
STATUS | wrapper  | 2016/11/21 11:35:54 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/11/21 11:35:54 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/11/21 11:35:54 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/11/21 11:35:54 | 
WARN   | wrapper  | 2016/11/21 11:35:55 | The value of wrapper.java.command does not appear to be a java binary.
WARN   | wrapper  | 2016/11/21 11:35:55 | The use of scripts is not supported. Trying to continue, but some features may not work correctly..
STATUS | wrapper  | 2016/11/21 11:35:55 | Launching a JVM...
INFO   | wrapper  | 2016/11/21 11:35:55 | Java Command Line:
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[0] : /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.111-2.6.7.2.el7_2.x86_64/jre/bin/java
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[1] : -Dfile.encoding=UTF-8
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[2] : -Djava.library.path=../lib
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[3] : -classpath
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[4] : ../lib/wrapper.jar:../tracker-server.jar
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[5] : -Dwrapper.key=cgBlftMlKTCCulXJ
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[6] : -Dwrapper.port=32000
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[7] : -Dwrapper.jvm.port.min=31000
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[8] : -Dwrapper.jvm.port.max=31999
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[9] : -Dwrapper.pid=1894
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[10] : -Dwrapper.version=3.5.28
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[11] : -Dwrapper.native_library=wrapper
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[12] : -Dwrapper.arch=x86
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[13] : -Dwrapper.cpu.timeout=10
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[14] : -Dwrapper.jvmid=1
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[15] : org.tanukisoftware.wrapper.WrapperSimpleApp
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[16] : org.traccar.Main
INFO   | wrapper  | 2016/11/21 11:35:55 |   Command[17] : ../conf/traccar.xml
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:697)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:567)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1888)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1543)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2818)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:338)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at java.util.XMLUtils.getLoadingDoc(XMLUtils.java:102)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at java.util.XMLUtils.load(XMLUtils.java:74)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at java.util.Properties.loadFromXML(Properties.java:868)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at org.traccar.Config.load(Config.java:29)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:141)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/11/21 11:35:55 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:745)
STATUS | wrapper  | 2016/11/21 11:35:58 | <-- Wrapper Stopped

**Comment by tananaev** [comment]
Looks like you have some problem with your config. It's not a valid UTF-8 document. I guess whatever editor you used to edit it ruined the encoding.

**Comment by sefelectronics** [comment]
i just edited it with winscp editor

**Comment by tananaev** [comment]
Well, it's an invalid document now. As far as I know WinSCP is not a text editor.

**Comment by sefelectronics** [comment]
what I meant I used the editor that winscp opens when you double click on a file, anyway the problem was with a character in the password `£` which was transformed and made xml file have a bad formatting, now it seems to work. Thanks for pointing me in the right direction!

**Comment by CVSz** [comment]
@stevenbouma if you used winscp to edit config file do not used double click and used right click select edit before edit check encoding

**Comment by stevenbouma** [comment]
@CVSz wrong user reference?
