### ISSUE TITLE
ACLs / Company Accounts

### ISSUE THREAD

**Issue by amenk** [traccar/traccar#2577]
Is it possible to define sub-accounts in one installation which can only view the tracking data, but for example not edit devices? Or define other limited access rights?

If not, is this planed?

**Comment by tananaev** [comment]
Yes, it is possible. You can share device between user account. Some user accounts can be marked as readonly which would not allow them to edit anything except their own user settings.

**Comment by kirantpatil** [comment]
@tananaev, where is that opiton to mark user accounts as readonly. From admin login I tried to edit user account but could not find any checkbox related to "Readonly". Below is screenshot.

![screenshot from 2016-11-22 11 16 04](https://cloud.githubusercontent.com/assets/1178055/20512451/6ea0dcf8-b0a5-11e6-8693-fb3f86371d0b.png)

**Comment by tananaev** [comment]
Well, you have to install the latest version of Traccar first.

**Comment by kirantpatil** [comment]
@tananaev do we have anywhere Changelog maintained for each version, so that it will be easy for us to see the list of features added or removed from the version.

**Comment by tananaev** [comment]
Yes we do:

https://www.traccar.org/blog/category/releases/

**Comment by kirantpatil** [comment]
@tananaev Thanks.
