### ISSUE TITLE
Time different

### ISSUE THREAD

**Issue by tanask** [traccar/traccar#2581]
There two different reading in time in V3.8 and in the previous volumes
If you ask the program to show route data it will display the data including the time. In this data the  time will read as the time set in the computer which is correct 
But if you export the the data the time will be different not the same, why? how to correct this problem?
[Report time.docx](https://github.com/tananaev/traccar/files/605761/Report.time.docx)

**Comment by tanask** [comment]
There two different reading in time in V3.8 and in the previous volumes
If you ask the program to show route data it will display the data including the time. In this data the time will read as the time set in the computer which is correct
But if you export the the data the time will be different not the same, why? how to correct this problem?
Report time.docx

**Comment by tananaev** [comment]
The issue is that server timezone might not be the same as client and excel reports are generated on the server side.

@Abyss777, any ideas on how to fix it? I'm thinking that we should tell server timezone somehow. Maybe there is a standard way? Then we can use that timezone for report generation.

**Comment by Abyss777** [comment]
@tananaev l see two options:
- Pass client browser timezone as request parameter
- Handle user attribute like `report.timezone`

**Comment by tananaev** [comment]
Another idea... can we reuse timezone from existing attributes? We already send full ISO time with timezone, right?

**Comment by Abyss777** [comment]
Good idea, I'll try to investigate it.

**Comment by tanask** [comment]
I think if we can tell the report (excel) read the time from the table written in (show route data)

**Comment by Abyss777** [comment]
@tananaev unfortunately we send time in UTC
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString

> The timezone is always zero UTC offset, as denoted by the suffix "Z".

**Comment by Abyss777** [comment]
@tananaev I have a draft of solution:
- Send date in ISO format, but with timezone `Ext.Date.format(from, 'c')`
- Catch it on the server side and calculate difference between server timezone and `from` timezone
- Pass `timezoneOffset` to excel template
- Only not very nice thing is that cell template will look like: `${new("java.util.Date", position.fixTime.getTime() + timezoneOffset)} `

**Comment by tananaev** [comment]
I think we should pass around `TimeZone` object and using it for formatting instead of raw offset.

**Comment by Abyss777** [comment]
joda time is much more convenient, i used `DateTimeZone timezone` and cell become like this
`${new("org.joda.time.DateTime", position.fixTime, timezone).toString("YYYY.MM.dd HH:mm:ss")}`

Offtopic, Why don't we use joda time everywhere?

**Comment by tananaev** [comment]
In most cases standard java classes are enough. Do you have any examples where we can benefit from joda time? I don't mind changing it.

**Comment by Abyss777** [comment]
You are right. Only a couple places where we do something more difficult than `new Date()`

**Comment by tanask** [comment]
Dear Anton
May I offer some help in translation
The Arabic language is not correct and some words are not translated
Can you tel me where and how to do better translation (in which file)
Thank you
Tanas

**Comment by tananaev** [comment]
You can fix localization here:

https://www.transifex.com/traccar/traccar/
