### ISSUE TITLE
Vehicle Icon disappears occasionally on map but text remains in 3.8

### ISSUE THREAD

**Issue by JohnnyDevine** [traccar/traccar#2585]
I upgraded to 3.8 and noticed occasionally the vehicle icon disappears from the map but the text remains, never saw this happen in 3.7

JD

**Comment by Abyss777** [comment]
There was implemented various vehicle icons in 3.8.
Please check if you correctly upgraded and have icons in `./traccar/web/images`
If yes, try to clear browser cache.

**Comment by kirantpatil** [comment]
This happened to me when using Android Webview app. If I just touch on map icon reappeared.
