### ISSUE TITLE
Reverse Geocoding

### ISSUE THREAD

**Issue by wolfbgn** [traccar/traccar#2605]
Hi, Mr. Tananaev.
I have two PCs running Traccar 3.5. The only reverse geocoder that works is Google.
Third machine is running Traccar 2.12. Nominatim works.

**Comment by tananaev** [comment]
What nominatim server are you using? What's the path in the URL?

**Comment by wolfbgn** [comment]
I use the server you provided with the original configuration file

**Comment by tananaev** [comment]
Never use that one for production. It's only for testing.
