### ISSUE TITLE
Geofences, Live Routes, Follow button status not visible

### ISSUE THREAD

**Issue by kirantpatil** [traccar/traccar#2607]
Geofences, Live Routes, Follow button status not visible to know whether they are in ON or OFF state.

Please find the below screenshot.

![screenshot from 2016-11-26 14 56 21](https://cloud.githubusercontent.com/assets/1178055/20639429/e5461a58-b3e8-11e6-8916-c926fe23af25.png)

**Comment by tananaev** [comment]
They are visible for me:

![screen shot 2016-11-26 at 10 52 11 pm](https://cloud.githubusercontent.com/assets/1161863/20639523/0451c0fe-b42b-11e6-94ae-f063ff80b284.png)

Not that obvious, but that's the standard theme. Background for enabled and disabled options is slightly different.

**Comment by kirantpatil** [comment]
On mobile phone it is very hard to make distinction.

**Comment by tananaev** [comment]
I guess we would have to modify some styles to make it more visible.
