### ISSUE TITLE
[Feature Request] SMTP Email test function

### ISSUE THREAD

**Issue by JohnnyDevine** [traccar/traccar#2609]
It would be nice to have an email test function to check all is OK with emil setup etc

JD

**Comment by tananaev** [comment]
I agree, it would help with configuring SMTP.

**Comment by JohnnyDevine** [comment]
indeed and many thanks, saves me having to drive the car as a test every time :)

**Comment by tananaev** [comment]
We already have an option to test notifications, including emails.
