### ISSUE TITLE
Trip Log Report

### ISSUE THREAD

**Issue by rdentandt** [traccar/traccar#2615]
Hi Guys,

I am having an issue where my trip log report is not showing street addresses on all entries. Some entries only have start address, other entries only have end address. There is no single entry with both?

Any assistance would be appreciated.

Thanks

**Comment by tananaev** [comment]
Have you configured reverse geocoding on your server?

**Comment by rdentandt** [comment]
Hi Anton

Yes, it is activated as it displays the address for some entries but not
all.

Thanks

**Comment by tananaev** [comment]
Well, it means that trips report is trying to use those positions that don't have address in your case.
