### ISSUE TITLE
IDD213-N Not receiving data

### ISSUE THREAD

**Issue by ngill4492** [traccar/traccar#2631]
Hello, 

I have installed the Traccar server on an ubuntu instance in AWS.  When I try connecting routing my OBD IDD213-N product to it nothing occurs.  I am wondering why this might be happening.  I've allowed port 5086 to been seen/open from outside sources. 

I've also tried it on Demo4 as well with no results.  

Does anybody know why this isn't working? 

Thank you, 
Nathan Gill

**Comment by tananaev** [comment]
Check this guide:

https://www.traccar.org/troubleshooting/
