### ISSUE TITLE
How to change address data to route name

### ISSUE THREAD

**Issue by tanask** [traccar/traccar#2642]
Dear all
Need your help to explain to me how to change the address to rout name instead of a map location

![address-1](https://cloud.githubusercontent.com/assets/23650952/20869182/a2227594-ba75-11e6-8bd4-9d08440804a6.png)

**Comment by tananaev** [comment]
Do you have reverse geocoder set up on the server?

**Comment by tanask** [comment]
How to do this?

**Comment by tananaev** [comment]
In the config file:

https://www.traccar.org/reverse-geocoding/
