### ISSUE TITLE
Tolerance for moving alerts

### ISSUE THREAD

**Issue by paraisotech** [traccar/traccar#2644]
I think it will be usefull if you create a parameter to adjust the tolerance within the movement event notification. When the sky is not clean or when the device is under a building for example, the gps singal became unstable and get many changes in a minute. And if there is no tolerance to deal with all this "position changes" the server is going to notify all of them, even if the car is phisicaly in the same place, but sufferring with gps unstable signal. So we'll have fake move events notifications...

**Comment by tananaev** [comment]
You can adjust speed using `event.motion.speedThreshold` parameter.
