### ISSUE TITLE
Total distance calcs

### ISSUE THREAD

**Issue by paraisotech** [traccar/traccar#2659]
How does the system calculates the total distance for a device? Not a issue at all, just a question...

**Comment by tananaev** [comment]
It is calculated based on the reported coordinates.

**Comment by cdmarioe** [comment]
is there any file or form to do it across database?

**Comment by tananaev** [comment]
I don't have any existing scripts, if that's what you are talking about. But it should be possible to do it with a relatively simple script.

**Comment by paraisotech** [comment]
But I think it would be something very hard to calculate. Imagine 300 users
calculating simultaneously. Maybe I have the script in PHP somewhere, that
converts the latitude and longitude values to meters... If you want or need
it, I can try to find it.

Em 26 de mai de 2017 9:04 PM, "Anton Tananaev" <notifications@github.com>
escreveu:

**Comment by tananaev** [comment]
I was not talking about live calculation. I was talking about doing it once.
