### ISSUE TITLE
[traccar-3.8] Found popup error "Not found exception" in the first page while is loading .

### ISSUE THREAD

**Issue by biskandar** [traccar/traccar#2661]
I have upgraded from traccar 3.6 to 3.8 .
I launched it with development box and access it with http://localhost:8082 , it run perfectly fine .

But when i deployed into the live server , it found popup error "Not found exception" and the login page is never raised after that, and I have checked the javascript console : found unreachable code after return statement at file ext-all-debug.js:45508:8 , do you why this is happen ? can you help me .

Cheers,
/Benny

**Comment by tananaev** [comment]
I need a screenshot of the error and console. Ideally it should be a debug version of the web interface.
