### ISSUE TITLE
deviceUnknown event

### ISSUE THREAD

**Issue by paraisotech** [traccar/traccar#2673]
How can i debug the logs or the database content in order to discover what kind of alarm the device sent to the server, and with this information try to give a correct name or create a new attribute to translate this deviceUnknown event in a known device event?

**Comment by tananaev** [comment]
This event means that device moved to "unknown" (yellow) state.

**Comment by paraisotech** [comment]
Oh great. Seems that the server has not yet decided if the device is online or offline...

**Comment by tananaev** [comment]
It usually happens when device doesn't send data for some time (by default 10 minutes).
