### ISSUE TITLE
ADD EVENTS GPS103 PROTOCOL

### ISSUE THREAD

**Issue by vipien** [traccar/traccar#2683]
Hello @tananaev , I would like to add some events for the gps103 protocol, but I'm not sure what the default should be for the names of these, I'm attaching the manual that sends me directly, so you can see section 3.1 and there to take account for example When a command is sent and the response arrives, think of something like ALARM_MOVEMENT_ENABLE for example. But I'm not sure. I await your comments to start adding them.
[COBAN GPRS PROTOCOL_20141212.pdf](https://github.com/tananaev/traccar/files/650024/COBAN.GPRS.PROTOCOL_20141212.pdf)

**Comment by tananaev** [comment]
Traccar already supports alarms for GPS103 protocol.

**Comment by vipien** [comment]
Yes, but not support responses from GPRS commands. Please ser 3.1 section.

**Comment by tananaev** [comment]
So, you asking for commands, not for events. Is that correct?

**Comment by vipien** [comment]
Yes, responses for commands. For example. I send a speed config to GPS, And
it respond that its Ok.

**Comment by tananaev** [comment]
That's not what I said. What you pointed out in the document is referring to commands, not "responses for commands". Please explain properly what you are looking for.

**Comment by vipien** [comment]
The boxes on the left are the commands from the server to the gps but the
boxes on the right are the responses from gps to the server

**Comment by tananaev** [comment]
OK, it looks like command responses. Those should be decoded as `KEY_RESULT` in the position. Traccar will automatically generate command response for those. Note that it's not possible to specify any additional information with this event.
