### ISSUE TITLE
Cannot calculate Distance properly in Report( Drives and stops)  in traccar 3.7 version.

### ISSUE THREAD

**Issue by sdip025** [traccar/traccar#2697]
I am using traccar 3.7.I attached a device which is running properly.I  also used speedLimit .But when i  wants to generate Report(Distance & Stop) for this particular device ,Cannot match Distance which  shown in web.
I am calculation it Timeduration(hr) * Speed(km/h).
My calculation is not match as per Report data.

How to solve this ?

**Comment by tananaev** [comment]
Please provide a screenshot of the report.
