### ISSUE TITLE
Disable New User Registration

### ISSUE THREAD

**Issue by Turbovix** [traccar/traccar#2700]
Anton, today I realized that even if I disable the option to register new users in the server settings, it is still enabled.
I tried to deactivate directly in the database but it has no effect, do you have other reports of Traccar users?

**Comment by tananaev** [comment]
There issue has been fixed in https://github.com/tananaev/traccar-web/issues/356.

As a workaround you can disable it in the database and restart service for changes to apply.

**Comment by Turbovix** [comment]
Thanks, I forgot to restart the server!

**Comment by negamkpk** [comment]
Hi,

tananaev/traccar-web#356
<https://github.com/tananaev/traccar-web/issues/356>. i referred in this
page.
It mention three files need to update in the web folder.
Could you tell me which files to update.

**Comment by tananaev** [comment]
@negamkpk, look at the commit linked to the issue.
