### ISSUE TITLE
Improved network location service

### ISSUE THREAD

**Issue by tananaev** [traccar/traccar#2703]
I have started working on better support for non-GPS locations. Some devices send multiple cell tower info, some even send WiFi access points information. We have to support it in Traccar.

**Comment by tananaev** [comment]
First commit (12e88e5cccc00eb5882124db9e0350ae568902e6) adds two new fields to the `Position` model:

- accuracy - position accuracy in meters
- network - information about cell and WiFi networks (serialized as JSON)

Both Mozilla and Google use very similar models for Geolocation requests, so I decided to use the same model for Traccar:

https://mozilla.github.io/ichnaea/api/geolocate.html
https://developers.google.com/maps/documentation/geolocation/intro

**Comment by d33pak-s1ngh** [comment]
awesome thank you for this so if i will upgrade to 3.9 now i can get these accuracy and network updates?

**Comment by tananaev** [comment]
It's not implemented yet. It will be available in version 3.10.

**Comment by d33pak-s1ngh** [comment]
waiting for it best of luck.

**Comment by tananaev** [comment]
This has been available for a while now.
