### ISSUE TITLE
device offline

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2715]
how do i know device got  offline while using socket. i am getting event for device online but not for offline.
 when i  start service status  from my mobile i got device online but when i stop service i am not getting device offline event.

**Comment by tananaev** [comment]
Offline status is not supported for OsmAnd protocol because of the nature of HTTP communication.

**Comment by d33pak-s1ngh** [comment]
so all mobile devices use OsmAnd protocols? is there any other way to do it.

**Comment by tananaev** [comment]
Yes, all devices that use OsmAnd protocol. Also, all devices that use UDP protocol as well. There is still "unknown" (yellow) state that works for all devices.

**Comment by d33pak-s1ngh** [comment]
yes i always got status unknown for offline devices.
