### ISSUE TITLE
H02 Protocol PDF from Manufacturer 

### ISSUE THREAD

**Issue by joepr** [traccar/traccar#2717]
Hello Forum

I own a few LK106 trackers. I did contact the manufacturer and they send me this PDF with the complete protocol supported by this H02 device. 

After playing around with their Demo GPS Management website http://www.zg666gps.com I notice a few interesting things Like:
1. Change the report time in seconds works directly on the website and I receive a acknowledge 
![image](https://cloud.githubusercontent.com/assets/10345032/21370992/26daeade-c6e5-11e6-9c80-b29f324028e5.png)

![image](https://cloud.githubusercontent.com/assets/10345032/21371143/f273b3b0-c6e5-11e6-98ca-626bbec699b9.png)

2. Get an **Audible alert** on the website when the **SOS button** is pressed on the device! 
![image](https://cloud.githubusercontent.com/assets/10345032/21371035/62298eb0-c6e5-11e6-8809-49b855c2cf65.png)

It would be amazing to have such great option like the SOS audible or at least alert at the Traccar platform. Hope this helps the support team and developers here to better understand how the H02 protocol works. 

[LKGPS protocol.pdf](https://github.com/tananaev/traccar/files/664942/LKGPS.protocol.pdf)

Manufacturer
http://lk-gps.com/e_productshow/?14-Waterproof-GPS-Tracker-LK106-14.html

**Comment by tananaev** [comment]
Both things that you are requesting are already available in Traccar.

**Comment by joepr** [comment]
Tananaev

Thats amazing! I guess I'm using a old version of traccar on my server.  

Could I test this features on the online demo to see how it works?

**Comment by tananaev** [comment]
Yes, you can.

**Comment by joepr** [comment]
I will try them right away . From which version have been available?

**Comment by tananaev** [comment]
This protocol has been available for some time.

**Comment by joepr** [comment]
I really appreciate your hard work. I'm testing it right now at demo4 and its working excellent. Is there a way the **SOS sound** could be changed when installed on my local server?

**Comment by tananaev** [comment]
You can just replace the sound file with your own one.

**Comment by joepr** [comment]
Hello tananaev

Quick question regarding sound file. I did try to replace the beep.wav located in /opt/traccar/web . I place the same owner and group however I don't hear the sound. 

I restarted traccar. I see the alarm popup but no sound. 

Is there a format, size or configuration I need to know to setup the .wav file?

Thanks!
