### ISSUE TITLE
can't execute ./traccar.run with centos 7 | traccar 3.9

### ISSUE THREAD

**Issue by AymenSlimi** [traccar/traccar#2726]
Hi all,
Whene i execute ./traccar.run i have errors and this is the output:
```
Verifying archive integrity... All good.
Uncompressing traccar  100%
++++++++++ YAJSW SET ENV ++++++++++
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
wrapper home : /opt/traccar
configuration: /opt/traccar/conf/wrapper.conf
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
---------- YAJSW SET ENV ----------
++++++++++ YAJSW SET ENV ++++++++++
/opt/traccar/bin/setenv.sh: line 44: java: command not found
wrapper home : /opt/traccar
configuration: /opt/traccar/conf/wrapper.conf
/opt/traccar/bin/setenv.sh: line 56: java: command not found
---------- YAJSW SET ENV ----------
/opt/traccar/bin/wrapper.sh: line 7: java: command not found
```
after investigation : line 44, line 56 and line are "$java_exe" -version
I tryed  to add java_exe=java as an envirment variable  but same error.
is there a solution for that thanks.

centos 7.3
traccar 3.9

**Comment by tananaev** [comment]
Looks like you don't have Java installed, or it's not configured properly.

**Comment by AymenSlimi** [comment]
this is my profile config for java:

export JRE_HOME=/opt/jdk1.8.0_111/jre
export JAVA_HOME=/opt/jdk1.8.0_111
export PATH=$PATH:$JAVA_HOME/bin
export CLASSPATH=$JAVA_HOME/jre/lib/ext:$JAVA_HOME/lib/tools.jar

And java -version work correctly

**Comment by tananaev** [comment]
It works correctly in your shell, but is it configured globally? Remember that service is run from root user in completely different shell.

**Comment by AymenSlimi** [comment]
but i configured java in profile using root user. it's not enough? how chould i configure it

**Comment by tananaev** [comment]
Why don't you just install Java standard way? It works just fine for me on CentOS. Obviously something is misconfigured.

**Comment by marsu211** [comment]
HI,
I have exact the same issue while installing a complete fresh instance on a newly installed Ubuntu.
I can't find where the error is, I re-installed all possible versions of Java too.
Did not have this issue with 3.7 and below.
Brgds
Patrick

**Comment by tananaev** [comment]
@marsu211, you don't need to install all possible versions of Java. You just have to install default version using standard package manager. Most of my server are using various versions of Ubuntu and there were no issues whatsoever. How did you install Java?

**Comment by marsu211** [comment]
Thank you Anton
in the meantime I found the reason and fixed it. Maybe to tired for working on this now.

It's so perfect.
Thx
