### ISSUE TITLE
Traccar Demo Server-4 crashes browser - test it on 3 different computers

### ISSUE THREAD

**Issue by joepr** [traccar/traccar#2728]
**Hello Anton**

Just want to inform that the last 2 days every time I use the demo4.traccar.org my chrome , firefox browser crashes specifically when I click on 1 of the 2 trackers (pet tracker) I have on the system. It's a strange behavior . I even test it on my mobile phone browser and does the same issue.  
 
![image](https://cloud.githubusercontent.com/assets/10345032/21458387/6821ce76-c90c-11e6-9ce6-7a151e9c1190.png)

**Comment by tananaev** [comment]
Can you please provide access to your account, so I can check it myself. My email address is in profile.

**Comment by joepr** [comment]
Done! please check your email

**Comment by tananaev** [comment]
Looks like your device sent some invalid data that breaks OpenLayers library:
```json
{
   "fixTime":"2063-12-23T08:04:03.000Z",
   "deviceTime":"2063-12-23T08:04:03.000Z",
   "outdated":false,
   "valid":false,
   "latitude":-6.8056469327705764E+38,
   "longitude":-6.8056469327705764E+38,
   "altitude":-6.8056469327705764E+38,
   "speed":137.68903500000002,
   "course":0.0,
   "protocol":"minifinder",
   "deviceId":1996,
   "id":0,
   "attributes":{
      "gsm":2,
      "charge":false,
      "battery":"4",
      "sat":"255",
      "ip":"209.198.195.41",
      "distance":0.0,
      "totalDistance":5224692.05
   }
}
```

**Comment by joepr** [comment]
The device is using the MinifinderPico protocol on port 5062. 
Is there something I need to modify on the device? 
It worked fine for 2 days. At this moment battery is dead but I'm charging it.

**Comment by tananaev** [comment]
I have restarted the service. Hopefully it helps.

The problem seems to be with the device, so I would recommend checking with vendor support.

**Comment by joepr** [comment]
I will test it for a few more days to see if the same issue happens again. 

Thanks for the support.
