### ISSUE TITLE
Command Sample

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2729]
How do we send commands to device i can see following menu on webinterface
![command](https://cloud.githubusercontent.com/assets/23626544/21466917/32b93834-c9ff-11e6-83f5-2aab501a8dc9.png)
 but i dont know what command to pass.

 for osmand protocol there is no file for command list and i think mobile devices are using osmnd protocol.
![osmnd](https://cloud.githubusercontent.com/assets/23626544/21466947/9bdd71a8-ca00-11e6-9878-cdf493a02210.png)

**Comment by tananaev** [comment]
For custom command you can either use text or HEX format, depending on the protocol. OsmAnd protocol does not support commands.

**Comment by d33pak-s1ngh** [comment]
I am using a device with protocol gt06 which is listed in protocol list what i can see in pdf files listed for gt06 protocol is only foramt of packets send and recieved by server or device.
![proto](https://cloud.githubusercontent.com/assets/23626544/21536935/a76ba3d4-cdaf-11e6-8541-2d773b06261f.png)

and i can see some command like in following image 
![coomnd](https://cloud.githubusercontent.com/assets/23626544/21536960/f344b246-cdaf-11e6-9a5d-0953507bab0a.png)

i have found only these three commands in pdf.
Function                                           Command 
Looking Up Location Information     DWXX#
Cutting Oil and Electricity                 DYD#
Connecting Oil and Electricity          HFYD#

So question is where i can find complete list of commands supported by gt06 protocol.

**Comment by tananaev** [comment]
I thought the question was about OsmAnd.

Have you tried to send `DWXX#` as a custom command?

**Comment by d33pak-s1ngh** [comment]
I will try and inform you right now device is offline so i cant send commands.
