### ISSUE TITLE
Only when the device is offline or online to send events?

### ISSUE THREAD

**Issue by gpsim** [traccar/traccar#2736]
Hello tananaev, report a small problem,
Always online equipment will be repeated in a specified period of time to send the online state event. In fact, the device is not offline, is not the state of the timeout settings to force the system to reconnect the device?
I think this may not be reasonable, this event allows users to feel the device is not normal offline.
In the event that the timeout detection does not send the event, only when the device is offline or online to send events?
```java
    private static final long DEFAULT_TIMEOUT = 600;
```

**Comment by tananaev** [comment]
It's really hard to understand what you mean. There is an unknown event, if that's what you are asking/talking about.

**Comment by gpsim** [comment]
Sorry, my English is not good。
You look at database data.
This is the event of a device, the device is always on the line, but the repeated cycle of sending the online state

id type servertime deviceId positionid geofenceid attributes
3185958 deviceOnline 2016-12-28 15:58:29 17 null null {} 
3183161 deviceOnline 2016-12-28 15:09:20 17 null null {} 
3181480 deviceOnline 2016-12-28 14:24:03 17 null null {} 
3178295 deviceOnline 2016-12-28 13:30:24 17 null null {} 
3175655 deviceOnline 2016-12-28 12:33:45 17 null null {} 
3174175 deviceOnline 2016-12-28 11:40:13 17 null null {}
3171120 deviceOnline 2016-12-28 10:54:02 17 null null {} 
3169172 deviceOnline 2016-12-28 10:10:21 17 null null {} 
3168337 deviceOnline 2016-12-28 09:25:14 17 null null {} 
3166538 deviceOnline 2016-12-28 08:37:51 17 null null {} 
3164421 deviceOnline 2016-12-28 07:35:46 17 null null {} 
3162587 deviceOnline 2016-12-28 05:25:17 17 null null {}
3160691 deviceOnline 2016-12-28 02:21:10 17 null null {} 
3159241 deviceOnline 2016-12-27 23:55:23 17 null null {} 
3156618 deviceOnline 2016-12-27 21:54:21 17 null null {}

**Comment by tananaev** [comment]
How did you select this sample? I can see that ids are not sequential.

**Comment by gpsim** [comment]
There are multiple devices, I just screening this one device and arranged in descending order of ID

SELECT * FROM `events` WHERE `deviceid` =17 ORDER BY `id` desc limit 100
It will be found that the repeat loop sends an online event

**Comment by tananaev** [comment]
It can happen if you reboot your server. It can also happen if you are using older version of Traccar which doesn't support "unknown" event.

**Comment by gpsim** [comment]
Did not restart the server, using the latest version,
Because the device has always been online, and there is no offline, repeat the on-line event, I think it is not reasonable.

**Comment by tananaev** [comment]
I would need access to the server to check.

**Comment by gpsim** [comment]
<entry key='event.statusHandler'>true</entry>
You open the event state processing, wait for a period of time, view the database event table, you should be able to see a lot of recurring online events.

**Comment by tananaev** [comment]
What protocol are you using?

**Comment by tananaev** [comment]
Are you sure you are using latest official release without any modifications to the code or config? If not, I need to know all the details.

**Comment by gpsim** [comment]
Estimation and agreement does not matter, for now, gt02 gt06 is the case. On the basis of your version changed the web layer, it should not affect, if you are willing to help. I can build a new service to let you see, in the use of the log is too big.

**Comment by tananaev** [comment]
I'm willing to help if it's a valid issue. Please prepare a service to reproduce the issue if you can.

**Comment by gpsim** [comment]
OK, thank you, I first set up the service, waiting for equipment to collect some event data, the service and information sent to your mail.

**Comment by tananaev** [comment]
Sounds like a plan, thanks.

**Comment by gpsim** [comment]
I installed a new service, turned 2 devices in the past, and did not find the situation before, strange.
Does this have anything to do with my previous upgrade, only to upgrade track-server.jar?

**Comment by tananaev** [comment]
Possibly.
