### ISSUE TITLE
upgrade from 3.2 to 3.9

### ISSUE THREAD

**Issue by snoop168** [traccar/traccar#2741]
I am trying to upgrade from 3.2 to 3.9. I first installed 3.3 and started the service and logged into the web interface once. I see there are 2 new DB tables related to schema updates. I then stopped 3.3 service, deleted the traccar directory and then installed 3.9 and started the service using the new .sh file. I realized I had an issue with my MYSQL connection url which I guess changed slightly since I first set it up.  
`sessionVariables=sql_mode=ANSI_QUOTES` changed to `sessionVariables=sql_mode=''` at the end. Not sure if that was an issue but changing to the 2 single quotes resolved an issue starting tracker service initially. 

So now I am able to get traccar service to start but I cannot load the web interface now...  If I check for open ports on my server I do not see anything listening on 8082

**Comment by tananaev** [comment]
Change in the database URL shouldn't affect anything.

If server is not listening on the port, it means that either something wrong with config file, or service is not running. Is it running?
