### ISSUE TITLE
DriverID

### ISSUE THREAD

**Issue by integreated** [traccar/traccar#2742]
Hi Anton
I am using 3.9 and have teltonika fm1100 setup to send driver id.
The issue I am having is that when I touch the key on the dallas it will send the id fine but when the next packet is received the id reverts back to the lowest number in the list which in my case is 0 (no logon).
If I hold the key on the dallas it will show the correct driver id.
Is it possible to add a command to tell the server to ignore dallas after the first read until the ignition is turned on again?
Regards
Mark

**Comment by tananaev** [comment]
I think it can be done as a customization.

**Comment by integreated** [comment]
Hi Anton
I'm no software specialist so could you give me an idea of the kind off command I would need and where to put it.I'm guessing it would be in the traccar.xml but I don't know.
Regards
Mark

**Comment by tananaev** [comment]
Source code has to be modified, it's not just configuration. Send me an email if you need help with it.
