### ISSUE TITLE
Create Device Category

### ISSUE THREAD

**Issue by nickiles** [traccar/traccar#2745]
Is there a way to amend the device category list and associated icons? This would allow people to add their own icons.

**Comment by tananaev** [comment]
It's possible with some simple code modifications. You have to modify `DeviceImages` store. Note that it has to be an SVG image and in the store you have to specify ids of various elements inside the SVG file.

**Comment by nickiles** [comment]
Hi, Sorry - so I have icons for other vehicles such as tractor/4x4/ATV/Van etc

I have modified the store for Device Images but can't seem to see how to add the 'Categories' so that when you edit the vehicle you can select them.

Nick

**Comment by tananaev** [comment]
Can we see the images?

As long as you've added them to `DeviceImages` class, it should work. I guess some parameters are incorrect if you don't see them. Also, if you are using release version, have you compiled a minified version of the web interface?

**Comment by nickiles** [comment]
Have amended /store/DeviceImages.js - do i now need to recompile?

I can't attach to the thread SVG files, so have dropped them across via email

Nick

**Comment by tananaev** [comment]
You can find minification script in the `tools` folder:

https://github.com/tananaev/traccar-web/tree/master/tools

**Comment by nickiles** [comment]
are there any dependencies needed to run the script?

**Comment by tananaev** [comment]
Yes, you need extjs and sencha cmd.

**Comment by nickiles** [comment]
Will try this shortly. Do you think it would be possible to add as a feature the ability to edit the categories and associated icons so they can be user defined?

**Comment by nickiles** [comment]
So I ran the minify command - all completed ok with no errors - however  no obvious changes - I changed files as per #368 which looks to be exactly the same kind of change - do I need to do a full compile from source?

**Comment by nickiles** [comment]
Script did create the .js file- is there an extra step I need to do- I stopped and started the server. To be clear as per issue 368 I updated the DeviceImages store, the en json etc

**Comment by nickiles** [comment]
have found the issue - app.min.js is zero size after running minify - need to look at why its failing.

**Comment by nickiles** [comment]
Just run again after updating paths in minify.sh, still generating zero sized file, any ideas?

**Comment by nickiles** [comment]
Solved it - was a permissions issue on tracer folder - now got the extra category image options appearing when editing a device - only issue now is to do with once set the icon image disappears on the map for one of the new icons - suspecting this is an SVG file format issue maybe.

**Comment by tananaev** [comment]
I guess there is some problem with your SVG files. That's why I said it's not that easy to create your own icons. You need to know correct element ids inside the SVG file.

**Comment by nickiles** [comment]
So I have it all working with extra icons - basically ended up using one of the existing template icons and copying in the design elements at code level to it to make it work - thats the beauty of SVG files.  Thanks for support. By the way have found a few license free icons which am happy to map into the right format if you want?

**Comment by tananaev** [comment]
I'm happy to add more icons as long as they look good and consistent with current ones.

**Comment by nickiles** [comment]
Will get some done where I can locate suitable license free images.

**Comment by Tech2life** [comment]
hey Anton,
I've tried to changed icons in the devices categories with other SVG icons, and they disappear from the drop down list, is their a specific tool that I need to generate my SVG icons with or there is other why of doing so ?

**Comment by tananaev** [comment]
If they disappear, it means that you haven't properly configured them. See my comments above.

**Comment by tananaev** [comment]
Some new icons have been added to the web app (see https://github.com/tananaev/traccar-web/issues/495).

**Comment by carlosplazaaguilera** [comment]
Hello, Thanks for Traccar at all!!. 

I think categories should be in a table in the Database. It will be much more easy to add more categories o directly in the user interface, with an image checker may be great.

Firefighting and rescue service vehicless has many categories reglated by UNE-EN 1846-1:2011 in Europe and in  Spain.
https://www.traficosyemergencias.es/herramientas-y-equipos-5/veh%C3%ADculos-de-bomberos/

Do you have a little tutorial/manual about how to add more categories, and compile web interface step by step (dummies proof), with clear specs for .svg files?

Thanks a lot.

**Comment by tananaev** [comment]
I don't think it makes sense to do for the old web app. There will be completely different implementation for the new web app.

**Comment by tananaev** [comment]
It should be much easier to add new categories to the modern app. You should be able to use standard SVG images. If dynamic icons are still required please create a new ticket in the `traccar-web` repository.
