### ISSUE TITLE
TLT2H not working when year 2017 is coming

### ISSUE THREAD

**Issue by blackmonk88** [traccar/traccar#2747]
Again this issue is NOT about traccar, but I hope we can have an open discussion why and how to troubleshoot this error.

Basically the symptom is TLT2H stop working when the date changed into January 1st 2017.
I do have lower firmware version dated 2011 and it's still working.
The faulty model is from 2012 software model version.

Basically when we issue SMS command 6660000, the result time will be NOW timestamp, but not with this faulty firmware as it will give date before 2017 by GMT time conversion. And so the GPRS report will also give faulty latitude, longitude, and timestamp.

I don't have the buggy models at my hands, as it's still attached at the cars. so I can't restart it manually, but I've done RESET by SMS command and the bug is still persist. I've also run RESTART command by SMS and the bug persist.

Do you also suffer the same issues, and are there any solutions for this ?

Thank you

**Comment by tananaev** [comment]
Can you provide some HEX message samples?

**Comment by mcastilloe** [comment]
Same issue here, i think it's a firmware bug, because earlier TLT's works fine. The problem is where to get an earlier firmware! Factories are not answering
