### ISSUE TITLE
Protocol identification (TK110)

### ISSUE THREAD

**Issue by tyepez** [traccar/traccar#2759]
Hi, please help me,

I ordered a new gps tracker from ebay, advertised as TK110 but it doesn't work on ports 5001, 5006, 5013, 5023.
Only works on port 5002, but the server not receive gps information, the time is wrong, and other data is empty, the field valid showed as NO.

It sends the following HEX to the server:
```
28303837303733313034333337425a30302c3734302c3030302c336266372c303432352c336266372c306266352c336266372c303965372c336266372c636261642c336266372c306463662c336266372c633762322c303130303030303029
```
I get this when I convert it to ASCII:
```
(087073104337BZ00,740,000,3bf7,0425,3bf7,0bf5,3bf7,09e7,3bf7,cbad,3bf7,0dcf,3bf7,c7b2,01000000)
```

Please help me, thanks.

Best Regards,

**Comment by tananaev** [comment]
Your device doesn't send GPS info. It looks like it sends cell towers info. Traccar supports those and you should be able to get a location if you configure geolocation provider in the config.

Note that currently Traccar only uses one cell tower, but device seems to be reporting more than one. Send me an email if you are interested to implementing the rest. It can increase the accuracy of the locations.

**Comment by tyepez** [comment]
Thanks.
How can I enable to get location from both sources, gps and cell towers?

**Comment by tyepez** [comment]
Sorry, I ask on Traccar server.
When I configure a traccar client  for receive position based on NETWORK, on my server never update the position. 
I seek the logs in client on my phones, but it never showed the position update that they send it. (only work with GPS)

**Comment by tyepez** [comment]
Yes, I know, all the time I have enabled data connection and GPS, but it dont work with network provider, I try in some phones, but only works with GPS provider.
Google maps works fine with data connection without GPS.
Thanks.

**Comment by tananaev** [comment]
You haven't actually answered the question.

**Comment by tyepez** [comment]
the answer is YES

**Comment by tananaev** [comment]
Can I see a screenshot of the Android location settings screen?

**Comment by tyepez** [comment]
![screenshot_2017-01-05-23-15-43_com android settings](https://cloud.githubusercontent.com/assets/14049287/21707437/6c522f22-d3cf-11e6-9747-96cc16bef529.png)

**Comment by tananaev** [comment]
Looks fine. Double-check that the app has all the permissions though.

**Comment by tyepez** [comment]
![screenshot_2017-01-05-23-21-52_com miui securitycenter_1483676581205](https://cloud.githubusercontent.com/assets/14049287/21707524/3d1638e2-d3d0-11e6-9789-44645d9b2905.jpg)

**Comment by tananaev** [comment]
Also looks fine... I guess. I don't understand the language though. So, everything should work then. If you still don't get location update message on the status screen in the app, it means that your device can't get a location for some reason.

**Comment by tyepez** [comment]
![screenshot_2017-01-05-23-31-50_com mlwrkz drawanywhere_1483677206692](https://cloud.githubusercontent.com/assets/14049287/21707689/b1863776-d3d1-11e6-8818-b7f506534c00.jpg)

**Comment by tananaev** [comment]
It uses Android APIs directly. If it doesn't work, it means that your phone doesn't report network location for some reason.

**Comment by tyepez** [comment]
Please help me.

I get the follow:
(087073104337BZ00,740,001,280b,6357,280b,6813,280b,5d7c,280b,6723,280b,6359,280b,6722,11000000)
(087073104337BZ00,740,000,3bf7,0425,3bf7,0bf5,3bf7,09e7,3bf7,cbad,3bf7,0dcf,3bf7,c7b2,01000000)
But server can't understand this.

**Comment by tananaev** [comment]
How did you determine that "server can't understand this"? I need to see logs.

**Comment by tyepez** [comment]
by this:
2017-01-12 14:28:55 DEBUG: [DB78856D: 5002 < 190.63.119.159] HEX: 28303837303733313034333337425a30302c3734302c3030312c323830622c363335372c323830622c363831332c323830622c356437632c323830622c363732332c323830622c363335392c323830622c363732322c313130303030303029
2017-01-12 14:28:55  INFO: [DB78856D] id: 087073104337, time: 1969-12-31 19:00:00, lat: 0.00000, lon: 0.00000, speed: 0.0, course: 0.0

All data is wrong, but when I send SMS, device return valid information.

**Comment by tananaev** [comment]
It's not wrong. Your device doesn't send any GPS data, so all zeroes is exactly what you get.

**Comment by tyepez** [comment]
How sure it? 
because, when I request information by SMS, device return valid information, as position, date, zonetime, speed, and others data.

**Comment by tananaev** [comment]
I am 100% sure. I deal with this stuff every day. I've heard this before that device send valid data via SMS, but nothing via GPRS. It's a common issue, but it's not a server issue, it's a device issue.

**Comment by tyepez** [comment]
thanks for you clarification

**Comment by azzahrah** [comment]
TK110 or TK110N protocol same as GPS103/GPS518 begining with '(' and ending with ')'
