### ISSUE TITLE
Protocol for T580W

### ISSUE THREAD

**Issue by FraserL** [traccar/traccar#2760]
Hello,

I've followed your instructions and managed to set up my server and device using port 5002 and I can see in the server log that they are communicating, however there is no update on my http://localhost:8082/ page. 

I decoded one of the HEX and this was the output:
```
(864768010869060,DW30,050117,A,5135.82713N,00001.17918E,0.089,154745,000.0,43.40,12)
(864768010869060,DW30,050117,A,5135.82700N,00001.17996E,0.042,154755,000.0,42.80,12)
(864768010869060,DW30,050117,A,5135.82715N,00001.18044E,0.023,154805,000.0,44.30,12)
(864768010869060,DW30,050117,A,5135.82690N,00001.18015E,0.038,154815,000.0,45.80,12)
(864768010869060,DW30,050117,A,5135.82722N,00001.18021E,0.069,154825,000.0,47.30,12)
(864768010869060,DW30,050117,A,5135.82783N,00001.18093E,0.036,154835,000.0,49.10,12)
```
It looks similar to TK103 - in which case 5002 should work? What are the next steps to troubleshooting the problem?

**Comment by tananaev** [comment]
It should be working. Are there any errors or warning in the log? Do you see decoded location data?

**Comment by FraserL** [comment]
It started worked soon after I posted this - not sure why it wasn't showing up but it's all fine now!

Sent from my iPhone

On 5 Jan 2017, at 21:18, Anton Tananaev <notifications@github.com<mailto:notifications@github.com>> wrote:


It should be working. Are there any errors or warning in the log? Do you see decoded location data?

-
