### ISSUE TITLE
tk103 device. It is updated. But there is no record

### ISSUE THREAD

**Issue by evigra** [traccar/traccar#2764]
Good Morning
My tk103 device. It is updated. But there is no record, in the positions table.
What is going on?
I do not see log errors.

**Comment by tananaev** [comment]
Please see following guide:

https://www.traccar.org/troubleshooting/

**Comment by evigra** [comment]
I did not know how to explain it.
The device if I can see it on my website.
The device is updated on the web.
In my database, the update is not inserted

At my base, the last position is 3 days ago.
On my website, if you are showing the update.

**Comment by tananaev** [comment]
Have you checked the log files?

**Comment by evigra** [comment]
In my log, look for the IP of the device. Also look for the IMEI.
In short, no longer update that device in the database

>2017-01-07 13:16:19  INFO: [2112C96F] connected
>2017-01-07 13:16:24  INFO: [44E7DD2E] connected
>2017-01-07 13:16:32 DEBUG: [0E29ECAD: 5055 < 187.216.136.202] HEX: 474554202f3f69643d3535393533362674696d657374616d703d31343833373934393837266c617$
>2017-01-07 13:16:32 DEBUG: [0E29ECAD: 5055 > 187.216.136.202] HEX: 485454502f312e3120323030204f4b0d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
>2017-01-07 13:16:32 DEBUG: [1B793BFB: 5020 < 187.210.230.26] HEX: 2424683134352c3836313037343032343935323630312c4141412c33352c31392e3031323439352c$
>2017-01-07 13:16:32  INFO: [0E29ECAD] id: 559536, time: 2017-01-07 13:16:27, lat: 19.11113, lon: -104.31037, speed: 0.0, course: 234.3
>2017-01-07 13:16:32  INFO: [1B793BFB] id: 861074024952601, time: 2017-01-07 13:16:30, lat: 19.01250, lon: -104.10945, speed: 0.0, course: 254.0
>2017-01-07 13:16:35  INFO: [A2F5ABC8] connected
>2017-01-07 13:16:54  INFO: [584C561E] connected
>2017-01-07 13:16:59 DEBUG: [BC16A9BC: 5020 < 187.237.39.24] HEX: 24244a3134362c3836313037343032343931383233302c4141412c33352c31392e3336393233332c2$
>2017-01-07 13:16:59  INFO: [BC16A9BC] id: 861074024918230, time: 2017-01-07 13:16:58, lat: 19.36923, lon: -99.09570, speed: 0.0, course: 5.0
>2017-01-07 13:17:05  INFO: [218EBD36] connected
>2017-01-07 13:17:08 DEBUG: [32D1F80A: 5001 < 187.210.230.27] HEX: 3836383638333032333236313931343b
>2017-01-07 13:17:08 DEBUG: [32D1F80A: 5001 > 187.210.230.27] HEX: 4f4e
>2017-01-07 13:17:14  INFO: [E03B4D34] connected
>2017-01-07 13:17:16 DEBUG: [D62BBE0B: 5020 < 187.210.230.24] HEX: 2424703134372c3836313037343032343537323434312c4141412c33352c31392e3133313038302c$
>2017-01-07 13:17:16  INFO: [D62BBE0B] id: 861074024572441, time: 2017-01-07 13:17:15, lat: 19.13108, lon: -104.33496, speed: 0.0, course: 335.0
>2017-01-07 13:17:24  INFO: [30C9225C] connected
>2017-01-07 13:17:27 DEBUG: [0E29ECAD: 5055 < 187.216.136.202] HEX: 474554202f3f69643d3535393533362674696d657374616d703d31343833373935303437266c617$
>2017-01-07 13:17:27 DEBUG: [0E29ECAD: 5055 > 187.216.136.202] HEX: 485454502f312e3120323030204f4b0d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
>2017-01-07 13:17:27  INFO: [0E29ECAD] id: 559536, time: 2017-01-07 13:17:27, lat: 19.11114, lon: -104.31037, speed: 0.0, course: 234.3
>2017-01-07 13:17:33 DEBUG: [1B793BFB: 5020 < 187.210.230.26] HEX: 2424693134352c3836313037343032343935323630312c4141412c33352c31392e3031323439352c$
>2017-01-07 13:17:33  INFO: [1B793BFB] id: 861074024952601, time: 2017-01-07 13:17:31, lat: 19.01250, lon: -104.10945, speed: 0.0, course: 254.0
>2017-01-07 13:17:35  INFO: [A19FC616] connected
>2017-01-07 13:17:41  INFO: [B6DD74C6] connected
>2017-01-07 13:17:44 DEBUG: [53C1AAC0: 5013 < 200.68.139.10] HEX: 2a48512c313530303036303630312c4c494e4b2c3133313734332c31322c31322c3130302c302c302$
>2017-01-07 13:17:54  INFO: [95997966] connected
>2017-01-07 13:18:00 DEBUG: [BC16A9BC: 5020 < 187.237.39.24] HEX: 24244b3134362c3836313037343032343931383233302c4141412c33352c31392e3336393233332c2$
>2017-01-07 13:18:00  INFO: [377C4C7C] connected
>2017-01-07 13:18:00 DEBUG: [377C4C7C: 5055 < 97.90.19.208] HEX: 474554202f3f69643d3633343831302674696d657374616d703d31343833373935303830266c61743d$
>2017-01-07 13:18:00 DEBUG: [377C4C7C: 5055 > 97.90.19.208] HEX: 485454502f312e3120323030204f4b0d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
>2017-01-07 13:18:00  INFO: [BC16A9BC] id: 861074024918230, time: 2017-01-07 13:17:58, lat: 19.36923, lon: -99.09570, speed: 0.0, course: 5.0
>2017-01-07 13:18:00  INFO: [377C4C7C] id: 634810, time: 2017-01-07 13:18:00, lat: 34.08018, lon: -118.07391, speed: 0.0, course: 0.0
>2017-01-07 13:18:05  INFO: [C287E7CE] connected
>2017-01-07 13:18:08 DEBUG: [32D1F80A: 5001 < 187.210.230.27] HEX: 3836383638333032333236313931343b
>2017-01-07 13:18:08 DEBUG: [32D1F80A: 5001 > 187.210.230.27] HEX: 4f4e
>2017-01-07 13:18:12  INFO: [740206E8] connected
>2017-01-07 13:18:17 DEBUG: [D62BBE0B: 5020 < 187.210.230.24] HEX: 2424713134372c3836313037343032343537323434312c4141412c33352c31392e3133313038302c$
>2017-01-07 13:18:17  INFO: [D62BBE0B] id: 861074024572441, time: 2017-01-07 13:18:16, lat: 19.13108, lon: -104.33496, speed: 0.0, course: 335.0
>2017-01-07 13:18:27 DEBUG: [0E29ECAD: 5055 < 187.216.136.202] HEX: 474554202f3f69643d3535393533362674696d657374616d703d31343833373935313037266c617$
>2017-01-07 13:18:27 DEBUG: [0E29ECAD: 5055 > 187.216.136.202] HEX: 485454502f312e3120323030204f4b0d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
>2017-01-07 13:18:27  INFO: [0E29ECAD] id: 559536, time: 2017-01-07 13:18:27, lat: 19.11117, lon: -104.31038, speed: 0.0, course: 234.3
>2017-01-07 13:18:42  INFO: [A3C1644C] connected
>2017-01-07 13:18:43  INFO: [D6E44E12] connected
>2017-01-07 13:18:52  INFO: [000960B6] connected
>2017-01-07 13:19:00 DEBUG: [BC16A9BC: 5020 < 187.237.39.24] HEX: 24244c3134362c3836313037343032343931383233302c4141412c33352c31392e3336393233332c2$
>2017-01-07 13:19:00  INFO: [BC16A9BC] id: 861074024918230, time: 2017-01-07 13:18:59, lat: 19.36923, lon: -99.09570, speed: 0.0, course: 5.0
>2017-01-07 13:19:08 DEBUG: [32D1F80A: 5001 < 187.210.230.27] HEX: 3836383638333032333236313931343b
>2017-01-07 13:19:08 DEBUG: [32D1F80A: 5001 > 187.210.230.27] HEX: 4f4e
>2017-01-07 13:19:12  INFO: [5F32D4B5] connected
>2017-01-07 13:19:13  INFO: [EB6ECA4D] connected
>2017-01-07 13:19:17 DEBUG: [D62BBE0B: 5020 < 187.210.230.24] HEX: 2424723134372c3836313037343032343537323434312c4141412c33352c31392e3133313038302c$
>2017-01-07 13:19:17  INFO: [D62BBE0B] id: 861074024572441, time: 2017-01-07 13:19:16, lat: 19.13108, lon: -104.33496, speed: 0.0, course: 335.0
>2017-01-07 13:19:19  INFO: [0AE962F9] connected
>2017-01-07 13:19:27 DEBUG: [0E29ECAD: 5055 < 187.216.136.202] HEX: 474554202f3f69643d3535393533362674696d657374616d703d31343833373935313637266c617$
>2017-01-07 13:19:27 DEBUG: [0E29ECAD: 5055 > 187.216.136.202] HEX: 485454502f312e3120323030204f4b0d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
>2017-01-07 13:19:27  INFO: [0E29ECAD] id: 559536, time: 2017-01-07 13:19:27, lat: 19.11111, lon: -104.31036, speed: 0.0, course: 234.3
>2017-01-07 13:19:39  INFO: [44D9FA9D] connected
>2017-01-07 13:19:44 DEBUG: [53C1AAC0: 5013 < 200.68.139.10] HEX: 2a48512c313530303036303630312c4c494e4b2c3133313934332c31332c31322c3130302c302c302$
>2017-01-07 13:19:49  INFO: [B42268E4] connected
>2017-01-07 13:19:49  INFO: [16C900F8] connected
>2017-01-07 13:20:02 DEBUG: [BC16A9BC: 5020 < 187.237.39.24] HEX: 24244d3134362c3836313037343032343931383233302c4141412c33352c31392e3336393233332c2$
>2017-01-07 13:20:03  INFO: [BC16A9BC] id: 861074024918230, time: 2017-01-07 13:20:00, lat: 19.36923, lon: -99.09570, speed: 0.0, course: 5.0
>2017-01-07 13:20:08 DEBUG: [32D1F80A: 5001 < 187.210.230.27] HEX: 3836383638333032333236313931343b
>2017-01-07 13:20:08 DEBUG: [32D1F80A: 5001 > 187.210.230.27] HEX: 4f4e
>2017-01-07 13:20:09  INFO: [967926AD] connectedv

**Comment by tananaev** [comment]
I don't see any errors in the log. It means that data should be stored in the database, assuming configuration file is correct.
