### ISSUE TITLE
Position of redundancy

### ISSUE THREAD

**Issue by gpsim** [traccar/traccar#2766]
Hello tananaev!
I found that some device(gt06 gt02) heartbeat data into the location data stored in the database, resulting in a lot of duplicate location data,.

**Comment by tananaev** [comment]
You can enable duplicate filtering in the config file.

**Comment by gpsim** [comment]
<entry key='filter.enable'>true</entry>
	<entry key='filter.duplicate'>true</entry>
	<entry key='filter.distance'>5</entry>
	<entry key='filter.zero'>true</entry>

I configured, there will still be a lot of duplicate

**Comment by gpsim** [comment]
Elegant, not found before such configuration

**Comment by tananaev** [comment]
Is it working now?

**Comment by gpsim** [comment]
Yes,it is working now, the configuration has come into effect.
