### ISSUE TITLE
Distance in minus

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2771]
@tananaev  in summary report when i am trying to get summary for device the distance  is coming into negative values and this things happen because some time false data stored into totalDistance and distance field of positions.
is there any solution??
![summery](https://cloud.githubusercontent.com/assets/23626544/21804698/4f4d7cc6-d756-11e6-8e85-2a4c22e4e6e2.png)

**Comment by tananaev** [comment]
The problem is likely that your device sent data in the wrong order. Distance calculation processes locations is the same order they come in. There is currently no solution for this issue.

**Comment by d33pak-s1ngh** [comment]
so this is a problem of device means i have to change a device or is there any other way to change it in device.
also i think mobile devices will not have this problem because that is developed by you and they will be in order.

**Comment by tananaev** [comment]
Some devices are configurable. We might implement some fix in future, but currently server doesn't handle this situation.

Traccar Client sends data in correct order.

**Comment by d33pak-s1ngh** [comment]
so this issue can be solve by client server if it is possible then i think it should be priority because report base on distance are important.

**Comment by tananaev** [comment]
It is not easy to solve, and it already works for most devices, so I'm not so convinced that it should the priority.

**Comment by d33pak-s1ngh** [comment]
i was checking my database to find reason for getting distance in minus found that at some point totaldistance set to 0 that's why trip was showing negative totaldistance.

i dont know how it happened but that is the reason for minus value  for total distance so i think there is no problem with device or from server.

![distance 6](https://cloud.githubusercontent.com/assets/23626544/22460973/661916a4-e7cd-11e6-941b-cf1cf237787c.png)

**Comment by d33pak-s1ngh** [comment]
other question i have is that what are the attributes we are using in positions and purpose of following attributes?

sat
mcc
mnc
lac
cid
index

**Comment by tananaev** [comment]
Are you sure you haven't reset the total distance yourself?

As for attributes:

sat - number of GPS satellites
mcc - MCC
mnc - MNC
lac - LAC
cid - cell id
index - serial number of the message

**Comment by d33pak-s1ngh** [comment]
i am not sure whether i have done that or not.

in following image i have seen that distance is same for many records and total distance is also same means distance is not adding into total distance some time take a look in this image where positions are unique but for all the position distance and total distance is same. 
i dont know when something like this happens.

![distance](https://cloud.githubusercontent.com/assets/23626544/22502670/e9cc4b08-e893-11e6-8f1d-bfcf70e57e6e.png)

**Comment by tananaev** [comment]
You have to check other fields as well, especially times. Also, check latest location from the device table.

Are you sure you don't have any attribute copying set up for the distance?
