### ISSUE TITLE
Information of new features in v3.9

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2773]
i would like to know what are the use of following screens or is there any documentation is available for these screens in v3.9.
Statistics
![state](https://cloud.githubusercontent.com/assets/23626544/21805663/6251f716-d75b-11e6-834d-ffa0e6d66bab.png)

Device Distance
![devices](https://cloud.githubusercontent.com/assets/23626544/21805677/7a81c078-d75b-11e6-8e63-c72f1ffff223.png)

Attribute aliases

![aleas](https://cloud.githubusercontent.com/assets/23626544/21805686/844a8644-d75b-11e6-8608-0491c86909cc.png)

**Comment by tananaev** [comment]
There is no documentation, but here is a short overview:

1. Statistics - server statistics information by day. It's calculated in-memory, so when you restart server, you lose data from the beginning of the day.

2. Device Distance - set or re-set total distance for a device. Useful when you had invalid data from a device that ruined total distance value.

3. Attribute Aliases - rename attributes in the status panel. For example, you might want to rename attribute like "adc1" to something more relevant to your use case (e.g. "temperature" or "fuel").

**Comment by d33pak-s1ngh** [comment]
thanx for reply i got it.

**Comment by SebastEnn** [comment]
Questions answered. Issue can be closed.
