### ISSUE TITLE
web design

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2774]
hi anton i want to give same look to my web interface as traccar interface  where  i can get html and javascript for that?(i am working with php)

**Comment by tananaev** [comment]
Have you tried to search? There is a repository for web interface:

https://github.com/tananaev/traccar-web

**Comment by d33pak-s1ngh** [comment]
yes i have this repository i was confused with Ext js so i read about it and now i know that html and css is built within Ext js.
so now i have to see how i can implement Ext js components into my php web interface.
thanx.

**Comment by tananaev** [comment]
The interface is built on the client side and server just gives data in JSON format to display. You can definitely implement something like that with PHP as well.

**Comment by SebastEnn** [comment]
He probably found the required resources. Issue can be closed.
