### ISSUE TITLE
Geofences error

### ISSUE THREAD

**Issue by ns327** [traccar/traccar#2778]
I have sucessfully added 2 geofences in the morning, but now when I try to add a new one I receive the following error:

`Unrecognized field "calendarId" (class org.traccar.model.Geofence), not marked as ignorable (5 known properties: "attributes", "id", "name", "description", "area"])
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@7d235dbb; line: 1, column: 121] (through reference chain: org.traccar.model.Geofence["calendarId"])`

I have only modified the config file to receive email notifications, nothing else.

**Comment by tananaev** [comment]
Looks like you are not using official release version.

**Comment by ns327** [comment]
Yours is the best. I have cloned the git, both server and web, edited the config for the database, email and a few filters.Tried clean install, but same result.

**Comment by tananaev** [comment]
I would recommend using official release.

As for the problem, it looks like your back-end doesn't match web interface.

**Comment by SebastEnn** [comment]
Problem was probably an old version or version mismatch. Issue can be closed.
