### ISSUE TITLE
company management

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2779]
hi @tananaev  i want to discuss something about  company or client management into traccar.
i have two clients what i want is both client will have their own admin who can login into system and manage thier own devices and groups and there will be super admin who can manage both client admin.
how i can achieve this into current traccar system?

what i am doing now is i am considering one group as a company and the user created under that group will be admin of that group and all the devices and fence belong to that group can be manage by user of that group. so if i have two clients then there will be two groups each with their own user.

**Comment by tananaev** [comment]
One option I can think of is to add permissions for users. So, one user would be able to manage other selected users.

@Abyss777, what do you think?

**Comment by d33pak-s1ngh** [comment]
yes that would be better if admin can manage permission for other users.

**Comment by tananaev** [comment]
Traccar has groups for devices, not for users.

**Comment by Abyss777** [comment]
Agree, "User manager" will be the simplest solution. Key changes I see:
- User field - Manager (like Admin)
- New table for linking user to other users
- `GET /api/users` will return list of linked users
- `PermissionManager.checkUser` will also check links
- User created by Manager automatically linked to him 
- only Admin can set Manager field and link users to manager

or

instead of boolean field Manager we can use integer UserLimit, I would say every user will be user manager with UserLimit  = 0, if UserLimit > 0 he will be treated as real user manager.

**Comment by tananaev** [comment]
We can just change `/api/users` to return the list of accounts that current user has access to. Admin would obviously have access to all users, plus it would be able to assign linking between users.

Maybe we need a "manager" flag to allow users to create and edit other users.

**Comment by Abyss777** [comment]
I think that someday people will want limit users count for managers. We can do it at the beginning.

I just want to say that UserLimit > 0 will be equivalent of boolean "manager" flag.

**Comment by tananaev** [comment]
I see your point. Yes, I guess it makes more sense in the long term.

**Comment by Abyss777** [comment]
How will we name the table, "user_user" ?

**Comment by Abyss777** [comment]
And API point for linking will be `"/api/permissions/users"` ?

**Comment by d33pak-s1ngh** [comment]
so i hope 3.10 will have this feature.

**Comment by tananaev** [comment]
@Abyss777, yes, that's what I was thinking.

@d33pak-s1ngh, possibly, but no guarantees.

**Comment by Abyss777** [comment]
Started writing code and could not stop :)
Working on "full-featured" manager implementation. Just news.

**Comment by d33pak-s1ngh** [comment]
feeling excited.. waiting for latest release.
one question there will any group of users will be there like group of device we have?
it will be like 3 or 4 user belong to same company (group) so manager (admin)of that company will manage other users.
manager can disable user.
limit device creation per user.
something of that nature.

**Comment by tananaev** [comment]
There will be no groups, but each manager would have users assign to him then and a limit of users.

**Comment by d33pak-s1ngh** [comment]
ok thats fine thank you.

**Comment by SebastEnn** [comment]
Seems like manager role has been implemented in [3.10](https://www.traccar.org/blog/traccar-3-10/). This issue can be closed.
