### ISSUE TITLE
Upgrade with Synology

### ISSUE THREAD

**Issue by Merangle** [traccar/traccar#2782]
Hello 

The installation procedure for synology refers to http://cphub.net.
On this site, there is no new version of traccar (the latest I was able to install was the 3.7).
Moreover the http://www.1sthandy.de/category/synology/synology-traccar/ (where you could previously download traccar for synology) does not provide any new traccar version. 

What can we do to upgrade to version 3.9 (is there a procedure to install traccar  on synology whitout reference to cphub.net)  
I'm currently using traccar-synology 3.7-011.

Any help would be appreciated.
Thanks

**Comment by tananaev** [comment]
You would have to contact @1sthandy. He is the author of Synology version of Traccar.

**Comment by corvankruchten** [comment]
Since @1sthandy seems to be disappearred: is there anyone else who is able to help to update the Traccar server on the Synology-nas from 2.11 to 3.10?

**Comment by SebastEnn** [comment]
Maybe. But not in this issue. So it can be closed.
