### ISSUE TITLE
disable device

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2786]
is there any feature to disable device.
so once user disable a device from web device will no longer visible on traccar unless user enable it again?

**Comment by tananaev** [comment]
No, it's not possible, but as an admin you can't unlink device from any user.

**Comment by pablitonadal** [comment]
Do you think it can be implemented in future versions?

**Comment by tananaev** [comment]
I need to know use cases for it first.

**Comment by pablitonadal** [comment]
Sorry, I use "traccar" in a volunteer association (civil protection), I can see the position of volunteers, but not always all the volunteers of the association are in service. In the database I included all the volunteers but it would be useful to have them displayed or not displayed on the map. Did I explain to you? sorry for my English.

**Comment by tananaev** [comment]
That can easily be accomplished. You can unlink devices from your user account, or you can create a group for active volunteers, or you can even filter by online/offline status.

**Comment by pablitonadal** [comment]
Thanks for your answer. If I create a group with active volunteers or with online volunteers, how do I show only the volunteers in that group or only active volunteers on the map? thanks for support.

**Comment by tananaev** [comment]
Filter by group in the devices list and it will show only that group on the map.

**Comment by pablitonadal** [comment]
Thank you, honestly I never knew of that option. thanks for the support.

**Comment by SebastEnn** [comment]
Question got answered. Also, [disabling devices is now possible](https://www.traccar.org/forums/topic/disable-devices/).

Issue can be closed.
