### ISSUE TITLE
Docker Image repository location

### ISSUE THREAD

**Issue by karispk** [traccar/traccar#2787]
I want to run traccar server on my Synology NAS running Docker version 1.11.2.

Unfortunately I cannot find the image (tananaev/traccar:[VERSION]) to pull on the Docker repository.

I have checked the instructions (https://www.traccar.org/docker/) however these appear to be to build the image & I do not think they are applicable for Synology NAS.

Could you provide location for the repository that contains the image or provide further instructions on how to build the image.

**Comment by tananaev** [comment]
There is no repository. At the moment the only way is to build your own image.

**Comment by acasandreiflorin** [comment]
there is an official docker image here: https://registry.hub.docker.com/r/traccar/traccar/
this should be closed, I guess
