### ISSUE TITLE
Language flipping back to English

### ISSUE THREAD

**Issue by HJvD123** [traccar/traccar#2798]
Hi,

I use my Traccar (3.9 on RaPi 3 with Debian Jesse light) in Dutch. Every time I log in I have to select the Dutch language, Traccar is not remembering this for me. Then when I'm not logging out and look again next day the server has flipped back to English. So what I'm wondering is why there is no default language setting (set and forget) in the account area? Most users never gonna change their using language I think.

**Comment by tananaev** [comment]
Traccar uses default browser language. If it's English, it means you have set English in your browser.

**Comment by HJvD123** [comment]
Traccar is always suggesting I use the English language on my Dutch Firefox browser 50.1. After your comment I tried the Edge browser: suggesting English in a Dutch browser.

**Comment by tananaev** [comment]
What do you mean by "suggesting"? Which one is it using?

**Comment by HJvD123** [comment]
Well, when I open my browser and filling in the url from Traccar. The login popup is showing the English language by default. You said it should choose Dutch by default because the browser is Dutch.

**Comment by tananaev** [comment]
Which language is the login page in?

**Comment by HJvD123** [comment]
English as well.

**Comment by tananaev** [comment]
Try to check `window.navigator.language` variable value in the browser developer tools.

**Comment by HJvD123** [comment]
Poa. Not very familiar with the developer tools. Tried looking tough in the debugger window but didn't found the variable you want me to look after.

**Comment by tananaev** [comment]
Just type it in the console and click "enter".

**Comment by HJvD123** [comment]
OK. Tried this. But no result in the debugger window by typing this variable. Tried "navigator.language" as well, but no result either.

**Comment by tananaev** [comment]
What do you mean by debugger window? Console? It should return you the value.

**Comment by HJvD123** [comment]
Well: the build in developper in Firefox tab debugger. No result for my search there.

**Comment by tananaev** [comment]
Not sure why you are on debugger tab when I asked you to use console:

![screen shot 2017-01-14 at 10 37 19 pm](https://cloud.githubusercontent.com/assets/1161863/21953986/1fe15816-daaa-11e6-8d68-0e6a6ec2358e.png)

**Comment by HJvD123** [comment]
OK. I'm still learning. The result is Array [ "nl", "en-US", "en" ] Do not know why there is "en-Us" and "en", I have a English spell checker installed but I can't see why this is interfering with Traccar.

**Comment by tananaev** [comment]
What if you type following expression:
```javascript
window.navigator.userLanguage || window.navigator.language
```

**Comment by HJvD123** [comment]
Response: "nl" that is correct in my humble opinion.

**Comment by tananaev** [comment]
It is correct. It should load "nl.json" instead of "en.json". Please check network tab to confirm.

**Comment by HJvD123** [comment]
Checked network tab, found there: locale-en.js and en.json. No good, I guess?

**Comment by tananaev** [comment]
The only option I see is to access your computer remotely and see what's happening, if that's possible.

**Comment by HJvD123** [comment]
Well, is my issue a incident or are there more problems with the language selection. Do you want to understand what is going wrong so you can improve your program? I'm familiar with using Teamviewer for remote access.

**Comment by tananaev** [comment]
It's the first such problem that I hear of. Yes, I want to check to improve the program.

**Comment by SebastEnn** [comment]
I guess you have solved this privately. Issue can be closed.
