### ISSUE TITLE
disable user

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2807]
once i disable user from admin account i am unable to activate that user again.
i am trying to uncheck disable checkbox and save still nothing is happening.

**Comment by tananaev** [comment]
Please see this thread:

https://github.com/tananaev/traccar-web/issues/356

**Comment by d33pak-s1ngh** [comment]
@tananaev  what is command to restart traccar server?

**Comment by d33pak-s1ngh** [comment]
from above thread i am not getting which files i need to update.

**Comment by tananaev** [comment]
Looks at the commit linked to the thread. To restart service (linux):
```
/opt/traccar/bin/stopDaemon.sh ; /opt/traccar/bin/startDaemon.sh
```

**Comment by SebastEnn** [comment]
Question answered. Issue can be closed.
