### ISSUE TITLE
server issue or miss configuration

### ISSUE THREAD

**Issue by zellditch78** [traccar/traccar#2808]
i have installed the server tracker in a windows 2008 server behind a router, open ports and run. everything ok. i test a tk103 and a traccar client and add it to server. with correspondant indentifier. i dont get any thing from server. and in the log file i get this 
```
2017-01-17 11:50:35  INFO: [CC8C0EF5] connected
2017-01-17 11:50:35 DEBUG: [CC8C0EF5: 5002 < 186.185.7.11] HEX: 23232c696d65693a3836383638333032353539313834372c413b
2017-01-17 11:51:05  INFO: [CC8C0EF5] disconnected
```

it repeat and repeat. just chance the hour.

what i miss up?

**Comment by tananaev** [comment]
First of all, you are using wrong port. You device is using GPS103 protocol, so correct port is 5001. 

Also, please carefully read following page:

https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/

**Comment by zellditch78** [comment]
thank you anton. it work perfectly. I went the wrong way and think it will use tk103 protocol, my fault. Thanks again
