### ISSUE TITLE
FixTime not fixing wrong device time

### ISSUE THREAD

**Issue by gbvaz** [traccar/traccar#2809]
Hi, I'm having some trouble with a few devices sending ocasional positions with wrong year, 2025. Shouldn't the fixTime column fix this discrepancy since it's completely different date from serverTime?

```
# id, protocol, deviceId, serverTime, deviceTime, fixTime, valid, latitude, longitude, altitude, speed, course, address, attributes
'53490547', 'mxt', '1274', '2017-01-15 08:45:10', '2025-11-07 10:17:47', '2025-11-07 10:17:47', '1', '-19.945384', '-43.964492', '0', '0', '0', NULL, '{\"index\":5174,\"ignition\":true,\"alarm\":false,\"input\":0,\"output\":0,\"charge\":true,\"sat\":1,\"hdop\":2,\"gsm\":14,\"temp1\":22,\"odometer\":2312261923,\"hours\":322796,\"power\":13.867,\"battery\":0,\"distance\":107915.15,\"ip\":\"177.79.224.108\"}'
'53529411', 'mxt', '1135', '2017-01-15 11:03:47', '2025-11-07 13:46:49', '2025-11-07 13:46:49', '1', '-19.966398', '-44.333389', '0', '55.0756', '0', NULL, '{\"index\":41663,\"ignition\":true,\"alarm\":false,\"input\":0,\"output\":0,\"charge\":true,\"sat\":4,\"hdop\":1,\"gsm\":29,\"temp1\":41,\"odometer\":9641725,\"power\":14.379,\"battery\":0,\"distance\":119241.72,\"ip\":\"177.79.226.108\"}'
'53939104', 'mxt', '1366', '2017-01-16 10:13:21', '2025-11-09 01:13:20', '2025-11-09 01:13:20', '1', '-20.197277', '-44.422225', '0', '16.7387', '315', NULL, '{\"index\":21359,\"ignition\":true,\"alarm\":false,\"input\":0,\"output\":0,\"charge\":false,\"odometer\":129214104,\"hours\":13871,\"power\":13.518,\"battery\":0,\"distance\":531508.94,\"ip\":\"177.79.226.108\"}'
```
I'm running Traccar 3.6. Thanks for the help!

**Comment by tananaev** [comment]
Why `fixTime` should fix anything and how? Both `deviceTime` and `fixTime` are timestamps reported by the device.

**Comment by gbvaz** [comment]
Isn't fixTime a Traccar generated time, that "fixes" the deviceTime?

**Comment by tananaev** [comment]
No, it's the time of the GPS fix.

**Comment by gbvaz** [comment]
Oh, I see, sorry I didn't know this. Then, do you know what could possibly be happening to those devices? Most of the time they report the correct timestamp, but some positions have those crazy times. Is there a way I can filter them instead of having to run a sql script deleting them every now and then?

**Comment by tananaev** [comment]
Well, you should probably contact device vendor and ask them to fix this issue. If it's not possible, you can use `filter.future`.

**Comment by gbvaz** [comment]
Ok, I'll try contacting them. How does this filter works? I couldn't find anything about it here: https://www.traccar.org/configuration-file/

**Comment by tananaev** [comment]
There will be a change in `filter.future`. Currently it's just a boolean flag (true or false). In the next version it will take a number.
