### ISSUE TITLE
Permissions polishing

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar#2810]
Agree, that permissions system became a bit too complicated, but not so much, we do not have user groups :)

I thing it has everything for most use cases now, except some small things should be polished:

1. As you mentioned, manager can set any expiration time for other user, it should be handled. If manager has expiration time, he should not be able set expiration time more then his one.

2. There is no protection from cycling management now. I mean if "manager" has user "sub-manager" who is manager of "manager". Behavior will be unpredictable.  Should we add something, or will rely on admins good sens? 

3. Could you remember, why you allowed readonly user edit his own account and notifications? I'm asking because totally readonly user fits more for public use case.

4. Users created by manager will have no device limit even manager has it, it is not good. But I do not have idea how to implement it correctly without backward user->manager confrontation. If you have, please share.

**Comment by tananaev** [comment]
I agree that manager shouldn't be able to create a user with expiration date more than his own.

I don't think we should handle corner cases with cycles. We should make logic as simple as possible. I'm against handling those types of things.

Originally idea for readonly user was to not allow it to create and edit devices. I guess with device limit, it makes less sense. Maybe we should make readonly users into full readonly.

Maybe if manager has a device limit, we would just limit him to creating users with 0 device limit.

**Comment by Abyss777** [comment]
Let's summarize 

1. Will implement it.
2. OK, leave it as is.
3. Will implement full readonly.
4. Will implement if manager has device limit then all users added/edited by him should has less or equal device limit. Not the best solution, but simple and rather close to optimal.

**Comment by tananaev** [comment]
4. I was thinking to make device limit 0 for users, so that only manager can create and assign devices. This way we have total limit of devices limited to the number on manager's account.

Alternative option is to subtract the limit from the manager. For example, if manager has limit 5 and he creates a user with limit of 2 devices, he would lose those 2 from his limit. It might be a bit confusing, so I don't really like it.

**Comment by Abyss777** [comment]
In that case manager can infinitely link device to user and unlink from himself.

Just subtraction is not enough, the ideal algorithm is following:

- Check user device limit (deny if reached)
- Get list of user managers (we need backward user->manager confrontation here)
- In cycle count managed devices for every manager and deny if count >= device limit of any appropriate manager.

It is too complicated and need additional HashSet user->manager

My suggestion is easier but in worth case company (manager and his users) will have userLimit * deviceLimit devices.

But agree with you we should implement some limitation in device creating as replacement for "not-full" readonly.

**Comment by tananaev** [comment]
If users have 0 limit, then only manager can create devices, so the total limit would be preserved.

**Comment by Abyss777** [comment]
No, manager will create device, link it to user, and unlink from himself and got 0 devices again. He can repeat it infinitely.

**Comment by tananaev** [comment]
What if we disallow manager to unlink devices from himself. Then my option would work.

**Comment by Abyss777** [comment]
Or, for manager we can check not directly linked devices but count of all managed devices.

**Comment by tananaev** [comment]
But then if you don't set device limit to 0 for users, they will be able to create devices even if the total manager limit is reached.

**Comment by Abyss777** [comment]
Sure, it was instead of deny unlinking from manager himself.

OK. Assume a bit:

- `checkDeviceLimit` will check count of managed devices for managers
- `deviceLimit = 0` means zero not limitless

What about permissions to change `deviceLimit` for manager?
On the one hand I want allow manager edit it (for example not more than his own limit)
On the other hand company total device count can be more then manager count with help of some tricks link/unlink.

**Comment by tananaev** [comment]
I think keeping total count within the limit is more important than allowing manager to select limit for users.

**Comment by Abyss777** [comment]
Let's look at service provider use case:

- admin create company manager with desired user and device limits
- manager can create users with 0 deviceLimit only (users can not create devices)
- manager can add devices only in his limit, link/unlink devices from users, but can not unlink from himself.

Looks fine to me or I miss something?

Will we implement some "unlimited" device limit value? `-1` for example.

**Comment by Abyss777** [comment]
Oh, forget, how will we migrate from "0 means unlimited" to "0 means zero"?

**Comment by tananaev** [comment]
Good question. We can change it to `-1`. We would have to follow the same logic for the user limit as well.

**Comment by Abyss777** [comment]
Will we also change default database/constructor value for `deviceLimit` to `-1` or leave to `0` ?

**Comment by tananaev** [comment]
It should probably be initialized to `-1` by default.

**Comment by Abyss777** [comment]
One more question, will user with `deviceLimit = 0` be able edit/delete devices?

**Comment by tananaev** [comment]
I think so, unless the user is also read-only.

**Comment by Abyss777** [comment]
I'm not sure. Then there will not be the way to get "device readonly" user. Such user just can't add new devices but can edit linked to them.
I would suggest do not allow such user add/edit/remove devices.

If admin want user allow edit devices he could set some positive value, like `1`

**Comment by tananaev** [comment]
If we want to have "device readonly" option, I think it's better to have an extra flag for it. Using device limit for it might be confusing.

**Comment by Abyss777** [comment]
Closing it.
Hope it will cover almost all possible use cases for personal and business.
Permissions subsystem became complicated, I would say on the edge. It's hard to cover all possible combinations in the head.
May be we should add tests somehow, or consider using some users/permissions framework.

**Comment by tananaev** [comment]
Agree, but it's OK for now.

**Comment by Abyss777** [comment]
Forget one thing, attribute aliases are linked to devices and logically "device readonly user" should not be able to edit them. Do you agree?

**Comment by tananaev** [comment]
Agree.
