### ISSUE TITLE
Device limit

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2811]
Once i set device limit for user it is working fine user can only create device as per device limit.

if i add a group(with 5 device in it) to a user and user's device limit is of 2 device and user have not created any device and try to create a device it is giving device limit reached error but that should not be happen because user have not created any device yet. but what happening is a group already contain 5 device that's why it is not allowing user to add any more device.
this situation is confusing.
because user with only limit of 2 device can have a group of 5 or 10 device.

**Comment by tananaev** [comment]
All linked devices are counted against the limit. Traccar doesn't save any information about the original creator of a device.

**Comment by d33pak-s1ngh** [comment]
it store user and device into user_device table so we can count from there how many device is created by user and define a limit constraint base on that.

**Comment by tananaev** [comment]
I think it makes more sense to count all devices. I don't see any good reason to not count the ones in the group.

**Comment by d33pak-s1ngh** [comment]
the only problem is that group can have a device more than users limit.

**Comment by d33pak-s1ngh** [comment]
also if user is allowed only for 2 device and admin can attach that user with 5 groups each with 5 device than user will have 25 device.

**Comment by Abyss777** [comment]
Also admin can link limitless number of devices to user directly. He is admin.

**Comment by tananaev** [comment]
Yes, but admin can do anything, including changing any limits.

**Comment by d33pak-s1ngh** [comment]
that is fine admin can do whatever but it has to be in proper format like if admin want user to have many devices he can increase users limit.
but if admin will attach a group with more device than users limit without increasing limit is not proper or systematic way.

**Comment by d33pak-s1ngh** [comment]
what i think is users should allowed to create a device if there is limit for device no matter what group is assigned to them.
if user allowed for 2 device and he is already with a group consist of 5 device still he should be able to create 2 device. just a suggetion.

**Comment by tananaev** [comment]
If you can explain the use case, we can consider it. Just saying that you think it's better is not a good argument.

**Comment by d33pak-s1ngh** [comment]
one argument that i have is user with limit of 5 device can not be in a group which have more than 5 device if all the links are count because that violates a constraint of device limit.  
what we can do is admin can assign as many group he want to assign to user but limit will be count on the devices users have created.
means if user have limit of 5 device then there can not be more than 5 record for that user in user_device table.
i dont have any problem with current system may be i am wrong just wanted to confirm that is it issue or feature.

**Comment by tananaev** [comment]
As I said, I want some business case for why someone would need it. It is implemented as it is, to make the code simpler. Simpler code means less bugs and issues.
