### ISSUE TITLE
Make two unit id report on single device id in traccar

### ISSUE THREAD

**Issue by gpproton** [traccar/traccar#2814]
Hi @tananaev 
i'm looking if it's possible to make two or more devices to report on just a device id, and Traccar is able merge the values received from them and apply some sort of filter that avoid misunderstanding and conflit between the two different devices, like it'll only accept one position log that is not less than 30seconds from previous log received, i feel it's possible to achieve it in some way,

**Comment by tananaev** [comment]
Are you asking about two devices reporting with the same unique id? It's not possible to handle it in Traccar. Why would you need it?

**Comment by gpproton** [comment]
Hi @tananaev 
This is for people who require maximum uptime and can't afford satalite based tracking devices and needs very reduced chance of failure using two devices, two different network, from my own view i feel it's a valid reason. like this can be optional

**Comment by tananaev** [comment]
I see. You want two unique id associated with a single device in the database. Why don't you just configure two devices to report the same unique id?

**Comment by gpproton** [comment]
But in situations where devices are different protocol and the unit is can't be changed, it can be handled better by traccar.

**Comment by tananaev** [comment]
That would require too many changes in the code. Why can't you just have two separate objects on the map?

Do you actually work on the project that requires it? Can I have some more details about it?
