### ISSUE TITLE
how to generate war file for traccar project

### ISSUE THREAD

**Issue by rameshrajana** [traccar/traccar#2815]
hii sir 

i have downloaded traccar and traccar-web from your github site 
then after working scenario  everything is fine
i am using netbeans IDE 
so i want to create war file for this tracccar project
can you please help how to create war file for traccar project in netbeans
 thanks in advance

**Comment by tananaev** [comment]
There are no "war" files in Traccar anymore. Last one was a long time ago.

**Comment by rameshrajana** [comment]
without war file how can i deploy project into own server like apache tomcat

**Comment by rameshrajana** [comment]
is there any other option to deploy project in apache tomcat server

**Comment by tananaev** [comment]
Technically you can deploy the static part there, but you would still need Traccar back-end for the API. I don't see any reason for deploying it on a Tomcat server. Traccar already includes an embedded server.

**Comment by rameshrajana** [comment]
how to check working status of geofence and fuel status of traccar project in web side...

**Comment by tananaev** [comment]
Fuel info should be visible in the "state" table. For checking geofence, you have to configure it. Then check even report when it's triggered.

**Comment by rameshrajana** [comment]
i have  configured TK103 DEVICE in my car but it doesn't show any live route ,when i click the "follow" and "live routes"  button on  web side but when i see reports i get the route information.it shows live route when i  carry device by hand 
what is the reason it does not  show live route when i fix device in my  car

thanks in advance

**Comment by tananaev** [comment]
Check this guide:

https://www.traccar.org/troubleshooting/

**Comment by rameshrajana** [comment]
i set geofence to my device when device is crossed  geofence boundary webview display notification like  "device has exited geofence"
but when the device enters into geofence area it does not show any notification in website

**Comment by rameshrajana** [comment]
yes i enabled both notifications in Notifiacations area....

**Comment by tananaev** [comment]
Then you should be getting both.

**Comment by rameshrajana** [comment]
state table  does not appear in my mysql database for checking fuel status information...

**Comment by tananaev** [comment]
There is no "state" table. All the data is stored in the "positions" table.

**Comment by rameshrajana** [comment]
can we set more than 5 geofences for one device using polygon and circle

**Comment by tananaev** [comment]
Where did the number 5 come from? There are no limits. You can create as many geofences as you want.

**Comment by rameshrajana** [comment]
sir i executed traccar web application in my pc  using netbeans everything working fine and also added devices in webside.problem is when i see route reports of devices it showing straight line on map and also tested my device in demo.traccar.org it also showing straight line on map.
can you please elaborate this particular point to show route map like a curve   

thanks in advance

**Comment by tananaev** [comment]
Do you mean to follow the road? To get better results you should increase report frequency.

**Comment by rameshrajana** [comment]
how to increase the report frequency can you plz explain

**Comment by tananaev** [comment]
What devices are you using?

**Comment by rameshrajana** [comment]
jmo1 and my personal mobile

**Comment by tananaev** [comment]
I'm not sure what JMO1 is, but if it's a hardware GPS tracker, then you should check device manual for more information.

As for mobile device, assuming that you are using Traccar Client app, there is a filed called "frequency".

**Comment by rameshrajana** [comment]
I  am using JM01  and TK103 GPS devices

**Comment by tananaev** [comment]
As I said, you should check manual. If there is nothing there, contact device vendor for more info.

**Comment by rameshrajana** [comment]
i want to develop an android application using traccar webside as a sever like getting reports,live route,notifications,list of devices and etc..
so can u please tell me how to develop android application using traccar server

**Comment by tananaev** [comment]
There is already Android application. It's called Traccar Manager.

**Comment by rameshrajana** [comment]
i seen traccar manager in google  playstore it looks like a webview android application

**Comment by tananaev** [comment]
There is a native version as well. Check corresponding branch on GitHub.

**Comment by rameshrajana** [comment]
can you please provide links for that version

**Comment by tananaev** [comment]
Source code is here:

https://github.com/tananaev/traccar-manager-android/tree/native

If you want APK, you can download 1.x version of the manager from releases.
