### ISSUE TITLE
command api

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2816]
i want to implement command api from my interface 
what i can see in api call it is asking for two parameters device id and command type.
then where i will send actual command.?
![cmd](https://cloud.githubusercontent.com/assets/23626544/22095476/f05c516a-de3a-11e6-8efb-923a843425fa.png)
another field is attributes so which key value pair i should use for that?

**Comment by malkitsingh** [comment]
You will send command to this url
http://your-ip-address:port/api/commands
Make sure you are making POST type request.

**Comment by d33pak-s1ngh** [comment]
thanx i know the url i am talking about body of request what parameters it will contain.
{
'deviceId':19,
'type':"custom",
'attributes':"command"
}

**Comment by d33pak-s1ngh** [comment]
i think problem is solved i am using following format
```
{
'deviceId':19,
'type':"custom",
'attributes':{"data":"command"}
}
```

**Comment by malkitsingh** [comment]
I am not sure about custom command but this is how I did it for sending engine stop command


```
                data: {
                    "deviceId":19,
                    "type":"engineStop"
                },

```

**Comment by d33pak-s1ngh** [comment]
thanx i will try that.

**Comment by tananaev** [comment]
All additional data goes into attributes. @d33pak-s1ngh, your last example should work.

**Comment by d33pak-s1ngh** [comment]
i had a device online and i try to send a command to device the response is quite similar as the request only difference is that  response have a new field call id with value 0.

request:
{
'deviceId':19,
'type':"custom",
'attributes':{"data":"AllMonitor"}
}
response:
{
id:0,
'deviceId':19,
'type':"custom",
'attributes':{"data":"AllMonitor"}
}

**Comment by tananaev** [comment]
You should probably read about REST APIs and how they work. Success or failure is returned as HTTP status code.

**Comment by Jromero97** [comment]
I'm pretty sure when you make that request the response could be HTTP 202 or 200 if is success, in other way could be HTTP 400 if is wrong to point you that your request is bad.
