### ISSUE TITLE
Traccar  does not keep track

### ISSUE THREAD

**Issue by LPastor1984** [traccar/traccar#2819]
Hello, good evening! After fighting for some time, I was able to run a Windows 7 boot. I was able to transmit data from my gps and I got the perfect ones on the server, so far, all great. But when I close my section and talk again my travels disappear, it is the first problem that came to me. Another problem I have, for example when a user assigned the administrator attribute, and then when I want to make that user an ordinary user I can not do it again. From now thank you very much and forgive if you do not understand what I wrote since it translated Google translator

**Comment by tananaev** [comment]
I have no idea what "section" and "travels" you are talking about.

As for un-checking admin flag, you should read this thread:

https://github.com/tananaev/traccar-web/issues/356

**Comment by LPastor1984** [comment]
Thanks for the prompt reply, in the first problem I mean the following, if
not start section but my gps device sends data to the server when I log
into the server that data I do not see it adds the following line to the
configuration file but not I had existed <entry
key='database.positionHistoryDay'>365</entry>

**Comment by tananaev** [comment]
Why do you need `database.positionHistoryDay`?
