### ISSUE TITLE
Teltonika FM1120 not work

### ISSUE THREAD

**Issue by vcoscarella** [traccar/traccar#2822]
Hi, I installed  traccar 3.6 on my server
Using different Teltonika devices: fm5300, fm1100, fm1120.
 but FM1120 not work. The device responds to command text message but does not store the data in the database. What can be the cause ??

**Comment by tananaev** [comment]
First of all, I would recommend to install the latest version. Why did you installed an outdated build?

As for the problem, check following page:

https://www.traccar.org/troubleshooting

**Comment by vcoscarella** [comment]
In July, the 3.6 was the last version.
Upgrade to 3.9 version just install new run or  change something in the database?
 Thank you for your answer and link

**Comment by tananaev** [comment]
Well, phrase "I installed traccar" implies that you did it recently.

For upgrading info see following page:

https://www.traccar.org/upgrading-traccar/
