### ISSUE TITLE
Invalid location jumps

### ISSUE THREAD

**Issue by Sargunan** [traccar/traccar#2823]
Hi,
In reference to this issue "Invalid Location Jumps for vehicles #1720" resolution points to setting device time. Could you please help us where to set the device time..?

Thanks in advance.

**Comment by tananaev** [comment]
You can use current time instead of device time when data is stored in the database. You can modify corresponding insert SQL query in the config file. Note that Traccar has internal cache and changing the query won't affect the cache.
