### ISSUE TITLE
ACC ON notifications comparing tracker and client locations

### ISSUE THREAD

**Issue by Argentum** [traccar/traccar#2846]
Hello,

It would be great for ACC ON notifications to the app, to compare position with the tracker before sending the notification to our smartphone. It could avoid generating so much junk notifications.

In order to not making the app all the day getting our GPS position and eating all the battery, I suggest to look for the phone location only when the server sends the notification of ACC ON, then the Manager compares position of both devices, and if they aren't similar, finally the notification appears.

At least, would be good if it appeared as an option.

Hope you like the idea.

**Comment by tananaev** [comment]
Why would your device generate so many ACC ON/OFF events? It sounds like device issue, not server.

**Comment by Argentum** [comment]
Everytime you start the car you get an ACC ON notification. Why do I need a start notification everytime I start my own car? It would be useful when my car starts when I'm not inside. This would mean like someone is stealing it.

**Comment by tananaev** [comment]
You are talking about completely different feature. You should be using alarms for that, not ignition notification.

**Comment by Argentum** [comment]
Could you explain it deeper?

**Comment by tananaev** [comment]
You are talking about can theft alarm. You should use a GPS device that supports it. Ignition notification is not intended for that.

**Comment by Argentum** [comment]
But with the thing I say, you can get that feature without having a tracker with theft alarm.

**Comment by tananaev** [comment]
Your case is too specific and complicated to implement.

**Comment by Argentum** [comment]
Thank you anyway.

**Comment by hackerunet** [comment]
To use this as you intend you should use the ARM command supported by gps103 (tracker) gps, when you leave your car you ARM the vehicle so you will receive an alarm notification if someone access to your vehicle or turn the vehicle on.
