### ISSUE TITLE
Attributes "io207"  in FM5300 Teltonika

### ISSUE THREAD

**Issue by vcoscarella** [traccar/traccar#2857]
Hello
io207 event is not included in the new table "events"?
how do you only get the RFID code read? in "positions"  is stored in attributes but with so many other values. solutions??
traccar version is 3.6

thank you

**Comment by tananaev** [comment]
What event is "io207"? Why should it be included?

**Comment by vcoscarella** [comment]
io207 is Rfid event.
Because it is included in the Teltonika protocol, and is an event generated by the device. 
you can not get it individually?

**Comment by tananaev** [comment]
There is no RFID event in Traccar.

**Comment by vcoscarella** [comment]
in field "attributes"

event:207
io207:code rfid in hex

{"priority":0,"sat":13,"event":207,"power":1,"io146":0,"io24":0,"io149":0,"io199":0,"io145":0,"io147":0,"io148":0,"io207":3472332702865371188,"ip":"5.170.226.18"}

**Comment by tananaev** [comment]
Can you please clarify what the problem or question is?

**Comment by netluca1** [comment]
the event 207 is part of teltonika protocol 2.15
