### ISSUE TITLE
Chinese tracking device not working

### ISSUE THREAD

**Issue by gpproton** [traccar/traccar#2858]
Hi @tananaev 

I'm currently trying to get a new Chinese tracking device to work but it just does not work, even if it look similar to H02 protocol which i have worked with a lot, below is the hex code and information decoded.
```
2a48512c3335353438383032303933303739362c56332c3030323333392c36323136302c30362c3032343835322c3033353432312c3134382c302c3032343835322c3033353432352c3134332c2c3032323235312c3033363438322c3133372c2c3032343835322c3030303333352c3133332c2c3032343835322c3033313735312c3133332c2c3032343835322c3033353432332c3133332c2c303241312c302c582c3031303130342c4546453746424646230d0a
```
```
*HQ,355488020930796,V3,002339,62160,06,024852,035421,148,0,024852,035425,143,,022251,036482,137,,024852,000335,133,,024852,031751,133,,024852,035423,133,,02A1,0,X,010104,EFE7FBFF#
```

I'll really appreciate any help.

**Comment by tananaev** [comment]
It is a variation of H02 protocol. It seems like it contains some cell tower information. I would need documentation to implement it.

**Comment by gpproton** [comment]
Hi @tananaev 
The device started working without enabling the cell id feature, thanks.
