### ISSUE TITLE
Reverse Geocoding in other language than English

### ISSUE THREAD

**Issue by metasy** [traccar/traccar#2865]
Is it possible to configure the reverse geocoding address into another language? I still can see it uses English to show in the State Address row

**Comment by hackerunet** [comment]
If you use nominatim you could pass this parameter to change the language: &accept-language=fr

**Comment by metasy** [comment]
how about Google maps?

**Comment by hackerunet** [comment]
You can of course google it:
https://developers.google.com/maps/documentation/geocoding/intro

**Comment by metasy** [comment]
what I mean is that where to configure the parameter. Is it on the Web server config or any other place? I tried with the custom map with no success

**Comment by metasy** [comment]
I did pass the language to the custom map and it does show the map in the correct language but address row in the state window still show it in english

**Comment by hackerunet** [comment]
please, give me the coordinates to check if is parameter issue or if is just as it will be shown in any language by google

**Comment by metasy** [comment]
try this:

https://www.google.com.kh/maps/place/Raintree/@11.5709973,104.9213644,15z/data=!4m5!3m4!1s0x0:0x59d77a25937e35f8!8m2!3d11.5720482!4d104.919109?hl=km

**Comment by hackerunet** [comment]
sorry, try to read google documentation at least, it's easy and if we are talking about google reverse geocoding don't share maps content, share google reverse URL's. As anton's usually say, "you haven't even try looking for an answer".
regards.
