### ISSUE TITLE
API /positions Device access denied - SecurityException (PermissionsManager:194 < PositionResource:89 < ...)

### ISSUE THREAD

**Issue by AbrahamAlmosawi** [traccar/traccar#2890]
We have installed Traccar on Windows 2012 R2 server.

We have 2 devices registered and working.  We have 1 iphone registered and working.

We have 1 user account: admin with a non default password.

Using the API these commands work correctly...
POST /api/session  (using params)
GET /api/devices - lists 3 devices
GET /api/users - lists 1 user and token
GET /api/events/{id} - retrieves events correctly

However, this API does NOT work...
GET /api/positions

the /api/positions generates this error...

> Device access denied - SecurityException (PermissionsManager:194 < PositionResource:89 < ...)

I can view the devices in the Traccar web app and I am using the Admin account which has access to everything.

It appears that the positions api does not function correctly.  I have checked the Traccar webapp and it does not use the positions API as it uses websockets instead.

I believe this is a bug in the API.

**Comment by tananaev** [comment]
It's not a bug. Make sure that you include "Accept" header in the request.

**Comment by AbrahamAlmosawi** [comment]
I already have the header set to 

Accept: */*

But is still does not work with the same error...

> Device access denied - SecurityException (PermissionsManager:194 < PositionResource:89 < ...)

I cannot find any reference to accept header in API documentation.

**Comment by tananaev** [comment]
That's an invalid header value. You have to specify the format that you want the data to be in. For example, you can try `application/json`.

**Comment by AbrahamAlmosawi** [comment]
Yay! That worked, thank you for your help.

**Comment by tejastank** [comment]
I had pass Accept and Header Type correct, even I face same issue.

**Comment by cgsadmin** [comment]
@tananaev ,
I got same issue also but does not found any solution on this even used same header json. but not solve

**Comment by tananaev** [comment]
@cgsadmin please use forum for discussions. Make sure you provide full request and response.
