### ISSUE TITLE
Device Offline and online synchronization

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2894]
i have a situation suppose device dont have internet and it is recording location offline after some hours it goes online and start sending data on server.
in that case first it will send offline data on server which it has recorded previously.
so traccar will display device as online base on server time because device time is older than current server time.
so how much time it will take to send old data to server and display a new online data.
because it is taking too much time to send old data on server.

**Comment by tananaev** [comment]
It depends on the device, network speed and your hardware.

**Comment by d33pak-s1ngh** [comment]
ok thanx

have u got anything for osmand protocol which can tell about offline status?

**Comment by tananaev** [comment]
OsmAnd is HTTP-based, so there is no way to know if device is offline. You get "unknown" status though after some time.

**Comment by d33pak-s1ngh** [comment]
so is there any other protocol which can be use for mobile devices?

**Comment by tananaev** [comment]
Any protocol, as long as you can find an app that implements that protocol.

**Comment by d33pak-s1ngh** [comment]
like when user click on service off in traccar client  a service destroyed message shows at that time we can store record in database that will tell that device is offline

**Comment by tananaev** [comment]
That's not how the status system works.
