### ISSUE TITLE
New Device

### ISSUE THREAD

**Issue by akmal1999** [traccar/traccar#2896]
Hi

Could we add Q90 and Q50 devices to the system.

http://www.iwonlex.com/

And following device  called tagg.

https://www.amazon.ca/Tagg-Pet-GPS-Plus-Attachment/dp/B00O93D3QW

Many thanks.

**Comment by tananaev** [comment]
I need protocol documentation to check.

**Comment by akmal1999** [comment]
Ok I will provide this tomorrow.

**Comment by tyepez** [comment]
please add these models

**Comment by tananaev** [comment]
See my comment above.

**Comment by tyepez** [comment]
I will try to find it!

**Comment by jcarlos78** [comment]
Hi @tananaev did you get Q50 working ?
protocol is as from my HEX - > [3G*6105681707*000A*LK,0,0,100]

**Comment by tananaev** [comment]
It's watch protocol. It's been supported for a long time.

**Comment by jcarlos78** [comment]
@tananaev thanks, working !
Now I just have to find out why I'm getting lat: 0.00000, lon: 0.00000

**Comment by tananaev** [comment]
Probably because your device doesn't have a GPS fix yet, or it doesn't send any location.

**Comment by jcarlos78** [comment]
@tananaev started working great after a few sent messages to server. thanks!

**Comment by tyepez** [comment]
@jcarlos78, como configuraste el q50 para comunicarse con traccar??

**Comment by JeansReal** [comment]
@tananaev 
Hello!

How traccar can send commands to the device(smartwatch)

**Comment by tananaev** [comment]
There is a button to send commands. For questions please use forum instead of asking on random GitHub thread.

**Comment by pzuk** [comment]
Hi, some devices send encrypted communication , like Garett kids 2 (Smartwatch Q90). Do you know how to decrypt "encrypted watch protocol"?
