### ISSUE TITLE
OBD II GPS Realtime Tracker device support

### ISSUE THREAD

**Issue by akmal1999** [traccar/traccar#2901]
Hi,

Does the system support following device. I saw some device names are different than other and some are Chinese names and product is the same.

OBD II GPS Realtime Tracker Car Mini Spy Tracking Device System GSM GPRS Blue ( Item#: K3775BL )

http://www.tomtop.com/gps-accessories-mounts-1648/p-k3775bl.html?currency=CAD&aid=gplaca3&gclid=Cj0KEQiAifvEBRCVx5up6Ojgr5oBEiQALHw1TtciXdquh7PaGoXFcE8z1Rbz1DXyaFOlpsivANlBawgaAkOK8P8HAQ

regards,

**Comment by tananaev** [comment]
Most likely it does. Check this page:

https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/

**Comment by akmal1999** [comment]
It worked and I figured it out. It supports harsh break and anything to do with cars, however, I sent smtp with amazon and it is not sending emails when geo fence is exited and entered... any suggestion?

**Comment by tananaev** [comment]
Probably you haven't linked the geofence to your device.
