### ISSUE TITLE
[doc] all attributes

### ISSUE THREAD

**Issue by glbatistabh** [traccar/traccar#2903]
Is there a url/wiki that contains all the "attributes" documented?

**Comment by tananaev** [comment]
Do you mean position attributes? Unfortunately there is no documentation for that. Most of the attributes are pretty self-explanatory though.

**Comment by glbatistabh** [comment]
I would like to know all the attributes that exist (example: SpeedLimit) to decide which ones are useful to me.

I was unaware of the "SpeedLimit" attribute. I was researching about speed limit and only then did I find out that "SpeedLimit" existed.

In the same way, there are probably other attributes that would be useful to me, but for lack of knowledge, I'm not using them.

**Comment by glbatistabh** [comment]
Example: one need I have, is to allow the user to create ONLY geofences and all rest of the traccar disabled (account "read only = on" ).

It may be that there is an attribute that enables the creation of geofences, but for lack of knowledge, I'm not using it.

**Comment by tananaev** [comment]
Documentation for configuration attributes is here:

https://www.traccar.org/configuration-file/

It includes server, user, device and group configuration attributes as well.
