### ISSUE TITLE
Dose Traccar support with JM08 device?

### ISSUE THREAD

**Issue by hengsoheak** [traccar/traccar#2909]
Dose Traccar support with JM08 device?

![image](https://cloud.githubusercontent.com/assets/812528/22918280/29397856-f2bc-11e6-855b-ac039440eec0.png)

**Comment by jaimzj** [comment]
Yes, Please refer here https://www.traccar.org/devices/

Port for JM08 is 5023

**Comment by hengsoheak** [comment]
how to configure for this device I've check many tutorial but I can not found the solution can anyone help to configure Traccar with this devices

**Comment by tananaev** [comment]
You have to configure IP address and port. If you don't know how to do it for your device, you should contact device vendor.
