### ISSUE TITLE
Traccar track error with current location 

### ISSUE THREAD

**Issue by hengsoheak** [traccar/traccar#2913]
Dear Traccar team,

I've try to install Traccar on Window, Ubunut  there are working as well But after we try to track some use navigation when they've moved without internet and connect the internet with they arrive home and office 
I've noted that the traccar was tracked with wrong with latitude or longitude.

So please check on out image to understand much more about this case. On red arrow  is the work place we have never go there.

![ice_screenshot_20170215-093835](https://cloud.githubusercontent.com/assets/812528/22960259/e3aa1e2c-f36e-11e6-9df3-c357f2d65698.png)

**Comment by tananaev** [comment]
Traccar shows location reported by the device. What device are you using?

**Comment by hengsoheak** [comment]
We are using Iphone 6plus and Iphone 5

**Comment by Turbovix** [comment]
Devices such as Smartphones have in their configuration different functions that work to decrease energy consumption when the equipment is not in use and the main ones are GPS, Data Network, core and clock of processors among others. In your case, this is exactly what happens, in some cases the System turns off GPS and the data network and when the Traccar app sends the location data to the server the information is not accurate at this time. On the Android System it is possible to tell which apps can remain active without them being disconnected, or turn off the GPS for a few minutes when the user is not using the device, however the user will have a higher battery consumption.

**Comment by hengsoheak** [comment]
So mean that we would let our user always connect internet both GPS by any duration as we want?

**Comment by tananaev** [comment]
@Turbovix, your explanation is incorrect. As far as I know, iOS won't switch GPS off if you request high accuracy location.

@hengsoheak, there can be two explanations for those inaccurate locations:

1. GPS does not work indoors or under any cover. It requires clear sky visibility. Sometimes it can pick up reflected GPS signal, but the result would be inaccurate.

2. If there was no GPS signal at all, iOS would use cell towers and WiFi access points to calculate location. In this case location can be very inaccurate. Potentially a few kilometers off in worst cases.

**Comment by Turbovix** [comment]
@tananaev  
You are right, at the IOS you can not turn off the precise location in the power saving settings. However, my explanation is accurate when it comes to the Android system, that is, the precise location is turned off when the device is idle and then the Traccar app configured to get a mixed location receives the location by cell towers and wifi access points  to which it is connected . I suffered from the same problem, and after setting up the Traccar app as an exception solved the problem.

**Comment by hengsoheak** [comment]
Thank you very much for your explain
