### ISSUE TITLE
hikari pool

### ISSUE THREAD

**Issue by netluca1** [traccar/traccar#2916]
i have this problem in the file wrapper.log
```
INFO|1584/0|Service traccar|17-02-15 22:12:37|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
INFO|1584/0|Service traccar|17-02-15 22:12:37|[main] INFO com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Driver does not support get/set network timeout for connections. (Method org.postgresql.jdbc.PgConnection.getNetworkTimeout() is not yet implemented.)
INFO|1584/0|Service traccar|17-02-15 22:12:37|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
```

**Comment by tananaev** [comment]
I think this INFO message can be safely ignored. Why are you asking about it? Does it cause any problems?

**Comment by netluca1** [comment]
no is not problem but i think this error is because traccar use old version of driver for postgres is possible upgrade?
more new function is implemented

**Comment by tananaev** [comment]
Traccar doesn't use old driver. What makes you think it does?

**Comment by netluca1** [comment]
is possible upgrade HikariCP-java7-2.4.9 to ultimate version HikariCP-java8-2.6.1

**Comment by tananaev** [comment]
It's not possible because Traccar requires Java 7, not Java 8.

**Comment by netluca1** [comment]
in  my server is present red hat7 with java 8 and function.

**Comment by tananaev** [comment]
Traccar is designed for everybody, not just for you.
