### ISSUE TITLE
History

### ISSUE THREAD

**Issue by tyepez** [traccar/traccar#2919]
Hi,

Help me please!
I've checked my history, but I only have 10 days.
Where can I modify for get more days?

Regards,

**Comment by tananaev** [comment]
What server are you using?

**Comment by tyepez** [comment]
Own, under Centos 6.8

**Comment by tyepez** [comment]
all devices are reporting every 30 sec

**Comment by tananaev** [comment]
If you don't have `database.positionsHistoryDays` in the config, you should be able to get whole history.

**Comment by tyepez** [comment]
I don't have this record in traccar.xml / default.xml
I save all data in MySQL Server

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://localhost:3306/traccardb?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>

**Comment by tananaev** [comment]
What happens when you select more than 10 days? Please provide as much information as possible. Just saying that it doesn't work won't help to diagnose the problem.

**Comment by tyepez** [comment]
nothing, the records are empty until 2017-02-06, but since that day show me records, previous records are disappeared.

**Comment by tananaev** [comment]
If the records were there before, someone must have removed them. I don't see any other explanation.

**Comment by tyepez** [comment]
It is impossible, I am the only one that manages the server, but I have found a device that reports every hour, and only this device maintains the previous records since December.

**Comment by tananaev** [comment]
Are the records missing in the database, or only in the report?

**Comment by tyepez** [comment]
Yes, I checked it, and records exist on database!!! the issue is only web (report option) with all devices that reports every 30 sec.
![region](https://cloud.githubusercontent.com/assets/14049287/23004167/38b43d86-f3c3-11e6-9513-43fea5809780.png)

**Comment by tyepez** [comment]
![region](https://cloud.githubusercontent.com/assets/14049287/23004777/809de7f2-f3c6-11e6-915b-b7fe5d6f711d.png)

**Comment by tyepez** [comment]
![region](https://cloud.githubusercontent.com/assets/14049287/23004846/eb13a5c2-f3c6-11e6-9d97-8a9eef14b657.png)

**Comment by tananaev** [comment]
I need access to the server to take a look.

**Comment by tyepez** [comment]
I checked it again, and I found a some records with old date on fixtime.
Please see the picture attached.
![region](https://cloud.githubusercontent.com/assets/14049287/23094836/1869269c-f5ce-11e6-835b-677a76d071dc.png)

**Comment by tananaev** [comment]
So, what's the question? Device report `fixTime`.
