### ISSUE TITLE
H02 vehicle status field

### ISSUE THREAD

**Issue by tananaev** [traccar/traccar#2920]
| Bit | | First | | Second | | Third |
|-|-|-|-|-|-|-|
| 0 | 0 | Illegal door open alarm | 0 | Thief alarm | 0 | Thief alarm |
| 1 | 0 | SOS | 0 | Rob alarm | 0 | Robbery alarm |
| 2 | 0 | Speed ​​alarm | 0 | Over speed alarm | 0 | overspeed speed |
| 3 | 0 | illegal ignition alarm | 0 | undefined | 0 | Illegal ignition alarm |
| 4 | 0 | Entering alarm | 0 | In geo-fence alarm | 0 | Entering alarm |
| 5 | 0 | GPS antenna disconnect alarm | 0 | undefined | 0 | GPS antenna disconnect alarm |
| 6 | 0 | GPS antenna short circuit alarm | 0 | undefined | 0 | GPS antenna short circuit alarm |
| 7 | 0 | Out alarm | 0 | Out geo-fence alarm | 0 | Out alarm |
| 8 | 0 | Door open | 0 | undefined | 0 | Door open |
| 9 | 0 | Armed | 0 | undefined | 0 | Vehicle fortification |
| 10 | 0 | ACC off | 0 | ACC OFF | 0 | ACC off |
| 11 | 0 | Crash alarm | 1 | undefined | 1 | reserves |
| 12 | 1 | keep | 1 | undefined | 1 | reserves |
| 13 | 0 | pump | 0 | undefined | 0 | engine |
| 14 | 0 | Custom alarm | 0 | undefined | 0 | Custom alarm |
| 15 | 0 | Over speed | 0 | undefined | 0 | overspeed |
| 16 | 0 | GPS mistake alarm | 0 | undefined | 0 | GPS receiver fault alarm |
| 17 | 0 | Shock alarm | 1 | Low battery alarm | 1 | reserves |
| 18 |0 | Tilt alarm | 1 | undefined | 1 | reserves |
| 19 | 0 | Use backup battery | 0 | GPS tracker is powered via built in battery | 0 | Terminal by backup battery power supply |
| 20 | 0 | Battery remove alarm | 0 | Main Power disconnect | 0 | Battery removed |
| 21 | 0 | GPS antenna disconnect | 0 | undefined | 0 | GPS antenna disconnect |
| 22 | 0 | GPS antenna short circuit | 0 | undefined | 0 | GPS antenna short circuit |
| 23 | 0 | Low level sensor 2 on | 0 | undefined | 0 | Low level sensor 2 on |
| 24 | 0 | Temple alarm | 0 | undefined | 0 | Temperature |
| 25 | 0 | Move alarm | 0 | undefined | 0 | Three input error password |
| 26 | 0 | Blind record alarm | 0 | undefined | 0 | GPRS backed up |
| 27 | 0 | Oil cut off | 0 | GPS Tracker in Disable Fuel | 0 | Vehicles in oil cut-off current state |
| 28 | 0 | Battery demolition | 0 | Main power off Alarm | 0 | Battery demolition |
| 29 | 0 | Home SOS alarm | 0 | undefined | 0 | High level sensor 1 is high |
| 30 | 0 | Office SOS alarm | 0 | undefined | 0 | High level sensor 2 is high |
| 31 | 0 | Low level sensor 1 on | 0 | undefined | 0 | Low level sensor 1 on |

**Comment by chaudhryfaisal** [comment]
hi Anton, may I ask if you plan on implementing some of these? I would be highly interested in all power related status updates. 

Please share your purpose of posting this. 
Thank you 
Faisal

**Comment by tananaev** [comment]
The reason is to understand differences in flags for different devices that use H02 protocol. It's fairly easy to add support for new flags. You can do it yourself if you have some basic programming skills.

**Comment by chaudhryfaisal** [comment]
Would you be able to provide some guidance on how to get started? 
I enabled debug logging and then disconnected power from my tracker. No logs were generated but I received an sms from tracker on power disconnect.

**Comment by tananaev** [comment]
The code is here:

[H02ProtocolDecoder.java#L68](https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/H02ProtocolDecoder.java#L68)

**Comment by chaudhryfaisal** [comment]
Perfect, Thank you 

How to assure device is posting data to traccar server?

**Comment by tananaev** [comment]
I don't understand the question. You would see the data if it's coming.

**Comment by chaudhryfaisal** [comment]
Sorry my questions was, how do I know tracker sends an event when power is disconnected. 

following java code produced the output below. Could you please help me make sense out of it?
```java
private void processStatus(Position position, long status) {
        StringBuilder sb = new StringBuilder("processStatus -> ");
        sb.append(status).append("\t");
        for (int i = 0; i < 32; i++)
            sb.append(String.format("%d=%b, ", i, BitUtil.check(status, i)));
        Log.info(sb.toString());
        
```

processStatus -> 4294966271  0=true, 1=true, 2=true, 3=true, 4=true, 5=true, 6=true, 7=true, 8=true, 9=true, 10=false, 11=true, 12=true, 13=true, 14=true, 15=true, 16=true, 17=true, 18=true, 19=true, 20=true, 21=true, 22=true, 23=true, 24=true, 25=true, 26=true, 27=true, 28=true, 29=true, 30=true, 31=true,

processStatus -> 4294966271  0=true, 1=true, 2=true, 3=true, 4=true, 5=true, 6=true, 7=true, 8=true, 9=true, 10=false, 11=true, 12=true, 13=true, 14=true, 15=true, 16=true, 17=true, 18=true, 19=true, 20=true, 21=true, 22=true, 23=true, 24=true, 25=true, 26=true, 27=true, 28=true, 29=true, 30=true, 31=true,
`

**You are an amazing help, I truly appreciate your prompt replies and help**

**Comment by tananaev** [comment]
In your examples you only have "ACC off" flag. Also, both examples are exactly the same. Not sure why you provided two of them.

**Comment by chaudhryfaisal** [comment]
it printed to log twice so I just shared it. 
it seems all the statuses are reversed. I should have only ACC on but I get the general Idea. 

Thank you

**Comment by renaudallard** [comment]
What is the meaning of first, second and third?
If I want to add a low battery alarm, would it be the following or something else?
`if (!BitUtil.check(status, 17)) {
            position.set(Position.KEY_ALARM, Position.ALARM_LOW_BATTERY); }`

**Comment by renaudallard** [comment]
Actually, if I look at the table, the bit 17 can be 0 or 1, so would this be correct?
`if (BitUtil.check(status, 17)) {
position.set(Position.KEY_ALARM, Position.ALARM_LOW_BATTERY);
        } else if (!BitUtil.check(status, 17)) {
            position.set(Position.KEY_ALARM, Position.ALARM_SHOCK); }`

**Comment by tananaev** [comment]
It doesn't work like that. The bit seems to mean different things for different devices.

**Comment by renaudallard** [comment]
Does it mean that if I add only the code for ALARM_SHOCK, it could do battery alerts for some devices and LOW_BATTERY for others?

**Comment by tananaev** [comment]
You need a way to differentiate device models.

**Comment by renaudallard** [comment]
And without knowing which one is for which device, it's even desperate. I am also surprised that devices which can report SHOCK cannot report LOWBAT, this is quite strange.
Does BitUtil.check check the changes to former status or just the bit in the status?

**Comment by tananaev** [comment]
Just current but state.
