### ISSUE TITLE
set toggle

### ISSUE THREAD

**Issue by netluca1** [traccar/traccar#2923]
what is this feature?

![set toggle](https://cloud.githubusercontent.com/assets/23439828/23045069/63cd8c1c-f4a3-11e6-8e58-26831e54fabc.jpg)

**Comment by tananaev** [comment]
It saves your map toggle button states into the user attributes, so when you refresh the page, they are persisted.

**Comment by Arturo2017** [comment]
Great feature !!!
...and the button just to the left with position mark?
THANKS

**Comment by tananaev** [comment]
Save map position and zoom.

**Comment by Arturo2017** [comment]
Very good too !!

By the way ... if it could be to give the map buttons a gray shading with more contrast (using a smart phone is very difficult to differentiate between both states)

THANKS

**Comment by tananaev** [comment]
Hopefully Sencha fixes it in one of the next themes.

**Comment by Arturo2017** [comment]
I just saw that it is not by the contrast of the gray ... to 3 of those buttons they lack the cross bar on the icon

![img_20170317_091921_314](https://cloud.githubusercontent.com/assets/25770031/24035110/70575a96-0af4-11e7-8afa-dff94d3843f5.jpg)

**Comment by tananaev** [comment]
There is no crossed out icons for other buttons, so it's not an option.
