### ISSUE TITLE
Variant of GT06

### ISSUE THREAD

**Issue by tyepez** [traccar/traccar#2933]
I recently bought other GT06 GPS, but it didn't work with GT06 protocol (port 5023) it works fine with tk103 protocol (5002), I dont know why but I have some problems working with this protocol with this device.
I can't send actions from server to device GT06 by GPRS on tk103 protocol.

Please see the attached manual that factory sends me.

[GPS tracker Communication__ Protocol V1[1].51.pdf](https://github.com/tananaev/traccar/files/785172/GPS.tracker.Communication__.Protocol.V1.1.51.pdf)

**Comment by tananaev** [comment]
Traccar doesn't support command for TK103 protocol yet.

**Comment by tyepez** [comment]
Ok, I understand this, but I have 2 variants of GT06 GPS, both versions work fine with custom commands.
Please help me, tell me how can I set command into drop-down list, without compile.

Currently traccar send following commands with GT06:
Relay,1#  (Stop Engine in Traccar)
787812800c0000000052656c61792c312300009dee0d0a
Relay,0#  (Resume Engine in Traccar)
787812800c0000000052656c61792c3023000081550d0a

I need put the following commands in the drop-down list: (without compile): is possible??? or give me please other easy way to do.


GT06 VARIANT 1 (this model is configured with GT06 protocol)
============================================================
UPDATE POSITION (DWXX,00000)
78781680100001A967445758582C3030303030302300A0062D0D0A

CUT ENGINE (DYD,00000)
787815800F0001A9584459442C3030303030302300A0DCF10D0A
787815800F0001A9614459442C3030303030302300A03E100D0A

RESUME ENGINE (HFYD,00000)
78781680100001A963484659442C3030303030302300A07BDC0D0A
78781680100001A964484659442C3030303030302300A08B1B0D0A


GT06 VARIANT 2 (this model is configured with tk103 protocol, custom command works fine)
============================================================
UPDATE POSITION (AP00)
(027044712594AP00)

RESTART (AT00)
(027044712594AT00)

CUT ENGINE (AV0X0)
DEVICE ID + AV000
(027044712594AV000) cut circuit
(027044712594AV010) cut oil

RESUME ENGINE (AV0X1)
TIME OR DEVICE ID + AV001
(027044712594AV001) resume circuit
(027044712594AV011) resume oil

GET VERSION (AP07)
(027044712594AP07)
RESPONSE:
(027044712594BP01GT06_V01_HY)

UPDATE POSITION WITH ACC
(027044712594AR050014) 14 = 20 sec OPEN ACC encendido

(027044712594AR06003C) 3C = 60 sec CLOSE ACC apagado
(027044712594AR060078) 78 = 2 min CLOSE ACC apagado

**Comment by tananaev** [comment]
GT06 (variant 1) already supports commands.

Send me an email if you want to discuss implementation of the commands for TK103 protocol.

**Comment by ckrey** [comment]
I started implementing commands in Tk103 and will contribute them when done

**Comment by tananaev** [comment]
Great, thanks.

**Comment by ckrey** [comment]
see #3286

**Comment by italocassio** [comment]
@tananaev  how to convert Relay,1# (Stop Engine in Traccar) for
787812800c0000000052656c61792c312300009dee0d0a ?

**Comment by tananaev** [comment]
You can find protocol documentation format here:

https://www.traccar.org/protocols/
