### ISSUE TITLE
Unable to connect TK103B to traccar

### ISSUE THREAD

**Issue by k30r88** [traccar/traccar#2936]
Dear @tananaev ,
We are trying to connect TK103B gps to demo.traccar.org via instruction from https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/
but have no luck.  We also try demo4.traccar.org
imei = 352887073216750
username : martin.kurnadi@gmail.com

**Comment by tananaev** [comment]
I can see that your device worked on port 5023 just fine. You should probably be more patient and wait for the data to appear.

**Comment by k30r88** [comment]
You are the best @tananaev !!!

**Comment by k30r88** [comment]
However looks like it is updating a bit slow @tananaev 
eventhough we set fix020s***n123456 sending location every 20 seconds. Could it be because of network or server ? Or wrong gps setting ?

**Comment by tananaev** [comment]
What do you mean by slow? There might be delay because of the server, but period between the reports should be fine.

**Comment by tyepez** [comment]
@tananaev When you use the photo command, where are the images stored and how do I consult them?

**Comment by tananaev** [comment]
Traccar doesn't support images at the moment.

**Comment by tyepez** [comment]
Currently I found available commands on Meitrack, Gps103, Pt502.
https://github.com/tananaev/traccar/search?utf8=%E2%9C%93&q=TYPE_REQUEST_PHOTO
Is not working this command? or what is it?

**Comment by tananaev** [comment]
Commands should work, although not tested, but the actual image data is not supported.

**Comment by tyepez** [comment]
but what does it do "TYPE_REQUEST_PHOTO" command?

**Comment by tananaev** [comment]
It's a command type to request a photo.

**Comment by SUXUMI** [comment]
Dear @tananaev 

I'd setup the traccar server and connected the TK103B GPS to it. Web app displayed the device as `online` but there were no data about location.

Now, for testing, I've connected it to demo5.traccar.org with IMEI = 8641800349*****
But unfortunately the same issue.

Any ideas?
Kind regards

**Comment by tananaev** [comment]
@SUXUMI, it means that your device doesn't report location. You should contact device vendor support.

**Comment by SUXUMI** [comment]
@tananaev thank you for your quickest response.. (and for your great efforts as well!!!)
