### ISSUE TITLE
Trip Reports

### ISSUE THREAD

**Issue by CapnBob** [traccar/traccar#2937]
"If I make a 1 week query, trip reports are few or non-existent. The same is true of events. even though a route report shows multiple trips over multiple days.
I am running a MySQL database. ./conf/default.xml is in default.xml. Where would I look to track down the issue? "

"the trip is calculated based on some parameters and the default values might not work for everybody. You might need to tweak them."

I see nowhere I can "tweak" default values, as there are no trip parameters anywhere in "config" files?
I have tried adding the lines listed elsewhere to config (report.trip.minimalTripDuration, etc),  with no change.

Trip reports were working with H2 & 3.8 / 3.9. 
I changed to MySQL about the same tine as I updated to 3.1 
Same devices as before are in place; All are GPS-306A

**Comment by tananaev** [comment]
Please check the official documentation:

https://www.traccar.org/configuration-file/

I believe there were no changes to trip reports since 3.9, so they should work exactly the same as before.
