### ISSUE TITLE
Geo Fence permission.

### ISSUE THREAD

**Issue by akmal1999** [traccar/traccar#2939]
Hi,

When geo fence are created for  users in the system by admin is visible to managers even if you do not share with them. This is a problem. Managers and admins should should not have access to there managers and admins who create geo fence for a particular device.

geo fence should be visible to those who create geofence and we should be able to share it if we need.

regards,

**Comment by tananaev** [comment]
@Abyss777, can you please check.

**Comment by Abyss777** [comment]
Frankly, I do not clearly understand the problem.
If "admin" creates geofence and link it to "user" then "manager" of that "user" can see (link/unlink) that geofence. As for me it is normal behavior.

**Comment by tananaev** [comment]
Yes, it's normal for the manager of that particular user. From the description it sounds like all managers and admins can see it.

**Comment by Abyss777** [comment]
Can't confirm that.
Admin can see it (link/unlink), "not-user-manager" can not see it, neither link nor on the map.

**Comment by tananaev** [comment]
@akmal1999, please clarify the problem.

**Comment by akmal1999** [comment]
Hi,

OK I figured out.

Every admin who creates geo fence will be accessible to its managers as far
as the manager is created by this admin in our case admin bing AAA.
If i login with another admin (BBB)and create a manager, this manager will
not have access to other admin's (AAA) geo fence.

Am I understanding this correctly? I assumed any geo fence created by Admin
should be shared to manager or reader of choice and not available by
default to every manager.

regards,

**Comment by tananaev** [comment]
I'm confused by your description. Geofence is visible by the users that have access to it explicitly, plus managers of that users. Admins have access to all geofences.

**Comment by SebastEnn** [comment]
I guess the problem is solved? Behavior got explained at least.

Issue can probably be closed.
