### ISSUE TITLE
Login using my own login form

### ISSUE THREAD

**Issue by jorjonna** [traccar/traccar#2943]
Hi Tananaev, can I use my Own login form to access the Traccar Manager ?

I have hit the [POST] api/session and have got return response, and don't know what to do next for entering the Traccar Manager dashboard.

**Comment by tananaev** [comment]
If you already create a session, all you need to do is open the web interface.

What do you mean by "Traccar Manager"?

**Comment by SebastEnn** [comment]
Meanwhile it's now possible to add SSO, so you can use the login form of that.

Issue can be closed.
