### ISSUE TITLE
Traccar server won't start after install

### ISSUE THREAD

**Issue by scherik** [traccar/traccar#2947]
Hi!

I'm trying to install traccar server 3.10 on Ubuntu server, but I can't get the web app running.
The steps i have done:

- Install Java

- wget https://github.com/tananaev/traccar/releases/download/v3.10/traccar-linux-3.10.zip

- unzip https://github.com/tananaev/traccar/releases/download/v3.10/traccar-linux-3.10.zip

- sudo ./traccar.run

- sudo /opt/traccar/bin/startDaemon.sh

After these steps I tryed to access the web app trough the :8082 port but it doesn't load.
I tryed rebooting, reinstalling, making sure port 8082 is open.

What shall I do to get the web app running?

**Comment by tananaev** [comment]
Your unzip command is incorrect. You have to unzip local fine, not URL. Also, you should probably check output of the commands that you type in and see if there are any errors or warnings.

**Comment by scherik** [comment]
The unzip command what I wrote in the issue was incorrect, I obviously uzipped the downloaded file. After running "sudo /opt/traccar/bin/startDaemon.sh" i get this output:

sudo /opt/traccar/bin/startDaemon.sh
++++++++++ YAJSW SET ENV ++++++++++
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
wrapper home : /opt/traccar
configuration: /opt/traccar/conf/wrapper.conf
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
---------- YAJSW SET ENV ----------
++++++++++ YAJSW SET ENV ++++++++++
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
wrapper home : /opt/traccar
configuration: /opt/traccar/conf/wrapper.conf
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
---------- YAJSW SET ENV ----------
YAJSW: yajsw-stable-12.08
OS   : Linux/4.4.0-59-generic/amd64
JVM  : Oracle Corporation/1.8.0_121//usr/lib/jvm/java-8-openjdk-amd64/jre/64
Feb 23, 2017 9:19:15 AM org.apache.commons.vfs2.VfsLog info
INFO: Using "/tmp/vfs_cache" as temporary files store.
Feb 23, 2017 9:19:15 AM org.rzo.yajsw.os.posix.PosixService init
INFO: /etc/init.d/traccar already exists
************* STARTING traccar ***********************

Feb 23, 2017 9:19:15 AM org.rzo.yajsw.os.posix.PosixService getPid
INFO: wrapper pid file: /run/wrapper.traccar.pid
Feb 23, 2017 9:19:15 AM org.rzo.yajsw.os.posix.PosixService start
INFO: already running
Feb 23, 2017 9:19:16 AM org.rzo.yajsw.os.posix.PosixService getPid
INFO: wrapper pid file: /run/wrapper.traccar.pid
Feb 23, 2017 9:19:16 AM org.rzo.yajsw.os.posix.PosixService getPid
INFO: wrapper pid file: /run/wrapper.traccar.pid
Service traccar started

**Comment by tananaev** [comment]
Check logs and see if the service is actually running.

**Comment by scherik** [comment]
Logs: 

tracker-server.log:

2017-02-23 09:24:50  INFO: Shutting down server...
2017-02-23 09:25:43  INFO: Operating system name: Linux version: 4.4.0-64-generic architecture: amd64
2017-02-23 09:25:43  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 25.121-b13
2017-02-23 09:25:43  INFO: Memory limit heap: 239mb non-heap: 0mb
2017-02-23 09:25:43  INFO: Character encoding: UTF-8 charset: UTF-8
2017-02-23 09:25:43  INFO: Version: 3.10-SNAPSHOT
2017-02-23 09:25:49  INFO: Starting server...

wrapper.log.2017.0223:

INFO|wrapper|Service traccar|17-02-23 09:24:49|Shutting down Wrapper
INFO|wrapper|Service traccar|17-02-23 09:24:49|stopping process with pid/timeout 1289 45000
INFO|1289/0|Service traccar|17-02-23 09:24:50|wrapper manager received stop command
INFO|1289/0|Service traccar|17-02-23 09:24:50|[Thread-13] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@3c23ccab{HTTP/1.1}{0.0.0.0:8082}
INFO|1289/0|Service traccar|17-02-23 09:24:50|[Thread-13] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@50eb4a2c{/api,$
INFO|wrapper|Service traccar|17-02-23 09:24:50|waitpid 1289 0
INFO|wrapper|Service traccar|17-02-23 09:24:50|exit code posix process: 0 application: 0
INFO|wrapper|Service traccar|17-02-23 09:24:50|killing 1289
INFO|wrapper|Service traccar|17-02-23 09:24:51|process exit code: 0
WARNING|wrapper|Service traccar|17-02-23 09:25:37|YAJSW: yajsw-stable-12.08
WARNING|wrapper|Service traccar|17-02-23 09:25:37|OS   : Linux/4.4.0-64-generic/amd64
WARNING|wrapper|Service traccar|17-02-23 09:25:37|JVM  : Oracle Corporation/1.8.0_121//usr/lib/jvm/java-8-openjdk-amd64/jre/64
INFO|wrapper|Service traccar|17-02-23 09:25:40|exec:"java" "-classpath" "/opt/traccar/wrapperApp.jar:/opt/traccar/tracker-server.jar:/opt/traccar/lib/log4j-1.2.17.ja$
INFO|wrapper|Service traccar|17-02-23 09:25:40|posix_spawn pid 1689
INFO|wrapper|Service traccar|17-02-23 09:25:40|started process 1689
INFO|wrapper|Service traccar|17-02-23 09:25:40|started process with pid 1689
INFO|1689/0|Service traccar|17-02-23 09:25:42|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|1689/0|Service traccar|17-02-23 09:25:43|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
INFO|1689/0|Service traccar|17-02-23 09:25:43|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
INFO|1689/0|Service traccar|17-02-23 09:25:44|INFO 2/23/17 9:25 AM: liquibase: Clearing database change log checksums
INFO|1689/0|Service traccar|17-02-23 09:25:45|INFO 2/23/17 9:25 AM: liquibase: Successfully acquired change log lock
INFO|1689/0|Service traccar|17-02-23 09:25:45|INFO 2/23/17 9:25 AM: liquibase: Successfully released change log lock
INFO|1689/0|Service traccar|17-02-23 09:25:45|INFO 2/23/17 9:25 AM: liquibase: Successfully acquired change log lock
INFO|1689/0|Service traccar|17-02-23 09:25:46|Failed to generate a seed from SecureRandom within {} seconds. Not enough entrophy?
INFO|1689/0|Service traccar|17-02-23 09:25:46|3
INFO|1689/0|Service traccar|17-02-23 09:25:48|INFO 2/23/17 9:25 AM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO|1689/0|Service traccar|17-02-23 09:25:48|INFO 2/23/17 9:25 AM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO|1689/0|Service traccar|17-02-23 09:25:48|INFO 2/23/17 9:25 AM: liquibase: ./schema/changelog-master.xml: changelog-3.8::changelog-3.8-dropuniquetoken::author: C$
INFO|1689/0|Service traccar|17-02-23 09:25:48|ALTER TABLE PUBLIC.users DROP CONSTRAINT uk_user_token [90057-193] [Failed SQL: ALTER TABLE PUBLIC.users DROP CONSTRAIN$
INFO|1689/0|Service traccar|17-02-23 09:25:48|INFO 2/23/17 9:25 AM: liquibase: Successfully released change log lock
INFO|1689/0|Service traccar|17-02-23 09:25:48|[main] INFO org.eclipse.jetty.util.log - Logging initialized @7167ms
INFO|1689/0|Service traccar|17-02-23 09:25:49|[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.21.v20170120
INFO|1689/0|Service traccar|17-02-23 09:25:51|[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@50eb4a2c{/api,null,$
INFO|1689/0|Service traccar|17-02-23 09:25:51|[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@d272c09{HTTP/1.1}{0.0.0.0:8082}
INFO|1689/0|Service traccar|17-02-23 09:25:51|[main] INFO org.eclipse.jetty.server.Server - Started @9531ms

**Comment by tananaev** [comment]
Everything looks fine, so you should be able to access the web interface. There must be some network issue. Possibly firewall blocking the port.
