### ISSUE TITLE
Get Current devices's unique id

### ISSUE THREAD

**Issue by sumisdev11** [traccar/traccar#2952]
Hi

I am trying to get current devices's unique id in my appplication, as when i opne a link in the browser,
I want to send the uniqueID of tracccar client to my application server.

Is is possible with API call?

Thanks in advance.

**Comment by tananaev** [comment]
Web application uses the same API, so it's possible to get all the data you want. I'm not sure if I understand what you want to do though.

**Comment by sumisdev11** [comment]
ok,
Which method can be used for it? I am referring swagger.json file 
(when I open my Application through the browser in the device, it should send the unique ID to my application server with out opening the traccar client).
Actually I just want the current deviceID of traccar client only.

**Comment by tananaev** [comment]
I don't think it's possible. Unless you have a single device in your user account, there is no way to know which one is "current".

**Comment by sumisdev11** [comment]
Okey,
Thanks for the response.
