### ISSUE TITLE
GT06 - Sending Custom Commands via API

### ISSUE THREAD

**Issue by mtangoo** [traccar/traccar#2954]
Thank you for Traccar. Its great piece of Software.

I have a problem sending custom command. I had exhausted all options when I got idea to run engineResume and check the logs and found command sent is `787816801000000000484659442c313233343536230000e2920d0a`. I have tried to break down how you do generate it (How to create serial for example, the lengths, et al) and found manual only confusing me. I know how to generate hex data of command itself, crc and appending start/stop bit. Can you help me to understand on how to generate valid command that can be sent via custom command?

The Protocol is GT06 running on TK100 device.

Thanks

**Comment by tananaev** [comment]
The code is in the [Gt06ProtocolEncoder class](https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gt06ProtocolEncoder.java).

**Comment by mtangoo** [comment]
>The code is in the Gt06ProtocolEncoder class.

Yeah, have read it multiple times and yet can't make sense of it. The problem is I don't send commands from Java. I generate commands with NodeJs (can use PHP also) and send them via API.

So when I send the hex of the command (I was thinking that traccar will add the necessary bits start, end, et al) it didn't work. So I tried to look into the manual on how to generate full packet with command embeded then I was confused. 

To rephrase my question, why is the stop/resume get packed (with start/stop, serial, crc, et al) while the custom command is not? Where do I modify if I want traccar to pack the command for me?

I think putting a configuration on whether traccar should pack the custom command or not will be great. If you can point me to the right direction I can do that and PR

**Comment by tananaev** [comment]
By default custom commands is sent as it is. For some protocols Traccar would automatically add header, checksum etc. It's not the case for GT06 at the moment. If you want to implement it that way, you can take a look at `RuptelaProtocolEncoder` for an example.

**Comment by mtangoo** [comment]
I get it. But one more question: Where does engine stop/resume get headers checksum, et al added before sent? I can see [here](https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gt06ProtocolEncoder.java#L69) that there is call to encodeContent(). Is that enough to encode a command adding necessary headers, checksum et al?

Finally where does custom command get processed? I could not find it.
Sorry if some are basic things, am new to Traccar internals

**Comment by tananaev** [comment]
Have you actually looked at the `encodeContent()` method? It has the answer to your first two questions.

What do you mean by "processed"?

**Comment by mtangoo** [comment]
>Have you actually looked at the encodeContent() method? It has the answer to your first two questions.

Yeah, I see. Sorry for bothering on that.

>What do you mean by "processed"?

I mean when I send custom command  from the API what stages does it pass? Which of the GT06 classes does the API call? I would like to have a look at it. 

Sorry for using ambiguous terms. English is my second language.

**Comment by tananaev** [comment]
It goes through `ConnectionManager`, `ActiveDevice` and then into the pipeline. In the pipeline it usually goes through the encoder class that converts model into a message that would be transmitted to the device.

**Comment by mtangoo** [comment]
Thank you. Let me go through those classes. If I find any question I will ask here. If I succeed then I'll do PR and close this!
