### ISSUE TITLE
[Feature request] CSV export

### ISSUE THREAD

**Issue by argokask** [traccar/traccar#2961]
Hi Anton,

Would it be possible to add additional export option as csv ? I would be more general to use with some kind of open office software. Before 3.8 it was possible to export in csv and that was good option for some users.

**Comment by tananaev** [comment]
It should be fairly easy to extend reports to support CSV. Let's see if more people request this feature.

**Comment by Abyss777** [comment]
We have it. But just via API `/positions/` only.

**Comment by argokask** [comment]
Seems like there is no big intrest in CSV export option. But if it is easy to extend as you are saying than would it be possible to add that feature for next server update, i would be very thankful for that ?

**Comment by argokask** [comment]
Hi Anton,

Do i have hope to get that feature request for the next server update ? The idea would be having more general basis for server, even if ms excel is very functional but, some users just want to get data out of server and put it to another program to view and analyze, CSV would be perfect for that.

Best regards,
Argo

**Comment by tananaev** [comment]
As @Abyss777 pointed out, there is already a way to get CSV data through API.

**Comment by argokask** [comment]
Ok, can you please explain me the process how to get CSV through API? 

Can all users do the same thing?

**Comment by tananaev** [comment]
You need some technical knowledge or a script to do it. API is available for all users.

**Comment by argokask** [comment]
Ok, probably i need some help to do that, i do not have that kind of programming skills to write script for that.

**Comment by argokask** [comment]
Even if i find a person who writes the script for me it is complicated to explain users why they need to use some additional thing to get CSV reports, so it think that it would not be very user friendly solution.

**Comment by tananaev** [comment]
Please send me an email to discuss the solution.

**Comment by argokask** [comment]
Ok, thank you!

**Comment by netluca1** [comment]
is an interesting function the can explain to me

**Comment by handfreezer** [comment]
Hello, as not closed, nor script given, I have to admit that I would prefer for sure to get a CSV export from report from webinterface instead of xls format if not to difficult (I tried to replay the export of report http request with mime type text/csv, but I got an answer: "HTTP 406 Not Acceptable" )

**Comment by tananaev** [comment]
CSV export is implemented. It can be downloaded with a request like this:
```
https://demo.traccar.org/api/positions/csv?deviceId=123&from=2022-07-03T07:00:00.000Z&to=2022-07-04T06:59:59.999Z
```
