### ISSUE TITLE
forward enable

### ISSUE THREAD

**Issue by netluca1** [traccar/traccar#2968]
Hi I wanted to know if I have two servers one with the original interface and another with the modified web interface.
The GPS data go to the first server and are stored there.
with "forward.enable" command I can forward data to the other Web servers ui keeping the data on the first server?
in essence, the data arriving to the first server and venvono stored and at the same time are forwarded to the second server.
It's possible?

**Comment by tananaev** [comment]
It's possible to forward essential GPS data to OsmAnd port, but you will lose all or most additional attributes.
