### ISSUE TITLE
Modify TeltonikaProtocolDecoder class

### ISSUE THREAD

**Issue by fmelin** [traccar/traccar#2972]
Hi, good morning.
Along with greeting I would like to know if it is possible to operate an IO, I explain immediately.
At the moment I am using a TELTONIKA device, which sends me a custom parameter that it obtains from another device like IO200, IO201, IO202.
Example:
![io200](https://cloud.githubusercontent.com/assets/23340246/23527999/e9f3636a-ff76-11e6-9e6d-2f199184f832.png)

![io201](https://cloud.githubusercontent.com/assets/23340246/23528007/f139c722-ff76-11e6-9788-4e9b0e2bdfdd.png)

It is possible to divide the io200-io201-io202 and save each parameter in a different io as an example
Io200 sends a value (hex) =93 c8 11 cd fe 00 c8 00 64 00 78 00 fa 00 cd ff f8 20 47

And save as an example

Io500=(hex)93=(dec)147
Io501=(hex)c8=(dec)200
Io502=(hex)11=(dec)17
Io503=(hex) cd =(dec)205
Io504=(hex) fe =(dec)254
Io505=(hex)00=(dec)0
Io506=(hex)c8=(dec)200
Io507=(hex)00=(dec)0
Io508=(hex)64=(dec)100
Io509=(hex)00=(dec)0
Io510=(hex)78=(dec)120
Io511=(hex)00=(dec)0
Io512=(hex)fa=(dec)250
Io513=(hex)00=(dec)0
Io514=(hex)cd=(dec)205
Io515=(hex)ff=(dec)255
Io516=(hex)f8=(dec)248
Io517=(hex)20=(dec)32
Io518=(hex)47=(dec)71

Is it possible to do it?, I know I have to modify the TeltonikaProtocolDecoder class, but I do not know how.
In case you could do it, what is the price?
Beforehand thank you very much.

**Comment by tananaev** [comment]
Traccar already does separate each IO into own parameter.

**Comment by fmelin** [comment]
For the specific case of these three io (io200, io201, io202), TRACCAR does not decode them because it comes complete in a single io

**Comment by tananaev** [comment]
Can I have a HEX message sample?
