### ISSUE TITLE
position accuracy

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2975]
i can see an accuracy column in my database but the value in column of accuracy is 0.
actually my database is upgraded to 3.10 and interface is still of 3.9
so i think because of that accuracy is always 0 i have to update it to 3.10 to get accuracy values.

**Comment by tananaev** [comment]
What are you expecting accuracy for? For GPS data it's always 0.

**Comment by d33pak-s1ngh** [comment]
i am expecting an accuracy in meters. i think 0 means 100 % accuracy for gps data? and for networks it should be in meters.

**Comment by tananaev** [comment]
Zero means that the accuracy is unknown. The values is in meters.
