### ISSUE TITLE
Maven project type

### ISSUE THREAD

**Issue by d33pak-s1ngh** [traccar/traccar#2978]
![traccar maven](https://cloud.githubusercontent.com/assets/23626544/23577916/32bcbf26-00f1-11e7-902d-abb3653e4739.PNG)

i want to develop it from scratch which of the following maven project need to be select in netbeans for traccar

**Comment by Turbovix** [comment]
You need to install the following plugin: Maven Utilities

**Comment by tananaev** [comment]
Also, you have to import project, not create a new one.
