### ISSUE TITLE
How to Send Data From Server (Reply) to Device

### ISSUE THREAD

**Issue by ronnydino** [traccar/traccar#3002]
Hi...

GT-06N / WeTrack2 (Concox)
Server sent data reply to device: `787805010022CA450D0A`
But device received data: `3738373830353031303032324341343530443041`

The question is how I convert (to data type), so device received data from server:  `787805010022CA450D0A`

Please help.
Regards,
Dino

**Comment by tananaev** [comment]
How is this question related to Traccar?

**Comment by vmaheshz** [comment]
You first need to encode your command contect like below:

public ChannelBuffer encodeContent(String content) {

        ChannelBuffer buf = ChannelBuffers.dynamicBuffer();// need to take dynamic buffer for sending command, it is needed

        buf.writeByte(0x78);//starting header
        buf.writeByte(0x78);//srarting header

        buf.writeByte(1 + 1 + 4 + content.length() + 2 + 2); // 1.first 5 is default length. 2.message length 3.4 bit is default 

        buf.writeByte(0x80); // message type

        buf.writeByte(4 + content.length()); // command length //
        buf.writeInt(0);
        buf.writeBytes(content.getBytes(Charset.defaultCharset())); // command

        buf.writeShort(0); // message index

        buf.writeShort(Checksum.crc16(Checksum.CRC16_X25, buf.toByteBuffer(2, buf.writerIndex() - 2)));

        buf.writeByte('\r');
        buf.writeByte('\n');

        return buf;
    }


Then:
getChannel().write(encodeContent(message.toString()),remoteAddress); 

For example :+1:
getChannel().write(encodeContent(" RELAY,1 #"),remoteAddress);
