### ISSUE TITLE
Upgrade to Postgresql 9.4.1212.jre7 to Current Version 42.0.0

### ISSUE THREAD

**Issue by netluca1** [traccar/traccar#3004]
is possible upgrade Current Version 42.0.0

This is the current version of the driver. Unless you have unusual requirements (running old applications or JVMs), this is the driver you should be using. It supports PostgreSQL 8.2 or newer and requires Java 6 or newer. It contains support for SSL and the javax.sql package.

If you are using Java 8 or newer then you should use the JDBC 4.2 version.
If you are using Java 7 then you should use the JDBC 4.1 version.
If you are using Java 6 then you should use the JDBC 4.0 version.
If you are using a Java version older than 6 then you will need to use a JDBC3 version of the driver, which will by necessity not be current, found in Other Versions.
PostgreSQL JDBC 4.0 Driver, 42.0.0
PostgreSQL JDBC 4.1 Driver, 42.0.0
PostgreSQL JDBC 4.2 Driver, 

Version	      JDBC 4.0	               JDBC 4.1	             JDBC 4.2
42.0.0	  42.0.0 JDBC 4	  42.0.0 JDBC 41	 42.0.0 JDBC 42
9.4.1212	9.4.1212 JDBC 4	9.4.1212 JDBC 41	9.4.1212 JDBC 42

**Comment by tananaev** [comment]
Libraries are updated every new release.
