### ISSUE TITLE
Traccar client is not updating location

### ISSUE THREAD

**Issue by AravinthElangovan** [traccar/traccar#3006]
In my tracer client(android) not updating the location while my GPS is working good in google maps and I have turn on my data pack...
It tells only the send failed message and my device is le 2 and asus zenfone 2 laser

**Comment by AravinthElangovan** [comment]
I'm using port 5055

**Comment by tananaev** [comment]
Have you read my comment on the other thread?

**Comment by AravinthElangovan** [comment]
Issue number...?

**Comment by tananaev** [comment]
https://github.com/tananaev/traccar/issues/3005#issuecomment-286372914

**Comment by AravinthElangovan** [comment]
I have checked but I still shows only the send failed message

**Comment by tananaev** [comment]
OK, then tell me each step of the troubleshooting guide that you followed and result for each step.

**Comment by AravinthElangovan** [comment]
first I checked the log file in /opt/traccar/logs it shows already one connected device which is iOS and my android is not shown there
