### ISSUE TITLE
Respect forceSettings on the server side

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar#3008]
Here is the topic to discuss

I have only one suggestion at the moment:
- `lookupAttribute()` https://github.com/tananaev/traccar/blob/master/src/org/traccar/database/DeviceManager.java#L388

**Comment by tananaev** [comment]
I think for the moment we can just force server settings, not config. So if there are no other places, we can leave it for now.

Let's keep this thread open in case we want to revisit this later.

**Comment by tananaev** [comment]
So far this hasn't come up as a request, so I think we can close for now. Force settings is usually useful for user preferences, but even then I don't think a lot of people are using it.
