### ISSUE TITLE
How to configure Traccar 3.9  with Mysql 5.7.16

### ISSUE THREAD

**Issue by hengsoheak** [traccar/traccar#3009]
I installed traccar3.9 it is working as well with defualt database configuration but after that I try to configure with mysql I got below error logs.

```
INFO|wrapper|Service traccar|17-03-15 00:53:54|Shutting down Wrapper
INFO|wrapper|Service traccar|17-03-15 00:53:54|stopping process with pid/timeout 26506 45000
INFO|26506/0|Service traccar|17-03-15 00:53:54|wrapper manager received stop command
INFO|wrapper|Service traccar|17-03-15 00:53:55|waitpid 26506 0
INFO|wrapper|Service traccar|17-03-15 00:53:55|exit code posix process: 0 application: 0
INFO|wrapper|Service traccar|17-03-15 00:53:55|killing 26506
INFO|wrapper|Service traccar|17-03-15 00:53:55|process exit code: 0
WARNING|wrapper|Service traccar|17-03-15 00:54:05|YAJSW: yajsw-beta-12.07
WARNING|wrapper|Service traccar|17-03-15 00:54:05|OS   : Linux/3.13.0-55-generic/amd64
WARNING|wrapper|Service traccar|17-03-15 00:54:05|JVM  : Oracle Corporation/1.8.0_121//usr/lib/jvm/java-8-openjdk-amd64/jre/64
INFO|wrapper|Service traccar|17-03-15 00:54:09|exec:"java" "-classpath" "/opt/traccar/wrapperApp.jar:/opt/traccar/tracker-server.jar:/opt/traccar/lib/log4j-1.2.17.jar:/opt/traccar/lib/joda-time-2.9.6.jar:/opt/traccar/lib/h2-1.4.193.jar:$
INFO|wrapper|Service traccar|17-03-15 00:54:09|posix_spawn pid 26671
INFO|wrapper|Service traccar|17-03-15 00:54:09|started process 26671
INFO|wrapper|Service traccar|17-03-15 00:54:09|started process with pid 26671
INFO|26671/0|Service traccar|17-03-15 00:54:11|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|26671/0|Service traccar|17-03-15 00:54:12|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO|26671/0|Service traccar|17-03-15 00:54:12|Wed Mar 15 00:54:12 EDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL con$
INFO|26671/0|Service traccar|17-03-15 00:54:12|Wed Mar 15 00:54:12 EDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL con$
INFO|26671/0|Service traccar|17-03-15 00:54:12|Wed Mar 15 00:54:12 EDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL con$
INFO|26671/0|Service traccar|17-03-15 00:54:12|Wed Mar 15 00:54:12 EDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL con$
INFO|26671/0|Service traccar|17-03-15 00:54:12|Wed Mar 15 00:54:12 EDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL con$
INFO|26671/0|Service traccar|17-03-15 00:54:12|Wed Mar 15 00:54:12 EDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL con$
INFO|26671/0|Service traccar|17-03-15 00:54:12|Wed Mar 15 00:54:12 EDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL con$
INFO|26671/0|Service traccar|17-03-15 00:54:13|Wed Mar 15 00:54:12 EDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL con$
INFO|26671/0|Service traccar|17-03-15 00:54:13|Wed Mar 15 00:54:13 EDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL con$
INFO|26671/0|Service traccar|17-03-15 00:54:13|Wed Mar 15 00:54:13 EDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL con$
INFO|26671/0|Service traccar|17-03-15 00:54:13|Wed Mar 15 00:54:13 EDT 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL con$
INFO|26671/0|Service traccar|17-03-15 00:54:15|Failed to generate a seed from SecureRandom within {} seconds. Not enough entrophy?
INFO|26671/0|Service traccar|17-03-15 00:54:15|3
```

**Comment by tananaev** [comment]
Those are not errors. Those are warnings that can be safely ignored.

**Comment by hengsoheak** [comment]
But can not connect my traccar website

**Comment by tananaev** [comment]
That's not a Traccar error. Are you using proxy?

**Comment by hengsoheak** [comment]
you know I disabled my configuration it wroking as well 
https://traccar.figix.asia/
You can test but if I enable my configuration it will never work 



<properties>

    <entry key="config.default">./conf/default.xml</entry>
    <entry key='database.driver'>org.h2.Driver</entry>
    <entry key='database.url'>jdbc:h2:./data/database</entry>
    <entry key='database.user'>sa</entry>
    <entry key='database.password'></entry>


</properties>

I got this below error when i used my cofiguration 

2017/03/15 01:08:41 [error] 27515#27515: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8082/", hos$
2017/03/15 01:08:42 [error] 27515#27515: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.166.249, server: traccar.figix.asia, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:$
2017/03/15 01:10:47 [error] 27515#27515: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8082/", hos$
2017/03/15 01:10:48 [error] 27515#27515: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.166.249, server: traccar.figix.asia, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:$
2017/03/15 01:10:59 [error] 27515#27515: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8082/", hos$
2017/03/15 01:11:00 [error] 27515#27515: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.166.249, server: traccar.figix.asia, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1$
2017/03/15 01:11:04 [error] 27515#27515: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8082/", ho$
2017/03/15 01:11:08 [error] 27515#27515: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.166.249, server: traccar.figix.asia, request: "

**Comment by hengsoheak** [comment]
2017/03/15 01:16:27 [error] 27515#27515: *220 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET /api/socket HTTP/1.1", upstream: "http://127.0.0.1$
2017/03/15 01:16:27 [error] 27515#27515: *226 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET /api/socket HTTP/1.1", upstream: "http://127.0.0.1$
2017/03/15 01:16:27 [error] 27515#27515: *229 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET /api/socket HTTP/1.1", upstream: "http://127.0.0.1$
2017/03/15 01:16:28 [error] 27515#27515: *231 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET /api/socket HTTP/1.1", upstream: "http://127.0.0.1$
2017/03/15 01:16:28 [error] 27515#27515: *233 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET /api/socket HTTP/1.1", upstream: "http://127.0.0.1$
2017/03/15 01:16:28 [error] 27515#27515: *235 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET /api/socket HTTP/1.1", upstream: "http://127.0.0.1$
2017/03/15 01:16:29 [error] 27515#27515: *238 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET /api/socket HTTP/1.1", upstream: "http://127.0.0.1$
2017/03/15 01:16:29 [error] 27515#27515: *241 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET /api/socket HTTP/1.1", upstream: "http://127.0.0.1$
2017/03/15 01:16:29 [error] 27515#27515: *243 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET /api/socket HTTP/1.1", upstream: "http://127.0.0.1$
2017/03/15 01:16:30 [error] 27515#27515: *245 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET /api/socket HTTP/1.1", upstream: "http://127.0.0.1$
2017/03/15 01:16:30 [error] 27515#27515: *247 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET /api/socket HTTP/1.1", upstream: "http://127.0.0.1$
2017/03/15 01:16:31 [error] 27515#27515: *249 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8082/", h$
2017/03/15 01:16:33 [error] 27515#27515: *251 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8082/", h$
2017/03/15 01:16:34 [error] 27515#27515: *253 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8082/", h$
2017/03/15 01:16:49 [error] 27515#27515: *255 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.167.124, server: traccar.figix.asia, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8082/", h$

**Comment by hengsoheak** [comment]
or I need to create all table in Database by manual ?

**Comment by tananaev** [comment]
It points to Cloudflare service. You should check if it works without any proxy.

**Comment by hengsoheak** [comment]
I see my record on cloudflair  as below images. So should i change it to DNS only?

![ice_screenshot_20170315-132647](https://cloud.githubusercontent.com/assets/812528/23936186/292508f2-0983-11e7-80b4-dd8763f1c5fb.png)

**Comment by tananaev** [comment]
You should contact Cloudflare support if you have questions about configuring their service.

**Comment by iiitmahesh** [comment]
@hengsoheak  did solved the problem???

**Comment by hengsoheak** [comment]
Not yet now testing still problem
