### ISSUE TITLE
Mail and sms notifications

### ISSUE THREAD

**Issue by forlearnios** [traccar/traccar#3010]
How to activate the mail and SMS notifications..?

**Comment by tananaev** [comment]
SMS notification will be available only in the next release. As for email, you need to configure SMTP server and enable notifications for your user. It has been discussed on the forum many times, so please search for more details if you have any questions.

**Comment by forlearnios** [comment]
I had searched but I'm not clear and tell how to setup mail notifications

**Comment by tananaev** [comment]
Here is an example:

https://www.traccar.org/forums/topic/smtp-config-for-notifications/

**Comment by forlearnios** [comment]
how to activate E-mail notification in demo server i.e., demo.traccar.org

**Comment by tananaev** [comment]
I would recommend to read the link more carefully. It has the answer to your question.

**Comment by forlearnios** [comment]
now I'm using demo.traccar.org for demo check can I configure the mail notification from that demo traccar site

**Comment by forlearnios** [comment]
If can <entry key='mail.smtp.from'>                   </entry> what I need to give in this mail.smtp.from entry

**Comment by tananaev** [comment]
Do you have an SMTP server?

**Comment by forlearnios** [comment]
I'm only having gmail smtp smtp.gmail.com

**Comment by tananaev** [comment]
Then "from" should be your email address. Gmail server would probably reject anything else.
