### ISSUE TITLE
How can I delete already registered user in my databasae

### ISSUE THREAD

**Issue by forlearnios** [traccar/traccar#3014]
where I can delete my already registered account in my database

**Comment by tananaev** [comment]
Login as admin and remove user from Settings -> Users menu.

**Comment by forlearnios** [comment]
Removed and where the registered data gets stored in codes... and there is no mysql connection too

**Comment by tananaev** [comment]
By default Traccar uses embedded H2 database instance.

**Comment by forlearnios** [comment]
where I can find that h2 database in source code

**Comment by tananaev** [comment]
It's a third party library dependency.

**Comment by forlearnios** [comment]
library name..?

**Comment by tananaev** [comment]
Library name is "h2".

**Comment by forlearnios** [comment]
I have checked the source code there is no h2 library

**Comment by tananaev** [comment]
Have you heard of maven?

**Comment by forlearnios** [comment]
No..
 What is that...?

**Comment by forlearnios** [comment]
can I able to change the admin name and password

**Comment by tananaev** [comment]
If you don't know what maven is, you should probably research it first before looking into the code.

Yes, you can change admin email and password.

**Comment by forlearnios** [comment]
Can I able to add a new field on this screenshot page
![screen shot 2017-03-16 at 10 47 10 am](https://cloud.githubusercontent.com/assets/26428130/23982814/fc70e368-0a35-11e7-8085-146b997a3418.png)

**Comment by forlearnios** [comment]
If can, on which file I want to give codes for adding a new field

**Comment by forlearnios** [comment]
I have added codes for adding a new field in login.js file but it is not reflected

**Comment by tananaev** [comment]
Have you minified the JavaScript code? Check `minify.sh` script.

**Comment by forlearnios** [comment]
No my minify code is this..


#!/bin/sh

cd $(dirname $0)/../web

SDK="../../../ext-6.2.0"

sencha compile --classpath=app.js,app,$SDK/packages/core/src,$SDK/packages/core/overrides,$SDK/classic/classic/src,$SDK/classic/classic/overrides \
       exclude -all \
       and \
       include -recursive -file app.js \
       and \
       exclude -namespace=Ext \
       and \
       concatenate -closure app.min.js

from this what I want to do If I want to add new field...?
 and my login.js new code is this...
{
            xtype: 'textfield',
            name: 'Identifier',
            reference: 'userField',
            fieldLabel: Strings.identifier,
            allowBlank: false,
            enableKeyEvents: true,
            listeners: {
                specialKey: 'onSpecialKey',
                afterrender: 'onAfterRender'
            }

**Comment by tananaev** [comment]
I meant that you have to run it.

**Comment by forlearnios** [comment]
I'm done but it not displaying the new field in the homepage it displays only this....
![screen shot 2017-03-16 at 11 44 28 am](https://cloud.githubusercontent.com/assets/26428130/23984154/0ae57a00-0a3e-11e7-8544-17446d91a47a.png)

**Comment by kumareshsaran** [comment]
i have added a code for adding the new filed in register.js file.But it will not reflected..why what is the   problem on that

**Comment by forlearnios** [comment]
where I can edit the homepage of web

**Comment by tananaev** [comment]
Source code is here:

https://github.com/tananaev/traccar-web

To be able to modify it, you need to have basic knowledge in HTML and JavaScript. If you don't have that knowledge, I would recommend to study it first.

**Comment by forlearnios** [comment]
I have edited the javascript files but it not reflected

**Comment by tananaev** [comment]
It means that you haven't compiled a minified version.

**Comment by forlearnios** [comment]
I'm not clear..

**Comment by tananaev** [comment]
Yes, run the file. Note that it requires some dependencies. Check the script for more info.

**Comment by forlearnios** [comment]
While running this minify.sh file on terminal it shows a sencha: command not found

**Comment by tananaev** [comment]
It means that you have to install sencha cmd. That's why I said it requires dependencies. Please search for the answer first before asking more question.

**Comment by forlearnios** [comment]
sorry for the silly questions because I'm new to mac
