### ISSUE TITLE
Database Store

### ISSUE THREAD

**Issue by AravinthElangovan** [traccar/traccar#3015]
where the registered users data get stored in local:8082 ? and I need storing of raw file details

**Comment by tananaev** [comment]
Database file location can be found in the config file.

**Comment by AravinthElangovan** [comment]
there is no config file in traccar-server-master source code file... please mention the exact name of the database file

**Comment by tananaev** [comment]
You can't run Traccar without a config file.

**Comment by AravinthElangovan** [comment]
I'm using mac in this where I can find that one...

**Comment by AravinthElangovan** [comment]
How can I reterieve the database file to see manually

**Comment by tananaev** [comment]
Are you running official release. If yes, then database file is located in `/opt/traccar/data`.

**Comment by AravinthElangovan** [comment]
Yeah I using the offical release....

**Comment by AravinthElangovan** [comment]
In my /opt/traccar/data file it shows two files one is database.mv.db and the another one is database.trace.db I tried to open this file but it shows "files does not exist" command...

**Comment by tananaev** [comment]
How did you try to open them? Make sure that Traccar server is stopped when you open the database.

**Comment by AravinthElangovan** [comment]
when traccar server is on idle can we open the db file ?

**Comment by tananaev** [comment]
No, only one process can access database.
