### ISSUE TITLE
Noran protocol causing exception

### ISSUE THREAD

**Issue by mrameezraja** [traccar/traccar#3016]
Hi @tananaev ,

Thank you for sharing such a tremendous piece of software with us. We are facing problems in connecting noran device (http://www.norantracker.com/Products/Detail/10) NR100 with traccar server. One problem is devices have `alphanumeric imei` numbers (NR09B00001) and traccar is considering every imei number as `long` which is causing exception. We are using traccar server version 3.7.

traccar-server.log:

<pre>An error occurred while converting the varchar value to JDBC data type BIGINT. - SQLServerException (... < QueryBuilder:322 < *:421 < DataManager:204 < DeviceManager:79 < ...)</pre>

wrapper.log:

<pre>WrapperSimpleApp: 
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: java.lang.NullPointerException
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: 	at org.traccar.database.DeviceManager.getAllDevices(DeviceManager.java:143)
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: 	at org.traccar.database.PermissionsManager.refreshPermissions(PermissionsManager.java:99)
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: 	at org.traccar.database.PermissionsManager.<init>(PermissionsManager.java:79)
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:226)
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2017/03/16 11:36:30 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Unknown Source)</pre>

Any help regarding this issue would be highly appreciated.

**Comment by tananaev** [comment]
Traccar does not consider IMEI number as `long`. Unique id is a string and can contain any characters.

**Comment by mrameezraja** [comment]
What could be possibly the issue? Because when i remove alphanumeric imei numbers, all works perfectly well.

**Comment by tananaev** [comment]
Are you using official version of Traccar without any modifications to the config?

**Comment by mrameezraja** [comment]
I am using official version but i have made changes in config as  i am using sql server database.

**Comment by tananaev** [comment]
So, can we see the config?

**Comment by mrameezraja** [comment]
Thank you so much @tananaev for your time. Issue is resolved now, below query was causing this issue.
<pre>SELECT CONCAT('1', IMEI_NUMBER) AS id, IMEI_NUMBER AS uniqueId FROM TX_GPS_DEVICES;</pre>

There is another problem. Noran protocol is not working. I have enabled `noran.port`. I have disabled all firewalls but having no luck. If i use another very basic udp server, port seems to be open but when i enabled it in traccar port doesn't reply. What could be the issue? I am using traccar v3.7

Thanks

**Comment by tananaev** [comment]
If server received data, you should at least be able to see HEX data in the log.

**Comment by mrameezraja** [comment]
Traccar server is not receiving data from noran devices, although i have a very basic udp server which is recieving data. Other protocol devices are working perfect. Here is screenshot from a test udp server:

<img width="677" alt="screen shot 2017-03-20 at 6 51 32 pm" src="https://cloud.githubusercontent.com/assets/8121938/24102586/4a307d1e-0d9e-11e7-8774-635ae298e492.png">

**Comment by tananaev** [comment]
If you don't see HEX messages in the Traccar log, it means that server doesn't receive any data from your device.

**Comment by mrameezraja** [comment]
Finally i am able to connect device. But battery/power attribute is not present in whole log (more than 200 logs of this specific device). Location data is fine.

Here is the log:
<pre>
2017-03-29 00:16:21 DEBUG: [35868E97: 5053 < 208.54.4.137] HEX: 34000800010c01000000000026438f75f4c2d2d315424e523039423238363136000031372d30332d32392030303a31363a313300
2017-03-29 00:16:21 DEBUG: uniqueId: NR09B0026, data: null
2017-03-29 00:21:04  INFO: [35868E97] id: NR09B0026, time: 2017-03-29 00:20:57, lat: 37.43969, lon: -122.23918, speed: 8.6, course: 224.0, attributes: {raw=34000800010b1000000000006043767af4c23ec215424e523039423238363136000031372d30332d32392030303a32303a353700, ip=208.54.4.137, distance=52.18, totalDistance=41930.92}
</pre>

**Comment by tananaev** [comment]
Traccar doesn't support battery for this particular protocol. Not sure if it's because doesn't report it, or it's just not implemented yet.
