### ISSUE TITLE
Postgresql database

### ISSUE THREAD

**Issue by robertoalmeida** [traccar/traccar#302]
The traccar and traccar-web work with postgresql database?

**Comment by GiSSoTesla** [comment]
How to create a DB in postgre  without sql ineqtion

**Comment by tananaev** [comment]
If you have correct config, you just need to open web interface once and it will generate database schema.

**Comment by tananaev** [comment]
If you are asking how to create database itself, you should be able to use any database client to do it (http://www.postgresql.org/docs/9.0/static/sql-createdatabase.html).

**Comment by GiSSoTesla** [comment]
No, im create tables in db traccar on postgre9.3, launch traccar.bat. How a create a new device with ID in postgre database? in next time need actualise web interface for postgre. If this was done. Im have donate this project. In standart sheme Wharper+traccar+h2db im recive in port 5006 HEX packet but he dont show in a web.

**Comment by tananaev** [comment]
I don't quite understand what the problem. Can you please give more details on what you are doing and what's going wrong.
