### ISSUE TITLE
 failed: Error during WebSocket handshake: Unexpected response code: 405

### ISSUE THREAD

**Issue by hengsoheak** [traccar/traccar#3020]
I've installed Traccar on Ubuntu within below server environment 
Server: ubuntu16  (digitalOcean)
Traccar 3.9
Devices: 
IPhone 6 pluse: port 5055
JM01:port 5053

everything working as well if you run without database configuration so after i configured database and all tables were created but Finally I can not see my device on the map and got error logs on browser and traccars logs on server is working as well it simply don't track any report or write the login event the WebSocket already send many errors on client browser.

 failed: Error during WebSocket handshake: Unexpected response code: 405

Please watch the images

![ice_screenshot_20170317-121102](https://cloud.githubusercontent.com/assets/812528/24029708/f2c9fc20-0b0a-11e7-93f5-1359951cc52f.png)

**Comment by tananaev** [comment]
It means that you have some problem with network.

**Comment by hengsoheak** [comment]
mean that my https block broxy or I have wrong proxy configuration?

**Comment by tananaev** [comment]
Possibly, but it can also be any other network issue as well.

**Comment by hengsoheak** [comment]
I've spent 3 days till now I still can not display the map so bad now my boos so angry

**Comment by tananaev** [comment]
You should check with your IT department. It's possible that something is blocked on your corporate network.

**Comment by fernandogutierrez27** [comment]
same issue when running over https

**Comment by tananaev** [comment]
@fernandogutierrez27, not sure what kind of comment you expect. It's either your network issue or proxy issue.

**Comment by hengsoheak** [comment]
Now it is working when I restart my server
