### ISSUE TITLE
HO2 devices reporting ignition on wrong

### ISSUE THREAD

**Issue by rdentandt** [traccar/traccar#3021]
Good day

I have a few HO2 devices and they are reporting the opposite of the ignition state. Eg. when ignition is off it reports it on and visa versa. What can I check?

Thanks

**Comment by rdentandt** [comment]
To clarify. All HO2 devices report wrong other protocols are fine.

**Comment by tananaev** [comment]
It's a know issue. It has been discussed many times and it will be fixed with next release.

**Comment by anasanzari** [comment]
is this fixed?
