### ISSUE TITLE
Change user using SQL query

### ISSUE THREAD

**Issue by inghoward** [traccar/traccar#3023]
Hello,
I want to change some user directly using SQL query, but I note somethig extrange. For example, If I change 'name' field in 'users' table then traccar UI doesn't show the changes, it keeps showing the old name. But, if the name is changed using UI, then the field 'name' changes as desired. Why?

**Comment by jaimzj** [comment]
Hello,

Changes done directly into database, will not reflect in the UI immediately, in some cases it would reflect after you logout of UI and relogin and in some cases, it would reflect after you restart the traccar service.

The best option is to use the Traccar API's to make changes etc to the database.

**Comment by tananaev** [comment]
Traccar has internal cache which won't be updated when you do changes directly in the database. As @jaimzj pointed out, you should be using API for any modifications.

**Comment by inghoward** [comment]
Thanks for your responses.
I can't find the way to change the name of user with id=2 using API, can you show me what is wrong in here, please?

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>testing api</title>
  </head>
  <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script type="text/javascript">  
//var id = "2"; 
var name = "New Name";
$.ajax({
    type: 'put',
    url: 'http://myserver.com/api/users/{2}',
    contentType: 'application/json',
    headers: {
        "Authorization": "Basic " + btoa("myemail@gmail.com" + ":" + "thepassword")
    },
    data:JSON.stringify({
          //id:id,
          name:name
        }),
    success: function (response) {
        console.log(response);
        //return response;
        }
});

    </script>
  </body>
</html>

**Comment by tananaev** [comment]
You have to send full user model in the payload.

**Comment by inghoward** [comment]
Thanks for your responses.
I can't find the way to change the name of user with id=2 using API, can you show me what is wrong in here, please?

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>testing api</title>
  </head>
  <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script type="text/javascript">  
//var id = "2"; 
var name = "New Name";
$.ajax({
    type: 'put',
    url: 'http://myserver.com/api/users/{2}',
    contentType: 'application/json',
    headers: {
        "Authorization": "Basic " + btoa("myemail@gmail.com" + ":" + "thepassword")
    },
    data:JSON.stringify({
          //id:id,
          name:name
        }),
    success: function (response) {
        console.log(response);
        //return response;
        }
});

    </script>
  </body>
</html>
```

**Comment by inghoward** [comment]
I've deleted the previous comment by mistake.
For example, I want to modify the name of user with id=2. 
Is this url ok? 'http://myserver.com/api/users/{2}',

When you say i have "to send full user model in the payload", you mean that I have to send all fields in row of users table, not only the name field?

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>testing api</title>
  </head>
  <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script type="text/javascript">
    
//var id = "2"; 
var name = "New Name";

$.ajax({
    type: 'put',
    url: 'http://myserver.com/api/users/{2}',
    contentType: 'application/json',
    headers: {
        "Authorization": "Basic " + btoa("myemail@gmail.com" + ":" + "mypassword")
    },
    data:JSON.stringify({
          //id:id,
          name:name
        }),
    success: function (response) {
        console.log(response);
        //return response;
        }
});

    </script>
  </body>
</html>
```

**Comment by tananaev** [comment]
The URL is correct.

Yes, you need to send all fields.

**Comment by inghoward** [comment]
Still not working. Now script have all fields. What is wrong here?

´´´
var data = {
    id: 2,
    name: 'New name',       
    email: 'tester@hotmail.com',
    admin: 0,
    hashedpassword: '5DC736989FEDD1D772C1DEFFCBAEAA27B050D391CEF3EB9C',
    salt: 'BFC74315A9F79DC9FAD3B1D1752086E139550F60FAF6D834',
    map: 'osm',
    distanceunit: 'km',
    speedunit: 'kmh',
    latitude: 0,
    longitude: 0,
    zoom: 0,
    twelvehourformat: 1,
    coordinateformat: '',
    disabled: 0,
    expirationtime: 2017-03-31,          
    devicelimit: 2,
    userlimit: 1,
    readonly: 0,
    devicereadonly: 0,
    attributes: {}
}

$.ajax({
    type: 'put',
    url: 'http://myserver.com/api/users/{2}',
    contentType: 'application/json',
    headers: {
        "Authorization": "Basic " + btoa("mymail@gmail.com" + ":" + "password")
    },
    data:JSON.stringify(data),
    success: function (response) {
        console.log(response);
        }
});
```

**Comment by tananaev** [comment]
What's the response?

**Comment by inghoward** [comment]
Status code 400 (bad request). Request body:

{"id":2,"name":"New name","email":"myemail@hotmail.com","admin":0,"hashedpassword":"5DC736989FEDD1D772C1DEFFCBAEAA27B050D391CEF3EB9C","salt":"BFC74315A9F79DC9FAD3B1D1752086E139550F60FAF6D834","map":"osm","distanceunit":"km","speedunit":"kmh","latitude":0,"longitude":0,"zoom":0,"twelvehourformat":1,"coordinateformat":"","disabled":0,"expirationtime":"2017-03-31","devicelimit":2,"userlimit":1,"readonly":0,"devicereadonly":0,"attributes":{}}

**Comment by inghoward** [comment]
I found the problem. Fields in data array was incorrect. Accepted values are listed below and are not exactly the fields in data base table users.

```
var data = {
    id: 2,
    name: 'New name',       
    email: 'myemail@hotmail.com',
    admin: 0,
    password: 'thedesiredpassword',
    map: 'osm',
    distanceUnit: 'km',
    speedUnit: 'kmh',
    latitude: 0,
    longitude: 0,
    zoom: 0,
    twelveHourFormat: 1,
    coordinateFormat: '',
    disabled: 0,
    expirationTime: '2017-03-31',          
    deviceLimit: 2,
    userLimit: 1,
    readonly: 0,
    deviceReadonly: 0,
    token: '',
    attributes: {}
}```

**Comment by inghoward** [comment]
But, what is the format of expirationTime? It works with '2017-03-31', but not  '2017-03-31 00:00:00'.

**Comment by inghoward** [comment]
API documentation lacks of this two variables userLimit and deviceReadonly.

**Comment by tananaev** [comment]
I guess it hasn't been updated yet. User limit is a number of users can be registered by this account. Device readonly flag means that the user won't be able to create or modify devices.
