### ISSUE TITLE
Which port can I use with my protocol?

### ISSUE THREAD

**Issue by Gefe1** [traccar/traccar#3024]
Hello how are you?

I am trying to configure my tracker and I can not find the protocol or maybe I have to add it.

My protocol is:
```
$GPRMC,ID,092313.299,A,2238.8947,N,11355.2253,E,0.00,311.19,010307,0,,SSSS,MMMMM, AA, mcc,mnc,cid,lac,0-100
```
$GPRMC: Data head
ID: 15 digit IMEI number 
UTC Time: 09:23 13.299
(A) Data is valid
Latitude: 2238.8947,North
Longitude: 11355.2253,East
Speed: 0.00 KM
Course: 311.19
Date: 01032007
Vehicle Status :SSSS
Mileage: MMMMM ( if set)
AA: Battery status
AGPS data : mcc,mnc,cid,lac   
0-100: Fuel level data by percent %

Which port should I use or need to add?
I'm using the latest version of Traccar (3.1.0)

Regards,

**Comment by tananaev** [comment]
It looks like ExtremTrac protocol, port 5126.

There is no version 3.1.0. I guess you meant 3.10.

**Comment by Gefe1** [comment]
Thank you very much, I'll steal and then confirm. Actually 3.10

I have one last query I have an obd device of the brand coban 306A. Is it possible to read ODO on the platform? I use port 5001 but I can not see ODO, I can only read three values ​​that I do not know that means are in 0 and 0%

**Comment by tananaev** [comment]
If your device sends OBD data, you should be able to see ODO value.

**Comment by Gefe1** [comment]
Yes, send obd values but I can not see

**Comment by tananaev** [comment]
I need to see OBD message sample from the server log.

**Comment by Gefe1** [comment]
Okay, I'll send it to you on Monday.

**Comment by Gefe1** [comment]
Hello Tananaev
I have the coban protocol 306A

As I can add?, it is pdf format

**Comment by tananaev** [comment]
So, where is the documentation?

**Comment by Gefe1** [comment]
How can I add to the forum?

**Comment by Gefe1** [comment]
[coban+GPRS+PROTOCOL_20141220_public%28default%29.pdf](https://github.com/tananaev/traccar/files/854605/coban.GPRS.PROTOCOL_20141220_public.28default.29.pdf)

**Comment by tananaev** [comment]
It's GPS103 protocol, so port 5001 should work for your device.

**Comment by Gefe1** [comment]
I know

But I can not read the values
![306a](https://cloud.githubusercontent.com/assets/12430402/24098196/94f7caee-0d69-11e7-9aaf-96e73f4ba136.png)

**Comment by Gefe1** [comment]
Hello,

With respect to the locator of the first question, it is not 5126

Regards,

**Comment by tananaev** [comment]
What values you cannot read?

If port 5126 doesn't work, I need protocol documentation and some message samples to investigate the problem.

**Comment by Gefe1** [comment]
Hi,
I attach the document with the protocols
[NEW EX PROTOCOL 2017 GREEN MC600.pdf](https://github.com/tananaev/traccar/files/858130/NEW.EX.PROTOCOL.2017.GREEN.MC600.pdf)

**Comment by tananaev** [comment]
I also need HEX message samples from real device.

**Comment by Gefe1** [comment]
Hello,
I have sent the messages to the tracker to configure, ip, port and apn. After this I can not receive the report by gprs, I have set port 5001 to receive.

Do you know if I'm doing something wrong?

regards

**Comment by tananaev** [comment]
Check this guide:

https://www.traccar.org/troubleshooting/
