### ISSUE TITLE
Feature request - Visibility of devices

### ISSUE THREAD

**Issue by Arturo2017** [traccar/traccar#3025]
In devices windows, would be great to have a checkbox by devices showing on the map (header default ALL)

![18 de marzo de 2017 21018 cet](https://cloud.githubusercontent.com/assets/25770031/24067731/b9fb40f4-0b80-11e7-8b3b-d4c51350b08b.jpg)

**Comment by conorwhyman** [comment]
Good idea. Would be also useful if we had an option that only the online devices would be visible.

**Comment by Abyss777** [comment]
@tananaev 
Where will we store state of this switches between sessions?

**Comment by tananaev** [comment]
I don't think we should.

@Arturo2017, what if we just had an option to switch between all/online only devices? Would that work for you? If not, please explain the use case.

**Comment by Abyss777** [comment]
Just looking for icons for switcher "All/Online"...
One suggestion is
All - http://fontawesome.io/icon/eye/
Online - http://fontawesome.io/icon/low-vision/

Or

All - http://fontawesome.io/icon/chain-broken
Online - http://fontawesome.io/icon/link

May be some other?

**Comment by tananaev** [comment]
I like the first one.

**Comment by Arturo2017** [comment]
Explanation to my example of the upper image: 1&3 devices are from one group while devices 2,4,5,6 are from another group.

http://traccar.litvak.su/features/visibility.html

**Comment by tananaev** [comment]
I see. We already have filtering by groups and search. Maybe we can use that for filtering devices on map as well. Also, we can add another filter by online/offline status. I think it would cover most of the cases.

**Comment by Abyss777** [comment]
We can add Status column and use this ExtJS feature http://examples.sencha.com/extjs/6.2.0/examples/kitchensink/#grid-filtering

And reflect devices filtering on the map.

**Comment by tananaev** [comment]
Sounds even better than my idea. Then we can remove regular search field.

**Comment by Abyss777** [comment]
The only doubt I have is performance of map markers update.
We will have to add/remove three type of markers from layers. (device, accuracy, liveRoute)

**Comment by tananaev** [comment]
I think if we do it properly, performance impact should be minimal.

**Comment by Arturo2017** [comment]
![img_20170321_105507_691](https://cloud.githubusercontent.com/assets/25770031/24141962/65e76fc2-0e25-11e7-9711-911b6f480bc8.jpg)

Anton&Andrey you are very big!!! THANKS

**Comment by tananaev** [comment]
We have filtering and search that hides devices. I think that should be enough for most use cases. If not, please create a ticket in the `traccar-web` repo with details.
