### ISSUE TITLE
Deployment of traccar server and web interface

### ISSUE THREAD

**Issue by BinduArora** [traccar/traccar#3029]
Hi,

I need help to deploy traccar server and web interface. I have build the traccar server, which resulted a tracker-server-jar-with-dependencies.jar and tracker-server.jar

Thanks
Bindu

**Comment by tananaev** [comment]
Have you tried reading the documentation?

https://www.traccar.org/build/

**Comment by BinduArora** [comment]
Yes, thats what I followed and using command line option mvn package it has
build the server.

**Comment by tananaev** [comment]
I suggest you read the full page before asking any further questions.

**Comment by BinduArora** [comment]
Hey,

I tried further steps also and while running setup/package.sh, it is giving
following error, even if I already installed sencha cmd from given patch:

Missing sencha cmd package (
https://www.sencha.com/products/extjs/cmd-download/)

Thanks
Bindu

**Comment by tananaev** [comment]
Compiling everything from source code requires some technical expertise. If the script can't find sencha cmd, you should probably modify your PATH environment variable to include sencha location.

**Comment by junaidalimughal** [comment]
Hi, tananaev. 
I am modifying traccar web interface. I needed to modify some dialogues like Device and User.
I changed the code in view files. Then, I build the web app using minify.sh but I don't see the changes being reflected on interface. 

Do I need to compile back-end too, to be able to make the changes show in interface?

**Comment by tananaev** [comment]
If you are changing web app only, you don't need to compile back-end.

**Comment by junaidalimughal** [comment]
Well, I have traccar-web-master in a separate folder. I implement changes in that folder and then build using minify.sh. After that i copy the web folder from that location and then replace it web folder in /opt/traccar/ ... is this right approach ... it doesn't seem because i am unable to reflect the changes. 

Is there any problem with the approach?

**Comment by tananaev** [comment]
Have you cleared browser cache? If it still doesn't help, use browser console to debug your problem. Traccar just serves static files. There are no tricks there.

**Comment by junaidalimughal** [comment]
Thank you Tananaev.
