### ISSUE TITLE
Google Street Maps

### ISSUE THREAD

**Issue by Gefe1** [traccar/traccar#3030]
Hello

I use google street maps in taccar. Version view
like in the picture

![maps-street-view](https://cloud.githubusercontent.com/assets/12430402/24107815/100d9548-0d8c-11e7-9eb6-05f85dc0f339.png)

**Comment by tananaev** [comment]
Good for you, but what is your question or problem?

**Comment by Gefe1** [comment]
Hello,

My question is, how can I get the link to add map street view?
Regards

**Comment by tananaev** [comment]
You modify the source code to add new functionality. What kind of answer do you expect here?

**Comment by Gefe1** [comment]
Ok I'll try tomorrow

How can i get the bing map to add?

thanks

**Comment by tananaev** [comment]
Check this page:

https://www.traccar.org/map-layers/

**Comment by Gefe1** [comment]
I just needed an example link for google street view and for bing. Just provide an example to develop and buy the license

Is for a personal business project, I am interested in paying license and paying for development assistance if necessary. Some functions may not be within my grasp.

**Comment by tananaev** [comment]
Code for Bing Map is in the `traccar-web` repo. I don't have any examples for Google Street View.

**Comment by miqueiasjed** [comment]
Como faço para adquirir o Google Street Maps?

**Comment by tananaev** [comment]
We have added a link to Street Views to the modern app.
