### ISSUE TITLE
Traccar stopped working frequently

### ISSUE THREAD

**Issue by himsashu** [traccar/traccar#3033]
I am running only 2 GPS Devices on a Traccar Server with 512MB RAM server.
The server is getting stopped randomly anytime and require it to be restart.
**The log of Wrapper.log is as below:**
```
INFO|wrapper|Service traccar|17-03-21 00:46:15|waitpid 5839 9
INFO|wrapper|Service traccar|17-03-21 00:46:15|exit code posix process: 9 application: 0
```
I successfully test OpenGTS with same 2 devices (GT06) on same server without any issue for few months. I am telling you this because previously I always thought that OpenGTS is more resource hungry but Traccar is light weight. Although I never made any testing. It is just my thought.

What could be the reason for this.

**Comment by tananaev** [comment]
I always recommend at least 1GB server for Traccar. It's possible to configure it to work on 512MB, but it requires some configuration (e.g. Java heap size).

**Comment by himsashu** [comment]
Hi Sir
Thanks for your reply.
If I am planning to add 100 devices (GT06 protocol), what should be the server configuration. Is there any formula to calculate it (I know it may not exist)??? But still want to know if I scale it then what should be server configuration.

**Comment by tananaev** [comment]
For 100 devices 1GB would be a minimum. I don't have a formula. It's mostly just from experience.

**Comment by romariogland** [comment]
4all, who wants, my config (for example):
~500 devices, HW: i3-2120, 8Gb RAM, SATA 3 HDD, FW: CenOS6_x86_64, MySQL 5.7, Oracle JRE8u121. With this config LA ~ 0.6...1.0, but HDD is in record mode usually. 1-2 time a week traccar stops themself, but I have not studied this issue

**Comment by tananaev** [comment]
I suspect that you have some other services running on the server, because with that hardware you server should easily be able to handle 500. Some demo servers have similar configuration and more devices and I almost never restart them. Maybe once in a few months.

**Comment by romariogland** [comment]
No other services: virgin system with traccar, mysqld and jre only. But it is no issue
