### ISSUE TITLE
Incorrect date value

### ISSUE THREAD

**Issue by remorquagesos** [traccar/traccar#3046]
In the web server of Traccar, the ''Time Value'' in the ''State'' file is incorrect for some of the devices. It shows that the value is in 2022-01-21. Though it is shown correctly in the devices box ''Last Update''. Is there a way to correct this issue?
![traccar date issue](https://cloud.githubusercontent.com/assets/26631843/24260808/6987cc56-0fcb-11e7-8989-22b77663ce4c.png)

**Comment by tananaev** [comment]
What protocol is that? H02?

**Comment by remorquagesos** [comment]
what do you mean about protocol?? and H02???

**Comment by tananaev** [comment]
Which port are you using?

**Comment by remorquagesos** [comment]
5001

**Comment by tananaev** [comment]
Then most likely it means that your device reported invalid data.

**Comment by remorquagesos** [comment]
i'm thinking that the traccar change the date alone, when i reconfigure it, it's working but i need to know why traccar change the date??

**Comment by tananaev** [comment]
Traccar doesn't change the date.

**Comment by remorquagesos** [comment]
Who’s changing the date????

 

Caroline Fortin

Directrice des opérations

 <mailto:francis.beauregard@remorquagesos.ca> caroline.fortin @remorquagesos.ca

 

 

Tél:  (418) 818-1818

Sans frais:  1-866-696-5123

Fax:  (418) 696-5931

1480, boul. du Royaume O

Saguenay, QC

G7H 5B1

www.remorquagesos.ca <http://www.remorquagesos.ca/> 

  <http://www.remorquagesos.ca/yannick/pubemail.jpg> 

 

De : Anton Tananaev [mailto:notifications@github.com] 
Envoyé : 24 mars 2017 07:39
À : tananaev/traccar <traccar@noreply.github.com>
Cc : remorquagesos <info@remorquagesos.ca>; Author <author@noreply.github.com>
Objet : Re: [tananaev/traccar] Incorrect date value (#3046)

 

Traccar doesn't change the date.

**Comment by tananaev** [comment]
Time the "State" panel is directly from device.
