### ISSUE TITLE
Expiration date of the Device and new Report.

### ISSUE THREAD

**Issue by hceccacci** [traccar/traccar#3056]
Can we limit the date when a device is available to a user? Example: If an administrator includes another device for the same user, this user's expiration date will be the expiration date of the new device, but the expiration date of the current device must be maintained.
It is also important to have a report that shows this relationship between User  X Groups X Expiration Date X Devices.

**Comment by tananaev** [comment]
No, it's not possible. At the moment only users have expiration dates.

**Comment by hceccacci** [comment]
Is it in roadmap? Thanks!

**Comment by tananaev** [comment]
I don't think it is.
