### ISSUE TITLE
MySQL error unknown column

### ISSUE THREAD

**Issue by vijaemanlapaz** [traccar/traccar#3057]
`Caused by: liquibase.exception.DatabaseException: Unknown column 'groupid' in 'IN/ALL/ANY subquery' [Failed SQL: UPDATE traccarDB.devices SET groupid = NULL WHERE groupid NOT IN (SELECT id FROM groups)]`

any idea how to fix this? im stuck

**Comment by tananaev** [comment]
Does this error happen on official Traccar release? What version of MySQL are you using?

**Comment by vijaemanlapaz** [comment]
hi anton,

Thank you for the reply, i was my fault i was configuring the wrong xml
file, it's all good now

i just have a question,i have a previous installation of tracca it uses h2
database hiw can i migrate the data to mysql?? my new installation now is
using mysql

**Comment by tananaev** [comment]
I guess the only option is to manually copy all the data. There might be some tools that can help you.

**Comment by vijaemanlapaz** [comment]
d you have documentation on how can do that?

**Comment by tananaev** [comment]
No, I don't, but it's not something specific to Traccar system.
