### ISSUE TITLE
wrapper problem

### ISSUE THREAD

**Issue by manoj425** [traccar/traccar#3059]
hi i too facing same issue
```
INFO | wrapper | 2017/03/27 11:40:55 | Wrapper Process has not received any CPU time for 50 seconds. Extending timeouts.
INFO | wrapper | 2017/03/27 11:41:34 | Wrapper Process has not received any CPU time for 39 seconds. Extending timeouts.
INFO | wrapper | 2017/03/27 11:42:07 | Wrapper Process has not received any CPU time for 32 seconds. Extending timeouts.
INFO | wrapper | 2017/03/27 11:43:02 | Wrapper Process has not received any CPU time for 54 seconds. Extending timeouts.
INFO | wrapper | 2017/03/27 11:43:35 | Wrapper Process has not received any CPU time for 33 seconds. Extending timeouts.
INFO | wrapper | 2017/03/27 11:44:35 | Wrapper Process has not received any CPU time for 60 seconds. Extending timeouts.
INFO | wrapper | 2017/03/27 11:45:35 | Wrapper Process has not received any CPU time for 60 seconds. Extending timeouts.
INFO | wrapper | 2017/03/27 11:46:35 | Wrapper Process has not received any CPU time for 60 seconds. Extending timeouts.
INFO | wrapper | 2017/03/27 11:47:08 | Wrapper Process has not received any CPU time for 32 seconds. Extending timeouts.
INFO | jvm 1 | 2017/03/27 11:52:06 | 2017-03-27 11:52:06,550 WARN [0-BAM::
```

**Comment by tananaev** [comment]
What are your server hardware specs?

**Comment by manoj425** [comment]
INFO   | jvm 1    | 2017/03/28 01:05:13 | 2017-03-28 01:05:13,108 WARN [scheduler_Worker-5] [JmsTemplateMessageSender] JmsException when trying to send message com.atlassian.bamboo.v2.build.agent.messages.UpdateHeartbeatMessage@64afe0f0. Retrying...
INFO   | jvm 1    | 2017/03/28 01:05:13 | org.springframework.jms.UncategorizedJmsException: Uncategorized exception occured during JMS processing; nested exception is javax.jms.JMSException: org.apache.activemq.transport.RequestTimedOutIOException
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.springframework.jms.support.JmsUtils.convertJmsAccessException(JmsUtils.java:316)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.springframework.jms.support.JmsAccessor.convertJmsAccessException(JmsAccessor.java:169)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:494)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.springframework.jms.core.JmsTemplate.send(JmsTemplate.java:566)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.springframework.jms.core.JmsTemplate.convertAndSend(JmsTemplate.java:689)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.springframework.jms.core.JmsTemplate.convertAndSend(JmsTemplate.java:677)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at com.atlassian.bamboo.v2.build.agent.remote.sender.JmsTemplateMessageSender.send(JmsTemplateMessageSender.java:42)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at com.atlassian.bamboo.v2.build.agent.remote.heartbeat.AgentHeartBeatJob.sendHeartbeat(AgentHeartBeatJob.java:89)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at com.atlassian.bamboo.v2.build.agent.remote.heartbeat.AgentHeartBeatJob.execute(AgentHeartBeatJob.java:56)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:49)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:525)
INFO   | jvm 1    | 2017/03/28 01:05:13 | Caused by: javax.jms.JMSException: org.apache.activemq.transport.RequestTimedOutIOException
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:72)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.apache.activemq.ActiveMQConnection.doSyncSendPacket(ActiveMQConnection.java:1459)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1439)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.apache.activemq.ActiveMQSession.send(ActiveMQSession.java:1809)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.apache.activemq.ActiveMQMessageProducer.send(ActiveMQMessageProducer.java:289)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.apache.activemq.ActiveMQMessageProducer.send(ActiveMQMessageProducer.java:224)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.apache.activemq.jms.pool.PooledProducer.send(PooledProducer.java:77)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.apache.activemq.jms.pool.PooledProducer.send(PooledProducer.java:60)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.springframework.jms.core.JmsTemplate.doSend(JmsTemplate.java:633)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.springframework.jms.core.JmsTemplate.doSend(JmsTemplate.java:604)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.springframework.jms.core.JmsTemplate$3.doInJms(JmsTemplate.java:569)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:491)
INFO   | jvm 1    | 2017/03/28 01:05:13 |       ... 12 more
INFO   | jvm 1    | 2017/03/28 01:06:12 | Caused by: org.apache.activemq.transport.RequestTimedOutIOException
INFO   | jvm 1    | 2017/03/28 01:06:12 |       at org.apache.activemq.transport.FutureResponse.getResult(FutureResponse.java:54)
INFO   | jvm 1    | 2017/03/28 01:06:12 |       at org.apache.activemq.transport.ResponseCorrelator.request(ResponseCorrelator.java:92)
INFO   | jvm 1    | 2017/03/28 01:06:12 |       at org.apache.activemq.ActiveMQConnection.doSyncSendPacket(ActiveMQConnection.java:1446)
INFO   | wrapper  | 2017/03/28 01:06:12 | Wrapper Process has not received any CPU time for 59 seconds.  Extending timeouts.
INFO   | jvm 1    | 2017/03/28 01:06:12 |       ... 22 more
INFO   | jvm 1    | 2017/03/28 01:06:12 | 2017-03-28 01:05:13,116 INFO [scheduler_Worker-10] [AgentHeartBeatJob] Not sending a new heartbeat since an old one is still being sent, last successful transmission time was 2 minutes ago, dropping the current heartbeat...

**Comment by JoseIgnacioD** [comment]
Hi, any solution for this problem? I have the same issue. Thanks!

**Comment by tananaev** [comment]
We haven't used wrapper for a very long time now.
