### ISSUE TITLE
 Message misunderstood 

### ISSUE THREAD

**Issue by FanSem** [traccar/traccar#3062]
Hi Anton,

I try to connect my device with traccar by sending binary format,
 At the first time this is  the message sent :
```
Remote <-- AVL
00 4B 00 02 00 01 46 DD F3 0A 46 33 00 02 00 2E 0B 2E 1E 11 03 1C 00 33 3A 92 FF
F4 5D 03 00 00 21 00 02 09 3D 00 00 07 C1 08 0A 00 01 00 00 00 00 00 0B 2E 1E 1
1 03 1C 09 38 37 11 03 1D
```
and this message which must be sent every time 
but here is the message sent after that : 
```
Remote <-- AVL (Heart beat)
00 1E 00 02 00 01 46 DD F3 0A 46 33 00 AB 00 06 09 39 0D 11 03 1D
Remote --> AVL
0D 0A 44 49 53 43 4F 4E 4E 45 43 54 0D 0A
DISCONNECT
```

 I did not understand these messages sent after,can you please tell me what is the problem

**Comment by tananaev** [comment]
What protocol is that? Are those messages from Traccar logs?

**Comment by FanSem** [comment]
IntellitracProtocol in binary format ,and those  messages are not from traccar logs

**Comment by tananaev** [comment]
Traccar doesn't support Intellitrac binary format at the moment.

**Comment by FanSem** [comment]
Hi,
yes I know ,and i try to treat the binary format i just want o ask you if traccar return erreur message  to a device  if it doesn't know the format

**Comment by tananaev** [comment]
No, it doesn't.

**Comment by FanSem** [comment]
Ok thank you Anton,
but we can for sure see that traccar send a message to the device after a heart beat one incoming from the device ... can you pliz tell me what is that message ?? 
regards

**Comment by tananaev** [comment]
Can I see Traccar log?

**Comment by FanSem** [comment]
2017-03-30 12:36:27 DEBUG: [E3A156BC: 5133 < 45.216.247.9] HEX: 03ef0002000146ddf30a46330002002e0e153211031c00333a92fff45d1a0000400001026b000007f30e07000100000000000e153211031c0b241c11031e
2017-03-30 12:36:36  INFO: [3FDD7A2F] connected
2017-03-30 12:36:37 DEBUG: [3FDD7A2F: 5133 < 196.112.40.22] HEX: 004f0002000146ddf30a463300ab00060b242511031e
2017-03-30 12:36:37  INFO: [3FDD7A2F] disconnected

**Comment by tananaev** [comment]
I don't see any replies from the server.

**Comment by FanSem** [comment]
yes the replies from the server does not appears in the traccar log but in the device terminal we can see that traccar sent a messaege as a respond to the heart beat message sent form the device ...as you can see in the picture bollow

![capture](https://cloud.githubusercontent.com/assets/25926391/24502944/e5ac997a-1547-11e7-8c0a-67af825be008.PNG)

**Comment by tananaev** [comment]
All application layer messages are logged.
