### ISSUE TITLE
Address columns is null

### ISSUE THREAD

**Issue by pedrovasques77** [traccar/traccar#3063]
For some reason the address is not tracked on database since yesterday.
I have the coordinates from the devices but address column is null.
Can some one help me on this topic?

**Comment by tananaev** [comment]
I guess your geocoder service doesn't return any data, so address is null.

**Comment by pedrovasques77** [comment]
How can I test?
I was using the google API but now i changed to:

<entry key='geocoder.enable'>true</entry>
 <entry key='geocoder.type'>gisgraphy</entry>
  <entry key='geocoder.url'>
http://services.gisgraphy.com/reversegeocoding/search</entry>

but still not working.

**Comment by tananaev** [comment]
It won't work. You can't use Nominatim or Gisgraphy free service.

**Comment by pedrovasques77** [comment]
What alternative i have?
Only buy a service? What you recomend?

**Comment by tananaev** [comment]
All free alternatives are limited.

**Comment by pedrovasques77** [comment]
If i need a paid one i need to change the configuration? In terms of costs
and your experience what should we use?

**Comment by tananaev** [comment]
Check this page:

https://www.traccar.org/reverse-geocoding/

It has links to the services where you can compare free limits and prices.

**Comment by malkitsingh** [comment]
@pedrovasques77 best option is to host [nominatim](nominatim.openstreetmap.org) on your server.

**Comment by pedrovasques77** [comment]
thanks, but on traccar server version 3.2 what i need to change to start
using nominatim <http://nominatim.openstreetmap.org/>.
can i do a trial on cloud to test?

**Comment by malkitsingh** [comment]
all you have to do is

<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>nominatim</entry>
<entry key='geocoder.url'>http://your-server.com/reverse.php</entry>

To test it on the cloud, go to [locationiq](http://www.locationiq.org/) and get yourself a new account. Locationiq is the same thing but hosted on some third party server.

**Comment by pedrovasques77** [comment]
I will need to change some server files also?
I changed the config file but still not work.

**Comment by pedrovasques77** [comment]
You know what is the minimum server version to run a geoloc Service
diferente from Google.

Pedro Vasques <pedro.vasques.almeida@gmail.com> escreveu em qui, 30/03/2017
às 12:50 :

**Comment by malkitsingh** [comment]
No, you don't need to change any other file. Change in the config file will do the job. Make sure you restart "traccar" service after making changes to the config file.
I am not sure about minimum version here, may be @tananaev can help on this.
Do you mind sharing your config file code here, there must be something wrong with the config file.

**Comment by tananaev** [comment]
Older versions of Traccar might have some limitations. For example, to use API key for Nominatim server, you need the latest version of Traccar. It means you won't be able to use LocationIQ with your version.

**Comment by pedrovasques77** [comment]
thanks. I will clone may server do the upgrade during the weekend and put
this service running.
I will need to upgrade to 3.4 and then to 3.10?

**Comment by tananaev** [comment]
If you want to use Nominatim with a key, yes.
