### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by RobertoVillegasA** [traccar/traccar#3064]
hello Anton

please help me... recently I generate jar file from source but I can't up server all works fine over IntelliJ IDEA but when I try to update in service instalation dont work

error when I try.......localhost:8082
```
Can not access this website
The localhost page has declined the connection.
Search for localhost 8082 in Google
ERR_CONNECTION_REFUSED
```

wrapper log file
```
[qtp1746257394-79] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@58886d2 in qtp1746257394{STARTED,8<=8<=200,i=2,q=0}
INFO|10264/0|Service traccar|17-03-30 11:36:15|[qtp1746257394-81] WARN org.eclipse.jetty.server.HttpChannel - /
INFO|10264/0|Service traccar|17-03-30 11:36:15|java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.isAsyncSupported()Z
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.server.handler.ResourceHandler.handle(ResourceHandler.java:522)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at java.lang.Thread.run(Unknown Source)
INFO|10264/0|Service traccar|17-03-30 11:36:15|[qtp1746257394-81] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - 
INFO|10264/0|Service traccar|17-03-30 11:36:15|java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getStatus()I
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.server.handler.ErrorHandler.handle(ErrorHandler.java:112)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.server.Response.sendError(Response.java:597)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.server.HttpChannel.handleException(HttpChannel.java:487)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.server.HttpConnection$HttpChannelOverHttp.handleException(HttpConnection.java:621)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:387)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO|10264/0|Service traccar|17-03-30 11:36:15|	at java.lang.Thread.run(Unknown Source)
INFO|10264/0|Service traccar|17-03-30 11:36:15|[qtp1746257394-81] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@58886d2 in qtp1746257394{STARTED,8<=8<=200,i=2,q=0}
```

**Comment by RobertoVillegasA** [comment]
I try with last version of source code

**Comment by tananaev** [comment]
Looks like you are missing some classes.

**Comment by RobertoVillegasA** [comment]
Hello Anton 

yes but also when I run source code ...

[qtp1636588948-85] WARN org.eclipse.jetty.servlet.ServletHandler - /api/socket
java.lang.NullPointerException
	at org.traccar.api.AsyncSocketServlet$1.createWebSocket(AsyncSocketServlet.java:37)
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:166)
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:153)
	at org.eclipse.jetty.websocket.servlet.WebSocketServlet.service(WebSocketServlet.java:151)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tananaev** [comment]
That means that you are trying to connect to the socket without authentication.

**Comment by RobertoVillegasA** [comment]
Hi Anton 
I'm new with that ... please would you tell me how to fix it.... 

thanks.

**Comment by tananaev** [comment]
You don't need to fix that. Just refresh the page and login.

**Comment by jayanti9687** [comment]
Hi @tananaev,

I am getting same issue using with authentictation as described in [app.js](https://github.com/traccar/traccar-web/blob/master/web/simple/app.js).

Good point, when I login using traccar web application one window and call api in next window with my code. Sockets works fine. I think server not setting session while use 'api/session'.

Code:
`        ajax('GET', url + '/api/server', function (server) {
            ajaxSession(function (user) {
                Get('devices', function (devices) {
                    var socket = new WebSocket('ws' + url.substring(4) + '/api/socket');
                    socket.onclose = function (event) {
                        console.log('socket closed');
                    };

                    socket.onmessage = function (event) {
                        var data = JSON.parse(event.data);
                        console.log(data);
                    };
                });
            });
        });
`

Could you please help me?
