### ISSUE TITLE
Traccar server fail to start after replacing tracker-server.jar

### ISSUE THREAD

**Issue by dhavalchikani** [traccar/traccar#3066]
Hello,

Thanks for such a nice tracking server.

I have successfully installed traccar package for from traccar-linux-3.10.zip. It's working very fine.

But I added SOS alert support for Ardi 01 protocol and build again from github source.
When I replace the tracker-server.jar in current setup /opt/traccar and run startDaemon.sh getting following error I am getting in start.

**wrapper error logs:**
```
FINEST|26917/0|Service traccar|17-03-31 13:28:12|INFO 3/31/17 1:28 PM: liquibase: Successfully released change log lock
FINEST|26917/0|Service traccar|17-03-31 13:28:12|[main] INFO org.eclipse.jetty.util.log - Logging initialized @4522ms
FINEST|26917/0|Service traccar|17-03-31 13:28:13|java.lang.reflect.InvocationTargetException
FINEST|26917/0|Service traccar|17-03-31 13:28:13|       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
FINEST|26917/0|Service traccar|17-03-31 13:28:13|       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
FINEST|26917/0|Service traccar|17-03-31 13:28:13|       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
FINEST|26917/0|Service traccar|17-03-31 13:28:13|       at java.lang.reflect.Method.invoke(Method.java:498)
FINEST|26917/0|Service traccar|17-03-31 13:28:13|       at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
FINEST|26917/0|Service traccar|17-03-31 13:28:13|       at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
FINEST|26917/0|Service traccar|17-03-31 13:28:13|Caused by: java.lang.ClassNotFoundException: org/traccar/protocol//Gps103ProtocolDecoder/java
FINEST|26917/0|Service traccar|17-03-31 13:28:13|       at java.lang.Class.forName0(Native Method)
FINEST|26917/0|Service traccar|17-03-31 13:28:13|       at java.lang.Class.forName(Class.java:264)
FINEST|26917/0|Service traccar|17-03-31 13:28:13|       at org.traccar.ServerManager.<init>(ServerManager.java:66)
FINEST|26917/0|Service traccar|17-03-31 13:28:13|       at org.traccar.Context.init(Context.java:307)
FINEST|26917/0|Service traccar|17-03-31 13:28:13|       at org.traccar.Main.main(Main.java:35)
FINEST|26917/0|Service traccar|17-03-31 13:28:13|       ... 6 more
INFO|wrapper|Service traccar|17-03-31 13:28:13|waitpid 26917 59136
INFO|wrapper|Service traccar|17-03-31 13:28:13|exit code posix process: 59136 application: 0
```
Thanks for support in advance.

**Comment by tananaev** [comment]
You need to take all dependencies as well, not just a single JAR file.

**Comment by dhavalchikani** [comment]
Hello,

Thanks for response.

As I am new to JAVA. Can you please explain in some more details regarding what all the things I have to copy after new compilation with tracker-server.jar.

Thanks for your time.

**Comment by dhavalchikani** [comment]
I have also tried to by replacing  **tracker-server-jar-with-dependencies.jar with tracker-server.jar** on  /opt/traccar/ but, still issue persist. Now I am getting below error logs.

Error logs:
INFO|3698/0|Service traccar|17-03-31 19:38:51|INFO 3/31/17 7:38 PM: liquibase: Successfully released change log lock
INFO|3698/0|Service traccar|17-03-31 19:38:51|[main] INFO org.eclipse.jetty.util.log - Logging initialized @4593ms
INFO|3698/0|Service traccar|17-03-31 19:38:52|java.lang.reflect.InvocationTargetException
INFO|3698/0|Service traccar|17-03-31 19:38:52|  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|3698/0|Service traccar|17-03-31 19:38:52|  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|3698/0|Service traccar|17-03-31 19:38:52|  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|3698/0|Service traccar|17-03-31 19:38:52|  at java.lang.reflect.Method.invoke(Method.java:498)
INFO|3698/0|Service traccar|17-03-31 19:38:52|  at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|3698/0|Service traccar|17-03-31 19:38:52|  at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|3698/0|Service traccar|17-03-31 19:38:52|Caused by: java.lang.ClassNotFoundException: org/traccar/protocol//IdplProtocolDecoder/java
INFO|3698/0|Service traccar|17-03-31 19:38:52|  at java.lang.Class.forName0(Native Method)
INFO|3698/0|Service traccar|17-03-31 19:38:52|  at java.lang.Class.forName(Class.java:264)
INFO|3698/0|Service traccar|17-03-31 19:38:52|  at org.traccar.ServerManager.<init>(ServerManager.java:63)
INFO|3698/0|Service traccar|17-03-31 19:38:52|  at org.traccar.Context.init(Context.java:304)
INFO|3698/0|Service traccar|17-03-31 19:38:52|  at org.traccar.Main.main(Main.java:35)
INFO|3698/0|Service traccar|17-03-31 19:38:52|  ... 6 more
INFO|wrapper|Service traccar|17-03-31 19:38:52|waitpid 3698 59136
INFO|wrapper|Service traccar|17-03-31 19:38:52|exit code posix process: 59136 application: 0

Please help me out.
Thanks.

**Comment by tananaev** [comment]
You are still missing some classes. I guess there is some problem with the way you build project.

**Comment by dhavalchikani** [comment]
Hello,

I have followed steps from below link:
https://www.traccar.org/forums/topic/build-traccar-from-source-via-command-line-method-on-ubuntu-server-16-10/

And I have taken source for 3.10 latest release for traccar.

From above steps I have successfully build and generate package also for 3.10 linux installation. That fresh package is working fine first time for me.

But later as I have changes one protocol file and successfully compiled it again. Now replacing the tracker-server.jar with all dependencies fail to start with above logs.

Please guide me if any step I have missed. Don't know what is going wrong.

Thanks for support.

**Comment by tananaev** [comment]
You can compile binary using `mvn package`. I'm not sure why it doesn't work for you.

**Comment by dhavalchikani** [comment]
Yes, I have compiled after change using **"mvn package"** only.

**Comment by tananaev** [comment]
What if you compile without any changes? Do you get the same error?

**Comment by dhavalchikani** [comment]
Yes, the problem exits. I have reverted the changes and compile again from source and replace tracker-server.jar with all the dependencies. But still facing the issue.

First time compilation with the package creation was working fine but later always faced issue once I compiled again and try to replace in existing setup.

Thanks for your support.

**Comment by tananaev** [comment]
I have no idea what the problem is, but it should definitely work if you don't modify anything. Also, make sure that you are using a tag, not master branch.

**Comment by jrkblo** [comment]
@dhavalchikani
Did you fixed your problem?

**Comment by dhavalchikani** [comment]
No, Problem still exist. I failed to do on Ubuntu still. Waiting for any resolution. 

But for now I have installed NetBeans IDE on my windows and with this I have done the changes I required and Its working when I replace tracker-server.jar with all the dependencies.

But It will be very helpful If any one can help me on my ubuntu stuff.

**Comment by jrkblo** [comment]
I was with the same problem.
After building your package with mvn command, open the "target" folder and you you'll see a folder called "lib" there are the libs that @tananaev told you to copy/paste.
![image](https://cloud.githubusercontent.com/assets/11820889/24835264/5a13fdac-1cd3-11e7-9d21-4aa75ee9075f.png)

A'm facing another problem, my st 300hd isn't communicating with my server. I've tried changing the configuration but the gps log only says "server comunication error", but when I try to work with a payed plataform, instead of traccar, it works.

**Comment by tananaev** [comment]
@jrkblo, I would recommend to create another thread for your issue. Also, check this page:

https://www.traccar.org/troubleshooting/
