### ISSUE TITLE
How to filter / delete incorrect datasets ?

### ISSUE THREAD

**Issue by Phantomatz** [traccar/traccar#3067]
Hello, I really enjoy the new version 3.10. Works fine with me, but I have a problem with one of my trackers (TK5000) which sometimes send wrong data 

1. sending positions with date in the future
2. sending positions which are totally of track due to bad GPS fix.

I have not yet found any opportunity to use the filter function to get red of such entries.

1. is very annoying as I need to delete the entries with PHPmyAdmin to assure that the Webinterface works correct again.
2. is vey annoying because, the its takes a lot of effort to correct tracks manually.

Any chance to use the filter functions (now) or maybe in the future ?

**Comment by tananaev** [comment]
You can enable filtering on the server side.

**Comment by Phantomatz** [comment]
Thanks for the feedback, however I do not completely understand which filter would help.

I need filter.enabled = yes together with which other filter settings to get rid of my issues ?


filter.enable	config	Boolean flag to enable or disable position filtering.
filter.limit	config	Time limit for the filtering in seconds. If the time difference between last position and a new one is more than this limit, the new position will not be filtered out.
filter.invalid	config	Filter invalid (valid field is set to false) positions.
filter.zero	config	Filter zero coordinates. Zero latitude and longitude are theoretically valid values, but it practice it usually indicates invalid GPS data.
filter.duplicate	config	Filter duplicate records (duplicates are detected by time value).
filter.distance	config	Filter records by distance. The values is specified in meters.

**Comment by Phantomatz** [comment]
Currently I have set the following filters, but still get faulty record entries with date 2018.

    <entry key='filter.enable'>true</entry>
    <entry key='filter.invalid'>true</entry>
    <entry key='filter.zero'>true</entry>

**Comment by tananaev** [comment]
You can use `filter.future`. The value is in seconds.

**Comment by Phantomatz** [comment]
Thanks a lot for the info. I think its not yet in the documentation. I will put into my config.

Another flag for filter.UnrealisticSpeed to filter all incorrect GPS positions which are caught in areas with bad GPS signal and jump from mid Europe to Africa and back within a few seconds :-).
If could be configured, would be great I would use a much lower max speed for my ebike tracker then for my car. That would allow to eliminate about 99% of the false entries I currently find wrt to weak GPS fix.

**Comment by tananaev** [comment]
I think there are already enough options for filtering.

**Comment by Phantomatz** [comment]
Agreed we have a lot of useful filters, but I do not know, how I could use the existing filters to eliminate the positions which are completely off track due to a bad GPS fix.

filter.distance defines the minimum distance between two positions, but I would need a max distance or max speed.

**Comment by tananaev** [comment]
If you get invalid location, it means that there is something wrong with your GPS device.

**Comment by Phantomatz** [comment]
Thanks for the info ... I try to get the wrong locations out of my logs and have found a strange issue with my tracker Incutex TK5000 (port 5032)

I found a tracker-server.log entry like:
2017-04-18 13:31:27  WARN: Geocoding failed - Empty address - GeocoderExcep$
$8 13:31:26, lat: 842.15070, lon: 942.94276, speed: 6.5, course: 242.0

but even the entry indicates the the location is incorrect, its tracked in traccar and recorded as valid dataset. 

traccar.xml config has defined:
    <entry key='filter.enable'>true</entry>
    <entry key='filter.invalid'>true</entry>

**Comment by tananaev** [comment]
Where does it indicate that it's incorrect?

**Comment by Phantomatz** [comment]
lat: 842.15070, lon: 942.94276 are invalid values I would suppose.

**Comment by tananaev** [comment]
Traccar does not validate the data. It uses validity flag reported by the GPS device.
