### ISSUE TITLE
How to Install API  swagger.json

### ISSUE THREAD

**Issue by aorellanaf** [traccar/traccar#3071]
i install traccar in vps, but how to installa api  swagger.json?

**Comment by tananaev** [comment]
Swagger is just a documentation, so your question doesn't make much sense.

**Comment by aorellanaf** [comment]
Sorry but i dont understand the documentation

**Comment by tananaev** [comment]
If you don't know what it is, you should probably start by researching it.

**Comment by aorellanaf** [comment]
Ok thanks

**Comment by sunhoww** [comment]
@aorellanaf for a more readable format try https://www.traccar.org/api-reference/
it's still in v3.9 but the changes to v3.10 aren't that much.
