### ISSUE TITLE
LBS device not decoding position

### ISSUE THREAD

**Issue by javier260** [traccar/traccar#3076]
Hi, first of all thanks for your software.

I'm trying to use an lbs-only tracker (to consume less power), but not sure if traccar server can decode lbs-only. Sorry if this is answered before. I'm testing with a device using H02 protocol, and traccar log is showing the following:
```
2017-04-04 22:59:21 DEBUG: [38438780: 5013 < 213.143.50.32] HEX: 2a48512c3335333530363131323435373636382c58542c3223

2017-04-04 22:59:35 DEBUG: [38438780: 5013 < 213.143.50.32] HEX: 
2a68712c3335333530363131323435373636382c56312c3033343630302c562c303030302e303030302c4e2c30303030302e303030302c452c3030302e30302c302c3031303131352c46464646464646462c3130302c332c3231342c3030332c323132362c3537332c302c323132362c3537362c32372c302c302c3023

2017-04-04 22:59:35  INFO: [38438780] id: 353506112457668, time: 2015-01-01 04:46:00, lat: 0.00000, lon: 0.00000, speed: 0.0, course: 0.0
```
see that traccar is showing lat:0 and lon: 0,, but if we decode last HEX line at https://www.traccar.org/hex-decoder/ we can get information of cell tower:
```
*hq,353506112457668,V1,034600,V,0000.0000,N,00000.0000,E,000.00,0,010115,FFFFFFFF,100,3,214,003,2126,573,0,2126,576,27,0,0,0#
```
mcc=214 - spain
mnc=3 - orange
lac=2126 
cellid=573

if we put those parameters at following web: http://cellidfinder.com/cells/findcell
we get: Google coordinates: (41.408985, 2.178322)

So I can get possition from log line in traccar. 

Questions are:
Can I use this device with traccar? how?
If this device is not the right one, what device lbs-only should I use with traccar?

Thanks

**Comment by tananaev** [comment]
Yes, Traccar can handle devices like this. You have to configure geolocation provider.

**Comment by javier260** [comment]
Fantastic, Thanks for your quick answer. I'll check where to configure it.

**Comment by javier260** [comment]
Hi another time. Sorry for asking something that probably is in the documentation, but I have not found how to do it. Could you please give a clue about how to configure a geolocation provider for LBS, and if possible, suggest which provider to use? Thanks a lot.

**Comment by tananaev** [comment]
You need to add `geolocation.*`parameters to the config file:

https://www.traccar.org/configuration-file/

**Comment by javier260** [comment]
Thanks, for new info. 
I have tried to get an API key from opencellid but unfortunatly they have new registrations dissabled until 18th. So I tried to test it with mozilla. Not sure if I need also to ask for an API key or not, so I tried the following parameters, but still getting lat 0.00 and lon 0.00

<entry key='geolocation.enable'>true</entry>	
<entry key='geolocation.type'>mozilla</entry>	
<entry key='geolocation.key'>test</entry>	

Questions:
1.- I used geolocation.type = mozilla   Is it the right parameter?

2.-  I've put as key the word 'test' as explained in the following page for testing mozilla: https://location.services.mozilla.com/api
Do I need a key for mozilla? Should 'test' key work?

3) What is going wrong? Where is the log to see what is happening with 'geolocation' decoding?

Thanks

**Comment by javier260** [comment]
upps, seems config lines have been modified in my comments. The parameters I used are the following, but starting with '<' and finisthing with '>':
     entry key='geolocation.enable'>true</entry	
     entry key='geolocation.type'>mozilla</entry	
     entry key='geolocation.key'>test</entry

**Comment by tananaev** [comment]
Looks correct. Possibly it just doesn't return location. Check logs for errors.

**Comment by javier260** [comment]
I think traccar is decoding lat & lon part sent by the device (0.00 & 0.00) and is not decoding LBS information sent in the same line.

`*hq,353506112457668,V1,034600,V,0000.0000,N,00000.0000,E,000.00,0,010115,FFFFFFFF,100,3,214,003,2126,573,0,2126,576,27,0,0,0#`

Is possible to force traccar to decode only LBS information?

Thanks

**Comment by tananaev** [comment]
It's possible to implement decoding if you have protocol documentation.

**Comment by javier260** [comment]
Hi Tananaev,

Protocol is H02, and decoding is working well. 
In the sample line you have LBS information just after 'FFFFFFFF'. In this case "FFFFFFFF,100,3,214,003,2126,573,0,2126,576,27,0,0,0#" -> 
   mcc=214 - spain
   mnc=3 - orange
   lac=2126
   cellid=573

but seems traccar is not using mozilla to get a position from LBS data. It's just using GPS part of the line, where lat & lon is 0.00 because this device has no GPS hardware.

Any option to get position from LBS data with traccar?

Sniff, thanks anyway. :)

**Comment by tananaev** [comment]
Have you enabled geolocation?

**Comment by tananaev** [comment]
Also, if your device reports coordinates with LBS data, you have to enable `processInvalidPositions` flag.

**Comment by malkitsingh** [comment]
this flag is not mentioned anywhere in https://www.traccar.org/configuration-file/

**Comment by tananaev** [comment]
It is now.

**Comment by javier260** [comment]
It's not working for me. I'm still getting lat 0.00 lon 0.00.

`2017-04-19 21:59:22  INFO: [77BFCB5C] id: 353506112457668, time: 2015-01-16 03:45:00, lat: 0.00000, lon: 0.00000, speed: 0.0, course: 0.0

My config file has following entries:

`<entry key='geolocation.enable'>true</entry>
<entry key='geolocation.type'>mozilla</entry>	
<entry key='geolocation.key'>test</entry>	
<entry key='geolocation.processInvalidPositions'>true</entry>	`

@Anton, maybe traccar is not considering lat 0.00 lon 0.00 as "Invalid Position". Could you check it?

Thanks

**Comment by tananaev** [comment]
Probably it's not marked as invalid. It should be if you see "V" in the message.

**Comment by javier260** [comment]
What I see in log is the following:
`2017-04-19 22:21:43 DEBUG: [965EB469: 5013 < 213.143.50.86] HEX: 2a48512c3335333530363131323435373636382c58542c3223
2017-04-19 22:22:13 DEBUG: [965EB469: 5013 < 213.143.50.86] HEX: 2a48512c3335333530363131323435373636382c58542c3223
2017-04-19 22:22:46 DEBUG: [965EB469: 5013 < 213.143.50.86] HEX: 2a48512c3335333530363131323435373636382c58542c3223
2017-04-19 22:23:15 DEBUG: [965EB469: 5013 < 213.143.50.86] HEX: 2a48512c3335333530363131323435373636382c58542c3223
2017-04-19 22:23:39 DEBUG: [965EB469: 5013 < 213.143.50.86] HEX: 2a68712c3335333530363131323435373636382c56312c3033313030302c562c303030302e303030302c4e2c30303030302e303030302c452c3030302e30302c302c3136303131352c46464646464646462c3130302c332c3231342c3030332c323132302c3435302c302c323132362c3537332c33382c323132302c373037302c333723
2017-04-19 22:23:39  INFO: [965EB469] id: 353506112457668, time: 2015-01-16 04:10:00, lat: 0.00000, lon: 0.00000, speed: 0.0, course: 0.0`

Hex decoded
"2a48512c3335333530363131323435373636382c58542c3223"  -> *HQ,353506112457668,XT,2#
"2a6871 .... 33723" -> *hq,353506112457668,V1,031000,V,0000.0000,N,00000.0000,E,000.00,0,160115,FFFFFFFF,100,3,214,003,2120,450,0,2126,573,38,2120,7070,37#

Ok, now I understand what is happening. I need a device not sending any GPS position, only LBS. Anyway, I was going to return this device because is not accepting a server name, only an IP, so is not valid for me. Other option could be to add a new flag in traccar to consider lat & lon 0.00 as invalid, just in case my next LBS device is sending also GPS position, but we'll see.

Thanks for your help.

**Comment by tananaev** [comment]
I don't think you do. Even I don't. The message has "V", so it means that it's invalid, so geolocation should work.

**Comment by javier260** [comment]
You are right, 'V' is there, so LBS decoding should work. 
Any option to get more log information to see why is returning 0.00?

**Comment by javier260** [comment]
I've tested sending the following line from a telnet connection, with a fake not-valid (V) position (42N, 2E):
`*hq,353506112457668,V1,031000,V,4000.0000,N,00200.0000,E,000.00,0,281116,FFFFFFFF,100,3,214,003,2120,450,0,2126,573,38,2120,7070,37#`

And the following is what is showed in traccar web:
![image](https://cloud.githubusercontent.com/assets/17258791/25206116/530a25a4-2566-11e7-95b5-4ec2d7e2fd92.png)

See that position is marked as (Valid=No) and is showing 42N 2E, not LBS decoded info.

Regards

**Comment by tananaev** [comment]
Wait, I think Traccar just doesn't decode the cell information. That's why it doesn't work. To support it, I need protocol documentation.

**Comment by neuharthr** [comment]
Did this get resolved for the H02 protocol to support LBS only?

**Comment by tananaev** [comment]
You have to provide some message samples. Different devices use different format. Some formats are supported.

**Comment by neuharthr** [comment]
Here is a sample:
*HQ,865205066666666,V3,000859,46000,07,010152,003723,161,-59,010152,003783,150,,010152,003871,141,,010152,003722,139,,010152,003872,138,,010152,003721,133,,010152,004000,131,,028F,0,X,010615,FFFEFBFF#

**Comment by neuharthr** [comment]
As an update, after reading the V3 protocol for H02, this message does have the LBS detail data and Traccar does parse it correctly based on what I saw in the latest code base.

**Comment by tananaev** [comment]
It has been implemented recently, so you probably need to wait for next release for it.

**Comment by neuharthr** [comment]
All is working; this issue can be closed. Thanks!
