### ISSUE TITLE
Celular no conecta.

### ISSUE THREAD

**Issue by nemtec** [traccar/traccar#3079]
Hola,

He instalado todo en un debian 8, el server funciona aparentemente bien, he creado una cuenta en dtdns.com y en el router redireccione en el "port forwarding" TCP 5055-5055, ya lo habia hecho con UDP, he probado de diferentes formas y no puedo ver el seguimiento, no conecta el celular.

Todo esta instalado en un Debian Server virtualizado.

Espero me puedan orientar.

Saludos Cordiales.

**Comment by tananaev** [comment]
I would recommend asking in English.

**Comment by inghoward** [comment]
Quiza sea asunto de red. Prueba no utilizando el nombre que has dado a tu servidor (x.dtdns.com), sino usando wifi y ip del servidor dentro de la red local.

**Comment by nemtec** [comment]
Gracias por la respuesta, lo intentare y comentare el resultado.

**Comment by nemtec** [comment]
Me resulto.  Eso quiere decir que el celular debe estar fuera de la red para que funcione con un sistema de nombre de dominio y que traccar funcione a travez de Internet?

**Comment by inghoward** [comment]
No necesariamente. Quiere decir que algo en tu red no esta bien configurado, pero no puedo saber que sea. Puede ser el router, un debian con ip dinámica, etc... debes revisar, pero no tiene que ver con Traccar tu problema

**Comment by nemtec** [comment]
Gracias por la ayuda, voy a revisar bien, comentare el resultado.

**Comment by marioaugustorama** [comment]
Para que funcione correctamente su teléfono celular no puede estar en la
misma red. Wifi apagado. Otra cosa, se ejecutan en el servidor: iptables -L
-n Hasta luego.

Em sáb, 8 de abr de 2017 às 17:57, nemtec <notifications@github.com>
escreveu:

**Comment by nemtec** [comment]
Me funciona, pero esta muy lenta la frecuencia con la que se actualiza, se salta mucho de un punto a otro punto muy lejano y no registra el camino.  Sera la configuración de red?, tengo configurado un servicio DNS en dtdns.com, sera malo?, sera mejor no-ip?.

Saludos Cordiales.
