### ISSUE TITLE
ST-901 - formulae calculate the upload time interval 

### ISSUE THREAD

**Issue by cbodapati** [traccar/traccar#3084]
Hi,
Iam new here and hoping to get some help.
This is what is mentioned in the user manual "X is mean interval time, the unit is seconds，the wide is 【1，1800】"
If I want to set the time to 6 secs. Can someone please help me understand how to calculate this?
thanks,
Srikanth

**Comment by tananaev** [comment]
What exactly do you want to calculate what? It sounds like you just need to use 6 as the value.

**Comment by cbodapati** [comment]
thanks for the reply.
This is what is mentioned in the manual.
-----------------------------------
"Command：809+user password+Space+X
X is the location upload interval when car acc off, in the unit of seconds.
Eg： 8090000 60
Reply: SET OK
Device will upload location to platform every 20 seconds when car acc is off.
Note : X is mean interval time, the unit is seconds，the wide is 【1，1800】
We suggest X be no more than 480 seconds to avoid gprs traffice jam."
-------------------------------------

I want to know what the meaning of mean interval time and how to calculate if I want to set the upload interval time to 8 (for example). how to use the interval [1,1800].

thanks
Srikanth

**Comment by tananaev** [comment]
[1,1800] is the range for the value (from 1 to 1800). If you want 8 seconds, just put 8 seconds there. E.g. `8090000 8`.

**Comment by cbodapati** [comment]
thanks for your reply.
I tried that, but it did not work 
but if you look at the example, it says -
if I use "8090000 60" then the device will upload location every 20 sec. I want to know what is the formula.
There is also a note - -----------------------------
Note : X is mean interval time, the unit is seconds，the wide is 【1，1800】
We suggest X be no more than 480 seconds to avoid gprs traffice jam."
------------------------------------------------------
I dont know how to understand/interpret the note correctly.

**Comment by tananaev** [comment]
There is no formula. It's just a value in seconds. 20 seconds is probably just a typo. If the command doesn't work, you should contact vendor to clarify. Possibly format is incorrect.

**Comment by cbodapati** [comment]
ok, I will try that again and post the results...
thanks
