### ISSUE TITLE
Two traccar services with common same mysql database

### ISSUE THREAD

**Issue by dhavalchikani** [traccar/traccar#3085]
Hello,

I have little modified the traccar UI. I want to run two traccar services with same common mysql database.
I have successfully run the two services on two different port. But as I have common two traccar services pointing to same database, it start misbehaving.

When I add the new device from one traccar, it didn't show in other traccar2 tab. Suddenly some time one service ask for authentication popup some time again.

Need your help.
Thanks in advance.

**Comment by tananaev** [comment]
Traccar has internal cache, so your second instance of Traccar won't automatically pick up updates from the database.

**Comment by dhavalchikani** [comment]
Any way to solve the issue.
And when I refresh the any of session it logout automatically.
Appreciate any help or work around.

Thanks for response.

**Comment by tananaev** [comment]
You would have to remove caching somehow or implement distributed cache.

I'm not sure if I understand the problem with session.

**Comment by dhavalchikani** [comment]
Ok. can you suggest step to do this changes for cache?

And why the session logout each time once I refresh. Both service pointing to same database then why would it not reflecting in each other.

I have checked the entries in database and new device added changes are successfully reflected in DB from either of service.

**Comment by tananaev** [comment]
You can start by looking through the classes in the `database` package. That's where the cache is.

As for logout, it shouldn't happen. Maybe you should provide a bit more details on what exactly you do and what happens.

**Comment by dhavalchikani** [comment]
I have created two services 
1. traccar and 2. traccar2

Both the services running on two different port with two separate database.
Then I created new mysql database and configured both services to same  mySQL database and restart the services.

Then I try to add the one new device in traccar2 and then check in other first traccar service. But new device didn't come up. Then I tried to refresh the page and the page logout and come up the login page. Event after login the new added device not come up in first traccar.

Similarly without any update even I tried first traccar service page refresh after second traccar2 login , first instance get logout.

As new added device successfully updated in mySQL when I did from any of the traccar service. Then why after refresh also new added device not display in other service.

Need some detailed help.
Thanks. #

Images:
![sql_snap](https://cloud.githubusercontent.com/assets/20392211/25042052/a927127c-2132-11e7-9409-55b3e963f86f.png)
![traccar_first_snap](https://cloud.githubusercontent.com/assets/20392211/25042053/a92ac11a-2132-11e7-8f20-4fb987ad18c5.png)
![traccar2_snap](https://cloud.githubusercontent.com/assets/20392211/25042054/a92f0978-2132-11e7-9888-a35e90e8067d.png)

**Comment by tananaev** [comment]
You don't need to explain the problem with using same database for two servers. I already explained what the problem is and how you can approach it.

You were talking about some session logout problem. What is that about?

**Comment by dhavalchikani** [comment]
I have logged in two different traccar service from two different port.
Now i have logged in one traccar first and then I have logged in traccar2. After login traccar2 first traccar session get logout on refreshing the page.

**Comment by tananaev** [comment]
It definitely has nothing to do with the second server. Session is not stored in the database, so servers have no way of communicating with each other.

**Comment by dhavalchikani** [comment]
Ok. Then what other parameter can cause this issue. Can you please guide me?

Thanks.

**Comment by tananaev** [comment]
I don't have an answer. You should probably debug the code and find out.
