### ISSUE TITLE
Minifinderpico battery alert

### ISSUE THREAD

**Issue by joepr** [traccar/traccar#3087]
Hello everyone 

After reading many posts I notice the battery alerts for protocol Minifinderpico is available. I'm using the latest version 3.11. I will like to receive email notifications when my device have low battery or less than 10%. 

Could someone point me to the right direction or share a link with the instructions? 

Regards

**Comment by tananaev** [comment]
At the moment Traccar supports only low battery alert that comes directly from devices. If you want to modify code, you can generate `Position.ALARM_LOW_BATTERY` somewhere in the decoder.

**Comment by joepr** [comment]
Thanks Anton

**Comment by joepr** [comment]
Anton 

Looking a some older posts I did found you mention that low battery is already implemented for some devices . In this case the minifinder seems to have this. Does this means when the device detects low battery Traccar will send me a notification?  Here is the link you share some time ago.

https://github.com/tananaev/traccar/blob/3b7148075815aa7f6cd650013949934a50a573f7/src/org/traccar/protocol/MiniFinderProtocolDecoder.java

**Comment by tananaev** [comment]
Looks like it is supported, so it should work.

**Comment by joepr** [comment]
Thanks Anton

I will use my device all day until battery drains out.  I should receive a email notification without modifying any code?

**Comment by tananaev** [comment]
Yes, you should, if you configured notifications correctly.
