### ISSUE TITLE
Minifinder commands not received by device

### ISSUE THREAD

**Issue by joepr** [traccar/traccar#3088]
Hello everyone

I have a minifinder pico device model minifinder atto. It works fine on the latest 3.11 installation. My small issue is when I send the commands via Traccar it seems no to take any effect on the device. The web interface tells that command has been sent. However after waiting for a few minutes I check the device settings via SMS or USB and it still  have the old configuration.

![image](https://cloud.githubusercontent.com/assets/10345032/25072518/34ae72b0-229e-11e7-8110-43ec3f8378da.png)

Example
When I select SOS number I don't have a box to input the number
![image](https://cloud.githubusercontent.com/assets/10345032/25072535/c18c74d4-229e-11e7-9cd3-5dd919f0c181.png)

I have try many of the available options and they don't offer a way to input the values as well. I will like to know if I'm missing a step here?

**Comment by tananaev** [comment]
What if you select custom command? Does it show the input field?

**Comment by joepr** [comment]
Anton 

I have test all the options. The only ones that offer a input field are **custom command**, **set timezone** ,**Set Indicator**  Do you think is something not configured correctly on mi side?

![image](https://cloud.githubusercontent.com/assets/10345032/25076650/ba60618c-22f0-11e7-8323-ba65ac468e2e.png)
![image](https://cloud.githubusercontent.com/assets/10345032/25076656/c55eced4-22f0-11e7-9082-72a48e85dbce.png)
![image](https://cloud.githubusercontent.com/assets/10345032/25076668/d2b9ee4c-22f0-11e7-9f25-81598b4f0f2b.png)

**Comment by tananaev** [comment]
It's expected. Web app doesn't support some commands at the moment, so it doesn't show extra parameters for those ones.

**Comment by joepr** [comment]
**Thanks Anton,**

Then a simple question.. Could I use the custom command field to type the commands manually? Like changing the Data transmission interval...
 
Looking at the minifinder protocol on your site it shows the following info (picture attached)   
https://dl.dropboxusercontent.com/s/gakwytimitwz50r/MiniFinder_Pico_Protocol.pdf
![image](https://cloud.githubusercontent.com/assets/10345032/25076973/ac2c104a-22f3-11e7-9680-05a782cd9075.png)

Will it works by typing ?
123456M,006

**Comment by tananaev** [comment]
Yes, it should work.

**Comment by agam16** [comment]
How can we get the response of the custom command?

**Comment by tananaev** [comment]
@agam16, please don't spam everywhere with the same question. One place is more than enough.
