### ISSUE TITLE
Device status is not working properly

### ISSUE THREAD

**Issue by sajjadG** [traccar/traccar#3090]
Don't know about other protocols but for android phones which use osmAnd protocol, status is not working and it seems it's because of the osmand/traccar/HTTP protocol shortcoming (#2825, #2894, #2715). Is there any plan to fix this issue?
Can implementing MQTT (#1582) fix this problem?!

**Comment by tananaev** [comment]
It's expected behaviour for HTTP-based protocols and there is no plan to fix it at the moment.
