### ISSUE TITLE
IllegalArgumentException when updating device distance

### ISSUE THREAD

**Issue by agilehobo** [traccar/traccar#3091]
I have this error message when updating device distance: IllegalArgumentException (DeviceManager:459 < DeviceResource:109 < ...)
![devicedistance](https://cloud.githubusercontent.com/assets/6602604/25079090/85cc2d52-2363-11e7-9f30-1ec1119bf001.PNG)

**Comment by tananaev** [comment]
Can I see what you are typing in the edit field?

**Comment by agilehobo** [comment]
I just select a device from the drop down list and enter any number in Total Distance field.
![capture](https://cloud.githubusercontent.com/assets/6602604/25086841/1d317180-2395-11e7-8c98-35b99bc7c343.PNG)

One more problem. I can input 'e' to Total Distance field and click "check mark" button even the text field is error with validation highlight.

**Comment by romariogland** [comment]
Its happens when device is not connected to server

**Comment by tananaev** [comment]
I've just tested and everything works for me.

As for the second problem, I don't really understand what the problem is and why you are trying to enter invalid values in the field.

**Comment by Abyss777** [comment]
As for initial problem it happen because you are trying to set Total Distance for Device have not reported anything yet. Firstly you have to get at least one position from device.
