### ISSUE TITLE
Battery and external voltage shown wrong with Meitrack devices

### ISSUE THREAD

**Issue by lalamper** [traccar/traccar#3093]
Hi All,

I have some Meitrack TC68S devices, they are working fine except Battery and External Voltage values.

This device sends (internal) battery and external voltage data as HEX values, which needed to be converted to decimal and needs some operation with them.

Current build only converts hex to decimal, which is not enough.

Example:
For internal battery, device sends hex data: 0A4D, traccar shows 2637 in web UI .
However to get the right decimal value it should be calculated by this way: HEX value * 3,3 * 2 / 4096

For external power, device sends hex data: 03D5, traccar shows 981 in web UI.
To get proper decimal value: HEX * 3,3 * 16 / 4096 

Here is the official GPRS protocol description:

Analog input value
Separated by "|".
Hexadecimal
AD1|AD2|AD3|Battery analog|External power analog
Note: Analog input values in an SMS report are empty.

Voltage formula of analog AD (AD1, AD2, and AD3):
MVT340/MVT380: (AD x 6)/1024
T1/T3/MVT600/MVT800/MVT100: (AD x 3.3 x 2)/4096
T322X/T333/T355: AD/100

Voltage formula of battery analog (AD4):
MVT340/MVT380: (AD4 x 3 x 2)/1024
MT90/T1/T3/MVT100/MVT600/MVT800/TC68S: (AD4 x 3.3 x 2)/4096
T311/T322X/T333/T355: AD4/100

Voltage formula of external power supply (AD5):
MVT340/MVT380: (AD5 x 3 x 16)/1024
T1/T3/MVT100/MVT600/MVT800/TC68S: (AD5 x 3.3 x 16)/4096
T311/T322X/T333/T355: AD5/100

Could you please implement in the next release?
Thanks,
Lajos

**Comment by tananaev** [comment]
Send me an email to discuss it.
