### ISSUE TITLE
HikariPool-1 - Connection is not available - error 500

### ISSUE THREAD

**Issue by floor1** [traccar/traccar#3094]
Hi,

I keep getting this error with some days in between. have anyone tried the same or know know how to fix ? the server is new installed and only runs traccar. When I try to connect to mysql then no problems.

Thanks
```
2017-04-18 08:21:06  WARN: HikariPool-1 - Connection is not available, request timed out after 30000ms. - SQLTransientConnectionException (... < QueryBuilder:54 < *:135 < DataManager:293 < DefaultDataHandler:27 < ...)
```

**Comment by tananaev** [comment]
It means that there was some problem with database connection.

**Comment by floor1** [comment]
Thanks, yes.

My sysadm tells me that DB/mysql have been stable and havent been down. hes sure that it has to do with some java connection file ?

**Comment by tananaev** [comment]
I'm not sure what you mean by "java connection file". The problem is clearly with database connection.

**Comment by floor1** [comment]
This is hes words.

Mysql runs perfect. I can connect and see records when traccar is not working. Problem is in traccar.
Could be java mysql driver too. I do not know java and can not debug.

**Comment by tananaev** [comment]
You can try to set high value to the "database.maxPoolSize" parameter.

**Comment by floor1** [comment]
He tried to run query and told me this. Traccar is not written well for db access. it does not close connections.

sleeping queries not terminated for 1700 seconds

**Comment by tananaev** [comment]
Whoever told you that doesn't know what he's talking about. Traccar caches database connections for performance reasons.

**Comment by floor1** [comment]
Next time when the error 500 happens he will can run tcpdump to see what network packets are transferred between the processes and see if  the very well performing cached queries are reaching mysql gate.
