### ISSUE TITLE
problem with 5th geofence for device

### ISSUE THREAD

**Issue by petersusan** [traccar/traccar#3109]
Hello

i get this message when i set the 5th geofence (or more) for a device:
```
NullPointerException (GeofenceManager:208 < DeviceGeofenceResource:43 < ...)
```
as i can see the geofence is inserted for the device but when i restart traccar then i can not connect to it.
8082 is not reachable

version 3.8

how can i use more geofence for devices?
thanks
peter

**Comment by tananaev** [comment]
It probably means that you have some invalid data in the database.

**Comment by petersusan** [comment]
what/where should i looking for?
device_geofence table looks like this:
 deviceid 	geofenceid 	
4 	3
4 	5
4 	6
4 	7

if one more row exist, then ttraccar does not start anymore
5     8

**Comment by tananaev** [comment]
Are you using MySQL with MyISAM engine by any chance?

**Comment by petersusan** [comment]
i think not but i have never take care about engines
mariadb  information_schema:

 ENGINE 	SUPPORT 	COMMENT 	TRANSACTIONS 	XA 	SAVEPOINTS 	
InnoDB 	DEFAULT 	Percona-XtraDB, Supports transactions, row-level l... 	YES 	YES 	YES
CSV 	YES 	CSV storage engine 	NO 	NO 	NO
MRG_MYISAM 	YES 	Collection of identical MyISAM tables 	NO 	NO 	NO
BLACKHOLE 	YES 	/dev/null storage engine (anything you write to it... 	NO 	NO 	NO
MEMORY 	YES 	Hash based, stored in memory, useful for temporary... 	NO 	NO 	NO
PERFORMANCE_SCHEMA 	YES 	Performance Schema 	NO 	NO 	NO
ARCHIVE 	YES 	Archive storage engine 	NO 	NO 	NO
MyISAM 	YES 	MyISAM storage engine 	NO 	NO 	NO
FEDERATED 	YES 	FederatedX pluggable storage engine 	YES 	NO 	YES
Aria 	YES 	Crash-safe tables with MyISAM heritage 	NO 	NO 	NO

**Comment by tananaev** [comment]
Well, you need to check which engine you are using.

**Comment by petersusan** [comment]
it uses innoDB

**Comment by tananaev** [comment]
Do you have any foreign keys in Traccar database?

**Comment by petersusan** [comment]
there is no foreign key, only primary keys as i can see

**Comment by tananaev** [comment]
It means that you are either using MyISAM or you had MyISAM before. There should be foreign keys in the database.

**Comment by petersusan** [comment]
i have checked all tables, and all of them use InnoDB.
in the past i do not know. i have never changed default engines which is innodb, but how knows.

but after all, what can be the solution?

**Comment by tananaev** [comment]
You need to have foreign keys or you will always have problem after removing any objects. If you don't have foreign keys at the moment, there are two options:

1. Re-create database and let Traccar create everything
2. Manually create foreign keys by checking all changelog file
