### ISSUE TITLE
Install "tracing" in another direction in linux 

### ISSUE THREAD

**Issue by zadhkiel** [traccar/traccar#3110]
Sorry, I would like to know if you can set the direction of installation of the tractor
Automatically installs in "opt" in linux I would like saver if it can be changed and as it would have to start the service of tracing if the "path" was different.

**Comment by tananaev** [comment]
You can manually install it into any path you want.

**Comment by zadhkiel** [comment]
How could you do this manual configuration?
Or any reference where you can help me

**Comment by tananaev** [comment]
Check manual installation option here:

https://www.traccar.org/download/
