### ISSUE TITLE
SMS HTTP protocol support

### ISSUE THREAD

**Issue by himsashu** [traccar/traccar#3111]
Hi Tananaev
Love to know that traccar now support SMPP protocol for sending SMS notification in latest version. I have two question regarding SMS notification:

1. Can be be possible to support HTTP protocol for sending SMS. As it is more easy to implement and easy to customize. In my case, I have a SMS gateway which has very easy API. The sample of http gateway is as below:
**http://GATEWAY_IP_ADDRESS/unified.php?usr=USERNAME&pwd=PASSWORD&sndr=SENDERID**&ph=MOBILE_NUMBER&text=SMS_MESSAGE.

In above, the BOLD link is fixed which can be stored in each account and MOBILE_NUMBER and SMS_MESSAGE can be generated by Traccar. So we may add this link to each account which need SMS alert.

2. Do traccar save the SMS notifications or Email notification in database so that it can be tracker that how much email or sms is consumed by each account. A report can be generated.

Hopefully my above suggestions may be useful for other users as well.

**Comment by tananaev** [comment]
1. The URL seems to be specific for some provider that you want to use. It's not a universal solution. Also there is already a thread with exactly the same request.

2. Events are saved in the database, so you can calculate how many emails and SMS messages were sent knowing user settings.

**Comment by tananaev** [comment]
We already support HTTP SMS. In fact it's the only option we support now.
