### ISSUE TITLE
JM09 protocol doesnt works

### ISSUE THREAD

**Issue by vegellibert** [traccar/traccar#3112]
My JM09 gps watch appears in 0.0. what is the problem?

**Comment by tananaev** [comment]
Without any additional information from you I can only guess that your device hasn't reported any GPS data, so coordinates are zero.

**Comment by vegellibert** [comment]
for example i can see my gps by sms commands, but i cant see it on traccar.
![traccar](https://cloud.githubusercontent.com/assets/7323449/25306529/68bb0310-2754-11e7-9d97-5925586bd8d5.png)

**Comment by tananaev** [comment]
Again, it means that your device doesn't send any valid GPS information.
