### ISSUE TITLE
Geocoding suggestions

### ISSUE THREAD

**Issue by thericardovega** [traccar/traccar#3123]
Excuse my English, I’m using a translator
Congratulations on tracar is excellent.
Rerefent to geocoder, I’m using an api with payment enabled google but it comes quite expensive,

A humble opinion, followmee.com is handled this way and it would be fantastic in a future version to draw it incorporate.
[Pic1](https://www.dropbox.com/s/axc8bhaxxctsey5/geocoder1.JPG?dl=0)
[Pic2](https://www.dropbox.com/s/jnhtxemmu6v4epp/geocoder2.JPG?dl=0)

Enable a button so that it is not generated in automatic query.

My regards

**Comment by tananaev** [comment]
I was thinking about it as well, but there are some problems if you think about generating reports.

**Comment by tananaev** [comment]
This is already available.
