### ISSUE TITLE
altitude in feet

### ISSUE THREAD

**Issue by htwmehdi** [traccar/traccar#3124]
Hello,

Any way to display altitude in feet ? also show magnetic course in degrees ?

Thank you!

**Comment by tananaev** [comment]
At the moment only by changing the source code.

**Comment by htwmehdi** [comment]
thank you for speedy reply,

what file should i edit ? thank you!

**Comment by tananaev** [comment]
Probably `AttributeFormatter` class.

**Comment by tananaev** [comment]
We've added support for altitude units (https://github.com/traccar/traccar-web/commit/8bde80a8cd1fb9b92f4867edbeeae48158f9036b).
