### ISSUE TITLE
Alarm poweron and ignition disappears

### ISSUE THREAD

**Issue by thericardovega** [traccar/traccar#3129]
Excuse my English, I'm using a translator.
Excellent work you do.

I am using gpstk103 protocol gps103, when iginicion is on, it is displayed on screen
Alarm poweron and ignition true, but after about 30 seconds it disappears. How can I do it so it will not be erased?

![ignition on](https://cloud.githubusercontent.com/assets/28070939/25519579/0f124760-2bbe-11e7-9f74-3a2407ed44f7.JPG)
...30s after
![ignition on2](https://cloud.githubusercontent.com/assets/28070939/25519585/15f42d0a-2bbe-11e7-8d3a-34229d968f9b.JPG)

Thanks for your help.

**Comment by tananaev** [comment]
You can use `processing.copyAttributes` config parameter:

https://www.traccar.org/configuration-file/

**Comment by thericardovega** [comment]
add this line traccar.xml

<entry key='processing.copyAttributes.enable'>true</entry> 
<entry key='processing.copyAttributes'>power,ignition,battery</entry>


but Still disappears,
What else could it be?
thanks for your time

**Comment by tananaev** [comment]
Have you restarted the service? Ignition should be copied now.

**Comment by thericardovega** [comment]
Yes i restart traccar.xml   service traccar restart

im unsing tk103 protocol gps103 **port 5001**  <--- Is correct the port?

Thank u

**Comment by tananaev** [comment]
If you get any data, it means that port is correct.
