### ISSUE TITLE
Traccar server stops frequently

### ISSUE THREAD

**Issue by mihir0109** [traccar/traccar#3130]
Hello,

I am using traccar on aws-EC2-t2.micro.. its 1 GM of RAM and 8GB volume. 
Around 60 GPS devices connected to server with around 30 seconds interval.. but sometimes traccar service is stops and manually I have to start it to work it again..

Any reason for this? Or any way to auto restart the service if it stops?

**Comment by tananaev** [comment]
You might need more memory. Also check this page:

https://www.traccar.org/optimization/

**Comment by mihir0109** [comment]
Yes, I am using mysql Database. But the max pool size is 5. Should I increase to 50, would it make difference here?
Any way to restart automatically if service stops?

**Comment by tananaev** [comment]
I would recommend to increase it at least to 10-20. It definitely won't hurt.

You can probably set up some script system-level script to restart service if it's not running.

**Comment by hackerunet** [comment]
What OS are you using in that server? I used to have traccar installed in amazon micro instance and I start having issues, after a year I found that was the Linux version, I was using Centos which is a red hat based distribution, so when I changed to debian based, debian 8, all my troubles went away.
After lots of issues 2 years later I finally got out from amazon due to maintainance costs and move to linode, then I moved out again to contabo and Im very happy to be there.
Hope this information helps you out on choosing the best option.

**Comment by hackerunet** [comment]
Often the file descriptors in red hat based distributions are too low so you need to raise them up to be able to attach more devices which means you need to support higher number of opened sockets and file descriptors. please check ulimit -Hn and ulimit -Sn in linux based systems.

**Comment by tananaev** [comment]
@hackerunet, this information is already included in the link that I provided earlier.

**Comment by mihir0109** [comment]
Hello, Thanks for your reply. I have increased pool size to 20, but still issue appears. I am using t2.micro with 8 Gb volume, and installed on ubuntu server. No other service is running except tomcat which is used for web services (very little usage).

**Comment by tananaev** [comment]
1. Have you checked logs to see what happens?

2. What do you mean by very little usage? Tomcat is pretty heavy service by itself.

**Comment by mihir0109** [comment]
Hello, I can see below logs in wrapper.log file:

**Comment by tananaev** [comment]
Looks like there is some problem with database connection.

**Comment by mihir0109** [comment]
Yes, but its not always. This exception comes randomly.. i.e.once in a day or 2

**Comment by tananaev** [comment]
Not sure how it's relevant information. It doesn't change the fact that MySQL closed the connection for some reason.
