### ISSUE TITLE
Let other users see device position securely

### ISSUE THREAD

**Issue by degaray** [traccar/traccar#3132]
I am implementing Uber-like car tracking for users in a mobile app. The drivers post to http://mydomain:5055?some_params=some_values. I need the users to check where the car is without comprising security. Is there a way to do so?

**Comment by tananaev** [comment]
You probably need an API call that would return some number of available cars around user.

**Comment by kirantpatil** [comment]
With 5 to 10 KM radius by default.

@degaray, are you using web app or building a native client for mobile ?

If it is opensource please share the code link, would like to test it.

**Comment by degaray** [comment]
Hi it is not open source and I do not have this functionality in place yet. My question is, is there a way to get a single device from the server without the actual device ID?

If I trust the device Id to anyone except the actual device then I think it will be an issue of security since anyone with the device ID will be able to change the position of the device by calling the URL.

**Comment by degaray** [comment]
By the way it is a IONIC app

**Comment by tananaev** [comment]
You can always exclude any data that you don't want user to see.

**Comment by degaray** [comment]
You mean by changing the query?

**Comment by tananaev** [comment]
I mean by changing the source code.

**Comment by Abyss777** [comment]
@degaray 
Just like an idea...
As you mentioned, every one who knows device id can substitute device location. If you are interested in security, you probably use SSL proxy for 5055 port (apache or nginx).
I suppose drivers are some how authorized in your system then you can enable authorization on this proxy with drivers credentials. It is not a big deal.
You'll get the system when only authorized driver can post location to traccar.

**Comment by tananaev** [comment]
I believe this should already be possible. You can create a separate user with whatever you want to share. And unlink after it's not needed. If something is still missing, feel free to create a new ticket with more details.
