### ISSUE TITLE
SkyPatrol TT8750+ Port

### ISSUE THREAD

**Issue by alejopachons** [traccar/traccar#3133]
I’m trying to connect SkyPatrol **TT8750+** but I have this entry in the server log. 
```
2017-05-01 22:58:59 DEBUG: [CFAD4C10: 5021 < 152.202.55.87] HEX: 0004021000202020202020202020313020202020202038363332383630323033343537333320204750524d432c3033353531362e30302c392c303434342e35363939342c4e2c30373430332e39393730312c572c302e3030302c302e302c3032303531372c2c2c412a3443202020302020202020202020202020302020343135342030303446
```
The HEX code to ascii is :
```
...10      863286020345733  GPRMC,035516.00,9,0444.56994,N,07403.99701,W,0.000,0.0,020517,,,A*4C   0           0  4154 004F
```
TT8750+ don't works for me.

Thanks for your support.

**Comment by tananaev** [comment]
You can try Enfora port.

**Comment by skyhunter15** [comment]
Hi!, Is there a file that receives GPS information? How can I change the attributes sent by a GPS? How can I add or modify a port?

**Comment by tananaev** [comment]
You have to ask manufacturer for information on how to configure device.

**Comment by skyhunter15** [comment]
Yes, but how can I receive the information in the application? How do I receive it so I can manipulate it?

**Comment by tananaev** [comment]
You can modify the code, you can use API, you can get it from the database. Your question is not very clear. What exactly are you looking for?

**Comment by skyhunter15** [comment]
I want to manipulate the information received by the GPS on the tracking platform, the GPS is displayed on the map but I do not know how the information arrives. Not by method or file arrive the data sent by the GPS, I would appreciate that you can help me, thanks for your time.

**Comment by tananaev** [comment]
Can you please stop spamming everywhere. I have answered here:

https://github.com/tananaev/traccar/issues/3131#issuecomment-303549642

**Comment by guifer01** [comment]
Good Morning, I was testing this skypatrol TT8750+ GPS and i have the same problem, could you share how you solve the problem, thanks,

I receave the same problem

2017-08-16 07:47:57 DEBUG: [2D6E54B0: 5021 < 190.113.210.54] HEX: 0005020000000000012020202020202020202020545438373530506c757320

thanks
