### ISSUE TITLE
Non-Administrative Users cannot send commands.

### ISSUE THREAD

**Issue by arrafa20** [traccar/traccar#3144]
I have successfully migrated from 3.7 version. But now i noticed non-administrative users cannot send commands. How can i set up the environment in order to non-adminstrative users will be available to send commands, without the option to see other users account or devices?

**Comment by tananaev** [comment]
Readonly users are not allowed to send commands. Regular or "device-readonly" users are still able to send commands.

**Comment by arrafa20** [comment]
device-readonly" users needs be administrators also?

device-readonly" users without the admin profile dont have the commands

**Comment by tananaev** [comment]
They should be able to send commands without being admins, unless you are using old version or you still have readonly flag for the user or server.

**Comment by arrafa20** [comment]
Thanks for the time anton, i was able to install 3.10, and i have a profile with:
readonly (uncheck)
administrator (uncheck)
Device readonly (check)

And i am not able to send commands. Was this fixed on 3.11?

In 3.10 just the profiles with the admin check are able to send commands

**Comment by tananaev** [comment]
What about server settings?

**Comment by arrafa20** [comment]
it was with the readonly checked. it is working now, without any of the 3 checks on the profile.

Thanks anton
