### ISSUE TITLE
tk103 not working with python

### ISSUE THREAD

**Issue by alejan2x** [traccar/traccar#3145]
I have my gps TK103 , I configured for sms to can work via GPRS. actually work perfectly with different pages of services of tracker as it is: Orage, gpswebtracker or gpstrackerxy. Also I have my own server , this server have Static IP Public with port open also I have installed in this sever the software call "GPS Tracker" and work perfectly

The problem is that I am developing my  script in python to have communication from mi server to gps. I followed the next steps:
 

1) change IP and port of my gps to can connect to my server
2) open the connection btw gps and server
3) the gps send me : `##,imei:123456789012345,A;`
4) anwer from my sever: `LOAD` (format text)

here begin the problem
5) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`

6) anwer from my sever: `**,imei:123456789012345,B;` (format Text)
7) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`

I repeat the step but with hex 

5) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`
 
6) anwer from my sever: `2a2a2c696d65693a3132333435363738393031323334352c42` (format HEX)
7) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`

also with:

5) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`
 
6) anwer from my sever: `**,imei:123456789012345,42;` (format Text and HEX)
7) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`

and the manual traccar say: use 12-digit device identifier instead of IMEI. Usually it consists of 11 last digits from IMEI plus leading zero. For example, if IMEI number is 123456789012345, the unique id would be 056789012345

5) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`
 
6) anwer from my sever: `**,imei:056789012345,B;` (format Text)
7) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`

I repeat the step but with hex 

5) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`
 
6) anwer from my sever: `422a2a2c696d65693a3035363738393031323334352c423b` (format HEX)
7) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`

also: 

5) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`
 
6) anwer from my sever: `**,imei:056789012345,42;` (format Text and HEX)
7) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`

Well, some time the gps send me:

5) the gps send me : `123456789012345;`
6) anwer from my sever: `ON` (format text)
7) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`

 
6) anwer from my sever: `4f4e` (format Hex)
7) the gps send me: `imei:123456789012345,tracker,,,L,,,97f,,77c7,,,;`

Then I ran the software GPS Tracker (previously installed in my server) and run perfectly .  Whyyyyyy??

So really I dont have idea that why not work my scripting or why not can capture the data the coordinates of my gps. really a Im desperate. Can you bring me you help.

Regards!

here my script in python 

```python
#!/usr/bin/python

_author__ = 'Alejandro hernandez'

import socket
import sys
import time
import re
import os

os.system('cls')

# Create a TCP/IP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Connect the socket to the port where the server is listening
localhost = "192.168.0.15"
port = int("6000")
server_address = (localhost,port)

def echo_server():

    imei = []

    print >>sys.stderr, 'starting up on %s port %s' % server_address

    sock.bind(server_address)
    sock.listen(1)
    print >>sys.stderr, 'waiting for a connection'
    connection, client_address = sock.accept()

    print >>sys.stderr, 'client connected:', client_address
    data = connection.recv(1024)


    if data.find('##') > -1:

        imei.append(data)
        print >>sys.stderr, 'received %s' % data

        for line in imei:
            imeidevice = re.sub("\D",'', line)
            id = '0%s' %imeidevice[4:15]

        print >>sys.stderr, 'sending  msg to client: LOAD'
        message = 'LOAD'
        connection.sendall(message)


        while True:

            ansdev = connection.recv(1024)
            print >>sys.stderr, 'received %s' % ansdev

            if len(ansdev) == 16:

                #message = '**,imei:%s,B;' %id
                message = 'ON'

                print >>sys.stderr, 'sending  msg to client: %s' %message
                connection.sendall(message)

                ansdev = connection.recv(1024)
                print >>sys.stderr, 'received %s' % ansdev

    connection.close()

def main():

    echo_server()


if __name__ == '__main__':
    main()
```

attach images of data trafic

![001gpstracker](https://cloud.githubusercontent.com/assets/28353371/25677215/bb95a554-300a-11e7-8ff0-8dee94927a31.png)
![001gpstrackercoordinates](https://cloud.githubusercontent.com/assets/28353371/25677219/bbaa9676-300a-11e7-966c-11b47f5978fb.png)
![001wireshark](https://cloud.githubusercontent.com/assets/28353371/25677216/bb96dc58-300a-11e7-9740-9dfdf687b5ce.png)
![traficcdatagpstracker](https://cloud.githubusercontent.com/assets/28353371/25677217/bb9ff856-300a-11e7-9515-af42c1ef73c4.png)
![traficdatapython](https://cloud.githubusercontent.com/assets/28353371/25677218/bba04658-300a-11e7-9dbe-1bf91740a85e.png)

**Comment by tananaev** [comment]
The problem is that your device doesn't seem to have a GPS fix. Are you testing it indoors?

**Comment by alejan2x** [comment]
No, the gps is in the street and no exist building  Or something that interferes with the signal. But i dont  understand, I have the same environment in the gps but with the web services (gpstracker u orange) work good perfectly, is more in my own server with the aplication 'gps tracker' have good results, but i try with python and can not. I haver the same trafic in the TCP ports such input and output, attached the images y the description cases.

**Comment by tananaev** [comment]
All I can tell from your long post is that your device doesn't send any GPS data. The problem must be either lack of GPS signal, or some device configuration issue.

**Comment by alejan2x** [comment]
I checked the connection that technical did in the GPS in the motorcycle andd puff , him installed bad, the Athena GPS was in the gsm and viceversa. I changed the wire and just now received  the coordinates perfectly, sorry for the inconvenience.

imei:0123456789012345,tracker,170504035029,,F,225027.000,A,2039.2726,N,10324.1718,W,13.45,73.95;
imei:0123456789012345,tracker,170504035032,,F,225030.000,A,2039.2807,N,10324.1637,W,13.93,30.57;
imei:0123456789012345,tracker,170504035032,,F,225030.000,A,2039.2807,N,10324.1637,W,13.93,30.57;
imei:0123456789012345,tracker,,,L,,,97f,,77c7,,,;

**Comment by neliobnjr** [comment]
Hey Alejan, I'm trying to use your script but it is now working on python3.7. 
which version were you working?
