### ISSUE TITLE
 WARN: [********] error - Connection reset by peer - IOException (...)

### ISSUE THREAD

**Issue by triton086** [traccar/traccar#3146]
Hi,

After I've upgraded to the latest version, I constantly get my tracking device disconnected from server 

```
2017-05-03 23:13:13  WARN: [********] error - Connection reset by peer - IOException (...)
2017-05-03 23:13:13  INFO: [********] disconnected
```

Any idea of what is going on there ?

Device : gt02_mt62600_v1.1 2015.12.26
Traccar server version : 3.11

Thanks

PS : Java version upgrade / restarting traccar server or the device didn't solve the issue.

**Comment by tananaev** [comment]
It means device has disconnected from the server.

**Comment by triton086** [comment]
Hi @tananaev 

Obvious :) . But could this "connection reset" be generated by the app ?

I've  checked the network ... and doesn't seems to be a network issue. There is no Loss between the server and the device and the ping response is constant.

The only thing that I didn't verified is the device itself. But this will be strange, because I didn't touch the device for few weeks and the place where is mounted is hidden and secured.

Anyway .. I will check the device and I will come back with an update.

**Comment by tananaev** [comment]
It cannot be generated by server, if that's what you are asking. As I said, it means that device has disconnected from the server, not the other way around.
