### ISSUE TITLE
GT005 device integration

### ISSUE THREAD

**Issue by SiddiqueAhmad** [traccar/traccar#3148]
Does traccar support GT005 i am integrating it but no luck so far, and i traced that 28 is not defined in protocol identifier
```
787822280f060100001c019a01025f27b731025f53e02c025f506d28025f79a81f000000000000000000000002a4920d0a
```

**Comment by tananaev** [comment]
Looks like message type 0x28 is not supported at the moment. Do you have protocol documentation that describes it?

**Comment by SiddiqueAhmad** [comment]
No
I have burn full night but couldn't find the document

**Comment by protomaxita** [comment]
Hello to everyone,
I have a GT007 , and I have send mail at www.hlxtsz.com maker of this family tracker, ,I waiting for reply.
Bye4now

**Comment by protomaxita** [comment]
I have received PDF with protocol of hlxtsz.com tracker, but I can't share. 
I send another mail for know why i'snt possible to share , I waiting for reply.
Please tananaev and SiddiqueAhmad if we can contact http://www.hlxtsz.com/ for obtain protocol and enable use of this tracker on traccar.

**Comment by SiddiqueAhmad** [comment]
I have contacted them but the document they shared is of no use

**Comment by protomaxita** [comment]
Any news ? 
tananaev is difficult add new protocoll with new port al Traccar server ?
Exist any documentation on add new protocoll ?

**Comment by tananaev** [comment]
It's not possible to add anything without documentation.

**Comment by protomaxita** [comment]
Documentation exist but Victoria from hlx tracker won't share on open source project.

I have received complete pdf with protocoll of this famiily tracker but I don't how This can't share.

If not share documentation this insn't a good product!!!

I'll still waiting for reply of victoria but nothing at this time.

Thanks and best regards

________________________________
Da: Anton Tananaev <notifications@github.com>
Inviato: martedì 16 maggio 2017 22.36.15
A: tananaev/traccar
Cc: protomaxita; Comment
Oggetto: Re: [tananaev/traccar] GT005 device integration (#3148)


It's not possible to add anything without documentation.

**Comment by SiddiqueAhmad** [comment]
That's incomplete

**Comment by protomaxita** [comment]
I have used with success GT06 protocoll with complete IMEI on traccar user on port 5023.
My GT007 tracker report powercut error but other function work great, battery level, RSSI, position, Time , Date, n. of sat.
Next I check why tracker report powercut error.
