### ISSUE TITLE
Problems with BD mysql connection

### ISSUE THREAD

**Issue by zadhkiel** [traccar/traccar#3150]
My connection to the database that comes with default "traccar" works, but when setting up my BD mysql does not work.
And I created my database that is called "traccar"
```xml
<entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
<entry key='database.url'>jdbc:mysql://localhost:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
<entry key='database.user'>root</entry> 
<entry key='database.password'>12345</entry>
```

**Comment by tananaev** [comment]
BD?

What is the error message in the logs?

**Comment by zadhkiel** [comment]
Sorry for the delay here more detail of the fault.

wrapper.log.20170508

INEST|2846/0|Service traccar|17-05-08 19:01:59|        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
FINEST|2846/0|Service traccar|17-05-08 19:01:59|        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
FINEST|2846/0|Service traccar|17-05-08 19:01:59|        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
FINEST|2846/0|Service traccar|17-05-08 19:01:59|        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
FINEST|2846/0|Service traccar|17-05-08 19:01:59|        at java.net.Socket.connect(Socket.java:576)
FINEST|2846/0|Service traccar|17-05-08 19:01:59|        at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
FINEST|2846/0|Service traccar|17-05-08 19:01:59|        at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
FINEST|2846/0|Service traccar|17-05-08 19:01:59|        ... 30 more
INFO|wrapper|Service traccar|17-05-08 19:01:59|waitpid 2846 59136
INFO|wrapper|Service traccar|17-05-08 19:02:00|exit code posix process: 59136 application: 0
------------------------------------------
tracker-server.log 

2017-05-08 18:52:31  INFO: Operating system name: Linux version: 3.2.0-4-686-pae architecture: i386
2017-05-08 18:52:31  INFO: Java runtime name: OpenJDK Client VM vendor: Oracle Corporation version: 24.121-b00
2017-05-08 18:52:31  INFO: Memory limit heap: 494mb non-heap: 118mb
2017-05-08 18:52:31  INFO: Character encoding: UTF-8 charset: UTF-8
2017-05-08 18:52:31  INFO: Version: 3.11-SNAPSHOT
2017-05-08 19:01:53  INFO: Operating system name: Linux version: 3.2.0-4-686-pae architecture: i386
2017-05-08 19:01:53  INFO: Java runtime name: OpenJDK Client VM vendor: Oracle Corporation version: 24.121-b00
2017-05-08 19:01:53  INFO: Memory limit heap: 494mb non-heap: 118mb
2017-05-08 19:01:53  INFO: Character encoding: UTF-8 charset: UTF-8
2017-05-08 19:01:53  INFO: Version: 3.11-SNAPSHOT
-------------------------------------------------------------------------------------------
log of apache2 error.log

[Mon May 08 22:10:00.535345 2017] [proxy_http:error] [pid 2929] [client 181.188.177.253:32137] AH01114: HTTP: f             ailed to make connection to backend: 192.168.2.150
[Mon May 08 22:10:00.912692 2017] [proxy:error] [pid 3312] (111)Connection refused: AH00957: HTTP: attempt to c             onnect to 192.168.2.150:8082 (192.168.2.150) failed
[Mon May 08 22:10:00.912735 2017] [proxy:error] [pid 3312] AH00959: ap_proxy_connect_backend disabling worker f             or (192.168.2.150) for 60s
[Mon May 08 22:10:00.912746 2017] [proxy_http:error] [pid 3312] [client 181.188.177.253:24151] AH01114: HTTP: f             ailed to make connection to backend: 192.168.2.150, referer: https://https://www.dominio.com/
[Mon May 08 22:16:48.058221 2017] [proxy:error] [pid 3314] (111)Connection refused: AH00957: HTTP: attempt to c             onnect to 192.168.2.150:8082 (192.168.2.150) failed
[Mon May 08 22:16:48.058289 2017] [proxy:error] [pid 3314] AH00959: ap_proxy_connect_backend disabling worker f             or (192.168.2.150) for 60s
[Mon May 08 22:16:48.058308 2017] [proxy_http:error] [pid 3314] [client 181.188.177.253:32044] AH01114: HTTP: f             ailed to make connection to backend: 192.168.2.150
[Mon May 08 22:16:48.309936 2017] [proxy:error] [pid 2928] (111)Connection refused: AH00957: HTTP: attempt to c             onnect to 192.168.2.150:8082 (192.168.2.150) failed
[Mon May 08 22:16:48.309987 2017] [proxy:error] [pid 2928] AH00959: ap_proxy_connect_backend disabling worker f             or (192.168.2.150) for 60s
[Mon May 08 22:16:48.310004 2017] [proxy_http:error] [pid 2928] [client 181.188.177.253:41347] AH01114: HTTP: f             ailed to make connection to backend: 192.168.2.150, referer: https://www.dominio.com

I look forward to any help.

Clarifying that if I work with the database that brings "Traccar".

**Comment by tananaev** [comment]
Not sure how Apache log is relevant here and your wrapper log is cut off, so it doesn't include the actual error message.

**Comment by Rofoezie** [comment]
zadhkiel, Were you able to resolve this issue? Kindly share your solution. I am also stock with a similar issue.
