### ISSUE TITLE
traccar not sending accurate live data  

### ISSUE THREAD

**Issue by sureshsiddhu** [traccar/traccar#3153]
i downloaded traccar code from github  when i run project every thing working fine but when i test traccar  with traccar client it does not send accurate live  data with frequency of 50 in traccar client app.
will same problem arises in  gps devices ??
can you please help me

**Comment by tananaev** [comment]
This has nothing to do with the server. You posted it in the wrong place.

**Comment by sureshsiddhu** [comment]
where i have to post this query

**Comment by tananaev** [comment]
Traccar Client for Android:

https://github.com/tananaev/traccar-client-android

Traccar Client for iOS:

https://github.com/tananaev/traccar-client-ios

**Comment by sureshsiddhu** [comment]
i am telling that traccar server does not receive accurate data

**Comment by tananaev** [comment]
OK, then please provide some evidence that it's a server problem and not the client.

**Comment by sureshsiddhu** [comment]
client sending location update but server receives  wrong latitude and longitudes
i dont understand problem from which side.my device acutally in visakhapatnam on map it  showing route map from hyderabad to visakhapatnam
![sss](https://cloud.githubusercontent.com/assets/24537849/25845189/ab62b41e-34ca-11e7-80f5-8add14d8a705.PNG)

**Comment by tananaev** [comment]
I am sure that the problem is not with the server, but with the client. In fact the location comes directly from the device, so it's either your phone issue or you just don't understand how it work.

**Comment by sureshsiddhu** [comment]
thank you for your  reply
and also which gps device is good 
and is it possible device last update for every 3 or 5 seconds

**Comment by tananaev** [comment]
Some devices restrict minimum update interval, but most of the hardware GPS trackers should be able to report at least every 5 seconds. I would recommend to contact device vendor for details about a specific device. I can't really recommend any specific models.

**Comment by sureshsiddhu** [comment]
can i know future updates of traccar

**Comment by sureshsiddhu** [comment]
when i run application spinner loading too much of time whats should i change in coding part

**Comment by tananaev** [comment]
I don't understand the question about future updates. There is no clearly defined roadmap, if that's what you are asking.

As for spinner, you can minify the web app to reduce the loading time.

**Comment by sureshsiddhu** [comment]
can you please suggest which android apps will play major role in future

**Comment by tananaev** [comment]
What are you talking about?

**Comment by sureshsiddhu** [comment]
for developing mobile application which type of applications are good as per your openion

**Comment by tananaev** [comment]
How is this question related to Traccar?

**Comment by sureshsiddhu** [comment]
sorry for asking this question

**Comment by sureshsiddhu** [comment]
can we get google address using latitude and longitude in reports column

**Comment by tananaev** [comment]
Yes, you can. Please do some research before asking any questions.

**Comment by sureshsiddhu** [comment]
thank you
