### ISSUE TITLE
Custom Attributes

### ISSUE THREAD

**Issue by Sargunan** [traccar/traccar#3155]
Hi,

 How to add custom attributes to device or user in latest version of Traccar,  ( This was possible in previous version, now attributes limited fixed set of entries in the combo box),

Thanks

**Comment by tananaev** [comment]
You can still add custom attributes the same way as before.

**Comment by gangadhark864** [comment]
Hi,
I am trying Add own attribute to my device, It is showing following error. please find the attached image.
Please help me to add custom attribute to particular Device.
![traccar](https://user-images.githubusercontent.com/24523272/39823746-bfbbfe7a-53be-11e8-8afb-762d608dcdc0.JPG)

Regards,
Gangadhar K.

![traccar](https://user-images.githubusercontent.com/24523272/39823575-64c4c088-53be-11e8-9590-f2cd0cb76f50.JPG)

**Comment by tananaev** [comment]
@gaborgsomogyi, use forum for questions. And please don't comment on random threads. Create a new one.

**Comment by gaborgsomogyi** [comment]
seems like the tagging has targeted me wrongly.

**Comment by tananaev** [comment]
@gaborgsomogyi, I'm really sorry. GitHub autocomplete. Previous comment was for @gangadhark864.
