### ISSUE TITLE
How to calculate Up time or travel time?

### ISSUE THREAD

**Issue by mihir0109** [traccar/traccar#3159]
How to calculate travel time during a day? suppose my car travels around 1 hour in a day.. 20 minutes in morning, 30 minutes in evening etc.. is there any way to find actual travel time?

**Comment by tananaev** [comment]
Summary report has engine hours calculated based on the ignition status.

**Comment by mihir0109** [comment]
I have checked that, But engine hours shows always 0 for each device.. I can see average and maximum speed, but engine hours always 0

**Comment by tananaev** [comment]
Does your device report ignition status?
