### ISSUE TITLE
traccar  Not Opening xt2400 port

### ISSUE THREAD

**Issue by jriverarojas** [traccar/traccar#3163]
I'm using traccar version 3.11 and traccar is not opening port 5138 for xt2400. I have tried to change the port for xt2400 to other port that was already working, but it didn't work neither. I'm sure the problem isn't the firewall.

**Comment by tananaev** [comment]
How did you check if the port is open or not? XT2400 protocol is UDP-based, so you can't use port check tool on the website.

**Comment by jriverarojas** [comment]
Yes, you are right the udp port es open. Where can i see which protocols are udp?

**Comment by tananaev** [comment]
You can search for UDP protocols like this:

https://github.com/tananaev/traccar/search?q=ConnectionlessBootstrap

**Comment by jriverarojas** [comment]
ok, thanks you
