### ISSUE TITLE
h2 protocol ignition always give false value

### ISSUE THREAD

**Issue by sonuauti** [traccar/traccar#3166]
hex received:
```
2481608955761727151605171852308806074248514e003168ffffbbff000000000000000001941627121c2c30
```
 
attributes
```json
{"power":6,"ignition":false,"status":4294949887,"ip":"xx.xx.xx.xx"}
```

**Comment by tananaev** [comment]
What version of Traccar are you using? And what makes you think it's a server issue?

**Comment by SBYDeveloper** [comment]
We are getting the same status but i think its a problem of the Tracker and Protocol not a server one. Further more with this protocol we are not able to get fuel consumption values but again i think its a problem of the tracker using the protocol not a server one
