### ISSUE TITLE
Server 3.11, Traccar Manager & Select group...

### ISSUE THREAD

**Issue by Neoespecialistas** [traccar/traccar#3169]
Hi Anton,
After install server 3.11 i'm trying to get a group of devices on my Lenovo K5 phone using Traccar Manager.
I think this is virtually impossible, because some submenus or listbox goes outside screen.

This screenshot show the issue:
![screenshot_2017-05-16-20-51-03](https://cloud.githubusercontent.com/assets/15131496/26133043/c8442b48-3a7a-11e7-9820-b4eb16416be9.png)

Perhaps a pushbutton, or a listbox could be usefull to get a group fastly.
Could you consider this tip on a new release ?
Thanks in advance,
David de Argentina

**Comment by tananaev** [comment]
Looks fine to me:
![screenshot_20170517-234715](https://cloud.githubusercontent.com/assets/1161863/26152528/63db382c-3b5b-11e7-906d-6ff69a344120.png)
