### ISSUE TITLE
Traccar api response "404 Not Found"

### ISSUE THREAD

**Issue by biskandar** [traccar/traccar#3170]
I'm using traccar version 3.9 , and  I tried to access the REST-Api with simple http authentication via browser, but it always display as "404 Not Found".
```
HTTP Get http://ax4.djak.co:8082/api/server
Request headers:
  Authorization: Basic XXXXXXXX

Response headers:
    Status Code: 404 Not Found
    Access-Control-Allow-Headers: origin, content-type, accept, authorization
    Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
    Access-Control-Allow-Origin: *
    Content-Length: 44
    Date: Wed, 17 May 2017 01:22:13 GMT
    Server: Jetty(9.2.19.v20160908)
    access-control-allow-credentials: true
Response body:
  HTTP 404 Not Found - NotFoundException (...)
```
Any clue? thanks

And i don't see any related information issue inside file the logs/traccar.log .

**Comment by tananaev** [comment]
Most likely you have some issue with the database. That's assuming that you haven't done any modifications to the server code.

By the way for server GET request you don't need authentication at all.

**Comment by biskandar** [comment]
I managed to resolve this issue .

I use Reflections instead to grep all the API class resources , because i put tracker-server.jar as part of the library .
