### ISSUE TITLE
device offline

### ISSUE THREAD

**Issue by 89kaka** [traccar/traccar#3175]
hi
i get this status "device offline"
i have opened port 8082, i used the port checker and it shows port open but it still shows device offline

**Comment by tananaev** [comment]
What device are you using? Port 8082 is NOT for devices.

**Comment by 89kaka** [comment]
Am using a pc as the server so the traccar service is listening on that port(8082) and i have a static ip

**Comment by 89kaka** [comment]
the client's device is an android phone

**Comment by tananaev** [comment]
Port for Traccar Client is 5055 and not 8082!

**Comment by 89kaka** [comment]
what about the 8082 used in the installation video

**Comment by tananaev** [comment]
I don't see anywhere in the video settings up port 8082 in the Traccar Client app. Port 8082 is for the web interface only. It's not for devices.

**Comment by 89kaka** [comment]
ohhhhhh oookay , so which port am i supposed to use when setting the client's app

**Comment by tananaev** [comment]
Can you please read my comments more carefully.

**Comment by 89kaka** [comment]
sorry to disturb you but what should i put under the server port in the traccar client

**Comment by 89kaka** [comment]
i figure it out it works now, thanks for the help one other thing though
how do you configure the "hidden release" of the client's app

**Comment by tananaev** [comment]
Same way you configure regular version.

**Comment by 89kaka** [comment]
k thank you

**Comment by raliam** [comment]
Hey... After I installed the software, which port i have to use? how 5055 is used?
Regards!

**Comment by tananaev** [comment]
Port 5055 is used for Traccar Client app.
