### ISSUE TITLE
Trip distance issue with teltonika device

### ISSUE THREAD

**Issue by chrissfoot** [traccar/traccar#3176]
I have some short trips with a teltonika device which are reporting as 0 for distance. Where can I start troubleshooting this? 

I have attached a route and trip report for the affected device.

[trip report.xlsx](https://github.com/tananaev/traccar/files/1013926/trip.report.xlsx)
[route report.xlsx](https://github.com/tananaev/traccar/files/1013927/route.report.xlsx)

**Comment by chrissfoot** [comment]
Could this be caused by the start and end of the journey being in the same place?

**Comment by tananaev** [comment]
It could be if your device reports odometer value. Check state view and see if there is odometer there and if yes, check if it changes.

**Comment by chrissfoot** [comment]
There is a distance and total distance attribute under state but no odometer. I've tried setting the ignoreOdometer setting but it doesn't seem to change things. It seems to use an as the crow flies calculation. The journey in the attached files for example shows 1.4km in traccar but google says it is 3.3km
https://www.google.co.uk/maps/dir/9+Michaels+Mews,+Aylesbury+HP19+7GG/4+Broadfields,+Aylesbury/@51.8199391,-0.8547976,14z/data=!4m15!4m14!1m5!1m1!1s0x4876f722feb85b77:0xd3ecb1efc4dd67bb!2m2!1d-0.8401462!2d51.8154561!1m5!1m1!1s0x4876f7158aaad003:0x624bdac07d11510b!2m2!1d-0.8373776!2d51.8242124!3e0!5i1

[trip report 2.xlsx](https://github.com/tananaev/traccar/files/1019521/trip.report.2.xlsx)
[route report 2.xlsx](https://github.com/tananaev/traccar/files/1019525/route.report.2.xlsx)

**Comment by tananaev** [comment]
OK, so it doesn't always return zero. Traccar calculates distance between points, so it will never be as accurate as Google Maps. You should probably just visually compare the tracks to understand why there is such a big difference.

**Comment by chrissfoot** [comment]
Ok, so is it it a direct start point to finish point calculation? Is there any way to get it to account for the actual journey without changing my tracking device? There are times when i'll have to go somewhere and come straight back without really stopping (like in my first route), would I be right in thinking that these could be counted as 0 miles? The route on traccar and google maps are identical in my second attachment.

**Comment by tananaev** [comment]
No, distance is calculated between each point. If the route in Traccar matches the route on Google Maps then the distance should match as well.

**Comment by chrissfoot** [comment]
Hi Tananaev,

Can you look at the attached files please. It's showing a trip with a negative distance. I have 
`<entry key='report.ignoreOdometer'>true</entry>`
set in the traccar.xml

Thanks

Chris
[negativeroute.xlsx](https://github.com/tananaev/traccar/files/1061210/negativeroute.xlsx)
[negativetrip.xlsx](https://github.com/tananaev/traccar/files/1061211/negativetrip.xlsx)

**Comment by tananaev** [comment]
The only other explanation could be that data comes in the wrong order. For example this can happen if device buffers data when there is no connection.
