### ISSUE TITLE
Update traccar manager inconsistent

### ISSUE THREAD

**Issue by aecsalome** [traccar/traccar#3177]
Hi Anton,

According my topic on https://www.traccar.org/forums/topic/access-traccar-manager-inconsistent/, follow the step by step where screen Traccar Manager still not update:

1) Open Traccar manager and click on device
2) Open Chrome , type server address and click on device
3) stay until the standby on the cellphone Android (black screen)
4) wait a time (1, 2, 3 ... 5 minutes,... don't matter)
5) unblock the cellphone and look the Traccar manager ( I have a old information)
6) look the google chrome ( I have a updated information)

follow the test doing considering time equal 1 minute:
https://drive.google.com/file/d/0B1mhLFkpr3AwWlFneWtHOEh4VVE/view?usp=sharing

Is there a way (syntax - variable to be set on traccar.xml, etc. - or change Traccar manager code) to force Traccar  manager  update  each 1 minute?

Best regards

Alex

**Comment by tananaev** [comment]
Most likely the issue is that session has expired, so you have to re-login. Traccar Manager doesn't allow you to refresh a page at the moment. Next version of Traccar will automatically redirect you to login screen, so you won't need to refresh anything manually and this issue will go away.

**Comment by aecsalome** [comment]
Hi Anton,
is it possible set/growing up the expired session time ? or instead automatically redirect you to login screen, automatically reflesh the page before expired session time?
I use the beep web notification to advise the people about geofence events. 
it does works as if it were  push notifications (workaround).

Best regards

**Comment by tananaev** [comment]
Have you actually read my comment?

**Comment by aecsalome** [comment]
Oh,so  sorry, it is "instead of", translate wrong
my apologices

yes, if growing up, the problem continues, but like I sad, it is a
workaround, because you tell / write that push notification is not to easy
to implement.

traccar has 3 option of alert:

web - beep only sounds when the sesison is active, if go to login page it
woulbe like as deactive session, so, beep will not works
e-mail: Brazil is poor country, some of person are old and do not
understand smartphone, image smartphone with e-mail
SMS: I am trying find in brazil a smpp provides, unfortunately I am search
yet


so, so sorry for english, and more once time thank you for the patient

Alex





2017-05-20 20:57 GMT-03:00 Anton Tananaev <notifications@github.com>:

**Comment by aecsalome** [comment]
what you suggest?

2017-05-20 21:09 GMT-03:00 aecsalome <aecsalome@gmail.com>:

**Comment by tananaev** [comment]
I suggest to use email or SMS notifications if you want guaranteed delivery.
