### ISSUE TITLE
[2.12 Doubt] Port Flooding Java process not closing

### ISSUE THREAD

**Issue by Starsiss** [traccar/traccar#3184]
Hi,
we are planning to upgrade traccar version to latest, but in this last week, we've been running into a problem where the server stops receiving data.

The java process used to listening the device (T55 on port 5005) never closes, and so, multiple instances of the same device appear on netstat, until the port gets flooded and we stop receiving positions.

we updated the java on the server to 1.8_131, and if we kill the java process, then new connections are stablished and positions are getting in again, without restarting the server.

so the question is, could this be a matter of the java version? or it is beause of old version server? also, will it still happen in version 3.11?

thanks.

**Comment by tananaev** [comment]
You can set connection timeout in the server config to avoid stale connections.

**Comment by Starsiss** [comment]
Do I set this value through the UI? or the config file? or directly to the database?

thanks.

**Comment by tananaev** [comment]
Please read my previous comment more carefully. It says that it's in the config file.

**Comment by Starsiss** [comment]
I did, thanks, i dind't find the entry in the default.xml config file, neither in the traccar.xml file. I did find the entry in your web and added manually.

thanks
