### ISSUE TITLE
how to open traccar web interface

### ISSUE THREAD

**Issue by vaibhiarora** [traccar/traccar#3186]
i am not able to run the traccar web interface. the backend code is successfully running in netbeans but i don't know how to proceed for opening the web interface. can anyone please guide me how to open that? thanks

**Comment by vaibhiarora** [comment]
@ta
can you please help?

thanks

**Comment by tananaev** [comment]
Have you downloaded web interface? If you have back-end running locally, you should be able to access it using following link:

http://localhost:8082

**Comment by vaibhiarora** [comment]
Yes, I've downloaded web interface. When I open the link which you have mentioned, I get an error

404 not found.

**Comment by tananaev** [comment]
It means that web interface files are missing.

**Comment by vaibhiarora** [comment]
Do I need any other IDE for running the web interface?

**Comment by vaibhiarora** [comment]
I am not getting the project files for opening the web interface in NetBeans

**Comment by tananaev** [comment]
I'm not sure what you are talking about. Web interface is just a bunch of HTML and JavaScript files that are served by back-end. If you have files, you will be able to open the web app. What config are you using? What's you current folder? What do you have in `traccar-web` folder?

**Comment by vaibhiarora** [comment]
In traccar-web, I have Tools and web folder. I have attached images showing all the contents.

![screen shot 2017-05-24 at 10 37 13 am](https://cloud.githubusercontent.com/assets/28899952/26387676/14ff328c-406d-11e7-8ae6-fc4386185b62.png)
![screen shot 2017-05-24 at 10 37 01 am](https://cloud.githubusercontent.com/assets/28899952/26387679/16f07ca4-406d-11e7-8798-cad43afdc9d0.png)
![screen shot 2017-05-24 at 10 36 48 am](https://cloud.githubusercontent.com/assets/28899952/26387681/1942145e-406d-11e7-86ab-97299566f70b.png)
![screen shot 2017-05-23 at 8 07 52 pm](https://cloud.githubusercontent.com/assets/28899952/26387684/1c16300c-406d-11e7-881e-aca6547e7d03.png)

**Comment by vaibhiarora** [comment]
I am using Eclipse for traccar-web and NetBeans for traccar-back-end

**Comment by tananaev** [comment]
So how do you connect you back-end with web app?

**Comment by vaibhiarora** [comment]
I am following this link for running the web app.

https://github.com/tananaev/traccar-web/issues/122

Compile project.
Run package.sh script to generate war file.

**Comment by tananaev** [comment]
Well, you are following very very outdate instructions that don't apply to any recent version.

**Comment by vaibhiarora** [comment]
Oh. So can you please guide me with the instructions. As of now I downloaded the traccar latest server traccar-macos-3.11.zip.

**Comment by tananaev** [comment]
All you need to do is to get code from `traccar` repository, including submodule. Then run it as a standard Java project. That's it. I'm not sure why you are using 2 IDEs.

**Comment by vaibhiarora** [comment]
Okay. I am cloning the code trom traccar repository and will run it in NetBeans. Previously the instructions which I followed were from 

https://www.traccar.org/build-in-netbeans/

Shall I follow the same?

**Comment by vaibhiarora** [comment]
@taananaev, the code is running fine now. I have opened the web interface. Thanks for your support. Will I be able to send and receive data from my device after connecting the device?

**Comment by tananaev** [comment]
Yes, of course.

**Comment by vaibhiarora** [comment]
I have GT03-c. I added the IMEI number on the web portal. I am not able to figure out the protocol and where I have to enter the protocol and port number

**Comment by tananaev** [comment]
Port is configured on the device. Please do some search before asking questions.

**Comment by vaibhiarora** [comment]
Okay. Thanks @tananaev

**Comment by bamartinezd** [comment]
@tananaev To me the same thing happens to me, this is the files in my **traccar** server directory cloned from github repo:
checkstyle.xml, nbactions.xml, schema
, swagger.json, test, debug.xml, pom.xml, setup, target, tools, LICENSE.txt, README.md, src, templates, traccar-web
and the directory **traccar-web** are the following files
LICENSE.txt
package.json
README.md
tools
web

**Comment by tananaev** [comment]
@bamartinezd 

0. Investigate the problem yourself (logs, browser console, debugger etc etc)
1. Create a separate thread
2. Describe exactly what the problem is
3. Describe what investigation you have done

**Comment by bamartinezd** [comment]
Okay, you're quite right, I'll start by descrying my problem step by step.
I have cloned the sources of **traccar-server** to my **Netbeans IDE** by following the steps perfectly described in (https://www.traccar.org/build-in-netbeans/) and perfectly executes the service which creates the database and all its objects ending up shows: **[main] INFO org.eclipse.jetty.server.Server - Started @ 27222ms**

but when I go to the browser and I type the host and port: **http: //127.0.0.1:8082** An error appears that says **404 - Not Found**

When I see this then I go back to github and clone the sources of another project **traccar-web ** from my **Netbeans IDE** to see if it works, because I need to run it to get started with my development, but running it shows a box that indicates a "Connection Error".

I do not know what else I can do please I need your help @tananaev, thank you!!!

**Comment by tananaev** [comment]
I asked you to create a separate thread.
