### ISSUE TITLE
Report Address/Coordinates

### ISSUE THREAD

**Issue by karls4** [traccar/traccar#3187]
Would it be possible to create a second reverse geocoder just for the reports instead of seeing coordinates?

Or I would happily give up the main reverse geocoding service to use it purely for the reports?

Thanks

**Comment by tananaev** [comment]
Why do you need two? One reverse geocoder works for everything.

**Comment by karls4** [comment]
Because most reverse geocoders only allow you to hit it 2000 times a day. So most of the reports will have the address' for the morning but none in the evening because the limits have been hit.

If the reverse geocoder only worked for the reports it would mean they would always have address values which is more valuable to me.

**Comment by tananaev** [comment]
It's not going to work like that. If you want to do reverse geocoding dynamically for report, it will take a very long time. For example, if you have device reporting every minute, it will require more than 1000 separate requests for a single report. It will take a very long time to process and will likely result in browser timeout.

**Comment by karls4** [comment]
Would it not be possible to take the row at the start and finish of every trip and reverse geocode them?

If you have a report over a week and roughly 6 journeys a day that would be 84 requests?

Or would it be possible to create a fall back server so if the limit is hit with one it falls back to the other service?

**Comment by tananaev** [comment]
It depends on what report you are talking about. Route report would require address for each position item.
