### ISSUE TITLE
quecklink gl505 protocol

### ISSUE THREAD

**Issue by bizkit1** [traccar/traccar#3196]
Hello. I am trying to connect a asset tracking device, quecklink gl505 device using the gl200 protocol. I can see device connecting, but the hex data does not contain lat/long and date is 1970-01-01. i think that there is another protocol for the gl505. I am attaching the protocol description, maybe someone who knows can implement it. The protocol is the same for models: GL505 and GL500.
[GL50X @Track Air Interface Firmware Update Protocol R1.00.pdf](https://github.com/tananaev/traccar/files/1033976/GL50X.Track.Air.Interface.Firmware.Update.Protocol.R1.00.pdf)
[GL50X @Track Air Interface Protocol R3.00.pdf](https://github.com/tananaev/traccar/files/1033975/GL50X.Track.Air.Interface.Protocol.R3.00.pdf)

**Comment by tananaev** [comment]
It's already supported. If you get year 1970, it most likely means that your device doesn't send any valid GPS data. Possibly it doesn't have a GPS fix.

**Comment by bizkit1** [comment]
yep, that is right, after it got position worked, but woul be nice if it can show the battery level param. For gl300 i can see battery level, but for gl505 it doesn't show. For example in traccar interface when the device sends data i can see Type=STR. 
Last message was:
2b524553503a47545354522c3430303330302c3836323336353033303134323238392c474c3530302c302c302c302c33392e342c39332c312c302e332c31372c3130352e382c32352e3934343234302c34342e3430333733362c32303137303532393134303533302c303232362c303030312c353643322c373038342c2c2c2c32303137303532393136303533302c3032444124
decoding means:
+RESP:GTSTR,400300,862365030142289,GL500,0,0,0,39.4,**93**,1,0.3,17,105.8,25.944240,44.403736,20170529140530,0226,0001,56C2,7084,,,,20170529160530,02DA$
where 93 is bettery level

**Comment by tananaev** [comment]
Traccar doesn't fully support `STR` message type. Send me an email if you need help with adding it.

**Comment by lantracking** [comment]
Hi @tananaev I'm getting these reports from my GL505 tracker. 
+RESP:GTCTN,400300,862365030030500,DEMO,0,1,0,24.1,75,0,0.6,0,108.6,-58.800959,-27.475868,20170721215947,0722,0310,0D66,F877,,,,20170721190746,00AB$
I have integrated traccar with my already working GTS Enterprise server, and in logs im getting these messages:
2017-07-21 22:18:13 DEBUG: [AC41B646: 5004 < 170.51.99.146] HEX: 2b524553503a475443544e2c3430303330302c3836323336353033303033303530302c44454d4f2c302c312c302c32342e312c37352c302c302e362c302c3130382e362c2d35382e3830303935392c2d32372e3437353836382c32303137303732313231353934372c303732322c303331302c304436362c463837372c2c2c2c32303137303732313139303734362c3030414224
2017-07-21 22:18:13  INFO: Query not provided: database.updateDeviceStatus
2017-07-21 22:18:13  WARN: Duplicate entry 'arostegui-gl505-1500685187-0' for key 'PRIMARY' - MySQLIntegrityConstraintViolationException (... < QueryBuilder:475 < DataManager:301 < DefaultDataHandler:27 < ...)
2017-07-21 22:18:13  INFO: Query not provided: database.updateLatestPosition
Is there any chance to decode the battery level (75%) from the string and write that value into GTS database?
This is my very first time with Queclink, so probably I have wrong settings.
I really appreciate your cooperation.

**Comment by tananaev** [comment]
Error message indicates that you have a duplicate entry in the database.

It's possible to include additional information, but you would have to modify SQL queries.

**Comment by lantracking** [comment]
How do you think I can insert the temperature value from traccar to SQL? Any clue?

**Comment by tananaev** [comment]
Obviously you need to know SQL language well enough. Also, you can search on forum and github. There were some related discussions before.

**Comment by lantracking** [comment]
@tananaev thank you so much for replying so quick.
I was checking the forum, and maybe using forwarder to GPRMC is the key to success.
Can you help me with some hints about extracting battery level and passing it to gprmc forwarder url?

**Comment by tananaev** [comment]
I don't think it's possible with GPRMC to pass any additional information. Anyway, this is completely off-topic now. If you want to discuss OpenGTS integration, you should find or create another thread.

**Comment by daipayan-matrix** [comment]
I have a query, I had installed the Driver in my laptop. Added the Server FTP path and allowed the port in the server. But problem is no file is generated in the provided FTP. Am tried to search a lot but no where I find any sort of files with GPS data.

Am using GL50X @Track Air Interface Protocol R3.00

Anyone please guide me!

**Comment by tananaev** [comment]
@daipayan-matrix, do you really think it's appropriate to spam like this? Please remove all of your comments except for one. Otherwise I would have to ban you from this repository.

**Comment by daipayan-matrix** [comment]
Okay, I will remove comments from other places. I never used Github, this is my first time. So dnt know the rules.
Accept my sincere apologies and if possible please try to guide me.
Am using this application - http://www.queclink.com/sites/default/files/PL2303_Prolific_DriverInstaller_v1_9_0.zip

**Comment by tananaev** [comment]
Most Queclink devices should be supported. If not, please create a new ticket.
