### ISSUE TITLE
Feature request: Expiration Date for Device

### ISSUE THREAD

**Issue by HaniTetouha** [traccar/traccar#3203]
Hello Dears,
I appreciate your fine work with Traccar, I have a feature request, expiration date for every device when attaching it to a user account, instead of expiration date for the whole account.

What you think of this feature?

Thanks alot.

**Comment by tananaev** [comment]
I've heard this request before. We might consider it at some point.

**Comment by HaniTetouha** [comment]
That would be great and very handy in many situations...

Thank you all 👍

**Comment by himsashu** [comment]
Kindly add this feature please.

**Comment by SebastEnn** [comment]
Feature got implemented. Issue can be closed.
