### ISSUE TITLE
Motion event - minimum time to switch from "moving" to "stopped" request

### ISSUE THREAD

**Issue by javier260** [traccar/traccar#3204]
Hi,
I have set:  "event.motion.speedThreshold" to 5 in order to avoid fake moving alerts, but now I'm getting an alert every time car is stopped by a red light, or stop, or queue. 

If not already exists, could be possible to set a parameter with minimum time needed to switch from "moving" to "stopped"?

Thanks

**Comment by tananaev** [comment]
Unfortunately it's not that easy. What you are asking would require to request data from the database on every report from the device.

**Comment by Abyss777** [comment]
@tananaev I just thought, what if also check `fixTime` difference between current and last? Can be any problems here?

**Comment by tananaev** [comment]
It will only work if the period between message is longer than time "threshold".

**Comment by Abyss777** [comment]
Agree.
Looks like the only way is cache all speed values for time "threshold" per device. The plus is that we can use it twice, for stop/moving and for overspeed.
