### ISSUE TITLE
Need help for traccar api

### ISSUE THREAD

**Issue by kedarnathjimage** [traccar/traccar#3206]
Hi Tananaev,

how to Set or unset a Notification  using traccar api.  in api-reference you have mentioned only following parameter attributes ,id, type, userId. when i api these parameter i get below error 
stdClass Object
```
(
    [responseCode] => 401
    [error] => 
    [response] => HTTP 401 Unauthorized - WebApplicationException (SecurityRequestFilter:108 < ...)
)
```
my question is how set another  parameter like web, sms, mail.

**Comment by tananaev** [comment]
Your problem is not parameters. It's authentication as the error suggests.

**Comment by dev1983** [comment]
Hi 

I am also getting error: HTTP 401 Unauthorized - WebApplicationException (SecurityRequestFilter:113 < ...)

what I did: 

I created new database "traccar" as root user then installed application. Once I login to app then it gives error also it gives Web socket connection error ! any clue please ?
