### ISSUE TITLE
Need helpto modify users permissions config file

### ISSUE THREAD

**Issue by joepr** [traccar/traccar#3208]
**Hello Traccar Team** 

I have a Traccar installation that need to modify to fit the user needs. In this case the users have the permissions - **Device Read Only** I try using the ReadOnly permission but it has to many limitations. 

I will like to know which configuration file should I edit on the source code to remove or disable this features. 

Thanks in advance!!

**Under Settings**
Disable access to Groups & Calendar
![image](https://cloud.githubusercontent.com/assets/10345032/26696942/78055d30-46de-11e7-9cd3-d4a7ad4c74ff.png)

**Under Notifications**
Remove the following options in yellow . Don't show them at all
![image](https://cloud.githubusercontent.com/assets/10345032/26697069/c7777f92-46de-11e7-9095-8c0a56b6e8cd.png)

**Disable Access to send commands**
![image](https://cloud.githubusercontent.com/assets/10345032/26696838/0fd0788a-46de-11e7-8514-60d03055bf42.png)
 
**Under State Window Remove some features**
![image](https://cloud.githubusercontent.com/assets/10345032/26697603/a7a0ecce-46e0-11e7-81c0-28c6dbdf1288.png)

**Comment by tananaev** [comment]
You have to modify JavaScript code and potentially back-end as well to implement what you want.

If you need help with customisation, please send me an email. Address is in profile.

**Comment by joepr** [comment]
Thanks Anton for your help
