### ISSUE TITLE
Adding a user using API by manager account

### ISSUE THREAD

**Issue by kedarnathjimage** [traccar/traccar#3210]
Hi Tananaev,

While crating a readonly user i am getting error  message "Manager access required". please tell me if any parameter is missing in the below code. 
```
public static function addUser($userid, $name,$email, $phone, $password, $expirationtime, $distanceunit, $speedunit, $devicelimit, $userlimit, $readonly, $disabled, $devicereadonly,  $cookie) {
        //"token":'.$cookie.',
        $data='{"id":-1, "name":"'.$name.'","email":"'.$email.'", "phone":'.$phone.',"password":"'.$password.'", "expirationTime":"'.$expirationtime.'", "deviceLimit":"'.$devicelimit.'", "userLimit":'.$userlimit.', "readonly":"'.$readonly.'",  "disabled":"'.$disabled.'", "deviceReadonly":"'.$devicereadonly.'","admin":false,"map":"","distanceUnit":"'.$distanceunit.'","speedUnit":"'.$speedunit.'","latitude":0,"longitude":0,"zoom":0,"twelveHourFormat":false}';

        return self::curl('/api/users/','POST',$cookie ,$data,array(self::$json));
    }
```
Thank you

**Comment by tananaev** [comment]
I guess your user is not allowed to create other user accounts.

**Comment by kedarnathjimage** [comment]
but I have given userlimit = 20

**Comment by tananaev** [comment]
I would recommend to try official Traccar web app first before trying API.

**Comment by kedarnathjimage** [comment]
Hi tananaev,

After doing a lot of permutation and combination, this is what i have finally understood. 

When a user (NON ADMIN) does NOT have expirationTime set for his account then he can add another user under him using API. Although if the user himself has expirationTime then when i invoke the same API with same parameter it throws Admin access required error.

Can you please verify if this issue can be replicated at your end and if this is bug. I have tried invoking the same using postman and seen a similar behavior

My JSON array is following
{"id":-1,"name":"Test That","password":"Testthat","email":"emailthat@gmail.com"}

Sent to 
{MYURL}/api/users

Method
POST

Header
Accept -> application/json
Content-Type -> application/json

Thanks

**Comment by tananaev** [comment]
@Abyss777, can you please check if we have some permissions issues here.

@kedarnathjimage, you don't have to send `"id":-1`. In case of official web app it's added by ExtJS framework, but it's ignored on the server. Not really relevant to the problem though.

**Comment by Abyss777** [comment]
@kedarnathjimage 
Please clarify what is the problem? Is the behavior different from explained here https://www.traccar.org/documentation-user-management/ ?

Also want to note that any new user can be POST if Registration is enabled.

**Comment by meneva** [comment]
hi Tananaev, thanks for your prompt reply. Can u please point me exactly which fields are for Admin user only. I tried to update just name and email but still can not update. thanks for your kind cooperation

**Comment by tananaev** [comment]
Fields that are in permissions section in the web app.

**Comment by meneva** [comment]
hi tananaev, thanks for your suggestion. Actually I am using the following function to interact with the web API. But it still there is no entry in "user_user" table.
`public static function addUser($cookie, $name, $email, $password) {
		$id = '-1';
		$name = $name;
		$email = $email;
		$readonly = 'false';
		$admin = 'false';
		$map = '';
		$latitude = '0';
		$longitude = '0';
		$zoom = '0';
		$password = $password;
		$twelveHourFormat = 'false';
		$coordinateFormat = '0';
		$disabled = 'false';
		$expirationTime = '';
		$deviceLimit = '0';
		$userLimit = '0';
		$deviceReadonly = 'false';
		$limitCommands = 'false';
		$token = '';
		//$attributes = $attributes;
		$data = '{"name":"' . $name . '","email":"' . $email . '","password":"' . $password . '","readonly":"' . $readonly . '","admin":"' . $admin . '","map":"' . $map . '","latitude":"' . $latitude . '","longitude":"' . $longitude . '","zoom":"' . $zoom . '","twelveHourFormat":"' . $twelveHourFormat . '","coordinateFormat":"' . $coordinateFormat . '","disabled":"' . $disabled . '","expirationTime":"' . $expirationTime . '","devicelimit":"' . $deviceLimit.'","userlimit":"' . $userLimit . '"}';

		return self::curl('/api/users', 'POST', $cookie, $data, array(self::$jsonC));
	}`

**Comment by tananaev** [comment]
Does it work when you do it in the official web app? Clearly it does, right? It should work from your code the same way.

**Comment by meneva** [comment]
Actually my code is sending the same parameter as the web API does. But now new user devicelimit is always set to "-1" even i force it to 0 in my code. I think that's why there is no entry in user_user table. Can we set the default devicelimit to 0 in traccar settings?  I already set in database column to 0 but it does not effect to anywhere.

**Comment by tananaev** [comment]
Sounds like you are not authenticated as admin or manager. That's the only reason device limit can be forcibly set to "-1".

**Comment by meneva** [comment]
Ok... Let me explain my scenario. I have a Manager user with the following settings:
a. devicelimit = 0
b. userlimit = 0
c. expirationtime = ''
And now i want to create another user under him using API.
what else condition we need to be a manager user?

**Comment by tananaev** [comment]
You can't create any users under him because that manager has a limit of 0 users, as you can see.

**Comment by tananaev** [comment]
Look, if you want to know how it work and you don't understand documentation, you can experiment with the web app. Documentation is available, examples are available. You just need to put some of your own effort and time to understand it.

**Comment by meneva** [comment]
Hi Tananaev, actually i increased the userlimit to 500 and devicelimit to 200 from web app but still can insert any record in user_user table while creating new user under this manager. For your information, I have gone throuh the whole user documentation and also played with the web app.

**Comment by meneva** [comment]
Hi tananaev, sorry to ask you again and again the same issue... actually I have followed the documentation for user management and tried to create a user as manager. but still can not create another user under him via api. Is there any other way to insert data into user_user table for parent-child relashionship ? I am just stuck creating parent-child user.

**Comment by kakashi01s** [comment]
@kedarnathjimage @meneva  hello how Did you manage to create a user using API ? Documentation seems very confusing, Do i need to create a session to make a new user?
