### ISSUE TITLE
Cannot Connect TK200 with Traccar 

### ISSUE THREAD

**Issue by sopheakmorm** [traccar/traccar#3211]
Hi Sir,
I have sent command to point with my traccar server on ubuntu 16.04 port 8082
Command : adminip123456 myip 5006 
and it replied "admin ok";

I think it successfully connected to that server.

But I cannot see the position update in my server tracer.

What was I wrong ?

Thank you !!! :)

**Comment by tananaev** [comment]
Please follow this guide:

https://www.traccar.org/troubleshooting/

**Comment by Sopheakmorm** [comment]
I have checked log already.
the device never connected to traccar server.
I think I may wrong some configuration such port ,
I have pointed to port 5002 and then tried with 5006 but still not work.
That is correct ?

thank you :) 👍

**Comment by Sopheakmorm** [comment]
The full IMEI is 352887074869789 and I have adjusted it to 087074869789 
depend on this instruction : https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices

**Comment by tananaev** [comment]
Where are the logs?
