### ISSUE TITLE
How to see the devices under each group for a user?

### ISSUE THREAD

**Issue by sharat94** [traccar/traccar#3219]
After going through the API Documentation I havent been able to find an API for a user to list out devices assigned to only a particular group among many other groups the user is signed on for. Please let me know if such API can be developed?
For example 
GET base_url/groups/id - returns all devices registered to the group

**Comment by tananaev** [comment]
There is no such API at the moment. User can only get all his devices or a specific device.

**Comment by tananaev** [comment]
I believe we have an option to request specific device or group of devices now.
