### ISSUE TITLE
Traccar reusing "most recent" position in invalid messages.

### ISSUE THREAD

**Issue by gustavofcalmeida** [traccar/traccar#3224]
The device sent this message:
```
2017-06-03 18:31:50 DEBUG: [63E7B52B: 5001 < 191.10.72.106] imei:***,tracker,2201030344,,F,064410.000,A,0811.6917,S,03455.1348,W,0.00,0;
2017-06-03 18:31:50  INFO: [63E7B52B] id: ***, time: 2022-01-03 00:44:10, lat: -8.19486, lon: -34.91891, speed: 0.0, course: 0.0
Database: gps103	2	2017-06-03 20:31:51	2022-01-03 03:44:10	2022-01-03 03:44:10	1	-8.194861666666666	-34.918913333333336	0	0	0	{"ip":"191.10.72.106","distance":847.13,"totalDistance":847.13}	0	null
```
This is obviously a device mistake that can be filtered with `filter.future`

After this, anytime the device's GPS is not fixed, Traccar is using the most recent position (the one above) to fill the missing fields. By most recent I mean the one with the biggest date, not the last one received. Example:
```
2017-06-04 00:25:22 DEBUG: [47D20566: 5001 < 152.253.180.108] imei:***,tracker,000000000,,L,,,4f9d,,51a6,,,;
2017-06-04 00:25:22  INFO: [47D20566] id: ***, time: 2022-01-03 00:44:10, lat: -8.19486, lon: -34.91891, speed: 0.0, course: 0.0
Database: gps103	2	2017-06-04 02:25:22	2017-06-04 02:25:22	2022-01-03 03:44:10	1	-8.194861666666666	-34.918913333333336	0	0	0	{"ip":"152.253.180.108","distance":0.0,"totalDistance":847.13}	0	{"radioType":"gsm","considerIp":false,"cellTowers":[{"cellId":20902,"locationAreaCode":20381,"mobileCountryCode":0,"mobileNetworkCode":0}]}

2017-06-05 16:00:37 DEBUG: [B7721749: 5001 < 177.79.82.19] imei:***,tracker,000000000,,L,,,4f9d,,519c,,,;
2017-06-05 16:00:38  INFO: [B7721749] id: ***, time: 2022-01-03 00:44:10, lat: -8.19486, lon: -34.91891, speed: 0.0, course: 0.0
Database: gps103	2	2017-06-05 18:00:38	2017-06-05 18:00:38	2022-01-03 03:44:10	1	-8.194861666666666	-34.918913333333336	0	0	0	{"ip":"177.79.82.19","distance":0.0,"totalDistance":847.13}	0	{"radioType":"gsm","considerIp":false,"cellTowers":[{"cellId":20892,"locationAreaCode":20381,"mobileCountryCode":0,"mobileNetworkCode":0}]}
```
LBS geolocation is disabled by default. So, shouldn't the two invalid positions above be discarded? And even if they are not, why are they using the "most recent" position?

This looks like a protocol error, because the flags `L` in the messages shouldn't be translated to `valid = 1` in the database.

**Comment by tananaev** [comment]
Looks like the message wasn't filtered. Probably because you didn't have filtering enabled at the point when position was received.

Traccar decodes additional data from `L` reports and appends last know GPS data, so it's not an error.

**Comment by gustavofcalmeida** [comment]
The server receives a message at `2017-06-04 00:25:22` when geolocation is disabled.
The message `imei:***,tracker,000000000,,L,,,4f9d,,51a6,,,;` says:
I have no GPS fix, I don't know where I am or what time is it, but I know I'm near this cell tower 4f9d, 51a6.

Using this the server creates the VALID position below:
`id: ***, time: 2022-01-03 00:44:10, lat: -8.19486, lon: -34.91891, speed: 0.0, course: 0.0`

How can this be right? I'm not saying this because of the future date. If I had filtering enabled, another more realistic position would have been used, but the effect would be the same.

**Comment by tananaev** [comment]
Clearly you didn't have filtering enabled. Otherwise it would be impossible for you to get year 2022 in the database. Maybe you had something misconfigured.

Anyway, I already explained why it is correct and that's how Traccar works.
