### ISSUE TITLE
How to add communication protocol in web server 

### ISSUE THREAD

**Issue by ramesh456** [traccar/traccar#3228]
Hi , 

I want to add different device(not listed on your site) communication protocol to get that device data. 

So how can i add new protocol and where i have to defined all the new things including port?

Please guide me

**Comment by tananaev** [comment]
Look at one of the existing protocols and do the same thing.

**Comment by ramesh456** [comment]
Ok. so just have to java files only ? or any other configuration ?

**Comment by tananaev** [comment]
Obviously you have to add it to the configuration as well.

**Comment by ramesh456** [comment]
Ok.
