### ISSUE TITLE
index Postgres

### ISSUE THREAD

**Issue by netluca1** [traccar/traccar#3229]
Hello
Are the postgress db tables indexed?

**Comment by tananaev** [comment]
Yes.

**Comment by netluca1** [comment]
Then I think I have a problem.
Is it normal to have as DB PostresSql and making a query does so much?
- Executing query:
Select * from positions;
Total query runtime: 07:41 minutes
1377271 rows retrieved.

**Comment by tananaev** [comment]
I'm just speechless. You are selecting ALL records from the database. What indexes are you talking about?
