### ISSUE TITLE
Raspberry pi 3

### ISSUE THREAD

**Issue by oaf2015** [traccar/traccar#3230]
How do I use the raspberry pi 3 as a trackable client? Is there an image for the pi or a way to run it side by side with raspbian and a usb gps antenna?

**Comment by tananaev** [comment]
There is no official client, but you can use some script or third party solution. For example:

https://github.com/liske/tralnx

**Comment by oaf2015** [comment]
The installation process seems a little confusing. Have you done it before?

**Comment by tananaev** [comment]
No, I have never used it. Note that it's not an official project. I'm not even sure if it works.
