### ISSUE TITLE
Save OBD data received from ELM327 usig traccar.

### ISSUE THREAD

**Issue by ranganathdg** [traccar/traccar#3259]
Hi,
      I am using Traccar plugin to save the GPS data from my mobile phone onto OpenGts. Now, I have developed
 an android app to talk to ELM327 - OBD2 dongle.  I am able to receive data from the dongle, now, I have to save OBD data like GPS data. How can this be done? Your help is appreciated.

Thanks,
Ranganath

**Comment by tananaev** [comment]
If you are using OsmAnd protocol you can include as many additional parameters as you want.

**Comment by MisterEffiks** [comment]
Hi ranganathdg,

have you made some progress with your own OBD2 data integration?

Thanks,
MrFX

**Comment by hiagocosta** [comment]
I'm interested too

> Hi, I am using Traccar plugin to save the GPS data from my mobile phone onto OpenGts. Now, I have developed an android app to talk to ELM327 - OBD2 dongle. I am able to receive data from the dongle, now, I have to save OBD data like GPS data. How can this be done? Your help is appreciated.
> 
> Thanks, Ranganath
