### ISSUE TITLE
GT003 - supported?

### ISSUE THREAD

**Issue by dv336699** [traccar/traccar#326]
http://i00.i.aliimg.com/img/pb/799/356/525/525356799_647.jpg
I didn't see GT003 in the devices list, so not sure if it's supported nor which port should I point it to.

wireshark capture - I used port 56565
http://www.sendspace.com/file/j6gn20

pointed to port 5023 as suggested to use GT06 here:
http://forum.gps-trace.com/viewtopic.php?id=4831

and got this:
```
2013-07-09 16:21:00 org.traccar.BasePipelineFactory$StandardLoggingHandler.log FINE: [5023 <- 179.161.47.41] - (HEX: 78780d010383613050218202000580740d0a)
2013-07-09 16:21:00 org.traccar.BasePipelineFactory$StandardLoggingHandler.log FINE: [5023 -> 179.161.47.41] - (HEX: 7878050100059ff80d0a)
```
I checked the GPS command and the GPS is not fixed, so most probably is that why there is no GPS data comming.

**Comment by warlockopy** [comment]
Dear Tananaev.
Anyone you know is working with this device, and that is compatible with GT06 protocol.
I am attaching the protocol for reference.

**Comment by warlockopy** [comment]
it seems #483 has solved it, i will check and update here also.

**Comment by rumapathi** [comment]
Hi friends,
                  I got value like '78780d013052887071911394000511540d0a' using  $d = unpack("H*data", $input); ..from that how can i get the  lat and lon ,speed..etc value..Please guide me to get the appropriate value.

Thanks in advance.

R.Umapathi

**Comment by tananaev** [comment]
@rumapathi, I would recommend to take a look at GT06 protocol decoder module:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gt06ProtocolDecoder.java

**Comment by rumapathi** [comment]
@tananaev ,
            Thanks for your reply. Can we get the value through PHP?

Thanks

**Comment by tananaev** [comment]
I don't know much about PHP, but there must be a way to work with binary data.

**Comment by rumapathi** [comment]
@tananaev,
               Once we got this 78780d013052887071911394000511540d0a value ..will we need to send reply to the device?. Then only we can get the lat and lon? or working with our 78780d013052887071911394000511540d0a is enough thing?

Thanks for your great support. 

Thank you

**Comment by tananaev** [comment]
It's a login message. You need to send a reply.

**Comment by rumapathi** [comment]
@tananaev 

Thanks for your useful information information.

**Comment by rumapathi** [comment]
@tananaev 

Will we need to convert this value into hexadecimal to send reply to the device?

Thnak you.

**Comment by tananaev** [comment]
It's binary data. You need to work with it as binary and reply in binary as well.

**Comment by rumapathi** [comment]
Hi all friends,

  Any one have, send reply from server to device script using php.? or reference links.?

Thank you

**Comment by azzahrah** [comment]
helo can u share GT003 Protocol?
