### ISSUE TITLE
Forward URL

### ISSUE THREAD

**Issue by SRIKAAA** [traccar/traccar#3265]
http://192.168.50.147:5560/Default.aspx?id={uniqueId}&amp;code=0x0000&amp;protocol={protocol}&amp;deviceid={deviceid}&amp;serverTime={serverTime}&amp;deviceTime={deviceTime}&amp;fixTime={fixTime}&amp;valid={valid}&amp;latitude={latitude}&amp;longitude={longitude}&amp;speed={speed}&amp;course={course}&amp;address={address}&amp;attributes={attributes}

Is the above URL in correct format. We are not receiving parameters . How to check the error.

**Comment by tananaev** [comment]
Looks fine to me. To check the problem I would recommend to start with as little parameters as possible, not as many as possible. And then when you get that working start adding more.
