### ISSUE TITLE
Traccar stops frequently

### ISSUE THREAD

**Issue by mihir0109** [traccar/traccar#3266]
Hello,
My traccar server stops frequently, I have 32 GB space and 2 GB RAM (AWS ubuntu). Around 150 devices are connected continuously. Any possibility to prevent this? Is there any way to disable logs so that can reduce the overhead? Because log files are generated daily and it increases huge amount of storage and have to frequently delete log file manually every week to empty the space.

**Comment by tananaev** [comment]
Check following page:

https://www.traccar.org/optimization/

**Comment by mihir0109** [comment]
Hello, Thanks for your suggestion. I have already increased connection limit earlier. it's right now:
65536 for -Hn and 1024 for -Sn
I am using mysql database. 
Can you post a timeout command to add in config file? And any possibility to disable logs?

**Comment by tananaev** [comment]
You should read official documentation:

https://www.traccar.org/configuration-file
