### ISSUE TITLE
Cannot Configure Traccar Server... please help

### ISSUE THREAD

**Issue by babislg** [traccar/traccar#3270]
I have successfully installed the server and its running... but when i tried to test server with your client app on my android phone it is not connecting to the server... at the status in the app its showing "Send Failed"

I have configured the app with my public IP address and given the port No. 5055

Then i tried it with demo traccar server... still its not working

Please help me on that.

**Comment by tananaev** [comment]
Check this guide:

https://www.traccar.org/troubleshooting/

**Comment by babislg** [comment]
Thanks Anton... problem solved, port forwarding was the problem... thr
traccar client app is working. Now i hv to see it with real device.

**Comment by babislg** [comment]
Hi anton,
please help me with another problem. I have setup a chinese generic device with port No. 5002, intially i got the location. but traccar server is not showing the movement of the device, the device set for 30 secs interval timer for uploading location details, whether traccar client app in android is showing movement.
in the user manual of the device it is written as a GT02A device but server is showing as TK103.
I have seen in the server log hex messages that server is recording speed, course etc but not showing them.
![serverhex](https://user-images.githubusercontent.com/29571245/27431921-d0cdfbdc-576b-11e7-82ef-07f6c92be74b.jpg)

**Comment by tananaev** [comment]
Everything seems to work according to the logs. You must be missing something.

**Comment by babislg** [comment]
Hi Anton,
couldnot solve the problem :( at last pointed the device in your demo4 server and tested it... configured the device with  time interval of 10 secs. In your server the device is moving but not how it should be... attached a screen shot of your server... is there any timezone issue? or my device is not updating location. please help...
![demo4](https://user-images.githubusercontent.com/29571245/27478237-9ac5f460-582c-11e7-874a-8e65de125aca.jpg)

**Comment by tananaev** [comment]
Traccar displays exactly what your device sends, so if something is wrong, it's likely on the device side.
