### ISSUE TITLE
Suggestion : Using fixtime for certain events instead of event tables servertime

### ISSUE THREAD

**Issue by jaimzj** [traccar/traccar#3276]
Hello,

This scenario was noticed on GT06 protocol.

While the device is offline and position is being stored locally on device storage, and later device comes online. (sequence example given below)

1. 7:29 AM ( deviceOffline)
2. 7:30 AM (ignitionOff)
3. 9:30 AM (deviceOnline)

at 9:30 AM device uploads old data however the (ignitionOff) data gets recorded with serverTime. and in the web-ui and API both it returns the event tables serverTime (which is 9:30 AM when the server recieved the data) however the actual event positionid record when checked shows that the fixTime actual event time was 7:30 am.

The problem is the ignitionOff or such events will give a wrong time stamp. as currently the serverTime specially and mainly only when its old/stored data being uploaded to server.

Please let me know if any log/record would be required for the same?

**Comment by tananaev** [comment]
Yes, I would need to see logs of all 3 messages.

Also, it's unlikely that we would change this because not all events are based on positions, so it's not possible to get fixTime for everything.

**Comment by jaimzj** [comment]
Shall re-create the scenario and share the logs shortly.

Maybe instead of changing the current displayed server time, a slight modification can be done to the web-ui where most event contain its corresponding positionid, so additional column fixtime from the position could be displayed if positionid is available for that event?

**Comment by tananaev** [comment]
We already do this.
