### ISSUE TITLE
Acknowledge to Login request from device for Location 0x12 and 0x1A

### ISSUE THREAD

**Issue by ashish2002** [traccar/traccar#3282]
Hi Tananaev,

I have passed acknowledgement with different values like

default one:
```
byte [] b1 = new byte[]{(byte)0x78, (byte)0x78, (byte)0x05, (byte)0x01, (byte)0x00, (byte)0x01, (byte)0xD9, (byte)0xDC, (byte)0x0D, (byte) 0x0A};
```
Tried below one:
```
byte [] b1 = new byte[]{(byte)0x78, (byte)0x78, (byte)0x05, (byte)0x12, (byte)0x00, (byte)0x01, (byte)0xD9, (byte)0xDC, (byte)0x0D, (byte) 0x0A};
```
can you please tell me what exact values i need to pass as an acknowledgement to get continuous response for 0x12 and 0x1A command protocol.

I am stuck here for more than 3 days.

Thanks

**Comment by tananaev** [comment]
Have you compared it with what Traccar sends?

**Comment by ashish2002** [comment]
nope,

**Comment by ashish2002** [comment]
Hi

I have used following functions to generate valid response.

    public  short crc16Ccitt(byte[] bytes) {
        int crc = 0xFFFF;          // initial value
        int polynomial = 0x1021;   // 0001 0000 0010 0001 (0, 5, 12)

        for (byte b : bytes) {
            for (int i = 0; i < 8; i++) {
                boolean bit = ((b   >> (7-i) & 1) == 1);
                boolean c15 = ((crc >> 15    & 1) == 1);
                crc <<= 1;
                if (c15 ^ bit) crc ^= polynomial;
            }
        }

        crc &= 0xffff;
        return (short) crc;
    }


    private byte[] getLoginResponse(byte[] req){
        byte[] b = new byte[4];
        byte[] bResponse = new byte[10];
        b[0] = 0x05;
        b[1] = req[3];
        b[2] = req[req[2] - 6 + 5];
        b[3] = req[req[2] -5 + 5];

        short x = crc16Ccitt(b);
        bResponse[0] = 0x78;
        bResponse[1] = 0x78;
        bResponse[2] = 0x05;
        bResponse[3] = req[3];
        bResponse[4] = req[req[2] - 6 + 5];
        bResponse[5] = req[req[2] -5 + 5];
        bResponse[6] = (byte) ((x >> 8) & 0xff);;
        bResponse[7] = (byte) (x & 0xff);
        bResponse[8] = 0x0D;
        bResponse[9] = 0x0A;
        return bResponse;
    }

**Comment by tananaev** [comment]
You have to compare what your server sends with what Traccar sends.

**Comment by ashish2002** [comment]
Below is the response getting on server.

Got a client 0
78 78 0D 01 03 58 51 10 22 63 63 06 00 03 CE 09 0D 0A
IMEI 0358511022636306
Response
78 78 05 01 00 03 3F D6 0D 0A
End of write data
Message sent to the client
78 78 0D 01 03 58 51 10 22 63 63 06 00 05 AB 3F 0D 0A
IMEI 0358511022636306
Response
78 78 05 01 00 05 5F 10 0D 0A
End of write data
Message sent to the client
78 78 0D 01 03 58 51 10 22 63 63 06 00 07 88 2D 0D 0A
IMEI 0358511022636306
Response sent to device
78 78 05 01 00 07 7F 52 0D 0A

**Comment by tananaev** [comment]
Now you need to send some of those messages to Traccar and compare responses.

**Comment by ashish2002** [comment]
let me know where i can send my messages to Traccar, can you please share the link of interface

**Comment by tananaev** [comment]
You should send it to port 5023. You can use `hex.sh` shell script from tools.

**Comment by ashish2002** [comment]
did not get you, can you please tell me what is the error area in our code

**Comment by ashish2002** [comment]
created sample app and send the same request to 5023 port, getting "connection time out" error. 

    private int SocketServerPort = 5023;
    private String hostAddress = "www.traccar.org";

please advise

**Comment by tananaev** [comment]
I'm not sure why you are pointing it to Traccar website. You have to install Traccar server or use one of the demo servers.

**Comment by ashish2002** [comment]
Hi ,

 

I have pointed one of your demo server and send data. I have developed sample app to send data on port.

 

IP: 149.56.170.158

Port: 5023

 

Data :  byte[] s = new byte[]{0x78,0x78,0x0D,0x01,0x03,0x58,0x51,0x10,0x22,0x63,0x63,0x06,0x00,0x3F,0x35,(byte)0xE6,0x0D,0x0A};

 

As you mentioned, to compare the response generated on our server and generated from your server.

 

After long time, no data is coming from the server. Please advise

 

 

 

Regards

Ashish C

 <http://www.agilissys.com> www.agilissys.com

+91 9879462342

**Comment by tananaev** [comment]
Your device also has to be registered on the server. If it still doesn't work, you are doing something wrong.

**Comment by ashish2002** [comment]
Hi Tananaev,

I have applied the CRC algorithm and validated that it is returning proper checksum / Error code 
78 78 05 01  00 01 D9 DC 0D 0A . it seems CRC algorithm has been implemented properly. however, i am not getting location information at certain interval (10 secs). 

I am sending response to device in 787805010001D9DC0D0A fomat. is it correct ?

or i need to send it like 0x787805010001D9DC0D0A, please advise

another question is, why device is not returning proper data ?
do we need to send response to every device request  ?

please advise

**Comment by tananaev** [comment]
You have to send binary data. I you need any further help, I want to see two `pcap` files. One for communication with Traccar, the other one is with your server.

**Comment by AnkitArora99** [comment]
Hello @ashish2002 did you find any solution for the problem, I am facing exact same problem I have code in c# which is working fine but code in python is not working but both of these code are giving same output

**Comment by dummyuser-123** [comment]
hi @ashish2002 and @AnkitArora99,

I am also facing similar problem like both of you. So, do you guys got any solution for this problem ?
I am using python language for the server and I am getting login response from terminal but when I am sending it back (As mentioned in protocol docs) then I am not getting anything in return and terminal is continuously sending login packet.

If any one of you could tell about how to solve this problem then it would be an great help for me.

**Comment by AnkitArora99** [comment]
@dummyuser-123 I didn't find anything on the internet so I ended up writing the whole code in c#
