### ISSUE TITLE
GT06N Device Status Always online even vechile igintion is turned off

### ISSUE THREAD

**Issue by Sargunan** [traccar/traccar#3283]
Hi,

We are trying integrate GT06N device, we found device status does not turn to OFFLINE, Even though ignition state changed to NO
is it configurable to show the device status as OFFLINE, when ignition status is NO

Thanks for your help

![](https://user-images.githubusercontent.com/5010960/27446188-49d960b0-579a-11e7-8c75-8516fb3155e6.png)

**Comment by tananaev** [comment]
Offline status indicates connection status. It has nothing to do with ignition.

It would require code modifications to use ignition for status. Send me an email if you need help with implementing it.

**Comment by ramakrishnaraov** [comment]
Thanks for your quick response.
