### ISSUE TITLE
Too many open files error while connecting multiple gps devices

### ISSUE THREAD

**Issue by jkhasiza** [traccar/traccar#3288]
Hello @tananaev 
We're using java socket to connect with GT06 devices. However, after some time we're getting following error in the logs
```
java.net.SocketException: Too many open files (Accept failed)
at java.net.PlainSocketImpl.socketAccept(Native Method) ~[?:1.8.0_121]
at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409) ~[?:1.8.0_121]
```
Can you suggest, what could be the root cause for this?
If you want, we can share the code snippet as well.

**Comment by VanitySoft** [comment]
​Are you running your own server on UNIX environment?..you just need to
increase the limt.
https://easyengine.io/tutorials/linux/increase-open-files-limit/
​

Jeryl Cook
Founder & Chief Executive Officer
VanitySoft, Inc.
A Geo Business Intelligence Technology Consulting Firm
www.vanity-soft.com
www.linkedin.com/in/jerylcook
Get answers to "who knew what, when, and where"... and everything in
between.

____________________________________________________
This message contains information which may be confidential and privileged.
Unless you are the addressee (or authorized to receive for the addressee),
you may not use, copy or disclose to anyone the message or any information
contained in the message. If you have received the message in error, please
advise the sender by reply e-mail jeryl.cook@vanity-soft.com, and delete
the message.

**Comment by tananaev** [comment]
I would also recommend to read this page:

https://www.traccar.org/optimization/

**Comment by jkhasiza** [comment]
Earlier ulimit was 1024, that might be causing the exceptions.
I've increased the ulimit. It looks like this now
$ ulimit -Hn
102400
$ ulimit -Sn
102400

Number of open files on restarting server is
$ lsof | grep java | wc -l
226
No. of open files are increasing gradually. After couple of hours, the result is
$ lsof | grep java | wc -l
879

At this stage, on sending sms to GT06 device, i am receiving following reply:
Battery:4.18V,NORMAL; **GPRS:Link Down** GSM Signal Level:Strong; GPS:Successful positioning; SVS Used in fix:15(12); , GPS Signal Level:34,35,37,34,33,36,38,32,18,33,0,0,0,0,0 ACC:OFF; Defense:OFF;
On restarting server: Following message is received
Battery:4.18V,NORMAL; **GPRS:Link Up** GSM Signal Level:Strong; GPS:Successful positioning; SVS Used in fix:15(12); , GPS Signal Level:34,35,37,34,33,36,38,32,18,33,0,0,0,0,0 ACC:OFF; Defense:OFF;

Is there any possibility of connection leak?
Here is my code snippet:

 public void saveGpsData(Socket clientCon) {
                InputStream ios = null;
                DataOutputStream dOut = null;
                try {
                    LOG.info("Just connected to {}", clientCon.getRemoteSocketAddress());
                    ios = clientCon.getInputStream();
                    dOut = new DataOutputStream(clientCon.getOutputStream());
                } catch (IOException e1) {
                    LOG.error("Exception occured", e1);
                }
                if (ios != null) {
                    try {
                        // Data parsing and save logic
                        
                    } catch (Exception e) {
                        LOG.error(e.getMessage(), e);
                    } finally {
                        try {
                            ios.close();
                            dOut.close();
                            clientCon.close();
                            LOG.info("Device disconnected");
                        } catch (IOException e) {
                            LOG.error("Exception while closing client", e);
                        }
                    }
                }
           
    }

P.S. I am using java.net.socket to create Socket. 

Thanks in advance.

**Comment by tananaev** [comment]
The problem is that if device loses connection it might not close the connection, so you have to have an idle timeout to close stale connections.
