### ISSUE TITLE
Reports are too slow as I have around 8 millions record

### ISSUE THREAD

**Issue by mihir0109** [traccar/traccar#3290]
Hello,
In my system, I have 300 GPS devices attached and each sending location at every 20 seconds or so. This becomes very huge amount of data in mysql. it took more than 30 seconds to generate report for even single day for single vehicle. Any solution on this? I keep deleting old data  i.e. more than 15 days data regularly.. but still records are more than 5 million. Any suggestion or solution for this?

Server is of 4 GM RAM.

**Comment by tananaev** [comment]
You can try to check query execution plan. If you are using old version of MySQL I would recommend to upgrade. It might improve performance.
