### ISSUE TITLE
¿What is traccar-master?

### ISSUE THREAD

**Issue by Roman0101** [traccar/traccar#3294]
I´m new at this and I want to know if the "traccar-master" package can be mounted on a server, if you can help me please...

**Comment by condeitokako** [comment]
You can mount it locally by downloading the original project.

**Comment by tananaev** [comment]
@Roman0101, `traccar-master` is a source code package. If you don't know what it is, most likely you should not be using it. If you want to install Traccar on your server you should download installation package from the official website:

https://www.traccar.org/download/

**Comment by Roman0101** [comment]
thank you guys, I was checking the codes of the traccar-master package and are very similar that the Traccar official but you know more than me so I will download the package from the official website, and again thank you very much.

**Comment by tananaev** [comment]
@Roman0101, traccar-master IS the official Traccar.
