### ISSUE TITLE
Attributes from external source

### ISSUE THREAD

**Issue by judeaddo** [traccar/traccar#3298]
Is it possible to query data from an external Db source (MySQL) and display as device attributes?

**Comment by tananaev** [comment]
Obviously it's not possible out of the box, but it's possible to implement as a customization.

**Comment by judeaddo** [comment]
Thanks for the reply. So what do I need to do?

**Comment by tananaev** [comment]
If you are interested in this customization please send me an email to discuss details.

**Comment by judeaddo** [comment]
Ok. Thanks.
