### ISSUE TITLE
Need support for TR02 - Protocol attached

### ISSUE THREAD

**Issue by tsk1979** [traccar/traccar#330]
Hello
I have a new concox device TR02. Does not seem to accept GT02 port though.
Attached is the protocol
https://docs.google.com/file/d/1GX2fIbWCSn19Bo6Bs1ncNxSHcYxC70BXkUfIwGzabOxXHjyBCg2wRE-sdPPV/edit?usp=sharing

**Comment by shyamkishor** [comment]
I have Open GTS enterprise with few running device. and i want to integrate TR02. So i want Communication protocol for TR02. so if you have communication protocol for this. then please help me.

**Comment by tananaev** [comment]
You can find protocol documents here:

https://www.traccar.org/protocols/

Next time please don't comment on old closed threads. For questions like this use forum.
