### ISSUE TITLE
Предложение ввести обнаружение остановки  (формирование события, формирование границы поездки в отчете по поездкам)

### ISSUE THREAD

**Issue by barikinboxru** [traccar/traccar#3300]
Хотелось бы увидеть в последующих редакциях Вашего детища возможность добавления (может булев флаг) на формирование границы поездки при изменении статуса устройства (неизвестно, оффлайн). Также неплохо было бы чтобы была возможность формировать событие при отсутствии сигнала от устройства.

**Comment by tananaev** [comment]
Событие есть на неизвестный статус, что по сути тоже самое что отсутствие сигнала от устройства.

В следующей версии Traccar если есть разрыв данных в отчете, то это помечается как остановка. Немного не то что вы хотите, но близко.

**Comment by barikinboxru** [comment]
а когда будет следующая версия?

**Comment by tananaev** [comment]
Планируется выпустить через пару недель.
