### ISSUE TITLE
Can not create sql server database

### ISSUE THREAD

**Issue by zonhanoz09** [traccar/traccar#3311]
<entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
    <entry key='database.url'>jdbc:sqlserver://localhost;user=sa;password=123;databaseName=database;</entry>
    <entry key='database.user'>sa</entry>
    <entry key='database.password'>123</entry>

Replaced in conf file but not yet.

**Comment by condeitokako** [comment]
Check it well, you have bad your configuration.

https://www.traccar.org/ms-sql/

**Comment by zonhanoz09** [comment]
I tried changing but could not create the database

**Comment by zonhanoz09** [comment]
![image](https://user-images.githubusercontent.com/20008948/27758571-d3c426ea-5e41-11e7-90d3-e7947523e195.png)

**Comment by condeitokako** [comment]
Try to change the name of the database, and make sure you have the necessary permissions of the sa user.

**Comment by Turbovix** [comment]
Friend, Traccar does not create the database automatically, this you should do manually via mysql, PhpMyAdmin or mysql workbench commands!

**Comment by Turbovix** [comment]
https://www.traccar.org/forums/topic/mysql-connection-issue/

**Comment by condeitokako** [comment]
You just have to create the database manually, the tables create traccar automatically.

**Comment by zonhanoz09** [comment]
![image](https://user-images.githubusercontent.com/20008948/27758684-ef3ef9ec-5e44-11e7-80a6-cdc7f11cb72f.png)

I have created a database in sql server
But when accessing http: // localhost: 8082 / it is not connectable

**Comment by condeitokako** [comment]
Restart service (traccar) two

**Comment by zonhanoz09** [comment]
thanks. I did it

**Comment by condeitokako** [comment]
it works now?

**Comment by zonhanoz09** [comment]
![image](https://user-images.githubusercontent.com/20008948/27758712-38e9da16-5e46-11e7-87c4-8e0a3542b138.png)

**Comment by condeitokako** [comment]
Perfect if you want something visual give me a look at my system.
187.190.109.14
user: demodemo
pass: demodemo

regars.

**Comment by zonhanoz09** [comment]
I saw your system. Thank you for helping me

**Comment by condeitokako** [comment]
No problem, regards.

**Comment by lenble** [comment]
@zonhanoz09 Can you share your sql server database? I am also a beginner.谢谢lenble@163.com
