### ISSUE TITLE
Priority alarms

### ISSUE THREAD

**Issue by ghost** [traccar/traccar#3315]
How about @tananaev , I came up with the following problem, I hope you can help me.

I have approx 30 gps different models gun well all I have von sos panic button.

My problem is that when I send an activation of the button panic sos takes a lot, I imagine by the tail of all gps.

Now my question is the following, something can be done so that when a low battery alarm or another alarm has priority and you go first to the bd, and the alarm is sent faster.

Greetings.

**Comment by tananaev** [comment]
I have read your comment 3 times and I still don't understand what you are talking about and what the problem is.

**Comment by condeitokako** [comment]
Sorry the problem is :

The problem is the arrival queue of the alarms.

When I send an alarm activation and it is processed until 1 min delay.

**Comment by tananaev** [comment]
1. What kind of alarm?
2. What device are you using?
3. Are you using latest official release of Traccar?
4. Are you sure there are no problems with WebSocket connection?
5. What do you mean by "processed"?

**Comment by condeitokako** [comment]
1 sos, battery low, power cut.
2 gl200 and tk103
3 yes 
4 no problem, data receiver all devices
5 procesing data receiver the gps

If I receive the alarms but with a long time delay.

Example 1 or 2 min

I want to know if this can be fixed.

**Comment by tananaev** [comment]
What makes you think that the delay is on the server? Please provide some evidence.
