### ISSUE TITLE
Osmand Bug on Server 3.13

### ISSUE THREAD

**Issue by Cashe18** [traccar/traccar#3328]
Normally when you press on a device on the main console, Map rearranges to center picked device. Upgraded to 3.13 and offline Osmand devices do not rearrange map. you manually have to move around to see the arrow of location.

**Comment by tananaev** [comment]
Most likely the problem is not with OsmAnd protocol, but with attributes. Check browser console for errors.

**Comment by Cashe18** [comment]
I see no errors. Other browser doing same thing. Enclosed is a private link showing the bug in action. Hope it helps the team.

https://youtu.be/lSxExRxU8KU
Cp

Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by tananaev** [comment]
I don't see browser console on the video.

**Comment by Cashe18** [comment]
Will send scree shot when I get to computer. But mobile app(android) doing same thing. 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------
