### ISSUE TITLE
"watch" audio & websockets

### ISSUE THREAD

**Issue by stalien** [traccar/traccar#3335]
Здравствуйте, Антон! 
Установил последний traccar 3.13, протокол "watch". Как работает получение аудио файлов с устройства? Как я понял должен сохраняться файл .amr формата в папке ./media, но этого не происходит. В логах ошибок нет. По вебсокетам сразу после передачи сообщения с "устройства" приходит обновление positions c параметрами audio=20170710025911.amr  в attributes, но на сервере такого файла нет, в чем может быть проблема? 
Еще один вопрос, можно ли по вебсокетам получать не только обновления позиций и alarm'ы , но и отслеживать любые изменения данных, например создание/удаление devices или изменение в их настройках? Какая вообще логика формирования сообщений по вебсокетам?

**Comment by tananaev** [comment]
Если имя файла приходит в атрибутах, это означает что файл был создан. Попробуйте задать полный путь к папке `media.path` в конфигурационном файле.

**Comment by stalien** [comment]
Ок, спасибо. Помогло, файлы сохраняются в папке. Все же можно ли где-то почитать какие именно данные могут прилетать через websockets?

**Comment by tananaev** [comment]
Через WebSocket приходят следующие данные:

1. Devices (только обновление статуса)
2. Positions
3. Events

**Comment by zzheads** [comment]
Антон, писать в сокет можно? Если можно, то где глянуть формат?

**Comment by tananaev** [comment]
Нет, писать нельзя. Точнее можно, но сервер будет просто игнорировать эти данные.
