### ISSUE TITLE
Traccar server - server timeout and its effect on on device settings.

### ISSUE THREAD

**Issue by akmal1999** [traccar/traccar#3345]
Hi,

Currently our devices are configured as following:

![image](https://user-images.githubusercontent.com/22064319/28129999-80cf03b8-6703-11e7-8cd3-6c4c02a84162.png)

Is this a correct way of putting it in the traccar.xml?

![image](https://user-images.githubusercontent.com/22064319/28129926-3badcc88-6703-11e7-84ce-b121cd27486d.png)

if the above is a correct way of setting up will it resolve the problem of log file that grows upto 10 gb?  pic below:

![image](https://user-images.githubusercontent.com/22064319/28130101-cb8cbcc4-6703-11e7-9ee5-00a11555c714.png)

Your suggestion is highly appreciated.

**Comment by Turbovix** [comment]
Friend, you should refer to the device according to the example below, which I use for Suntech trackers.

<entry key='suntech.timeout'>600</entry>

**Comment by akmal1999** [comment]
Hi Turbovix,

Many thanks are you referring to the server hostname?

**Comment by akmal1999** [comment]
@Turbovix

**Comment by Turbovix** [comment]
Maybe I did not understand your problem.
The solution I've pointed out is to close the connections opened by the devices, that is, to decrease the use of the server resources.

**Comment by akmal1999** [comment]
You are actually correct.  I was referring to "suntech" is that the hostname of your server?

**Comment by tananaev** [comment]
@akmal1999, `server.timeout` should work fine if you are using a recent version of Traccar.

**Comment by akmal1999** [comment]
I am not trying to disconnect only one device with this rather I want the server to disconnect any device that is not active for 500 . meaning:

anydevice that is not active for 500 then then close it...  in your clause you have written "suntech" is this supposed to be my server hostname or .... the function       server.timeout refers to the server and should not be changed with another name like "suntech" or a host name.

**Comment by akmal1999** [comment]
@Turbovix

**Comment by akmal1999** [comment]
@tananaev  so the place i have chosen is correct
https://user-images.githubusercontent.com/22064319/28129926-3badcc88-6703-11e7-84ce-b121cd27486d.png

and also the way I have written it is correct.

if the above is correct then great.  One more question i brought in the table was our device is 300 is the 500 a good number to choose for this? is there an impact on other parameters?

**Comment by Turbovix** [comment]
@akmal1999 
Suntech is the brand of the tracking module, hence the name of the protocol.

**Comment by akmal1999** [comment]
@Turbovix I think then you are going device by device.  What I wanted to achieve is a wildcard for all the devices.

**Comment by tananaev** [comment]
Yes, it's correct. I would recommend to put it into `traccar.xml` file though, not `default.xml`. But both will work.

**Comment by akmal1999** [comment]
@Turbovix  @tananaev  Anton is correct.

**Comment by akmal1999** [comment]
@tananaev  I have placed that in the traccar.xml however, this traccar is based on 3.9 and vitaldize's version on top of it.

**Comment by akmal1999** [comment]
@tananaev is that going to work?

**Comment by tananaev** [comment]
It's not supported in 3.9. You should use 3.11 or higher.

**Comment by akmal1999** [comment]
oh ok. So an upgrade is required now.

**Comment by akmal1999** [comment]
thanks.
