### ISSUE TITLE
Get data from web to server 

### ISSUE THREAD

**Issue by neroshin** [traccar/traccar#3358]
Hello @tananaev I want to try to fetch the data of combobox from web to server. do you think it possible to do it? http://prntscr.com/fwjgg6

**Comment by tananaev** [comment]
It is definitely possible to do. Check extjs documentation for more info.

**Comment by neroshin** [comment]
okay @tananaev thank you ,I'll be use the selenium libraries for webelement.

**Comment by tananaev** [comment]
I thought Selenium is an automation framework. Also, I'm not sure how it's related to your original question which seems to be about ExtJS.
