### ISSUE TITLE
Enfora MT2500 Devices Drivers

### ISSUE THREAD

**Issue by richardramirez** [traccar/traccar#3361]
Hello everyone
 i have a couple **Enfora  MT2500** devices that should work with taccar . Unfortunately i don't have usb drivers for configuration. Company which sold them to me with their system don't want to cooperate (they stated they don't share drivers with third party). Novatel (producer) support is not reponding to my emails.

Maybe somebody here can share link to drivers. 

Best regards
G

**Comment by tananaev** [comment]
I would recommend to ask on forum. There is probably a better chance of getting reply there.

**Comment by richardramirez** [comment]
Can you point me to some forum? I cannot find any useful. 
All i get is some topics on typical xexun tk devices on cars forums.

**Comment by Turbovix** [comment]
https://www.traccar.org/forums/forum/

**Comment by tananaev** [comment]
Official Traccar forum:

https://www.traccar.org/forums/forum/devices/
