### ISSUE TITLE
Which protocol is this? I only get strange letters..

### ISSUE THREAD

**Issue by Hans5546** [traccar/traccar#3365]
Hello!

I got a new GPS tracker from Amazon.de (sold by a marketplace seller).

SMS-Link works with "smslink123456". Setting APN and IP works also.

The tracker is connected to my traccar server and is sending data like this;
```
78781f12110712080b1ac905a7*****
```
When I convert it, I get
```
xx...
```
I think, something it going wrong?

Can you identify the protocol or is it just nonsense? I already tried port 5000, 5001 and 5006 but it is not recognized,

Many thanks!

EDIT: Changed data to by anonym ;-)

**Comment by tananaev** [comment]
It's GT06 protocol, port 5023 in Traccar. It's a binary protocol, so you can't use hex decoder on it.

**Comment by Hans5546** [comment]
Hello!

Many thanks, the device is recognized now and I get the correct position :-)
