### ISSUE TITLE
Feature request: support for geocoding using Mapzen Search

### ISSUE THREAD

**Issue by drewda** [traccar/traccar#3367]
Please consider supporting geocoding using Mapzen Search, a hosted geocoder with a generous free tier. API documentation at: https://mapzen.com/documentation/search/reverse/

**Comment by tananaev** [comment]
As far as I understand their pricing is 50¢ per 1000 requests, which is exactly the same as Google. Google data quality is far superior in most areas though. Can you please explain the reasoning for using Mapzen API?

Their free tier is far from being generous. It gives you 25,000 requests/month for free. Google gives you 2,500 requests/day for free, which adds up to 75,000 requests/month. Some other providers give you even more. For example, LocationIQ gives 10,000 request/day for free.

**Comment by drewda** [comment]
If you haven't already noticed in my profile, I work at Mapzen. My main interest in offer this suggestion is to explore potential ways that Traccar and Mapzen services can integrate. Everything we do is open-source, so we're always on the look-out for other open-source projects to learn about or potentially integrate with.

Thanks for the feedback regarding Mapzen Search pricing. FWIW, Mapzen Search offers two advantages that may be relevant to some of your users:

- For users who outgrow the hosted Mapzen Search service (or who wish to control their own infrastructure), they can run the same service on their own infrastructure -- it's open-source: https://github.com/pelias/pelias

- Mapzen Search geocoding results (which come from OpenStreetMap, OpenAddresses, and other open data sources) can be stored and displayed on any vendors' maps. ([In contrast](https://developers.google.com/maps/documentation/geocoding/policies#map): "The Google Maps Geocoding API may only be used in conjunction with displaying results on a Google map. It is prohibited to use Google Maps Geocoding API data without displaying a Google map.")

**Comment by tananaev** [comment]
Google was provided as an example of the most expensive API out there. Other providers are cheaper and don't have limitations to use with specific map vendor.

How does hosted Mapzen Search service compare to other open source reverse geocoding solutions (e.g. Nominatim)? I'm especially interested in performance comparison.

So far the only the only possible reason I can see for using Mapzen is the case when client already uses Mapzen for some other reason. Then it makes sense to re-use the same instance/account.

**Comment by drewda** [comment]
A few ways that Mapzen Search/Pelias is different than other open-source geocoders:

- It's built on ElasticSearch, a search engine that provides many full-text search options, geographic indexing options, and distribution across multiple nodes. (In contrast, Nominatim use Postgres, which has more limited support for full-text search.)

- Its import pipeline is fast and flexible -- built in NodeJS. In addition to importing from OpenStreetMap, it can import from [OpenAddresses](https://openaddresses.io/) and [Who's on First](https://whosonfirst.mapzen.com/), among other sources of address and point-of-interest data.

- It's API is flexible -- also based on NodeJS -- and supports other methods besides reverse-geocoding. For example, it can support autocomplete, as users type in an address or landmark name. (Nominatim does not support autocomplete and the terms of the hosted version do not allow it.)

For more on Pelias, the open-source project that powers Mapzen Search, please do have a look at http://pelias.io/

**Comment by brendanyounger** [comment]
I would like to see a Mapzen integration.  The major difference for us is that Google Maps requires a premium plan for asset tracking which is US$10,000/year.  Mapzen allows us to pay for use without such a large upfront investment.

**Comment by tananaev** [comment]
As far as I know Mapzen uses OpenStreetMaps data, so I don't see much point. Am I missing something?

**Comment by tananaev** [comment]
Google Maps have changed their terms. It doesn't require premium plan now, as far as I know.

I'm going to close this for now, but if someone is interested in contributing the implementation, happy to accept it.
