### ISSUE TITLE
how to connect with Wetrack2 device from web server ?

### ISSUE THREAD

**Issue by ghost** [traccar/traccar#3376]
# #

**Comment by kirantpatil** [comment]
Hi, Please change the Title of the issue. You are adding description/question to Title, which is not appropriate.

Please refer other issues to understand how to provide proper Title.

**Comment by tananaev** [comment]
@ShubhamKadam141994, first of all, please don't spam everywhere with your question. If your question is not related to Traccar project, then it doesn't belong here.
