### ISSUE TITLE
Traccar 3.13 Api error get Positions

### ISSUE THREAD

**Issue by fabriziovirdis** [traccar/traccar#3390]
Hi,
if i use api for get positions for all device its ok, i i add parameter deviceId i have this error:
```
NullPointerException (... < DateUtil:64 < PositionResource:67 < ...)
```
Thank you

**Comment by Abyss777** [comment]
You have to set `from` and `to` parameters
https://github.com/tananaev/traccar/blob/master/swagger.json#L297

**Comment by fabriziovirdis** [comment]
oh no, what is the format form from and to?

**Comment by tananaev** [comment]
ISO format. You can check what official web app sends when you request reports.

**Comment by VigoKrumins** [comment]
Hey! I've the same issue. Installed fresh Traccar Server, everything worked fine with /api/positions to get all devices' current locations, but after the server restart, it asks for the date. So, after restart, API doesn't work without any params. Is it a bug or what? How to fix it? I've made a 3rd party application which uses /api/positions to get current location of vehicles. :?
