### ISSUE TITLE
device changed tlf number, but didnt come back on the map

### ISSUE THREAD

**Issue by zellditch78** [traccar/traccar#3394]
Hello tananaev, i have a chinese tk103a device, the device had a problem with the sim card and i change it for another one(diferrent number). i edited the device on ther server same imei but diferrent number. the server show on the device list the correct last connection time ~ 5 min. but the information like position speed etc dont show. Icon show in green!.... so i decided to delete the device and add it up again. same behavior just that this time no icon shown on the map, but yes (green) in the device list. did i do something wrong?

**Comment by tananaev** [comment]
Sounds like your device doesn't send any GPS information.
