### ISSUE TITLE
Current queclink devices event reporting

### ISSUE THREAD

**Issue by ckrey** [traccar/traccar#3400]
We are using a number of recent queclink devices with recent protocol versions
- GV65 (R6.03)
- GV65plus (R6.03)
- GV500 (R7.01)
- GMT200 (R2.01)

They all work will with traccar using the gl200 protocol.

However not all of the events delivered by the devices (e.g. MPN/MPF main power on/off) are recorded as either alarms nor events.

Some events (e.g. IGN/IGF for ignition on/off) are not reported as normal positions only, but not as events.

I will work to update the Gl200TextDecoder class.

@tananaev did you use older versions of the protocol specs or is the mapping of messages to events and alarms intentionally the way it is?

see #2359, #3196, #1408, #1151, #1983

**Comment by tananaev** [comment]
I don't think it was intentionally. When GL200 was implemented (many years ago) there were no events or notifications in Traccar. Since then we've modified protocol a few times mostly by requests from customer, but still not all of the message types are fully supported.

**Comment by daipayan-matrix** [comment]
I have a query, I had installed the Driver in my laptop. Added the Server FTP path and allowed the port in the server. But problem is no file is generated in the provided FTP. Am tried to search a lot but no where I find any sort of files with GPS data.

Am using GL50X @Track Air Interface Protocol R3.00

Anyone please guide me!

**Comment by tananaev** [comment]
I think we can close this for now. There were a lot of changes in the GL200 decoder. If someone want to contribute more, it's always welcome.
