### ISSUE TITLE
Accessing status attributes for eelink

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3413]
Tk116

Returned status is 8235  or 0010000000101011

KEY_BLOCKED should be true if I have read the protocol decode correctly. How would I access this as a custom attribute? Just 'blocked'? I always get error. 

Bit 0 seems not to be mapped to a key ie KEY_GPSPOS, it's possible that a unit could have different status value from the position status.

**Comment by tananaev** [comment]
You can find keys here:

[Position.java](https://github.com/tananaev/traccar/blob/master/src/org/traccar/model/Position.java)

**Comment by tsmgeek** [comment]
Thanks, I was referring to that class for the keys. But 'blocked' is never set for some reason.

Are these additional attributes stored in the position DB table?

**Comment by tananaev** [comment]
Yes, all additional attributes are stored in `attributes` column in JSON format.

**Comment by tsmgeek** [comment]
This is the data in my attributes column.
`{"index":147,"ignition":false,"status":8234,"battery":4.505,"rssi":14,"adc1":1264,"adc2":0,"distance":0.0,"totalDistance":0.0,"ip":"xxxxxx","motion":false,} `

https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/EelinkProtocolDecoder.java#L99-L113

You can see the status is recorded as per L112 but L106-107 should record the status of bits 5-6 which is 10 and that should mean 'blocked' on bit 6 or as the eelink specs say 'oil cut', this is what RELAY.1# toggles.

Should this not always be recorded in the attributes?

**Comment by tananaev** [comment]
It's only included if bit 5 is "1".

**Comment by tsmgeek** [comment]
That is correct, this is the status ID.

Dec: 8235 
Bin: 0010000000101011

Binary is a little rusty to me so I hope I am reading this correct.
The specs say to read this from low-high ie 15-0.

If that is the case using the BIN shown above, Bit5 is 1 and bit6 is 0.
Bit 0: is GPS status
Bit 1: ACC status available
Bit 2: ACC status
Bit 3: Armed status available
Bit 4: Armed status
Bit 5: Blocked status available
Bit 6: Blocked status <<<

**Comment by tananaev** [comment]
Your example looks correct, but you haven't provided full original message, so I'm not sure if you are looking at the correct field.

**Comment by tsmgeek** [comment]
Here is the 0x02 gps packet split, i have xxx the parts with GPS and GSM data, the <<< is the part i think.

6767
02
0025
01bd
xxxxxxxx
xxxxxxxx
xxxxxxxx
00
0000
xxxx xxxx xxxx xxxxxx
00
202b <<<
119c
000e
04f0
0000

**Comment by tananaev** [comment]
I need to see full original HEX. If you don't want to share it here, you can send me an email.

**Comment by tsmgeek** [comment]
sent you email with HEX for responses for all my tickets

**Comment by tawsif93** [comment]
@tsmgeek, I have recently bought a GPS device named tk116 but facing some issues with it. Can you help me to figure it out?

It continuously sending blank data to server and closing the connection but sms query woking fine. I’m struggling with this problem for a long time. Couldn’t find perfect solution.

**Comment by tsmgeek** [comment]
What makes you think it's blank?
If you see the same sequence serial number each time then it's normally because the device is not getting a reply from traccar so it keeps sending its buffer. 
Send VERSION? and post the result.

I posted updates to eelink protocol for newer firmware versions but it has not been merged in.

**Comment by tawsif93** [comment]
@tsmgeek I have tested using a php script to get the sent message but each time It sent blank message, continuously connecting and disconnecting. Even in traccar log there is a ERROR  for this device.

 `2017-10-05 16:45:54  INFO: [CD1F2F66] connected
2017-10-05 16:45:54  WARN: [CD1F2F66] error - Connection reset by peer - IOException (...)
2017-10-05 16:45:54  INFO: [CD1F2F66] disconnected
2017-10-05 16:45:54  INFO: [4E5288A4] connected
2017-10-05 16:45:54  WARN: [4E5288A4] error - Connection reset by peer - IOException (...)
2017-10-05 16:45:54  INFO: [4E5288A4] disconnected
2017-10-05 16:45:57  INFO: [06F21947] connected
2017-10-05 16:45:57  WARN: [06F21947] error - Connection reset by peer - IOException (...)
2017-10-05 16:45:57  INFO: [06F21947] disconnected
2017-10-05 16:45:59  INFO: [D38F0079] connected
2017-10-05 16:45:59  WARN: [D38F0079] error - Connection reset by peer - IOException (...)
2017-10-05 16:45:59  INFO: [D38F0079] disconnected`

VERSION Command reply: 
```
Imei:**** ********
Ver:M5216_V1.6.9
App:M5216_V1.6.9
Build:2012/10/22 12:52
Model:5201
```

**Comment by tsmgeek** [comment]
That is quite an old firmware build, my devices are using 2.0.2

Pull the log data from the traccar log for that device, ie HEX data.

**Comment by tjeerd13** [comment]
> 
> 
> That is correct, this is the status ID.
> 
> Dec: 8235
> Bin: 0010000000101011
> 
> Binary is a little rusty to me so I hope I am reading this correct.
> The specs say to read this from low-high ie 15-0.
> 
> If that is the case using the BIN shown above, Bit5 is 1 and bit6 is 0.
> Bit 0: is GPS status
> Bit 1: ACC status available
> Bit 2: ACC status
> Bit 3: Armed status available
> Bit 4: Armed status
> Bit 5: Blocked status available
> Bit 6: Blocked status <<<

Did you solve this problem? I have the same isue. Have devices with Eelink 1.9 protocol and Eelink 2.0 protocol.  They both send the same status value. (when i toggle  engine on/off)  Buth only the 1.9 version shows blocked true and false,
