### ISSUE TITLE
odometer / mileage

### ISSUE THREAD

**Issue by wopl** [traccar/traccar#3419]
I receive following string from my GPS-Tracker (no name, brand not known)
```
(087074966619BP05352887074966619170805A5053.9381N00716.2451E000.2200725000.0001000010L000450AB)
```
I assume its TK103 protocol (or similar?).
My issue: last characters "L000450AB" should represent odometer / mileage.
But they never change. All other values are valid.

Any idea?

**Comment by tananaev** [comment]
I think it's a common problem with TK103-based devices. I don't know if there is any solution other than relying on the server-side distance calculation.

**Comment by wopl** [comment]
Thanks for your answer. I'll continue to investigate. So I could wonder, if the device is communicating with the car (as all other parameters are from the tracker-device itself).
