### ISSUE TITLE
No admin privileges 

### ISSUE THREAD

**Issue by andi968** [traccar/traccar#3423]
For some reason I lost all my devices and admin privileges.
I am running Raspian on RPi 3 with no other problems, however I am now unable to re add my devices.
Where is the database file located so I can edit it accordingly and what do I need to do exactly once I find it ?
One concern is the RPi has sat behind the TV with no keyboard or mouse connected, where do I find the log to see if I have been remotely hacked?
Thanks in advance

**Comment by tsmgeek** [comment]
What DB are you using, should say in the traccar.conf file.
If mysql then look at your local instance.
If H2 I had to download the jar file and access it from the CLI to change admin flag on a user account (it was possable to remove admin access from the currently logged in account, I did it by mistake), was not too difficult.

**Comment by andi968** [comment]
Thanks, I am having great difficulty finding the file, can you point me in the right direction please.

**Comment by tananaev** [comment]
@andi968, I would recommend you to read documentation and search for existing discussions before asking any further questions. Please don't ask trivial questions like config file location. There is documentation for that. Study it first.

**Comment by andi968** [comment]
I am struggling here, the nature of GitHub is for like minded ppl to share their knowledge, I mentioned in the other post in regards to the possibility my system has been hacked. Nothing has been said to address that security  issue.
What may sound trivial you is not trivial to the person asking nor is the fact that devices are suddenly removed and admin privileges also removed when you consider people are using this to "protect" their assets and suddenly lose the ability to track and trace them.

**Comment by tananaev** [comment]
There are no logs that would show that you have been hacked.

**Comment by andi968** [comment]
That's a real shame, one of the pitfalls with open ports.
This is the first problem I have had since installing it on the RPi it has run for nearly 1,000 hours without issue, also using a gif gaff sim reporting back every 60sec it has only cost £0.55p !! I am so confident with the app I have cancelled my £169 a year subscription with Tracker UK 🇬🇧 
I am still having problems finding the config file, I have searched /opt/traccar folder and sub folders and still cannot find it, I have searched the site and web and cannot find its location referred to.
Will someone kindly put me out of my misery and share the location so I can get back up and running.

**Comment by tsmgeek** [comment]
**/opt/traccar/conf/traccar.xml** on my machine, not sure if the RPi version is any different.

Does RPi have the `locate` command ie `locate traccar.xml`?

As I have my own server, i run mine for myself and friends too. What tracking units are you using?

**Comment by andi968** [comment]
Thank you so much 😀
Command not found.
It helped when I selected show hidden files.
This is the unit https://www.amazon.co.uk/gp/product/B01DEZU55W/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1
Very impressed with build quality, plus the fact if you connect via USB you can edit all settings within notepad, ideal if you have a few to set up no need for countless SMS to configure

**Comment by tsmgeek** [comment]
I use very small TK116 units, just one SMS to point it to the server then all setup commands can be issued from traccar. I need small units to hide in a motorbike.

**Comment by andi968** [comment]
Yes. They look ideal where space is an issue, mine are in motorhome so easy to hide🤐
I am now back up and running, after a clean install I have also now made a backup image for the RPi so if anything goes wrong in the future again, I can quickly restore and save all the grief of today repeating itself.
