### ISSUE TITLE
Feature request: Engine status in Android app

### ISSUE THREAD

**Issue by jjanno** [traccar/traccar#3425]
Is it possible to use bluetooth connection status as engine status on Android?
Usecase: Phone connects to car bluetooth, when engine starts. Phone disconnects, when engine shuts down.
Would like to do some filtering based on engine status afterwards. I'm using mysql and would probably delete all entries that are older than a day and engine is off.

**Comment by tsmgeek** [comment]
I would say this should be additional fields, not exactly engine status.

But you would need to define a specific bluetooth device to report if connected and then use that to either populate a custom param or predefined flags.

**Comment by tsmgeek** [comment]
Anyway should this not be posted to...
https://github.com/tananaev/traccar-client-android
https://github.com/tananaev/traccar-client-ios

**Comment by tananaev** [comment]
@jjanno, I don't think we would add a feature like that to the official version, but it's possible to make a custom build. Send me an email if you are interested.

**Comment by tananaev** [comment]
Closing as this belongs to Traccar Client.
