### ISSUE TITLE
Traccar service is not starting

### ISSUE THREAD

**Issue by srinivasacharymusalogu** [traccar/traccar#3427]
I have installed Traccar on AWS. I have configured mysql on AWS RDS service. It was working fine.
Due to some issue I have not paid bill of AWS. They have de activated my services. After that I have paid bill but RDS was deleted. AWS told to restore from Snapshot. I have restored but not it is not working. 
Can you please help me to solve this. 

Below are the message I am getting:
```
INFO|wrapper|Service traccar|17-08-08 16:10:37|posix_spawn pid 1629
INFO|wrapper|Service traccar|17-08-08 16:10:37|started process 1629
INFO|wrapper|Service traccar|17-08-08 16:10:37|started process with pid 1629
INFO|1629/0|Service traccar|17-08-08 16:10:38|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|1629/0|Service traccar|17-08-08 16:10:39|java.lang.reflect.InvocationTargetException
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at java.lang.reflect.Method.invoke(Method.java:498)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|1629/0|Service traccar|17-08-08 16:10:39|Caused by: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 293; columnNumber: 2; The content of elements must consist of well-formed character data or markup.
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:80)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at java.util.Properties$XmlSupport.load(Properties.java:1201)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at java.util.Properties.loadFromXML(Properties.java:881)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at org.traccar.Config.load(Config.java:37)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at org.traccar.Context.init(Context.java:186)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at org.traccar.Main.main(Main.java:35)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  ... 6 more
INFO|1629/0|Service traccar|17-08-08 16:10:39|Caused by: org.xml.sax.SAXParseException; lineNumber: 293; columnNumber: 2; The content of elements must consist of well-formed character data or markup.
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.startOfMarkup(XMLDocumentFragmentScannerImpl.java:2635)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2732)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(PlatformXmlPropertiesProvider.java:106)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:78)
INFO|1629/0|Service traccar|17-08-08 16:10:39|  ... 11 more
INFO|wrapper|Service traccar|17-08-08 16:10:39|waitpid 1629 59136
INFO|wrapper|Service traccar|17-08-08 16:10:39|exit code posix process: 59136 application: 0
```

**Comment by tsmgeek** [comment]
Have you changed your traccar.xml file recently? ie to change db info?

**Comment by srinivasacharymusalogu** [comment]
In the process of troubleshooting, I have executed traccar.run once and then edited back to old configuration of traccar.xml and default.xml. Using command line I am able to connect to AWS RDS mysql server.

**Comment by tsmgeek** [comment]
you should not need to change default.xml, only traccar.xml with the options you need.
The log says SAX Parser error which to me indicates XML formatting error.

**Comment by srinivasacharymusalogu** [comment]
I have backup of default.xml. shell I restore that?

**Comment by srinivasacharymusalogu** [comment]
ubuntu@India2go:/opt/traccar/conf$ sudo service traccar restart
ubuntu@India2go:/opt/traccar/conf$ tail -f /var/log/syslog
Aug  8 17:21:38 India2go traccar[1913]: Aug 08, 2017 5:21:38 PM org.rzo.yajsw.os                                                                                                                                                    .posix.PosixService startProcess
Aug  8 17:21:38 India2go traccar[1913]: INFO: calling java -Dwrapper.pidfile=/ru                                                                                                                                                    n/wrapper.traccar.pid -Dwrapper.service=true -Dwrapper.visible=false -Djna_tmpdi                                                                                                                                                    r=/opt/traccar/tmp -jar /opt/traccar/wrapper.jar -c /opt/traccar/conf/wrapper.co                                                                                                                                                    nf
Aug  8 17:21:38 India2go traccar[1913]: Aug 08, 2017 5:21:38 PM org.rzo.yajsw.os                                                                                                                                                    .posix.PosixService getPid
Aug  8 17:21:38 India2go traccar[1913]: INFO: wrapper pid file: /run/wrapper.tra                                                                                                                                                    ccar.pid
Aug  8 17:21:40 India2go traccar[1913]: Aug 08, 2017 5:21:40 PM org.rzo.yajsw.os                                                                                                                                                    .posix.PosixService getPid
Aug  8 17:21:40 India2go traccar[1913]: INFO: wrapper pid file: /run/wrapper.tra                                                                                                                                                    ccar.pid
Aug  8 17:21:40 India2go traccar[1913]: Aug 08, 2017 5:21:40 PM org.rzo.yajsw.os                                                                                                                                                    .posix.PosixService getPid
Aug  8 17:21:40 India2go traccar[1913]: INFO: wrapper pid file: /run/wrapper.tra                                                                                                                                                    ccar.pid
Aug  8 17:21:40 India2go traccar[1913]: Service traccar started
Aug  8 17:21:40 India2go systemd[1]: Started LSB: yajsw wrapper for Traccar.
Aug  8 17:21:51 India2go traccar[1996]: Stopping traccar ...
Aug  8 17:21:51 India2go traccar[1996]: YAJSW: yajsw-stable-12.08
Aug  8 17:21:51 India2go traccar[1996]: OS   : Linux/4.4.0-89-generic/amd64
Aug  8 17:21:51 India2go traccar[1996]: JVM  : Oracle Corporation/1.8.0_131//usr                                                                                                                                                    /lib/jvm/java-8-openjdk-amd64/jre/64
Aug  8 17:21:52 India2go traccar[1996]: Aug 08, 2017 5:21:52 PM org.apache.commo                                                                                                                                                    ns.vfs2.VfsLog info
Aug  8 17:21:52 India2go traccar[1996]: INFO: Using "/tmp/vfs_cache" as temporar                                                                                                                                                    y files store.
Aug  8 17:21:52 India2go traccar[1996]: Aug 08, 2017 5:21:52 PM org.rzo.yajsw.os                                                                                                                                                    .posix.PosixService init
Aug  8 17:21:52 India2go traccar[1996]: INFO: /etc/init.d/traccar already exists
Aug  8 17:21:52 India2go traccar[1996]: ************* STOPPING traccar *********                                                                                                                                                    **************
Aug  8 17:21:52 India2go traccar[1996]: Aug 08, 2017 5:21:52 PM org.rzo.yajsw.os                                                                                                                                                    .posix.PosixService getPid
Aug  8 17:21:52 India2go traccar[1996]: INFO: wrapper pid file: /run/wrapper.tra                                                                                                                                                    ccar.pid
Aug  8 17:21:52 India2go traccar[1996]: Aug 08, 2017 5:21:52 PM org.rzo.yajsw.os                                                                                                                                                    .posix.PosixService stopProcess
Aug  8 17:21:52 India2go traccar[1996]: INFO: stop daemon with pid 1929
Aug  8 17:21:52 India2go traccar[1996]: Aug 08, 2017 5:21:52 PM org.rzo.yajsw.os                                                                                                                                                    .posix.PosixService stopProcess
Aug  8 17:21:52 India2go traccar[1996]: INFO: process not running
Aug  8 17:21:52 India2go traccar[1996]: Aug 08, 2017 5:21:52 PM org.rzo.yajsw.os                                                                                                                                                    .posix.PosixService getPid
Aug  8 17:21:52 India2go traccar[1996]: INFO: wrapper pid file: /run/wrapper.tra                                                                                                                                                    ccar.pid
Aug  8 17:21:52 India2go traccar[1996]: Service traccar stopped

**Comment by srinivasacharymusalogu** [comment]
I have restored default.xml but not able to start service.

**Comment by tsmgeek** [comment]
look at the traccar-server.log and wrapper log files, may give more info.

**Comment by srinivasacharymusalogu** [comment]
traccar-server.log output
------------------------------------------------------------------------------------------------------

-2017-08-08 15:41:48  INFO: Shutting down server...
2017-08-08 15:41:48  INFO: [08A5B2B9] disconnected
2017-08-08 15:41:48  INFO: [4B2DCCE5] disconnected
2017-08-08 17:21:41  INFO: Operating system name: Linux version: 4.4.0-89-generic architecture: amd64
2017-08-08 17:21:41  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 25.131-b11
2017-08-08 17:21:41  INFO: Memory limit heap: 239mb non-heap: 0mb
2017-08-08 17:21:41  INFO: Character encoding: UTF-8 charset: UTF-8
2017-08-08 17:21:41  INFO: Version: 3.10-SNAPSHOT

**Comment by srinivasacharymusalogu** [comment]
wrapper.log --- output
-------------------------
INFO|wrapper|Service traccar|17-08-08 17:21:39|posix_spawn pid 1945
INFO|wrapper|Service traccar|17-08-08 17:21:39|started process 1945
INFO|wrapper|Service traccar|17-08-08 17:21:39|started process with pid 1945
INFO|1945/0|Service traccar|17-08-08 17:21:40|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|1945/0|Service traccar|17-08-08 17:21:41|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
INFO|1945/0|Service traccar|17-08-08 17:21:42|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
INFO|1945/0|Service traccar|17-08-08 17:21:42|INFO 8/8/17 5:21 PM: liquibase: Clearing database change log checksums
INFO|1945/0|Service traccar|17-08-08 17:21:43|INFO 8/8/17 5:21 PM: liquibase: Successfully acquired change log lock
INFO|1945/0|Service traccar|17-08-08 17:21:43|INFO 8/8/17 5:21 PM: liquibase: Creating database history table with name: TraccarDB.DATABASECHANGELOG
INFO|1945/0|Service traccar|17-08-08 17:21:43|INFO 8/8/17 5:21 PM: liquibase: Successfully released change log lock
INFO|1945/0|Service traccar|17-08-08 17:21:43|INFO 8/8/17 5:21 PM: liquibase: Successfully acquired change log lock
INFO|1945/0|Service traccar|17-08-08 17:21:44|Failed to generate a seed from SecureRandom within {} seconds. Not enough entrophy?
INFO|1945/0|Service traccar|17-08-08 17:21:44|3
INFO|1945/0|Service traccar|17-08-08 17:21:45|INFO 8/8/17 5:21 PM: liquibase: Reading from TraccarDB.DATABASECHANGELOG
INFO|1945/0|Service traccar|17-08-08 17:21:45|SEVERE 8/8/17 5:21 PM: liquibase: ./schema/changelog-master.xml: changelog-3.3::changelog-3.3::author: Change Set changelog-3.3::changelog-3.3::author failed.  Error: Table 'users' already exists [Failed SQL: CREATE TABLE TraccarDB.users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(128) NOT NULL, email VARCHAR(128) NOT NULL, hashedpassword VARCHAR(128) NOT NULL, salt VARCHAR(128) NOT NULL, readonly BIT(1) DEFAULT 0 NOT NULL, admin BIT(1) DEFAULT 0 NOT NULL, map VARCHAR(128) DEFAULT 'osm' NOT NULL, language VARCHAR(128) DEFAULT 'en' NOT NULL, distanceunit VARCHAR(128) DEFAULT 'km' NOT NULL, speedunit VARCHAR(128) DEFAULT 'kmh' NOT NULL, latitude DOUBLE DEFAULT 0 NOT NULL, longitude DOUBLE DEFAULT 0 NOT NULL, zoom INT DEFAULT 0 NOT NULL, CONSTRAINT PK_USERS PRIMARY KEY (id))]
INFO|1945/0|Service traccar|17-08-08 17:21:45|INFO 8/8/17 5:21 PM: liquibase: changelog-3.3::changelog-3.3::author: Successfully released change log lock
INFO|1945/0|Service traccar|17-08-08 17:21:45|java.lang.reflect.InvocationTargetException
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at java.lang.reflect.Method.invoke(Method.java:498)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|1945/0|Service traccar|17-08-08 17:21:45|Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set changelog-3.3::changelog-3.3::author:
INFO|1945/0|Service traccar|17-08-08 17:21:45|     Reason: liquibase.exception.DatabaseException: Table 'users' already exists [Failed SQL: CREATE TABLE TraccarDB.users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(128) NOT NULL, email VARCHAR(128) NOT NULL, hashedpassword VARCHAR(128) NOT NULL, salt VARCHAR(128) NOT NULL, readonly BIT(1) DEFAULT 0 NOT NULL, admin BIT(1) DEFAULT 0 NOT NULL, map VARCHAR(128) DEFAULT 'osm' NOT NULL, language VARCHAR(128) DEFAULT 'en' NOT NULL, distanceunit VARCHAR(128) DEFAULT 'km' NOT NULL, speedunit VARCHAR(128) DEFAULT 'kmh' NOT NULL, latitude DOUBLE DEFAULT 0 NOT NULL, longitude DOUBLE DEFAULT 0 NOT NULL, zoom INT DEFAULT 0 NOT NULL, CONSTRAINT PK_USERS PRIMARY KEY (id))]
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.Liquibase.update(Liquibase.java:214)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.Liquibase.update(Liquibase.java:192)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.Liquibase.update(Liquibase.java:188)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:145)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at org.traccar.database.DataManager.<init>(DataManager.java:71)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at org.traccar.Context.init(Context.java:198)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at org.traccar.Main.main(Main.java:35)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  ... 6 more
INFO|1945/0|Service traccar|17-08-08 17:21:45|Caused by: liquibase.exception.DatabaseException: Table 'users' already exists [Failed SQL: CREATE TABLE TraccarDB.users (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(128) NOT NULL, email VARCHAR(128) NOT NULL, hashedpassword VARCHAR(128) NOT NULL, salt VARCHAR(128) NOT NULL, readonly BIT(1) DEFAULT 0 NOT NULL, admin BIT(1) DEFAULT 0 NOT NULL, map VARCHAR(128) DEFAULT 'osm' NOT NULL, language VARCHAR(128) DEFAULT 'en' NOT NULL, distanceunit VARCHAR(128) DEFAULT 'km' NOT NULL, speedunit VARCHAR(128) DEFAULT 'kmh' NOT NULL, latitude DOUBLE DEFAULT 0 NOT NULL, longitude DOUBLE DEFAULT 0 NOT NULL, zoom INT DEFAULT 0 NOT NULL, CONSTRAINT PK_USERS PRIMARY KEY (id))]
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:309)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  ... 15 more
INFO|1945/0|Service traccar|17-08-08 17:21:45|Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'users' already exists
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at com.mysql.jdbc.Util.getInstance(Util.java:408)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:307)
INFO|1945/0|Service traccar|17-08-08 17:21:45|  ... 20 more
INFO|wrapper|Service traccar|17-08-08 17:21:45|waitpid 1945 59136
INFO|wrapper|Service traccar|17-08-08 17:21:45|exit code posix process: 59136 application: 0

**Comment by tsmgeek** [comment]
Seems its trying to create the tables again in your DB but they already exist.

**Comment by srinivasacharymusalogu** [comment]
how to fix this now?. I have already restored old back default.xml file.

**Comment by tsmgeek** [comment]
Are you sure your DB was restored correctly.
There should be a table DATABASECHANGELOG which handles the schema, I guess that if thats not there it assumes the DB has not been created and will run all the schema updates.

**Comment by srinivasacharymusalogu** [comment]
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| TraccarDB          |
| innodb             |
| mysql              |
| performance_schema |
| sys                |
| tmp                |
+--------------------+
7 rows in set (0.01 sec)

mysql>

**Comment by srinivasacharymusalogu** [comment]
mysql> show tables;
+------------------------+
| Tables_in_TraccarDB    |
+------------------------+
| DATABASECHANGELOG      |
| DATABASECHANGELOGLOCK  |
| application_settings   |
| device_icons           |
| devices                |
| devices_geofences      |
| events                 |
| geofences              |
| groups                 |
| groups_users           |
| maintenances           |
| notification_settings  |
| notification_templates |
| pictures               |
| positions              |
| reports                |
| reports_devices        |
| reports_geofences      |
| reports_users          |
| sensors                |
| ui_state               |
| user_settings          |
| users                  |
| users_devices          |
| users_geofences        |
| users_notifications    |
+------------------------+
26 rows in set (0.00 sec)

mysql>

**Comment by srinivasacharymusalogu** [comment]
I am able to see this DB log file.

**Comment by tsmgeek** [comment]
Show all the rows in DATABASECHANGELOG table and also list contents of the traccar/schema directory what version you are using.

**Comment by srinivasacharymusalogu** [comment]
mysql> select * from DATABASECHANGELOG;
Empty set (0.00 sec)

mysql> select * from DATABASECHANGELOGLOCK;
+----+--------+-------------+----------+
| ID | LOCKED | LOCKGRANTED | LOCKEDBY |
+----+--------+-------------+----------+
|  1 |        | NULL        | NULL     |
+----+--------+-------------+----------+
1 row in set (0.00 sec)

mysql>

**Comment by srinivasacharymusalogu** [comment]
total 56
drwxr-xr-x  2 root root 4096 Feb 15 11:59 ./
drwxr-xr-x 11 root root 4096 Feb 15 17:29 ../
-rw-r--r--  1 root root 4312 Aug  8 07:38 changelog-3.10.xml
-rw-r--r--  1 root root 7346 Aug  8 07:38 changelog-3.3.xml
-rw-r--r--  1 root root 2803 Aug  8 07:38 changelog-3.5.xml
-rw-r--r--  1 root root 4927 Aug  8 07:38 changelog-3.6.xml
-rw-r--r--  1 root root 1833 Aug  8 07:38 changelog-3.7.xml
-rw-r--r--  1 root root 5507 Aug  8 07:38 changelog-3.8.xml
-rw-r--r--  1 root root 1286 Aug  8 07:38 changelog-3.9.xml
-rw-r--r--  1 root root  836 Aug  8 07:38 changelog-master.xml

**Comment by tsmgeek** [comment]
Found your answer there, the DATABASECHANGELOG table is empty without this the system thinks that its new and will try setting up all the tables again.

Are your other tables empty too (check devices)? Is it possable they only restored the schema and not the actual data?

**Comment by srinivasacharymusalogu** [comment]
| 325192          | NULL                   |        1 |    NULL |           1803552 |        1 |     NULL |
+----+--------------------+-------------+----------------------+-----------------------+----------------------+-----------------+-----------------------+----------+--------------+-----------+--------------------+---------------------+-------------+------------------+--------------------+-------------+---------------------+----------+--------------+--------------+-------------------+--------+---------+-----------------+------------------------+----------+---------+-------------------+----------+----------+
12 rows in set (0.02 sec)

**Comment by srinivasacharymusalogu** [comment]
I see devices

**Comment by srinivasacharymusalogu** [comment]
I see users also

**Comment by srinivasacharymusalogu** [comment]
Shell I create parallel database and check. I can change database name in traccar.xml file.

**Comment by gulsal123** [comment]
Hello sir...sir how to configure traccar server 2.11 in my web site...coz I am beginner so please help me sir
