### ISSUE TITLE
Unable to add same device to 2nd account

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3428]
Issue trying to add same device to 2nd account.
```
Unique index or primary key violation: "UK_DEVICE_UNIQUEID_INDEX_B ON PUBLIC.DEVICES(UNIQUEID) VALUES ('12345', 31)"; SQL statement:
INSERT INTO devices (model, category, name, groupId, uniqueId, attributes, contact, lastUpdate, phone) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-196] - JdbcSQLException (... < QueryBuilder:477 < DataManager:455 < BaseObjectManager:87 < ...)
```

**Comment by tananaev** [comment]
Obviously you can't add two device with same UNIQUE id. You need admin to share original device with both users.

**Comment by tananaev** [comment]
I think the message is pretty clear.

**Comment by tsmgeek** [comment]
It may be clear but cant be handled nicely with JSON over API. Should not be exposing this out on an API.
On some apps I develop at work we do the following, in debug mode a catchable exception such as unique constraint is pushed out in separate variable but live this goes to log.
Really a check if device already exists can be done before system tries to put it in the DB and just return a sane message.

> {
>   success:false,
>   message:"Can not create as already exists",
>   debugMessage:"TRACE message"
> }

**Comment by tananaev** [comment]
In general I agree that it would be nice to have better error messages, but if we fix it, we need to fix them all. There are hundreds of possible exception conditions, not just this one.

As for checking before calling database, yes it's possible, but why would you duplicate the logic? It's never a good idea.

**Comment by tsmgeek** [comment]
Fixes have to start somewhere unfortunately, im trying to refactor a very large DAM system and CMS at work to use S3 backend its a PITA but after the pain things get easier.

Easy to handle on the front-end though during the transition, if return is json then handle it one way if string handle it the current way.

**Comment by tananaev** [comment]
Fixes like this should start with clear understanding of how we are going to fix the whole system. We don't have to do it in one go, but I don't think randomly fixing it one by one is a good idea. We need a clear and consistent approach.
