### ISSUE TITLE
Mail template or unknown.vm Can't find

### ISSUE THREAD

**Issue by addonravi** [traccar/traccar#3429]
Hi,
Here is exception 
```
Exception in thread "Thread-13" org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource './templates/mail/unknown.vm'
```

I have defined the path in default.xml file like "<entry key="mail.templatesPath">./templates/mail</entry>"
but never get the template 

please help me if i m missing something then

Thanks,

**Comment by tananaev** [comment]
The error is pretty self-explanatory. What parameter did you define exactly?

**Comment by addonravi** [comment]
In existing traccar i have just put path in config file 
like  in default.xml
<entry key="mail.templatesPath">./templates/mail</entry>

**Comment by tananaev** [comment]
That's wrong configuration. Parameter that you have set should point to a subfolder inside `templates.rootPath`, so I don't see any good reason for you to specify it.

**Comment by jon-stumpf** [comment]
@addonravi I made the same mistake.

**Comment by addonravi** [comment]
Now resolved. 
Thanks

**Comment by tananaev** [comment]
I believe we recently simplified this configuration.
