### ISSUE TITLE
Updating Timezone of GT06 via tcp

### ISSUE THREAD

**Issue by jkhasiza** [traccar/traccar#3432]
We've GT06 and Wetrack2 devices with us. Is there any way to set the timezone of device via server during tcp connection?

Thanks in advance

**Comment by jaimzj** [comment]
@jkhasiza yes you can use the same command that you send via SMS, through Traccar by using the command->Custom Command option.

**Comment by tsmgeek** [comment]
If all GT06 protocol devices can support this in the same syntax then the commands function can be enabled with the special timezone method rather than reverting to SMS commands. Would be easier.
