### ISSUE TITLE
Attributes not binding to Devices when created from UI

### ISSUE THREAD

**Issue by sudalwar** [traccar/traccar#3433]
Hey there,
I have been trying to create devices from my application connecting to the traccar api - I am able to create the device instance however, the attributes are not binding to the device. When I switch on the service status - ideally the position of the device should be updated but it does not have any call.

Could you please help at the earliest?
![capture](https://user-images.githubusercontent.com/30466330/29178501-5ea26186-7e0f-11e7-8308-a2f384d3a1dc.JPG)

**Comment by tsmgeek** [comment]
Look at your traccar-server log file to see if its being identified correctly (ie the IMEI is not truncated, port number is correct for device type);

**Comment by sudalwar** [comment]
Thank you for responding quick. 

Yes - everything seems to be alright with the device. It is not reflecting only for those devices created dynamically through my website. If I manually create a device through the api and turn on the switch from my phone, all the attributes are set as expected.

I need the position to be updated with the positionid, lat and longs for displaying the markers.

**Comment by sudalwar** [comment]
Would the positionid be generated only after turning the switch on in the device ? and when would inturn update the device with the position id ? how can I trigger put operation on creation of the positionid to update the device - since we dont have the post method for position?

**Comment by tsmgeek** [comment]
The device id probably does not match what you entered when you created the device though the API.

In the API uniqueId should match the ID you device is sending in its update packets.

Are you using Traccar Client on the phone?

**Comment by sudalwar** [comment]
All those parameters are matching and yes, I am using Traccar client on my phone

**Comment by tsmgeek** [comment]
As long as the client app is running you should see the updates show up in traccar-server log.

`2017-08-10 19:09:44  INFO: [32ABD553] id: 123456, time: 2017-08-10 19:09:43, lat: 51.0000, lon: -0.0000, speed: 0.0, course: 0.0`

If you see this and no device unknown lines then it will be logging the position in the DB, should not be anything else you need to do. If id does not match what is setup then you will not see anything.

**Comment by sudalwar** [comment]
For creating the device instance - the body has to be passed as the parameter.. could you please let me know the default values that should be set for the a device to be created? 

I am currently passing group id, name and device id - rest of the other body parameters are going null including the attributes and georeferences. The positionid is defaulting to 0.

**Comment by sudalwar** [comment]
{"id":0,"attributes":null,"name":"sudalwar","uniqueId":"000010002011","status":null,"lastUpdate":null,"positionId":null,"groupId":3315,"geofenceIds":null,"phone":null,"model":null,"contact":null,"category":null}

**Comment by tsmgeek** [comment]
There is API doca on the main traccar site.

**Comment by sudalwar** [comment]
{"id":0,"attributes":{"Protocol" : "", "Longitude": "", "Latitude": ""},"name":"Josh Fork","uniqueId":"000010002011","status":null,"lastUpdate":null,"positionId":null,"groupId":3315,"geofenceIds":null,"phone":null,"model":null,"contact":null,"category":null}


I managed to resolve it - attributes were setting to null - so created nulls against the sub properties of attributes. I hope this is the right way.

**Comment by tananaev** [comment]
This doesn't seem right. Why would you add those attributes to the device?

**Comment by sudalwar** [comment]
There is an attribute property against the devices - if that is set to null - none of the attributes are set when the position is triggered.

**Comment by tananaev** [comment]
There are attributes on all object types. Device attributes have nothing to do with Position attributes.
