### ISSUE TITLE
Windows vs Lunix Hosting service benchmarking ?

### ISSUE THREAD

**Issue by AymanElarian** [traccar/traccar#3434]
Hello , i am deploying the a new upgrade for my infrastructure   i am just confusing about keep windows hosting for data service (traccar ) or move it to linux 

so any benchmarking about windows/linux  for same hardware ?

**Comment by tsmgeek** [comment]
Personally linux for me all the time for this type of stuff, much less overhead.
I do not see any reason windows is needed unless you are going to do specific modules in the java code to interact with it, most things can be done via API or accessing the DB directly to pull data if needed.

**Comment by AymanElarian** [comment]
it connect to sql server , i think linux will be slower here ?

**Comment by tsmgeek** [comment]
Not really, use mysql server is fast.

**Comment by tananaev** [comment]
Linux will definitely be faster with the same hardware specs. For one thing the OS itself uses less resources.
