### ISSUE TITLE
Extension to OsmAnd protocol

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3438]
Proposal to add extension to the protocol for traccar to support secure signed updates. 
This is not to secure the data as that is where SSL can be used but rather add some assurance that the track is authentic and the data has not been tampered in transit.

1. define attribute with a private key
2. track comes in, check if device config defines that it needs to be signed
3. if track is signed then add to DB, if not then ignore completely and do not even update device last update
4. track can be validated that signature is within time frame for added security (devices should have correct time)

Method of signing similar to AWS v2.
Auth to be passed via HTTP header Authorization (would not show in logs) or via query string.

1. Add timestamp to query string
2. sort query string keys alphabetically
3. concatenate query string
4. HMAC string with private key
5. add resulting signature to query string in request or add signature to Authorization header with timestamp.

**Comment by tananaev** [comment]
HTTPS supports client certificate validation, so I don't think it makes sense to invent a custom solution for it.

**Comment by tsmgeek** [comment]
More hassle to set that up for most people plus would need https running.
This is compatible with all and protects.

Why propose a harder system for people to work with when this is tried and
tested?

**Comment by SebastEnn** [comment]
OsmAnd protocol extension didn't got approved. Issue can be closed.
