### ISSUE TITLE
DB optimisation column types

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3441]
What would be the best way to make DB optimisations that would alter datatypes right back to the first changelog.

There is lots of uses of `INT` instead of `INT UNSIGNED` and a few other things

I am thinking to change all the `createTable` statements in all the changelogs first then create a new changelog that will correct column types if they are not already that type, seems that it may end up being a big change due to foreign key constraints.

**Comment by tananaev** [comment]
I would recommend to discuss changes before making them. For example `UNSIGNED` doesn't make sense because Java doesn't have unsigned data types.

**Comment by tsmgeek** [comment]
That is fine, internally in java if needed use `long` but for the DB UserID/DeviceID/PositionID could all be unsigned INT. Gives more headroom for MySQL db before having to move to bigint.

`timestamps` should be set as `datetime`, for MySQL timestamp field will change values automatically if a user was to change something in the DB or a changelog was to say update a value during a migration the column will get new timestamp.

**Comment by tananaev** [comment]
I'm not sure how you are planning to change id data type. I don't think it makes sense until we actually encounter any problems.

You can specify behaviour for timestamp. The reason we use timestamp is that it's a standard SQL data type supported by most/all databases. So, I don't see any reason for switch either.

**Comment by tsmgeek** [comment]
Liquibase should handle the timestamp vs datetime issue for different databases, I had a quick look of the datatype code and it seems they do some switching to timestamp when a DB does not specifically support datetime.

> By default, the first TIMESTAMP column has both DEFAULT CURRENT_TIMESTAMP and ON UPDATE CURRENT_TIMESTAMP if neither is specified explicitly.

**Comment by tananaev** [comment]
I agree with changing timestamp to datetime, but I'm not sure if we should change it for events and positions. It would create issues for during upgrade.

**Comment by tsmgeek** [comment]
Change it in the createTables so that new installs are all correct.
I agree for large installs the upgrade could cause issues, timeouts etc, this could be done via a separate upgrade script if user wants to run it from tools directory.

**Comment by tananaev** [comment]
No, we never modify changelog history. It's a wrong approach.

**Comment by tsmgeek** [comment]
The createTables will never be run again so i think its a valid approach in this instance, but if you incorporate it as a column change in a new schema it would be applied to existing installs as far as I am aware which is not a good idea (unless there is a way to prevent that) and only do it on initial setup.

**Comment by tananaev** [comment]
You are trying to fix one problem by introducing another one. That's not an option.

**Comment by tsmgeek** [comment]
This seems to be the way to correct the problem.

> ##Original Change Set was Wrong or Buggy
> There are times when a change that was created wrong, especially if you are using the `<sql>` tag and have a complicated statement. When you catch the problem, you are often not able to recover original data or structures, but want the change to be correct for new databases going forward. In this case, it is best to use add a `<validCheckSum>` tag to the changeSet specifying that the new check sum is correct. To know the check sum to specify, simply make your change and try to update a database. The resulting verification error will include the new check sum.

**Comment by tananaev** [comment]
Sorry, but I don't see how it's relevant to what we are discussing.

**Comment by tananaev** [comment]
They are talking about very specific case:

> ... you are often not able to recover original data or structures ... In this case ...

**Comment by tsmgeek** [comment]
That is one example they have given, another would be this case. Its not as if we are moving from datetime to int for timestamps, the change is transparent to the app.

**Comment by tananaev** [comment]
OK, what if we decide to rename the column later? How would you do it after your change?

**Comment by tsmgeek** [comment]
For a rename it would be done via  `<renameColumn/>` in a new changelog.

**Comment by tananaev** [comment]
Yes, obviously, but it requires `columnDataType`.

**Comment by tsmgeek** [comment]
What are the chances that the datetime fields in question will be renamed?
I think it is fairly slim due to their nature, if that was to happen then go with the new data type.
There is a point where you just cant get away from a major DB alter statement, online DDL can do lots but not all.
With old mysql databases you could even get into a problem where the timestamp format is old and any change on the table would end up rebuilding it all anyway and there is nothing you can do about that as it depends on mysql version.
