### ISSUE TITLE
Event forwarding type sent as NULL

### ISSUE THREAD

**Issue by kedarnathjimage** [traccar/traccar#3459]
hi tananaev,

I have forwarded event via config file.  In response we are not getting event type. Kindly  check the below  response:

Config file code:
```xml
  <entry key='event.forward.enable'>true</entry>
  <entry key='event.forward.url'>http://<<url>>/eventforward</entry>
  <entry key='event.forward.header'>content-type: application/x-www-form-urlencoded</entry>
```

Response:

'{\"{\\\"position\\\":{\\\"id\\\":75047,\\\"attributes\\\":{\\\"sat\\\":15,\\\"ignition\\\":false,\\\"distance\\\":10_62,\\\"totalDistance\\\":755301_56,\\\"ip\\\":\\\"49_14_34_186\\\",\\\"motion\\\":false},\\\"deviceId\\\":1,\\\"type\\\":null,\\\"protocol\\\":\\\"gt06\\\",\\\"serverTime\\\":null,\\\"deviceTime\\\":\\\"2017-08-21T06:24:16_000_0000\\\",\\\"fixTime\\\":\\\"2017-08-21T06:24:16_000_0000\\\",\\\"outdated\\\":false,\\\"valid\\\":true,\\\"latitude\\\":18_554139999999997,\\\"longitude\\\":73_79818666666667,\\\"altitude\\\":0_0,\\\"speed\\\":0_0,\\\"course\\\":80_0,\\\"address\\\":\\\"Baner_Road,_Pune,_Maharashtra,_IN\\\",\\\"accuracy\\\":0_0,\\\"network\\\":{\\\"radioType\\\":\\\"gsm\\\",\\\"considerIp\\\":false,\\\"cellTowers\\\":\":{\"{\\\"cellId\\\":2573,\\\"locationAreaCode\\\":10107,\\\"mobileCountryCode\\\":404,\\\"mobileNetworkCode\\\":22}\":\"\"},\"0\":[\"\"]}'
 
How do i know what the event is from this response ? Am i missing something ? 

THanks

**Comment by tananaev** [comment]
What "response" is that? It looks like position data, not an event.

**Comment by kedarnathjimage** [comment]
Yes, that's exactly my point. I am doing event forwarding and this is what i am receiving in my PHP script.  This is what i defined in my traccar.xml

`   <entry key='event.forward.enable'>true</entry>
    <entry key='event.forward.url'>http://<<MY_URL>>/eventforward</entry>
    <entry key='event.forward.header'>content-type: application/x-www-form-urlencoded</entry>
`
Whats seems to be the issue ?

**Comment by tananaev** [comment]
Are you sure you are using latest official release without any modifications? I'm looking at the code and it doesn't seem to be possible to receive something like that.

**Comment by kedarnathjimage** [comment]
Yes. I am using version 3.13 which i downloaded yesterday itself.

**Comment by tananaev** [comment]
No, you don't need to enable position forwarding. The only way to check what the problem is, is to debug the code.

**Comment by kaustubhlohiya** [comment]
@kedarnathjimage 
<entry key='event.forward.header'>content-type: application/x-www-form-urlencoded</entry>

This is whats creating the problem. Instead of x-www-form-urlencode use JSON. On the other side i.e. in PHP script access it using raw stream. Since PHP will not give variables in POST data because its JSON and not FORM-ENCODED.
