### ISSUE TITLE
Deployment of web interface files

### ISSUE THREAD

**Issue by saranshchat** [traccar/traccar#3469]
I have made changes in the minified version but the file needs to be saved.

**Comment by tananaev** [comment]
What is the question or problem?

**Comment by saranshchat** [comment]
I read the documentation but could not understand how to deploy of changes made in wen interface files
can you expalin these lines in documentation
"Upload new files into the server "web" folder and use "debug.html" to load non-compressed version of the web interface"

**Comment by tananaev** [comment]
Compile minified version and replace files all in "web" folder.

**Comment by saranshchat** [comment]
which web folder its is?
It is of server?

**Comment by tananaev** [comment]
How many web folders do you have? There is only one in Traccar server.

**Comment by tsmgeek** [comment]
Personally I would have changed the files in the 'app' dir' then created a new minified version from that using the ExtJs cli tools.
