### ISSUE TITLE
Request for an official IRC channel on freenode.net

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar#3475]
Hello,

Every great FOSS project has a presence on IRC, especially on the freenode.net network,
alas traccar doesn't.

There are forums, or github issues. The first needs registration, which seems broken at the moment, the second induces a lot of spam messages for basic/newbie questions. IRC is a way to fix this.

It would be nice if there was an **official** #traccar channel, for now I'm announcing the **unofficial** ##traccar on freenode.net, following their guidelines.

Basic rule is as usual: "Don't ask to ask, just ask"

Hope this will help !

**Comment by tananaev** [comment]
What is the problem with registration? I have just tested login, registration and password reset flows and everything is working perfectly for me.

**Comment by tsmgeek** [comment]
Slack would be better than IRC, lots of hooks for external services like Github/Travisetc

**Comment by oliv3** [comment]
On 08/25/2017 11:22 PM, Anton Tananaev wrote:
> What is the problem with registration? I have just tested login,
> registration and password reset flows and everything is working
> perfectly for me.

The captchas are way too complicated. Takes ages to post a question on
the forums.

People want to ask questions without going through a
signup/captchas/waitforregistrationmail/signin/postquestion/waitforanswer
that can take days.

And you might not have a browser.

The only mailing-list available is the newsletter.

And people DO use IRC. Heavily.

**Comment by oliv3** [comment]
On 08/26/2017 02:11 AM, tsmgeek wrote:
> Slack would be better than IRC, lots of hooks for external services like
> Github/Travisetc

Slack is proprietary / paying software.

IRC has hooks for whatever you'd dream of, like receiving push
notifications from git or build results from travis, from the very
beginning.

BR,

**Comment by tananaev** [comment]
@oliv3, "broken" and "captchas are way too complicated" are two completely different things. Please explain your claim in the first comment.

**Comment by oliv3** [comment]
@tananaev I created an account some times ago, with the new version of the website I now have to fill the captchas, to end up with an error like "Record not found"

**Comment by tananaev** [comment]
It probably means that login that you are using is incorrect. Captchas are usually shown only if are using some dodgy browser settings, or you share IP address with someone suspected of malicious activity.

**Comment by oliv3** [comment]
My login is/was correct. I might not have a browser. And I don't share my IP address with someone suspect, the same was over trusted networks and/or VPNs

**Comment by oliv3** [comment]
And now we're kinda having a chat over github... See what's wrong ?

**Comment by oliv3** [comment]
http://irc.netsplit.de/channels/?net=freenode

**Comment by tananaev** [comment]
Send me your email and login to check please.

**Comment by oliv3** [comment]
Le 26 août 2017 04:18:23 GMT+02:00, Anton Tananaev <notifications@github.com> a écrit :
>Send me your email and login to check please.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tananaev/traccar/issues/3475#issuecomment-325074442

Hi,

How does this answer the original question ?

BR, 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tananaev** [comment]
I believe we already discussed IRC. Before doing anything I want to see what other people think.

But if there is a problem with website login, I want to fix that. That's why I'm asking for help.

**Comment by oliv3** [comment]
@tananaev yes we already discussed about IRC. In my opinion that's a huge lack for such a project.
What about the community ? It's just another support channel.

You say: "Before doing anything I want to see what other people think.", how do you see this ? A poll ?

BR,

**Comment by arkanoid87** [comment]
libera or oftc would be a better place, FOSS projects are fleeing from Freenode
