### ISSUE TITLE
Button for print direct reporting of the platform

### ISSUE THREAD

**Issue by speedprovedor** [traccar/traccar#3479]
Have to be deployed somehow to print reports directly from the platform

Print all types of reports

**Comment by tananaev** [comment]
There's an export button. You can easily print excel report.

**Comment by speedprovedor** [comment]
Does not work as a document because it can be written and some reports do not go out

**Comment by tananaev** [comment]
Do not go out? Are you saying something doesn't work?

**Comment by speedprovedor** [comment]
Moderia put more information.
And excel reports is not valid as a document

**Comment by tananaev** [comment]
Closing as not enough information. If it's still needed, please create a ticket with proper details.
