### ISSUE TITLE
Traccar server is not multi-threaded

### ISSUE THREAD

**Issue by mpraki** [traccar/traccar#3488]
When I call http://127.0.0.1:5055?id=qwerty123&lat=17.814226150512695&lon=78.52687072753906&speed=42&timestamp=1503991223&address=Chennai,%20India for multiple devices continuously(not parallely, one after the other without any delay between subsequent call) , same deviceId got updated in the positions table for all the device requests.

When I added 2 seconds time delay before making the next call, it worked fine.

So, traccar does not support multi-threads?

**Comment by tananaev** [comment]
Please check this:

https://www.traccar.org/forums/topic/qustion-about-the-sessions/

**Comment by mpraki** [comment]
`<entry key='decoder.ignoreSessionCache'>true</entry>`

Even after adding this, same issue.

**Comment by tananaev** [comment]
That shouldn't be possible. You must be missing something.

**Comment by mpraki** [comment]
```
if (**channel != null && channel.getPipeline().get(HttpRequestDecoder.class) != null**
                || Context.getConfig().getBoolean("decoder.ignoreSessionCache")) {
            long deviceId = findDeviceId(remoteAddress, uniqueIds);
            if (deviceId != 0) {
                if (Context.getConnectionManager() != null) {
                    Context.getConnectionManager().addActiveDevice(deviceId, protocol, channel, remoteAddress);
                }
                return new DeviceSession(deviceId);
            } else {
                return null;
            }
        }
```
I see the above code. Even if we set the `decoder.ignoreSessionCache` set to true, above code gets device from session.

**Comment by tananaev** [comment]
Where exactly do you see that? Because I don't.

**Comment by mpraki** [comment]
Ignore that please... If session is the issue, my doubt is how come making 2 seconds delay works..

**Comment by tananaev** [comment]
Can I see logs with the issue?
