### ISSUE TITLE
DNS for TK103A

### ISSUE THREAD

**Issue by andi968** [traccar/traccar#3495]
Hi
Has anyone had success setting up dns on a tk103a?
I send command
`adminip123456 *******.dyndns.org 5001`
I receive
`adminip ok!`
However after sending
`check123456`
I get
`IP: 0.0.0.0:0`

Thanks in advance

**Comment by tananaev** [comment]
Maybe it doesn't support domain names? Try IP address directly.

**Comment by andi968** [comment]
IP address works fine, however my isp is a dynamic provider which means I lose connection every time it changes, hence the need for dns.
As stated in op it accepts the dns address but stores it incorrectly, I wondered if anyone else with similar setup had managed.

**Comment by evigra** [comment]
Si son los Tk103 solo soportan IPs no URLs

**Comment by Shinryuken** [comment]
try this command (works for me)

`dns123456 www.traccar.org 5001`

as referenced here:
https://www.traccar.org/forums/topic/coban-306a-adminip/

This should be put somewhere because the manual does not mention this command (or just any other manual found on internet)

**Comment by andi968** [comment]
Absolutely fantastic !!!!! It works 
THANK YOU SO SO MUCH.
It definitely needs adding to the user manual and perhaps a sticky

**Comment by Shinryuken** [comment]
thank goes to mohanand from the traccar.org forum, happy to know that works for you too, i searched on internet for about 2 days and i only found that comment mentioning it.

**Comment by Shinryuken** [comment]
@tananaev 

Could this command be put somewhere on the traccar.org portal?, it could be very useful, there is a lot of people on the internet complaining about this issue without finding a solution.

**Comment by tananaev** [comment]
I can't think of any good place to put it. I think we should just point to the original forum thread several times and eventually it would become easy to find the answer.

**Comment by Shinryuken** [comment]
ok, i forgot to mention that after sending that dns command the tracker will answer with "**dns success!**"
