### ISSUE TITLE
GT02A TCP communication

### ISSUE THREAD

**Issue by benj-c** [traccar/traccar#3516]
Hi.

i've configured GT02A gps tracker to transmit data to an online server on port 5013 by creating server using this perl [https://github.com/corbamico/GT02A/blob/master/perl/gt02a_tcp_server.pl](url) script.

and here's the data stream received from this open port
```
(027045009305BP05355227045009305170909A0602.0766N08013.0997E000.6080515000.0001000000L00000000)
```
but i dont know how to parse this data into a readable format, could you please help me, i'm new to this tech.

Thanks a lot !

**Comment by tananaev** [comment]
It's TK103 protocol in Traccar.

**Comment by benj-c** [comment]
right, i found some protocol information but,
what's this data stream,

(027045009305BP05355227045009305,{413,2,30073,16724}
{413,2,30073,16730}
{413,2,30073,49860}
,01000000)

**Comment by benj-c** [comment]
now the data stream format has been changed, didnt change anything in my code but now the terminal shows completely different output, con someone please tell what's this difference here ??

**Comment by tananaev** [comment]
That looks like a different message type.

**Comment by MarcioBRSP** [comment]
Hi tatanaev, how are you? I hope fine, its my second message here in github, I saw a lot of messages from you, can you see if you can help me with thishttps://github.com/tananaev/traccar/issues/3564 ? thanks a lot

**Comment by 0neday** [comment]
> That looks like a different message type.

It can not be fixed?

**Comment by tananaev** [comment]
It can be implemented. If you're interested in sponsoring the work, please send us an email.
