### ISSUE TITLE
NullPointer Exception when generating reports through api

### ISSUE THREAD

**Issue by saranshchat** [traccar/traccar#3520]
Hello Anton,

I am passing device id in the url of report :- http://localhost:8082/api/reports/summary?deviceId=12345 through postman but it returns 400 bad request and when checked for error i got this :-
```
NullPointerException (... < DateUtil:64 < ReportResource:93 < ...)
```
Also I pasting my code here, please if you could provide any suggestion
```js
var settings = {
  "async": true,
  "crossDomain": true,
  "url": "http://localhost:8082/api/reports/summary?deviceName=12345",
  "method": "GET",
  "headers": {
    "authorization": "Basic YWRtaW5AZ21haWwuY29tOmFkbWlu",
    "cache-control": "no-cache",
    "postman-token": "7b26482a-d518-4577-6167-239ce8a715bb"
  }
}

$.ajax(settings).done(function (response) {
  console.log(response);
});
```

**Comment by tananaev** [comment]
You are missing `Accept` header.

**Comment by saranshchat** [comment]
hello anton,
Thanks i resolved that error but new exception is thrown 
Manager access required - SecurityException (PermissionsManager:158 < *:270 < Summary:74 < ReportResource:92 < ...)
Is this related to authnetication?

**Comment by tananaev** [comment]
Looks like you are requesting something that requires manager or admin access.

**Comment by saranshchat** [comment]
But I have given admin details. Then why this error is coming

**Comment by tananaev** [comment]
Apparently you haven't.

**Comment by saranshchat** [comment]
Hello, 
I have checked and have provided the admin auth but same exception occuring also removed other login details

**Comment by tananaev** [comment]
It won't happen for admin user, so you must be missing something.

**Comment by saranshchat** [comment]
Hello,
Can you brief out what I am missing because there is no user other than me as the devices api is running successfully and giving details of the devices.

**Comment by tananaev** [comment]
I have no idea what's missing.
