### ISSUE TITLE
For those who have the "changelog lock" problem on H2.

### ISSUE THREAD

**Issue by veniciosn** [traccar/traccar#3531]
I see several people just deleting old DB because of that.

1 - Download liquibase

2 - Download H2 Driver

3 - Change permission on database file so your user can grant rw

4 - Copy and paste de following making the necessary changes

```
java -jar liquibase.jar \
         --driver=org.h2.Driver \
         --classpath=h2-1.4.196.jar \
         --url=jdbc:h2:/opt/traccar/data/database \
         --username=sa \
         --password= \
         releaseLocks
```

**Comment by tananaev** [comment]
Nice solution. Thanks for sharing. By the way, you don't need to download liquibase and h2 driver because Traccar already includes them.

**Comment by smingoli** [comment]
Thanks for the solution @veniciosn .... in my case had to do some changes, maybe because of the version of liquidbase

For future reference versions are: liquibase-3.6.3 and h2-1.4.198

Code that i had to run is the following


 ```
java -cp ".:/home/traccar/fixtraccar/liquibase.jar:/home/traccar/fixtraccar/lib/:/home/traccar/fixtraccar/lib/logback-classic-1.2.3.jar:/home/traccar/fixtraccar/lib/logback-core-1.2.3.jar:/home/traccar/fixtraccar/lib/slf4j-api-1.7.25.jar:/home/traccar/fixtraccar/lib/snakeyaml-1.18.jar" liquibase.integration.commandline.Main \
		 --driver=org.h2.Driver \
         --classpath=/home/traccar/fixtraccar/h2-1.4.198.jar \
         --url=jdbc:h2:/opt/traccar/data/database \
         --username=sa \
         --password= \
         releaseLocks
 ```
/home/traccar/fixtraccar is where I put liquidbase and the H2 Driver

Put also the following in my .bash_profile
 ```
JAVA_HOME=/opt/traccar/jre
export JAVA_HOME
PATH="$PATH:$JAVA_HOME/bin"
export PATH
 ```

**Comment by tananaev** [comment]
Versions depend on Traccar version. We always update dependencies before release.

**Comment by nebula-it** [comment]
Hey @veniciosn ,

I tried your suggestion but gives out this error `Error: Unable to access jarfile liquibase.jar`, any ideas? I tried running find but even that was unable to located liquidbase.jar file.

I tried @smingoli 's code as welll and that results in following error: `Error: Could not find or load main class liquibase.integration.commandline.Main`

I'm running the `traccar/traccar:alpine` image in docker.

**Comment by jonhassall** [comment]
In case this helps someone:

```
java -jar liquibase-core-4.3.5.jar \
         --driver=com.mysql.cj.jdbc.Driver \
         --classpath=mysql-connector-java-8.0.25.jar \
         --url=jdbc:mysql://mysql:3306/traccar \
         --username=traccar \
         --password=YOURPASSWORD \
         releaseLocks
```
