### ISSUE TITLE
Feature Request: Total Hour for vehicle just like Total Distance 

### ISSUE THREAD

**Issue by darshan2210** [traccar/traccar#3532]
Hello Anton,

Request you for the feature for maintain the vehicle Total Hour just like as Total Distance option available right now in server.

This will help us for the vehicle that have the Total Hour instead of Odometer.

Thanks.

**Comment by tsmgeek** [comment]
Working off the ACC signal? Does not guarantee that engine is running though. May need to be a configurable option as some trackers could use a GPIO port or a separate flag for if engine is running.

**Comment by darshan2210** [comment]
Yes, that would be nice idea.

**Comment by pc500** [comment]
Some trackers report "Ignition".  That could be used.  Yes, someone could have the key turned all the way without the engine running, but most won't as the battery would be depleted quick.  It's like GPS computed mileage... "close enough".

**Comment by Abyss777** [comment]
Here is some thoughts about this feature.

Before implementing server side engine hours accumulator based on ignition we need to standardize a attribute.
I believe `KEY_HOURS` is for that.

From the server side it is simpler use milliseconds (just subtract unix time), but we have number of protocols already used this attribute.
- Aplicom
- Astra
- Continental
- Gl200Text
- GoSafe
- Gps103
- Mta6
- Mxt
- Suntech
- Vtfms
- Xirgo

Looks like most of them mean that as hours, I think it is not enough precise to accumulating. Also we already have engine hours in reports and it is in milliseconds. I think it is better make it consistent.

@tananaev what do you think? Or may be better add another attribute for that?

**Comment by tananaev** [comment]
I think we should convert it to milliseconds, even if devices report in much lower precision. If device reports it, we shouldn't override it.

**Comment by Abyss777** [comment]
Looks like here is small issue https://github.com/traccar/traccar/blob/master/src/org/traccar/protocol/GoSafeProtocolDecoder.java#L111

There must be `hours[1]` and `hours[2]`. It is OK, i'll fix it but...
there is a test 
https://github.com/traccar/traccar/blob/master/test/org/traccar/protocol/GoSafeProtocolDecoderTest.java#L14
with `COT:65;20` where `20` do not match documentation
> `Engine hour, time format: <Hour>-<Minute>-<Second>`
> `Range: 0-0-0~99999-0-0`

How will we treat it? Like hours with omitted minutes and seconds, or seconds without hours and minutes?

**Comment by tananaev** [comment]
I think we can assume that it's hours and then fix if there is an issue.

**Comment by Abyss777** [comment]
OK.
Can't find documentation for `GTCAN` packets in GL200, could you please check this value units https://github.com/traccar/traccar/blob/master/src/org/traccar/protocol/Gl200TextProtocolDecoder.java#L602

Looks like hours, but better recheck if you have the documentation.

**Comment by tananaev** [comment]
Just checked documentation and it says `h` (hours).

**Comment by Abyss777** [comment]
Thanks

**Comment by Abyss777** [comment]
I have find out hours units in three other protocols. `Mxt` and `Suntech` report in minutes, that means that we can't just assume that it is usually hours.

I could not find documentation (or it is for other versions) for the rest of protocols (not ticked)
Could you please check in your archives? Gps103 called "odb" and Xirgo variant called "new" in code.

**Comment by tananaev** [comment]
For Xirgo I haven't found specific documentation for the format, but in one of the Xirgo documents I found `ObdTotEngHours` is in `hours`, so I'm assuming that it's the case for all their protocols.

With GPS103 it's worse. There is no information about units:

![screen shot 2018-05-29 at 8 36 21 pm](https://user-images.githubusercontent.com/1161863/40647456-033e23f0-6380-11e8-8703-d3e97657e866.png)

**Comment by Abyss777** [comment]
And it might be even not engine hours but something like "trip time" ...

What about others: Aplicom, Astra, Continental, Vtfms?

**Comment by tananaev** [comment]
I think it's better to go with assumption that it's hours and then fix it as we go.

**Comment by Abyss777** [comment]
Just not to create separate discussion in web repo...

We have three places where we will use engine hours, we need to decide how to format and convert it.
- Now we have `durationFormatter` that represent it as `0 h 0 m` in reports, I think it is also applicable to State panel.
- We have Charts, do not think it is good if it will be in milliseconds, it will be logically to convert `hours` in hours :) (float) for Charts.
- We have Maintenances, where it will be second by popularity attribute to use (I suppose). I think a periods will be rather big (1000 h or so) and also it is logically to ask users enter hours, not minutes or seconds.
- May be in future we will add a way to reset `hours` (like `totalDistance`) value is also should be entered in hours.

My suggestion is to format hours as `0 h 0 m` but convert as floating point hours for `CustomNumberField` and Charts.

**Comment by tananaev** [comment]
I agree with suggestion.
