### ISSUE TITLE
Streamline logging

### ISSUE THREAD

**Issue by mwl** [traccar/traccar#3543]
I'm happy to do this piece of refactoring myself, but before I set out to do the work, I want to come to an agreement on the current situation and what should be done.

As far as I'm concerned I see the following issues
- Logging in different formats
- Logging to `stderr` rather than `stdout`
- Impossible to adjust per class logging level

As a solution I suggest
- [ ] Choose an overall logging framework
- [ ] Eliminate "other" logging apis and replace with bridges
- [ ] Configure a common logging output format
- [ ] Deprecate `org.traccar.helper.Log` class
- [ ] Remove usage of `org.traccar.helper.Log` class

Let me know your thoughts and have a friendly discussion about the approach.

Thanks,
-@mwl

**Comment by mwl** [comment]
As for the overall logging framework, I've noticed that there's at least the following frameworks on classpath
- Log4j
- Slf4j
- Commons-logging

In my experience, Slf4j has the best bridges, at least for the other two mentioned frameworks.

**Comment by tananaev** [comment]
I don't mind improving logging, but I would prefer to keep some things from current class. For example compact stack traces are very useful for investigating issues. We also use them for service calls.

Adjusting logging per class is fine as long as the whole system is not overcomplicated.

**Comment by Abyss777** [comment]
It would be nice to make cloudhopper-smpp write PDUs in traccar log instead of wrapper

**Comment by tananaev** [comment]
Agree. Same applies to Jetty and Liquibase logs.

**Comment by Abyss777** [comment]
@mwl Any news in refactoring?
