### ISSUE TITLE
Teltonika IO decoding

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar#3544]
I think it is more convenient to discuss and collect it here
I've collected IO meanings from some documentation, last column from official for FMBXXX devices http://teltonika.lt/?media_dl=6079 only permanent and eventual IOs.

[Teltonika Summary IO Table.xlsx](https://github.com/tananaev/traccar/files/1323815/Teltonika.Summary.IO.Table.xlsx)

Marked green that totally compatible, marked red that is not compatible from device to device.

**Comment by tananaev** [comment]
Uploaded to Google Docs:

https://docs.google.com/a/traccar.org/spreadsheets/d/1BTbIQ9nlkwqDO1s9AnoighdxyiwCSCCVVEBdi0dOjTU

**Comment by tananaev** [comment]
Sounds good to me.
