### ISSUE TITLE
Feature request: Multiple maintenance

### ISSUE THREAD

**Issue by juanjorgebm** [traccar/traccar#3548]
Create different maintenance attributes. For example: oil change, change of tires, anual revision, etc.

**Comment by Abyss777** [comment]
It is probably makes sense to implement this as full featured `ExtendedObject` with three fields:
- Description
- Start
- Interval
And link any number of maintenance periods to device.

Do we have any other suggestions about maintenance?

I know that in some other systems it is implemented as state, when interval passed, device switches in "Required Maintenance" state until user manually switch it to normal state. But I think it is not worth the time and complexity spent on this feature.

**Comment by tananaev** [comment]
I don't recall any other requests for this feature, so let's wait and see if anyone else is interested.

**Comment by juanjorgebm** [comment]
Yes, that could work perfectly.
I've been thinking on this and could be great if "maintenance" were more complex and User could register all the information and check it later. 
Like, when was the last time I change the oil. For example, if the car don't move a lot you must change oil 3 month after the last change

**Comment by FabianInostroza** [comment]
I would like to be able to change the attribute on which the maintenance interval is checked, as an example: every 1000 hours of operation, every 1000 liters of used fuel, etc.

I already have some code to evaluate the custom attribute for maintenance in the server (it's really simple) but I don't know how to integrate it in the UI.

**Comment by inghoward** [comment]
Multiple maintenance interval is something necesary. Is there possible configure maintenance alarms based on odometer using computed attributes?

**Comment by msalman786** [comment]
I agree, it is very important feature. @FabianInostroza your suggestion can be a wonderful addition too.
