### ISSUE TITLE
eelink - Mute certain alerts when ignition is on

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3550]
Not so much a problem as the system is doing exactly what its told.

Eelink devices still give certain alerts ie vibration even though ignition is on so its up to the online platform to handle these appropriately. So when I start and leave home in the morning I can get three notices, Ignition On, Vibration (when i start moving), geofence out and while I am out if I happen to stop moving for a few mins then start again (Ignition always on) i can get another vibration alert.

Currently traccar does not seem to support if/then/else notification rules so I am wondering what is the best way to do this other than change the protocol decoder (or create a custom version for my purpose)? I was thinking attributes on either the notification or device, ie ignoreIfIgnitonOn:true.

**Comment by tananaev** [comment]
There is no explicit option, but you can probably use computed attributes to clear alarm if ignition is ON.

**Comment by briggz84** [comment]
How did you go with the solution tsmgeek? I get accident alarm constantly riding my bike when I hit any large bump on the road. Extremely annoying. I was wondering if the following computed attribute would work?

alarm == "accident" ? "85" : null

**Comment by tsmgeek** [comment]
Send WARNING,180# to your tracker. It turns off crash and freefall alerts
which are useless on bikes as give too many false positives.

On 15 Oct 2017 07:14, "Paul" <notifications@github.com> wrote:

How did you go with the solution tsmgeek? I get accident alarm constantly
riding my bike when I hit any large bump on the road. Extremely annoying. I
was wondering if the following computed attribute would work?

alarm == "accident" ? "85" : null

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tananaev/traccar/issues/3550#issuecomment-336689256>,
or mute the thread

**Comment by briggz84** [comment]
Thanks! Will give it a try.

**Comment by briggz84** [comment]
Seemed to do the trick. Please send me an email paul.briggs@gmail.com, would like to discuss further with you on the subject of the eelink devices.

**Comment by tsmgeek** [comment]
@briggz84 send me a message to tsmgeek@gmail.com what you would like to know about them.

**Comment by tsmgeek** [comment]
@tananaev @briggz84 
I have looked into doing this with computed attributed and have come to conclusion that its not possible for a few reasons.
This is the JEXL code I was testing with `alarm ? ignition == true && alarm == "vibration" ? null : alarm : null`

1. eelink alert packets 0x04 do not  pass the general status of the device which are supplied in 0x02, newer V2 protocol has changed this in the 0x14 warning packet which is currently correctly supported in the update I did to the proto decoder.
2. current decoder does not load the last packet data for things like alert/warning packets, this means you cant run computed attributes unless the latest packet also includes the values you are checking. I think I corrected this in my update to the proto decoder, ie for things like 0x04/0x14 packets it will load the last logged track then add the changes to it.
3. I may just add a flag in the decoder to easily set certain conditions ie Ignore Device Events If Ignition On.

I need to re-merge in the latest alterations that were done to the decoder into mine and it would need to be merged into master.

**Comment by tsmgeek** [comment]
@tananaev  Does 'Processing: Copy Attributes' under device attributes, does this copy all the attributes are copied from current track to latest track that is being processed, so like a base set of attributes to which the new ones are merged in?

**Comment by tananaev** [comment]
You need to specify list of attributes to copy.

**Comment by freman** [comment]
I'm having a similar problem with my bike triggering crash smses (and external power shutdown! - it nuked my battery, so I moved it all to acc)

I've poked around, the eelink v2 protocol doc says if the message is empty then it won't send the SMS but I can't find a way to tell traccar to send back the empty message.

Is there a way to do this?
