### ISSUE TITLE
Traccar does not start... DATABASECHANGELOGLOCK LOCKED=0, GT02 which is not interpreted

### ISSUE THREAD

**Issue by evigra** [traccar/traccar#3557]
Good morning Anton. Thank you so much for all your help.
Problems were piled up.
I do not know if there is a relationship between them.

1.- My server does not start, I attach historical files.
2.- My table DATABASECHANGELOGLOCK, i have row: LOCKED=0 (I truncate)
3.- I have a GT02, which is not interpreted. Ports used: 5001,5022,5023

My log
```
>2017-09-30 09:13:02  INFO: Operating system name: Linux version: 2.6.32-642.11.1.el6.x86_64 architecture: amd64
>2017-09-30 09:13:02  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.91-b01
>2017-09-30 09:13:02  INFO: Memory limit heap: 592mb non-heap: 214mb
>2017-09-30 09:13:02  INFO: Character encoding: UTF-8 charset: UTF-8
>2017-09-30 09:13:02  INFO: Version: 3.7-SNAPSHOT
>2017-09-30 09:13:08  WARN: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp - SQLException (... < QueryBuilder:355 < *:421$
>2017-09-30 09:13:08  WARN: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN] - JsonParsingExc$
>2017-09-30 09:13:08  WARN: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN] - JsonParsingExc$
```
My Wrapper
```
>STATUS | wrapper  | 2017/09/30 04:02:47 | <-- Wrapper Stopped
>STATUS | wrapper  | 2017/09/30 04:13:01 | --> Wrapper Started as Daemon
>STATUS | wrapper  | 2017/09/30 04:13:01 | Java Service Wrapper Community Edition 64-bit 3.5.28
>STATUS | wrapper  | 2017/09/30 04:13:01 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
>STATUS | wrapper  | 2017/09/30 04:13:01 |     http://wrapper.tanukisoftware.com
>STATUS | wrapper  | 2017/09/30 04:13:01 |
>STATUS | wrapper  | 2017/09/30 04:13:02 | Launching a JVM...
>INFO   | jvm 1    | 2017/09/30 04:13:02 | WrapperManager: Initializing...
>INFO   | jvm 1    | 2017/09/30 04:13:03 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
>INFO   | jvm 1    | 2017/09/30 04:13:04 | INFO 9/30/17 9:13 AM: liquibase: Clearing database change log checksums
>INFO   | jvm 1    | 2017/09/30 04:13:04 | INFO 9/30/17 9:13 AM: liquibase: Successfully acquired change log lock
>INFO   | jvm 1    | 2017/09/30 04:13:04 | INFO 9/30/17 9:13 AM: liquibase: Successfully released change log lock
>INFO   | jvm 1    | 2017/09/30 04:13:04 | INFO 9/30/17 9:13 AM: liquibase: Successfully acquired change log lock
>INFO   | jvm 1    | 2017/09/30 04:13:07 | INFO 9/30/17 9:13 AM: liquibase: Reading from admin_soles37.DATABASECHANGELOG
>INFO   | jvm 1    | 2017/09/30 04:13:07 | INFO 9/30/17 9:13 AM: liquibase: Reading from admin_soles37.DATABASECHANGELOG
>INFO   | jvm 1    | 2017/09/30 04:13:07 | INFO 9/30/17 9:13 AM: liquibase: Successfully released change log lock
>INFO   | jvm 1    | 2017/09/30 04:13:08 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @5971ms
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp:
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error: Encountered an error running main:
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error: java.lang.NullPointerException
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error:       at org.traccar.database.DeviceManager.getAllDevices(DeviceManager.java:143)
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error:       at org.traccar.database.PermissionsManager.refreshPermissions(PermissionsM$
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error:       at org.traccar.database.PermissionsManager.<init>(PermissionsManager.java:$
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error:       at org.traccar.Context.init(Context.java:218)
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error:       at org.traccar.Main.main(Main.java:35)
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.ja$
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccesso$
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:606)
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:3$
>INFO   | jvm 1    | 2017/09/30 04:13:09 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:745)
>STATUS | wrapper  | 2017/09/30 04:13:11 | <-- Wrapper Stopped
```

GT02 my log
```
>======== ASCII ======== (027044975530BR00170930A1916.5856N10343 =======
>2017-09-30 05:11:41 DEBUG: [83A19C47: 5022 < 187.210.230.154] HEX: 283032373034343937353533304252303031373039333041313931362e353835364e31303334332$
>2017-09-30 05:11:41  WARN: Unknown device - 137303933304131 (187.210.230.154)
>2017-09-30 05:11:41  WARN: Unknown device - 13931362e353835 (187.210.230.154)
>
>
>2017-09-30 05:10:41 DEBUG: [83A19C47: 5022 < 187.210.230.154] HEX: 283032373034343937353533304252303031373039333041313931362e353836304e31303334332$
>2017-09-30 05:10:41  WARN: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp - SQLException (... < QueryBuilder:355 < *:421$
>2017-09-30 05:10:41  WARN: Unknown device - 832313157303030 (187.210.230.154)
```

**Comment by tananaev** [comment]
I think there is some problem with database or config.

Almost all lines in your logs are cut by your text editor.

**Comment by evigra** [comment]
Before setting up the GT02 everything worked fine.
I commented because, the server restarts daily.
traccar, restarts every hour.

I use crons because, 
Traccar stopped interpreting

`
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    

    <entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>/opt/traccar/web</entry>

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>

    <entry key='event.enable'>true</entry>
    <entry key='event.overspeedHandler'>true</entry>
    <entry key='event.overspeed.notRepeat'>true</entry>
    <entry key='event.motionHandler'>true</entry>
    <entry key='event.geofenceHandler'>true</entry>
    <entry key='event.alertHandler'>true</entry>
    <entry key='event.ignitionHandler'>true</entry>

    

    <entry key='database.driver'>org.h2.Driver</entry>
    <entry key='database.url'>jdbc:h2:/opt/traccar/data/database</entry>
    <entry key='database.user'>sa</entry>
    <entry key='database.password'></entry>

    <entry key='database.ignoreUnknown'>true</entry>

<entry key='processing.copyAttributes.enable'>true</entry>
<entry key='processing.copyAttributes'>power,ignition,battery</entry>

<entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
<entry key='database.url'>jdbc:mysql://localhost:3306/admin_soles37?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
<entry key='database.user'>admin_traccar</entry> 
<entry key='database.password'>EvG30JiC06</entry>



    <entry key='database.changelog'>/opt/traccar/schema/changelog-master.xml</entry>

    <entry key='database.selectServers'>
        SELECT * FROM server;
    </entry>

    <entry key='database.updateServer'>
        UPDATE server SET
        registration = :registration,
        readonly = :readonly,
        map = :map,
        bingKey = :bingKey,
        mapUrl = :mapUrl,
        distanceUnit = :distanceUnit,
        speedUnit = :speedUnit,
        latitude = :latitude,
        longitude = :longitude,
        zoom = :zoom,
        twelveHourFormat = :twelveHourFormat,
        attributes = :attributes
        WHERE id = :id;
    </entry>

    <entry key='database.loginUser'>
        SELECT * FROM users
        WHERE email = :email;
    </entry>

    <entry key='database.selectUser'>
        SELECT * FROM users
        WHERE id = :id;
    </entry>

    <entry key='database.selectUsersAll'>
        SELECT * FROM users;
    </entry>

    <entry key='database.insertUser'>
        INSERT INTO users (name, email, hashedPassword, salt, admin, map, distanceUnit, speedUnit, latitude, longitude, zoom, twelveHourFormat, attributes)
        VALUES (:name, :email, :hashedPassword, :salt, :admin, :map, :distanceUnit, :speedUnit, :latitude, :longitude, :zoom, :twelveHourFormat, :attributes);
    </entry>

    <entry key='database.updateUser'>
        UPDATE users SET
        name = :name,
        email = :email,
        admin = :admin,
        map = :map,
        distanceUnit = :distanceUnit,
        speedUnit = :speedUnit,
        latitude = :latitude,
        longitude = :longitude,
        zoom = :zoom,
        twelveHourFormat = :twelveHourFormat,
        attributes = :attributes
        WHERE id = :id;
    </entry>

    <entry key='database.updateUserPassword'>
        UPDATE users SET hashedPassword = :hashedPassword, salt = :salt WHERE id = :id;
    </entry>

    <entry key='database.deleteUser'>
        DELETE FROM users WHERE id = :id;
    </entry>

    <entry key='database.selectDevicePermissions'>
        SELECT userId, deviceId FROM user_device;
    </entry>

    <entry key='database.selectGroupPermissions'>
        SELECT userId, groupId FROM user_group;
    </entry>

    <entry key='database.selectDevicesAll'>
        SELECT * FROM devices;
    </entry>

    <entry key='database.insertDevice'>
        INSERT INTO devices (name, uniqueId, groupId, attributes) VALUES (:name, :uniqueId, :groupId, :attributes);
    </entry>

    <entry key='database.updateDevice'>
        UPDATE devices SET name = :name, uniqueId = :uniqueId, groupId = :groupId, attributes = :attributes WHERE id = :id;
    </entry>

    <entry key='database.updateDeviceStatus'>
        UPDATE devices SET lastUpdate = :lastUpdate WHERE id = :id;
    </entry>

    <entry key='database.deleteDevice'>
        DELETE FROM devices WHERE id = :id;
    </entry>

    <entry key='database.linkDevice'>
        INSERT INTO user_device (userId, deviceId) VALUES (:userId, :deviceId);
    </entry>

    <entry key='database.unlinkDevice'>
        DELETE FROM user_device WHERE userId = :userId AND deviceId = :deviceId;
    </entry>

    <entry key='database.selectGroupsAll'>
        SELECT * FROM groups;
    </entry>

    <entry key='database.insertGroup'>
        INSERT INTO groups (name, groupId, attributes) VALUES (:name, :groupId, :attributes);
    </entry>

    <entry key='database.updateGroup'>
        UPDATE groups SET name = :name, groupId = :groupId, attributes = :attributes WHERE id = :id;
    </entry>

    <entry key='database.deleteGroup'>
        DELETE FROM groups WHERE id = :id;
    </entry>

    <entry key='database.linkGroup'>
        INSERT INTO user_group (userId, groupId) VALUES (:userId, :groupId);
    </entry>

    <entry key='database.unlinkGroup'>
        DELETE FROM user_group WHERE userId = :userId AND groupId = :groupId;
    </entry>

    <entry key='database.selectPositions'>
        SELECT * FROM positions WHERE deviceId = :deviceId AND fixTime BETWEEN :from AND :to ORDER BY fixTime;
    </entry>

    <entry key='database.insertPosition'>
        INSERT INTO positions (deviceId, protocol, serverTime, deviceTime, fixTime, valid, latitude, longitude, altitude, speed, course, address, attributes)
        VALUES (:deviceId, :protocol, :now, :deviceTime, :fixTime, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :attributes);
    </entry>

    <entry key='database.selectLatestPositions'>
        SELECT * FROM positions WHERE id IN (SELECT positionId FROM devices);
    </entry>

    <entry key='database.updateLatestPosition'>
        UPDATE devices SET positionId = :id WHERE id = :deviceId;
    </entry>

    <entry key='database.selectEvent'>
        SELECT * FROM events WHERE id = :id;
    </entry>

    <entry key='database.insertEvent'>
        INSERT INTO events (type, serverTime, deviceId, positionId, geofenceId, attributes)
        VALUES (:type, :serverTime, :deviceId, :positionId, :geofenceId, :attributes);
    </entry>

    <entry key='database.selectEvents'>
        SELECT * FROM events WHERE deviceId = :deviceId AND type LIKE :type AND serverTime BETWEEN :from AND :to ORDER BY serverTime DESC;
    </entry>

    <entry key='database.selectGeofence'>
        SELECT * FROM geofences
        WHERE id = :id;
    </entry>

    <entry key='database.selectGeofencesAll'>
        SELECT * FROM geofences;
    </entry>

    <entry key='database.insertGeofence'>
        INSERT INTO geofences (name, description, area, attributes)
        VALUES (:name, :description, :area, :attributes);
    </entry>

    <entry key='database.updateGeofence'>
        UPDATE geofences SET
        name = :name,
        description = :description,
        area = :area,
        attributes = :attributes
        WHERE id = :id;
    </entry>

    <entry key='database.deleteGeofence'>
        DELETE FROM geofences WHERE id = :id;
    </entry>

    <entry key='database.selectGeofencePermissions'>
        SELECT userId, geofenceId FROM user_geofence;
    </entry>

    <entry key='database.linkGeofence'>
        INSERT INTO user_geofence (userId, geofenceId) VALUES (:userId, :geofenceId);
    </entry>

    <entry key='database.unlinkGeofence'>
        DELETE FROM user_geofence WHERE userId = :userId AND geofenceId = :geofenceId;
    </entry>

    <entry key='database.selectGroupGeofences'>
        SELECT groupId, geofenceId FROM group_geofence;
    </entry>

    <entry key='database.linkGroupGeofence'>
        INSERT INTO group_geofence (groupId, geofenceId) VALUES (:groupId, :geofenceId);
    </entry>

    <entry key='database.unlinkGroupGeofence'>
        DELETE FROM group_geofence WHERE groupId = :groupId AND geofenceId = :geofenceId;
    </entry>

    <entry key='database.selectDeviceGeofences'>
        SELECT deviceId, geofenceId FROM device_geofence;
    </entry>

    <entry key='database.linkDeviceGeofence'>
        INSERT INTO device_geofence (deviceId, geofenceId) VALUES (:deviceId, :geofenceId);
    </entry>

    <entry key='database.unlinkDeviceGeofence'>
        DELETE FROM device_geofence WHERE deviceId = :deviceId AND geofenceId = :geofenceId;
    </entry>

    <entry key='database.selectNotifications'>
        SELECT * FROM notifications;
    </entry>

    <entry key='database.insertNotification'>
        INSERT INTO notifications (userId, type, attributes)
        VALUES (:userId, :type, :attributes);
    </entry>

    <entry key='database.updateNotification'>
        UPDATE notifications SET
        userId = :userId,
        type = :type,
        attributes = :attributes
        WHERE id = :id;
    </entry>

    <entry key='database.deleteNotification'>
        DELETE FROM notifications WHERE id = :id;
    </entry>

    <entry key='database.deletePositions'>
        DELETE FROM positions WHERE serverTime &lt; :serverTime AND id NOT IN (SELECT positionId FROM devices);
    </entry>

    

    <entry key='gps103.port'>5001</entry>
    <entry key='tk103.port'>5002</entry>
    <entry key='gl100.port'>5003</entry>
    <entry key='gl200.port'>5004</entry>
    <entry key='t55.port'>5005</entry>
    <entry key='xexun.port'>5006</entry>
    <entry key='xexun.extended'>false</entry>
    <entry key='totem.port'>5007</entry>
    <entry key='enfora.port'>5008</entry>
    <entry key='meiligao.port'>5009</entry>
    <entry key='trv.port'>5010</entry>
    <entry key='suntech.port'>5011</entry>
    <entry key='progress.port'>5012</entry>
    <entry key='h02.port'>5013</entry>
    <entry key='jt600.port'>5014</entry>
    <entry key='huabao.port'>5015</entry>
    <entry key='v680.port'>5016</entry>
    <entry key='pt502.port'>5017</entry>
    <entry key='tr20.port'>5018</entry>
    <entry key='navis.port'>5019</entry>
    <entry key='meitrack.port'>5020</entry>
    <entry key='skypatrol.port'>5021</entry>
    <entry key='gt02.port'>5022</entry>
    <entry key='gt06.port'>5023</entry>
    <entry key='megastek.port'>5024</entry>
    <entry key='navigil.port'>5025</entry>
    <entry key='gpsgate.port'>5026</entry>
    <entry key='teltonika.port'>5027</entry>
    <entry key='mta6.port'>5028</entry>
    <entry key='tzone.port'>5029</entry>
    <entry key='tlt2h.port'>5030</entry>
    <entry key='taip.port'>5031</entry>
    <entry key='wondex.port'>5032</entry>
    <entry key='cellocator.port'>5033</entry>
    <entry key='galileo.port'>5034</entry>
    <entry key='ywt.port'>5035</entry>
    <entry key='tk102.port'>5036</entry>
    <entry key='intellitrac.port'>5037</entry>
    <entry key='gpsmta.port'>5038</entry>
    <entry key='wialon.port'>5039</entry>
    <entry key='carscop.port'>5040</entry>
    <entry key='apel.port'>5041</entry>
    <entry key='manpower.port'>5042</entry>
    <entry key='globalsat.port'>5043</entry>
    <entry key='atrack.port'>5044</entry>
    <entry key='pt3000.port'>5045</entry>
    <entry key='ruptela.port'>5046</entry>
    <entry key='topflytech.port'>5047</entry>
    <entry key='laipac.port'>5048</entry>
    <entry key='aplicom.port'>5049</entry>
    <entry key='gotop.port'>5050</entry>
    <entry key='sanav.port'>5051</entry>
    <entry key='gator.port'>5052</entry>
    <entry key='noran.port'>5053</entry>
    <entry key='m2m.port'>5054</entry>
    <entry key='osmand.port'>5055</entry>
    <entry key='easytrack.port'>5056</entry>
    <entry key='gpsmarker.port'>5057</entry>
    <entry key='khd.port'>5058</entry>
    <entry key='piligrim.port'>5059</entry>
    <entry key='stl060.port'>5060</entry>
    <entry key='cartrack.port'>5061</entry>
    <entry key='minifinder.port'>5062</entry>
    <entry key='haicom.port'>5063</entry>
    <entry key='eelink.port'>5064</entry>
    <entry key='box.port'>5065</entry>
    <entry key='freedom.port'>5066</entry>
    <entry key='telic.port'>5067</entry>
    <entry key='trackbox.port'>5068</entry>
    <entry key='visiontek.port'>5069</entry>
    <entry key='orion.port'>5070</entry>
    <entry key='riti.port'>5071</entry>
    <entry key='ulbotech.port'>5072</entry>
    <entry key='tramigo.port'>5073</entry>
    <entry key='tr900.port'>5074</entry>
    <entry key='ardi01.port'>5075</entry>
    <entry key='xt013.port'>5076</entry>
    <entry key='autofon.port'>5077</entry>
    <entry key='gosafe.port'>5078</entry>
    <entry key='tt8850.port'>5079</entry>
    <entry key='bce.port'>5080</entry>
    <entry key='xirgo.port'>5081</entry>
    <entry key='calamp.port'>5082</entry>
    <entry key='mtx.port'>5083</entry>
    <entry key='tytan.port'>5084</entry>
    <entry key='avl301.port'>5085</entry>
    <entry key='castel.port'>5086</entry>
    <entry key='mxt.port'>5087</entry>
    <entry key='cityeasy.port'>5088</entry>
    <entry key='aquila.port'>5089</entry>
    <entry key='flextrack.port'>5090</entry>
    <entry key='blackkite.port'>5091</entry>
    <entry key='adm.port'>5092</entry>
    <entry key='watch.port'>5093</entry>
    <entry key='t800x.port'>5094</entry>
    <entry key='upro.port'>5095</entry>
    <entry key='auro.port'>5096</entry>
    <entry key='disha.port'>5097</entry>
    <entry key='thinkrace.port'>5098</entry>
    <entry key='pathaway.port'>5099</entry>
    <entry key='arnavi.port'>5100</entry>
    <entry key='nvs.port'>5101</entry>
    <entry key='kenji.port'>5102</entry>
    <entry key='astra.port'>5103</entry>
    <entry key='homtecs.port'>5104</entry>
    <entry key='fox.port'>5105</entry>
    <entry key='gnx.port'>5106</entry>
    <entry key='arknav.port'>5107</entry>
    <entry key='supermate.port'>5108</entry>
    <entry key='appello.port'>5109</entry>
    <entry key='idpl.port'>5110</entry>
    <entry key='huasheng.port'>5111</entry>
    <entry key='l100.port'>5112</entry>
    <entry key='granit.port'>5113</entry>
    <entry key='carcell.port'>5114</entry>
    <entry key='obddongle.port'>5115</entry>
    <entry key='hunterpro.port'>5116</entry>
    <entry key='carcell.port'>5114</entry>
    <entry key='obddongle.port'>5115</entry>
    <entry key='hunterpro.port'>5116</entry>
    <entry key='raveon.port'>5117</entry>
    <entry key='cradlepoint.port'>5118</entry>

</properties>

`

**Comment by tananaev** [comment]
I have removed your config because nobody going to review the whole file. If you made some changes there, you should just post those changes.

Also, it looks like you are not using latest release. I would recommend to upgrade.

**Comment by evigra** [comment]
thanks friend
