### ISSUE TITLE
Position ID in devices table sometime is Null or zero

### ISSUE THREAD

**Issue by hoaadv** [traccar/traccar#3559]
I deploy the traccar server on a VPS-Windows and using with MySQL database.
System working with some mobile phones as clients.

But sometime the positionId don't appear in device record, so I can't locate where current device on the map. And one serious problem that the totalDistance attribute is reset to 0 after that.

This problem sometime happen with some devices not all devices.

Thank you for your help.

**Comment by tananaev** [comment]
You should probably check logs and trace all the messages for the devices that have problems.

**Comment by hoaadv** [comment]
I think problem is here!
Do you have any suggestion to solve this problem?

Thanks

> 2017-10-01 15:24:12  WARN: Incorrect string value: '\xE1\xBA\xA3ng ...' for column 'address' at row 1 - SQLException (... < QueryBuilder:477 < DataManager:327 < DefaultDataHandler:27 < ...)
2017-10-01 15:24:12  WARN: Incorrect string value: '\xC6\xA1n, B...' for column 'address' at row 1 - SQLException (... < QueryBuilder:477 < DataManager:327 < DefaultDataHandler:27 < ...)

**Comment by tananaev** [comment]
Errors like that usually mean incorrect database encoding. It has been discussed a few times before. Use search.
