### ISSUE TITLE
Enabling DayLight Saving for NewZealand Timezone

### ISSUE THREAD

**Issue by conqsys** [traccar/traccar#3560]
How do we enable DayLight saving for New Zealand timezone?

**Comment by tananaev** [comment]
You don't need to enable anything. If you browser is configured to correct timezone, everything will work automatically.

By the way I live in New Zealand and everything works perfectly.

**Comment by conqsys** [comment]
actually in Device Table last heartbeat is stored in LastContactDate column, which is 1hr past but my server timezone is correct and showing correct time

**Comment by tananaev** [comment]
What is LastContactDate column?
