### ISSUE TITLE
Please add ET-01 Protocol

### ISSUE THREAD

**Issue by dargh1** [traccar/traccar#357]
Hi, Tananaev,
Could please add protocol for this tracker: Easy track ET-01.
(How can I send the communication protocol to you?).

Thanks, this is truly great work....I love it.
Dargh

**Comment by lupearljam** [comment]
How to decode speeds like this 
7a44 -> 31300 -> 31300 / 100.0 -> '313km '?

**Comment by tananaev** [comment]
@lupearljam, please don't resurrect issues from 2013. Create a new one if you have a question or problem.

**Comment by WellingtonGAlves** [comment]
Good afternoon, would you have the protocol to communicate with the platform yet? Thank you very much in advance.

**Comment by tananaev** [comment]
You can find protocol documentation here:

https://www.traccar.org/protocols/

**Comment by WellingtonGAlves** [comment]
Thank you very much Friend !!!
