### ISSUE TITLE
"Unknown" status

### ISSUE THREAD

**Issue by mastergso** [traccar/traccar#3570]
Hello, is there a configuration to pass from "online" to "offline" status directly? Or to reduce the "unknown" status to few seconds? Thanks.

**Comment by tananaev** [comment]
It can already transition from green to red directly.

**Comment by mastergso** [comment]
Hello, thanks for your reply. I've some devices which close TCP socket after sending the position. They send the position every 1 minute when the vehicle is moving. When the vehicle is in parking do not send positions because are off. 

In default.xml I've put:

1) <entry key='status.ignoreOffline'>[protocol]</entry>
OK devices now stay in the green status when the vehicle is moving. Works perfectly.

2) <entry key='status.timeout'>300</entry>
OK devices now terminates the green status after 5 minutes. Works perfectly. But after 5 minutes the "unknown-yellow" status appear for hours. 

Assuming that '[protocol].timeout' affect the yellow status, I've tried to set:
<entry key='[protocol].timeout'>0</entry>
<entry key='[protocol].timeout'>1</entry>
<entry key='[protocol].timeout'>10</entry>
<entry key='[protocol].timeout'>300</entry>
<entry key='[protocol].timeout'>310</entry>
But none changes. This option seems to have no impact in any way. I've also tried to deactivate the 'status.timeout' assuming a conflict with this option, but the devices stay green-Online for hours.

I would like to avoid the "unknown-yellow" status for hours, because makes the end-users a bit confused. How to get the transition from green (Online status) to red (Offline status) if the server do not receive positions for 5 minutes? Or any other option to remove the "unknown-yellow" status?

Thanks.

**Comment by mastergso** [comment]
Hello, thanks for your reply. 
I've some devices which close TCP socket after sending the position. They send the position every 1 minute when the vehicle is moving. When the vehicle is in parking do not send positions because are off. 

In default.xml I've put:

1) entry key='status.ignoreOffline'>[protocol]<
OK devices now stay in the green status when the vehicle is moving. Works perfectly.

2) entry key='status.timeout'>300<
OK devices now terminates the green status after 5 minutes. Works perfectly. But after 5 minutes the "yellow-Unknown" status appear for hours. 

Assuming that '[protocol].timeout' affect the yellow-Unknown status, I've tried to set:
entry key='[protocol].timeout'>0<
entry key='[protocol].timeout'>1<
entry key='[protocol].timeout'>10</entry
entry key='[protocol].timeout'>300</entry
entry key='[protocol].timeout'>310</entry
But none changes. This option seems to have no impact in any way. I've also tried to deactivate the 'status.timeout' assuming a conflict, but in this case the devices stay in green-Online status for hours.

I would like to avoid the "yellow-Unknown" status for hours, because makes the end-users a bit confused. How to get the transition from green-Online status to red-Offline status when the server do not receive positions for 5 minutes? 
Or any way to remove the "Yellow-unknown" status?

Thanks. 
Giacomo.

**Comment by mastergso** [comment]
Thanks for the answer. But how to get this transition without a very long "yellow-Unknown" status in the middle? I've some locators with TK103 protocol. They close TCP socket after sending the position and are OFF while parking.

So I've put in default.xml file the options "status.ignoreOffline" and "status.timeout">300< to get "green-Online status" stable and reliable when the vehicle is moving. But after 5 minutes with no positions, the status changes to "yellow-Unknown" for a long time.

Do the options "[protocol].timeout" and/or "server.timeout" works for TK103? I've tried them but doesn't change anything. Which other solution to pass directly from "green-Online" to "red-Offline" without a very long yellow-Unknown status in the middle?

Thanks.
Giacomo.

**Comment by tananaev** [comment]
Red status means that device disconnected from the server. If your device disconnects, you will get it without any delays.

**Comment by idxn** [comment]
@tananaev i intend to have my traccar setup behind the nginx as a tcp proxy because i don't want to expose my traccar server to the internet so i would like to make sure that there is no way we can avoid this problem in this setup through the traccar configs and i need to find the other way around.

**Comment by tananaev** [comment]
What devices are you planning to use? Most devices use raw TCP and UDP protocols, not HTTP.

**Comment by idxn** [comment]
Raw TCP and using nginx as a tcp proxy

**Comment by tananaev** [comment]
I was not aware of such functionality. Does it combine multiple connections into one? If that's the case, it won't work for large number of protocols and connection status of course won't work either.

**Comment by idxn** [comment]
Thanks for the clarification, Anton. I'll take a look at the nginx side what can be done or maybe use other proxy solution.
