### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by nelledge83** [traccar/traccar#3571]
I saw a post telling a user to post requests on GitHub so here i am....
I currently use FleetLocate.com to track my fleet and I am slowly migrating over our fleet to Traccar. I love it in general but I fell there is some small things that could make it a lot better for everyone.
1) Add ability to **click** on the vehicle on the map and get a menu of options like
   a) Show Trip
   b) Set Driver
   c) Edit Vehicle
2) Add ability to **hover** over vehicle and display current status of vehicle including speed or how long they have been stopped.
3) Make the vehicle icons dynamic, show one color or shape if moving and another if stopped.
4) Ability to toggle off the labels on geo fences but still show them on the map. 
5) Add the ability to click on geo fences to edit them
6) Auto hide the geo fence labels once you zoom out so if you have alot of geo fences they dont cover the screen with labels.
7) Add the ability to have more then 1 custom map.
I know using this for free is a blessing and I really appreciate all your support.

**Comment by gpproton** [comment]
In my opinion your suggestions are really cool, if implemented.

**Comment by tananaev** [comment]
Some of your requests have already been suggested before. I would recommend you to express your interest on those features.

**Comment by tananaev** [comment]
Please break down into separate requests. Also, most of them should probably be in the web app repository.
