### ISSUE TITLE
flespi integration

### ISSUE THREAD

**Issue by janbartnitsky** [traccar/traccar#3575]
Hello
Let's discuss the possibility of integrating [flespi](https://flespi.com) platform into traccar.
There are useful features that can be integrated to traccar via flespi [REST API](https://flespi.io/docs).

**Comment by tananaev** [comment]
I would recommend to discuss features separately. Do you have a list of features that you want to integrate? Any technical details on you want to integrate them?

**Comment by ashchurko** [comment]
The simpliest way is to link one flespi channel (by specifying token and channel id) into traccar protocol instance and communicate with it via HTTP REST API. 

But give me few days to look into the architecture and source code of traccar and I will be back with the proposition.

**Comment by ashchurko** [comment]
Anton, please review pull request above by @nadezhdamosunova as a proposed integration between traccar and flespi. The poll method we implemented is different to current tcp/udp connections listeners protocols, so we are open for any feedback.

**Comment by tananaev** [comment]
Flespi has been support for a while.
