### ISSUE TITLE
how  to install traccar source code via cmd in windows

### ISSUE THREAD

**Issue by sureshsiddhu** [traccar/traccar#3576]

**Comment by sureshsiddhu** [comment]
i  installed all jars via cmd using mvn package command and build successfully completed.then how to start server using cmd.


thank  you

**Comment by tananaev** [comment]
You run jar file with config file as an argument.

**Comment by sureshsiddhu** [comment]
thank you server is running perfectly.
but traccar-web is  not showing. how  to execute traccar web using cmd
can you pls send manual for  that one

**Comment by tananaev** [comment]
Have you downloaded and compiled it?

**Comment by sureshsiddhu** [comment]
i did  it but   only spinner  loading

login page is not showing  anything

**Comment by sureshsiddhu** [comment]
i dont know how  to compile traccar-web 
can you explain

**Comment by tananaev** [comment]
Check minify shell script.
