### ISSUE TITLE
GT06 Odometer Mismatch

### ISSUE THREAD

**Issue by SRIKAAA** [traccar/traccar#3579]
```json
{"ignition":true,"status":70,"battery":3,"rssi":1,"ip":"27.97.175.218","distance":0.0,"totalDistance":9511030.2}
{"sat":1,"ignition":true,"ip":"27.97.175.218","distance":14.4,"totalDistance":9511044.6}
{"ignition":false,"status":68,"battery":4,"rssi":1,"ip":"27.97.175.218","distance":0.0,"totalDistance":9511044.6}
{"sat":12,"ignition":false,"odometer":2361754,"ip":"27.97.175.218","distance":32.98,"totalDistance":9511077.58}
{"sat":0,"ignition":false,"status":148,"battery":7,"rssi":1,"ip":"27.97.175.218","distance":7.05,"totalDistance":9511084.63}
{"ignition":true,"status":70,"battery":4,"rssi":2,"ip":"27.97.175.218","distance":0.0,"totalDistance":9511084.63}
{"sat":0,"ignition":true,"ip":"27.97.175.218","distance":1.24,"totalDistance":9511085.87}
{"ignition":false,"status":64,"battery":4,"rssi":1,"ip":"27.97.175.218","distance":0.0,"totalDistance":9511085.87}
{"sat":15,"ignition":false,"odometer":2361762,"ip":"27.97.175.218","distance":11.44,"totalDistance":9511097.31}
```

Above is the sequential data that we are receiving from GT06 device. the internal mileage calculation is coming only when the ignition is OFF.
Kindly confirm what could be the reason.

**Comment by tananaev** [comment]
You need to provide full position model, not just attributes.

**Comment by SRIKAAA** [comment]
[FullLog_traccar.xlsx](https://github.com/tananaev/traccar/files/1378137/FullLog_traccar.xlsx)

Kindly find the attached log requested for above issue.
GT06 device with new firmware is sending mileage (odometer) in every packet but why traccar service is storing it randomly.

Refer to Highlighted Yellow rows.

Kindly provide a solution for the same.

Sent Email also

**Comment by tananaev** [comment]
Please provide proof that your device sends odometer in every packet.
