### ISSUE TITLE
Not able to get device details of particular id 

### ISSUE THREAD

**Issue by ramesh456** [traccar/traccar#3580]
I am using traccar server 3.11 & I am using following api to get particular device details:

http://localhost:8082/api/devices?id=5 but i am getting all device list. 

i have also tried this -> http://localhost:8082/api/devices?all=false&id=5 but still it gives me list of all devices !

How to get only particular device details ?

**Comment by tananaev** [comment]
It's not possible on 3.11.

**Comment by tananaev** [comment]
It is possible now.
