### ISSUE TITLE
GT02 receiving many invalids

### ISSUE THREAD

**Issue by evigra** [traccar/traccar#3584]
Goodnight.
I have a GT02, and it is configured to port 5002.
but I am receiving many invalids.

What could it be??

**Comment by tananaev** [comment]
What invalids? Where are logs? What version of Traccar?

**Comment by evigra** [comment]
Goodnight.
Traccar 3.7

>2017-10-18 01:36:58 DEBUG: [794841E7: 5002 < 187.210.230.179] HEX: 283032373034343937353533304250303033353532323730343439373535333048534f31393929
>2017-10-18 01:36:58 DEBUG: [794841E7: 5002 > 187.210.230.179] HEX: 283032373034343937353533304150303131393929
>2017-10-18 01:36:59 DEBUG: [D89771C0: 5001 < 187.210.230.30] HEX: 696d65693a3836343138303033323335383834332c747261636b65722c3137313031383039333635$
>2017-10-18 01:36:59  INFO: [D89771C0] id: 864180032358843, time: 2017-10-18 01:36:53, lat: 19.09060, lon: -104.28381, speed: 0.0, course: 0.0
>2017-10-18 01:37:01 DEBUG: [C2CA81C2: 5001 < 187.210.99.8] HEX: 696d65693a3836383638333032393333343437352c747261636b65722c313731303138303933373030$
>2017-10-18 01:37:01  INFO: [C2CA81C2] id: 868683029334475, time: 2017-10-18 01:36:56, lat: 19.05322, lon: -104.31460, speed: 0.0, course: 0.0
>2017-10-18 01:37:03 DEBUG: [D89771C0: 5001 < 187.210.230.30] HEX: 3836343138303033323335383834333b
>2017-10-18 01:37:03 DEBUG: [D89771C0: 5001 > 187.210.230.30] HEX: 4f4e
>2017-10-18 01:37:05 DEBUG: [F14F7044: 5001 < 200.68.138.36] HEX: 696d65693a3836383638333032373539313134322c747261636b65722c31373130313830393337303$
>2017-10-18 01:37:05  INFO: [F14F7044] id: 868683027591142, time: 2017-10-18 01:36:59, lat: 19.27641, lon: -103.73033, speed: 0.0, course: 0.0
>2017-10-18 01:37:09 DEBUG: [6AE2A865: 5001 < 200.68.138.73] HEX: 3836383638333032393336343538393b
>2017-10-18 01:37:09 DEBUG: [6AE2A865: 5001 > 200.68.138.73] HEX: 4f4e
>2017-10-18 01:37:10 DEBUG: [794841E7: 5002 < 187.210.230.179] HEX: 283032373034343937353533304252303031373130313841313931352e333135304e31303334332$
>2017-10-18 01:37:10  INFO: [794841E7] id: 027044975530, time: 2017-10-18 01:37:08, lat: 19.25525, lon: -103.73113, speed: 0.0, course: 0.0
>2017-10-18 01:37:10 DEBUG: [D3B5A5F8: 5001 < 187.210.230.130] HEX: 696d65693a3836343138303033323632353431352c747261636b65722c313731303138303933373$
>2017-10-18 01:37:10 DEBUG: [6230E38A: 5001 < 187.210.230.8] HEX: 696d65693a3836343138303033323633353031382c747261636b65722c31373130313830393337303$
>2017-10-18 01:37:10  INFO: [D3B5A5F8] id: 864180032625415, time: 2017-10-18 01:37:04, lat: 19.25742, lon: -103.73071, speed: 0.0, course: 0.0
>2017-10-18 01:37:10  INFO: [6230E38A] id: 864180032635018, time: 2017-10-18 01:37:05, lat: 19.08429, lon: -104.30333, speed: 0.0, course: 0.0
>2017-10-18 01:37:15 DEBUG: [C2FF77A9: 5001 < 200.68.138.214] HEX: 696d65693a3836383638333032373539303032392c747261636b65722c3137313031383039333731$
>2017-10-18 01:37:15  INFO: [C2FF77A9] id: 868683027590029, time: 2017-10-18 01:37:08, lat: 19.10845, lon: -104.26300, speed: 0.0, course: 0.0
>2017-10-18 01:37:17 DEBUG: [BBB2A842: 5001 < 187.210.230.43] HEX: 696d65693a3836343138303033323639313532342c747261636b65722c3137313031383039333731$
>2017-10-18 01:37:17  INFO: [BBB2A842] id: 864180032691524, time: 2017-10-18 01:37:15, lat: 19.25546, lon: -103.73138, speed: 2.9, course: 339.0
>2017-10-18 01:37:20 DEBUG: [BBB2A842: 5001 < 187.210.230.43] HEX: 696d65693a3836343138303033323639313532342c747261636b65722c3137313031383039333731$
>2017-10-18 01:37:20  INFO: [BBB2A842] id: 864180032691524, time: 2017-10-18 01:37:17, lat: 19.25551, lon: -103.73138, speed: 2.9, course: 319.2
>2017-10-18 01:37:20 DEBUG: [C57879DF: 5002 < 187.216.136.11] HEX: 283032373034343937353134324252303031373130313841313931362e363038304e31303334362e$
>2017-10-18 01:37:20  INFO: [C57879DF] id: 027044975142, time: 2017-10-18 01:37:18, lat: 19.27680, lon: -103.78091, speed: 0.0, course: 0.0
>2017-10-18 01:37:20 DEBUG: [3F4A43C6: 5002 < 200.68.138.140] HEX: 283032373034343937343936324250303033353532323730343439373439363248534f31393929
>2017-10-18 01:37:20 DEBUG: [3F4A43C6: 5002 > 200.68.138.140] HEX: 283032373034343937343936324150303131393929



![captura de pantalla de 2017-10-17 20-38-21](https://user-images.githubusercontent.com/1538600/31697122-3753a9ae-b37b-11e7-8869-b38d42fa1587.png)

**Comment by tananaev** [comment]
First of all, can you please format logs properly. Secondly your text editor has cut most of the useful data from the logs.

**Comment by evigra** [comment]
An apology, update the log

**Comment by tananaev** [comment]
I have looked at a couple of messages and they are valid. I guess your log doesn't match your SQL results, or you are using old version or something is misconfigured.
