### ISSUE TITLE
EasyTrack ET01 (Cut engine power) GPRS Commands

### ISSUE THREAD

**Issue by gabrieldev30** [traccar/traccar#3588]
Hello, I would like to know if traccar has the cut engine power command built-in

**Comment by tananaev** [comment]
No.

**Comment by gabrieldev30** [comment]
Can you implement it on traccar? I read the protocol's doc, but It doesn't seem to work.

I tried cutting the fuel with this hexadecimal: 0x2A45542C3335383135353130303036383239332C46442C4631593123 , but nothing happened.

**Comment by tananaev** [comment]
Please provide documentation.

**Comment by tsmgeek** [comment]
Seems there has been some discussion on the forum for this unit.

https://www.traccar.org/forums/topic/easytrack-et-01/
