### ISSUE TITLE
Hide state field attributes

### ISSUE THREAD

**Issue by MarceloMJM** [traccar/traccar#3590]
Master Anton how to hide device protocol in attributes field?

**Comment by tananaev** [comment]
In the next release there will be `ui.hidePositionAttributes` to hide attributes, but I'm not sure if it works for protocol because it's part of the base model.

**Comment by MarceloMJM** [comment]
thank you.

**Comment by tananaev** [comment]
In the modern app attributes are configurable directly in preferences.
