### ISSUE TITLE
Computed Attributes - unable remove attribute

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3591]
This in relation to the JEXL in #3550

I have looked at the code and from my understanding there is no way to unset an attribute, I may be mistaken though.
If you return null it leaves it as is, if you return false and type is String then it just becomes a string, for other types it gets cast.
I propose a way to return a value that means to unset the attr.
Obviously this presents an issue with Boolean type as how do you differentiate between true/false/null while also allowing unset.
What about using the return string "unset" this would remove the attribute completely and would work across all datatypes.

**Comment by tananaev** [comment]
I believe `null` should mean unset. I don't see any problem with boolean.

**Comment by tananaev** [comment]
@Abyss777, what do you think?

**Comment by tsmgeek** [comment]
https://github.com/tananaev/traccar/blob/master/src/org/traccar/processing/ComputedAttributesHandler.java#L99-L114
Null is just ignored and left as is.

Boolean return value would be fine for a string/number, but for a Boolean data type it would not work as false may be valid vs unset.

I need to specifically unset the 'alarm' attr.

**Comment by tananaev** [comment]
I still don't understand your point about boolean. False is false, null is null. I said null should unset the value.

**Comment by tsmgeek** [comment]
If you return null from jexl it does not change anything, there is a test to see if result is null and just returns position as it went in.

Look at L99. It seems if your expression returns null then the result is a literal null.

**Comment by tananaev** [comment]
Yes, that's why I'm proposing to unset it if the result is null. What I don't understand is what the problem with boolean.

**Comment by tsmgeek** [comment]
While it may be a good idea to use null, it would break any expressions that people have already written returning null when they do not want to change anything.
If you did use null to unset then how would someone make sure the value was not unset but no nothing to it, just pass the param back i assume, main point is backwards compatibility with existing installed base.
My problem with Boolean is based on the assumption that null is not changed to mean unset, leaving just True/False, if that is the case what do you use to unset.

**Comment by tananaev** [comment]
Yes, if you want to keep parameter you can use existing value.

**Comment by Abyss777** [comment]
Hello
The idea of computed attributes is not correct existed reported by device, but create new one based on reported. As I understand philosophy of traccar we decoding "known" attributes in common way and they are standardized, it is not needed correct them.

I believe raw data should be leaved as is. Why it is needed to delete any attribute? Let them lay in DB.

**Comment by tananaev** [comment]
I agree in general, but what's the hard in adding option to remove attributes this way? It adds extra functionality that might be useful for some and I don't see any drawbacks. Do you?

**Comment by Abyss777** [comment]
I don't, we are creating flexible application. Why not to add it.
But I think we should make it switchable and disabled by default for backward compatiblity, what about `processing.computedAttributes.deleteOnNull` name for switch?

**Comment by tananaev** [comment]
I don't think we need to complicate it with configuration parameter. It's a relatively new feature, so I wouldn't be worried too much about backward compatibility.

**Comment by tsmgeek** [comment]
Why not instead put flag on the command itself, on update the attributes that currently exist will have flag set to indicate its an old type. New ones don't have this flag.
The ui could have a toggle for this, put entry in log if it's an old attribute so users will check and update. 
Could end up with some fallout on issues if backwards compatability at least for a while is not supported, you already have issue about minor support tickets.

**Comment by tananaev** [comment]
I don't want to complicate code without any good reason. It's a new feature, so it means there is a very little chance that someone has implemented this corner case. Also, even if they did, it was not official documented behaviour (as far as I know).

**Comment by Abyss777** [comment]
Unfortunately https://www.traccar.org/documentation/computed-attributes/
> Empty result of computation (null, but not the empty string) will not be stored to position.

And it was in examples

**Comment by tananaev** [comment]
OK, but I still think we should change it. It just makes more sense for it to work this way.

**Comment by Abyss777** [comment]
OK. What do you think how to modify this example?
````
Fuel
adc1 ? adc1 * 0.065 : null
Number
````

**Comment by tsmgeek** [comment]
Use a keyword is not an awful fix to this, not nice but easiest to implement, only would cause issue if someone wanted to have a string field actually have that keyword.

**Comment by tananaev** [comment]
@Abyss777, I believe your example will look exactly the same. No changes needed. If ADC is not present and result is `null`, then Traccar would try to "unset" fuel parameter, but because it's not there in the first place result would be the same... no fuel parameter if no ADC value.

@tsmgeek, I don't see any good reason for implementing some hack like that. I would maybe understood if we had this functionality for many years and suddenly decided to change, but in our case it has been available for a few months, so I doubt it would cause any serious problems.

**Comment by Abyss777** [comment]
@tananaev 
Lets imagine `adc1` reported not in every position, we have to populate `fuel` via attribute copying, `fuel` will be deleted then.

**Comment by tananaev** [comment]
In that case you can copy `adc1` instead of fuel. A bit more data in the position attributes, but the result is pretty much the same.

**Comment by Abyss777** [comment]
Good, that is solution.

**Comment by tananaev** [comment]
I think we support removing attributes.
