### ISSUE TITLE
New Device/User/Group Notifications Problem

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3598]
I have just updated to latest code and rebuilt both server/web code.

1. On tables which have userid/notificationid etc. there is no PK on the two columns together, this should be done to prevent duplicates from ever happening at a DB level but also some SQL editors will not allow removing rows without PK index. This PK issue seems to exist elsewhere too. Some tables had Index created on a single column and FKs created another, but instead of individual index a PK across two columns would work better.

2. If you remove a User Notification, it is removed from notifications table but not from the user_notifications table or device_notifications table, not tested group_notifications. This ends up causing a NullPointerException showing whenever packets come in from devices.
`2017-10-21 20:27:55  WARN: [ED4E2140] error - NullPointerException (NotificationManager:46 < *:68 < *:97 < ConnectionManager:109 < BaseProtocolDecoder:220 < ...)`

**Comment by tananaev** [comment]
@Abyss777, can you please check.

**Comment by tsmgeek** [comment]
PS also the Web gui does not pull latest notifications from system when dialog is opened on 2nd attempt, could cause issues if multiple users manage a single account.

**Comment by Abyss777** [comment]
@tsmgeek 
Are you sure, new schema was correctly applied? From this line 
to the end https://github.com/tananaev/traccar/blob/master/schema/changelog-3.15.xml#L86

PS. web gui does not pull again many other things also.

**Comment by tsmgeek** [comment]
@Abyss777 
Tracked down to default schema on DB is MyISAM on MySQL 5.6 not InnoDB (5.7 default), yes default could be changed but there are many other databases on this server, MySQL does not allow setting default engine on a per database level unfortunately. It does not fail as on MyISAM it interprets the FKC as an Index.
I have manually applied all the FKC to the DB and it works now.

I still think it would be a good idea to create a PK across the two columns.

I propose a few solutions to assist others.
1. Change previous changesets as per correct liquibase method and add the following at the top to force innodb on all new installations.
```
    <sql dbms="mysql">
		SET default_storage_engine=INNODB;
    </sql>
```
2. Use the following modify SQL on each create table statement specific to MySQL.
http://www.liquibase.org/documentation/modify_sql.html.
