### ISSUE TITLE
Feature: Saved Commands - Custom - Filter by protocol

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3601]
Limit custom saved commands by device protocol.

Non-custom commands are filtered

**Comment by Abyss777** [comment]
As I understand you correctly it is already implemented, `custom` are always shown in the list, other types are shown only if they are supported by current device protocol.

**Comment by tsmgeek** [comment]
@Abyss777 I noticed that types other than 'custom' are filtered correctly.
An extra field when creating custom commands to enter a protocol name would allow filtering these commands to a specific protocol else you could have 'Stats' on two different trackers but they would be selectable for either even though the protocol is incompatible.
Its a nicety more than anything.

**Comment by Abyss777** [comment]
I see it as implementing additional field `protocol` (or attribute) to `Command` model. If it is empty, command can be sent to any device.

But still, I think it is better to implement commands as native than make workarounds for `custom`. @tananaev what do you think?

**Comment by tsmgeek** [comment]
I think its too limiting to force all commands as native (if by native you mean within the protocol encoder), there are lots of un-documented, little used commands, or ones which are very specific which only may be used during setup etc.

**Comment by Abyss777** [comment]
Lets look from other side...
I believe you want limit commands by protocol to avoid mistakes by ordinary users. How frequently they use un-documented, little used commands?

**Comment by tsmgeek** [comment]
Most of the time I preset the commands for them on their account and assign to the correct trackers. 

Im more one that tries to anticipate a problem rather than wait for it to happen.
