### ISSUE TITLE
Delayed Events that can be cancelled

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3602]
Is there a way currently within the code to implement delayed events that can be canceled?

This is the scenario.
User moves bike to unlock it a few seconds before turning it on, I would prefer to suppress the received vibration event for X seconds, if IGN event comes in within that time it will/can cancel the delayed vibration event but still submit the IGN event. This would be to prevent multiple alerts all being sent out within seconds of each-other. Could also be used to suppress multiple events for exactly the same thing within given time frames etc.

**Comment by tananaev** [comment]
I remember that there is some logic for suppressing continuous speeding events, but I'm not sure if it would help in your case.

**Comment by tsmgeek** [comment]
Thanks, that may put some ideas on how it could be done.

From AlertEventHandler store the alert/position and set timer, timer can be cancelled by subsequent IgnitionEventHandler, if timer is fired then it could refire off the AlertEventHandler with the stored position.

**Comment by tananaev** [comment]
Closing as there doesn't seem to be enough interest in something like this.
