### ISSUE TITLE
Data without location support in Traccar

### ISSUE THREAD

**Issue by TrackerT** [traccar/traccar#3605]
Hello there, 

I want to know what's the current status of data without location support in traccar.

On issue https://github.com/tananaev/traccar/issues/454#issuecomment-37083249 you mention that there was no support for this in traccar (in 2014)

By the end of the issue https://github.com/tananaev/traccar/issues/454#issuecomment-217295774 you mention that you implemented support for codec 12  (in 2016) - which is some sort of data without location

Can you please explain in detail how is codec 12 implemented in traccar and where should the data be seen - in the database at least

I understand that implementing this into the web interface is difficult as it is not well defined and varies but having it within the database along with the attributes for example, it would be very useful.

**Comment by tananaev** [comment]
It has been supported for a while now. Basically last known location is appended to any data that doesn't have a location.

**Comment by TrackerT** [comment]
I have tried to send message from Garmin but i haven't found anything in the attributes column so i thought that was the reason. But you clarified this, thanks!

Please tell me in which attributes column i should find the Garmin message, or how does it work. 

Thank you

**Comment by tananaev** [comment]
I'm not sure. I've never used Garmin.
