### ISSUE TITLE
Feature - Delayed geofence based on multiple tracks

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3609]
Not sure if already possable.

Ive noticed that if I have set relatively small geofence, sometimes the GPS track can move down the road for one more position updates, when this happens the platform sends event out but in reality it has not moved at all.
Is there a way to put a soft delay so that it would ignore the first X positions after a geofence exit before it would alert. This would stop false positives due to wondering GPS signal or when the device may switch over to LBS location momentarily.

**Comment by tananaev** [comment]
What about increasing geofence size or enable filtering? Either should solve the problem.

**Comment by tsmgeek** [comment]
I am going to try filtering, the jump was over 50m, it is rare its has happened but happened non the less.

**Comment by tananaev** [comment]
Again, it doesn't seem like it's a common issue and there are ways around it, so closing.
