### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by juanjorgebm** [traccar/traccar#3610]
Have you thought to add this feature?

**Comment by tananaev** [comment]
You should probably explain what you mean by that.

**Comment by juanjorgebm** [comment]
“A Progressive Web App uses modern web capabilities to deliver an app-like user experience"

I think could be great to have push notifications on our phones and some other capabilities, like work offline and "add an icon to homescreen", this tecnology has.

I guess we would not need a native app if the web has this feature.

I haven't read a lot about Progressive Web App but it just some javascript files so I don't think we have problems to add it,

**Comment by tsmgeek** [comment]
There is no support for it on iOS currently.
Essentially I think PWAs are a bundle of tools like Chome Service Workers and more integration with the device.
PWA is similar to hybrid apps like PhoneGap/Ionic

**Comment by juanjorgebm** [comment]
Yes but I read and article about Apple just started to work on that
[https://cloudfour.com/thinks/apple-starts-work-on-progressive-web-apps/](url)

**Comment by tananaev** [comment]
Already available with the modern app.

**Comment by juanjorgebm** [comment]
Awesome, thanks
