### ISSUE TITLE
SMS without SMPP

### ISSUE THREAD

**Issue by veniciosn** [traccar/traccar#3613]
Our service to send SMS use the following:

http://54.173.24.177/painel/api.ashx?action=sendsms&lgn=LOGIN&pwd=PASS
&msg=Message%20ToSend&numbers=3199999999

They do not have smpp support. Can I use this URL to send SMS on events?

Thanks for the great work.

**Comment by tananaev** [comment]
Unfortunately not.

**Comment by tsmgeek** [comment]
Could the SMS provider be altered through config so a choice could be made between SMPP/HTTP POST?
What I mean is would you object if a change was made to allow for this if the module was created?

**Comment by tananaev** [comment]
No, I don't have any objections to that.

**Comment by filosganga** [comment]
Would be good to support AWS SNS as well

**Comment by joseph-santos** [comment]
hello someone can help me to install a q24 modems to the traccar platform

**Comment by tananaev** [comment]
We support HTTP-based SMS providers and AWS SNS.
