### ISSUE TITLE
Feature Request - Delayed Geocoding

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3616]
For the most part its not really required to know the road name on each and every track of a journey, only the ones you want to know.
I was thinking of a way that geocoding can be turned off but when the user requests a specific position via the api it would geocode at that point.
Problems with this approach would be with reporting etc but it could be done at report time etc.

**Comment by tsmgeek** [comment]
#3632

**Comment by hatami98** [comment]
+1 I would like to have this feature. Do you manage to get it working @tsmgeek ?

**Comment by tsmgeek** [comment]
@hatami98 im not writing it @Abyss777 is doing it, currently a PR

**Comment by tananaev** [comment]
This is already supported.
