### ISSUE TITLE
Filter issue

### ISSUE THREAD

**Issue by perseptron** [traccar/traccar#3618]
Hello Anton,
There is a little mistake in processing filtering position.
I use 3.14 ver. of program with such set of filters:
 ```
<entry key = 'filter.enable'>true</entry>
   <entry key = 'filter.duplicate'>true</entry>
   <entry key = "filter.distance">50</entry>
   <entry key = 'filter.skipLimit'>3600</entry>
   <entry key = "filter.maxSpeed">80</entry>
   <entry key = "filter.skipAlarms">true</entry>
   <entry key = 'filter.future'>600</entry>
   <entry key = 'filter.zero'>true</entry>
```
So when my teltonika 1125 start after long time of not working it send zero coordinates. These coordinates have to be filtered because of filter.zero = true, but they are not, because of skipLimit. 
As a result I have to correct device distance from time to time.

**Comment by perseptron** [comment]
Yes I need (maybe not only me) to disable skiplimit for zero coordinates only. How can I do that?

**Comment by tananaev** [comment]
Unfortunately it's not possible at the moment.

**Comment by perseptron** [comment]
It seems to me that some kind of filters can't be skipped. I believe they are  - maxspeed, future and zero. They are wrong positions, so do not need to write them out anyway. It would be nice if in new version you take it into account. Thank you.

**Comment by tananaev** [comment]
What about `filter.approximate` and `filter.skipAttributes`?

**Comment by perseptron** [comment]
Do you mean, you want create new filter - filter.skipAttributes with list of all filters that can be skipped? If so, I think that decision will solve the problem.

**Comment by tananaev** [comment]
It has already been implemented.

**Comment by perseptron** [comment]
but what for that filters are? I can't find them in documentation...

**Comment by tananaev** [comment]
Those options are not documented yet. They are only in the code.
