### ISSUE TITLE
Map stop responding on IOS

### ISSUE THREAD

**Issue by ninioe** [traccar/traccar#3619]
When I open the web app in iOS 11 the map stop responding

**Comment by tananaev** [comment]
Please provide a video.

**Comment by tananaev** [comment]
How many devices do you have in your account?

**Comment by ninioe** [comment]
I have 3 devices in this account.
I never had this problem before.
I only noticed this issue after I updated the iOS to 11

**Comment by tananaev** [comment]
Possibly an OpenLayers issue. I would recommend to wait for the next release or try build from source code.

**Comment by ninioe** [comment]
Ok thanks

**Comment by wolfbgn** [comment]
It is an issue with iOS 11 not with Traccar or map. Apple say that devices that are repaired with non orriginal parts have touch screen problems. My iPhone is never been repaired and has that issue.

**Comment by djbo1982** [comment]
Hello... @tananaev i have the same problem with Traccar APP in iOS, the map of Google y frozen, i have 220 devices, but my serves is a beast, locate in Azure services. This happens only with Google maps, i change the layer to Microsoft and dont have the same problem

**Comment by ninioe** [comment]
Hi Anton,
I think that upgrading openlayers should fix this issue.

https://github.com/openlayers/openlayers/issues/7202

Thanks
Erez

**Comment by tananaev** [comment]
We have already done that.

**Comment by ninioe** [comment]
This is great.

Thanks

‫ב-3 בדצמ׳ 2017, בשעה 22:51, ‏‏Anton Tananaev ‏<notifications@github.com> כתב/ה:‬

**Comment by ninioe** [comment]
I have upgraded to the latest version but the map is still freezing on iOS 11

**Comment by tananaev** [comment]
We haven't released a new version yet. Next time check dates on the release.

**Comment by dot1q** [comment]
Does 4.6.4 have this issue?

**Comment by tananaev** [comment]
There is no such version. Where did you get this number?

**Comment by dot1q** [comment]
Wow, I'm sorry I am on the wrong project. Disregard everything I have said!
