### ISSUE TITLE
REST API works partly (w/o sessions)

### ISSUE THREAD

**Issue by philomatic** [traccar/traccar#3620]
Thanks for the great work of traccar!

~~For the REST API, I assume that everything should also work w/o session initiation (as REST'ly)?
In my installation (3.14-SNAPSHOT Docker) I have the current behavior:
GET calls to /api/devices, /api/groups, /api/server and so on are working nicely with basic http authentication.
But GET calls (haven't tried POST/PUT yet) to /api/commands are always returning:
`HTTP 404 Not Found - NotFoundException (...)`
or
`HTTP 405 Method Not Allowed - NotAllowedException (...)`
Why this? Am I assuming correct that this should not require sessions?~~

EDIT: See below.

Furthermore, trying to open a sessions by POST via swagger ui I get:

`"token": null,`

Is this intended?

**Comment by philomatic** [comment]
Ok, I'm sorry.

My version is not 3.14-Snapshot (as shown in console), but release 3.14 (with docker image magnaz/traccar).
So swagger.json on HEAD was simply wrong for me.
I will look further if anything of this is still an issue in HEAD, but don't think so.

However, the session thing `"token": null` still wonders me.

**Comment by tananaev** [comment]
Session endpoint returns user model. Token is part of user model. In your case it looks like you haven't set the token, so it's null.

**Comment by tsmgeek** [comment]
What is the internal code reason to need to go though the session setup? Cant it be altered so that token is accepted, stateless and just processes call.

**Comment by tananaev** [comment]
There is no specific reason. It was just implemented this way historically.

**Comment by tsmgeek** [comment]
I'm thinking oauth2 may be good, at the start just with password grant against existing DB and also an additional grant to use the token eventually it could auth against other.  Config flags to enable it and also to disable basic authentication etc.
