### ISSUE TITLE
sir 

### ISSUE THREAD

**Issue by NareshGautam007** [traccar/traccar#3623]
hey  i have a device tk103 
i have code of php but i am unable to configure tk103 
to our code please help me

**Comment by tananaev** [comment]
How is this related to Traccar project?

**Comment by djbo1982** [comment]
Sorry @tananaev i go to help to this man
@NareshGautam007 uses this to config the TK103 device:
With the phone, use the TXT message to send the initial command to the device, the origial password of the device is 123456, buy may can be other.
To initialized the device send:
begin123456
you go to received begin OK
send adminip123456 x.x.x.x 5001 where x.x.x.x is your server IP and the port 5001 is the port for your device
for time to report to server used
fix030s***123456  and this mean the device report to server every 30 second

with this basic command you can begin to see your devices in the traccar
