### ISSUE TITLE
Filter suggestion

### ISSUE THREAD

**Issue by perseptron** [traccar/traccar#3627]
Hello Anton,
with all  filters below, I still can't overcome coordinate jumps during parking, especcialy when vehicle in repair box.  So I suggest  small change to  filter.static - it would be nice to enable that filter when vehicle in geofence only. Thanks!
```xml
   <entry key = 'filter.enable'>true</entry>
   <entry key = 'filter.duplicate'>true</entry>
   <entry key = "filter.distance">50</entry>
   <entry key = 'filter.skipLimit'>3600</entry>
   <entry key = "filter.maxSpeed">80</entry>
   <entry key = "filter.skipAlarms">true</entry>
   <entry key = 'filter.future'>600</entry>
   <entry key = 'filter.zero'>true</entry>

   <entry key = "coordinates.filter">true</entry>
   <entry key = "coordinates.minError">50</entry>
```

**Comment by tananaev** [comment]
Distance filtering should be enough. You might need to increase threshold if jumps are bigger than 50 meters.

**Comment by perseptron** [comment]
yeah, but  will not the useful coordinates be skipped in this case? Because eg. when vehicle make turn, device send more data in short time period, also what do I get when vehicle move slowly in trafic jam? I am afraid of data be lost

**Comment by tananaev** [comment]
They might be, but I'm not sure if geofence filtering is a good universal solution.

**Comment by AymanElarian** [comment]
What about
   <entry key = "filter.distance">50</entry>
   <entry key = "filter.distance.condition">ignition=0,adc1!=oldadc1</entry> for example
?

**Comment by perseptron** [comment]
there are large part of devices that don't tell ignition state (and most of jums problem happens exactly with such devices) so I think geofence + filter.static is better. Not universal of course but better than filter.static only.
