### ISSUE TITLE
cached data updates ? persistence ?

### ISSUE THREAD

**Issue by AymanElarian** [traccar/traccar#3634]
hello , if i use traccar server with my own web client ,any way to update cached data 

via socket , for example ,if i add new device , add car to group , add driver , traccar update its local data after interval ? if yes, can i sent socket msg or kafka msg to server to update its data

also about persistence , if i restart server, it hold the last states of the unit ?

**Comment by tananaev** [comment]
There is no way to get notification about updates.

Of course data is persisted, except connection status.

**Comment by AymanElarian** [comment]
so how can you update cached data , every interval ?

**Comment by tananaev** [comment]
I guess. We never had a need to.

**Comment by AymanElarian** [comment]
so if a new unit add , its automatically insert in cached data ? 

Computed Attributes load at each msg ? or update each interval ?

for example i add fuel=adc1*500 at 12:00 am 
at 12:20 am i update it to adc1*400 it will reflect directly or it will keep the 1rst cached , or update it self at each X Interval ? ('again using custom web portal not the official one ')

**Comment by tananaev** [comment]
Server side obviously knows when something changed, so cache is always up-to-date.

**Comment by AymanElarian** [comment]
can i know how can server side know that something  updated ? internal socket ? hook methods in web api ?

**Comment by tsmgeek** [comment]
1. computed attributes as i understand it are calculated at the point the update is received from the external tracking device, the data is changed by the attributes and saved to the DB along with the position, it is not calculated on the fly or retrospectively
2. internally when you update attributes or many other settings there is a caching layer, so if you update an entry in the DB directly it does not reflect in the running instance, this is my experience and not sure how often it updates settings from the DB. But if you use the API then changes are reflected immediately from that point on.

This is my understanding of how it works to lower the DB accesses.

**Comment by AymanElarian** [comment]
@tsmgeek  thats exactly what am asking about , if reflect happing every interval or   only reflect throw API
