### ISSUE TITLE
filter maxspeed issue

### ISSUE THREAD

**Issue by perseptron** [traccar/traccar#3640]
Hello Anton,
I noticed unproperly behavior of maxspeed filter.
When device goes offline (for some reason) and vehicle still running, it colect all the data to internal memory. Then, say after 10 hours it goes online and start send collected data. Firstly it send current coordinates and then it send recorded data. When in that earlier data are some inproper coordinates they will not be filtered by maxspeed filter ( I think it's because filter compare that bad data with last data, time difference is large (and negative) in that case and data will not be thrown away).

**Comment by tananaev** [comment]
Yes, at the moment Traccar does not handle situation when device reports data in wrong order.

**Comment by tsmgeek** [comment]
@perseptron which tracker are you using?

**Comment by perseptron** [comment]
I have different devices, but the issue is on china tk-103

**Comment by pc500** [comment]
I've seen some Max speed > 100 MPH.  I'm not sure the cause (haven't investigated), but it's also on a China tk-103 that played back GPS positions from a while while it did not have cell coverage later in the day.  If the fixtime is used to calculate, it should work... but I don't know Traccar's logic.
