### ISSUE TITLE
Ignition on/off not receiving in cellocator device.

### ISSUE THREAD

**Issue by jackeychina** [traccar/traccar#3641]
Hi , 

I am running my cellocator device on 5033 port and its work perfect with speed , location but its not showing ignition attributes ! 

![tr1](https://user-images.githubusercontent.com/29410200/32823565-aba1db16-ca03-11e7-8fc1-ab00306b9a27.PNG)

![tr2](https://user-images.githubusercontent.com/29410200/32823582-b7e20252-ca03-11e7-8daa-ce8ce8504aff.PNG)

**Comment by tananaev** [comment]
Ignition is not supported for this particular protocol yet.

**Comment by jackeychina** [comment]
Ok Thanks.

**Comment by jackeychina** [comment]
Is there any way to implement ignition on/off in this protocol ?

**Comment by tananaev** [comment]
It should be possible if your device reports that information.

**Comment by jackeychina** [comment]
Yes my device sends that information.

**Comment by jackeychina** [comment]
Any update on this ?

**Comment by tananaev** [comment]
We would need protocol documentation and HEX message samples.

**Comment by luisfusim** [comment]
https://github.com/Drivetech/cellocator-parser
This library is working perfect 

`const parseIO = bytes21To24 => {
  const byte21 = core.hex2bin(bytes21To24.substring(0, 2));
  const byte22 = core.hex2bin(bytes21To24.substring(2, 4));
  const byte23 = core.hex2bin(bytes21To24.substring(4, 6));
  const byte24 = core.hex2bin(bytes21To24.substring(6, 8));
  return {
    unlock: byte21[0] === '0',
    sos: byte21[1] === '0',
    driving: byte21[2] === '0',
    shock: byte21[6] === '0',
    door: byte21[7] === '0',
    ignition: byte22[0] === '1',
    accelerometer: byte22[1] === '1',
    lock: byte22[5] === '0',
    gpsPower: byte23[4] === '1',
    gradualStop: byte23[5] === '1',
    siren: byte23[6] === '1',
    cfeOut1: byte23[7] === '1',
    charge: byte24[0] === '1',
    standardImmobilizer: byte24[2] === '1',
    blinker: byte24[4] === '1',
    ledOut: byte24[7] === '1'
  };
};`
