### ISSUE TITLE
traccar server is crashing

### ISSUE THREAD

**Issue by RakeshBhandarkar** [traccar/traccar#3644]
Hi,

My server is crashing daily and there is no logs to show any cause of the crash. The application is crashing daily night.

Below are the logs written,
tracker-server.log.20171118:
```
2017-11-18 21:45:03  INFO: [C04FEF40] id: 351608083320528, time: 2017-11-18 21:45:01, lat: 24.05744, lon: 75.06733, speed: 9.7, course: 240.0
2017-11-18 21:45:12 DEBUG: [C04FEF40: 5023 < 223.184.50.50] HEX: 78781f12110b12100f0bca0294c184080dc6e00b551301945d714a007e5f00fca78c0d0a
2017-11-18 21:45:12 DEBUG: [C04FEF40: 5023 > 223.184.50.50] HEX: 78780512000c68c80d0a
2017-11-18 21:45:12  INFO: [C04FEF40] id: 351608083320528, time: 2017-11-18 21:45:11, lat: 24.05739, lon: 75.06700, speed: 5.9, course: 275.0
2017-11-18 21:45:32 DEBUG: [C04FEF40: 5023 < 223.184.50.50] HEX: 78781f12110b12100f1fc90294c150080dc6200054e201945d714a007e5f00fd17f60d0a
2017-11-18 21:45:32 DEBUG: [C04FEF40: 5023 > 223.184.50.50] HEX: 78780512000d79410d0a
2017-11-18 21:45:32  INFO: [C04FEF40] id: 351608083320528, time: 2017-11-18 21:45:31, lat: 24.05736, lon: 75.06690, speed: 0.0, course: 226.0
2017-11-18 21:46:45  INFO: Shutting down server...
2017-11-18 21:46:45  INFO: [C04FEF40] disconnected
```
wrapper.log.20171118:
```
INFO|25965/0|Service traccar|17-11-18 17:03:05|[main] INFO org.eclipse.jetty.util.log - Logging initialized @6854ms
INFO|25965/0|Service traccar|17-11-18 17:03:06|[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.22.v20170606
INFO|25965/0|Service traccar|17-11-18 17:03:08|[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@6603286a{/api,null,AVAILABLE}
INFO|25965/0|Service traccar|17-11-18 17:03:08|[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.t.w.@6f90cd6e{/,null,AVAILABLE}
INFO|25965/0|Service traccar|17-11-18 17:03:08|[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@234ecffb{HTTP/1.1}{0.0.0.0:8082}
INFO|25965/0|Service traccar|17-11-18 17:03:08|[main] INFO org.eclipse.jetty.server.Server - Started @10034ms
INFO|wrapper|Service traccar|17-11-18 21:46:44|stopping process with pid/timeout 25965 45000
INFO|wrapper|Service traccar|17-11-18 21:46:44|Shutting down Wrapper
INFO|25965/0|Service traccar|17-11-18 21:46:45|[Thread-12] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@234ecffb{HTTP/1.1}{0.0.0.0:8082}
INFO|25965/0|Service traccar|17-11-18 21:46:45|wrapper manager received stop command
INFO|25965/0|Service traccar|17-11-18 21:46:45|[Thread-12] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.t.w.@6f90cd6e{/,null,UNAVAILABLE}
INFO|25965/0|Service traccar|17-11-18 21:46:45|[Thread-12] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@6603286a{/api,null,UNAVAILABLE}
INFO|wrapper|Service traccar|17-11-18 21:46:45|waitpid 25965 0
INFO|wrapper|Service traccar|17-11-18 21:46:45|exit code posix process: 0 application: 0
INFO|wrapper|Service traccar|17-11-18 21:46:45|killing 25965
INFO|wrapper|Service traccar|17-11-18 21:46:46|process exit code: 0
```
Regards
Rakesh

**Comment by tananaev** [comment]
How much free memory do you have on the server? How many devices do you have?

**Comment by RakeshBhandarkar** [comment]
Hi Tananaev,

The application needs to support up-to 1500 devices but currently in test it is 2 to 5 devices now.

Below is snapshot of free memory in server right now,

root@Snooky:/tmp/Rakesh# free -m
             total       used       free     shared    buffers     cached
Mem:          3952       3616        335         46          8       2269
-/+ buffers/cache:       1338       2614
Swap:            0          0          0

root@Snooky:/tmp/Rakesh# cat /proc/meminfo
MemTotal:        4047340 kB
MemFree:          344352 kB
MemAvailable:    2470452 kB
Buffers:            9204 kB
Cached:          2323752 kB
SwapCached:            0 kB
Active:          3519072 kB
Inactive:         107080 kB
Active(anon):    1305432 kB
Inactive(anon):    35424 kB
Active(file):    2213640 kB
Inactive(file):    71656 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                64 kB
Writeback:             0 kB
AnonPages:       1293200 kB
Mapped:            35796 kB
Shmem:             47660 kB
Slab:              42752 kB
SReclaimable:      19464 kB
SUnreclaim:        23288 kB
KernelStack:        3424 kB
PageTables:        10764 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     2023668 kB
Committed_AS:    2039516 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       97928 kB
VmallocChunk:   34359586156 kB
HardwareCorrupted:     0 kB
AnonHugePages:    962560 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       98284 kB
DirectMap2M:     3047424 kB
DirectMap1G:     1048576 kB

root@Snooky:/tmp/Rakesh# vmstat
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  0      0 344300   9236 2323808    0    0  4289    48    1    0 35  6 59  0  0

**Comment by tananaev** [comment]
I guess the problem is not in lack of resources. Are you sure it wasn't just stopped with a stop script?
