### ISSUE TITLE
Unable to clear per-user preferences when the selection is part of a drop-down.

### ISSUE THREAD

**Issue by pc500** [traccar/traccar#3645]
Preferences set at a server level are used unless a user preference is defined, but once that user preference is present there does not appear to be a way to "remove" or "clear" that preference.

For example, once I set a map provider, I can not "remove" that selection to allow my choice to fall through to the server preference without deleting and re-creating the account..  I can only change it by selecting another map provider.

A clear or delete button would be great!

**Comment by tananaev** [comment]
I believe this has already been suggested somewhere; possibly on the forum.

**Comment by pc500** [comment]
I'll look again.  I gave it a first three pages of google search and didn't have any luck :).  I'm not sure if this would be a bug or feature request, so Ill leave this open for now unless you want it closed.

**Comment by tananaev** [comment]
This has been fixed a while ago.
