### ISSUE TITLE
Feature request: Show last GPS fix under devices as a field chooser option.

### ISSUE THREAD

**Issue by pc500** [traccar/traccar#3646]
In the devices tab, currently there is a field called "last update" which provides how long since the device last contacted the server.  It's derived from current time - servertime in the last update

This may not be represent the last GPS fix, especially if a device is playing back old data or simply doesn't have a current GPS signal.

Can a separate field be added titled "Last GPS fix", or similar?  Last update is the best default, but knowing the last gps fix can also prove useful.  Off by default is fine, but it would be nice if it was viewable.

Last GPS fix would just be the same logic, but current time - fixtime.

Note:  My table shows devicetime and fixtime the same.  I'm not sure the purpose of these two fields.

**Comment by tananaev** [comment]
We already show fix time when you select device. If that's not enough, please submit a ticket in `traccar-web` repo.
