### ISSUE TITLE
Feature Request: Deliver SMS as email to a defined address.

### ISSUE THREAD

**Issue by pc500** [traccar/traccar#3651]
It's a challenge to get SMS provider support today for SMPP.  However, many US providers offer SMS-to-email gateways.  For smaller installations, this may be adequate.

This request is for a "deliver SMS as e-mail" checkbox under user account preferences, which allows one to supply a "sms e-mail" address (IE: 555-1212@vtext.com).  If this were to be checked for a user, all Traccar would need to do is route ordinary SMS notifications to the body of an e-mail message and use the defined SMS e-mail for delivery.

**Comment by tsmgeek** [comment]
#3636 
There is a current request to try and expand the SMS support to give HTTP gateway links. I know this will not fix your issue but it is a change in that area of the system which may end up better supporting your request.

**Comment by pc500** [comment]
Lots of things have changed since 2017 when this was submitted.  The first, has been a global movement of disabling e-mail-to-sms gateways at providers in favor of pay-to-play and better provider control of SMS senders.

Secondarily, has been the introduction of many effective commercial HTTP-based API providers who purchase SMS access to provider networks and intermediate to the end user to sell access to users phones (IE: Twilio and others).

The importance of doing this no longer exists.  The favored market direction of HTTP-API has won, and we'll just pay the $10/year for enough SMS credits.  Furthermore, Traccar now supports this.

Hopefully eventually the notification would will move on from SMS to something free (IE: Smartphone notifications), but for now, it's ubiquitous and works everywhere.

This issue can be closed.
