### ISSUE TITLE
Problems to connect with mysql

### ISSUE THREAD

**Issue by mendesdouglas** [traccar/traccar#3653]
```xml
<properties>

    <entry key="config.default">./conf/default.xml</entry>
<!--
    <entry key='database.driver'>org.h2.Driver</entry>
    <entry key='database.url'>jdbc:h2:./data/database</entry>
    <entry key='database.user'>sa</entry>
    <entry key='database.password'></entry>
-->

    <entry key='database.driver'>com.mysql.jbdc.Driver</entry>
    <entry key='database.dataSource'>com.mysql.jdbc.jdbc2.optional.MysqlDataSource</entry>
    <entry key='database.url'>jdbc:mysql://localhost:3306/traccar?useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
    <entry key='database.user'>root</entry>
    <entry key='database.password'>123</entry>

</properties>
```
My Logs of today
```
INFO|wrapper|Service traccar|17-11-22 11:55:08|posix_spawn pid 7813
INFO|wrapper|Service traccar|17-11-22 11:55:08|started process 7813
INFO|wrapper|Service traccar|17-11-22 11:55:08|started process with pid 7813
INFO|7813/0|Service traccar|17-11-22 11:55:10|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|7813/0|Service traccar|17-11-22 11:55:11|java.lang.reflect.InvocationTargetException
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at java.lang.reflect.Method.invoke(Method.java:498)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|7813/0|Service traccar|17-11-22 11:55:11|Caused by: java.lang.ClassNotFoundException: com.mysql.jbdc.Driver
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at java.lang.Class.forName0(Native Method)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at java.lang.Class.forName(Class.java:264)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at org.traccar.database.DataManager.initDatabase(DataManager.java:108)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at org.traccar.database.DataManager.<init>(DataManager.java:80)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at org.traccar.Context.init(Context.java:281)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	at org.traccar.Main.main(Main.java:35)
INFO|7813/0|Service traccar|17-11-22 11:55:11|	... 6 more
INFO|wrapper|Service traccar|17-11-22 11:55:11|waitpid 7813 59136
INFO|wrapper|Service traccar|17-11-22 11:55:11|exit code posix process: 59136 application: 0
```
I known that problem is caused by mysql driver not found, but I dont know how solve it.
**Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver**

can you help me Please?

**Comment by tsmgeek** [comment]
Download the mysql J connector from MySQL website.
https://dev.mysql.com/downloads/connector/j/
Extract and put the .jar file in the libs directory.

This is from what I remember doing.

**Comment by mendesdouglas** [comment]
The connector exists in lib's folder, but for some reasons, that I don't know,  not found the connector
user@traccar-1:/opt/traccar/lib$ ls
HikariCP-java7-2.4.12.jar             jackson-jaxrs-json-provider-2.8.4.jar      log4j-1.2.17.jar
activation-1.1.jar                    jackson-module-jaxb-annotations-2.8.4.jar  logback-core-1.1.3.jar
antlr-2.7.2.jar                       javassist-3.20.0-GA.jar                    mail-1.4.7.jar
aopalliance-repackaged-2.5.0-b32.jar  javax.annotation-api-1.2.jar               mssql-jdbc-6.2.1.jre7.jar
async-http-client-1.9.40.jar          javax.inject-2.5.0-b32.jar                 mysql-connector-java-5.1.44-bin.jar
ch-commons-charset-3.0.2.jar          javax.json-1.0.4.jar                       mysql-connector-java-5.1.44.jar
ch-commons-util-6.0.2.jar             javax.servlet-api-3.1.0.jar                netty-3.10.6.Final.jar
ch-smpp-5.0.9.jar                     javax.ws.rs-api-2.0.1.jar                  oro-2.0.8.jar
commons-beanutils-1.9.2.jar           jcl-over-slf4j-1.7.12.jar                  osgi-resource-locator-1.0.1.jar
commons-chain-1.1.jar                 jersey-client-2.25.1.jar                   poi-3.16.jar
commons-codec-1.9.jar                 jersey-common-2.25.1.jar                   poi-ooxml-3.16.jar
commons-collections-3.2.1.jar         jersey-container-servlet-2.25.1.jar        poi-ooxml-schemas-3.16.jar
commons-collections4-4.1.jar          jersey-container-servlet-core-2.25.1.jar   postgresql-42.1.4.jre7.jar
commons-digester-1.8.jar              jersey-entity-filtering-2.25.1.jar         servlet-api-2.3.jar
commons-jexl-2.1.1.jar                jersey-guava-2.25.1.jar                    slf4j-api-1.7.21.jar
commons-lang-2.4.jar                  jersey-media-jaxb-2.25.1.jar               slf4j-simple-1.7.25.jar
commons-lang3-3.3.2.jar               jersey-media-json-jackson-2.25.1.jar       snakeyaml-1.17.jar
commons-logging-1.1.jar               jersey-server-2.25.1.jar                   sslext-1.2-0.jar
commons-validator-1.3.1.jar           jetty-client-9.2.22.v20170606.jar          stax-api-1.0.1.jar
core                                  jetty-http-9.2.22.v20170606.jar            struts-core-1.3.8.jar
curvesapi-1.04.jar                    jetty-io-9.2.22.v20170606.jar              struts-taglib-1.3.8.jar
dom4j-1.1.jar                         jetty-jndi-9.2.22.v20170606.jar            struts-tiles-1.3.8.jar
extended                              jetty-proxy-9.2.22.v20170606.jar           threetenbp-1.3.3.jar
groovy                                jetty-security-9.2.22.v20170606.jar        validation-api-1.1.0.Final.jar
h2-1.4.196.jar                        jetty-server-9.2.22.v20170606.jar          velocity-1.7.jar
hk2-api-2.5.0-b32.jar                 jetty-servlet-9.2.22.v20170606.jar         velocity-tools-2.0.jar
hk2-locator-2.5.0-b32.jar             jetty-util-9.2.22.v20170606.jar            websocket-api-9.2.22.v20170606.jar
hk2-utils-2.5.0-b32.jar               jetty-webapp-9.2.22.v20170606.jar          websocket-client-9.2.22.v20170606.jar
ical4j-2.0.4.jar                      jetty-xml-9.2.22.v20170606.jar             websocket-common-9.2.22.v20170606.jar
jackson-annotations-2.8.4.jar         joda-time-2.9.9.jar                        websocket-server-9.2.22.v20170606.jar
jackson-core-2.8.4.jar                jxls-2.4.2.jar                             websocket-servlet-9.2.22.v20170606.jar
jackson-databind-2.8.4.jar            jxls-poi-1.0.13.jar                        xmlbeans-2.6.0.jar
jackson-jaxrs-base-2.8.4.jar          liquibase-core-3.5.3.jar

Is what have in my libs folder. 
mysql-connector-java-5.1.44-bin.jar is the file copied.

**Comment by tananaev** [comment]
Are you using official release?

**Comment by mendesdouglas** [comment]
Yes.

**Comment by tananaev** [comment]
Not sure why you need that bin file there. It should not be there in official version.

**Comment by tananaev** [comment]
I have checked several servers and they only have `mysql-connector-java-5.1.44.jar`. There is no `-bin` file. All of the servers I checked are using official 3.14.

**Comment by mendesdouglas** [comment]
Yes, I'm following the link above, of mate @tsmgeek, he recommended do a download of connector directly of web-site, And I did. So I just show all files that exists in my folder lib. And the same connector exists

**Comment by tananaev** [comment]
His suggestion makes no sense. Traccar includes MySQL database driver by default.

I think maybe the problem is conflicting MySQL driver already present on your system. Try removing it.

**Comment by mendesdouglas** [comment]
When I posted my question, the problem already existed.

but I did what you asked me to do, and I removed the file, then the same thing happens.

**Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver**

**Comment by tananaev** [comment]
I think you misunderstood me. Most likely you have driver installed globally on your system somewhere.

**Comment by tsmgeek** [comment]
@tananaev
The only time I had this issue was when I compiled my own traccar, think netbeans compiled against newer version. Then it started complaining.
