### ISSUE TITLE
GT06 Speed Issue

### ISSUE THREAD

**Issue by SRIKAAA** [traccar/traccar#3660]
Dear Tananaev

We have identified a new issue in GT06 traccar decoder.
Even if vehicle is stopped , we are receiving last speed constantly.

Kindly resolve the same.

Look into the highlighted yellow rows where speed is same.

[GT06_speedissue.xlsx](https://github.com/tananaev/traccar/files/1508799/GT06_speedissue.xlsx)

**Comment by tananaev** [comment]
It's not an issue. Traccar uses last known location (and speed) if your device sends report without location.

**Comment by SRIKAAA** [comment]
How do i identify from database whether the device has sent report without location.

**Comment by tananaev** [comment]
There is no flag, but you can probably see it by the `fixTime` field.
