### ISSUE TITLE
Feature Request: Google geocoder option long_name

### ISSUE THREAD

**Issue by burol** [traccar/traccar#3664]
This feature request is about google geocoder.
 
Config option out of default.xml:
```xml
<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>google</entry>
```
Feature request: 
Add a new config option:
```xml
<entry key='geocoder.google.route_long_name‘>true</entry>
```
If set to true the Traccar reverse geocoder for Google will use the 
„long_name“ key value pair of a returned address. 

Reason for feature request:
My assumption is that by default Traccar reverse geocoder is using key „short_name“.
In some cases the default „short_name“ key provides short name values which are not useful.

Example:
```
https://maps.googleapis.com/maps/api/geocode/json?latlng=47.059836,8.287325
```
Result extract:
```json
{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "59",
               "short_name" : "59",
               "types" : [ "street_number" ]
            },
            {
               "long_name" : "Reussinsel",
               "short_name" : "9",
               "types" : [ "route" ]
```
JSON content of key "types" = „route“, 
"long_name" : "Reussinsel" is much more accurate compared to
"short_name" : "9"

**Comment by mandadimuralidharreddy** [comment]
@burol did you found any solution for this.

**Comment by burol** [comment]
@mandadimuralidharreddy, no I have not. 
I hope Anton and his team will sooner or later implement this feature request.

**Comment by tananaev** [comment]
There's an option to use formatted address directly from Google. I believe it should solve the problem. If not, please let us know.
