### ISSUE TITLE
ignition attribute for meitrack

### ISSUE THREAD

**Issue by slachtar** [traccar/traccar#3666]
Hello,
traccar is not setting the ignition attribute while meitrack protocol already supports it by checking event code.
if event code is 2 or 3 or 4 then ignition is on, else if event code is 10 or 11 or 12 then ignition is off.

http://www.meitrack.com/cd-download/Protocols/MEITRACK_GPRS_Protocol.pdf (page 9, 10)

Best regards,

**Comment by tananaev** [comment]
Feel free to send a pull request.
