### ISSUE TITLE
Feature Request additional attributes in device list view

### ISSUE THREAD

**Issue by burol** [traccar/traccar#3682]
This Feature Request is about the following:

User Interface, Section Devices

Enable the ability to add at least the following 
attributes: Speed, Battery, Address, Driver

Reason for Feature Request:
Ability to have all devices and status of additional 
attributes in one list.

Please find the related mock up in the attachment

[TraccarFeatureRequestDevicesAttributesDetail.pdf](https://github.com/tananaev/traccar/files/1564248/TraccarFeatureRequestDevicesAttributesDetail.pdf)

**Comment by tananaev** [comment]
I believe it has been discussed before somewhere.

**Comment by tananaev** [comment]
Modern web app has some more info in the device list. If that's not enough, please create a ticket in `traccar-web`.
