### ISSUE TITLE
REST API: allow to use public (external) device ID in requests

### ISSUE THREAD

**Issue by Anton-V-K** [traccar/traccar#3703]
It would be very handy for simple cases to reference devices by the "public" IDs (`uniqueId`) when submitting requests via REST API (at the moment only internal IDs (`deviceId`) are supported).
This eliminates one step when requesting data (so one doesn't need to [GET /devices](https://www.traccar.org/api-reference/#operation--devices-get) to find out internal IDs).
Good candidates for such improvements are:

- all reports (GET /reports/events, GET /reports/route, GET /reports/stops, GET /reports/summary, GET /reports/trips - see #958 )
- GET /positions
- GET /notifications
- GET /geofences
- GET /drivers
- GET /commands
- GET /attributes/computed
- something else?

**Comment by tananaev** [comment]
Doesn't look like there's enough interest, so I don't think it makes sense at this time.
