### ISSUE TITLE
API/DEVICES 

### ISSUE THREAD

**Issue by allanqm** [traccar/traccar#3712]
Good Night,

Json's address http://xxx.xxx.xxx.xxx:8082/api/devices is not bringing me the value of the phone field.

The result is:

> [{"id":2,"attributes":{},"name":"JR Celular","uniqueId":"478213","status":"unknown","lastUpdate":"2018-01-11T18:49:30.492+0000","positionId":2237,"groupId":0,"geofenceIds":null,**"phone":null**,"model":null,"contact":null,"category":null},{"id":3,"attributes":{},"name":"Magno Moto Trilha","uniqueId":"864180034307021","status":"offline","lastUpdate":"2018-01-11T21:08:30.213+0000","positionId":2388,"groupId":0,"geofenceIds":null,**"phone":null**,"model":null,"contact":null,"category":null},{"id":5,"attributes":{},"name":"Novo Uno Magno","uniqueId":"864180034263001","status":"offline","lastUpdate":"2018-01-12T00:47:24.305+0000","positionId":2496,"groupId":0,"geofenceIds":null,**"phone":null**,"model":null,"contact":null,"category":null}]

The field phone appears the result null. Which file do I need to modify to resolve this query?
I need this value for my project.

Very thanks.

Traccar 3.9

Sorry for my English, im Brazilian.

**Comment by tananaev** [comment]
If it's `null` it means that it's not set up.

**Comment by allanqm** [comment]
Which client do you tell me to connect to the h2 database and make queries?

My JR Mobile device has the phone field set to 0819999999, but appears null in /api/devices

Ty for answer

**Comment by tananaev** [comment]
You can use any JDBC client.
