### ISSUE TITLE
Wrong/OLD time Stamp Issue

### ISSUE THREAD

**Issue by piyushsingh172** [traccar/traccar#3715]
Packet received at : 01-15T02:42:52. => Jan 15 2018 08:12:50

Time of fix: `1515973790` => Jan 15 2018 05:19:50   dataHex:`7878222212010e173132c30312b598084d670000149d01940a009900305a010400017bd8530d0a`:returnResponse:`{\"jsonResponse\":{\"altitude\":0,\"mobileIdType\":\"1\",\"serviceType\":\"0\",\"messageType\":\"2\",\"heading\":157,\"satellites\":0,\"carrier\":0,\"rssi\":0,\"commState\":0,\"hdop\":0,\"inputs\":0,\"unitStatus\":0,\"eventIndex\":0,\"eventCode\":\"a\",\"accums\":16,\"append\":0,\"accumulator0\":\"00000000\",\"accumulator1\":\"00000000\",\"accumulator2\":\"00000000\",\"accumulator3\":\"00000000\",\"accumulator4\":\"00000000\",\"accumulator5\":\"00000000\",\"accumulator6\":\"00000000\",\"accumulator7\":\"00000000\",\"accumulator8\":\"00000001\",\"accumulator9\":\"00000000\",\"accumulator10\":\"00000000\",\"accumulator11\":\"00000000\",\"accumulator12\":\"00000000\",\"accumulator13\":\"00000000\",\"accumulator14\":\"00000000\",\"accumulator15\":\"00000000\",\"mobileId\":\"0351777090001403\",\"updateTime\":1515973790,\"timeOfFix\":1515973790,\"latitude\":28.643213333333332,\"longitude\":77.38353777777778,\"speed\":0,\"fitStatus\":0,\"sequenceNumber\":379},\"packetResponse\":\"\"}","time":"2018-01-15T02:42:52.623Z","v":0}`

Above packets results in following trip summary: just 5.5kms of journey and time is 3hour+. This journey has started actuall around 8:12 am but due to bad packet from device, system is showing start time as 5:19 am

**Comment by tananaev** [comment]
What timezone are you in? Is your device reporting UTC time?

**Comment by Knowledgetreedata** [comment]
hi am in Melbourne Australia and need to change to here. Help please

**Comment by tananaev** [comment]
Server expects UTC time.

**Comment by piyushsingh172** [comment]
I am in GMT 5:30

**Comment by tananaev** [comment]
It doesn't matter where you are. You need to configure to report in UTC timezone.

**Comment by Knowledgetreedata** [comment]
Thanks i am utc+10




Get Outlook for Android







On Tue, Jan 16, 2018 at 5:55 PM +1100, "Anton Tananaev" <notifications@github.com> wrote:












It doesn't matter where you are. You need to configure to report in UTC timezone.

**Comment by tananaev** [comment]
I think you misunderstood me. Device need to report in UTC timezone (aka UTC+0).
