### ISSUE TITLE
Suggestion:  create a field to store the license plate car

### ISSUE THREAD

**Issue by JBFelizberto** [traccar/traccar#3717]
I would suggest creating a column on  Devices (table) to store the vehicle's license plate information. This field is displayed on the web enviroment  too.

reason: Currently there is only the "model" field to identify the vehicle.

Regards

JB

**Comment by tananaev** [comment]
Model is supposed to be device model, not vehicle model. Traccar is not only vehicle tracking solution. It's a universal solution to track anything, so it doesn't make much sense to add a field very specific to vehicles.

**Comment by JBFelizberto** [comment]
Thank you for feedback.

Maybe you can insert a "Manufacturer" Field (simple text).

JB

**Comment by tsmgeek** [comment]
You have a 'Model' field, can you not repurpose this?
When ive been field limited in the past I have sometimes taken one and pipe separated values within it.
Note you can type in any name you wish when using 'Attributes' or alter the WebUI device attributes model to give an additional custom value for you.
