### ISSUE TITLE
On demand  geocoding bug?

### ISSUE THREAD

**Issue by socstur** [traccar/traccar#3726]
Hi Guys,
             I'm using the on demand geocoding to limit the number of geocoding requests sent to my google account. I have set the config below to use this feature. Everything seems to working ok but I notice I'm still running out of my 5000 geocoding requests per day within 12hrs. It looks to me requests are regularly being sent to my google account.  I'm using google API key and I have it only responding to requests from my server so I don't believe anyone else is stealing from my quota.

I'm wondering if there is somewhere in the code that is still hitting the geocoding servers?

I also noticed in statistics the geocoding request count is always "0" even when I have manually made geocoding requests. 
```xml
    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>
    <entry key='geocoder.processInvalidPositions'>false</entry>
    <entry key='geocoder.onRequest'>true</entry>
    <entry key='geocoder.ignorePositions'>true</entry>
```

**Comment by tananaev** [comment]
Looks like statistics does count on demand requests. Also note that statistics is updated once a day and it accumulates data in-memory, so if you restart server it resets counters for the day.

Some reports also use geocoding, but it shouldn't hit 5000 unless you have a huge number of users.
