### ISSUE TITLE
Create new tables in existing Database.

### ISSUE THREAD

**Issue by dhawala190** [traccar/traccar#3733]
Hi Anton I have recently downloaded and setup Traccar. I see that I can add database queries in the config file, but I want to add new tables. Not sure how to do it and how to integrate them in the existing model.

**Comment by tananaev** [comment]
Look at the existing tables and follow the same pattern.

**Comment by tananaev** [comment]
They are created by liquibase library.

**Comment by dhawala190** [comment]
OK. Thanks.
