### ISSUE TITLE
[Feature request] Pushover push notifications

### ISSUE THREAD

**Issue by jgaurilo** [traccar/traccar#3757]
I have been using pushovers email to push notification for a while now. While it works kinda okayish most of the time, I would like to see proper pushover api support implemented in traccar to cut delays in notifications caused by email.

https://pushover.net/api
https://github.com/sps/pushover4j/

**Comment by tananaev** [comment]
As far as I know, pushover is a proprietary service, so I'm not comfortable with locking users into a single platform like that.

**Comment by jpmens** [comment]
Pushover is proprietary, and IMO there's no real need to implement support for it in Traccar.

Using event forwarding we can "translate" Traccar events to a payload suitable to direct at services such as Pushover. 

I'm actually working on documenting this at the moment and will try and remember to link to it here if that's ok.

**Comment by Shinryuken** [comment]
Hi, 

as Jpmens said you can already send messages to services like pushover using the event forwarding module, give a look here (we talked about telegram too):

https://github.com/tananaev/traccar/pull/3624

**Comment by tananaev** [comment]
Yes, but there is no way to differentiate users with forwarding.

**Comment by Shinryuken** [comment]
yes, if he uses those event notifications, they will be generic

**Comment by condeitokako** [comment]
@jgaurilo My system performs this function and more additional functions, if you are interested, I am to order,

Best regards,

Conde

**Comment by atiqsamtia** [comment]
Hey, I have implemented the FCM with single tokens and tested with multiple users check out my pull request here #4002

**Comment by jpmens** [comment]
It took a long time to do, but I finally wrote about the [position and event forwarding](https://jpmens.net/2018/09/14/position-and-event-forwarding-from-traccar/).

**Comment by psyciknz** [comment]
> It took a long time to do, but I finally wrote about the [position and event forwarding](https://jpmens.net/2018/09/14/position-and-event-forwarding-from-traccar/).

Getting mqtt directly into traccar would simplify this somewhat.

**Comment by tananaev** [comment]
We do support Pushover notifications.
