### ISSUE TITLE
Suggestion: Speed column to events report

### ISSUE THREAD

**Issue by gpproton** [traccar/traccar#3759]
Hi everyone have using the events report for couple of daily report it's really cool having so much info together but i feel it will be better if reports like over-speed get the corresponding speed in another column.
will be quite helpful

**Comment by vitormfreis** [comment]
I'm still interested on this topic @gpproton did you find out how to do it?

**Comment by victorferreira** [comment]
I'm also interested. I tried to implement myself but couldn't figure out how to add a new column on the Events report.
