### ISSUE TITLE
arm/lock, and disarm/unlock TK510 meiligao protocol

### ISSUE THREAD

**Issue by arrafa20** [traccar/traccar#3764]
Hello everyone,

We bought a TK510 GPS, it works under the meiligao protocol, but on the options there is no Arm/disarm the alarm, also it have doors lock/unlock on output 4 and 5.

How difficult its to create a command on the server to arm/lock, and another to disamr/unlock (As tk103b)

[TK510 user manual V4.0_20170103.pdf](https://github.com/tananaev/traccar/files/1709082/TK510.user.manual.V4.0_20170103.pdf)
[TOPTEN GPRS Communication Protocol V5.0_20171213.pdf](https://github.com/tananaev/traccar/files/1709083/TOPTEN.GPRS.Communication.Protocol.V5.0_20171213.pdf)

**Comment by tananaev** [comment]
Not very difficult.

**Comment by arrafa20** [comment]
Are you able to create it? I am not a very experienced programmer

**Comment by tananaev** [comment]
Sure, we provide professional services:

https://www.traccar.org/product/professional-services/

**Comment by arrafa20** [comment]
How many hours could you need to update the meiling protocol with these options?

Once done you will provide a new traccar package version?

This update will help several user going on

**Comment by tananaev** [comment]
Please send me an email to discuss details.

**Comment by delkant** [comment]
Will these new features be added on a new version?

**Comment by jaroja4** [comment]
Hello, this GPS has option to send photos with alarms.

Traccar can visualize these photos??

**Comment by tananaev** [comment]
Photos are supported for Meiligao protocol in general. Not sure about particular functionality that you are talking about.

**Comment by jaroja4** [comment]
Thanks for answering.
I have a Tk510 (Meiligao protocol) and I'm using demo2.traccar.org to try. I can see the GPS on the map but when requesting a photo, nothing happens. What should happen? Where does the photo arrive?
Greetings.

**Comment by tananaev** [comment]
You should see a link in the state panel.

**Comment by jaroja4** [comment]
You talk about this:

https://user-images.githubusercontent.com/5688080/35791079-7d2eb9c6-0a67-11e8-8453-5d04d5cd8965.png

No, that attribute is not visible in the panel.

Since I am using the demo server I do not have access to the log, any idea?

**Comment by tananaev** [comment]
Yes. What's the device id? And when did it send photo.

**Comment by jaroja4** [comment]
Thanks for the help Anton the device id is:

64507034522846

At this moment I am doing photo request tests

**Comment by tananaev** [comment]
I have checked logs. I can see the photo request, but your device doesn't seem to respond to it.
