### ISSUE TITLE
Build from source files

### ISSUE THREAD

**Issue by arrafa20** [traccar/traccar#3766]
Hi Anton,

I already tried to look for it, but unable to find it. I already build the source with intellij IDEA to implement some changes(Working on local host) , where should be the files that i must copy into the production servers to get my changes?

**Comment by tananaev** [comment]
I would recommend to build a jar file with maven.

**Comment by arrafa20** [comment]
i Have compiled the tracker-server.jar. Once i replaced the one on the server, i am getting some issues, for example this one when i try to add a new device:

Column "DISABLED" not found; SQL statement:
INSERT INTO devices (groupId, phone, contact, uniqueId, disabled, attributes, model, lastUpdate, category, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [42122-196] - JdbcSQLException (... < QueryBuilder:60 < *:137 < DataManager:446 < BaseObjectManager:87 < ...)

Should i change something somewhere when a custom jar file is used?

**Comment by arrafa20** [comment]
Disregard previous comment, what means this issue, when i try to add a new user? how can be fixed?

Column "POILAYER" not found; SQL statement:
INSERT INTO users (deviceLimit, coordinateFormat, deviceReadonly, name, admin, latitude, limitCommands, token, longitude, userLimit, attributes, salt, login, hashedPassword, phone, poiLayer, twelveHourFormat, readonly, email, expirationTime, zoom, disabled, map) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [42122-196] - JdbcSQLException (... < QueryBuilder:60 < *:137 < DataManager:446 < BaseObjectManager:87 < ...)

**Comment by tananaev** [comment]
I would recommend to use source code from tag.

**Comment by tsmgeek** [comment]
@tananaev are you still recommending Maven or now gradle?

**Comment by tananaev** [comment]
I would recommend using Gradle.

**Comment by tsmgeek** [comment]
Thanks, noted.

**https://www.traccar.org/build/** this page still talks about Maven, another task in the future to update.

**Comment by tsmgeek** [comment]
I few things to note which ive found trying to get this to compile in idea.

Needs the following ENV to be set if you get the following error `unmappable character for encoding cp1252`.
https://medium.com/@osamadwairi/unmappable-character-for-encoding-java-compiler-issue-e2c5cfc28273

Also i get a lot of errors showing `Wrong 3rd argument type. Found: 'java.lang.Object', required 'io.netty.buffer.ByteBuf'`. I can make it work if I do `Make 'binary' return 'io.netty.buffer.ByteBuf'`.

**Comment by tananaev** [comment]
Are you trying master branch? I don't get any of the issues.

**Comment by tsmgeek** [comment]
Yes, I wonder if its some default setup error on my idea ultimate.
Ile clear the config and try again.
