### ISSUE TITLE
Negative distance in summary and trips report

### ISSUE THREAD

**Issue by socstur** [traccar/traccar#3767]
Hi Guys,
             I'm seeing negative distance values in my summary and trips report data. I think the problem has to do with generating the report over a time period that has some empty data. As an example I generate a report for today(which is 12am to 11:59pm) but my device only reported data for half the day. I think this is resorting in traccar generating a negative distance. If I change the time period to exactly when data is reported the problem goes away. Do you think this can be remedied?

![image](https://user-images.githubusercontent.com/15850216/36054047-02aca806-0dba-11e8-97b8-ba756fa86342.png)

**Comment by tananaev** [comment]
It can mean one of two things:

1. Your device reports odometer and it's incorrect
2. Your device reports data in wrong order

**Comment by socstur** [comment]
Hi Anton,
              Thanks for quick reply. I usually have mileage reporting turned off on my devices but I'll keep monitoring to see if I can collect more data that shows this behavior.

Thanks!
