### ISSUE TITLE
[Feature request] InfluxDB support 

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar#3768]
That would be so Nice. Storing locations in a TSDB, what else ?

**Comment by tananaev** [comment]
I would recommend providing more context and details.

**Comment by wuast94** [comment]
I think he mean that the locations get stored in Influxdb so that it can be visualized in grafana

**Comment by tananaev** [comment]
With the new storage interface it should be theoretically possible to implement. I don't think we have time to do it, but a contribution is welcome.
