### ISSUE TITLE
Problem accessing /traccar/dataService

### ISSUE THREAD

**Issue by mikeandersun** [traccar/traccar#377]
I start traccar service in Windows 7 , and try to visit localhost:8082
here is error I faced!
please help me.

HTTP ERROR 503

Problem accessing /traccar/dataService. Reason:

```
Service Unavailable
```

Caused by:

org.eclipse.jetty.servlet.ServletHolder$1: javax.persistence.PersistenceException: [PersistenceUnit: release] Unable to build EntityManagerFactory
    at org.eclipse.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:498)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:552)
    at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:417)

**Comment by effumachi** [comment]
Hi

I've changed the "localhost" by IP because database is located at another server, but, after this change I cant connect to web anymore.The login window doesnt appear!

tks

**Comment by tananaev** [comment]
@effumachi, are there any error messages in the log (wrapper.log)? What do you mean by not working? It doesn't show up or you cannot login?
