### ISSUE TITLE
Traccar Android Client visible in status line

### ISSUE THREAD

**Issue by gknauf** [traccar/traccar#3770]
I think it would be nice as a reminder and help for quicker access if the Traccar Android Client would be visable in the status bar if in active state.

**Comment by tananaev** [comment]
It is visible in the status bar on the new versions of Android.

**Comment by tananaev** [comment]
It's actually the other way around. It's not possible to hide it on new versions. As far as I know, most people who use Traccar Client would prefer not to show it. There used to be a flag in the app.
