### ISSUE TITLE
Adding new protocol to traccar on CentOS

### ISSUE THREAD

**Issue by aagadewar** [traccar/traccar#3772]
Hi,

i am trying to add new protocol with new port on centOS.

i added protocol.java and protocolDecoder.java to traccar/src/opt/traccar/protocol directory and protocolDecoderTest.java to traccar/test/org/traccar/protocol. 
and made entry in traccar/setup/default.xml.

i compiled this with maven. it is compiling successfully creating target folder with .jar files.
after installing it to /opt/, the entry of new port should be there in /opt/traccar/conf/traccar.xml but it is not there.

so the port is not opening.

Is this process correct?
correct me if i am wrong.

thank you.

**Comment by tananaev** [comment]
Sounds right, but you should probably debug the code before trying to deploy it.

**Comment by aagadewar** [comment]
thank you sir for your reply,

Same source code is working on Intellij IDEA IDE, opening new port.
and 

how to debug the code.... ?
is it /opt/traccar/bin/traccar console

**Comment by tananaev** [comment]
If it works in IDE it should work on the server as well.

**Comment by aagadewar** [comment]
But it is not... 

Do i need to made entry in /traccar/debug.xml too?

**Comment by tananaev** [comment]
You need to add entry in the configuration file that you are using.

**Comment by aagadewar** [comment]
I am building it using maven.

In IDE, we can mention the configuration file. But how to do it with maven?

Which configuration file does maven use during building project.
I am building it with this command
`mvn package -e`

How should i mention a configuration file in this command?

**Comment by tananaev** [comment]
Configuration is a run-time thing, not a build time.

**Comment by aagadewar** [comment]
ok.

So, do i need only to add entry in traccar/setup/default.xml ?

**Comment by tananaev** [comment]
Yes, or `traccar.xml`.

**Comment by aagadewar** [comment]
I remove entry from setup/default.xml and made it in setup/traccar.xml. 

Still port is not opened.
