### ISSUE TITLE
Communication failure

### ISSUE THREAD

**Issue by casp3rvpn** [traccar/traccar#3773]
![image](https://user-images.githubusercontent.com/33877926/36100151-5ba12a28-1016-11e8-9846-9a40cc2781a8.png)

Выскакивает ошибка при попытке вывести отчет за месяц. Маленькие проходят на ура. Место на сервере есть. В логах - ошибок не нашел. 
Подскажите, куда смотреть?

**Comment by tananaev** [comment]
Скорее всего это тайм-аут в браузере.

**Comment by casp3rvpn** [comment]
http://localhost:8082/api/reports/route?_dc=1520938176552&groupId=4&type=allEvents&from=2018-02-10T21%3A00%3A00.000Z&to=2018-02-15T21%3A00%3A00.000Z&page=1&start=0&limit=250

Вот в чем проблема. Лимит не работает, и через xhr выдает все записи. оттуда и вешается все.
Как пофиксить?

**Comment by LucasBSC** [comment]
Is it possible to solve this issue for Chrome? I think I did not understand very well the explanations with translation, sorry.

**Comment by tananaev** [comment]
The issue is browser timeout. We can't fix it.

**Comment by casp3rvpn** [comment]
Антон, судя по всему, дело не в тайм-ауте браузера. По дебагу - отмена идет со стороны пользователя. А именно - от ExtJs. При XHR запросе, если не указан таймаут, по деволту он 30 секунд. Чего не хватает.

**Comment by casp3rvpn** [comment]
Подтверждаю - Ext.override(Ext.data.proxy.Ajax,{timeout: 6000000}); в начало app.min.js
И никаких разрывов)

**Comment by tananaev** [comment]
Interesting I didn't know you could control timeout. For synchronous requests it's not possible, but for ajax it works. Fixed the issue:

https://github.com/traccar/traccar-web/commit/d67213556dcc87453c0ad5cd6f9e8851c477a2f3

**Comment by LucasBSC** [comment]
Thanks.
