### ISSUE TITLE
Geocoding issue with gps in standby

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#3774]
https://github.com/tananaev/traccar/blob/master/src/org/traccar/GeolocationHandler.java#L48-L49

Small issue, eelink devices when in low power mode shutdown their GPS (i suspect others may do the same), decoder reports this as invalid location (setValid). The last position is technically correct as long as the unit has not actually moved. The device does continue to send updated GSM location info and the Geocoder ends up moving the position due to this and it can be way off.
I was trying to think of a way that this could be better handled.
Bit10 of the status flag im thinking indicates if the GPS module is shutdown, Bit0 indicating if position is fixed. If Bit10=0 & Bit=0 it could be considered valid by default.
Ile have to test but its possible that device ends up waking up sending status which shows GPS is active but not locked yet.
Its a catch 22 situation it seems.

**Comment by tananaev** [comment]
I don't think invalid GPS location should be considered valid, even if in your particular case it happens to point to the correct location. You can enable geocoding for invalid locations as a workaround for your case.

**Comment by tsmgeek** [comment]
That is the problem, the GPS location is not invalid, just it has not been
updated as tracker has not moved and its in standby. It sends flag to say
it does not have a fix, but in fact it just means its in standby and gps is
turned off.
I used the flag you mentioned and all my trackers that were in standby
moved major distance to where the cellsite is instead.

On 13 Feb 2018 00:09, "Anton Tananaev" <notifications@github.com> wrote:

I don't think invalid GPS location should be considered valid, even if in
your particular case it happens to point to the correct location. You can
enable geocoding for invalid locations as a workaround for your case.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tananaev/traccar/issues/3774#issuecomment-365106730>,
or mute the thread

**Comment by tananaev** [comment]
Validity flag is coming directly from GPS module. I don't think we plan to adjust it.
