### ISSUE TITLE
Geofence error

### ISSUE THREAD

**Issue by condeg** [traccar/traccar#3779]
Traccar is presenting a bug in the geofence, is that although the GPS reports in the geofence, traccar does not trigger the event enter geofence or exit geofence. It is happening when I assign a geofence to a group, in some devices the event of enter geofence or exit geofence is not performed, I tried associating the devices directly to the geofences and it fails intermittently. That is 5 times that passes through the geofence 1 time the event does not occur.
The geofences are assigned 150 devices reporting every 100 meters the shape of the geofence is a rectangle of 120 meters.
example 
![geofence error](https://user-images.githubusercontent.com/32559472/36463158-fc830904-1695-11e8-833c-41c6e3511ee0.PNG)

**Comment by tananaev** [comment]
Please provide details of a case when it failed to detect entering or existing geofence. We would need geofence object details and logs with device passing through it.

**Comment by condeg** [comment]
Geofence
POLYGON((9.193534299509523 -75.8161426350667, 9.193550186034159 -75.81580467673082, 9.192078031723497 -75.8157456681325, 9.192078031723497 -75.8160889908864, 9.193534299509523 -75.8161426350667))


[Pictures.zip](https://github.com/tananaev/traccar/files/1744454/Pictures.zip)

**Comment by tananaev** [comment]
How can I find your device in the log?

**Comment by condeg** [comment]
id device 1360000186

**Comment by tananaev** [comment]
I have tested your geofence with data from logs and I see 2 geofence events, so everything is working as expected:

![screen shot 2018-02-22 at 12 10 28 pm](https://user-images.githubusercontent.com/1161863/36510865-67d7a172-17c9-11e8-942d-9719fa258504.png)

If it didn't work for you, most likely it means that something was misconfigured.
