### ISSUE TITLE
[Feature request] Share position of the unit

### ISSUE THREAD

**Issue by PiotrIT** [traccar/traccar#3789]
A newly registered user has no possibility to easily share their location (for example his family). He must ask the System Administrator to add a new (read only) user to his account. 
I think sharing location is an important and useful feature. This should be simpler and work without participation of the entire system administrator. It's worth thinking about adding this function.
Maybe the ability to set the number of users (2) for the new register account (like we can set device limit on config.xml file) will be a good solution .
The second thing is sharing the token. This should be the entire login link, not the token itself.

**Comment by LucasBSC** [comment]
I think it is actually a great Feature to have also. Maybe a self destructive link that shares device position upon request and destroys itself after determined period of time. This is useful for many logistics companies that deliver products to specific clients and would like this client to see the current position of a deliver.

**Comment by Dnhatsave** [comment]
Hi everyone any update about this request ??

**Comment by Ombrelin** [comment]
I would also be interested in this feature
