### ISSUE TITLE
[Feature Request] LBS location cacheing 

### ISSUE THREAD

**Issue by salmandhariwala** [traccar/traccar#3790]
Hello,

Can we develop LBS location caching mechanism instead of hitting service each time?

**Comment by tananaev** [comment]
I guess it's possible, but what's the use case? It's only called when device doesn't have a GPS fix.

**Comment by tsmgeek** [comment]
Watch out as some devices when not moving after a while shutdown the GPS until its moved and report no GPS fix to the server, this can then cause LBS location to be used and then you get the position jump elsewhere.

**Comment by wupeka** [comment]
When a device does not have a GPS fix (e.g. a garage) then even if it's stationary every location packet will cause a call to geolocation API - this can burn thrugh google geolocation API budget very rapidly.

**Comment by tananaev** [comment]
We've added an option to reuse last geolocation result if parameters haven't changes. Use `geolocation.reuse` config key to enable this.
