### ISSUE TITLE
Mapping a device to a geofence in firefox not achievable

### ISSUE THREAD

**Issue by Mexallon** [traccar/traccar#3793]
It is not possible to map a device to a geofence in firefox 58.0.2 by clicking on the device in the device list then clicking on the gears -> geofences. If one of the checkboxes is clicked nothing happens. This is not an issue with chrome - everything works there.

**Comment by Turbovix** [comment]
My friend, I took the test here, and everything is working in Mozilla 58.0.2!
Ubuntu 17.10 64-bit / Mozilla 58.0.2
![captura de tela de 2018-03-04 13-11-53](https://user-images.githubusercontent.com/3914126/36947652-d4b3e2b0-1fad-11e8-817a-b85f6f6d7d73.png)

**Comment by tananaev** [comment]
Try clicking slightly to the right of checkbox.

**Comment by Mexallon** [comment]
Yes it works when I click on the right 20% of the table cell. Thanks for the feedback and this great piece of software!
