### ISSUE TITLE
Feature Request:  Filtering old/buffered data

### ISSUE THREAD

**Issue by rhazbun** [traccar/traccar#3800]
It would be great if we could filter out old/buffered data on the server.  Since buffered data 

Here is the original post discussing this:
https://www.traccar.org/forums/topic/is-it-possible-to-disable-data-buffering/#post-27786

Looking at default.xml file, and some of my recent positions (via API call) I imagine this would be accomplished by comparing the serverTime and fixTime, and filtering out any positions where the two properties are more than _X_ number of seconds (or milliseconds?) different.

And then probably set up as a boolean config option in default.xml (or maybe integer to set allowed "age" of fix vs server time).

**Comment by tananaev** [comment]
Thanks for request. Let's see if anyone else is interested in this feature.

**Comment by parveenkumardeeva** [comment]
+1, Much needed feature to filter down old positions with some specific conditions.

**Comment by condeitokako** [comment]
@rhazbun My system performs this function and more additional functions, if you are interested, I am to order,

Best regards,

Conde

**Comment by mutasimissa** [comment]
+1 to filter out old telematics based on time parameter

**Comment by tananaev** [comment]
Added `filter.past` config parameter.

The original forum thread was about Traccar Client buffered data. We actually have an option in the app to disable buffering.
