### ISSUE TITLE
New Calendar implementation

### ISSUE THREAD

**Issue by netluca1** [traccar/traccar#3803]
Hi Anton, I congratulate with team Traccar for the excellent product and the continuous evolution of the platform.
I was thinking of a new integration of the Calendar.
Turning online I found a project very interested that if integrated would make more complete and independent Traccar.
This is https://fullcalendar.io/ or https://github.com/fullcalendar/fullcalendar
Currently Traccar uses the external lightning extension of Thunderbird as an external program and maybe with this integrated program in Traccar we should no longer resort to the use of external apps
I hope it can be useful

**Comment by alisaniko** [comment]
https://github.com/traccar/traccar/issues/4351

**Comment by alisaniko** [comment]
https://github.com/traccar/traccar/issues/4351
there was an offer

**Comment by tananaev** [comment]
We've implemented an option to define a calendar directly in Traccar (https://github.com/traccar/traccar-web/commit/6975055fd388c813e730a9be65f6fc96ad5f213e). It's not a full calendar, but it handles most of the common cases.
