### ISSUE TITLE
Since updates, no longer uploads location to server

### ISSUE THREAD

**Issue by PCSD** [traccar/traccar#3807]
Since the app updated like 2-3 updates ago, it no longer uploads my location to my private server. I says send failed. I have had my IT department look into it and they cannot get the app to work. Is their a way to get the previous version or way to walk me through what changed and make it work with my server?

**Comment by tananaev** [comment]
Send failed means that either app hasn't received a reply from the server or there was some issue and server returned error in response. You need to check server logs to see what happened.
