### ISSUE TITLE
Will you go to the new version Netty ?

### ISSUE THREAD

**Issue by Mahdihp** [traccar/traccar#3813]
Will you go to the new version of Netty 4.1.22.Final ?

**Comment by tananaev** [comment]
It is plans, but it will require huge amount of effort to implement. Why are you asking? Are you interested in working on it?

**Comment by Mahdihp** [comment]
I'm working on a project like your project in Iran.
But unfortunately I do not have enough time to work on your project.
Thank.

**Comment by azzahrah** [comment]
Very easy migrate to newest netty version 4.1.x

**Comment by tananaev** [comment]
Feel free to send a pull request if you think it's easy. I don't think it's that easy.

**Comment by azzahrah** [comment]
What i have develop its really different with traccar...

**Comment by tananaev** [comment]
Traccar has been migrated to Netty 4.1.
