### ISSUE TITLE
Why would we need to call skipLimit check before filterZero, filterFuture, filterMaxSpeed checks?

### ISSUE THREAD

**Issue by parveenkumardeeva** [traccar/traccar#3816]
Hi,

Why would we need to call skipLimit check before filterZero, filterFuture, filterMaxSpeed checks when the device is constantly sending the positions which are somehow related to filterZero, filterFuture or filterMaxSpeed ?

Any specific reasons to store these positions by skipping ( After skipLimit time) which should be filtered out by one of the these 3 filters ?

Any specific informations which should not be filtered out by filterZero, filterFuture, filterMaxSpeed by time and it's necessary to store that information?

**Comment by tananaev** [comment]
What about other filters?

**Comment by parveenkumardeeva** [comment]
As per my opinion there is no need to save these positions as their name suggests they are completely invalid. Yes we can also consider filterInvalid ( but somewhere into the forum I found that sometimes devices send some important data during invalid location, So not sure about it. And sorry I also don't know the actual reason behind it as per now ).

Zero Position, Future Position, and Max Speed always creates confusion into the customer's mind. 
They always asks why it's happening.

In some other filters we have to save the data because they all are valid but just don't want to save repeated data to save the db space. 
Some others are dependent upon user preferences that how much accuracy they want. Just like filterAccuracy, filterApproximate filters. That should not be a problem.

What's your opinion?

**Comment by tananaev** [comment]
The only reason for using `skipLimit` is to get periodical message from your device to make sure it's still online. It's important for security reasons. In this case even invalid location might be useful. For example, it can have cell info that can be used for tracking.

**Comment by parveenkumardeeva** [comment]
Yes, I know that it's necessary to save periodical message after a limit.

Zero Position, Future Position, and Max Speed are the sudden tweaks as far as I know and skipLimit can easily always save it if the time is greater than skipLimit time.

If a device is sending them regularly then it's a problem with device or need to be restart or time is to be set again or it's a new device ( need to be configured ). Means customer always have to contact the manager or server admin.

What's the probability for getting Zero Position, Future Position, and Max Speed randomly?

**Comment by tananaev** [comment]
Why randomly? Let's say you parked your car in a garage without GPS signal. In this case some devices report zero location. You might still want to get the data because it has cell info and possibly some other valid sensor info.

Either way. Let's see if anyone else is interested in this.

**Comment by parveenkumardeeva** [comment]
Ok, Thanks again.

**Comment by tananaev** [comment]
I believe we already implemented something similar to the proposed logic.
