### ISSUE TITLE
Logs for API requests

### ISSUE THREAD

**Issue by delkant** [traccar/traccar#3820]
Hello! thank you for traccar! it is amazing!

I would be nice to have a configuration option to get logs for every API request(with the user and other importan info), this can allow to have reports on how many requests users are making to certain API's and several other api related reports.

**Comment by tananaev** [comment]
All API calls are logged in the log file.

**Comment by delkant** [comment]
Is there any configuration I have to change? 

I have this in my default.xml
```
<entry key='logger.enable'>true</entry>
<entry key='logger.level'>all</entry>
<entry key='logger.file'>./logs/tracker-server.log</entry>
```
but I don't get any API call logged in that file or any other in the logs/ directory.

Thanks.

**Comment by tananaev** [comment]
You don't need to configure anything, but you have to use latest official release.

**Comment by delkant** [comment]
I have upgraded from traccar-macos-3.15 to traccar-macos-3.16 and tried from the browser listing the devices ( http://localhost:8082/api/devices/ ) I get the list and everything works fine but no logs anywhere, the only difference I have  is on my config file since I am using MySQL .

**Comment by tananaev** [comment]
I think only API that modify data are logged.

**Comment by delkant** [comment]
I see, thanks

**Comment by tananaev** [comment]
We also log reports now.
