### ISSUE TITLE
BCE device CAN BUS

### ISSUE THREAD

**Issue by nestaro** [traccar/traccar#3825]
Hello. I use the traccar 3.10 software. And i was wondering if the last version of traccar suports the BCE Can bus protocol. Beacause we buyed some BCE Devices and we can't read the can data.
Thanks!

**Comment by tananaev** [comment]
As far as I can see, only basic location data is supported at the moment.

**Comment by nestaro** [comment]
Any chance to support all the data from the protocol?

**Comment by tananaev** [comment]
Please send an email to discuss it. Address is in profile.
