### ISSUE TITLE
Docker documentation references empty database folder

### ISSUE THREAD

**Issue by chk1** [traccar/traccar#3828]
I'm running Traccar with Docker on the default H2 database, I started it according to the [Traccar Docker Documentation page](https://www.traccar.org/docker/) with this command:

> Running with host folder mapped to container database folder:
> ```
> docker run -d --name traccar-server -v /my-database-folder:/opt/traccar/data/database -p 5000-5150:5000-5150 -p 8082:8082 tananaev/traccar:[VERSION]
> ```

I was looking around in my local `/my-database-folder` and wondered why it was empty even after few weeks. 

I looked around in my Docker container and the structure in the `/opt/traccar/data` folder was as follows:
```
database          <-- empty folder!
database.mv.db
database.trace.db
```

Is the database folder supposed to be empty? If so, the documentation should probably mention the parent /opt/traccar/data folder instead of /opt/traccar/data/database.

Thank you!

**Comment by tananaev** [comment]
I haven't tried Docker version for a while, but in regular release there is no `database` folder.

**Comment by chk1** [comment]
You are right, 
I created another few containers (based on the Traccar 3.15 image) and there is no database folder within data. Using `-v /my-database-folder:/opt/traccar/data` the two database files are kept and can be migrated between Docker containers.
