### ISSUE TITLE
Feature Request - Password forgot/reset Function for all user

### ISSUE THREAD

**Issue by veerendra2k1** [traccar/traccar#3831]
Hi 

It is a feature request to add password forgot/reset function via email link or sending otp to email or mobile. This is for Traccar Web UI and mobile app.

**Comment by condeitokako** [comment]
my system performs this function and more additional functions, if you are interested, I am to order,

Best regards,

Conde

**Comment by victorferreira** [comment]
I'm also very much interested in this feature. @tananaev, are there any plans to implement it?

**Comment by tananaev** [comment]
There are no immediate plans, but it's a high priority.

**Comment by LucasBSC** [comment]
Really good feature to have implemented for us also.

**Comment by tananaev** [comment]
It is implemented and will be available in the next release.
