### ISSUE TITLE
What kind of design pattern is the GPS system used?

### ISSUE THREAD

**Issue by Mahdihp** [traccar/traccar#3832]
What kind of design pattern is the GPS system used?
What is your design pattern?

**Comment by tananaev** [comment]
Network part uses Interceptor Chain Pattern.

**Comment by Mahdihp** [comment]
For example, take a sample of this Pattern؟ 
example simple ?

**Comment by Mahdihp** [comment]
Do you mean [intercepting_filter_pattern](https://www.tutorialspoint.com/design_pattern/intercepting_filter_pattern.htm)
or 
[Interceptor_pattern](https://en.wikipedia.org/wiki/Interceptor_pattern) ?

**Comment by tananaev** [comment]
Interceptor Chain Pattern.

**Comment by Mahdihp** [comment]
Is it possible to give an example?

**Comment by tananaev** [comment]
I don't have an example.

**Comment by Mahdihp** [comment]
I did not find an example on the Internet.
