### ISSUE TITLE
How do you recognize the model of the device?

### ISSUE THREAD

**Issue by Mahdihp** [traccar/traccar#3834]
How do you recognize the model of the GPS device?
Where's the line number code?

**Comment by tananaev** [comment]
We don't recognize models. Each protocol uses own port.

**Comment by Mahdihp** [comment]
How do you handle 10 GPS device from 1 model?
Requests for these 10 models,  How to manage?

**Comment by tananaev** [comment]
What exactly is the problem with handling 10 devices? It seems like you lack some basic knowledge in software development. There are plenty of recourses online where you can learn, but this is not one of them. I'm not interested in providing mentoring services.

**Comment by Mahdihp** [comment]
I'm analyzing your system. So I can write it like that.

**Comment by tananaev** [comment]
You need to have some fundamental knowledge before you can start analyzing anything.

**Comment by Mahdihp** [comment]
like what?

**Comment by tananaev** [comment]
Like learning network protocol stack and how sockets work in operating systems.

**Comment by Mahdihp** [comment]
I have a degree in network+.

**Comment by tananaev** [comment]
How is it related to Traccar project?

**Comment by Mahdihp** [comment]
search in google & github.
