### ISSUE TITLE
Documentation does not mention "%f" (formatted address) in geocoder.format

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar#3839]
In src/org/traccar/geocoder/AddressFormat.java:
        result = replace(result, "%f", address.getFormattedAddress());

This is lacking in https://www.traccar.org/configuration-file/

**Comment by tananaev** [comment]
Fixed. Please next time create a forum thread for issues that are not related to Traccar code (e.g. documentation issues).

**Comment by oliv3** [comment]
Documentation is not available in github

**Comment by tananaev** [comment]
That's why I'm saying that you should be using forum.
