### ISSUE TITLE
[3.16] Wrong shebang in /opt/traccar/bin/stopDaemonNoPriv.sh

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar#3840]
This script has a broken shebang:

grep "bin/env" /opt/traccar/bin/*.sh
(...)
/opt/traccar/bin/startDaemonNoPriv.sh:#!/usr/bin/env bash
/opt/traccar/bin/startDaemon.sh:#!/usr/bin/env bash
/opt/traccar/bin/stopDaemonNoPriv.sh:#!/bin/bash#!/usr/bin/env bash <= HERE
/opt/traccar/bin/stopDaemon.sh:#!/usr/bin/env bash
(...)

Which obviously will cause the script to fail:
bash: /opt/traccar/bin/stopDaemonNoPriv.sh: /bin/bash#!/usr/bin/env: bad interpreter: No such file or directory

**Comment by tananaev** [comment]
It's a known issue in YAJSW:

https://www.traccar.org/forums/topic/stop-traccar-error/
