### ISSUE TITLE
Warning about gt06.timezone

### ISSUE THREAD

**Issue by tyepez** [traccar/traccar#3853]
Hi,
I get in logs a message: deprecated parameter.
```
WARN: Config parameter gt06.timezone is deprecated
```
```xml
<entry key='gt06.timezone'>-18000</entry>
```

**Comment by tananaev** [comment]
You should use device or server attribute instead now.

**Comment by tyepez** [comment]
what is the exact attribute and where set?
I have tried with the same attribute "gt06.timezone" in server and in device and it does not work, I have also tried with the already established attribute Timezone and it does not work either

**Comment by tananaev** [comment]
Attribute is the same.

**Comment by tyepez** [comment]
in server or device setting?

**Comment by tananaev** [comment]
Either one.
