### ISSUE TITLE
New Meitrack Protocol

### ISSUE THREAD

**Issue by bernamaxim** [traccar/traccar#3854]
Hi Anton, can u help me to new protocol from Meitrack P99G?

Thank you.

[MEITRACK_P99G_GPRS_Protocol.pdf](https://github.com/traccar/traccar/files/1937235/MEITRACK_P99G_GPRS_Protocol.pdf)

**Comment by tananaev** [comment]
What exactly do you need help with?

**Comment by bernamaxim** [comment]
Can u help me to implement it on Traccar?

**Comment by tananaev** [comment]
It's already supported, as far as I know.

**Comment by bernamaxim** [comment]
for model P99G, Traccar not implemented yet. Because the protocol is different from other Meitrack protocol. It's totally new protocol.

**Comment by tananaev** [comment]
Have you tried?

**Comment by bernamaxim** [comment]
not yet
