### ISSUE TITLE
Error to update user V 3.16

### ISSUE THREAD

**Issue by irvinvp** [traccar/traccar#3855]
With a completely new installation, when trying to change the administrator data, you get this error every time.
```
Unrecognized field "distanceUnit" (class org.traccar.model.User), not marked as ignorable (23 known properties: "readonly", "limitCommands", "deviceLimit", "poiLayer", "login", "name", "latitude", "phone", "admin", "userLimit", "zoom", "twelveHourFormat", "attributes", "deviceReadonly", "token", "id", "email", "longitude", "password", "map", "coordinateFormat", "disabled", "expirationTime"])
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@314a449f; line: 1, column: 385] (through reference chain: org.traccar.model.User["distanceUnit"])
```

**Comment by tananaev** [comment]
Your first statement is a lie. It's a not a clean installation. Such error happens if you have incompatible database or web app.

**Comment by irvinvp** [comment]
I've already tried it on different virtual and real machines with new installation, same bug every time, it's a real bug.

**Comment by tananaev** [comment]
No, it's not. It's either problem with database or misconfiguration. Either way it's definitely not a clean new installation.
