### ISSUE TITLE
MySQL 8.0 issue

### ISSUE THREAD

**Issue by tananaev** [traccar/traccar#3858]
Looks like word `admin` was added to the list of reserved keywords, so our queries are failing now. @Abyss777, what do you think we should do? We can't just rename it because all our Liquibase history fails now.

New keywords in MySQL 8.0:

https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-new-in-current-series

Issue on forum:

https://www.traccar.org/forums/topic/problems-using-mysql/

**Comment by Abyss777** [comment]
Very interesting... 

I see the next solution (not the best I guess).

- Rename it in 3.3 changelog (it is bad, but looks like the only way)
- Add to current changelog column renaming with precondition that uses `<columnExists>` https://www.liquibase.org/documentation/preconditions.html

**Comment by Abyss777** [comment]
Also add to instruction to update traccar before mysql

**Comment by tananaev** [comment]
I was also thinking about it and came up with the same idea. I can't think of any better solution.

**Comment by tananaev** [comment]
I have renamed `admin` to `administrator` in database and model, but left admin is most other places. Please check back-end and web app commits to make sure I didn't mess up anything. Here is the web commit:

https://github.com/traccar/traccar-web/commit/7e1ed7fee9ec411df0d198d10dc1a7f8e0e6eaf9

**Comment by Abyss777** [comment]
Good. Checked them, looks like everything is fine.

**Comment by tananaev** [comment]
Thanks.

**Comment by sake402** [comment]
Neat fix guys. But now when the project is run you get
liquibase.exception.DatabaseException: Column "ADMIN" not found; SQL statement:
Because changelog-3.17 still referenced column "ADMIN"

I changed the "changelog-3.3-admin" changeset's preConditions in changelog-3.17 to
    <preConditions onFail="MARK_RAN">
        <columnExists tableName="users" columnName="admin" />
    </preConditions>

And the error goes away
