### ISSUE TITLE
Feature Request: Notification when media file has been uploaded

### ISSUE THREAD

**Issue by Jromero97** [traccar/traccar#3863]
Hi, there is  some way that you can enable notification when a media file has been uploaded?

Example: 

New audio file in /media.

Notification: 'New audio file has been uploaded'*

New image file in /media.

Notification: 'New image has been uploaded'*

**Comment by sonerVrs** [comment]
Hello,
Did you find a solution for that?
Thanks!

**Comment by Jromero97** [comment]
@sonerVrs Hey, yes i found a solution, but it was made a customization in the source code. I can share the code, but I wanna know your device's protocol.
