### ISSUE TITLE
Can't insert a geofence because value is too long

### ISSUE THREAD

**Issue by backjeff** [traccar/traccar#3867]
Hello
Im trying to insert some geofences using the **[POST]api/geofences** and the code is ok (php).
But in some requests i got this response: 

> Value too long for column "AREA VARCHAR(4096) NOT NULL .....

I dont know how to resize this in h2. Can someone help me?

**Comment by tananaev** [comment]
I would recommend to not use H2 database. Install MySQL or some other fully featured database.
