### ISSUE TITLE
mysql database issue

### ISSUE THREAD

**Issue by JoemarB** [traccar/traccar#3872]
Good Day,
I already installed traccar and its default database is working fine and i have no issue about it but when i change my database with mysql  and supplying all necessary data needed. my traccar no longer accept data from the client. Here is my complete config below:
```xml
    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://localhost:3306/db_traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
    <entry key='database.user'>root</entry>
    <entry key='database.password'>password</entry>
```

**Comment by tananaev** [comment]
You have to check log files for errors.
