### ISSUE TITLE
Unable to Add Computed Attribute to device,

### ISSUE THREAD

**Issue by gangadhark864** [traccar/traccar#3875]
Hi,
I am trying to Add Computed Attribute to my device, It is showing following error. please find the attached image. Please help me to add custom attributes to particular Device.
![traccar](https://user-images.githubusercontent.com/24523272/39856900-9e06b1b0-5442-11e8-810d-85c8c819cf9e.JPG)

**Comment by jaimzj** [comment]
On the below link, check the 'expression' section. you are entering invalid/wrong expressions. 

https://www.traccar.org/documentation/computed-attributes/

**Comment by tananaev** [comment]
The attribute you have in your expressions doesn't exist.

**Comment by gangadhark864** [comment]
Hi,
Thank you for your replay.
How can i add custom Attribute for device , i want to add one attribute to my device like as given image.
Regards,
Gangadhar K.
![untitled1](https://user-images.githubusercontent.com/24523272/39897624-2a8a1a88-54c4-11e8-8544-4f98e5a393fb.png)

**Comment by tananaev** [comment]
There is documentation for it:

https://www.traccar.org/documentation/computed-attributes/

**Comment by gangadhark864** [comment]
how to add and show  custom property in State pannel.

**Comment by gangadhark864** [comment]
Hi, 
I am waiting for the response please give me suggestions for how to Add Own attribute and How to show added attribute in State pannel.

**Comment by tananaev** [comment]
I have already replied.
