### ISSUE TITLE
Feature Request: Driver name on map

### ISSUE THREAD

**Issue by tenten99** [traccar/traccar#3876]
Request that driver name that is assigned to an RFID is displayed on the map.

option to choose to show on the map either the device name or the driver assigned to RFID identifier.

**Comment by cesarserafim** [comment]
would be great, as well as a popup by the mouse over with status instead of the existing column

**Comment by tenten99** [comment]
Good to see someone else sees the value in my idea.  It can be hard to generate momentum in the sea of other good ideas that need attention.  Thanks

**Comment by lucianoreis** [comment]
My Suntech ST340UR tracker sends the RFID data, I don't know how to save it in the position table or show it in the reports. This proposal would be even better.

**Comment by tananaev** [comment]
Please move this ticket to the web app repo.
