### ISSUE TITLE
Nullpointer Exception in NotificationResource.java

### ISSUE THREAD

**Issue by celan69** [traccar/traccar#3877]
When event.enable is set to false in the configuration and logging in through the GUI, a Nullpointer exception is delivered in NotificationResource:54. I think this is a server side problem in the API. Probably there is no NotificationManager object because events are disabled.

Workaround: Set event.enable to true (which is the default).

**Comment by Abyss777** [comment]
There are number of failed requests when events is disabled on server side

![image](https://user-images.githubusercontent.com/5688080/40471870-5e67e7e4-5f51-11e8-9c51-4dd5b83a2ab9.png)

But only one bothers user https://github.com/traccar/traccar-web/blob/master/web/app/store/AllNotificationTypes.js#L28

We can just remove `showError` on client side or return empty results with API on server side if events are disabled.

@tananaev which will be better solution?

**Comment by tananaev** [comment]
I guess we can do it, but I think it's kind of expected behaviour.
