### ISSUE TITLE
Changing User Name

### ISSUE THREAD

**Issue by wolfbgn** [traccar/traccar#3878]
Hi, Anton.
To my understanding there are three types of users in Traccar.

1. ADMIN - can do any thing.
2. USER - has some privileges - changing map layers, measurement units and etc.
3. READ ONLY USER - just looking at the devices assigned to his/her account.

I think it is inconvenient that USER can change his/her NAME which was given by the ADMIN at the moment of creation the account. If you have 1000-2000 users, allowing them to change the NAME may lead to total confusion. They can change name,email and of course password. How ADMIN can keep track who is who?
I think probably it is better USER not to be able to change his/her NAME.
If you allow me to go further I would say that it is better if USER can not change his/her EMAIL too.
If you have 10 000 devices the amount of emails could be significant and if you do not have your local mail server for Traccar emails your IP will be blacklisted as spammer sooner than later.
Also when you open the Account, browsers automatically fill User and Password fields which may lead to accidentally (without realizing) changing the password. Can Password field be shown after clicking a button saying CHANGE PASSWORD?
Thanks for the great work.

**Comment by wolfbgn** [comment]
I am not complaining. System is good.
First for emails: For fully functioning of email service you can not use gmail, for example, because they have limitations for emails sent for 24 hours. I think 2000 or something like this. If you have say 10 000 devices you can get several thousands emails sent per hour or two hours. If you use your own domain and mail server and all these emails go to external email accounts your IP would be blacklisted. But if you have local email server and all of the clients have email accounts on your server then the massages will circulate only internally. I am not saying to reduce emails. Disallowing change of email will prevent sending emails to other email accounts but only to accounts you gave to users on your mail server.
Password: Visible password space provokes users to write something there. Usually they do not remember what it was.
Name: Since you have set expiration date for user not for device, a user can have 2 devices with different expiration dates if he/she pays for the service. Then you probably have a separate file where you keep track of payments. It seems to me rather inconvenient and might be confusing to synchronize changed names all the time.

**Comment by tananaev** [comment]
1. Are you giving users email addresses on your own server? If that's the case I would say that you are pretty much the only one who does it like this.
2. Who needs several thousand email notifications per hour? No matter if it's your own email server or gmail, no person would be interested in that amount of data.

**Comment by wolfbgn** [comment]
1. Yes, I have my own mail server on an old computer. My friends connect their SMART phones through Exchange account and get push notifications in 10-20 seconds. I do not think it is a big deal. Traccar is on another machine on LAN. No Spam.
2. I do not know who needs all of these email notifications! But I can tell you that some of my friends who use my Traccar server to guard their cars have checked all of the notifications. It is free after all. I imagine if I have not thousands of clients but several hundreds they will produce tens of thousands of emails.

**Comment by tananaev** [comment]
If my math is correct, your numbers basically mean one notification every 2-3 seconds on average. I would need to understand reasoning why anyone would be interested in such amount and frequency of notifications. At the moment it makes zero sense to me.

**Comment by wolfbgn** [comment]
I totally agree with you but that is what actually happens. I have one user with 12 pickup trucks. They send positions respectively alarms every 10 seconds. Every night he detaches the batteries of the all 12 trucks. 12 devices start sending Power cut alarm every 10 seconds. 12 by 6 massages per minute, by 60 per hour = 4300 emails per hour generated by one user.

**Comment by tananaev** [comment]
Throttling or limiting email notifications might be a useful feature, but I don't think disabling email editing a solution for that problem.

**Comment by wolfbgn** [comment]
Anton, this is your project and you decide. I do not intend to argue with you or to make you do something. I am giving feed back on real case scenarios. The system can not be foolproof.

**Comment by ms502040** [comment]
@wolfbgn if you have 10000 users you need understand system administration and programming or hire sysadmin and programmer ;)
with 10000 users you can make min  about $20000 monthly - you cat pay for it. ;)

**Comment by tananaev** [comment]
Added an option to disable email change for regular users.

**Comment by mapoloco** [comment]
Hello, How did you do it? 

I dont find the options. If I use read only, user casnt go to options.

Thank you very much.

**Comment by tananaev** [comment]
I don't think it's available in the legacy UI. You can use the modern app to enable it and then switch to legacy.

**Comment by mapoloco** [comment]
> I don't think it's available in the legacy UI. You can use the modern app to enable it and then switch to legacy.

I did it, but when turned back to legacy, emails can be changed...

**Comment by tananaev** [comment]
Have you tried? There will be a backend error.

**Comment by mapoloco** [comment]
> Have you tried? There will be a backend error.

yes, if I enable modern, I enable in a user "dont change email". Then, I put again legacy in traccar.xml, I restart server and  this user can change email.

**Comment by tananaev** [comment]
Can you provide an access to try it out?

**Comment by mapoloco** [comment]
> Can you provide an access to try it out?

of course, talk to me in private mode.

**Comment by tananaev** [comment]
You can email me details. Email address in the profile.
