### ISSUE TITLE
send custom command

### ISSUE THREAD

**Issue by guerrab** [traccar/traccar#3885]
i want send custom command by traccar but has not working
```
$login = traccar::loginAdmin();
$traccarCookie = traccar::$cookie;

$deviceinfo    = traccar::sendCommand(60550,'custom','Nouveau','find',$traccarCookie);

echo '
';
print_r($deviceinfo);
echo '
';
```
Note : I'm using php 'requests'

Sincerely

**Comment by jaimzj** [comment]
You should post these in the traccar forum and not github https://www.traccar.org/forums/forum/other/
and you need to also share the class/file in php, this is just the function call.

**Comment by guerrab** [comment]
okey thank you so much

**Comment by guerrab** [comment]
I use this command to add contacts 
[3G*$ID$*0053*PHB,1111111,0066007200690065006e00640031,2222222,0066007200690065006e00640032,,,,,,]
but what's commands to delete these contacts
NB: commands protocols watch
