### ISSUE TITLE
Seems it is bug

### ISSUE THREAD

**Issue by rabdavinci** [traccar/traccar#3888]
I am getting two errors on demo page:
1) https://clip2net.com/s/3UoIWYw   
 ext-all.js:22 GET http://demo5.traccar.org/api/session?_dc=1527267636186 404 (Not Found)

2) app.min.js:116 POST demo5.traccar.org/fake-login.html 404 (Not Found)

Can you tell please, are these bug or not? 

Thank you

**Comment by tananaev** [comment]
It's expected behaviour.
