### ISSUE TITLE
Run compressor

### ISSUE THREAD

**Issue by rabdavinci** [traccar/traccar#3890]
Hi all!

I modified js code, and seems i need run compressor to apply it?
Can you please tell, how can i do it? 
if it is possible more in detail

Thank you !!!

**Comment by tananaev** [comment]
There is a minify shell script in tools folder. You should use it. You also need extjs and sencha cmd.

**Comment by rabdavinci** [comment]
There is not tools folder, May be wrapper.sh in bin folder?

**Comment by tananaev** [comment]
There is definitely a tools folder:

https://github.com/traccar/traccar/tree/master/tools
