### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by rabdavinci** [traccar/traccar#3891]
I got this error, do you know what is it? 
![photo_2018-05-26_21-11-28](https://user-images.githubusercontent.com/30826165/40578222-dd587eae-6129-11e8-9a43-7bc1f1462d6d.jpg)

Firefox can’t establish a connection to the server at ws://navix.uz/api/socket. Web socket connection error

![photo_2018-05-26_21-18-17](https://user-images.githubusercontent.com/30826165/40578284-9d106414-612a-11e8-93d9-e49efb6a9c84.jpg)

![photo_2018-05-26_21-21-16](https://user-images.githubusercontent.com/30826165/40578288-c895fefa-612a-11e8-80e5-f56cbc117533.jpg)

**Comment by tananaev** [comment]
It means that something is blocking WebSocket connection.

**Comment by rabdavinci** [comment]
It is on client or on server ?

**Comment by rabdavinci** [comment]
Thank, you, i fixed it in apache configuration!
