### ISSUE TITLE
After 12 minutes unknown 

### ISSUE THREAD

**Issue by rabdavinci** [traccar/traccar#3892]
Hi!

When i deactivate device, traccar shows status 'online' 12 minutes, after than status is 'unknown'. And it does not show 'offline'.

Any idea?

**Comment by tananaev** [comment]
What device?

**Comment by rabdavinci** [comment]
![photo_2018-05-27_15-07-56](https://user-images.githubusercontent.com/30826165/40584746-da45f12e-61bf-11e8-9bbb-60f251e0d66f.jpg)

smartphone

**Comment by tananaev** [comment]
If you are talking about Traccar Client app then it will never show offline because there is no concept of connection. It uses HTTP-based protocol. So, that's expected behaviour.

**Comment by MAPIIIAJI** [comment]
After a long time client status changes to offline

**Comment by tananaev** [comment]
No, it doesn't. I only changes to offline if you restart service.

**Comment by MAPIIIAJI** [comment]
Maybe! Thank u. I understand! You can close this post.
