### ISSUE TITLE
Appear Error with content "Web socket connection error"

### ISSUE THREAD

**Issue by MAPIIIAJI** [traccar/traccar#3893]
Hi! We testing Traccar!
Web server Traccar works through Apache proxy
Apache proxy virtual host config:
```
<VirtualHost *:80>
    ServerName xxx.xx
    ServerAlias xxx.xx
    ProxyRequests Off
    ProxyPreserveHost On
    ProxyPass /api/socket ws://192.168.100.217:8082/api/socket
    ProxyPassReverse /api/socket ws://192.168.100.217:8082/api/socket
    ProxyPass / http://192.168.100.217:8082/
    ProxyPassReverse / http://192.168.100.217:8082/
    ProxyPassReverseCookiePath / /
    Redirect permanent / /
</VirtualHost>
```

But I receive this error in screenshot

![photo_2018-05-27_15-08-56](https://user-images.githubusercontent.com/35526267/40585063-6daaf0d6-61c5-11e8-9822-75cb61c0c2f1.jpg)
Please, help me!

**Comment by tananaev** [comment]
You can get this error message if there are no updates from device(s) for some time. In that case you can safely ignore it.

**Comment by MAPIIIAJI** [comment]
Thank you for your answer! One question! is it possible to change the content, when device is offlne e.g. status of offline device "Warning! "Device is offline"" Instead "Error "Web socket connection error""?

**Comment by tananaev** [comment]
No, this message is not about device. It just means that there was no communication from the server which might indicate connection issue.

**Comment by MAPIIIAJI** [comment]
thank u for answer. You can close this post.
