### ISSUE TITLE
It traccar support "TKSTAR TK905"?

### ISSUE THREAD

**Issue by hikmat30ce** [traccar/traccar#3899]
Hi,
Actually this is not an issue, I just want to confirm wether this project support "TKSTAR TK905" or planning to support in future.

if it support which port we need to use?

**Comment by tananaev** [comment]
Have you actually tried searching for an answer?

https://www.traccar.org/forums/topic/tk905/

**Comment by hikmat30ce** [comment]
Thanks for your prompt response, yes it helped.
Thanks again
