### ISSUE TITLE
Remove engine hours recalculation

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar#3902]
We need to remove fallback of engine hours recalculation in reports in May 2019

https://github.com/traccar/traccar/blob/2a34f67542221e27e64ee48928fe8fd7d59f7714/src/org/traccar/reports/ReportUtils.java#L270

https://github.com/traccar/traccar/blob/2a34f67542221e27e64ee48928fe8fd7d59f7714/src/org/traccar/reports/Summary.java#L55

Introduced in #3901

**Comment by tananaev** [comment]
Looks like it's been removed.
