### ISSUE TITLE
Java Error when Installing

### ISSUE THREAD

**Issue by eangulus** [traccar/traccar#3904]
Have a clean Ubuntu Server 18.04 LTS x64. Nothing on it other than defaults and Webmin.

Installed Java using: `sudo apt install default-jdk`
Downloaded Traccar 3.17
Tried installing: `sudo ./traccar.run`

Get this:
```
Creating directory out
Verifying archive integrity...  100%   All good.
Uncompressing traccar  100%
/usr/bin/java
Java 7 or higher is required
```

`java -version` reports:
```
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)
```

**Comment by tananaev** [comment]
Install Java 9 or Java 8.

**Comment by eangulus** [comment]
Might be handy to actually mention that. Instructions say 7 or Higher.

Oh, and I did work that out a few minutes ago, but not really that simple. For people not experts in Ubuntu, you have to install an older version of java then set the default version to use. Otherwise, Traccer still complains

**Comment by tananaev** [comment]
Ubuntu 18.04 was released less than 2 months ago, so obviously there might be some issues.

**Comment by tananaev** [comment]
I have fixed the issue in https://github.com/traccar/traccar/commit/946c14ab4d69ac4c0742178d94f254233017034a.
