### ISSUE TITLE
Не правильная передача координат

### ISSUE THREAD

**Issue by rabdavinci** [traccar/traccar#3906]
Что имеем:
1) Смартфон Xiomi Mi 5+
2) Система Android 7.1.2
3) Приложение: Traccar Client for Android

Проблема:

При включении клиента Traccar, исходные координаты перемещаются на определенное место(погрешность ~ 500 м) и в зависимости от частоты обновления, возвращается на 50м от исходного положения, при этом мы никуда не двигались, находились на одном и том же месте.  Ниже будет приложен скриншот для детального понимания проблемы.

Дополнительная информация:
Location accuracy: High
Частота обновление: 2с
Расстояние: 0м
Угол: 0

P.S. Тесты проводились исключительно с клиентскими приложениями Android.

![photo_2018-06-02_03-09-07](https://user-images.githubusercontent.com/30826165/40874165-5527c24a-6685-11e8-9fec-da47a2d56f0b.jpg)

**Comment by tananaev** [comment]
Смотрите точность каждой посылки.

**Comment by rabdavinci** [comment]
Не подскажете как это проверить?

Только что проверили на IOS и не было такой проблемы. Может проблема в приложении Android?

**Comment by tananaev** [comment]
В панели State отображаться должно.

**Comment by rabdavinci** [comment]
Посмотрели State, там координаты соответствуют картинке, Координаты пробили в яндекс картах и убедились, что переданные данные соответствуют.
Видимо клиент передает не правильные координаты, полученные с GPS телефона. Может ли GPS телефона передавать не правильные координаты?

Внизу будет приложен еще один пример, когда мы стоим на месте, а координаты перемещаются на 500м. от нас.

![photo_2018-06-02_03-55-49](https://user-images.githubusercontent.com/30826165/40874636-e759cbb8-668a-11e8-9a08-a747d52000ab.jpg)

**Comment by tananaev** [comment]
Я спрашивал про accuracy.

**Comment by rabdavinci** [comment]
Accuracy показывает 2.50км (

**Comment by tananaev** [comment]
Значит это не GPS координаты, а cell или wifi.

**Comment by rabdavinci** [comment]
Спасибо, тема закрыто
