### ISSUE TITLE
Netty 4 migration

### ISSUE THREAD

**Issue by tananaev** [traccar/traccar#3910]
Version 3 is very old and doesn't seem to be supported, so I think it's time to migrate to the latest Netty release.

I have done most of the migration except for the frame and protocol decoders. There might be some issues with frame decoders, but protocol decoders should be fairly easy to implement. Migrating decoders should be fairly trivial task, but because we have 160+ protocols it will take a lot of time.

Notes to consider during migration:

- Replace `ChannelBuffer` with `ByteBuf`
- Use `AdvancedStringEncoder` and `AdvancedStringDecoder` instead of `StringEncoder` and `StringDecoder`
- When sending command or reply to the device use `NetworkMessage` class (explanation below)
- Buffer is now always big endian, but when data is in little endian format use `readXxxLE` instead of `readXxx` like before
- There are some TODOs that I need to fix at some point
- When writing to channel use `writeAndFlush` instead of simple `write`

Biggest change is coming from the way UDP channels are handled now. Before we could get remote address in the decoder. Now instead of receiving buffer and remote address as separate parameters we get a `DatagramPacket`. Which means that UDP and TCP protocol are handler completely different and that's a problem for us. I added `NetworkMessageHandler` class to `BasePipelineFactory` to wrap buffer or string in a `NetworkMessage` object which has data and remote address. This probably means that we can't use standard Netty handlers because they don't know how to handle `NetworkMessage` objects. We'll probably need to find a way to handle frame decoders. Also, that's the reason for using our own string encoder and decoder.

Branch for the work in progress: [netty4](https://github.com/traccar/traccar/tree/netty4).

References to relevant threads: #937, #1338, #3813.

**Comment by Abyss777** [comment]
Very good. I hope it solve some issues like mixed order incoming messages.

I believe you have already know that, but just in case:

> - Core codec classes are moved to the `io.netty.handler.codec` package.
> - `FrameDecoder` has been renamed to `ByteToMessageDecoder`.
> - `OneToOneEncoder` and `OneToOneDecoder` were replaced with `MessageToMessageEncoder` and `MessageToMessageDecoder`.
> - The method signatures of `decode()`, `decodeLast()`, `encode()` were changed slightly to support generics and to remove redundant parameters.


> **HTTP codec**
HTTP decoders now always generates multiple message objects per a single HTTP message:
> ```
> 1       * HttpRequest / HttpResponse
> 0 - n   * HttpContent
> 1       * LastHttpContent
> ```
> For more detail, please refer to the updated `HttpSnoopServer` example. If you wish not to deal with multiple messages for a single HTTP message, you can put an `HttpObjectAggregator` in the pipeline. `HttpObjectAggregator` will transform multiple messages into a single `FullHttpRequest` or `FullHttpResponse`.



Just checklist for porting https://netty.io/wiki/new-and-noteworthy-in-4.0.html#porting-the-server

I want to start from familiar to me teltonika, wondex, wialon, gl200 to feel the new framework, then continue with others.

**Comment by tananaev** [comment]
Sounds good. Let me know if you have any questions. I'll probably work on frame decoders in general and try to do some HTTP-based protocols, specifically OsmAnd.

**Comment by Abyss777** [comment]
Yes, it would be nice to implement OsmAnd for testing

**Comment by tananaev** [comment]
I already have a solution. Working on it as we speak. I'll push it soon.

**Comment by tananaev** [comment]
We will be able to use standard frame decoders and string handlers.

**Comment by tananaev** [comment]
Done. I have just pushed changes to the branch. I've added some wrappers that would allow us to continue using original frame decoders and string decoder/encoder. Should be much easier to migrate.

**Comment by Abyss777** [comment]
Perfect. Did I understand correctly, we can use netty and custom protocol frame decoders/encoders without modifications? They will be wrapped automatically.

**Comment by tananaev** [comment]
Yes, correct.

**Comment by tananaev** [comment]
OsmAnd protocol is ready. Lessons:

- I always forget to use `writeAndFlush` and `NetworkMessage` in response (we would need to keep an eye on this and check that we use it everywhere)
- For HTTP protocols always use `HttpObjectAggregator` and use `Full` request and response versions

**Comment by tananaev** [comment]
I'll start implementing protocols in alphabetical order. When you finished with the ones that you picked you can start from the end of the alphabet, so we don't work on the same decoders.

**Comment by Abyss777** [comment]
Good, agree. Have the same problem with `writeAndFlush`.

Do you have an example with custom frame decoder? Based on old `org.jboss.netty.handler.codec.frame.FrameDecoder`

**Comment by tananaev** [comment]
Another note if you work on binary protocol and it used to be little endian, you need to use `LITTLE_ENDIAN` frame decoder for it.

**Comment by tananaev** [comment]
I have migrated protocols with names that start with "A".

I have implemented a new base class `BaseFrameDecoder` to keep frame decoder code and test same as before. Please use it instead of my previous example.

One more note. Option to use `indexOf` with `StringFinder` was removed from Netty. I am using `ByteBufUtil.indexOf` instead now. See `AtrackFrameDecoder` for example.

Please try to make minimal modifications. Ideally even keep formatting where possible. This is so that we have less merge conflicts and it's easier to track history later.

**Comment by tananaev** [comment]
I don't think it's a good idea to convert whole array into a string.

**Comment by Abyss777** [comment]
`copy` parameter is false
http://netty.io/4.1/api/io/netty/util/AsciiString.html#AsciiString-java.nio.ByteBuffer-int-int-boolean-

**Comment by Abyss777** [comment]
I think it is useful class to treat byte buffers as ASCII strings without actual converting it.

**Comment by tananaev** [comment]
It says storage will be shared "if possible". Not sure what it means.

**Comment by Abyss777** [comment]
Sorry, gave a link to wrong constructor. This one is right http://netty.io/4.1/api/io/netty/util/AsciiString.html#AsciiString-byte:A-int-int-boolean-

"if possible" means if we pass `nioBuffer` and its `hasArray()` is true. At least how I understand the documentation.

**Comment by tananaev** [comment]
I have finished with protocol "B" and "C". Also merged your pull request.

**Comment by Abyss777** [comment]
I'm working on XexunFrameDecoder, it uses search starting from custom index:
https://github.com/traccar/traccar/blob/netty4/src/org/traccar/protocol/XexunFrameDecoder.java#L42

but `ByteBufUtil.indexOf` do not support such search...
Looks like Xexun sends string. Can I use variant with AsciiString? Or any other suggestion?

**Comment by tananaev** [comment]
I actually thought about it already. My suggestion would be to create a sub-buffer. There is a way to create a buffer with different indexed, but same backing array (no copying). But maybe there is a better way.

Another option is to just implement our own util class based on `ByteBufUtil.indexOf` method. It's pretty simple.

**Comment by Abyss777** [comment]
You are right, I believe this will fit:
> ```
> Unpooled.wrappedBuffer(byte[] array, int offset, int length)
> Creates a new big-endian buffer which wraps the sub-region of the specified array.
> ```

**Comment by Abyss777** [comment]
Hm, but there is `int length` then better create a util class to make code shorter.

**Comment by tananaev** [comment]
If you create a utility class please update places where we used `ByteBufUtil`.

**Comment by Abyss777** [comment]
Yes, sure.

**Comment by tananaev** [comment]
Migrated D, E and F protocols.

**Comment by tananaev** [comment]
Migrated G protocols. There were quite a few of those. Also, fixed some code style issues.

**Comment by tananaev** [comment]
Migrated H, I, J and K protocols.

One think we are not handling at the moment is reference counting:

http://netty.io/wiki/reference-counted-objects.html

I think it will work like before, but using reference counting would make code more efficient.

**Comment by Abyss777** [comment]
Great.
Yes, I also noted this feature. We should handle it on one of the next iterations of polishing, after we get fully working code.

Also there is 
> Codec embedder has been replaced by `io.netty.channel.embedded.EmbeddedChannel` to allow a user to test any kind of pipeline including a codec.

I think we can implement testing of full pipeline, not only pieces.

**Comment by tananaev** [comment]
I agree, we should make it working first and then worry about other details.

**Comment by tananaev** [comment]
Migrated L, M and N protocols.

**Comment by tananaev** [comment]
O and P protocols are ready. We are getting close to migrating all of them.

**Comment by Abyss777** [comment]
Very good. I'm slowly working on T, but it is massive. When you come to T please say, we will make the point of convergence.

**Comment by tananaev** [comment]
I finished with R and S. Ready to help you with T.

**Comment by Abyss777** [comment]
I've sent a PR with T protocols I've done today.

I have a difficulties with Little Endian in Tramigo, can't understand how to handle it if we extend `LengthFieldBasedFrameDecoder`

**Comment by tananaev** [comment]
It's easy. You can pass order to `LengthFieldBasedFrameDecoder` constructor. That's still supported.

**Comment by tananaev** [comment]
Migrated remaining protocols. I think the main issue now is to understand how to properly handle reference counting.

**Comment by tananaev** [comment]
Turns out implementing reference counting properly is not that easy. I have started, but there are a lot of places where we create temporary buffers. I marked all places that we need to fix with "TODO".

In many places we create buffer for response content, but then we create another buffer for the full message. We send only the second one, so first one gets leaked. The best option here is instead of writing original content buffer make a wrapped buffer that includes content as a part of it.

There are also some places where we need to decode data in frame decoder. Possibly it's fine, but need to verify, so I marked just in case.

**Comment by Abyss777** [comment]
Also this note
> When a ByteBuf is used in a ChannelPipeline, there are additional rules you need to keep in mind:

> Each inbound (a.k.a. upstream) handler in a pipeline has to release the received messages. Netty does not release them automatically for you.
> Note that codec framework does release the messages automatically and a user has to increase the reference count if he or she wants to pass a message as-is to the next handler.
> When an outbound (a.k.a. downstream) message reaches at the beginning of the pipeline, Netty will release it after writing it out.

Looks like it is rather complex

May help:

> **Automatic buffer leak detection**
> Although reference counting is very powerful, it is also error-prone. To help a user find where he or she forgot to release the buffers, the leak detector logs the stack trace of the location where the leaked buffer was allocated automatically.

> Because the leak detector relies on `PhantomReference` and obtaining a stack trace is a very expensive operation, it samples approximately 1% of allocations only. Therefore, it's a good idea to run the application for a reasonably long time to find all possible leaks.

> Once all leaks are found and fixed. You can turn this feature off to remove its runtime overhead completely by specifying the `-Dio.netty.noResourceLeakDetectio` JVM option.

**Comment by Abyss777** [comment]
Installed netty4 branch on my home server for test and got this from wondex device:
```
2018-06-09 10:45:28 DEBUG: [3ef0c344: 5032 > 178.176.112.244] HEX: d0d70000015ed0b2
2018-06-09 10:45:28  WARN: [3ef0c344] error - refCnt: 0, decrement: 1 - IllegalReferenceCountException (... < ExtendedObjectDecoder:68 < ... < WrapperContext:102 < ... < WrapperInboundHandler:53 < ...)
2018-06-09 10:45:28  INFO: [3ef0c344] disconnected
```

**Comment by Abyss777** [comment]
With teltonika works fine
```
2018-06-09 11:39:02 DEBUG: [1dba827c: 5027 < 85.140.19.207] HEX: 000f333532303934303832323739313439
2018-06-09 11:39:02 DEBUG: [1dba827c: 5027 > 85.140.19.207] HEX: 01
2018-06-09 11:39:03 DEBUG: [1dba827c: 5027 < 85.140.19.207] HEX: 0000000000000107080400000163e3441158002419af1821dde2f300000000000000000704ef00f0005000c80203423206430fa4440000000000000163e344dc78002419af1821dde2f300000000000000450f06ef00f00050001500c800450208b5000cb6000$
2018-06-09 11:39:03 DEBUG: [1dba827c: 5027 > 85.140.19.207] HEX: 00000004
2018-06-09 11:39:03  INFO: [1dba827c] id: 352094082279xxx, time: 2018-06-09 11:37:59, lat: 56.81897, lon: 60.56630, course: 0.0
2018-06-09 11:39:03  INFO: [1dba827c] id: 352094082279xxx, time: 2018-06-09 11:38:51, lat: 56.81897, lon: 60.56630, course: 0.0
2018-06-09 11:39:03  INFO: [1dba827c] id: 352094082279xxx, time: 2018-06-09 11:38:52, lat: 56.81897, lon: 60.56630, course: 0.0
2018-06-09 11:39:03  INFO: [1dba827c] id: 352094082279xxx, time: 2018-06-09 11:38:55, lat: 56.81897, lon: 60.56630, course: 0.0
2018-06-09 11:39:03  INFO: [1dba827c] disconnected
```

**Comment by tananaev** [comment]
Fixed the issue: https://github.com/traccar/traccar/commit/58a222ba3d546dc2366586f2c904e70680a394bd.

**Comment by Abyss777** [comment]
Thanks. Working now.

**Comment by tananaev** [comment]
I have handled all TODOs with reference counting. For now I decided to simply use same code and call release after buffer is used. It should work fine assuming that there are no exceptions in the code between allocating and releasing buffers. Frame decoders seem to work correctly and don't require any changes.

Do you think the code is ready to be merge to master now?

**Comment by Abyss777** [comment]
Very good.
I recompiled and installed it on my home server yesterday, with `-Dio.netty.leakDetectionLevel=advanced`

Works fine with teltonika and OsmAnd without any errors and any leakage detected.
I believe it is rather stable to be merged to master.

**Comment by tananaev** [comment]
I am working on some new protocols at the moment. I'll merge it all together after I'm finished.

**Comment by tananaev** [comment]
Branch has been merged into master.
