### ISSUE TITLE
Different location on map and reports

### ISSUE THREAD

**Issue by LucasBSC** [traccar/traccar#3922]
Hi Anton,

I have the following issue here:

https://ibb.co/kKmQiT

My route report shows a location that I know it is true, since I validated it locally. But the green marker kees popped-up on a different location I do not know why, probably an old one position.

Could you have a guess why is this happening?

We have a VPS hosted with the MySQL DB and this server application is hosted on a different VPS with its DB pointed to the MySQL DB on the previous machine.

Thanks.

**Comment by tananaev** [comment]
Please provide a screenshot from your "current" location with state info.

**Comment by LucasBSC** [comment]
The current physically location is the blue marker but the "current" location with state info is the following 
![screen shot 2018-06-08 at 5 11 22 pm](https://user-images.githubusercontent.com/32658387/41178928-485d63b2-6b3f-11e8-994d-079d77784182.png)

**Comment by tananaev** [comment]
As you can see, the year is 2032. This issue has been discussed countless number of times. I'm closing this. Please use search.
