### ISSUE TITLE
Location Updates when screen is Off

### ISSUE THREAD

**Issue by born-confused** [traccar/traccar#3927]
Sir, how do we tackle the issue of Doze mode that was introduced in android 6+
Traccar app isn't able to send location updates because it goes to doze mode and not standby mode
https://developer.android.com/training/monitoring-device-state/doze-standby

Waiting for your valuable input in this!

**Comment by tananaev** [comment]
What makes you think it doesn't handle it? Traccar Client uses foreground service which is not affected by doze mode.

Next time please create issue in appropriate repository. This one is for server only. There is a separate one for Traccar Client.
