### ISSUE TITLE
site can’t be reached :: api/positions

### ISSUE THREAD

**Issue by m-menon** [traccar/traccar#3928]
I was just trying out the latest version (3.17) and realized that the positions api doesn't work. The other APIs like devices, session, users etc all seem to work. api/positions returns

```
This site can’t be reached
The webpage at https://abc.example.co/api/positions might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
```
Does anyone hold a clue?

**Comment by tananaev** [comment]
Have you specified accept header in the request?

**Comment by m-menon** [comment]
Oops, that was it! :)

**Comment by tananaev** [comment]
Yes, most APIs work without it because only return option is JSON. Positions support CSV and other options.

**Comment by m-menon** [comment]
Alrighty, cool

**Comment by php1999** [comment]
Can anyone please help me how to "accept header in the request" to solve the issue?
