### ISSUE TITLE
Feature Request: Speed on the events report

### ISSUE THREAD

**Issue by LucasBSC** [traccar/traccar#3929]
Hello Anton,

Since the feature of the geofence speed limit was implemented, the field of Geofence on the Events Report was added like this image below:

![traccargeofence](https://user-images.githubusercontent.com/32658387/41244169-9e6a9d78-6d7a-11e8-935e-49e80fe32fb8.PNG)

Would it be possible to add also a field called 'Speed' on this very table? So it could display also the excessive speed which the geofence was crossed and one could export a report to handle these data.

Currently, as we click on a specific row, the speed is shown on the 'State' tab, but it would be better for sure to see it side by side on the reports tab.

Best regards!

**Comment by vitormfreis** [comment]
I also want to know how to do it!

**Comment by cesarserafim** [comment]
it is probably possible by modifying the XLSX template in the /templates/export folder.

**Comment by tananaev** [comment]
Added event data here https://github.com/traccar/traccar-web/commit/a2a8644deefc80c920b05e3bbb36efb60cfc88f8. Speed value is also there.
