### ISSUE TITLE
Feature Request, New categories!

### ISSUE THREAD

**Issue by mattfleaydaly** [traccar/traccar#3930]
Would love a new category please, Train!
This will go well for train services. A simple train icon would be amazing!!

**Comment by mhuzqu** [comment]
i think you just add SVG image and add some code in load.js (see window.Images array)

**Comment by mattfleaydaly** [comment]
Thanks Mate!!

**Comment by mattfleaydaly** [comment]
Happened to notice that the image adds, however the title text for the icon doesn't. Any ideas?

**Comment by mhuzqu** [comment]
You should edit the .svg file, open the .svg file it will be xml format. For example, open up the truck.svg, you should find the tag with string "truck", so if you have train.svg, change the tag to "trai" too

**Comment by mattfleaydaly** [comment]
Thanks for the reply!
Attempted this with no success finding those tags

**Comment by tananaev** [comment]
They provide free licenses for open source projects.

**Comment by Abyss777** [comment]
Do you have one? Can you download that icons in svg?

**Comment by tananaev** [comment]
Looks like they downgraded our license. Not able to download SVGs. I will check with their support if they still provide it.
