### ISSUE TITLE
API returns Unexpected 'H' when trying to get registered devices

### ISSUE THREAD

**Issue by rakeshbaral92** [traccar/traccar#3934]

**Comment by tananaev** [comment]
Clearly the request that you are sending to the API is incorrect.

**Comment by rakeshbaral92** [comment]
How to resolve that ?

**Comment by tananaev** [comment]
To resolve you have to use correct format. If you don't know what it should look like, check what official web app sends. Also, read Traccar documentation and general information about REST API and JSON. There is plenty of information online to resolve the issue. You just need to do your research.
