### ISSUE TITLE
Unable to get the parameter.

### ISSUE THREAD

**Issue by rakeshbaral92** [traccar/traccar#3938]
I am unable to get the parameter value. What is this parameter dc which is after route in the API ?
```
http://demo4.traccar.org/api/reports/route?_dc=1529060076993&deviceId=14207&type=allEvents&from=2018-06-14T23%3A15%3A00.000Z&to=2018-06-16T17%3A15%3A00.000Z&page=1&start=0&limit=25
```

**Comment by tananaev** [comment]
You don't need dc parameter. It's ignored on server.

In future use forum for questions.
