### ISSUE TITLE
Missing house numbers ?

### ISSUE THREAD

**Issue by LarsNorgaard** [traccar/traccar#3939]
Hi,

I don't know what happened, but I can't traccar to display any house/street numbers today.
The version I'm using is 3.17, but I did a clean install of 3.16, because I was 100% it worked the other day.

Also seems they are missing on the demo server 5 right now.

Is it an local issue or is the pooling from osm bugged today?

 - Lars

**Comment by tananaev** [comment]
We changed default map layer. You can always switch back to OSM in settings.
