### ISSUE TITLE
Тэг: Предложение

### ISSUE THREAD

**Issue by MAPIIIAJI** [traccar/traccar#3940]
![icon_new3](https://user-images.githubusercontent.com/35526267/41496793-a92c31b4-7161-11e8-9d7f-1864e9a4dcdd.png)

Антон, добрый день! Хочу внести маленькую лепту (для начало) в ваш проект. Отправляю Вам новый вариант логотипа для рассмотрения.

**Comment by tananaev** [comment]
Пожалуйста аргументируйте чем ваш вариант лучше текущего логотипа.

**Comment by MAPIIIAJI** [comment]
1. Образ спутникой тарелки более объективно отражает реальную форму спутникой тарелки;
2. Бренды с мировым статусом стараются использовать простой в конструкции логотип (с использованием меньшего количества элементов), но при этом понятный и отражающий род их деятельности. Суть второго пункта - простота.

**Comment by tananaev** [comment]
Вы профессиональный дизайнер? Мне кажется что в вашем лого отсутствует один из самых важных моментов - симметрия.

**Comment by MAPIIIAJI** [comment]
Нет, я не профессиональный дизайнет. Но этот момент (симметричность элементов) всегда можно поправить!

**Comment by tananaev** [comment]
Честно говоря мне наш текущий вариант больше нравится. Единственное что можно было бы поменять это цвет, но это уже сделано. В последней версии цвет с черного заменен на темно-голубой чтобы сочетаться со стилем ExtJS.

**Comment by MAPIIIAJI** [comment]
Спасибо, что выделили время чтобы ответить. За ваш проект же отдельное вам спасибо.
