### ISSUE TITLE
Geocoding failed

### ISSUE THREAD

**Issue by eangulus** [traccar/traccar#3941]
Using Traccar 3.17 on Ubuntu 18.04 with Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 25.171-b11

Whatever service I try to use for reverse geocoding I get the following error:

```
Geocoding failed - java.net.ConnectException: https://locationiq.org:443 - ExecutionException (...)
```
OR
```
Geocoding failed - java.net.ConnectException: https://maps.googleapis.com:443 - ExecutionException (...)
```

I haven't used this before so I cannot be over limits. And besides this error is happening for both Google and LocationIQ.

My Config is:

```xml
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <entry key='config.default'>./conf/default.xml</entry>

    <!--

    This is the main configuration file. All your configuration parameters should be placed in this file.

    Default configuration parameters are located in the "default.xml" file. You should not modify it to avoid issues
    with upgrading to a new version. Parameters in the main config file override values in the default file. Do not
    remove "config.default" parameter from this file unless you know what you are doing.

    For list of available parameters see following page: https://www.traccar.org/configuration-file/

    -->

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>nominatim</entry>
    <entry key='geocoder.url'>https://locationiq.org/v1/reverse.php</entry>
    <entry key='geocoder.key'>********</entry>
    <entry key='geocoder.format'>%f</entry>
    <entry key='geocoder.reuseDistance'>500</entry>

    <entry key='filter.enable'>true</entry>
    <entry key='filter.distance'>10</entry>
    <entry key='filter.duplicate'>true</entry>
    <entry key='filter.maxSpeed'>80</entry>

    <entry key='distance.enable'>true</entry>

    <entry key='processing.remoteAddress.enable'>true</entry>

    <entry key='forward.enable'>true</entry>
    <entry key='forward.url'>https://********/tools/krcspeedlimit/?lat={latitude}&amp;lon={longitude}&amp;speed={speed}&amp;name={name}</entry>

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://********:3306/traccar?useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
    <entry key='database.user'>krc.traccar</entry>
    <entry key='database.password'>********</entry>

    <entry key='event.motion.speedThreshold'>1.07991</entry>

    <entry key='report.trip.useIgnition'>true</entry>

</properties>
```

(Private information replaced with ********

**Comment by tananaev** [comment]
From the error message it seems like you have some network issues on the server.

**Comment by eangulus** [comment]
In terms of what?

Everything else seems to be working fine so far. Tracking works, remote viewing of the UI works.

The setup is behind a separate Apache Reverse proxy with the following config:

```
<VirtualHost *:443>
    # TRACCAR-SERVER-GPS-KRC-01
    ServerName gps.krc.direct
    ServerAlias traccar.krc.direct track.krc.direct

    RemoteIPHeader X-Forwarded-For
    
    ProxyPass /api/socket	"ws://********:8082/api/socket"
    ProxyPassReverse /api/socket "ws://********:8082/api/socket"    
    ProxyPass /	"http://********:8082/"
    ProxyPassReverse / "http://********:8082/"

    Use SSLCertificates
   Use ErrorLogs
</VirtualHost>
```

**Comment by tananaev** [comment]
Clearly outgoing HTTPS request from your server fails. Possibly it's blocked somewhere on the firewall.

**Comment by eangulus** [comment]
Nope. Already thought of that.

this URL works from the server directly.

https://maps.googleapis.com/maps/api/geocode/json?latlng=-32.260197,148.606785&language=en

Returns the JSON result.

**Comment by eangulus** [comment]
443 is directed to Apache in the firewall on the router.

But I cant see how that would matter. Port 8082 and device ports are mapped to the traccar server IP.

**Comment by tananaev** [comment]
Connection clearly fails. I don't know what else I can say.

**Comment by eangulus** [comment]
Well, me neither as everything works fine on the server, the test URL calls fine from the same server etc. The only issue is Traccar can't call it.

There is no firewall on the server itself. No blocking of ports etc. The server is receiving all other data and sends all other data.

Is there a way to get more information from the logs than what I am currently getting?

And another confirmation that network is fine, the maps show.

**Comment by eangulus** [comment]
Could it be Java as the error does say java.net.ConnectException?

**Comment by eangulus** [comment]
Also just tried from command line:  curl https://maps.googleapis.com/maps/api/geocode/json?latlng=-32.260197,148.606785&language=en

And I get the JSON result fine too.

**Comment by eangulus** [comment]
Java SSL wasn't mentioned in the install instructions.

Do I have to configure them?

**Comment by eangulus** [comment]
OK just made another test.

In the config, I change the URL from https://locationiq.org/v1/reverse.php to http://locationiq.org/v1/reverse.php

THis then works.

So it seems that Java cannot communicate over 443.

At this stage, I am at a dead end as I have refreshed the Java certs and it didn't fix it.

I am not sure now what to do as I am unsure if it is Java's end, the Apache Reverse Proxy (thou I configured according to instructions). SSL works from every other part of Ubuntu just not from Java.

**Comment by tananaev** [comment]
It seems like SSL certificates are misconfigured for your Java VM. How did you install it?

**Comment by eangulus** [comment]
Installed it using like this:
sudo apt-get install default-jre

**Comment by tananaev** [comment]
There must be some issue with the package or your system then.

**Comment by eangulus** [comment]
I may have to give up then.

This is the 3rd clean install of Ubuntu 18.

I have nothing else on the system, no special configs or anything like that. It is set up 100% as a Traccar server. I have done 3 installs as I played with it first, then the second run I screwed something up on it. The 3rd is my proper setup to go into production.

Reverse Geocode has never worked on any of the setups. I followed all instructions to the letter. Have everything else running fine and I even have other Java-based servers running 100% fine on the same network with similar setups (Xen VM's behind Apache Proxy).

Traccar is the ONLY one that seems to have this issue. I can connect to SSL via curl, via Webmin Tunnell etc.

I have tried looking into the Java SSL issues, I have regenerated certificates for Java and did all that I can to make sure its a standard install.

I can see the requests leaving the network on the router, all other computers can see SSL websites with no issues.

I know you keep saying its a java issue, but for all the testing and setups I have done, this is a Java & Traccar issue.

Java & my other servers don't have this problem.

Because I don't know what else to do or even look at, and with all my testing saying everything is good otherwise, and with you saying it's not Traccar its Java, then I give up.

I can do without the reverse geocode but I am also trying to do forward.enable but the URL is also SSL and without it, the whole reason for using this falls flat.

**Comment by tananaev** [comment]
I would recommend to install previous stable version of Ubuntu.

**Comment by eangulus** [comment]
Seeing it's my only real option, I'll try that.

I'll setup an Ubuntu 16 VM and report back here when I'm done.

**Comment by eangulus** [comment]
Question.

I don't want to lose my existing data. It is running on an external MySQL server.

Will just resetting up the connection keep all the data that already there?

**Comment by tananaev** [comment]
Yes, all data should be there.

**Comment by eangulus** [comment]
That worked.

So for what its worth for some reason, Ubuntu 18.04 will not work 100% with Traccar 3.17

**Comment by tananaev** [comment]
I have heard about issues with Ubuntu 18.04. It will work eventually. It will probably work fine if you install older version of JRE there.
