### ISSUE TITLE
Problem with Trigger in positions table

### ISSUE THREAD

**Issue by jackeychina** [traccar/traccar#3942]
I have added 1 trigger in position table . 
```sql

ALTER TRIGGER [dbo].[positions_AFTER_INSERT]  ON  [dbo].[positions]
   
AFTER INSERT

AS

DECLARE @Imei VARCHAR(50), @PacketDt DateTime, @Lat float, @Lng float, @Spd decimal(10, 2), @IGN VARCHAR(6) , @IGNITION int = 0
DECLARE @attributes VARCHAR(MAX),@deviceid int

SELECT	@PacketDt=devicetime,@Lat=latitude,@Lng=longitude,@Spd=speed,@attributes=attributes	,@deviceid=deviceid
FROM INSERTED

IF(@PacketDt IS NOT NULL)
BEGIN

		 Select @IGN = StringValue from parseJSON(@attributes) where NAME = 'ignition'

		 IF (@IGN = 'true')
				set @IGNITION = 1
		 ELSE
				set @IGNITION = 0
				
		 select @Imei = uniqueid from devices where id = @deviceid
		 
		 set @Spd = 1.852*@Spd
				
	     SELECT @ALERT_STRING = '1~' + CAST(@IGNITION AS VARCHAR(20) ) + '#' + '2~1'

		 EXEC TRACC.DBO.INSERT_DATA @Imei, @Lat, @Lng, @PacketDt, @Spd , @IGNITION, '',''				   
END 

```
In this trigger it will get data from position table and then send to other database stored procedure.

Now when i enable this trigger it will send all data to other database stored procedure but after that it will not showing data on traccar web.

What is the issue with trigger ? Why traccar web not showing any data after called this trigger ?

**Comment by jackeychina** [comment]
@jpmens  @gahissy  @kero99  @ulion  @stevebma  please review this

**Comment by jackeychina** [comment]
@tananaev  please review this.

**Comment by tananaev** [comment]
It doesn't seem to be related to Traccar code. If you need help with customisation, there is always paid support option:

https://www.traccar.org/product/professional-services/
