### ISSUE TITLE
OpenChannelHandler and NetworkMessageHandler

### ISSUE THREAD

**Issue by azzahrah** [traccar/traccar#3945]
Helo

I just wonder, why you create OpenChannelHandler and NetworkMessageHandler when those can merger into single handler for handler connection and incoming message?

**Comment by tananaev** [comment]
To separate different functionality. Why would you combine those?

**Comment by azzahrah** [comment]
To process process, I think to many handler in Pipeline will need more process, this just my opinion

**Comment by tananaev** [comment]
Sorry, but I don't understand what you are saying. Please explain. What do you mean by "reduce process"?

**Comment by azzahrah** [comment]
"Reduce process", as i remember netty always call handler from first to end in pipeline, and this consume time to execute every handler

**Comment by tananaev** [comment]
Combining two handlers into one won't improve anything. Same logic needs to be executed, so it will consume exactly the same amount of CPU time, if that's what you are talking about.
