### ISSUE TITLE
Geofence does not check group ID

### ISSUE THREAD

**Issue by siilats** [traccar/traccar#3952]
1. I create a regular user and regular geofence from admin account
2. I give user access to a group
3. I give group access to geofence
4. I log in as the user. He should have access to geofence but does not.
5. I give in addition to the group, the user access to the geofence, then log in as the user, then the user can see the geofences, and also when queries geofences of the group, can see those.

I was looking under api/resource comparing devices and geofences, geofences does not have any group specific code so it looks like it ignores group permissions. This is version 3.16

**Comment by tananaev** [comment]
I think you misunderstand how groups work in Traccar. Group is just a group of devices, so there is very little difference between device and group in terms of permissions. If you link geofence to a device that two users have access to, it won't automatically give access to that geofence to both users. Same with groups.

Groups can only be used to control access to devices, but not other entities.

**Comment by siilats** [comment]
Makes sense. Please add a configuration flag "Make all geofences public" there is no need to have access control on the geofences. I use geofence attributes to figure out whats going on. User logs in, then sees a device, checks the geofences figures out how much it costs etc.

**Comment by tananaev** [comment]
We can leave it here for now and see if other people are interested in this feature.

**Comment by siilats** [comment]
Thinking about this, actually the parameter needs to give readonly as public, you don't want users editing the geofences ...

**Comment by tananaev** [comment]
Doesn't look like there's a lot of interest, so I'm going to close for now, but we can reopen if more people ask for it.
