### ISSUE TITLE
Help to add GPS 303G

### ISSUE THREAD

**Issue by arturo1704** [traccar/traccar#3954]
Hi everybody, I'm newbie in traccar, i hope you can help me and understandme. (English is not my natal language, i'm working in that)
Well, look, i've downloaded and installed traccar on windows, at this point everything it's Ok, the inssue came when i try add my device, i writte the ID (I read the ID is the IMEI) and the Name, but its nothing happen.
On my router i configured my ip DMZ

My GPS is 303G 
WINDOWS 7 64x
Public IP.
Router Huawei  HG658d
Infinitum TELMEX MEXICO.

I hope you can help me to configure it, because i have another 3 devices to add.

**Comment by tananaev** [comment]
Have you configured your device to report data to the server? If not, do it. If yes, follow this:

https://www.traccar.org/troubleshooting/

If you have any further questions use forum, not GitHub.
