### ISSUE TITLE
E-mail not working on "demo.traccar.org"

### ISSUE THREAD

**Issue by canove** [traccar/traccar#3955]
Hello!

I use demo server to track my motorcycle. Some days ago, I stopped to receive e-mail notifications.

I checked the account atributes and all seems to be ok. When I press the "Send test notification" button, I get this error:

![image](https://user-images.githubusercontent.com/24817866/42067725-18fa0c44-7b1e-11e8-968a-dd1dea68a5a2.png)

I also tested the same configuration on "demo5.traccar.org" and notifications works well. 

Thanks.

**Comment by tananaev** [comment]
I have restarted server just in case. If it doesn't help, there must be something with your email service.

**Comment by canove** [comment]
I have tested the same configuration on demo5.traccar and it works. I also tried to configure another smtp server, and receive the same error on demo.traccar.

I even tested with a brand new account, and just get the same "communication error" on demo.traccar.  Without a log to troubleshoot its hard to say that is my e-mail server. =\

**Comment by tananaev** [comment]
Check browser console for more info about request.
