### ISSUE TITLE
Classes and packages sorting

### ISSUE THREAD

**Issue by Abyss777** [traccar/traccar#3956]
I have two suggestions about classes in packages list optimizing

**org.traccar**
It contains 36 classes now, I think we can sort them out in some sub-packages. For example some pipeline related classes move to `org.traccar.pipeline` or something.
Base geolocation and geocoder classes move to appropriate sub-packages.
May be you have another vision...

**org.traccar.notification**
I have a feeling that firstly we need rename `NotificationWeb`, `NotificationMail` etc. to `NotificatorWeb`, `NotificatorMail` etc.
And maybe move them to `org.traccar.notificators` package with base class `Notificator` and `NotificatorManager`, but I'm not sure.

What do you think?

**Comment by tananaev** [comment]
I think we should move any netty pipeline and general network-related classes into a `network` package.

Agree with notifications renaming.

**Comment by tananaev** [comment]
Closing as some of it is already implemented.
