### ISSUE TITLE
Geofence coordinates can exceed valid bounds

### ISSUE THREAD

**Issue by rkscott** [traccar/traccar#3957]
### lon value can exceed 180º (or indeed 360º)

**Steps to reproduce:**
Create a geofence
Zoom out to see 'world'
spin the world round once (i.e. head east until you are back where you started)
zoom back in and create another geofence.

**Expected result:**
Both geofences should be visible.

**Actual Result:**
Only the first geofence is visible.  
In the db the value for the second geofence area is typically the invalid  CIRCLE(1.234 -367.8, 123)

This could possibly be eliminated using modulo operation ???
`return ((lon + 180) % 360) - 180 ;  // or similar`

**Comment by Abyss777** [comment]
I think it is openlayers library which cause the problem, firstly that generates geometry with invalid(?) coordinates, secondly could not show such geometry correctly.

Also I'm not sure that we should normalize such geometries on the server side. Imagine that you live near the 180 lon (in Russia :)
How do you differentiate (66,179) -> (66,-179) is it "line" (66,179) -> (66,181) or "line" around 358 degrees?

**Comment by rkscott** [comment]
if we consider lon is a double data type, and
` lon = ((lon + 180) % 360) - 180;` 

for lon = 179.9999...
lon would remain correct as 179.9999...

for lon = -179.9999... 
lon would remain correct as  -179.9999...

for lon = -180
lon would remain correct as  -180

for lon = 180  
lon would be converted to -180 (this value being perfectly valid and equal to 180)

I'm not sure I can see any value for a normalized lon that would upset our Russian friends... :-)

**Comment by tananaev** [comment]
I believe that we are just using OpenLayers API, so if there is a problem it's on OpenLayers side.

**Comment by rkscott** [comment]
Anton,
I'll close the issue as I expect any workaround to normalize Openlayers output may well create other issues. e.g. lines/polygons that bridge the 180th meridian.
I can see [similar threads](https://github.com/openlayers/openlayers/issues/7756) over at the Openlayers issue tracker
