### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [traccar/traccar#3964]
Greetings, Im a graphics designer here on Github and I would like to ask for your permission to design for your logo/icon that you maybe used for your future plans in your project. I want to help open source projects by designing logos or banners for there project. Thank you for your time reading this

Best regards
-jbeguna04

**Comment by tananaev** [comment]
Do you have a link to your design portfolio that we can check?

**Comment by jbeguna04** [comment]
@tananaev , Greeting, You can visit my profile to see recent activities of the Logo's done in other github projects.

**Comment by jbeguna04** [comment]
https://github.com/angrykoala/wendigo
https://github.com/gaborbata/jpass
https://github.com/f2prateek/dart
https://github.com/FreeTubeApp/FreeTube

**Comment by tananaev** [comment]
OK, is it only 4 so far? Do you have any other professional work to show?

**Comment by jbeguna04** [comment]
Those are professionally done. But If you have a doubt on it, I didn't have a compilation of all of my work. Thank you for your time and responses

**Comment by tananaev** [comment]
I think we're pretty happy with the current design, but I'm going to close this for now.
