### ISSUE TITLE
Adding IP address and port info

### ISSUE THREAD

**Issue by suncho26** [traccar/traccar#3965]
It will be good if the next version adds the ability to record the IP address and port of each GPS device.

**Comment by tananaev** [comment]
You can already record IP addresses. There is no port number, but you have protocol which identifies port.

**Comment by suncho26** [comment]
How we can put IP address to forward functionality?

**Comment by tananaev** [comment]
I don't understand the question.

**Comment by suncho26** [comment]
How I can put IP address of the device inside <entry key='forward.url'>. What the parameter should be?

**Comment by tananaev** [comment]
Please read documentation before asking questions like this.

https://www.traccar.org/configuration-file/
