### ISSUE TITLE
found wierd data stream (could not be an issue)

### ISSUE THREAD

**Issue by benj-c** [traccar/traccar#3967]
the usual format of `TK103` `BP05` command looks like this,
```
(027045392677BP05355227045392677180706A0657.1036N07954.9172E000.1192652000.0001000000L00000000)
```

but i found something like this long data stream,
```
(027044925311BP05355227044925311180706A0657.1053N07954.9176E000.3191540000.0001000000L00000000)(027044925311BR00180706A0657.1045N07954.9177E000.2191550000.0001000000L00000000)(027044925311BR00180706A0657.1041N07954.9181E001.2191600000.0001000000L00000000)(027044925311BR00180706A0657.1045N07954.9183E000.4191610000.0001000000L00000000)
```

this is just one string, what could be this ?

**Comment by tananaev** [comment]
It looks like several messages. Why would that be an issue?

**Comment by benj-c** [comment]
no no, i's not an issue, i just asked, but is it possible to contain several messages as one, this just happened for the first time, i thought something was wrong with the device, is it possible ?

**Comment by tananaev** [comment]
Nothing is wrong. It's perfectly fine behaviour.
