### ISSUE TITLE
ST-902

### ISSUE THREAD

**Issue by Lkissane** [traccar/traccar#3968]
Hi all,
Just recieved my tracker.
I have inserted the SIM
Plugged the device into the OBD port in my car.
Blue light flashing (no GPS?)
Orange light static
I have attempted sending sms as directed by the user manual but its still not showing any changes in the user interface.
Help this poor little sausage before I attempt to drive off a cliff in frustration!

**Comment by tananaev** [comment]
For questions about devices there is forum:

https://www.traccar.org/forums/forum/devices/

**Comment by Lkissane** [comment]
Hi Ive checked the forums and none answer my questions

**Comment by tananaev** [comment]
You can create a new topic. GitHub is not the right place.
