### ISSUE TITLE
As of version 3.15, the status of the device is not changed correctly from unknown to disconnected.

### ISSUE THREAD

**Issue by jcorreajr** [traccar/traccar#3970]
How to simulate the problem:

**Traccar version: 3.14**

Default installation

. Ubuntu 14.04
. java version "1.8.0_171"

Options configured in traccar.xml:
```
   <entry key='status.timeout'>120</entry>
   <entry key='server.timeout'>180</entry>
```
Simulation of sending device position using the Netcat tool:

```
$ nc SERVER 5001
```
send command: 
```
imei:123987,tracker,180704003958,,F,163954.000,A,2900.5697,S,05115.2764,W,0.00,0;
```
Note; The device ID 123987 must already be created on the Traccar

* What happens:
1 - After 2 minutes without sending new positions the status of the device changes from 'OnLine' to 'Unknown'
2 - After 3 minutes without sending new positions the status of the device changes from 'Unknown' to 'Disconnected'

*This behavior is normal.*

**Traccar version: 3.15, 3.16, 3.17**

. Default installation
. Ubuntu 14.04
. java version "1.8.0_171"

Options configured in traccar.xml:
```
   <entry key='status.timeout'>120</entry>
   <entry key='server.timeout'>180</entry>
```
Simulation of sending device position using the Netcat tool:
```
$ nc SERVER 5001
```
send command: 
```
imei:123987,tracker,180704003958,,F,163954.000,A,2900.5697,S,05115.2764,W,0.00,0;
```
Note; The device ID 123987 must already be created on the Traccar

* What happens:
1 - After 2 minutes without sending new positions the status of the device changes from 'OnLine' to 'Unknown'
2 - The Device **never changes its status to 'Disconnected'**

*This is problematic behavior*

Note: For the simulation, the gps103 protocol was used. Port 5001/tcp

**Comment by tananaev** [comment]
Do you have `status.ignoreOffline` parameter in any of the config files?

**Comment by jcorreajr** [comment]
For the above simulation, I used the default configuration files, just adding the options: *status.timeout and server.timeout*

**Comment by tananaev** [comment]
OK, can I have access to the server to try myself?

**Comment by jcorreajr** [comment]
Do I send the information for connection by email?

**Comment by tananaev** [comment]
Sure, you can send by email.

**Comment by jcorreajr** [comment]
Okay, I sent the information by email support@traccar.org

**Comment by tananaev** [comment]
I have tested on the latest code and it works correctly, so I'm closing this. You have to either wait for next release or build a version from source code.
