### ISSUE TITLE
Teltonika - Map the gps status

### ISSUE THREAD

**Issue by TheITCloud** [traccar/traccar#3973]
The GPS Status for teltonika should be mapped:

![image](https://user-images.githubusercontent.com/3840996/42807239-8992f9de-89b0-11e8-9357-0f14c8cd184f.png)

**Comment by tananaev** [comment]
What should we map it to?

**Comment by TheITCloud** [comment]
I've added a PR for it: https://github.com/traccar/traccar/pull/3974

**Comment by tananaev** [comment]
Looks like you just saved the value instead of mapping it to appropriate attributes.

**Comment by TheITCloud** [comment]
Indeed, my change adds the gpsStatus to the attributes of a Position.

Should I have mapped it differently? I see that Position.KEY_GPS already exists, should I be using that to map the value?

**Comment by tananaev** [comment]
I think it should be mapped to validity state.

**Comment by TheITCloud** [comment]
I've updated my PR to map the gpsStatus to validity state (it already uses satellites for validity as well).

**Comment by tananaev** [comment]
It looks like it's not a universal solution, so I'll have to change it. Different documentation:
![screen shot 2018-07-28 at 10 04 24 am](https://user-images.githubusercontent.com/1161863/43348332-addb5fde-924d-11e8-9101-15a1fcac2bcc.png)

**Comment by TheITCloud** [comment]
Maybe we should retain the previous validity logic then? 

See: https://github.com/traccar/traccar/pull/3974/files

**Comment by tananaev** [comment]
I'm actually removing that logic from all decoders. We shouldn't determine validity on the server side. Device should either report it explicitly, or we should assume that it's valid.
