### ISSUE TITLE
SQL Server Install

### ISSUE THREAD

**Issue by dark-equinox** [traccar/traccar#398]
Hi. Installed traccar, runs fine on H2 database. I see there are other issues running this on windows and ms sql server. Can you give me the scripts to create the tables in sql server? Web service is not creating them. I attached my config just in case. I can log in to site just fine, add device, no issues, but doesn't display any information from device. weird that it will save the device, but i have no tables...

Any help would be appreciated.

 <entry key='database.driverFile'>C:\Program Files (x86)\Traccar\lib\sqljdbc4.jar</entry>
<entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
<entry key='database.dataSource'>com.microsoft.sqlserver.jdbc.SQLServerDataSource</entry>
<entry key='database.dataSource'>com.microsoft.sqlserver.jdbc.SQLServerDataSource</entry>
<entry key='database.url'>jdbc:sqlserver://my-PC\SQLEXPRESS;databaseName=Tracking;user=user;password=password;</entry>
<entry key='database.user'>user</entry>
<entry key='database.password'>password</entry>

**Comment by iamstanly** [comment]
trying to use MS SQL with traccar.. but its not working...

**Comment by tananaev** [comment]
What errors do you get in the log files?
