### ISSUE TITLE
Support for Chinese characters 

### ISSUE THREAD

**Issue by danielnitu** [traccar/traccar#3982]
Hi,

I have a question and couldn't register for the forums, so I'll post here.
Is traccar able to handle Chinese characters? We bought a device and tried to configure it to send data to our servers, but all we're getting on our logs is something like:
```
some binary data
```

Thanks!

**Comment by tananaev** [comment]
It's not Chinese characters. It's binary data, so you shouldn't try to convert it into text.

**Comment by danielnitu** [comment]
Thank you! Any work around this? Our current devices send data like this:
imei:868683027xxxxxx,tracker,18072104xxxx,,F,204055.000,A,5111.3368,N,00016.4584,E,0.01,22.50,,0,,,,;

**Comment by tananaev** [comment]
To decode binary data you need protocol documentation.

**Comment by danielnitu** [comment]
Thank you for your help. I've found some more helpful resources on Traccar's forum. I'll close the issue.
