### ISSUE TITLE
API support for adding locations

### ISSUE THREAD

**Issue by leifnel** [traccar/traccar#3983]
If the API supported adding locations, it would be fairly easy to create a webapp which both showed your location and your group.

A webapp can get the users location, and it could send data to a port emulating a physical tracker, but an API would be easier.

An input API would also be useful for integrating data from other applications. (For instance locations from sportstrackers like Endomondo)

**Comment by tananaev** [comment]
How is API easier than for example using OsmAnd protocol?

**Comment by leifnel** [comment]
The OsmAnd protocol is indeed very easy to use. I didn't know about it.
