### ISSUE TITLE
GT-06 Continuous Login Packet 

### ISSUE THREAD

**Issue by elixirtechne** [traccar/traccar#3985]
Hello,

I have developed a GT-06 receiver in C++ (Linux) with Asynchronous mode. I am using e-poll mechanism.
This is a single threaded server which will read and process data and converted it into JSON string. The server works fine upto 10 devices sending data but then after the device starts sending only Login packet and Heartbeat packets. I can get instant data for ignition ON and OFF but the GPS packets are not coming.

I verified that there is no connection kept in queue.

Does anyone here help me to provide any pointers?

Thanks in advance.

Regards,
Jitendra Sanghani

**Comment by tananaev** [comment]
Closing as it's not related to Traccar project. Personally I suspect there is a bug in your code because we have more that 10 GT-06 devices working on a single server without any issues.
