### ISSUE TITLE
Route line on map is not correct ! Help

### ISSUE THREAD

**Issue by macano13** [traccar/traccar#3989]
Hi,
Can someone help me, when i go to the Reports and check Route , my route line is not correct , first the Route line doesnt follow the road, the second is that Route line show some route  where I did not go at all . Can someone please help me with this, is it my phone problem and is there any solution for this problem ? I attached  pictures of the problem 

![traccar1](https://user-images.githubusercontent.com/42044350/43603100-470f663a-9692-11e8-8551-1fe7161e5abd.jpg)

**Comment by tananaev** [comment]
That's what your device reported.
