### ISSUE TITLE
Build failure: (Test errors)

### ISSUE THREAD

**Issue by ibrahimertok** [traccar/traccar#3990]
Hello,

I'm building traccar 3.7 with `mvn package` command and I'm getting "There are test failures" error. Then I omit test builds with `mvn package -DskipTests` command. I replaced the old "tracker-server.jar" file and "lib" folder with lastly generated and traccar is not starting. By the way I am using Windows Server. Where is the mistake that I did?

Thanks in advance.

**Comment by tananaev** [comment]
How did you get source code for version 3.7?

**Comment by ibrahimertok** [comment]
3.17. I'm sorry. 3.7 is written wrong.

**Comment by tananaev** [comment]
How did you get 3.17 source code?

**Comment by ibrahimertok** [comment]
From traccar repository. Your last version is 3.17 isn't it?

**Comment by ibrahimertok** [comment]
What the problem can be? Will you help me about what to do? My main purpose is to get .jar file which will be replaced.

**Comment by tananaev** [comment]
If you are taking sound code from master branch, then it's NOT 3.17. It's future version which obviously won't work if you leave all other files from 3.17.

**Comment by ibrahimertok** [comment]
Thank you very much for your response. Target folder is created when I build the source code with `mvn package -DskipTests`. How can I deploy this build to server? Where should I locate newly generated files?

Thanks in advance.

**Comment by tananaev** [comment]
They are in target folder. You need JAR file.

**Comment by ibrahimertok** [comment]
Where I'm gonna place this .jar file and lib folder? Currently installed 3.17 on my server. I installed it via setup from your download page. I build project (latest source code on your repository) and replace .jar file and lib folder. Then traccar doesn't start. What can be the problem? I will be grateful if you help. Thank you very much.

**Comment by tananaev** [comment]
It probably means that what you installed is not compatible with what you are building.

**Comment by ibrahimertok** [comment]
Thank you very much.
