### ISSUE TITLE
PostgreSQL changelog issue

### ISSUE THREAD

**Issue by tananaev** [traccar/traccar#3993]
Looks like upgrade doesn't work well on PostgreSQL:

https://www.traccar.org/forums/topic/versiya-40/page/2/#post-33622

@Abyss777, any ideas how to solve it?

**Comment by Abyss777** [comment]
Hm, looks like we should replace compares with `= 1` to `IS TRUE` or `= TRUE` for postgresql only. Because mysql and especially mssql will not understand them.

**Comment by Abyss777** [comment]
Or construction like `web::int = 1`

**Comment by Abyss777** [comment]
Also my be will work universal for `CAST(web AS integer) = 1` it will generate unnecessary cast for mysql and mssql, but necessary for postgresql.
I'l be able to check it at the end of the day.

**Comment by tananaev** [comment]
Can we just use `TRUE` and `FALSE`? It looks like MS SQL has them:

https://docs.microsoft.com/en-us/sql/t-sql/data-types/bit-transact-sql?view=sql-server-2017

**Comment by Abyss777** [comment]
I'm not sure about all mssql versions, but looks like yes it should works.
And in mysql it also should works https://dev.mysql.com/doc/refman/5.7/en/boolean-literals.html

But on the other hand, 1 and 0 also should work in postgresql https://www.postgresql.org/docs/9.1/static/datatype-boolean.html
`1` and `0` in literals list I do not understand why it is not.

**Comment by tananaev** [comment]
Yes, that's weird.

**Comment by Abyss777** [comment]
Might it be version depend? or some configuration flag?

**Comment by tananaev** [comment]
Maybe Liquibase uses column type that's not compatible without explicit cast.

**Comment by Abyss777** [comment]
OK. Variant `TRUE` and `FALSE` works with postresql and mysql.
Now I can't test it with MS SQL because I have 2008 R2 and it is incompatible with recent driver.

**Comment by tananaev** [comment]
Downgrade driver version locally. Probably the easiest option.

**Comment by Abyss777** [comment]
Looks like it does not work in MSSQL
`Недопустимое имя столбца "TRUE". [Failed SQL: UPDATE [dbo].[tc_notifications] SET [notificators] = 'web,mail,sms' WHERE web = TRUE AND mail = TRUE AND sms = TRUE]`

**Comment by tananaev** [comment]
What about `CAST`? Does it work on all database engines?

**Comment by Abyss777** [comment]
It is really hell...
`CAST(web AS INTEGER)` works in MS and PG, but not in MY
`CAST(web AS SIGNED INTEGER)` works in MY, but not in PG
`CAST(web AS TINYINT)` works in MY and MS, but not in PG

**Comment by tananaev** [comment]
Why doesn't first option work in MySQL? What's the error? Also, does it work in H2?

**Comment by tananaev** [comment]
Here is another issue somewhat related:

https://www.traccar.org/forums/topic/mssql-erorr-on-traccar-4/

**Comment by Abyss777** [comment]
Yes, I also noticed it when experimented with MS

**Comment by Abyss777** [comment]
>  What's the error? 

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INTEGER) = 1 AND CAST(mail AS INTEGER) = 1 AND CAST(sms AS INTEGER) = 1' at line 1 [Failed SQL: UPDATE traccar_test2.tc_notifications SET notificators = 'web,mail,sms' WHERE CAST(web AS INTEGER) = 1 AND CAST(mail AS INTEGER) = 1 AND CAST(sms AS INTEGER) = 1]`

**Comment by Abyss777** [comment]
I'm afraid we will not find any intersection in type names

**Comment by Abyss777** [comment]
I have a working solution (common for h2,my,ms and separate for pg)
How will we design it? separate changelog, will replace a 4.0 changelog?
