### ISSUE TITLE
Illegal character in query - causes device disconnect

### ISSUE THREAD

**Issue by stevebates** [traccar/traccar#3995]
Following an upgrade to Traccar Server 4.0 I am seeing all my devices disconnect immediately and not updating their locations. After reviewing the Traccar logs this appears to be in relataiton to the following values being set in configuration (after disabling it works as normal):

`<entry key="forward.enable">true</entry>`

`<entry key='forward.url'>https://[removed]/traccar/log_position/[removed]/[removed]?name={name}&amp;uniqueId={uniqueId}&amp;deviceId={deviceId}&amp;protocol={protocol}&amp;deviceTime={deviceTime}&amp;fixTime={fixTime}&amp;valid={valid}&amp;latitude={latitude}&amp;longitude={longitude}&amp;altitude={altitude}&amp;speed={speed}&amp;course={course}&amp;statusCode={statusCode}&amp;address={address}&amp;attributes={attributes}&amp;gprmc={gprmc}</entry>`

The error logged in the files is below however I'd prefer to send full logs via private message as they contain private information.

`error - java.net.URISyntaxException: Illegal character in query at index 91:`

On first inspection the HTTP field 'name' doesn't appear to be URL encoded as 'name=Mercedes C 180K' is an example from the log files. This also matches the index position.

**Comment by tananaev** [comment]
It tells you exactly where the problem is.

**Comment by stevebates** [comment]
Yes but the illegal character is from {name}, like I say the space. From my response you can tell I have been able to identify this but have no control over the field value as its set by the software.

The rest of the URL fields are URL encoded so I take it there is now no intentions from the short reply to URL encode {name} when it was working before upgrade?

For example:

`address=9+Park+Hill+Road%2C+Birmingham%2C+West+Midlands%2C+B17%2C+GB`

and 

`name=Mercedes C 180K`

**Comment by tananaev** [comment]
It was never encoded, but I'm happy to discuss it.

**Comment by stevebates** [comment]
OK well in that case if it was never encoded then I guess we can no longer use this field in forward.url due to code changes then? Prior to upgrade I was using this field assuming it was URL encoded and post upgrade the server now can not handle any forward.url values with this field present.

If set in a forward.url template string, I am seeing my server immediately disconnect the devices and no location information is logged. forward.url was not changed between upgrades and during this time a vehicle was able to leave its geofence, arrive home, park up for the night and then return to the city this morning with no location updates. Disabled this feature this morning and it instantly updated the position in Traccar server.

This behaviour was not seen before so assumed it was a bug however I guess I am wrong.

**Comment by tananaev** [comment]
There were no changes to the formatting. Maybe HTTP library change caused this.

**Comment by tananaev** [comment]
Added name encoding.
