### ISSUE TITLE
Reports always empty

### ISSUE THREAD

**Issue by BeepLoveKarki** [traccar/traccar#3997]
Traccar api for all reports like events, routes,trips provide me empty array whereas in dashboard I get perfect result. The reports are never null. Please help me.

**Comment by tananaev** [comment]
Compare your request with what web app sends.

**Comment by tananaev** [comment]
You need to send full ISO time format, including time with seconds and timezone. In future if something doesn't work, compare your request with request that web app sends. Any questions like this one should go on forum (not GitHub), and only after you have done research and compared requests.
