### ISSUE TITLE
Websocket connection from Swift client

### ISSUE THREAD

**Issue by ibrahimertok** [traccar/traccar#3998]
Hello Anton,

I am trying to connect `ws://my.domain.com:8082/api/socket` from native iOS app written in Swift. I am using Starscream library and when I try to connect the socket, I get `503` error because of authentication. However when I try to connect from browser, there is no problem because browser holds the cookie automatically. Your api accepts only session cookie so I can't add the cookie to request header. Is there a way to handle that issue?

Thanks and best regards.

**Comment by ibrahimertok** [comment]
I read API documentation and I saw two options for authentication. I added basic authentication header to the request and I managed to handle the issue.

**Comment by abdullahqureshi1994** [comment]
Can you please pinpoint the API documentation, I am also facing this issue.

Thanks and best regards.

**Comment by ibrahimertok** [comment]
Hello Abdullah,
I don’t remember it clearly but first you should get authentication cookie by POST request (session endpoint) and use that cookie to connect to web socket.

**Comment by msobhanasim** [comment]
> I read API documentation and I saw two options for authentication. I added basic authentication header to the request and I managed to handle the issue.

Hi Ibrahim. I am facing the same issue. I also tried your Solution, i.e. Adding an Authentication Header.. But it didn't helped... Can you give a code snippet that you used for your solution to the problem... It will be a great help. 
Thanks in Advance!!

Regards.

**Comment by ibrahimertok** [comment]
Unfortunately I can't. Because I don't have it. The source code is at the company that I used to work.
