### ISSUE TITLE
Trips report not working on 4.0

### ISSUE THREAD

**Issue by karls4** [traccar/traccar#3999]
When running a trips report it exports fine but once I open it and says there is a problem with some content in the report and if you try a recovery it doesn't work.

Thanks

**Comment by tananaev** [comment]
What are you opening it with?

**Comment by karls4** [comment]
Office 365 Excel

**Comment by karls4** [comment]
I can confirm that I was able to open it with Google Sheets fine. Downloaded it from sheets and was able to open it in Excel fine.

Thanks

**Comment by tananaev** [comment]
I guess there is some incompatibility. Not sure what can be done about it.

**Comment by karls4** [comment]
It was working fine before the 4.0 update.

**Comment by Abyss777** [comment]
It is possible, may be I used LibreOffice
Hm... templates themselves work fine in MS Office, but exported appears damaged...

**Comment by karls4** [comment]
I opened the template using Office365, saved it without any changes and replaced the file in the templates folder and that seems to have solved the problem.

Thanks
