### ISSUE TITLE
Upgrade to Traccar 4.0 and Microsoft SQL 2014

### ISSUE THREAD

**Issue by dlajusticia** [traccar/traccar#4000]
Hi,
We had running Traccar 3.16 with a SQL 2008 database, and we upgraded to SQL 2014 so we can use version 4.0. Since upgrading to 4.0 the service doesn't start and I think there's a problem when the service starts and tries to update the database (I think some table names changed in this version). I checked the wrapper log but I can't see what is the problem.

Heres our DB config lines in traccar.xml:
```xml
<entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
<entry key='database.url'>jdbc:sqlserver://server_ip;user=traccar_user;password=xxxxx;databaseName=traccar;</entry>
<entry key='database.user'>traccar_user</entry>
<entry key='database.password'>xxxxx</entry>
```
And our wrapper.log:

https://pastebin.com/iZaHePgD

Any hint of what its happening? Thanks in advance.

**Comment by tananaev** [comment]
Related discussion - #3993.
