### ISSUE TITLE
Not Read by traccar

### ISSUE THREAD

**Issue by devzonetrack** [traccar/traccar#4003]
who can describe what this protocol code, i can't find on concox product?
```
7979005BFD0358899051450552004C00045DAC86C8E549D10389E98F59A4303B3A5B56455253494F4E5D47543036445F32315F3630444D325F423235455F5632355F574D5B4255494C445D323031342F30352F30382031383A3131005004450D0A
```

**Comment by tananaev** [comment]
It's GT06 protocol, if that's what you asking.

**Comment by devzonetrack** [comment]
I thin protocol number FD?

7979 header
005B length packet
FD ?
0358899051450552 Imei

**Comment by tananaev** [comment]
I don't know what that message type mean. You would need to get documentation from your GPS device vendor.

**Comment by devzonetrack** [comment]
i have Communication Protocol（GT06N,GT06F,GT06E, but not available inside documentation
