### ISSUE TITLE
Server webpage is (almost) empty; illegal character warning

### ISSUE THREAD

**Issue by chaoscommander** [traccar/traccar#4006]
I installed the server as per the Linux instructions and set up a proxy with Apache2 to get https encryption. So far so good, but when I now go to the site (https://strikeslipvault.org/tracker) all I see is "Powered by Traccar GPS tracking system".

The wrapper log shows:

`FINEST|25304/0|Service traccar|18-08-12 07:30:21|[qtp299783910-35] WARN org.eclipse.jetty.http.HttpParser - Illegal character 0x16 in state=START for buffer HeapByteBuffer@15647f6a[p=1,l=200,c=16384,r=199]={\x16<<<\x03\x01\x00\xC3\x01\x00\x00\xBf\x03\x03\x87\xE4\xA8h~\xAc\xFc...\x04\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01\x02\x03\x02\x01>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
FINEST|25304/0|Service traccar|18-08-12 07:30:21|[qtp299783910-35] WARN org.eclipse.jetty.http.HttpParser - badMessage: 400 Illegal character 0x16 for HttpChannelOverHttp@19aa923c{r=0,c=false,a=IDLE,uri=}
`

Any help would be appreciated.

**Comment by tananaev** [comment]
Check browser console. You are missing crucial files. I'm not sure if it's proxy misconfiguration or an issue with your installation.

**Comment by chaoscommander** [comment]
Aha! It's this issue: https://www.traccar.org/forums/topic/reverse-proxy-apache-with-subdirectory/
Following the instructions in the thread, I got the interface up. Now if only osmand would actually send my position... But that's a problem for a different repo, I guess. :)
