### ISSUE TITLE
FrameDecoder Concox

### ISSUE THREAD

**Issue by devzonetrack** [traccar/traccar#4007]
Why create custom frameDecoder when netty provide DelimiterBasedFrameDecoder like below sample?
```
byte delimiter[] = {0x0D, 0x0A};                
ch.pipeline().addLast("frameDecoder", new DelimiterBasedFrameDecoder( 5 * 1024, Unpooled.wrappedBuffer(delimiter)));

```
mybe anyone can explain it?

**Comment by tananaev** [comment]
What protocol are you talking about?

**Comment by devzonetrack** [comment]
Concox like GT06

**Comment by tananaev** [comment]
It's a binary protocol, so obviously you can't use delimiter based frame decoder for it.

**Comment by devzonetrack** [comment]
But, i have try for more than 500 GT06 Device, and its working fine with DelimiterBasedFrameDecoder, so i am confused why you say can't use delimiter base on DelimiterBasedFrameDecoder

**Comment by tananaev** [comment]
Because `0D0A` sequence can randomly happen anywhere in the message.

**Comment by devzonetrack** [comment]
Thank u for your explanation.....
