### ISSUE TITLE
Feature Request: New Filter Option

### ISSUE THREAD

**Issue by CarlosBrazil** [traccar/traccar#4009]
I would like to request a new filter:   upload data to database when there is no movement, so upload every x minutes.     example:    If my car is parked,  so it will upload data to database every 120 minutes.   I would like to have a choice of this time to upload when the vehicle is parked.

**Comment by tananaev** [comment]
How is this related to the server?

**Comment by CarlosBrazil** [comment]
sorry, after I have posted it that I saw the wrong place.
