### ISSUE TITLE
Help with Teltronika FM1000 - Fuel Level

### ISSUE THREAD

**Issue by psavva** [traccar/traccar#4017]
I'm trying to get the fuel level from a Teltronika FM1000 module.
I've enabled all IO's and cannot see the fuel level being reported in traccar.

Is the fuel level implemented?
How can I check the Hex message to see if the data is there at all?

Any help is appreciated.

**Comment by tananaev** [comment]
It's not implemented, so you would need to convert raw IO into fuel using computed attributes.

**Comment by psavva** [comment]
@tananaev I have checked the implementation, and expect that any io received is actually stored in the tc_positions table in the attributes field.  Or do I read this incorrectly.

https://github.com/traccar/traccar/blob/5848419666fc6eb14c5b0178a9738f19f0be2b61/src/org/traccar/protocol/TeltonikaProtocolDecoder.java#L203

As per the Link: https://teltonika.lt/?media_dl=6266  (Excel from Teltonika with their ODB IO's)
The fuel level should have been saved as io48 at least in the parsed data.

I guess this only means that the ODB is not sending the fuel level (I thought it was configured to), or my vehicle is simply not broadcasting it...

If my understanding above is right, I should go ahead and close this request.

Any other advise how to get the Fuel Level values into attributes?

**Comment by tananaev** [comment]
Yes, if you don't see IO value, then your device is not sending it.
