### ISSUE TITLE
Custom parameters in EventForwarder are no longer possible

### ISSUE THREAD

**Issue by jpmens** [traccar/traccar#4018]
PR #3624 added support for custom parameters for the EventForwarder, and that worked very well using a configuration like this:

```xml
<entry key='event.forward.payloadAsParamMode'>true</entry>
<entry key='event.forward.paramMode.payloadParamName'>payload</entry>
<entry key='event.forward.paramMode.additionalParams'>
    beverage=Espresso
</entry>
```

I note that this no longer works in 4.0 (the JSON payload is in the request body) but I fail to find the spot in which the removal is documented. A `grep -ir` on the keywords  finds zero matches in the current source tree.

Has this gone away permanently or has it simply not yet been ported?

**Comment by tananaev** [comment]
See commit 5a9811c3771d92832c9bba718b5ec935844978e8. It was removed because network library was removed and it was too complicated to migrate it. Anyone welcome to re-implement it using new network library.
