### ISSUE TITLE
Installing Traccar with MySQL: SQL syntax errors preventing installation

### ISSUE THREAD

**Issue by jike212** [traccar/traccar#4024]
I'm creating a fresh install using the following:
Traccar-Docker (latest version)
MySQL Docker (8.0.12)

When creating the Traccar docker container, I get the SQL Syntax errors in the logs for the following command:

```
UPDATE trackdb.devices SET groupid = NULL WHERE groupid NOT IN (SELECT id FROM groups)
```

**Comment by tananaev** [comment]
Version before 8.x.
