### ISSUE TITLE
What Device Typr

### ISSUE THREAD

**Issue by devzonetrack** [traccar/traccar#4025]
What device type based on this data log? header 0x29 0x29
```
2929B10007322458630C970D
```

**Comment by tananaev** [comment]
Try KHD protocol

**Comment by devzonetrack** [comment]
OK,

I will try

**Comment by devzonetrack** [comment]
base on my hardware  AutoLeaders AL-900C

This wrong way read imei
```
  private String readSerialNumber(ByteBuf buf) {
        int b1 = buf.readUnsignedByte();
        int b2 = buf.readUnsignedByte() - 0x80;
        int b3 = buf.readUnsignedByte() - 0x80;
        int b4 = buf.readUnsignedByte();
        return String.format("%02d%02d%02d%02d", b1, b2, b3, b4);
    }

```
this right way read imei.
```
 private String readSerialNumber(ByteBuf buf) {
        return ByteBufUtil.hexDump(buf.readSlice(4));
}
```

**Comment by tananaev** [comment]
Please provide documentation that proves your point.

**Comment by devzonetrack** [comment]
[GPRS protocol 2012-1-30.pdf](https://github.com/traccar/traccar/files/2322921/GPRS.protocol.2012-1-30.pdf)

check attachment

**Comment by devzonetrack** [comment]
My Device has Imei: 359772032245863
Login Message
```
2018-08-27 13:27:33 DEBUG: [06d96785: 9012 < 182.1.70.126] HEX: 2929b10007322458630c970d
```
base on above message, we can devide into :
header Code : 2929 
msg code:b1
length data:0007
Imei: 32245863
Check:0c97
End Code:0d

**Comment by tananaev** [comment]
What do you get in Traccar as id?

**Comment by devzonetrack** [comment]
Imei:50-92-4099

**Comment by devzonetrack** [comment]
sorry i don't understand u mean....

```java
 private String readSerialNumber(ByteBuf buf) {
        int b1 = buf.readUnsignedByte();
        int b2 = buf.readUnsignedByte() - 0x80;
        int b3 = buf.readUnsignedByte() - 0x80;
        int b4 = buf.readUnsignedByte();
        return String.format("%02d%02d%02d%02d", b1, b2, b3, b4);
    }
```
above function with return "50-92-4099"

**Comment by tananaev** [comment]
That function returns nothing for the sample that you provided.

**Comment by caluca20** [comment]
> sorry i don't understand u mean....
> 
> ```java
>  private String readSerialNumber(ByteBuf buf) {
>         int b1 = buf.readUnsignedByte();
>         int b2 = buf.readUnsignedByte() - 0x80;
>         int b3 = buf.readUnsignedByte() - 0x80;
>         int b4 = buf.readUnsignedByte();
>         return String.format("%02d%02d%02d%02d", b1, b2, b3, b4);
>     }
> ```
> 
> based on this log 2929b10007322458630c970d, above function with return "50-92-4099"

> sorry i don't understand u mean....
> 
> ```java
>  private String readSerialNumber(ByteBuf buf) {
>         int b1 = buf.readUnsignedByte();
>         int b2 = buf.readUnsignedByte() - 0x80;
>         int b3 = buf.readUnsignedByte() - 0x80;
>         int b4 = buf.readUnsignedByte();
>         return String.format("%02d%02d%02d%02d", b1, b2, b3, b4);
>     }
> ```
> 
> based on this log 2929b10007322458630c970d, above function with return "50-92-4099"

Dear devzonetrack, I have the same problem in the server log the iD appear like 17-12-7938 I am using GPS AL-900 with KHD protocol, if you solve the problem please help me.
