### ISSUE TITLE
How to change source java web server and run traccar ?

### ISSUE THREAD

**Issue by mahdi00021** [traccar/traccar#4028]
How to change source java web server and run traccar ?
And how to change database to mysql?

**Comment by tananaev** [comment]
1. We use Jetty as a web server. I don't know why you would want to change it. You should probably explain your request in more details.

2. As for MySQL, read documentation on the official website.

**Comment by mahdi00021** [comment]
Thank for your answer

I want change source because I want that add multi feature to source java for example : when I click on icon on map show information of every driver or added other features

**Comment by mahdi00021** [comment]
@tananaev

**Comment by mahdi00021** [comment]
@tananaev please help
