### ISSUE TITLE
Is there any development of the front-end to change sencha ExtJS?

### ISSUE THREAD

**Issue by jhfaber** [traccar/traccar#4029]
Hi! i want to know if there is any development of the front-end to change sencha ExtJS, maybe to material or something like that, if thais is so, how many time do you take to update that changes.

Thanks!

**Comment by tananaev** [comment]
Please don't duplicate your questions:

https://www.traccar.org/forums/topic/is-there-any-development-of-the-front-end-to-change-sencha-extjs/
