### ISSUE TITLE
doesn't show list commands traccar

### ISSUE THREAD

**Issue by mahdi00021** [traccar/traccar#4031]
@tananaev

picture two 
![1](https://user-images.githubusercontent.com/9013165/44789909-171be580-abb3-11e8-8118-87b8ff44d6eb.jpg)
![2](https://user-images.githubusercontent.com/9013165/44789919-20a54d80-abb3-11e8-9ed3-175123f0048c.jpg)

**Comment by tananaev** [comment]
For questions like this you should use forum. GitHub is for development related issues.

**Comment by mahdi00021** [comment]
In forum don't become insert picture

**Comment by mahdi00021** [comment]
Please this place answer me very important for me

**Comment by tananaev** [comment]
You can upload images to any third party image hosting and reference them from forum.

**Comment by mahdi00021** [comment]
In forum don't answer me
I really very important is my work
Please you sey this place to me very very thsnks
