### ISSUE TITLE
[Feature Request] Display Units Customization

### ISSUE THREAD

**Issue by ac3bf1** [traccar/traccar#4032]
Dear Devs,

I found that this software works very well also for tracking our fleet of aircraft at our flying club in Rome, Italy.
It would be great to be able to customize the display of the units in order for us to use feet and knots.
Any roadmap for this feature?

Thanks
Jonathan

**Comment by tananaev** [comment]
You can already change units.

**Comment by tananaev** [comment]
In the modern app the units configuration is more discoverable.
