### ISSUE TITLE
No longer works (after update to 5.11)

### ISSUE THREAD

**Issue by luke-jr** [traccar/traccar#4039]
Device: Moto E LTE (surnia)
OS: LineageOS / Android 7.1.2

Affected phones seem to be using Traccar Client 5.11. Phones running Traccar Client 5.10 seem to still work.

Downgrading an affected phone to 5.10 caused Traccar to crash any time it's opened. Clearing data fixed that, and the phone is now working again. So this seems to be a regression in 5.11.

Curiously, the GPS/location icon (in the status bar) seems to never turn on with either version.

**Comment by tananaev** [comment]
What accuracy are you using? If you want to use GPS, make sure you switch it to high accuracy.

Also, in future please use Traccar Client repo if the issue is related to the app:

https://github.com/traccar/traccar-client-android

**Comment by luke-jr** [comment]
High accuracy. Oops, sorry, wrong repo. Shall I re-create it?

**Comment by tananaev** [comment]
That's fine. We can keep this issue here.

Just to clarify, I'm talking about accuracy configuration in the app, not Android settings.

**Comment by luke-jr** [comment]
Actually, I forgot to re-set the accuracy after clearing the data. It defaults to Medium.

So with 5.11, it NEVER shows the GPS indicator. With 5.10, it shows it only if I set High accuracy.

**Comment by luke-jr** [comment]
To clarify:

With 5.10:

* High accuracy shows GPS indicator in status bar.
* Reports work fine with either Medium or High accuracy.

With 5.11:

* Status bar NEVER shows GPS indicator, with any accuracy setting.
* Reports don't work at all (I guess I only tested High accuracy here).

**Comment by tananaev** [comment]
I don't see any changes that could break it:

https://github.com/traccar/traccar-client-android/compare/v5.10...v5.11

Maybe target API update to 28 changed some behaviour?

**Comment by luke-jr** [comment]
I don't know... any way to test? (I have root, so I can hack plain text files on the phone directly for testing?)

**Comment by tananaev** [comment]
I have checked and Android 7.1.2 is only API 25, so there should be no difference. Check app logs. Maybe there is some clue there.

**Comment by luke-jr** [comment]
The log was nearly silent, as if it wasn't even trying.

**Comment by luke-jr** [comment]
It had location permissions prior to the automatic upgrade, and still had it when it wasn't working. Disabling and re-enabling location permissions didn't help.

Status screen shows only "Network online" events.

**Comment by luke-jr** [comment]
It doesn't have a location fix, because Android thinks no apps want location services at that moment. If I run a GPS Test app, Android turns on the GPS - if I close it, it turns the GPS back off. (Even when it's on for GPS Test, Traccar Client still doesn't make logs...)

**Comment by tananaev** [comment]
Not sure what can be done. I guess only debugging the app on your particular phone would help. I have tested on 7.1 Android emulator and it works fine.

**Comment by luke-jr** [comment]
How can we do that?

**Comment by tananaev** [comment]
Remote debugging might work, but I'm not sure when I would have time for it.

**Comment by oliv3** [comment]
Not to mention that the phone looks rooted.

**Comment by luke-jr** [comment]
@oliv3 It's not at the moment, but why would you think that mattered?

**Comment by oliv3** [comment]
@luke-jr about your issue, when you mention "GPS indicator", you're talking about the Traccar notification icon, right ?

**Comment by oliv3** [comment]
@luke-jr about the phone being rooted, everything is possible in that case (adding some kind of malware -just an example-, or in your case messing with the location stack), that's why Google doesn't recognize those as "officially supported".

**Comment by luke-jr** [comment]
No, by GPS indicator, I mean in the top-right indicator area.

![](https://luke.dashjr.org/tmp/screenshots/Screenshot_20180903-014926.png)

**Comment by luke-jr** [comment]
Rebooted the phone I was using to test, and the notification appeared, but it also started working again... I think I'm out of phones that exhibit this problem. :/

Note: I have no reason to think it stopped working at a reboot specifically.
