### ISSUE TITLE
[OsmAnd] Handle "alarm" attribute

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar#4042]
Traccar client uses the OsmAnd protocol, and sends an "alarm" parameter when the SOS shortcut is used.
Any reason why this is not implemented in the decoder ?
It's done in other protocols, and should be easy to add.

**Comment by tananaev** [comment]
It's already handled.

**Comment by oliv3** [comment]
In the default branch of the switch..
Why does "batt" deserves it's own test then ?
It's never send by the OsmAnd application.

**Comment by tananaev** [comment]
It deserves separate case because we need number value for battery. For alarm we expect string value, so default case works just fine.
