### ISSUE TITLE
traccar web server

### ISSUE THREAD

**Issue by sbNoura** [traccar/traccar#4043]
Hi!i want ask about traccar code source working.
i want to understand its type project and whitch web server use for web application
i have build source code in netbeans 
thanks!

**Comment by tananaev** [comment]
Traccar includes embedded Jetty web server.

**Comment by sbNoura** [comment]
thanks for reply
what i want to know is how it works .
the backend application is it a service ??
how deploy the code source in server

**Comment by tananaev** [comment]
It's a service. Well, what you build from source code is just a regular Java application. We use YAJSW to run it as a service.

**Comment by sbNoura** [comment]
so if i wante to use the source code for creation my own application and deploy it in a server i have to use
YAJSW??

**Comment by tananaev** [comment]
You don't have to. You can use whatever you want. It's a standard java application. You can just run it directly:

https://www.traccar.org/manual-installation/
