### ISSUE TITLE
NullPointer Exception (PermissionManager:381 < *:389 < PermissionResource:67 < ...)

### ISSUE THREAD

**Issue by bernamaxim** [traccar/traccar#4050]
I got this error when check device for user from "Users" menu.
<img width="1028" alt="screen shot 2018-09-12 at 7 33 34 pm" src="https://user-images.githubusercontent.com/2969479/45425231-f085a080-b6c2-11e8-8809-633dce7b78f0.png">

And always got this error when access url.
<img width="1048" alt="screen shot 2018-09-12 at 7 38 31 pm" src="https://user-images.githubusercontent.com/2969479/45425517-cc768f00-b6c3-11e8-96c4-7d7053f8182c.png">

I have been using the latest Traccar version

**Comment by tananaev** [comment]
I suspect that your configuration is incorrect.

**Comment by bernamaxim** [comment]
Thanks @tananaev 
incorrect configuration on event.enable
