### ISSUE TITLE
Traccar Service stops every few days.

### ISSUE THREAD

**Issue by eangulus** [traccar/traccar#4055]
I have traccar server 4 installed on Ubuntu 18.04.

Runs great except for the fact that every 3 or 4 days the service stops and I have to manually start the traccar service manually. Once started it will run for another 3 to 4 days and stops again.

Can't see anything in the logs either that points at an issue.

**Comment by tananaev** [comment]
What do you see in the wrapper log at the time of stop?

**Comment by eangulus** [comment]
Haven't been able to pin point anything, as I don't really know when it stops. I only find out by going to access traccar and it's down, then I restart the service and access.

I only just restarted the service a few minutes ago, so when it stops again, I'll check the logs before I start the service and report back.

**Comment by eangulus** [comment]
The server stopped again. Here are the logs.

`2018-09-17 19:01:56 DEBUG: [08fd78fd: 5030 < 1.144.105.103] HEX: 23383636343235303330303738343635234d543535302330303030234155544f4c4f5723310d0a23244750524d432c3039303135362e30302c412c333231352e363639392c532c31343833372e343931342c452c302e32372c2c3137303931382c2c2c412a35310d0a23230d0a
2018-09-17 19:01:56  INFO: [08fd78fd] id: 866425030078465, time: 2018-09-17 19:01:56, lat: -32.26117, lon: 148.62486, speed: 0.3, course: 0.0
2018-09-17 19:11:55  INFO: Shutting down server...
2018-09-17 19:11:55  INFO: [fef6f9b5] disconnected
2018-09-17 19:11:55  INFO: [a37c8552] disconnected
2018-09-17 19:11:55  INFO: [f4d5a8dc] disconnected`

**Comment by tananaev** [comment]
Unfortunately I won't be able to help if you completely ignore my comments.

**Comment by eangulus** [comment]
I don't understand. What comments?

**Comment by tananaev** [comment]
I asked for wrapper logs. That's not what you provided.

**Comment by eangulus** [comment]
Where are the wrapper logs?

**Comment by eangulus** [comment]
I found them. Hang on getting those.

**Comment by tananaev** [comment]
Are you serious? It's in the same place and called "wrapper.log.XXX".

**Comment by eangulus** [comment]
For your information, I only see about 10 files at once in the logs directory and all say logs until I explicitly go to the end. So unless I knew I am looking for something my only interest is the top file for the latest logs.

So my apologies for not knowing that there were wrapper logs and where they were.

Here is the last wrapper log:

[http://krc.direct/wrapper.log.20180917](http://krc.direct/wrapper.log.20180917)

**Comment by tananaev** [comment]
I explicitly asked for wrapper logs. If you don't know what that is or where to find them, you could have asked.

Here is the error:
```
...
INFO|852/0|Service traccar|18-09-17 19:10:55|Missing wrapper ping within timeout of 30000
FINEST|852/0|Service traccar|18-09-17 19:11:54|[HikariPool-1 housekeeper] WARN com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m28s277ms617Âµs285ns).
WARNING|852/0|Service traccar|18-09-17 19:11:54|ping between java application and wrapper timed out. if this this is due to server overload consider increasing wrapper.ping.timeout
INFO|852/0|Service traccar|18-09-17 19:11:55|wrapper manager received stop command
FINEST|852/0|Service traccar|18-09-17 19:11:55|[Thread-11] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@5a583720{HTTP/1.1}{0.0.0.0:8082}
FINEST|852/0|Service traccar|18-09-17 19:11:55|[Thread-11] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.t.w.@1dcca426{/,null,UNAVAILABLE}
FINEST|852/0|Service traccar|18-09-17 19:11:55|[Thread-11] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@8ef1d58{/api,null,UNAVAILABLE}
INFO|wrapper|Service traccar|18-09-17 19:11:56|waitpid 852 0
INFO|wrapper|Service traccar|18-09-17 19:11:56|exit code posix process: 0 application(status/signal): 0/0
```

Timeout usually means that you don't have enough resources on your server.

**Comment by eangulus** [comment]
Runs as a VM on a Dual CPU E5640 configured with:

Dual Core and 4GB RAM.

Should I be upping the CPU cores?

**Comment by eangulus** [comment]
OK, read thru that.

Seeing that at this stage I have only 1 GPS traccar connecting, I increased the java max memory and also set the TCP and UDP timeouts.

And cause I have the resources, I upped the CPU to 4 Cores 1 socket.

I'll know in about a week if it still happens, I report back next week.

**Comment by tananaev** [comment]
If you get this problem with a single device, it's probably not a memory issue. Try using Java 8, if you are not using it already.

**Comment by eangulus** [comment]
Stopped again.

Same Error.

`INFO|9889/0|Service traccar|18-09-23 19:11:25|Missing wrapper ping within timeout of 30000
WARNING|9889/0|Service traccar|18-09-23 19:11:25|ping between java application and wrapper timed out. if this this is due to server overload consider increasing wrapper.ping.timeout
FINEST|9889/0|Service traccar|18-09-23 19:11:25|[HikariPool-1 housekeeper] WARN com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m33s392ms731??s556ns).
INFO|9889/0|Service traccar|18-09-23 19:11:26|wrapper manager received stop command
FINEST|9889/0|Service traccar|18-09-23 19:11:26|[Thread-11] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@ab92553{HTTP/1.1}{0.0.0.0:8082}
FINEST|9889/0|Service traccar|18-09-23 19:11:26|[Thread-11] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.t.w.@b339a08{/,null,UNAVAILABLE}
FINEST|9889/0|Service traccar|18-09-23 19:11:26|[Thread-11] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@5d297d4d{/api,null,UNAVAILABLE}`

**Comment by eangulus** [comment]
Checked my Java version and it was using 10.

Installing 8 now and setting that and will give it another go.

**Comment by eangulus** [comment]
Still stopping. Now running Java 8 and it is still crashing.

Logs:

`INFO|603/0|Service traccar|18-09-25 10:44:48|[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.t.w.@35d26ad2{/,null,AVAILABLE}
INFO|603/0|Service traccar|18-09-25 10:44:48|[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@40c06358{HTTP/1.1}{0.0.0.0:8082}
INFO|603/0|Service traccar|18-09-25 10:44:48|[main] INFO org.eclipse.jetty.server.Server - Started @7698ms
INFO|603/0|Service traccar|18-09-25 17:36:16|[qtp1896708863-44] WARN org.eclipse.jetty.http.HttpParser - Illegal character 0x3 in state=START for buffer HeapByteBuffer@3f535b95[p=1,l=47,c=16384,r=46]={\x03<<<\x00\x00/*\xE0\x00\x00\x00\x00\x00Cookie:...nistr\r\n\x01\x00\x08\x00\x03\x00\x00\x00>>>d=4&type=allEvent...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
INFO|603/0|Service traccar|18-09-25 17:36:16|[qtp1896708863-44] WARN org.eclipse.jetty.http.HttpParser - badMessage: 400 Illegal character 0x3 for HttpChannelOverHttp@6b09554f{r=0,c=false,a=IDLE,uri=}
INFO|603/0|Service traccar|18-09-26 13:20:12|[qtp1896708863-44] WARN org.eclipse.jetty.http.HttpParser - Illegal character 0x5 in state=START for buffer HeapByteBuffer@70037e45[p=1,l=3,c=16384,r=2]={\x05<<<\x01\x00>>> /api/reports/rou...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
INFO|603/0|Service traccar|18-09-26 13:20:12|[qtp1896708863-44] WARN org.eclipse.jetty.http.HttpParser - badMessage: 400 Illegal character 0x5 for HttpChannelOverHttp@56c74e50{r=0,c=false,a=IDLE,uri=}
INFO|603/0|Service traccar|18-09-26 13:21:00|[qtp1896708863-38] WARN org.eclipse.jetty.http.HttpParser - Illegal character 0x4 in state=START for buffer HeapByteBuffer@70037e45[p=1,l=9,c=16384,r=8]={\x04<<<\x01\x00P\x05\xBc\xD2\x0c\x00>>>reports/route?_dc...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
INFO|603/0|Service traccar|18-09-26 13:21:00|[qtp1896708863-38] WARN org.eclipse.jetty.http.HttpParser - badMessage: 400 Illegal character 0x4 for HttpChannelOverHttp@2d072f68{r=0,c=false,a=IDLE,uri=}
INFO|603/0|Service traccar|18-09-27 02:02:14|Missing wrapper ping within timeout of 30000
WARNING|603/0|Service traccar|18-09-27 02:02:51|ping between java application and wrapper timed out. if this this is due to server overload consider increasing wrapper.ping.timeout
INFO|603/0|Service traccar|18-09-27 02:02:52|wrapper manager received stop command
INFO|603/0|Service traccar|18-09-27 02:02:52|[Thread-12] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@40c06358{HTTP/1.1}{0.0.0.0:8082}
INFO|603/0|Service traccar|18-09-27 02:02:52|[Thread-12] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.t.w.@35d26ad2{/,null,UNAVAILABLE}
INFO|603/0|Service traccar|18-09-27 02:02:52|[Thread-12] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@1c8f6c66{/api,null,UNAVAILABLE}`

**Comment by tananaev** [comment]
Try to run it manually (java command directly) and see if there are any issues.

**Comment by eangulus** [comment]
I don't understand? How do I do that?

**Comment by tananaev** [comment]
Check this:

https://www.traccar.org/manual-installation/

**Comment by eangulus** [comment]
Not sure how this helps?

Traccar does run. It just stops running after a few days and I have to restart it.

Is this to see if its an issue with the service itself?

**Comment by eangulus** [comment]
Spoke too soon. crashed again today. Couldn't get the text copied so I screenshotted the VM console.

[https://drive.google.com/file/d/15dYXaRENW9AAFJYhmjui1O3bcVMkS0MS/view?usp=sharing](url)

**Comment by tananaev** [comment]
Looks like your problem is with IO, not memory.

**Comment by tananaev** [comment]
I don't know how it happened either. Possibly there is some issue with JVM or just some OS issue.

**Comment by eangulus** [comment]
Can't be jvm. Tried 2 different versions.

And 3.17 works fine, but not 4.0.

**Comment by tananaev** [comment]
Netty 4 was a big change in Traccar 4.0, but I don't think it could cause an issue like this. Everything else should work pretty much the same way as older versions.

**Comment by eangulus** [comment]
So my only solution is to roll back to 3.17 then?

**Comment by tananaev** [comment]
I guess so, but I suspect you will have the same issue. You can try.

**Comment by eangulus** [comment]
I have already stated that 3.17 works fine.

I have rebuilt this server over and over again using different versions of Traccar.

Again, 3.17 works 100% fine. It doesn't have this crashing issue. Only 4.0 does.
