### ISSUE TITLE
Entity not getting recognised in POST request.

### ISSUE THREAD

**Issue by alperc92** [traccar/traccar#4061]
I am calling the POST method as such:

http://localhost:8082/api/devices/?id=0001&name=test-sting1&uniqueId=test-sting1&status=test&disabled=false&lastUpdate=2018-08-20T11:00:00Z&positionId=1&groupId=1&model=Sting&contact=OPM&category=humidity

Debugging the BaseObjectResource, the method @POST Response add(T entity) gets called.
Inside this method, it understands this as the Device.java Model that will be persisted, however the object T entity obtained from the argument parameter is Null, so I get a NullPointerException. Why is that?

**Comment by tananaev** [comment]
I would recommend you to start with reading about POST. Then read about REST API. Then about Traccar REST API. And then look at what official web app sends.
