### ISSUE TITLE
UnsupportedTemporalTypeException

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar#4063]
Hi,

This one happened on a fresh 4.0 install. Never saw that, so I'm kind of stumped right now, any idea ?
Nothing in the logs, just a popup in the interface:

```
Unsupported field: Year - UnsupportedTemporalTypeException (... < StatisticsManager:75 < *:106 < SecurityRequestFilter:92 < ...)
```

**Comment by oliv3** [comment]
Wouldn't know how to reproduce, either.
It happened when I went back to a browser tab running a (possibly old) session.
Reloaded the tab, worked again. Weird.

**Comment by tananaev** [comment]
Fix the issue. Thanks for reporting it.

**Comment by oliv3** [comment]
That was fast ! Great !
If you could telll more about the problem I'd be glad to learn more, thanks !

**Comment by tananaev** [comment]
We removed Joda time library and use Java 8 standard API. Looks like it doesn't want to format the date without timezone. I added default timezone to the formatter.

**Comment by oliv3** [comment]
Thank you for this explanation.
