### ISSUE TITLE
new user can not login to traccar

### ISSUE THREAD

**Issue by meneva** [traccar/traccar#4068]
hello,
I have created new user via my php script to traccar database. using the following snippet:
```php
$name = "testme2";
$email = "testme2@test.com";
$password = "123456";

$string = mcrypt_create_iv(24, MCRYPT_DEV_URANDOM);
$salt = strtoupper(bin2hex($string));
$salt = bin2hex($string);

$hash = hash_pbkdf2("sha1", $password, $string, 1000, 24, true);
$hash = strtoupper(bin2hex($hash));
$hash = bin2hex($hash);

//finally execute the following query:

$sql_insert = "INSERT INTO users (name, email, hashedpassword, salt, readonly, admin, map,latitude, longitude, zoom) VALUES ('$name', '$email', '$hash', '$salt', 0, 0, 'osm', 0, 0, 0)";
$result = mysqli_query($con,$sql_insert);
```

but while i am trying to login it just shows me error: permissionmanager:249 
can u pls suggest me regarding this matter?
thanks in advance
MEHOSSAIN

**Comment by meneva** [comment]
yes... it works after restart the server manually. But is there any other way to tackle this issue? The new user can register any time and we should not restart the server only for this purpose. it is not so standard.

**Comment by tananaev** [comment]
The right way is to use API.

**Comment by meneva** [comment]
thanks for your advice. One more query.... I added an additional filed into users table and trying to insert record via API. now it can not recognize my new field and throws unrecognized error. I restarted the traccar but no luck.

**Comment by tananaev** [comment]
Just look at how existing fields are implemented and do the same thing. If it doesn't work, you are clearly missing something, but from your description there is no way to know what it is.
