### ISSUE TITLE
Log files filling up disk

### ISSUE THREAD

**Issue by hallmark9** [traccar/traccar#407]
Looks like log files are rotated daily and a new log is created every day but the problem is, old log files are not automatically removed. As a result, the logs are filling up the disk quickly.

How can I disable the log rotation by traccar so as to use the Linux logrotate instead?

**Comment by jzahraoui** [comment]
I found a way to do it for the wrapper.log :
wrapper.logfile=/var/log/traccar/wrapper.log
#wrapper.logfile=/var/log/traccar/wrapper.log.YYYYMMDD
#wrapper.logfile.rollmode=DATE

but I'm still looking for doing it to the tracker-server.log file.

any help will be appreciated :)
