### ISSUE TITLE
Error geocoding on traccar master

### ISSUE THREAD

**Issue by gpproton** [traccar/traccar#4073]
Hi Anton,

I clone directly from the traccar but every time i try receive a new position i get this error on the web interface and the other below on the log.

1.
```
com.fasterxml.jackson.databind.JsonMappingException: Can not find a deserializer for non-concrete Map type [map type; class javax.json.JsonObject, [simple type, class java.lang.String] -> [simple type, class javax.json.JsonValue]]
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@7e40ca14; line: 1, column: 1] - ResponseProcessingException (... < JsonGeocoder:106 < ServerResource:57 < ...)
 ```
 2.
```
2018-09-30 00:57:21  INFO: [f607efde: 5026 < 127.0.0.1] HEX: 244652434d442c3132333435362c5f53656e644d6573736167652c2c303635312e30393730382c4e2c303333362e31313139322c452c302e302c33302e32342c35362e302c3239303931382c3233353831382e3030302c312a36370d0a
2018-09-30 00:57:23  WARN: Geocoding failed - Error reading entity from input stream. - ProcessingException (...)
2018-09-30 00:57:23  INFO: [f607efde] id: 123456, time: 2018-09-30 00:58:18, lat: 6.85162, lon: 3.60187, speed: 30.2, course: 56.0
```

**Comment by tananaev** [comment]
Have you updated all dependencies?

**Comment by gpproton** [comment]
This is a fresh clone, no mod

**Comment by tananaev** [comment]
OK, but how did you deploy it? Please provide details of what you did exactly.

**Comment by gpproton** [comment]
Just running directly with java -jar tracker-server.jar conf/traccar.xml

**Comment by gpproton** [comment]
I tried with 4.0 release it works perfectly but not with the new build.

**Comment by tananaev** [comment]
Well, you need to build JAR file first, right? Where did you get `conf/traccar.xml`? Repository doesn't even have `conf` folder.

**Comment by tananaev** [comment]
OK, if that's all you did, where did you get `conf` folder from?

**Comment by gpproton** [comment]
default.xml and traccar.xml were from the setup folder and i added more configuration to traccar.xml

**Comment by tananaev** [comment]
I don't know why you are refusing to provide full information.

**Comment by gpproton** [comment]
Really sorry, but i created new logs folder, copied schema folder from project root, configuration from setup, with tracker-server.jar and all lib already compiled and i'm currently running it on a windows 10 OS

**Comment by gpproton** [comment]
Thats all i'm not sure why the gives this error but i've always done this from every new release or build from traccar master.

**Comment by tananaev** [comment]
I think you are missing some libraries. It works for me on Mac.

**Comment by gpproton** [comment]
Ok i'll try on my ubuntu partition and revert back

**Comment by oliv3** [comment]
I have exactly the same issue with BAN geocoder on a build I did yesterday. 
It wasn't showing up when I pushed it.
Rebased my branch since.
Hope this can shred the window. 
Also hope it's not related to the new package.sh

**Comment by oliv3** [comment]
If it is, well I messed up.

**Comment by tananaev** [comment]
I have found and fixed the problem. Looks like behaviour of one of the libraries has changed.
