### ISSUE TITLE
Protocol for TOPFLYTECH T8803

### ISSUE THREAD

**Issue by sebalin-n** [traccar/traccar#4080]
I work with the Topflytech T8803 because on the documentation of traccar mentions that they have support for the topflytech protocol but when I wish send a command doesn't appear any command only the customs commands are available, I need help  :(

**Comment by sebalin-n** [comment]
What would the custom command be to stop the engine?

**Comment by tananaev** [comment]
Your device vendor should be able to answer that question.

**Comment by sebalin-n** [comment]
Oki doki, and another question, the notification on traccar (web) when the SOS is enabled also don't supported for this device (T8803)?

**Comment by tananaev** [comment]
As far as I can tell, alarms are not supported at the moment for this particular protocol. Assuming that you are talking about **Topflytech** protocol in Traccar.

**Comment by sebalin-n** [comment]
Thanks :+1:
