### ISSUE TITLE
Installer ends with a getcwd() error

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar#4085]
Please do not close unconfirmed issue. (#4082)

**Comment by tananaev** [comment]
You can reopen the issue. Please don't create a new issues.

**Comment by oliv3** [comment]
@tananaev Well, strangely I could not. There was no option to reopen, or I missed some obvious button ?

**Comment by tananaev** [comment]
I can definitely re-open them. Maybe you can't because I closed them. Either way, you can just put a comment that it still doesn't work and I'll re-open.

**Comment by oliv3** [comment]
Then please do.

**Comment by tananaev** [comment]
Is it still broken? Make a comment on appropriate thread and I'll re-open.
