### ISSUE TITLE
Enabling logger results in a crash

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar#4086]
Please do not close issue with a _potential_ fix until confirmed. (#4083)

**Comment by tananaev** [comment]
You can reopen the issue. Please don't create a new issues.

**Comment by oliv3** [comment]
Same for this one, no way to reopen.

**Comment by oliv3** [comment]
@tananaev Please reopen, this one is still not fixed.

**Comment by tananaev** [comment]
Please comment on original threads.
