### ISSUE TITLE
Moving /data & /conf to different server causes Warning missing tables from H2 database errors

### ISSUE THREAD

**Issue by Youselr1** [traccar/traccar#4088]
I am getting all sorts of errors when trying to log into any user account from the original /data and /conf that i moved over to a new server. It keeps throwing errors in logs that table 'USERS' not found and table 'DEVICES' not found...etc.

I thought when backing up and moving to a new server only requires backing up /data and /conf.  Why am i getting these errors?

Please help!

Linux ubuntu 18.04
traccar server 4.0

**Comment by tananaev** [comment]
Sounds like you haven't done it properly.

**Comment by Youselr1** [comment]
@tananaev can you tell me what more i need to do to backup and restore the database and settings?

The old server had Traccar 3.17
The new server Traccar 4.0

I stopped Traccar server then just copied /data & /conf from the one server over to the new server.

Can you advise why im getting missing database tables if i made an exact copy over?

**Comment by Youselr1** [comment]
Maybe H2 database is not that reliable?

**Comment by tananaev** [comment]
H2 is definitely not reliable. Also, I don't understand why you copied full `conf` folder. That's definitely a bad idea.

**Comment by Youselr1** [comment]
@tananaev so what do you suggest then? Should i first migrate old database to mySQL and then move that over?

i thought conf folder had all the settings for the server, but i take it all settings are embedded in H2 database?

**Comment by tananaev** [comment]
I would definitely recommend to migrate to some other proper database.

As for configuration, it changes with every release. You can't just blindly copy and overwrite files.

**Comment by Youselr1** [comment]
@tananaev thanks i solved the problem by re-installing and only replacing the /data folder.
