### ISSUE TITLE
Error when clicking on "show address" NullPointerException (ServerResource:56 < ...)

### ISSUE THREAD

**Issue by ROnt2** [traccar/traccar#4096]
This is a fresh installation on Ubuntu 18.04 linux server 4.0, update came through on device, DB is default H2.
- Added device
- When update came through for device, i click on Show Address and it throws that error.

Invalid paramters or contraints violation
NullPointerException (ServerResource:56 < ...)

Traccar logs show nothing but normal device updates.

Is this a bug or am i missing some kind of dependency maybe?

**Comment by ROnt2** [comment]
I found this: https://www.traccar.org/forums/topic/nullpointerexception-serverresource56-less2/

By the way this same error happens on any firefox browser AND on the Traccar Manager app

All latest versions

**Comment by ROnt2** [comment]
Reading a bit further i discovered that i need to get an API key for a reverse geocoding so that "Show Address" works.
@tananaev Can i ask why this used to work on previous default traccar installations? did something change? and why is there no announcement somewhere of this?

**Comment by tananaev** [comment]
Yes, reverse geocoding has been disabled by default because Google no longer works without API key.
