### ISSUE TITLE
[feature]what 3 words address

### ISSUE THREAD

**Issue by icf20** [traccar/traccar#4102]
i let this videos here so you get the idea

https://www.youtube.com/watch?v=a4ZBzM3L6ws

https://www.youtube.com/watch?v=Fus75eaLK5A

is there any interest in having an `what 3 words ` next to show address ?

api: https://docs.what3words.com/api/v2/

**Comment by tananaev** [comment]
I've heard about it and I don't really like that it's a proprietary solution. Also, I don't think it's popular enough to be considered at this point.

**Comment by whatnick** [comment]
This is an open/free equivalent technology from Google - https://plus.codes/ . Less memorable than words, but similar advantages apply.

**Comment by icf20** [comment]
i dont see exactly how is exactly proprietary since are just words, one could get the list and rehost it and would totally be OK

**Comment by tananaev** [comment]
How do you get the list/database?

**Comment by icf20** [comment]
that is quite a task since you need to use a api https://what3words.com/developers/ to get access to their database and there is no way to get the whole thing, as far i understand you can save and copy everything you get from the api

**Comment by tananaev** [comment]
If you crunch the numbers, it's an impossible task. That's why it's proprietary solution. There is no database. There is a formula that they don't disclose.
