### ISSUE TITLE
TK110 GPRS tracking problem

### ISSUE THREAD

**Issue by hako2008** [traccar/traccar#4103]
hello team,
we bought the TK110 while doing the tests.
the problem is when we activate the GPRS mode and change the server, we receiving a unclear messages, otherwise it's sending the information correctly to gprs110.org (their original web server tracker).
you can check the attached photos, and it's compared with your app that clearly posting a HTTP variables
best regards.

![tk110](https://user-images.githubusercontent.com/16450992/46920998-efab9b80-cfed-11e8-9750-d7eceea41739.png)
![tk2007921744](https://user-images.githubusercontent.com/16450992/46920999-f0443200-cfed-11e8-83df-8d48b874e103.png)
![2](https://user-images.githubusercontent.com/16450992/46921000-f0dcc880-cfed-11e8-8b49-5fc4b1094839.png)
![adminip ok](https://user-images.githubusercontent.com/16450992/46921001-f0dcc880-cfed-11e8-87c0-a8ac4cf6a477.png)
![check](https://user-images.githubusercontent.com/16450992/46921002-f1755f00-cfed-11e8-8195-cab2bd920a7d.png)
![gprs ok](https://user-images.githubusercontent.com/16450992/46921003-f2a68c00-cfed-11e8-894f-93e289aa0d00.png)

**Comment by tananaev** [comment]
Sorry, but how is this related to Traccar server project?

**Comment by hako2008** [comment]
it's clearly didn't worked with the traccar server , this is why i made the TCP/IP server to detect the problem, so i asked here if you have already faced this, i'm looking for solution to make it worked with traccar server.
i'm sorry it's my bad :).

**Comment by tananaev** [comment]
If it didn't work with Traccar, you should start by following troubleshooting guide from Traccar website. If it doesn't help, provide HEX samples from Traccar log and protocol documentation for your device.
