### ISSUE TITLE
[Feature Request] Adding support for Megastek MT80 GPRS Commands

### ISSUE THREAD

**Issue by DevOps2050** [traccar/traccar#4104]
Hi,

Is there a plan to add support for Megastek MT80 GPRS Commands?

Regards,

**Comment by tananaev** [comment]
What commands are you interested in? Do you have documentation?

**Comment by DevOps2050** [comment]
Thanks for your quick reply.

http://www.megastek.com/en/download/mt80-command-list-pdf/ for commands list documentation.

**Comment by tananaev** [comment]
Documentation link is not working.
