### ISSUE TITLE
I want step by step process install traccar and use of mysql and php?

### ISSUE THREAD

**Issue by sujatahmad** [traccar/traccar#4105]
Hi All,
 I am new for traccar, Please let me know step by step process of Install and use of traccar in Php Mysql with gt06n Dvice and i want mysql database for my custom web application. 

Thanks in advance. 

 Regards,
 Sujat

**Comment by tananaev** [comment]
For questions like your one, there is forum:

https://www.traccar.org/forums/

Also, please read available documentation first before asking questions there.
