### ISSUE TITLE
[Feature Request] Importing GPX file as Polyline Geofence

### ISSUE THREAD

**Issue by captain-paranoia** [traccar/traccar#4106]
The GPX file format is almost universally accepted by both GPS devices and mapping tools. It is used to define routes to be exchanged.

Traccar's Polyline Geofence, with configurable distance alert, is a great way to detect if a device is going off-route.

Whilst the Polyline can be defined within the Traccar UI, it would be great if a GPX route could be imported as a Polyline, allowing convenient exchange with other mapping tools.

**Comment by tananaev** [comment]
This is already supported.
