### ISSUE TITLE
Email notification limits (submission rate exceeded)

### ISSUE THREAD

**Issue by charliewillemson** [traccar/traccar#4109]
Hi, 

I would like to know does traccar server limits somehow outgoing emails or it is more about e-mail account itself?

For example if i have 10+ devices entering to the same geofence at the same time?  Does server could handle many outgoing notification emails at the same time? It is complicated to test it because i do not have many devices at the moment but i just like to know limitations to be more futureproof.

I tried to make very basic test pressing "test email" button for many times row but at the some point server gives _Error: "Message submission rate for this client has exceeded the configured limit - SMTPSendFailedException"_.

**Comment by tananaev** [comment]
There are no limits in Traccar. It must be your SMTP service issue.

**Comment by charliewillemson** [comment]
Thank you! Good to know.
