### ISSUE TITLE
issue with latitude & longitude format

### ISSUE THREAD

**Issue by krishnakulkarni88** [traccar/traccar#4110]
hii,
i am using quectel mc60 board to send the gps data to traccar.My board can obtain the data in DMM format only.but your traccar  uses DD format,how can you support for this type of boards not having your format.I have tried converting DMM to DD but it would not happen in my board.so add a format for your application which can accept DMM.

**Comment by tananaev** [comment]
What protocol are you talking about?

**Comment by krishnakulkarni88** [comment]
osmand,but that problem is solved and raised with another problem.I am sending utc time like timestamp=2018-10-17%2018:55:47   but iam not able to receive the correct date and time.for date it is incrementing by one day.and if my sending of time stamp is false can you say me the format of how to send the time stamp.many thanks for your reply.

**Comment by tananaev** [comment]
You can use OpenGTS protocol:

[OpenGtsProtocolDecoderTest examples](https://github.com/traccar/traccar/blob/master/test/org/traccar/protocol/OpenGtsProtocolDecoderTest.java)

**Comment by krishnakulkarni88** [comment]
> You can use OpenGTS protocol:
> 
> [OpenGtsProtocolDecoderTest examples](https://github.com/traccar/traccar/blob/master/test/org/traccar/protocol/OpenGtsProtocolDecoderTest.java)

thanks a lot ...  I need one solution,i am hitting the server from my device but it is not updating the data on my web app.if i hit the server from a browser it is updating the data.can you suggest a solution for it.many thanks for your replies.

**Comment by tananaev** [comment]
It probably means that there is some difference in what you are sending.
