### ISSUE TITLE
traccar 4.1 stoped interpret href in device contact field

### ISSUE THREAD

**Issue by lukazi** [traccar/traccar#4112]
I used the contact field for href to live video stream from vehicles ip camera. It was interpreted like url in version 4.0. After upgrade to 4.1 raw text <a href .... in the contact field...  Could You help me to have correct urls also in 4.1 or ideally how to add custom field "camera" with url inside please? 

href sample
```html
<a href="#" target="popup" onclick="window.open('http://ec2-18-195-101-182.eu-central-1.compute.amazonaws.com:8081/bitmovin2.html?var1=pd178','popup','width=640,height=360,menubar=0,scrollbars=0,location=0,toolbar=0,titlebar=0'); return false;">Cam</a>
```

**Comment by tananaev** [comment]
It's no longer supported because it's a potential XSS security issue. You need to modify the code if you want to add some JavaScript.
