### ISSUE TITLE
Previous traccar.xml conf not working after migrating 4.0 to 4.1

### ISSUE THREAD

**Issue by JuanIrache** [traccar/traccar#4115]
Hi,

I just upgraded to 4.1. Uninstalled 4.0, installed 4.1 and after replacing conf/traccar.xml with my old one traccar does not start

> ● traccar.service - traccar
>    Loaded: loaded (/etc/systemd/system/traccar.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Sun 2018-10-21 15:48:36 EDT; 2s ago
>   Process: 3473 ExecStart=/opt/traccar/jre/bin/java -jar tracker-server.jar conf/traccar.xml (code=exited, status=1/FAILURE)
>  Main PID: 3473 (code=exited, status=1/FAILURE)

If I keep the default traccar.xml pointing to the h2 database it all goes well.

Edit: I'm pointing to a MySQL database

**Comment by JuanIrache** [comment]
Yes. Nothing gets written to logs when I start Traccar with my own conf.

These are the last lines written when I use the default conf

> 2018-10-22 05:14:37  INFO: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOG
> 2018-10-22 05:14:37  INFO: Reading from PUBLIC.DATABASECHANGELOG
> 2018-10-22 05:14:37  INFO: SELECT * FROM PUBLIC.DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
> 2018-10-22 05:14:37  INFO: Successfully released change log lock
> 2018-10-22 05:14:37  INFO: Logging initialized @8966ms to org.eclipse.jetty.util.log.Slf4jLog
> 2018-10-22 05:14:39  INFO: Operating system name: Linux version: 4.4.0-122-generic architecture: amd64
> 2018-10-22 05:14:39  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 10.0.2-ojdkbuild+13
> 2018-10-22 05:14:39  INFO: Memory limit heap: 121mb non-heap: 0mb
> 2018-10-22 05:14:39  INFO: Character encoding: UTF-8 charset: UTF-8
> 2018-10-22 05:14:39  INFO: Version: 4.1-SNAPSHOT
> 2018-10-22 05:14:39  INFO: Starting server...
> 2018-10-22 05:14:40  INFO: jetty-9.4.12.v20180830; built: 2018-08-30T13:59:14.071Z; git: 27208684755d94a92186989f695db2d7b21ebc51; jvm 10.0.2-ojdkbuild+13
> 2018-10-22 05:14:40  INFO: Started o.t.w.@53d30d23{/,null,AVAILABLE}
> 2018-10-22 05:14:40  INFO: DefaultSessionIdManager workerName=node0
> 2018-10-22 05:14:40  INFO: No SessionScavenger set, using defaults
> 2018-10-22 05:14:40  INFO: node0 Scavenging every 660000ms
> 2018-10-22 05:14:43  INFO: Started o.e.j.s.ServletContextHandler@3dded90a{/,null,AVAILABLE}
> 2018-10-22 05:14:43  INFO: Started ServerConnector@28538def{HTTP/1.1,[http/1.1]}{0.0.0.0:8082}
> 2018-10-22 05:14:43  INFO: Started @14367ms
> 2018-10-22 05:16:11  INFO: Shutting down server...

**Comment by tananaev** [comment]
It seems like someone has just shut down the server. If there is a problem, you should see an error.

**Comment by JuanIrache** [comment]
> 2018-10-22 05:16:11 INFO: Shutting down server...

That's me restarting traccar for my custom traccar.xml to take effect.

**Comment by tananaev** [comment]
It probably means that there is some critical issue in your config file, so Traccar couldn't even find logging configuration.

**Comment by oliv3** [comment]
Isn't it because the SQL driver name changed in 4.1 ? Just a guess.

**Comment by tananaev** [comment]
If there is some problem with database connection, you should at least see it in logs. If you don't have any logs, it probably means that something is seriously wrong with config file, and even logging config wasn't loaded.

**Comment by JuanIrache** [comment]
It was this line. It used to be ok in 4.0

`<entry key='logger.level'>error</entry>`

**Comment by Abyss777** [comment]
There is one drawback without wrapper, we will never know if any issue in configuration XMLs structure. Can we do something with it?

**Comment by Abyss777** [comment]
I would suggest to use `java.io.tmpdir` to place temporary log.

**Comment by tananaev** [comment]
The problem is that people would never look there. We'll get a lot of issues raised.

Implemented this solution for now: 49d57451db0b9860f40b2ba53bc96069bb86261f

**Comment by Abyss777** [comment]
OK. I think it is fine for now, enough to not get in a situation without information.

**Comment by ombasaMukhwami** [comment]
i have seen some devices are not saving raw data even after setting <entry key='database.saveOriginal'>true</entry> 
or if it save then data is trancated

**Comment by ombasaMukhwami** [comment]
{"priority":0,"sat":0,"event":0,"io200":3,"gpsStatus":3,"di1":0,"out1":false,"di2":0,"di3":0,"power":13.016,"battery":0.0,"adc1":87,"axisX":-142,"axisY":-79,"axisZ":991,"io16":619392,"raw":"0200001f25","distance":0.0,"totalDistance":4803450.82,"motion":false,"ignition":false}
{"priority":0,"sat":0,"event":0,"io200":3,"gpsStatus":3,"di1":0,"out1":false,"di2":0,"di3":0,"power":13.016,"battery":0.0,"adc1":87,"axisX":-141,"axisY":-78,"axisZ":990,"io16":619392,"raw":"01000079ab","distance":0.0,"totalDistance":4803450.82,"motion":false,"ignition":false}
{"priority":0,"sat":0,"event":0,"io200":3,"gpsStatus":3,"di1":0,"out1":false,"di2":0,"di3":0,"power":13.033,"battery":0.0,"adc1":87,"axisX":-142,"axisY":-78,"axisZ":991,"io16":619392,"raw":"010000fd0b","distance":0.0,"totalDistance":4803450.82,"motion":false,"ignition":false}
{"priority":0,"sat":0,"event":0,"io200":3,"gpsStatus":3,"di1":0,"out1":false,"di2":0,"di3":0,"power":13.055,"battery":0.0,"adc1":87,"axisX":-140,"axisY":-78,"axisZ":991,"io16":619392,"raw":"01000098c3","distance":0.0,"totalDistance":4803450.82,"motion":false,"ignition":false}
{"priority":0,"sat":0,"event":0,"io200":3,"gpsStatus":3,"di1":0,"out1":false,"di2":0,"di3":0,"power":13.058,"battery":0.0,"adc1":87,"axisX":-142,"axisY":-78,"axisZ":992,"io16":619392,"raw":"0100008e79","distance":0.0,"totalDistance":4803450.82,"motion":false,"ignition":false}
{"priority":0,"sat":0,"event":0,"io200":3,"gpsStatus":3,"di1":0,"out1":false,"di2":0,"di3":0,"power":13.055,"battery":0.0,"adc1":87,"axisX":-142,"axisY":-78,"axisZ":990,"io16":619392,"raw":"0100009eb4","distance":0.0,"totalDistance":4803450.82,"motion":false,"ignition":false}
{"priority":0,"sat":0,"event":0,"io200":3,"gpsStatus":3,"di1":0,"out1":false,"di2":0,"di3":0,"power":13.058,"battery":0.0,"adc1":87,"axisX":-141,"axisY":-79,"axisZ":991,"io16":619392,"raw":"01000022dd","distance":0.0,"totalDistance":4803450.82,"motion":false,"ignition":false}
{"priority":0,"sat":0,"event":0,"io200":3,"gpsStatus":3,"di1":0,"out1":false,"di2":0,"di3":0,"power":13.06,"battery":0.0,"adc1":87,"axisX":-142,"axisY":-78,"axisZ":990,"io16":619392,"raw":"010000931d","distance":0.0,"totalDistance":4803450.82,"motion":false,"ignition":false}
{"priority":0,"sat":0,"event":0,"io200":3,"gpsStatus":3,"di1":0,"out1":false,"di2":0,"di3":0,"power":13.097,"battery":0.0,"adc1":87,"axisX":-142,"axisY":-80,"axisZ":990,"io16":619392,"raw":"010000ec0b","distance":0.0,"totalDistance":4803450.82,"motion":false,"ignition":false}
{"priority":0,"sat":0,"event":0,"io200":3,"gpsStatus":3,"di1":0,"out1":false,"di2":0,"di3":0,"power":13.062,"battery":0.0,"adc1":87,"axisX":-142,"axisY":-79,"axisZ":991,"io16":619392,"raw":"010000736b","distance":0.0,"totalDistance":4803450.82,"motion":false,"ignition":false}

**Comment by ombasaMukhwami** [comment]
Have you introduced a new configuration to truncate raw data?

**Comment by tananaev** [comment]
Not that I'm aware of.

**Comment by ombasaMukhwami** [comment]
@tananaev i think line 38 in ExtendedObjectDecoder is where the  raw message is 
truncated
