### ISSUE TITLE
Missing documentation for #4047

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar#4116]
Hi, 
Looks like #4047, although not announced, made it in 4.1.
(Congrats to the team for this release by the way). 
Looking at https://www.traccar.org/reverse-geocoding/ I can't find any documentation for it.
Thanks again !

**Comment by tananaev** [comment]
Please provide text for the documentation.

**Comment by oliv3** [comment]
# Base Adresse Nationale
[Base Adresse Nationale](https://adresse.data.gouv.fr/) is a free service limited to French addresses and 10 requests per IP per second.

Configuration parameters:

```xml
<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>ban</entry>
<entry key='geocoder.format'>%f (%d)</entry>
```

**Comment by tananaev** [comment]
Thanks. I have updated the page:

https://www.traccar.org/reverse-geocoding/
