### ISSUE TITLE
Strings are being escaped to XML, breaking geofence names and custom maps

### ISSUE THREAD

**Issue by stere0123** [traccar/traccar#4117]
Going from version 4.0 to 4.1 I have noticed that geofence names with special characters (e.g. apostrophes) get escaped and render as the XML code:
![image](https://user-images.githubusercontent.com/4117048/47277071-5864bc00-d58a-11e8-953b-e61ad3650d1a.png)
![image](https://user-images.githubusercontent.com/4117048/47277072-5ef33380-d58a-11e8-835e-55cb4195fc80.png)

Additionally, the custom map URL gets escaped when it is saved rendering it unusable as it tries to load the URL with the escaped XML code for ampersands:
![image](https://user-images.githubusercontent.com/4117048/47277037-e9876300-d589-11e8-9bfd-7ea62fb1bc72.png)

**Comment by tananaev** [comment]
Please check existing threads before creating a new issue. There are several forum topics about this.
