### ISSUE TITLE
Improvement suggestion - new filter

### ISSUE THREAD

**Issue by JBFelizberto** [traccar/traccar#4120]
I would like to propose a new filter that considers [and store in DB] only valid location within a geofence, and ignores the positions outside of this geofence.

Even with some filters configured - see below - I have the position of some vehicles that are on the sea.
```xml
        <entry key='filter.enable'>true</entry>
        <entry key='filter.invalid'>true</entry>
        <entry key='filter.zero'>true</entry>
        <entry key='filter.duplicate'>false</entry> 
        <entry key='filter.maxSpeed'>25000</entry>
        <entry key='filter.future'>86400</entry> 
        <entry key='filter.distance'>100</entry> 
        <entry key='coordinates.maxError'>2000</entry> 
```
to avoid this situation:

https://drive.google.com/file/d/1Stsgj5dpO5jdQG-EqF6mp-TnbIBTzEuW/view?usp=sharing

JB

**Comment by oliv3** [comment]
Would need some design, which geofences, for who ? Global, by device or group ?
But I basically like the idea.

**Comment by JBFelizberto** [comment]
In my mind, keep the things simple, in other words:
- set-up only global [on server parameters - admin tool]
- a rectangle, [basically]

use this image as reference: https://drive.google.com/file/d/1Stsgj5dpO5jdQG-EqF6mp-TnbIBTzEuW/view?usp=sharing

**Comment by dirkdeb** [comment]
This would definately be helpfull.
 Usually the geofence is connected to a group. If only one device needs to be part of this, add a group and link the device/s and rule to that.

**Comment by JBFelizberto** [comment]
Agree

**Comment by JBFelizberto** [comment]
I would like know If this request may should be launched on the next traccar release

**Comment by tananaev** [comment]
It hasn't been implemented yet, if that's what you are asking.

**Comment by JBFelizberto** [comment]
Hi Anton,

Congratulations for 4.3 version. Seems more stable than 4.2 on windows until now.

About  to the matter at hand, I wonder to know if it is possible to have this filter in the next version of the traccar. Some of my vehicles (with tk303 and gt06) have positioning records at sea.

Regards

JB

**Comment by leandroljunior** [comment]
I would like to have this functionality. I am facing issues with some devices TK303g out of land and wrong reports .

**Comment by JBFelizberto** [comment]
Anton, is it possible consider this improvement for next release?

Regards

JB
