### ISSUE TITLE
Systemd Exit Status 143

### ISSUE THREAD

**Issue by neilromig** [traccar/traccar#4121]
I'm seeing this when traccar-4.1 stops:

```
Oct 24 06:17:10 pinnacle systemd[1]: Stopped traccar.
Oct 24 06:17:10 pinnacle systemd[1]: traccar.service: Failed with result 'exit-code'.
Oct 24 06:17:10 pinnacle systemd[1]: traccar.service: Main process exited, code=exited, status=143/n/a
Oct 24 06:17:09 pinnacle systemd[1]: Stopping traccar...
```

I have added `SuccessExitStatus=143` to my .service file to prevent it appearing to fail.

**Comment by tananaev** [comment]
Exit code 143 corresponds to `SIGTERM`, which means that someone has killed the process.

**Comment by neilromig** [comment]
The command issued was

```
systemctl restart traccar
```

Which I think is the correct way to stop & start a systemd service.

**Comment by tananaev** [comment]
Yes, I think it's expected result.

**Comment by neilromig** [comment]
I still think you should add the SuccessExitStatus to the .service file!

**Comment by tananaev** [comment]
But then any actual failure would be ignored as well. I think we need to find a proper way to exit the service.

**Comment by tananaev** [comment]
I have implemented your suggestion for now, thanks.
