### ISSUE TITLE
filter.future filter doesn't work properly with filter.skipLimit

### ISSUE THREAD

**Issue by lukazi** [traccar/traccar#4128]
I have future filter enable but still future positions in the database. It seems filter.skipLimit omits filter.future .  When is filter.skipLimit disabled, filter.future works fine.
Traccar version v4.1.

```
    <entry key='filter.enable'>true</entry>
    <entry key='filter.duplicate'>false</entry>
    <entry key='filter.zero'>false</entry>
    <entry key='filter.invalid'>true</entry>
    <entry key='filter.distance'>0</entry>
    <entry key='filter.static'>false</entry>
    <entry key='filter.future'>86400</entry>
    <entry key='filter.skipLimit'>120</entry>
    <entry key='filter.maxSpeed'>25000</entry>
    <entry key='filter.skipAttributes'>ignition</entry>
    <entry key='event.overspeed.notRepeat'>true</entry>
```

> 4140272 | opengts | 80 | 2018-10-29 16:43:43.164 | 2099-01-01 01:00:00 | 2099-01-01 01:00:00 | FALSE | 50.11049668333333 | 14.267933966666666 | 0.0 | 0.0 | 78.2 | null | {"distance":0.0,"totalDistance":274857.49,"motion":false} | 0.0 | null
> -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
> 4140269 | opengts | 69 | 2018-10-29 16:43:20.387 | 2099-01-01 01:00:00 | 2099-01-01 01:00:00 | FALSE | 50.11049668333333 | 14.267933966666666 | 0.0 | 0.0 | 78.2 | null | {"distance":0.0,"totalDistance":1602294.32,"motion":false} | 0.0 | null
> 4140263 | opengts | 27 | 2018-10-29 16:42:55.157 | 2099-01-01 01:00:00 | 2099-01-01 01:00:00 | FALSE | 50.11049668333333 | 14.267933966666666 | 0.0 | 0.0 | 78.2 | null | {"distance":0.0,"totalDistance":1443093.93,"motion":false} | 0.0 | null
> 4140246 | opengts | 60 | 2018-10-29 16:42:20.916 | 2099-01-01 01:00:00 | 2099-01-01 01:00:00 | FALSE | 50.11049668333333 | 14.267933966666666 | 0.0 | 0.0 | 78.2 | null | {"distance":0.0,"totalDistance":194024.67,"motion":false} | 0.0 | null
> 4140242 | opengts | 62 | 2018-10-29 16:42:20.891 | 2099-01-01 01:00:00 | 2099-01-01 01:00:00 | FALSE | 50.11049668333333 | 14.267933966666666 | 0.0 | 0.0 | 78.2 | null | {"distance":0.0,"totalDistance":200534.41,"motion":false} | 0.0 | null
> 4140231 | opengts | 80 | 2018-10-29 16:41:33.194 | 2099-01-01 01:00:00 | 2099-01-01 01:00:00 | FALSE | 50.11049668333333 | 14.267933966666666 | 0.0 | 0.0 | 78.2 | null | {"distance":0.0,"totalDistance":274857.49,"motion":false} | 0.0 | null
> 4140226 | opengts | 69 | 2018-10-29 16:41:07.261 | 2099-01-01 01:00:00 | 2099-01-01 01:00:00 | FALSE | 50.11049668333333 | 14.267933966666666 | 0.0 | 0.0 | 78.2 | null | {"distance":0.0,"totalDistance":1602294.32,"motion":false} | 0.0 | null
> 4140215 | opengts | 27 | 2018-10-29 16:40:44.609 | 2099-01-01 01:00:00 | 2099-01-01 01:00:00 | FALSE | 50.11049668333333 | 14.267933966666666 | 0.0 | 0.0 | 78.2 | null | {"distance":0.0,"totalDistance":1443093.93,"motion":false} | 0.0 | null
> 4140212 | opengts | 60 | 2018-10-29 16:40:03.521 | 2099-01-01 01:00:00 | 2099-01-01 01:00:00 | FALSE | 50.11049668333333 | 14.267933966666666 | 0.0 | 0.0 | 78.2 | null | {"distance":0.0,"totalDistance":194024.67,"motion":false} | 0.0 | null
> 4140202 | opengts | 80 | 2018-10-29 16:39:22.181 | 2099-01-01 01:00:00 | 2099-01-01 01:00:00 | FALSE | 50.11049668333333 | 14.267933966666666 | 0.0 | 0.0 | 78.2 | null | {"distance":0.0,"totalDistance":274857.49,"motion":false} | 0.0 | null
> 4140169 | opengts | 69 | 2018-10-29 16:38:24.238 | 2099-01-01 01:00:00 | 2099-01-01 01:00:00 | TRUE | 50.11049668333333 | 14.267933966666666 | 0.0 | 0.0 | 78.2 | Schengenská, Prague, Prague, CZ | {"distance":0.0,"totalDistance":1602294.32,"motion":false} | 0.0
>

**Comment by tananaev** [comment]
That's expected behaviour.

**Comment by lukazi** [comment]
Can't agree Anton. Duplicate, distance, static filters are filtering positions which could be valid but which are send too often. SkipLimit could make the sence there. 
But Future filter is filtering positions which are invalid by nature as you can see above.
Try to thing about that. Thanks, L
