### ISSUE TITLE
Suggestion: can we create a beta brand to avoid simple bugs like in v4.1 ?

### ISSUE THREAD

**Issue by castillo92** [traccar/traccar#4129]
Hello, I want to ask @tananaev and all of developers, who spend it's time using and improving Traccar, if they look good idea create a _channel Beta_ to try Traccar 1 week before Anton upload it to _https://www.traccar.org/download/_

By this way, some users (who do not care about try a beta compilation) could try it and tell Anton the most important bugs, and if it is possible to fix them easily, those bugs will not arrive to the main page of traccar and take the risk of downloading

What do you think?

**Comment by tananaev** [comment]
Release takes quite a bit of time, so I don't think I can dedicate even more time for it to provide beta builds, but any contribution and help on that front is welcome.

**Comment by whatnick** [comment]
Perhaps the CI can assist by uploading nightlies/tagged builds back onto github for user-testing. 
https://docs.travis-ci.com/user/deployment/releases/

**Comment by tananaev** [comment]
That's releases. We don't want to clutter release list with daily build.
