### ISSUE TITLE
[feature request] do not skip filter.future by filter.skipLimit

### ISSUE THREAD

**Issue by lukazi** [traccar/traccar#4135]
filter.skipLimit omits filter.future.  Duplicate, distance, static filters are filtering positions which could be valid but which are sent by devices too often. SkipLimit makes the sence there.
But Future filter is filtering positions which are invalid by nature.
That's why I mean filter.future should not be skipped by filter.skipLimit

**Comment by tananaev** [comment]
What about other filters?

**Comment by lukazi** [comment]
Not sure what do you mean by question. I think other filters can stay like they are. Only future filter is another principle

**Comment by tananaev** [comment]
What about zero coordinates filtering? Or invalid positions?

**Comment by lukazi** [comment]
Well,  zero and invalid should not be canceled by skipLimit also I mean. Only filters duplicate, distance, static.
Or it could be filters attribute eg. filter.static.skipLimit

**Comment by tananaev** [comment]
In your previous comment you said only future filter should not be cancelled. Now you are saying there are other.

I suggest that you properly review all available filters and make a well defined feature request with proper justification for every case. Then we can discuss it.

**Comment by lukazi** [comment]
All filters are not documented here https://www.traccar.org/configuration-file/ but as far as I can understand the code how they work

These filters should not be cancelled by skipLimit
filter.future
filter.invalid
filter.zero
filter.maxspeed
filter.minperiod
filter.accurancy
filter.approximate

These filters should be cancelled by skipLimit
filter.static
filter.duplicate
filter.distance

The question is if it's not better to have an skipLimit option for each of them (filter.xyz.skipLimit)

**Comment by tananaev** [comment]
Let's see what other people say. Using separate skip limit for each option seems to be an overkill, but then not everyone would agree with your split.

**Comment by gpproton** [comment]
filter.static, filter.duplicate, filter.distance are also very important, in a setup where there's above 1000 vehicle they're a life saver, my opinion would be slowing skipLimit during movement.

**Comment by GPSIndia** [comment]
This is affecting to us as well. Suggest Tananaev to consider this

**Comment by GPSIndia** [comment]
Thanks for your support. How can we get this update, any jar file or setup

**Comment by tananaev** [comment]
It will be available with next release.
