### ISSUE TITLE
Traccar 4.1 - It is not possible use the filters  on mobile 

### ISSUE THREAD

**Issue by JBFelizberto** [traccar/traccar#4136]
I noticed that I am not able anymore to use filters on device table viewed by mobile (filter by name, for example , it is not possible type the string to search. it is only possible sort by A-Z, Z-A).

I saw it on Android / Chrome

JB

**Comment by tananaev** [comment]
What exactly prevents you from filtering?

**Comment by JBFelizberto** [comment]
when we click on item or on arrow, the string box do not appear to be typed:

https://drive.google.com/file/d/1ZgRb5pL2TFSu5jz50zDrEHXeWHPzq-QB/view?usp=sharing

**Comment by tananaev** [comment]
Duplicate of https://github.com/traccar/traccar-web/issues/713. Please look up for existing issues before posting new ones.
