### ISSUE TITLE
Sanitizing strings

### ISSUE THREAD

**Issue by diego-cr** [traccar/traccar#4137]
I think this is "sanitizing" mapurl, bingkey, etc..... and replace "&" by "&and;"

https://github.com/traccar/traccar/commit/fac0cc89583d9294285af84853b2f9e7a02fb46c

**Comment by tananaev** [comment]
It does, but what's your point?

**Comment by diego-cr** [comment]
When edit something on server tab on bing or custom map strings shows &amps, if apply changes without replace it with good strings it add %amp to DB and stop working, need to change it always than you make a change on server tab.

**Comment by tananaev** [comment]
Have you completely ignored my comment?

**Comment by diego-cr** [comment]
No.
Enter on server settings, add custom map url, apply, works.
Enter again on server settings, don't modify anything or other thing that custom map, apply, stop working.

To complie it on my machine I had to add this on pom.xml

            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.10</version>
            </plugin>

**Comment by diego-cr** [comment]
Thanks for your great work, this fix it.

https://github.com/traccar/traccar-web/commit/58e1f370c568af64a1dcbd9af1d5541b0e9314ed
