### ISSUE TITLE
Address link error 

### ISSUE THREAD

**Issue by JBFelizberto** [traccar/traccar#4140]
The address link on the device panel appears to be wrong. it points to its own website (loop)

https://drive.google.com/file/d/1MypoF_3v2zsMIZr1azw9yU7SzjdC-urf/view?usp=sharing

JB

**Comment by tananaev** [comment]
That's not a regular link.

**Comment by JBFelizberto** [comment]
in 3.17 version, when I click on the link, it shows a address  (in string format, converting coordinates on address). Now the link do not works. 

JB

**Comment by tananaev** [comment]
Works for me.
