### ISSUE TITLE
[Feature Request] Integration of Google Maps using official APIs legally

### ISSUE THREAD

**Issue by ali-raza101** [traccar/traccar#4143]
Dear @tananaev , I'm creating this feature request as I'm unable to do this, As per discussion about Google maps with you 5 months ago here, https://github.com/traccar/traccar/issues/2991

The Google Maps are most updated and popular maps with enriched places labeling but traccar doesn't support it. Now before someone says that they are already using Google maps layer in traccar mentioned din https://www.traccar.org/map-layers/, Lets me remind everyone that is is strictly prohibited and Google will block every domain/server who is using tile server directly. 

Please read Google FAQ and TOS here: https://developers.google.com/maps/faq#tos_tiles

After the new pricing plans of 2018 now I think any small scale business can use Google Maps. Just view their pricing which Google sent me in email here when I contact their sales department for premium License https://cloud.google.com/maps-platform/pricing/sheet/

Please do have a look yourself and share it with your team. This is very useful and demanding feature. Thanking you in anticipation.

**Comment by ali-raza101** [comment]
@tananaev have you seen this? It has been 9 days, please respond.

**Comment by ali-raza101** [comment]
@tananaev please respond

**Comment by tananaev** [comment]
I've seen it. What exactly do you want me to respond to?

**Comment by ali-raza101** [comment]
Can you consider this feature to be included in your traccar next version? Or at least have this in your project pipeline?

**Comment by tananaev** [comment]
We'll consider it.

**Comment by ali-raza101** [comment]
Thanks a lot sir. :smiley:

**Comment by ali-raza101** [comment]
@tananaev It has been 4 months, any chance of Google Maps Api integration in next release?

**Comment by tananaev** [comment]
I will comment here if there is an update.

**Comment by twf-nikhila** [comment]
Is it implement? @tananaev

**Comment by tananaev** [comment]
@twf-nikhila see comment above.

**Comment by twf-nikhila** [comment]
I was just checking incase it's implemented but not updated in here.

Anyways, Thank you

**Comment by ali-raza101** [comment]
@tananaev any luck for integration of Google Maps legally in traccar?

**Comment by ali-raza101** [comment]
@tananaev  sir hope you are fine, kindly tell us about update regarding this? stay blessed

**Comment by wkhaksar** [comment]
We are also interested in this. Hope we get a positive response with this feature implemented.

**Comment by tananaev** [comment]
Currently it's not really possible because Maplibre can't use Google Maps. Closing for now, but we can reassess if things change in the future. Maybe someone comes up with a workaround for this.
