### ISSUE TITLE
Protocol AIS140 Updates

### ISSUE THREAD

**Issue by GPSIndia** [traccar/traccar#4144]
[AIS140_message_formats_257.docx](https://github.com/traccar/traccar/files/2588200/AIS140_message_formats_257.docx)

The AIS140 protocol has been updated. Suggest if someone can update the same based on the document attached. It will be great help to Indian GPS System

**Comment by GPSIndia** [comment]
Can anyone help on this ?

**Comment by GPSIndia** [comment]
This protocol is of utmost importance for my country.

**Comment by GPSIndia** [comment]
This is still not working. Any takers for this task to help my country use traccar ?

**Comment by GPSIndia** [comment]
Awaiting some help here.

**Comment by greatidea1** [comment]
Protocol will depend on the device and it's firmeware. 
AIS140 is a standard, not a protocol
You can use the 'implement new protocol' feature.

**Comment by greatidea1** [comment]
Protocol will depend on the device and it's firmware.
AIS140 is a standard, not a protocol
You can use the 'implement new protocol' feature.

**Comment by GPSIndia** [comment]
AIS140 is a standard. But that talks about generalization of the protocol that has to be used. So its a fix protocol that has to be used. This will not depend on device and its firmware. Each and every device following AIS140 standard has to implement same protocol

**Comment by GPSIndia** [comment]
This is still not working completely as per the document......please check.......
