### ISSUE TITLE
Location markers disappear from the map due to one tracker

### ISSUE THREAD

**Issue by VBP8501** [traccar/traccar#4148]
Hello, 

We currently have version v4.2 installed and 261 devices connected. 

One of the devices using the osmand protocol communicated during its startup the following :
```
GET ?alarm=&timestamp=1542894386&id=866191035136357&lat=0.00000&lon=0.00000&speed=0&heading=0&sat=0&temp=34&battery=3.4&valid=false HTTP/1.1
```
It communicated this string about 10 times before running out of battery. Since it was temporarily charged in a concrete building, it couldn't get a proper fix at that time.

When a user had this tracker in its list of devices, not a single other tracker would have a location marker on the map. At first I thought this was due to a limited number of location markers allowed on the map but that is not the case (?). Then I started disabling one by one the trackers until I arrived at this specific tracker. 

It turns out that it was enough to have this device in the list with any other devices to clear the map of location trackers for all devices.

No javascript or html errors appear in the console. 

I moved the device outside to get a fix and when it started sending proper coordinates, the maps was again filled with location markers.
Note that I tried to change the category (icon) of the device but that did not help solve the issue.

**Comment by tananaev** [comment]
The problem like this can happen if device coordinates are out of valid range.

**Comment by VBP8501** [comment]
Thanks for the respons Anton. Do you consider this normal behaviour or a bug that needs to be fixed?

**Comment by tananaev** [comment]
It's a device bug. It should not send data out of range. It might be a good idea to handle it on the server side, but it's not really a server bug.

**Comment by VBP8501** [comment]
Ok in that case you can close this issue. However I think that the server side user interface should be able to handle one faulty device and not stop working properly for all other devices. I also don't see anything wrong with the data that the device has sent. 0,0 are normal coordinates I believe?

**Comment by tananaev** [comment]
Zeroes are normal coordinates, but you need to check "current" location of the device.

**Comment by VBP8501** [comment]
Ok I understand what you mean though I could have used some more information. With "current" location you mean the positionid mentioned in tc_devices and that the position this refers to should be correct values.

I've done some more investigation and it turns out that the device once transmitted these values:
"latitude";"longitude"
-178.59582;151.89559
The latitude is out of bounds. I've reset the positionid to one of these values and indeed, all the markers disappeared from the map.

I agree that in the first place a device should not transmit this data
But I also believe that traccar should know how to handle this kind of "runtime error" without crashing.

**Comment by tananaev** [comment]
The crash is actually in the map library, so "fixing" it in Traccar is not possible. We can only implement some workaround.

**Comment by tananaev** [comment]
Closing as this is not related to the new web app.
