### ISSUE TITLE
WARN: Empty address

### ISSUE THREAD

**Issue by JBFelizberto** [traccar/traccar#4151]
Since I have installed traccar 4.1 and now, using traccar 4.2, I am getting a lot of "warn empty address" in logs.
I am providing the Google Key, to resolve the address only by demand (geocoder.onRequest), and no for all request.

Please see topic 2 from https://www.traccar.org/forums/topic/warn-empty-address).

Regards

JB

**Comment by tananaev** [comment]
So what's your request or problem?

**Comment by JBFelizberto** [comment]
There are a lot of reverse geocoding request occuring, although the parameter 'geocoder.ignorePositions=true' is set.

I mean, automatic reverse geocoding requests for all positions are not being disable.

Could you check pls?

**Comment by tananaev** [comment]
The requests that you get are likely for notifications. For events we use reverse geocoding, if `onRequest` is enabled.
