### ISSUE TITLE
Java Error on Traccar Connection to SQL Server

### ISSUE THREAD

**Issue by traccaruser** [traccar/traccar#4152]
Tried signing up at traccar org forums, but failed. I am having trouble getting Traccar to connect to a new SQL database. I have edited the traccar.xml to include the format
```xml
	<entry key='database.driverFile'>C:\sqljdbc_6.0\enu\jre8\sqljdbc42.jar</entry>
	<entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
	<entry key='database.url'>jdbc:sqlserver://[SERVER]\MSSQLSERVER;user=UserName;password=*****; databaseName=[Database];</entry>
	<entry key='database.user'>UserName</entry>
	<entry key='database.password'>*****</entry>
```
and verified the location of the .jar. I am getting this error in my server-tracker.log file:
```
ERROR: Main method error - Unable to make void jdk.internal.loader.ClassLoaders$AppClassLoader.appendToClassPathForInstrumentation(java.lang.String) accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @355ac898 - InaccessibleObjectException (... < DataManager:113 < *:89 < Context:382 < Main:110 < ...)
```
I can't seem to shake this one on my own, and I found one other user on here with the same error, but his solution didn't work for me (adding or removing the database name). I am running Traccar 4.2. Any thoughts on where to look? That is the only error I receive, then service must stall because traccar refuses to connect.

Thanks,

David

**Comment by tananaev** [comment]
Remove `database.driverFile`. Why are you using it?

**Comment by traccaruser** [comment]
I had found a few older examples of it being used to show where the jdbc driver file was. I thought it had to be used because all the driver installer did was extract the contents to a folder.

**Comment by tananaev** [comment]
I would recommend you to use official documentation as the main source of information:

https://www.traccar.org/ms-sql/

You don't need to install any drivers. Traccar already includes MS SQL driver.
