### ISSUE TITLE
windows service

### ISSUE THREAD

**Issue by AhmadNosratian** [traccar/traccar#4155]
hi 
first , thank you for this system .
 then , i want to change traccar service name 
i use this command to delete traccar service -->java -jar tracker-server.jar --uninstall ./conf/traccar.xml
but it doesnt work .
please help me to do this :)

**Comment by tananaev** [comment]
Please don't duplicate your messages:

https://www.traccar.org/forums/topic/windows-service/

**Comment by AhmadNosratian** [comment]
@tananaev 
can i do this ?

**Comment by tananaev** [comment]
It should work.

**Comment by AhmadNosratian** [comment]
this command i used is right ???
in netbeanse when i passed this  parameter and debug it ,i return false and servicemanger return null !

**Comment by AhmadNosratian** [comment]
execuseme but  i this i am admin user i try it in my laptop and desktop computer but it doesnt work for me
