### ISSUE TITLE
forward.url deviceTime format

### ISSUE THREAD

**Issue by xspid3r** [traccar/traccar#4157]
Hi, i'm using forward.url and save the result in a file but when i saw the time format **1544543508000** first i thought its timestamp but when i tried converting it didn't give the right date

**Comment by tananaev** [comment]
It is a timestamp.

**Comment by xspid3r** [comment]
But when i convert it, it gives the following  **20/8/50914 à 23:20:00** !!

**Comment by tananaev** [comment]
It's in milliseconds, not seconds.

**Comment by xspid3r** [comment]
Okey thanks.
