### ISSUE TITLE
No notificator configured for type : mobile

### ISSUE THREAD

**Issue by evallgar** [traccar/traccar#4158]
I'm getting this error on _tracker-server.log_ file.
```
2018-12-13 01:41:44  WARN: No notificator configured for type : mobile
2018-12-13 01:41:44  WARN: You are using null notificator, please check your configuration, notification not sent
```
It was working fine yesterday, I only uploaded modifications to web app. I been hitting my head against the wall the whole day with this, If someone can enlighten me I would really appreciate it. At this point I'm lost. 

Thanks.

**Comment by tananaev** [comment]
Well, you have some problem with configuration.

**Comment by evallgar** [comment]
This is my firebase configuration

````
<entry key='notificator.types'>web,mail,firebase,forward</entry>
<entry key='notificator.firebase.key'>AAAABGURGJE:APA91bES7878y8lOcYwyKp-mZFRpLGMofAMnRPqISZqrV-PnG-3g5v48z9UnTIkrfiRvc57kGcbnAQUrgQzX6GqQoK6rn-BmcuL-3yqsMGQzZONdhgXXXXXXXXXXXXXXXXXXXXXXXX</entry>
`````
I double-checked for typos and I see it ok, what else could I be missing?

**Comment by tananaev** [comment]
Looks like you are not using official version of Traccar, so I don't think we would be able to help. Try official release and see if it helps.

**Comment by evallgar** [comment]
I removed my own version, reinstated official version, removed _forward_ from notificator types configuration entry and still getting the same ...
I will start from blank to catch the error ... I think it has to be some very stupid error from my side ...

Thanks

**Comment by evallgar** [comment]
As I said, I wrote "mobile" instead of "firebase". Please excuse the mistake.
