### ISSUE TITLE
Question about device(IDD-213GL) with Castel protocol decoder

### ISSUE THREAD

**Issue by BryanCoronelTapia** [traccar/traccar#4159]
Hellow, Im new in traccar
Someone know if platform supports device IDD-213GL(with castel protocol), because I recive porwer on alarm just once, but later when I shut down my car I do not recive the alarm. I have checked the logs with hex decoder, but I can not understand that data. 

Pd: Sorry because of my English.

**Comment by tananaev** [comment]
Please make title normal case, not all caps!

**Comment by BryanCoronelTapia** [comment]
I`m not shure if now it is correct? I`m new in the comunity.
Thanks for quick answer

**Comment by tananaev** [comment]
Doesn't matter what community you are in. Writing in all-caps is showing your disrespect to that community.

**Comment by BryanCoronelTapia** [comment]
mmm I can`t understand what means all-caps? , english is not my native language....

**Comment by tananaev** [comment]
https://en.wikipedia.org/wiki/All_caps

**Comment by BryanCoronelTapia** [comment]
ok, I understand,sorry. I had changed my title

**Comment by oliv3** [comment]
I wouldn't be sorry. Yelling at users because they make mistake is also a form of disrespect.

**Comment by tananaev** [comment]
No one is yelling. Also, I don't think it's a mistake. We all know why people use all-caps.

**Comment by BryanCoronelTapia** [comment]
Yes no one is yelling, I was trying sql queries so I forgot my all caps active, when I check my issue.

**Comment by tananaev** [comment]
About your issue. You need to provide HEX samples (of what's not working) and protocol documentation.

**Comment by BryanCoronelTapia** [comment]
That is a hex sample, and I´m searching protocol documentation and the device specifications to find what that information means....
![capturahex](https://user-images.githubusercontent.com/45852846/49951289-95cd3200-fec7-11e8-84ce-49a67c0dafde.PNG)

**Comment by tananaev** [comment]
I would need it in text form, not a screenshot. Also, using Hex Decoder for a binary protocol is pointless.

**Comment by BryanCoronelTapia** [comment]
I recibe this kind of hex code in server, I don`t think it is binary.
 
`2018-12-13 08:14:41 DEBUG: [F96344CB: 5086 < 200.7.236.9] HEX: 4040760004323133474c3230313630303138353700000000004004ee68125c5169125c000000000000000001000000020000000400036400111a0003001a032104210521062107210b210c210d210e210f2111211321142115211c211f2121212e213021332142214521472149214a214c212aff0d0a`

**Comment by tananaev** [comment]
It is binary. Not sure why you would think otherwise, especially after I told you it is.

**Comment by BryanCoronelTapia** [comment]
mmm okay, then I understand that traccar does not use a hex decoder to proccess data from castel protocol. Then I have to identify the data directly, isn`t it?

**Comment by tananaev** [comment]
Hex decoder is for people to be able to read messages from text-based protocols. Traccar never uses it. It fact it never even deals with hex data. It decodes binary data into values or strings.

**Comment by BryanCoronelTapia** [comment]
I was looking for especifications from the vendor but I have the same problem: 

[https://www.traccar.org/forums/topic/sinocastel-idd-212g-device/page/2/](url)

With different model device.
