### ISSUE TITLE
GT06 Filters

### ISSUE THREAD

**Issue by GPSIndia** [traccar/traccar#4162]
Below filters affects working of GT06. 

Request you to please ignore them for GT06 or provide an option to apply them at device level instead of in the config file 

filter.duplicate=false
decoder.ignoreSessionCache=true

**Comment by GPSIndia** [comment]
Can any please help here

**Comment by tananaev** [comment]
I don't really understand what you want. If you want to change how Traccar works, you need to explain it properly and provide justification. We won't change something just because you want it to work certain way.

**Comment by GPSIndia** [comment]
These filters work well with other protocol devices and are required for their smooth operation. I mean to avoid Jumps and  false movement.

When applied GT06 devices stop working

**Comment by tananaev** [comment]
It means that device reports same location, if duplicate filtering affects it.

**Comment by GPSIndia** [comment]
Even with the device moving, when the filter.duplicate is set to false and decoder.ignoreSessionCache is set to true. GT06 devices are shown as offline

**Comment by tananaev** [comment]
You can't use `ignoreSessionCache` with GT06 because it sends IMEI in the first message only.

**Comment by GPSIndia** [comment]
You are correct But this is required for other device I am not able to put these two filters at the device level or the group level. Both of them can be assigned at the top level only. So either these have to be ignore for GT06 or there has to be provision to allow them at the device level or group level

**Comment by tananaev** [comment]
You should be using different configuration parameter.

**Comment by GPSIndia** [comment]
Use of these filters cannot be omitted. As such request you to work out a option to skip them for GT06 protocol or provide option for assigning these filters on device level or group level

**Comment by GPSIndia** [comment]
Is this being considered for assistance ?

**Comment by GPSIndia** [comment]
pl suggest the way forward....
