### ISSUE TITLE
Duplicate filtering on ingress should check DB

### ISSUE THREAD

**Issue by PhilRW** [traccar/traccar#4163]
I noticed that the duplicate filter only compares to the last Position. I believe the filter should look in the database to see if a duplicate Position already exists. The client I use, [GPS Logger](http://gpslogger.app), can automatically upload its history at a set interval, but it uploads all positions for the day since midnight every time, whether or not they have already been sent to the server. This results in many duplicate entries.

This may be related to issue #1620.

**Comment by tananaev** [comment]
What you are asking is not feasible from performance point of view.

**Comment by PhilRW** [comment]
Then how about a utility to scrub the database for duplicate entries that could be run as needed?

**Comment by tananaev** [comment]
That might be a better option. You can probably already write an SQL query that would do this for you.

**Comment by PhilRW** [comment]
I'll see what I can come up with. You can assign this issue to me if you want as a reminder.

**Comment by tananaev** [comment]
We don't usually assign issues.
