### ISSUE TITLE
Error Socket Connection with JavaScript, Ajax

### ISSUE THREAD

**Issue by josuelmm** [traccar/traccar#4167]
Good day, I have a problem with a socket in js.
```js
$.get( '<?= env('URL_PORT_TRACCAR');?>/api/server', function( data ) {
       $.post('<?= env('URL_PORT_TRACCAR');?>/api/session',{
			 email: '<?= env('USER_TRACCAR');?>', 
			 password: '<?= env('PASS_TRACCAR');?>'
       },function( data ) {
          openWebsocket2();
      });
    });
``` 

```js
var openWebsocket2 = function(){
            var socket;
            socket = new WebSocket('ws://<?= env('SOCKET_TRACCAR');?>/api/socket');

            socket.onclose = function (event) {
                console.log("WebSocket closed");
            };

            socket.onmessage = function (event) {
                var i, j, store, data, array, entity, device, typeKey, alarmKey, text, geofence;
                console.log(event.data);
            };
        };
```

This is my code. The problem is if I do not have the session initiated by port 8082, the socket does not work. It should be with the ajax code to be able to open the session and use the socket, but it is not working. The post function returns the user's data, so if the user is sent and email and receiving a response, but is not opening the socket or the session to use the socket.
What can be.

**Comment by gaiththewolf** [comment]
Hi, i have the same problem i tried every thing in documentation and in the sample but the ajax not saving the session that will be used in websocket, i'm using the latest version of traccar on windows server
