### ISSUE TITLE
Trccar 4.2 - Start MySQL Error 

### ISSUE THREAD

**Issue by jaroja4** [traccar/traccar#4169]
Hi.

I have a problem with a clean installation.

So it seems that MySQL does not like the default value of devicetime.

This is my version of MYSQL:
mysql See 14.14 Distrib 5.7.24, for Linux (x86_64) using EditLine wrapper

When I start the Traccar service, the log indicates the following:

```
2018-12-22 00:53:33 ERROR: Change Set changelog-4.0-clean::changelog-4.0-clean::author failed.  Error: Invalid default value for 'devicetime' [Failed SQL: CREATE TABLE traccar.tc_positions (id INT AUTO_INCREMENT NOT NULL, protocol VARCHAR(128) NULL, deviceid INT NOT NULL, servertime timestamp DEFAULT NOW() NOT NULL, devicetime timestamp NOT NULL, fixtime timestamp NOT NULL, valid BIT(1) NOT NULL, latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, altitude FLOAT NOT NULL, speed FLOAT NOT NULL, course FLOAT NOT NULL, address VARCHAR(512) NULL, attributes VARCHAR(4000) NULL, accuracy DOUBLE DEFAULT 0 NOT NULL, network VARCHAR(4000) NULL, CONSTRAINT PK_TC_POSITIONS PRIMARY KEY (id))]


2018-12-22 00:53:33  INFO: Successfully released change log lock


2018-12-22 00:53:33 ERROR: Main method error - Migration failed for change set changelog-4.0-clean::changelog-4.0-clean::author:
     Reason: liquibase.exception.DatabaseException: Invalid default value for 'devicetime' [Failed SQL: CREATE TABLE traccar.tc_positions (id INT AUTO_INCREMENT NOT NULL, protocol VARCHAR(128) NULL, deviceid INT NOT NULL, servertime timestamp DEFAULT NOW() NOT NULL, devicetime timestamp NOT NULL, fixtime timestamp NOT NULL, valid BIT(1) NOT NULL, latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, altitude FLOAT NOT NULL, speed FLOAT NOT NULL, course FLOAT NOT NULL, address VARCHAR(512) NULL, attributes VARCHAR(4000) NULL, accuracy DOUBLE DEFAULT 0 NOT NULL, network VARCHAR(4000) NULL, CONSTRAINT PK_TC_POSITIONS PRIMARY KEY (id))] - MigrationFailedException (... < DataManager:312 < *:90 < Context:382 < Main:110 < ...)
```
I appreciate the help you can give me.

**Comment by tananaev** [comment]
Let's see your config file.

**Comment by jaroja4** [comment]
The configuration file is the default.

[/opt/traccar/conf/traccar.xml]

The only thing that was modified was the connection to the BD



    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>   
    <entry key="database.dataSource">com.mysql.jdbc.jdbc2.optional.MysqlDataSource</entry>
    <entry key='database.url'>jdbc:mysql://localhost:2020/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8</entry>
    <entry key='database.user'>miusuario</entry>
    <entry key='database.password'>mipasswd</entry>
    <entry key='database.ignoreUnknown'>true</entry>
    <entry key='database.changelog'>/opt/traccar/schema/changelog-master.xml</entry>


This configuration is taken from another server that is in production with Ubuntu 14.04 and the following version of MySQL:
mysql  Ver 14.14 Distrib 5.5.57, for debian-linux-gnu (x86_64) using readline 6.3


the file default.xml has not been modified

**Comment by tananaev** [comment]
You should follow official documentation:

https://www.traccar.org/mysql/

**Comment by jaroja4** [comment]
Hello Anton, I already tried with the configuration in clean:

<entry key = 'database.driver'> com.mysql.jdbc.Driver </ entry>
<entry key = 'database.url'> jdbc: mysql: // [HOST]: 3306 / [DATABASE]? useSSL = false & amp; allowMultiQueries = true & amp; autoReconnect = true & amp; useUnicode = yes & amp; characterEncoding = UTF-8 & amp; sql_mode = '' </ entry>
<entry key = 'database.user'> [USER] </ entry>
<entry key = 'database.password'> [PASSWORD] </ entry>

But it still fails the same. As the log says, the problem is in the devicetime default value. Has this never happened to you?

**Comment by tananaev** [comment]
It happens when you don't follow documentation.
