### ISSUE TITLE
New Http Sms API

### ISSUE THREAD

**Issue by gdrako** [traccar/traccar#4171]
Hello

If there is time available from the developers I would like to implement a new API interface for sending sms.
Here is the information from the official site.
https://www.smsapi.com/docs/#1-introduction

Regards

**Comment by tananaev** [comment]
Can't you already use it with HTTP API option?

**Comment by gdrako** [comment]
Yes, I tried with all three examples but without success.
See below the log...

WARN: Unable to connect to SMPP server:  - Unable to connect to host [localhost] and port [2775]: Connection refused: localhost/127.0.0.1:2775 - SmppChannelConnectException (... < SmppClient:171 < ReconnectionTask:29 < ...)

Also see an example that works well with the API in php..
https://drive.google.com/open?id=1jvSFpcElf9tE9OcwC11-83qL7ffpeXbJ

Regards

**Comment by gdrako** [comment]
The error stopped appearing when I made false the "sms.enable" parameter
However, it still does not send sms alerts
Probably something I  be wrong ..Here is the current config..

<entry key='notificator.types'>web,mail,sms</entry>
<entry key='sms.enable'>false</entry>
<entry key='notificator.sms.manager.class'>org.traccar.sms.HttpSmsClient</entry>
<entry key='sms.http.url'>https://api2.smsapi.com/sms.do</entry>
<entry key='sms.http.authorization'>XXXXXXXXXXXXXXXXXXXzGO4CIxXKxCpbIg</entry>
<entry key='sms.http.template'>
    [{
        "to": "{phone}",
        "message": "{message}",
        "device_id": 1
    }]
</entry>
