### ISSUE TITLE
[Feature Request]  Sendgrid Support

### ISSUE THREAD

**Issue by Igor-Lopes** [traccar/traccar#4172]
Hi,

I would like to suggest [Sendgrid](https://sendgrid.com/) support for email notification. It's a great platform for email delivery, with easy template customization and other features. Perhaps we could see how many people are interested in this feature and if it's possible to implement it.

Thank you

**Comment by MartinAarts** [comment]
Can't you just use the Sendgrid SMTP, like any other SMTP?

**Comment by tsmgeek** [comment]
https://sendgrid.com/blog/web-api-or-smtp-relay-how-should-you-send-your-mail/

Aparently using their API directly is faster and better error handling.

May be an idea to have this support built into the smtp/mail to use a http endpoint.

**Comment by tananaev** [comment]
I don't think we need it to be faster. We don't send a massive number of emails. SMTP should work and doesn't seem like there's a lot of interest, so I'm going to close it. But if someone is interested in contributing this, we can consider it.

**Comment by enriqueillan** [comment]
I am disagree with you. Using gmail is simply not a good idea. It is very easy and fast to get blocked from the API because what you are doing is considered spam. There are limits in that aspect. Therefore having support for a much larger amount of emails should be an included feature.

**Comment by tananaev** [comment]
I don't see any suggestions to use gmail, so I'm not sure what exactly you're disagreeing with. Most email API services, including Sendgrid, provide SMTP API option.

**Comment by enriqueillan** [comment]
![image](https://github.com/traccar/traccar/assets/7118479/a6aaa423-6fce-413d-bd63-c3c8796b7f10)

https://support.google.com/mail/answer/22839?hl=en#:~:text=%22You%20have%20reached%20a%20limit,within%201%20to%2024%20hours.

May be this should help

**Comment by tananaev** [comment]
I think you should re-read this thread because nobody but you is talking about gmail.

**Comment by enriqueillan** [comment]
I think you should be more objective with respect to the fact that in the documentation that I suppose you carry out you talk about SMTP specifically for Gmail.

https://www.traccar.org/gmail/

 It is more than clear that the current thread talks about another type of implementation to send emails. If you want to tangentially deviate from something that is an obvious requirement, that's up to you. But it is more than obvious that Gmail is not a suitable mechanism to send emails.

In any case, you want to avoid that Gmail is not an adequate mechanism for the massive use of emails and tools like sendgrid come to help in this aspect is something that is quite evident.

**Comment by tananaev** [comment]
Gmail is completely adequate for a small deployment, like a personal tracking or a business with a small fleet of vehicles. Small deployments is a vast majority of Traccar deployments, so it's completely reasonable to have a documentation targeting those use cases, especially because those people are usually less tech savvy.

Having said that, it is probably not a good option to use gmail for large deployments. But we never argued that it is. And this topic has absolutely nothing to do with gmail. And I have no idea why you keep talking about gmail here.
