### ISSUE TITLE
Device location isn't showing on the map on the initial signup.

### ISSUE THREAD

**Issue by methmal59** [traccar/traccar#4174]
First of all thanks a lot for this open source amazing software. 

I  made some customizations to your traccar native app. I added a signup using the traccar API which assigns a device to a user once he signs up. When a user enters the correct data and logs in for the first time and when he clicks on the devices menu, he can see the correct device he's assigned to with the correct device name. But when he clicks on that device, it's not shown in the map. 

But when he logs out and logs in again, and clicks on the device, it works perfectly as expected.

Simply, the user can see the device in the devices tab when he first signs up, but the device marker is not showing in the map. But when he logs out and logs in again, the marker works perfectly.
Any reason for this? TIA

**Comment by tananaev** [comment]
Please record a video showing the problem.
