### ISSUE TITLE
Make Device with persistent connection

### ISSUE THREAD

**Issue by meneva** [traccar/traccar#4175]
Hello,
I am using Websocket api provided by Traccar to show my devices in the map.
if the status of any device goes to "Unknown", it is totally disappeared from the map.
**my question is:** Is there any way to show it to the map even it is disconnected from the server?
i want the device to show in the map with last known location if it is disconnected.

thanks in advance

**Comment by tananaev** [comment]
Not sure what you mean. If you are using API, it's up to you to show it. You always receive last known location.
