### ISSUE TITLE
doubts

### ISSUE THREAD

**Issue by balag05** [traccar/traccar#4182]

**Comment by balag05** [comment]
Hi sir,i am new to this traccar sw.i have some doubts.

1.Is there is any possibility to develope this application in java spring framework.

2.Possible means,i like to go through traccar master or traccar web interface

**Comment by tsmgeek** [comment]
What are your reasonings to do this?
The project works well and spring would only be more overhead for what is needed currently.

Ps. One of my devs is always talking about micronaut as a great Rest api framework and kotlin.
