### ISSUE TITLE
TK103 Protocol Update

### ISSUE THREAD

**Issue by GPSIndia** [traccar/traccar#4187]
The tk103 protocol working on 5002 port is having certain issues. We are herewith providing updated protocol document for the same.

Kindly process the same.
[Tracker Communication Protocol V1.5.3.pdf](https://github.com/traccar/traccar/files/2743931/Tracker.Communication.Protocol.V1.5.3.pdf)

**Comment by tananaev** [comment]
Let me know if it's still an issue.
