### ISSUE TITLE
traccar.run assumes systemd

### ISSUE THREAD

**Issue by earies** [traccar/traccar#4196]
While the instructions at https://www.traccar.org/linux/ convey this is tested on Ubuntu and should work w/ most distros, it would be best to not assume systemd is mandatory on a given distro from the installer

```bash
$ sudo ./traccar.run 
Creating directory out
Verifying archive integrity...  100%   All good.
Uncompressing traccar  100%  
mv: cannot move '/opt/traccar/traccar.service' to '/etc/systemd/system': No such file or directory
chmod: cannot access '/etc/systemd/system/traccar.service': No such file or directory
./setup.sh: line 10: systemctl: command not found
./setup.sh: line 11: systemctl: command not found
```

While traccar will still function, there are plenty of distributions that are not using systemd and likely never may for a variety of reasons

**Comment by oliv3** [comment]
From what I know, running Traccar on *BSD systems right now is somewhat tricky.

**Comment by oliv3** [comment]
Apart from porting from source, obviously

**Comment by tananaev** [comment]
For the case when systemd is not available we provide manual installation package. You are also welcome to contribute a solution that would work on distros that don't have systemd.

**Comment by earies** [comment]
Thx @tananaev - I didn't see the manual package initially - This will work for my purpose.  Will take a look at the installer logic for wider support from this regard

In the meantime, might I propose changing the wording for 'Linux 64' in:
https://www.traccar.org/download/
https://www.traccar.org/linux/

To reflect Linux x86_64 (w/ systemd)
