### ISSUE TITLE
Server wide computed attributes and user permission issue

### ISSUE THREAD

**Issue by charliewillemson** [traccar/traccar#4197]
Hi Traccar people!

Can you please give me short overview how to manage few things on my traccar server.

I would like to add computed attributes to all devices added to server. At the moment it seems to be bit complicated because when admin adds new computed attribute then each user must enable that to each device he sees on the device list. 
Another issue is that user must have right permissions to make changes on device. When user is "device readonly" then he can not link created geofences or computed attributes to device, funny thing is that user can create geofence but can not link that to device (device readonly permission).

**Comment by tananaev** [comment]
You can have a global group with all devices and link computed attributes to that group.

As for permissions, it works as expected, as far as I can tell.
