### ISSUE TITLE
Protocol tk103 not extracting temperature data

### ISSUE THREAD

**Issue by josuelmm** [traccar/traccar#4200]
Good day, it is possible to obtain the temperature from a device that has the tk103 protocol

According to the documentation, it must be like this:
<img src="https://i.imgur.com/qYy4x6p.png">

What should I do to get the temperature value?

**Comment by tananaev** [comment]
It's already supported, as far as I know.

**Comment by josuelmm** [comment]
Into the status no exist the parameter

**Comment by tananaev** [comment]
Send HEX sample from logs.

**Comment by josuelmm** [comment]
2019-02-13 00:02:44  INFO: [b00919f4: 5002 < 132.251.1.69] HEX: 283039343632353932383030304252303031393032313341313135362e303433315330373730352e36313435573030302e3030303032333532312e34303030303030303030374c30303030303331345431313329
2019-02-13 00:02:44  INFO: [b00919f4] id: 094625928000, time: 2019-02-13 00:02:35, lat: -11.93405, lon: -77.09358, course: 21.4

**Comment by josuelmm** [comment]
<img src="https://i.imgur.com/Q0tK6K0.png">

**Comment by josuelmm** [comment]
This Value HEX 283039343632353932383030304252303031393032313341313135362e303433315330373730352e36313435573030302e3030303032333532312e34303030303030303030374c30303030303331345431313329 return

(094625928000BR00190213A1156.0431S07705.6145W000.000023521.40000000007L00000314T113)

**Comment by tananaev** [comment]
OK, looks like this format for temperature is not supported yet.

**Comment by josuelmm** [comment]
Mmm ok that is to say, that this protocol at the moment does not obtain the temperature in Traccar.

**Comment by josuelmm** [comment]
Where can I do the respective modification to make this part work in that protocol?

**Comment by tananaev** [comment]
In the protocol decoder class.

**Comment by tananaev** [comment]
Feel free to send a pull request.
