### ISSUE TITLE
Q50 watch wrong data

### ISSUE THREAD

**Issue by rapstar2004** [traccar/traccar#4202]
Hello Anton,
i installed the traccar and connected q50 watch. but there is a problem about incoming data. its from logs,
```
ff41515348002b01000000895a95df5825f7cc85dcdda93dfd9fa57c41885840d8ff4e754acd58a4ea52585c49fb0e1c
```
hext to text
```
... some binary data ...
```

normally i have to see 
how can resolve it i guess there is problem about decode

**Comment by tananaev** [comment]
Obviously it's a binary protocol, so there is no point in trying to convert it to text. It's not possible. You would need to get protocol documentation from your device vendor.

**Comment by tananaev** [comment]
It's not the same. Clearly your device is sending binary data, so it's different protocol.

**Comment by pzuk** [comment]
I noticed some devices send encrypted data, sample buffer can start from "�AQSH\u0000+\u0001\u0000\u0000\u0000O���I�\\�i�����,H\u0005���\u0007�?�8�sq�" instead of classic "[3G*000000.....]". I have no idea how to decode it, maybe someone from this group can suggest?

**Comment by tananaev** [comment]
@pzuk please don't spam everywhere with your question. Without protocol documentation we won't be able to do anything about it.

**Comment by pzuk** [comment]
Sorry, i placeed my question in 3 places only with hope that someone faced
such issue already and there is a common way to decode it.

**Comment by techminded** [comment]
@pzuk due to security concerns a lot of the Mediatek type Chinese GPS watches have had their firmware updated to encrypt data going from watch to server. As far as I know, it now uses AES-128 or AES-256 encryption and the key is buried away somewhere in the device. The first byte is always "FF" followed by "AQSH" and then some other data before the payload. The last byte is a checksum and something like the 4 bytes before that is a timestamp. To answer your question though, there is no way to decode this without the key which is not freely available. If this level of security isn't a concern for you, you could possibly revert back to a previous version of the firmware.

**Comment by lesensei** [comment]
@techminded thanks for this insight ! I'm facing this very problem. Do you know where one might find firmware files in order to downgrade  a Q50 watch ? I know this is old stuff, but I just bought one with the intent of tracking it with traccar, only to face this issue now :-(

**Comment by mikeotech** [comment]
@lesensei you could try the below... no idea if this firmware  will still work. 
Note: when I clicked this link, my virus checker complained... even though I doubt this file contains a virus of any kind, thread carefully.

http://www.3g-elec.com/updata/ceshi/ycsj/20170207/jt_ads.bin

**Comment by lesensei** [comment]
I'm happy to report this firmware makes it work again :-) Thanks @mikeotech and @tananaev !

**Comment by boytunp** [comment]
Can you guys please give a hint on  how to downgrade this firmware? @mikeotech @lesensei

**Comment by lesensei** [comment]
When connected to a computer, the watch should be seen as a USB ass storage device. Find the original "jt_ads.bin" file, back it up, and then replace it on the watch with the firmware linked to by @mikeotech . Unmount the watch ("eject" under Windows) and you should be good to go.

**Comment by XanderF** [comment]
I would like to use the jt_ads.bin firmware. But when I connect the Q50 watch to a Windows PC or a Mac via USB it's not shown as a USB mass storage device. Is there a solution for that?

**Comment by lesensei** [comment]
I've sometimes had difficulty with that myself. The connector on the watch is not of the best quality. Try using another USB cable and fiddling with the connection.

**Comment by XanderF** [comment]
> I've sometimes had difficulty with that myself. The connector on the watch is not of the best quality. Try using another USB cable and fiddling with the connection.

Thank you @lesensei, your reply made me try it once more. And with success! Used the firmware from an earlier reply and now the gps tracker works with Traccar.

A hint for noobs like me :) turn the device off before connecting it to your pc via USB. It won't work if the device is powered on.

**Comment by lzkill** [comment]
@XanderF, could you send me the working firmware? I've tried the one linked by @mikeotech, but it breaks my q50 watch. It makes the watch boot up into the sound recorder, it then keeps recording until the battery dies.

**Comment by hoanglongutc** [comment]
> Tôi vui mừng thông báo phần sụn này giúp nó hoạt động trở lại :-) Cảm ơn@mikeotechVà@tananaev!

Can you describe more clearly the steps to configure the Q50 watch to connect to Traccar? Thanks

**Comment by hoanglongutc** [comment]
> I'm happy to report this firmware makes it work again :-) Thanks @mikeotech and @tananaev !

Can you describe more clearly the steps to configure the Q50 watch to connect to Traccar? Thanks

**Comment by XanderF** [comment]
> @lesensei
> 
> > I'm happy to report this firmware makes it work again :-) Thanks @mikeotech and @tananaev !
> 
> Can you describe more clearly the steps to configure the Q50 watch to connect to Traccar? Thanks
It is added just like any other device in Traccar, see the documentation for details. If you have a specific problem, plz describe and I'll try to help.

**Comment by hoanglongutc** [comment]
> > Can you describe more clearly the steps to configure the Q50 watch to connect to Traccar? Thanks
> 
> It is added just like any other device in Traccar, see the documentation for details. If you have a specific problem, plz describe and I'll try to help.

Thank you for your feedback, Can you send me the link to buy the Q50 watch?
I want to refer to the information before buying and using

**Comment by tananaev** [comment]
Please use the forum for general questions.
