### ISSUE TITLE
Feature Request: SSO Support

### ISSUE THREAD

**Issue by victorferreira** [traccar/traccar#4207]
It would be great if Traccar had support for Single Sign-On. This feature would allow Traccar to be easily integrated with others services. I've been looking into [Keycloak](https://www.keycloak.org) and seams like a great open source option for a self-hosted SSO and a good fit to be integrated into Traccar. I wonder how much work would take implement support for something like this. 

@tananaev do you have any recommendation on how to approach an integration like this?

**Comment by tananaev** [comment]
It would be nice to have something that can be directly integrated into Traccar, not a standalone server.

**Comment by victorferreira** [comment]
Just like there's third-party integrations for geocoding and map layer, it's possible to have more than one option. An implementation like this would be optional and additional to the system in place. For example, I could add the config bellow and point the authentication process to another service.

```
<entry key='auth.enabled'>true</entry>
<entry key='auth.service'>Keycloak</entry>
<entry key='auth.url'>https://auth.example.com</entry>
<entry key='auth.key'>h7vVHhjvlJVY8</entry>
```

In this case the end user could use the login and password they already. Also, having a standalone server would help build a micro-service architecture, instead of having everything inside Traccar. Complementary services like billing, support, etc... could easily integrated sharing the same credentials for the user.

**Comment by tananaev** [comment]
I don't agree with your opinion. If it's a relatively small module and can be integrated directly, I don't see why we would want third party service.

As for micro-service architecture, it doesn't make sense for our case.

**Comment by tsmgeek** [comment]
Keycloak is a good product that I use, but its just a oauth/saml provider so you would not intregate it directly into Traccar but instead build support for oauth and this can be done using the Traccar java libs, then you are free to use any other service you wish.
Basic idea but the actual implementation may be more complicated as you may want to accept additional roles and attributes to be passed ie admin/read only/TZ etc.

**Comment by mxplusb** [comment]
I would love to have OAuth2/OIDC support built into Traccar, but I agree with @tananaev, it should be an integration, not something bundled.

**Comment by mrabbah** [comment]
Hello, having the possibility to interface with a external OAuth2/OpenID Connect solution for SSO is interesting, because most company now have already their own Identity Access Management System, like Keycloak, Okta..., and all authorization and authentication are managed in those systems. The embedded SSO solution will be a nice to have, but does not answer to the need of most company.

**Comment by Jafner** [comment]
I would love to see some activity on this. SSO support (LDAP, SAML, or OAuth2) is a requirement for every (production) enterprise environment I've worked with.

**Comment by SebastEnn** [comment]
SSO support was added in [5.7](https://www.traccar.org/blog/traccar-5-7/).

This issue can be closed.
