### ISSUE TITLE
Traccar phoning home by default is not enough documented

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar#4208]
Following https://github.com/traccar/traccar/issues/4066, now `server.statistics` is mentioned in the [configuration file](https://www.traccar.org/configuration-file/). Still is undocumented what is sent:

```json
{
"version":"4.2-SNAPSHOT",
"captureTime":"2019-01-30T00:00:51.699Z",
"activeUsers":"1",
"activeDevices":"0",
"requests":"14",
"messagesReceived":"0",
"messagesStored":"0",
"mailSent":"0",
"smsSent":"0",
"geocoderRequests":"0",
"geolocationRequests":"0"
}
```

In my case, I would expect geocoderRequests to be > 0.

Can you please document more on this ?

**Comment by tananaev** [comment]
I think most fields are pretty self-explanatory. Anything specific you want to be documented?

**Comment by oliv3** [comment]
* requests
* messagesReceived
* messagesStored

In my case, same as geocoderRequests, mailSent should be > 0.
What is geolocationRequests ?

**Comment by tananaev** [comment]
- requests - API requests
- messagesReceived - number of received messages from devices
- messagesStored - number of stored messages (positions)

If you get zeroes, it likely means that you have restarted service in which case data is lost.

Geolocation is cell and wifi based location requests. We use term geolocation in many places in the official documentation and configuration.

**Comment by oliv3** [comment]
Ok, thanks.
