### ISSUE TITLE
Forward URL - include the traccar positions table id in the data forwarded

### ISSUE THREAD

**Issue by jedjones-uk** [traccar/traccar#4210]
Is it possible to include the position ID in the data forwarded by traccar? I know that the Handler comes before the data is written into the database, but I am unsure of what code changes need to be made to the handler if we make it part of the Outbound stack of handlers.

Can we simply extended it from the ChannelOutboundHandlerAdapter class, or will that interfere with the MainEventHandler Class?

**Comment by tananaev** [comment]
You can probably just re-order handlers in pipeline.
