### ISSUE TITLE
Problem with TRV protocol modified by the manufacturer

### ISSUE THREAD

**Issue by jycemea** [traccar/traccar#4212]
Anton, 
regarding the ticket #4209 you closed 2 days ago and where you asked me to realise some tests I already did ; I'm still in trouble with the standard TRV protocol in Traccar

It is actually possible to link my watch to Traccar (port 5010), ... but impossible to get positions. I'm always located in latitude 0, longitude 0, whatever if I'm moving or not (and I did some tests during the 2 last days...).

Studying the diferences between the sandard TRV protocol and the modified TRV protocol the "manufacturer" gave me, I think I identified the issue... The manufacturer did some modifications on the orginal one ... It is probably nothing but I don't know how to modified your TRV protocol... directly inside Traccar. Do I have to compil a new version of Traccar to include the watch protocol ? If yes... I don't know how to write it correctly... I did not find any tutos for this...

With the Androïd  app delivered by the chineese manufacturer, everything is running fine, positionning is ok, heartbeat, blodd pressure, alarms... but they won't deliver me any way to run outside of this app... except if I'm buying 500 units :))) 

Here is a copy of :
- my tracker-server.log
- watch manufacturer protocol
- pic of my null position in Traccar.

Could you help me to solve this troubles?
Thanks.

[tracker-server.log](https://github.com/traccar/traccar/files/2824665/tracker-server.log)
[H12 Communication Protocol.pdf](https://github.com/traccar/traccar/files/2824666/H12.Communication.Protocol.pdf)
![scennshot_2019-02-02 19-39-37](https://user-images.githubusercontent.com/19631789/52167341-5f22d380-2722-11e9-8f0f-359915731f01.png)

**Comment by jycemea** [comment]
You are right. It does not report in Traccar but it does in their App (ambercare). I can send you some pics, if you need...

Maybe you already met the same problem with the TRV protocol ?... Just have a look at https://www.traccar.org/forums/topic/istartek-vt202/

Inside, it seems you are speaking about a request to send to the device... Is it possible... and how to write it?

**Comment by tananaev** [comment]
I don't have any more information than I provided in that forum thread.
