### ISSUE TITLE
Feature Request: Serving all css, js aso. from the Web Interface Domain, not using CDN

### ISSUE THREAD

**Issue by vsatmydynipnet** [traccar/traccar#4215]
Good Morning,

it would be really cool if the traccar server would be able to server all scripts, css, aso, without using a CDN like cloudflar or jsdelivr.net. It is not only because of tracking by 3rd paty, it is also a problem if the server opens only the ports for the devices to report to the public and https is avalaible only from an isolated net. if this net has no access to the CDN because of firewall rules, the web interface will not work.

Tank you for your gret work!

**Comment by tananaev** [comment]
We no longer use CDN. Pretty much everything should be local now. The only exception is fonts for the map.
