### ISSUE TITLE
Update 4.3: server not starting on windows

### ISSUE THREAD

**Issue by HaniTetouha** [traccar/traccar#4217]
Hello,

After updating server 4.2 to 4.3 the server will not start, tried to start it manually from the command line using the default executable parameters from the windows Service console it returns the following 

```
.\java -Duser.dir="C:\Program Files\Traccar\tracker-server.jar" -jar "C:\Program Files\Traccar" --service ".\conf\traccar.xml"
Error: Could not find or load main class .dir=C:\Program Files\Traccar\tracker-server.jar
Caused by: java.lang.ClassNotFoundException: /dir=C:\Program Files\Traccar\tracker-server/jar
```

**Comment by tananaev** [comment]
The issue is fixed and release has been updated. Please re-download.
