### ISSUE TITLE
Traccar stops loggin OsmAnd positions after some time

### ISSUE THREAD

**Issue by oliv3** [traccar/traccar#4218]
On versions >= 4.1, server stops logging positions sent by devices using the OsmAnd protocol after some time:

```
2019-02-08 16:14:46  INFO: [0a3e4ae8] connected
2019-02-08 16:14:46  INFO: [0a3e4ae8: 5055 < 172.19.0.11] HEX: 504f535...0d0a0d0a
2019-02-08 16:14:46  INFO: [0a3e4ae8: 5055 > 172.19.0.11] HEX: 485454502f312e3120323030204f4b0d0a636f6e74656e742d6c656e6774683a20300d0a0d0a
2019-02-08 16:14:46  INFO: [0a3e4ae8] disconnected
```
Please note that there are no log message about the position, whereas a device using TK102 protocol is correctly logged:
```
2019-02-08 16:15:05  INFO: [6c874b4f: 5006 < 37.164.255.173] HEX: 31393...0a0d
2019-02-08 16:15:05  INFO: [6c874b4f] id: 862117021654396, time: 2019-02-08 16:12:48, lat: 49.27488, lon: -0.25897, speed: 3.0, course: 231.4
```
All HEX messages coming from Android devices are correct.
Emptying the TC_POSITIONS table does not help: TK102 devices are logged, OsmAnd devices are **not** logged.

**Comment by oliv3** [comment]
Also:
* Positions are correctly forwarded for TK102, **not** OsmAnd.
* Querying TC_POSITIONS shows inserts for TK102, **not** OsmAnd.

**Comment by oliv3** [comment]
Of course, positions on the map are **not** updated anymore.

**Comment by tananaev** [comment]
Are you using any third party services (geolocation, geocoding etc)?

**Comment by oliv3** [comment]
Geocoding, yes. Turned it off and now it works. Thing is, there is no problem with the service itself,
I'm way under quota, and querying the service from the server's ip works.

**Comment by oliv3** [comment]
Also, sending Dalvik/1.0 as user agent works. IIRC that's how traccar announces itself.

**Comment by oliv3** [comment]
With geocoding on and
```xml
<entry key='geocoder.onRequest'>false</entry>
```
positions are updated and geocoding works for the TK102 device, **not** the OsmAnd one.

**Comment by oliv3** [comment]
Also, selecting the OsmAnd device displays the "Show address" link, selecting the TK102 device displays the address.

**Comment by tananaev** [comment]
Have you tested latest Traccar server with latest Traccar Client app? I have just tried and everything works fine. I would need steps to reproduce the issue to investigate it further.

**Comment by oliv3** [comment]
* Traccar Server 4.2 (docker), 4.3 doesn't work (at least, the docker image):
![screenshot_2019-02-08_21-09-09](https://user-images.githubusercontent.com/84910/52503541-297c5f80-2be6-11e9-86b4-0133ba4a54db.png)
* Traccar Client 4.18. Sends position every 30s
* Along is a TK102 device

Relevant part of the config:
```xml
    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>ban</entry>
    <entry key='geocoder.format'>%f</entry>
    <entry key='geocoder.onRequest'>false</entry>
```

**Comment by oliv3** [comment]
So, after more testing:
* Only TK102 positions make it into the database (`SELECT * FROM TC_POSITIONS` only shows '`xexun`' data in the `PROTOCOL` column, no '`osmand`')
* Traccar Client reports location updates without errors, those appear in the server log, still without id/lat/lon/speed/course along, when TK102 updates do
* Both devices show as green in the interface
* Selecting the TK102 device displays the correct address
* Selecting the Android device displays the "Show address" link. Clicking the link displays the correct address
* "Last update" time for both devices is OK

**Comment by tananaev** [comment]
The issue is clearly somewhere in decoder or decoder handler.

**Comment by oliv3** [comment]
Do you mean OsmAnd protocol decoder ? It must have been battleground-tested...

**Comment by tananaev** [comment]
Sorry, I meant "geocoder", not decoder.

**Comment by oliv3** [comment]
I don't see why geocoding would work fine for TK102 **all the time**, and also for OsmAnd, then stop working for this protocol after some time.

**Comment by tananaev** [comment]
Don't know either, but you said it works without geocoding, right?

**Comment by oliv3** [comment]
It works without geocoding for devices using OsmAnd protocol.
It works with geocoding, for devices using other protocols.

**Comment by oliv3** [comment]
Now I think I found it: Traccar server doesn't seem to like the OsmAnd protocol being reverse-proxied by a web server doing SSL termination.

Usual configuration for the client is to hit a URL like: `http://example.com:5055` (which is totally insecure).
Adding a web server upstream that acts as a reverse-proxy doing SSL termination, URL now looks like: `https://osmand.example.com`.

In the first case (direct access), everything works as expected. In the latter, it doesn't.

Here are the two requests (HEX-decoded) sent by the client:

1. using direct access:
```
POST /?id=XXXX&timestamp=1549666641&lat=49.2734912&lon=-0.2601572&speed=0.0&bearing=0.0&altitude=61.0&accuracy=22.511999130249023&batt=81.0 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: Dalvik/2.1.0 (Linux; U; Android 8.0.0; F5321 Build/34.4.A.2.118)
Host: example.com:5055
Connection: Keep-Alive
Accept-Encoding: gzip
Content-Length: 0
```
2. behind a proxy:
```
POST /?id=XXXX&timestamp=1549664041&lat=49.2734938&lon=-0.2602435&speed=0.0&bearing=0.0&altitude=0.0&accuracy=13.043999671936035&batt=80.0 HTTP/1.1
Host: osmand.example.com
Connection: close
X-Real-IP: aa.bb.cc.dd
X-Forwarded-For: aa.bb.cc.dd
X-Forwarded-Proto: https
X-Forwarded-Ssl: on
X-Forwarded-Port: 443
Content-Length: 0
Content-Type: application/x-www-form-urlencoded
User-Agent: Dalvik/2.1.0 (Linux; U; Android 8.0.0; F5321 Build/34.4.A.2.118)
Accept-Encoding: gzip
```
The obvious difference is in the `Connection:` HTTP header (first case - Keep-Alive, second case - close).
So, I'd say the `Connection: close` header is not gracefully handled.

**Comment by tananaev** [comment]
What is not handled correctly and on which side. It sounds to me like the issue is with the proxy.

**Comment by oliv3** [comment]
It's not handled correctly server-side. It's perfectly legal to send a `Connection: close` header when using HTTP/1.1.

**Comment by tananaev** [comment]
OK, but what exactly is not handled correctly? What makes you think it's causing the issue?

**Comment by oliv3** [comment]
Because it works when the client sends `Connection: Keep-Alive`, and doesn't when it sends `Connection: close` ?
That's the only difference I see between the two requests. All other `X-` headers are not to be suspected.

**Comment by oliv3** [comment]
If you're asking me where the bug is server-side, then I have no idea.

**Comment by tananaev** [comment]
It can be anything else. Not sure why you are so confident it's this specific header, or why is it even related to the request itself. Your original log shows that connection is closed, so it looks correct to me.

**Comment by oliv3** [comment]
What can be "anything else", then ?

**Comment by tananaev** [comment]
Have no idea, but without being able to reproduce it, I don't think I can do anything.

**Comment by oliv3** [comment]
Well, you could at least try to do what I do. That is, having a reverse proxy in front of port 5055 ?

**Comment by oliv3** [comment]
Also, can you admit that this is **not** a geocoder issue ?
As I said, it works fine with devices that have **direct** TCP connections to the serveur.

**Comment by tananaev** [comment]
Just tested with reverse proxy and works fine as well.

**Comment by oliv3** [comment]
Which web server did you use ?

**Comment by oliv3** [comment]
Also, can you share the HEX received by the server in this case ? That would help, thanks.

**Comment by tananaev** [comment]
Tested on Jetty and Apache proxy servers. Both show very similar result:
```
POST /?id=1&timestamp=1549776160&lat=0.0&lon=0.0&speed=0.0&bearing=0.0&altitude=-28.399999618530273&accuracy=16.027000427246094&batt=100.0 HTTP/1.1
Host: localhost:5055
Content-Type: application/x-www-form-urlencoded
User-Agent: Dalvik/2.1.0 (Linux; U; Android 9; Pixel 3 XL Build/PQ1A.190105.004)
Accept-Encoding: gzip
X-Forwarded-For: 1.1.1.1
X-Forwarded-Host: demoX.traccar.org
X-Forwarded-Server: demoX.traccar.org
Connection: Keep-Alive
Content-Length: 0
```

**Comment by oliv3** [comment]
1. Are they SSL-enabled ?
2. Did you try with the `ban` geocoder ?

**Comment by tananaev** [comment]
1. Apache was SSL.
2. No, I haven't.

**Comment by oliv3** [comment]
For 2., can you check since you were suspecting a geocoder issue ?
For 1., even if I see no reason for proxying to fail, upstream has a combination of Nginx (doing SSL termination), chained with HAProxy for port 5055.

Still, I see no reason why in the logs, device connects properly, sends a valid request, gets an OK response, and appears as disconnected, while no logs of id/lat/lon/bearing/etc show up.
They do when accessed directly with plain HTTP on 5055 port.

**Comment by tananaev** [comment]
I think I know what the issue is. Because connection is closed, the message is not delivered through the pipeline. It happens only with geocoding enabled because geocoding introduces some delay.

**Comment by oliv3** [comment]
That's good news. Any plans ?

**Comment by tananaev** [comment]
Not really sure how to fix it, so there is no immediate plan.

**Comment by vudinhtu** [comment]
I got this issue also when I develop a new Protocol which is the same OsmAnd and run on RaspberryPi. I think we can remove geocoderHandler in BasePipelineFactory.java. After that, we create new thread for updating address for location like Geocoder does.
Is there any problem if we do like this?

**Comment by oliv3** [comment]
In a near future, Android will enforce secure connections (https://android-developers.googleblog.com/2018/04/protecting-users-with-tls-by-default-in.html).
Hence, Traccar client won't be able to send clear-text traffic on port 5055 anymore.
Since Traccar server can't handle SSL, most of the security-aware admins run it behind a SSL proxy (at least, for the web interface for now)
But when it will come to securing connections between Traccar Client and Server, I suggest this issue to be urgently addressed.

**Comment by tsmgeek** [comment]
@oliv3 
slap traefik on the front of Traccar Server, support LE certs and easy to setup, ive setup httpd proxy_pass due to already having it on my machine but on standalone I would have used traefik.

**Comment by oliv3** [comment]
@tsmgeek, there is no issue with Traccar server sitting behind a proxy.
The issue here is reverse proxying port 5055.
In short, instead of using `http://example.org:5055`, the client uses `https://example.org/client`, which does SSL termination and proxy pass to port 5055.
And this is where it breaks. Also, customer uses nginx and not traefik.

**Comment by tsmgeek** [comment]
You can setup traefik on 5055 and bypass nginx altogether.

Have you tried to setup nginx to keep the connection open longer?
https://stackoverflow.com/questions/46771389/why-does-nginx-proxy-pass-close-my-connection

@tananaev 
Is there anyway to respond instantly that it has accepted a formatted packet, push to a queue which then processes them in the background?

**Comment by tananaev** [comment]
Actually the problem is the opposite. We should wait instead of replying instantly, which is what we are doing now. It messes up with Netty pipeline.

**Comment by oliv3** [comment]
Does "we" have an idea how to fix this ?

**Comment by oliv3** [comment]
@tananaev Any news on this ?

**Comment by oliv3** [comment]
@tananaev Ok, if you have no plans to fix this, customer wants to off-load the geocoding process, since Traccar can't handle this when sitting behind a reverse-proxy.
Question is, regarding OsmAnd, if we do geocoding upstream and then pass the URL as `...&address=[some_address]`, will this end up in the database correctly, as I the server managed to do the job ?

**Comment by fabricioadorno** [comment]
> You can setup traefik on 5055 and bypass nginx altogether.
> 
> Have you tried to setup nginx to keep the connection open longer?
> https://stackoverflow.com/questions/46771389/why-does-nginx-proxy-pass-close-my-connection
> 
> @tananaev
> Is there anyway to respond instantly that it has accepted a formatted packet, push to a queue which then processes them in the background?

I had same issue. Configuring nginx to keep connection open longer worked for me, just like @tsmgeek suggested from stackoverflow.

**Comment by mcypy** [comment]
@oliv3
Did you manage to fix the issue of Osmand protocol not updating the device location?I have the same issue with a home made GPS tracker.Thanks

**Comment by jcardus** [comment]
I have this problem, for some reason, sometimes the pipeline is empty when referenced by the geocoding callback, so the call to "fireChannelRead" does nothing...

I added this:

`if (ctx.pipeline().toMap().isEmpty()) {
                            LOGGER.warn("empty pipeline on ...") 
}`

And I see a lot of it in the log, especially on osmand, but also on teltonikas. Teltonika is no so bad because I guess it doesn't send the ack to the device, so it's retried.
