### ISSUE TITLE
Feature Request: Location to store sim card ICCID on vehicle

### ISSUE THREAD

**Issue by pc500** [traccar/traccar#4219]
Any chance we can add a dedicated field for ICCID so I can get rid of a separate spreadsheet I have doing this?

I put it under "Contact" which seems to work ok, but it'd be great to have a dedicated ICCID field.

![image](https://user-images.githubusercontent.com/33823824/52524877-c8d93b00-2c56-11e9-8678-ab9b73d34e4d.png)

**Comment by pc500** [comment]
Any chance we can add a dedicated field for ICCID so I can get rid of a separate spreadsheet I have doing this?

I put it under "Contact" which seems to work ok, but it'd be great to have a dedicated ICCID field.

![image](https://user-images.githubusercontent.com/33823824/52524877-c8d93b00-2c56-11e9-8678-ab9b73d34e4d.png)

**Comment by tananaev** [comment]
You can use attributes.
