### ISSUE TITLE
Feature request: Filter positions in the past similar to filter.future

### ISSUE THREAD

**Issue by pc500** [traccar/traccar#4220]
Currently, there is a feature to filter in the future:
```xml
<entry key='filter.enable'>true</entry>
<entry key='filter.future'>86400</entry>
```
Could we also get a an option to filter in the past?
Sometimes my tracker reports stuff from 1999.

**Comment by tananaev** [comment]
Why do you care about data in the past? It doesn't interfere with reports or live status.

**Comment by pc500** [comment]
Is Traccar doing nothing with it other than putting it in the positions table?  If so, we can just ignore it.

**Comment by tananaev** [comment]
Closing as it doesn't really affect any functionality.
