### ISSUE TITLE
Cycle in group hierarchy - IllegalArgumentException 

### ISSUE THREAD

**Issue by kirantpatil** [traccar/traccar#4222]
Hi,

We are experiencing this issue and we are on latest version (4.3) of traccar.

Steps to reproduce:
------------------------
1) create the "group_1" group using API 
2) Edit the group "group_1"  using API

Expected result:
--------------------
group "group_1" should succeed with edit

Actual result:
----------------
response:- `Cycle in group hierarchy - IllegalArgumentException (GroupsManager:46 < *:83 < *:29 < BaseObjectResource:127 < ...)`

Screenshot:
--------------
Once I get this error then, it is not allowing me to create, edit or delete the group from API side and even from a web interface side. 

Below error, I'm getting when I'm trying to create a group using a web interface 

![group_issue](https://user-images.githubusercontent.com/1178055/52647473-c9016100-2f0a-11e9-88d4-b3ba80df4695.png)

Edit:
You can login and check at http://13.127.55.238:8082/ using admin/admin.

**Comment by tananaev** [comment]
Please provide API request.

**Comment by kirantpatil** [comment]
1) created the group using API
{
    "name": "mini",
    "attributes": {
        "cost_per_km": 8,
        "start": "17.0",
        "end": "18.3",
        "peak_cost": 1,
        "base_km": 2,
        "base_fare": 35,
        "ride_time_fare": 0.6,
        "wait_time_fare": 0.3,
        "cancellation": 35,
        "tax": 8,
        "active": true
    }
}

status:- created successfully

2) trying to edit the same group using API 
{
    "id":7,
    "name": "mini",
    "attributes": {
        "cost_per_km": 8,
        "start": "17.0",
        "end": "18.3",
        "peak_cost": 1,
        "base_km": 2,
        "base_fare": 35,
        "ride_time_fare": 0.6,
        "wait_time_fare": 0.3,
        "cancellation": 35,
        "tax": 8,
        "active": true
    }
}

**Comment by tananaev** [comment]
Compare with what official web app sends. Are you making those requests from a web app? If yes, provide Chrome screenshot of the request in network console.

**Comment by kirantpatil** [comment]
From Api I am making those requests.

**Comment by kirantpatil** [comment]
Closing this for now, since we are unable to reproduce after once again clean install.
