### ISSUE TITLE
Battery level parameter always showing 100 traccar 4.3

### ISSUE THREAD

**Issue by kedarnathjimage** [traccar/traccar#4227]
Hi Anton,
Whenever I get low battery alarm battery level is 100. Is there any issue battery level parameter. In the previous traccar version, we get a separate battery parameter. In 4.3 version battery parameter is missing.
```json
{"sat":15,"ignition":false,"status":68,"charge":true,"blocked":false,"batteryLevel":100,"rssi":4,"alarm":"lowBattery","distance":0.0,"totalDistance":137288.65,"motion":false,"hours":124489000}
```
Thanks

**Comment by tananaev** [comment]
Show what you had in the previous version.

**Comment by kedarnathjimage** [comment]
{"status":5,"ignition":false,"charge":true,"blocked":false,"battery":6,"rssi":4,"distance":0.0,"totalDistance":113719.08,"motion":false}

**Comment by tananaev** [comment]
Is that GT06? Battery value 6 maps to 100% battery level, so everything is decoded correctly.
