### ISSUE TITLE
notifications are only sent to one user

### ISSUE THREAD

**Issue by flocsy** [traccar/traccar#4230]
I have a device that belongs to two users. They both see it on the map, but only one of them gets notifications.

user1 is admin, the device was created by it.
user2 is not admin (tried normal, read-only, device read-only). No matter what I tried it doesn't get the notifications.

**Comment by tananaev** [comment]
Have you tried debugging it?

**Comment by flocsy** [comment]
tried, but couldn't find the reason yet. I get to NotificationManager::updateEvent, then getEffectiveNotifications and then to SimpleObjectManager::getUserItems. For user2 this returns an empty Set
