### ISSUE TITLE
Data isn't receiving to the Server

### ISSUE THREAD

**Issue by kundansingh86** [traccar/traccar#4231]
Hi, I've been trying to create a TCP Listener for my GT06 based gps device. 

I've tested my listener through a TCP client and its working fine, but no data is been receiving on the TCP Listener from the device. I've also hosted this listener on a VPS.

I've checked that GPRS is enabled and device is sending data to another server and working fine there.

What could be the issue?

**Comment by tananaev** [comment]
How is this related to Traccar project?

**Comment by kundansingh86** [comment]
I know thia is not related to Traccar project directly but since traccar has the large community for GPS devices traking so wondering if I'll get some help from it.

**Comment by tananaev** [comment]
You can ask on Traccar forum. GitHub issues is only for bugs and feature requests for official Traccar project.
