### ISSUE TITLE
Special characters in user name

### ISSUE THREAD

**Issue by maximilianloy** [traccar/traccar#4234]
When creating a user with the name including special characters like **Ĕ** or **č** the following error is returned:

`Incorrect string value: '\xC4\x94\xC4\x8Di\xC4...' for column 'name' at row 1 - SQLException (... < QueryBuilder:480 < DataManager:458 < BaseObjectManager:90 < ...)`

Those are valid characters e.g. for Croatian names and the issue prevents users from signing up!

Happens with version 4.3 and older.

**Comment by tananaev** [comment]
That's a problem with your database collation.
