### ISSUE TITLE
REST gpx export generates ill-formed XML

### ISSUE THREAD

**Issue by alexanderzatko** [traccar/traccar#4237]
It seems the **xmlns** and **xmlns:xsi** attributes in the gpx element are not properly ended with quotation marks. As a result, all parsers I tried complain (for example gpsprune).

Traccar API exports xml like this:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance creator="Traccar" version="1.1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
```
....

Instead of:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" creator="Traccar" version="1.1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
```

**Comment by tananaev** [comment]
Just tried and I'm getting a valid format:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><gpx xmlns="http://www.topografix.com/GPX/1/1" creator="Traccar" version="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd"><trk>
<name>test</name><trkseg>
</trkseg></trk></gpx>
```

**Comment by alexanderzatko** [comment]
I guess it is fixed in the more recent version. I am running 4.2-SNAPSHOT.

**Comment by oliv3** [comment]
There must be a relevant commit @tananaev forgot to mention.

**Comment by tananaev** [comment]
There were no changes to it since it was implemented more than 2 years ago:

https://github.com/traccar/traccar/blob/master/src/org/traccar/web/GpxBuilder.java#L28-L32

**Comment by alexanderzatko** [comment]
fascinating. I unpacked the traccar jar and in the web directory in the GpxBuilder.class file see what @tananaev sees (note: I am not java programmer):

`<gpx xmlns="http://www.topografix.com/GPX/1/1" creator="Traccar" version="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">`

I tried to use another REST client app (Chrome extension) and it too returns the broken xml. hmm..

I will install the most recent version of the Server tomorrow and announce the result here.

**Comment by oliv3** [comment]
@alexanderzatko Great, there is never magic anywhere, I'm just eager to see/wondering where this bug could come from. Good luck in your investigations !

**Comment by alexanderzatko** [comment]
I installed Version: 4.3 and see the same problem. @tananaev if you want, I can send you the server URL and create a test user account for you on my system to see what's up.

I have a little theory about this. The GpxBuilder.class indeed spits out a well-formed document, but there is some other post-processing going on (the one that generates the REST response?) that modifies the xml before it is sent out.

**Comment by tananaev** [comment]
Please email me details to check.

**Comment by tananaev** [comment]
Tested with your details like this:
```
curl --header "Accept: application/gpx+xml" --user test@example.com:password "http://8.8.8.8:8082/api/positions?deviceId=21&from=2019-03-03T00:00:40.000Z&to=2019-03-03T23:00:40.000Z"
```
No issues:
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><gpx xmlns="http://www.topografix.com/GPX/1/1" creator="Traccar" version="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd"><trk>
<name>GPST-008</name><trkseg>
...
```

**Comment by alexanderzatko** [comment]
I installed a new version of OS this morning (MacOS 10.14) and re-tested using the same apps I used before the upgrade. Now the returned xmls are ok. go figure.
thanks for looking into this.
