### ISSUE TITLE
Marker Error

### ISSUE THREAD

**Issue by muzzammilhussain** [traccar/traccar#4238]
Dear Anton,

I have updated to traccar 4.3 and then I have enabled google maps and as well as added google maps key for reverse encoding. But still no car is showing marker
```
TypeError: i is undefined[Learn More]
RBush.js:113
TypeError: s.children is undefined[Learn More]
```
```xml
  <entry key='geocoder.enable'>true</entry>  
   <entry key='geocoder.key'>(Orignial Key added here)</entry>
<entry key='geocoder.type'>google</entry> 
```
Cars are showing address.

**Comment by muzzammilhussain** [comment]
I am getting these in console constantly
[Violation] 'click' handler took <N>ms
28[Violation] Forced reflow while executing JavaScript took <N>ms
[Violation] Forced reflow while executing JavaScript took 133ms
[Violation] Forced reflow while executing JavaScript took 126ms
[Violation] Forced reflow while executing JavaScript took 43ms
[Violation] Forced reflow while executing JavaScript took 142ms
[Violation] Forced reflow while executing JavaScript took 88ms
[Violation] Forced reflow while executing JavaScript took 40ms
[Violation] Forced reflow while executing JavaScript took 32ms
[Violation] Forced reflow while executing JavaScript took 47ms
[Violation] Forced reflow while executing JavaScript took 34ms
[Violation] Forced reflow while executing JavaScript took 32ms
[Violation] Forced reflow while executing JavaScript took 71ms
[Violation] Forced reflow while executing JavaScript took 137ms
[Violation] Forced reflow while executing JavaScript took 133ms
[Violation] Forced reflow while executing JavaScript took 169ms
[Violation] Forced reflow while executing JavaScript took 140ms
[Violation] Forced reflow while executing JavaScript took 40ms
[Violation] Forced reflow while executing JavaScript took 149ms
[Violation] Forced reflow while executing JavaScript took 133ms
[Violation] Forced reflow while executing JavaScript took 77ms
[Violation] Forced reflow while executing JavaScript took 125ms
[Violation] Forced reflow while executing JavaScript took 278ms
[Violation] Forced reflow while executing JavaScript took 39ms
[Violation] Forced reflow while executing JavaScript took 31ms
[Violation] Forced reflow while executing JavaScript took 46ms
[Violation] Forced reflow while executing JavaScript took 47ms
[Violation] Forced reflow while executing JavaScript took 46ms
[Violation] Forced reflow while executing JavaScript took 47ms
[Violation] Forced reflow while executing JavaScript took 45ms
app.min.js:190 [Violation] 'setInterval' handler took 78ms
app.min.js:286 [Violation] 'setInterval' handler took 84ms

**Comment by tananaev** [comment]
How is geocoding related to not showing marker? Can you please provide screenshot of the full stack trace.

**Comment by muzzammilhussain** [comment]
No it is not related . i just mentioned. 

![image](https://user-images.githubusercontent.com/39291256/53720010-74099880-3e81-11e9-8de6-b6b9eee8626e.png)

**Comment by tananaev** [comment]
You need to check all devices and make sure that coordinates are in the valid range.

**Comment by muzzammilhussain** [comment]
![image](https://user-images.githubusercontent.com/39291256/53720122-c6e35000-3e81-11e9-8eea-652cf152ed37.png)


I pasted Same Coords on Google map and it shows , location

**Comment by muzzammilhussain** [comment]
These are coords 
![image](https://user-images.githubusercontent.com/39291256/53720175-e5494b80-3e81-11e9-981d-8b004a9aca53.png)

**Comment by tananaev** [comment]
I'll repeat it again. You need to check **all devices** and make sure that coordinates are in the valid range.

**Comment by muzzammilhussain** [comment]
Ok Anton !

**Comment by muzzammilhussain** [comment]
Bundle of thanks 

![image](https://user-images.githubusercontent.com/39291256/53720356-60126680-3e82-11e9-80a9-eb0fc60350a6.png)

**Comment by tananaev** [comment]
Was it exactly what I said? Can we close the issue?

**Comment by muzzammilhussain** [comment]
There are some rouge Chinese devices which are targeting tracker servers. I just enabled anonymous device register. Which caused all this error

![image](https://user-images.githubusercontent.com/39291256/53720578-e7f87080-3e82-11e9-8459-b01924fc3559.png)
