### ISSUE TITLE
Get Map State causing Google Map to go blank

### ISSUE THREAD

**Issue by echostation25** [traccar/traccar#4240]
When you have Google Road/Satillite Map Layer set in Custom Map, and set a Get Map State (in Server Settings or Users), the map goes blank, only showing your trackers. 
This also happens when you remove Get Map State (set Latitude, Longitude, and Zoom back to 0)

To fix this after setting Get Map State: 
Either change Custom Map to another Google Map Layer or just select all/paste the same Google Map Layer back into Custom Map, save and reload the page. Only returns after doing this.

This only happens with the Google Map Layers so far. I tested all others in the link below with no issue.
https://www.traccar.org/map-layers/

**Comment by tananaev** [comment]
Please provide a screen recording.

**Comment by echostation25** [comment]
https://cl.ly/305639799fe7

Don't know if this is supposed to happen but the Google Map Layer changes to what is below.

https://mt0.google.com/vt/lyrs=m&amp;amp;hl=en&amp;amp;x={x}&amp;amp;y={y}&amp;amp;z={z}&amp;amp;s=Ga

**Comment by tananaev** [comment]
Looks like you are not using latest release.

**Comment by echostation25** [comment]
No. Was this issue fixed in the latest release or should I just update to see if it keeps happening?

**Comment by tananaev** [comment]
Yes, it was fixed. In future please always check on latest version before raising an issue.

**Comment by echostation25** [comment]
Oh. I am sorry about that. Thanks for your help.

**Comment by kapilepatel** [comment]
I have same issue, I believe I have latest 4.5 from https://www.traccar.org/download/ traccar-linux-64-4.5.zip and installed on DigitalOcean. 
When setting Map Layer as 'Custom Map' and 'POI Layer' as 'https://mt0.google.com/vt/lyrs=m&hl=en&x={x}&y={y}&z={z}&s=Ga' 
I see blank map with marker and this error in browser console: https://mt0.google.com/vt/lyrs=m&amp;hl=en&amp;x=%7Bx%7D&amp;y=%7By%7D&amp;z=%7Bz%7D&amp;s=Ga 400

**Comment by echostation25** [comment]
Under Bing Maps Key you will see Custom Map, paste  https://mt0.google.com/vt/lyrs=m&hl=en&x={x}&y={y}&z={z}&s=Ga  in there, save and reload page. Leave POI Layer blank.

**Comment by kapilepatel** [comment]
@echostation25 It worked when I logged in as Admin.

**Comment by echostation25** [comment]
Great. So did you do what I mentioned or it just works now?

**Comment by kapilepatel** [comment]
I followed your advice and it worked! thanks :)
https://github.com/traccar/traccar/issues/4240#issuecomment-493222201

**Comment by echostation25** [comment]
Very nice @kapilepatel. Happy to help. :)
