### ISSUE TITLE
v4.3 Geofence exit/enter

### ISSUE THREAD

**Issue by wolfbgn** [traccar/traccar#4242]
I have two Linux boxes. One is running Traccar 3.14 and the other one Traccar 4.3
Notifications for enter/exit geofence work like a charm on v3.14 but do not work on v.4.3
Should I make some additional adjustments to conf files to make them work on v4.3? 
Also problem with blank map when custom map is Google persist in v4.3

**Comment by tananaev** [comment]
There were no changes to geofencing for a long time, so most likely you misconfigured something.

As for Google Maps, have you set URL correctly?

**Comment by wolfbgn** [comment]
SMTP Configurations for the two instances of Traccar are the same.
Google Maps URL is correct. You get Google map and it shows in UI until you make some change to server. After that you have to delete Custom map URL, save changes  and paste it again to start working.

**Comment by tananaev** [comment]
It means that you are still not using version 4.3. Have you cleared the cache after upgrading?

**Comment by wolfbgn** [comment]
Both instances of Traccar are clean installs wuthout messing with your code or configurations.
The only conf is in traccar.xml foe smtp.

**Comment by tananaev** [comment]
You have to clear browser cache, if you upgraded from previous version recently.

**Comment by wolfbgn** [comment]
Yes sir, i know and I did that. Custom map disappearance is not a big issue if you do not make server changes often. I can not figure out why notifications for geofences don't work.
