### ISSUE TITLE
GT06 protocol based device always sent Login packet to server

### ISSUE THREAD

**Issue by achagu** [traccar/traccar#4245]
Hi,

I am using my own TCP based tracker server it is written in python. My problem is , Device is always send login packet to my server.

I tried sending response to login packet in below formats
response `787805010001d9dc0d0a`
response `0x787805010001D9DC0D0A`
Binary Data 
`1111000011110000000010100000001000000000000000111011001110111000000110100001010`
`responseByteStream bytearray(b'xx\x05\x01\x00\x01\xd9\xdc\r\n')`

I compared the hex strings which is sent by traccar and my server, both are same.
Can any one suggest me what is the correct format of response to login packet.

Thanks

**Comment by tananaev** [comment]
For general questions please use forum. GitHub is dedicated for issues specific to Traccar software.
