### ISSUE TITLE
Driver identification for Suntech and iButton

### ISSUE THREAD

**Issue by LucasBSC** [traccar/traccar#4250]
Hello,

I am trying to get the driver identification working on the platform with iButton gadget so I think I would need to configure it on the traccar.xml in order to save the driver id on the positions table in attributes column.
```
2019-02-27 23:59:34  INFO: [68ede89b: 5011 < 177.79.226.108] HEX: 53543330305354543b3930373133313037373b30343b3730363b32303139303232373b32333a35393a33343b63633731393b2d31322e3936333439303b2d3033382e3439393538373b3030302e3036373b3030302e30303b373b313b35373039353b31322e35303b3030303030303b313b303333373b3030303230373b302e303b313b303b30313245373137463031303030303b310d
```
```
ST300STT;907131077;04;706;20190227;23:59:34;cc719;-12.963490;-038.499587;000.067;000.00;7;1;57095;12.50;000000;1;0337;000207;0.0;1;0;012E717F010000;1
```

I think that somehow I would need to understand the following code below to save the incoming driver id string on the database. Does anyone have a direction how to do this config?

https://github.com/traccar/traccar/blob/e3e57a159842a97d6e0dff1b067cb241848b03da/src/org/traccar/protocol/SuntechProtocolDecoder.java#L319-L357

**Comment by Escalion** [comment]
It should just work - do you have any logs of connecting the iButton?

**Comment by ThomazCampos** [comment]
I am facing same issue indicated above..

**Comment by eueduardo3** [comment]
> I am facing same issue indicated above..

eu também
