### ISSUE TITLE
Error while running mvn package

### ISSUE THREAD

**Issue by achagu** [traccar/traccar#4251]
I am using maven 3.6.0. Below is the error while running mvn package.
```
[ERROR] Plugin org.apache.maven.plugins:maven-enforcer-plugin:1.4.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-enforcer-plugin:jar:1.4.1: Could not transfer artifact org.apache.maven.plugins:maven-enforcer-plugin:pom:1.4.1 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version ->
```

**Comment by tananaev** [comment]
Looks like you have some network issue.

**Comment by achagu** [comment]
Hi Anton,
my internet is working fine. I did ping repo.maven.apache.org and it is working fine. Can there be any other reason for the error.
Thanks

**Comment by tananaev** [comment]
Pinging is not the same thing. Your issue is more likely with SSL connection negotiation.
