### ISSUE TITLE
Compiling issues in traccar server code

### ISSUE THREAD

**Issue by achagu** [traccar/traccar#4252]
I checked out the latest code but there seems to be compiling issues in the code.

![compilationErrors](https://user-images.githubusercontent.com/27474414/54528332-b44d3880-49a2-11e9-8aba-e9838cf39f12.PNG)

**Comment by tananaev** [comment]
There are no compiling issues. You are doing something wrong.

**Comment by tsmgeek** [comment]
I just checked out into idea without any problems and compiled straight up, just follow the instructions on the traccar website.

**Comment by achagu** [comment]
Below are the steps i followed.
1.Click on import Project.
![import1](https://user-images.githubusercontent.com/27474414/54594864-883fbf00-4a57-11e9-9f90-8e9e300cf0a3.PNG)

2. Select traccar root folder
![SelectFile2](https://user-images.githubusercontent.com/27474414/54594976-c2a95c00-4a57-11e9-8d55-e9bfcbee5c27.PNG)

3. Select "Create project from existing sources"
![createProject3](https://user-images.githubusercontent.com/27474414/54595087-ea98bf80-4a57-11e9-9ccc-720c9648b72d.PNG)

4.Select project Name and project location.
![projectName4](https://user-images.githubusercontent.com/27474414/54595207-2b90d400-4a58-11e9-9e1d-3c5f9dba38a3.PNG)

5.Select source files and test files that will added to project root.
![sourceFiles5](https://user-images.githubusercontent.com/27474414/54597779-300bbb80-4a5d-11e9-8ace-e4fb35f16d91.PNG)

6.Select traccar module
![Modules6](https://user-images.githubusercontent.com/27474414/54597834-487bd600-4a5d-11e9-90e1-93830cf75dd1.PNG)

7. Click on finish.

**Comment by tsmgeek** [comment]
This is a maven project, follow instructions on the website.

https://www.traccar.org/build-in-intellij-idea/

**Comment by achagu** [comment]
Thanks for your reply. I dont have any compilation issues now.
