### ISSUE TITLE
Tk103 Protocol - Alarm without Date and Coordinates not decoded

### ISSUE THREAD

**Issue by c3r63ru5** [traccar/traccar#4254]
Hey,

I'm using one of vjoycars devices via tk103 and the server does not decode alarm messages without coordinates (and date)... so I looked at Tk103ProtocolDecoder.java.

I added a Parser and function for handling messages of that type, this is what they look like:
`(123456,ZC11,,0.00,0,0)`

So only the ID and Command is there, the decoder would now identify the message based on "ZC,," runs the function to basically just create a position with the ID and alarm set. Do I need to do more, the server does not seem to create an alarm for that position, logs only show the hex... not sure what I'm missing here.

```java
private Position decodeAlarmNoLoc(Channel channel, SocketAddress remoteAddress, String sentence) {
        Parser parser = new Parser(PATTERN_ALARM_NOLOC, sentence);
        if (!parser.matches()) {
            return null;
        }

        DeviceSession deviceSession = getDeviceSession(channel, remoteAddress, parser.next());
        if (deviceSession == null) {
            return null;
        }

        Position position = new Position(getProtocolName());
        position.setDeviceId(deviceSession.getDeviceId());

        getLastLocation(position, null);

        position.set(Position.KEY_ALARM, Position.ALARM_MOVEMENT);

        return position;

    }
```

Thanks,
Sebastian

**Comment by tananaev** [comment]
Share your commit.

**Comment by c3r63ru5** [comment]
OK, I tidied up my code and may have had something wrong in the parser regex. It now works, I'll close the issue, maybe this helps somebody... the snippet in the main decoder and the parser below.

```
    private static final Pattern PATTERN_ALARM_NOLOC = new PatternBuilder()
            .text("(").optional()
            .number("(d+),")                     // device id
            .text("ZC11,")
            .any()
            .compile();
```

```
        } else if (sentence.contains("DW5")) {
            return decodeLbsWifi(channel, remoteAddress, sentence);
        } else if (sentence.contains("ZC11,,")) {
            return decodeAlarmNoLoc(channel, remoteAddress, sentence);
        }
```

**Comment by c3r63ru5** [comment]
> Share your commit.

Sure... the patch attached.
[tk103-alarmsnoloc.patch.txt](https://github.com/traccar/traccar/files/2990446/tk103-alarmsnoloc.patch.txt)

**Comment by tananaev** [comment]
Thanks.
