### ISSUE TITLE
sorting devices using status

### ISSUE THREAD

**Issue by wisdomrider** [traccar/traccar#4257]
is there any way to get a list of online devices in api  like
/api/devices?status=online should return all online devices

**Comment by Escalion** [comment]
I haven't checked the endpoint, but surely it is trivial to sort this application side anyway?

**Comment by wisdomrider** [comment]
can you please elaborate

**Comment by Escalion** [comment]
It depends on the language you are using to access from. But simply retrieving all devices and filtering by the status property will serve the purpose you require.
