### ISSUE TITLE
Which algorithm you have used for geo-fence ?

### ISSUE THREAD

**Issue by ramesh456** [traccar/traccar#4260]
Hi , 
As i can see i can create Geo-fence in polygon , poly line and circle manner.

So i just want to know which algorithm you have used to identify if that device is IN/OUT Geo-fence ?

Have you used "Even–odd rule" for polygon Geo-fence to identify IN/OUT ?

**Comment by ramesh456** [comment]
@tananaev

**Comment by ramesh456** [comment]
@tananaev

**Comment by tananaev** [comment]
You will get banned from here if you spam like this again.

**Comment by ramesh456** [comment]
Ok. I am sorry for this.  Can you explain about this ?

**Comment by tsmgeek** [comment]
https://github.com/traccar/traccar/blob/master/src/org/traccar/geofence/GeofencePolygon.java

https://github.com/traccar/traccar/blob/master/src/org/traccar/helper/DistanceCalculator.java
