### ISSUE TITLE
[Future request] Android/iOS multi server support

### ISSUE THREAD

**Issue by SamNLD** [traccar/traccar#4263]
Hello Anton,

We really love Traccar, so much that we have multiple servers running.
Is it possible to add the option to switch between servers in the Android and iOS app?

The only way to switch at the moment is to uninstall and install the app.

Best regards,
Sam

**Comment by tananaev** [comment]
Why is the issue in the server repository? If your feature request is for mobile app, you should create in the corresponding repo.
