### ISSUE TITLE
Wrong Units of event.attribute in Excel Reports

### ISSUE THREAD

**Issue by cesarserafim** [traccar/traccar#4264]
for example in overspeed event report, the event attribute showing the unit in knots. How to present the units according to what is defined in the system, in my case km / h?

**Comment by tananaev** [comment]
Please provide a screenshot of what you are talking about.

**Comment by cesarserafim** [comment]
![event report](https://user-images.githubusercontent.com/7399657/55575810-23869480-56e6-11e9-8de2-5f7541ba6d15.jpg)
This event report for overspeed that speedlimit is set to 110Km/h is showing information in knots not in kmh.

**Comment by jinzo** [comment]
knots are the default speed unit in Traccar. You can change that on per-user or per-server basis with "Speed Unit" attribute.

**Comment by cesarserafim** [comment]
I know, it is configured for the server and user according to image, even so in the report it presents in knots like this stored in sql. This creates a damned mess for the user and does not make sense at all.

**Comment by tananaev** [comment]
You should be able to handle it via template.

**Comment by cesarserafim** [comment]
Hi Anton! That was my original question, I believe it's just this E9 cell.

**Comment by jinzo** [comment]
I just opened trips.xlsx and if I understand it right the solution is to use .format and/or multiply the value by 1.852? So you could use ${speedUnit.equals...} similary as in trips.xlsx for a fully useful solution.

**Comment by cesarserafim** [comment]
Thanks Jinzo, I'll try and get the result, more people will need it.

**Comment by cesarserafim** [comment]
could someone tell me the way to merge data from two reports? I would like to add the contents of the Summary report in the route report.
