### ISSUE TITLE
Features Requests: Better End User Experience

### ISSUE THREAD

**Issue by cesarserafim** [traccar/traccar#4266]
I use Traccar since version 3.1, which gets better and better with each new update. Not being a programmer, I would like to collaborate at least by sharing the main needs / difficulties of the end users who have experience with several other systems in the market. Perhaps experienced members of this community can collaborate with the code.

1- Fewer clicks with better information - right click, balloon mouse over/click:
The resizeble status area of the device could also be collapsible, but mainly it should be possible to sort and hide any of the attributes according to the needs and device used. Most users prioritize Driver, Speed, Address, Ignition and sometimes Sensors. In everyday use they want to know objectively "who is where and how." These selectable attributes should be displayed together with the marker when selecting a device, and, if necessary, use the detailed status. Call a report, send a command and other options present on the buttons of the devices area just right clicking in the marker or list is more objective and more secure.

2 - Another important information to have on status is the actual idle / moving time and the markers and icons could change according to moviment status and alarms not just when online/offline

3 - Quick Map change:
In many situations it is necessary to switch between maps to better identify where the device is located. Wikimedia is clean and light, great as a default map, but sometimes we need to switch to Bing Hybrid just to understand what's in that place.

4 - Search Tool:
in situations of driver assistance and geofence creation, it is necessary to use another window or monitor to find an address in another service and locate it again on the screen of the Traccar.

5 - More conclusive and practical reports:
5.1 - The Summary report could show a count of overspeeding, total time in motion and idle. All information of Summary Report would be present in all other reports avoiding the need to generate and cross multiple reports and files.

5.2 - Before Export would be more interesting a preview of the content in html and only then the save as option. The exported file should be auto named as reporttype_device / group_period, at least report_type.xlsx

Please do not understand all this as a criticism of this beautiful work, as I said at the outset, we just do not have the technical capacity to carry them out. On the other hand we deal daily with dozens of other users with the most diverse needs, information that can contribute much to the constant evolution of our good old Traccar. A hug to everyone.

**Comment by jinzo** [comment]
There is some work/discussion being done on a more modern Web Frontend/GUI, see: https://github.com/traccar/traccar-web/issues/592

But as you can see no one had the time to put the needed work into getting on par with the current functionality. As Traccar is used by a lot of different companies, with different needs, it's probably quite hard to please everyone. 

Anyway - I think this is better debated in the traccar-web repository/sub-project.

**Comment by cesarserafim** [comment]
I know ): my hope was that version 4 would bring changes in this direction. Who came closest to that was the Vitaly Litvak Mod, unfortunately stopped at 3.9

**Comment by tananaev** [comment]
Some of these are already implemented. Others need to be broken down into separate tickets. Also please create tickets in the web app repo if it's related to the web app.
