### ISSUE TITLE
Multiple specific network address binds

### ISSUE THREAD

**Issue by Zimmedon** [traccar/traccar#4267]
Currently it is possible to bind to specific addresses and ports, but I do not see any way of binding to multiple addresses without binding to every available one. I'd like to be able to for instance use the following:
```
<entry key='osmand.port'>5055</entry>
<entry key='osmand.address'>1.2.3.4</entry>
<entry key='osmand.address'>1:2:3:4:5:6:7:8</entry>
```
or
```
<entry key='osmand.port'>5055</entry>
<entry key='osmand.address'>1.2.3.4</entry>
<entry key='osmand.address6'>1:2:3:4:5:6:7:8</entry>
```

**Comment by tananaev** [comment]
It's not supported currently.
