### ISSUE TITLE
AIS140 LIstener issue

### ISSUE THREAD

**Issue by ctpl0504** [traccar/traccar#4268]
We have configured  a device to port 5179

find the attached log. But we are not getting records in positions table. Please help
[tracker-server.txt](https://github.com/traccar/traccar/files/3048278/tracker-server.txt)

**Comment by tananaev** [comment]
You would have to provide corresponding HEX samples from your log. We are not going to search for it through the whole file.

**Comment by ctpl0504** [comment]
Please find below log, we are not receiving any data to positions table
[5179 log.txt](https://github.com/traccar/traccar/files/3067811/5179.log.txt)

**Comment by ctpl0504** [comment]
How to Send reminder in traccar portal

**Comment by ctpl0504** [comment]
We are waiting for your reply on the above error. Please help us in this regard

**Comment by tananaev** [comment]
Are you using latest source code?

**Comment by ctpl0504** [comment]
yes we are using latest version 4.3

**Comment by tananaev** [comment]
That's not what I asked.

**Comment by ctpl0504** [comment]
We are using traccar windows application i.e. traccar-wndows-64-4.3

**Comment by tananaev** [comment]
It means that the answer to my original question is NO. I'm closing this ticket for now. Either test with source code or wait for next official release.
