### ISSUE TITLE
ITS Protocol minor update request

### ISSUE THREAD

**Issue by jaimzj** [traccar/traccar#4272]
The following data from device is not being recognized at the moment.

New Hex:
```
244e524d2c524f41445250412c312e394149532c4e522c30312c4c2c3836393836373033363031353636392c2c312c30383034323031392c3230303530362c32362e39303634353636372c4e2c37352e37383936323333332c452c302e302c3238302e37342c31342c3437312e322c302e38302c302e36302c566f6461666f6e65202d2052616a61737468616e2c302c312c31322e392c342e322c302c4f2c32302c3430342c36302c303746352c333939462c31302c303746352c324434372c31302c303746352c333941312c31302c303746352c324136452c30382c303746352c333536382c303030302c30302c3030333838342c39364434463730312a
```
Decoded value of New hex:
```
$NRM,ROADRPA,1.9AIS,NR,01,L,869867036015669,,1,08042019,200506,26.90645667,N,75.78962333,E,0.0,280.74,14,471.2,0.80,0.60,Vodafone - Rajasthan,0,1,12.9,4.2,0,O,20,404,60,07F5,399F,10,07F5,2D47,10,07F5,39A1,10,07F5,2A6E,08,07F5,3568,0000,00,003884,96D4F701*
```
Attached is the protocol document for reference for the same.

[68201793238AMFinal_Draft_AIS_140.pdf](https://github.com/traccar/traccar/files/3056104/68201793238AMFinal_Draft_AIS_140.pdf)

Existing decoder test line in source code  which matches almost close to the new hex shared above: https://github.com/traccar/traccar/blob/e6b0e38e6d250253b62c41dac3f01a9309a8de7f/src/test/java/org/traccar/protocol/ItsProtocolDecoderTest.java#L14

**Comment by tananaev** [comment]
Works for me. Have you tested latest source code?

**Comment by jaimzj** [comment]
Oh, so sorry I have not done that, I tested it on 4.3 release. not the latest source code.

**Comment by ashishnimrot** [comment]
$,NRM,MARK,V0.0.1,NR,01,L,351510091197148,000000000,1,23072019,062823,20.745541,N,78.598259,E,0.9,29.90,9,300.7,2.6,1.7,IDEA,1,1,0.0,4.1,0,18,404,22,ED03,1145,ED03,958,49,ED03,959,31,ED03,1147,30,ED03,4A9,28,1000,01,0.0,48288,000060,0,0,0,7379,*

Update Required
