### ISSUE TITLE
Unknown Protocol

### ISSUE THREAD

**Issue by PeteYorn** [traccar/traccar#4273]
Hello

I'm trying to make some chinese equipments work in traccar.
I'm receiving this on the logs:
```
aa007020000100000000000033353333353830313831353431313700000000000000000000
```
The protocol is in attachment.
Is there already a protocol that communicates with these equipments?

Thanks
[GPS GPRS protocol.pdf](https://github.com/traccar/traccar/files/3060155/GPS.GPRS.protocol.pdf)

**Comment by tananaev** [comment]
Looks like a new protocol.

**Comment by PeteYorn** [comment]
Hello Anton

Can you please help to add this new protocol?

Thanks

**Comment by tananaev** [comment]
Sure. Send me an email to discuss.
