### ISSUE TITLE
Added Telegram Notification support

### ISSUE THREAD

**Issue by he-leon** [traccar/traccar#4274]
Hi, 

I added Notifications support for Telegram Messenger. See 22436a2434faa8912c8a352e65306d0dc0669b5c

Example config:
```
<entry key='notificator.types'>telegram,web</entry>
<entry key='notificator.Telegram.apikey'>YOUR_BOT_API_KEY</entry>
<entry key='notificator.Telegram.chatid'>CHAT_ID</entry>
```
You can add a bot and get an api key using the BotFather contact in Telegram. 
After doing that you have to get the chatid as described in this link: https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id

Feel free to test it.

Todo: 
- Notification channel shows up as notificatorTelegram in the Web UI. I guess this can be fixed by adding translations to traccar-web. 
- Telegram supports simple HTML formatting in the messages. For now it uses the plain short message format. With a custom formatter (similiar to the Mail formatter) you could make the message look nicer.

Note: I'm not a Java programmer, so the code is probably not perfect. Feel free to correct and improve it. I used the NotificatorFirebase class and modified it to work with Telegram. Hope this is useful for someone.

Best
Leonhard

**Comment by djbo1982** [comment]
Hi...

Excelen solution to get on live notification, can you send us more information about this?

**Comment by Nitrosito** [comment]
+1 ¿How configure it?
I suppose we copy 2 modified files. And in the config file, set 3 entrys (example config you post). 

This must will native feature!! Developers, merge this in the official branch!

**Comment by he-leon** [comment]
@Nitrosito Yep, either copy the modifications to your branch or just clone my fork. Of course you have to compile traccar afterwards to get the new tracker-server.jar file. You can then swap the old tracker-server.jar from your installation with the newly compiled one.

**Comment by tananaev** [comment]
@he-leon can you send a pull request?

**Comment by Nitrosito** [comment]
> 
> 
> @he-leon can you send a pull request?

+1

**Comment by adadnc** [comment]
You may want to consider that the config keys are not
```
notificator.Telegram.apikey
notificator.Telegram.chatid
```

From the current source code it needs to be:
```
notificator.telegram.key
notificator.Telegram.chatid
```

**Comment by tananaev** [comment]
From next release keys will be:

- notificator.telegram.key
- notificator.telegram.chatId

**Comment by kobisamoray** [comment]
Hi,
I believe that sending a private message to a user as other notificators do is more elegant.
I've coded this, but IDK how to propose this (should I just push this change into github?).

**Comment by tananaev** [comment]
@kobisamoray, do you mean something like this?

https://github.com/traccar/traccar/pull/4309

**Comment by kobisamoray** [comment]
@tananaev sort of.
I've used the phone number to retrieve the user's chat id from telegram.

**Comment by tananaev** [comment]
That would be much better. Feel free to send a PR.

**Comment by kobisamoray** [comment]
Added #4310

**Comment by Nitrosito** [comment]
Its possible configure APIKEY and UserChatID per USER in tracar?
It would be interesting if this was configurable by user in the traccar GUI

By the way, have not put the documentation of this function in documents

**Comment by San4euS** [comment]
Небольшая инструкция как я подключал Telegram

В файле opt/traccar/conf/traccar.xml добавить следующие строки

<entry key='notificator.types'>web,mail,telegram</entry>
<entry key='notificator.telegram.chatId'>-888398996</entry>
<entry key='notificator.telegram.key'>765112785:AAHoRzesUk5f4YCBjtz0U88X2XVcTCBG1b8</entry>

далее необходимо получить chatId и Key

1. Создаете бота зайдя в @BotFather
Во вкладке API Token узнаете Key
765112785:AAHoRzesUk5f4YCBjtz0U88X2XVcTCBG1b8

2. Создаете группу и добавляете туда @my_bot
После чего набираете /my_id
Он вам дас id группы

Your group Chat ID : -888398996
Title : Gps

3. Заходим в фаил /etc/resolv.conf
Добавляем строку nameserver 4.2.2.1

далее проверяем

curl -X POST "https://api.telegram.org/bot765112785:AAHoRzesUk5f4YCBjtz0U88X2XVcTCBG1b8/sendMessage" -d "chat_id=-888398996&text=my sample text"

получаем сообщение OK

{"ok":true,"result":{"message_id":105,"from":{"id":765112785,"is_bot":true,"first_name":"Bot_gps","username":"gps_bot"},"chat":{"id":-888398996,"title":"Gps","type":"group","all_members_are_administrators":true},"date":1565795133,"text":"my sample text"}}

Теперь заходите в уведомления и настраиваете и в нужных уведомлениях добавьте notificatorTelegram

**Comment by tshelver** [comment]
My 2 cents worth on this.  

I have just been through the process of creating a Telegram bot / service to send events to users, and to allow them to get the current status and position of their vehicles.
This is off my own custom Postgresql database that gets feeds from another telematics system, and will also be picking up data from Traccar in the near future.

You will obviously need to create a bot using BotFather first.

First issue was finding out the Telegram user (chat id) to send it to.  Note that you need to create a bot to determine the user's chat id, unless you use a channel.

**Round 1** was to create a Telegram channel:
Create a public channel, add your telegram bot as an administrator.
Take the channel private, and get the channel id (first numeric string between =c and _ in the URL).
Invite users

This method is a bit time consuming and a bit complex for the administrator to handle.

**Round 2** was to allow the user to register themselves:
Create a python listener using the bot updater to receive commands, one of those being to allow the user to register themselves
I set up a command handler for /register where the user supplied a known fact in the system.
The user will need to add your bot as a contact and send (for example) a /register command 
From that received message I get get the user's chat id and the known fact and the department ID they wish to monitor
I pass this message into a Redis queue so as not to block the message handler, and to allow some more complex stuff such as database connection handling and so on which you don't want in the handler.  It's also difficult to easily debug the message handler as these run in background, and only accept minimal parameters.

This message is picked up from Redis by a dedicated task: note that multiple task handlers can run against this queue to spread the load.
The task handler then creates the relevant backend information and messages the confirmation to the user.

The system now can message all events to the user and allow them to do additional functions.

Using the same bot, I also allow the user to do vehicle status queries, which send back current known position, address, direction of travel, speed and so on.

This entire process is driven by the user, with additional work required by the admin.

**Comment by gabrielloren** [comment]
> From next release keys will be:
> 
> * notificator.telegram.key
> * notificator.telegram.chatId

Will we be able to send individual messages to traccar users? Is that possible?

**Comment by macano13** [comment]
Is there any possibility for other users of my traccar server to use telegram notification?

I set everything up properly and on my mobile phone I get telegram notifications but I tested and added another user and through another mobile phone and another number installed the telegram and made contact with my previously created bot from the previous mobile phone but I still get notifications on the first mobile phone from which I created a bot telegram (I added phone number on that new user account).

**Comment by soshial** [comment]
Hey, @tananaev, you promised to add documentation for Telegram notifications.

**Comment by tananaev** [comment]
Added documentation here:

https://www.traccar.org/documentation/notifications/#telegram

Thanks for contributions.
