### ISSUE TITLE
jre is missing in setup folder witch is called by .service

### ISSUE THREAD

**Issue by hoerbi1000** [traccar/traccar#4276]
setup.sh is copying all from the folder to '/opt/traccar'
```bash
#!/bin/sh

mkdir -p /opt/traccar
cp -r * /opt/traccar
```

service file is also moved to the right destination but the service faile contains 
`ExecStart=/opt/traccar/jre/bin/java -jar tracker-server.jar conf/traccar.xml`

but in the copy command from the setup folder there is no folder jre.

i guess that the file is missing?

**Comment by tananaev** [comment]
Have you built your own installer?

**Comment by hoerbi1000** [comment]
i have only executed the setup.sh in from the setupfolder

**Comment by tananaev** [comment]
Why would you do that? Setup script is supposed to be part of the installation package. It's not intended to be called directly.

**Comment by oliv3** [comment]
Why don't you add a README.md in this directory with instructions ?

**Comment by hoerbi1000** [comment]
https://www.traccar.org/linux/

i guess it should also be documented here.
