### ISSUE TITLE
Problème hors ligne traccar

### ISSUE THREAD

**Issue by youssrabaja** [traccar/traccar#4285]
Bonjour, j'ai travaillée sur un projet d’implémentation d'une solution  traccar de gps   pour suivre les voitures..j'ai déjà  commencée a ce projet  mon appareil gt06N s’apparut  une seul fois en ligne mais par la suite elle est toujours en ligne sachant que on a vérifiés toutes  trableshoting de traccar  mais le problème reste .

**Comment by tananaev** [comment]
Duplicate of [the forum thread](https://www.traccar.org/forums/topic/probleme-hors-statu-traccar/).
