### ISSUE TITLE
An exceptionCaught() event was fired error

### ISSUE THREAD

**Issue by AymanElarian** [traccar/traccar#4289]
hello , i have the following error 

`2019-04-23 10:59:15  WARN: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. - Too many open files - IOException (...)`

```
~# ulimit -Hn
65536
~# ulimit -Sn
65536
```
Any help regarding to avoid that ,

**Comment by kelany** [comment]
@AymanElarian  please check this settings
https://easyengine.io/tutorials/linux/increase-open-files-limit

**Comment by AymanElarian** [comment]
@kelany Thank you man will try it

**Comment by AymanElarian** [comment]
@kelany  still error appear 
`2019-04-23 11:35:50  WARN: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. - Too many open files - IOException (...)`

```

root:~# cat /proc/sys/fs/file-max
2097152
root:~# sysctl -p
vm.max_map_count = 262144
net.core.somaxconn = 1024
net.core.netdev_max_backlog = 5000
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_wmem = 4096 12582912 16777216
net.ipv4.tcp_rmem = 4096 12582912 16777216
net.ipv4.tcp_max_syn_backlog = 8096
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_tw_reuse = 1
net.ipv4.ip_local_port_range = 10240 65535
fs.file-max = 2097152
root:~#

```

**Comment by kelany** [comment]
@AymanElarian the process show that your max open files is 4096 not 65536

**Comment by AymanElarian** [comment]
@kelany even after reboot it still not increase the limit , i follow the link you mention 

root:~# sysctl -p
vm.max_map_count = 262144
net.core.somaxconn = 1024
net.core.netdev_max_backlog = 5000
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_wmem = 4096 12582912 16777216
net.ipv4.tcp_rmem = 4096 12582912 16777216
net.ipv4.tcp_max_syn_backlog = 8096
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_tw_reuse = 1
net.ipv4.ip_local_port_range = 10240 65535
fs.file-max = 2097152
root:~#

do you know why it not reflect "fs.file-max = 2097152" ?

**Comment by kelany** [comment]
@AymanElarian did you did this point?
Open file: /etc/security/limits.conf

Paste following towards end:

```
*         hard    nofile      500000
*         soft    nofile      500000
root      hard    nofile      500000
root      soft    nofile      500000
```

**Comment by AymanElarian** [comment]
yup 
<img width="749" alt="Screen Shot 2019-04-23 at 3 20 59 PM" src="https://user-images.githubusercontent.com/364872/56580531-6b108a00-65db-11e9-854f-053491c6060c.png">

**Comment by AymanElarian** [comment]
for any one else who face this problem 

even after you change the value  it will stay the same , 
if you hook process by id in run time , after 2 minutes it will crach

the exact solution is the following 

1. follow https://easyengine.io/tutorials/linux/increase-open-files-limit
2. nano /etc/systemd/system/traccar.service
3. at [SERVICE] Section add paramter LimitNOFILE as this limit used per process for max open files
[Service]
Type=simple
LimitNOFILE=49152
WorkingDirectory=/opt/traccar

**Comment by netomx** [comment]
Same issue for me, solved with https://unix.stackexchange.com/questions/382877/systemd-limitnofile-capped-to-4096

> Late answer; limits.conf is not used when systemd is running (limits.conf is for non-systemd systems).
> The file you actually want is; /etc/systemd/system.conf - this is the global config.
