### ISSUE TITLE
How to test jcache

### ISSUE THREAD

**Issue by gpproton** [traccar/traccar#4293]
Hi @tananaev I would like to test the hazelcast jcache feature is there any suggestion on the current state of it usable or not and if it usable anything in the configuration.

**Comment by tananaev** [comment]
You can try and build it from source, but it doesn't work very well.

**Comment by gpproton** [comment]
Hi @tananaev i tried it out and it works quite well for the status sync which is almost immediately, but sadly i'm not sure why i kept getting the error below.

```````````````
HTTP 401 Unauthorized - WebApplicationException (SecurityRequestFilter:113 < ...)
```````````````

when ever any of the host are accessed the other goes down, see my hazelcast configuration below.

Host 1

```````````````
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.7.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <network>
        <port auto-increment="false">5701</port>
        <join>
            <multicast enabled="false" />
            <tcp-ip enabled="true">
                <member>localhost:5702</member>
            </tcp-ip>
        </join>
    </network>
</hazelcast>
```````````````````

Host 2

````````````````
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.7.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <network>
        <port auto-increment="false">5702</port>
        <join>
            <multicast enabled="false" />
            <tcp-ip enabled="true">
                <member>localhost:5701</member>
            </tcp-ip>
        </join>
    </network>
</hazelcast>
````````````````

This is a really nice feature can't wait to see it advance to a better version of what i see now, if oyu'd like me to share the logs from my test i'd be happy to do so.

**Comment by tananaev** [comment]
We reimplemented horizontal scaling with smart caching and multicast synchronization. It's all available on master. So jcache is no longer relevant.
