### ISSUE TITLE
traccar Messages Delay

### ISSUE THREAD

**Issue by AymanElarian** [traccar/traccar#4295]
Hello , 
i face a delay with traccar that delay disappear once i restart even with 5 minutes timeout . delay some time be in hours ,

once i start service delay disappear 

1. i use load balancer and 2 traccar servers and load balancer  fwd port to target server based on port, each  node hold 1 protocol
2. database is postgres 
3. devices is 12k 
4. i receive the following info error on start 

> Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability

5. Devices send to 2 ip one is vendor devices and it update with in minutes but on traccar with in hours  unless restart 

is this related to this problem ?

**Comment by tananaev** [comment]
Most likely database issue. PostgreSQL doesn't work very well with Traccar. MySQL works ~5x faster.

**Comment by AymanElarian** [comment]
@tananaev  its jdbc driver issue , or db it self ?

**Comment by tananaev** [comment]
Don't know, but I know some people did tests on both databases and MySQL was much faster.
