### ISSUE TITLE
Translation push notifications Firebase

### ISSUE THREAD

**Issue by conde000011100** [traccar/traccar#4296]
I have push notifications, but they all arrive in the default English language, how can I change the language of push notifications?

Attachment of notification reception code:
```java
    public void onMessageReceived(RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);

        PendingIntent pendingIntent = PendingIntent.getActivity(
                this, 0, new Intent(this, MainActivity.class), PendingIntent.FLAG_ONE_SHOT);
        NotificationCompat.Builder builder = new NotificationCompat.Builder(this, getString(R.string.notification_channel_id))
                .setSmallIcon(R.drawable.ic_notify_small)
                .setContentTitle(getString(R.string.app_name))
                .setContentText(remoteMessage.getNotification().getBody())
                .setAutoCancel(true)
                .setContentIntent(pendingIntent);;
        ((NotificationManager) getSystemService(NOTIFICATION_SERVICE)).notify(remoteMessage.hashCode(), builder.build());
    }

    @Override
    public void onNewToken(String token) {
        super.onNewToken(token);
        ((MainApplication) getApplication()).broadcastToken(token);
    }
}
```

Best regards

**Comment by conde000011100** [comment]
Any help about this teacher @tananaev

**Comment by tananaev** [comment]
How is it related to official Traccar project? Also, is this a server or mobile app question?

**Comment by conde000011100** [comment]
I think I say it for everyone, since all the push notifications of firebase and telegram are 100% in English, it would be good to be able to personalize the language, do not you think? regards

**Comment by tananaev** [comment]
Notifications and reports can be localized through templates. I'm closing this ticket for now. If you want to request some feature, please clearly explain what you want to do and why. Also, it has to be in correct repository.
