### ISSUE TITLE
erro why are you giving me an error when installing and executing

### ISSUE THREAD

**Issue by maxicabanillas78** [traccar/traccar#4298]

**Comment by maxicabanillas78** [comment]
root@ip-172-31-1-179:/home/admin# sudo ./traccar.run
Creating directory out
Verifying archive integrity...  100%   All good.
Uncompressing traccar  100%  
Failed to get D-Bus connection: Unknown error -1
Failed to get D-Bus connection: Unknown error -1
root@ip-172-31-1-179:/home/admin# sudo systemctl start traccar.service
Failed to get D-Bus connection: Unknown error -1

**Comment by tananaev** [comment]
Closing as duplicate:

https://www.traccar.org/forums/topic/why-are-you-giving-me-an-error-when-installing-and-executing/

Questions like this belong on the forum.
