### ISSUE TITLE
Replace tracker-server.jar failure

### ISSUE THREAD

**Issue by conde000011100** [traccar/traccar#4299]
How about @tananaev , I'm packing traccar with my protocol, all right, but the problem is when I replace the new tracker-server.jar, it sends me the following windows error, try linux and the service does not start.

attached image
https://subefotos.com/ver/?8bf78cf99b9b941a12e5f35d5a0d24cco.png#codigos
https://subefotos.com/ver/?c03f9ec1dd612836ee4bdc32f36ac135o.png#codigos
https://subefotos.com/ver/?a2023a01a63c145bb6d528b8cd6f0486o.png#codigos

Start the project and I get it right, I can access without problems, the problem is when the project is compiled, but I do not know what it can be.
image run
https://subefotos.com/ver/?27e630c1f06f9ea4a680d65eb39e2249o.png#codigos
Version 4.4

regards.

**Comment by tananaev** [comment]
You need to find actual error message.

**Comment by conde000011100** [comment]
The interesting thing is that I have the log without any error

**Comment by conde000011100** [comment]
What version of java jre and sdk are needed now I have jdk1.8.0_181y jre1.8.0_211 installed

**Comment by tananaev** [comment]
Traccar has JRE bundled with it, so you don't need to install it separately.

**Comment by conde000011100** [comment]
@tananaev  Finally I could solve it, the solution was to copy the entire "lib" folder to the new project, thank you very much.

regards
