### ISSUE TITLE
email Subject ($subject="") in Notifications  doesn't support UTF-8 encoding

### ISSUE THREAD

**Issue by GusGiann** [traccar/traccar#4305]
First of all THANK YOU all you contributors for this beautifull GPS Tracking Platform.

I Have a problem !
Velocity Engine Seems that doesn't support UTF encoding in email subject of notifications.
Email subject shows funny letters (ex ????????????)

Is there a way to enforce utf encoding (or other encoding) directly in template file (*.vm) ?

Everything else is lookong OK. (in body message)
(Traccar Server version 4.4)

Thank you in Advance !

**Comment by tananaev** [comment]
Just tested UTF subject encoding in the Velocity and it's working. I suspect it's the email limitation.
