### ISSUE TITLE
change the map to baidu ，map‘s interface is blank

### ISSUE THREAD

**Issue by dodojie** [traccar/traccar#4306]
Hi , I'm Chinese , 

I set the server's map  to baidu ,  map's interface is blank。

I hope you can answer my question.

**Comment by dodojie** [comment]
![QQ图片20190506120840](https://user-images.githubusercontent.com/37992219/57206352-bffaca00-6ff7-11e9-8abb-e449eb919caf.png)

**Comment by tananaev** [comment]
As far as I know, there is a problem with Baidu SSL certificate.

**Comment by dodojie** [comment]
thank you very much!

**Comment by dodojie** [comment]
So, what should I do about this?

**Comment by dodojie** [comment]
> As far as I know, there is a problem with Baidu SSL certificate.

So, what should I do about this?

**Comment by tananaev** [comment]
Baidu is not supported anymore, but we use AutoNavi instead for China.
