### ISSUE TITLE
Traccar Synology - Not Working

### ISSUE THREAD

**Issue by chbardel** [traccar/traccar#4308]
The Package is not starting. I have everything installed. Database Password is correct etc. However there is no database user created neither is the database. I also dont get an Wrapper log. Only the server log. I am using Java 8 and installed all the dependencies via IPKG. Package was installed via Package Manager but I am not able to start it. Also tried manually starting the shell script traccar.sh. It told me it is running and returned to command prompt.
I got only one error/warning while installing coreutils via IPKG telling me some of the files where already installed via gettext.

Dont know how to drill down to the issue without log. Please help!

**Comment by tananaev** [comment]
1. Please don't duplicate your threads.
2. This question doesn't belong here in the first place. Synology package is not an official Traccar project.
