### ISSUE TITLE
Prevent spiders/robots from indexing traccar

### ISSUE THREAD

**Issue by fabiofdsantos** [traccar/traccar#4312]
Any reason to not preventing robots from indexing Traccar by default?

Meaning, if you google "Powered by Traccar GPS Tracking System." you will find at least some servers running Traccar. Since Traccar is protected by login, there's no reason to allow Google (or any other search engine to index these pages).

In case of a vulnerability, it will be easy to get a list of potential victims.

**Comment by tananaev** [comment]
I don't really see any good reason to disable it by default.
