### ISSUE TITLE
The server time zone value 'EDT' is unrecognized or represents more than one time zone

### ISSUE THREAD

**Issue by JuanIrache** [traccar/traccar#4314]
Got this error after upgrading from 4.3 to 4.5

> 2019-05-08 13:47:43  INFO: HikariPool-1 - Starting...
>   2 2019-05-08 13:47:43  WARN: Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
>   3 2019-05-08 13:47:48 ERROR: HikariPool-1 - Exception during pool initialization. - The server time zone value 'EDT' is unrecognized or repre
>     sents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a
>      more specifc time zone value if you want to utilize time zone support. - InvalidConnectionAttributeException (... < DataManager:139 < *:89
>      < Context:292 < Main:110 < ...)
>   4 2019-05-08 13:47:48 ERROR: Main method error - The server time zone value 'EDT' is unrecognized or represents more than one time zone. You
>     must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if yo
>     u want to utilize time zone support. - InvalidConnectionAttributeException (... < DataManager:139 < *:89 < Context:292 < Main:110 < ...)

Rolled back to 4.3 and all is good.

**Comment by tananaev** [comment]
I would recommend you to search before creating tickets.

**Comment by JuanIrache** [comment]
Thanks, thats what I did
https://imgur.com/lCrs70J

**Comment by JuanIrache** [comment]
Here's the answer for anyone else: https://www.traccar.org/forums/topic/upgraded-to-44-no-mysql-connection-anymore/
