### ISSUE TITLE
Traccar  data not updating when i add a device or user in sql database

### ISSUE THREAD

**Issue by wisdomrider** [traccar/traccar#4319]
Traccar  data not updating when i add a device or user in sql database i have to restart the sever then only the data gets uploaded . How can i make it visible without restarting the traccar server any idea?
 PS : I am importing data from my another site and triggering in database

**Comment by tananaev** [comment]
You need to use API. Also, for questions please use forum.

**Comment by wisdomrider** [comment]
forum register is broken

**Comment by wisdomrider** [comment]
> You need to use API. Also, for questions please use forum.

Forum register is broken

**Comment by tananaev** [comment]
It's not broken. I can see quite a few new users registered today.
