### ISSUE TITLE
Telegram HTTP 400 Bad Request

### ISSUE THREAD

**Issue by gpproton** [traccar/traccar#4324]
I keep getting this error even after i've tested like 9 times and i don'd think it's a configuration issue because i've tested like a lot even the the direct url call and it works with my group.

This returns my group chat Id:
```
https://api.telegram.org/bot<botid>:<api-key>/getUpdates
```
And when in do this 

``````````````
 curl -X POST "https://api.telegram.org/botbot<botid>:<api-key>/sendMessage" -d "chat_id=-<group-chatid>&text=my sample traccar alert"
``````````````
I get this response and my message appears on group.

`````````````
{"ok":true,"result":{"message_id":7,"from":{"id":<botid>,"is_bot":true,"first_name":"group_username","username":"mygroup_bot"},"chat":{"id":-<group-chatid>,"title":"group_username","type":"group","all_members_are_administrators":true},"date":1558957634,"text":"my sample traccar alert"}}
`````````````

But for Traccar this is what i below in log file, always. and appreciate a response if anyone have a solution.

````````````````
2019-05-27 12:36:00  WARN: Telegram API error - HTTP 400 Bad Request - BadRequestException (...)
````````````````

**Comment by vitormarcelino** [comment]
Same issue.

**Comment by tananaev** [comment]
Just tested Telegram notifications and they are working correctly. Not sure what the issue is. Possibly it was already fixed at some point.
