### ISSUE TITLE
when i choose bing map (road view),the web window is blank

### ISSUE THREAD

**Issue by eclipseorc** [traccar/traccar#4326]
i have choosed the bing map(road view) in website on admin role
but the web window got blank.
how can i solve this problem

**Comment by tananaev** [comment]
Have you configured Bing Map key in the server settings? In future please ask questions like this on forum, not here.

**Comment by eclipseorc** [comment]
in forum, nobody will answer the question!
well ,i asked in here.
Bing Map Key already setting,but i can't confirm that is correctly.
follow this:
<entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>Bing Maps</entry>
    <entry key='geocoder.url'>https://cn.bing.com/api/maps/mapcontrol</entry>
    <entry key='geocoder.key'>AmpAp5nLWqLnwwHltaHBwN7reZGj99yI3IXbNeLvtKlOvblPV8bEo_qYRLDU-ute</entry> 

thank u again!

**Comment by eclipseorc** [comment]
`<entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>Bing Maps</entry>
    <entry key='geocoder.url'>https://cn.bing.com/api/maps/mapcontrol</entry>
    <entry key='geocoder.key'>AmpAp5nLWqLnwwHltaHBwN7reZGj99yI3IXbNeLvtKlOvblPV8bEo_qYRLDU-ute</entry>`

**Comment by tananaev** [comment]
What you have in the config doesn't make any sense, but it also has nothing to do with web app map layer.

I'm closing this thread. If you have any further questions, use forum.
