### ISSUE TITLE
Color of "pressed" Buttons

### ISSUE THREAD

**Issue by Mindreader12345** [traccar/traccar#4332]
Is it possible to change the color of "pressed" Buttons in the upper right corner in next Releases ?
It´s really difficult to see the difference between the grey and light grey Button...

**Comment by kirantpatil** [comment]
Hi,

Are you talking of [this](https://github.com/traccar/traccar/issues/2607) issue ?

Thanks.

**Comment by Mindreader12345** [comment]
Yes, I mean this Issue. I didn´t saw this. But it´s nearly 3 Years old !?

**Comment by alisaniko** [comment]
This has been discussed many times.
But the simple option is to define the element through the Google console, register your own adding! Important, and an easy way to add it to the app.css file

**Comment by tananaev** [comment]
Closing as it's not relevant with the release of the modern app.
