### ISSUE TITLE
Secure server(https) with domainname not showing tracker icons, server (http) on ip address showing tracker icons.

### ISSUE THREAD

**Issue by GroteVriendelijkeReus** [traccar/traccar#4337]
Hi All,

I'm a bit flabberguested as i am encountering the following issue. 
I've installed a Traccar server, 4.5 [Traccar documentation](https://www.traccar.org/linux/)
All is working fine and when i log on to the server on ip, i can see the device icons.
I've secured the server, [Traccar documentation](https://www.traccar.org/secure-connection/)
Again, all seems to work fine.
However, here comes the issue. When i visit the site via a domain, i don't see the device icon's.
If i connect through ip, I do.
Visitng via domain:  (not visible)
![visiting via the domain](https://user-images.githubusercontent.com/12912050/60050563-3a2efd00-96d1-11e9-86aa-01dee498b740.jpg)
Visiting through ip: (visible)
![visiting through ip](https://user-images.githubusercontent.com/12912050/60050564-3a2efd00-96d1-11e9-920d-e23187f52dd5.jpg)

I can't seem to find any errors on logs, whatsoever. Can someone point me in the right direction? This is pretty curious for me.

Thanks in advance.

**Comment by tananaev** [comment]
1. For questions use forum.
2. Don't duplicate threads.
