### ISSUE TITLE
GT02 tracker sends junk data to server ?! 

### ISSUE THREAD

**Issue by adrianTNT** [traccar/traccar#4340]
Can someone give me some tips please ? I am lost.
I got a GPS tracker that looks like a GT02 clone, I send the SMS command to send data to my server, then I listen on this port and the data looks like this (attached) ...
Can anyone tell if this looks like an encoding issue or maybe it sends some chinese characters ? Is there some decoding that I can try ?

```
Rg!r▒^

Rg!r▒;#

Rg!r▒▒x

Rg!r▒▒▒

Rg!r▒|

Rg!r▒_

Rg!r▒▒G

Rg!r▒▒

Rg!r▒▒▒

Rg!r▒"n▒

Rg!r▒,▒▒

Rg!r▒3o▒

Rg!r▒5
```

**Comment by tananaev** [comment]
Closing as a duplicate:

https://www.traccar.org/forums/topic/gt02a-clone-sends-strange-data-to-server/
