### ISSUE TITLE
Disadvantage with Panics of TT8750 + devices

### ISSUE THREAD

**Issue by rlamap** [traccar/traccar#4346]
The GPS data is arriving, but the events are not, for example panic does not arrive or generate data in the table tc_events, could you please give me a suggestion, thanks.

The position data is:
```
2019-07-04 19:39:07 INFO: [1bd2ffbe] id: 861074021696763, time: 2019-07-04 19:39:06, lat: -2.19217, lon: -79.90057, course: 0.0
```
The data that i capture when press sos(panic) is
```
00050210041b3fffff0000001d2020202020203836313037343032313639363736332001ca000000020004071301ffdfb91afb424f880000000013270600012c1000530c3519300c3519302f82000500000000000500000000000500000000c5d3
```
and when i use de https://www.traccar.org/hex-decoder/ get me this:
```
... binary data ...
```

**Comment by tananaev** [comment]
It's probably not supported yet.

**Comment by rlamap** [comment]
Ok, put in this case i use Traccar, is working GPS information, put not the sos(panic) events, You want to say that your events are not yet supported, right?

Because the device is the list

![Capture](https://user-images.githubusercontent.com/4149156/60736756-ba4d3200-9f1d-11e9-9710-36db4dc1dd53.JPG)

De igual forma te paso el equipo que indico

![image](https://user-images.githubusercontent.com/4149156/60736798-e4065900-9f1d-11e9-8195-31d4c4054a80.png)

**Comment by tananaev** [comment]
That's exactly what I'm saying. Those events are probably not supported for this particular device or protocol.
