### ISSUE TITLE
notificationTokens taking up users->attributes size limit

### ISSUE THREAD

**Issue by jaimzj** [traccar/traccar#4350]
In user table the attributes column has a type varchar(4000)

Firebase tokens  'notificationTokens' are currently getting stored under user->attributes, however when a single user account is being used by multiple devices the 4000 limit can be easily reached.

In such cases:
1. Adding new attributes does not work.
2. Also making changes to existing attributes with a value larger than previous value as well does not work.
3. New devices login in to the same user account won't get notifications as their notification Id wont be stored either.

Proposed Solution/Suggestion:
- Having a separate table for notificationTokens mapped to users->attributes column with just their reference Id.

**Comment by tananaev** [comment]
Yeah, it's a known issue. I think creating a separate table and API just for firebase tokens is a bit excessive. I think the issue can be simpler:

1. Store only limited number of tokens (for example, up to 5).
2. If token on same device is updated, replace old token.

**Comment by jaimzj** [comment]
Would it be good to implement that when a user log out their token is as well removed from the attributes? thus freeing up space for notifications to work for only logged in users?

**Comment by tananaev** [comment]
Yes, that also makes sense.

**Comment by tananaev** [comment]
Just implemented a limit to 3 device tokens (https://github.com/traccar/traccar-web/commit/468ed8b75c45b3d713449ced8466bab22227cb9f). It keeps only the last 3. I believe it should be enough for vast majority of the cases.
