### ISSUE TITLE
Feature Request: Calendar built into the TRACCAR

### ISSUE THREAD

**Issue by alisaniko** [traccar/traccar#4351]
I do not know how others will react, but it seems to me for those people who use the calendar, it would be great if you could create a calendar (schedule) directly in the web version, without using third-party programs.
Although maybe I missed it somewhere on the forum.

**Comment by tananaev** [comment]
Great suggestion. It should probably be in the web app repo though because it's a UI feature.

**Comment by alisaniko** [comment]
https://github.com/traccar/traccar/issues/4351

**Comment by alisaniko** [comment]
there was an offer https://github.com/traccar/traccar/issues/3803

**Comment by alisaniko** [comment]
I ran into the problem of having to make a large schedule for reading.
Then I wanted to try to create all this not in the morale, but in the Google calendar. But traccar did not want to be friends with google calendar

**Comment by tananaev** [comment]
It looks like there is a way to export data from Google Calendar:

https://support.google.com/calendar/answer/37111

It didn't work?

**Comment by alisaniko** [comment]
thanks Anton)

**Comment by alisaniko** [comment]
Hi Anton, the question arose again.  I'll try to explain.  I have 10 timelines with different periods in which the tracker should work.  and the time I need to change every 2-3 days.  that is, I need to create a schedule of on and off for tracking the tracker.  Could you tell me how to solve this problem?  this is now done through the calendar.  but maybe it is possible to enter data in the application itself or maybe it can be uploaded with some data to the server?  for example 7: 00-8: 00, 10: 00-12: 00 14: 00: 15: 00 16: 00: 17: 00, etc.

**Comment by alisaniko** [comment]
Hi Anton, the question arose again.  I'll try to explain.  I have 10 timelines with different periods in which the tracker should work.  and the time I need to change every 2-3 days.  that is, I need to create a schedule of on and off for tracking the tracker.  Could you tell me how to solve this problem?  this is now done through the calendar.  but maybe it is possible to enter data in the application itself or maybe it can be uploaded with some data to the server?  for example 7: 00-8: 00, 10: 00-12: 00 14: 00: 15: 00 16: 00: 17: 00, etc.
I'm not sure that this refers to the calendar section of course

**Comment by alisaniko** [comment]
I also forgot to indicate that I have 10 trackers and for each tracker there is a time and work schedule

**Comment by tananaev** [comment]
We've implemented an option to define a calendar directly in Traccar (https://github.com/traccar/traccar-web/commit/6975055fd388c813e730a9be65f6fc96ad5f213e). It's not a full calendar, but it handles most of the common cases.
