### ISSUE TITLE
Gps103 device is showing online but not sending data to server in GPRS mode

### ISSUE THREAD

**Issue by Maydi1122** [traccar/traccar#4353]

**Comment by jinzo** [comment]
Did you set it up with "fix" command? Or rather how did you set it up?

**Comment by Maydi1122** [comment]
@jinzo yes dear i have already set it up with fix command and is working properly in GPS mode but not it GPRS mode!
On traccar server my device status shows online but no marker or data is received from tracker

**Comment by jinzo** [comment]
What does the check command report? Also what port did you set it up at?
