### ISSUE TITLE
Optional custom CDN urls

### ISSUE THREAD

**Issue by edvalley** [traccar/traccar#4354]
I would like the used CDNs to be configurable, in a file not overwritten on update. I have a few ideas I want to discuss, that of course, will end up in a pull request. Thanks.

**Comment by edvalley** [comment]
All paths to scripts and styles loaded by load.js, can be stored on a JSON file on the web server, which can be processed by load.js. If that file is not found, or no URL for specific CDN, it can relay back on default value, already hard-coded in load.js. Comments and opinions are welcomed. Thanks...

**Comment by tananaev** [comment]
You can just change paths in the `load.js` directly. Why do you want another file? Also, this discussion probably belongs in the `traccar-web` repo.

**Comment by edvalley** [comment]
Sorry, I just noted I opened this issue on traccar instead of traccar-web, but I'm not sure if that "configuration", can also be done on traccar.xml and passed to the web server some way. Anyway, if this is the wrong place, just tell me and I'll move it there. Thanks again.

**Comment by edvalley** [comment]
Thanks. Will load.js change on update?

**Comment by edvalley** [comment]
Moving this to `traccar-web`.
