### ISSUE TITLE
When using Docker, Email Notification put internal Docker IP.

### ISSUE THREAD

**Issue by agungsijawir** [traccar/traccar#4360]
I think this is a kind of bug. When I set up notification using email, it works flawlessly.
But, my current setup is using Docker, the content of body email notification seems wrong.

```
Device: AGUNG-Z2PLAY
Status is unknown
Time: 2019-07-22 11:26:51
Link: http://172.23.0.4:8082?eventId=13 
```
Looking at the contents, line "Link: ....." shown the IP of internal docker. Can we display custom domain instead using internal docker IP? This should be configurable somewhere on settings.

**Comment by tananaev** [comment]
It's not a bug. You need to setup correct URL in the config file. For questions please use forum.

**Comment by agungsijawir** [comment]
thank you for your reply.
