### ISSUE TITLE
ITS Protocol minor update request

### ISSUE THREAD

**Issue by ashishnimrot** [traccar/traccar#4361]
```
$,NRM,MARK,V0.0.1,NR,01,H,351510091197148,000000000,1,23072019,062852,20.745541,N,78.598259,E,0.9,29.90,9,300.7,2.6,1.7,IDEA,1,1,0.0,4.1,0,18,404,22,ED03,1145,ED03,958,48,ED03,1147,30,ED03,4A9,27,ED03,B,27,1000,01,0.0,48288,000061,0,0,0,5BD6,*
```
Not Working in Traccar 4.5

**Comment by ashishnimrot** [comment]
Protocol documentation

[Wetrack140 communication protocol 2019-05.pdf](https://github.com/traccar/traccar/files/3421677/Wetrack140.communication.protocol.2019-05.pdf)
Do

**Comment by tananaev** [comment]
Have you tested latest source code?

**Comment by ashishnimrot** [comment]
Yes I have tested on latest source code but pattern partially parse. e.g. Network column has no data.

**Comment by tananaev** [comment]
Tested and it's supported in the current version.
