### ISSUE TITLE
How to connect Traccar Mobile Client app with the server ?

### ISSUE THREAD

**Issue by omarasimd005** [traccar/traccar#4362]
Hello People,

I have recently installed Traccar on my personal PC that is being acting as a server, I have created the account and added up the the mobile device with the identifier being mentioned in the traccar client application, I'm following the instructions and as told I'm trying to change the Server URL in the application with my public IP address it is giving me error which is "Please enter a valid http:// or https://". Kindly let me know the solution for it. In Logs of the client app location sending is failing.

**Comment by Turbovix** [comment]
The correct place to get help is in the forum!

https://www.traccar.org/forums/
