### ISSUE TITLE
Changing background image in login page and logo of the login form

### ISSUE THREAD

**Issue by omarasimd005** [traccar/traccar#4364]
Hello People,
Please advice how to change the background of the login page, as for testing purposes I have edited the release.html sheet with the code
```
<style> body { background-image: url("icon.png"); } </style>
```
This code was written under the body section but the issue is, when the page is loading image is being shown for 2 secs and as login form appears the background image disappears and shows the default grey background. Kindly let me know the solution for it, other than the above code I have used `<body background = "icon.png">` also but it shows the same error.

Secondly let me know how can I change the logo image being shown on the login form. I'm using the latest version of traccar

**Comment by tananaev** [comment]
Closing as duplicate.

https://www.traccar.org/forums/topic/changing-logo-in-login-form-and-background-of-the-login-page/

**Comment by omarasimd005** [comment]
Hi Tananaev,

I have posted in both the forums to get a reply as early as possible, I can see you have closed ticket. I'll really appreciate if you would give a solution for the query asked.

**Comment by tananaev** [comment]
Please never duplicate your threads. It won't help you get faster reply. The only thing it can get you is a blocked account.

GitHub is only for official Traccar development related discussion. If you have question about system or customization, forum is the right place to ask.

**Comment by omarasimd005** [comment]
Thank you Tananaev for the advice, i'll make sure it does not happen again. Is it possible for you to reply to the thread over the forum please.
