### ISSUE TITLE
Huabao Protocol  add ALARM_POWER_CUT

### ISSUE THREAD

**Issue by onethings** [traccar/traccar#4365]
Hi Tananaev,
    Could you add ALARM_POWER_CUT for Huabao protocol, 
here is the link of huabao protocol china version, on page 24 https://jt808.s3.amazonaws.com/7E-JT808-China_Version.pdf i found the alarm of power cut.

Thanks.

i'm not sure add on line 183 is ok or not
https://github.com/traccar/traccar/blob/9fb2e1f44a49f088f7239b2a2fcf0ff4533aa99c/src/main/java/org/traccar/protocol/HuabaoProtocolDecoder.java#L183

```
//MSG_LOCATION_REPORT = 0x0200; 

// 10 is Fuel power Line( 0 is fuel line power normal, 1 was cut)
else if (!BitUtil.check(status, 10)) {
            position.set(Position.KEY_ALARM, Position.ALARM_POWER_CUT);
        }

// 11 is Electric Power Line( 0 is fuel line power normal, 1 was cut)		
else if (!BitUtil.check(status, 11)) {
            position.set(Position.KEY_ALARM, Position.ALARM_POWER_CUT);
        }
```
screen shot of page 24
https://jt808.s3.amazonaws.com/powercut-alarm.png

**Comment by tananaev** [comment]
Please send a pull request and we'll take a look.

**Comment by onethings** [comment]
ok
