### ISSUE TITLE
when teltonika device is in gps sleep mode events are marked as invalid and vehicle appears to be offline

### ISSUE THREAD

**Issue by opendba** [traccar/traccar#4366]
Issue related to teltonika devices. 

I have a device that goes to GPS sleep after 2 days of inactivity. According to https://wiki.teltonika.lt/view/FMB_AVL_ID valid values for GPS/GNSS state are:
* 0 - OFF
* 1 – ON with fix
* 2 - ON without fix
* 3 - In sleep state

When device moves to sleep state, last coordinates are still send, but number of satellites is set to 0. traccar treats records with 0 satellites as invalid and this triggers vehicle offline event. I suggest to mark records as valid when device is in sleep mode

![image](https://user-images.githubusercontent.com/6765564/62010366-b0ac9800-b172-11e9-89ff-7e1ea2caa3ca.png)

**Comment by tananaev** [comment]
Invalid location has nothing to do with offline connection status.

**Comment by opendba** [comment]
Yes, but in my case device is configured to send location in case of inactivity every hour. Traccar is configured with 'status.timeout' set to 5400 (90min), when device is in sleep mode and starts sending "invalid" record I get offline/online event notification.

But none the less, I think that these kind of records should be considered valid (I'm also testing fix for this at the moment).

![image](https://user-images.githubusercontent.com/6765564/62010781-c1134180-b177-11e9-925b-325b201ea158.png)

**Comment by opendba** [comment]
Thanks, Anton for pointing in right direction! I got it after looking into the source :)

I see this kind of behavior, because my device does not keep connection open with the server and physically disconnects, which causes server to mark it as offline.
https://github.com/traccar/traccar/blob/9fb2e1f44a49f088f7239b2a2fcf0ff4533aa99c/src/main/java/org/traccar/MainEventHandler.java#L128

I will still submit PR for issue with record being marked as invalid in sleep mode.

Thanks for help.

**Comment by opendba** [comment]
From the manual on sleep modes:

4.2.2 Deep Sleep mode
While in deep sleep mode, FMB9YX sets GNSS receiver to sleep mode and turns off GSM/GPRS module (it is not possible to wake up device via SMS). Despite records with last known coordinate are being saved and send to AVL server (GSM/GPRS module is turned on to send data and after that it is turned off again), power usage is decreased to save vehicle’s battery.

...

4.2.3 Online Deep Sleep mode
In this mode device works as in Deep Sleep mode, but without deregistering from GSM network. GSM part stays powered, so this increases power consumption. In this mode, device should receive/send SMS and make/receive calls. Also not closes GPRS context, if previously opened.

so this all makes perfect sense.

**Comment by opendba** [comment]
for future reference, I can use status.ignoreOffline parameter to indicate that I don't want "offline" events to fire for particular protocol.
