### ISSUE TITLE
geofence issues

### ISSUE THREAD

**Issue by luigihs** [traccar/traccar#4370]
Hello guys!

I recently upgraded my Traccar to 4.5 ; However, the old version that used to have allows non-admin users to create geofence and link to the device they want, but I'm having issues now since 4.5 I can only create the geofence but cannot link to the device I want to apply  this rule. 

Does anyone can give me hint how to link the device to the geofence in 4.5 without making that user admin?

Thanks!

**Comment by tananaev** [comment]
Use forum for question. Closing as duplicate:

https://www.traccar.org/forums/topic/traccar-geofence-45-issues/

**Comment by luigihs** [comment]
but haven't got any answers for anyone.. could you please advice how to do it ? or you got rid of the 4.5 to only admin to link device to the geofence .. I don't understand why I can create geofence but cannot link to the device I want.  thanks

**Comment by tananaev** [comment]
If you didn't get answer there, it doesn't mean you can start duplicating your questions here. GitHub is only for development related discussions and confirmed bugs.
