### ISSUE TITLE
handle offline GPS and terminal info data in CONCOX GT06n 

### ISSUE THREAD

**Issue by swadhinchandpatro** [traccar/traccar#4375]
I can properly use the device when the device is online and sending heartbeat packet ( which contains ignition status info) and location packet periodically.

But when the vehicle goes under a tunnel or to an area where SIM signal is not reachable it stores the data in memory. When it again comes online it sends all those offline GPS location information to the server but it doesn't send ignition status information of the time it remained offline. 

So if the vehicle changed the ignition in between the time the device was offline, I am losing that data. 

Can anyone please help me figure out this problem. I couldn't find any solution . I think I described my problem clearly, but if you need any more info please ask. Thanks in advance

**Comment by tananaev** [comment]
Please use forum for questions.
