### ISSUE TITLE
Storing device session state

### ISSUE THREAD

**Issue by tsmgeek** [traccar/traccar#4380]
Is there a way to store a custom variable that can persist with the deviceSession?

I could just do a query for the last position but I was hoping to not hit the DB if possible.

eelink has an INDEX value which always increments with each packet received, I wanted to track this and check if the packets are missed or out of order, this would be more important with UDP delivery. If I could just store this on the deviceSession it would be great.

**Comment by tananaev** [comment]
Last position does not hit the database. We have it cached.

**Comment by tsmgeek** [comment]
After thinking about it more, idealy I want it in relation to the session as I also need to know if the session is new, I cant tell that from last position.

Could we have DeviceSession extends ExtendedModel or implement the functions of the ExtendedModel directly into it?

**Comment by deXetrous** [comment]
Hi @tsmgeek I want to work on this if that's fine. Can you please help me to get started and understand the code base?

**Comment by tananaev** [comment]
`DeviceSession` now supports custom parameters.
