### ISSUE TITLE
Atrack protocol decoder binary

### ISSUE THREAD

**Issue by pabl8garcia** [traccar/traccar#4381]
I am testing the protocol decoder for atrack devices, when single position format is sent it is working as expected, but when multiple positions are sent the protocol doesnt work for binary format because in the AtrackFrameDecoder and AtrackProtocolDecoder it is asking for the byte ',' to test if it is in ascii format.
this code line shows that it is asking for the byte '.'
In AtrackFrameDecoder
```
else if (buf.getUnsignedShort(buf.readerIndex()) == 0x4050 && buf.getByte(buf.readerIndex() + 2) != ',') {
```
in AtrackProtocolDecoder 
```
if (buf.getByte(buf.readerIndex() + 2) == ',') {
```
```
40502c37003c3f4a0003153f3f3f3f5d533e615d533e625d533e623f3f7617005b3f3f003f0200063f61000901002600000000073f073f00254349254d5600003f40505752003c3f4b0003153f3f3f3f5d533e635d533e645d533e653f3f763f005b3f3f00740200063f62000b01002500000000073f073f00254349254d5600003f40503f03003c3f4c0003153f3f3f3f5d533e655d533e665d533e693f3f773f005b3f3f00510200063f62000901002900000000073f073f00254349254d5600003f40503f56003c3f4d0003153f3f3f3f5d533e715d533e725d533e723f3f7c3f005b3f2900710200063f63000701002900000000073f073f00254349254d5600003f4050753f003c3f4e0003153f3f3f3f5d533e785d533e795d533e793f3f7f0e005b3f3700510200063f64000801002900000000073f073f00254349254d5600003f40503f79003c3f4f0003153f3f3f3f5d533e7d5d533e7e5d533e3f3f3f3f15005b3f3f00740200063f65000701002e00000000073f073f00254349254d5600003f40503f75003c3f500003153f3f3f3f5d533e3f5d533e3f5d533e3f3f3f3f25005b3f3f00510200063f65000701002c00000000073f073f00254349254d5600003f40506f3f003c3f510003153f3f3f3f5d533e3f5d533e3f5d533e3f3f3f3f5e005b3f5a007a0200063f66000701002800000000073f073f00254349254d5600003f40502c3f003c3f520003153f3f3f3f5d533e3f5d533e3f5d533e3f3f3f3f3f005b3f3f003f0200063f66000701002c00000000073f073f00254349254d5600003f
```
this is a multiple position sent by a device and is in binary format, so in this case is treated as text format and it is not decode correctly.
I think it is better to configure 2 differents ports in traccar server, one for binary and one for ascii because those protocols are differents and i think there is no reliable way to know if it is binary or ascii directly from the raw message.
the configuration from one port in binary (13059) is as an example 
```
AT$FORM=1,@P,0,"%CI%MV%BV"
```
the configuration from other port in ascii (XXXXX) is as an example 
```
AT$FORM=0,@P,0,"%CI%MV%BV"
```

**Comment by tananaev** [comment]
We already have too many ports. Unless there is absolutely no other way, we should use the same.

**Comment by pabl8garcia** [comment]
Thanks for answer.
Then you should only support one protocol for atrack devices, because supporting both you cant be realiable, in multiple position format sometimes it is decoded as text and it is a bug.

**Comment by deXetrous** [comment]
Hi @pabl8garcia I want to work on this if that's fine. Can you please help me to get started and understand the code base?

**Comment by tananaev** [comment]
I believe the binary format is already supported.

**Comment by juanpablo-garcia** [comment]
Thank, you do a great job
