### ISSUE TITLE
[Feature request] delete position API endpoint

### ISSUE THREAD

**Issue by maximilianloy** [traccar/traccar#4387]
I would like to request a DELETE operation for the positions endpoint with parameters to delete a positions based on id or timespan.

**Comment by deXetrous** [comment]
Hi @maximilianloy I want to work on this if that's fine. Can you please help me to get started and understand the code base?

**Comment by maximilianloy** [comment]
Sorry, I don't know the code base. You need to ask Anton.

Harshit Patel <notifications@github.com> schrieb am Sa., 24. Aug. 2019,
10:45:

**Comment by deXetrous** [comment]
Hi @tananaev  I want to work on this if that's fine. I need your help to understand the code base?

**Comment by tananaev** [comment]
What kind of help do you need?

**Comment by deXetrous** [comment]
I want to work on this feature request, but I am not sure how to proceed?

**Comment by tananaev** [comment]
Study the code, look at other APIs that already implemented.

**Comment by rovertzxd** [comment]
Hello @tananaev I have continued the work that Alexander started for adding the DELETE positions endpoint. my implementation requires all arguments and can only delete positions based on timespan. Please let me know if this is in good shape for merge, or if you have any additional requirements for this feature.

Thank you for your time!
