### ISSUE TITLE
g05 packet issue

### ISSUE THREAD

**Issue by ctpl0504** [traccar/traccar#4391]
We are receiving below packet from  the device.
```
2a48512c3836353230353033353331383033382c56312c3039353430372c412c313830382e303632322c4e2c30373933302e353633372c452c2032362e30362c3031392c3238303831392c464646464646464623
```
i.e (string)
```
*HQ,865205035318038,V1,095407,A,1808.0622,N,07930.5637,E, 26.06,019,280819,FFFFFFFF#
```
The packet is getting inserted but speed is inserted as zero.

Kindly confirm if it is firmware issue or wrong port as we identified extra space in "speed" attribute

**Comment by tananaev** [comment]
Are you using latest release?

**Comment by ctpl0504** [comment]
yes  ver 4.6

**Comment by tananaev** [comment]
Looks like the issue with extra space before speed.

**Comment by ctpl0504** [comment]
Kindly confirm  is it firmware issue or any other?

**Comment by tananaev** [comment]
I believe this should already be supported.
