### ISSUE TITLE
Request: improve notification information

### ISSUE THREAD

**Issue by d9394** [traccar/traccar#4400]
I want get more infomation from email or sms notification, such as last position or  last geolocation info, for all type notification include deviceOnline \ deviceOffline \ deviceUnknow ....
then I can use "Point: $position.Latitude°, $position.Longitude°<br>" in email template to show the infomation.

**Comment by tananaev** [comment]
Please use forum for questions.

**Comment by d9394** [comment]
but this a Feature Request, not a question.

**Comment by tananaev** [comment]
Status events don't have location info because and that's by design.

**Comment by d9394** [comment]
So, I hope you can redesign the status notificatiton
