### ISSUE TITLE
Nginx reverse proxy

### ISSUE THREAD

**Issue by jaynaidoopr** [traccar/traccar#4403]
Nginx. On this reverse proxy can you add a port for the devices like 5013 on the coñfig.Reason being I have 2 servers and can only use one port forwarder per ip on my router. Any assistance will help.

**Comment by tananaev** [comment]
1. Use forum for question. GitHub is only for development related discussions.
2. Never duplicate threads.

https://www.traccar.org/forums/topic/nginx-reverse-proxy/
