### ISSUE TITLE
Traccar Web Socket Error Windows Server 2016

### ISSUE THREAD

**Issue by mattfleaydaly** [traccar/traccar#4405]
Hey all,
I know this has already been asked in the past, however there seems to be no solution for me.

I am running Traccar on Windows Server 2016 with IIS, and it seems that I am getting a Web Socket Error.
I can't find any relevant error messages, however our devices don't live track on the map.

I've checked my firewall and ISP and everything says it should be working.
Any suggestions?

**Comment by Akito13** [comment]
Is IIS your reverse proxy?
Did you do [something like this](https://www.saotn.org/install-web-websockets-feature-iis-using-powershell/)?

**Comment by mattfleaydaly** [comment]
Hey @Akito13 cheers for the reply!
Already done this, but still no luck.

**Comment by mattfleaydaly** [comment]
Does anyone else have any ideas?

**Comment by pareliuss** [comment]
https://www.traccar.org/forums/topic/tutorial-how-to-secure-traccar-with-ssl-https-for-free-using-iis-and-lets-encrypt-on-windows-server/page/2/
