### ISSUE TITLE
Ldap search filter

### ISSUE THREAD

**Issue by napaster** [traccar/traccar#4409]
Доброго времени суток. Можно ли добавить возможность не только фильтровать принадлежность пользоваля к админской группе, но так же и в просто фильтре проверять принадлежность пользователя к определенной группе. 
В текущий момент выгребаются все пользователи ldap и просто имеется фильтр админ не админ.

**Comment by napaster** [comment]
Не возможно включить в поиск memberOf только 3 параметра в поиске uid mail cn

**Comment by VBP8501** [comment]
You can use the ldap.base option to only allow users from a certain AD group to be allowed access to traccar.
