### ISSUE TITLE
database: LdapProvider: impossible to setup STARTTLS connections

### ISSUE THREAD

**Issue by k0ste** [traccar/traccar#4410]
Traccar can't setup encrypted connection with LDAP server via STARTTLS (ldap:// on 389) or SSL (ldaps:// on 636 (deprecated)).

**Comment by VBP8501** [comment]
Yes it can, please see this forum post thread: https://www.traccar.org/forums/topic/error-logging-ldap-connection

@k0ste, @tananaev  I think this issue can be closed.
