### ISSUE TITLE
Laipac new message $AVRSP

### ISSUE THREAD

**Issue by AhmedDeffous** [traccar/traccar#4423]

**Comment by tananaev** [comment]
Please write proper title and description.

**Comment by AhmedDeffous** [comment]
i receive this Message $AVRSP,11280009,01*44     wat is   $AVRSP 
my GPS block and send alway same AVRMC message and never change date and time :


---------------------------------------------------------------
$AVRSP,11280009,03*46
---------------------------------------------------------------
 
$AVRMC,11280009,142858,r,3640.6701,N,00416.9235,E,0.00,0.00,110718,A,3596,65459,1,90,0,0,0,0,0*79
$AVRMC,11280009,142953,R,3640.6701,N,00416.9235,E,0.00,0.00,110718,A,3570,65459,1,90,0,0,0,0,0*5B
$AVRMC,11280009,143547,R,3640.6701,N,00416.9235,E,0.00,0.00,110718,5,3570,65459,1,77,0,0,0,0,0*2E
$AVRMC,11280009,143547,R,3640.6701,N,00416.9235,E,0.00,0.00,110718,i,3570,65459,1,77,0,0,0,0,0*72
$AVRMC,11280009,143547,R,3640.6701,N,00416.9235,E,0.00,0.00,110718,A,3570,65459,1,77,0,0,0,0,0*5A
$AVRMC,11280009,143547,R,3640.6701,N,00416.9235,E,0.00,0.00,110718,A,3570,65459,1,77,0,0,0,0,0*5A
$AVRMC,11280009,143547,R,3640.6701,N,00416.9235,E,0.00,0.00,110718,A,3570,65459,1,77,0,0,0,0,0*5A
$AVRMC,11280009,143547,R,3640.6701,N,00416.9235,E,0.00,0.00,110718,A,3570,65459,1,77,0,0,0,0,0*5A
$AVRMC,11280009,143642,R,3640.6701,N,00416.9235,E,0.00,0.00,110718,A,3544,65459,1,77,0,0,0,0,0*5B
$AVRMC,11280009,143742,R,3640.6701,N,00416.9235,E,0.00,0.00,110718,A,3544,65459,1,77,0,0,0,0,0*5A

**Comment by tananaev** [comment]
Why is the message sample in the title?

**Comment by AhmedDeffous** [comment]
this is the laipac finder message sample,  this message  $AVRSP,11280009,01*44
