### ISSUE TITLE
Response change on API - POST /commands/send/

### ISSUE THREAD

**Issue by lcsvcn** [traccar/traccar#4425]
Hello I would recommend to change the response of the  **POST API /commands/send/**

### What I expected?

Response to be the result of the command. I send the command and it receive at response I received the command result. It receives the send command, useless!

### What I need to do:

Send command using API and get response to send another that depends on the first one response. The device has a two-step authentication for unlock/lock.

### How it's done:
Send command using POST.
setTimeout and then after X time send a GET /api/positions/ and filter for deviceId
The response of the GET /api/positions/ I use to send the other command.

**Comment by tananaev** [comment]
The problem is that not all devices send responses, so it's really not possible to implement the way you want it to work. If your device does support command results, you should wait for the result notification.
