### ISSUE TITLE
Several potential ArrayIndexOutOfBounds Exception

### ISSUE THREAD

**Issue by ITWOI** [traccar/traccar#4442]
Hi all,

Our tool has found several potential ArrayIndexOutOfBounds bugs.

Most array accesses to the variable ```values``` in method [decodePosition](https://github.com/traccar/traccar/tree/v4.6/src/main/java/org/traccar/protocol/WatchProtocolDecoder.java#L141) are hardcoded, which may lead to ArrayIndexOutOfBounds exceptions in some corner cases. The array access at line  [163](https://github.com/traccar/traccar/tree/v4.6/src/main/java/org/traccar/protocol/WatchProtocolDecoder.java#L163) is an example.  There are nine array accesses by ```index++```in the method. 

Similarly, in method [```decodeCan```](https://github.com/traccar/traccar/tree/v4.6/src/main/java/org/traccar/protocol/Gl200TextProtocolDecoder.java#L591), the array accesses to variable ```values``` contains more hardcoded cases. For example, from lines [599]( https://github.com/traccar/traccar/tree/v4.6/src/main/java/org/traccar/protocol/Gl200TextProtocolDecoder.java#L599) to [602](https://github.com/traccar/traccar/tree/v4.6/src/main/java/org/traccar/protocol/Gl200TextProtocolDecoder.java#L602). Moreover, array accesses at lines [605](https://github.com/traccar/traccar/tree/v4.6/src/main/java/org/traccar/protocol/Gl200TextProtocolDecoder.java#L605) to [745](https://github.com/traccar/traccar/tree/v4.6/src/main/java/org/traccar/protocol/Gl200TextProtocolDecoder.java#L745) contains many conditions like ```if (BitUtil.check(reportMask, 21) && !values[index++].isEmpty()) {```, which may unexcepily increase the ```index``` and causes exceptions. There are 42 array accesses by ```values[index++]``` in the method.

Thanks.

**Comment by ITWOI** [comment]
Hi, we have reported the bugs a while ago would you please take a look and confirm if they are real bugs. We have been conducting an experiment to measure the accuracy of our static checker. We would be deeply appreciated if you can provide some feedback!

**Comment by tananaev** [comment]
Closing as not specific bug details provided.
