### ISSUE TITLE
Geocoder Geocoder network error

### ISSUE THREAD

**Issue by metacreo** [traccar/traccar#4446]
```xml
    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>nominatim</entry>
    <entry key='geocoder.url'>https://nominatim.openstreetmap.org/reverse</entry>
```
```
WARN: Geocoder network error - HTTP 403 Forbidden - ForbiddenException (... < JsonGeocoder:107 < ServerResource:57 < ...)
```
console:
```
root@myhostname:/opt/traccar # curl 'https://nominatim.openstreetmap.org/reverse?format=json&lat=54.686922&lon=25.290683&addressdetails=1'
```
Response OK city, street, etc...

Problem is traccar not sent user-agent in request.

console:
```
root@myhostname:/opt/traccar # curl -A '' 'https://nominatim.openstreetmap.org/reverse?format=json&lat=54.686922&lon=25.290683&addressdetails=1'
```
Response:  Access blocked

**Comment by tananaev** [comment]
Sounds like an issue with Nominatim server, not Traccar.

**Comment by metacreo** [comment]
Почему? Их сервер требует user-agent и это нормально.
Если запрос без агента, ответ сервера:
<h1>Access blocked</h1>
<p>You have been blocked because you have violated the
<a href="https://operations.osmfoundation.org/policies/nominatim/">usage policy</a>
of OSM's Nominatim geocoding service. Please be aware that OSM's resources are
limited and shared between many users. The usage policy is there to ensure that
the service remains usable for everybody.</p>
<p>Please review the terms and make sure that your
software adheres to the terms. You should in particular verify that you have set a
<b>custom HTTP referrer or HTTP user agent</b> that identifies your application, and
that you are not overusing the service with massive bulk requests.</p>
<p>If you feel that this block is unjustified or remains after you have adopted
your usage, you may contact the Nominatim system administrator at
nominatim@openstreetmap.org to have this block lifted.</p>

**Comment by IronVV** [comment]
I confirm this problem. I tried to change geocoder.url:
<entry key='geocoder.url'>https://nominatim.openstreetmap.org/reverse</entry>
or
<entry key='geocoder.url'>https://nominatim.openstreetmap.org/reverse?</entry>
or
<entry key='geocoder.url'>https://nominatim.openstreetmap.org/reverse.php</entry>
or
<entry key='geocoder.url'>https://nominatim.openstreetmap.org/reverse.php?</entry>

Don't working. The problem appears relatively recently. I did not make any changes before this problem.

**Comment by IronVV** [comment]
Maybe probleme with java? v11.0.4 not working corectly with TLS 1.3?
I have certificate from letsencrypt TLS 1.3. Openstreetmap using letsencrypt TLS 1.2.
Maybe this is the problem?

**Comment by metacreo** [comment]
Ни хотите, как хотите :)
Here is my 10min solution:
https://www.traccar.org/forums/topic/geocoding-reverse-problem/#post-47739

**Comment by IronVV** [comment]
Doesn't work for me, but maybe help for other.

**Comment by metacreo** [comment]
To perform this, you need some skills of webserver administration and need understand how all processes work. I can try help you, but I need to known what exactly not work. Please write to traccar forum in topic https://www.traccar.org/forums/topic/geocoding-reverse-problem/ describe more what not work for you.
