### ISSUE TITLE
streaming gps data from flespi using retranslator to traccar getting double in gps speed

### ISSUE THREAD

**Issue by theinhtitenyo** [traccar/traccar#4450]
![Screenshot_5](https://user-images.githubusercontent.com/56152430/69706015-29256480-1125-11ea-82e6-311f21d980f9.jpg)

Hi,
I attached the screenshot of gps speed having over 174 km/hr when we stream gps data from flespi to traccar. The real speed is only 94 km/hr when I check at flespi and other gps platforms.  Traccar port I use is 5167(retranslator) and it has some issue with speed. Traccar version is latest 4.6.

**Comment by tananaev** [comment]
Are you sure you are using 4.6? It's already been fixed in eedf41bb641a8429d3bfe624d9dcbbd543eec494.

**Comment by theinhtitenyo** [comment]
Yes, I am sure I am using 4.6. I think you are giving me 5149(flespi) protocol. I am talking about flespi retranslator, port no. 5167.

**Comment by theinhtitenyo** [comment]
> 
> 
> Are you sure you are using 4.6? It's already been fixed in [eedf41b](https://github.com/traccar/traccar/commit/eedf41bb641a8429d3bfe624d9dcbbd543eec494).
Yes, I am sure I am using 4.6. I think you are giving me 5149(flespi) protocol. I am talking about flespi retranslator, port no. 5167. Can you please check retranslator protocol?

**Comment by tananaev** [comment]
Would need protocol documentation to check against.
