### ISSUE TITLE
How to convert from WGS-84 to GCJ-02?

### ISSUE THREAD

**Issue by CongQing-0719** [traccar/traccar#4451]
How to convert from WGS-84 to GCJ-02?
GCJ-02 is used in China map service. If the custom map url option is set to China map url, the location displayed on the map is not the actual location.
How do I convert WGS-84 to GCJ-02 for use in China?
Chinese map url (Chinese)
```
https://webrd01.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x={x}&y={y}&z={z}
```
China map url (English)
```
https://webrd01.is.autonavi.com/appmaptile?lang=en&size=1&scale=1&style=8&x={x}&y={y}&z={z}
```

**Comment by tananaev** [comment]
I know it's an old thread, but we finally added GCJ-02 support:

https://github.com/traccar/traccar-web/commit/f71884a29993772f49135d118f29d4f5a9c48564
