### ISSUE TITLE
New protocol in kidswatch

### ISSUE THREAD

**Issue by measaura** [traccar/traccar#4458]
Hi,

I found a new protocol which I can't find any match in Traccar. Previously the KW06 watch from Unikom (http://www.unikom-tech.com/index.php?m=goods&a=details&content_id=142) is using the standard Kidswatch protocol (`[3G*device id*len*command]`). Earlier this month I bought several new KW06 to use with Traccar but it sends something like `AQSH+...`. However, this device still works with SE Tracker 2 app when I switch back to their server.

Anybody knows what protocol or encryption used?

**Comment by tananaev** [comment]
Please use forum for questions.
