### ISSUE TITLE
Teltonika MTB 100 support 

### ISSUE THREAD

**Issue by durduliu2009** [traccar/traccar#4461]
Hello, 
Is there any plan to add support for Teltonika MTB 100 device ? (default port 11919) 
https://teltonika-gps.com/product/mtb100/#downloads
https://wiki.teltonika.lt/view/FMB_AVL_ID

Many thanks in advance

**Comment by tananaev** [comment]
Duplicate of the forum thread:

https://www.traccar.org/forums/topic/teltonika-mtb-100-support/
