### ISSUE TITLE
GM02E or GT06 mini Chinese Model Not Working 

### ISSUE THREAD

**Issue by mukesh008** [traccar/traccar#4462]
Device Also know as GT06 mini , EV02 in markert.
User Manual  - https://drive.google.com/file/d/1eg26rNBHezt5_hgjhQ8SO25_kh8SRdQA/view
Protocol - https://drive.google.com/file/d/1Q3xy-LHjpCpuScAI6DPIKEWL1X3IyLC1/view

I register a my Device to demo.traccar.org
With IMEI : 866551036956956
server,0,40.112.128.183,5023,0#

Device Not Showing Online.

but in Other Platform (GPSWOX) this devices working fine.
I Register This device as Concox GT06.  

Please help.

**Comment by tananaev** [comment]
For questions there a forum:

https://www.traccar.org/forums/

**Comment by tananaev** [comment]
By the way. GPSWOX uses Traccar, so if it works there, it should work here as well.

**Comment by mukesh008** [comment]
![not_online](https://user-images.githubusercontent.com/455829/71763376-4fe37180-2f01-11ea-82b8-7cb6ccb5f42b.PNG)
![sms](https://user-images.githubusercontent.com/455829/71763377-4fe37180-2f01-11ea-8bba-0683a61e3a6c.jpeg)

Still Not Showing.
