### ISSUE TITLE
Issue with computed attributes and warnings

### ISSUE THREAD

**Issue by victor-butler** [traccar/traccar#4463]
Just discovered an issue with computed attributes, and no matter what variations of the formula I try, nothing seems to work. See below:

The problem is when we have an element that can have value of `0` **AND** is not reported with each record. Let's say we have `io30`:

**Case 1:**
`io30` is repored by the device as `100`;
Formula: `io30 ? io30 : null`
Computed attribute = `100`.
All OK.

**Case2:**
`io30` is repored by the device as `0`;
Formula: `io30 ? io30 : null`
Computed attribute is missing. That is because the formula `io30 ?` evaluates the `0` as `null` and the returned value is `null`.

**Case3** - modifying the above formula to treat the `0` as valid value:
`io30` is repored by the device as `0`;
Formula: `(io30 || io30 ==0) ? io30 : null`
Computed attribute = `0`. This formula works when the `io30` is being reported.

However, with the formula in **Case3** if `io30` is not reported I get warning message in the traccar log:
`WARN: Attribute computation error - org.traccar.handler.ComputedAttributesHandler.computeAttribute@102![0,5]:`

So the problem is:
With the formula in **Case2**, there is no warning message but if `io30 == 0`, then the computed attribute is not recorded.
With the formula in **Case3**, if `io30 == 0` the value is recorded but I get a warning message.

This is what I also tried but does not work:
`io30 != "" ? io30 : null`
`!empty(io30) ? io30 : null`
`io30 ? (io30 != "" ? io30 : null) : null`
`if( io30 || io30 == 0 ) { io30; else null; }`

It seems it's not the formula but the fact that Traccar treats the `0` when evaluated as `null`;

**Comment by tananaev** [comment]
It would be nice if you formatted your comment with proper markdown. It's very hard to read this blob of text and formulas.

**Comment by victor-butler** [comment]
Yes, Anton...trying to do this now...I am not familiar with Github comments.

**Comment by tananaev** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by victor-butler** [comment]
Ok, should be better now, markdown is similar to Stackoverflow and Traccar forum...

**Comment by tananaev** [comment]
Traccar uses JEXL, so I guess that rule is coming from there:

https://commons.apache.org/proper/commons-jexl/

**Comment by victor-butler** [comment]
Yes, I have reviewed JEXL syntax in detail while trying to troubleshoot the issue with the formula BUT, I cannot see any reference there that `0` == `null`. 

I have also tried the `empty` function as per JEXL syntax like so: `!empty(io30) ? io30 : null`. `0` is still treated as `null`.

Can you confirm that the value `0` is treated as `null` according to JEXL syntax?

**Comment by esdan7** [comment]
Hi Anton,

Still no solution for this issue?

**Comment by tananaev** [comment]
Solution for what? Traccar uses JEXL. There is no other magic on Traccar side.

**Comment by esdan7** [comment]
A solution for the case where the attribute value is 0. If io30 = 0, JEXL evaluates io30 as false in this case `io30 ? io30 : null`. 
`!empty(io30) ? io30 : null` is also false.
This is obviously a problem, because the attribute is not empty.

**Comment by tananaev** [comment]
You can probably use less/greater comparison as a workaround.

**Comment by victor-butler** [comment]
@tananaev, the problem with this issue is not the comparison operator but the fact that JEXL (or Traccar) evaluates the `0` value as `null`. There is a way to solve this problem (see above) but if the attribute is not reported by the device then Traccar throws a warning error for EVERY data packet sent by the device.
If you have a suggestion of particular evaluation statement to use, let me know and I will test it out. 
But until then I think it might be a good idea to keep this issue open - someone might find a solution for it.

**Comment by tananaev** [comment]
Have you tried `io30 != null`?

**Comment by victor-butler** [comment]
Hey Anton,
sorry I was on holiday!
I just tired your suggestion with the following expression `io30 != null ? io30 : null`, as suggested earlier.

If io30 is not reported I still get the same warning in the log:

`WARN: Attribute computation error - org.traccar.handler.ComputedAttributesHandler.computeAttribute@102![0,5]: 'io30 != null? io30 : null;' undefined variable io30 - Variable (... < ComputedAttributesHandler:102 < *:113 < BaseDataHandler:27 < ... < *:29 < ... < *:29 < ... < *:29 < ... < GeocoderHandler:90 < ...)`

So unfortunately the issue persists.

**Comment by tananaev** [comment]
I don't know if there's any workaround for this. I guess that's just how JEXL works.

**Comment by tananaev** [comment]
Then it can break other expressions where number is expected.

**Comment by victor-butler** [comment]
Then what about edit the `0` variable both on the input and output:
`if(variable == 0){ 
    string = variable; //convert the 0 to string
    //JEXL doing its thing here, this time avoiding to evaluate 0 == null
}else { 
    //for any other case where the variable is different than 0 proceed as usual
}`

And on the output:
`if(JEXL_variable_output == 0){ //only the JEXL output is 0
    number = JEXL_variable_output; //convert the 0 string back to number again
}`

This logic might create an issue only if JEXL currently can (under some conditions) output a `0` value as string but given what I have seen about JEXL I doubt it.

**Comment by tananaev** [comment]
I understand that it's possible to handle, but I'm talking about all existing expressions. It will break backward compatibility.
