### ISSUE TITLE
Add logging for LDAP(s) connection

### ISSUE THREAD

**Issue by VBP8501** [traccar/traccar#4465]
See this forum thread: https://www.traccar.org/forums/topic/error-logging-ldap-connection

Currently, no output is given when the ldap connection failed.

**Comment by tananaev** [comment]
Is this a feature request or is it something you want to work on? Contributions are always welcome.

**Comment by VBP8501** [comment]
I see this more as a request for bugfix than a feature request. 

I don't have a java dev environment set up so contributing is difficult

**Comment by tananaev** [comment]
As far as I can see, we do log all the errors that we can catch.
