### ISSUE TITLE
Feature Request :  Notification for Critical errors in traccar

### ISSUE THREAD

**Issue by jaimzj** [traccar/traccar#4467]
A feature where admin users can set a notification for critical errors or warning (Configurable by the admin) in config file. Specially errors that makes traccar unstable or non operational.

From the many errors that are being logged into the log file. One such example error/warning would be 👍 

> 2020-01-13 00:00:02  WARN: Failed to store position - The table 'tc_positions' is full - SQLException

In the above case which is just one example where traccar service continues to run and is unable to store data thus leading to loss of tracking data.

And many other errors or warnings such can be helpful to the admin.

Use Case :  It will help make admin's aware that their traccar service is at that moment unstable or not working at an optimal level. Whenever there is criticial warnings or issues with traccar service/database etc.

Example demo servers sometimes have disk storage full issues (In such cases it could help the admin have this information as it happens).

**Comment by tananaev** [comment]
For the issue with storage, we now have an option to get storage info as a part of `/api/server` request. You need to be logged in as an admin.

You should really track usage and get a warning before there's no storage at all.
