### ISSUE TITLE
No datbase indexes in liquidbase 4+ schema

### ISSUE THREAD

**Issue by neuharthr** [traccar/traccar#4468]
I have noticed that the liquidbase 4+ files do not have any indexes created on the new tables (tc_*). I confirmed this as well by looking at my Postgres install and did not see any indexes in the database either. Was this intentional or am I missing something? I am using Traccar v4.6.

**Comment by neuharthr** [comment]
I have manually added the 2 missing indexes from the previous version and things seem to be performing better. Here is the SQL used:
CREATE INDEX position_deviceid_fixtime ON public.tc_positions USING btree (deviceid, fixtime);
CREATE INDEX user_device_user_id ON public.tc_user_device USING btree (userid);

**Comment by tananaev** [comment]
Fixed the problem. Thanks for reporting it. I wonder why it wasn't discovered earlier.
