### ISSUE TITLE
ServletHelper: IndexOutOfBoundsException at remoteAddress.substring()

### ISSUE THREAD

**Issue by ilockit-CFR** [traccar/traccar#4473]
I got an IndexOutOfBoundsException as I tried the new logging method from Traccar 4.7, because there was no additional data at the remoteAddress string. So the remoteAddress.indexOf(",") returned -1.

I solved the issue with:
```
return remoteAddress.substring(0, remoteAddress.indexOf(",") == -1 ? remoteAddress.length() : remoteAddress.indexOf(",")); // removes the additional data
```

**Comment by tananaev** [comment]
Fixed, thanks.
