### ISSUE TITLE
"OmnicommMessageOuterClass does not exist" error while compiling v4.7 source code

### ISSUE THREAD

**Issue by rakz123** [traccar/traccar#4474]
In OmnicommProtocolDecoder.java file import "org.traccar.protobuf.OmnicommMessageOuterClass;" has error while building and compiling the Traccar  v4.7 source code . As no such file exist in the described location. 

Note : No file has been edited or modified, this error occurs on first compilation of source code. 

![traccar_error](https://user-images.githubusercontent.com/36769190/73158004-b4f94400-4108-11ea-8240-470531a24b6b.JPG)

**Comment by tananaev** [comment]
Compile using maven or gradle.
