### ISSUE TITLE
Sinotrack ST-901A+ protocol

### ISSUE THREAD

**Issue by PeteYorn** [traccar/traccar#4475]
I'm having some problems with Sinotrack ST-901A+.

If you send:

-     SMS1:7100000
-     SMS2:8040000 45.112.204.217 8800
-     SMS3:8030000 APN APNuser APNpassword
-     SMS4:8050000 60
-     SMS5:8090000 600
When they are configured to www.sinotracker.com / 45.112.204.217 they work well.
They send every 60 seconds when ignition is ON and every 600 seconds when OFF.

When you send the same commands but to your traccar server just replacing:

-     SMS2:8040000 yourIP 5015

The equipments go crazy and try to send every 1 second when ignition is ON and every 60 seconds when OFF.
To me this seems clearly that the huabao protocol is not fully compatible with Sinotrack ST-901A+.

I also think it would be a good idea, since there are a lot of users using equipments from this supplier, to create 2 additional ports:

-     one for ST-901, ST-901M, ST-902, etc.
-     and another for ST-901A+, etc.

Thanks in advance

**Comment by tananaev** [comment]
Why is this in the GitHub for the server? If you are trying to say that the server is doing something incorrectly, you need to provide evidence of that. If you are not sure, you shouldn't post on GitHub. Use forum instead. Closing this for now until information is provided.

**Comment by PeteYorn** [comment]
I've posted this here because this is protocol related.

**This is what happens in Traccar:**
Below you can see the behaviour I described when ignition is ON (please see that devicetime and fixtime are almost every second despite the configuration for every 60 seconds):
![sinotrack_error1](https://user-images.githubusercontent.com/2798184/73202542-2bab3700-4133-11ea-8d75-4c2944bb4ad5.jpg)

In this image below you can see the behavior when ignition is OFF, sends every 60 seconds when it should be every 600 seconds:
![sinotrack_error2](https://user-images.githubusercontent.com/2798184/73202557-3239ae80-4133-11ea-8efe-f73bb0fe3f4c.jpg)

**This is what happens in Sinotrack server:**
Now the same device with exact same configurations on Sinotrack server with the expected behaviour, sends every 60 seconds when ignition is ON and sends every 600 seconds when ignition is OFF:
![sinotrack_error3](https://user-images.githubusercontent.com/2798184/73203711-7cbc2a80-4135-11ea-8460-9b85e6fbc05e.jpg)




This is why I'm almost 100% sure this is a protocol issue.

**Comment by tananaev** [comment]
So, what exactly is wrong with the server?

**Comment by PeteYorn** [comment]
As you can see from the images on my previous post, the **same device** with the **same configuration** behaves differently in traccar and in sinotrack.

I think it has something to do with the way the traccar server is replying, with Acknowledges to the equipment.
I think that the equipments don't receive the correct ack from traccar server and keep trying to send their latest position, over and over again, every few seconds.
On the other hand, traccar server "thinks" it has sent the correct acks and the behavior keeps going on.

The protocol we are using is from huabao in the port 5015.
Maybe it is just different enough from ST-901A+ protocol to make this behavior.
The protocol for ST-901A+ is: https://drive.google.com/open?id=1u0C_hFm5vJYskVWS7Npd3vtFN5xmPSWk

**Comment by tananaev** [comment]
OK, let me know if you figure out what is wrong with response.

**Comment by PeteYorn** [comment]
Unfortunately I don't know what is wrong with it.
That is why I'm asking for your help and the rest of the community with this.
