### ISSUE TITLE
Support for temperature and humidity in GTFRI for gl200

### ISSUE THREAD

**Issue by jbx1** [traccar/traccar#4476]
Devices such as the Queclink GL300A send Temperature, Humidity and some other optional indicators as part of the GTFRI message. 

The Gl200TextProtocolDecoder PATTERN_FRI (line 178) does not seem to be currently supporting this information, so Traccar is ignoring this information. 

Manuals with protocol information for GL300A can be found here: 
http://www.queclink.com/sites/default/files/GL300A_Develop_Suit_A03V08_Eng_%28Doc_and_Tool%29_BQ5W.zip

**Comment by DeveloperKurt** [comment]
That's because it is GL200's decoder and GL200 does not support temperature or humidity, unlike GL300 series. I can try to add an encoder, decoder for GL300A though. 
@tananaev  Can you assign me to the issue?

**Comment by tananaev** [comment]
We don't assign issues, but feel free to work on it if you're interested. Pull requests are always welcome.
