### ISSUE TITLE
Wrapper log

### ISSUE THREAD

**Issue by cdmarioe** [traccar/traccar#4478]
Can't find wrapper.log en traccar 4.8, just tracker-server.log
![Captura](https://user-images.githubusercontent.com/17935222/74291045-4a93f680-4cf9-11ea-8e0a-22cb9e0d63e4.PNG)

**Comment by tananaev** [comment]
There is no wrapper log anymore. For questions please use forum, not GitHub.

**Comment by cdmarioe** [comment]
Sorry
