### ISSUE TITLE
Omnicomm: datetime issue and BufferOverflowException

### ISSUE THREAD

**Issue by Igreh** [traccar/traccar#4479]
Hi!
We're constantly receiving positions with fixed date (2009-01-01 07:00:00) from omnicomm trackers.
Other position data looks good. 
Also it looks like trackers do not receive acknowledgement  from server because they've been sending tons of data (actually useless data because of "empty" date) for already 2 days..
Moreover grepping for "error" in log shows thousands of repeated errors connected to omnicomm. One of them is BufferOverflowException. Log:
[omnicomm.log](https://github.com/traccar/traccar/files/4192116/omnicomm.log)

So, is all of these connected to server decoding issues or it's somehow connected to trackers itself?
PS version is 4.8
PPS no issues with other trackers communicating through EGTS

**Comment by tananaev** [comment]
Which version of the protocol do your devices use?

**Comment by Igreh** [comment]
Unfortunately I do not have direct access to devices. All the info I have for this moment is:
1. Device: omnicomm opti
2. Version of software installed: 308, release date: 15.11.2019

Other notice: some of these omnicomm devices send data with closer to today date (2020-01-13 ) and simple groupping sql
```
select devicetime, count(*)
from tc_positions
where deviceid = 20
group by devicetime, latitude, longitude
having count(*) > 1
```
 shows us that these pos entries are duplicated.

We'll try to update soft for latest release if it's available. I'll let you know if that helps

**Comment by tananaev** [comment]
There are two versions of the protocol. Traccar supports only second version.
