### ISSUE TITLE
Attributes not carrying over into home assistant

### ISSUE THREAD

**Issue by deanlongstaff** [traccar/traccar#4480]
Hi,

I am using monitored_conditions in home assistant. However the attributes "Satellites" and "Total Distance" dont work on the integration?

**Comment by tananaev** [comment]
How is this related to official Traccar source code?

**Comment by deanlongstaff** [comment]
I asked the home assistant guys and they told me to ask here. Other conditions work like "course" but not these two. Even if i can create a custom attribute to show the value of them that would work i think. But i don't know how.

**Comment by tananaev** [comment]
For questions there's forum.

**Comment by deanlongstaff** [comment]
I posted in multiple forums since November but no one is replying :(
