### ISSUE TITLE
http link SMS API - Whatsapp API

### ISSUE THREAD

**Issue by crottolo** [traccar/traccar#4481]
in the http request to api service, the character & is not accepted.

If you change the symbol & with %26 the traccar start.
if you leave & the server don't start.

the link for the api is:
```
https://api.mercury.chat/sdk/whatsapp/sendMessage?api_token=XXXXXXXXXXXXXXXXXXXinstance=L15816XXXXXXXXX
```
the documentation :https://docs.mercury.chat/?version=latest

if you implement this features, can you send message notification with whatsapp.

another provider very simple for send sms with API is https://www.waboxapp.com/

the documentation for simple CURL notification.

https://www.waboxapp.com/assets/doc/waboxapp-API-v3.pdf

thanks

**Comment by tananaev** [comment]
Have you checked the logs? Your XML is probably invalid.

**Comment by crottolo** [comment]
this is xml 
traccar clear installation


i have tried with %26 and & symbol.
with %26 the server as started with & simbol dont start.

<entry key='sms.http.url'>https://www.waboxapp.com/api/send/chat?token=MYTOKEN&uid=390355788XXX&to=39393587XXX&custom_uid=msg0001&text=Hello+dude</entry>



log  string:
2020-02-17 21:29:31  INFO: [3471f637: osmand > 37.46.85.161] HEX: 485454502f312e3120323030204f4b0d0a636f6e74656e742d6c656e6774683a20300d0a0d0a
2020-02-17 21:29:31  INFO: [3471f637] id: 1234567, time: 2020-02-17 21:29:23, lat: 45.69736, lon: 9.65370, course: 0.0, accuracy: 65.0
2020-02-17 21:29:32  WARN: SMS send failed - HTTP 403 Unauthorized - ForbiddenException (...)
 

    <entry key='database.driver'>org.h2.Driver</entry>
    <entry key='database.url'>jdbc:h2:./data/database</entry>
    <entry key='database.user'>sa</entry>
    <entry key='database.password'></entry>

<entry key='notificator.types'>web,sms</entry>
<entry key='notificator.sms.manager.class'>org.traccar.sms.HttpSmsClient</entry>
<entry key='sms.http.url'>https://www.waboxapp.com/api/send/chat?token=MYTOKEN%26uid=390355788XXXX%26to=393935873XXXX%26custom_uid=msg0001%26text=Hello+dude</entry>
<entry key='sms.http.template'>
{
        "phone":3939358XXXXX,
        "body":"HI"
}


</entry>




 <entry key='web.debug'>true</entry>
        <entry key='web.console'>true</entry>
<entry key='logger.enable'>true</entry>
        <entry key='logger.file'>/tmp/debug.log</entry>

</properties>

**Comment by tananaev** [comment]
I would recommend to read this:

https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents

**Comment by crottolo** [comment]
thanks! it's work
the solution is: <entry key='sms.http.url'>https://www.waboxapp.com/api/send/chat?token=mytoken&amp;uid=39035578XXXX&amp;</entry>

**Comment by cristianp431** [comment]
Hi Crottolo I have this error  when I try to send a test message. I don´t Know What Im doing wrong. the code is like you have also I have changed the code with the last solution that you gave us.

I hope you and sombody could help me

{"error":"Missing 'to' parameter"} - MessageException (HttpSmsClient:97 < NotificatorSms:48 < NotificationResource:63 < ...)

**Comment by cristianp431** [comment]
my  code is 

<entry key='sms.enable'>true</entry>
<entry key='notificator.types'>web,sms</entry>
<entry key='notificator.sms.manager.class'>org.traccar.sms.HttpSmsClient</entry>
<entry key='sms.http.url'>https://www.waboxapp.com/api/send/chat?token=[TOKEN]&amp;uid=573187xxxxx&amp;</entry>
<entry key='sms.http.template'>
{
        "to":57318xxxxxx,
        "custom_uid":"HI"
        "text":"HI"
}

**Comment by crottolo** [comment]
> Hi Crottolo I have this error when I try to send a test message. I don´t Know What Im doing wrong. the code is like you have also I have changed the code with the last solution that you gave us.
> 
> I hope you and sombody could help me
> 
> ```
> {"error":"Missing 'to' parameter"} - MessageException (HttpSmsClient:97 < NotificatorSms:48 < NotificationResource:63 < ...)
> ```

try https://www.waboxapp.com/api/send/chat?token=[TOKEN]&amp;uid=573187xxxxx&amp;to=57318xxxxxx&amp;custom_uid=ciaociao&amp;text=ciaociao 
bypass che sms template, and check if you can send message without template...
you can try this in postman
![Schermata 2022-08-02 alle 13 28 26](https://user-images.githubusercontent.com/16843729/182364069-b8d8415b-1055-46eb-afbc-b946f7a77a69.png)

**Comment by crottolo** [comment]
> 
"to":57318xxxxxx,
        "custom_uid":"HI", <---- missing semicolon
        "text":"HI"
