### ISSUE TITLE
Admin password must be changed before users added

### ISSUE THREAD

**Issue by bmsleight** [traccar/traccar#4482]
Tested in 4.8 and 4.7

traccar-linux-64-4.8.zip
traccar-linux-64-4.7.zip

If users are added, with password set and then admin password updated. Unable to login with new admin and users passwords. 
If admin password is change before users added, others users can be added with no errors. 

### Install Server
new server on ubuntu 

```
apt-get update
apt-get install unzip
wget https://github.com/traccar/traccar/releases/download/v4.8/traccar-linux-64-4.8.zip
unzip traccar-linux-64-4.8.zip
./traccar.run
systemctl start traccar
```

in webbrowser login at http://ip:8082

 ### Steps to Not reproduce Error 

1. Add users with passwords
2. Change admin password
3. Logout
4. Login - fails with admin or new users

 ### vs. Steps to reproduce Error

in webbrowser login at http://ip:8082

1. Change admin password
2. Logout
3. Add users with passwords
4. Logout
5. Login - success with admin and user

Happy to test further and reproduce logs.

**Comment by tananaev** [comment]
Just tested and I'm not able to reproduce the issue. If it really happens to you, you must have some customization in the server or the database.

**Comment by bmsleight** [comment]
Hmm - this was a fresh install
I tested it twice and got the same issue.

**Comment by tananaev** [comment]
I'm very skeptical about this issue. Why would one user affect others? Anyway, at this point I'm not able to repro it, so I don't think we can do anything about it.

**Comment by 2ecomp** [comment]
I have this same problem but it is related to strong passwords with characters + @% for example password "Tc+9810384@!" use it and try to login

**Comment by zorketRU** [comment]
> Я очень скептически отношусь к этому вопросу. Почему один пользователь влияет на других? В любом случае, на данный момент я не могу воспроизвести это, поэтому я не думаю, что мы можем что-то с этим поделать.

I have the same problem in version 5.1

**Comment by zorketRU** [comment]
> Я очень скептически отношусь к этому вопросу. Почему один пользователь влияет на других? В любом случае, на данный момент я не могу воспроизвести это, поэтому я не думаю, что мы можем что-то с этим поделать.

У меня такая же проблема на версии arm 5.1

**Comment by zorketRU** [comment]
> I'm very skeptical about this issue. Why would one user affect others? Anyway, at this point I'm not able to repro it, so I don't think we can do anything about it.

I installed on a single board pc version of arm, linux debian.
After installation, I can not change the password.
I change, then I go in - it does not enter.
Login only with admin password

**Comment by tananaev** [comment]
That's a known issue that's already fixed (https://github.com/traccar/traccar/commit/16e63283a2b64b2e1b490701c219beed653f2b17). Please next time don't comment on old closed threads.
