### ISSUE TITLE
Problem with filter.skipAttributes

### ISSUE THREAD

**Issue by DarioB92** [traccar/traccar#4500]
Hello, my tracker sometimes sends me invalid positions, so i added a filter.
However I want to know when power it's cutted, valid position or not. So I did:

`   <entry key='filter.enable'>true</entry>`
`<entry key='filter.invalid'>true</entry>`
`<entry key='filter.skipAttributes.enable'>true</entry>`
`<entry key='filter.skipAttributes'>alarm,ignition,result,status</entry>`  
But I receive

`  2020-03-14 17:10:21  INFO: Position filtered by Invalid filters from device: 91711**** `  
even when I cut power.
I am on Traccar 4.6 and 4.8
Are configs wrong? 
Actually filter.skipAttributes.enable it's not documented, but I read in discussion it's needed.
Thanks!

**Comment by tananaev** [comment]
For questions there is forum. For posting anything on GitHub please read contributing guidelines.

**Comment by DarioB92** [comment]
Question was to be polite. 
filter.skipAttributes does not works, enabled or not.
I posted same issue on forum 4 days ago, it's the only thread without answer

**Comment by tananaev** [comment]
If nobody answered you there, it doesn't mean it's ok to duplicate your question here.
