### ISSUE TITLE
Issue when building from sources (404 - Not Found)

### ISSUE THREAD

**Issue by burnout87** [traccar/traccar#4502]
Dear all,

I am building the Traccar back-end from sources with the following configuration:

- **IDE**: IntelliJ
- **OS**: Windows 10
- **JDK**: 11

I follow the procedure and create the _Run configurations_ as indicated, I run the application, the server seems to be correctly starting on the port (8082), but as I browse there, I get 404 error.

Any hints on what I could check? Perhaps some configuration...

Thanks

**Comment by tananaev** [comment]
Have you checked out the web app repo?

**Comment by burnout87** [comment]
I made a full recursive clone of the traccar repository, as indicated in the documentation.

I didn't get anything from the web-app repo (yet)

**Comment by tananaev** [comment]
There must be something wrong with the config then.

**Comment by burnout87** [comment]
I noticed the following entry within the deafult.xml config XML file
<entry key='web.path'>./web</entry>

Could this be the reason of the issue?

I read on the support page that this should be pointing to the directory that contains web interface files.

But, there's no such directory when clinging the repository. Am I missing something?

Thank for your help

**Comment by tananaev** [comment]
Which config are you using? You should be using `debug.xml` which defines correct location:
```xml
<entry key='web.path'>./traccar-web/web</entry>
```

**Comment by burnout87** [comment]
Yes, I am using that one.
By mistake, I copied fro the wrong file, that I opened while exploring the various project files.

Anyway, I don't have anything inside the traccar-web folder.

**Comment by tananaev** [comment]
If "traccar-web" is empty, it means that you haven't done proper recursive cloning.

**Comment by burnout87** [comment]
Ok, figured out the issue. As I had forked the repository, I forgot the submodules.

Thanks for the help
