### ISSUE TITLE
knowing its limits

### ISSUE THREAD

**Issue by gquiros** [traccar/traccar#4507]
Hello guys, I am new here, Latin American based of company

I am planning on installing TRACCAR, my hardware config would be as follows;

For the Database, it will be a dedicated server / bare metal (Located in Miami, so fiber would be showing low latency, below 50 Ms)

- 128GB DDR
- 500GB SSD or NVMe drives over raid
- 16 Cores / 32 Threads @ E5-2670 2.60 GHZ
- Guaranteed speed 1 GB up and down

**Datacenter in over 5 years have been down for me a total of 30 minutes (usually a fuse / breaker tripping...**

For the WEB / VPS on 3 different facilities for redundancy and doing load balancing:
- 20 GB SSD
- 2 or 4gb ram
- 2 vCores
- 100 Megs speed
(If need to change something, let me know)

My questions would be:
1. How many objects can I track ?
2. which is the best Database server to be implemented (MariaDB) ?
3. Stability: Which Linux/bsd distro should install???
4. I assume NginX over Apache, right ?

Based on the scenario I am describing, how many devices can I safely track before server starts getting sluggish and over heavy load 

Thanks for your help, guide and advise would be always appreciated

**Comment by tananaev** [comment]
Have you checked contributions guidelines before posting here? For questions like this we have the forum. GitHub is only for development related discussions.
