### ISSUE TITLE
Traccar server update from 4.1 to 4.7 and teltonika ble temperatures are no longer available

### ISSUE THREAD

**Issue by Gianfree182** [traccar/traccar#4508]
Hello everybody,

I have many Teltonika FMB125 control units that communicate with traccar and after updating the traccar server from version 4.7 to 4.1 the temperatures of the BLE probes of Teltonika are no longer visible. In particular io25, io26, io 27 and io28 are aggregated in a single temperature:

As seen in the java class snippet: TeltonikaProtocolDecoder.java
```java
private void decodeOtherParameter(Position position, int id, ByteBuf buf, int length) {
        switch (id) {
            case 1:
            case 2:
            case 3:
            case 4:
                position.set("di" + id, readValue(buf, length, false));
                break;
            case 9:
                position.set(Position.PREFIX_ADC + 1, readValue(buf, length, false));
                break;
            case 17:
                position.set("axisX", readValue(buf, length, true));
                break;
            case 18:
                position.set("axisY", readValue(buf, length, true));
                break;
            case 19:
                position.set("axisZ", readValue(buf, length, true));
                break;
            case 21:
                position.set(Position.KEY_RSSI, readValue(buf, length, false));
                break;
            case 25:
            case 26:
            case 27:
            case 28:
                position.set(Position.PREFIX_TEMP + (id - 24), readValue(buf, length, true) * 0.1);
                break;
....
```
In the older version of the server the four temperatures are kept divided. I need to have the same management as before ...

In the java class: TeltonikaProtocolDecoder.java (Old version) :
```java
private void decodeOtherParameter(Position position, int id, ByteBuf buf, int length) {
        switch (id) {
            case 1:
            case 2:
            case 3:
            case 4:
                position.set("di" + id, readValue(buf, length, false));
                break;
            case 9:
                position.set(Position.PREFIX_ADC + 1, readValue(buf, length, false));
                break;
            case 17:
                position.set("axisX", readValue(buf, length, true));
                break;
            case 18:
                position.set("axisY", readValue(buf, length, true));
                break;
            case 19:
                position.set("axisZ", readValue(buf, length, true));
                break;
            case 21:
                position.set(Position.KEY_RSSI, readValue(buf, length, false));
                break;
            case 66:
                position.set(Position.KEY_POWER, readValue(buf, length, false) * 0.001);
                break;
            case 67:
...
```
Thank you

Best Regards, Gianfranco

**Comment by tananaev** [comment]
Nothing is aggregated.

**Comment by Gianfree182** [comment]
Sorry, maybe I wasn't clear,
with the new logic io25, io26, io27 and io28 they are renamed to temp1, temp2, temp3 and temp4. And then these values ​​are overwritten by io72, io73, io74, because the same prefix, PREFIX_TEMP is used. So at the end of the switch we have at best 4 temperatures and not 8, because the temperatures of io25, io26, io27 are overwritten by io72, io73 and io74

> case 25:
            case 26:
            case 27:
            case 28:
                position.set(Position.PREFIX_TEMP + (id - 24), readValue(buf, length, true) * 0.1);
                break;
...
 case 72:
            case 73:
            case 74:
                position.set(Position.PREFIX_TEMP + (id - 71), readValue(buf, length, true) * 0.1);
                break;


Thanks and best regards

**Comment by tananaev** [comment]
You just need to update indexes to not overwrite those.

**Comment by geduxas** [comment]
> You just need to update indexes to not overwrite those.

hm.. @tananaev  it seams @Gianfree182 is correct, acording to that, dallas temp sensors will be saved in temp1-temp4, also BLE temp sesonrs will be temp1-temp4. So after saiving to database it will be not possible to determinate which is which.

**Comment by tananaev** [comment]
That's why I said we should use different indexes.
