### ISSUE TITLE
[Feature Request] Add device expiration date

### ISSUE THREAD

**Issue by mujeerhashmi** [traccar/traccar#4513]
The business model many companies adopt is based on device subscription rather than user subscription. For the support of such business model we need device expiration feature. After device expiration date the device should get disabled so that the user will not be able to see the device updates until the subscription is renewed. 
A system level device grace period, If the subscription is not renewed within grace period after device expiration then the device will be deleted from the platform.

**Comment by tshelver** [comment]
Can't you handle this from your subscription / accounting system via the Traccar API?

**Comment by mujeerhashmi** [comment]
This logic should be part of traccar is what i feel just like the way user expiration and user or device limit per user is handled already.

**Comment by kgrosvenor** [comment]
@mujeerhashmi in terms of subscription models, the main issue is when user wants to downgrade to less devices, since they are already written into the system with db relations

**Comment by mujeerhashmi** [comment]
> @mujeerhashmi in terms of subscription models, the main issue is when user wants to downgrade to less devices, since they are already written into the system with db relations

I am talking about a different business model here where every device will be charged for the subscription and not user subscription for a defined number of devices.

**Comment by tananaev** [comment]
I would argue that we should probably remove any expiration from the system. A billing system should be configured to use API. Traccar shouldn't implement its own system for something that already exists.

**Comment by mujeerhashmi** [comment]
But Traccar should facilitate a billing system/model, we do not want Traccar to generate invoices or keep track of payments & subscription history. But it should keep the data like registration date of the device on the platform and expiration date after which it will not be accessible to the user.

**Comment by tananaev** [comment]
I'm not sure I agree with that. Usually billing systems take care of that, including updating that information.

**Comment by mujeerhashmi** [comment]
We will otherwise create a dependency between billing system and traccar. I feel that is not a good idea. From the billing system point of view. They will not want to update the traccar device data either on subscription updates.

I would also like to know about the billing system which uses Traccar API already if any.

**Comment by tananaev** [comment]
Wouldn't you still have a dependency for subscription renewal?

**Comment by mujeerhashmi** [comment]
My billing system will keep track of the subscriptions. On renewals, If their is a provision for expiration date I will update them on Traccar platform. Right now I do not have such a provision to limit the users access to a device automatically.

**Comment by tananaev** [comment]
Why wouldn't your system disable device instead when subscription expire?

**Comment by mujeerhashmi** [comment]
> We will otherwise create a dependency between billing system and traccar. I feel that is not a good idea. From the billing system point of view. They will not want to update the traccar device data either on subscription updates.
This is the whole point.

**Comment by tananaev** [comment]
Sorry, but I don't understand the reasoning.

**Comment by mujeerhashmi** [comment]
Traccar has a provision to limit users access to the system based on expiration date then why not similarly have a provision for limiting users access to a device based on expiration date ?

I have looked into the forums but could not find a billing system that does what you suggest. We will have to have such a system otherwise.

**Comment by tananaev** [comment]
I think we are going in circles. I guess we can leave this here for now and see if anyone else is interested, but the argument is very weak so far.

**Comment by mujeerhashmi** [comment]
The argument is very simple, let me try to comprehend

- Traccar has a business model of User based subscription for particular no. of devices for a particular period. To support this you have the provision of user expiration & device limit.

- I am talking of supporting another business model in Traccar based on device subscription. which requires provision for device expiration. But you suggest this to be handled in billing software using APIs. In that case, with same arguments why not take out user expiration as well from the system & lay that responsibility on billing software ?

As an open source software Traccar should support multiple business models.

May be I have not completely understood the purpose of user expiration.I rest my case.

**Comment by tananaev** [comment]
I think you completely ignored what I said previously:

>  I would argue that we should probably remove any expiration from the system.

**Comment by mujeerhashmi** [comment]
OK. In that case for a proper business solution we need to have a billing software that integrates Traccar. Do we have one already or we need to find a billing software & integrate traccar?

**Comment by mujeerhashmi** [comment]
Also when running Traccar as a service business, you cannot expect the `manager` user to send you(`admin` user) the details of device/user registration for managing subscription/expiration. He will need these features of expiration to manage his customers. lest you need to configure the billing software integrated with traccar for the `manager` user as well. I strongly feel we will end up adding high dependency on having a billing software integrated with traccar to use traccar as a business solution.

**Comment by tananaev** [comment]
I don't understand this dependency argument. You still need to update the expiration date in your solution. What's the difference?

**Comment by mujeerhashmi** [comment]
People will not be able to manage subscriptions manually using excel sheet like programs. Not necessarily everyone has to have a billing software that integrates Traccar.

**Comment by tananaev** [comment]
OK, but I still don't see the difference. Let's say you have a monthly subscription. You have to go and update expiration date every month, or you can disable user/device once if user hasn't renewed. Am I missing something? Latter seems easier.

**Comment by mujeerhashmi** [comment]
Like said, This will facilitate the billing. After having initially entered the expiration date, I will have the luxury of updating the expiration date as & when the customer renews it, It may not be on regular basis. So even if I miss disabling the user/device, the system will have taken care.

**Comment by oluwatobi-roie** [comment]
Yesi agree with mujeershashmi. device expiry date should be a feature that can be included in the traccar application. 

Anton, i understand your idea in using API to disable unit once it is expired. but its much more healthier if the system automatically disables the unit, just as it would for a user. 

in conclusion, i am in support of adding expiry dates to unit on the platform.

**Comment by StarGPS** [comment]
I also join the guys and **add my vote to have the device with a create/expiry date**. I was really surprised when I found that the famous Traccar has not this feature, as all the Tracking Apps I used, have this option without any exception. The business model of user based plans is not suitable for small businesses and freelancers. For example, In my country I have customers that start with 1-3 devices then they add more devices from time to time, we are paid in yearly subscription per devices and it is done by cash most of the time and we manage subscriptions only by setting the expiry date on the tracking system we are using. I really wanted to start using the Traccar OPEN SOURCE solution and also contribute to its community as the best I can, however, without this feature, I wouldn't be able to manage my business as we used to, and as all the tracking businesses and customers are doing here, and we are not able to get a billing system to do this for us, as it wouldn't be affordable for us and also customers in my country don't like to use their credit cards for payments.

**Comment by axutech** [comment]
device based expiration is important feature, it's common feature of this kind of applications in general

**Comment by adadnc** [comment]
I'm not sure why you guys are asking for a feature that can easily be done with a few lines of code that disables your expired user, which you manage in your billing database, with Traccar API. 
Managing your billing system outside would even give you much more control than something within Traccar.

**Comment by ali-raza101** [comment]
@tananaev  Yes @mujeerhashmi is right. In most of the tracking companies the users have multiple devices which are subscribed on different months in a year. The renewal of these devices will obviously occur when the their subscription period expires usually one year. Now if traccar had this device expiration feature and tracking company is not very efficient at billing or don't have any modern billing/subscription system then device will be automatically disappeared from the user-account as the defined expiration date arrives. So even if the company by mistake missed renewal of a device then the user will contact the tracking company himself to renew his subscription in order to continue the services, by this way not a single device can be missed not even for 1 day. 👍 for the idea

**Comment by himsashu** [comment]
I suggest to add a column in user and device table for creationTime and expiryTime. The creation time is equally important. This will show when a user or device is created on the traccar.

**Comment by kjetilpp** [comment]
+1 om this. Maybe @tananaev can reconsider this feature? Looks like many users here want it 😃

**Comment by pepelillo** [comment]
I also vote for this feature.... hope this can be reconsidered
