### ISSUE TITLE
Technical characteristics of the vehicle

### ISSUE THREAD

**Issue by netluca1** [traccar/traccar#4521]
Hi I wanted to ask if it was possible to implement a function that I think is interesting.
My idea is to create a space or table dedicated to the media and its technical characteristics. example the tank capacity, Euro class, Weight, etc.
This should give us the possibility according to the medium used, knowing the capacity of the tank we can calculate the fuel consumed

**Comment by tananaev** [comment]
You can add those parameters to the attributes.

**Comment by netluca1** [comment]
@tananaev refers to a solution for few vehicles?
Because in a business context where the means are many and vary according to the medium I think it is difficult to manage them with the calculated attributes.
While having a table x each medium by selecting that medium we would have the data ready.
@tananaev could give you an example of how to use calculated attributes for fuel control

**Comment by tananaev** [comment]
I was not talking about computed attributes. I was talking about regular device attributes.
