### ISSUE TITLE
Monitoring traccar and process manager

### ISSUE THREAD

**Issue by britisharmy** [traccar/traccar#4524]
I am running traccar on a vps and i am concerned about memory usage and what happens when there is no more memory.

I would like to monitor memory usage and also be able to automatically restart if need be. What is the recommended process manager like PM2 but for java environment should one use?.

Also, what monitoring tool would you recommend?.

**Comment by jcardus** [comment]
You should use the forum.

In my case, I start the process with 3G heap size.
 
I'm starting to implement https://github.com/jmxtrans to send monitor data to cloudwatch (aws). 
I can share the configuration scripts when it's done.

Here's my procfile:
web: java -Xms3g -Xmx3g -Dcom.amazonaws.sdk.enableDefaultMetrics -javaagent:lib/jmxtrans-agent-1.2.6.jar=jmxtrans-agent.xml -jar tracker-server.jar conf/traccar.xml

**Comment by jcardus** [comment]
It's implemented. Works like a charm :-)

I made a pull request for it. You will need the jmxtrans agent.

Check the image.

Here's my configuration:

`<jmxtrans-agent>
  <queries>
    
    <query objectName="java.lang:type=OperatingSystem" attribute="SystemLoadAverage" resultAlias="os.systemLoadAverage"/>

    
    <query objectName="java.lang:type=Memory" attribute="HeapMemoryUsage" key="used"
           resultAlias="jvm.heapMemoryUsage.used"/>
    <query objectName="java.lang:type=Memory" attribute="HeapMemoryUsage" key="committed"
           resultAlias="jvm.heapMemoryUsage.committed"/>
    <query objectName="java.lang:type=Memory" attribute="NonHeapMemoryUsage" key="used"
           resultAlias="jvm.nonHeapMemoryUsage.used"/>
    <query objectName="java.lang:type=Memory" attribute="NonHeapMemoryUsage" key="committed"
           resultAlias="jvm.nonHeapMemoryUsage.committed"/>
    <query objectName="java.lang:type=Threading" attribute="ThreadCount" resultAlias="jvm.thread"/>

    
    <query objectName="org.eclipse.jetty.server.session:context=ROOT,type=defaultsessioncache,id=0"
           attribute="sessionsCurrent"
           resultAlias="traccar.sessionsCurrent"/>
    <query objectName="org.eclipse.jetty.server.session:context=ROOT,type=defaultsessioncache,id=0"
           attribute="sessionsMax"
           resultAlias="traccar.sessionsMax"/>
    <query objectName="org.eclipse.jetty.server.session:context=ROOT,type=defaultsessioncache,id=0"
           attribute="sessionsTotal"
           resultAlias="traccar.sessionsTotal"/>

    
    <query objectName="org.eclipse.jetty.io:context=*,type=connectionstatistics,id=0"
           attribute="connectionDurationMax"
           resultAlias="traccar.connectionDurationMax"/>
    <query objectName="org.eclipse.jetty.io:context=*,type=connectionstatistics,id=0"
           attribute="connectionDurationMean"
           resultAlias="traccar.connectionDurationMean"/>
    <query objectName="org.eclipse.jetty.io:context=*,type=connectionstatistics,id=0"
           attribute="connectionDurationStdDev"
           resultAlias="traccar.connectionDurationStdDev"/>
    <query objectName="org.eclipse.jetty.io:context=*,type=connectionstatistics,id=0"
           attribute="connections"
           resultAlias="traccar.connections"/>
    <query objectName="org.eclipse.jetty.io:context=*,type=connectionstatistics,id=0"
           attribute="connectionsMax"
           resultAlias="traccar.connectionsMax"/>
    <query objectName="org.eclipse.jetty.io:context=*,type=connectionstatistics,id=0"
           attribute="connectionsTotal"
           resultAlias="traccar.connectionsTotal"/>
    <query objectName="org.eclipse.jetty.io:context=*,type=connectionstatistics,id=0"
           attribute="receivedBytes"
           resultAlias="traccar.receivedBytes"/>
    <query objectName="org.eclipse.jetty.io:context=*,type=connectionstatistics,id=0"
           attribute="receivedBytesRate"
           resultAlias="traccar.receivedBytesRate"/>
    <query objectName="org.eclipse.jetty.io:context=*,type=connectionstatistics,id=0"
           attribute="sentBytes"
           resultAlias="traccar.sentBytes"/>
    <query objectName="org.eclipse.jetty.io:context=*,type=connectionstatistics,id=0"
           attribute="sentBytesRate"
           resultAlias="traccar.sentBytesRate"/>
    <query objectName="org.eclipse.jetty.io:context=*,type=connectionstatistics,id=0"
           attribute="sentMessages"
           resultAlias="traccar.sentMessages"/>
    <query objectName="org.eclipse.jetty.io:context=*,type=connectionstatistics,id=0"
           attribute="sentMessagesRate"
           resultAlias="traccar.sentMessagesRate"/>
  </queries>
  <outputWriter class="org.jmxtrans.agent.CloudWatchOutputWriter"/>
  <collectIntervalInSeconds>30</collectIntervalInSeconds>
</jmxtrans-agent>
`

**Comment by britisharmy** [comment]
Many thanks. I shall have a look.
