### ISSUE TITLE
H02 Support - ST901 Sinotrack

### ISSUE THREAD

**Issue by mikekoumas** [traccar/traccar#4526]
Hello guys I am struggling over a week to get my motorcycle GPS working but nothing yet.

I put my HASSIO-Traccar ip address on my GPS device and set it up to port **5013** as I read from the support page of TRACCAR for st-901 device.

I receive the following data on to the Traccar's LOGS (replace with * just to hide personal data)
```
**[20/Apr/2020:15:01:20 +0300] 400 -(213.***.***.***) *HQ,917*******,V1,084739,A,3506.8437,N,03***.5127,E,000.03,**0,200420,FBFFB9FF,000,00,0,0# (-)**
```

I do not receive anything else from the device or I may only see that.

What the "**400**" means after date and time of the log?
Please help me and get it working.
Thank you so much

**Comment by tananaev** [comment]
For questions there's forum:

https://www.traccar.org/forums/
