### ISSUE TITLE
Using a message broker to queue positions and events

### ISSUE THREAD

**Issue by parthibd** [traccar/traccar#4528]
Hi @tananaev . I want to integrate a message broker i.e RabbitMQ in Traccar server . My aim is simple , I want to listen for all positions and events regardless of any user roles or whether those notifications are added to traccar . I want to capture all positions and events , unbiased . I am lost looking for the place in the code to hook this . Can you please point me in the right direction ?

**Comment by dough29** [comment]
Hello !
Maybe you can do some magic with the `traccar.xml` file and `forward.enable` + `event.forward.enable` properties.
I use this to send positions & events to my home automation system (Jeedom).

**Comment by parthibd** [comment]
@dough29 Thank you for the suggestion! I actually haven't tried `forward.enable` but does it forward all events and positions regardless or user roles or whether a particular event has been enabled in a device ?

**Comment by dough29** [comment]
Yes :
- `forward.enable` forwards every position Traccar receives to `forward.url`
- `event.forward.enable` forwards every event (on/off, entering/exiting area, ...) Traccar receives to `event.forward.url`

**Comment by dough29** [comment]
I don't know if there is a full documentation on this but here are some starting elements : https://www.traccar.org/configuration-file/

**Comment by parthibd** [comment]
Thank you for the suggestions . Let me try them out .

**Comment by parthibd** [comment]
Thank you ! It worked :)
