### ISSUE TITLE
id of position always zero in json payload

### ISSUE THREAD

**Issue by parthibd** [traccar/traccar#4529]
When using `forward.url` with `json` , the id of the position object is always zero . Ex - 

```json
{"id":0,"attributes":{"batteryLevel":53,"distance":0,"totalDistance":5922.96,"motion":false},"deviceId":1,"type":null,"protocol":"osmand","serverTime":"2020-05-07T09:48:18.770+0000","deviceTime":"2020-05-07T09:48:15.000+0000","fixTime":"2020-05-07T09:48:15.000+0000","outdated":false,"valid":true,"latitude":21.1416013,"longitude":99.6410078,"altitude":0,"speed":0,"course":90,"address":null,"accuracy":2200,"network":null}
```

Here `id` is `0` . It should instead reflect the last insert id.  @dough29 @tananaev

**Comment by parthibd** [comment]
` addHandlers(
                pipeline,
                FilterHandler.class,
                GeocoderHandler.class,
                MotionHandler.class,
                CopyAttributesHandler.class,
                EngineHoursHandler.class,
                ComputedAttributesHandler.class,
                WebDataHandler.class,
                DefaultDataHandler.class);`

in this code if I switch positions of the last two handlers ,it solves my problem. Is this a bug ?

**Comment by tananaev** [comment]
Not a bug. The idea is that internal position id is irrelevant to an external server that you forward to.

**Comment by parthibd** [comment]
I understand now. Actually I am trying to use tracccar as a microservice that just collects data, and use a message broker or webhook to communicate. Are you planning to support any message broker anytime soon? If not, I can give it a try.

**Comment by tananaev** [comment]
No plan at the moment, as far as I know.
