### ISSUE TITLE
Different Data between tc_events and tc_positions

### ISSUE THREAD

**Issue by FerdinaKusumah** [traccar/traccar#4530]
Timezone in Asia/Jakarta, so it need to be plus 7 hour for debugging only

This is the data coming from tc_events, in this picture it is clear that the ignition on changes occur at 13:04 noon
![Screen Shot 2020-05-11 at 17 29 54](https://user-images.githubusercontent.com/19812460/81552242-5ef59700-93ad-11ea-8953-2b5ec2105343.png)

And one more data coming from tc_positions which displays ignition true data at 00:20 am.
How can data in positions differ from data in events.
![Screen Shot 2020-05-11 at 17 29 46](https://user-images.githubusercontent.com/19812460/81552364-93695300-93ad-11ea-9adc-a76a7991364a.png)

While the correct data is the data that comes in tc_events.
Is this a system error?

**Comment by tananaev** [comment]
Are you comparing fix time with server time? That would explain it.

**Comment by FerdinaKusumah** [comment]
Nop, that query used same date with device time.

**Comment by tananaev** [comment]
You need to consider server time as well because events are generated as the data coming in.

**Comment by FerdinaKusumah** [comment]
ok, if so what kind of time should I use to retrieve event data from the tc_position table?

Do I have to search based on servertime, devicetime or fixtime?

then how does traccar define each incoming event?

in the traccar documentation it is said that the traccar generates an event by looking at the previous data, if the previous data is the ignition is off and the current data is the ignition status is on.  then the traccar will generate the ignition on event right?

but by looking at the data above it is very clear that tc_event is generated in another way, so that it displays data that is different from tc_position, did I make a mistake in retrieving the data above?

**Comment by tananaev** [comment]
It's not really clear to me. The only clear thing is the data is coming in the wrong order (see the difference between server time and device time), which can mess up all the events.

**Comment by tananaev** [comment]
We now use position time for events, so hopefully this is resolved.
