### ISSUE TITLE
When edit "Account"/ "User", login field data is "blanked"

### ISSUE THREAD

**Issue by ehsolis1** [traccar/traccar#4541]
As decribed, but all context and story:
I am implementing traccar for my enterprise. I need login with "login" field in "Users" table, and store a valid email in "email" field, to send email reports.
When i edit an user, from admin session, email data is overwritten by login field data, and login field data is blanked.
Before modify:
![image](https://user-images.githubusercontent.com/66650830/84093026-b98b0e80-a9be-11ea-9e63-46e8f8077d81.png)
After modify:
![image](https://user-images.githubusercontent.com/66650830/84093166-138bd400-a9bf-11ea-8e5f-3800573f4e46.png)

After that, i edit traccar.xml file, adding this entry:
```
<entry key='database.loginUser'>
        SELECT * FROM tc_users
        WHERE login = :email
    </entry>
```

and this solve my problem (apparently): I edit whatever user, and no email overwritten, and no login blanked.

But, when I enter to "Account" or "Users" and modify my own account, 
![image](https://user-images.githubusercontent.com/66650830/84092729-e854b500-a9bd-11ea-8b04-f9df5b021da9.png)
login data is "blanked", and email is preserved, and this is a big problem with data consistency:
![image](https://user-images.githubusercontent.com/66650830/84091660-b7bf4c00-a9ba-11ea-93fb-6f0d5bf44ad9.png)

I've search throuhgout forums but no similar info to help me fix the problem, only references about LDAP integration, but my traccar isn't with it, so I think is convenient handle this as an important bug.

Thanks!

**Comment by tananaev** [comment]
Why you posted this on GitHub instead of forum?

**Comment by ehsolis1** [comment]
I think is an interesting issue. If you want, can close it and then I create one in forum.

**Comment by tananaev** [comment]
Contribution guidelines apply to the issues as well:

https://github.com/traccar/traccar/blob/master/.github/CONTRIBUTING.md

Please use forum.
