### ISSUE TITLE
Add New Protocol Documentation

### ISSUE THREAD

**Issue by Namec** [traccar/traccar#4547]
Hello,

i am wondering if there is any documentation or how to add, new protocols and make them available on the traccar server

i am thinking about Carrier and Thermoking reefers telematics, and a lot more (ACTIA, FALCOM, ...)

best

**Comment by tananaev** [comment]
There is documentation (probably slightly outdated):

https://www.traccar.org/implement-protocol/

P.S. Please use forum for questions.

**Comment by Namec** [comment]
thank you
