### ISSUE TITLE
exported gpx is invalid

### ISSUE THREAD

**Issue by 7hemas7er** [traccar/traccar#4555]
after a valid gpx export the file generates some errors when opened in several softwares.
I tried to change the element from `<geoidheight>` to `<ele>` and it works.
Is there a specific motivation to use a geoidheight reather ele?

thanks for your time

**Comment by tananaev** [comment]
I don't think there was any specific motivation. Feel free to send a PR to change it.

**Comment by 7hemas7er** [comment]
Done
thank you very much.
