### ISSUE TITLE
phone field is missing in User model

### ISSUE THREAD

**Issue by mujeerhashmi** [traccar/traccar#4559]
The `phone` field is missing in User model class.
```
"phone": {
    "type": "string"
}
```

**Comment by tananaev** [comment]
How is this related to Traccar backend?

**Comment by mujeerhashmi** [comment]
> How is this related to Traccar backend?

This is missing in `swagger.json`.

**Comment by tananaev** [comment]
Feel free to send a pull request. And next time please provide full information.
