### ISSUE TITLE
 The server reboots itself, v4.10

### ISSUE THREAD

**Issue by Bloopps** [traccar/traccar#4563]
**Describe the bug**
I've just upgraded from version 4.8 to 4.10, everything works fine except that every 5min the server restarts by itself but no particular error. 

> 2020-07-27 16:54:24  INFO: Started ServerConnector@f29353f{HTTP/1.1, (http/1.1)}{0.0.0.0:80}
2020-07-27 16:54:24  INFO: Started @13839ms
2020-07-27 16:59:22  INFO: HikariPool-1 - Starting...
2020-07-27 16:59:23  INFO: HikariPool-1 - Start completed.

> 2020-07-27 16:59:36  INFO: Started ServerConnector@f29353f{HTTP/1.1, (http/1.1)}{0.0.0.0:80}
2020-07-27 16:59:36  INFO: Started @14880ms
2020-07-27 17:04:33  INFO: HikariPool-1 - Starting...
2020-07-27 17:04:34  INFO: HikariPool-1 - Start completed.

**Server**
 - OS: Ubuntu 18.04.4
 - Version 4.10

**Desktop:**
 - OS: Windows 10
 - Browser Firefox

**Comment by tananaev** [comment]
Try disabling watchdog timer in the service config.

**Comment by Bloopps** [comment]
It does work without the  watchdog timer !

**Comment by tananaev** [comment]
It looks like for some reason health check doesn't get enabled. Are you sure you are using official version without any modifications to the code or config? Most importantly `default.xml` file.

**Comment by Bloopps** [comment]
The installation was done with the zip file of the github repository.The only ones that could have been modified are the traccar.xml and maybe the default.xml a long time ago.

**default.xml**
`<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    

    <entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>./web</entry>
    <entry key='web.cacheControl'>max-age=3600,public</entry>

    <entry key='geocoder.enable'>false</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>info</entry>
    <entry key='logger.file'>./logs/tracker-server.log</entry>
    <entry key='logger.rotate'>true</entry>
    <entry key='filter.enable'>true</entry>
    <entry key='filter.future'>86400</entry>

    <entry key='event.enable'>true</entry>
    <entry key='event.ignoreDuplicateAlerts'>true</entry>
    <entry key='processing.computedAttributes.enable'>true</entry>
    <entry key='processing.engineHours.enable'>true</entry>

    <entry key='media.path'>./media</entry>

    <entry key='notificator.types'>web,mail</entry>

    <entry key='commands.queueing'>true</entry>

    <entry key='database.ignoreUnknown'>true</entry>
    <entry key='database.generateQueries'>true</entry>
    <entry key='database.changelog'>./schema/changelog-master.xml</entry>
 
    <entry key='database.loginUser'>
        SELECT * FROM tc_users
        WHERE email = :email OR login = :email
    </entry>

    <entry key='database.selectPositions'>
        SELECT * FROM tc_positions WHERE deviceId = :deviceId AND fixTime BETWEEN :from AND :to ORDER BY fixTime
    </entry>

    <entry key='database.selectLatestPositions'>
        SELECT tc_positions.* FROM tc_positions INNER JOIN tc_devices ON tc_positions.id = tc_devices.positionid;
    </entry>

    <entry key='database.updateLatestPosition'>
        UPDATE tc_devices SET positionId = :id WHERE id = :deviceId
    </entry>

    <entry key='database.selectEvents'>
        SELECT * FROM tc_events WHERE deviceId = :deviceId AND serverTime BETWEEN :from AND :to ORDER BY serverTime
    </entry>

    <entry key='database.deletePositions'>
        DELETE FROM tc_positions WHERE serverTime &lt; :serverTime AND id NOT IN (SELECT positionId FROM tc_devices WHERE positionId IS NOT NULL)
    </entry>

    <entry key='database.deleteEvents'>
        DELETE FROM tc_events WHERE serverTime &lt; :serverTime
    </entry>

    <entry key='database.selectStatistics'>
        SELECT * FROM tc_statistics WHERE captureTime BETWEEN :from AND :to ORDER BY captureTime
    </entry>

    <entry key='h02.port'>5013</entry>

</properties>`

**traccar.xml**
`<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <entry key="config.default">./conf/default.xml</entry>

    <entry key='web.port'>80</entry>

    <entry key='geocoder.enable'>false</entry>

    <entry key='database.driver'>com.mysql.cj.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://localhost:3306/traccar?serverTimezone=UTC&amp;useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
    <entry key='database.user'>user</entry>
    <entry key='database.password'>MDP</entry>
    
    <entry key='server.timeout'>120</entry>


    <entry key='mail.smtp.host'>smtp.gmail.com</entry>
    <entry key='mail.smtp.port'>465</entry>
    <entry key='mail.smtp.ssl.enable'>true</entry>
    <entry key='mail.smtp.from'>mail@gmail.com</entry>
    <entry key='mail.smtp.auth'>true</entry>
    <entry key='mail.smtp.username'>mail@gmail.com</entry>
    <entry key='mail.smtp.password'>MDP</entry>

</properties>`

**Comment by tananaev** [comment]
Your `default.xml` clearly doesn't match the latest version. There is a good reason it has this warning:
```
DO NOT MODIFY THIS FILE. Use traccar.xml instead.
```
Closing this as expected. If you modify `default.xml`, you have to keep it up to date with each release.
