### ISSUE TITLE
[Feature Request] Add variable Eco score

### ISSUE THREAD

**Issue by lukasha12** [traccar/traccar#4564]
More and more devices can calculate Ecodriving points. In this regard, the ECOscore variable would be useful.

**Comment by tananaev** [comment]
How is it calculated?

**Comment by lukasha12** [comment]
Algorithms are device dependent - value reports the device
It is generally a value mostly in the range 0,00-100,00.

For Teltonika (io15 , Unsigned 2byte * 0.01)
range: 0,00-10,00
Eco score = 10 / ((Total events) / ((Trip distance in km) * (Allowed events per km))).
Allowed events per km = (Eco Score Allowed Events) / 100.
When Total events < 1, we ignore the formula and then Eco Score is equal to 10.

**Comment by tananaev** [comment]
Are you asking for Traccar to calculate the score or just decode score reported by device?

**Comment by lukasha12** [comment]
Only decode score reported by device.

**Comment by tananaev** [comment]
That's not really a feature request. Anyway, here are the requirements for new attribute:

1. To add a new attribute we need at least two protocols that report it.
2. For Teltonika we confirmation that the IO id works on ALL devices (including legacy ones).

**Comment by lukasha12** [comment]
OK, I'll look for other protocols. I'll be back with the information.

**Comment by lukasha12** [comment]
Ecoscore supports e.g. Cellocator.
https://flespi.com/protocols/cellocator
trip.eco.score (range 0-100)
Teltonika Ecoscore is supported by:
FMB001, FMB010, FMB110, FMB120, FMB122, FMB125, FMU125, FMC125, FMM125, FMB130, FMU130, FMC130, FMM130, FMB140, FMB900, FMB920, FMB962, FMB964, FM3001, FMB4202, FMB206, FM1002
Unfortunately, I have not found information whether older devices support ecoscore

**Comment by tananaev** [comment]
The question is not about support. It's about IO conflicts. Some other devices might use `io15` for something other than eco score.

**Comment by lukasha12** [comment]
Got it, so I suggest adding the ECOScore variable. And I'll assign the value via the computed arguments.

**Comment by tananaev** [comment]
For that we need to have at least two protocols that decode it in decoder.

**Comment by lukasha12** [comment]
OK. I understand. Unfortunately it can get complicated :(
