### ISSUE TITLE
No notifications with latest 4.10

### ISSUE THREAD

**Issue by krasi-georgiev** [traccar/traccar#4567]
Don't receive any email or web notifications for any type of event.

When I send a test notification I receive both - web and email.

I have enabled <entry key='logger.level'>info</entry> , but nothing unusual in the logs

Latest 4.10 server

This is only a test installation so happy to give you access to the server if you need any other details.

Attached is a screenshot that shows more details.

![Screenshot_20200822_200411](https://user-images.githubusercontent.com/8903888/90961602-c8a83580-e4b2-11ea-971d-d76a1a0c9a84.png)

**Comment by krasi-georgiev** [comment]
I will be using the software for a non-funded open-source environment preservation project so no money available :)

I just wanted to save you time for troubleshooting that is why I suggested to give you access.

Otherwise don't mind troubleshooting it myself. The fact that test notifications work and nothing else seems to indicate almost a definite bug on the software.

**Comment by tananaev** [comment]
There are thousands of server installations of Traccar 4.10. If notifications didn't work, I'm sure we'll have many more reports.

Anyway, keep us posted on your troubleshooting results.

**Comment by krasi-georgiev** [comment]
Yep fair enough. 

If the logs don't show any errors, what else should you suggest that I check?

**Comment by krasi-georgiev** [comment]
@tananaev any pointers on where should I look next?

**Comment by tananaev** [comment]
Not sure.

**Comment by krasi-georgiev** [comment]
I figured it out.
After creating the geo fences and setting the notifications also need to select each device on the left and then add it to the created geofence and the notifications type.

when creating a notification there is a tick box to apply to all devices, but It seems that this is misleading and need to do it for each device separately.

Thanks for support.

**Comment by tananaev** [comment]
Can you please explain what's misleading about the checkbox?

**Comment by krasi-georgiev** [comment]
I mean when you create a notification, what is the purpose of the checkbox "All devices"? 
In my case, it doesn't do anything. 
To apply a notification to a device I still need to select a device and then enable the notification about that device. 

![Screenshot_20200916_123355](https://user-images.githubusercontent.com/8903888/93320321-9bcd1100-f819-11ea-96b6-f8dbe579f9b7.png)

**Comment by tananaev** [comment]
I think you are mixing up two completely different things. You **have to link geofences** to devices, but you **don't have to link notifications** to individual devices if you selected "all devices" when you create notification. The flag applies only to notifications as it's in the notifications dialog.

**Comment by krasi-georgiev** [comment]
ok so why in my video I selected "All devices" for notifications and yet nothing got triggered?

**Comment by krasi-georgiev** [comment]
Got it, thanks for taking the time to explain!
