### ISSUE TITLE
GT06 Bike Device Packet Ignored by server when  starting bit are 0x7979

### ISSUE THREAD

**Issue by iamsrivastava** [traccar/traccar#4569]
**Describe the bug**

I am reciving two type of packet from the device
1. Starting Bit 7878 which is I am to save in DB using (Gt06ProtocolDecoder.decodeBasic) function

Example:
```
7878251614081d0b2a13c3030f05b0084e19500344bd0901940a009d0062bf0806040302000703280d0a
```

2. Starting Bit 7979 which is ignored by the server (Gt06ProtocolDecoder. decodeExtended) function

Example:
```
797900789404414c4d313d44353b414c4d323d44353b414c4d333d35463b414c4d343d46303b535441313d43303b4459443d30313b534f533d2c2c3b43454e5445523d3b46454e43453d46656e63652c4f46462c302c302e3030303030302c302e3030303030302c3330302c494e206f72204f55542c313b0008338d0d0a
```

The device is [wetrack 2](https://www.iconcox.com/products/general-gps-vehicle-tracker-wetrack2.html)
[Screen Recording 2020-08-29 at 5.18.56 PM.mov.zip](https://github.com/traccar/traccar/files/5145164/Screen.Recording.2020-08-29.at.5.18.56.PM.mov.zip)

I am attaching a debugging video where you can see the problem

**Comment by tananaev** [comment]
Protocol documentation?

**Comment by ryan1969** [comment]
What is this am I being bugged
