### ISSUE TITLE
Disable notification for disabled users

### ISSUE THREAD

**Issue by 5of9** [traccar/traccar#4574]
Wouldn't it be good if notifications to disabled users would be disabled if the user gets disabled?
Now you disable a user, but it still gets i.e. Mailnotifications.

**Comment by tananaev** [comment]
As admin you can disable all used notifications if you want. I don't really see a problem.

**Comment by 5of9** [comment]
Thats correct, but would be a comfort feature, disable user, stops all!?

**Comment by tananaev** [comment]
I guess I'm not against it. Feel free to send a PR.

**Comment by michaelloliveira** [comment]
Remove firebase token when disable user!
