### ISSUE TITLE
Filter Invalid Record - Omit other information in the packet

### ISSUE THREAD

**Issue by gpsmand** [traccar/traccar#4575]
When a gps tracker moves below the building wherein GPS / Satellite signals are not available, but somehow the data network is working the other information of the packet like speed, ignition, motion and status are not getting reflected as the GPS coordinates are invalid.

Since parking of vehicles are constructed below the ground, this scenario is bound to happen and we cannot ignore the other information of the packet. 

the GPS coordinates can be the last coordinate available, while rest of the things need to be updated.

**Comment by tananaev** [comment]
Why are they not getting reflected? Do you have some filtering enabled?

**Comment by gpsmand** [comment]
I have enabled following filters

<entry key='filter.enable'>true</entry>
<entry key='filter.future'>86400</entry>
<entry key='filter.invalid'>true</entry>
<entry key='filter.zero'>true</entry>
<entry key='filter.accuracy'>50</entry>
<entry key='filter.duplicate'>true</entry>
<entry key='filter.skipLimit'>180</entry>
<entry key='filter.maxSpeed'>250</entry>
<entry key='coordinates.filter'>true</entry>
<entry key='coordinates.minError'>30</entry>
<entry key='filter.distance'>40</entry>
<entry key='filter.skipAttributes.enable'>true</entry>
<entry key='filter.skipAttributes'>ignition,result</entry>
<entry key='filter.skipAlarm'>true</entry>

**Comment by lukasha12** [comment]
These filters delete this data:
<entry key='filter.invalid'>true</entry>
<entry key='filter.zero'>true</entry>

**Comment by gpsmand** [comment]
Yes, you are right but when the other information from the device changes, the previous lat-longs should be copied and updates will be sent to the server like ignition is turned off, speed is gone to zero etc .......

**Comment by tananaev** [comment]
Filtering completely removes the data. That's how it currently works.
