### ISSUE TITLE
api positions not returning in version 4.10

### ISSUE THREAD

**Issue by mattfleaydaly** [traccar/traccar#4579]
Not sure if this is a bug or not
but /api/positions use to always return the current positions of all devices when you entered it into the URL of your browser.
Since updating to 4.10 It does not return anything.
Cheers

**Comment by tananaev** [comment]
You need to pass `Accept` header. It has been discussed countless number of times and it's not a bug.

**Comment by mattfleaydaly** [comment]
Hey @tananaev 
Looked like it was an IIS bug on my end, another reboot fixed it.
Thanks !

**Comment by tananaev** [comment]
Unlikely. If you don't pass `Accept` header, you get random response. So, sometimes it works and sometimes doesn't.

**Comment by mattfleaydaly** [comment]
> 
> 
> Unlikely. If you don't pass `Accept` header, you get random response. So, sometimes it works and sometimes doesn't.

Yeah was an Odd issue because we were passing the header. I'd suspect IIS playing games.
Anyway thanks again, sorry for the ticket for this issue :)
