### ISSUE TITLE
Traccar Server not showing RS485 FLS temp sent from GalileoSky

### ISSUE THREAD

**Issue by AlomariMAN** [traccar/traccar#4590]
Hello Sir
Traccar Server not parsing and showing RS485 Fuel Level Sensor(FLS) temp which sent from GalileoSky7.0

1. I am using Traccar Server 4.10 installed in Linux. 
2. Using GalileoSky 7.0 
3. Using Digital RS485 Fuel Level Sensor 
4. in Galileo confiscator I can see the values comes from the sensor (Level,Temp)
5. form Traccar server I am able to see the level information only .
6. I contacted to Galileo for this issue and they confirm the configuration that I made to the Device
7. as well we connect the device to Galileo platform so they can analyise the packet , and the confirm that the level & temp appear.
8. they check the packet received from Traccar , and they confirm that the data is available received packet .
9. they guide to check with Traccar Support for why the information related to TEMP not parsed in time that it is exist in the HEX packet.

attached 1
![image(1)](https://user-images.githubusercontent.com/63209842/96716904-5f5b7a80-13ae-11eb-9c8b-c0da4319da02.png)

attached 2
![image(2)](https://user-images.githubusercontent.com/63209842/96716939-6d110000-13ae-11eb-92cf-8f9cebab3057.png)

attached 3
![image](https://user-images.githubusercontent.com/63209842/96716952-713d1d80-13ae-11eb-87d6-60cfc3b55993.png)

and this is a part of the communication done with Galileo team 

_**_10/21/2020 12:03:23 PM, you_**_
2020-10-21 11:44:09 DEBUG: [cf03dd7e: 5556 < x.x.x.x] HEX: 013f0003383638333435303332303635303133043200109d0020f9f48f5f300c737f7a010114ca023300000000347502350740003a412d3042090f431f608d028a187ded 2020-10-21 11:44:09 DEBUG: [cf03dd7e: 5556 > x.x.x.x] HEX: 027ded

_**_10/21/2020 12:28:04 PM, Владимир (Technical support)_**_
013f0003383638333435303332303635303133043200109d0020f9f48f5f300c737f7a010114ca023300000000347502350740003a412d3042090f431f608d02 

(8a) - This is the tag number (screenshot) (18) - this is the value in the tag ( in dec = 24) 7ded

**_10/21/2020 12:28:04 PM, Владимир (Technical support)_**
<a target="_blank" rel="nofollow noopener" href="https://files.jivosite.com/file-transfer/322125/2020-10-21/8ff2fffff5f8238f56c4.png">image.png</a>

**_10/21/2020 12:29:36 PM, Владимир (Technical support)_**
data is transmitted according to the Galileosky protocol: https://galileosky.com/assets/files/docs/manuals_en/general-information.-server-exchange-protocol-description.pdf

**_10/21/2020 12:30:09 PM, you_**
so what is the issue

**_10/21/2020 12:32:39 PM, Владимир (Technical support)_**
From our side, the data is being sent correctly. To display this tag in the monitoring software, please contact the monitoring software support. This tag is transmitted in a packet from the terminal and goes to the monitoring software server, you need to take into account whether they parse it? If - yes, then why is it not displayed, it is in the package.

so please guide to solve this issue .

thank you

**Comment by tananaev** [comment]
My guess is that it's not implemented. So the solution is to update the decoder to support it.

**Comment by AlomariMAN** [comment]
Could you please guide me what and how to do it ?

**Comment by tananaev** [comment]
You need to make changes in the [GalileoProtocolDecoder](https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/protocol/GalileoProtocolDecoder.java) class.

**Comment by AlomariMAN** [comment]
could you please send the path for this file , I am using Linux

**Comment by AlomariMAN** [comment]
I am not deep technical skils , so if you can help send to me the update and how to implement it ?

**Comment by tananaev** [comment]
Are you interested in sponsoring this work? If not, you'll have to wait till we get to this task, which might be quite a while.

**Comment by AlomariMAN** [comment]
yes sure , how much time , how much cost ?

**Comment by tananaev** [comment]
Send an email to discuss those details.

**Comment by AlomariMAN** [comment]
send your email address please.

**Comment by tananaev** [comment]
Open profile.

**Comment by AlomariMAN** [comment]
I got it

**Comment by AlomariMAN** [comment]
check your email
