### ISSUE TITLE
Traccar in a microservice environment 

### ISSUE THREAD

**Issue by parthibd** [traccar/traccar#4593]
I have an already existing app with its own native authentication and authorization system. I want to integrate traccar in my application so that both my applications only talk in the backend. The problem is that I want to have SSO for both the apps. My application uses JWT and traccar has Basic Digest authentication. And I want to allow roles and permission assignments in my app and want this information to propagate to Traccar. How do I got ahead to achieve that?

**Comment by tananaev** [comment]
Traccar has an API that you can use. If you want to modify that API or use different authentication method, source code is open and you are welcome to modify it to your needs.
