### ISSUE TITLE
User & Device manage Problem

### ISSUE THREAD

**Issue by Rkhdaa** [traccar/traccar#4597]
Hi
I have an idea for properly manage user & device.
Please see the screenshot. 
Sazzad Hosen is an admin account. He created sub-user account. Then admin account add/edit/delete/assign a device in any sub user account directly from an admin account.
And show all users & device in admin account and do anything like enable disable device Location check report check from admin account.
That's all.
Please see screenshot for more clear idea.
![Screenshot_2020-10-29-17-05-36-666_com sinotrack](https://user-images.githubusercontent.com/73643926/97561543-89deb080-1a0a-11eb-9409-a4ef09bd8296.jpg)

**Comment by tananaev** [comment]
You should probably explain first what problem you are trying to solve and what's wrong with the way Traccar handles user management currently.

**Comment by Rkhdaa** [comment]
Hi
Current problem is as an admin user, I can't add or delete a device in my
sub-user account.
Can't assign a device from one account to another account.
Thanks

**Comment by tananaev** [comment]
That's an incorrect statement. You can already do it in Traccar.

**Comment by Rkhdaa** [comment]
But how to add or delete a device on my sub-user account without logging
his account.

**Comment by tananaev** [comment]
For questions you can use forum, but this functionality is already available and have been available for a very long time.
