### ISSUE TITLE
Support Calamp's user message

### ISSUE THREAD

**Issue by aherrera1997** [traccar/traccar#4600]
I'm working with a LMU2720 connected to a serial device , and when the LMU recieves a serial message it sends this kind of message to the server: 
```
2020-10-30 13:05:13  INFO: [53f664d3: calamp < 179.28.88.198] HEX: 830547643586340101010400105f9c39ba5f9c302eeb36d5bddf39df700000000000000000003400040321ff9f4f0087080200001c30783330304544383946333335303139303030303030343637450d0a
```
I have a program to decode this HEX message and I have this values:

![Captura](https://user-images.githubusercontent.com/73838765/97882409-59e12700-1d02-11eb-855f-cdafa21a5201.PNG)

I'm interested in the las two values.

In traccar's forum I was told that this kind of messages (type 4: user) are not currently decoded by traccar, so I would like to know if there is any possiblity to start developing this feature.

**Comment by tananaev** [comment]
Of course. We can develop it if you are interested in sponsoring the work. Email support if that's the case.

**Comment by tananaev** [comment]
Fixed in https://github.com/traccar/traccar/commit/1afe1e818d77d2e6df520071aa7e6b0c9f335454.
