### ISSUE TITLE
Question about why requests are made to traccar.com on v4.11

### ISSUE THREAD

**Issue by est61** [traccar/traccar#4602]
So i just upgraded traccar server from 4.6 to 4.11 and i noticed the new modern interface.
Since i use noscript in general, i saw suddenly that this new version requires to connect to traccar.com.  Why? This was never the case with older versions of traccar.
Why is our self-hosted server dependent on traccar.com to open the web interface completely?
I am concerned with the privacy about this.

**Desktop**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 4.11

See screenshot
![traccar](https://user-images.githubusercontent.com/56405634/99131341-8870d300-261b-11eb-96dc-f8636e015622.png)

**Comment by tananaev** [comment]
That's needed for map layer. For the record, all version of Traccar require external dependencies, especially for map. If anything, new web app actually needs less of them.

Either way, this is not the right repo for it. You need to create a ticket in `traccar-web` if you want to discuss it.
