### ISSUE TITLE
Best practice for building the WebSocket client using Node.js

### ISSUE THREAD

**Issue by bozzlab** [traccar/traccar#4604]
Hi, I would like to ask about the way to implement the WebSocket client as receiver on Node.js. It like a another Back-end server.

I'm quite confuse about the **Session cookie** for authorized the WebSocket,
It's seem I have to login with browser for getting it. right? **(JSESSION=xxxx)**

As I know the **/api/session** (POST) didn't return a session cookie right?

So Is possible way to make it automatically?
For Instance, I just login one time then use the API to refresh the expired session time?

**Comment by tananaev** [comment]
For questions please use the forum.

**Comment by hansfpc** [comment]
@bozzlab i have the same problem, can you help me?

**Comment by bozzlab** [comment]
> @bozzlab i have the same problem, can you help me?

Firstly you can ask any question in thier forum. not in here they said like that.

For my apporach, I just work on node.js with websocket,  (https://www.npmjs.com/package/ws) 
Moreover, you have to handle the session token also.
