### ISSUE TITLE
404 on loacalhost:8082

### ISSUE THREAD

**Issue by gauravk-1994** [traccar/traccar#4605]
After creating a build of source I replaced the jar under the installation directory...
And restarted the server is up and running...

![image](https://user-images.githubusercontent.com/70271706/99355980-47a0e480-28cf-11eb-8c4d-faedbe9d0df9.png)

But when I try to hit localhost:8082 it shows 404

![image](https://user-images.githubusercontent.com/70271706/99356010-60a99580-28cf-11eb-8049-aa1a79d10c0d.png)

I followed the instruction mentioned here:

https://www.traccar.org/build/

and https://www.traccar.org/quick-start/

**Comment by tananaev** [comment]
Usually it means you are missing web app files.

**Comment by gauravk-1994** [comment]
Thanks after a little bit config I get rid out of it.. Thanks.
