### ISSUE TITLE
change DB to mongodb

### ISSUE THREAD

**Issue by itpengwei** [traccar/traccar#4606]
Hello, developer, if I want to change DB to mongodb, what should I do? Can you give me a hint and look forward to your reply?

**Comment by tananaev** [comment]
Probably search where we use JDBC and replace all relevant code with MongoDB equivalent.

**Comment by itpengwei** [comment]
I found JDBC, but the cost is relatively high. Do you have a developed program?

**Comment by tananaev** [comment]
There's no official modifications, but I heard there are some forks. Personally, I don't really understand the reason for using MongoDB.
