### ISSUE TITLE
receive ( Password error!) message from GPS device (TR06) ( TK06) ( TG06) 

### ISSUE THREAD

**Issue by Ahmedgps** [traccar/traccar#4607]
i have an GPS devices (TR06) ( TK06) ( TG06)  and need to know its status or version or any information about them .
And trying to send SMS message . the reply is ( Password error!)  for all SMS  messages . 
how to solve this problem or how to hard reset these GPS

**Comment by tananaev** [comment]
For questions please use the forum. Github is not the right place for these kinds of questions.
