### ISSUE TITLE
Feature request: Read config from environment variables 

### ISSUE THREAD

**Issue by mulka** [traccar/traccar#4611]
**Is your feature request related to a problem? Please describe.**
I'd like to deploy Traccar to ECS Fargate via Docker, but adding a single file to the container isn't that easy.
https://github.com/traccar/traccar-docker

**Describe the solution you'd like**
I'd like to be able to configure Traccar via environment variables instead of a config file.

**Describe alternatives you've considered**
I could modify the Dockerfile to include a specific config file. I could use one of the supported ways to add the config file to a volume type that Fargate supports.

**Additional context**

**Comment by tananaev** [comment]
You mean something like https://github.com/traccar/traccar/pull/3136?

**Comment by mulka** [comment]
That does seem like what I want. Where's the documentation for it?

**Comment by tananaev** [comment]
I don't think we have any official documentation for it.

**Comment by RobBickel** [comment]
You will have to use a layered docker filesystem. I can share source code if you ping me.

**Comment by Mexx77** [comment]
you need to set CONFIG_USE_ENVIRONMENT_VARIABLES in docker to enable this feature.

E.g. in docker-compose like that:

 traccar:
  image: traccar/traccar:4.15-alpine
  environment:
   - CONFIG_USE_ENVIRONMENT_VARIABLES=true
   - MAIL_SMTP_USERNAME=myName

Found it here https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/config/Config.java#L51
