### ISSUE TITLE
Traccar database does not display tables

### ISSUE THREAD

**Issue by leratom** [traccar/traccar#4613]
Hi,

I have installed traccar on my ubuntu server successfully and I am able to track my phone on the UI with no issues. But know when I try to access the database, it does not have any tables.

Please advise.

Many thanks,
Ratos

**Comment by tananaev** [comment]
Please use the forum for questions. See contributing guidelines.

**Comment by leratom** [comment]
Hi,

Thank you for the reply. 

Can you kindly please provide me with a link where I can post my question please?

Many thanks,
Ratos

**Comment by tananaev** [comment]
Do you see the link at the bottom of this page?

**Comment by leratom** [comment]
Got it. Thank you
