### ISSUE TITLE
Summary report poorly calculated average speed

### ISSUE THREAD

**Issue by lukasha12** [traccar/traccar#4616]
reports poorly calculated average speed.
This can be seen in the example:
![image](https://user-images.githubusercontent.com/66280366/102881515-41ad9e80-444d-11eb-909d-befd66e5e248.png)
The car traveled 52.95 km. The engine working time was 1h 6m (or less because the engine could work when parked, according to the trips report, the working time while driving was 1h 5m). So the average speed is: (52.95 / 66) * 60 = 48.14 km / h (or (52.95 / 65) * 60 = 48.88 km / h). Traccar calculated 22.1 km / h.

And in trpis report something is wrong with the average speed because:
![image](https://user-images.githubusercontent.com/66280366/102882233-5e96a180-444e-11eb-86db-4867d4446024.png)
(26.95 / 34) * 60 = 47.55 no 36.2 km / h
(18.73 / 20) * 60 = 56.19 not 46.3 km / h
(7.22 / 11) * 60 = 39.39 no 28.8 km / h

My observations show that the average speed is always wrong - there must be a mistake in the calculation algorithm

I checked how the average speed is calculated in trips report.
Is:
average speed = sum of speeds / number of records
This pattern is good when the speed is sent at exactly the same time. Modern devices send records at different times (e.g. turn, distance, speed), therefore there is a mistake in trip report.

Lukasz

**Comment by tananaev** [comment]
Good catch. Fixed it.
