### ISSUE TITLE
Xirgo 2169 errors.

### ISSUE THREAD

**Issue by starblazr** [traccar/traccar#4620]
```
2021-01-15 17:05:16  INFO: [5c13b169: xirgo < 12.153.231.169] HEX: 24243138343830313339382c343030362c30312f31352f323032313b32333a30353a31332c34343237313036352c2d38383432393332392c323439322c302c302c31322c31362c31343635392c352c302c332c302c372c2d372c302c322323
2021-01-15 17:05:16  INFO: [5c13b169: xirgo > 12.153.231.169] HEX: 215544505f41434b2c343030362c32
2021-01-15 17:05:16  WARN: [5c13b169] error - For input string: "2021;23:05:13" - NumberFormatException (... < XirgoProtocolDecoder:226 < *:190 < ExtendedObjectDecoder:51 < ... < WrapperContext:102 < ...)
```

**Comment by tananaev** [comment]
Please provide protocol documentation.

**Comment by starblazr** [comment]
[2169x-proto1.pdf](https://github.com/traccar/traccar/files/5823664/2169x-proto1.pdf)

**Comment by tananaev** [comment]
Have you configured format string on the server?

**Comment by starblazr** [comment]
Yea, but now it's not adding the period in the lat/lon.

 id: 184801398, time: 1969-12-31 18:00:00, lat: 46271064.00000, lon: -90429243.00000, course: 0.0

**Comment by tananaev** [comment]
Please provide the config parameter that you've added.

**Comment by starblazr** [comment]
<entry key='xirgo.timeout'>120</entry>
    <entry key='xirgo.form'>UID,EV,D;T,LT,LN,AL,GSPT,SV,HP,BV,CQ,MI,GS,SI,IG,OT</entry>

**Comment by tananaev** [comment]
This is [decoded](https://www.traccar.org/hex-decoder/) version of your sample:
```
$$184801398,4006,01/19/2021;23:43:46,44271064,-88429243,260,0,0,7,39,14554,7,0,3,0,-1,1,0,2##
```
Latitude and longitude don't seem correct. Documentation says it should be degrees. Am I missing something?

**Comment by starblazr** [comment]
It is degrees but it's missing the decimal point. I will raise it up with
the to make sure it's correy

**Comment by starblazr** [comment]
I have a feeling it's 6 shifted over from the end of the string, but I'm waiting for confirmation.

**Comment by starblazr** [comment]
the 2169 reports like the 2469, which you divide everything by 1000000

**Comment by starblazr** [comment]
totally an idiot, don't know how to submit patches on git, been trying for a little bit.

rev#489ee8f503bd13f7991056d65fbdf1c69c997d21 commit #489ee8f5

**Comment by tananaev** [comment]
Have you managed to get correct protocol documentation? Or an explanation why there is no decimal point?

**Comment by starblazr** [comment]
The protocol documentation that I posted earlier is correct.  There is an option in the firmware to add the decimal places, but it adds the decimal places to all integers, which then breaks the decoder in a different way (it's not expecting decimal places on the other variables)

**Comment by tananaev** [comment]
Can you send a pull request with the fix?

**Comment by starblazr** [comment]
yea, working on it.

**Comment by starblazr** [comment]
#4625

**Comment by starblazr** [comment]
We may want to fork off the 2169 to a XtViola decoder.  There are a ton more changes that I'm working on.

Such as:
Ignition state is different than others.  0 = none, 1= off 2 = on
battery voltage is on decimal/100 versus just giving the value on this one.
The Date/Time technically is different, in the protocol, there is no separate Time/Date.


Thoughts?

**Comment by tananaev** [comment]
I would prefer to keep the same port if possible.

**Comment by starblazr** [comment]
Ugh, okay.  I'm not sure if that's going to be possible without breaking all the other Xirgo devices.  The unit test doesn't explain what the actual variables should be -- is "2" on whatever devices they are the same as the 2169?  What devices/firmware were those tests created on?

**Comment by tananaev** [comment]
Not entirely sure. Worst case we can have separate decoding methods for different formats.
