### ISSUE TITLE
Web socket connection error

### ISSUE THREAD

**Issue by jangrewe** [traccar/traccar#4629]
**Describe the bug**
The websocket connection timeouts and the message "Web socket connection error" is shown.

**To Reproduce**
1. Go to Traccar server
2. Wait
3. See error pop up

**Expected behavior**
The websocket does not timeout.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox 85.0

**Additional context**
I have just upgraded to the 4.12 Docker image, and while everything seems to work fine at first, the websocket connection timeouts. There is no message in the log, only in the web interface. 

In the developer tools i can see that the websocket is opened successfully, the `{"positions": [...]}` object is received, and then it timeouts after (i guess) 60s and shows `Connection Closed: 1001 java.util.concurrent.TimeoutException: Idle timeout expired: 60000/60000 ms`

I have Nginx as a reverse proxy in front of it and that also worked perfectly fine with 4.11 (as far as i remember, can't say i ever saw that error before).

The relevant part from my Nginx config:
```
location /api/socket {
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
    proxy_read_timeout 600s;
    proxy_pass http://127.0.0.1:4047/api/socket
}
```

**Comment by tananaev** [comment]
Did you have any updates from devices in that minute? If not, that's expected.

**Comment by jangrewe** [comment]
Ah, so it only keeps the connection open when devices are online.

But why? A device could come online at any moment, and in all the projects where i used WebSockets, it is kinda expected that the connection is always-on - otherwise you'd miss events.

**Comment by tananaev** [comment]
If there's a websocket issue, we have a fallback to normal polling API. That's the main reason. But maybe we should increase the timeout a bit.

**Comment by jangrewe** [comment]
why not use ping/pong? https://tools.ietf.org/html/rfc6455#section-5.5.2

also for reference: https://stackoverflow.com/questions/23238319/websockets-ping-pong-why-not-tcp-keepalive

**Comment by tananaev** [comment]
Sounds like a good solution. Feel free to send a pull request.

**Comment by arkanoid87** [comment]
I ended up here as I though it was an error, even if I see websocket coming back automatically when data flow is restored.
If it is not an error but an intended behavior I think it should not popup as "Web socket connection error", as it mean something is wrong. I tend to see WS stay open in other webapps, probably using some keepalive mechanism as already proposed, but not an expert here.

**Comment by tananaev** [comment]
We already removed the error message.

**Comment by arkanoid87** [comment]
That was fast! I've upgraded my docker traccar instance from 4.8 to "traccar/traccar:latest" a couple of hours ago!
I think I've to wait for docker image to be upgraded, correct?

**Comment by tananaev** [comment]
You have to wait for the next release.

**Comment by exaucae** [comment]
Bump! 

Is anyone working on the `[ping/pong alternative](https://github.com/traccar/traccar/issues/4629#issuecomment-772651685)`? I am willing to help.

**Comment by tananaev** [comment]
I believe we already have a keepalive message.
