### ISSUE TITLE
New protocols addition 

### ISSUE THREAD

**Issue by hemrajsaxena** [traccar/traccar#4632]
We would like to integrate the new protocols to the traccar server 4.12 

We are new to traccar services 

Kindly suggest the same or mark us a mail on [removed]

https://drive.google.com/file/d/1syR1IkdKY7EiExmcSTiTm1QSLHIDvGKa/view?usp=sharing
https://drive.google.com/file/d/1WT0t0y_ggNRqmH412MOn3paJ5KBtXt3e/view?usp=sharing
https://drive.google.com/file/d/1Bu-ZJczpNA7_sA55aHLmh_2nS5mGlpz9/view?usp=sharing

**Comment by jkelany** [comment]
@hemrajsaxena do you checked [Siwi Protocol](https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/protocol/SiwiProtocol.java)?

it's matches your document payload example
`$SIWI,1234567890123,45,E,0,89917650642221590319,0,1,1,0,141313,0,9,A,21.981985,85.221165,804,280,105113,260418,17,1,13,5,4071,1,0,8,0,0,0,1.0,4.9CHKS_6.21,0!`
