### ISSUE TITLE
MaxSpeed ​​locking gt06 devices

### ISSUE THREAD

**Issue by thalysonaraujo** [traccar/traccar#4640]
hello, i have some devices with gt06 protocol that when they are offline and after a certain distance and time online, is filtered by Maxspeed and keeps sending the same position. When I remove Maxspeed from traccar.xml it updates the position of the vehicle.

does anyone have any suggestions how to fix this?

                <entry key='filter.enable'>true</entry> 
		<entry key='filter.invalid'>true</entry>
		<entry key='filter.zero'>true</entry>
		<entry key='filter.maxSpeed'>100</entry>
		<entry key='filter.accuracy'>40</entry>
		<entry key='filter.duplicate'>true</entry>
		<entry key='filter.future'>900</entry> 
		<entry key='filter.distance'>20</entry>
	       <entry key='filter.skipAlarm'>true</entry>
              <entry key='filter.skipAttributes.enable'>true</entry>
	      <entry key='filter.skipAttributes'>alarm,ignition</entry>
              <entry key='coordinates.filter'>true</entry> 
	      <entry key='coordinates.minError'>60</entry>
              <entry key='coordinates.maxError'>3000</entry>
	      <entry key='event.motion.speedThreshold'>5</entry>

![Capturar](https://user-images.githubusercontent.com/74936571/108079249-62f5ca00-704d-11eb-8ca5-4d0a045152ac.PNG)

**Comment by tananaev** [comment]
Please use forum for questions.
