### ISSUE TITLE
For input string: "1,2" - NumberFormatException 

### ISSUE THREAD

**Issue by Husenjon** [traccar/traccar#4645]
Traccar 4.12
http://localhost:8082/api/reports/events?_dc=1614348890152&deviceId=27,49&type=allEvents&from=2021-02-25T19:00:00.000Z&to=2021-02-26T19:00:00.000Z&daily=false&page=1&start=0&limit=25

returns For input string: "1,2" - NumberFormatException (...)

**Comment by tananaev** [comment]
Where did you get the request from? It looks invalid.

Also, you should ask questions on forum instead.

**Comment by Husenjon** [comment]
on giving multiple parameters to deviceId, there appear an above error 
However, when I give only one parameter then everything works fine
 ( Each request is with authorization)
