### ISSUE TITLE
GPX export using CURL returns 406 exception

### ISSUE THREAD

**Issue by loriscn12** [traccar/traccar#4646]
**Describe the bug**
GPX using CURL returns 406 exception

**To Reproduce**
pi@raspberrypi4:~ $ curl --header "Accept: application/gpx+xml" --user admin:passwd "http://192.168.1.12:8082/api/positions?deviceId=1&from=2021-02-25T00:00:00Z&to=2021-02-26T00:00:00Z"

**Expected behavior**
HTTP 406 Not Acceptable - NotAcceptableException (...)

**Additional context**
application/json works fine, not sure gpx/xml is still supported?

**Comment by tananaev** [comment]
It's not supported anymore.

**Comment by loriscn12** [comment]
hey thanks, was this implemented through ui or was it a deliberate choice to stop exporting gpx? What would you suggest to people looking to export their trips in gpx?

**Comment by tananaev** [comment]
It was removed because the code wasn't great and it was using some unmaintained libraries, as far as I remember. For now I would recommend to get JSON and convert it in a script externally.

**Comment by pkoevesdi** [comment]
I'd strongly appreciate if it came back. GPX I consider the simpler and more common format, compared to kml.
