### ISSUE TITLE
Support for cn13 GPS relay tracker device?

### ISSUE THREAD

**Issue by csurf** [traccar/traccar#4651]
I'm wondering if traccar currently (or possibly could)  support a series of GPS relay tracker devices known as the cn13, which are physically similar to units as the CJ720/730 but that use a different protocol. The unit I purchased is specifically tied to an application/website known as 'www.360gps.net', although this appears to be some kind of vendor-specific rebrand of a generic app framework for this particular device.

I set traccar to receive an incoming message from this tracker, and received a message in the following format:
```
 TRVAP00[15_digit_IMEI]#
```
Here's a list of the limited SMS commands that I was able to get from a random Chinese Vendor:
![image](https://user-images.githubusercontent.com/627526/110256602-99d54680-7f4e-11eb-9bf8-3b6d3b3dd586.png)

Does this happen to match or look similar to one of the existing protocols? If not, what else can I do to assist in deciphering the protocol?

**Comment by tananaev** [comment]
For questions please use the forum.
