### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by jcardus** [traccar/traccar#4652]
Moving the thread forum here.

https://www.traccar.org/forums/topic/new-registration-with-email-verification/#post-60554

**Is your feature request related to a problem? Please describe.**
User email should be confirmed. Main reasons for me would be security and email sending server reputation. High bounce rate will lead to black lists and account suspension.

This is just to start a discussion around it. I'm interested in contributing.

**Comment by tananaev** [comment]
Do you have an idea on how to implement this? Happy to discuss it before you start coding.

**Comment by jcardus** [comment]
We would add a readonly attribute to the user indicating if the email is validated.

When creating a new user or changing the user actual email we would first set the emailValidated attribute to false, create a token somewhere internally, and include it in a link sent to the new email.

When traccar receives the link invocation it would search for the user associated to the token and change the emailValidated attribute to true. This attribute could only be updated this way.

Traccar email sending process would only send emails to the users with true in the emailValidated attribute, except when sending the email validation email.

**Comment by tananaev** [comment]
I would prefer to avoid a new attribute and creating users when email is not validated yet. What we can do is create a User model and sent it as a URL to verification, including some signature. That way we don't add user until verification is clicked and we don't need any extra fields.

**Comment by jcardus** [comment]
And when a user changes it's email?

**Comment by tananaev** [comment]
That's a good question... we can also send some token before allowing the change.

**Comment by jcardus** [comment]
When a user creates another user, before it's confirmed, how will he have visibility that it's pending email validation? Where will that user model be stored?

**Comment by tananaev** [comment]
That's my point, we don't want to store it until the email is confirmed.

**Comment by jcardus** [comment]
Ok, sounds good, we would change create user and update user (when email changed) api methods to just send an email. When the click is received on a new method (allowing not authenticated calls) of the api we would call internal code to effectively create or update the user.
If email is disabled on traccar we wil not be able to create users, I'm assuming this is not a problem.

**Comment by tananaev** [comment]
Wait wait wait. No, it's not ok. It has to be configurable. If emails are disabled, it should work as it is now. Also, you should be able to change parameters other than email address without verification.

**Comment by tananaev** [comment]
Also, if verification is enabled, we should probably restrict user from setting their own SMTP server.

**Comment by jcardus** [comment]
Ok, it will be configurable. We may create another configuration option and default it to false.
I was talking about changing user email only. By the way, if an update user call changes email and some other attributes, the latter will change and the email change will stay pending, right?

**Comment by tananaev** [comment]
> By the way, if an update user call changes email and some other attributes, the latter will change and the email change will stay pending, right?

Correct. Email will get updated once you confirm it.

> So, which smtp would we use?

Any. What do you mean? Whatever is configured we can use.

**Comment by jcardus** [comment]
I didnt get the part the user would use its own smtp server

**Comment by tananaev** [comment]
Well, if user can override server SMTP settings then verification is pointless, right?

**Comment by jcardus** [comment]
But he can't right?

**Comment by tananaev** [comment]
Why not? Currently users can set their own SMTP servers.

**Comment by jcardus** [comment]
didn't know that, how is it done?

**Comment by tananaev** [comment]
User attributes.

**Comment by jcardus** [comment]
Oh, I see now, 

that or we could make sure the verification email is sent using the server configured smtp

**Comment by tananaev** [comment]
Yeah, that's also an option.

**Comment by jcardus** [comment]
Ok, thanks Anton, I'll work on the PR
