### ISSUE TITLE
Feature Request: GeoNotifications

### ISSUE THREAD

**Issue by mychristopherta** [traccar/traccar#4655]
My suggestion is about adding Geo Notifications. Similar to GeoFences, a seperate place to add geo markers (polygons, straight lines, etc) as a display-only with the option to display on all users. 

Use case: 
Multiple users are logged in to the dashboard looking at locations. A road has been closed in the area. A Geo Marker is added at the location of the closure. That marker is now displayed on everyone's map showing the marker, and they can click for details.
Another use case: A tornado has touched down. A geo marker is drawn around the area of most damage. That marker is now displayed on all users map so they are aware of where to avoid, or where to go, etc.

I understand we could sort of do this now with a Geofence, but adding a geofence then adding to all users is time consuming. I believe a GeoMarker functionality that automatically displays on all users, or a user setting on individual users "Display Geo Markers" .

Thanks!

**Comment by tananaev** [comment]
There's a POI layer feature that should work for this use case. You can set a global one.
