### ISSUE TITLE
Create a new user and set user attributes - the attributes are not reported via API

### ISSUE THREAD

**Issue by alexbk66** [traccar/traccar#4659]
If you create a new user and set user attributes (speed/distance units) - the attributes are not reported via API - unless you set any other user Preferences (i.e. I set Map Layer).  
`{"id":1520,"attributes":{},"name":"ale`
After that I get the User.Attributes
`{"id":1520,"attributes":{"distanceUnit":"km","speedUnit":"kmh","volumeUnit":"ltr"}`

**Comment by tananaev** [comment]
I'm not able to reproduce the issue. I created a new user and attributes are reported just fine. Tested the latest version.
