### ISSUE TITLE
new Device Protocol

### ISSUE THREAD

**Issue by nebiti** [traccar/traccar#4660]
Hex on Traccar log : (013632782450BR00101130A2234.0270N11405.9126E000.00623168.5400000005A
EL0000067ET0CDF080P035)

"(" stand for packet start
"013632782450" stand for tracker ID
"BR00" stand for command
"101130" stand for data, 10 year 11 month 30 day
"A" stand for gps data valid, "V" stand for gps data no valid
"2234.0270" stand for latitude, format is ddmm.mmmm
"N" stand for north, "S" stand for south
"11405.9126" stand for longitude, format is dddmm.mmmm
"E" stand for east, "W" stand for west
"000.0" stand for speed, unit is km/h
"062316" stand for time, 06 hour 23 minutes 16 seconds, UTC time
"8.5400" stand for direction
"000005AE" stand for I/O state， first bit stand for main power, “0” stand for external power supply. “1” stand for battery supply. Second bit stand for ACC state, “0” stand for ACC off, “1”
stand for ACC on. Third, fourth, fifth reserved. The three bits
of sixth, seventh, eighth stand for voltage value. The unit is
10mV, Hex format. Value from 0 to 960, voltage from 0V to
24V. Such as 5AE is 5*16*16 + A*16 + E =1454 (10mV) =
14.54V This is the fuel sensor data
"L" stand for mileage flag
"000067E" stand for mileage value, hex format,
67E = 6*16*16+7*16+E=1662 meters.
"T" stand for temperature flag.
"0CD" The three digits after T represent the temperature, which is in
hexadecimal.First convert hexadecimal to binary, a total of 12 digits,
for the part with less than 12 digits, add with 0 in front of the integer,
such as 12E Converted to binary is 100101110, 12 bits is
000100101110, and the first bit is 0, indicating that the temperature
is positive. Converted to decimal: 302, the temperature is 30.2 ° .
For example, 811, converted into binary: 100000010001, the first bit
is 1, the temperature is negative. After removing the first digit 1, the
remaining part 10001 is converted to decimal 17, and the
temperature value is -1.7 °
“F080” the limit speed : max=80
“P035” This is Pulse coefficient 35km/h
")" stand for packet end

**Comment by tananaev** [comment]
You have to provide proper protocol documentation.

**Comment by nebiti** [comment]
[protocol  about the GPS parts.pdf](https://github.com/traccar/traccar/files/6284585/protocol.about.the.GPS.parts.pdf)
[speed limiter protocol data explain.pdf](https://github.com/traccar/traccar/files/6284586/speed.limiter.protocol.data.explain.pdf)

**Comment by tananaev** [comment]
It's already supported.
