### ISSUE TITLE
Sino Track ST-906 setting to server

### ISSUE THREAD

**Issue by Crystien20** [traccar/traccar#4663]
Good afternoon friends, this is my first post, this is to see if you can help me on an issue that has been going wrong for me for several days.

I have 1 sinotrack computer model ST-906W which I managed to adapt the information that it sends to my own listener but it turns out that the battery voltage data both of the equipment itself and the voltage of the unit do not receive it.

Does anyone know how I can solve my problem? I appreciate it in advance. Also the gps sends me the last 4 values in 0 and I don't know how to make it report the pertinent information, here is a sample of the plot:
```
*HQ,0000000000,V6,204537,A,1000.5000,N,06006.0400,W,0.00,0,160421,fbffffff,000,00,0000,0000#
```

Excuse my English, I'm using google translator +_+

**Comment by tananaev** [comment]
You should use the forum for questions.

**Comment by Crystien20** [comment]
how do i do it? i'm new, thanks

**Comment by tananaev** [comment]
Ask on the forum here:

https://www.traccar.org/forums/

**Comment by Crystien20** [comment]
thank you very much really
