### ISSUE TITLE
Event save error - Unknown column 'eventTime' in 'field list'

### ISSUE THREAD

**Issue by maotm** [traccar/traccar#4665]
Hello,
New server install, activated events with 
<entry key='event.enable'>true</entry>

If I modify in tc_events column name from servertime to eventTime, the events are saved in db, but I can't see them in reports  on web ui, which breaks.
Thx.

**Comment by tananaev** [comment]
Please use the forum for questions. Looks like you didn't install an official release and that's why you are getting this error.
