### ISSUE TITLE
Help with identifying device support via protocol document

### ISSUE THREAD

**Issue by ikraamg** [traccar/traccar#4673]
EDIT: I found an old issue https://github.com/traccar/traccar/issues/1184 that I think explains that this is actually a TK102 device. Is this correct?

Good day,

I have been given a protocol [document](https://github.com/traccar/traccar/files/6445114/PinPoint.Protocols.pdf) of a re-branded device. I, unfortunately, do not have access to the device itself, so I can't [identify the protocol ](https://www.traccar.org/identify-protocol/) as per instructions.

If possible, kindly help me identify if Traccar supports the protocol in the [document](https://github.com/traccar/traccar/files/6445114/PinPoint.Protocols.pdf).
Or perhaps point me in the right direction, please.

Thank you!

**Comment by tananaev** [comment]
It could be TK102 protocol. Please next time read contribution guidelines first and use forum for questions.
