### ISSUE TITLE
HTTP SMS API throttling; globally and per device.  A bad device sent hundreds of SMS in 20-30 minutes.

### ISSUE THREAD

**Issue by pc500** [traccar/traccar#4675]
**Is your feature request related to a problem? Please describe.**

For a HTTP SMS API (or other notification sink), a maximum "notifications per second" at a connector level, and a "notifications per device per minute" and/or "notifications per group per minute" throttle.

A bad actor (or defective device) can send device-level updates which invoke SMS notifications at a virtually unlimited rate, causing hundreds of messages per minute and an eventual denial of service from the SMS provider.

**Describe the solution you'd like**

A throttling mechanism to ensure reasonable rate limits on HTTP SMS connectors and individual devices in a flexible manner to address most deployed use cases.

**Comment by tananaev** [comment]
Seems like a duplicate of #2980.
