### ISSUE TITLE
Setup and database error

### ISSUE THREAD

**Issue by Berk3535** [traccar/traccar#4679]
Hello, 
1. I open this https://www.traccar.org/build/ 
2. Downloaded git clone --recursive https://github.com/traccar/traccar.git on my computer and I can ran server with https://www.traccar.org/build-in-intellij-ide
3. Then downloaded https://github.com/traccar/traccar-client-android on my computer and I changed settings_url_default_value  http://localhost:5055  in the values.xml file and ı ran it with Android Studio. 

I changed database congifiguration in the setup/traccar.xml file

     <entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
    <entry key='database.url'>jdbc:sqlserver://DESKTOP-G3I5468JT;user=ercesa;password=123;databaseName=Takip;</entry>
    <entry key='database.user'>ercesa</entry>
    <entry key='database.password'>123</entry>

And I ran again with invalidate chaches/restart .Database tables did not exist in the Microsoft Sql Server. And I have one more question on the traccar client side does any database have a configuration process?
How it is work? Please, could you please help.

**Comment by tananaev** [comment]
Please use the forum for questions.
