### ISSUE TITLE
Overspeed event with minimum time 

### ISSUE THREAD

**Issue by jcardus** [traccar/traccar#4681]
**Is your feature request related to a problem? Please describe.**
It would be nice if you could define the minimum time span for the overspeed event. 

**Describe the solution you'd like**
For example, the event would only be fired if the vehicle was over 90 km/h for more than one minute.

Does it make sense to work on a PR?

**Comment by tananaev** [comment]
Makes sense to me.

**Comment by jcardus** [comment]
I'm thinking about creating the config overspeedMinimumSeconds

**Comment by tananaev** [comment]
Actually, looks like we already have it:
```
"event.overspeed.minimalDuration"
```

**Comment by jcardus** [comment]
Didn't know that. From what I can see it's not configurable by vehicle / group. I could implement that.

**Comment by tananaev** [comment]
Does it need to be configurable per device? It seems like overkill. We need to be careful with per-device configuration because it can potentially impact performance.

**Comment by jcardus** [comment]
You can have different customers on the same server. Some want it some don't...

**Comment by jcardus** [comment]
We are already doing it for the speed limit

**Comment by tananaev** [comment]
Then I guess it makes sense.

**Comment by jcardus** [comment]
ok great, I'll work on the PR.
