### ISSUE TITLE
tc_events

### ISSUE THREAD

**Issue by MuhammadShoaibAhmad** [traccar/traccar#4685]
Hello Anton,

I was Wondering How tc_events is being Populated.

tc_events does not Include Any reference to tc)positions.

I would Like to KNow the Lat, long, speed, and Time on Event. These Features Are only available in tc_positions table.

Can You add this Feature where we can relate tc_events with tc_locations Just Like teltonika Tavl.message and tavl.eventslog.

Or Perhaps you Could Guide me How tc_events is being populated and I will update the repository by forking => Updating and Creating Pull Request.

Thanks !

have a Good Day !

**Comment by tananaev** [comment]
Please use the official forum for questions.
