### ISSUE TITLE
Problem with telegram notifications after 4.13 update

### ISSUE THREAD

**Issue by scabi69** [traccar/traccar#4690]
HTML code is send as raw in telegram notifications, as this start using full templates after 4.13 upgrade:

![HTML keys in telegram message](https://imagizer.imageshack.com/img924/3394/HjeQPS.png)

**Comment by Thiritin** [comment]
I can confirm the issue on my installation aswell.

**Comment by tananaev** [comment]
@soshial it looks like there's an issue with full templates after your change. Can you please fix it.

**Comment by RafaelMiquelino** [comment]
Same issue here. Does anyone have this working?

**Comment by dennisb1** [comment]
How can i restore it to the old way? It was fine as it was..

**Comment by RafaelMiquelino** [comment]
Hi, in my opinion we should get back to the short templates until a final solution is available. This upgrade broke this feature for me and as I can see on this thread, it’s not working for anyone. 

Also, as far as I know the Telegram bot api doesn’t support full html syntax, just some specific tags for text formatting, as describes in the docs: https://core.telegram.org/bots/api. So, the full templates as they are today is not actually going to work.

**Comment by RafaelMiquelino** [comment]
> Also the docker container creates a link to the internal 172.x.x.x ip range of the docker network instead of the WAN interface or better a domain i use.

Hi, agree with you but this quoted statement specifically is another topic and if you want to fix that, you may refer to this thread on the forum.

**Comment by dennisb1** [comment]
> > Also the docker container creates a link to the internal 172.x.x.x ip range of the docker network instead of the WAN interface or better a domain i use.
> 
> Hi, agree with you but this quoted statement specifically is another topic and if you want to fix that, you may refer to this thread on the forum.

Actually its not totally.

Telegram:
`<!DOCTYPE html>
<html>
<body>
Device: Bike<br>
Online<br>
Time: 2021-06-08 14:05:47<br>
Link: <a href="http://172.17.0.3:8001?eventId=25382">http://172.17.0.3:8001?eventId=25382</a>
</body>
</html>`

**Comment by scabi69** [comment]
I would prefer, if it's possible, that the template is sent before the image. Because this way you could read the message at mobile notifications place, and not only the text "image" (what happens when image gets first). 

It could be my system, or my telegram, but sometimes it arrives me the text before the image (the good way for me, as it was working until now), but mostly times the image arrives first, who knows...

**Comment by soshial** [comment]
> I would prefer, if it's possible, that the template is sent before the image. Because this way you could read the message directly at mobile notifications place, and not only the text "image" (what happens when image gets first).

Text is sent first, location is second:
![image](https://user-images.githubusercontent.com/100644/123538732-4e39e900-d747-11eb-8a4d-a53d1f17232a.png)

Location is sent first:
![image](https://user-images.githubusercontent.com/100644/123538751-598d1480-d747-11eb-944f-57fe3b3e7ef2.png)

Is there any difference, @scabi69?

**Comment by dennisb1** [comment]
I dont like the map at all. Its not needed at all in my situation. It’s annoying. Can we make it an option in the config to do it or not?

**Comment by soshial** [comment]
> I dont like the map at all. Its not needed at all in my situation. It’s annoying. Can we make it an option in the config to do it or not?

I am afraid, this is beyond my abilities of coding.

**Comment by scabi69** [comment]
Well seen, it may be better sending the location first (or even an option to disable it as @dennisb1 says).
As I told I get a mess with my server because sometimes it sents location first and some after the message.
After a time of use, as @soshial says, the location goes better before, as the the text remains in main screen of telegram:
![Location at end](https://imagizer.imageshack.com/img923/3079/Z7pZ6b.jpg)
![Message at end](https://imagizer.imageshack.com/img922/806/Y8cF5X.jpg)
