### ISSUE TITLE
Display POI Description when click on the POI.

### ISSUE THREAD

**Issue by ilevans** [traccar/traccar#4691]
**Is your feature request related to a problem? Please describe.**
Wish to see addition information about a point of interest.

**Describe the solution you'd like**
It would be nice to be able to click on a Point of Interest to see the associated description. It could disappear after a period of time or a click elsewhere.

**Describe alternatives you've considered**
Carrying a notebook with details about each POIs

**Additional context**
For our Rural Fire Brigade adding information about a POI would be very useful.
EG: For a water source a description about how to gain access and which key to use.

**Comment by tananaev** [comment]
This should be moved to the web app repo.
