### ISSUE TITLE
Version info in web interface

### ISSUE THREAD

**Issue by bloodygoodbloke** [traccar/traccar#4693]
**Is your feature request related to a problem? Please describe.**
it would be handy to have a version info on the web interface.  A quick and easy check to see if you are on the latest version or not. As someone who doesnt manage the system often my memory is not as good and im terrible at documenting so i sometimes forget if i have updated or not. 

**Describe the solution you'd like**
A menu option just above logout where you click and see the version info

**Describe alternatives you've considered**
as a non native linux user and looking to host in cloud it is not quick and easy to check the versioning.  

**Additional context**

**Comment by tananaev** [comment]
You can just use server API endpoint like this:

https://demo.traccar.org/api/server

Gives you the version.
