### ISSUE TITLE
New protocol Topflytech device: TLP1-SF (4G LTE)

### ISSUE THREAD

**Issue by BoDiechmann** [traccar/traccar#4694]
Is it possible to integrate the new devices from TOPFLYtech, here are the protocol files
password to the file is topflytech

[TOPFLYTECH 0x270x27 Protocol 2021-03-18 (TLP1 series and TLP2-SFB).xlsx](https://github.com/traccar/traccar/files/6616275/TOPFLYTECH.0x270x27.Protocol.2021-03-18.TLP1.series.and.TLP2-SFB.xlsx)

Best regards
Bo Diechmann

**Comment by tananaev** [comment]
Of course it's possible. If you are interested in sponsoring the work, please send me an email.

**Comment by BoDiechmann** [comment]
Hello Anton

With joy, how much are we talking about?

Sincerely
Bo
Med venlig hilsen

Bo Diechmann
ALCO Company ApS
Åbrinken 28
7700  Thisted

Tlf: 9791 1470

***@***.***

**Comment by tananaev** [comment]
Please send an email to discuss.

**Comment by BoDiechmann** [comment]
?

Venlig hilsen
Bo Diechmann

**Comment by BoDiechmann** [comment]
Where should I send mail?

Med venlig hilsen

Bo Diechmann
ALCO Company ApS
Åbrinken 28
7700  Thisted

Tlf: 9791 1470

***@***.***

**Comment by tananaev** [comment]
You can find my email address in the profile.

**Comment by tananaev** [comment]
I think this protocol is already supported.
