### ISSUE TITLE
New protocol Topflytech: ODB II TLD1 and TLD1-D

### ISSUE THREAD

**Issue by BoDiechmann** [traccar/traccar#4695]
Is it possible to integrate the new devices from TOPFLYtech, here are the protocol files

[TOPFLYTECH 0x260x26 Protocol 2021-03-18 (TLD1-DADE, TLD2-D).xlsx](https://github.com/traccar/traccar/files/6616318/TOPFLYTECH.0x260x26.Protocol.2021-03-18.TLD1-DADE.TLD2-D.xlsx)

Password: topflytech

Best Regards
Bo Diechmann

**Comment by tananaev** [comment]
Of course it's possible. If you are interested in sponsoring the work, please send me an email.

**Comment by BoDiechmann** [comment]
Hello Anton

With joy, how much are we talking about?

Sincerely
Bo
Med venlig hilsen

Bo Diechmann
ALCO Company ApS
Åbrinken 28
7700  Thisted

Tlf: 9791 1470

***@***.***

**Comment by tananaev** [comment]
I think this is already supported.
