### ISSUE TITLE
A new user appeared after the update to version 4.13

### ISSUE THREAD

**Issue by Turbovix** [traccar/traccar#4696]
**Describe the bug**
A new user appeared after the update to version 4.13

Hi Anton,
after upgrading from version 4.10 to version 4.13, I noticed that a new user appeared in the Traccar user list.
name: avtodop
email: ***@mail.ru

Do you have any idea where this user came from?
**Expected behavior**

**Screenshots**
![traccar](https://user-images.githubusercontent.com/3914126/121302390-ff2f2f80-c8cf-11eb-8f60-3b0436960223.jpg)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser [Chrome]

**Comment by tananaev** [comment]
Traccar doesn't create any users other than default admin. Someone must have created that account on your system.

Please next time use the forum.
