### ISSUE TITLE
Directory browsing issue

### ISSUE THREAD

**Issue by enoxos** [traccar/traccar#4701]
**Describe the bug**
Directory browsing is not enabled by default. LAN and WAN access both result in directory browsing. 

**To Reproduce**
1. LAN: 192.168.1.5:8082/images (use sever LAN ip)
2. WAN: mywebsite.com/images
3. Note: all directories are visible, not just /images.

**Expected behavior**
Directories should bot be visible.

**Screenshots**
[screenshot](https://ibb.co/5GHm5tM)

**Comment by tananaev** [comment]
The issue is fixed. You can either compile a version from source or wait for the next official release.

**Comment by enoxos** [comment]
Thank you,
Can i just replace the affected two files without rebuilding and reinstalling the program?

**Comment by tananaev** [comment]
Unfortunately no. You can replace the binary, but you'll have to compile it first.

**Comment by enoxos** [comment]
Ah ok, thank you for fixing it so quickly and will compile it. Was it an issue on v4.13 only?

**Comment by tananaev** [comment]
Hard to tell. I have a feeling that Jetty changed defaults at some point. My guess is most recent versions are affected.

**Comment by enoxos** [comment]
Just a suggestion, it may be a good idea to upload an updated version in the traccar.org site. I believe that most people that have installed traccar's latest version may not be aware of this issue which is an important one for privacy and I am sure they would like to install the fix asap. 
Thanks for a great software.
