### ISSUE TITLE
Save per-user UI preferences for columns

### ISSUE THREAD

**Issue by soshial** [traccar/traccar#4704]
![image](https://user-images.githubusercontent.com/100644/123054767-42cc8200-d416-11eb-8823-f10227fa3ceb.png)

**Comment by tananaev** [comment]
Wrong place.

**Comment by soshial** [comment]
> Wrong place.
In what sense?

**Comment by tananaev** [comment]
This is Traccar back end repo.

**Comment by soshial** [comment]
Please, delete the issue.
