### ISSUE TITLE
Forward url JSON is sending position id as 0  Tested on master branch

### ISSUE THREAD

**Issue by heisGarvit** [traccar/traccar#4709]
**Describe the bug**
Positions JSON that is forwarded on url is sending position ID as 0

**To Reproduce**
1.  forward positions to url
2. log position object
3. see position ID

**Expected behavior**
Position ID is should not be 0

**Screenshots**

![JSON screenshot](https://user-images.githubusercontent.com/9434908/123583305-04abd580-d7fd-11eb-9645-51682e16ff33.jpeg)

**Additional context**
Was working as expected in older versions

**Comment by tananaev** [comment]
It is expected behavior because forwarding is happening before data is stored in the database, so we don't have id at that point yet.

**Comment by heisGarvit** [comment]
But the position id exists in device object of the request; is it older id? Also we used to receive id in position object in older versions.

**Comment by tananaev** [comment]
It's probably older position id. I don't think we changed the order, so it shouldn't work in older version, but I'm not too sure about it.

**Comment by heisGarvit** [comment]
Thanks for clarifying.
