### ISSUE TITLE
No/limited OBD data via hex?

### ISSUE THREAD

**Issue by botts7** [traccar/traccar#4718]
**Describe the bug**
Hi,

I have my Freematics One+ B up and running and I get GPS coordinates to my traccar server. But no/limited OBD data.

The hex for the GPS comes in and is decoded fine, but not sure what the below is and not sure why I am getting no other OBD data.

In Hex decoder I get the following:

[device_id]#EV=2,TS=80580,ID=[device id],VIN=[cars vin],*1B

device id and vin are correct. (redacted)

not sure what EV,TS or the *1B are?

also get via hex to server 1#EV=7,RX=1,TS=1033123*14 (decoded hex)

or why no pid data is coming through. PID data is available in the CSV files on the SD card

I have verified with an elm327 that the PIDS are being read and are correct via the torque app with the elm327 as well

Any ideas?

**Desktop (please complete the following information):**
 - OS: hassio addon with Traccar v4.13
 - Browser chrome

**Comment by tananaev** [comment]
Have you checked their documentation? This seems like a question to freematics.
