### ISSUE TITLE
TK06A New Protocol, Which port

### ISSUE THREAD

**Issue by sen2009** [traccar/traccar#472]
Hi, 
I want to use TK06A devices with traccar. I cannot understand if this protocol is present in Traccar supported devices list. If not, can support for this device be added?

If already present, then which port to use?

Below is the protocol as received from manufacturer. 

```
Example for complete protocol data
example for complete protocol data as follow : 
#353509009009443#13486270583#0#0000#AUT#04#57e84d79#12125.1905,E,2840.9889,N,0.00,1.06#110709#163047.000#57e84d79#12125.1905,E,2840.9889,N,0.00,1.06#110709#163102.000#57e84d79#12125.1905,E,2840.9889,N,0.00,1.06#110709#163117.000#57e84d79#12125.1905,E,2840.9889,N,0.00,1.06#110709#163132.000##

Split structures as follow ( it has been manual joined the newline for convenient reading ): 
#353509009009443#13486270583#0#0000#AUT#04
#57e84d79#12125.1905,E,2840.9889,N,0.00,1.06#110709#163047.000
#57e84d79#12125.1905,E,2840.9889,N,0.00,1.06#110709#163102.000
#57e84d79#12125.1905,E,2840.9889,N,0.00,1.06#110709#163117.000
#57e84d79#12125.1905,E,2840.9889,N,0.00,1.06#110709#163132.000##

Structure
it can be seen as above, the structure is made up of packet header:
#353509009009443#13486270583#0#0000#AUT#04
And each data
#57e84d79#12125.1905,E,2840.9889,N,0.00,1.06#110709#163117.000
Plus ## ending character .


Format explaination in details:
Packet header structure as follow: 
#IMEI number#SIM card  mobile number#0#device manage password#AUT#data numbers(2 digits)
1. the IMEI number cannot be empty, if the SImcard number regarded as device series number, then the data of IMEI part should be filled in SIM cad number.
2. SIM card number: this part can be empty , or also can be same as 1st point , fill in SIM card number.
3. 0 or 1 , reserve (original meaning is ACC status )
4. Device password ( 0-9 numbers, digit cannot over 6 digits, generally is in 4 digits )
5. Reserved word AUT, cannot be changed .
6. Numbers of data, 00-99 , in 2 digits.
The format of Each data as below: 
#base station number#Longitude, East and West identification, latitude,North and South identification,speed(nm), direction angle (0-360)#date#time
1. Base station number can be empty.
2. Longitude, format : dddff.ffff, the degree part must be in 3 integer, the minute part must be in 2 integer, the decimal part is in 4 digits, there is no separator between degree and minute.
3. East and West identification, only one character , E/W.
4. Latitude, format : dddff.ffff, same as Longitude , only the degree part is in 2 integer.
5. North and South identification, only one character , N/S.
6. Speed: can be 0.
7. Direction : can be 0.
8. Date, format : ddmmyy.
9. Time, format: hhnnss.mmm, the part before decimal point should be hour, minute and second in turn, each is in 2 digits, the part after decimal point should be milliseconds, it can be 000.

simple example
simple example（upload 1 data at a time ):
#353509009009443#13486270583#0#0000#AUT#01
#57e84d79#12125.1905,E,2840.9889,N,0.00,1.06#110709#163117.000
##
Don't transmission with a newline, so the most simple data correct example as follow:
#13486270583##0#0000#AUT#01#57e84d79#12125.1905,E,2840.9889,N,0.00,0.00#110709#163117.000##
```

**Comment by gauthamreddy555** [comment]
hi

I have this GT02A, looks like its little different when compared with regular GT02.. looks like when i connect the device and when i dail the number its not recognizing.. is there any way to fix it.. more specific can we change the IMEI or need to do something.. pls help

**Comment by tananaev** [comment]
@gauthamreddy555, please provide some HEX message samples from your device.

**Comment by gauthamreddy555** [comment]
how do i get them.. i dono please help

**Comment by tananaev** [comment]
You can find those in `tracker-server.log` file.

**Comment by gauthamreddy555** [comment]
No yar, after inserting the sim .. the mobile number is not detected.. looks like a IMEI issue
![p_20151209_030301](https://cloud.githubusercontent.com/assets/16214524/11669252/d292ff76-9e21-11e5-9cef-8824bf495bc1.jpg)
![p_20151209_030328](https://cloud.githubusercontent.com/assets/16214524/11669251/d290a794-9e21-11e5-9b0c-419ac0dd5c81.jpg)
![p_20151209_030359](https://cloud.githubusercontent.com/assets/16214524/11669253/d2953f98-9e21-11e5-96d0-854e821a2a8b.jpg)
![p_20151209_030428](https://cloud.githubusercontent.com/assets/16214524/11669254/d29c2d6c-9e21-11e5-82a4-1c29f3fc4d97.jpg)

**Comment by gauthamreddy555** [comment]
am new to this ... pls guide me how to fix devices with IMEI issues

**Comment by tananaev** [comment]
Why do you think it's IMEI issues? And what does it even mean?

**Comment by gauthamreddy555** [comment]
ok when i insert the sim and switch on the device..  i dont hear the dial tone when i call the device.. it says not reachable to switched off... i think this might be IMEI issues

**Comment by tananaev** [comment]
What do you mean by IMEI issues? IMEI is just a unique identifier of the modem.

**Comment by gauthamreddy555** [comment]
ok now what might be the issue.. its not working.. i have 50 units like this...

**Comment by tananaev** [comment]
I guess there is either some problem with the device or with your sim card.

**Comment by gauthamreddy555** [comment]
sim card works fine with other models

**Comment by gauthamreddy555** [comment]
i feel its a device issue
 and i dono how to fix it

**Comment by tananaev** [comment]
What SIM card are you using?

**Comment by gauthamreddy555** [comment]
Aircel GSM  and it never worked with airtel or vodofone..

**Comment by tananaev** [comment]
Make sure that SIM provider uses frequencies supported by the device. I have same device and I had problems with some SIM cards here in New Zealand.

**Comment by gauthamreddy555** [comment]
ohh ok.. but how to find thoes frequencies..  ok can you please guide how to go inside the device,.. do we have any tools to hack these devices

**Comment by tananaev** [comment]
You need to find out from device specification. If you don't have those, ask seller.

**Comment by gauthamreddy555** [comment]
seller is also not aware i bought this in aliexpress the device specification says the regular specs of the sim frequencies.. please help guys

**Comment by tananaev** [comment]
What do you mean by "regular"?

**Comment by gauthamreddy555** [comment]
the spec says 850/900/1800/1900 mhz

**Comment by tananaev** [comment]
I remember that one of the SIM cards that I have wasn't compatible with the device. In your case it might be just faulty device or some other issue.
