### ISSUE TITLE
GET /web/api/server 404 (Not Found)

### ISSUE THREAD

**Issue by kos-ds** [traccar/traccar#4720]
Good Day!
Help me figure it out, I open a web project in VSC, I run Live server in chrome in the console error "ext-all-debug.js: 25489 GET http://127.0.0.1:5500/web/api/server?_dc=1627552553342 404 (Not Found) ..." 
the server side is also downloaded. Another window appears with an error "incorrect parameters or no access" in the message window 
"<! DOCTYPE html>
<html lang = "en">
<head>
<meta charset = "utf-8">
<title> Error </title>
</head>
<body>
<pre> Cannot GET / web / api / server </pre>
</body>
</html>
"
Tell me what the problem is.
Thanks in advance!
![!Errr](https://user-images.githubusercontent.com/48374001/127473507-4dea1652-d1eb-41a5-bb28-e3a42f300563.jpg)

**Comment by tananaev** [comment]
First of all, please use the forum for question.

Secondly, why do you have "web" in front of the "api". Doesn't seem like you are using official setup.

**Comment by kos-ds** [comment]
Thanks for the answer!
I can't answer why do you have "web" in front of the "api", I haven't changed the code.
And tell me please, but where is the forum, I did not see it on the site.

**Comment by tananaev** [comment]
https://www.traccar.org/forums/

**Comment by kos-ds** [comment]
Thank you!
