### ISSUE TITLE
Please make a new release - last one is 2 months old

### ISSUE THREAD

**Issue by krasi-georgiev** [traccar/traccar#4722]
I am using the docker images and these are also 2 months old. Please consider making a new release.

**Comment by krasi-georgiev** [comment]
sorry was the issue unapropriate?

**Comment by tananaev** [comment]
GitHub is for feature requests or bug reports. We don't really accept requests for new releases.

Also, you haven't provided any good argument for why we need to make a new release. Good example would be if there's some known security issue in a dependency or something like that. Then it might have been appropriate to flag.
