### ISSUE TITLE
Can' find main class in IntelliJ IDEA

### ISSUE THREAD

**Issue by Donald30498** [traccar/traccar#4723]
**Describe the bug**
I followed the tutorial "Build From Source" , and I am stuck "Build in IDEA" because I can't find the Main Class when adding an application.
By the way , I'm using VirtualBox-Ubuntu.

// I'm a beginner of almost everything , so please ignore and close this issue if this is a meaningless question.//

**To Reproduce**
1. Go to ' /idea*/bin/ ' and insert ' ./idea.sh ' to open IDEA
2. Open ' traccar '
3. Add configuration and select application
4. Can't find anything of Main Class

**Expected behavior**
Find the file the tutorial said

**Screenshots**
![image](https://user-images.githubusercontent.com/77958256/129693477-72c88c39-22f2-4837-84eb-f6771f72c36a.png)

**Desktop (please complete the following information):**
 - OS: VirtualBox-Ubuntu
 - Browser : IntelliJ IDEA

**Comment by tananaev** [comment]
Do you have a JDK installed?

**Comment by Donald30498** [comment]
I'm sorry for replying so late , because I found I have trouble doing everything and I'm trying hard solving them .
I didn't install JDK , and I have some trouble when trying to install it .
I'm now viewing some website for solution and dealing with problems come after it .
Sorry for bothering and thanks for your time , I think I should start from basic stuffs .
