### ISSUE TITLE
Teltonika with LVCAN incorrect report after device reboot

### ISSUE THREAD

**Issue by cop98** [traccar/traccar#4724]
Sometimes Teltonika devices, reboot automatically for various reasons.
If this reboot happens during the night, the first values received during the day will be 0 (we are mainly interested in the odometer and fuel liters).
This causes a negative value in the fuel consumption and odometer in the "summary" report!

**To Reproduce**
1. Restart the Teltonika with LVCAN and do not use the vehicle again for the rest of the day
2. The next day make a trip with the vehicle
3. View the "summary" report

**Expected behavior**

You should implement a check that if the first value of the day is 0, to create the report you look at the last correct value.
In particular, we need the odometer value and the fuel consumption.
Beware that these values are often derived from calculated attributes!

**Comment by tananaev** [comment]
Are you reporting it as a Traccar bug? Can you please clarify.

**Comment by cop98** [comment]
I reported it as a bug as it completely throws off the whole report.
It should be implemented a control that checks if the odometer and the fuel consumption have suddenly become 0 and in the event uses as initial value the last ones considered valid.
Do we agree that the odometer of a car cannot go backwards?

I imagine that the problem does not occur only with Teltonika, but with many devices connected via can-bus

**Comment by tananaev** [comment]
This is the first time I hear about this problem. Do you have a proof that it happens with other devices? Any references?

Also, what solution do you propose exactly? I imagine we can do something filtering, but need to know the logic to use.

**Comment by cop98** [comment]
I'll show you a concrete example:
In the summary you can clearly see that the odometer and fuel value is off.
The odometer you see is actually the distance attribute, when you see it at 0 at the moment this is used!

![1](https://user-images.githubusercontent.com/49091679/130098906-09473273-96e6-495c-b773-c356d4cf5e68.JPG)

This happened because the attributes were at 0 due to an automatic restart!

![2](https://user-images.githubusercontent.com/49091679/130100296-44fe03c9-97a8-423f-b20f-34d6871f3482.JPG)

![3](https://user-images.githubusercontent.com/49091679/130100495-0fd995c7-c1a4-4740-8163-d0292f4392e4.JPG)
In the last photo you can see the values resetting once the car is turned on. From the next day the reports are correct again until the next reboot

You should discard all values that are at 0 until you find the last values received before the restart.

**Comment by tananaev** [comment]
> You should discard all values that are at 0 until you find the last values received before the restart.

This is not a workable solution. Zero could be a valid value in some cases. In other cases devices could report zero forever for values that are not provided.

**Comment by prensburg** [comment]
Hi Cop98, in the Teltonika Configurator under CAN Adaptor settings you can disable "Send data with 0, if ignition is off". Left top of the CAN Adaptor settings page. Please check if that work for you.
