### ISSUE TITLE
Incorrect timestamp decode for Teltonika FMT100 or FMB920

### ISSUE THREAD

**Issue by YmaPl** [traccar/traccar#4726]
**Describe the bug**
Traccar decode timestamp from Teltonica devices with seconds difference. This event does not always occur but very often. 

**To Reproduce**
Just using device for longer time (several minutes)

**Expected behavior**
Correct issue in such a way that Traccar does not modify the deviceTime and fixTime value

**Screenshots**

1. Log screenshot from Traccar log file
<img width="1137" alt="raw_data_in_traccar_log" src="https://user-images.githubusercontent.com/89246898/130205046-84e23cf4-1ab4-4da9-b505-9d41c9b74737.png">

2. Data for this record in database
<img width="914" alt="result_in_database" src="https://user-images.githubusercontent.com/89246898/130205051-06f168d0-5d58-4209-bfb3-0226af2b7ee4.png">

3. Decoded frame with Teltonica frame decoder
<img width="794" alt="carrectly_decoded_data" src="https://user-images.githubusercontent.com/89246898/130205052-57276953-78de-431d-afab-218ac7b0e15b.png">

**Additional context**
We need to capture date at equal intervals of time but this is not possible with Traccar

BR. Yma

**Comment by YmaPl** [comment]
Here is the log in TXT mode for ease

`2021-08-18 10:49:45  INFO: [f14748fa] id: 352625696906948, time: 2021-08-18 10:49:43, lat: 51.38383, lon: 18.55632, speed: 68.6, course: 47.0
2021-08-18 10:49:45  INFO: [0bc2df86: teltonika < 185.99.25.65] HEX: 000000000000004208010000017b58e18d70000b0f699a1ea084b800ac002f14007f000c05ef01f00115024501fc0006b5000ab600064233d918007fcde683cee61e01f10000659200010000aeb6
2021-08-18 10:49:45  INFO: [0bc2df86: teltonika > 185.99.25.65] HEX: 00000001`

**Comment by iceberg1369** [comment]
@YmaPl could you please provide the link for teltonika frame decoder?

**Comment by tananaev** [comment]
@YmaPl you have to provide matching HEX and decoded data. Decoded data comes **after** raw HEX, not before.

**Comment by YmaPl** [comment]
I'm so sorry, of course you have right. It's my mistake. False alarm. Thank you for your comment and sorry again.
