### ISSUE TITLE
New Xexun protocol

### ISSUE THREAD

**Issue by darioniz** [traccar/traccar#4727]
Xexun has released new trackers that use a new protocol. I got a hand on the protocol description but I am wondering is anyone already working on implementation?

[XEXUN Devices and Server Data Protocol for GPS tracker 20210520 .pdf](https://github.com/traccar/traccar/files/7020744/XEXUN.Devices.and.Server.Data.Protocol.for.GPS.tracker.20210520.pdf)

**Comment by tananaev** [comment]
It doesn't seem to be supported and I don't think we are working on the implementation currently, but if you are interested in sponsoring the work, we can help with adding support for it.

**Comment by sean97140** [comment]
I am working on implementing this now, I have it about 80% written. I could use help getting my environment setup for testing this.

**Comment by sean97140** [comment]
I had it written and parsing all the sample data, and more I got from them directly in some code I wrote in C#, I have translated it to Java and Traccar, but I am struggling to get the dev env set up so I can debug the code live.

**Comment by tananaev** [comment]
Can you provide your branch to take a look?

**Comment by sean97140** [comment]
https://github.com/traccar/traccar/compare/master...sean97140:XexunBinaryProtocol?expand=1
I must warn you, it's fairly rough.

**Comment by sean97140** [comment]
[How to integration XEXUN device to your serve questions and answers.20210804 (3).pdf](https://github.com/traccar/traccar/files/7445827/How.to.integration.XEXUN.device.to.your.serve.questions.and.answers.20210804.3.pdf)

**Comment by sean97140** [comment]
I'd love to collaborate to make this a reality, I have a bunch of sample data streams, and have some of the actual devices that use this protocol. My main challange is getting my dev env setup so I can actually test this.

**Comment by tananaev** [comment]
Protocol is implemented.
