### ISSUE TITLE
Back button on Geofence page in modern UI exits to legacy UI.

### ISSUE THREAD

**Issue by pc500** [traccar/traccar#4734]
If you click the left arrow "back" as highlighted in this screenshot on the modern UI of 4.14, it exits to the legacy UI.  I believe the intent would be to stay in the modern UI and return to the main modern map page.

![image](https://user-images.githubusercontent.com/33823824/131262364-afea38a3-2c14-4eea-a54f-e9cbc7a98744.png)

**Comment by jinzo** [comment]
Probably needs to be reported here: https://github.com/traccar/traccar-web/issues ?

**Comment by tananaev** [comment]
Also, it would be nice to have steps to reproduce the issue.

**Comment by pc500** [comment]
Opened ticket here. https://github.com/traccar/traccar-web/issues/897

Reproduction should be fairly straightforward.  Go to the geofences page and click this back button.

I added these steps the new issue.
![image](https://user-images.githubusercontent.com/33823824/131266506-2b902ce3-8905-4ee9-a95c-7c0ab41b4d39.png)
