### ISSUE TITLE
Filter duplicates logic is not ideal

### ISSUE THREAD

**Issue by soshial** [traccar/traccar#4735]
**Describe the bug**
Imagine that a tracking device didn't have network available and after network reappears, it starts to re-upload locations in batches. Some of these location previously already had been uploaded, some of them had not. The device can't be 100% sure, since it uses UDP.

Current logic only takes the last location from DB and compares it with the new one.  But this logic would NOT discard a location that was already in the DB a month ago, for example. Can we change the logic here?
https://github.com/traccar/traccar/blob/8ecc4af154ec67a8818a21b96a9f10a74bfc919c/src/main/java/org/traccar/handler/FilterHandler.java#L149
https://github.com/traccar/traccar/blob/8ecc4af154ec67a8818a21b96a9f10a74bfc919c/src/main/java/org/traccar/handler/FilterHandler.java#L71-L81

**Comment by tananaev** [comment]
Filtering only works correctly if your device uploads locations in the correct order.

**Comment by soshial** [comment]
Yes, I understand that. But this scenario (uploads locations in the correct order) doesn't sound quite realistic to me.
Can we change the logic? It shouldn't be too hard to change that.

**Comment by tananaev** [comment]
Why is it not realistic?

**Comment by soshial** [comment]
I explained it in the main message: sometimes there is no coverage and no internet and these parts do not get uploaded at the time they were captured by GPS. How do we upload them to avoid dupicates?

**Comment by tananaev** [comment]
It's doable, but it would mean inconsistency between filtering implementations.

**Comment by soshial** [comment]
I wouldn't say so. Instead of _ultimately last_ position, we should load _relatively last_ position, i.e. the last before `fixTime` (of the position being added).

**Comment by tananaev** [comment]
It will have a pretty big performance impact.

**Comment by soshial** [comment]
Can we create a configurable setting for filtering to switch between ultimately and relatively last position?

**Comment by tananaev** [comment]
Sure. Would you be interested in contributing the change?
