### ISSUE TITLE
Globalstar Provision Support

### ISSUE THREAD

**Issue by pvictorlv** [traccar/traccar#4736]
**Describe the bug**
Can't finish the GlobalStar homologation because Traccar doesn't full support it.

**To Reproduce**
Just send the default and required provision requisition to traccar globalstar's port number (5185)
Req 1: 
```
<?xml version="1.0" encoding = "UTF-8"?>
<prvmsgs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://cody.glpconnect.com/XSD/ProvisionMessage_Rev1_0.xsd" timeStamp="25/08/2009 21:00:00 GMT" prvMessageID="56bdca48088610048fddba385e1cd5b8">
</prvmsgs>

```
Req 2:
```
<?xml version="1.0" encoding = "UTF-8"?>
<prvmsgs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://cody.glpconnect.com/XSD/ProvisionMessage_Rev1_0.xsd" timeStamp="25/08/2009 21:00:00 GMT" prvMessageID="56bdca48088610048fddba385e1cd5b8">
<prvmsg>
<esn>9-99998</esn>
<provID>1234</provID>
<tStart> 10:30:00 </tStart>
<tEnd> 12:30:00 </tEnd>
<txRetryMinSec> 100 </txRetryMinSec>
<txRetryMaxSec> 600 </txRetryMaxSec>
<txRetries>2</txRetries>
<rfChannel> A </rfChannel>
</prvmsg>
<prvmsg>
<esn>9-99999</esn>
<provID>2345</provID>
<tStart> 11:30:00 </tStart>
<tEnd> 12:30:00 </tEnd>
<txRetryMinSec> 100 </txRetryMinSec>
<txRetryMaxSec> 600 </txRetryMaxSec>
<txRetries>2</txRetries>
<rfChannel> A </rfChannel>
</prvmsg>
</prvmsgs>

```
**Expected behavior**
We need to get any response from the server. At the moment, we got only "Error: socket hang up"
Expected response: 
```
<?xml version="1.0" encoding="UTF-8"?>
<prvResponseMsg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://cody.glpconnect.com/XSD/ProvisionResponse_Rev1_0.xsd"
deliveryTimeStamp="02/03/2012 17:38:06 GMT" messageID="8675309"
correlationID="56bdca48088610048fddba385e1cd5b8">
<state>PASS</state>
<stateMessage>Store OK</stateMessage>
</prvResponseMsg>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/10038242/131903410-06385e82-5595-4b28-b1e7-027b7ff39b27.png)
![image](https://user-images.githubusercontent.com/10038242/131903466-8c8133a9-ae6e-4631-8253-1f60fc4c0859.png)

**Comment by tananaev** [comment]
There is a response:

https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/protocol/GlobalstarProtocolDecoder.java#L85-L117

I would recommend debugging the code to see why your specific requests are not processed correctly.

**Comment by pvictorlv** [comment]
@tananaev the error only occurs when we try provisions requests. The STUs works perfectly.
![image](https://user-images.githubusercontent.com/10038242/131916647-b34b4515-2950-4705-982a-be17ff513863.png)

**Comment by tananaev** [comment]
Yeah, then it looks like it's not supported currently. You should still be getting a response though, but it would be incorrect response.

**Comment by pvictorlv** [comment]
Exactly, but we need it in order to get GlobalStar approval.
Without it, they don't allow the use.

**Comment by tananaev** [comment]
Feel free to send a pull request.

**Comment by MarceloMJM** [comment]
Dear Sirs, I am facing the same problem reported above, in the provisioning request, error socket hang up.
Traccar Version 6.5
I'm grateful for any help.

![Error-socket](https://github.com/user-attachments/assets/1648f37f-cba0-44ed-8ae1-31a9878645f7)
