### ISSUE TITLE
Sinotrack HuabaoProtocol - OBD Information

### ISSUE THREAD

**Issue by arindamsaha1976** [traccar/traccar#4738]
Hi,

I am using the tracer application. Honestly, it is a great platform.

I purchased Sinotrack device and integrated with tracer. Now problem is it doesn't talk to the given protocol - h02. But I tried - HuabaoProtocol and it worked. But now the problem is I am not getting the OBD details like rpm, air pressure, coolant temp etc. However those information are available in their portal.

Could you please help me with that

Thanks,
Arindam

**Comment by tananaev** [comment]
Please use the forum for questions.
