### ISSUE TITLE
Offline version

### ISSUE THREAD

**Issue by kerzol81** [traccar/traccar#4739]
Hi, I managed to make the previous 2 versions full offline. I modified the loads.js file to load the necessary **js** and **css** files from locally. I need to make it offline since the firewall configuration is very strict. But this new version is bit different.

I created a shell script to download all the cdn hosted files:
https://github.com/kerzol81/traccar_mods/blob/main/offliner.sh

and then modified the load.js file:
https://github.com/kerzol81/traccar_mods/blob/main/load.js

And interestingly, when I try to add this css in line 128:
_//addStyleFile('offline/theme-triton-all.css');
This does not work all the graphic is broken immediately.

Could you please help with this?

**Comment by tananaev** [comment]
Have you missed the news? Traccar is already serving all dependencies locally.

**Comment by kerzol81** [comment]
I might have :-) But I'm using the dockerized version, and there ar a dozen CDN requests going out for the graphics.
