### ISSUE TITLE
button to delete old data

### ISSUE THREAD

**Issue by kerzol81** [traccar/traccar#4742]
Dear Anton,

I'm using 2-3 traccars in docker containers at the company. I dont intend to use outside mysql server H2 local engine is ok. 
Is there a way to build in a button into the web interface to clear old data? Such as clear older than 30-60-90-120 days on all devices?

Thanks, 

Zolee

**Comment by tananaev** [comment]
There's no plan to add a button. Also, you shouldn't use H2 because it often gets corrupted.
