### ISSUE TITLE
Тraccar messed up device coordinates 

### ISSUE THREAD

**Issue by bastijan** [traccar/traccar#4743]
**Describe the bug**

Coordinates of device 1275164376  traccar stored as device 1275123671 coordinates!!!

2021-09-11 21:49:11  INFO: [d1a5d479: calamp < 12.153.230.160] HEX: **8305127516437601010102007f613d2457613d245614be5df8cea69be5000064c30000000000001002019aff9f0f0680001c02040000000f94000030d4017e8f03002fa6e3**
2021-09-11 21:49:11  WARN: Unknown device - 1275164376 (12.153.230.160)
2021-09-11 21:49:11  INFO: [d1a5d479: calamp > 12.153.230.160] HEX: 0201007f020000000000
2021-09-11 21:49:11  INFO: [d1a5d479] id: 1275123671, time: 2021-09-11 21:49:11, **lat: 34.80202, lon: -82.79419**, course: 0.0
2021-09-11 21:49:28  INFO: [d1a5d479: calamp < 12.153.231.160] HEX: 83051275123705010101020c59613d2468613d2468181e6b00d27e375a0000313700000c0b00fa1202019affb70f0691002c6f040000000f84000035840520aecb00ea9b64
2021-09-11 21:49:28  INFO: [d1a5d479: calamp > 12.153.231.160] HEX: 02010c59020000000000

**Screenshots**

![image](https://user-images.githubusercontent.com/1077956/133116280-607b25ec-2ae3-4887-9128-f493c029a6f1.png)

and all routes are messed up
![image](https://user-images.githubusercontent.com/1077956/133116447-cc33ab22-defc-4c96-b29c-14964cbc3f4b.png)

**Comment by tananaev** [comment]
1. Are you using the latest official release without any modifications to the code or config?
2. Can you please provide longer fragment of the log for testing.

**Comment by bastijan** [comment]
1) Traccar was installed on October 30 latest release at this time. Nothing changed in the code.

I have a plan upgrade today to the latest version and I'll inform you again.

2) Here is my traccar.xml

<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <entry key="config.default">./conf/default.xml</entry>

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://localhost/traccar?serverTimezone=UTC&amp;useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
    <entry key='database.user'>**********</entry>
    <entry key='database.password'>**************</entry>

    <entry key='database.saveOriginal'>true</entry>

    <entry key='filter.enable'>true</entry>
    <entry key='filter.zero'>true</entry>
    <entry key='filter.duplicate'>false</entry>
    <entry key='filter.future'>10800</entry>
    <entry key='filter.maxSpeed'>20000</entry>


    <entry key='processing.remoteAddress.enable'>true</entry>
    <entry key='processing.copyAttributes.enable'>true</entry>
    <entry key='processing.copyAttributes'>power,ignition,battery</entry>
    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>nominatim</entry>
    <entry key='geocoder.url'>https://****OUR URL*****</entry>

</properties>

and log files

[tracker-server.log](https://github.com/traccar/traccar/files/7156093/tracker-server.log)
[tracker-server.log.txt](https://github.com/traccar/traccar/files/7156095/tracker-server.log.txt)
[tracker-server.log.20210910.txt](https://github.com/traccar/traccar/files/7156096/tracker-server.log.20210910.txt)
[tracker-server.log.20210911.txt](https://github.com/traccar/traccar/files/7156097/tracker-server.log.20210911.txt)

**Comment by bastijan** [comment]
The new version of Traccar was installed, this is the current state, I used gsp data after installation

Still exists coordinates that go to few points. I investigate this location and seems as AT&T data center coordinates

![image](https://user-images.githubusercontent.com/1077956/133138377-90543bde-5546-41b6-bff6-3ff8e2ac7d02.png)

**Comment by tananaev** [comment]
Can you please provide new logs and point out incorrectly assigned location there.

**Comment by bastijan** [comment]
Of course, this is the new  log
[tracker-server.log.txt](https://github.com/traccar/traccar/files/7156746/tracker-server.log.txt)

**Comment by tananaev** [comment]
I looked through your logs and there's no way to clearly identify which HEX belongs to which location message. You have geocoding enabled, which means that everything can be mixed up together. How did you identify matching logs?

**Comment by bastijan** [comment]
Please check the first screenshot.
On the right side, I decoded HEX message. This message contains: 
device id (MobileID): 1275164376
lat: 34.80202, lon: -82.79419

After this log recorded: 
WARN: Unknown device - 1275164376

And FINALY in database stored DeviceId: 1275123671, time: 2021-09-11 21:49:11, lat: 34.80202, lon: -82.79419

This can see in the snippet of the log that I copied in the issue report.

This is a clear issue - the unknown device message trigger putting data to the next received device.

On today's route report brown device (9375-1275164307) mix up coordinates with RED (5447-1275123707) and VIOLET path

![image](https://user-images.githubusercontent.com/1077956/133208747-85083905-26d4-4176-9cb4-70ef1f8e6bcb.png)

In this magnified screenshot you can see how the route is hijacking from another route. This can be a device issue - coordinates (brown) lie right on highway on path of another route (violet). The real path and coordinates of the brown route/device are about 600 miles south in Chattanooga TN, not near Chicago IL.

![image](https://user-images.githubusercontent.com/1077956/133209193-9cb70945-dfa3-4f60-ac7b-ca0c7d6ef830.png)

A similar issue is on the south of the same path (brown):

![image](https://user-images.githubusercontent.com/1077956/133209911-50105000-4a2d-4dc7-a78d-e3969e93e3a3.png)

There is no way to device sent wrong coordinates that lie exactly on the path of another device. This must be an application issue.


Yes, geocoding is enabled, but this is a future of Traccar, right?z

**Comment by tananaev** [comment]
I believe that there could be an issue. What I don't understand is how you determined which specific HEX corresponds to which stored message in the database.

**Comment by bastijan** [comment]
I using Cal/Amp LMU Toolbox to decoding HEX.
**2021-09-11 21:49:11 INFO: [d1a5d479: calamp < 12.153.230.160] HEX: 8305127516437601010102007f613d2457613d245614be5df8cea69be5000064c30000000000001002019aff9f0f0680001c02040000000f94000030d4017e8f03002fa6e3**

Cal/Amp LMU Toolbox show me  
DeviceId **1275164376** lat: 34.80202, lon: -82.79419

Two lines below this HEX message I found decoded line with the same coordinates but the different device (the difference is about 600 miles)
**2021-09-11 21:49:11 INFO: [d1a5d479] id: 1275123671, time: 2021-09-11 21:49:11, lat: 34.80202, lon: -82.79419, course: 0.0**

DeviceId: **1275123671**, time: 2021-09-11 21:49:11, lat: 34.80202, lon: -82.79419

**Comment by tananaev** [comment]
OK, that makes sense now. Have you tried `calamp.ignoreSessionCache` config parameter? Does it help?

**Comment by bastijan** [comment]
Let mi try and I will inform you later.

**Comment by bastijan** [comment]
calamp.ignoreSessionCache stopped receiving GPS data
calamp.ignoreSessionCache false give me a similar issue with less errors
![image](https://user-images.githubusercontent.com/1077956/133449804-0672aa81-ec47-49df-9c2e-f9e887229b31.png)

**Comment by tananaev** [comment]
False is the default. Is there a way for you to test with just two devices and disabled geocoding, so we have smaller and cleaner log to investigate?

**Comment by bastijan** [comment]
Yes, I can. But I can report to you tomorrow

**Comment by tananaev** [comment]
Please try on the latest release. We changed device session logic a lot.
