### ISSUE TITLE
Slow working without any errors

### ISSUE THREAD

**Issue by nabiloce** [traccar/traccar#4745]
Hello ,
After a long time of normal operation, we have a bug without errors the server started to generate delay in a precise time of the day (9h - 20h) where is the top time of sending data.

devices type : teltonika , ruptela , gps103 .
version of traccar 4.5 with a lot of customized change.

Number of devices 7000.
server configuration 16CPU - 64Go - Ubuntu 18.04.

htop 
![prob11](https://user-images.githubusercontent.com/15571323/133767434-0e7c21e3-e3f8-41aa-83cb-661e65649c53.PNG)

ps -x | netstat -ant | awk '{print $6}' | sort | uniq -c | sort -n
![prob22](https://user-images.githubusercontent.com/15571323/133769300-543454db-2302-40fe-8685-d9bfa2a8d449.png)

we have added some message to log to find where the start appear 
![prob33](https://user-images.githubusercontent.com/15571323/133769336-0b1022bc-3131-4549-8cd2-8d91bf59bb1d.png)

how you can see that the device connects to the server but remains stabilized for 10 seconds or more before starting the processing of the frame 

What could be the source of problem ?

Best Regards

**Comment by tananaev** [comment]
Where did you add the log exactly?

**Comment by nabiloce** [comment]
we added message with channel remote address into  MainEventHandler  => channelActive 

    @Override
    public void channelActive(ChannelHandlerContext ctx) {
        if (!(ctx.channel() instanceof DatagramChannel)) {
            LOGGER.info(formatChannel(ctx.channel())+"  "+ctx.channel().remoteAddress()+ " connected");
        }
    }
and into NetworkMessageHandler 
 ```
 @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) {
        LOGGER.info(ctx.channel().remoteAddress()+ " channel reader");  // <=== LINE ADDED
        if (ctx.channel() instanceof DatagramChannel) {
            DatagramPacket packet = (DatagramPacket) msg;
            ctx.fireChannelRead(new NetworkMessage(packet.content(), packet.sender()));
        } else if (msg instanceof ByteBuf) {
            ByteBuf buffer = (ByteBuf) msg;
            ctx.fireChannelRead(new NetworkMessage(buffer, ctx.channel().remoteAddress()));
        }
    }
```
we do simulator of device to see how it work.
you can see in the first Picture how time he take between the connection of device and the traitement .
between channelActive and channelRead

**Comment by tananaev** [comment]
So sounds like the issue is somewhere internally in Netty. Maybe you need more threads? Or maybe something blocks existing threads causing this. Probably a good idea to analyze jstack dump.

**Comment by nabiloce** [comment]
thank you so much,
I have already loaded the jstack but I found it difficult to analyze it
[jstack2.txt](https://github.com/traccar/traccar/files/7186742/jstack2.txt)
.
