### ISSUE TITLE
h2 database clean

### ISSUE THREAD

**Issue by kerzol81** [traccar/traccar#4749]
Hi, 

it's not really an issue however I'd like to be able to clear the H2 database since I never managed to deploy traccar in docker with mysql.

This is the test script:
https://github.com/kerzol81/traccar_mods/blob/main/dbmanager.py

and here is the debug message:
```
org.h2.jdbc.JdbcSQLSyntaxErrorException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TC_EVENTS" not found; SQL statement
```
And surely there is a device on the traccar (my phone with osmand protocol). I'd like just 3 days data in the H2 server so I thought I would create a python script that is run every day once by cron to keep the database small. i guess the H2 database tables are not the same structre as it would be a mysql database.

Do you have any suggestion?

Thanks

**Comment by tananaev** [comment]
You should use the forum for questions.
