### ISSUE TITLE
Teltonika Attribute ID389 Conflict

### ISSUE THREAD

**Issue by sfthink** [traccar/traccar#4760]
The implementation of decoding attribute with id 389 in TeltonikaProtocolDecoder.java as position.set(Position.KEY_ALARM, Position.ALARM_SOS) conflicts with the the current Teltonika protocol specification where id 389 is "OBD OEM Total Mileage".

Source: https://wiki.teltonika-gps.com/view/FMB003_Teltonika_Data_Sending_Parameters_ID#OBD_OEM_elements

I verified the linked specification with a current generation FMB003 tracker with newest firmware. However, I am not sure whether this is a bug in traccar or the Teltonika protocol changed.

**Comment by tananaev** [comment]
Removed the mapping.
