### ISSUE TITLE
Startek protocol not decoded correctly

### ISSUE THREAD

**Issue by slachtar** [traccar/traccar#4767]
startek protocol is not being decoded even when using last code from master branch.

The trccar output in log in hex is:
``
2626573134392c3836353432393034333331393533372c3030302c302c2c3231313130333031333531322c412c32322e3637393030332c3131342e3034353038352c31362c312e312c302c3237312c37362c3130393037352c3436307c307c323439467c30303030313043352c31392c30303030303033452c30302c30302c304135377c303136387c303030307c303030302c312c30313030303030430d0a
``

when converted to ascii:
``
&&W149,865429043319537,000,0,,211103013512,A,22.679003,114.045085,16,1.1,0,271,76,109075,460|0|249F|000010C5,19,0000003E,00,00,0A57|0168|0000|0000,1,0100000C
``

**Comment by tananaev** [comment]
Please provide protocol documentation.

**Comment by slachtar** [comment]
Please find here the required protocol documentation.
[iStartek GPS Tracker Communication Protocol V1.3.pdf](https://github.com/traccar/traccar/files/7482736/iStartek.GPS.Tracker.Communication.Protocol.V1.3.pdf)

**Comment by tananaev** [comment]
The format doesn't seem to match, but added more relaxed check to decode at least common data.

**Comment by slachtar** [comment]
Hello,
compiled the last source version, but still not decoded:

2021-11-08 08:54:21  INFO: [fe76b182: startek < 223.104.63.194] HEX: 2626563135372c3836313135373034303030393735312c3030302c302c2c3231313130383038353432312c412c32322e3637383538312c3131342e3034363138332c31392c302e382c302c3334342c36342c32303531372c3436307c307c323439467c30414332363230442c33312c30303030303031462c30302c30302c303442317c303141347c303030307c303030302c312c3031303030307c3032303030302c2c46420d0a

thanks
