### ISSUE TITLE
Order.java file missing

### ISSUE THREAD

**Issue by asymptotes** [traccar/traccar#4768]
**Source file missing from the archive**
/traccar-4.14/src/main/java/org/traccar/database/Order.java file is missing from the release tag of 4.14.

**To Reproduce**

1. Download the release tag of 4.14 from https://github.com/traccar/traccar/archive/refs/tags/v4.14.zip
2. Build from source using the command ./gradlew assemble
3. Got the following error
```
/var/www/html/traccar-4.14/src/main/java/org/traccar/database/DataManager.java:44: error: cannot find symbol
import org.traccar.model.Order;
                        ^
  symbol:   class Order
  location: package org.traccar.model
/var/www/html/traccar-4.14/src/main/java/org/traccar/database/DataManager.java:398: error: cannot find symbol
                return Order.class;
                       ^
  symbol:   class Order
  location: class DataManager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

```
**Additional context**
I fixed this issue by copying the file from master branch.

**Comment by tananaev** [comment]
I just checked `DataManager` from the tag and it doesn't have anything about orders. Looks like you didn't get it from the tag.

**Comment by asymptotes** [comment]
Hi Tananaev,
I have checkced this once again today by downloading both .zip and tar.gz extensions from https://github.com/traccar/traccar/releases
Still i found Order.java missing in the files
I get the erroe about the missing files when i try to build .jar file from the souce.

**Comment by tananaev** [comment]
Please carefully read my comment.
