### ISSUE TITLE
Fixing Device bug using Traccar Server

### ISSUE THREAD

**Issue by mail2bishnoi** [traccar/traccar#4780]
Hi Anton,

Earlier I have discussed this issue with you and could not convince you to add the solution to the Traccar server. The problem is not in the traccar server, but in some devices.

Problem: Sometimes when we immediately stop the vehicles/devices, it might be possible that devices continuously report speed more than zero even if devices are stopped. For example, see below details
```
 Fix Time                          Latitude          Longitude        Speed
2021-12-10 22:27:45     23.034113°     70.137090°      4.3 kn
2021-12-10 22:27:45     23.034113°     70.137090°      4.3 kn
2021-12-10 22:27:45     23.034113°     70.137090°      4.3 kn
2021-12-10 22:27:45     23.034113°     70.137090°      4.3 kn
```
From the above details, it's clear that the device is idle, and due to some bug or whatever, the problem device is reporting speed more than zero.

Solution: When we process positions data we can check FixTime, latitude, and longitude in the current position and all three are the same as in the last position we can make speed zero.
```java
if (position.fixTime == lastPosition.fixTime && position.latitude == lastPosition.Latitude && position.longitude == lastPosition.longitude ) {
position.speed = 0;
}
```
if you allow me to merge, I can open a PR for this issue.

Thanks

**Comment by tananaev** [comment]
It doesn't make sense. You can see it's the same timestamp. It doesn't prove that device didn't move.

**Comment by mail2bishnoi** [comment]
Hi Anton,

Can you please explain How it doesn't make sense? 

I think it makes more sense because fixTime is the same, latitude is the same, longitude is the same and even if the course is also the same and it's a sure shot sign that the device is stationary. However, serverTime is different for every position.

FYI, I am discussing it because my clients are complaining that their devices are stationary and still server is reporting a speed more than zero.

Thanks.

**Comment by tananaev** [comment]
It doesn't make sense because you will have position with the same timestamp and different values. It is simply false information. At that point in time device had a speed value that is not zero. This situation can also happen when device is not stationary.

**Comment by mail2bishnoi** [comment]
0k.
