### ISSUE TITLE
gt02a no location information.

### ISSUE THREAD

**Issue by ly012156** [traccar/traccar#4799]
Hi. I have a gt02a gps tracker. Using your platform: http://demo.traccar.org. The device's imei=868120138313363. I text the gps tracker: dserver,666666,1,demo.traccar.org,5002,0# and dserver,666666,1,demo.traccar.org,5013,0#. SMS recovery is "ok". I have 2 accounts registered. rv1: 868120138313363, rv2: 020138313363. But no location information. Please help. thanks.

**Comment by tananaev** [comment]
Please use forum for questions. Also, we don't provide support for demo servers.
