### ISSUE TITLE
V4.15 Critical error and crash

### ISSUE THREAD

**Issue by TecSeguridad** [traccar/traccar#4802]
We did the update from version 4.13 to 4.15 and after a day traccar got deactivated and we couldn't get it working again not even reinstalling. We went back to version 4.13.

An error log file was generated "A fatal error has been detected by the Java Runtime Environment"

[hs_err_pid921.log](https://github.com/traccar/traccar/files/7956007/hs_err_pid921.log)

**Comment by tananaev** [comment]
Looks like JVM bug. You can try using different Java version.

**Comment by TecSeguridad** [comment]
Anton thanks for the answer, although I have 2 instances with the same version of java and only one failed, maybe it's just a coincidence. Which version do you recommend for Traccar 4.15? Greetings

**Comment by tananaev** [comment]
I recommend the latest stable LTS version.
