### ISSUE TITLE
Position is not Updating since 4.15

### ISSUE THREAD

**Issue by drive-n-code** [traccar/traccar#4808]
I've updated traccar to version 4.15 (docker image traccar/traccar:4.15-alpine).
Since the Update the positions of the vehicle positions are not updating anymore. They are online (green) with last update 0 minutes ago, but they don't move.

The lastUpdate Timestamp is available in the database, but the positions are missing:

```
SELECT lastupdate FROM tc_devices ORDER BY lastupdate DESC LIMIT 1;
+---------------------+
| lastupdate          |
+---------------------+
| 2022-02-02 11:59:03 |
+---------------------+
1 row in set (0.001 sec
```

```
SELECT devicetime FROM tc_positions ORDER BY devicetime DESC LIMIT 1;
+---------------------+
| devicetime          |
+---------------------+
| 2022-01-28 02:30:01 |
+---------------------+
1 row in set (1.603 sec)
```

The positions are received with the osmand protocol.

**Comment by tananaev** [comment]
Have you tried disabling geocoding?

**Comment by drive-n-code** [comment]
Thanks. It works again after disabling geocoding / set geocoding on user request only.

I was a little bit confused, because everything was working fine again after a downgrade to version 4.14. No it's also fine for version 4.15 with the following geocoding config `<entry key='geocoder.onRequest'>true</entry>`
