### ISSUE TITLE
Add calendar bug Traccar v4.15

### ISSUE THREAD

**Issue by Palmc** [traccar/traccar#4809]
**Describe the bug**
Unable to add a calendar

**To Reproduce**
1. Go to Settings > Calendars
2. Click on Add
3. Fill the name and click save

```
Error at line 1:Unexpected end of file at [Source: 

(org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 28] 

(through reference chain: org.traccar.model.Calendar["data"])
```

**Expected behavior**
It should be able to add a new calendar.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: V1.35.100

Tested with another browsers with the same result.

Has anyone else experienced this issue ?

Thanks !

**Comment by tananaev** [comment]
Looks like you haven't uploaded the actual calendar file. That's exactly what the errors is about.

**Comment by Palmc** [comment]
Nevermind, i just tried to generate the .ics file and worked like a charm.

Thanks !
