### ISSUE TITLE
"Last update" column data (in devices table) getting lost after logout

### ISSUE THREAD

**Issue by Arismane** [traccar/traccar#4815]
**Describe the bug**
Data is received from a device, last update data is stored and showed in column, but if the user logs out from the web gui and logs in again the "last update" column is empty.

**To Reproduce**
1. Just get some data from devices
2. Log out from web gui
3. Login again
4. Last update column is empty

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Mozilla Firefox
 - Version 97

**Traccar Server installed in Debian Linux 11 (bullseye) 64 version**

**Comment by tananaev** [comment]
Looks like 4b4201de3519ce744dcbba303bd10aaaa4d3fa7b broke it, so reverted it 5f007edebf88afb353f26310645639e051a53c0e.
