### ISSUE TITLE
osmand add course parameter 

### ISSUE THREAD

**Issue by abhijitgujar86** [traccar/traccar#4825]
**Is your feature request related to a problem? Please describe.**
Although we have api to add positions i found that course is not passed 

**Describe the solution you'd like**
```
http://demo.traccar.org:5055/?id=123456&lat={0}&lon={1}&timestamp={2}&hdop={3}&altitude={4}&speed={5}&course={65.34}
```

**Comment by tananaev** [comment]
You can use either "heading" or "bearing".
