### ISSUE TITLE
instalation doesnt work in vps or linux 

### ISSUE THREAD

**Issue by waleedelsafty** [traccar/traccar#4831]
following server installation steps [Install on VPS](https://www.traccar.org/install-digitalocean/), and [Linux Installation](https://www.traccar.org/linux/)  
 after finishing the setup steps 
 and starting the server.  the server doesn't start  at all ,  and the http://IP_ADDRESS:8082 has nothing 
 
  i tied installing on windows  and it did not work ,  but I don't want to run the server on my local machine 
  I want to run in on my c panel account but there is no clear instruction and there is no clear schema for  creating the MySQL database 
  
 why  does  the open-source server be so secretive , with very little  instructions or documentation

**Comment by tananaev** [comment]
Please use the forum for questions.
