### ISSUE TITLE
Blank hash & salt on new user

### ISSUE THREAD

**Issue by arpanEnbake** [traccar/traccar#4837]
**Describe the bug**
After the latest pull, when trying to create a new user from admin panel, salt and hashedpassword are going blank in the database.

**To Reproduce**
Checkout latest code
Login via admin / admin (h2 database, same with postgres too)
Create an user
In a new window try to login with same creds 
It fails to login
Database has blank hashedpassword and salt.

**Expected behavior**
User should have all data filled and able to login.
Branch checkedout : master

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by arpanEnbake** [comment]
Just to add. this is happening because of queryExtended added in User.java. 
https://github.com/traccar/traccar/commit/1c73bae2e23242673e0a07cdbc2493700f134ceb

**Comment by tananaev** [comment]
Try storage branch.

**Comment by arpanEnbake** [comment]
@tananaev  Seems to work fine in storage branch.

Here is steps in summary, For master branch:

1. Create new user
2. Try to login with new user creds 
3. Null error
4. Set password again
5. Works fine, user can now login
6. Edit user, set attributes, user login works fine.

If we comment queryExtended then:
1. Create new user
2. Try to login with new user creds 
3. Works fine now
4. but Edit user, set attributes , password is set null. User can not login

**Comment by tananaev** [comment]
If it's already fixed in the storage branch then we can close this ticket. We plan to merge it before the release.

**Comment by arpanEnbake** [comment]
@tananaev  should we use storage branch ?
Will it has all the latest code updates otherwise.

**Comment by tananaev** [comment]
Both master and storage are unstable branches with active development. I don't recommend using either.

**Comment by BIhab** [comment]
Hi Anton, I'm facing the same issue.
Log:

XHRPOSThttp://localhost:3000/api/session
[HTTP/1.1 400 Bad Request 37ms]

1

NullPointerException (... < DataConverter:29 < Hashing:82 < User:298 < ...)

When I try to print  log hashedPassword and salt, I got that there are equal to null, I'm trying to solve the issue and check if it's a specific or general issue, if you have any idea it will be really helpful unless I'm missing something.

**Comment by tananaev** [comment]
If you want to report a bug, you should create a separate ticket and provide all details. If you're not sure if it's a bug, you should use the forum instead.
