### ISSUE TITLE
Commands Teltonika GPRS

### ISSUE THREAD

**Issue by sinjero97** [traccar/traccar#4838]
Hello greetings. I have a doubt with the teltonik protocol
I understand that it is possible to send teltonika commands but the format is not clear to me.
I need to control the remote shutdown or blocking of a vehicle by gprs via traccar.
Do you have a documentation or list of commands that you can provide me with. Do they need to be custom?
Thanks for your time

**Comment by tananaev** [comment]
Please use the forum for questions.
