### ISSUE TITLE
StarLinkMessage class not found in the project

### ISSUE THREAD

**Issue by novaris** [traccar/traccar#4844]
**Describe the bug**
StarLinkMessage class not found in the project.

**To Reproduce**
1. Geting  project from git.
2. Generate project for eclipse: gradle eclipse (adding eclipse plugin into build.gradle)
3. Project not compile - org.traccar.protobuf.starlink.StarLinkMessage - not found in StarLinkProtocolDecoder

**Screenshots**
![image](https://user-images.githubusercontent.com/13179534/167883837-15e4bb24-448b-4dad-aeab-ede873f35ff3.png)

**Additional context**
May by StarLinkMessage not added into git

**Comment by novaris** [comment]
Yes, i figured out the answer? In Eclipse need  installed protobuf-dt.

**Comment by tananaev** [comment]
You can just compile it from the command line once and then it should work without any plugins.
