### ISSUE TITLE
Cannot create group or view existing groups in latest master. MySQL database

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar#4846]
**Describe the bug**
Groups not visible to a user after browser refresh. MySQL database.

**To Reproduce**
1. Go to settings, groups
2. Click on add
3. Create new group
5. Refresh browser
6. Go back to settings, groups and the group is not showing.
7. Select users, user, groups and the groups are there.
8. Select the groups to link to the user.
9. Refresh browser and go back into groups and the groups are not visible.
10. When calling group api see error:
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups ON tc_user_group.groupid = groups.parentid WHERE userId = 1)' at line 1 - SQLSyntaxErrorException (... < QueryBuilder:405 < DatabaseStorage:58 < SimpleObjectResource:54 < ...)
```
**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser 'Edge'

**H2 Database
When connecting to H2 database all works fine

**Comment by tananaev** [comment]
Are you sure you're using the latest code? I'm not able to reproduce with today's code.

**Comment by joystickjockey** [comment]
1. I've cloned master:
git clone --recurse-submodules https://github.com/traccar/traccar.git
(cd traccar/traccar-web && git checkout master)

2. Minified web app

3. Created new database called 'traccar'

4. Made below changes to traccar.xml





<entry key='database.driver'>com.mysql.cj.jdbc.Driver</entry>
<entry key='database.url'>jdbc:mysql://localhost:3306/traccar?serverTimezone=UTC&amp;allowPublicKeyRetrieval=true&amp;useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
<entry key='database.user'>my username</entry>
<entry key='database.password'>my password</entry>

5. Opened web browser and connect to server. Login with user admin, password admin

6. Create new group.

7. Refresh web page and the group is not showing.

Am I doing something wrong or different to how you would do it?

https://user-images.githubusercontent.com/63212232/170150160-0a3601a0-7653-4d2e-87c7-eb563f1b9b72.mp4

**Comment by tananaev** [comment]
That's correct, but we're actively working on the project, so things change many times every day. Are you sure you pulled the latest code from today?

**Comment by joystickjockey** [comment]
Hi Anton, I've pulled it about 1 hour ago.

**Comment by joystickjockey** [comment]
Changed back to H2 database and it works fine.


https://user-images.githubusercontent.com/63212232/170152884-618c80da-3b64-4621-9d6d-849c43287e8d.mp4

**Comment by tananaev** [comment]
What version of MySQL are you using?

**Comment by joystickjockey** [comment]
Ver 8.0.29-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))

**Comment by metacreo** [comment]
'group' and 'groups' in mysql are reserved words and must be escaped.
https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-G
`check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups ON tc_user_group.groupid = groups.parentid WHERE userId = 1)' at line 1`

**Comment by metacreo** [comment]
leave mysql config with added lines and try edit traccar.xml
change db connection entry to:
`<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/traccar?serverTimezone=UTC&amp;useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>`

**Comment by metacreo** [comment]
I think  sql_mode still not switched try to connect to mysql from console and set right mode
$ mysql -uroot -p
mysql> show variables like '%mode%';
and if sql_mode have any value set:
mysql> SET sql_mode = '';

**Comment by tananaev** [comment]
Please try this:

https://github.com/traccar/traccar/commit/8e8a435cea0ea44dfcb20b45dcbb881b87361676

**Comment by metacreo** [comment]
> Please try this:
> 
> [8e8a435](https://github.com/traccar/traccar/commit/8e8a435cea0ea44dfcb20b45dcbb881b87361676)

I built and start. All ok. Works like before. No changes. But 8e8a435 is still good idea.

I think this issue is not related to traccar. Because I have mysql 8.0.28 on freebsd and no problem with group creation query. I think this issue related to mysql server config more than traccar.

**Comment by joystickjockey** [comment]
I have other servers running mysql 8.0.29 with traccar v4.15 and have no issues but wit latest master have issues

**Comment by metacreo** [comment]
I updated mysql to mysql80-server-8.0.29 and traccar to 5. No issues with group creation. All queries to database return without errors.
