### ISSUE TITLE
Summary report crash

### ISSUE THREAD

**Issue by cop98** [traccar/traccar#4848]
**Describe the bug**
When I add the "fuel consumption" column to the summary report, the session crashes

Traccar version: 5.0

**To Reproduce**

MODERN INTERFACE

1. Go to Report
2. Create summary reports
3. Add in the Columns "fuel consumption"
4. Click view 
5. See error

**Expected behavior**
The report should work

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser [Chrome]
 - Version [last]

**Comment by tananaev** [comment]
Please report tickets in the right place:

https://github.com/traccar/traccar-web
