### ISSUE TITLE
[Modern} - Replay on a day with no dataloads blank screen

### ISSUE THREAD

**Issue by OutrightHosting** [traccar/traccar#4849]
**Describe the bug**
Trying to replay track from a tracker for a day with no data causes blank page and undefined error in console. 

**To Reproduce**
Create a device, 
Select Replay
Choose a day with no data

**Expected behavior**
An error message on the map to say no data for this date or similar would be good. 

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/72134131/170126263-adb118c6-5d24-4008-9df6-c28094a89bb4.png)

**Comment by tananaev** [comment]
Fixed here https://github.com/traccar/traccar-web/commit/c1bf7f8adf2d5b2206c7da2e618d4df43f3a57c2. Next time can you please report web app issues in the [traccar-web](https://github.com/traccar/traccar-web) repo.
