### ISSUE TITLE
unable to edit/delete user, add device and report

### ISSUE THREAD

**Issue by arpanEnbake** [traccar/traccar#4852]
**Describe the bug**
In the latest master, with database storage, we are unable to delete user as permission fails. 
Reason is because generic permission class assumes both columns as userId. Hence query fired is 
```
 SELECT id FROM tc_users WHERE id IN (SELECT userid FROM tc_user_user WHERE userId = :userId)
 ```
As a workaround, i have put following code in DatabaseStorage class in formatPermissionQuery
```
+        if (outputKey.compareTo("userId") == 0 && outputKey.compareTo(conditionKey) == 0) {
+            outputKey = "manageduserid";
+        }
```
Another issue  was builder replace variable was missing in DatabaseStorage (getPermissions function). This was causing device add issue.

```
+        Condition conditionAll = Condition.merge(conditions);
+        query.append(formatCondition(conditionAll));
         try {
             QueryBuilder builder = QueryBuilder.create(dataSource, query.toString());
+            for (Map.Entry<String, Object> variable : getConditionVariables(conditionAll).entrySet()) {
+                builder.setValue(variable.getKey(), variable.getValue());
+            }
```

Reports was throwing error, as server was null. To get it working, server should be getServer().
```
@@ -68,7 +68,7 @@ public class PermissionsService {
 
     public void checkReports(long userId) throws StorageException, SecurityException {
         if (!getUser(userId).getAdministrator()
-                && (server.getDisableReports() || getUser(userId).getDisableReports())) {
+                && (getServer().getDisableReports() || getUser(userId).getDisableReports())) {
```

Hope these helps. Looking forward to next update.

**Comment by tananaev** [comment]
Could you send those changes as pull requests please?

**Comment by tananaev** [comment]
Fixed, thank you for reporting this.

**Comment by tananaev** [comment]
Let us know if you find any more issues.
