### ISSUE TITLE
New notification automatically link to all users

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar#4853]
Issue: Newly created notifications automatically link to all users.

Ho to recreate:
1. Create new notification.
2. Select users, select any user, select notification and the new notification is linked to the user.
3. And if you uncheck the notification, they are checked again after refresh

https://user-images.githubusercontent.com/63212232/170606545-8a843ced-c35d-438b-800c-6eec6de00b04.mp4

**Comment by tananaev** [comment]
The issue should be fixed. Thanks for reporting it. Please let us know if you find any other problems.
