### ISSUE TITLE
Support in V5 for Bing Ordinance Survey maps for the UP

### ISSUE THREAD

**Issue by helfirex** [traccar/traccar#4855]
Would it be possible to implement the addition of the Bing maps for UK Ordinance survey as one that can be selected from the menu. As this is the default mapping for all of the UK used by many people.

**Comment by tananaev** [comment]
1. Wrong repository. Please move this ticket to web app repo.
2. Please provide all relevant links to the map you're referring it.
3. Did it work with the legacy app?
