### ISSUE TITLE
Implement "UI configuration/Attributes" in the new interface

### ISSUE THREAD

**Issue by glbatistabh** [traccar/traccar#4857]
At Anton's suggestion, I'm creating this ticket to request that "interface attributes" be implemented in the new web version:
```
Attributes -> UI: Disable Drivers: true / false
Attributes -> UI: Disable Calendars: true / false
Attributes -> UI: Disable Maintenance: true / false
Attributes -> UI: Disable Events: true / false
more...
```
From now on, I leave my thanks to all the developers of the project.

**Comment by glbatistabh** [comment]
Anton in the **old web interface**, there are these 7 Interface attributes (that I know of):
```
Server -> Attributes -> UI: Disable Report
Server -> Attributes -> UI: Disable Events
Server -> Attributes -> UI: Disable Vehicle Features
Server -> Attributes -> UI: Disable Drivers
Server -> Attributes -> UI: Disable Computed Attributes
Server -> Attributes -> UI: Disable Calendars
Server -> Attributes -> UI: Disable Maintenance
```

**But I only use the 4:**
```
Server -> Attributes -> UI: Disable Drivers
Server -> Attributes -> UI: Disable Calendars
Server -> Attributes -> UI: Disable Maintenance
Server -> Attributes -> UI: Disable Events
```
**My** need is just the 4 attributes listed above. But I believe that other users can use the other attributes. That's why I said "more..."

**Comment by tananaev** [comment]
Implemented here https://github.com/traccar/traccar-web/commit/b418d001a498b5a5108bb13983b4f3aba6c60dbc.

P.S. please use `traccar-web` repo for web app related issues.
