### ISSUE TITLE
Ctrl+F5 generate "404 Not Found"

### ISSUE THREAD

**Issue by glbatistabh** [traccar/traccar#4858]
Access any installation of **traccar v5.0**, such as the server `https://demo4.traccar.org/modern/login` and press **Ctrl+F5** to reload the page. It will generate the error `404 - Not Found`

The same goes for the `https://demo4.traccar.org/modern/reports/route` route. When reloading the page, the error `404 - Not Found` appears.

**Step 1:** page `https://demo4.traccar.org/modern/login`
<img src="https://user-images.githubusercontent.com/8257020/171084565-943e2814-a883-4994-904b-e7ed854092cc.png" width="50%">

**Step2:** Ctrl+F5
<img src="https://user-images.githubusercontent.com/8257020/171084699-0b57f982-c404-4ff0-b756-452fb71a40cb.png" width="50%">

**Comment by chroniclesofdave** [comment]
I am having a similar issue. posted is the youtube link to show what is happening. [https://www.youtube.com/watch?v=K27loCRcbNE](url)

**Comment by tananaev** [comment]
That's expected for now. You need to start with root. There's a plan to fix it.

**Comment by tananaev** [comment]
Fixed in https://github.com/traccar/traccar/commit/3b5c04b4ddf71223371815575fa1b652fea1d5da.

**Comment by pdvro** [comment]
still an issue with 5.2

**Comment by tananaev** [comment]
Do you have a link?

**Comment by pdvro** [comment]
> Do you have a link?

http://track.gpsromania.ro/

**Comment by tananaev** [comment]
It says you're using version 5.0. Can you explain it?

**Comment by pdvro** [comment]
Clean install, onle traccar.xml moved over

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tananaev** [comment]
It means you installed the wrong version. What you have there is not 5.2.

**Comment by pdvro** [comment]
hmm, seems ok now, just reinstalled, thanks for pointing it out
