### ISSUE TITLE
Device Info Popup empty page (error message)

### ISSUE THREAD

**Issue by Spitzbua** [traccar/traccar#4859]
A Klick on the Info Button on the Device Overlay shows more information about the device. 

**To Reproduce**
1. Connect a TK915
2. Click on Device Info Button
3. See error
4.
```
react-dom.production.min.js:216 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BradioType%2C%20considerIp%2C%20cellTowers%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _o (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Ia (react-dom.production.min.js:176:171)
    at Us (react-dom.production.min.js:268:385)
    at Ol (react-dom.production.min.js:250:347)
    at xl (react-dom.production.min.js:250:278)
    at _l (react-dom.production.min.js:250:138)
    at pl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
```
**Expected behavior**
A dialog with infos open instead of empty page.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version Current

**Additional context**

**Comment by tananaev** [comment]
I believe it's already fixed here: https://github.com/traccar/traccar-web/commit/b1f3e7d1753e0c0bc04372ccd1f34ce21277f658.

**Comment by Spitzbua** [comment]
Thank you for the quick reply. Is there a way to support this project?
Another question: I am looking for a small gps tracker with battery fully compatible with traccar using 12volt. Mainly use in motorcycles.
Thank you!

**Comment by tananaev** [comment]
There are many ways to support the project. You can [contribute](https://www.traccar.org/contribute/) in many ways.

As for the device question, I would recommend asking on [the forum](https://www.traccar.org/forums/forum/devices/).
