### ISSUE TITLE
Cannot Check Computed Attribute for testing - Latest Master

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar#4863]
**Describe the bug**
Getting error "Invalid parameters or constraints violation" when testing a computed attribute. 

**To Reproduce**
1. Go to 'settings', 'computed attributes'.
2.  Create new attribute OR select one of your existing attributes.
3. Click on 'Check Computed Attribute'
4. Select a device from the dropdown. (Preferably one that is currently active and recently responded.)
5. See error

![Screenshot 2022-06-08 092054](https://user-images.githubusercontent.com/63212232/172499145-dac02967-75ab-477b-adbf-b5df463e12f8.png)

**Comment by tananaev** [comment]
Does your device have a position? Is it online?

**Comment by joystickjockey** [comment]
Yes it is Online and the computed attribute I am testing is the Battery Level, which is actually showing in state panel.
![Screenshot 2022-06-08 110212](https://user-images.githubusercontent.com/63212232/172509209-8e6e8b61-17c6-4036-95f5-a14ea3cb0c86.png)

**Comment by tananaev** [comment]
This should fix the problem. Thanks for reporting it.
