### ISSUE TITLE
Feature Request: Weather Radar Map Overlay

### ISSUE THREAD

**Issue by dsimmons1977** [traccar/traccar#4865]
It would be great to have a radar overlay for the map. Especially for those of us who offshore fish so our land based support systems can get a better idea of where we are in relation to storms moving in.

The request it to have the ability to overlay a live weather radar map (accuweather, weather underground... etc) on top of the Traccar map so we can see LIVE weather data radar in relation to our Traccar client locations.

**Comment by dsimmons1977** [comment]
*Updated*

**Comment by tananaev** [comment]
Is there a free weather map out there? API links?

**Comment by tananaev** [comment]
Implemented in https://github.com/traccar/traccar-web/commit/3eb1bb2e3f3d43cda2efe92754be4285dac6dbfd.

**Comment by dsimmons1977** [comment]
This is awesome!  Thank you so much for taking this into consideration and implementing it!
