### ISSUE TITLE
Configurar y personalizacion de notificaciones en gmail

### ISSUE THREAD

**Issue by eduarflx** [traccar/traccar#4867]
cordial saludo a todos, en este espacio deseo consultar como podria realizar la personalizacion a la notificacion via gmail.

Tengo actualmente funcionando en mi version 5.0 la notificacion de gmail funcionan muy bien pero estan en idioma ingles deseo cambiar el idioma cuando lleguen a los correos configurados.

ademas cuento  configurado en el archivo traccar,xml el envio de la ubicacion en la notificacion de gmail por url de la siguiente manera.
<entry key='web.url'>https://gps.controltaken.com/</entry>

cabe destacar que cada vez que van a realizar una consulta deben logear lo que entorpeze un poco la consulta.

Mi pregunta principal es  que parametro debo establecer para que en vez de enviarme la ubicacion por url cada vez que me notifique en gmail seria mejor que me la envie por coordenadas asi que cuando el gmail las reciba lo redirija al google maps.

la segunda pregunta concreta es desde donde puedo configurar para que las notificacion que me envie traccar al gmail lleguen en idiama español y no en ingles como biene por defecto..

quedo atento a su colaboracion compartiendo su valioso conocimiento.

y tengo la version 5.0 me funciona de maravilla lo unico es que he intentado incorporar el mapa de google maps pero no me deja pero aun asi e encanta la interfax =)

**Comment by tananaev** [comment]
Please use the forum for questions.

Also, I would recommend asking in English.
