### ISSUE TITLE
Отображение иконок на картах.

### ISSUE THREAD

**Issue by sem1300000000** [traccar/traccar#4868]
Установил сервер 5.0
На карте в новом интерфейсе нет иконок автомобиля. Точнее они есть только на карте LocationIQ.

**Comment by tananaev** [comment]
Скриншоты? Вы посмотрели ошибки в консоле?

**Comment by tananaev** [comment]
В следующий раз проблемы с веб пожалуйста сюда:

https://github.com/traccar/traccar-web/
