### ISSUE TITLE
Custom Map on latest master throw error - Modern App

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar#4869]
How to recreate:
1. Settings, server, Custom map and paste url copied from Documentation Map Layers.
2. Make sure sanitation is disabled with <entry key='web.sanitize'>false</entry> 
3. Select Preferences, Map, Active Maps and select Custom (XYZ)
4. Open modern app and select map styles, custom.

Screen go all white and error below appear in web dev console

![error](https://user-images.githubusercontent.com/63212232/174554060-f029b2ee-5bb4-435a-8ca8-b3c40ba4c05d.png)

**Comment by tananaev** [comment]
Fixed in https://github.com/traccar/traccar-web/commit/8d56a292a5df90c00699f01e9188d7185a9b18af. Please next time submit UI issues to the right repository:

https://github.com/traccar/traccar-web/issues
