### ISSUE TITLE
Modern UI - Computed attributes - New name not possible

### ISSUE THREAD

**Issue by BenjaminK87** [traccar/traccar#4870]
I wanted to add a new computed attribute in the Modern UI. But it is only possible to select already existing ones and not just type a new name in the field.
In the classic UI it works.

Using Chrome Browser and v5.0/traccar-linux-64-5.0

**Comment by tananaev** [comment]
Fixed in https://github.com/traccar/traccar-web/commit/c591835bd91d5ae0c93471a246fa92d7c327464d.

Please submit UI-related tickets to the `traccar-web` repository instead.
