### ISSUE TITLE
Reports diagram - leading values hidden on the y axis

### ISSUE THREAD

**Issue by Spitzbua** [traccar/traccar#4873]
**Describe the bug**
The values on the y axis (speed diagram) are cut off and the values are not readable. 

**To Reproduce**
1. Go to Reports diagram
2. Click on device, and speed and show
3. Values are cut off on the y axis

**Expected behavior**
The values on the y axis are readable und fully shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/18468473/175047006-b528a729-bcb5-4962-9b5f-d780ced0a5fe.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 102

**Smartphone (please complete the following information):**
 - Device: HUAWEI P30PRO
 - OS: Android 11
 - Browser Chrome

**Comment by tananaev** [comment]
Are you using master branch?

**Comment by Spitzbua** [comment]
No, iam using 5.0 from the official releases.

**Comment by tananaev** [comment]
I believe it's already fixed on master.
