### ISSUE TITLE
We are unable to create alarm . Is it possible to use this alarm from mobile device ?

### ISSUE THREAD

**Issue by Narendraweb3** [traccar/traccar#4876]
We are unable create alarm .
We have configured Traccar v5.0 server in a window server and try to create alarm for a mobile device where we have insttaled traccar client but its not working .
Any thing needs to be done in order to configure this feature ? 
Please suggest your opinion .

**Comment by tananaev** [comment]
GitHub is only for bugs, feature requests and development related discussions. Use the forum for questions.
