### ISSUE TITLE
What is the best way to integrate with traccar, direct database access or traccar API?

### ISSUE THREAD

**Issue by K1DV5** [traccar/traccar#4883]
Hi, and thank you for the awesome project. I'm starting to integrate traccar into my project and right now I'm using the API to get realtime location updates and manage devices. And now I'm wondering if some tasks are better managed using a direct database connection. Is it discouraged to directly connect to the database behind traccar?

**Comment by tananaev** [comment]
API is definitely better. For questions please use the forum instead.

**Comment by K1DV5** [comment]
Thank you Anton. Right, forum it is.
