### ISSUE TITLE
java.net.ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by masterwishx** [traccar/traccar#4885]
Using lasted version in docker in Unraid (Linux x64)
Using MariaDB docker from LinuxServer MySQL: 5.5.5-10.5.16-MariaDB-log с PHP-расширением MySQLi

some time ago i changed all my database to utf8mb4_unicode_ci also traccar , maybe it causee the problem ?
having some errors on database conection in log :

![image](https://user-images.githubusercontent.com/28630321/177798099-b5cfc966-f988-4133-bca0-88beababd9ea.png)

![image](https://user-images.githubusercontent.com/28630321/177798212-7d2f4333-1fdb-4102-a107-7efd4665fffa.png)

**Comment by tananaev** [comment]
The database is not accessible from the server. Please remember that GitHub is for bugs and feature requests only. Everything else should go to the forum instead.
