### ISSUE TITLE
add email display name in mail.smtp.from

### ISSUE THREAD

**Issue by OperationOne** [traccar/traccar#4887]
**Is your feature request related to a problem? Please describe.**
all email notifications are named with bare mail address, is impossible to insert a "from" description name, cfr. https://www.traccar.org/forums/topic/email-display-name/#post-72839

**Describe the solution you'd like**
something like this in traccar.xml (that unfortunately isn't working at the moment): 
<entry key='mail.smtp.from'>Lorems Traccar &lt;mytraccaremail@gmail.com&gt;</entry>

**Describe alternatives you've considered**
none AFAIK

**Additional context**
naming clearly a notification mail is a nice and polite option. thanks!

**Comment by tananaev** [comment]
Add support for name as a separate parameter:
```xml
...
<entry key='mail.smtp.fromName'>Traccar</entry>
<entry key='mail.smtp.from'>notification@traccar.org</entry>
...
```
