### ISSUE TITLE
localhost:8082 and publicip:8082 showing online but www showing offline

### ISSUE THREAD

**Issue by abhinay2022** [traccar/traccar#4891]
Hi,
I make my local machine as server and binding with DNS, when I open localhost:8082 or publicip:8082 device showing online 0 min ago, but when I open on www showing offline 0 min ago

Server OS : windows 10 64bit

Please response if credentials is required.
![Screenshot_2022-07-12-21-42-59-35_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/77523385/178542112-118070bf-b9df-4519-bb6c-3745fc2b77cd.jpg)
![Screenshot_2022-07-12-21-43-22-54_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/77523385/178542140-f33764c6-f322-452e-b262-fe4fad6ad133.jpg)

**Comment by mrlorenz28** [comment]
I have the same problem when I migrate from version 5.0 to 5.1

**Comment by tananaev** [comment]
The issue should be fixed now. You can download an updated version from here:

https://www.traccar.org/preview/

**Comment by abhinay2022** [comment]
Now it's working as expected thanks @tananaev
