### ISSUE TITLE
Error when adding devices to new group

### ISSUE THREAD

**Issue by joystickjockey** [traccar/traccar#4896]
Only affects devices that were added using database.registerUnknown.
Getting error as per below when attempting to add the device to a newly created group. Also get a 400 (Bad Request) error in web dev. EditView.js:60

**To Reproduce**
1. Use latest master
2. Create new database for testing
3. Enable database.registerUnknown in traccar.xml
4. Start server and wait for a few devices to be added
5. Create new group
6. Add one of the newly created devices to the group
7. Select save and see error

![error](https://user-images.githubusercontent.com/63212232/179097284-cb025d7f-5d08-4823-be6c-2f65ba2db37c.png)

**Comment by tananaev** [comment]
It should already be fixed - https://github.com/traccar/traccar/issues/4890#issuecomment-1182795524.

**Comment by tananaev** [comment]
Please try the fix.
