### ISSUE TITLE
Notification behaviour changed from previous release

### ISSUE THREAD

**Issue by imzenreally** [traccar/traccar#4898]
since the latest docker container update i've noticed that if i have the webclient open - wheni first open it all my devices will show offline until they send their next ping to the main server - then if i can the webclient open i get notified via pushover that the device is online even though the device was already online - this is a change in behaviour from the last release - where when you logged into the webclient the server tracked the status and the webclient would just show that (i'm assuming i don't java)

perhaps this is by design and perhaps i'm not doing the best job explaining - happy to provide more data

**Comment by tananaev** [comment]
It's a known issue that's already fixed (https://github.com/traccar/traccar/issues/4891).
