### ISSUE TITLE
A Meitrack protocol error

### ISSUE THREAD

**Issue by gitalgps** [traccar/traccar#4899]
Meitrack protocol

The current battery and power values are 100 times higher than the actual values.
Actual values：4.06V and 14.07V
![error](https://user-images.githubusercontent.com/53261223/179773485-376dd509-ef30-47d8-9e88-58f1a8c26e16.jpg)
hex code:
2424463136302c3836313431323034333032373936352c4141412c32322c34352e3439393435382c2d38322e3439333538312c3232303731383137313432382c562c302c302c302c302c302e302c302c3232373934302c3131393831322c3330327c3232307c443844367c30383645314232422c303030302c303030307c303030307c303030307c303139317c303537332c2c2c332c2c3030323133342c302c302a4641
[MEITRACK_T366 & T366G & T1 & T333_GPRS_Protocol_V1.2--20180817.pdf](https://github.com/traccar/traccar/files/9141905/MEITRACK_T366.T366G.T1.T333_GPRS_Protocol_V1.2--20180817.pdf)

If in the V4 version, it looks more confusing.

![ERROR](https://user-images.githubusercontent.com/53261223/179813462-8043edb8-391c-4ae3-80e5-5d8baaeea678.jpg)

**Comment by Itheras** [comment]
Do you mean you would like to see the decimal point? I feel that's more accurate is not higher there is just no decimal point.

**Comment by gitalgps** [comment]
Yes, it looks like it is because there is no decimal point.


> Do you mean you would like to see the decimal point? I feel that's more accurate is not higher there is just no decimal point.

**Comment by tananaev** [comment]
For it to decode correctly you actually need to specify the model.
