### ISSUE TITLE
No temperature data in the reports

### ISSUE THREAD

**Issue by gitalgps** [traccar/traccar#4900]
Protocol:meitrack
The device provides temperature data(temp0=25.7), but there is no temperature data in the reports

![error](https://user-images.githubusercontent.com/53261223/179775832-7d72270a-c68a-4b6d-8f1c-36196c76cae4.jpg)

![error2](https://user-images.githubusercontent.com/53261223/179776779-a05ba8e4-dfff-48d9-9efc-ba8b3ad7c83f.jpg)

**Comment by tananaev** [comment]
That's a limitation of the web app.
