### ISSUE TITLE
Traccar 5.2 and KML files as POI layer in Modern interface

### ISSUE THREAD

**Issue by KlaasM58** [traccar/traccar#4902]
**Describe the bug**

Installed traccar 5.2 on a test Windows 2019 server.
I noticed a difference in how Traccar displays a KML file in Modern and Legacy interface.
In Modern interface only dots are showing (i think the coordinates as they are in the KML file).
Where lines are displayed in Legacy Interface.
Also Placemarks are not showing in Modern Interface, their names are showing

**To Reproduce**
Switch between Modern and Legacy interface

**Expected behavior**

1. A Track as in a KML (converted from GPX file) shows the complete route, not only the dots of the coordinates.
2. Display Placemarks

**Screenshots**

Legacy Interface:
![image](https://user-images.githubusercontent.com/94906544/180086232-ed5f721a-d9b6-4d53-a09f-abcccee07700.png)

Modern Interface:
![image](https://user-images.githubusercontent.com/94906544/180086377-e9364e3f-f064-4319-85c1-fe174e14c187.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 103.0.5060.134 (Officiële build) (64-bits)

- OS: Ubuntu
 - Browser Firefox
 - Version 102.0 (64-bit)

**Additional context**
Since we heavily depend on those lines and Placemarks (Waypoints) showing (routes bicycle races) Modern interface is unusable for us.

Example file:
[2022-09-03_Trynwalden.zip](https://github.com/traccar/traccar/files/9154689/2022-09-03_Trynwalden.zip)

**Comment by tananaev** [comment]
This fixes the issue:

https://github.com/traccar/traccar-web/commit/d9c66515419cfe4df11a5b57dd587e48f2a91f1a

Next time please create UI-related tickets in the web app repo.
