### ISSUE TITLE
Existing device shows up as unknown device in Log (Traccar v5.2)

### ISSUE THREAD

**Issue by swaydevs** [traccar/traccar#4911]
Hello,

Traccar version: 5.2

Problem 1: Added 7 devices via API, 6 registered successfully and received data. However, 1 of the device when data was received on the server it showed up as an unknown device in the log

- Resolved by restarting Traccar

Traccar is deployed with 2 servers,  1 for DB (MySQL) and another for Traccar.

Not sure if it may have anything to do with the communication between MySQL server and Traccar?

I am unable to recreate the scenario or find a specific point of failure when this happens. so any guidance on this will be helpful

**Comment by tananaev** [comment]
Was the device sending data before you registered it?

**Comment by swaydevs** [comment]
Yes, The device was active and sending data before I registered it on Traccar.

**Comment by tananaev** [comment]
That would explain it. We have throttling to avoid querying the database too much.
