### ISSUE TITLE
Ignition on off doesn't show realtime in traccar 5.3

### ISSUE THREAD

**Issue by Rkhdaa** [traccar/traccar#4922]
Hi
How are you anton. I found an issue in traccar 5.3.
when i turn ignition on then traccar web show ignition on in seconds, but after 10 seconds, turn ignition off then it doesn't show ignition off in seconds. it show ignition off after 2 minutes.

i have also test this in traccar 4.15. ignition on off show in realtime in seconds.
Note: we use same device (Sinotrack ST901) & same sim card for both testing.

Please check it yourself & fix this bug in next release.
Thanks for your great project.

**Comment by Rkhdaa** [comment]
No this is not a network issue. Because in same time i test two servers 4.15 & 5.3
4.15 show ignition on off in seconds. But 5.3 show it after two minutes.
Please take a gps device and turn ignition on off in traccar 5.3
Then you see the results!
Thank you

**Comment by tananaev** [comment]
Just tested. No delays, so I'm not able to reproduce it.
