### ISSUE TITLE
Token Not Found

### ISSUE THREAD

**Issue by bernamaxim** [traccar/traccar#4924]
I'm using Traccar version 5.3.
It not showing token at Account menu in Permission tab.

Screenshot:
<img width="320" alt="Screen Shot 2022-08-20 at 12 21 59 PM" src="https://user-images.githubusercontent.com/2969479/185730396-6ca78941-8988-4e25-aeb7-0f4c6f2e4051.png">

**Comment by tananaev** [comment]
Token is now generated using a separate API and it's not stored with the user. Check the modern app preferences.
