### ISSUE TITLE
new version gt02a ( gt02a-v03 181010)  have different data style

### ISSUE THREAD

**Issue by 0neday** [traccar/traccar#4925]
log is here 
```
2022-08-20 10:44:47  INFO: [Td289cc5c: tk103 < 0] 283032373034363433343835384250303033353532323730343634333438353848534f31393929
2022-08-20 10:44:47  INFO: [Td289cc5c: tk103 > 0] 283032373034363433343835384150303148534f29

```
hex to text is here

```
(027046434858BZ00,{460,0,20xx,58xxxx}
{460,0,20xx,54xxx}
{460,0,2xxxx,19xxx}
,01000000)
```

I use `027046434858` as uniqe identifier, and test all port depend this https://www.traccar.org/clones/, and no lucky

I use latest tarcar server.

**Comment by tananaev** [comment]
It's not supported yet. If you're interested in sponsoring the implementation, send us an email.

**Comment by 0neday** [comment]
thank you for reply. maybe this device is fake product. I have throw it into  trash
