### ISSUE TITLE
Cannot get unit from admin user using API

### ISSUE THREAD

**Issue by bernamaxim** [traccar/traccar#4928]
Hi Anton,

I'm using version 5.3.

I've read from traccar api-reference, said that : "Can only be used by admins or managers to fetch all entities"

Case example:

<img width="1275" alt="Screen Shot 2022-08-22 at 1 24 39 PM" src="https://user-images.githubusercontent.com/2969479/185854076-18501cc0-fc70-4fca-80dd-b7b70ac2197f.png">

If I checklist device 353701094726243 and it shows on device list, than I can fetch the information of that device:

<img width="1066" alt="Screen Shot 2022-08-22 at 1 25 08 PM" src="https://user-images.githubusercontent.com/2969479/185854445-48aa8809-9227-4170-96af-85713374c80d.png">

But it will not show on response if I fetch other device:
<img width="1062" alt="Screen Shot 2022-08-22 at 1 25 36 PM" src="https://user-images.githubusercontent.com/2969479/185854559-8c4dd92e-53f2-44aa-a2bb-2ecf852a6bd9.png">

I have used version 3.x before and it can fetch all unit which registered on tc_devices.

**Comment by tananaev** [comment]
Are you an admin and you're sure that device exists?

**Comment by bernamaxim** [comment]
Yes I using basic authentication with admin authorization (screenshoot attached).
I'm sure that device exist.

**Comment by tananaev** [comment]
Looks like we changed the logic a little bit. Now you cannot request individual devices, unless they are linked to your account.
