### ISSUE TITLE
Rendering of larger charts slow, browser reports crash

### ISSUE THREAD

**Issue by Akretsch** [traccar/traccar#4931]
**Describe the bug**
The rendering of charts over longer periods needs too much time. The old GUI did it in a more proper way.

**To Reproduce**
1. Select Reports->Chart
2. Select a valid device and Chart Type = Speed
3. Select Period = Previous Month
4. Press "Show"
5. Firefox complains "This page slows down Firefox ...", later "Gah. Your tab just crashed. ...", Similar behaviour with chromium.

**Expected behavior**
Restore the speed and responsiveness of the former GUI.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux LMDE 5 Elsie on x86_64
 - Browser: Firefox 
 - Version104.0 (64 bit)

**Smartphone (please complete the following information):**
 - n/a

**Additional context**
Traccar server  running on RaspberryPi (8GB) with Debian GNU/Linux 11 in a docker container. Image from https://github.com/traccar/traccar-docker. CPU load always below 10%.

**Comment by Akretsch** [comment]
Today I tried Chrome and Edge at Windows 10. Same problem. But while waiting for Chrome you are able to access the server with Edge (and maybe some other clients). So it seems to be a browser local (Javascript engine?) problem.

My car sends a record every 30 minutes. While moving it sends a record every minute. So I would assume 1000 data points?

**Comment by tananaev** [comment]
Instead of making assumptions can you please check the actual report please.

**Comment by Akretsch** [comment]
How do I get the exact number of data points?

**Comment by tananaev** [comment]
I very much doubt a 1000 records would cause an out of memory.

**Comment by Akretsch** [comment]
I tried an email export: 22600 records. 
But few moth ago it was working ..

**Comment by Akretsch** [comment]
One record every 115 seconds

**Comment by tananaev** [comment]
Why not just reduce the time interval for the report?

**Comment by Akretsch** [comment]
Of course I can do. But: "Everything was better before." :-)
Thanks for having a look to this issue.
