### ISSUE TITLE
Users cannot send saved commands

### ISSUE THREAD

**Issue by bielsko** [traccar/traccar#4932]
Users with assigned commands but with "Limit Commands" permission cannot send them.

1. Create "saved command" and assign it to user which does not have "admin" permission checked, also assign command to the device which belongs to that user.
2. Login to that user account and try to send saved command to device.

Command should be sent by it's impossible. The error message is: `Operation restricted - SecurityException (PermissionsService:95 < CommandResource:100 < ...)`.

The problem is from version 5.1 to 5.3.

**Comment by tananaev** [comment]
Are you saying it was possible before? Limit commands disables the commands completely, as far as I know.

**Comment by bielsko** [comment]
Yes it was possible before. Limit commands permission worked before as a lock for creating new commands for users.
