### ISSUE TITLE
add a search magnifying glass to facilitate the search of users

### ISSUE THREAD

**Issue by mirindao** [traccar/traccar#4934]
add a search magnifying glass to facilitate the search of users
agregar la cantidad de dispositivo que tiene el usuario y grupo que esta el usuario
```
name | Usuario | Group | divices |  Deshabilitado | last acces | finish


luisa guevara hurtado | guevaraluisa2011@hotmail.com | grop finagro | 7  | 22/08/2022  |  22/08/2023 | 
```

**Comment by tananaev** [comment]
We've already added it in mobile view.

**Comment by mirindao** [comment]
I'm on the latest version of traccar That option is not shown on my mobile and neither is it on desktop

**Comment by tananaev** [comment]
Latest official release? It's on master.

**Comment by mirindao** [comment]
DOWNLOAD IT HERE FOR LINUX IF THERE IS ANOTHER LINK PROVIDE IT TO DOWNLOAD IT
https://www.traccar.org/download/

**Comment by tananaev** [comment]
As I said it's on master branch and not in the official release yet. Stop writing in all caps everywhere or you will be banned here.
