### ISSUE TITLE
Add the new GT600 protocol provided by manufacturer

### ISSUE THREAD

**Issue by mirindao** [traccar/traccar#4935]
[Copia de GL600 GPS Smart Lock User GuideV2 3-Mobicom Telematics.pdf](https://github.com/traccar/traccar/files/9483020/Copia.de.GL600.GPS.Smart.Lock.User.GuideV2.3-Mobicom.Telematics.pdf)
[Copia de GL600 Protocol Manual  V2.5.pdf](https://github.com/traccar/traccar/files/9483021/Copia.de.GL600.Protocol.Manual.V2.5.pdf)
[Copia de GL600 Specification.pdf](https://github.com/traccar/traccar/files/9483022/Copia.de.GL600.Specification.pdf)
[G108 User GuideV1.3-Mobicom Telematics.pdf](https://github.com/traccar/traccar/files/9483023/G108.User.GuideV1.3-Mobicom.Telematics.pdf)

**Comment by tananaev** [comment]
Closing as description is missing.

**Comment by mirindao** [comment]
![gl600](https://user-images.githubusercontent.com/109631800/188537487-5e684299-c3f6-43ac-9a43-674ce6eed1c4.png)

**Comment by mirindao** [comment]
In a previous conversation, the padlock and the manual that is up only reports to port 5013
only in that port does it appear on the map but in the middle of the sea it does not mark a route or anything

**Comment by mirindao** [comment]
that's why I enclose the communication protocol that the manufacturer gave me
