### ISSUE TITLE
temporary access for clients

### ISSUE THREAD

**Issue by mirindao** [traccar/traccar#4936]
an idea for future launches the client wants to see his cargo so a link can be sent to his email and he can monitor the vehicle that carries his cargo for a while
![temp2](https://user-images.githubusercontent.com/109631800/188283605-a9442a30-0553-4957-a775-21088bf71f22.png)
![temporal](https://user-images.githubusercontent.com/109631800/188283607-6eebdbf8-b54d-4696-bf74-6178d99515a1.png)

**Comment by tananaev** [comment]
Closing as duplicate #3789.
