### ISSUE TITLE
Average speed in daily summary seems wrong

### ISSUE THREAD

**Issue by x821938** [traccar/traccar#4937]
**The bug**
In "Report->Summary->Daily Summary" the Average speed for each day is very low - often 0 km/h. 
This happen even if there is a lot of movement all day long. 

If I go to the trip report for a specific day, then the average speed seems reported ok.

**Screen dumps**
![Daily summary](https://cloud.screenpresso.com/wrJad/2022-09-03_09h30_08.png)

![Trip summary](https://cloud.screenpresso.com/Pjbug/2022-09-03_16h37_18.png)

**Version**
Traccar 5.3

**SQL DUMP**
The dumped data can be downloaded here: [traccar_dump_2022_08_31.sql](https://drive.google.com/file/d/1gyP3PPXCvdY5YV2h8pBC9xe01VRm85Mt/view?usp=sharing)

**Comment by tananaev** [comment]
You have reducing engine hours, which results in negative value, so average speed is not calculated. That's why you have zero.

**Comment by x821938** [comment]
How is that reduced?
Is that a setting in traccar or in my device?

**Comment by tananaev** [comment]
It can either be reported by the device or it can be calculated on the server based on ignition.

**Comment by x821938** [comment]
Thanks. I will look into it :)
