### ISSUE TITLE
configure legacy web interface

### ISSUE THREAD

**Issue by fmelin** [traccar/traccar#4940]
Hello good day, I am trying to configure the legacy version of the web interface,
But I can't find what the configuration key is, I checked it in the following link but I didn't find it

[Configuration File - Traccar](https://www.traccar.org/configuration-file/)

Although in the changelog of version  [5.3 Traccar](https://www.traccar.org/blog/traccar-5-3/) in point one it says that, if the change can be made, try to do it by making the following modification.

from
`<entry key='web.path'>./modern</entry>`
to
`<entry key='web.path'>./web</entry>`

But it throws me the following error.
Failed to fetch

Please help me with the configuration.
regards

**Comment by tananaev** [comment]
You should use the forum for questions, not GitHub.

Also, you should search first for existing threads, like this one:

https://www.traccar.org/forums/topic/web-app-selection-in-traccar-53/#post-74852
