### ISSUE TITLE
Database error in logs after upgrading (postgresql, "geofenceIds")

### ISSUE THREAD

**Issue by olewales** [traccar/traccar#4945]
Hi, 
After upgrading to 5.3 i have errors in my log with every request: 

```
[...]
2022-09-12 02:13:53  INFO: [T32b36255: osmand < x.x.x.x (redacted)] 504f(...)(redacted)831
2022-09-12 02:13:53  INFO: [T32b36255: osmand > x.x.x.x] 48(...)(redacted)d0a
2022-09-12 02:13:53  INFO: [T32b36255] error - ERROR: column "geofenceids" of relation "tc_devices" does not exist
  Position: 23 - PSQLException (... < QueryBuilder:473 < DatabaseStorage:108 < GeofenceEventHandler:82 < ...)
2022-09-12 02:13:53  INFO: [T32b36255] disconnected
```

After quick investigation I think this issue was introduced in 5.2 with this part of schema changelog:

```

    <addColumn tableName="tc_devices">
      <column name="geofenceIds" type="VARCHAR(128)" />
    </addColumn>

```

Afaik this is the only column name in the entire project to use uppercase characters and this naming inconsistency exposed a bug where names in postgresql query passed without quotes are internally converted to lowercase by DB. 

Changing column name by executing 
`alter table tc_devices rename COLUMN "geofenceIds" TO geofenceids` 
on database fixes the issue

**Comment by tananaev** [comment]
Fixed here https://github.com/traccar/traccar/commit/b51526fdb177d3641e2780d5485586b487850874. Thanks for reporting.

**Comment by tananaev** [comment]
You just need to rename the database field.

**Comment by GusGiann** [comment]
Fast as light.! I will only rename the table field.

Is there a way to check across all tables for inconsistencies.? (doing a first run for creating tables and then importing data from old database didn't make the trick).

Once again Thank You personally.!
Gus
