### ISSUE TITLE
pgsql: wrong datatypes in tc_keystore

### ISSUE THREAD

**Issue by bzed** [traccar/traccar#4947]
**Describe the bug**
Traccar 5.3 create the tc_keystore table in postgresql as

```
                           Table "public.tc_keystore"
   Column   |  Type   | Collation | Nullable |             Default              
------------+---------+-----------+----------+----------------------------------
 id         | integer |           | not null | generated by default as identity
 publickey  | oid     |           | not null | 
 privatekey | oid     |           | not null | 
Indexes:
    "tc_keystore_pkey" PRIMARY KEY, btree (id)
```

oid is not a datatype that was meant to be used by other things than postgresql itself, the appropriate type would be **bytea**.

This results in

```
2022-09-13 12:57:45  WARN: Token generation failed - ERROR: column "publickey" is of type oid but expression is of type bytea
  Hint: You will need to rewrite or cast the expression.
  Position: 56 - PSQLException (... < QueryBuilder:473 < DatabaseStorage:89 < CryptoManager:97 < ...)
```

**To Reproduce**

Connect traccar to an empty postgresql database, version 13 in my case, look at the table definition.

**Expected behavior**
The table should look like
```
traccar=# \d tc_keystore
                           Table "public.tc_keystore"
   Column   |  Type   | Collation | Nullable |             Default              
------------+---------+-----------+----------+----------------------------------
 id         | integer |           | not null | generated by default as identity
 publickey  | bytea   |           | not null | 
 privatekey | bytea   |           | not null | 
Indexes:
    "tc_keystore_pkey" PRIMARY KEY, btree (id)
```

**Screenshots**

**Desktop (please complete the following information):**
 - not relevant
 
**Smartphone (please complete the following information):**
 - not relevant

**Additional context**
```
 alter table tc_keystore alter COLUMN publickey type bytea using NULL::bytea;
 alter table tc_keystore alter COLUMN privatekey type bytea using NULL::bytea;
```
seems to help for now.

**Comment by tananaev** [comment]
Yeah, looks like there was the same problem there: https://github.com/traccar/traccar/issues/3223.

**Comment by senhaesite** [comment]
Helo, I tried solving this problem altering data type to bytea, as requested by Postgres, however a new problem emerged after this when I try to generate a TOKEN in "preferences" page.

`IOException : DER input, Integer tag error - InvalidKeyException (... < CryptoManager:85 < *:50 < TokenManager:63 < SessionResource:157 < ...)`
