### ISSUE TITLE
never get alarm data (0x16) from gps gt06

### ISSUE THREAD

**Issue by jalledtarek** [traccar/traccar#4959]
hello 
i don't know why but i nerver get alarm data package (0x16 protocol number) from my gt06 gps tracker
i get only login message (0x01) , heartbeat message (0x13), data location message (0x12)
but nerver 0x16 message !!!
thank you

**Comment by tananaev** [comment]
For questions, especially the ones unrelated to the server, you should use the forum instead.

**Comment by jalledtarek** [comment]
thank you
give me the forum link please

**Comment by tananaev** [comment]
You should be able to find it on the official website.
