### ISSUE TITLE
How to enable UDP protocol in Meitrack devices ?

### ISSUE THREAD

**Issue by andromida** [traccar/traccar#496]
Hi,

Traccar software considers that Meitrack devices communicate with TCP protocols, but Meitrack devices can communicate with UDP also. How can we track Meitrack devices which communicate with UDP ?

**Comment by Jyotimobideveloper** [comment]
Script to read message tcp, udp and store them in a database. messages are sent by GPS tracker with documented protocols.

**Comment by Jyotimobideveloper** [comment]
I want to discuss more regarding this so anybody here who know more about this please guide me

**Comment by tananaev** [comment]
@Jyotimobideveloper, please don't comment on old closed issues.

As for the question, Traccar already does exactly what you are asking for. It receives data from devices and store it in the database.

**Comment by Jyotimobideveloper** [comment]
Yes sure, Thanks for information i will remember
