### ISSUE TITLE
Get property error - No serializer found

### ISSUE THREAD

**Issue by tl-vt** [traccar/traccar#4961]
**Describe the bug**
When creating or updating geofence through APIs, the bellow error is being logged into the server logs:
```
WARN: Get property error - No serializer found for class org.traccar.geofence.GeofenceCircle and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) - InvalidDefinitionException (... < QueryBuilder:310 < DatabaseStorage:104 < BaseObjectResource:98 < ...)
```

**To Reproduce**
1. Create a geofence through API.
2. Check logs.

Probably it is same to #2941, but since alot has been changed, I see this error again in v5.3 and v5.4.

**Comment by tl-vt** [comment]
> 1. Just to confirm, you've tried the official 5.4 release without any customization to the code?

Yes.

> 2. Please provide the API request that causes this.

`PUT http://server-url/api/geofences/36`
```
Request Body
    {
        "id": 36,
        "attributes": {
            "enabled": "true"
        },
        "calendarId": 0,
        "name": "geofence 1",
        "description": "this is description ",
        "area": "CIRCLE (50.239693446903274 3.784217166687739, 100.0)"
    }
```
> 3. Does the web app work for creating the geofence? What's the difference with your call?

Both in web app and API calls it works to create or update geofence, but at the same time of creation/updating, this error is also being logged.

**Comment by tananaev** [comment]
Should be fixed now. Please check if you can.

**Comment by tl-vt** [comment]
I checked and it is fixed now.

Thanks for the hard work.
