### ISSUE TITLE
Server don't work

### ISSUE THREAD

**Issue by Fabianroma91** [traccar/traccar#4963]
Hola, en este momento no permite cargar la página de mi servidor.
El error es el siguiente: ERR_CONNECTION_REFUSED
url server: http://116.203.196.181/
OS: WINDOWS 10
Browser: Chrome Versión 106.0.5249.119
![image](https://user-images.githubusercontent.com/116095381/196467814-40c6a2db-e7fd-4b6b-a8d0-9a06845cbd1c.png)

Estaba funcionando sin problema y de repente dejó de funcionar.

Gracias.

**Comment by tananaev** [comment]
If it's about a subscription, you should contact support@traccar.org.
