### ISSUE TITLE
Time override option at device level

### ISSUE THREAD

**Issue by muchahagrande** [traccar/traccar#4965]
**Is your feature request related to a problem? Please describe.**

I have a problem with a Samsung S5 Neo that reports a FIXTIME with the year set in 2003. The other smart phones works right as expected.
I tested time.override=serverTime option on osmand protocol, but in that case it overrides the DEVICE TIME on all smart phones because the override happens at protocol level. 

**Describe the solution you'd like**
I'd like to have time.override option at device level implemented as a string attribute of the device.
So I can have some osmand devices with DEVICE TIME and others with SERVER TIME just adding the "time override" attribute of string type and assigning deviceTime or serverTime.

**Describe alternatives you've considered**
An alternative is to add an attribute of boolean type ("Use server time") that sets SERVER TIME when it's checked.
So the device use its own time when the option it unchecked and the SERVER TIME when is set.

**Additional context**

![Captura de pantalla de 2022-10-21 00-41-26](https://user-images.githubusercontent.com/20299175/197106710-ce8056b5-ed71-49d2-a501-127dffe72831.png)
![Captura de pantalla de 2022-10-21 00-41-58](https://user-images.githubusercontent.com/20299175/197106714-1a06d6b8-d252-428f-a2a0-9b71ebe30407.png)

**Comment by tananaev** [comment]
Is it the GPS week rollover issue?

**Comment by muchahagrande** [comment]
Hi @tananaev, it probably is. This was reported in the forum some days ago, but in that case it was with an older smart phone: https://www.traccar.org/forums/topic/getting-wrong-time-and-date-information-from-client-running-on-android-4-jelly-bean-samsung-s3-mini-transferred-to-server/

As a workaround I set time.override=serverTime for osmand protocol. But this will override every device that use the same protocol, including the ones that doesn't have the GPS issue

**Comment by tananaev** [comment]
Decided to fix this on the Client side - https://github.com/traccar/traccar-client-android/commit/a2b2c215da2bc411af3dedf1e909008a30fb17f3.

**Comment by muchahagrande** [comment]
Excelent, and thank you for this great work...
