### ISSUE TITLE
Teltonika TFT100 CAN Data

### ISSUE THREAD

**Issue by kenanilgun** [traccar/traccar#4971]
Hi everyone,

I'm using TFT100 devices on my cars, but I dont manage below CAN data, io900 between io907 need see exactly raw value, is it possible?

Also io839, io840 value not have list on computed attribute match, when I'm using custom attribute and description not matching positions attributes.

![image](https://user-images.githubusercontent.com/3466008/198386003-a227b3d8-f107-4461-8623-cebb39284a64.png)

KR.

**Comment by tananaev** [comment]
You already have the raw data. And if something is not listed, it probably means your device doesn't report it.

For questions please use the forum instead.
