### ISSUE TITLE
Teltonika Manual Can Mask

### ISSUE THREAD

**Issue by kenanilgun** [traccar/traccar#4973]
Hi everyone,

I'm using Teltonika manual mask properties. Do it have some configuraion/feature or options for work with it? 

Thank you.

**Comment by tananaev** [comment]
Please use the forum for questions.

**Comment by kenanilgun** [comment]
Hi Anton,

Actually it's not qeustions. It's conversation about feature. What about you think?

**Comment by tananaev** [comment]
Discussions should be on the forum as well. GitHub is only for feature requests (finalized) or bug reports.
