### ISSUE TITLE
Bugs in Stop and Trip report in version 5.4

### ISSUE THREAD

**Issue by mmft1359** [traccar/traccar#4977]
I receive error with status code 503 when call Stop and Trip report in version 5.4.
please check that.

**Comment by tananaev** [comment]
You have to provide more details, like full error message, steps to reproduce etc.

**Comment by mmft1359** [comment]
![Screenshot_20221103_063059](https://user-images.githubusercontent.com/24897467/199640072-1852dd48-e98e-4335-8f18-1e475df0896a.png)
