### ISSUE TITLE
Marker on route.

### ISSUE THREAD

**Issue by mauroreggio** [traccar/traccar#4981]
Hi all and thanks for the project.
I install Traccar for the first time and i try some test. I'm an old OpenGTS user.
The version that i install is the one for linux, following the simple instruction page (https://www.traccar.org/linux/).
Today i'm able to track the entire route on map, with Traccar Android Client, in offline mode (i discover that only HIGH precision position is necessary on the client setup for use satellite postioning), and it work.
A feature that miss me very much, unlike it exist on OpenGTS, is the possibility to have on the map of the track many marker, one per 5 minutes, where i can point the mouse and i can see time and other data (but time is sufficient) of when i'm axactly in that coordinates, directly on the period track map.
There is a way to add a marker every 5 minutes on the track route in Traccar and maybe have the possibility to interact with it?
I talk about a report on the map, where is marked the route of the selected period and various point of the route. A static report, not like REPLAY, but with point of the route marked. Something like the image in this page (sorry if i add a link to other product) http://www.opengts.org/TrackMap.jpeg
In this map, if i put the mouse on every red point, it say me the time when i'm there.
This is only an example for explain better what i mean.
Thanks you very much.
Mauro

**Comment by tananaev** [comment]
It's already available in master. The track will have clickable points.
