### ISSUE TITLE
Device markers should have a way to set different colors depending on the state.

### ISSUE THREAD

**Issue by nyash** [traccar/traccar#4983]
Hi,

Upgraded to the latest traccar version with material design web gui.

One thing that immediatelly stands out and is a big regression is that the markers for various devices have no indication whether a device is online/active or inactive/offline which was the case for the older web gui (markers were green/yellow/red depending on the state). 

They all look the same, which means to find out the device state you need to search for it in the side panel, in the device list.

**Comment by tananaev** [comment]
What browser are you using?

**Comment by nyash** [comment]
@tananaev 
Now that the browser was mentioned: Firefox on WIN10, and all the icons are white circles with black markers. Clearing browser cache has not fixed it on firefox.

I had opened traccar now in Edge and indeed the markers are coloured so apparently this is a browser issue.
