### ISSUE TITLE
Show the Heartrate as Atrribute

### ISSUE THREAD

**Issue by Nikutrax** [traccar/traccar#4986]
it would be great to display heart rate as a separate attribute in the future.

Or an independent protocol which can also send commands to the devices for the EVIEW devices.

**Comment by tananaev** [comment]
What do you mean? You should probably provide more context.

**Comment by Nikutrax** [comment]
![Screenshot 2022-11-18 135547](https://user-images.githubusercontent.com/112165998/202710274-4671fc86-cf70-49b3-a37d-c4cfc540c9e8.jpg)

in this selection are the heartrate unvailable

**Comment by tananaev** [comment]
You can type an attribute there.

**Comment by Nikutrax** [comment]
![Screenshot 2022-11-23 112620](https://user-images.githubusercontent.com/112165998/203524088-5e9a02a2-8bd0-43e5-a336-d14b93ac9c31.jpg)
![Screenshot 2022-11-23 112701](https://user-images.githubusercontent.com/112165998/203524096-c53225b2-d665-4ee3-9c67-738f2d1651f5.jpg)

when the device upload new data i became a blank side

**Comment by tananaev** [comment]
Check browser console for errors.

**Comment by Nikutrax** [comment]
Einige Cookies verwenden das empfohlene "SameSite"-Attribut inkorrekt. 2
Das Cookie "JSESSIONID" verfügt über keinen gültigen Wert für das "SameSite"-Attribut. Bald werden Cookies ohne das "SameSite"-Attribut oder mit einem ungültigen Wert dafür als "Lax" behandelt. Dadurch wird das Cookie nicht länger an Kontexte gesendet, die zu einem Drittanbieter gehören. Falls Ihre Anwendung das Cookie in diesen Kontexten benötigt, fügen Sie bitte das Attribut "SameSite=None" zu ihm hinzu. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. [server](http://81.169.236.70/api/server)
Das Cookie "JSESSIONID" verfügt über keinen gültigen Wert für das "SameSite"-Attribut. Bald werden Cookies ohne das "SameSite"-Attribut oder mit einem ungültigen Wert dafür als "Lax" behandelt. Dadurch wird das Cookie nicht länger an Kontexte gesendet, die zu einem Drittanbieter gehören. Falls Ihre Anwendung das Cookie in diesen Kontexten benötigt, fügen Sie bitte das Attribut "SameSite=None" zu ihm hinzu. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. [server](http://81.169.236.70/api/server)
Passwort-Felder sind auf einer unsicheren (http://) Seite vorhanden. Dies ist ein Sicherheitsrisiko, durch das Zugangsdaten gestohlen werden können.
[login](http://81.169.236.70/login)
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 16
DataCloneError: SVGAnimatedString object could not be cloned. 3 [content.aos.js:26](moz-extension://3cf3ef42-f91e-40c7-8d1a-1f9ebb370ba7/common/scripts/content.aos.js)
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 16
After reporting 32, no further warnings will be reported for this WebGL context.
DataCloneError: SVGAnimatedString object could not be cloned. 2 [content.aos.js:26](moz-extension://3cf3ef42-f91e-40c7-8d1a-1f9ebb370ba7/common/scripts/content.aos.js)
TypeError: h[e] is undefined
    children http://81.169.236.70/static/js/main.08469deb.js:2
    J_ http://81.169.236.70/static/js/main.08469deb.js:2
    To http://81.169.236.70/static/js/main.08469deb.js:2
    Ml http://81.169.236.70/static/js/main.08469deb.js:2
    bc http://81.169.236.70/static/js/main.08469deb.js:2
    vc http://81.169.236.70/static/js/main.08469deb.js:2
    gc http://81.169.236.70/static/js/main.08469deb.js:2
    ic http://81.169.236.70/static/js/main.08469deb.js:2
    lc http://81.169.236.70/static/js/main.08469deb.js:2
    Hn http://81.169.236.70/static/js/main.08469deb.js:2
    ac http://81.169.236.70/static/js/main.08469deb.js:2
[main.08469deb.js:2:691948](http://81.169.236.70/static/js/main.08469deb.js)
Uncaught TypeError: h[e] is undefined
    children http://81.169.236.70/static/js/main.08469deb.js:2
    J_ http://81.169.236.70/static/js/main.08469deb.js:2
    To http://81.169.236.70/static/js/main.08469deb.js:2
    Ml http://81.169.236.70/static/js/main.08469deb.js:2
    bc http://81.169.236.70/static/js/main.08469deb.js:2
    vc http://81.169.236.70/static/js/main.08469deb.js:2
    gc http://81.169.236.70/static/js/main.08469deb.js:2
    ic http://81.169.236.70/static/js/main.08469deb.js:2
    lc http://81.169.236.70/static/js/main.08469deb.js:2
    Hn http://81.169.236.70/static/js/main.08469deb.js:2
    ac http://81.169.236.70/static/js/main.08469deb.js:2
[main.08469deb.js:2:3278589](http://81.169.236.70/static/js/main.08469deb.js)
Unbekannte Pseudoklasse oder Pseudoelement '-webkit-full-screen'.  Regelsatz wegen ungültigem Selektor ignoriert. [maplibre-gl.css:1:229](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:3233](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:3836](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:7140](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:9834](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:15358](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:18072](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:21896](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:46746](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:64264](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:67969](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:68505](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:68505](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:68505](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [maplibre-gl.css:1:68505](http://81.169.236.70/static/node_modules/maplibre-gl/dist/maplibre-gl.css)
Unbekannte Pseudoklasse oder Pseudoelement '-webkit-full-screen'.  Regelsatz wegen ungültigem Selektor ignoriert. [mapbox-gl.css:1:195](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:2152](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:2607](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:5816](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:9011](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:14570](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:18144](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:28869](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:29303](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:34058](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:35146](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:35146](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:35146](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:35146](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Name einer Medienfunktion erwartet, aber '-ms-high-contrast' gefunden. [mapbox-gl.css:1:35146](http://81.169.236.70/static/node_modules/mapbox-gl/dist/mapbox-gl.css)
Source-Map-Fehler: Error: JSON.parse: unterminated string at line 1 column 8352750 of the JSON data
Ressourcen-Adresse: http://81.169.236.70/static/js/main.08469deb.js
Source-Map-Adresse: main.08469deb.js.map

Fehler beim Verarbeiten des Wertes für 'user-select'.  Deklaration ignoriert. [81.169.236.70](http://81.169.236.70/)

​

**Comment by tananaev** [comment]
Probably some API returned an error.
