### ISSUE TITLE
All Teltonika devices - fmb920 / fm1120 - stop sending location from 23-11-2022

### ISSUE THREAD

**Issue by BIhab** [traccar/traccar#4988]
**Describe the bug**
Hi,
I hope you're fine, I think there is a problem with Teltonika Protocole issue from yesterday, none of my teltonika devices about hundreds are sending their location from yesterday, I didn't do any changes or update on our production server, all was working fine until yesterday they stop sending location, but other devices like Coban Tk103 still work like a charm.

**Comment by tananaev** [comment]
We haven't touched Teltonika decoded for more than a month. Also, even if we did, we haven't released a new version of Traccar. You should only create bug tickets on GitHub if you're absolutely sure it's a Traccar bug and have evidence.

**Comment by BIhab** [comment]
> We haven't touched Teltonika decoded for more than a month. Also, even if we did, we haven't released a new version of Traccar. You should only create bug tickets on GitHub if you're absolutely sure it's a Traccar bug and have evidence.

You're right, sorry for bodering you
