### ISSUE TITLE
Feature Request - Event report : allow to select multiple devices from listbox

### ISSUE THREAD

**Issue by dough29** [traccar/traccar#4989]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to select multiple devices from the listbox when viewing/generating event report.

**Describe the solution you'd like**
Maybe we can add checkbox next to the device or use CTRL + mouse click.

This feature is lost from the "old" UI in Traccar 4.x

Thanks.

**Comment by tananaev** [comment]
This should be in the web app repository. Also provide the use cases for it.
