### ISSUE TITLE
Feature Request - Event report : allow to sort columns

### ISSUE THREAD

**Issue by dough29** [traccar/traccar#4990]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to sort the columns from the event report screen.

**Describe the solution you'd like**
Make the columns sortable.

This feature is lost from the "old" UI in Traccar 4.x

Thanks.

**Comment by tananaev** [comment]
First of all, this should be in the web app repository. Also you should provide details why it is important, what business use cases you see for it.
