### ISSUE TITLE
Compilation Tests Error

### ISSUE THREAD

**Issue by viniciusdesa** [traccar/traccar#4991]
**Description**
When building the Server, it reports the following error:
```
D:\dev\traccar\src\test\java\org\traccar\protocol\WialonProtocolDecoderTest.java:67: error: unmappable character (0x8F) for encoding windows-1252
                "#B#080914;073235;5027.50625;N;03026.19321;E;0.700;0.000;NA;4;NA;NA;NA;;NA;Батаре�?:3:100 %|080914;073420;5027.50845;N;03026.18854;E;1.996;292.540;NA;4;NA;NA;NA;;NA;Батаре�?:3:100 %"));
                                                                                                        ^
```

**To Reproduce**
1. Clone traccar repository (master)
2. Open intellij
3. Open Gradle window (at right)
4. Expand tracker-server -> Tasks -> build
5. Double click on build

**Expected behavior**
Success on build

**Screenshots**
![image](https://user-images.githubusercontent.com/80352552/205145944-50f807cc-6cc5-4c74-ab17-923860535daf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Single Language
 - Version 22H2
 - Regional Settings: Country = Brazil | Current Format = Portuguese (Brazil)
 - Default Encoding: Windows 1252

**Additional context**
The problem is happening because there are russian characters in the string. You should remove these characters or change some option in the project to compile from UTF-8. 
If I change in Settings the Encoding to UTF-8, the following problems happen:
![image](https://user-images.githubusercontent.com/80352552/205147923-71440ddd-e6b9-4f58-8e89-3babc9df0736.png)
Then I need to change the checkstyles.xml to solve this problem:
```
<module name="NewlineAtEndOfFile">
        <property name="lineSeparator" value="crlf" />
    </module>
```
Then, the last error that will remain os on CalendarTest:
![image](https://user-images.githubusercontent.com/80352552/205148388-74e13405-233d-4906-9f9b-f64e8a6117b0.png)

To solve it, I need to comment the lines 49 and 54 of CalendarTest.java. Then, everything works!
![image](https://user-images.githubusercontent.com/80352552/205148715-50a4774e-fe51-4a1f-9e97-8a5d1d20a625.png)

@tananaev Need your help on this! Thanks!

**Comment by tananaev** [comment]
All the source code should be in UTF-8. Why is it in windows-1252 encoding? There's some issue with your setup. It's not something with the source code.

**Comment by viniciusdesa** [comment]
> All the source code should be in UTF-8. Why is it in windows-1252 encoding? There's some issue with your setup. It's not something with the source code.

@tananaev  I didn't choose "my encoding should be Windows-1252". I believe that Windows 10 in portuguese (that come with any notebook acquired in a store in Brazil) already do that automatically. When I open Settings, I get:
![image](https://user-images.githubusercontent.com/80352552/205149486-7862b9dc-0b51-4085-8880-97503932da7b.png)

Even if I change to UTF-8, the errors as I described remain (CRLF instead of LF, CalendarTest.java errors, etc.).

**Comment by tananaev** [comment]
I don't use Windows, so not sure, but I know other people do use Windows without any issues, so I'm pretty confident it's something with your setup. Maybe some issue with git configuration when you cloned the project.

**Comment by viniciusdesa** [comment]
The git configuration is the default (install git, next, next, next, end..). So do you recommend using Linux to avoid these git and intellij issues?

**Comment by tananaev** [comment]
I'm personally using Mac, but I've used Linux in the past. Again, I know a lot of people using Windows without any issues either.
