### ISSUE TITLE
GT06 Device Suddenly sending invalid packets after traccar restart

### ISSUE THREAD

**Issue by vamsisnikky** [traccar/traccar#4995]
Hello Anton,

GT06 Device Suddenly sending invalid packets after traccar restart, 
Below was the sample logs

IMEI: 358899057878764

`2022-12-08 18:37:52  INFO: [cd4bf9c3: gt06 < 223.180.224.189] HEX: 78780d0103588990578787640358f71e0d0a`
`2022-12-08 18:37:52  INFO: [cd4bf9c3: gt06 > 223.180.224.189] HEX: 7878050103583cf00d0a`
`2022-12-08 18:37:58  INFO: [cd4bf9c3] id: 358899057878764, time: 1970-01-01 05:30:00, lat: 0.00000, lon: 0.00000, course: 0.0`

Traccar Version:  `Version: 4.12`
This issue happend to multiple devices & It stopped inserting into tc_positions as invalid packet. 
but Packets were receiving to traccar with  time: 1970-01-01 05:30:00, lat: 0.00000, lon: 0.00000, course: 0.0

Device Working fine  & in GPS Green, GPRS Green, Power Green
Could you please help out what could the reason

**Comment by tananaev** [comment]
You should check the latest version first before submitting a ticket. Also before submitting make sure that it's a server issue and not a device.
