### ISSUE TITLE
Not owned geofence but receiving notifications

### ISSUE THREAD

**Issue by tl-vt** [traccar/traccar#4998]
**Describe the bug**
One device is assigned to 3 different users (e.g A, B and C). Every user has their own Geofences and they assigned the Geofences to the device and enabled email and push notifications for thierselves.

When a Geofence notification is generated for user "A", the other two users "B" and "C" are also getting this notification per email, even they didn't created this Geofence and not shared between them. The same occurs if a Geofence notification is generated for user "B" then user "A" and "C" are also getting the notification.

**To Reproduce**
1. Creat two different users
2. Share a device between them
3. Create at least one Geofence for each user
4. Assign newly created Geofence to the device
5. Enable Geofence notification for both users (Email & maybe push)

**Expected behavior**
Every user should get a Geofence Exit or Geofence Enter notification from thier own Geofence which they created for themselves.

**Comment by tananaev** [comment]
This is expected behavior. Notifications are configured per device. There is no filtering by geofence or anything else.

**Comment by tl-vt** [comment]
Okay got it.
