### ISSUE TITLE
traccar is producing OpenWeatherMap API usage alerts

### ISSUE THREAD

**Issue by magoralczyk** [traccar/traccar#4999]
I do not know, if this is a server or webclient problem but I get regularly mails from openweathermap, informing me, they blocked my free api key temporarly, "due to the continual sufficient exceeding of the calls per minute limit by performing 710 requests within a minute but the limit for the Free account is 60 rpm."
I have one webinterface running, not all the time opened in the browser, maybe a few times a day. Using the weather api would be sufficient once an hour, and 710 requests per minute is bad shit crazy.

**Comment by tananaev** [comment]
What makes you think it's crazy? Have you actually checked how many tiles you have on the screen and how many were loaded when you moved/zoomed the map?

**Comment by magoralczyk** [comment]
Well, it is your software, so decide for yourself,  but for me 710 http requests per minute seems still crazy, especially for the little benefit. Maybe it would be better to get the information only for a fixed zoom level and then scale it to prevent new api calls when zooming or panning but if you are happy with it or have bigger fish to fry, just close this one. I just found the feature cool, so I tried it out, but I have no problem using traccar without it. 
This is not on topic but has to be said: Thanks for this great, free software.

**Comment by tananaev** [comment]
I just tried it on my desktop. It load 40 tiles just for a single static screen. There are something like 20 zoom levels. So even if you don't move the map and zoom from lowest to highest level, you get 800 API requests. This is how all tile-based maps work, so it does not seem unreasonable to me that you're hitting 700+ requests occasionally if you actively use the map.
