### ISSUE TITLE
Web live route length not as defined 

### ISSUE THREAD

**Issue by anpalama1** [traccar/traccar#5001]
**Describe the bug**
Under server attributes I defined it to 5000 meters but the length is always the same max. 600m or shorter

![Screenshot_20221216_053614_Traccar Manager](https://user-images.githubusercontent.com/120574638/208024923-601ed6ce-5a83-490f-8622-3591fd7d38bd.jpg)

**Comment by tananaev** [comment]
How did you set it in meters? We don't even have such configuration.

**Comment by anpalama1** [comment]
You see it on the map scala

**Comment by tananaev** [comment]
I don't think you answered my question.

**Comment by anpalama1** [comment]
![Screenshot_20221216_064205_Traccar Manager](https://user-images.githubusercontent.com/120574638/208030420-b22e7de9-c9a7-4b5e-ab3a-bd9cfaa5f857.jpg)

**Comment by tananaev** [comment]
That's great but where do you see **meters**?

**Comment by anpalama1** [comment]
I thought that are meters. It was so in the old version or not.  It the old version it works

**Comment by tananaev** [comment]
It was never in meters. It was always a number of locations.

**Comment by anpalama1** [comment]
Whatever. But now it doesn't work

**Comment by tananaev** [comment]
Just tested and it is working for me. Looking at your screenshots, it seems like you're not using the latest version of Traccar.

**Comment by anpalama1** [comment]
I use the latest 5.5 version.  
the entry no matter which value shows me no effect

**Comment by tananaev** [comment]
What I see on screenshot tells me that you're not using version 5.5. Show a screenshot where you enabled the live routes.

**Comment by anpalama1** [comment]
You don't know your own program? It's definitely 5.5

![Screenshot_20221216_210715_Traccar Manager](https://user-images.githubusercontent.com/120574638/208180880-7ea07047-1c8c-469b-b27e-368e4b78a18a.jpg)
![Screenshot_20221216_210658_Traccar Manager](https://user-images.githubusercontent.com/120574638/208180885-33fab9fa-1598-4019-b039-a0e8b77c2e11.jpg)

**Comment by tananaev** [comment]
Actually I know what the problem might. You set the value in the server settings. Try user settings. I missed the title on that screenshot. That's why I thought you're not using wrong version.

**Comment by anpalama1** [comment]
Do you mean here?  The user attribute  called live routes and not live route length.  
![Screenshot_20221216_212235_Traccar Manager](https://user-images.githubusercontent.com/120574638/208183200-6cc55364-4cbf-4853-a973-48c5d627f98d.jpg)

**Comment by tananaev** [comment]
The screen is right, but it seems like you've changed the wrong attribute. You have to use the same attribute you've used in the server settings.

**Comment by anpalama1** [comment]
But there is no live routes length under user attributes

**Comment by tananaev** [comment]
There's an "Add" button for that.

**Comment by anpalama1** [comment]
Thanks. I got it. I just missed it. I find the configuration very tiring. same attributes in many places.

**Comment by tananaev** [comment]
If you know how to improve it, let us know.

**Comment by anpalama1** [comment]
will do. promised😀
