### ISSUE TITLE
Assign a device to read only user from admin throw null reference exception 

### ISSUE THREAD

**Issue by AlaaL** [traccar/traccar#5005]
Hello,
I am trying to assign a device to a specific user using the permission API using an admin auth, but it throws an exception 

`Cannot invoke "java.util.LinkedHashMap.keySet()" because "entity" is null - NullPointerException (PermissionsResource: 58 < *: 69 < *: 87 < ...)`

The same exception occurs when using MySQL InnoDb (I checked foreign keys as suggested on other threads) and the default database engine H2

The http request from postman:

`POST /api/permissions?userId=9&deviceId=1 HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=`

![image](https://user-images.githubusercontent.com/5410074/208600138-e3429e69-8cbe-4653-b08e-18621303e6f6.png)

I also checked the user id and device id from the database.
Another note when I do the request from PHP Laravel the exception is different `"Cannot invoke "java.lang.Class.getSimpleName()" because "ownerClass" is null - NullPointerException (Permission:85 < *:97 < DatabaseStorage:161 < PermissionsResource:73 < ...)"`

**Comment by tananaev** [comment]
Your request is completely incorrect. Read documentation.

Also please use the forum instead of GitHub for questions.

**Comment by AlaaL** [comment]
Ok I will use the forum sorry i did not know that, but can you just point out the documentation you mean ? because in the API reference mentioning that i should send userId first and second deviceId or i miss understood it ?

![image](https://user-images.githubusercontent.com/5410074/208702609-6dbb934a-2f27-4c0e-848a-027bc8f1a06b.png)
