### ISSUE TITLE
TK-905 Watch Protocol ALARM 00000000

### ISSUE THREAD

**Issue by sincze** [traccar/traccar#5006]
I've been using Traccar for quite some time now with a TK-905 2G Traccar.
It used to raise an alarm when a shock was detected. ( If I add add admin mobile number to the device it will send me a text message "Sensor Alarm!"), so that works.

I removed the admin mobile number as I forward these events with Traccar to a webservice using traccar.xml.

Some time ago out of the blue this 'shock alarm' stopped working, GPS , device moving e.g. worked just fine with traccar.
I tried to live with it. 
Black Friday I saw an offer I could not refuse the TK-905 4G, so I thought well let's revive the shock alarm for this price. 
Unfortunately the same issue... Did not work anymore

I spoke to a friend who also is experiencing the same and a forum user is mentioning the same:
https://www.traccar.org/forums/topic/tk-905-al-message/#post-79086

At the moment I use traccar 5:5 and started to look at the logs because I thought the rootcause could be in the code.
I took the GPS inside and gave it a twist to raise an alert.. (below is decrypted message anonymized.

```
2022-12-15 20:29:55  INFO: [8774924e: watch < XXX.XX.XXX.XXX] 
[SG*XXXXXXXXXX*0067*AL,151222,202944,V,XXXX,N,XXXX,E,0.0,060,9,00,70,90,0,50,00000000,1,1,204,4,20304,25909761,19,,10]

2022-12-15 20:29:55  INFO: [8774924e: watch > XXX.XX.XXX.XXX] 
[SG*XXXXXXXXXX*0002*AL]
```
According to the watch protocol this is the correct sequence. 
I notice however "00000000", which I guess means "nothing" while still interpreting the manual of the protocol.
In my head this is the thing that does issue the SMS message when an admin number has been assigned to the GPS device, hence should be an alarm in traccar as well.

After the initial session of "AL" I notice the UD2 message. Should also be quite common.

```
2022-12-15 20:29:55  INFO: [8774924e] id: XXXXXXXXXX, time: 2022-12-15 20:29:44, lat: XXXX, lon: XXXX, course: 60.0
2022-12-15 20:29:57  INFO: [8774924e: watch < XXX.XX.XXX.XXX] 
[SG*XXXXXXXXXX*0068*UD2,151222,202950,V,XXXX,N,XXXX,E,0.0,060,9,00,70,90,0,50,00000000,1,1,204,4,20304,25909761,19,,00]
2022-12-15 20:29:57  INFO: [8774924e] id: XXXXXXXXXX, time: 2022-12-15 20:29:50, lat: XXXX, lon: XXXX, course: 60.0

2022-12-15 20:29:59  INFO: [8774924e: watch < XXX.XX.XXX.XXX] XXXX:
[SG*XXXXXXXXXX*006A*UD2,151222,202952,A,XXXX,N,XXXX,E,1.277,000,12,8,70,90,0,50,00000000,1,1,204,4,20304,25909761,19,,00]
```

I went through the Github change log and found:

[Merge Request Removed Alarm](https://github.com/traccar/traccar/commit/ea7b68003bce6603e6ad6227d022bca2867b64f3)

That alarm '3' was removed without mentioning a reason of why.

```
        } else if (BitUtil.check(status, 3)) {
            return Position.ALARM_OVERSPEED;
```
It is an official alarm according to the documentation of the protocol.

And
[Merge Request Fix alarm response](https://github.com/traccar/traccar/commit/3b62f3c29e181f6c3aefbfeff24281ed3332562e)

`if (type.equals("AL")) { `

vs

```
if (type.startsWith("AL")) {
```

in [Merge Request Fix alarm decoding](https://github.com/traccar/traccar/commit/51c6b0fe2ce11af9ce5f758dd81ffec3e59ad83b)
the removal of

```
                if (position != null) {
                    position.set(Position.KEY_ALARM, Position.ALARM_SOS);
                }
```

This last change/removal Is I guess the one we are looking for.
I went through some old traccar logs and did notice something
[Link](https://www.dropbox.com/s/h60jpw0offg28c5/report.xlsx?dl=0)

```
Type=Alarm
Attributes=alarm=sos
```
The code could have been removed from the code of this watch protocol by accident or an undocumented conflict that occurred. 
If we could have this change reverted or have it configurable TK-905 (and more users) may be able to use the SHOCK and ALARM functions of this great tracker in traccar again..

**Comment by tananaev** [comment]
Please provide the protocol documentation to support your request.

**Comment by sincze** [comment]
```
The terminal sending:
[CS*YYYYYYYYYY*LEN*AL,location data(Appendix 1)]
Example:
[SG*8800000015*0087*AL,220414,134652,A,22.571707,N,113.8613968,E,0.1,0.0,100,7,60,90,1000,50,0001,4,1,460,0,9360,4082,131,9360,4092,148,9360,4091,143,9360,4153,141]
Platform reply:
 [CS*YYYYYYYYYY*LEN*AL]
Example:[SG*8800000015*0002*AL]
Instruction:The terminal will send alarming information to platform when there is emergency.If the terminal does not get the reply ,it will reports on time until getting the alarming confirmation.

```
[Tk-Star](https://www.tk-star.com/?m=common&a=down&id=14)
[Extensive](https://sistemasorp.es/wp-content/uploads/2019/04/Communication-Protocol.pdf)

**Comment by tananaev** [comment]
I've read the original comment again and I'm a bit confused. We removed SOS and overspeed alarms, but you're talking about shock alarm, which is a completely different thing. So it sounds to me your case is a good example of the conflict. Am I misunderstanding something?

**Comment by sincze** [comment]
Haha I can imagine.
No my bad. 
The "Shock" in my words == A sudden Movement that wakes the device and initiates the following line 1 time:

```
2022-12-15 20:29:55  INFO: [8774924e: watch < XXX.XX.XXX.XXX] 
[SG*XXXXXXXXXX*0067*AL,151222,202944,V,XXXX,N,XXXX,E,0.0,060,9,00,70,90,0,50,00000000,1,1,204,4,20304,25909761,19,,10]

2022-12-15 20:29:55  INFO: [8774924e: watch > XXX.XX.XXX.XXX] 
[SG*XXXXXXXXXX*0002*AL]
```
Unfortunately they assigned AL -> 00000000 to it. 
In the past that would trigger an event forward in TRACCAR that would result into a phone call to me ;-) that something is happening near the car. 

After AL I receive only UD (Location data reporting).

**Comment by tananaev** [comment]
I understand that shock is a sudden movement and it's not the same thing as SOS alarm that you said you had previously. I'm still confused because you're basically confirming that it was working incorrectly before (wrong alarm), but you want to return it back? Shouldn't we fix it properly instead? I still don't understand what the right alarm should be because the documentation you provided doesn't specify it.

**Comment by sincze** [comment]
What I try to explain is that in older versions of TRACCAR it worked FLAWLESS a.k.a. excellent  ;-) perfectly happy.
(also mentioned by Joost on the forum, it used to work with TK-905) 

Use Case: 
- Car is parked.
- A door is opened
- I got a phone call. 

So no need for thieves to steal the car and start driving.
Just opening the door is sufficient to get alarmed. 

In the new version... No Alarm, 

Does this help a little in the use case experience?

**Comment by tananaev** [comment]
Traccar doesn't do phone calls. Is the issue with some response or command to the device?

**Comment by sincze** [comment]
I know 

Traccar does do event.forward 
And that triggers the phone call. :)

No alarm 
No forward 
No phone call.

**Comment by tananaev** [comment]
OK, that makes more sense. So what does the AL message mean? In the documentation it just says it's some generic alarm.

**Comment by sincze** [comment]
> OK, that makes more sense. So what does the AL message mean? In the documentation it just says it's some generic alarm.

That is the annoying part indeed. :)

If I add an admin to the tracker it triggers the SMS I mentioned earlier (no traccar needed this is the tk-905 firmware) however i dont want an sms due to costs hence i remove the admin phone number from the Tk-905.

I want traccar to still deal with this generic alarm :) so we can still do something usefull with it. Traccar used to do this but the functionality seems to have been removed from the code base.

Can we please reintroduce this generic alarm (traccar being able to do something usefull when the TK-905 raises the AL 00000000 message.

**Comment by jmedansc** [comment]
@sincze thanks for doing your research!! I do experience the same behaviour on the alarm event since upgrading Traccar from v4.8 to v5.3. The alarm event initiated by vibration/shock of the TK905 was my main reason to use Traccar software; it warns me for unwanted access to my vehicle. I have also connected the forward.event to a VOIP provider to alert me instantly by phone. (Opening a door would already trigger the alarm) Due to the code changes I only have the deviceMoving event left, which obviously comes in too late to act in time. Would be great if the Alarm SOS event could be added back to the Watch Protocol. Please see also my explanation in thread: https://www.traccar.org/forums/topic/tk-905-al-message/#post-78971

**Comment by tananaev** [comment]
I've added a general alarm for now.
