### ISSUE TITLE
Received Email alert notification Point URL is redirecting to local host ip. Should redirect to external ip

### ISSUE THREAD

**Issue by irfancyp** [traccar/traccar#5011]
**Describe the bug**
When an email alert is received for example speed alert. The received email consists data regarding alert. "Point:" data which supposed to redirect you to google maps where event occurred is using local host url but when you are outside of your local environment you cannot click and view "point:" url. It should have and hyperlink with external ip 

**To Reproduce**
1. Go to '...' receive any exceeds the speed event via email
2. Click on '....' check "Point:" url. it is not redirecting to external ip. it is redirectign you to local ip

**Screenshots**
![ss](https://user-images.githubusercontent.com/118547134/209525203-96b1da63-9ce0-4a7b-994e-c1a543703061.jpg)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Browser chrome
 - Version 108.0.5359.125

**Comment by tananaev** [comment]
Sounds like you simply haven't configured your external URL in the configuration file.

**Comment by irfancyp** [comment]
I have check your documents but i could not find the paramater.  Could you
please tell me the paramater to set it or send me the document link

**Comment by tananaev** [comment]
https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/config/Keys.java#L1525-L1531
