### ISSUE TITLE
Ban on the frequency of requests.

### ISSUE THREAD

**Issue by bivilbi** [traccar/traccar#5016]
Good afternoon. Now the server is banned by IP if you request Traccar too often via the API. But if there are a lot of GPS receivers and it is necessary to massively send commands (different) to them, then you have to do sleep between requests. How can I disable blocking for a specific ip by the number of requests? Or deploy the receiver locally to send to Traccar? Thanks.

**Comment by tananaev** [comment]
You can change `web.maxRequestsPerSec` configuration value. Next time please use the forum for questions. GitHub issues are ONLY for bugs and feature requests.
