### ISSUE TITLE
statusCode on Tracar integration with OpenGTS

### ISSUE THREAD

**Issue by fboesche** [traccar/traccar#502]
Hi, there is any way to include statusCode data when Traccar is integrated with OpenGTS ?

**Comment by cesarnava** [comment]
Hello.

When I setup my device TT8750, only sending AT commands similar to the following:

AT+CGDCONT=1,"IP","internet.itelcel.com","",0,0;&W
AT+CGDCONT=2,"IP","internet.itelcel.com","",0,0;&W
AT$GPSOSI=60,5;&W
AT$NETMON=10,1,0,1;&W
AT$STOATEV=1,AT$MSGLOGEN=0;&W
AT$STOATEV=2,AT$MSGLOGEN=1;&W
AT$EVTIM2=1800;&W
AT$UDPAPI= "199.245.180.013", 1802;&W
AT$FRIEND=1,1,"192.168.251.056";&W
AT$IODBNC=4,30;&W
AT$IODBNC=1,3;&W
AT$IODBNC=8,4;&W
AT$EVTIM2=300;&W
AT$EVENT=8,1,13,1,1;&W
AT$EVENT=8,3,40,2,1703935;&W

How do I set these bits 0 and 27?
