### ISSUE TITLE
GT06 protocol ignition value not copying from heartbeat

### ISSUE THREAD

**Issue by gaurav28121986** [traccar/traccar#5020]
We are getting igniton value in heartbeat packets and we want to copy it in location packets so we have using copyAttributes.Below is our settings but it is not working

![image](https://user-images.githubusercontent.com/113875836/213929709-b1be5f9b-d18d-4a34-a430-5229e013aeca.png)

please help me if anybody also got the same type of issue and how did you resolve it.

**Comment by tananaev** [comment]
For questions and discussions you should use the forum.
