### ISSUE TITLE
RegisterUnknown filter only allow number as identifier

### ISSUE THREAD

**Issue by bernamaxim** [traccar/traccar#5023]
Hi Anton,

I let Register Unknown be true.

``` <entry key='database.ignoreUnknown'>true</entry> ```
``` <entry key='database.registerUnknown'>true</entry> ```

But the problem is lots of strange data as new and unknown unit is entered, even unit without Identifier can be entered and register as new unit. Most are entered with an identifier in the form of a hexadecimal number.

Is it possible to implement the Traccar feature to filter out units like this (example: only allow numbers, contain certain words, etc.)

<img width="1273" alt="Screen Shot 2023-01-31 at 2 25 14 PM" src="https://user-images.githubusercontent.com/2969479/215695785-e0999f10-b206-4365-99c3-46be8100281f.png">

**Comment by tananaev** [comment]
Seems like a good idea.
