### ISSUE TITLE
Add device location sharing function

### ISSUE THREAD

**Issue by gitalgps** [traccar/traccar#5025]
Add device location sharing function.
Usage scenario.
Some companies and fleets have many irregular customers (e.g. one-time customers), and sometimes some customers request to monitor the location of their cargo.
We can then temporarily share a link to the customer for monitoring one or some devices (and can set an expiration date that will automatically stop the sharing).

No registration and no login. This has the advantage that there is no need to create users, reducing the cost of user management time.

I share a link (don't worry about my privacy, I use a virtual location)
[https://demo-hs.gpswox.com/sharing/a459534ba067e22d802fa9aca265d855](url)

**Comment by jsnxptech** [comment]
Até hoje, vi apenas:

[https://github.com/traccar/traccar/issues/3789](url) e [https://github.com/traccar/traccar/issues/4936](url) ...


mmas pelo visto nadaa vai pra frente.

**Comment by jsnxptech** [comment]
tanks
