### ISSUE TITLE
Update Notifications Channels

### ISSUE THREAD

**Issue by voklav** [traccar/traccar#5027]
Hello everyone.
I would like to have more channels for notifications. Now we have only web and mail.
it will be great if we have telegram, webhook, and everything else that modern systems have :)

p.s. inspired by [uptime-kuma](https://github.com/louislam/uptime-kuma) which I recently ran on my home server.

**Comment by tananaev** [comment]
I suggest you read the documentation first. We support Telegram, webhooks and many other options.

**Comment by voklav** [comment]
thanks, and sorry,
my mistake, I confused [Events and Notifications](https://www.traccar.org/events/) with [Notifications Configuration](https://www.traccar.org/notifications/)
