### ISSUE TITLE
Cannot declare variables in Computed attributes

### ISSUE THREAD

**Issue by memesaregood1** [traccar/traccar#5028]
**Describe the bug**
Local JEXL variables cannot be accessed or declared anymore. Worked in 5.3, as far as I remember.

**To Reproduce**
1. Go to 'Computed Attributes'
2. Click on '+'
3. Enter this expression: `var theAnswer = 42; theAnswer += 2; theAnswer`, type: number
4. See error: `org.traccar.handler.ComputedAttributesHandler.computeAttribute:105@1:1 parsing error in 'var' - Parsing (... < ComputedAttributesHandler:105 < AttributeResource:63 < ...)`

**Expected behavior**
44

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser; Chrome
 - Version: 109

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9
 - OS: Android 11
 - Browser: Chrome
 - Version 107

**Additional context**
Traccar version: 5.6, upgraded from 5.5, previously upgraded from 5.3. Java 17.
Reference: https://commons.apache.org/proper/commons-jexl/reference/syntax.html

**Comment by tananaev** [comment]
I think it's just a limitation of the new version of JEXL. We run it as an expression using [createExpression](https://commons.apache.org/proper/commons-jexl/apidocs/org/apache/commons/jexl3/JexlEngine.html#createExpression(java.lang.String)) method.

**Comment by memesaregood1** [comment]
It does not make sense to me. If this is mentioned in Syntax documentation, as well as function declaration, why isn't it supported in _your_ JEXL?

**Comment by tananaev** [comment]
I don't know, but feel free to investigate and let us know if you find anything.

**Comment by memesaregood1** [comment]
I've indeed done some digging. It appears that some functions are indeed disabled, but they can be enabled using ``JexlFeatures``. If used correctly, it may be used to enable missing funcitonality and not expose any security vulnerabilities.
I'll be preparing a PR in a short while.
