### ISSUE TITLE
TK103-B+ with 2 Fuel sensors.

### ISSUE THREAD

**Issue by geniez** [traccar/traccar#503]
I tested my tracker with traccar and it worked fine under GPS-103 protocol. But with my tracker i couldnt find few entries, Like door alarm, ACC alarms. Also I have 2 fuel sensors in my tracker which i want to monitor. Need help with decoder. 
Here's what i tried to catch on tcp connection using wireshark. 

imei:359710041961583,tracker,1312170400,,F,230030.000,A,2455.3288,N,06705.8537,E,0.00,0,,0,0,0.00%,,;
ON

And heres what is writes in 'others' field 

11, '', 0, 0, 24.9221466666667, 67.0975616666667, '<info><protocol>gps103</protocol><alarm>tracker</alarm></info>', , 0, '2013-12-16 17:44:31', 1, 1

Thnx

**Comment by and12345** [comment]
Hi geniez, sorry for bringing up an old thread. But i need help regarding this problem, would you mind sharing your work

**Comment by martynask** [comment]
Hi geniez/tananaev, please share your work, it would be very helpful to other traccar users.

**Comment by tananaev** [comment]
@martynask, all source code is available here on GitHub. Latest version of Traccar can parse 4 additional parameters for GPS103 protocol.
