### ISSUE TITLE
Feature Request - add password to telegram-bot

### ISSUE THREAD

**Issue by umbm** [traccar/traccar#5045]
For increased security level please add a password to telegram bot.

After a user sends /start to the bot he will be asked for the password, so all other activities are blocked for not authorized users.

**Comment by tananaev** [comment]
What if you add a password to the bot now? Something doesn't work?

**Comment by umbm** [comment]
In other projects the bot client side handles the password as I understand.
But it's a one way from traccar to telegram user this time so it might be unimportant.
