### ISSUE TITLE
Are polyline geofence coordinates not correctly reverse ?

### ISSUE THREAD

**Issue by comicat-hu** [traccar/traccar#5048]
I use modern web to draw a polyline geofence, I got `LINESTRING (121.50858529026766 24.999844298491823, 121.51249677946782 25.00435771739683)` in DB, it is not work when device cross the line.

draw a polygon geofence,  I got `POLYGON ((25.002757200386966 121.51101066162965, 25.002194338295013 121.51053651743189, 25.00181304315457 121.5110874596341, 25.002418272984812 121.5115549257444, 25.002757200386966 121.51101066162965))` in DB, it can work.

Whether LINESTRING coordinates should be reversed at the frontend or backend ?

this line in GeofencePolyline.java seem to set lat to 121.50858529026766 and set lon to 24.999844298491823 when handle polyline from wkt format.
https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/geofence/GeofencePolyline.java#L99

**Comment by tananaev** [comment]
Looks like the issue was only when you have a single segment line. Fixed it here https://github.com/traccar/traccar-web/commit/cb0f64ecd9bf1de543d6a30f65fdddb92b4d926a.
