### ISSUE TITLE
error on screen when changing maps

### ISSUE THREAD

**Issue by ubiteczla** [traccar/traccar#5050]
**Describe the bug**
error on screen when changing maps

**To Reproduce**
the error is more common in chrome and edge browsers, less in opera and almost never appears in brave, it also appears in the traccar manager app. It happens when changing maps at random moments, to forcefully play it enter and start changing maps with the button for that use on the right of the screen above, (note, it happens mostly with google maps, but it has also been seen with bing in less moments or only with carto and openstreetmaps)

![IMG-20230320-WA0012 1](https://user-images.githubusercontent.com/128443896/226509023-467bf010-3506-433c-bf3c-55404fe6747e.jpg)

**Screenshots**
attachments.

**Desktop (please complete the following information):**
  win10 win11 and android with mentioned browsers

**Additional context**

**Comment by ubiteczla** [comment]
same error  on another vps

![IMG-20230320-WA0013 1](https://user-images.githubusercontent.com/128443896/226510932-3850f4c3-480b-4d53-94ef-8746c75fb07f.jpg)

**Comment by tananaev** [comment]
This should be under the web app repo. Also make sure to include version and any other relevant information, like configuration and settings.
