### ISSUE TITLE
Implement OpenID Connect SSO

### ISSUE THREAD

**Issue by dan-r** [traccar/traccar#5056]
Initially discussed in #5055

So focusing on the OIDC code flow, I'd propose 2 new API endpoints:
- /api/session/openid/auth - Checks for an existing session and redirects to identity provider if necessary 
- /api/session/openid/callback - Callback URL for the identity provider

I'd also add the following configuration variables:
- oidc.enable - boolean state
- oidc.force - true = don't show Traccar login page, redirect straight to identity provider
- oidc.clientId - OIDC client ID
- oidc.authURL - OIDC authorization URL
- oidc.tokenURL - OIDC token URL
- oidc.userinfoURL - OIDC user info URL
- oidc.adminGroup - OIDC group to grant admin access

The proposed implementation steps would be:
- Add config keys to Config.java
- Add new API endpoints to SessionResource.java
- Create a new module in org.traccar.api.security to handle everything SSO
  - Potentially refactor some of LoginService.java if a lot of it is ending up copied to the new module
- Add a redirect for when oidc.force is true to either traccar-web logic or WebServer.java
- Update tests, Swagger spec and documentation

![Untitled Diagram](https://user-images.githubusercontent.com/1384852/229298644-0f534013-d5ba-4a78-8f9a-884ec7bfc426.jpg)

**Comment by tananaev** [comment]
Would you be interesting it writing a short documentation on how to set everything up? Maybe with one example provider, ideally something popular, like Google. I want to publish it in the documentation section on the website.

**Comment by tananaev** [comment]
Yes, something like that.

**Comment by tananaev** [comment]
Either one. I think generic like LDAP works. It would also be nice to have some real example.

**Comment by dan-r** [comment]
Sure, I'll give it a go and put it in here

**Comment by tananaev** [comment]
You can just prepare a Google doc or something like that. I'll transfer it to the website after. The website source code is not public.

**Comment by tananaev** [comment]
Thanks for such a detailed documentation. I've published it on the website:

https://www.traccar.org/openid-sso/

I haven't linked to it from the main documentation page yet to not confuse people. With the next official release I'll link to it from some prominent place there and of course mention it in the release blog post.
