### ISSUE TITLE
Unable to create or update notification entry

### ISSUE THREAD

**Issue by dan-r** [traccar/traccar#5059]
**Describe the bug**
Post-OpenID implementation I'm testing a build of master on my local Traccar instance. When updating or creating notifications in the web app, I get:

With inbuilt H2:
`Column "COMMANDID" not found; SQL statement: INSERT INTO tc_notifications(commandId, notificators, always, type, calendarId, attributes) VALUES (?, ?, ?, ?, ?, ?) [42122-214] - JdbcSQLSyntaxErrorException (... < QueryBuilder:71 < *:146 < DatabaseStorage:93 < BaseObjectResource:71 < ...)`

With MySQL:
`Unknown column 'commandId' in 'field list' - SQLSyntaxErrorException (... < QueryBuilder:469 < DatabaseStorage:95 < BaseObjectResource:71 < ...)`

An example of a failing API request:
POST /api/notifications
`{type: "deviceOnline", notificators: "web"}`

**To Reproduce**
1. Create or update a notification entry

**Desktop (please complete the following information):**
Windows 11 Chrome (Latest)

**Smartphone (please complete the following information):**
iOS Safari (Latest)

**Comment by tananaev** [comment]
Are you sure you've updated the schema files?

**Comment by dan-r** [comment]
I thought I had... Give me a sec I'll copy it all over again as a sanity check

**Comment by dan-r** [comment]
Had them all but didn't overwrite master, doh, thanks Anton
