### ISSUE TITLE
Too many open file descriptor despite optimization

### ISSUE THREAD

**Issue by GeminiKiller** [traccar/traccar#5072]
We have implemented based on your optimization and set tcp.timeout at 3600s in traccar.xml.

We have only 1200 active devices and 1500 offline.

At the start, we have 1182 active ESTABLISHED connections and very low close_wait.

at day 5, the numbers jumped.

currently we find very odd behaviour that ESTABLISHED network is 3x  after day 5.
      1 FIN_WAIT2
      1 Foreign
      1 established)
      7 SYN_RECV
     11 LISTEN
     61 FIN_WAIT1
    253 TIME_WAIT
   3385 ESTABLISHED
 106560 CLOSE_WAIT

what can it be done to reduce those numbers?

**Comment by tananaev** [comment]
For discussions you should use the forum instead.
