### ISSUE TITLE
[BUG] Sending commands to groups of devices 5.7

### ISSUE THREAD

**Issue by Track-traces** [traccar/traccar#5075]
The conversation is on the traccar forum but its not possible to reply anymore to your questions on the topic (shows forbidden)
[https://www.traccar.org/forums/topic/sending-commands-to-groups-of-devices-57/page/2/](https://www.traccar.org/forums/topic/sending-commands-to-groups-of-devices-57/page/2/)

So i did send the requested details to support@traccar.org

**Describe the bug**

When a group command is send when a device which is member of a group is offline. Then the command is not send or send to onlysome devices.
When all devices whcih are member of the group are online. Then all commands are send correctly. 

**To Reproduce**
See traccar forum thread with examples.

**Comment by tananaev** [comment]
Good catch. Fixed it.

**Comment by Track-traces** [comment]
Thanks
