### ISSUE TITLE
Case Sensitivity in User Registration: A Potential Security Vulnerability

### ISSUE THREAD

**Issue by sqrtZeroKnowledge** [traccar/traccar#5076]
**Describe the bug**

Hello Team,

While working on a private project, I discovered a security issue that could potentially impact Traccar web application users. The issue is related to the ability to register a new account using the same email address, which could allow for account takeover by resetting the password or other similar techniques.

**To Reproduce**
1. Create User account example [example@example.com]
2. At this point you can create another account under the same information of the same account including same email address with uppercase like [EXAMPLE@EXAMPLE.COM]
3. Set the SMTP Server and port request reseting password.

**Expected behavior**
If a user can register using an email that has already been registered but only differs in case sensitivity. This is due to the possibility that an attacker may use it to impersonate another user and access their account.

If the email "example@example.com" is already registered in the system, for instance, an attacker can create a new account with the email "EXAMPLE@EXAMPLE.COM" and use the "Reset Password" function to access the victim's account.

The Traccar registration section should check case-insensitive email uniqueness during the registration and login processes in order to stop this kind of attack.

**Screenshots**

![imaxe](https://user-images.githubusercontent.com/31594437/235953396-0b74573f-5505-4dec-8c4e-e01861c27ef0.png)

**Comment by tananaev** [comment]
It sounds like your database is misconfigured. You need to make sure you configure it as case insensitive, which is the default for most common databases.

**Comment by sqrtZeroKnowledge** [comment]
Well noted, Thanks for the clarification i will inform the people concerned about the deployment part. 
Thanks.
