### ISSUE TITLE
POI Layer KML Support StyleURL 

### ISSUE THREAD

**Issue by DeanoXX** [traccar/traccar#5091]
I would like to be able to differentiate different tracks loaded via the POI Layer based on their color and width as defined within the "StyleURL" tags within the KML file.

I use Traccar to monitor children's hiking groups progress against multiple planned routes that are either close or cross each other. Allowing the style (color, width etc) to be varied between routes (tracks), inlcuding the style of the coordinates would significantly increase the clarity.

**Comment by tananaev** [comment]
This should be in https://github.com/traccar/traccar-web.
