### ISSUE TITLE
Showing reports-> trips does not load

### ISSUE THREAD

**Issue by marno2703** [traccar/traccar#5094]
Hi, 

I updated traccar today from 4.14 to the latest release.
Every reports works fine except trips. (it does before updating, nothing changed in config)
If there are no data for the device this report "works". If there is some data, it show three grey bars (loading indicator) and nothing happens. There is no error in the logs.
After some time (timeout) it displays a message on the browser:
```json
{ "servlet":"org.glassfish.jersey.servlet.ServletContainer-1d6713dd", "message":"Service Unavailable", "url":"/api/reports/trips", "status":"503" }
```
When I directly call the api /api/reports/trips in GET with correct data (incorrect data gives error), it runs into timeout.

Marius

**Comment by tananaev** [comment]
It sounds like it just times out.

**Comment by marno2703** [comment]
> It sounds like it just times out.

Yes, I'm shure it does. But it should not. And there is no reason. It times out even when there is only a very smal amount of data. As I said, the older version works great and very fast, even with huge amount of data.

**Comment by marno2703** [comment]
> How much data and what time does it fail after?

I used 1 Device with an period of time with 8 events logged within.
The old version, works with reports with > 20000 events within 1 second.
Timeout feels like 120 seconds, did not measure it.

**Comment by tananaev** [comment]
Why are we talking about events? I thought it's a trip report, so you need to check how many positions you are extracting from the database.

**Comment by marno2703** [comment]
> you need to check how many positions you are extracting from the database.

If the 253 positions for this device within the selected period.

**Comment by tananaev** [comment]
Oh yeah, it definitely shouldn't timeout. I suspect you have some database issue in that case. What troubleshooting have you done so far?

**Comment by marno2703** [comment]
> What troubleshooting have you done so far?

All, I described here so far.

Tried to call the json-api
looked into logs
queried mysql directly

**Comment by tananaev** [comment]
Check MySQL processes to see if the query is locked. Get Java dump to see where the code gets stuck.

**Comment by marno2703** [comment]
I just tried a really short period, and I got a crazy response from api:

https://files.mariusnoetzel.de/dropshare//a5nVZDg3gOYiwC1M92tkIOMHsmYPOIBqeQwG61lZY9E9dLdSKRYoKFF5xlciSDGFSTJ3OEQ7Lra95XVuGv6gXRS5uhTFop566pwk.png

This is definetly no json ;) Rest-Tool is set to utf-8 all other api-endpoints give correct response.

**Comment by tananaev** [comment]
I'm not asking you to lock the database. I'm asking you to check the running queries.

To get Java dump you can use jstack.

As for the JSON, you have to provide Accept header. It's the industry standard and not something specific to Traccar.

Also, can you please take your time and do some research before rushing with an answer. Many of these things have been discussed on the forum.

**Comment by marno2703** [comment]
Hmm,

I saw an example, where the Request-Header "Content-Type" is set to "application/json". Same way as I set Basic-Auth. (I still could not find something about Content-Type within the docs, perhaps I'm to stupid.). But I still get the same response.

**Comment by tananaev** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept

**Comment by marno2703** [comment]
What I can see, is: 

Traccar make some Select queries from users, devices, groups and positions. These were answered, then it makes a:

`SELECT * FROM tc_reports`

This query comes three times, with exactly 60 seconds beetween them. So for me it seems like, traccar runs into a timeout or something like that with this query. tc_reports is an empty table. This select should not be any problem.

**Comment by tananaev** [comment]
That has nothing to do with your issue. I think we should probably move this discussion to the forum first until we establish that there's some bug.
