### ISSUE TITLE
New fast reports bug

### ISSUE THREAD

**Issue by merabtenei** [traccar/traccar#5104]
**Describe the bug**
I'm getting the following error with the new updated fastReports method:
```
NullPointerException (ReportUtils:174 < *:272 < *:395 < *:298 < TripsReportProvider:65 < ReportResource:251 < ...)
```

**To Reproduce**
1. set report.fastThreshold to 180000
2. request a Trips report from=2023-05-01T23:00:00.000Z&to=2023-05-31T22:59:59.000Z

**Another thing is with an interval greater than report.fastThreshold maxSpeed is always zero.**

**Additional context**
Traccar version: Git master branch.
This only happening in our development server. I think there's something wrong somewhere in the collected data that causes this. But I think the report should still check and avoid NullExceptions to provide a valid response.

**Comment by tananaev** [comment]
It seems like you're missing some positions.

**Comment by merabtenei** [comment]
In production server there is no exception but we still get max speed as zero with large interval. Can you check that with the latest version ?
When selecting Trips for an interval less than 24 hours (which does not trigger fastReports and use old method) max speed is correctly reported. When using interval larger than 24 hours max speed is zero for every trip.

**Comment by tananaev** [comment]
That is expected behavior. Max speed is not available for fast reports. You can change the threshold for fast reports in the config file.
