### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by carlock2022** [traccar/traccar#5105]
Greetings, apparently the version https://github.com/traccar/traccar/releases/download/v5.8/traccar-linux-64-5.8.zip has the web app 5.7 integrated, this image is a fresh installation with that file

![image](https://github.com/traccar/traccar/assets/114795834/76231698-2bcd-445f-9fe5-0016f39513ba)

**Comment by tananaev** [comment]
It probably indicates that you have not cleared the browser cache. I just tested on a clean server and the version is correct.

**Comment by carlock2022** [comment]
ok, ithere is something in the browsers and the latest version of traccar. even in the demos, vps or server with versions 5.7 open perfectly, but in 5.8 it fails in some browsers, tested on 5 pc in different networks and versions it fails 50% always the same message n developerm I hope this helps

Uncaught Error: {"requestedAttributes":{"alpha":true,"stencil":true,"depth":true,"failIfMajorPerformanceCaveat":false,"preserveDrawingBuffer":false,"antialias":false},"statusMessage":"Could not create a WebGL context, VENDOR = 0x8086, DEVICE = 0x0102, GL_VENDOR = Google Inc. (Intel), GL_RENDERER = ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumd64.dll -9.17.10.4459), GL_VERSION = 9.17.10.4459, Sandboxed = yes, Optimus = no, AMD switchable = no, Reset notification strategy = 0x8252, ErrorMessage = BindToCurrentSequence failed: .","type":"webglcontextcreationerror","message":"Failed to initialize WebGL"}
    at Map._setupPainter (map.ts:2752:23)
    at new Map (map.ts:483:14)
    at MapView.js:17:20
    at index.js:46:1
    at index.js:46:1

![Captura de pantalla 2023-06-06 160340](https://github.com/traccar/traccar/assets/114795834/d37e526c-9fad-4c53-84eb-73dfcd595b6d)

**Comment by carlock2022** [comment]
exactly same pc and  navigator accesing a fresh 5.7 
![Captura de pantalla 2023-06-06 160944](https://github.com/traccar/traccar/assets/114795834/34e11723-d5bc-45fb-a7cc-c6fd7f77115d)

**Comment by tananaev** [comment]
Which browsers are failing? Do you have a way to reproduce on a clean server?

**Comment by carlock2022** [comment]
The first image is from demo 4 of official traccar, 3 has the same drawback, I also tested 5.8 on new digital ocean vps and it can't be seen, just a blank screen with the indicated error, delete the droplet to be sure and create new with 5.7 and that works in all the browsers I have (brave, edge, crhome), the error indicates a problem with webgl, so I checked https://get.webgl.org/ in all browsers and it's perfect, in some manages to load 5.8 but after a long time. I know it looks like some driver or compatibility with old drivers, by the way, all pc's are windows 10 or 11 (note that 5.7 in the second image opens and 5.8 doesn't open in the same browser on the same pc)

**Comment by tananaev** [comment]
To investigate I need a way to reproduce it locally.
