### ISSUE TITLE
Code Overview about API receiving GPS location 

### ISSUE THREAD

**Issue by infotechirfannasim** [traccar/traccar#5108]
I want to know the IP location of URL
```
http://localhost:8082?id=irfan&timestamp=1686208865&lat=37.4226711&lon=-122.0849872&speed=0.0&bearing=0.0&altitude=0.0&accuracy=899.9990234375&batt=100.0
```
that what is the code / method where this request is landing, i have found that in MainEventHandler.channelRead() receiving but this is not an API / resource. how HTTP call is working and request is landing here.?

**Comment by tananaev** [comment]
For questions you should use the forum instead.

**Comment by infotechirfannasim** [comment]
@tananaev  unable to register on forum so that I have used this portal
