### ISSUE TITLE
Version 5.8 does not launch the web

### ISSUE THREAD

**Issue by hiagodotme** [traccar/traccar#5109]
Version 5.8 does not launch the web. The error below appears in the console, I thought it could be some new configuration that I didn't implement, so I noticed that the problem occurs even on demo servers that have this version.

Tested in [https://demo4.traccar.org/](https://demo4.traccar.org/)
```
Uncaught Error: {"requestedAttributes":{"alpha":true,"stencil":true,"depth":true,"failIfMajorPerformanceCaveat":false,"preserveDrawingBuffer":false,"antialias":false},"statusMessage":"Could not create a WebGL context, VENDOR = 0x8086, DEVICE = 0x0102, GL_VENDOR = Google Inc. (Intel), GL_RENDERER = ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumd64.dll -9.17.10.4459), GL_VERSION = 9.17.10.4459, Sandboxed = yes, Optimus = no, AMD switchable = no, Reset notification strategy = 0x8252, ErrorMessage = BindToCurrentSequence failed: .","type":"webglcontextcreationerror","message":"Failed to initialize WebGL"}
    at Map._setupPainter (main.6cd3a572.js:sourcemap:2:1590063)
    at new Map (main.6cd3a572.js:sourcemap:2:1571685)
    at main.6cd3a572.js:sourcemap:128:253993
    at main.6cd3a572.js:sourcemap:178:576531
    at main.6cd3a572.js:sourcemap:178:576534
```

**Comment by tananaev** [comment]
This probably belongs in the `traccar-web` repo.

Also I can't reproduce it. What device / platform / browser are you using?

**Comment by hiagodotme** [comment]
Here the problem occurs when trying to access through google chrome, version 114.0.5735.110 on a computer with Windows 11 64bit.

When accessing the iOS application everything works normally, in Safari access also works normally. I've tried clearing the caches, and entering incognito mode, but the problem persists.

**Comment by tananaev** [comment]
Does the map here work for you?

https://maplibre.org/maplibre-gl-js-docs/example/simple-map/

**Comment by carlock2022** [comment]
greetings anton, it is the same error as in the case https://github.com/traccar/traccar/issues/5105 I have not been able to dedicate time to specify its scenario, note, the previous link does not open on the same computers of mine where it does not open 5.8)

**Comment by carlock2022** [comment]
Greetings, apparently the inconvenience is with the compatibility to webgl 2.0 most of the integrated intel cards have compatibility problems with this, here is a page to confirm compatibility https://webglreport.com/?v=2

**Comment by carlock2022** [comment]
Versions prior to this run perfectly, some of the changes at this time are causing the incompatibility 

https://github.com/traccar/traccar-web/tree/5bb0ec8bab20ca3aa2ee50328e81d25c0e986520

**Comment by hiagodotme** [comment]
I had thought the same, but I looked here and chrome remains in the same version.

**Comment by tananaev** [comment]
No, but there's a forum.

**Comment by guicrocetti** [comment]
facing the same problem after upgrade to 5.8

> Version 5.8 does not launch the web. The error below appears in the console, I thought it could be some new configuration that I didn't implement, so I noticed that the problem occurs even on demo servers that have this version.
> 
> Tested in https://demo4.traccar.org/
> 
> ```
> Uncaught Error: {"requestedAttributes":{"alpha":true,"stencil":true,"depth":true,"failIfMajorPerformanceCaveat":false,"preserveDrawingBuffer":false,"antialias":false},"statusMessage":"Could not create a WebGL context, VENDOR = 0x8086, DEVICE = 0x0102, GL_VENDOR = Google Inc. (Intel), GL_RENDERER = ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumd64.dll -9.17.10.4459), GL_VERSION = 9.17.10.4459, Sandboxed = yes, Optimus = no, AMD switchable = no, Reset notification strategy = 0x8252, ErrorMessage = BindToCurrentSequence failed: .","type":"webglcontextcreationerror","message":"Failed to initialize WebGL"}
>     at Map._setupPainter (main.6cd3a572.js:sourcemap:2:1590063)
>     at new Map (main.6cd3a572.js:sourcemap:2:1571685)
>     at main.6cd3a572.js:sourcemap:128:253993
>     at main.6cd3a572.js:sourcemap:178:576531
>     at main.6cd3a572.js:sourcemap:178:576534
> ```

facing the same problem after upgrade to 5.8

**Comment by hiagodotme** [comment]
@guicrocetti I couldn't replicate the problem, when I went to do other tests everything was back to normal. So I don't know if it was some cache or something, but for now everything is OK here.

**Comment by guicrocetti** [comment]
I'm facing this only on an old laptop and phone. I tried to clean all cache eveen on fresh new firefox instalation, still get the same error.  I tried chrome, IE and Firefox with private browsing as well. 

this is the error:

map.ts:2752 Uncaught Error: {"requestedAttributes":{"alpha":true,"stencil":true,"depth":true,"failIfMajorPerformanceCaveat":false,"preserveDrawingBuffer":false,"antialias":false},"statusMessage":"Could not create a WebGL context, VENDOR = 0x8086, DEVICE = 0x0046, GL_VENDOR = Google Inc. (Intel), GL_RENDERER = ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumd64.dll -8.15.10.2900), GL_VERSION = 8.15.10.2900, Sandboxed = yes, Optimus = no, AMD switchable = no, Reset notification strategy = 0x8252, ErrorMessage = BindToCurrentSequence failed: .","type":"webglcontextcreationerror","message":"Failed to initialize WebGL"}
    at Map._setupPainter (map.ts:2752:23)
    at new Map (map.ts:483:14)
    at MapView.js:17:20
    at index.js:45:1
    at index.js:45:1

**Comment by carlock2022** [comment]
https://github.com/traccar/traccar/issues/5109#issuecomment-1586004188

> I'm facing this only on an old laptop and phone. I tried to clean all cache eveen on fresh new firefox instalation, still get the same error. I tried chrome, IE and Firefox with private browsing as well.
> 
> this is the error:
> 
> map.ts:2752 Uncaught Error: {"requestedAttributes":{"alpha":true,"stencil":true,"depth":true,"failIfMajorPerformanceCaveat":false,"preserveDrawingBuffer":false,"antialias":false},"statusMessage":"Could not create a WebGL context, VENDOR = 0x8086, DEVICE = 0x0046, GL_VENDOR = Google Inc. (Intel), GL_RENDERER = ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumd64.dll -8.15.10.2900), GL_VERSION = 8.15.10.2900, Sandboxed = yes, Optimus = no, AMD switchable = no, Reset notification strategy = 0x8252, ErrorMessage = BindToCurrentSequence failed: .","type":"webglcontextcreationerror","message":"Failed to initialize WebGL"} at Map._setupPainter (map.ts:2752:23) at new Map (map.ts:483:14) at MapView.js:17:20 at index.js:45:1 at index.js:45:1

https://github.com/traccar/traccar/issues/5109#issuecomment-1586004188

**Comment by tananaev** [comment]
Does it work in the newer versions?

**Comment by hiagodotme** [comment]
@tananaev yes, everything works here in 5.9

**Comment by hiagodotme** [comment]
In fact, 5.8 where the problem occurred started working again after a while.
