### ISSUE TITLE
Computed Attributes, JEXL and advanced usage 

### ISSUE THREAD

**Issue by jinzo** [traccar/traccar#5116]
While trying to do a little bit more advanced computed attributes I encountered some difficulties and I'm opening this bug report to track what I found out and hopefully provide a pull request. And maybe @memesaregood1 can provide some insight, as he did some changes to this lately. 

Namely - first, what I'm sure is a bug/needs documentation update is the mention that new() can be used: 
```
new("java.lang.Double", 10)
```
This needs an additional note that it needs to be enabled before with (same as the note for localVariables)
```
<entry key='processing.computedAttributes.newInstanceCreation'>true</entry>
```
And from what I can see, this computedAttributes settings are not mentioned in the auto generated config file documentation?

But even after enabling this, it does not work. I suspect it's because of the sandboxing - but need to investigate further
**Test**
```
var foo = new("java.lang.Double", 10)
return "baz" + foo
```
**Error**
```
org.traccar.handler.ComputedAttributesHandler.computeAttribute:119@1:1 unsolvable function/method 'java.lang.Double(Byte)' - Method (ComputedAttributesHandler:120 < AttributeResource:63 < ... < OverrideFilter:50 < ...)
```
As I'm a little bit pressed for time, I'm not sure if I will tackle this immediately or solve my problem in a different way for now and then investigate this further. From a quick look JEXL config/sandboxing is not so simple to understand, at least for me.

**Comment by memesaregood1** [comment]
You are right.
I [threw together](https://gist.github.com/memesaregood1/18d24f79e8a3c8b5f47be312e9ddb6ed) some code to play around with the engine, and, as you suspected, Sandbox is blocking the `new()` calls for denied types, if such are not allowed. Strangely enough, when I was testing around when I made changes to Traccar, things worked fine.

**Comment by jinzo** [comment]
Thanks for your effort - so I would suggest that the basic types that could be used for manipulating the attributes are added:
```
        sandbox.allow(Double.class.getName()); //types have to be allowed too!
        sandbox.allow(Float.class.getName());
        sandbox.allow(Integer.class.getName());
        sandbox.allow(Long.class.getName());
        sandbox.allow(Short.class.getName());
        sandbox.allow(Character.class.getName());
        sandbox.allow(Boolean.class.getName());
        sandbox.allow(String.class.getName());
```
And documentation update with this info should be enough for now? And then later down the line this can be extended/made configurable if the need arises?

@memesaregood1 @tananaev what do you guys think about this suggestion?

**Comment by tananaev** [comment]
Adding primitive types makes sense to me.

**Comment by jinzo** [comment]
So I guess if @tananaev will update the documentation with this two notes:
a) "new" has to be enabled with ```<entry key='processing.computedAttributes.newInstanceCreation'>true</entry>```
b) it can only instantiate ```Double, Float, Integer, Long, Short, Character, Boolean, String, Byte```

Thanks @memesaregood1 for the triaging and the fix and @tananaev for merging!

**Comment by memesaregood1** [comment]
@tananaev following #5320, please update the doc.
