### ISSUE TITLE
TypeError in Combined reports with OB22 (Concox)

### ISSUE THREAD

**Issue by corv89** [traccar/traccar#5120]
**Describe the bug**
```
TypeError: Cannot read properties of undefined (reading 'latitude')
    at https://domain.com/static/js/main.862191b0.js:178:3303
    at Array.map ()
    at https://domain.com/static/js/main.862191b0.js:178:3225
    at Array.flatMap ()
    at lw (https://domain.com/static/js/main.862191b0.js:178:3204)
    at Mo (https://domain.com/static/js/main.862191b0.js:2:681543)
    at Ds (https://domain.com/static/js/main.862191b0.js:2:693231)
    at Ml (https://domain.com/static/js/main.862191b0.js:2:739539)
    at Sc (https://domain.com/static/js/main.862191b0.js:2:727762)
    at yc (https://domain.com/static/js/main.862191b0.js:2:727690)
```
**To Reproduce**  
Steps to reproduce the behaviour:
1. Go to Combined reports
2. Click on show
3. See error

**Expected behaviour**
Expected to see a map plotting locations

**Desktop (please complete the following information):**
 - OS: MacOS 13.4
 - Browser: Chromium 114.0.5735.110

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 12
 - Browser: Chrome

**Additional context**
Phone tracker (Traccar Client) is not affected. This happens when using Concox/Jimi OB22

**Comment by tananaev** [comment]
Fixed in https://github.com/traccar/traccar-web/commit/0810d3fc2a2fc17131cffb442e7f050467275693.
