### ISSUE TITLE
Commands for protocol gt06 and gator

### ISSUE THREAD

**Issue by seym45** [traccar/traccar#5140]
I am working with devices with protocol gt06 and gator. Need to send command to these devices.

**Comment by tananaev** [comment]
Is this a feature request? Are commands not working? Where's the documentation?

**Comment by seym45** [comment]
It's a feature request. Currently Commands are not supportedfor Gator
protocol.

For gator, custom commands are supported. Need to implement commands like
getDeviceInfo.

By the way, I am planning to commit the required code in the upcoming
weekend.

Documentation are available in traccar website.

https://www.traccar.org/protocol/5052-gator/S208%20S228%20protocolENGLISH-st.doc

**Comment by tananaev** [comment]
OK, if you're interested in sponsoring the work or contributing the change, let us know.
