### ISSUE TITLE
minifinder2, BLE loc don´t work in the preview version

### ISSUE THREAD

**Issue by Nikutrax** [traccar/traccar#5149]
I tested the preview version and found that the BLE location doesn't work it shows zero coordinates.

**Comment by tananaev** [comment]
Please provide a HEX sample and the documentation.

**Comment by Nikutrax** [comment]
Page 16 -BLE Location (0x23)
[Eview Personal Alarm Communication Protocol V20221115.pdf](https://github.com/traccar/traccar/files/12215572/Eview.Personal.Alarm.Communication.Protocol.V20221115.pdf)

**Comment by tananaev** [comment]
OK, just need the sample now.

**Comment by Nikutrax** [comment]
ab1030008b1804010110013836313632393035303139333639310924b148c26408124a5a13269dceb28550ed3921b21ef084980500000000

**Comment by tananaev** [comment]
Which version did it work on?

**Comment by Nikutrax** [comment]
what do you mean?

**Comment by Nikutrax** [comment]
5.6,5,7 and 5.8

**Comment by tananaev** [comment]
Just tested. It's working on the latest master.

**Comment by Nikutrax** [comment]
have you the latest master for me?

**Comment by tananaev** [comment]
Well, it's in this repo.

**Comment by Nikutrax** [comment]
have you a new preview version

**Comment by tananaev** [comment]
https://github.com/traccar/traccar/actions/runs/5726927968
