### ISSUE TITLE
Problem accessing the devices page when I have more than one member.

### ISSUE THREAD

**Issue by hiagodotme** [traccar/traccar#5150]
**Describe the bug**
Problem accessing the devices page when I have more than one member.

```
TypeError: Cannot read properties of undefined (reading 'name')
    at https://mydomain.me/static/js/main.6cd3a572.js:178:558904
    at Array.map ()
    at M$ (https://mydomain.me/static/js/main.6cd3a572.js:178:558753)
    at Mo (https://mydomain.me/static/js/main.6cd3a572.js:2:681543)
    at Ds (https://mydomain.me/static/js/main.6cd3a572.js:2:693231)
    at Ml (https://mydomain.me/static/js/main.6cd3a572.js:2:739539)
    at Sc (https://mydomain.me/static/js/main.6cd3a572.js:2:727762)
    at yc (https://mydomain.me/static/js/main.6cd3a572.js:2:727690)
    at vc (https://mydomain.me/static/js/main.6cd3a572.js:2:727553)
    at oc (https://mydomain.me/static/js/main.6cd3a572.js:2:724333)
```

**To Reproduce**
1. Go to Settings > Users
2. Locate your user and click on the icon to manage connections
3. Under Devices, associate another user's device with the account.
4. Now when going to the Settings > Devices menu the error is displayed.

**Expected behavior**

**Screenshots**
![problema-varios-dispositivos](https://github.com/traccar/traccar/assets/11755715/0fbcf220-7810-4985-b722-cd06cf401b7e)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 115.0.5790.110

**Additional context**
If I only have one device associated with the account, everything works normally. After associating another one, the error is displayed. The error is occurring in traccar version 5.8

**Comment by hiagodotme** [comment]
The problem occurs because in the DevicesPage.js file line 86 it tries to access the name property within a group that was not returned.

Groups Array List:
![Captura de tela 2023-07-31 180334](https://github.com/traccar/traccar/assets/11755715/94c5e86f-2fde-4692-8b69-008394f1b258)

Device Group Id:
![Captura de tela 2023-07-31 180401](https://github.com/traccar/traccar/assets/11755715/2bbc09a5-588e-4dd5-9bde-82934e5d5c6c)

**Comment by tananaev** [comment]
Have you tried the latest master?

**Comment by hiagodotme** [comment]
@tananaev I use the latest version 5.8 available at https://[github.com/traccar/traccar/releases/download/v5.8/traccar-other-5.8.zip](https://github.com/traccar/traccar/releases/download/v5.8/traccar-other-5.8.zip)

**Comment by hiagodotme** [comment]
To solve it I deleted all the groups and directly associated the devices.

**Comment by tananaev** [comment]
I'm pretty sure it's already fixed on master.
