### ISSUE TITLE
R2P tracker - "Device moving" and "Device stopped" events are not fired suddenly 

### ISSUE THREAD

**Issue by sweco-dkson** [traccar/traccar#5151]
**Describe the bug**
When using R2P tracker to send gps data to Traccar,  Traccar stops receiving those events after sometime. 

**Screenshots**
![2023-08-01_08-32-34](https://github.com/traccar/traccar/assets/61972236/9082e731-03a8-454e-aeb2-c2ab943739a7)

**Additional context**
Sorry, I think this is more like a question rather than a bug. 

I have a R2P tracker connects to Traccar through OSMAND protocol. At the first stage, Traccar received the "Device moving" and "Device stopped" quite well. But after sometime, Traccar stops receiving those events and I don't know why.

I will be very appreciated if anyone have idea about this problem. 

Thank you very much!

**Comment by tananaev** [comment]
For questions please use the forum.
