### ISSUE TITLE
Ignore invalid null latitude and longitude

### ISSUE THREAD

**Issue by omogenot** [traccar/traccar#5156]
First of all, congrats for the traccar applications.

**Describe the bug**
For whatever reason, my tracker reports using H02 protocol some positions with latitude and longitude values of 0.
This information is introduced in the database and this creates problems when you try to retrace the device route.

**Expected behavior**
Ignore null latitude and longitude position (the odds that the device is really at position 0,0 are null as well :smile )

I imagine that this is an easy modification...

Let me know if I can help.

**Comment by omogenot** [comment]
Won't that filter be defined and set by default?

**Comment by omogenot** [comment]
I understand, however what are the odds that the reported longitude AND latitude are EXACTLY 0.000000 and 0.000000?

**Comment by tananaev** [comment]
The odds are very good. It's a value that many devices report when they don't have a GPS fix.
