### ISSUE TITLE
Edit option in Legacy mode users dont change email

### ISSUE THREAD

**Issue by mapoloco** [traccar/traccar#5160]
Hi Anton, I talked to you by email. I would like to have in Legacy mode, the same option as in modern mode: 
Let admin to have a check box for users dont change emails.

I have to change to modern view, edit user option to dont let they change their emails, restart server, and again, change to Legacy mode and restart server...

Thank you very much.

**Comment by tananaev** [comment]
If it's a feature request specific to UI, it should be in the web app repo:

https://github.com/traccar/traccar-web

Are you interesting in sponsoring the work or implementing it yourself?
