### ISSUE TITLE
Speed Limit Threshold parameter

### ISSUE THREAD

**Issue by RB-NZ-1974** [traccar/traccar#5161]
When using speed limit provider, such as Overpass, we may want to allow some variance in the overspeed calculation. Can you add another variable into the code/config to allow for a threshold.

For example, if we are ok with users 5% over the posted speed limit.;
 <entry key='speedLimit.threshold'>1.05</entry>

**Comment by tananaev** [comment]
I think it might make sense for all speed limits. What do you think?

**Comment by RB-NZ-1974** [comment]
I have set my legacy system wide Speed limit to 105km/h which is the legal open road limit in NZ of 100km/h + 5%. 
So if you want to make it applicable system wide and tell users to setup their  legacy limits and then apply a threshold to all, then yeah thats fine. I guess thats up to you to determine how you want to implement it, by adding it into the speedlimit provider lookup calculation only, or the OverspeedProcessor. Im supportive of either

**Comment by tananaev** [comment]
100 is an easy example. What if you have 35 mph limit and need to add 5%? It won't be a nice round number 😁

As for applying it to existing users, we'll just have zero by default, so it won't break existing usage.

**Comment by RB-NZ-1974** [comment]
Sounds good to me. 

100 is always an easy number to work with :)
