### ISSUE TITLE
 Feature request: Exporting device list

### ISSUE THREAD

**Issue by hypoclone** [traccar/traccar#5163]
**Is your feature request related to a problem? Please describe.**
Right now there is no way to generate a spreadsheet of the list of all devices you have on traccar, for example in a situation where you need to generate all the phone numbers and identifiers of all devices so as to subscribe data on them, it is difficult if you don't already maintain a list of all your devices monthly.

**Describe the solution you'd like**
Ability to export an excel file containing list of all devices under Devices in Setting, just as shown below
![Traccar request](https://github.com/traccar/traccar/assets/992984/b67e609d-7698-41be-9caf-c3c80bc38ccb)

**Comment by 0xenca** [comment]
This should be implemented

**Comment by tananaev** [comment]
@0xenca we're all waiting for a PR from you.

**Comment by maltegrosse** [comment]
just use the API, which returns a json with all necessary information :)

**Comment by hypoclone** [comment]
Closed because the feature has been implemented, Thank you.
