### ISSUE TITLE
language in Version 5.9 by last online in device list is only in english

### ISSUE THREAD

**Issue by Nikutrax** [traccar/traccar#5166]
the language in last online by device list is only in english
example last online 12 minutes ago instead of "vor 12 Minuten" in german language

Traccar Version 5.9 by 5.8 Version was it right

**Comment by tananaev** [comment]
Fixed by https://github.com/traccar/traccar-web/commit/9a59d6524c45d5542433302a498f9ada4e45e806.

**Comment by HenrickLangner** [comment]
sorry, but would you mind to tell me how to fix this problem in easy words? I do not know how to use the informations following the link...
thanks!

**Comment by geduxas** [comment]
It will appere in new release, or you should compile it from source.
