### ISSUE TITLE
Token auth for websocket API

### ISSUE THREAD

**Issue by AndreKR** [traccar/traccar#5168]
**Is your feature request related to a problem? Please describe.**
The need to create a session cookie to access the web socket API makes it hard to use the websocket API in machine-to-machine applications, because a lot of clients (e.g. Node-RED) and reverse proxies (e.g. Caddy, nginx) cannot perform the required HTTP call to `/api/session` to obtain the cookie.

**Describe the solution you'd like**
I'd like the Websocket API (i.e. the `/api/socket` endpoint) to accept a user token for authentication.

As a standards compliant way, the user token can be provided in the `Authorization: Bearer ...` header.

The token could also be provided as part of the URL (`/api/socket?token=...`). This would be slightly unorthodox, but it would make it easier to work with clients that cannot send headers (like Node-RED at the moment).

HTTP basic auth with username and password would be another useful option.

**Describe alternatives you've considered**
At the moment I'm creating a session and then I put the session cookie value into my reverse proxy configuration and hope that the session doesn't time out too often.

**Comment by tananaev** [comment]
You can set the session timeout.

**Comment by michaelsantosidealnet** [comment]
If this option was implemented, it would be great! Many times it is quite limited for us to create or pass information to Traccar because the creation of the Token is not configured to be created from outside in the case of a JWT, Websocket, etc...

In a laravel application I always have a bigger job of authenticating in Traccar and also in my laravel application. If the API had the option to integrate to create and send the token, it would be wonderful.

**Comment by salluspeaks** [comment]
@tananaev any reason why websocket is protected only by Session cookie and not with tokens? Shall into it and pick this up?

**Comment by tananaev** [comment]
If you want to take it on, feel free. I think there's a technical limitation, so it might not be easy to do.

**Comment by MuadDibVV** [comment]
Hello,
I understand that token is usable with websocket since release 6.2 ("Support token authentication for WebSocket").
I haven't seen any documentation; is anyone know how we could use it ?
(I also use NodeRed)
Thanks

**Comment by tananaev** [comment]
You just add it as a query parameter:
```
/api/socket?token=...
```

**Comment by AndreKR** [comment]
Oh, so this got implemented? 😮 Shall we close the issue?
