### ISSUE TITLE
gps103 protocol changing GPRS time sent by device

### ISSUE THREAD

**Issue by hackerunet** [traccar/traccar#517]
Hi anton, I have a huge problem with traccar, my devices are sending this string as time 1416011324 which would be January 16  2014 13:24 hrs, and I'm getting inside the database the current database time instead, which is 17:34.
I already check the logs and traccar shows 17:34 and my TCP TEST TOOL is showing me that the device time is 13:24

What is going on with it?

**Comment by lukney** [comment]
Hai,iam new to this gps tracking project.
this is my code..
var gps = require("gps-tracking");
 
var options = {
    'debug'                 : false,
    'port'                  : 8090,
    "device_adapter": require("./my_custom_adapter")
}
 
var server = gps.server(options,function(device,connection){
    /*  Available device variables:
        ----------------------------
        device.uid -> is setted when the first packet is parsed
        device.name -> you can set a custon name for this device.
        device.ip -> ip of the device
        device.port --> device port
    */
    
    /******************************
    LOGIN
    ******************************/
    device.on("login_request",function(device_id,msg_parts){
        //Do some stuff before authenticate the device...  
        
        this.login_authorized(true); //Accept the login request. 
    });
    device.on("login",function(){
        //this = device 
        console.log("Hi! i'm "+this.uid);
    });
    device.on("login_rejected",function(){
    
    });
    
    
    /******************************
    PING - When the gps sends their position  
    ******************************/
    device.on("ping",function(data){
        //After the ping is received 
        //console.log(data); 
        console.log("I'm here now: "+gps_data.latitude+", "+gps_data.longitude+"");
        return data;
    });
    
    
    /******************************
    ALARM - When the gps sends and alarm  
    ******************************/
    device.on("alarm",function(alarm_code,alarm_data,msg_data){
        console.log("Help! Something happend: "+alarm_code+" ("+alarm_data.msg+")");
        call_me();
    }); 
    
    
   
    /******************************
    MISC 
    ******************************/
   
    device.on("handshake",function(){
        
    });
    
});
If do this is iam directly connect device..
