### ISSUE TITLE
background app stops receiving positions

### ISSUE THREAD

**Issue by jdrr2590** [traccar/traccar#5170]
the problem occurs when the smartphone lost connection will the app is in background, for example you could open the app, put it on the Background and change connection from wifi o 4g wait for a moment an reopen the app from the background, the data won't be fetched until you restart the app. the problem occurs on both iphone and android

**Comment by tananaev** [comment]
Which app?

**Comment by jdrr2590** [comment]
TRACCAR MANAGER

**Comment by tananaev** [comment]
Then this is the wrong place for this ticket.
