### ISSUE TITLE
Overpass Speed lookup accuracy

### ISSUE THREAD

**Issue by RB-NZ-1974** [traccar/traccar#5175]
**Is your feature request related to a problem? Please describe.**
The current Overpass speed API call is using "around:100.0" which can return several way points with varying speed limits posted.
e.g., `https://overpass-api.de/api/interpreter?data=[out:json];way[maxspeed](around:100.0,-36.860069,174.755718);out%20tags;`
How is Traccar interpreting this when several ways/speed limits are found? I'm not sure if Traccar is taking the lowest value returned, or just the first value?
When I enable the speed alerts this is causing a large number of false positives in examples where users are driving on a motorway with a parallel side road with a lower speed limit, driving along a main road with a T intersection and the side road has a lower speed limit.
If the parameter is changed to around:10.0 in the above example only 1 way result is returned with the correct value.

**Describe the solution you'd like**
Can we have another config parameter for 'event.overspeed.accuracy'? 100 can be default, but can change to other values as required.
Would it also be helpful to have another parameter to define the behavior of using highest or lowest speed limit if several are found?

Thanks.

**Comment by tananaev** [comment]
We take the first element, as far as I remember.

What does that parameter mean? Do you the overpass documentation?

**Comment by RB-NZ-1974** [comment]
Extract from the Overpass documentation; https://dev.overpass-api.de/overpass-doc/en/full_data/polygon.html
"Filter Around Absolute Coordinates
It can be searched not only around the given objects, but also around the given coordinates. 
This query selects all objects into the set that have to the given coordinate a distance of at most 100 meters."

**Comment by tananaev** [comment]
Is there a way to sort the result to get the closest one first? I think that would be the best option.

**Comment by RB-NZ-1974** [comment]
I dont beleive theres any other function in Overpass. In the example I gave, the correct road is OpenStreetMaps WAY#154101740, and is the 5th entry received in the XML Looking at all 9 entries in the XML, it appears that Overpass generates the file from north to south within the file, meaning the correct WAY is going to always be the middle one.
100m is a very large radius considering the most devices should return accuracy within 5-10m.
