### ISSUE TITLE
401 when removing user in Users section

### ISSUE THREAD

**Issue by zRickz** [traccar/traccar#5183]
Hello! 
I'm getting the 401 error when I remove a user through the settings in the users section... Having to log in again, is there any way to prevent this from happening?

**Comment by tananaev** [comment]
Did you remove yourself? 🤣

**Comment by zRickz** [comment]
No! 🤣
I thought it could be this too, but I made sure by creating another user and deleting it...
I think I found my solution, the code in the backend(https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/api/resource/UserResource.java LINE 125, if i'm right...) resets the session when DELETE is requested. I'll test it tomorrow to confirm my theory and I'll come back here with the answers, thanks for the support in any way and sorry for the inconvenience! If I need you again, I'll call you here tomorrow.

**Comment by tananaev** [comment]
Turns out we really had an issue with users API. Good catch. Thank you for reporting it.
