### ISSUE TITLE
Error: Unexpected server response: 503 Service Unavailable

### ISSUE THREAD

**Issue by victorang1** [traccar/traccar#5188]
Im trying to connect to the traccar websocket, 
i have already get the session id with `api/session` with sample url like this http://domain:82/api/session and get the `JSESSIONID`. 

After that im using postman to connect to the traccar websocket like this
url: `ws://domain:82/api/socket`
headers ->
Cookie: {JSESSIONID value get from `api/session`}

The postman giving **`Error: Unexpected server response: 503`** this error.

What am i doing wrong? Thanks

**Comment by tananaev** [comment]
For questions you should use the forum instead.
