### ISSUE TITLE
OpenIdConnect: Signature Encoding Error with Keycloak v22

### ISSUE THREAD

**Issue by Tsegmid** [traccar/traccar#5189]
I encounter a signature encoding error when attempting to access the backend using a bearer token. By default, Keycloak uses the RS256 Signature Algorithm, while Traccar's backend employs SHA256withECDSA.

I attempted to resolve this by:

Modifying the backend code to use SHA256withRSA
Adjusting Keycloak’s algorithm to ES256
However, the signature encoding error persists in both cases.

Any guidance on resolving this issue would be appreciated.

"signature length not correct: got 123 but was expecting 128 - signatureexception"

similar to this error
https://stackoverflow.com/questions/46225417/rsa-signatureexception-signature-length-not-correct

**Comment by tananaev** [comment]
Sorry, but where are we using "SHA256withECDSA" for OpenID?

**Comment by Tsegmid** [comment]
https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/api/signature/CryptoManager.java

on line 54 
Signature signature = Signature.getInstance("SHA256withECDSA");

Sorry if my explanation was not clear enough.

I already did connect traccar server to keycloak with openId, modern frontend can login and get cookie just fine now.
However, i have other services that also utilize Keycloak tokens. When I attempt to call one of Traccar's APIs using a bearer token from Keycloak, I receive a 401 error.

Is this a completely new use case?

**Comment by tananaev** [comment]
`CryptoManager` has absolutely nothing to do with OpenID.
