### ISSUE TITLE
TLT2H 4-digit battery voltage

### ISSUE THREAD

**Issue by TazerReloaded** [traccar/traccar#5197]
**Describe the bug**
The newest firmware versions of the MT700 from Mictrack transmit a 4-digit battery voltage.
Although the parser should be able to parse this number, the result is not displayed in the UI.
The factor als needs to change for 4-digit numbers, it's 1000 instead of 10.

**To Reproduce**
1. Connect a MT700 with a production date after 2023-05-01
2. Go to the "details" page of the device
3. Attribute "battery" is missing

**Expected behavior**
The battery attribute should be present and show the battery voltage like for older firmware versions.

**Additional context**
Sample packet hex:
```
23383637363635303431363839343835234d543730304e233030303023485423310a2335303635244750524d432c3134383939362e30302c412c323438352e323435382c4e2c30313235382e343533352c452c2c2c3135313334382c2c2c412a35440a2323
```
Sample packet decoded:
```
#867665041689485#MT700N#0000#HT#1
#5065$GPRMC,148996.00,A,2485.2458,N,01258.4535,E,,,151348,,,A*5D
##
```

Battery voltage is at the start of line 2: 5065 (5.065V)
I changed a few digits to hide my location, checksum will not match!

**Comment by tananaev** [comment]
Please provide the protocol documentation.

**Comment by TazerReloaded** [comment]
Thank you for the quick reply!
The protocol documentation can be found here:
https://www.mictrack.com/downloads/protocols/Mictrack_Communication_Protocol_For_MT700_V1.0.pdf

The change for battery voltage representation is not documented yet, but I have 2 MT700 that use the 4-digit variant since firmware 2.0.8, which was released 2023-05-05.

**Comment by tananaev** [comment]
If it's not documented, we probably need to wait for the updated documentation first.

**Comment by TazerReloaded** [comment]
I asked the manufacturer, they sent me a link to the updated documentation:
https://help.mictrack.com/articles/how-to-calculate-battery-voltage-into-percentage-for-mictrack-devices/

The 4-digit seems to only affect some versions, quote from our conversation:
> Because the voltage range for the rechargeable battery (3.3-4.2V) is different from the non-rechargeable battery (1.2-1.5V).
> So we have already updated the firmware for the MT700-N/MT700-NW to report the backup battery with 4 digits.

**Comment by tananaev** [comment]
That's just a mapping from voltage to percentage for different device types.

**Comment by TazerReloaded** [comment]
The manufacturer updated the documentation yesterday:
https://www.mictrack.com/downloads/protocols/Mictrack_Communication_Protocol_For_MT700_V1.0.pdf

It now contains the updated battery voltage specification.
