### ISSUE TITLE
geofences api is not responding 

### ISSUE THREAD

**Issue by amitnextgen** [traccar/traccar#5198]
1. When  I hit geofences api 1000 time in a sec
![Screenshot 2023-10-20 182158](https://github.com/traccar/traccar/assets/127732060/14928795-2a53-436a-9b15-89f66a0c6965)
ond then api is not responding  on chrome

**Comment by tananaev** [comment]
I think you forgot to provide some context.

**Comment by amitnextgen** [comment]
Hi @tananaev when I hit any api less than 100 time on load testing it is working but when I hit more than 1000 time it is showing failed.

**Comment by amitnextgen** [comment]
I have a kml file and after parsing kml file I got 1000 geo points and so thats why I am hitting geofences api 1000 time

**Comment by geduxas** [comment]
> I have a kml file and after parsing kml file I got 1000 geo points and so thats why I am hitting geofences api 1000 time

Refere to log files, it's seam's you're running out of resources.

**Comment by amitnextgen** [comment]
Hi @geduxas  I am running this project on my local machine and I am using Mysql database .
I have to send 1000 request at at time can you suggest me how to handle this issue ?
![logs](https://github.com/traccar/traccar/assets/127732060/615f13bc-27b8-4cf1-b049-beb8eac8a208)
![jmetelogs](https://github.com/traccar/traccar/assets/127732060/46393c5a-a850-4a9c-9ab2-4adef28f0969)

**Comment by geduxas** [comment]
Read traccar log file

**Comment by amitnextgen** [comment]
When i hit api logs are 

![errorLogs](https://github.com/traccar/traccar/assets/127732060/749a1c48-136a-4d13-a244-ed2a99c123a9)

**Comment by geduxas** [comment]
> When i hit api logs are
> 
> ![errorLogs](https://user-images.githubusercontent.com/127732060/277285565-749a1c48-136a-4d13-a244-ed2a99c123a9.png)

It's too late, need start of problem i still think you're out of resources..

**Comment by amitnextgen** [comment]
> > When i hit api logs are
> > ![errorLogs](https://user-images.githubusercontent.com/127732060/277285565-749a1c48-136a-4d13-a244-ed2a99c123a9.png)
> 
> It's too late, need start of problem i still think you're out of resources..

Can you suggest me how to manage resource for this ?

**Comment by geduxas** [comment]
first you need find root of problem. in screenshot i see only consequences after it failing.. first line of error's might point to problem. Also it could lead to too low memory, or calculation timeout's

**Comment by amitnextgen** [comment]
> first you need find root of problem. in screenshot i see only consequences after it failing.. first line of error's might point to problem. Also it could lead to too low memory, or calculation timeout's

first line of the error  is "error has occurred while writing a response message entity to the container output stream. - An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full - IOException (... < OverrideFilter:56 < ...)"

how to handle this problem ?
