### ISSUE TITLE
Topin LBS packet parsing

### ISSUE THREAD

**Issue by FoxExe** [traccar/traccar#5200]
I have a "**ZX905**" gps tracker (4G/LTE/GPS/LBS. Based on Quectel EC800N-CN). Seems like it works with "Topin" protocol.
It can send data about surrounding base (mobile) stations.
As far as I understand, Traccar supports location determination by cell towers, but this protocol does not have the necessary functionality.
I was able to partially disassemble these packages and I ask you to add their parsing to the server (in the "Topin" protocol)

**Example packet:**
`7878081a231024143712a439b373813c33c0252fa72eaa3afef5c4ab2ba15108c6b333865c5450d4f78e17d05650642b77c2ef5a7062b8ceab8c5b12521ce1bcca5b0300fa0200001d240b4bc7016d00001d240b4bc7016d00001d240b4bc7016d000d0a`

**Parsed to blocks:**
`7878 08 1a 23.10.24-14:37:12 a439b373813c-33 c0252fa72eaa-3a fef5c4ab2ba1-51 08c6b333865c-54 50d4f78e17d0-56 50642b77c2ef-5a 7062b8ceab8c-5b 12521ce1bcca-5b 0300fa0200 001d240b4bc7016d00 001d240b4bc7016d00 001d240b4bc7016d0 00d0a`

`0x08` - Count of base stations info in this package (Not size of package)
`0x1a` or `0x1b` - packet type (its same)
`231024143712` - date and time "as is" in UTC format `%y%m%d%H%M%S` = `23.10.24 14:37:12`
`7062b8ceab8c-5b` - WiFi MAC Address and signal strength.
`03-00-fa-02-00` - 5 bytes of current network info. `0x03` - LCID, `0xFA` + `0x02` = 25002 (Russia / Megafon). Other bytes - unknown :(
`00-1d24-0b4bc7-01-6d-00` - Three identical blocks of current station info (big-endian int's): [`unknown` - `TAC` - `eNB` - `TA` - `RSRQ` - `unknown`]

More example packets:

- `7878001b2308310804210300fa0200001d240b4bc7017b00001d240b4bc7017b00001d240b4bc7017b000d0a`
- `7878001b2310241924070300fa0200001d240b4bc7016f00001d240b4bc7016f00001d240b4bc7016f000d0a`
- `7878001a2310241925130300fa0200001d240b4bc7017000001d240b4bc7017000001d240b4bc70170000d0a`
- `7878061a23091609392608c6b33347785254c2509ada515840313c0ee3bd5bcc32e582a8f85c50ff201399b35d1c3bf327ae865f0300fa0200001d240b4bba017500001d240b4bba017500001d240b4bba0175000d0a`
- `7878061b231024161223a439b373813c33fef5c4ab2ba14d08c6b333865c5312521ce1bcca5412521ce1aa7d5c58d56eba74555c0300fa0200001d240b4bc7016a00001d240b4bc7016a00001d240b4bc7016a000d0a`
- `7878081a231024161241a439b373813c33fef5c4ab2ba14d12521ce1bcca5508c6b333865c5550d4f78e17d0557062b8ceab8c5858d56eba74555ab0a7b993bb0c5d0300fa0200001d240b4bc7016700001d240b4bc7016700001d240b4bc70167000d0a`
- `7878081b231024161241a439b373813c33fef5c4ab2ba14d12521ce1bcca5508c6b333865c5550d4f78e17d0557062b8ceab8c5858d56eba74555ab0a7b993bb0c5d0300fa0200001d240b4bc7016700001d240b4bc7016700001d240b4bc70167000d0a`

**Comment by tananaev** [comment]
Do you have the protocol documentation?

**Comment by FoxExe** [comment]
Nope :(

**Comment by tananaev** [comment]
What is not working exactly?

**Comment by FoxExe** [comment]
The tracker supports determination by base stations. Traccar, how much I understood - too.
But I did not find a protocol in which this function is implemented.

The tracker works in GPS mode, but all its data related to LBS - Traccar simply ignores.

**Comment by tananaev** [comment]
There are many protocols that support it, including Topin. What makes you think Traccar is ignoring it? Have you checked the decoded data? Have you enabled geolocation?

**Comment by FoxExe** [comment]
![image](https://github.com/traccar/traccar/assets/3135063/bcb11957-eed5-4081-a3d4-680903ac23b7)
There is no answer in logs.
In [TopinProtocolDecoder.java](https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/protocol/TopinProtocolDecoder.java) no parsing for `0x1a`/`0x1b` (But 0x1a mapped to `MSG_LBS_WIFI_2`)

in my `conf/traccar.xml` i added:
```xml
    <entry key='geolocation.enable'>true</entry>
    <entry key='geolocation.type'>google</entry>
    <entry key='geolocation.key'>[API_KEY]</entry>

```

**Comment by FoxExe** [comment]
Oh, my mistake - i read old code.
In new code need add `public static final int MSG_LBS_WIFI_3 = 0x1B;` (Or rename to WIFI_A/WIFI_B?)
And add this var to line 225 (in `decode()` function)

But still not show coordinates on map when GPS is not available.
How to debug geolocation calls? What did i miss?

**Comment by tananaev** [comment]
I'm not sure what you're missing, but on the protocol level it is supported.
