### ISSUE TITLE
More Alarm Bits for Fifotrack Protocol

### ISSUE THREAD

**Issue by Nikutrax** [traccar/traccar#5206]
At the moment there are only the following alarm bits

![fifotrack_alarm_decode](https://github.com/traccar/traccar/assets/112165998/09f020a9-4720-4792-aead-61ce1cdc9c1e)

It is possible to implement the other Bits ?
22 - No Movement Alarm
25 - Tilt/Man Down
31 - Fall Down

on Page 30 are all codes!

[fifotrack Q3 Command List V1.6.pdf](https://github.com/traccar/traccar/files/13297962/fifotrack.Q3.Command.List.V1.6.pdf)

Thanks for your response

**Comment by tananaev** [comment]
We would need the full protocol documentation.

**Comment by Nikutrax** [comment]
on page 30 are all alarms

**Comment by Nikutrax** [comment]
[fifotrack A03 GPRS Protocol.pdf](https://github.com/traccar/traccar/files/13298074/fifotrack.A03.GPRS.Protocol.pdf)

**Comment by tananaev** [comment]
I don't see it in the protocol documentation. Why are they different?

**Comment by Nikutrax** [comment]
but in command list  v 1.6 on page 30

**Comment by tananaev** [comment]
I don't think that's an answer to my question.

**Comment by Nikutrax** [comment]
I don't know, but there are only three bits missing!

case 22:
   return Position.ALARM_NO_Movement; like this or so
case 25:
  return Position.ALARM_TILT; like this or so
case 31:
  return Position.ALARM_FALL_DOWN;

**Comment by tananaev** [comment]
OK, once you have an answer from the vendor, let us know.

**Comment by Nikutrax** [comment]
I contacted the manufacturer and asked, as soon as I have an answer I will pass it on.
Nevertheless, you can see on page 30 which alarms are triggered with which bit!

**Comment by Nikutrax** [comment]
Here are the Protocol
[fifotrack A03 GPRS Protocol.pdf](https://github.com/traccar/traccar/files/13305153/fifotrack.A03.GPRS.Protocol.pdf)

**Comment by tananaev** [comment]
Added "fall down" code here https://github.com/traccar/traccar/commit/d57af42117c98a0c52d9bd776aa8d24af2dfafeb. Others we don't really have standard alarms for.

**Comment by Nikutrax** [comment]
<p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; font-family: DengXian; margin: 0cm; text-align: justify; font-size: 10.5pt; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(23, 54, 93);">We attached the protocol file for your reference. The last page is full alarm code list.</span></p><p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; font-family: DengXian; margin: 0cm; text-align: justify; font-size: 10.5pt; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(23, 54, 93);">Now below alarm codes are not integrated, could you manage to add them? Thanks.   </span></p><p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; font-family: DengXian; margin: 0cm; text-align: justify; font-size: 10.5pt; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><span style="font-size: 11pt; font-family: Calibri, sans-serif; color: rgb(23, 54, 93);"> </span></p>

22 | GPRS | No Movement Alarm | No Movement
-- | -- | -- | --
25 | GPRS | Tilt/Man Down | Tilt
53 | GPRS | Device Power ON | Power ON
54 | GPRS | Device Power OFF | Power OFF
55 | GPRS | Charging ON | Charging ON
56 | GPRS | Charging OFF | Charging

[fifotrack A03 GPRS Protocol.pdf](https://github.com/traccar/traccar/files/13315971/fifotrack.A03.GPRS.Protocol.pdf)

**Comment by Nikutrax** [comment]
Are follow Bits are passible, too:

case 22:
                    return Position.ALARM_NO_MOVEMENT;  - like this  or ALARM_MOVEMENT, false;
case 53:
                    return Position.ALARM_POWER_ON;  - like this
case 54:
                    return Position.ALARM_POWER_OFF;  - like this
case 55:
                    return Position.KEY_CHARGE, true;   - like this
case 56:
                    return Position.KEY_CHARGE, false;   - like this

**Comment by tananaev** [comment]
Only 53 and 54 make sense.

**Comment by Nikutrax** [comment]
"I don't understand why the movement and charging don't make sense. Money was paid to implement the protocol, and yet you repeatedly say it doesn't make sense. I find this unfortunate, especially since we practically provided you with the solution!"

**Comment by tananaev** [comment]
They don't make sense because such alarms don't exist in Traccar. If you paid us for some implementation and thing this was missed, you have continue the discussion on the relevant email thread instead.

**Comment by Nikutrax** [comment]
Power on and power off are aviable in traccar and charge too

**Comment by Nikutrax** [comment]
I apologize; the translation program wrote so aggressively. - Sorry

**Comment by Nikutrax** [comment]
> Only 53 and 54 make sense.

It is possible to intergrade this?
