### ISSUE TITLE
traccar features

### ISSUE THREAD

**Issue by Juan-Facundo** [traccar/traccar#521]
Hi, i am really new at traccar. I wonder if it has features such as evens at overspeed or event like zone-in zone-out, etc... I couldn't find them.

Thanks.

**Comment by addonravi** [comment]
Hi, To all
Can any one know me, is that any  queue implementation in traccar for handle device listener data ?

**Comment by tananaev** [comment]
What do you mean by queue?

**Comment by addonravi** [comment]
means storing temporary data and  retrieving data of device.

**Comment by addonravi** [comment]
like message queue,priority queue used for storing and retrieving data.

**Comment by tananaev** [comment]
It's all handled automatically by Netty library.

**Comment by addonravi** [comment]
Thank you very much.
