### ISSUE TITLE
feature request: don't store positions after X days

### ISSUE THREAD

**Issue by gpedro** [traccar/traccar#5212]
**Describe the solution you'd like**
i don't want to store a whole positions for ever, because the database can be get a huge size. my suggestion is a scheduler to cleanup old positions/events after X days.

**Comment by tananaev** [comment]
It can be easily configured outside of Traccar:

https://www.traccar.org/clear-history/

There's no plan to implement it in Traccar itself.

**Comment by gpedro** [comment]
sorry about that. I didn't found that link on the docs.
