### ISSUE TITLE
Position forwarding (with REDIS) in 5.9. not working

### ISSUE THREAD

**Issue by joerg-walter-de** [traccar/traccar#5213]
debug output from PositionForwardingHandler.handlePosition() shows that positionForwarder is null

```
    @Override
    protected Position handlePosition(Position position) {
        if (positionForwarder != null) {
            PositionData positionData = new PositionData();
            positionData.setPosition(position);
            positionData.setDevice(cacheManager.getObject(Device.class, position.getDeviceId()));
            new AsyncRequestAndCallback(positionData).send();
        }
        return position;
    }
```

When I look for creations of position forwarders I find this one location in MainModule.providePositionForwarder()
![image](https://github.com/traccar/traccar/assets/33499391/d62dfd8e-9af2-4fcd-abe9-6dbdc1b0b76c)

which in turn is not called anywhere:

![image](https://github.com/traccar/traccar/assets/33499391/18f69784-73de-4859-8716-37cb14376629)

How is this meant to work?

**Comment by tananaev** [comment]
For questions you should use the forum instead.
