### ISSUE TITLE
Kafka forwarder: position id always zero

### ISSUE THREAD

**Issue by gpedro** [traccar/traccar#5214]
**Describe the bug**
<img width="673" alt="Captura de Tela 2023-11-14 às 08 17 17" src="https://github.com/traccar/traccar/assets/2898638/eb3589a8-0870-43e3-8abf-752084ba73cb">

**To Reproduce**
1. Set up Kafka
2. Set up Kafka UI
3. Set up Traccar Kafka Forwarder
4. Wait for Position
5. Check Kafka UI

**Expected behavior**
real position id

**Comment by tananaev** [comment]
That is expected. Filtering is happening before we store positions in the database.

**Comment by gpedro** [comment]
any chance to that be parametrized ?

**Comment by tananaev** [comment]
No, it's can't be parametrized currently.
