### ISSUE TITLE
Notification suppression for data records with fix time in the past

### ISSUE THREAD

**Issue by victor-butler** [traccar/traccar#5217]
**Is your feature request related to a problem? Please describe.**
Not a problem but an improvement in user experience.

**Describe the solution you'd like**
Add an option to suppress notification sending if the record fix time is greater than some specified amount of time.

**Use case**
Device has no mobile connection and saves Ignition on event on its internal memory. After 5 hours, mobile connection is restored and the device sends all cached data. With current setup, the user will receive a notification for Ignition on when in fact his vehicle might be parked already. Currently, a notification like that will only cause a confusion so it's better to be filtered.

**Simpler solution**
Add a configuration option to enable notification suppression for **all** notifications if the record fix time is greater than X. X can be a configurable time duration like 10 min or 2 hours. 
This will basically stop all notifications if the fix time is too old.

**Optimal solution**
Add a configuration option to enable notification suppression **per notification** if the record fix time is greater than X. X can be a configurable time duration like 10 min or 2 hours and can be different for each notification type. 
In this case, the admin will be able to suppress only certain notifications that wouldn't make sense to send if the event was in the past, e.g. Ignition start and in the same time will allow sending for other notifications that would be good to have, e.g. Power cut.

**Comment by iceberg1369** [comment]
This is a really imporant issue
