### ISSUE TITLE
Samsung Galaxy Watch6 LTE - WearOS - Working but the app closes by itself

### ISSUE THREAD

**Issue by Micboule** [traccar/traccar#5227]
Hi, 

The org.traccar.client is able to be installed on WearOS - Watch6 Samsung. 
It does install successfully via ADB and the tracking works until the Traccar Client app ask to disable the Battery Optimization which that feature dont exist on the watch. 

Is there a way to remove that request of disabling battery optimization from the Traccar Client App?

**Comment by tananaev** [comment]
We don't officially support WearOS currently.

What is the exception though?

**Comment by Micboule** [comment]
Hi, Thanks for the reply!

I'm a runner, I like to run. I bought this watch for the main purpose of listening Audible while I run. Also, listening to music Radio from the LTE. And I can also call and text in case I need help during a run.

There is some other software that can do that, but I currently use Traccar and I like it.

I have Traccar on multiple devices and I thought that it would be nice to have it work on a watch for the purpose of letting know the family/friends where I am while I'm out there in case of help or meet somewhere.

The software org.traccar.client really working on WearOS right now, it's just the popup of battery optimization that make the app to close because of not responding. 

The ID is also set on the Traccar server and I receive coordinations.  As soon as I put the server link address and I click on the button to start the tracking, I receive data in Traccar server but not for long because of the popup msg I'm talking about that closes the app.

Thanks @tananaev

**Comment by Micboule** [comment]
Hi @tananaev 
Not sure if it is what you were asking for... but I have a logcat file which I get the crash message in txt file from traccar:
  At startup of the watch:

--------- beginning of crash
11-30 07:33:03.733  3655  3655 E AndroidRuntime: FATAL EXCEPTION: main
11-30 07:33:03.733  3655  3655 E AndroidRuntime: Process: org.traccar.client, PID: 3655
11-30 07:33:03.733  3655  3655 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver org.traccar.client.StatusWidget: java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.appwidget.AppWidgetManager.getAppWidgetIds(android.content.ComponentName)' on a null object reference
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4364)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2173)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7962)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.appwidget.AppWidgetManager.getAppWidgetIds(android.content.ComponentName)' on a null object reference
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at org.traccar.client.StatusWidget.updateWidgets(StatusWidget.kt:47)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at org.traccar.client.StatusWidget.onReceive(StatusWidget.kt:32)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4355)
11-30 07:33:03.733  3655  3655 E AndroidRuntime: 	... 9 more

I have for 18mb of data in that txt file. Any specific thing you want to me to paste to you? 

Thanks again for replying and your interest.

**Comment by Micboule** [comment]
[log.txt](https://github.com/traccar/traccar/files/13516183/log.txt)

**Comment by tananaev** [comment]
Actually looks like you're asking in the wrong repository.

And also the error seems to be related to the widget and has nothing to do with battery optimization. It's related to this: https://github.com/traccar/traccar-client-android/pull/431.

**Comment by Micboule** [comment]
@tananaev

The link you are giving to me, is it th solution? Is it something I can do to make it work or not?

Thanks,

**Comment by tananaev** [comment]
No, it's probably the source of the problem.
