### ISSUE TITLE
Trojan horse

### ISSUE THREAD

**Issue by jcomey** [traccar/traccar#5229]
**Is your feature request related to a problem? Please describe.**
![QQ截图20231201084117](https://github.com/traccar/traccar/assets/1287894/316fd35c-bcd6-4938-acad-f5892ee42c2e)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tananaev** [comment]
Closing because:
1. Unclear description
2. Wrong repository
3. The only provided information is a screenshot without any translation
4. No description or any other details
