### ISSUE TITLE
Reports "Group" filter not refreshed between different users login within same browser session.

### ISSUE THREAD

**Issue by RB-NZ-1974** [traccar/traccar#5232]
If you login as a user who can see all the groups on the server and run a report that support groups (combined and summary), then logout and login as a user who can only one group and go back a report that support groups (combined and summary) you still see all the groups. 
But if you close the browser between logins then the groups are filtered correctly. 
To be clear, it doesnt display any data from those groups to that user, its only the issue of exposing the existence other groups to that user.

**Comment by tananaev** [comment]
Fixed in https://github.com/traccar/traccar-web/commit/7d607dbc8f2f5636dd1319ff018add3265c923aa.
