### ISSUE TITLE
No IPv6 Support in Docker image

### ISSUE THREAD

**Issue by JuniperChris929** [traccar/traccar#5239]
**Describe the bug**
The latest Docker image does NOT run traccar with IPv6, therefore rendering it useless in modern environments (which are obviously IPv6-only)

**To Reproduce**
fetch the latest alpine / ubuntu / debian docker hub image
go into the container
run "netstat -tulpn" - you will see, that the only listener is purely IPv4...

**Expected behavior**
Should at least run dual-stack but better just IPv6 to limit the attack scope

**Additional context**
Why is this a thing in 2023 (almost 2024)???????

**Comment by tananaev** [comment]
The right place to ask would probably be here:

https://github.com/traccar/traccar-docker
