### ISSUE TITLE
HTTP 401 Unauthorized - WebApplicationException (SecurityRequestFilter:128 < ... < OverrideFilter:49 < ...)

### ISSUE THREAD

**Issue by PiSchleuder** [traccar/traccar#5242]
**Describe the bug**
Installation is working without any problems, but after registration and logging in the error appears.
After that, no entries can be saved. Installation was carried out on a Raspberry Pi 4 with Raspian OS for IoBroker
(Bookworm).

**Screenshots**
![Screenshot 2024-01-09 23 00 13](https://github.com/traccar/traccar/assets/103071036/10a526d5-59d0-4e25-a35c-fe10468e7cd4)

**Desktop (please complete the following information):**
 - OS: Chromeos
 - Browser chrome
 - Version: Version 120.0.6099.186

**Additional context**
The same behavior occurs when I install the server as docker on a synology (DSM 7)

Any hint ?

**Comment by tananaev** [comment]
The error just means that you're not authenticated for some reason. Before submitting a bug we need to figure out whether it's a bug in Traccar or not. I'm going to close it for now. You should probably start a thread on the forum instead.
