### ISSUE TITLE
Blank page (web & app) after updating the server - requires deletion of cookies

### ISSUE THREAD

**Issue by btgitcat** [traccar/traccar#5246]
Today I updated from 5.9 to 5.11 and was then greeted by a blank page.
This behavior was seen on all devices with which I was logged in to Traccar before I updated the server. I use Traccar with the Android App and via browser.

I am using [web.persistSession](https://www.traccar.org/configuration-file/) = True and the server is accessible via HTTPS (used proxy, as [recommended)](https://www.traccar.org/secure-connection/)

The bug was solved for the moment by deleting the browser cookie and reinstalling the app.

**Comment by tananaev** [comment]
The issue is probably with the browser cache.
