### ISSUE TITLE
Service restart

### ISSUE THREAD

**Issue by aruznieto** [traccar/traccar#5251]
**Describe the bug**

When I type `service traccar restart` or reboot my VM, the service no restart correctly

![telegram-cloud-photo-size-4-5866114054714671175-x](https://github.com/traccar/traccar/assets/40019177/448a21d6-ac1c-45be-b690-aab2ae29f07f)

**To Reproduce**
1. Type `service traccar restart`

**Desktop (please complete the following information):**
 - OS: ProxMox (VM with Ubuntu 22.04)

**Comment by tananaev** [comment]
You have to investigate what the root cause is before filing a bug. It's most likely something you did wrong. For example wrong configuration would cause the service to fail.
