### ISSUE TITLE
Permit use "full" templates on Telegram

### ISSUE THREAD

**Issue by aruznieto** [traccar/traccar#5254]
I would like that users can select if they want short or full message in Telegram.

**Comment by tananaev** [comment]
You have to provide more details for it to be considered.

**Comment by aruznieto** [comment]
I think that it would be interesting to put one variable

notificator.[notificator].messageStyle that can take "short" or "full" value

and inside [NotificatorTelegram.java](https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/notificators/NotificatorTelegram.java) (in this case) at send function (line 89), write

`var message = notificationFormatter.formatMessage(notification, user, event, position,  config.getString(Keys.NOTIFICATOR_TELEGRAM_MESSAGESTYLE));`

**Comment by tananaev** [comment]
I think you misunderstood the question. If it's a feature request, we have a template that you have to fill out. Looks like you completely ignored that template and we can't accept a request like this. You have to provide justification for why we should include it and why it would benefit a large number of users.

**Comment by aruznieto** [comment]
Ok, i am going to try do it alone, I think that is interesting to give the user the possibility to select the message style that their want

**Comment by tananaev** [comment]
OK, I'm going to close this for now.
