### ISSUE TITLE
traccar 5.12 reports fail java

### ISSUE THREAD

**Issue by mapoloco** [traccar/traccar#5260]
1- When i run traccar: /opt# sudo ./traccar.run
```
Creating directory out
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing traccar  100%
cp: cannot create regular file '/opt/traccar/jre/bin/java': Text file busy
```
2- Another problem is: with 5.10 geofences works normally, but in 5.12 I must delete the device and add again. If not, notification geofences does not work.

**Comment by tananaev** [comment]
1. It seems like some file system issue on your end.
2. Have you tried reconnecting the device instead? I just tested and it works for me perfectly fine without recreating device.

**Comment by tananaev** [comment]
Sorry, but I'm not able to reproduce either of the issues.

**Comment by mapoloco** [comment]
ok.
