### ISSUE TITLE
Car dissappeared from the map after updating from old version of traccar to latest version (v5.12)

### ISSUE THREAD

**Issue by heisenberg2980** [traccar/traccar#5266]
**Describe the bug**
After updating traccar to the latest version (v5.12) the car is not appearing in the traccar UI anymore but the car is still in the database because if I try to add it again I receive the error ```Duplicate entry 'xxxxxxxxxxxx' for key 'tc_devices.uniqueid' - SQLIntegrityConstraintViolationException (... < QueryBuilder:469 < DatabaseStorage:95 < BaseObjectResource:72 < ...)```

**To Reproduce**
1. Update traccar to v5.12 while a car is already existing in the database

**Expected behavior**

**Screenshots**
![image](https://github.com/traccar/traccar/assets/58039006/f64f2650-b595-4ba3-a5e5-4da5d04cd64e)
![image](https://github.com/traccar/traccar/assets/58039006/ed17a1de-76f3-476d-bd5c-41fd572abb34)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 121.0.6167.184 (Official Build) (64-bit)

**Additional context**
As an additional note, traccar is still reporting the position of the car to Home Assistant

**Comment by tananaev** [comment]
I'm pretty sure it has nothing to do with the upgrade. You need to investigate it first before submitting a bug. And if it indeed a bug, provide steps to reproduce starting from a clean server.

**Comment by heisenberg2980** [comment]
@tananaev I just realised I should have included another test I performed before opening the issue. I downgraded the traccar version to a previous version (v5.8) and the car reapeared on the UI, and as soon as I upgrade to v5.12 the car dissapear again.
