### ISSUE TITLE
Неверное отображение поездок в отчетах.

### ISSUE THREAD

**Issue by borozenetsvv** [traccar/traccar#5267]
Прошу прощения, в английском не силен.

Проблема в том, что при выборе в отчетах пункта "Поездки" - "Прошлая неделя" я заметил что поездки отображаются не полностью, а какие-то обрывки трека. Причем если выбрать отдельный день, то поездка отображается полностью.

По скринам ниже - утром на работу, вечером домой.

![1](https://github.com/traccar/traccar/assets/12553723/20fd15dc-c3c5-4b37-aedb-d6a7287f2e6f)
![2](https://github.com/traccar/traccar/assets/12553723/ed6275b2-3f3a-42fe-b753-3869bd201658)

![1-1](https://github.com/traccar/traccar/assets/12553723/5bbc7c19-a989-412e-bae5-0e22d2ce7e7e)
![2-1](https://github.com/traccar/traccar/assets/12553723/655ef899-2f8b-42b9-a38d-359bc562a1ff)

**Comment by tananaev** [comment]
Это быстрые отчеты. Почитайте на форуме обсуждалось неоднократно.
