### ISSUE TITLE
GUI failed login requests not being logged

### ISSUE THREAD

**Issue by ptzenos** [traccar/traccar#5275]
Using 5.12. Trying to set up fail2ban for the web interface.

While trying different combinations of username/passwords on the gui (port 8082) no failed login entries are being generated in the logs. The log level is set to "info" but I did try to also set it to "all".

According to what I've found by searching around, it should log something like "INFO: login failed.* ".

Any idea why is this happening or where to begin investigation? 

Thanks

**Comment by tananaev** [comment]
You should use the forum for discussions.
