### ISSUE TITLE
No logging attempt log

### ISSUE THREAD

**Issue by SecT0uch** [traccar/traccar#5278]
**Describe the bug**
When running the docker version:
- HTTP response on wrong user/pass: 400  `NullPointerException (SessionResource:121 < ... < OverrideFilter:49 < ...)`
- No Login attempt in log file. Feature from https://github.com/traccar/traccar/pull/4460

**To Reproduce**
1. Run the docker image like in the example
2. Try to login with `doesnotexist`:`password`
3. Nothing in traccar log file

**Expected behavior**
`"Failed Login Attempt. IP address: %s"` in logs

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: latest

**Comment by tananaev** [comment]
https://github.com/traccar/traccar/issues/5275

**Comment by SecT0uch** [comment]
> #5275

Well it look like a bug so a Github issue sounds more appropriate than a discussion on the forums

**Comment by tananaev** [comment]
The issue is already resolved.

**Comment by SecT0uch** [comment]
Can you show me which commit resolved it ?
I am using the tag `traccar:latest` (I just pulled) and it is not working

**Comment by tananaev** [comment]
You can probably search through the history yourself, but I can tell you that it's not in an official release yet.

**Comment by SecT0uch** [comment]
Indeed sorry, I missed the commits.

For future reference: https://github.com/traccar/traccar/commit/cb20b6984f6cc75e161e37baa6ff8a56a2e246a7 and https://github.com/traccar/traccar/commit/967d32485fc685774a9cbeba5b42273b0695bcf7
