### ISSUE TITLE
Notification not deactivated

### ISSUE THREAD

**Issue by rvcretin** [traccar/traccar#5287]
When deactivating a virtual paramètre to a user, he continues to receive the notifications 'enter the perimeter' or 'exit the perimeter'.

**To Reproduce**
First, create a virtual perimeter. Then assign this perimeter to a user and assign the 'enter virtual perimeter' and 'exit virtual perimeter'.
Everything works fine, meaning the user receive a mail each Time the device enter or exit the perimeter.

Then , remove the virtual perimeter' to the same user.

**Expected behavior**
It is expected that the user does not receive any email when the device enter or exit the virtual perimeter. 

Traccar server running on Docker: version:5.9

**Comment by tananaev** [comment]
You have to upgrade first.
