### ISSUE TITLE
Traccar v6 ARM does not start on Raspberry Pi OS

### ISSUE THREAD

**Issue by TheShadowAngel** [traccar/traccar#5293]
**Describe the bug**
Service does not start on Raspberry Pi OS (Debian 12)

**To Reproduce**
Update from 5.12 (work) to 6 (not work)

/opt/traccar/jre/bin/java: error while loading shared libraries: libjli.so: wrong ELF class: ELFCLASS64

---

После обновления рабочей версии 5.12 до 6 перестал запускаться сервис, в логах обозначенная выше ошибка.
Откатил на версию 5.12, всё работает.

**Comment by TheShadowAngel** [comment]
Architecture:            aarch64
Vendor ID:               ARM
Model name:           Cortex-A72

**Comment by tananaev** [comment]
And you installed the ARM version of Traccar? It should work on aarch64.

**Comment by tananaev** [comment]
It's also interesting because ARM in 5.12 was 32 bit, but you're saying it worked on your system.

**Comment by TheShadowAngel** [comment]
Yes, I am upgrade previous version 5.11 to 5.12 from this link:
https://github.com/traccar/traccar/releases/download/v5.12/traccar-linux-arm-5.12.zip
And yes, it is work fine.
![изображение](https://github.com/traccar/traccar/assets/41905618/2395857b-fb47-41dd-b3c7-b17869b68264)

**Comment by tananaev** [comment]
That was 32 bit ARM version. So something in your information is not correct.

**Comment by TheShadowAngel** [comment]
Redownload now, upgrade and:

> systemd[1]: Started traccar.service - traccar.
> (java)[2063]: traccar.service: Failed to execute /opt/traccar/jre/bin/java: No such file or directory
> (java)[2063]: traccar.service: Failed at step EXEC spawning /opt/traccar/jre/bin/java: No such file or directory
> systemd[1]: traccar.service: Main process exited, code=exited, status=203/EXEC
> systemd[1]: traccar.service: Failed with result 'exit-code'.

**Comment by tananaev** [comment]
I just tested and it work fine for me on aarch64 machine.

**Comment by geduxas** [comment]
Raspberry pi cpu is 64 bit but os was always 32bit

**Comment by tananaev** [comment]
Yeah, we don't provide 32bit version anymore. Is there a reason you didn't say that you're using 32bit when I asked about your system?

**Comment by TheShadowAngel** [comment]
Thanks all 🙏
Check now and find: Raspbian 12 (32 bit)

**Comment by tananaev** [comment]
We don't support ARM 32 anymore because many Java distributions are dropping support for it. I strongly recommend migrating to ARM 64 OS.
