### ISSUE TITLE
Assets for v6.0 have been silently replaced

### ISSUE THREAD

**Issue by tituspijean** [traccar/traccar#5294]
**Describe the bug**
Assets from https://github.com/traccar/traccar/releases/tag/v6.0 have been silently replaced.

Traccar is packaged for YunoHost, and YunoHost's application CI has detected that the assets have been changed: https://ci-apps.yunohost.org/ci/job/25322

```
4117 WARNING Failed to provision sources : YunoHost was able to download the asset 'main' (https://github.com/traccar/traccar/releases/download/v6.0/traccar-other-6.0.zip) for traccar, but the asset doesn't match the expected checksum. This could mean that some temporary network failure happened on your server, OR the asset was somehow changed by the upstream maintainer (or a malicious actor?) and YunoHost packagers need to investigate and update the app manifest to reflect this change.
    Expected sha256 checksum: face8357aed406f459f1bc56a80be1c53d5a6a08416a56a5fb80401ebebb8ce9
    Downloaded sha256 checksum: d6813dec896a466744006543387e5615244fa9ce2f0674fbb06c4864a0bac0a6
    Downloaded file size: 125M
```

Indeed, v6.0 has been published Apr 6, 2024, 11:40 PM GMT+2; but the assets have changed around Apr 7, 2024, 4:26 PM GMT+2

**Expected behavior**
Assets should not change after publication, that will trigger all bells and whistles for people relying on their checksum to make sure the downloaded file is uncorrupted (or worse...).

**Comment by tananaev** [comment]
We do replace binaries sometimes if we find critical issues.

**Comment by tituspijean** [comment]
I see https://github.com/traccar/traccar/commit/9a285e59e580994dc9c3f80935f766f3dafdcd46. Why not publish a 6.0.x version?

**Comment by tananaev** [comment]
Because I don't want people getting confused about several versions.

**Comment by OniriCorpe** [comment]
> critical issues.

so people won't update their installation because the binary has been silently replaced, that's not the clever move you think it is

**Comment by geduxas** [comment]
> > critical issues.
> 
> so people won't update their installation because the binary has been silently replaced, that's not the clever move you think it is

Critical i think if project wont run at all.. or break's.. also in short time from release. Don't think. It's huge problem

**Comment by OniriCorpe** [comment]
yeah not big deal, it’s just triggering all “this software has been tampered with” alarms on packagers side

in this way, we (YunoHost packagers) have been detected malicious alterations to various softwares on several occasions
but if we're treated like this when we report them, we won't report them anymore, that's all

bear in mind that if it happens too often, maybe we won't be packaging this software anymore, as a safety measure

**Comment by geduxas** [comment]
Sorry if my comment trigger some bad opinions, i am regular user who uses traccar for personal use.. no offense, just for me it's not problem.
