### ISSUE TITLE
WebUI 404 not Found

### ISSUE THREAD

**Issue by LeonEmm** [traccar/traccar#5299]
**Describe the bug**
When I try to access the webUI, I get an 404 not found from the traccar-server... No Errors in tracker-server.log shown. 

**To Reproduce**
Unknown - I guess updating to the newest version

**Expected behavior**
A working Access to WebUI

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: latest

**Additional context**
Docker runs on a Unraid-Server with image: traccar/traccar:latest

**Comment by tananaev** [comment]
And you're using default configuration files? No changes at all?

**Comment by LeonEmm** [comment]
Yes, this is my docker-compose.yml:

`version: "3.8"
services:
    
    traccar:
        image: traccar/traccar:latest
        container_name: traccar
        depends_on:
           - db
        restart: always
        volumes:
            - /mnt/user/appdata/traccar/traccar-conf:/opt/traccar/conf/
            - /mnt/user/appdata/traccar/trccar-logs:/opt/traccar/logs:rw
        #ports:
        #    - "192.168.11.5:5000-5150:5000-5150"
        #    - "192.168.11.3:80:80"
        environment:
           - MYSQL_DATABASE=tc
           - MYSQL_USER=tc
           - MYSQL_PASSWORD=traccarpasswd#2023
        networks:
          frontend_network:
            ipv4_address: 192.168.11.5
          backend: 
          
    db:
        image: mysql:8.0.20
        hostname: traccardb
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - /mnt/user/appdata/traccar/mysql-data:/var/lib/mysql
            - /mnt/user/appdata/traccar/mysql-config:/etc/mysql/conf.d
        environment:
          - MYSQL_ROOT_PASSWORD=###########
        networks:
          backend:
        cap_add:
          - SYS_NICE


networks:
    frontend_network:
      external: true
      name: br0.11
    backend:
`

Other than that no changes were made...

**Comment by tananaev** [comment]
I can see that you mounted the config folder. There must be a reason for it.

**Comment by LeonEmm** [comment]
In the config folder there are two files:

**default.xml**
`<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    

    <entry key='web.port'>8082</entry>
    <entry key='web.path'>./modern</entry>
    <entry key='web.sanitize'>false</entry>
    <entry key='web.persistSession'>false</entry>

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>locationiq</entry>
    <entry key='geocoder.key'>pk.689d849289c8c63708068b2ff1f63b2d</entry>
    <entry key='geocoder.onRequest'>true</entry>
    <entry key='geocoder.ignorePositions'>true</entry>

    <entry key='logger.level'>info</entry>
    <entry key='logger.file'>./logs/tracker-server.log</entry>
    <entry key='logger.rotate'>true</entry>

    <entry key='filter.enable'>true</entry>
    <entry key='filter.future'>86400</entry>

    <entry key='event.ignoreDuplicateAlerts'>true</entry>

    <entry key='media.path'>./media</entry>

    <entry key='notificator.types'>web,mail,command</entry>

    <entry key='server.statistics'>https://www.traccar.org/analytics/</entry>

    <entry key='commands.queueing'>true</entry>

    <entry key='database.ignoreUnknown'>true</entry>
    <entry key='database.changelog'>./schema/changelog-master.xml</entry>

    <entry key='gps103.port'>5001</entry>
    <entry key='tk103.port'>5002</entry>
    <entry key='gl100.port'>5003</entry>
    <entry key='gl200.port'>5004</entry>
    <entry key='t55.port'>5005</entry>
    <entry key='xexun.port'>5006</entry>
    <entry key='xexun.extended'>false</entry>
    <entry key='totem.port'>5007</entry>
    <entry key='enfora.port'>5008</entry>
    <entry key='meiligao.port'>5009</entry>
    <entry key='trv.port'>5010</entry>
    <entry key='suntech.port'>5011</entry>
    <entry key='progress.port'>5012</entry>
    <entry key='h02.port'>5013</entry>
    <entry key='jt600.port'>5014</entry>
    <entry key='huabao.port'>5015</entry>
    <entry key='v680.port'>5016</entry>
    <entry key='pt502.port'>5017</entry>
    <entry key='tr20.port'>5018</entry>
    <entry key='navis.port'>5019</entry>
    <entry key='meitrack.port'>5020</entry>
    <entry key='skypatrol.port'>5021</entry>
    <entry key='gt02.port'>5022</entry>
    <entry key='gt06.port'>5023</entry>
    <entry key='megastek.port'>5024</entry>
    <entry key='navigil.port'>5025</entry>
    <entry key='gpsgate.port'>5026</entry>
    <entry key='teltonika.port'>5027</entry>
    <entry key='mta6.port'>5028</entry>
    <entry key='tzone.port'>5029</entry>
    <entry key='tlt2h.port'>5030</entry>
    <entry key='taip.port'>5031</entry>
    <entry key='wondex.port'>5032</entry>
    <entry key='cellocator.port'>5033</entry>
    <entry key='galileo.port'>5034</entry>
    <entry key='ywt.port'>5035</entry>
    <entry key='tk102.port'>5036</entry>
    <entry key='intellitrac.port'>5037</entry>
    <entry key='gpsmta.port'>5038</entry>
    <entry key='wialon.port'>5039</entry>
    <entry key='carscop.port'>5040</entry>
    <entry key='apel.port'>5041</entry>
    <entry key='manpower.port'>5042</entry>
    <entry key='globalsat.port'>5043</entry>
    <entry key='atrack.port'>5044</entry>
    <entry key='pt3000.port'>5045</entry>
    <entry key='ruptela.port'>5046</entry>
    <entry key='topflytech.port'>5047</entry>
    <entry key='laipac.port'>5048</entry>
    <entry key='aplicom.port'>5049</entry>
    <entry key='gotop.port'>5050</entry>
    <entry key='sanav.port'>5051</entry>
    <entry key='gator.port'>5052</entry>
    <entry key='noran.port'>5053</entry>
    <entry key='m2m.port'>5054</entry>
    <entry key='osmand.port'>5055</entry>
    <entry key='easytrack.port'>5056</entry>
    <entry key='gpsmarker.port'>5057</entry>
    <entry key='khd.port'>5058</entry>
    <entry key='piligrim.port'>5059</entry>
    <entry key='stl060.port'>5060</entry>
    <entry key='cartrack.port'>5061</entry>
    <entry key='minifinder.port'>5062</entry>
    <entry key='haicom.port'>5063</entry>
    <entry key='eelink.port'>5064</entry>
    <entry key='box.port'>5065</entry>
    <entry key='freedom.port'>5066</entry>
    <entry key='telic.port'>5067</entry>
    <entry key='trackbox.port'>5068</entry>
    <entry key='visiontek.port'>5069</entry>
    <entry key='orion.port'>5070</entry>
    <entry key='riti.port'>5071</entry>
    <entry key='ulbotech.port'>5072</entry>
    <entry key='tramigo.port'>5073</entry>
    <entry key='tr900.port'>5074</entry>
    <entry key='ardi01.port'>5075</entry>
    <entry key='xt013.port'>5076</entry>
    <entry key='autofon.port'>5077</entry>
    <entry key='gosafe.port'>5078</entry>
    <entry key='tt8850.port'>5079</entry>
    <entry key='bce.port'>5080</entry>
    <entry key='xirgo.port'>5081</entry>
    <entry key='calamp.port'>5082</entry>
    <entry key='mtx.port'>5083</entry>
    <entry key='tytan.port'>5084</entry>
    <entry key='avl301.port'>5085</entry>
    <entry key='castel.port'>5086</entry>
    <entry key='mxt.port'>5087</entry>
    <entry key='cityeasy.port'>5088</entry>
    <entry key='aquila.port'>5089</entry>
    <entry key='flextrack.port'>5090</entry>
    <entry key='blackkite.port'>5091</entry>
    <entry key='adm.port'>5092</entry>
    <entry key='watch.port'>5093</entry>
    <entry key='t800x.port'>5094</entry>
    <entry key='upro.port'>5095</entry>
    <entry key='auro.port'>5096</entry>
    <entry key='disha.port'>5097</entry>
    <entry key='thinkrace.port'>5098</entry>
    <entry key='pathaway.port'>5099</entry>
    <entry key='arnavi.port'>5100</entry>
    <entry key='nvs.port'>5101</entry>
    <entry key='kenji.port'>5102</entry>
    <entry key='astra.port'>5103</entry>
    <entry key='homtecs.port'>5104</entry>
    <entry key='fox.port'>5105</entry>
    <entry key='gnx.port'>5106</entry>
    <entry key='arknav.port'>5107</entry>
    <entry key='supermate.port'>5108</entry>
    <entry key='appello.port'>5109</entry>
    <entry key='idpl.port'>5110</entry>
    <entry key='huasheng.port'>5111</entry>
    <entry key='l100.port'>5112</entry>
    <entry key='granit.port'>5113</entry>
    <entry key='carcell.port'>5114</entry>
    <entry key='obddongle.port'>5115</entry>
    <entry key='hunterpro.port'>5116</entry>
    <entry key='raveon.port'>5117</entry>
    <entry key='cradlepoint.port'>5118</entry>
    <entry key='arknavx8.port'>5119</entry>
    <entry key='autograde.port'>5120</entry>
    <entry key='oigo.port'>5121</entry>
    <entry key='jpkorjar.port'>5122</entry>
    <entry key='cguard.port'>5123</entry>
    <entry key='fifotrack.port'>5124</entry>
    <entry key='smokey.port'>5125</entry>
    <entry key='extremtrac.port'>5126</entry>
    <entry key='trakmate.port'>5127</entry>
    <entry key='at2000.port'>5128</entry>
    <entry key='maestro.port'>5129</entry>
    <entry key='ais.port'>5130</entry>
    <entry key='gt30.port'>5131</entry>
    <entry key='tmg.port'>5132</entry>
    <entry key='pretrace.port'>5133</entry>
    <entry key='pricol.port'>5134</entry>
    <entry key='siwi.port'>5135</entry>
    <entry key='starlink.port'>5136</entry>
    <entry key='dmt.port'>5137</entry>
    <entry key='xt2400.port'>5138</entry>
    <entry key='dmthttp.port'>5139</entry>
    <entry key='alematics.port'>5140</entry>
    <entry key='gps056.port'>5141</entry>
    <entry key='flexcomm.port'>5142</entry>
    <entry key='vt200.port'>5143</entry>
    <entry key='owntracks.port'>5144</entry>
    <entry key='vtfms.port'>5145</entry>
    <entry key='tlv.port'>5146</entry>
    <entry key='esky.port'>5147</entry>
    <entry key='genx.port'>5148</entry>
    <entry key='flespi.port'>5149</entry>
    <entry key='dway.port'>5150</entry>
    <entry key='recoda.port'>5151</entry>
    <entry key='oko.port'>5152</entry>
    <entry key='ivt401.port'>5153</entry>
    <entry key='sigfox.port'>5154</entry>
    <entry key='t57.port'>5155</entry>
    <entry key='spot.port'>5156</entry>
    <entry key='m2c.port'>5157</entry>
    <entry key='austinnb.port'>5158</entry>
    <entry key='opengts.port'>5159</entry>
    <entry key='cautela.port'>5160</entry>
    <entry key='continental.port'>5161</entry>
    <entry key='egts.port'>5162</entry>
    <entry key='robotrack.port'>5163</entry>
    <entry key='pt60.port'>5164</entry>
    <entry key='telemax.port'>5165</entry>
    <entry key='sabertek.port'>5166</entry>
    <entry key='retranslator.port'>5167</entry>
    <entry key='svias.port'>5168</entry>
    <entry key='eseal.port'>5169</entry>
    <entry key='freematics.port'>5170</entry>
    <entry key='avema.port'>5171</entry>
    <entry key='autotrack.port'>5172</entry>
    <entry key='tek.port'>5173</entry>
    <entry key='wristband.port'>5174</entry>
    <entry key='lacak.port'>5175</entry>
    <entry key='milesmate.port'>5176</entry>
    <entry key='anytrek.port'>5177</entry>
    <entry key='smartsole.port'>5178</entry>
    <entry key='its.port'>5179</entry>
    <entry key='xrb28.port'>5180</entry>
    <entry key='c2stek.port'>5181</entry>
    <entry key='nyitech.port'>5182</entry>
    <entry key='neos.port'>5183</entry>
    <entry key='satsol.port'>5184</entry>
    <entry key='globalstar.port'>5185</entry>
    <entry key='sanul.port'>5186</entry>
    <entry key='minifinder2.port'>5187</entry>
    <entry key='radar.port'>5188</entry>
    <entry key='techtlt.port'>5189</entry>
    <entry key='starcom.port'>5190</entry>
    <entry key='mictrack.port'>5191</entry>
    <entry key='plugin.port'>5192</entry>
    <entry key='leafspy.port'>5193</entry>
    <entry key='naviset.port'>5194</entry>
    <entry key='racedynamics.port'>5195</entry>
    <entry key='rst.port'>5196</entry>
    <entry key='pt215.port'>5197</entry>
    <entry key='pacifictrack.port'>5198</entry>
    <entry key='topin.port'>5199</entry>
    <entry key='outsafe.port'>5200</entry>
    <entry key='solarpowered.port'>5201</entry>
    <entry key='motor.port'>5202</entry>
    <entry key='omnicomm.port'>5203</entry>
    <entry key='s168.port'>5204</entry>
    <entry key='vnet.port'>5205</entry>
    <entry key='blue.port'>5206</entry>
    <entry key='pst.port'>5207</entry>
    <entry key='dingtek.port'>5208</entry>
    <entry key='wli.port'>5209</entry>
    <entry key='niot.port'>5210</entry>
    <entry key='portman.port'>5211</entry>
    <entry key='moovbox.port'>5212</entry>
    <entry key='futureway.port'>5213</entry>
    <entry key='polte.port'>5214</entry>
    <entry key='net.port'>5215</entry>
    <entry key='mobilogix.port'>5216</entry>
    <entry key='swiftech.port'>5217</entry>
    <entry key='iotm.port'>5218</entry>
    <entry key='dolphin.port'>5219</entry>
    <entry key='ennfu.port'>5220</entry>
    <entry key='navtelecom.port'>5221</entry>
    <entry key='startek.port'>5222</entry>
    <entry key='gs100.port'>5223</entry>
    <entry key='mavlink2.port'>5224</entry>
    <entry key='uux.port'>5225</entry>
    <entry key='r12w.port'>5226</entry>
    <entry key='flexiblereport.port'>5227</entry>
    <entry key='thinkpower.port'>5228</entry>
    <entry key='stb.port'>5229</entry>
    <entry key='b2316.port'>5230</entry>
    <entry key='hoopo.port'>5231</entry>
    <entry key='dualcam.port'>5232</entry>
    <entry key='xexun2.port'>5233</entry>
    <entry key='techtocruz.port'>5234</entry>
    <entry key='flexapi.port'>5235</entry>
    <entry key='dsf22.port'>5236</entry>
    <entry key='jido.port'>5237</entry>
    <entry key='armoli.port'>5238</entry>
    <entry key='teratrack.port'>5239</entry>
    <entry key='envotech.port'>5240</entry>
    <entry key='bstpl.port'>5241</entry>
    <entry key='thuraya.port'>5242</entry>
    <entry key='ndtpv6.port'>5243</entry>
    <entry key='g1rus.port'>5244</entry>
    <entry key='rftrack.port'>5245</entry>
    <entry key='vlt.port'>5246</entry>
    <entry key='transync.port'>5247</entry>

</properties>`

and

**traccar.xml**

`<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <entry key='config.default'>./conf/default.xml</entry>

    

    <entry key='database.driver'>com.mysql.cj.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://traccar-db-1:3306/tc?zeroDateTimeBehavior=round&amp;serverTimezone=UTC&amp;allowPublicKeyRetrieval=true&amp;useSSL=false&amp;allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
    <entry key='database.user'>hidden</entry>
    <entry key='database.password'>hidden but correct</entry>
    <entry key='web.enable'>true</entry>
    <entry key='web.port'>80</entry>
    <entry key='mail.smtp.port'>587</entry>
    <entry key='mail.smtp.starttls.enable'>true</entry>
    <entry key='mail.smtp.host'>hidden</entry>
    <entry key='mail.smtp.from'> hidden </entry>
    <entry key='mail.smtp.auth'>true</entry>
    <entry key='mail.smtp.username'> hidden </entry>
    <entry key='mail.smtp.password'> hidden but correct</entry>   `

**Comment by tananaev** [comment]
I already see the problem. You shouldn't use old config files.

**Comment by LeonEmm** [comment]
I did recreate the default.xml but now all recorded Data is gone. How is that possible?
