### ISSUE TITLE
Add UDP support for tlt2h protocol (e.g. Mictrack MT710)

### ISSUE THREAD

**Issue by heypete** [traccar/traccar#5307]
**Background**
I have a Mictrack MT710 tracker. It is [compatible with Traccar](https://www.traccar.org/forums/topic/mini-cat-m1-nb-iot-gps-tracker-mt710-feedback/#post-85045) using the tlt2h protocol on TCP port 5030. The tracker can communicate using either TCP or UDP.

**Problem**
Traccar only supports this device (and the tlt2h protocol more broadly) using TCP, not UDP.

Due to the overhead involved with the TCP handshake, payload exchange, and connection teardown, transmitting a small quantity of data (like that from a GPS tracker) using TCP uses roughly 2x the billable data to send the same amount of payload data compared to using UDP.

**Requested Feature**
Implement support for UDP for this protocol/device.

**Describe alternatives you've considered**
Continuing to use TCP is possible, but results in higher data usage.

**Additional context**
I am happy to pay a financial bounty for this feature, amount TBD.

**Comment by tananaev** [comment]
Do you have the documentation?

**Comment by heypete** [comment]
> Do you have the documentation?

Certainly.

- [MT710 communications protocol](https://www.mictrack.com/downloads/protocols/Mictrack_Communication_Protocol_For_MT710_V1.0.pdf)
- [MT710 manual](https://www.mictrack.com/downloads/user-manual/4g-gps-tracker/MT710_User_Manual_V1.0.pdf)
- [MT710 commands list (SMS, USB, and downlink)[https://www.mictrack.com/downloads/Commands-list/Mictrack_MT710_Commands_List.pdf]

The English in the manuals is generally ok, but some parts can be somewhat unclear. I have been reading through them in detail for several days and am happy to help disambiguate them as best I can if needed.
