### ISSUE TITLE
Teltonika FCM130 Driver ID

### ISSUE THREAD

**Issue by vk5657** [traccar/traccar#5311]
Hello,

The driver identification in Teltonika protocol is not working for tracker model FCM130. I just made a little change to receive driver identification. Please, see attachments.

Best regards,
Volnei

![Screenshot 2024-04-25 at 17 49 48](https://github.com/traccar/traccar/assets/168142338/7561a4b4-0044-4efc-9776-e9e2c0eb1c36)
![Screenshot 2024-04-25 at 18 42 07](https://github.com/traccar/traccar/assets/168142338/f8c0a97e-d6c5-4aad-bd6a-8d5dea3ed7bb)

**Comment by tananaev** [comment]
Can you provide a screenshot where you set the model for your device.

**Comment by vk5657** [comment]
Hi thanks for your answer.
I just made this two changes:
Add the model "FCM130" in  "var fmbXXX" and change the register 78 from null to fmbXXX, according to the second image.

Best regards,
Volnei

**Comment by tananaev** [comment]
Sounds like you broke it instead of fixing.

**Comment by vk5657** [comment]
Before this change, I received the data with the driver id, like this:
{"priority":0,"sat":0,"event":0,"ignition":true,"motion":true,"rssi":4,"io200":0,"io69":2,"pdop":0.0,"hdop":0.0,"power":12.373000000000001,"battery":0.0,"io68":0,"operator":72410,"odometer":0,"io78":86625417254928633,"distance":0.0,"totalDistance":3.4036757690413915E7,"hours":14692950}

**Comment by vk5657** [comment]
The driver ID was sent in "io78"

**Comment by tananaev** [comment]
This does not belong on GitHub. We only accept bugs in the official version or feature requests.
