### ISSUE TITLE
  Traccar as MQTT consumer

### ISSUE THREAD

**Issue by fred-gb** [traccar/traccar#5317]
Hi,

**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
A device publish on MQTT broker gps positions. And Traccar read on mqtt topic.

**Describe alternatives you've considered**
Not considering alternative yet. 

**Additional context**
I think MQTT protocol is lighter than HTTP.
And MQTT retained message can permit more accurate tracing.

Thanks

**Comment by tananaev** [comment]
1. What device are you talking about?
2. MQTT might be lighter than HTTP (even that is questionable), but it's definitely not lighter than raw TCP and UDP that most devices use currently.
3. How is using MQTT make tracking more accurate?

**Comment by fred-gb** [comment]
Sorry I expressed myself badly. I was too fast and not enough details.

1. What device are you talking about?
raspberry pi

2. MQTT might be lighter than HTTP (even that is questionable), but it's definitely not lighter than raw TCP and UDP that most devices use currently.
OK

3. How is using MQTT make tracking more accurate?
I think it's for data tracing. If a component like for example Traccar is offline. Devices can continue to send their position. And when Traccar comes back online, it recovers the position history, so there are no losses.

And I think that MQTT is the protocol suitable for IOT. So I thought this option could have additional value.

THANKS

**Comment by tananaev** [comment]
We have more than 250 different device communication protocols already, including some MQTT-based. Adding another one without actually a mass-produced device would only make sense if there are good reasons. So far you haven't been articulate any reasons.

**Comment by fred-gb** [comment]
ok
Thanks
