### ISSUE TITLE
[5.10] Can't set Total Distance, IllegalArgumentException (DeviceResource:155 < ... < OverrideFilter:49 < ...) 

### ISSUE THREAD

**Issue by rpsjr** [traccar/traccar#5319]
**Describe the bug**
Traccar 5.10
Old DB running, after clearance of tc_positions, tc_statistics and tc_events trables rows, can't set Total Distance acummulator anymore.

IllegalArgumentException (DeviceResource:155 < ... < OverrideFilter:49 < ...) 

**To Reproduce**
Request URL:
.../api/devices/.../accumulators
Request Method:
PUT
Status Code:
400 Bad Request

{"deviceId":...,"hours":0,"totalDistance":0}

**Expected behavior**

**Screenshots**
![image](https://github.com/traccar/traccar/assets/42212369/ff7df7bd-60c2-4e78-a6be-1e62359a3669)
**Desktop (please complete the following information):**
 - OS: Ubuntu 18 server
 - Browser agnostic

**Comment by tananaev** [comment]
We only accept bugs in the current version, not older ones.
