### ISSUE TITLE
Feature Request: Reports use attribute "Web: Report Color" to display lines

### ISSUE THREAD

**Issue by michalis97500** [traccar/traccar#5322]
I'm always frustrated when trying to produce reports of several vehicles at the same time. All lines are drawn with the same blue color and thus distinguishing routes of different vehicles becomes extremely difficult

Each vehicle can get the color from its attribute as a way to display the routes in the reports.

No alternatives to this. The data must be exported, analyzed and plotted manually (maybe by python?) which defeats the purpose of the reports

**Comment by tananaev** [comment]
Wrong repository. This belongs to the web app.
