### ISSUE TITLE
OpenID not showing up in web ui

### ISSUE THREAD

**Issue by ClumsyAdmin** [traccar/traccar#5323]
Just creating and closing this issue just in case anyone else runs into this issue so they can hopefully find this GH issue. I've ran traccar for quite a few years and I saw that OpenID was recently added so went to set that up and couldn't get the UI to properly display it or get it to redirect me even to my authentication provider. The issue ended up being that the traccar update script doesn't wipe out old files so I've been stuck on whatever old web ui version/modern beta. Wiped those files and copied updated web folder and it redirected perfectly. The new UI (well at least new to me) is awesome, great job team. That's all, thanks!

**Comment by tananaev** [comment]
Sounds like you didn't follow the upgrade instructions.

**Comment by ClumsyAdmin** [comment]
Ah, seems so. I misunderstood the instructions thinking those steps were only needed on an earlier version. Thanks.
