### ISSUE TITLE
White screen after installation

### ISSUE THREAD

**Issue by mobiusrpi** [traccar/traccar#5330]
**Describe the bug**
New installation on a fresh VPS server under Debian
When I run "My-ip:8082/traccar" I have a white screen

**To Reproduce**
Create mysql database traccar via phpmyadmin
Download  traccar-linux-64-latest.zip and unzip
do sudo ./traccar.run
sudo systemctl start traccar

Run "http://my-ip:8082/traccar" 
I have a white screen 
Browser console indicate
<body>
    <noscript>Enable JavaScript to use <a href="https://www.traccar.org/">Traccar GPS Tracking System</a>.</noscript>
    <div id="root" class="root"></div>
</body>
javascript is well installed in Chrome settings
I tried under Chrome and Firefox 
Same on other PC 

**Noticed**
In the folder /opt/traccar/conf there is no default.xml file (call from traccar.xml)
Previously I had installed Traccar on my old server and this file was present

**Expected behavior**
Access to the traccar login page

**Desktop 
 - OS: Windows 11 and windows 10
 - Browser Chrome and Firefox
 - Debian 12, Apache2.4.59, PHP8.2.18, Mysql8.2.18

**Comment by tananaev** [comment]
Have you cleared all the website data?

**Comment by tananaev** [comment]
I mean browser caches.

**Comment by mobiusrpi** [comment]
Yes, the cache was been cleared and I also used a freshly installed Firefox and changed of computers to check if the javascript issue was coming from the computer

**Comment by tananaev** [comment]
What's the URL?

**Comment by mobiusrpi** [comment]
http://51.79.53.111:8082/traccar
Not yet domain name

**Comment by tananaev** [comment]
Why do you have traccar as a path? We don't support that in the official version. You have to recompile the app for that to work.

**Comment by mobiusrpi** [comment]
I don't know why traccar as a path. 
I didn't modify any file fron the unzipping of provide package 
I strickly followed the linux installation from your documentation https://www.traccar.org/linux/

What about the default.xml file not provided in traccar-linux-64-latest.zip

**Comment by tananaev** [comment]
This seems to work just fine for me:

http://51.79.53.111:8082
