### ISSUE TITLE
share device is not avaiable when Terms and privacy policy option active.

### ISSUE THREAD

**Issue by mapoloco** [traccar/traccar#5333]
**Describe the bug**
If you active Terms and privacy policy option and share a device, when try to accept Terms and privacy policy options there is an error: "Write access denied - SecurityException (PermissionsService:119 < *:126 < BaseObjectResource:89 < ... < OverrideFilter:49 < ...)"

**To Reproduce**
1. Go to 'Server, atributes, active terms and condicion, put both url'
2. Click on a device, share device 
3. copy and paste url in a New incognito (private) window
4. Try accept Terms and privacy policy option
5. See error.

**Screenshots**
![private mode error](https://github.com/traccar/traccar/assets/32565873/8bc71c32-61d7-4372-b4bc-e737e776d418)

**Desktop (please complete the following information):**
 - OS: Traccar 6.2
 - Browse chrome, brave, edge,...

**Comment by tananaev** [comment]
Fixed in https://github.com/traccar/traccar/commit/2147ecb2d9fe0fb49b3f03dc650bc363e72e3fd2.
