### ISSUE TITLE
Count device offline, online, and outside geofence

### ISSUE THREAD

**Issue by candrawardana** [traccar/traccar#5338]
outside geofence, wich is group connection or device connection

**Comment by tananaev** [comment]
You have to provide more details if it's the feature request.

**Comment by candrawardana** [comment]
by now, there is no such things to call devices count that are online or offline, if possible, how to count device that exit geofence  too?

**Comment by tananaev** [comment]
There is a count by status already.

**Comment by candrawardana** [comment]
how? (and how about geofencing?)

**Comment by tananaev** [comment]
For discussions we have the forum. I'm going to close this for now because it looks like you're not very familiar with the app and also not enough details provided.
