### ISSUE TITLE
Address not showing in Home Assistant

### ISSUE THREAD

**Issue by m3tc0n** [traccar/traccar#5341]
Hi, I am running a Traccar server in Docker. I have added my phone and my wife's phone. When I press the entities, I can choose to show the current address. The right address is shown.

I am also running the Traccar integration in Home Assistant. My phone and my wife's phone are added with 8 entities each. One of those entities is the address entity. This one is shown as unknown, see the screenshot. How to solve this?

Screenshot (HA):
![Screenshot_20240611-114754.png](https://github.com/traccar/traccar/assets/106514117/a40c668d-8df0-4d44-9e78-5c716c7faaef)

**Comment by tananaev** [comment]
We don't an official Home Assistant integration.
