### ISSUE TITLE
Feature request: sms function using a url

### ISSUE THREAD

**Issue by TelecomServices** [traccar/traccar#5346]
Whe have a sms provider that is using a url:
https://service.speakup.nl/msgbroker/?username=[username]&password=[password]&originator=[originator]&recipients=[recipients]&message=[message]
Is it possible to add this function to the traccar sms?

**Comment by tananaev** [comment]
It does not support a POST? Where's the documentation?

**Comment by TelecomServices** [comment]
i have asked the provider, and waiting for a awnser.

**Comment by jinzo** [comment]
From https://service.speakup.nl/msgbroker/ I would say it does support POST too. So should be possible to implement as is.

**Comment by tananaev** [comment]
If POST is supported, it should be possible to use it already.

**Comment by TelecomServices** [comment]
Hi, i have the awnser from the provider:
The are using the: Post
https://api.speakup.nl/msgbroker/docs
