### ISSUE TITLE
Bug Report: The device cache is never removed when the device is disconnected.

### ISSUE THREAD

**Issue by mrajaei76** [traccar/traccar#5356]
**Describe the bug**
The condition 
`if (deviceReferences.computeIfAbsent(deviceId, k -> new AtomicInteger()).incrementAndGet() <= 0)`
 in the [removeDevice method](https://github.com/traccar/traccar/blob/d47da84d3bfea34266ba83ea8595a7ad9a7031b9/src/main/java/org/traccar/session/cache/CacheManager.java#L170C1-L181C6) is problematic because the `incrementAndGet()` method always increments the value and returns the incremented value. As a result, the condition will never be `true`, and the device will never be removed from cache as intended.

**Additional context**
I checked the Git history for the selected section, and it decrements references and checks the condition but now it increase and check it. I think there is a bug in this method, and we should use `decrementAndGet` instead of `incrementAndGet`.

**Comment by tananaev** [comment]
Good catch. Fixed.
