### ISSUE TITLE
connection suddenly refused

### ISSUE THREAD

**Issue by opa-rudi** [traccar/traccar#5363]
My traccar server on a Debian machine was running for a long time. Now it stopped working but I cannot find the reason. Possibly I did some changes (upgrades) on the system but I can´t remember. I updated the traccar server to the newest version but the error still occurs:

`HikariPool-1 - Starting...`
`ERROR: Main method error - Connection refused - ConnectException (... < DatabaseModule:80 < <gener:-1 < *:-1 < ... < MainModule:128 < ...)`

Says the log. I have no idea what that means. Can anybody give some advice? 

THX

**Comment by tananaev** [comment]
For questions and discussions you should use the forum.
