### ISSUE TITLE
Dear, can you fix address from localdb or our own address server

### ISSUE THREAD

**Issue by igpl734** [traccar/traccar#5369]
**Is your feature request related to a problem? Please describe.**
Address via many other platforms you have listed, doesnot matches exact requirement

**Describe the solution you'd like**
So i want to put either address locally and get them parsed and give structure so i can add address there

**Describe alternatives you've considered**
or link like 
https://apkapi.lol/address.php?lat=25.985536&long=75.732870 
so the data can be more accurate and even user can update it.
.

**Additional context**

**Comment by tananaev** [comment]
Our of scope for Traccar currently. You can just have an external service that does what you want.
