### ISSUE TITLE
User Specific Settings for Third Party Services

### ISSUE THREAD

**Issue by abish7643** [traccar/traccar#5374]
**Is your feature request related to a problem? Please describe.**
We do not charge anything from people who do not need any custom requirements, just basic tracking functionality. In most of the use cases, the operating cost is mostly contributed by the third party APIs used within Traccar.
For example, I do believe that the pricing for Google Maps is quite high, which means that we need to charge more from end users to make it sustainable.

**Describe the solution you'd like**
User specific settings will be useful for services which utilizes third party APIs. The following services is most notable the ones which I think are important.
- Maps (Select Maps from Supported Map List)
- SMS Services (Enable / Disable, Rate Limit?)
- Geocoder Service

Already there are user specific connections, but these settings will also be specifically useful.
I'm not sure how complex this will be in terms of implementation, but I'm certainly sure that significant efforts are required.

**Comment by tananaev** [comment]
1. Maps are already per user.
2. SMS services rate limiting is already requested in another ticket.
3. Geocoder - how would you handle if the same device is linked to two users?

**Comment by tananaev** [comment]
1. You can already have global settings and you can also force server settings.

**Comment by abish7643** [comment]
1. Are you suggesting **Active Maps** attribute?

**Comment by tananaev** [comment]
Yes.

**Comment by abish7643** [comment]
I don't think you got my point. The user can change the **Active Maps** parameter, not just the Admin / Manager. 
It's sort of a default option for a user which the user can obviously change.

> If there are maps X, Y & Z -> Admin / Manager can give access to X & Y, not Z to a specific user. So that the user can only switch between X & Y within the Active Maps. The user won't even see the option Z. 

I'll give you practical example, if every user switches to Google Maps, operating cost will be sky high.
If the option of Google Maps can be taken away from the free users, it'll be sustainable.
I hope this will clear your doubt.

Attaching screenshots.

![image](https://github.com/user-attachments/assets/43919e3c-c8c7-4670-841e-09c47147b49b)
![image](https://github.com/user-attachments/assets/29ab5e08-4428-41e8-804d-8c80942195db)

**Comment by tananaev** [comment]
You can force server settings.

**Comment by abish7643** [comment]
- If there are X, Y, Z Maps in total.
- User A should only have access to X & Y maps.
- User B should only have access to X, Y & Z maps.

Please suggest how this is possible with your point of view?

### Server Settings Screenshots 
User Should Only Have Access to 2 Out of 3 Maps.

![image](https://github.com/user-attachments/assets/aacce21d-fa75-462d-bd56-f82bb821e33e)
![image](https://github.com/user-attachments/assets/ad12380e-8f7d-4506-b8f1-1f24079f68d6)

### User Settings
User already have access to all the 3 maps.

![image](https://github.com/user-attachments/assets/ab125836-007a-43ad-9ffa-2b5f941256aa)
![image](https://github.com/user-attachments/assets/02b25d82-b0cb-4ca6-aa9f-a39e9c180d59)
![image](https://github.com/user-attachments/assets/5e499cbe-fb78-4aeb-b6b2-6966d68d30bc)

**Comment by tananaev** [comment]
Have you enabled force server settings? I don't see it on the screenshots.

**Comment by tananaev** [comment]
I'm confused why user should have access to two maps only? If your server config has 3 and you have forced enabled.

**Comment by abish7643** [comment]
You're the one who suggested to force it. I initially shared the use case, right?

- If there are X, Y, Z Maps in total.
- User A should only have access to X & Y maps.
- User B should only have access to X, Y & Z maps.

Please suggest if this is possible.

**Comment by tananaev** [comment]
It's not possible to force those, unless you're using read-only users.

**Comment by abish7643** [comment]
This was a feature request, and I clearly mentioned a practical reason also.

![image](https://github.com/user-attachments/assets/005723b6-63b3-433f-90f5-ebeadb7a1403)


> If there are maps X, Y & Z -> Admin / Manager can give access to X & Y, not Z to a specific user. So that the user can only switch between X & Y within the Active Maps. The user won't even see the option Z.

> I'll give you a practical example, if every user switches to Google Maps, operating cost will be sky high.
> If the option of Google Maps can be taken away from the free users, it'll be sustainable.
> I hope this will clear your doubt.

If you are not interested in the use case, It's okay. I'll close the issue.

**Comment by tananaev** [comment]
A feature request is fine, but you mixed up multiple requests, some which are already possible and some duplicating other requests.
