### ISSUE TITLE
MT65Plus not in traccar

### ISSUE THREAD

**Issue by TobiasHamer** [traccar/traccar#5376]
Hi Anton, 

here is the protocol document of the device MT65Plus.
The thread in traccar forum: [Megastek MT65Plus](https://www.traccar.org/forums/topic/megastek-mt65plus/)

Thanks and kind regads,
Tobias

[MT65plus GPRS data upload protocol(1).pdf](https://github.com/user-attachments/files/16471304/MT65plus.GPRS.data.upload.protocol.1.pdf)

**Comment by tananaev** [comment]
Make sure you either link the original thread or provide full context and details here. Also let us know if you're interested in sponsoring this work or just want to wait.

**Comment by TobiasHamer** [comment]
I did a little donation but be sure, it is not the last one :-)
Also I edited my first post with the link of the traccar thread.
