### ISSUE TITLE
Watch Protocol - TK913-4G - 0% battery if not moving

### ISSUE THREAD

**Issue by deralexmalex** [traccar/traccar#5377]
**Describe the bug**
Discription in the traccar Forum from the User "Rob" ( https://www.traccar.org/forums/topic/watch-protocol-oddity/#post-95374 ).
There is a Problem with the device TK913-4G (XTK913-4G), labled with the text "TKMARS". Eventuelly other devices are affected, too?

Ther is a problem with the "UD" Message, if the tracker is not moving. In this case the battery status changes the array Position and the Decoder "can not find the battery status anymore and decodes the battery status "0%".

My Tracker data from ceck… SMS:
I changed my ID ans IP to random values.
```
TK913(70ELASCD)_V_2.1 2024/05/06
ID:1234567890
IP:172.0.0.1:5093
BAT:100%
APN:iot.telefonica.de,,
GPS:0
LTE:21
,,,
```

**To Reproduce**
1. Own a TK913-4G
2. Connect the device to your server with the Watch Protocol
3. Move with the Device to get the battery status (long "UD" Message)
4. Don't move to get the wrong Status (short "UD" Message)

**Expected behavior**
I think the code example from Rob is a good approach to fix it ( https://www.traccar.org/forums/topic/watch-protocol-oddity/#post-95374 ).
Eventually there is a way to enable the code snippet with a configparameter.

**Comment by tananaev** [comment]
From what I understand it's a device bug because it the format doesn't match the documentation. Or do you have an updated documentation?

**Comment by deralexmalex** [comment]
Okay, no I didn't. But isn't it possible to define an new or modified documentation or protocol to support this device completely from stock?

**Comment by tananaev** [comment]
Your device vendor has to provide the updated documentation first before we can implement it.

**Comment by deralexmalex** [comment]
Okay. I don‘t know the vendor. Then I‘ll buy another Tracker. Thanks.
