### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by devSorcere** [traccar/traccar#5381]
I updated Traccae from 5.9 to 6.3.
so I have error
"No SMTP configuration found - MessagingException (SmtpMailManager:114 < *:99 < NotificatorMail:44 < NotificationResource:129 < ... < OverrideFilter:49 < ...)"

**Comment by tananaev** [comment]
The error doesn't seem to be related to the update. You probably put configuration in the wrong place previously.

**Comment by devSorcere** [comment]
how do I do?

**Comment by tananaev** [comment]
The error is pretty clear. You're missing SMTP configuration. We have documentation on how to configure it. Read it. If you have questions, use the forum. GitHub is only for bug reports and feature requests.

**Comment by devSorcere** [comment]
I fixed it.
thank you
