### ISSUE TITLE
Traccar 6.3 Announcement error

### ISSUE THREAD

**Issue by devSorcere** [traccar/traccar#5382]
**Describe the bug**

No SMTP configuration found - MessagingException (SmtpMailManager:114 < *:99 < NotificatorMail:44 < NotificationResource:129 < ... < OverrideFilter:49 < ...)

**To Reproduce**
1. Go to 'Announcement '
2. Input values
3. Click on 'send'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windoes 10, Ubuntu]
 - Browser [chrome,]

**Additional context**

No SMTP configuration found - MessagingException (SmtpMailManager:114 < *:99 < NotificatorMail:44 < NotificationResource:129 < ... < OverrideFilter:49 < ...)

**Comment by devSorcere** [comment]
I have install traccar and then run it.

**Comment by tananaev** [comment]
Duplicate of https://github.com/traccar/traccar/issues/5381. This is the second warning. You will be banned if you continue misusing GitHub issues.
