### ISSUE TITLE
Chart dropdown not showing on first load

### ISSUE THREAD

**Issue by legrandron** [traccar/traccar#5384]
**Describe the bug**
About 3-4 updates ago, the chart dropdown selector does not load (it is greyed out) on the first load. The dropdown being referred to is the one which enables the user to select the chart that they want, e.g Fuel, Speed etc. The user needs to first "Show" the default selected chart (Usually Speed), After that one loads, they will then be able to select other charts from the dropdown. This is a bit confusing for users and if possible, can it be reverted to how it was before where a user could simply select the chart that they want then click on "Show"

**To Reproduce**
1. Go to Reports
2. Click on Chart
3. Select Device and period
4. Chart type is greyed out

**Expected behavior**
For the chart type to be selectable on initial load

**Comment by tananaev** [comment]
This is expected behavior. We don't know what's available until we request the data.

**Comment by legrandron** [comment]
Okay thank you. Is there a way to revert to how it was before on my end? I do not mind recompiling the web app if you can kindly point me on where to edit. We had assumed it is a bug hence we had paused effecting a major update so we would like our user experience not to change if possible.

**Comment by tananaev** [comment]
You can revert to whatever version you need.
