### ISSUE TITLE
configure traccar client through url string parameters

### ISSUE THREAD

**Issue by antonymikhael** [traccar/traccar#5389]
Traccar is aweeeeeesome However one downside to to it is that it is hard for normal users to configure it . I wish there is a way to generate a link that has the basic traccar configurations embeded in like device id and server url and update frequency as well as distance that we can generate for our users that upon tapping on it it opens the traccar client and automatically fill in these data instead of having the user fill it in manually themselves. Maybe something like `configs.traccar.org?deviceid=blahblah&serverlurl=blahblah&frequency=x&distance=x&accuracy=medium`

It think this is doable and will be very helpful as the main issue I face with apps I am creating on top of traccar is that non techy users will fail to fill in their info on traccar client . Would you please consider building this into traccar ? Thanks

**Comment by tananaev** [comment]
Wrong repository.
