### ISSUE TITLE
Adding a hybrid accuracy mode in traccar client

### ISSUE THREAD

**Issue by antonymikhael** [traccar/traccar#5390]
One of the very few limitations of traccar is that the user has to switch the accuracy themselves , even though it isn't hard , But better automate it , What if traccar has a hybrid accuracy mode that while the user is stationary will use the medium accuracy and that it has it own set of configs like frequency of 900 and distance 200 but if the user moved x meters in x minutes then switch accuracy to high for maybe 5 minutes and set frequency to 20 and distance to 100 for example . This way the default settings on traccar will work much better since the location will update in real time when the user moves and when the user is stationary it will save battery .

**Comment by tananaev** [comment]
Wrong repository.

**Comment by antonymikhael** [comment]
oops sorry you are right , My apologies . Let me post on the right repo
