### ISSUE TITLE
Date Formatter input

### ISSUE THREAD

**Issue by TecSeguridad** [traccar/traccar#5397]
**Describe the bug**
When I try to modify a date in dd/mm/yyyy format in users, for example

**To Reproduce**
I write the day, the month, and then, when I'm typing the second digit of the year, a jump occurs, and the date ends up as "dd/mm/yyyy". After this, I have to delete the year, enter the day again, and then the month to make sure the date is correct and to avoid this error.

**Screenshots**

![image](https://github.com/user-attachments/assets/2c21047b-c4f0-410d-9ac8-5e45c363f161)

What is shown in the screenshot example happens after typing 01/01/20  I didn't get to type 24.

I’ve tried to fix it in formatter.js, but I haven’t been successful. Best regards

**Comment by tananaev** [comment]
Is this the latest official release without any code modifications?

**Comment by TecSeguridad** [comment]
Hello, yes Anton there is no code modifications. Thanks

**Comment by tananaev** [comment]
Fixed in https://github.com/traccar/traccar-web/commit/0b64296c0b983a05eb61db05d771018e74f219e5.

**Comment by TecSeguridad** [comment]
I noticed another issue related to the expiration date; there is a difference of 1 day between what is shown in the user list and on the account page of same user.


user list
![image](https://github.com/user-attachments/assets/d29ff8a2-a48d-4b27-ba11-6e1af6bce418)

account page
![image](https://github.com/user-attachments/assets/88dcd217-2ac1-4549-beb9-37577e395eed)


 there is no code modifications. v6.4 Thanks

**Comment by tananaev** [comment]
I think it's because one is recorded in UTC and the other one is formatted in local time.

**Comment by TecSeguridad** [comment]
Where would it be more convenient to fix it, in the account or in the devices?

**Comment by tananaev** [comment]
Probably needs to be fixed in the editor.

**Comment by TecSeguridad** [comment]
Probably
