### ISSUE TITLE
Sms for teltonika devices

### ISSUE THREAD

**Issue by jcardus** [traccar/traccar#5402]
**Is your feature request related to a problem? Please describe.**
Many teltonika devices don't have user / pass configured so the sms needs two have to spaces at the beggining.

**Describe the solution you'd like**
Send sms as is

**Describe alternatives you've considered**
Remove the trim

**Additional context**
https://github.com/traccar/traccar/blob/cc47d2a79e263d8a56ad557e8f2c501097738d53/src/main/java/org/traccar/sms/HttpSmsClient.java#L80

**Comment by truppelito** [comment]
This change has broken notifications for me. With `traccar/traccar:6.4-ubuntu` docker image, this is what Traccar sends to the HTTP endpoint when pressing "Test Channels":

```
xxx@server:~$ nc -l -p 8080
POST /my-endpoint HTTP/1.1
Content-Type: application/json
User-Agent: Jersey/3.1.7 (HttpUrlConnection 17.0.12)
Host: 10.2.3.4:8080
Accept: */*
Connection: keep-alive
Content-Length: 41

{"tag": "traccar", "body":"Test message"}^C
```

This is what happens with `traccar/traccar:6.5-ubuntu`:

```
xxx@server:~$ nc -l -p 8080
POST /my-endpoint HTTP/1.1
Content-Type: application/json
User-Agent: Jersey/3.1.7 (HttpUrlConnection 17.0.12)
Host: 10.2.3.4:8080
Accept: */*
Connection: keep-alive
Content-Length: 41

{"tag": "traccar", "body":"Test message
"}^C
```

Note the extra newline. As a result, the JSON payload is invalid and the POST request errors out.
