### ISSUE TITLE
Suntech protocol add KEY_BLOCKED

### ISSUE THREAD

**Issue by juniormelo26** [traccar/traccar#5406]
**Is your feature request related to a problem? It is not a problem but a suggestion. Please describe.**
When sending the lock command to suntech, Ex: (ST310UC2). The equipment returns the value 1 at output1.

**Describe the solution you'd like**
The suggestion would be to add KEY_BLOCKED based on this result.

**Describe alternatives you've considered**
The idea would be this below:
` position.set(Position.KEY_BLOCKED, io.charAt(4) == '1'); // add for info blocked based on output 1 `

**Additional context**
This way we would have a return with the information BLOCKED true or false on the details page and in the equipment positions.
![Preview de page Position(details)](https://i.imgur.com/XAQA2Qe.png)

**Comment by tananaev** [comment]
Do you have documentation available to show this is correct?

**Comment by juniormelo26** [comment]
Not explicitly, but as defined in the traccar protocol itself in the TYPE_EGINE_STOP command. This command activates output1 and blocks the vehicle.
` case Command.TYPE_ENGINE_STOP ->
                    formatCommand(command, prefix + "CMD;%s;02;Enable1\r", Command.KEY_UNIQUE_ID);`


![excerpt from documentation](https://i.imgur.com/x7HcvIs.png)

**Comment by tananaev** [comment]
That was done almost 10 years ago. It doesn't seem correct either, but we probably didn't have the same command options as we do now, so it was probably a workaround. We have a proper output command now.

**Comment by juniormelo26** [comment]
I understand Anton, this is just a suggestion, as this way we would have more information about whether the vehicle is blocked or not, and which would be appropriate and could this not be attributed to KEY_BLOCKED? the image below is from a current document 2024-07. 
The intention is not to be boring but to always contribute.
[Link Protocol Document](https://drive.google.com/file/d/1wHrlHqYl-5jFYsHrwswI3rqLSto0KRxp/view?usp=sharing)
![Below is a link to the document.](https://i.imgur.com/vlPGTph.png)

**Comment by tananaev** [comment]
The right way of doing this is using computed attributes.
