### ISSUE TITLE
Flag notifications that use the Command channel.

### ISSUE THREAD

**Issue by Turbovix** [traccar/traccar#5411]
**Is your feature request related to a problem? Please describe.**
Whenever notifications are created that use the "Command" channel, these notifications are stored without a way to identify them later, that is, what does this command do?, so think about it if there are many, it is almost impossible to assign them to devices.

**Describe the solution you'd like**
I think it would be interesting to have an "Observation:" field and in this we could put what that Notification/Command is about.

**Describe alternatives you've considered**

**Additional context**

**Comment by tananaev** [comment]
What do you think about adding a "description" field to notifications? This is something we've done as a customization in the past, but seems like a pretty common issue.

**Comment by Turbovix** [comment]
I believe it should resolve.

**Comment by Turbovix** [comment]
Funcionou perfeitamente. Obrigado!
