### ISSUE TITLE
CJ730 Plus 4G (H02 protocol) can activate relay but cannot deactivate

### ISSUE THREAD

**Issue by slydiman** [traccar/traccar#5417]
**Describe the bug**
Traccar server v5.12
Connected the device `CJ730 Plus 4G` (H02 protocol, port 5013)
The command `Engine Stop` (activate the relay) works just fine .
The command `Engine Resume` (deactivate the relay) does not work. It is possible to deactivate the relay by SMS `666`.

**To Reproduce**
1. Activate the relay on the device by sending the command `Engine Stop` via the device toolbar or by SMS `555`.
2. Send the command `Engine Resume`.
3. Nothing happened.

**Expected behavior**
The relay must be deactivated.

**Desktop:**
 - OS: Windows
 - Chrome
 - Version 128.0.6613.138

**Additional context**
I see the following in logs after sending commands `Engine Stop` and `Engine Resume`:
```
2024-09-21 03:43:13  INFO: [T4481de22] id: 734000xxxx, command type: engineResume sent
2024-09-21 03:43:13  INFO: [T4481de22: h02 > xx.249.25.83] 2a48512c373334303030xxxxxxxx2c5332302c3033343331332c312c3023
2024-09-21 03:43:13  INFO: [T4481de22: h02 < xx.249.25.83] 2a48512c373334303030xxxxxxxx2c56342c5332302c3033343331332c312c3123

2024-09-21 03:43:15  INFO: [T4481de22: h02 < xx.249.25.83] 24734000xxxx234315200924xx321436000xx213275e000176f7ffffffff041f000000000001cc00ff000015007d0000000035
2024-09-21 03:43:15  INFO: [T4481de22] id: 734000xxxx, time: 2024-09-21 03:43:15, lat: xx.53573, lon: xx.35546, course: 176.0

2024-09-21 03:43:20  INFO: [T4481de22] id: 734000xxxx, command type: engineResume sent
2024-09-21 03:43:20  INFO: [T4481de22: h02 > xx.249.25.83] 2a48512c373334303030xxxxxxxx2c5332302c3033343332302c312c3023
2024-09-21 03:43:20  INFO: [T4481de22: h02 < xx.249.25.83] 2a48512c373334303030xxxxxxxx2c56342c5332302c3033343332302c312c3123
```
I see the following in logs after SMS `666` which deactivated the relay:
```
2024-09-21 03:44:16  INFO: [T4481de22: h02 < xx.249.25.83] 24734000xxxx234415200924xx321339000xx213043e000210f7ffffffff041f000000000001cc00ff000014007d0000000038
2024-09-21 03:44:16  INFO: [T4481de22] id: 734000xxxx, time: 2024-09-21 03:44:15, lat: xx.53557, lon: xx.35507, course: 210.0
```

**Comment by tananaev** [comment]
You have to check the latest version first. And also provide the protocol documentation.

**Comment by slydiman** [comment]
@tananaev 
The line `formatCommand(time, uniqueId, "S20", "1", "0");` in H02ProtocolEncoder.java is the same for last 6 years, 
so there is no any functional change after v5.12.
I have no any protocol documentations. 
I guess the correct command must be `formatCommand(time, uniqueId, "S20", "0", "0");` as it was 8 years ago. 
Do you have the clear documentation for this change https://github.com/traccar/traccar/commit/735fc1483817da385dce0fb572440261b6a644a3 ?

**Comment by slydiman** [comment]
[The documentation](https://www.traccar.org/protocol/5013-h02/GPS+Tracker+Platform+Communication+Protocol-From+Winnie+HuaSunTeK-V1.0.5-2017.pdf) is not clear.
```
cut off oil-engine/recovery oil&engine(S20) 
*XX,YYYYYYYYYY,S20,HHmmss,C,T# 
C: Ultimate power mode. 1 or other digits: Static cut off oil&engine,no engine detection,power relay always pull in, turn off the circuit 
T: cut off or recovery 0 represents recovery,1 represents cut off 
```
`1 or other digits` sounds strange.
The documentation:
```
Finally is completely power off, and according to the C provision way to keep power off, after complete power off then return information 
*HQ,2020916012,V4,S20,80,130305,050316,A,2212.8745,N,11346.6574, E,14.28,028,220902,F7FFFBFF, 460,000,27A6,0F70# 
```
But I got the following response for `Engine Stop`: `*HQ,734000xxxx,V4,S20,034313,1,1#`
and the same for `Engine Resume`. Note there is no unknown `80` between `S20` and time. Probably `1,1` at the end is the current status. So it is possible to check that the command was successful.

**Comment by tananaev** [comment]
So it looks like the format of the command is correct according to this documentation. I'm going to close for now. If you find out some other documentation that shows that something is incorrect in Traccar, feel free to reopen the ticket.

**Comment by slydiman** [comment]
It seems arm/disarm will not work too because of different commands `SCF` and `S6`.

**Comment by slydiman** [comment]
And you can check the response. I got the response `*HQ,7340000000,V4,S20,034320,1,1#` to the command `Engine Resume`, which means FAILED.

**Comment by tananaev** [comment]
Well, we need documentation that will show what's wrong in the current implementation.

**Comment by slydiman** [comment]
[Here is the protocol H02 for MT532](https://www.mictrack.com/downloads/protocols/Mictrack_Communication_Protocol_For_MT532.pdf) which uses the command `*HQ,8168000005,S20,061713,0,0#` to restore engine.
First digit 0 means SAFE method with checking the current status (probably speed).
From other documentation:
```
C: represent final way to Diable Fuel or Electricity:
C=0：represent Dynamic Diable Fuel or Electricity, Once detected engine instantaneous operation to Diable Fuel or Electricity for 5 seconds, compel the engine to stop.
C=1 or other number: represent static Diable Fuel or Electricity. No need detect engine status, relay always close to Diable Fuel or Electricity.
```
So `...,0,0#` must work for all trackers and it is the best option. Note it was in traccar 6 years ago.

**Comment by tananaev** [comment]
Which other documentation?

**Comment by slydiman** [comment]
https://www.traccar.org/protocol/5013-h02/h02_cantrack_secumore.pdf

**Comment by tananaev** [comment]
OK. But how did you make this conclusion?

> So `...,0,0#` must work for all trackers and it is the best option.

Most documents show 1 and not 0. Also SAFE method doesn't make sense to me for resuming operation.
