### ISSUE TITLE
Send Device Commands with Watch Protocol

### ISSUE THREAD

**Issue by strangerCatLv** [traccar/traccar#5418]
**Describe the bug**
how to use send device command witch traccar API. if i want send the data `[3G*9505278414*002C*PHB,081123456789,Zoe,08987654321,yudhi,,,,,,]` from watch protocol??
how about the URL API and the raw data? 

i use URL `https://x.x.x.x:xxxx/commands/send`

**Desktop (please complete the following information):**
 - OS: Linux
- version : Ubuntu 22.04.2 LTS

**Comment by tananaev** [comment]
For questions you should use the forum.
