### ISSUE TITLE
is web app repo needed?

### ISSUE THREAD

**Issue by pool2mine** [traccar/traccar#5438]
Hello guys,

Just installed TRACCAR Server and currently testing it... but i was checking out your github and i see a separate repo called traccar-web. I was confused as i just finalized installing the server and it does include a web interface. Do i still have to install traccar-web repo? I see that it was recently updated so I would like to know what's the difference with the one included on the server repo.

**Comment by tananaev** [comment]
The installer does include both the backend and the web app.

**Comment by pool2mine** [comment]
I'm sorry to bother again, but i still have not clear where the website is stored... i see the traccar.conf file points to /var/www but it's clearly not there... So i found a folder in the installation directory "opt/traccar/web".

but inside that folder i changed all the images and only the favicon was shown in my website... al the rest of the logo files did not change. i cleared cache and cookies, still nothing. when i try to do it on the server/attributes page, i can see the image but after reloading i lose it.

so i am assuming that if i just replace the image files i should then have to make a rebuild of the site... can you please tell me how to do it?

**Comment by tananaev** [comment]
For questions please use the forum. GitHub issues are reserved for bugs and feature requests.
