### ISSUE TITLE
Configuration File to enable new protocol

### ISSUE THREAD

**Issue by asigint** [traccar/traccar#5448]
Hi All,
i just created a new protocol, and added this line to conf/traccar.xml 

 <entry key='protocols.enable'>asi</entry>
 <entry key='asi.port'>2101</entry>

 But I'm not able to have this port listen. Do I have to enable the protocol in some other sort of file? Where to change in debug and in production? 

Regards,
Gianmaria

**Comment by tananaev** [comment]
For questions please use the forum.
