### ISSUE TITLE
Motion reporting when the car is parked

### ISSUE THREAD

**Issue by kiko-ops** [traccar/traccar#5449]
Hello Everyone,

We have installed traccar on a computer and we have version 64-5.9 and we use FMC teltonic devices. The problem we have is that the car from the parking lot is reporting movement and kilometers (
<img width="405" alt="Untitled" src="https://github.com/user-attachments/assets/93cb332c-0ac5-42cd-9019-32e54db0322f">
attached). Any solution for this problem?

Thanks

<img width="405" alt="Untitled" src="https://github.com/user-attachments/assets/ee7879d6-f901-4404-9e9e-5c35f5260c12">

**Comment by tananaev** [comment]
Use the forum for questions.
