### ISSUE TITLE
 Use Traccar Protocol for Listening on a Specific Port and Decoding Raw Data from S20 GPS Device

### ISSUE THREAD

**Issue by BenTrinidad** [traccar/traccar#5452]
Hi Traccar team,

I would like to use Traccar's existing protocol-handling capabilities to listen on a specific port for my S20 GPS device and decode the raw data that the device sends. Specifically, I would like to:

Set up Traccar to listen to a specific port that the S20 GPS device communicates on.
Use the appropriate Traccar protocol or class to decode and parse the raw data that the device sends.

Could you provide guidance on how to configure the protocol for this device and the steps required to decode and parse the data using Traccar's protocol classes?

Thank you for your help!

**Comment by tananaev** [comment]
Please use the forum for questions.
