### ISSUE TITLE
Unknown device does not appear in the LOGS report Version 6.5

### ISSUE THREAD

**Issue by juniormelo26** [traccar/traccar#5459]
**Describe the bug**
Unknown device, no longer appears in the log report.

**To Reproduce**
1. Go to 'Log report'
2. See error 'No more logs appear for the Unknown device

**Expected behavior**
I expected the line with the device identifier to be clickable to add.

**Screenshots**
![Server Image LOG](https://i.imgur.com/pYyqylo.png)

![Front Image LOG](https://i.imgur.com/qonp4xL.png)

**Comment by tananaev** [comment]
Are you sure you set `web.showUnknownDevices` to `true`?

**Comment by juniormelo26** [comment]
Sorry Anton, I didn't have this option enabled. After enabling it works.
