### ISSUE TITLE
Error in OsmAnd documentation

### ISSUE THREAD

**Issue by robin-thoni** [traccar/traccar#5463]
**Describe the bug**
 
The [doc](https://www.traccar.org/osmand/) specifies:

> `wifi`: WiFi access point information in the format "macAddress:signalStrength".

However, the [code](https://github.com/traccar/traccar/blob/master/src/main/java/org/traccar/protocol/OsmAndProtocolDecoder.java#L120) says:

```java
String[] wifi = value.split(",");
```

**To Reproduce**
Send a `:` separated request, and the connection will close unexpectedly. Works well w/ a `,`, as expected.

**Comment by tananaev** [comment]
The documentation is correct, but incomplete. The format for each access point is "macAddress:signalStrength", but you can have multiple ones separated by a comma.

What exactly didn't work? Please provide a specific request example.
