### ISSUE TITLE
Startek protocol - continue to capture driverId

### ISSUE THREAD

**Issue by Theerayuttu** [traccar/traccar#5477]
Refer this issue: https://www.traccar.org/forums/topic/startek-protocol-driveruniqueid-after-event-swiping-card/

to support continue to capture driver Id when event card is swiped.

Document: 
[iStartek Protocol for DLT Function User Guide.pdf](https://github.com/user-attachments/files/18089355/iStartek.Protocol.for.DLT.Function.User.Guide.pdf)

example log:
```
26264c3137312c3836383832353036343238323034302c3030302c302c2c3234313230393036333330322c412c31332e3830393635362c3130302e3535383235352c31342c302e392c302c302c36372c313536302c3532307c347c413431387c30303841414333462c33312c30303030303042442c30322c30302c303445337c303137317c303030307c303030302c3133312c2c2c2c33313030202031202036313030303534312020313038303020203f46450d0a
```

**Comment by Theerayuttu** [comment]
Is it possible to support this request?

**Comment by tananaev** [comment]
What do you mean?

**Comment by Theerayuttu** [comment]
Sorry, I mean could you confirm if this request is feasible? Is there any additional information you require.

**Comment by tananaev** [comment]
It is feasible, of course.

**Comment by Theerayuttu** [comment]
Thank you Anton,
Can you help us with this request? are there any costs?

**Comment by tananaev** [comment]
If you want to sponsor the implementation, you can email us. Otherwise you can just wait until we get enough interest from the community and implement it.

**Comment by Theerayuttu** [comment]
Okay, I will email to you. thank you.

**Comment by Theerayuttu** [comment]
Thank you very much Anton, 
Not sure, if we want to test and use it right away, do we have to build server source ourselves?

**Comment by tananaev** [comment]
You can try the preview version:

https://www.traccar.org/preview/

**Comment by Theerayuttu** [comment]
> You can try the preview version:
> 
> https://www.traccar.org/preview/

thanks again Anton, I tried to do build it myself, but still it didn't work. 555.
![Screenshot 2024-12-14 125522](https://github.com/user-attachments/assets/e7f1de5e-a119-42e5-ac13-d47af1933995)
