### ISSUE TITLE
 I can't link my FMC920 to my server.

### ISSUE THREAD

**Issue by tutumano** [traccar/traccar#5481]
*
*Describes the error**
A clear and concise description of what the error is. Don't link to my server.

**To play**
1. I have the installation using a script:
https://community-scripts.github.io/ProxmoxVE/scripts?id=traccar

2.- I can access the server and register without problem through its corresponding port 8082.

3.- I have tried to connect to my server through Cloudfare, and when it does not work, also through the NO-IP.com server, since I have a Dynamic IP.

4.- Both through Cloudfare and through my No-Ip domain I access without problems the main page of traccar, where I add the unique IMEI of the FMC920.

5.- I have configured the FMC920 through a traccar demo server, and it linked me without problems and on the first try. 

**Expected behavior**

I have the problem installing traccar in proxmox, and I don't know where in the installation and I don't know how to solve it.

**Additional context**
If you need any other information to help, feel free to ask me.

Thank you very much

**Comment by tananaev** [comment]
This doesn't sound like Traccar bug. For discussions you should use the forum instead.
