### ISSUE TITLE
Aspicore protocol support

### ISSUE THREAD

**Issue by grisxa** [traccar/traccar#584]
Hi!
Does Traccar server support Aspicore GSM Tracker for Symbian ( http://aspicore.com/?lang=en#download )?
It sends commands like this:

```
IMEI 354183021376658
No GPS info
CurCell 7972823 LAC 7808 Name MegaFon MCC 250 MNC 02 MODE 6 SSI 68
*74025D76
IMEI 354183021376658
$GPRMC,200129.694,V,,,,,,,270214,,,N*4C
CurCell 7972823 LAC 7808 Name MegaFon MCC 250 MNC 02 MODE 6 SSI 68
*EC84096A
IMEI 354183021376658
$GPRMC,200137.098,A,6000.00733,N,03015.88164,E,,,270214,,,A*6F
$GPGGA,200134.000,,,,,0,,,,,,,,*7C
CurCell 7972823 LAC 7808 Name MegaFon MCC 250 MNC 02 MODE 6 SSI 68
*C0FA3D92
```

The protocol is described here: http://www.aspicore.com/support/gsmtrckr/default.htm#udp_protocol_description and I guess OpenGTS supports it as of version 2.2.6: http://sourceforge.net/projects/opengts/files/server-base/2.2.6/OpenGTS_2.2.6.txt/view

**Comment by pedro1066** [comment]
Hi.
I want to connect a nokia c6 (symbian 60) with traccar. I trying to figure it out with the Aspicore GSM Tracker for Symbian but I cannot connect it to my traccar server. I have some questions regarding this. 
1- what is the identifier ? (I am using the full nokia's imei number, is it correct?)
2- If I go to settings > Net I filled out the server and port with my server's ip and use the port 5055 (as per comments above:  T55 decoder) is it ok?
3- what else need to be filled out?
thanks in advance for your help
greetings!
Roger

**Comment by tananaev** [comment]
1. Should be, but you can also check logs to find out if it's different.

2. Port for T55 protocol is 5005, not 5055.
