### ISSUE TITLE
GT02A Clone issue with traccar

### ISSUE THREAD

**Issue by claugira1** [traccar/traccar#606]
Hello, I´m testing traccar, and I think it´s a very usefull tool, I already test it with a TK102 GPS Tracker, now I´m installing a GT02A Clone, but no data is sended, I have proved 8821, 20488, 5002, 5013, 5022 ports and nothing, when I´m going to the tracker-server file, I see since I change de GPS there is not data information, nothing.  The GPS is working fine, GPRS is connection, but I dont know why the data is not send to traccar.
Somebody know how I can fix it?

**Comment by jimmyhuynz** [comment]
I have the same issue. I can receive the hex code from GT02A, but i can not display it on the traccar

**Comment by jimmyhuynz** [comment]
Debug has this one: 2016-06-18 00:21:30 DEBUG: [61C2EC5E: 5006 < 118.149.177.161] HEX: 283032373034333433363533344252303031363036313841343632352e393337385331363832332e31383537453034352e3130343231323939302e35313030303030303030304c303030303030303029

**Comment by tananaev** [comment]
@jimmyhuynz, you are using incorrect port. Correct one is 5002 and your device id is `027043436534`.

Please next time create a new issue instead of commenting on an old closed thread.

**Comment by jimmyhuynz** [comment]
oh thank you. i will try again.
