### ISSUE TITLE
Delete old records

### ISSUE THREAD

**Issue by netomx** [traccar/traccar#63]
Any way to delete the old records? Thank you

**Comment by peptoni** [comment]
Hi, sorry to reopen this question.
I would like to delete records older than certain date.  It seems that the configuration file does not contain the key database.initialize anymore.  ¿What is the best way to execute a purge sentence...?
Thank you very much.

**Comment by tananaev** [comment]
I think the best way at the moment is to use MySQL database and have a separate task that will clean up old records.

**Comment by peptoni** [comment]
OK.  Thanks for the answer.  Right now, I'm test running Traccar on an Amazon EC2 linux virtual machine.  It works very nice, with very low resource usage.  I would prefer not to switch to MySQL, but I guess I will have to.  Thanks very much for your great work.

**Comment by borhanreo** [comment]
I did not found in  default.xml
`<entry key="database.initialize">`
