### ISSUE TITLE
EV603 GPS Support

### ISSUE THREAD

**Issue by hackerunet** [traccar/traccar#64]
Hi anton, here is another device that maybe you could add some support in the future.
regards.
http://ubicatugps.com/manual/EV601FullProtocols.doc
By the way, this GPS sends the IMEI only the first time it communicates with the server, the rest of the time its only sending the latitud, longitud, speed, degrees data, plus a couple of things, but no ID or IMEI is ever sent again.
Thanks

**Comment by ahmedtab** [comment]
Hello
When I registry ev603 device firmware V03.103.06.1412 it doesn’t work. It is sending
!C,30/1/16,1:1:6,31.259157,30.020910,0,0,100001,25.32,100,0.03,0.01,0;
I modified MiniFinderProtocolDecoder.java
Line 36  .expression("![A-D],")
Line 65  add || sentence.startsWith("!C") in if statment
It works fine now. Are there any suggestions?
Thanks

**Comment by tananaev** [comment]
@ahmedtab, I have implemented your suggestion. Please next time create a new issue instead of reviving 4 years old thread.
