### ISSUE TITLE
Protocol DYTECH ( china GPS tracker GT02A )

### ISSUE THREAD

**Issue by BersBaD** [traccar/traccar#661]
Hello! 

Lucky enough to buy this wonderful device [GPS tracker GT02A](http://www.aliexpress.com/item/Guaranteed-100-4-band-car-GPS-tracker-GT02A-Google-link-real-time-tracking-free-shipping/1257279802.html), which in fact does not support the protocol "GT02A", and uses its :( ... [Protocol DYTECH](https://drive.google.com/file/d/0BydVV-voIdj-TUJQYnNoSl9walk/edit?usp=sharing) 

After correspondence with the supplier ... they have kindly given me the protocol description [DYTECH](https://drive.google.com/file/d/0BydVV-voIdj-TUJQYnNoSl9walk/edit?usp=sharing). 

Hope you can add it :) ?

Sorry for my not native English.

**Comment by johansid** [comment]
Anyone use this device has a send data problem?
after several hours, it stop send data and i should send apn setting to make this device wake up.
