### ISSUE TITLE
I'm using Locus Pro Android client (with Live-Tracking)

### ISSUE THREAD

**Issue by marcwlux** [traccar/traccar#742]
I'm using Locus Pro Android client. Is it possible to upload positions via http get or post requests?
Is there any known device/protocol working like this?
some infos here:
http://support.locusmap.eu/hc/en-us/articles/200050282-Live-Tracking

thank you

**Comment by xjhelp** [comment]
如何让队员位置在locus种显示呢？

**Comment by xjhelp** [comment]
如何让队员位置在locus map软件显示呢？
我使用过其它类似跟踪系统，加载一个包含有网址的kml文件就可以显示，在谷歌地球种也能加载显示
