### ISSUE TITLE
Features implementation request

### ISSUE THREAD

**Issue by jekyll2014** [traccar/traccar#758]
From the point of view of hiker/bicycle rider I'd like to see the following features:
Server side:
1) several tracks visualization at one screen - it's useful to see several sportsmen during the orienteering competition (for example)... This case tracks must be drawn with different colors (set in the preferences of each object or system decides).
2) exporting selected object track into any well known file format (GPS, KML, PLT).
3) Autorefreshing the tracks on the screen (by a special check-box) - this will make observing a group of objects a little more comfortable.
4) "Observer" mode to see a set of tracks without logging in - useful to demonstrate a competition to a wide auditory. Observer have no control - it can only select which object's track he would like to see on the screen.
Client side:
1) buffering the outbound to send it as soon as connection available - it's better to have a full details of one's track even if mobile network connection is poor in some areas. It'll need to modify the client-server protocol to have a feedback or it's possible to save the track locally on the phone and synchronize it later with server on a manual request (when at home with stable WiFi connection). It is also possible to check if the system has Internet connection (server ping?) before sending the string to server.

**Comment by tsmgeek** [comment]
2. ive seen an API call for this (not used it) just does not seem to be implemented in the WebUI
3. position updates should be realtime, i can see my devices move without me doing anything
4. create a user with 'ReadOnly' flags set on account etc, this would prevent changes, then allow that user to see all the required devices you want.
5. normally GPS trackers buffer their updates if they lose connection to server, once they connect they upload all their old tracks. There is an issue I have seen is that some trackers will push the latest position firt then send the buffer once it reconnects, I think this does not work with traccar as it will throw the old tracks away, not sure but I remember someone else asking the same thing.

**Comment by tananaev** [comment]
We've just added KML support. I know it's a very old ticket, but if the requests are still relevant please break them down into separate tickets.
