### ISSUE TITLE
ACC status in GT06

### ISSUE THREAD

**Issue by DeanChugall** [traccar/traccar#760]
Greetings,

please, is already implemented ACC status in GT06 protocol. From source code I can see that is in `extendedInfo.set("acc", (flags & 0x2) != 0);` fields. Am i right or ?

Just one more Q. if this true, can I separate this filed, and can you give me short info how to achive that?

Thank you.

**Comment by saulo1212** [comment]
Hi!
I started a project with gt06, I'm getting the localization package,

<Buffer 78 78 1f 12 15 04 11 0d 3a 38 c9 01 d9 66 a4 05 07 04 8c 00 18 00 02 d4 02 51 02 00 ad 9a 00 f5 4c 16 0d 0a>

how to extract the inginition status on or off, I was confused by the documentation

**Comment by saulo1212** [comment]
Hi!
I started a project with gt06, I'm getting the localization package,

<Buffer 78 78 1f 12 15 04 11 0d 3a 38 c9 01 d9 66 a4 05 07 04 8c 00 18 00 02 d4 02 51 02 00 ad 9a 00 f5 4c 16 0d 0a>

how to extract the ignition status on or off, I was confused by the documentation
