### ISSUE TITLE
SkyPatrol TT8750 UDP-5021

### ISSUE THREAD

**Issue by penag** [traccar/traccar#791]
I’m trying to connect SkyPatrol TT8750 but I have this entry in the server log. What that’s mean ?
```
2014-07-19 17:40:23 DEBUG: [5021 <- 186.169.1.223] - HEX: 00040200202020202020202020382020202020202030313137323230303131383531373820313220244750524d432c3232343833392e30302c412c303332382e3433383830362c4e2c30373633312e3630373731372c572c302e302c302e302c3139303731342c332e382c452c412a32420d0a00
```
The HEX code to ascii is : 

[1]         `8       011722001185178 12 $GPRMC,224839.00,A,0328.438806,N,07631.607717,W,0.0,0.0,190714,3.8,E,A*2B`

The “8” is the 8 in the EVENT (see below), “011722001185178” is the IMEI and the “12” before $GPRMC is the 12 in the EVENT (see below).

At the TT8750 I’m using `AT$EVENT=12,3,42,8,4230` (change 52 by 42 due to is UDP port 5021 not TCP)

Thanks in advance for your help.

**Comment by BETINTGO** [comment]
Hello Penag and tananaev apology to bother you but I have searched more scrip not give that report data traccar one TT8750, YOU CAN help me with a script you have.
thx

**Comment by tananaev** [comment]
Unfortunately I know very little about SkyPatrol device configuration.

Make sure you enable mask field in reports otherwise it's impossible to decode messages from device on the server side.

**Comment by cesarnava** [comment]
Hello. I test a TT8750 in both ports (5021 and 5008), and none works for me. The Log of my server is:

2015-04-09 15:31:47 DEBUG: [E3331A91: 5021 <- 187.237.39.19] - HEX: 000502000000000220202020202020204e53323530323933443131333320d1df002f00000d01612f011d8dcfff689d1a000000000319880009ec0800000000

**Comment by orly1387** [comment]
Amigo Penag favor me podría ayudar con la configuración del equipo para que se pueda reportar en TRACCAR.

**Comment by guifer01** [comment]
Good Morning, I was testing this skypatrol TT8750+ GPS and i have the same problem, could you share how you solve the problem, thanks,

I receave the same problem

2017-08-16 07:47:57 DEBUG: [2D6E54B0: 5021 < 190.113.210.54] HEX: 0005020000000000012020202020202020202020545438373530506c757320

thanks

**Comment by pableras99** [comment]
Good night, I was testing this skypatrol TT8750+ GPS and i have the same problem, could you share how you solve the problem, thanks,

**Comment by penag** [comment]
Hello everybody, sorry for my late answer. I'm making a litle change in the script due to 8750 and 8750+ are different. Please take into account this isn't last version of traccar. 

full script :  (This works for me)

public class SkypatrolProtocolDecoder extends BaseProtocolDecoder {

    private static final Pattern patternGPRMC1 = Pattern.compile(
    	    "GPRMC," +
            "(\\d{2})(\\d{2})(\\d{2}).(\\d{2})," + // Time (HHMMSS.SS)
            "([AV])," +                  // Validity
            "(\\d{2})(\\d{2}.\\d{6})," + // Latitude (DDMM.MMMMMM)
            "([NS])," +
            "(\\d{3})(\\d{2}.\\d{6})," + // Longitude (DDDMM.MMMMMM)
            "([EW])," +
            "(\\d+.\\d)?," +             	// Speed
            "(\\d+.\\d)?," +             	// Course
            "(\\d{2})(\\d{2})(\\d{2})," +	 // Date (DDMMYY)
            "(\\d+.\\d)?," +            	
            "([EW])," +                      
            "([AV])" +	   					// Validity
    	    "\\*([0-9,A-F]{2})" +			// checksum
    	    "[\r\n\u0000]*" +
    	    "(\\s{1,11}+\\d{1,11}$)" );

    private static final Pattern patternGPRMC2 = Pattern.compile(
    	    "GPRMC," +
            "(\\d{2})(\\d{2})(\\d{2}).(\\d{2})," + // Time (HHMMSS.SS)
            "([AV])," +                  // Validity
            "(\\d{2})(\\d{2}.\\d{5})," + // Latitude (DDMM.MMMMMM)
            "([NS])," +
            "(\\d{3})(\\d{2}.\\d{5})," + // Longitude (DDDMM.MMMMMM)
            "([EW])," +
            "(\\d+.\\d+)?," +             	// Speed
            "(\\d+.\\d+)?," +             	// Course
            "(\\d{2})(\\d{2})(\\d{2}),,," +	 // Date (DDMMYY)
    	    "([A-F])" +						// 
    	    "(\\*[A-F,0-9]{2})" +			// checksum
    	    "([0-9 ]{1,12}$)" );
    
    private final long defaultMask;

    public SkypatrolProtocolDecoder(SkypatrolProtocol protocol) {
        super(protocol);
        defaultMask = Context.getConfig().getInteger(getProtocolName() + ".mask");
    }

    private static double convertCoordinate(long coordinate) {
        int sign = 1;
        if (coordinate > 0x7fffffffL) {
            sign = -1;
            coordinate = 0xffffffffL - coordinate;
        }

        long degrees = coordinate / 1000000;
        double minutes = (coordinate % 1000000) / 10000.0;

        return sign * (degrees + minutes / 60);
    }

    @Override
    protected Object decode(
            Channel channel, SocketAddress remoteAddress, Object msg) throws Exception {

        ChannelBuffer buf = (ChannelBuffer) msg;

        int apiNumber = buf.readUnsignedShort();
        int commandType = buf.readUnsignedByte();
        int messageType = BitUtil.from(buf.readUnsignedByte(), 4);
        long mask = defaultMask;
        if (buf.readUnsignedByte() == 4) {
            mask = buf.readUnsignedInt();
        }
        
        // Binary position report
        if (apiNumber == 4 && commandType == 2 && messageType == 1) {
  
            Integer start = ChannelBufferTools.find(buf, 0, buf.readableBytes(), "GPRMC");
            if (start == null) {
                // Message does not contain GPS data
                return null;
            }
            int end = buf.capacity() - (start+1) + 1;
            String sentence = buf.toString(start, end, Charset.defaultCharset());
            
            boolean plus = false;
            
            Matcher parser = patternGPRMC1.matcher(sentence);                
            	if (!parser.matches()) {                    
                    parser = patternGPRMC2.matcher(sentence);                	
                	if(!parser.matches()){
                            // No valid NMEA data
                            return null;
                        }                    
                    plus = true;                           
                }
            
            Position position = new Position();
            position.setProtocol(getProtocolName());    
            
            //act1 (eventid)
            String act1 = buf.toString(buf.readerIndex(), 11, Charset.defaultCharset()).trim();         
            buf.skipBytes(15);
            
            String imei = buf.toString(buf.readerIndex(), 18, Charset.defaultCharset()).trim();            
            buf.skipBytes(20);
            
            if (!identify(imei, channel, remoteAddress)) {
                return null;
            }
            position.setDeviceId(getDeviceId());           
   
            int index = 1;
                
            // Time
            Calendar time = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
            time.clear();
            time.set(Calendar.HOUR_OF_DAY, Integer.valueOf(parser.group(index++)));
            time.set(Calendar.MINUTE, Integer.valueOf(parser.group(index++)));
            time.set(Calendar.SECOND, Integer.valueOf(parser.group(index++)));
            time.set(Calendar.MILLISECOND, Integer.valueOf(parser.group(index++)) * 10);

            // Validity
            position.setValid(parser.group(index++).compareTo("A") == 0);

            // Latitude
            Double latitude = Double.valueOf(parser.group(index++));
            latitude += Double.valueOf(parser.group(index++)) / 60;
            if (parser.group(index++).compareTo("S") == 0) latitude = -latitude;
            position.setLatitude(latitude);

            // Longitude
            Double longitude = Double.valueOf(parser.group(index++));
            longitude += Double.valueOf(parser.group(index++)) / 60;
            if (parser.group(index++).compareTo("W") == 0) longitude = -longitude;
            position.setLongitude(longitude);

            // Altitude
            position.setAltitude(0.0);

            // Speed
            String speed = parser.group(index++);
            if (speed != null) {
                position.setSpeed(Double.valueOf(speed));
            } else {
                position.setSpeed(0.0);
            }

            // Course
            String course = parser.group(index++);
            if (course != null) {
                position.setCourse(Double.valueOf(course));
            } else {
                position.setCourse(0.0);
            }

            // Date
            time.set(Calendar.DAY_OF_MONTH, Integer.valueOf(parser.group(index++)));
            time.set(Calendar.MONTH, Integer.valueOf(parser.group(index++)) - 1);
            time.set(Calendar.YEAR, 2000 + Integer.valueOf(parser.group(index++)));
            position.setTime(time.getTime());
            
            if (plus) 	{ index = index + 2;}
            if (!plus) 	{ index = index + 4;}
          
            // Odometer
            String odometer = parser.group(index++).trim();              
            long odom = 0;
            if (odometer != null && !odometer.isEmpty()) {
                odom = Long.valueOf(odometer);
            } 
            
            position.setOdometer(odom); 
            position.setEvent(getEventDescription(position, act1));
                       
            position.set(Event.KEY_ODOMETER, odom);
            position.set(Event.KEY_EVENT, act1);

            //Log.info(position.getProtocol() + " - Device id/IMEI : " + position.getDeviceId() + "/" + imei);   
            
            return position;
            
        }

        // Binary position report
        if (apiNumber == 5 && commandType == 2 && messageType == 1 && BitUtil.check(mask, 0)) {

            Position position = new Position();
            position.setProtocol(getProtocolName());

            if (BitUtil.check(mask, 1)) {
                position.set(Event.KEY_STATUS, buf.readUnsignedInt());
            }

            String id;
            String odometer = "0";
            String event = "N/A";
            
            if (BitUtil.check(mask, 23)) {
                id = buf.toString(buf.readerIndex(), 8, Charset.defaultCharset()).trim();
                buf.skipBytes(8);
            } else if (BitUtil.check(mask, 2)) {
                id = buf.toString(buf.readerIndex(), 22, Charset.defaultCharset()).trim();
                buf.skipBytes(22);
            } else {
                Log.warning("No device id field");
                return null;
            }
            if (!identify(id, channel, remoteAddress)) {
                return null;
            }
            position.setDeviceId(getDeviceId());

            if (BitUtil.check(mask, 3)) {
                buf.readUnsignedShort(); // io data
            }

            if (BitUtil.check(mask, 4)) {
                buf.readUnsignedShort(); // adc 1
            }

            if (BitUtil.check(mask, 5)) {
                buf.readUnsignedShort(); // adc 2
            }

            if (BitUtil.check(mask, 7)) {
                buf.readUnsignedByte(); // function category
            }

            DateBuilder dateBuilder = new DateBuilder();

            if (BitUtil.check(mask, 8)) {
                dateBuilder.setDateReverse(
                        buf.readUnsignedByte(), buf.readUnsignedByte(), buf.readUnsignedByte());
            }

            if (BitUtil.check(mask, 9)) {
                position.setValid(buf.readUnsignedByte() == 1); // gps status
            }

            if (BitUtil.check(mask, 10)) {
                position.setLatitude(convertCoordinate(buf.readUnsignedInt()));
            }

            if (BitUtil.check(mask, 11)) {
                position.setLongitude(convertCoordinate(buf.readUnsignedInt()));
            }

            if (BitUtil.check(mask, 12)) {
                position.setSpeed(buf.readUnsignedShort() / 10.0);
            }

            if (BitUtil.check(mask, 13)) {
                position.setCourse(buf.readUnsignedShort() / 10.0);
            }

            if (BitUtil.check(mask, 14)) {
                dateBuilder.setTime(
                        buf.readUnsignedByte(), buf.readUnsignedByte(), buf.readUnsignedByte());
            }

            position.setTime(dateBuilder.getDate());

            if (BitUtil.check(mask, 15)) {
                position.setAltitude(buf.readMedium());
            }

            if (BitUtil.check(mask, 16)) {
                position.set(Event.KEY_SATELLITES, buf.readUnsignedByte());
            }

            if (BitUtil.check(mask, 17)) {
                buf.readUnsignedShort(); // battery percentage
            }

            if (BitUtil.check(mask, 20)) {
                position.set("trip", buf.readUnsignedInt());
            }

            if (BitUtil.check(mask, 21)) {
                position.set(Event.KEY_ODOMETER, buf.readUnsignedInt());
            }

            if (BitUtil.check(mask, 22)) {
                buf.skipBytes(6); // time of message generation
            }

            if (BitUtil.check(mask, 24)) {
                position.set(Event.KEY_POWER, buf.readUnsignedShort() / 1000.0);
            }

            if (BitUtil.check(mask, 25)) {
                buf.skipBytes(18); // gps overspeed
            }

            if (BitUtil.check(mask, 26)) {
                buf.skipBytes(54); // cell information
            }

            if (BitUtil.check(mask, 28)) {
                position.set(Event.KEY_INDEX, buf.readUnsignedShort());
            }
       return position;
        }

        return null;
    }

**Comment by pableras99** [comment]
Thanks for your information
