### ISSUE TITLE
BCE Device [Fixed]

### ISSUE THREAD

**Issue by afvalzak** [traccar/traccar#805]
I am using a BCE (http://www.bce.lt/light_specification) traccar.
This first sends a short String #BCE# and then sends the actual GPS information in a binary format. 

Can you please help me in decoding this info to the appropriate format?  
This is an example of the package coming in (HEX):
085a629c834601008600a59b41c760ed5c0bc0d39204201909de41f95a5742001c72e400000000008000ed030101010903570b003000000040110583040d001200001f0c1a03c605004d690b0000416766ed5c0bc0d39204201909de41f95a5742001b72e400000000008000ee030101010903570b003000000040110583040d001200001f0c1a03c605004d690b0000a0

To get the IMEI number for example:
08 5a 62 9c 83 46 01 00 (IMEI 0x146839c625a08 = 359006055062024)

But I'm unsure how to follow this logic using Traccar, can you help me out?

**Comment by tananaev** [comment]
I have added support for BCE protocol to Traccar. Here is a new server version to try:
https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

You also need to add following lines to the config file:
<pre>    &lt;entry key='bce.enable'&gt;true&lt;/entry&gt;
    &lt;entry key='bce.port'&gt;5080&lt;/entry&gt;</pre>

**Comment by bizkit1** [comment]
Hello. Does the bce protocol also support can bus params? I am trying a BCE BLUE with canbus connection, but i only see classic data coming, location, gms, odometer... If i create a sensor with "can_mileage" i can;t see it. Any help? Thanks!

**Comment by tananaev** [comment]
Traccar only supports basic data for BCE protocol at the moment.

**Comment by eric-lancelot** [comment]
Me am stack here

DEBUG:root:Calculated Checksum: 101
DEBUG:root:Received Checksum: 101
DEBUG:root:Payload (hex): 3bf74fd5fe8bc00080008640007bdb04426589d63e001c00680400000000c0883736991081020acc008c5c005095031a0080810080810080810000000a7650d5fe009f534352413bd751d5fe8bc00080008640007bdb04426589d63e001c00680400000000c0881436971081020acc00b25d005c95031a0080810080810080810000003bb753d5fe8bc00080008640007bdb04426589d63e001c00680400000000c0882536971081020acc00b25d005b95031a0080810080810080810000003b9755d5fe8bc00080008640007bdb04426589d63e001c00680400000000c0883736971081020acc00b25d005b95031a0080810080810080810000003b7757d5fe8bc00080008640007bdb04426589d63e001c00680400000000c0883736971081020acc00b25d005b95031a0080810080810080810000003b5759d5fe8bc00080008640007bdb04426589d63e001b00680400000000c0881c36991081020acc00b25d005b95031a0080810080810080810000000a265ad5fe6603534352410a765ad5fe0000534352413b675bd5fe8bc0008000864000a0db04425a84d63e001c00850400000000c08814369a1081020acc008c5c005095031a0080810080810080810000000a665ad5fe6705534352410a665ad5fe6414534352410a165bd5fe6445534352410a265bd5fe009e534352410a465bd5fe008f534352410a665bd5fe00a4534352410a765bd5fe0091534352413b475dd5fe8bc0008000864000a0db04425a84d63e001c00850400000000c0881436951081020acc008c5c005095031a008081008081008081000000
DEBUG:root:Mask1: 0b1111011100111011
DEBUG:root:Raw Latitude Bytes: 4fd5fe8b
DEBUG:root:Raw Latitude Value: -1946233521
DEBUG:root:Raw Longitude Bytes: c0008000
DEBUG:root:Raw Longitude Value: 8388800
INFO:root:Parsed data: [{'imei': 867556044663907, 'service_id': 165, 'confirmation_key': 197, 'data': {'latitude': -194.6233521, 'longitude': 0.83888}}]
DEBUG:root:Created confirmation packet: 636cdda10915030002001945ce
DEBUG:root:Sending confirmation: 636cdda10915030002001945ce

the cordinates are incorrect, i was expecting these : 0.41918566823, 33.2143516541
