### ISSUE TITLE
H2 Database to MySQL

### ISSUE THREAD

**Issue by andresmastertkd** [traccar/traccar#817]
Does somebody could tell me how to make Traccar generating MySQL databases instead of H2 database??. Of course I read the help on the Traccar web page (http://www.traccar.org/docs/mysql.jsp), but I need some extra support ;) , I mean, I would like to understand how to solve this: 

NOTE: Traccar will create tables for you, but you need to create database with selected name by yourself.

I would be really grateful, Im working in my final project in University, and I am too worried about it :/ 

Grettings to everyone from Ecuador :)

**Comment by andyguz08** [comment]
he intentado sin éxito hacer que trabaje con la base de datos mysql, 
luego de instalar mysql, crear el usuario en mysql y configurar el archivo traccar.cfg y le doy iniciar traccar y me sale este aviso:

traccar may have failed to start.

ayuda porfavor!!!

**Comment by tananaev** [comment]
@andyguz08, please create a new thread. Also, check log file (wrapper.log) for a detailed error message.
