### ISSUE TITLE
TK103B (Heacent) does not work

### ISSUE THREAD

**Issue by mstekker** [traccar/traccar#841]
Hi,

I am trying to use a TK103B with Traccar but it is not working. The device is sending data:

```
2014-08-25 20:26:33 DEBUG: [5002 <- x.x.x.x] - HEX: 23232c696d65693a3335393731303034323938303836332c413b
2014-08-25 20:27:55 DEBUG: [5002 <- x.x.x.x] - HEX: 23232c696d65693a3335393731303034323938303836332c413b
```

I cannot find any device id in the logging an tried several other TK103 protocols.

Does anyone has suggestions?

Thanks! Mart.

**Comment by caluca20** [comment]
Hi friend, I am Carlos from Ecuador, please help me the tacher tk103 send me only this information 78780d01035868880025909500098e970d0a   using the decoder show xxXh%, please could you help me	

**Comment by tananaev** [comment]
@caluca20, your device is using GT06 protocol. Correct port is 5023.

**Comment by caluca20** [comment]
Hi friend, thanks for you answer but I use the TK103 ( it has remote control), I was doing test with port 5001 and 5002 (traccar) and the problem is the same, please help how to do test.
I connected the TK to the server (in china) and it working normally. 
but with traccar is not working.

**Comment by caluca20** [comment]
Friend, thanks now the TK is working in the Port 5023.

**Comment by caluca20** [comment]
Hello friends, please , could you help me with the problem , I bought a tracker AL- 900E , which configures the port 5058 , but does not work , please help me .

**Comment by tananaev** [comment]
@caluca20, please don't spam with your question everywhere. Create a new thread and ask there.

**Comment by spider94** [comment]
my device keeps showing *HQ,imei_num,V1,112427,A,1536.72871,N,03232.43386,E,20.03,78,070318,FFFFFBFF#

anyone help plz

**Comment by tananaev** [comment]
@spider94, don't comment on old closed GitHub thread. Create a new forum thread if you want to ask something. Also, you would need to clearly explain what the issue is.
