### ISSUE TITLE
GT06 time correction

### ISSUE THREAD

**Issue by tejno** [traccar/traccar#881]
Hi, I have 2pcs of GT06 trackers. both are set for correct time zone ( command GMT. I always receiv correct time as SMS. Problem is that traccar decode time + 8 hours.
Info from user manual of GT06: 
"The default time zone of the device is GMT+8. Command format：GMT, E/W,hours,minutes# Time zone position：E stands for east，W stands for west. Time zone (hours) range is 0-12 Time zone (minutes) range is 15、30、45 Example 1：GMT,W,11# （the time zone is GMT-11） Example 2：GMT,E,5,30# （the time zone is GMT+5:30）"

 Is it possible to implement as setting in traccar.conf or web interface ( part of device setting ) time correction in scale +- XX hours ? Or fix this time shift, because i see that traccar expect GMT time and GT06 sending GMT+8.

many thanks

**Comment by shubhamalive** [comment]
Hello, i am using GT06 device with Traccar Server, i have set Time Zone By SMS is UTC +5:30, For SMS notifications time is correct, but while tracking online the time is +5:30 Hrs. i.e. If IST is 2:00 AM, on server device shows up 7:30 AM.
I have tried replacing tracker-server.jar provided above at https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0, that did not solve the issue.
Tried inserting <entry key='gt06.timezone'>19800</entry> (5:30 = 19800 Seconds), but when i add this line to my traccar.xml Device stops reporting on server.

**Comment by tananaev** [comment]
I don't see how setting the timezone results in device not reporting to the server. It must be some coincidence or you just missing something. Also, if you still have some issue, I would recommend to create a new thread.

**Comment by shubhamalive** [comment]
I even tried to change mt device timezone to GMT,E,0,0# it freezes the update on server again.

**Comment by tananaev** [comment]
I guess the problem is that your last report is from future, and server ignores any new reports with correct time because they are considered old comparing to the last update.

**Comment by shubhamalive** [comment]
So should i wait atleast 5:30 Hrs to see if i get new update on server or not after adding gt06.timezone key ?

**Comment by tananaev** [comment]
Yes, you can try to wait. Another option is to re-create device.

**Comment by hatami98** [comment]
Hi @tananaev,

I have the same problem with my GT02 devices. Is there any gt02.timezone key ?

Thanks.

**Comment by tananaev** [comment]
There is no such flag for GT02.

**Comment by Kyouga** [comment]
Sorry to revive old issue, I just want to ask whether the gt06.timezone config will make the log report the corrected time or still the raw time from device?

**Comment by tananaev** [comment]
It will affect logs as well, but please don't comment on old threads in future.

**Comment by Kyouga** [comment]
Thank you.
