### ISSUE TITLE
Wrapper problems

### ISSUE THREAD

**Issue by hackerunet** [traccar/traccar#89]
This is what I get using the last 32 bits stable release on a CentOS 64 bits environment:
```
[root@b196 traccar]# service traccar console
Running traccar...
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Community Edition 32-bit 3.5.16
wrapper  |   Copyright (C) 1999-2012 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |
wrapper  | Wrapper Process has not received any CPU time for 12 seconds.  Extending timeouts.
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
wrapper  | Wrapper Process has not received any CPU time for 49 seconds.  Extending timeouts.
```
When I try to stop the program I get this status:
```
[root@b196 traccar]# service traccar status
traccar is running: PID:5824, Wrapper:STOPPING, Java:Unknown
[root@b196 traccar]#
```

**Comment by manoj425** [comment]
hi i too facing same issue 

INFO   | wrapper  | 2017/03/27 11:40:55 | Wrapper Process has not received any CPU time for 50 seconds.  Extending timeouts.
INFO   | wrapper  | 2017/03/27 11:41:34 | Wrapper Process has not received any CPU time for 39 seconds.  Extending timeouts.
INFO   | wrapper  | 2017/03/27 11:42:07 | Wrapper Process has not received any CPU time for 32 seconds.  Extending timeouts.
INFO   | wrapper  | 2017/03/27 11:43:02 | Wrapper Process has not received any CPU time for 54 seconds.  Extending timeouts.
INFO   | wrapper  | 2017/03/27 11:43:35 | Wrapper Process has not received any CPU time for 33 seconds.  Extending timeouts.
INFO   | wrapper  | 2017/03/27 11:44:35 | Wrapper Process has not received any CPU time for 60 seconds.  Extending timeouts.
INFO   | wrapper  | 2017/03/27 11:45:35 | Wrapper Process has not received any CPU time for 60 seconds.  Extending timeouts.
INFO   | wrapper  | 2017/03/27 11:46:35 | Wrapper Process has not received any CPU time for 60 seconds.  Extending timeouts.
INFO   | wrapper  | 2017/03/27 11:47:08 | Wrapper Process has not received any CPU time for 32 seconds.  Extending timeouts.
INFO   | jvm 1    | 2017/03/27 11:52:06 | 2017-03-27 11:52:06,550 WARN [0-BAM::

**Comment by tananaev** [comment]
@manoj425, have you looked at the date on the thread? Your issue is definitely different. Please don't comment on old closed thread. If you have some problem or question, create a new issue.
