### ISSUE TITLE
http://demo.traccar.org/

### ISSUE THREAD

**Issue by toudidel** [traccar/traccar#896]
How can I login or register new account in http://demo.traccar.org/?

Each time I input a username I receive that the username has already taken.

**Comment by olegkarmazin** [comment]
The demo does not work anymore. Cannot register, everytime: Username is already taken. Help me please!

**Comment by tananaev** [comment]
Please try again now.

**Comment by olegkarmazin** [comment]
Hi,
Anton, I tried, it does not work, the problem remains the same.

2015-03-12 21:37 GMT+02:00 Anton Tananaev <notifications@github.com>:

**Comment by olegkarmazin** [comment]
Hi,
Anton, I tried, it does not work, the problem remains the same.
