### ISSUE TITLE
Error after removing and adding again a device

### ISSUE THREAD

**Issue by connectnet** [traccar/traccar#933]
After removing and adding again a device I found this error in the traccar-server.log file:
WARN: Cannot add or update a child row: a foreign key const
raint fails (`gps`.`positions`, CONSTRAINT `FK65C08C6ADB0C3B8A` FOREIGN KEY (`de
vice_id`) REFERENCES `devices` (`id`)) - com.mysql.jdbc.exceptions.jdbc4.MySQLIn
tegrityConstraintViolationException (NativeConstructorAccessorImpl.java:-2)

**Comment by connectnet** [comment]
Im very sorry but the bug still exist. After more than 20 minutes Traccar Server log says:
WARN: Cannot add or update a child row: a foreign key constraint fails (`gps`.`positions`, CONSTRAINT `positions_fkey_device_id` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`)) - com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException (null:-1)

**Comment by sodasonic** [comment]
This problem  i add filed  device_enabled bit (1) to devices table  and  edit query use device_enabled=true only

**Comment by tananaev** [comment]
@sodasonic, please don't comment on closed thread. Create a new one and include all the information that you have.
