### ISSUE TITLE
Support for GT02 device

### ISSUE THREAD

**Issue by mwaltham** [traccar/traccar#96]
Hi,

Does traccar support the Cothinking/Concox GT02 GPS device?
This seems to be a very common chinese made device.

**Comment by gent2** [comment]
**`tananaev`** could You help with this JAR file ?

**Comment by tananaev** [comment]
@gent2, you should probably look at the dates in this thread. Support for GT02 protocol has been available in Traccar for almost 5 years now. Just use official release. You don't need this JAR file.

**Comment by gent2** [comment]
@tananaev I'm trying to set up OpenGTS, but this one GT02 isnt supported
Traccar is probably comercial server.

**Comment by tananaev** [comment]
Traccar software is free and open source. If you want to discuss it further, please create a new thread instead of commenting on ancient closed thread.

**Comment by gent2** [comment]
thanks.
