### ISSUE TITLE
Traccar Monitoring Integrated

### ISSUE THREAD

**Issue by bernamaxim** [traccar/traccar#985]
Hi Tananaev,

Can u help me to integrate Traccar with monitoring service like Loggly, etc.
So, if there are problem with Traccar, we can only analyze, should not login to terminal console, view log, and etc.

Thanks.

**Comment by Abyss777** [comment]
Some basic monitoring parameters about JVM and wrapper can be accessed after enabling JMX
https://wrapper.tanukisoftware.com/doc/english/jmx.html#jconsole

May be we should add some counters to traccar itself, like devices count, positions per second and others. But I think it is very minor task at the moment.

**Comment by tananaev** [comment]
Agree, I think this is lower priority than some other features.

**Comment by tananaev** [comment]
We already have some statistics. Also, Loggly supports reading log file directly.
